firebase/firebase-ios-sdk

FirebaseVertexAI/Sources/ModelContent.swift
- Added more detail to the `fileData` enum case to highlight that this is for Cloud Storage *for Firebase* files.
- These files must be in a Cloud Storage **for Firebase** bucket. Standard Google Cloud Storage buckets will not work.
In Xcode, this now looks like:
#no-changelog
=> [Vertex AI] Update documentation for file data

FirebaseVertexAI/Sample/VertexAISample.xcodeproj/project.pbxproj, FirebaseVertexAI/Sample/VertexAISample/VertexAISampleApp.swift
- Added the FirebaseAppCheck, FirebaseAuth and FirebaseStorage frameworks to the sample app to make it easier for devs to try out related features.
- Added a placeholder `AppCheckProviderFactory` that returns a simple `AppCheckNotConfigured` error since `AppCheckDebugProviderFactory` and `DeviceCheckProviderFactory` are very noisy with `-FIRDebugEnabled` (if App Check is not configured on the Firebase app -- the more common situation for sample users).
- Switched from configuring Firebase in `init()` to a `UIApplicationDelegate` to silence a `[GoogleUtilities/AppDelegateSwizzler][I-SWZ001014] App Delegate does not conform to UIApplicationDelegate protocol.` warning with `-FIRDebugEnabled`.
#no-changelog
=> [Vertex AI] Add AppCheck, Auth and Storage frameworks to sample

Firestore/core/test/unit/FSTGoogleTestTests.mm
=> [Firestore] Cleanup compilation guards for building on older SDKs

FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/Logging.swift, FirebaseVertexAI/Sources/Safety.swift
- Changed (or added) logging tags from `[GoogleGenerativeAI]` to `[FirebaseVertexAI]`.
- Switched to `-FIRDebugEnabled` as the launch argument to enable additional logging.
- `-GoogleGenerativeAIDebugLogEnabled` is still accepted with a warning message.
- Updated additional logging instructions with new tag and argument.
- No longer prints `"To enable additional logging, add -GoogleGenerativeAIDebugLogEnabled as a launch argument in Xcode."` when additional logging is already enabled.
#no-changelog
=> [Vertex AI] Update logging details from Google AI SDK

FirebaseInAppMessaging/Sources/Analytics/FIRIAMClearcutLogStorage.m, FirebaseInAppMessaging/Sources/Analytics/FIRIAMClearcutUploader.m, FirebaseInAppMessaging/Sources/DefaultUI/Banner/FIRIAMBannerViewController.m, FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMBaseRenderingViewController.m, FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMRenderingWindowHelper.m, FirebaseInAppMessaging/Sources/DefaultUI/ImageOnly/FIRIAMImageOnlyViewController.m, FirebaseInAppMessaging/Sources/DefaultUI/Modal/FIRIAMModalViewController.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMActivityLogger.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayCheckOnAppForegroundFlow.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMFetchOnAppForegroundFlow.m
=> [FIAM] Cleanup compilation guards for building on older SDKs

FirebaseVertexAI/Sample/README.md
Updated the instructions for running the sample app. These are linked from https://github.com/firebase/quickstart-ios/blob/main/vertexai/README.md.
Note: the `git checkout release-10.26` should be removed after merging into `main`.
#no-changelog
=> [Vertex AI] Update sample instructions for public preview

FirebaseVertexAI/Sample/ChatSample/ViewModels/ConversationViewModel.swift, FirebaseVertexAI/Sample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift, FirebaseVertexAI/Sample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift, FirebaseVertexAI/Sample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift
Switched from `gemini-1.0-pro` / `gemini-1.0-pro-vision` to `gemini-1.5-pro-preview-0409` in the Vertex AI samples.
#no-changelog
=> [Vertex AI] Switch to `gemini-1.5-pro-preview-0409` in sample app

FirebaseVertexAI/Sources/VertexAI.swift
Link to the exact section on a bad location.
Maybe too fragile?
=> [vertex-ai] more accurate location error message

FirebaseVertexAI/Sample/README.md
Updated the Vertex AI sample app's instructions now that it has been merged into `main`.
#no-changelog
=> [Vertex AI] Update sample README for `main`

FirebaseVertexAI-Docs.not_podspec
Renamed the `FirebaseVertexAI-Docs.podspec` used for documentation generation to `FirebaseVertexAI-Docs.not_podspec`. This avoids including it in the `update_SpecsTesting_repo` job.
#no-changelog
=> [Vertex AI] Rename `FirebaseVertexAI-Docs.podspec` to avoid CI

FirebaseVertexAI-Docs.not_podspec
- Updated various versions in the podspec used for generating documentation for the Vertex AI for Firebase Preview.
- Updated the `:tag` to `'CocoaPods-' + s.version.to_s`.
- Removed extraneous `source_files` and C flags not needed in a Swift-only pod.
- Updated the `name` to `FirebaseVertexAI-Docs` for linting.
Notes:
- `pod spec lint` passes by switching to `CocoaPods-10.27.0.nightly` temporarily (`CocoaPods-10.27.0` should work after we move the tags to the tip of `main`).
- `pod gen` still works after temporarily renaming from `.not_podspec` to `.podspec`.
#no-changelog
=> Update versions in `FirebaseVertexAI-Docs.not_podspec`

FirebaseVertexAI/Sample/ChatSample/ViewModels/ConversationViewModel.swift, FirebaseVertexAI/Sample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift, FirebaseVertexAI/Sample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift, FirebaseVertexAI/Sample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/VertexAI.swift
Updated the Vertex AI samples and docs to use the `gemini-1.5-flash-preview-0514` model.
Note: See [Gemini 1.5 Pro model names](https://firebase.google.com/docs/vertex-ai/gemini-models#model-names-gemini-1.5-pro) for the `gemini-1.5-pro-preview-0409` (previous model) discontinuation date.
#no-changelog
=> [Vertex AI] Update samples/docs to use `gemini-1.5-flash-preview-0514`

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.m, Crashlytics/UnitTests/FIRCLSRolloutsPersistenceManagerTests.m
https://github.com/firebase/firebase-ios-sdk/issues/12913 reports hangs writing to rollouts.
I was able to reproduce this in a test by putting a long running operation on the `FIRCLSGetLoggingQueue()`. Root cause is dispatching synchronously for writes to rollouts.
Added a test case to ensure `updateRolloutsStateToPersistenceWithRollouts` returns to the caller without blocking on the dispatch queue.
=> Crashlytics dispatch Rollouts writes async to prevent hangs

FirebaseAuth/Sources/Swift/Utilities/AuthURLPresenter.swift
While doing exploratory testing investigating the GitHub provider workflow for #11759, I discovered that dismissing the sign in window didn't properly reset to try again and then once fixing that, the dismiss didn't happen in the main thread.
Fixed by implementing the missed SFSafariViewControllerDelegate delegate method - `safariViewControllerDidFinish` and fixing the async queue for the `dismiss` method.
=> [auth-swift] Fix two flow porting errors in AuthURLPresenter.swift

.github/workflows/dynamiclinks.yml, FirebaseDynamicLinks/CHANGELOG.md, FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLinks.h, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift, scripts/create_spec_repo/Sources/SpecRepoBuilder/main.swift, scripts/health_metrics/pod_test_code_coverage_report.sh
=> Deprecation warning for FDL

FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/SystemService/AuthNotificationManager.swift, FirebaseAuth/Sources/Swift/User/User.swift, FirebaseAuth/Sources/Swift/User/UserInfoImpl.swift, FirebaseAuth/Sources/Swift/Utilities/AuthUIDelegate.swift, Package.swift
Now only application:didReceiveRemoteNotification:fetchCompletionHandler: is supported unconditionally along with https://github.com/google/GoogleUtilities/pull/162.
This is part of fixing #11693.  FirebaseMessaging still needs review and updates.  GoogleUtilities needs to be updated to 8.0.0 for both CocoaPods and SPM.
This PR also fixes a regression in Phone Auth. (It depends on a nil uid at creation.)
=> [auth-swift] Modernize Phone Auth Notification Implementation

.github/workflows/vertexai.yml, FirebaseVertexAI/Sources/Errors.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/GenerateContentResponses/unary-failure-firebaseml-api-not-enabled.json, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
If a developer tries to use the Vertex AI SDK without going through the Firebase Console setup flow then they will receive an error saying:
> Firebase ML API has not been used in project 1234567890 before or it is disabled...
Since it may not be clear that the `firebaseml.googleapis.com` API is needed for Vertex AI, added a more detailed log message with direct links to the Firebase Console page:
> The Vertex AI for Firebase SDK requires the Firebase ML API `firebaseml.googleapis.com` to be enabled for your project. Get started in the Firebase Console (https://console.firebase.google.com/project/my-project-id/genai/vertex) or verify that the API is enabled in the Google Cloud Console (https://console.developers.google.com/apis/api/firebaseml.googleapis.com/overview?project=my-project-id). …
=> [Vertex AI] Add error message for Firebase ML API not enabled

FirebaseVertexAI/Sources/GenerativeAIService.swift
Updated logging to print response payloads even when `-FIRDebugEnabled` is _not_ enabled.
<details>
<summary>Example Error Response Log</summary>
If the Vertex AI API (aiplatform.googleapis.com) is not enabled:
```
[FirebaseVertexAI] Response payload: {
"error": {
"code": 403,
"message": "Vertex AI API has not been used in project my-project-id before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/aiplatform.googleapis.com/overview?project=my-project-id then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
"status": "PERMISSION_DENIED",
"details": [
{
"@type": "type.googleapis.com/google.rpc.Help",
"links": [
{
"description": "Google developers console API activation",
"url": …
```
=> [Vertex AI] Log server error responses without `-FIRDebugEnabled`

.github/workflows/auth.yml
Fix Sample build for pre-released Analytics SPM dependency like https://github.com/firebase/firebase-ios-sdk/actions/runs/9181564314/job/25248577833
=> [auth-swift] Fix auth sample CI for latest analytics

FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m, FirebaseAuth/Tests/Unit/FIRAuthTests.m, FirebaseDatabase/Tests/Integration/FIRDatabaseTests.m, FirebaseDynamicLinks/Sources/FIRDLDefaultRetrievalProcessV2.m, FirebaseInAppMessaging/Sources/Analytics/FIRIAMClearcutLogStorage.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMActivityLogger.m, FirebaseMLModelDownloader/Sources/FileDownloader.swift, FirebaseMLModelDownloader/Sources/ModelInfoRetriever.swift, FirebaseSharedSwift/Sources/third_party/FirebaseDataEncoder/FirebaseDataEncoder.swift, FirebaseSharedSwift/Tests/third_party/DataEncoderTests.swift, FirebaseStorage/Sources/StorageError.swift
* Removed redundant availability checks and attributes to match the deployment targets specified in `Package.swift` and `Firebase.podspec`
* Removed unused fallbacks for earlier versions
* Removed `_safariVC` from `FIRAppDistributionUIService`’s implementation, but retained the `SFSafariViewControllerDelegate` conformance as part of the interface
* Refactored `FIRDLDefaultRetrievalProcessV2`’s `retrievePasteboardContents` to return optional strings
=> Removed Unused Availability Checks

FirebasePerformance/CHANGELOG.md, FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m
Fix #12983 
(Similar fix to #11825 and #11905)
=> Fix fireperf exception

FirebasePerformance/Sources/Instrumentation/FPRNetworkTrace.m, FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLConnectionInstrument.m
After moving to `GoogleUtilities` 8.0 we need to use a bridged cast when passing an `NSString *const` as key in `GULObjectSwizzler`'s `- setAssociatedObject:key:value:networkTrace:association:` method. See https://github.com/google/GoogleUtilities/pull/141 for the details.
#no-changelog
=> [Firebase 11] Add bridged casts in FirebasePerformance

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.h, Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.m, Crashlytics/Crashlytics/FIRCrashlytics.m, Crashlytics/UnitTests/FIRCLSRolloutsPersistenceManagerTests.m
Related to #12913 
I haven't be able to reproduce the problem naturally but with some hack I am able to get the exactly same stack trace as the user showed. It seems like when dispatch async the default logging queue is deallocated already. 
The bit wired thing for this particular issue is that if we can log the crash, this means the logging queue and exception queue has been initialized previously under [here](https://github.com/firebase/firebase-ios-sdk/blob/main/Crashlytics/Crashlytics/Components/FIRCLSContext.m#L236). So for a more safe approach, creating a queue for rollouts logging and double check for the the existence.
=> Make sure rollouts logging queue is not nil

FirebaseMessaging/Sources/FIRMessaging.m, FirebaseMessaging/Sources/FIRMessagingRemoteNotificationsProxy.m, FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.m, FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m
In conjunction with Auth (#13003) and GoogleUtilities v9, drop support for  `(void)application:(UIApplication *)application     didReceiveRemoteNotification:(NSDictionary *)userInfo ` in favor of  (void)application:(UIApplication *)application     didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:`
The PR also fixes decoder warnings that show up running the unit tests.
Fix #11693
=> [v11] Drop support for deprecated notification methods

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/FIRConfigValue.m, FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h, FirebaseRemoteConfig/Swift/FirebaseRemoteConfigValueDecoderHelper.swift, FirebaseRemoteConfigSwift/Tests/SwiftAPI/APITests.swift
Fix #10870
CI failures are pending v11 fixes for quickstarts and Swift library consolidation
=> [v11] RC stringValue is now nonull

Package.swift
- Increased to `swift-tools-version:5.9` since it is available in Xcode 15+.
- Removed the `firebaseVisionOS` extension on `Platform` (`visionOS` is available in Xcode 15).
#no-changelog
=> [Firebase 11] Update to `swift-tools-version:5.9` in Package.swift

FirebaseMessaging/Sources/FIRMessagingPubSub.m
Since it's now just a one-line implementation with recent platform versions
Fix #12922
#no-changelog
=> [v11] Stop using GULSecureCoding

FirebaseCore/CHANGELOG.md, FirebaseDatabase/CHANGELOG.md, FirebaseInAppMessaging/CHANGELOG.md, FirebaseRemoteConfig/CHANGELOG.md, Firestore/CHANGELOG.md
Removal PRs:
- #13085
- #13076
- #13057
- #13056
- #13052
Fix https://github.com/firebase/firebase-ios-sdk/issues/12092
=> [v11] Add changelog entries for Swift extension removal

CoreOnly/Tests/FirebasePodTest/Podfile, FirebaseAnalytics.podspec, FirebaseAppCheck.podspec, FirebaseAuth.podspec, FirebaseCrashlytics.podspec, FirebaseFirestoreInternal.podspec, FirebaseFunctions.podspec, FirebaseInAppMessaging.podspec, FirebaseInstallations.podspec, FirebaseMessaging.podspec, FirebasePerformance.podspec, FirebaseSessions.podspec, FirebaseStorage.podspec, GoogleAppMeasurement.podspec, IntegrationTesting/ClientApp/Podfile, Package.swift
- Update to breaking change podspec versions of nanopb and GDT
- Tighten version ranges for other deps
- Incorporate AppCheck fixes from https://github.com/google/app-check/pull/60
Part of https://github.com/firebase/firebase-ios-sdk/issues/10187
=> [v11] Dependency version updates

FirebasePerformance.podspec, FirebasePerformance/CHANGELOG.md, FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.h, FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m, FirebasePerformance/Sources/FPRNanoPbUtils.m, Package.swift
SystemConfiguration framework APIs are getting deprecated. This PR replaces the usage of SystemConfiguration with Network Monitoring provided by Apple - this API is available from 12.0 onwards.
This fixes https://github.com/firebase/firebase-ios-sdk/issues/13079.
=> Replace SystemConfiguration with a more recent Apple provided network monitoring API.

.github/workflows/vertexai.yml, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift, Package.swift, scripts/build.sh
- Skip Vertex AI integration tests when the `VertexAIRunIntegrationTests` environment variable is not set.
- Switched `spm-integration` to run on iOS.
- Cleaned up dependencies in the `FirebaseVertexAIIntegration` test target.
#no-changelog
=> [Vertex AI] Add environment variable to control integration tests

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sample/ChatSample/ViewModels/ConversationViewModel.swift, FirebaseVertexAI/Sample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift, FirebaseVertexAI/Sample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift, FirebaseVertexAI/Sample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift, FirebaseVertexAI/Sources/VertexAI.swift
Updated the Vertex AI samples and docs to use the auto-updating `gemini-1.5-flash` model.
Note: See [Gemini 1.5 Flash model names](https://firebase.google.com/docs/vertex-ai/gemini-models#model-names-gemini-1.5-flash) for the `gemini-1.5-flash-preview-0514` (previous model) discontinuation date.
=> [Vertex AI] Update samples/docs to use `gemini-1.5-flash`

.github/workflows/vertexai.yml, FirebaseVertexAI/Sources/Chat.swift, FirebaseVertexAI/Sources/Constants.swift, FirebaseVertexAI/Sources/CountTokensRequest.swift, FirebaseVertexAI/Sources/GenerateContentError.swift, FirebaseVertexAI/Sources/GenerateContentRequest.swift, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Sources/GenerationConfig.swift, FirebaseVertexAI/Sources/GenerativeAIRequest.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/Logging.swift, FirebaseVertexAI/Sources/ModelContent.swift, FirebaseVertexAI/Sources/PartsRepresentable+Image.swift, FirebaseVertexAI/Sources/PartsRepresentable.swift, FirebaseVertexAI/Sources/Safety.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Sources/VertexAIComponent.swift, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/Fakes/AuthInteropFake.swift, FirebaseVertexAI/Tests/Unit/GenerationConfigTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift, FirebaseVertexAI/Tests/Unit/MockURLProtocol.swift, FirebaseVertexAI/Tests/Unit/ModelContentTests.swift, FirebaseVertexAI/Tests/Unit/PartsRepresentableTests.swift, FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
Added support for compiling the Vertex AI SDK on tvOS. Note that the following still applies: https://github.com/firebase/firebase-ios-sdk/blob/901844a9213e241d06315f92d6524d8c695e0dd7/FirebaseVertexAI/Sources/Constants.swift#L17-L19
#no-changelog
=> [Vertex AI] Add support for compiling on tvOS

.github/workflows/vertexai.yml, FirebaseVertexAI/Tests/Unit/PartsRepresentableTests.swift
Added CI for testing the Vertex AI SDK on visionOS. Note that the following still applies: https://github.com/firebase/firebase-ios-sdk/blob/901844a9213e241d06315f92d6524d8c695e0dd7/FirebaseVertexAI/Sources/Constants.swift#L17-L19
#no-changelog
=> [Vertex AI] Add CI for visionOS

Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.m
Add early returns for errors which cannot proceed further writes
#no-changelog
=> Early return for rollouts write errors 

FirebaseAppCheck.podspec, FirebaseAppCheck/Interop/Public/FirebaseAppCheckInterop/FIRAppCheckInterop.h, FirebaseAppCheck/Interop/Public/FirebaseAppCheckInterop/FIRAppCheckProtocol.h, FirebaseAppCheck/Interop/Public/FirebaseAppCheckInterop/FIRAppCheckTokenProtocol.h, FirebaseAppCheck/Interop/Public/FirebaseAppCheckInterop/FirebaseAppCheckInterop.h, FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheck.h, FirebaseAppCheck/Tests/Interop/ObjC/FIRAppCheckInteropAPITests.m, FirebaseAppCheck/Tests/Interop/ObjC/FIRAppCheckProtocolAPITests.m, FirebaseAppCheck/Tests/Interop/Swift/AppCheckInteropAPITests.swift, FirebaseAppCheck/Tests/Interop/Swift/AppCheckProtocolAPITests.swift, FirebaseAppCheckInterop.podspec
Previously a user of `FIRAppCheckProtocol` would need access to the `FIRAppCheckToken` class (in the main SDK, not in the Interop SDK) to get the token/error value.
=> Add `FIRAppCheckTokenProtocol` for use in `FIRAppCheckProtocol`

FirebaseAppCheck/Interop/Public/FirebaseAppCheckInterop/FIRAppCheckTokenProtocol.h
Added `#import <Foundation/Foundation.h>` to `FIRAppCheckTokenProtocol.h` to fix the bazel build when copying into the internal codebase.
#no-changelog
=> Import `Foundation` in `FIRAppCheckTokenProtocol`

FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Models/AuthMenu.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Utility/DataSourceProvider/DataSourceProvider.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Utility/Extensions.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Utility/TransitionAnimator/Animator.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AccountLinkingViewController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AuthViewController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/LoginController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/OtherAuthMethodControllers/OtherAuthViewController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/UserViewController.swift
Address easy Swift 6 warnings building Auth sample.
Several `@Sendable` warnings remain and a few more are fixed by `@retroactive` but that fails to build in Swift 5.
=> Address some Swift 6 warnings in Auth sample

FirebaseStorage/CHANGELOG.md, FirebaseStorage/Sources/AsyncAwait.swift, FirebaseStorage/Sources/Internal/StorageGetDownloadURLTask.swift, FirebaseStorage/Sources/Internal/StorageTokenAuthorizer.swift, FirebaseStorage/Sources/Result.swift, FirebaseStorage/Sources/Storage.swift, FirebaseStorage/Sources/StorageDownloadTask.swift, FirebaseStorage/Sources/StorageError.swift, FirebaseStorage/Sources/StorageReference.swift, FirebaseStorage/Sources/StorageTaskSnapshot.swift, FirebaseStorage/Sources/StorageUploadTask.swift, FirebaseStorage/Tests/Integration/StorageAsyncAwait.swift, FirebaseStorage/Tests/Integration/StorageIntegration.swift, FirebaseStorage/Tests/Unit/StorageAPITests.swift, FirebaseStorage/Tests/Unit/StorageGetMetadataTests.swift, FirebaseStorage/Tests/Unit/StorageReferenceTests.swift, FirebaseStorage/Tests/Unit/StorageTests.swift
Fix #13071 Fix #10889
Storage Error handling was a mix of Swift error and NSError generation. With this PR, all errors are created as Swift errors and thanks to [CustomNSError](https://developer.apple.com/documentation/foundation/customnserror), NSError's are generated as needed from the Swift error enum.
- All Objective C/NSError handling should remain the same from a public API perspective
- Some of the Swift error enums have additional fields to have enough information to support the corresponding NSError and to provide useful information to Swift error enum users. This is most commonly information about underlying server errors.
- Additional error codes are added to provide NSError code mapping for errors that were introduced only in Swift after the Swift implementation transition. …
=> [v11] Storage Error Handling Consistency

FirebaseMessaging/CHANGELOG.md, FirebaseMessaging/Sources/Token/FIRMessagingBackupExcludedPlist.h, FirebaseMessaging/Sources/Token/FIRMessagingBackupExcludedPlist.m, FirebaseMessaging/Sources/Token/FIRMessagingCheckinStore.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingBackupExcludedPlistTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingCheckinStoreTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenStoreTest.m
Fix #13134 
Rename `initWithFileName` internal method. No references should remain in Firebase.
There is another unused definition in GoogleUtilities that will be removed in GoogleUtilities 8.0.0.
=> [Messaging] Rename initWithFileName internal method

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/AuthProvider/AuthProviderStrings.swift, FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift, FirebaseAuth/Sources/Swift/Backend/RPC/RevokeTokenRequest.swift, FirebaseAuth/Tests/Unit/AuthProviderIDTests.swift, FirebaseAuth/Tests/Unit/AuthTests.swift, FirebaseAuth/Tests/Unit/OAuthProviderTests.swift, FirebaseAuth/Tests/Unit/ObjCAPITests.m, FirebaseAuth/Tests/Unit/RevokeTokenTests.swift, FirebaseAuth/Tests/Unit/SwiftAPI.swift
Better enum name thanks to @ncooke3 . Fix #9236
=> [v11] Rename AuthProviderString to AuthProviderID

FirebaseAuth/Sources/Swift/Backend/IdentityToolkitRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/GetProjectConfigRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/GetRecaptchaConfigRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SecureTokenRequest.swift, FirebaseAuth/Tests/Unit/AuthBackendRPCImplentationTests.swift, FirebaseAuth/Tests/Unit/GetRecaptchaConfigTests.swift
Processing the GetRecaptchaConfigRequest RPC request was failing because it was getting a `true` from the `containsPostBody` var because it defined a `containsPostBody` func instead of overriding the var.
=> [v11] Fix recaptcha bug - mixing vars and funcs

.github/workflows/symbolcollision.yml
Fix #13150 - originally tested fix in #13151. 
Looks like one of the binary deps is built with a newish Xcode 15 version.
=> Fix symbol collision nightly

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.m, Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c, Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c, Crashlytics/Crashlytics/Handlers/FIRCLSSignal.h
Reverting #12881 due to https://github.com/firebase/firebase-ios-sdk/issues/13117
We will revisting the change and look into a different way for implementation with more control. Now trying to unblock user as quick as possible.
=> Revert "Add SIGTERM support (#12881)"

FirebaseCore/Extension/FIRLogger.h, FirebaseMLModelDownloader.podspec, FirebaseMLModelDownloader/Sources/DeviceLogger.swift, FirebaseMLModelDownloader/Tests/Unit/ModelDownloaderUnitTests.swift, Package.swift
Migrate from `GULLoggerWrapper` from `GoogleUtilities` to `FirebaseLogger` from `FirebaseCoreExtension`. After this change, `FirebaseCoreExtension` is the only target in the repo depending directly on `GULLogger`.
Note: `FirebaseLogger` still uses the ASL-based implementation of `GULLogger`. Migration to OSLog won't happen until Firebase 11.
#no-changelog
=> [MLModelDownloader] Use `FirebaseLogger` instead of `GULLoggerWrapper`

FirebaseMessaging/CHANGELOG.md, FirebaseMessaging/Sources/FIRMessagingUtilities.m
On visionOS we should use the APS Entitlement Key [`aps-environment`](https://developer.apple.com/documentation/bundleresources/entitlements/aps-environment), not [`com.apple.developer.aps-environment`](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_aps-environment) (macOS only -- excluding Catalyst). This should fix #13173.
Note: Previously `TARGET_OS_IOS` was true on visionOS but not as of [Xcode 15.2](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_2-release-notes#Resolved-Issues).
=> [Messaging] Fix APS Environment entitlement key on visionOS

scripts/rotate_secrets.sh
nits: Add double quotes to prevent globbing and word splitting in `rotate_secrets.sh` ([SC2086](https://www.shellcheck.net/wiki/SC2086)).
#no-changelog
=> [Infra] Add double quotes around vars in rotate_secrets.sh

FirebaseAppCheckInterop.podspec
These were accidentally reverted when resolving the merge conflicts in https://github.com/firebase/firebase-ios-sdk/pull/13169.
#no-changelog
=> Fix deployment targets in FirebaseAppCheckInterop.podspec

FirebaseMessaging/CHANGELOG.md
10.29.0 is not released yet so grouping release notes under "Unreleased" header
#no-changelog
=> [Messaging] Update CHANGELOG.md

FirebaseStorage/Sources/StorageMetadata.swift
The only change for building with Swift 6 that doesn't look to be part of a big lift to Sendable.
#no-changelog
=> Storage: Fix a var that should be a let

FirebaseMessaging/Sources/FIRMessaging.m, FirebaseMessaging/Sources/FIRMessagingContextManagerService.m, FirebaseMessaging/Sources/FIRMessagingExtensionHelper.m, FirebaseMessaging/Sources/FIRMessagingRemoteNotificationsProxy.m, FirebaseMessaging/Sources/FIRMessagingUtilities.m, FirebaseMessaging/Sources/Token/FIRMessagingAuthKeychain.m, FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.m, FirebaseMessaging/Tests/IntegrationTests/FIRMessagingPubSubTest.swift, FirebaseMessaging/Tests/IntegrationTests/FIRMessagingTokenRefreshTests.swift, FirebaseMessaging/Tests/UnitTests/FIRMessagingAnalyticsTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingAuthKeychainTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingBackupExcludedPlistTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingCheckinStoreTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingContextManagerServiceTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingExtensionHelperTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingUtilitiesTest.m
Updated `TARGET_OS_*` in Messaging now that Xcode 15.2 is required and `TARGET_OS_IOS` is no longer `1` on visionOS.
#no-changelog
=> [Messaging] Update `TARGET_OS_*` conditionals

FirebaseCore/Extension/FIRLibrary.h, FirebaseCore/Sources/FIRApp.m, FirebaseInAppMessaging/Sources/FIRInAppMessaging.m
=> [v11] Remove `configureWithApp:` API in FIRLibrary protocol

FirebaseMessaging/CHANGELOG.md
Note: This is the only changelog with `Unreleased` entries for the upcoming release.
=> [Messaging] Update CHANGELOG for 10.29 release

.github/workflows/vertexai.yml, FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/Chat.swift, FirebaseVertexAI/Sources/CountTokensRequest.swift, FirebaseVertexAI/Sources/GenerateContentError.swift, FirebaseVertexAI/Sources/GenerateContentRequest.swift, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Sources/GenerationConfig.swift, FirebaseVertexAI/Sources/GenerativeAIRequest.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/Logging.swift, FirebaseVertexAI/Sources/ModelContent.swift, FirebaseVertexAI/Sources/PartsRepresentable+Image.swift, FirebaseVertexAI/Sources/PartsRepresentable.swift, FirebaseVertexAI/Sources/Safety.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Sources/VertexAIComponent.swift, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/Fakes/AuthInteropFake.swift, FirebaseVertexAI/Tests/Unit/GenerationConfigTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift, FirebaseVertexAI/Tests/Unit/MockURLProtocol.swift, FirebaseVertexAI/Tests/Unit/ModelContentTests.swift, FirebaseVertexAI/Tests/Unit/PartsRepresentableTests.swift, FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
Added support for compiling the Vertex AI SDK on watchOS. Note that the following still applies: https://github.com/firebase/firebase-ios-sdk/blob/901844a9213e241d06315f92d6524d8c695e0dd7/FirebaseVertexAI/Sources/Constants.swift#L17-L19
=> [Vertex AI] Add support for compiling on watchOS

FirebaseDataConnect/README.md
Also adjust the order of process to have developers setup FDC before a Cloud SQL instance is ready
=> remove the coresdkpackagelocation as it is no longer needed

FirebaseStorage/Sources/Internal/StorageDeleteTask.swift, FirebaseStorage/Sources/Internal/StorageGetDownloadURLTask.swift, FirebaseStorage/Sources/Internal/StorageGetMetadataTask.swift, FirebaseStorage/Sources/Internal/StorageInternalTask.swift, FirebaseStorage/Sources/Internal/StorageListTask.swift, FirebaseStorage/Sources/Internal/StorageTokenAuthorizer.swift, FirebaseStorage/Sources/Internal/StorageUpdateMetadataTask.swift, FirebaseStorage/Sources/Internal/StorageUtils.swift, FirebaseStorage/Sources/Result.swift, FirebaseStorage/Sources/Storage.swift, FirebaseStorage/Sources/StorageDownloadTask.swift, FirebaseStorage/Sources/StorageError.swift, FirebaseStorage/Sources/StorageListResult.swift, FirebaseStorage/Sources/StorageMetadata.swift, FirebaseStorage/Sources/StorageObservableTask.swift, FirebaseStorage/Sources/StorageReference.swift, FirebaseStorage/Sources/StorageTask.swift, FirebaseStorage/Sources/StorageTaskSnapshot.swift, FirebaseStorage/Sources/StorageUploadTask.swift, FirebaseStorage/Tests/Integration/StorageIntegration.swift, FirebaseStorage/Tests/Unit/StorageDeleteTests.swift, FirebaseStorage/Tests/Unit/StorageGetMetadataTests.swift, FirebaseStorage/Tests/Unit/StorageListTests.swift, FirebaseStorage/Tests/Unit/StorageMetadataTests.swift, FirebaseStorage/Tests/Unit/StorageReferenceTests.swift, FirebaseStorage/Tests/Unit/StorageUpdateMetadataTests.swift
Streamline  internal FirebaseStorageTask implementations.  All of the Internal StorageTask classes now do their fetcher calls from common code in StorageInternalTask.swift. Should be functionally equivalent to old implementation. It does a bit to improve concurrency and should make next steps easier.
This PR also adds availability checks to support building on Swift Package Manager with its lower global minimum platform versions for iOS.
TODO future: Assess feasibility of similar updates to public StorageTask classes. Determine if we still want to support the APIs providing the dispatch queue override. Assess how to do pause, resume and cancel for public tasks. Ultimately, we may want to switch out GTMSessionFetcher first.
#no-changelog
=> [v11] Streamline internal FirebaseStorageTask implementations

FirebaseVertexAI/README.md, FirebaseVertexAI/Tests/Unit/README.md, Package.swift, README.md, scripts/README.md
Added a `README.md` with instructions for running the `update_vertexai_responses.sh` script. This file was also added as a resource in the `FirebaseVertexAIUnit` `testTarget` ensuring that a `Bundle.module` will always be generated by Swift Package Manager. This prevents the following build error if the script has not yet been run:
#no-changelog
=> [Vertex AI] Add README for unit test mock files

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
Updated the Carthage artifacts for the https://github.com/firebase/firebase-ios-sdk/releases/tag/10.29.0. Verified with `carthage update`.
<details>
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseABTestingBinary.json" "10.29.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAdMobBinary.json" "10.29.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "10.29.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppCheckBinary.json" "10.29.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppDistributionBinary.json" "10.29.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" "10.29.0"
binary …
```
=> [Release] Carthage updates for 10.29.0

FirebaseStorage/Tests/Integration/StorageIntegration.swift
Fix a real storage integration test bug introduced in #13114.  It looks like it was missed because of other test flakiness
#no-changelog
=> Fix Storage integration test

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/ActionCode/ActionCodeInfo.swift, FirebaseAuth/Tests/Unit/SwiftAPI.swift
The property definition was inconsistent with the non-nullable initializer parameter.
=> [Auth] Update unnecessary nullable API

.github/workflows/auth.yml, FirebaseAuth/Tests/SampleSwift/AuthenticationExample.xcodeproj/project.pbxproj, FirebaseAuth/Tests/SampleSwift/AuthenticationExampleUITests/AuthenticationExampleUITests.swift, scripts/build.sh
The Auth integration tests were failing to run because of dependencies on old Swift Package binaries. They don't cause a failure to build when using the Xcode UI, but fail with xcodebuild. To resolve, I updated the Facebook SDK version and removed the recaptchaEnterprise dependency. Until Recaptcha resolves, its package should be added for manual testing.
I also separated the three integration tests with a matrix for easier analysis and fixed a regression that happened in the UITests.
#no-changelog
=> [Auth] Investigate and fix v11 integration test CI failures

FirebaseMessaging/Sources/FIRMessaging.m
Removed an extraneous `const` on the `BOOL` return type of `FIRMessagingIsAPNSSyncMessage(...)` to resolve a warning surfaced with internal tooling:
> return type 'const BOOL' (aka 'const bool') is 'const'-qualified at the top level, which may reduce code readability without improving const correctness
>
> https://clang.llvm.org/extra/clang-tidy/checks/readability/const-return-type.html
#no-changelog
=> [Messaging] Remove extraneous const on FIRMessagingIsAPNSSyncMessage

.github/workflows/auth.yml, FirebaseAuth.podspec, FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift, FirebaseAuth/Sources/Swift/User/User.swift, scripts/build.sh
Demonstrates how to disable deprecation warnings when linting pods on CI.
#no-changelog
(reverted for now) commit needed to apply to spm: https://github.com/firebase/firebase-ios-sdk/pull/13264/commits/01febc66e5b4c488d160f61b42fa6ff02edf671f
=> [Auth] Compile out deprecated API on CI

cmake/external/GoogleUtilities.cmake
Updated the cmake `GoogleUtilities` dependency to [`8.0.0`](https://github.com/google/GoogleUtilities/releases/tag/8.0.0) 
#no-changelog
=> Update cmake dependency for GoogleUtilities to 8.0.0

FirebaseRemoteConfig/Sources/RCNConfigRealtime.m, FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
When constructing the request payload for the realtime connection, a FIS token is requested for including in the payload. Previously, the payload construction did not wait for the FIS token request as it was async. I'm unsure if it was intentional or not, but it opened it up to a race condition where the async FIS token request may write to ivars that collide with reads to ivars during request payload construction. 
There's an existing comment indicating that the realtime request _needs_ a FIS token. In experiments thought where I hardcoded the FIS token to nil, I was still able to successfully fetch so that's a bit confusing. The wait for the installations token should be short in practice and it may set the realtime request up for success to have it.
This may address #13193 (I was not …
=> [Config] Wait for installations token before starting realtime connection

.github/workflows/google-utilities-components.yml, GoogleUtilitiesComponents.podspec, GoogleUtilitiesComponents/Sources/GULCCComponentContainer.m
- Update GoogleUtilitiesComponent for a breaking change to its internal dependency - GoogleUtilities.
- Drop osx and tvos support since its only client, MLKit, is iOS only
- Bump minimum iOS version to 12 
- Specify version for GoogleUtilities dependencies
**NOTE:** Clients still using the GoogleUtilitiesComponents 1.x may need to add `pod GoogleUtilities/Logger', "~> 7.13"` to their Podfiles.
=> [GoogleUtilitiesComponents] Major version update

FirebaseAuth/Sources/Swift/Auth/AuthTokenResult.swift, FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift, FirebaseAuth/Sources/Swift/User/User.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Models/UserActions.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Utility/Extensions.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/UserViewController.swift
- Add a missing API - Firebase 10 was missing an `NS_SWIFT_NAME` on one of the getIDToken APIs, leading to an inconsistent API set.
- Fix an error handling case that could crash in Firebase 10 and wasn't ported correctly in Firebase 11
- Update the sample app to make it easier to test the async getIDToken APIs
Details below:
Firebase 10 APIs
Firebase 11 APIs after this PR
In Firebase 10 it was possible for the completion handler to return both a nil tokenResult and error, when `tokenResultWithToken:token` errored.  In Firebase 11, the JWT error detection wasn't yet implemented. That is now fixed.
=> [auth] Fix getIDToken API and an error handling case

Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c
PThread attributes should be destroyed in failure and success cases.
#no-changelog
=> Clean up PThread attributes when it fails to be created

Firestore/Example/Tests/API/FSTUserDataReaderTests.mm, Firestore/Example/Tests/Integration/API/FIRCompositeIndexQueryTests.mm, Firestore/Example/Tests/Integration/API/FIRCursorTests.mm, Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm, Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm, Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm, Firestore/Example/Tests/Integration/API/FIRTypeTests.mm, Firestore/Example/Tests/Integration/FSTDatastoreTests.mm, Firestore/Source/API/FIRDocumentSnapshot.mm, Firestore/Source/API/FSTUserDataReader.mm, Firestore/Source/API/converters.mm
At HEAD, I'm getting:
```
% pod repo push --skip-tests --use-json  staging FirebaseFirestoreInternal.podspec --sources=git@github.com:firebase/SpecsStaging.git,https://cdn.cocoapods.org
Validating spec
-> FirebaseFirestoreInternal (11.0.0)
- WARN  | compiler_flags: Warnings must not be disabled(`-Wno compiler` flags).
- ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
- NOTE  | xcodebuild:  note: Building targets in dependency order
- NOTE  | xcodebuild:  note: Target dependency graph (24 targets)
- NOTE  | xcodebuild:  ld: warning: ignoring duplicate libraries: '-lc++'
- NOTE  | xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. …
```
=> [Infra] Use full paths when importing public Core header

FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift, FirebaseStorage/Sources/StorageUploadTask.swift
Our internal build system needs separate imports for each GoogleUtilities module like SWIFT_PM and unlike CocoaPods, so switch the define flag accordingly.
=> Update imports for internal build system

Package.swift
Fixes SPM warning: `Invalid Resource 'vertexai-sdk-test-data/mock-responses': File not found.`
=> [Infra] Remove missing resource for Vertex AI

FirebaseVertexAI/Tests/Unit/vertexai-sdk-test-data/mock-responses, Package.swift
- Revert #13300 
- Add a placeholder file instead to avoid the Swift Package Manager missing resource warning
Fixes failure in https://github.com/firebase/firebase-ios-sdk/actions/runs/9987020216
=> Fix VertexAI Unit Test resource handing in SPM

CONTRIBUTING.md, FirebaseDynamicLinks/CHANGELOG.md, FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m, FirebaseRemoteConfig.podspec, Firestore/Source/Public/FirebaseFirestore/FIRLocalCacheSettings.h, SwiftPackageManager.md
Please review the changes and let me know if this process is acceptable so that I can continue cleaning up the files incrementally, making this awesome SDK even more perfect.
Thank you
=> Fix typo in some method documentations, md files and local variables

scripts/build_zip.sh, scripts/check.sh, scripts/cpplint.py, scripts/health_metrics/README.md, scripts/health_metrics/generate_code_coverage_report/README.md, scripts/health_metrics/generate_code_coverage_report/Sources/IncrementalCoverageReportGenerator/main.swift, scripts/health_metrics/generate_code_coverage_report/Sources/UpdatedFilesCollector/main.swift, scripts/rotate_secrets.sh, scripts/run_database_emulator.sh
- All script files, README documents, and Swift codes under the scripts directory have been reviewed.
Please review the changes and let me know if this process is acceptable so that I can continue cleaning up the files incrementally, making this awesome SDK even more perfect.
Thank you
=> Fix typo of all scripts

FirebaseAppCheck.podspec, FirebaseAppCheck/Sources/DebugProvider/FIRAppCheckDebugProvider.m, FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckTests.m, FirebaseAppCheck/Tests/Unit/DeviceCheckProvider/FIRDeviceCheckProviderTests.m, Package.swift
I think this was leftover from the AppCheck implementation refactor. It should be ok to remove.
#no-changelog
=> [AppCheck] Remove unused Promises dependency

.github/workflows/zip.yml, FirebaseCore/CHANGELOG.md, ReleaseTooling/Sources/ZipBuilder/main.swift, scripts/build_zip.sh
#no-changelog
Selective revert.
Probably should look into building/running the dylib tests on a less frequent basis.
=> [Firebase 11] Default back to building static frameworks for RCs

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.m, Crashlytics/Crashlytics/Components/FIRCLSContext.m, Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m, Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.m, Crashlytics/Crashlytics/Helpers/FIRCLSFile.m, Crashlytics/Crashlytics/Models/FIRCLSInstallIdentifierModel.m, Crashlytics/Crashlytics/Models/FIRCLSLaunchMarkerModel.m, Crashlytics/Crashlytics/Models/FIRCLSOnDemandModel.m, Crashlytics/Crashlytics/Models/FIRCLSSymbolResolver.m, Crashlytics/Crashlytics/Settings/Models/FIRCLSApplicationIdentifierModel.m, Crashlytics/Shared/FIRCLSNetworking/FIRCLSNetworkResponseHandler.m, Crashlytics/UnitTests/FIRCLSDwarfTests.m
- All md files, Objective-C, and Swift codes under the Crashlytics directory have been reviewed.
=> Fix typo of the Crashlytics Objective-C and MD files

FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SignUpNewUserRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/VerifyPasswordRequest.swift, FirebaseAuth/Sources/Swift/MultiFactor/MultiFactorInfo.swift, FirebaseAuth/Sources/Swift/Utilities/AuthErrors.swift, FirebaseAuth/Tests/Unit/SwiftAPI.swift
- All source codes under the FirebaseAuth directory have been reviewed.
Important Note:
- I have ignored spelling variations when the word was acceptable in another English variation, such as British English, but there are inconsistencies in using these variations originally.
- I have ignored strings that are returned by the code [like this one where `unparseable` is not the standard spelling and The correct spelling is `unparsable`.](https://github.com/firebase/firebase-ios-sdk/blob/3c760cb1803e3cde368d8f3a28ef1 …
=> Fix typo of the FirebaseAuth source and test files

CoreOnly/Tests/FirebasePodTest/FirebasePodTest/SceneDelegate.swift
- **All files** (including source codes, md files, and etc.) under the CoreOnly directory have been reviewed.
- The corrected typo was found in a comment and non-compiling sections of the project so it is fully backward-compatible, with no breaking changes introduced.
Important Note:
- I ignored the typos in the NOTICES file ([like this on](https://github.com/firebase/firebase-ios-sdk/blob/6b74ae7ec159ad73c9c96782381b9a90e5e2dae4/CoreOnly/NOTICES#L352C55-L352C62)) because it seemed like they were from another source and could cause conflicts in the future. Please let me know if I am wrong, and I will fix them as well.
=> Fix typo of the CoreOnly directory files

CoreOnly/Tests/FirebasePodTest/FirebasePodTest/SceneDelegate.swift, Crashlytics/Crashlytics/Components/FIRCLSProcess.c, Crashlytics/Crashlytics/Handlers/FIRCLSException.mm, Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c, Crashlytics/Crashlytics/Private/FIRStackFrame_Private.h, Crashlytics/Crashlytics/Unwind/Compact/FIRCLSCompactUnwind.c, Crashlytics/Crashlytics/Unwind/Dwarf/FIRCLSDwarfUnwind.c, Crashlytics/Crashlytics/Unwind/FIRCLSUnwind.c, Crashlytics/Crashlytics/Unwind/FIRCLSUnwind_arm.c, Crashlytics/Crashlytics/Unwind/FIRCLSUnwind_x86.c
- All source codes under the Crashlytics directory have been reviewed. (Swift, md, and other files were reviewed previously)
Important Note:
- One of the fixes is a `pragma mark` which seems to be safe to change.
- One of the fixes is **a log message** which seems to be safe to change.
=> Fix typo of the Crashlytics c files

FirebaseABTesting/Sources/FIRExperimentController.m
- All files (including Swift, Objective-C, etc.) under the FirebaseABTesting directory have been reviewed.
Fortunately, there was only a single typo in a single comment among all the files of this package.
=> Fix typo of the FirebaseABTesting files

ReleaseTooling/Sources/FirebaseReleaser/main.swift
When `--update--tags-only` is used, I think it could be helpful to advise to re-push pods as needed. I'd like to make it do so by default, but this PR is small improvement on the way there.
Example of what the output looks like (I amended the code to add a trailing newline for the first line after screenshotting this):
#no-changelog
=> [Infra] Improve release tooling logging when updating tags

Crashlytics/Crashlytics/Helpers/FIRCLSContextInitData.h, Crashlytics/Crashlytics/Helpers/FIRCLSContextInitData.m, Crashlytics/UnitTests/FIRCLSRolloutsPersistenceManagerTests.m, Firestore/Swift/FirebaseFirestore.h, Firestore/core/src/api/listen_source.h, Firestore/core/src/util/thread_safe_memoizer.h, Firestore/core/test/unit/util/thread_safe_memoizer_test.cc, scripts/check_copyright.sh
`scripts/check_copyright.sh` was broken in #11647 
Fix the script and the files that were added with incorrectly formatted copyrights since.
=> Fix file copyrights

FirebaseAppCheck/Sources/Core/FIRAppCheckValidator.h, FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestProviderTests.m, FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckValidatorTests.m, FirebaseAppCheck/Tests/Unit/DebugProvider/FIRAppCheckDebugProviderTests.m, FirebaseAppCheck/Tests/Unit/DeviceCheckProvider/FIRDeviceCheckProviderTests.m
[Closes #13326]
* Added tests for `getLimitedUseTokenWithCompletion:` in `FIRAppAttestProvider`, `FIRDeviceCheckProvider`, and `FIRAppCheckDebugProvider`
* Added a test for `FIRAppCheckDebugProvider`’s `localDebugToken`
* Introduced the `FIRAppCheckValidatorTests` suite
* Marked `FIRAppCheckValidator`’s `init` as unavailable
=> [#13326] App Check Tests

FirebaseCore/Extension/FIRLogger.h, FirebaseCore/Sources/FIRApp.m, FirebaseCore/Sources/FIRComponentContainer.m, FirebaseCore/Sources/FIROptions.m
- **All source codes** (including Swift, Objective-C, etc.) under the FirebaseCore source directory have been reviewed.
=> Fix typo of the FirebaseCore source files

.github/workflows/remoteconfig.yml
Fix CI failure resulting from Analytics now requiring at least Xcode 15.2.
https://github.com/firebase/firebase-ios-sdk/actions/runs/10037044999/job/27764665204
=> Update Xcode for RC Sample

FirebaseDynamicLinks/Tests/Sample/FDLBuilderTestAppObjC/SceneDelegate.m
- All files (including source/non-source files) under the FirebaseAppDistributionInternal directory have been reviewed.
Fortunately, there was only a single comment in the test sample project remaining among all the files of the package.
=> Fix all typos found under the FirebaseDynamicLinks/Tests and the main directory 

FirebaseAppDistributionInternal/Sources/ApiService.swift
- All files (including source/non-source files) under the FirebaseAppDistributionInternal directory have been reviewed.
Fortunately, there was only a single file with a few typos in its comments among all the files in this directory.
=> Fix typo of the FirebaseAppDistributionInternal files

FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FDLURLComponents.h, FirebaseDynamicLinks/Sources/Utilities/FDLUtilities.h, FirebaseDynamicLinks/Sources/Utilities/FDLUtilities.m
- All source codes under the FirebaseDynamicLinks/Sources directory have been reviewed.
- All corrected typos found in the comments of the files.
=> Fix all typos found in the FirebaseDynamicLinks/Sources directory

FirebaseDatabase/Tests/Resources/syncPointSpec.json, FirebaseDatabase/Tests/Unit/FArraySortedDictionaryTest.m, FirebaseDatabase/Tests/Unit/FCompoundWriteTest.m, FirebaseDatabase/Tests/Unit/FTreeSortedDictionaryTests.m, FirebaseDatabase/Tests/Unit/Swift/DatabaseAPITests.swift
- All source codes under the FirebaseDatabase/Test and the main directory were reviewed.
- Corrected typos primarily found in comments, exception logs, and non-compiling sections of the project.
=> Fix all typos found under the FirebaseDatabase/Tests and the main directory

FirebaseDatabase/Sources/Core/FQueryParams.m, FirebaseDatabase/Sources/Core/FRangeMerge.m, FirebaseDatabase/Sources/Core/FRepo.m, FirebaseDatabase/Sources/Core/FWriteTree.m, FirebaseDatabase/Sources/Core/FWriteTreeRef.m, FirebaseDatabase/Sources/Core/View/FKeepSyncedEventRegistration.m, FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m, FirebaseDatabase/Sources/Realtime/FWebSocketConnection.m, FirebaseDatabase/Sources/Snapshot/FCompoundWrite.m, FirebaseDatabase/Sources/Utilities/FNextPushId.m, FirebaseDatabase/Sources/third_party/FImmutableSortedDictionary/FImmutableSortedDictionary/FLLRBValueNode.m
- All source codes under the FirebaseDatabase/Sources directory have been reviewed.
Important note
Based on my experience with the previous PRs, I have decided to make the commit chunks bigger and group them by their parent directory for ease of use.
=> Fix all typos found under the FirebaseDatabase/Sources directory

FirebaseCombineSwift/DECISIONS.md
- All files (including both Swift and MD files) under the FirebaseCombineSwift directory have been reviewed.
Fortunately, there was only a single typo in a single md file among all the files of this directory.
=> Fix typo of the FirebaseCombineSwift files

.github/workflows/crashlytics.yml, .github/workflows/messaging.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml
Fix messaging https://github.com/firebase/firebase-ios-sdk/actions/runs/10053579898/job/27786610055 from nightlies
Fix crashlytics https://github.com/firebase/firebase-ios-sdk/actions/runs/10051567235/job/27782964149
Stop ObjC quickstarts for products that depend on Swift-implementations in release and prerelease jobs
=> Quickstart testing fixes

FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/App/InAppMessaging-Example-iOS/AppDelegate.m, FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/App/InAppMessaging-Example-iOS/AutoDisplayFlowViewController.m, FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/App/InAppMessaging-Example-iOS/AutoDisplayMessagesTableVC.h, FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/App/InAppMessaging-Example-iOS/AutoDisplayMessagesTableVC.m, FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/App/InAppMessaging-Example-iOS/Base.lproj/Main.storyboard, FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/InAppMessaging-Example-iOS.xcodeproj/project.pbxproj
- The primary change is due to a typo in a class name and its corresponding file name.
- All references to the updated resources have been revised, including storyboards, headers, implementations, and project files, using Xcode’s native refactor feature.
Please manually verify the changes in addition to my manual tests, as there are no existing UI tests to ensure coverage and this PR contains changes in XML files.
=> Fix typos in the FunctionalTestApp project of the FirebaseInAppMessaging package

FirebaseInAppMessaging/Sources/DefaultUI/ImageOnly/FIRIAMImageOnlyViewController.m, FirebaseInAppMessaging/Sources/DefaultUI/Modal/FIRIAMModalViewController.m, FirebaseInAppMessaging/Sources/Private/Runtime/FIRIAMSDKSettings.h, FirebaseInAppMessaging/Sources/Runtime/FIRIAMActionURLFollower.m, FirebaseInAppMessaging/Sources/Runtime/FIRIAMRuntimeManager.m
- All source codes under the FirebaseInAppMessaging/Sources directory have been reviewed.
=> Fix all typos found under the FirebaseInAppMessaging/Sources directory

FirebaseInAppMessaging/Tests/Unit/FIRIAMClearcutUploaderTests.m, FirebaseInAppMessaging/Tests/Unit/FIRIAMMsgFetcherUsingRestfulTests.m, FirebaseInAppMessaging/Tests/Unit/FIRIAMSDKModeManagerTests.m
- All files in the FirebaseInAppMessaging/Tests directory have been reviewed.
- All corrected typos were just comments so no breaking changes were introduced.
=> Fix all typos found under the FirebaseInAppMessaging/Tests directory

FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsBackoffController.m
All files (including Swift, Objective-C, etc.) in the package directory have been reviewed.
Fortunately, there was only a single typo in a single comment among all the files.
=> Fix all typos found in the FirebaseInstallations package

FirebaseMessaging/Sources/Token/FIRMessagingCheckinService.h, FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m, FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.m
All files in the directory have been reviewed and all the typos were just comments.
=> Fix all typos found under the FirebaseMessaging/Sources/Token directory

FirebaseMessaging/Sources/FIRMessaging.m, FirebaseMessaging/Sources/FIRMessagingRemoteNotificationsProxy.m, FirebaseMessaging/Sources/FIRMessagingRmqManager.h, FirebaseMessaging/Sources/FIRMessagingRmqManager.m, FirebaseMessaging/Sources/FIRMessagingSyncMessageManager.h
All files in the directory have been reviewed and all the typos were just comments.
I had to use a slightly less common version of a word to satisfy the linter line length check.
=> Fix all typos found under the FirebaseMessaging/Sources directory

FirebaseMLModelDownloader/Tests/Unit/ModelDownloaderUnitTests.swift
All files in the package directory have been reviewed.
Fortunately, there was only a single typo in a single comment and a single one in an XCTFail message among all the files.
=> Fix typos in FirebaseMLModelDownloader package

FirebaseRemoteConfig/Tests/Swift/SwiftAPI/FirebaseRemoteConfigSwift_APIBuildTests.swift
All Swift files have been reviewed and the only change was in a single comment because of a typo.
=> Review FirebaseRemoteConfig Tests Swift files

FirebaseVertexAI/Tests/Unit/PartsRepresentableTests.swift
It was a single typo repeated in multiple XCTFail messages, likely due to a copy-paste error.
=> Review FirebaseVertexAI Tests

FirebaseStorage/Tests/Unit/StorageAPITests.swift
The only change is the name of a local variable within a closure that has a very limited scope and is unused. It might be best to remove it entirely.
=> Review FirebaseStorage test files

Firestore/third_party/nlohmann_json/json.hpp
All changes are in the comments.
The correct form of `Endianess` is `Endianness` and it is correct at the referenced StackOverflow link in the code.
=> Review Firestore third party files

ReleaseTooling/Sources/Utils/String+Utils.swift
I checked all the util sources and found only one simple typo in a comment.
=> Review ReleaseTooling Utils Sources

cmake/external/leveldb_patch.py
The only issue was in a string that appeared to be a message. Please double-check the usage. Thanks.
=> Review external cmake files

ReleaseTooling/Sources/FirebaseReleaser/main.swift
I ran into this when moving tags. My local tags were outdated so it recommending re-staging pods that had already been staged.
=> [Infra] Fetch tags first when running firebase-releaser

FirebaseMessaging/Tests/UnitTests/FIRMessagingExtensionHelperTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingPendingTopicsListTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingPubSubTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m
I missed this one. All changes to this one were in comments, log messages, and pragmas as well.
=> Review FirebaseMessaging Tests files

FirebaseFunctions/Sources/Internal/FunctionsSerializer.swift, FirebaseFunctions/Tests/Unit/SerializerTests.swift
* Updated `FUNSerializer`:
* Nested the error type inside `FUNSerializer`
* Extended `Error.unsupportedType` to include the type name (as resolved at runtime)
* Refactored `decode(_:)`’s handling of dictionaries
* Removed the explicit initializer
* Updated `SerializerTests`:
* Introduced tests for encoding and decoding values of unsupported types
* Moved `serializer` initialization to `setUp()`
* Removed commented test (seems like it’s already implemented in Swift)
=> Functions Serializer Updates

FirebaseStorage/Sources/StorageDownloadTask.swift, FirebaseStorage/Sources/StorageUploadTask.swift
Make code more readable by using async `beginFetch` from GTMSessionFetcher
=> [storage] Use async GTMSessionFetcher method

FirebaseStorage/Sources/Internal/StorageTokenAuthorizer.swift, FirebaseStorage/Sources/Storage.swift, FirebaseStorage/Sources/StorageDownloadTask.swift, FirebaseStorage/Sources/StorageObservableTask.swift, FirebaseStorage/Sources/StorageReference.swift, FirebaseStorage/Sources/StorageUploadTask.swift, FirebaseStorage/Tests/Unit/StorageAuthorizerTests.swift, FirebaseStorage/Tests/Unit/StorageDeleteTests.swift, FirebaseStorage/Tests/Unit/StorageGetMetadataTests.swift, FirebaseStorage/Tests/Unit/StorageListTests.swift
After #13405, Storage no longer depends on GTMSessionFetcher to do callbacks, so simplify the implementation accordingly.
Note, that the public property will be less important the more people use the async API variations.
=> [storage] Simplify callback implementation

FirebaseFunctions/Sources/Functions.swift, FirebaseFunctions/Sources/FunctionsError.swift, FirebaseFunctions/Sources/Internal/FunctionsSerializer.swift, FirebaseFunctions/Tests/Unit/FunctionsSerializerTests.swift
* Renamed `FUNSerializer` to `FunctionsSerializer` to follow the naming convention for Swift
* Renamed `SerializerTests` to `FunctionsSerializerTests` for consistency
* `FunctionsSerializer` is internal, so this change does not affect the public API
=> Renamed `FUNSerializer` to `FunctionsSerializer`

.github/workflows/zip.yml
In the event there is a failure, it may be helpful to have the directory so we can access the build logs. This should hopefully save the need to locally build the zip to figure out what went wrong.
=> [Infra] Upload build-from-HEAD zips on failures

.swiftformat, scripts/check.sh, scripts/style.sh
Added a `.swiftformat` file for SwiftFormat configuration options, similar to `.clang-format`. This makes it easy to override options in specific subdirectories.
Enabled `sortedImports`, which was previously [disabled](https://github.com/firebase/firebase-ios-sdk/blob/6c5b8b796d9c772ea1072c3d12ce0081515666b4/scripts/style.sh#L98-L99). This feature appears to be working correctly now.
#no-changelog
=> Move swiftformat options to a config file

FirebaseFunctions/Sources/Internal/FunctionsSerializer.swift, FirebaseFunctions/Tests/Unit/FunctionsSerializerTests.swift
* If `FunctionsSerializer` is given an object of unsupported type to encode, it throws an error
* However, if that object is contained in a dictionary, `FunctionsSerializer` crashes the app because of a force-unwrap
* The change fixes this inconsistency
* Additionally, array decoding no longer uses an `if-let` and instead inserts the optional value `as Any`
* Overall, this change achieves consistency in encoding and decoding of collections: Any non-codable element fails the operation, without crashing the app or resulting in missing elements
* New tests were added to check these scenarios
=> Consistent Collections Coding in `FunctionsSerializer`

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/AuthProvider/AuthProviderID.swift, FirebaseAuth/Sources/Swift/AuthProvider/AuthProviderStrings.swift, FirebaseAuth/Tests/Unit/SwiftAPI.swift
Fix #13429
The change from an `enum` to a `struct` also enables us to add future providers without breaking existing code.
=> [Auth] Add custom provider support for AuthProviderID

Crashlytics/UnitTests/FIRCLSReportManagerTests.m
`FIRCLSReportManagerTests.m` flakes pretty consistently for macCatalyst. I'm experimenting with making things a bit more stable.
Fix #13431
=> [Infra] Attempt to fix some Crashlytics flakes

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Utilities/AuthErrors.swift, FirebaseAuth/Tests/Unit/SwiftAPI.swift
Fix #13430 
AuthErrorCode now implements Swift.Error
A `code` var is added to provide backwards compatibility.
=> [AuthErrorCode] should conform to Swift.Error

.github/workflows/prerelease.yml, scripts/release_testing_setup.sh
https://github.com/firebase/firebase-ios-sdk/pull/13217 did not work as expected and the prerelease nightly has been broken. I think the takeaway is that the GITHUB_TOKEN cannot be used in new clones, only in the workflow's original checkout context.
#no-changelog
=> [Infra] Fix auto-tagging in `release_testing_setup.sh` for prerelease.yml

FirebaseAppCheck/Sources/Core/FIRApp+AppCheck.m, FirebaseAppCheck/Sources/Core/FIRAppCheck.m, FirebaseAppCheck/Sources/Core/FIRHeartbeatLogger+AppCheck.m
This PR is a bit defensive since I don't know if this will be a problem. It's possible
these symbols, if not linked, could lead to undefined behavior in a SwiftUI preview
context where we don't have clear control over the linking parameters.
=> [AppCheck] Force link categories

scripts/release_testing_setup.sh
Merge job worked in a feature branch: https://github.com/firebase/firebase-ios-sdk/actions/runs/10188890512/job/28185925280
But, not working on main after #13427: https://github.com/firebase/firebase-ios-sdk/actions/runs/10188797807
This PR includes a unrelated fix (quieter git fetch) with some debugging code for the current issue.
#no-changelog
=> [Infra] Quiet the git fetch (#13436)

.github/workflows/prerelease.yml, scripts/release_testing_setup.sh
The issue stems from #13061. I think it's a good, future-looking fix (because of long running)
pre-release branches for major version changes, but didn't take into account that the
checkout action will only do a shallow checkout. The script can't find the latest tag merged to
main when the checkout is shallow, so doing a full clone should resolve this.
=> [Infra] Attempt to fix post-merge tagging in prerelease.yml

.editorconfig
Added a starter `.editorconfig` file for the repo. Xcode 16 [adds support](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes#New-Features-in-Xcode-16-Beta) for a subset of all [EditorConfig properties](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties).
#no-changelog
=> Add basic EditorConfig file for repo

FirebaseStorage/CHANGELOG.md, FirebaseStorage/Sources/Internal/StorageDeleteTask.swift, FirebaseStorage/Sources/Internal/StorageFetcherService.swift, FirebaseStorage/Sources/Internal/StorageGetDownloadURLTask.swift, FirebaseStorage/Sources/Internal/StorageGetMetadataTask.swift, FirebaseStorage/Sources/Internal/StorageInternalTask.swift, FirebaseStorage/Sources/Internal/StorageListTask.swift, FirebaseStorage/Sources/Internal/StorageUpdateMetadataTask.swift, FirebaseStorage/Sources/Storage.swift, FirebaseStorage/Sources/StorageDownloadTask.swift, FirebaseStorage/Sources/StorageObservableTask.swift, FirebaseStorage/Sources/StorageReference.swift, FirebaseStorage/Sources/StorageTask.swift, FirebaseStorage/Sources/StorageUploadTask.swift, FirebaseStorage/Tests/Unit/StorageComponentTests.swift, FirebaseStorage/Tests/Unit/StorageDeleteTests.swift, FirebaseStorage/Tests/Unit/StorageGetMetadataTests.swift, FirebaseStorage/Tests/Unit/StorageListTests.swift, FirebaseStorage/Tests/Unit/StorageTestHelpers.swift, FirebaseStorage/Tests/Unit/StorageUpdateMetadataTests.swift
Fix #13369
Moves fetcherService to an actor
Not only should it fix the issue, the code and tests are more compact and readable.
Removed unnecessary `availability` checks that were incorrectly setting watchOS to 8
=> [storage] Migrate to actor to fix a potential data race in initialization

FirebaseStorage/Sources/Storage.swift
For context, the original error was: <img width="587" alt="Screenshot 2024-08-01 at 1 31 49 PM" src="https://github.com/user-attachments/assets/496e1a93-54df-4643-8a0d-5096782c0e78">
The important takeaway is that if you synchronize something with an actor (e.g. instance management) in a method that isn't async like:
```swift
private class func storage(app: FirebaseApp, bucket: String) -> Storage
```
you'd have to change the signature of the public function which would be breaking.
So I avoided the formal route by decorating the property with `nonisolated(unsafe)` which tells the compiler that we know what we are doing (which we do with the locking mechanism in place). But using `nonisolated(unsafe)` ([3f1ba97](https://github.com/firebase/firebase-ios-sdk/pull/13445/commits/3f1ba97f27051d6 …
=> [Storage] Addressing Swift 6 issues with `Storage`'s instance management

FirebaseFunctions/Sources/Functions.swift, FirebaseFunctions/Sources/Internal/FunctionsSerializer.swift
* Removed `dateFormatter` from `FunctionsSerializer` as it wasn’t used anywhere
* Redeclared `FunctionsSerializer` as a native Swift class
* Updated `Functions`’s `callFunction(url:withObject:options:timeout:context:completion:)` to reduce mutability
=> Functions Cleanup

.github/workflows/release.yml, scripts/release_testing_setup.sh
Addressing comment in https://github.com/firebase/firebase-ios-sdk/pull/13427#discussion_r1699155417
Successful invocation: https://github.com/firebase/firebase-ios-sdk/actions/runs/10217804453
#no-changelog
=> [Infra] Removing 'release.yml' special casing in 'scripts/release_testing_setup.sh'

FirebaseStorage/Sources/Internal/StorageFetcherService.swift, FirebaseStorage/Sources/Internal/StorageInternalTask.swift, FirebaseStorage/Sources/Storage.swift, FirebaseStorage/Sources/StorageDownloadTask.swift, FirebaseStorage/Sources/StorageUploadTask.swift, FirebaseStorage/Tests/Unit/StorageAuthorizerTests.swift, FirebaseStorage/Tests/Unit/StorageDeleteTests.swift, FirebaseStorage/Tests/Unit/StorageGetMetadataTests.swift, FirebaseStorage/Tests/Unit/StorageListTests.swift, FirebaseStorage/Tests/Unit/StorageTestHelpers.swift, FirebaseStorage/Tests/Unit/StorageUpdateMetadataTests.swift
Follow on to #13428 
Manage fetcherService from a data race safe singleton
Remove fetcherService property from Storage class
Update unit tests
=> [Storage] Manage fetcherService from a data race safe singleton

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AuthViewController.swift, FirebaseAuth/Tests/Unit/AuthAPNSTokenManagerTests.swift, FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
Issue reproducible by changing unit test like so:
--- 
In the Objective-C implementation, `(nil, nil)` was being passed back by
getToken during timeouts.
https://github.com/firebase/firebase-ios-sdk/blob/eca84fd638116dd6adb633b5a3f31cc7befcbb7d/FirebaseAuth/Sources/SystemService/FIRAuthAPNSTokenManager.m#L89-L95
This didn't cause issue though because the API calling getToken only checked for
the presence of a non-nil token:
https://github.com/firebase/firebase-ios-sdk/blob/eca84fd638116dd6adb633b5a3f31cc7befcbb7d/FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m#L613-L618
In Swift though, the catch block will implicitly unwrap error, leading to the
crash when error is nil due to the timeout:
https://github.com/firebase/firebase-ios-sdk/blob/a5c253d1b4409eb8aef4346015ba000f9935 …
=> [Auth] Fix async/await crash from implicitly unwrapped nil error

FirebaseFunctions/Sources/Functions.swift
* Removed a force unwrap to prevent the app from crashing when the request data cannot be encoded
* Moved fetch-result handling to separate (throwing) functions to improve readability and ensure that the completion handler is called exactly once
* For consistency, all calls to `completion` occur on the main thread
=> Refactored Function Calling

FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatController.swift, FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift
```swift
public final class HeartbeatController {
/// ...
static let dateStandardizer: (Date) -> (Date) = {
var calendar = Calendar(identifier: .iso8601)
calendar.locale = Locale(identifier: "en_US_POSIX")
calendar.timeZone = TimeZone(secondsFromGMT: 0)!
return calendar.startOfDay(for:)
}()
/// ...
}
```
Gave the following error:
> error: static property 'dateStandardizer' is not concurrency-safe because non-'Sendable' type '(Date) -> (Date)' may have shared mutable state
static let dateStandardizer: (Date) -> (Date) = {
^
I marked the closure `@Sendable` (because there should be no mutable state due to this static property), which silenced the Swift 6 build but the Swift 5 build issues a warning for this:
> warning: converting non-sendable function value to '`@Sendable` (Date) -> (Date)' …
=> [CoreInternal] Address Swift 6 warnings (1)

Firestore/Swift/Source/Codable/DocumentReference+Codable.swift, Firestore/Swift/Source/Codable/FieldValue+Encodable.swift, Firestore/Swift/Source/Codable/GeoPoint+Codable.swift, Firestore/Swift/Source/Codable/Timestamp+Codable.swift, Firestore/Swift/Source/Codable/VectorValue+Codable.swift
Addresses Swift 6.0 warning introduced in https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md
Using backwards compatible solution described in https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md#source-compatibility
=> [Firestore] Resolve protocol conformance warnings

FirebaseInAppMessaging/Sources/FIRInAppMessaging.m, FirebaseInAppMessaging/Sources/Runtime/FIRInAppMessaging+Bootstrap.m, FirebaseInAppMessaging/Sources/Util/NSString+FIRInterlaceStrings.m, FirebaseInAppMessaging/Sources/Util/UIApplication+FIRForegroundWindowScene.m, FirebaseInAppMessaging/Sources/Util/UIColor+FIRIAMHexString.m, FirebaseInstallations/Source/Library/FIRInstallations.m, FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsItem+RegisterInstallationAPI.m, FirebaseMessaging/Sources/FIRMessaging.m, FirebaseMessaging/Sources/NSDictionary+FIRMessaging.m, FirebaseMessaging/Sources/NSError+FIRMessaging.m
Final follow-up to #13435.
Used following command to find category implementations:
```
grep -E -l -r '@implementation\s+\w+\s+\(\w+\)\s*$' . --include='*.m' --exclude-dir='Tests' --exclude-dir='gen'
```
I skipped files where the category implementation was in a .m that also had a
non-category implementation.
Hard to say if any of these would affect SwiftUI preview/live preview behavior, but this PR shouldn't hurt.
#no-changelog
=> [Infra] Force link remaining categories after #13435

FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Models/AuthMenu.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AccountLinkingViewController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AuthViewController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/OtherAuthMethodControllers/PasswordlessViewController.swift
Add abilities for swift sample app to add hosting domain for FDL deprecation.
Sample HTTP request observed from testing
postBody -
["requestType": AnyHashable("PASSWORD_RESET"), "continueUrl": AnyHashable("fake"), "clientType": AnyHashable("CLIENT_TYPE_IOS"), "canHandleCodeInApp": AnyHashable(true), "iOSBundleId": AnyHashable("fake"), "email": AnyHashable("fake"), "linkDomain": AnyHashable("<input link>")]
=> update the sample app to use link domains for ActionCodeSettings

FirebaseAuth.podspec, FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift, FirebaseAuth/Tests/Unit/FIROAuthProviderTests.m, Package.swift
This test demonstrates calling the UI off the main thread for Objective-C only as reported at https://github.com/firebase/FirebaseUI-iOS/issues/1199
Add back some ObjC unit tests for ObjC FIROAuthProvider including adapting one for main thread testing. 
Use CI only ifdef to access an internal property in ObjC unit test setup.
Note: the test only runs via the CocoaPods setup.
=> Fix and Regression Test for FirebaseUI 1199

FirebaseVertexAI/Sources/FunctionCalling.swift, FirebaseVertexAI/Sources/Schema.swift
Moved `Schema` and `DataType` out of the `FunctionCalling.swift` file since they are used for both function calling and JSON mode. Done in a separate PR to make the upcoming `Schema` changes easier to diff.
#no-changelog
=> [Vertex AI] Move `Schema` and `DataType` to separate file

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Added an optional `title` field to `Citation`. Made the `uri` field optional since it may not be included when the `title` is provided. This resolves #13518.
Sample files for tests updated in https://github.com/FirebaseExtended/vertexai-sdk-test-data/pull/15.
=> [Vertex AI] Make `uri` optional in `Citation` and add `title` field

FirebaseFunctions/Sources/Internal/FunctionsContext.swift
* Changed `FunctionsContext` and `FunctionsContextProvider` to structs since reference semantics isn’t used anywhere
* Removed `FunctionsContext`’s explicit initializer
* Changed `FunctionsContextProvider`’s instance properties to constants
=> `FunctionsContext` Updates

Package.swift
OCMock 3.9.4 now includes https://github.com/erikdoe/ocmock/pull/537 that fixes Xcode 15.3 builds on Intel.
=> Update OCMock dependency to v3.9.4

FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
This is one step towards fixing #13479.
There are two parts to fix for that issue:
1. why invalid app credential is being returned
2. how SDK responds to it
After testing 10.29.0, I can only reproduce the issue on 11.0.0. This PR addresses the second point– how the SDK responds to the error.
Based on the 11.0.0 code comment (see diff) and 10.29.0 code (see below snippet), reCAPTCHA should launch for a missing app token or invalid app credential. 
https://github.com/firebase/firebase-ios-sdk/blob/eca84fd638116dd6adb633b5a3f31cc7befcbb7d/FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m#L628-L630
The issue is that the v11 parsing logic was expecting the invalid app credential to be an internal error, but it is not wrapped as such, so the control flow never enters the …
=> [Auth] Phone Auth – Fallback to reCATCHA flow when "invalid app credential" error is thrown

Firestore/core/src/remote/grpc_stream.cc, Firestore/core/src/remote/remote_store.cc, Firestore/core/src/remote/stream.cc, Firestore/core/src/util/string_format.cc, Firestore/core/test/unit/util/string_format_test.cc
While trying to record Firestore logs within our app, we started to notice many log lines were being reported as `(null)` in the Console. This seems to be because when logging the reference to the C++ objects, the `%s` format was adding non-UTF8 encodable characters into the string. This meant when using `MakeNSString` in the Firestore logger, those non-UTF8 characters failed the string initialization, and it returns `nil`.
Since there is already quite a lot of use of `absl` in the repo, I figured we could quick-win, use that to convert the string to hex and record that instead. I suspect logging the object was meant just to see if the value drifted overtime, rather than anything intrinsic to the object itself, so the hex value should do the same thing.
I only added a test for the record …
=> Support hex strings to prevent broken log lines

FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
The model resource name is configured in the `VertexAIComponent` when constructing a `GenerativeModel` so the `GenerativeModel.modelResourceName` method was always following the path:
```
if name.contains("/") {
return name
}
```
Added tests for `VertexAI.modelResourceName(location:)` to verify that the correct values are propagated to the `GenerativeModel`.
#no-changelog
=> [Vertex AI] Remove extraneous `GenerativeModel.modelResourceName` method

FirebaseVertexAI/Sample/VertexAISample.xcodeproj/project.pbxproj
Updated the Vertex AI sample apps to use [MarkdownUI 2.4.0](https://github.com/gonzalezreal/swift-markdown-ui/releases/tag/2.4.0) ([55441810c0f678c78ed7e2ebd46dde89228e02fc](https://github.com/gonzalezreal/swift-markdown-ui/commit/55441810c0f678c78ed7e2ebd46dde89228e02fc)). This fixes the Circular Reference error (https://github.com/gonzalezreal/swift-markdown-ui/issues/323) when compiling on Xcode 16 Beta (first included in [MarkdownUI 2.3.1](https://github.com/gonzalezreal/swift-markdown-ui/releases/tag/2.3.1) but updating to latest).
#no-changelog
=> [Vertex AI] Update MarkdownUI dep to 2.4.0 in sample app

FirebaseAuth/Tests/SampleSwift/AuthenticationExample/SceneDelegate.swift
Without this in the auth sample app, recaptcha's login safari controller won't dismiss when swizzling is disabled. cc: @rizafran 
This is already covered in the last code snippet of the docs which is good: https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling
In iOS 13+, the scene delegate may take priority when opening URLs: https://stackoverflow.com/a/75064585/9331576
#no-changelog
=> [Auth] When swizzling is disabled, open URLs via SceneDelegate

FirebaseVertexAI/Sources/FunctionCalling.swift, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Sources/JSONValue.swift, FirebaseVertexAI/Sources/ModelContent.swift, FirebaseVertexAI/Sources/Safety.swift
Added `Sendable` conformance to Vertex AI types in preparation for strict concurrency checking in Swift 6.
#no-changelog
=> [Vertex AI] Add `Sendable` conformance to types

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/Backend/RPC/CreateAuthURIResponse.swift, FirebaseAuth/Tests/SampleSwift/SwiftApiTests/EmailPasswordTests.swift
- Revert the URL to match Firebase 10 (https://github.com/firebase/firebase-ios-sdk/blob/eca84fd638116dd6adb633b5a3f31cc7befcbb7d/FirebaseAuth/Sources/Auth/FIRAuth.m#L676). This actually didn't make a difference and I was able to get valid sign in methods when using both forms. LMK if there is a reason to not change it back.
- The below line lead to crash as `response.signinMethods` is `nil` so the continuation throws an implicitly unwrapped error which crashes.
https://github.com/firebase/firebase-ios-sdk/blob/486a0a03c197a267a4a54d5f0077e1703b197588/FirebaseAuth/Sources/Swift/Auth/Auth.swift#L298
- This can be reproduced in a scenario where email enumeration protection is turned on. The unit test added will fail without the corresponding changes in …
=> [Auth] Fix unexpected nil in fetchSignInMethods success case

.github/workflows/zip.yml
There seems to be a general issue with macos-14 GHA configurations. See https://github.com/actions/runner-images/issues/10386#issuecomment-2322779560
Reverting to macos-13 fixes the problem at the cost of slower builds.
Let's merge this Tuesday if nightlies are still broken
Investigating zip failure in #13558
=> Revert zip builds to macos-13

FirebaseFunctions/Sources/Functions.swift, FirebaseFunctions/Sources/FunctionsError.swift
* Moved `FunctionsCodeForHTTPStatus(_:)` and `FunctionsErrorForResponse(status:body:serializer:)` to a `FunctionsErrorCode` extension to reduce the number of global symbols
* Updated `FunctionsCodeForHTTPStatus(_:)`’s documentation to reflect the actual behavior (return value for unknown status codes)
=> Updated Functions Errors

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
Fix #13565 
The tenantID on the Auth instance must be set before calling `updateCurrentUser`
=> Fix user session persistence in multi tenant projects

FirebaseDatabase/CHANGELOG.md, FirebaseDatabase/Sources/Core/FPersistentConnection.m, FirebaseDatabase/Sources/Realtime/FWebSocketConnection.m
Remove background/foreground notification handling. They were only unnecessary for watchOS since it doesn't support persistent connections. When it was mistakenly applied to other platforms with the Socket Rocket to Web Socket update, it caused extra disconnects.
Fix #13529
=> Fix temporary disconnect when app goes inactive

FirebaseVertexAI/Sources/Logging.swift
Made the `Logger` properties in the Vertex AI `Logging` struct constants since they can be immutable. This fixes a warning with Swift 6 strict concurrency checking:
> Static property 'default' is not concurrency-safe because it is nonisolated global shared mutable state; this is an error in the Swift 6 language mode
#no-changelog
=> [Vertex AI] Make `Logger` properties constants

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sample/ChatSample/Screens/ConversationScreen.swift, FirebaseVertexAI/Sample/ChatSample/ViewModels/ConversationViewModel.swift, FirebaseVertexAI/Sample/FunctionCallingSample/Screens/FunctionCallingScreen.swift, FirebaseVertexAI/Sample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift, FirebaseVertexAI/Sample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift, FirebaseVertexAI/Sample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift, FirebaseVertexAI/Sources/Chat.swift, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift, FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
Turned `GenerativeModel` and `Chat` into Swift actors in preparation for supporting concurrency-safe history in the two classes (history _may_ migrate from `Chat` to `GenerativeModel`).
Note: This does not address Swift 6 Strict Concurrency warnings but compiles without warnings in Xcode 15.2 and 16.1 Beta 1 with the default settings.
=> [Vertex AI] Make `GenerativeModel` and `Chat` into Swift actors

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerationConfig.swift, FirebaseVertexAI/Tests/Unit/GenerationConfigTests.swift
Added `responseSchema` to `GenerationConfig` to allow a schema to be provided for generated JSON when `responseMIMEType` is `application/json`. See [control generated output](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/control-generated-output) for more details.
=> [Vertex AI] Add `responseSchema` to `GenerationConfig`

cmake/compiler_setup.cmake
Add `-Wno-error=redundant-move` to avoid failing the build due to unnecessary `std::move()` calls. It is common practice to use `std::move()` liberally, even if it's not strictly beneficial, to ensure that a type is moved if its definition is ever changed to not be trivially movable. Therefore, it doesn't make sense to fail the build due to unnecessary `std::move()` calls.
This fixes the following compiler error:
```
[2094/2338] Building CXX object Firestore/core/CMakeFiles/firestore_util.dir/src/util/logic_utils.cc.o
FAILED: Firestore/core/CMakeFiles/firestore_util.dir/src/util/logic_utils.cc.o 
/usr/bin/ccache /usr/bin/c++ -DCARES_STATICLIB -DFIRESTORE_HAVE_CONFIG_DETECTED_H -DPB_ENABLE_MALLOC -DPB_FIELD_32BIT -DPB_NO_PACKED_STRUCTS=1 -Ifirebase-ios-sdk/cmake-build-debug …
```
=> Add `-Wno-error=redundant-move` to cmake builds

cmake/external/nanopb.patch
If performing a cmake build with Python 3.11 or earlier, everything works fine; however, if using Python 3.12 the cmake build fails with `ModuleNotFoundError: No module named 'distutils'`. This is because the `distutils` module was deleted in Python 3.12 (see https://peps.python.org/pep-0632/ and https://docs.python.org/3/whatsnew/3.12.html#distutils).
The problem was coming from nanopb which referenced the `distutils` module in its `CMakeLists.txt`. The fix was to copy the replacement command that works in Python 3.12, and should work all the way back to Python 3.7 (see https://github.com/nanopb/nanopb/pull/727 and https://github.com/nanopb/nanopb/pull/730). This PR merely tweaks the patching that is already done on nanopb.
Here is what the error looks like, which this PR fixes:
```
$ …
```
=> Fix cmake builds with Python 3.12, which deleted the long-deprecated 'distutils' module

Package.swift
Updated the `FirebaseFirestoreInternal` binary target in preparation for the 11.2.0 release.
Note: This will need to be cherry-picked into https://github.com/firebase/firebase-ios-sdk/tree/release-11.2 since `main` has commits after code freeze.
=> [Release] Update Firestore SPM binary for 11.2.0

Package.swift
Cherry-picking https://github.com/firebase/firebase-ios-sdk/commit/60b6dd591e1e24ede5a82b8e1b2fa44c807da4c8 into `release-11.2`.
#no-changelog
=> [Release] Update Firestore SPM binary for 11.2.0 (#13594)

FirebaseAuth/Sources/Swift/Utilities/AuthErrorUtils.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/SettingsViewController.swift
- Add description string to generated keychain errors
- Use public API to set shared keychain instead of internal one in sample
=> [Auth] Better keychain error descriptions

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Backend/RPC/Proto/AuthProtoMFAEnrollment.swift, FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPMultiFactorInfo.swift, FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift, FirebaseAuth/Tests/Unit/UserTests.swift
Fix #13591
- Remove unneeded `totpInfo` property because it's not used. The property on `AuthProtoMFAEnrollment` is enough (e.g. `git grep "\.totpInfo" -- FirebaseAuth/Sources/Swift`. https://github.com/firebase/firebase-ios-sdk/blob/ed4269b40ceb932f82132032722fa2f6fd91c0d1/FirebaseAuth/Sources/Swift/Backend/RPC/Proto/AuthProtoMFAEnrollment.swift#L19
---
```console
nickcooke@nickcooke-mac firebase-3 % git grep "\.totpInfo" -- FirebaseAuth/Sources/Swift
FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift:          } else if let _ = enrollment.totpInfo {
FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift:        } else if enrollment.totpInfo != nil {
```
=> [Auth] Forward secure coding calls for TOTPMultiFactorInfo

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Backend/RPC/Proto/AuthProtoMFAEnrollment.swift, FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPMultiFactorInfo.swift, FirebaseAuth/Tests/Unit/UserTests.swift
#no-changelog
will move cocoapods tags upon merge
=> [Release] Cherry-pick #13592 into `release-11.2`

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/FunctionCalling.swift, FirebaseVertexAI/Sources/ModelContent.swift, FirebaseVertexAI/Tests/Unit/ModelContentTests.swift
Added decoding support for `ModelContent.Part.functionResponse`. Although `FunctionResponse` parts are never returned from the backend, `Decodable` conformance allows this type to be serialized/deserialized from disk. See #13593 for an example use case.
#no-changelog
=> [Vertex AI] Add `Decodable` conformance for `FunctionResponse`

FirebaseAuth/Tests/Unit/AuthBackendRPCImplentationTests.swift, FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift
This pattern should hopefully reduce testing flakes such as this: https://github.com/firebase/firebase-ios-sdk/actions/runs/10770066986/job/29862664996
Comments throughout to document approach.
#no-changelog
=> [Infra] Reduce test flakes due to async variable assignment

.github/workflows/notice_generation.yml
=> [Infra] Update notice_generation.yml

FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Utility/Extensions.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AccountLinkingViewController.swift
Manually tested and confirmed the following:
- link account with SiwA successful
- unlink account with SiwA will also revoke SiwA token and remove the app from your Apple ID dashboard (new for this PR)
#no-changelog
=> [Auth] Revoke SiwA token when unlinking Apple provider

FirebaseCore/Tests/SwiftUnit/FirebaseAppTests.swift
=> [Infra] Fix Swift 6 warning in FirebaseAppTests.swift

FirebaseRemoteConfig/Tests/Swift/FakeUtils/URLSessionPartialMock.swift
=> [Infra] Address Sendable warnings in RC's URLSessionPartialMock.swift

FirebaseAuth/Tests/Unit/SwiftAPI.swift
=> [Infra] Fix warning in Auth's 'SwiftAPI.swift' tests

FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Silenced the followed warning on on `extension SafetyRating: Comparable`:
> Extension declares a conformance of imported type 'SafetyRating' to imported protocol 'Comparable'; this will not behave correctly if the owners of 'FirebaseVertexAI' introduce this conformance in the future
`SafetyRating` does not have a natural ordering because its property `let category: SafetySetting.HarmCategory` does not (e.g., `dangerousContent` can't be compared as being greater than or equal to `harassment`): https://github.com/firebase/firebase-ios-sdk/blob/9e537325bf36a7c053154b685134a8bf99542c11/FirebaseVertexAI/Sources/Safety.swift#L84-L102
For this reason, it is reasonable to assume that we will not add `Comparable` conformance to `SafetyRating` in the SDK and the warning can be ignored with …
=> [Vertex AI] Silence `SafetyRating: Comparable` warning in tests

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/SystemService/AuthStoredUserManager.swift
Address https://github.com/firebase/firebase-ios-sdk/pull/11109/files#r1759803212
I wasn't able to mirror exact behavior when repro'ing #13584, but I think this should address it.
=> [Auth] Query with `kSecAttrSynchronizable` when auth sharing enabled

FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
Follow-up to https://github.com/firebase/firebase-ios-sdk/pull/13521 that may solve an issue reported after rolling out that fix: https://github.com/firebase/firebase-ios-sdk/issues/13480#issuecomment-2351567621
=> [Auth] Await header value from underlying queue

scripts/check_copyright.sh
Since they have a gRPC Authors copyright
=> Skip copyright check for data-connect ProtoGen files

FirebaseInAppMessaging/Sources/Analytics/FIRIAMClearcutUploader.m, Firestore/core/src/immutable/keys_view.h, Firestore/core/src/util/filesystem_posix.cc, Firestore/core/src/util/hashing.h, scripts/setup_check.sh, scripts/style.sh
Upgrade `clang-format` to v19 since v18 is no longer available on Homebrew.
#no-changelog
=> [Infra] Upgrade to `clang-format@19`

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift, FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift
Follow-up to #13647 to further attempt to fix #13650.
The crash reports from #13650 show [`swift_unknownObjectRetain`](https://github.com/swiftlang/swift/blob/4e32b60e9e29eaf75f7facbc514a280d5e637a05/stdlib/public/runtime/SwiftObject.mm#L596-L602) as the last frame in the terminating thread.
Using a symbolic breakpoint, I verified that `swift_unknownObjectRetain` gets called to get the `rpcIssuer` used below:
https://github.com/firebase/firebase-ios-sdk/blob/b5e2c182c83db543829f2a712f5cff7e6ad1ce1e/FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift#L274-L275
Stepping through the assembly from `swift_unknownObjectRetain`, the `objc_retain` is returned from its [source](https://github.com/swiftlang/swift/blob/4e32b60e9e29eaf75f7facbc514a280d5e637a05/stdlib/public/runtime/SwiftObject.mm#L59 …
=> [Auth] Use native Swift types in Auth backend types

Package.swift
Expose FirebaseCore via SPM primarily for internal dependents like Data Connect, but also available for external clients - for direct `import` access for FirebaseApp APIs.
=> Expose FirebaseCore via SPM

FirebaseAuth/Sources/Swift/SystemService/AuthStoredUserManager.swift
This should be covered in the changelog for entry for the previous PR that added back the missing key.
Addressing the second case described in https://github.com/firebase/firebase-ios-sdk/issues/13584#issuecomment-2352608025:
> There is another case I'm still investigating where a user (again with auth configured with a keychain access group and shareAuthStateAcrossDevices == true) is stored on 11.0, 11.1, or 11.2 and missing that key. In this case, such entries will not be read properly when 11.3 adds back the missing key (basically, the same problem you reported but from the upgrade path 11.0/ 11.1/11.2 -> 11.3 (fixed) rather than from 10.x -> 11.0/ 11.1/11.2). I'll leave this issue open until I have a fix for this case also staged in 11.3.
This was tricky enough where I thought it …
=> [Auth] Handle corrupt keychain value resulting from incomplete v11 port

FirebaseVertexAI/Sources/Safety.swift
Removed the `SafetyFeedback` struct from the Vertex AI SDK since it isn't used anywhere. This also means that `SafetyRating.HarmProbability`, `SafetySetting` and `SafetySetting.BlockThreshold` and no longer need to be `Codable` since they are exclusively used for request (`Encodable`) or response (`Decodable`) types.
#no-changelog
=> [Vertex AI] Remove `SafetyFeedback` struct

FirebaseVertexAI/Sources/Safety.swift
Removed the extraneous `public init(from decoder: Decoder) throws` implementation from `SafetySetting.BlockThreshold`. This type is now `Encodable`-only as of https://github.com/firebase/firebase-ios-sdk/pull/13666 since it is only used in requests.
Removed extraneous cases `unknown` and `unspecified` from the `BlockThreshold` enum. Considering this non-breaking since any requests using `unknown` or `unspecified` will results in errors from the backend.
#no-changelog
=> [Vertex AI] Cleanup Decodable impl from BlockThreshold

FirebaseCore/Sources/FIRApp.m
This PR adds support for SDKs outside of the firebase-ios-sdk repo to register with core. Like how the Swift SDKs inside of the firebase-ios-sdk repo are registered, it relies on hardcoding information about the SDK in core.
To support SDKs that may have a version different from core, they have the option of implementing the `func sdkVersion() -> String` method.
For example, the below code belongs to the `Foo` package that lives outside of the firebease-ios-sdk repo. If the below code is included in the Foo SDK, and the client depends on both Foo and the firebase-ios-sdk packages, Foo will register itself with core.
```swift
// Foo.swift
// Inside of the `Foo` package
@objc(FIRFooComponent) class FirebaseFooComponent: NSObject {
@objc static func sdkVersion() -> String {
return "12.0.0" …
```
=> [Core] Add ability to load version from product SDK

FirebaseAuth/Sources/Swift/Backend/AuthRequestConfiguration.swift, FirebaseAuth/Sources/Swift/Backend/RPC/DeleteAccountResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/EmailLinkSignInResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/GetAccountInfoResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SetAccountInfoResponse.swift, FirebaseAuth/Sources/Swift/SystemService/AuthAPNSToken.swift, FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift, FirebaseAuth/Sources/Swift/SystemService/AuthAppCredential.swift, FirebaseAuth/Sources/Swift/SystemService/AuthAppCredentialManager.swift, FirebaseAuth/Sources/Swift/SystemService/AuthNotificationManager.swift, FirebaseAuth/Sources/Swift/Utilities/AuthErrorUtils.swift, FirebaseAuth/Sources/Swift/Utilities/AuthWebUtils.swift
Reviewing checklist:
Changed type should not have...
- open access
- public access
- NSSecureCoding availability
#no-changelog
=> [Auth] Move applicable non-public types away from subclassing NSObject

.github/workflows/abtesting.yml, .github/workflows/appdistribution.yml, .github/workflows/auth.yml, .github/workflows/core.yml, .github/workflows/core_internal.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/dynamiclinks.yml, .github/workflows/firebase_app_check.yml, .github/workflows/functions.yml, .github/workflows/inappmessaging.yml, .github/workflows/installations.yml, .github/workflows/messaging.yml, .github/workflows/mlmodeldownloader.yml, .github/workflows/performance.yml, .github/workflows/remoteconfig.yml, .github/workflows/sessions.yml, .github/workflows/shared-swift.yml, .github/workflows/storage.yml, .github/workflows/vertexai.yml
=> [Infra] Limit concurrent matrix jobs in 'spm' jobs

.github/workflows/vertexai.yml
This resolves a failure that occurs when multiple jobs resolve Package.swift in parallel or in quick successful (the binary downloads fail). This PR uses `actions/cache/save` and `actions/cache/restore` to cache the `swift package resolve` steps where binary artifacts are downloaded. This also re-enables running the matrix platforms for `spm-unit` in parallel.
#no-changelog
=> [Vertex AI] Use `actions/cache` in workflow

ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
Removed the `FirebaseVertexAI` pod from `FirebaseManifest`.
Context: Won't be included in the next zip release. Will re-add in the future.
#no-changelog
=> [Vertex AI] Remove pod from `FirebaseManifest`

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sample/ChatSample/Views/ErrorDetailsView.swift, FirebaseVertexAI/Sources/Safety.swift
- Removed the `unspecified` case from `HarmCategory` since it should never be returned by the backend and should never be provided in a request.
- The `unknown` case would cover this anomalous scenario if it ever occurred.
- Moved the `HarmCategory` enum out of `SafetySetting` since it is also used in `SafetyRating`.
=> [Vertex AI] Refactor `HarmCategory` enum

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/Safety.swift
Renamed the `BlockThreshold` enum in `SafetySetting` to `HarmBlockThreshold` to match the other SDKs and protos.
=> [Vertex AI] Rename `BlockThreshold` to `HarmBlockThreshold`

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sample/ChatSample/Views/ErrorDetailsView.swift, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Sources/Safety.swift
Removed the `unspecified` enum cases from `FinishReason`, `PromptFeedback` and `HarmProbability`. These should never be returned from the backend but, if ever, would be handled by the `unknown` case.
=> [Vertex AI] Remove `unspecified` enum cases from response types

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift, FirebaseVertexAI/Sources/Chat.swift, FirebaseVertexAI/Sources/ModelContent.swift, FirebaseVertexAI/Sources/PartsRepresentable+Image.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift, FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
Renamed the `Part` enum case from `data` to `inlineData` to align with the other SDKs.
=> [Vertex AI] Rename `Part` enum case `data` to `inlineData`

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Renamed `CitationMetadata.citationSources` to `CitationMetadata.citations` to match other platforms.
=> [Vertex AI] Rename `citationSources` to `citations`

.github/workflows/firestore.yml
The Firestore status check should only be required on Firestore PRs.
Relevant docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
AC (to be tested post-merge): 
#no-changelog
=> [Infra] Require firestore status check only if firestore code changes

FirebaseAuth/Sources/Swift/Utilities/AuthWebViewController.swift
Manually tested via macCatalyst (see below comment as to why) and confirmed that delegate gets triggered in both a macCatalyst app built with Xcode 15 and an app built with Xcode 16.
Fix #13507
This appears to avoif the `#if`s needed in this [workaround](https://github.com/swiftlang/swift/issues/74904#issuecomment-2289909804). 
#no-changelog
=> [Infra] Fix warning in Auth's AuthWebViewController.swift

FirebaseRemoteConfig/Sources/Private/RCNConfigFetch.h, FirebaseRemoteConfig/Sources/RCNConfigFetch.m
#no-changelog
- WARN  | [iOS] xcodebuild:  /Users/runner/work/firebase-ios-sdk/firebase-ios-sdk/FirebaseRemoteConfig/Sources/FIRRemoteConfig.m:255:3: warning: Null passed to a callee that requires a non-null 2nd parameter [nullability.NullPassedToNonnull]
=> RC: fix internal API nullability issue caught by analyzer

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Utilities/AuthURLPresenter.swift
I figured how to easily reproduce #13645:
1. Launch app on iOS simulator
2. Navigate to the phone number view controller and enter a phone #, tap **Send Verification Code**
3. The reCaptcha flow should start. Dismiss the presented controller by tapping **Done** in top left or swiping down
4. An error should be propagated to indicate the user cancelled action. On Firebase 10.29.0, the error will be caught and displayed. On 11.2.0, nothing happens. 
This PR fixes the issue and the error propagates.
Compared to v10 implementation, the v11 implementation was missing **line 130**.
https://github.com/firebase/firebase-ios-sdk/blob/eca84fd638116dd6adb633b5a3f31cc7befcbb7d/FirebaseAuth/Sources/Utilities/FIRAuthURLPresenter.m#L127-L137
Fix #13645
=> [Auth] nil out SafariViewController when presentation finishes

FirebaseAuth/Sources/Swift/Utilities/AuthWebViewController.swift
While testing #13634, found one behavior regression that led to reCATPCHA not working on macCatalyst.
Steps to repro:
1. Build Auth sample for macCatalyst (requires some disabling of code to get build green, and enabling Catalyst support)
2. Phone number flow, add phone #, verify
3. A blank screen will be presented
With this PR, the reCAPTCHA flow will be presented instead of a blank screen.
In v10, `allow` was always returned:
https://github.com/firebase/firebase-ios-sdk/blob/eca84fd638116dd6adb633b5a3f31cc7befcbb7d/FirebaseAuth/Sources/Utilities/FIRAuthWebViewController.m#L87
=> [Auth] Match Firebase 10 implementation in WKNavigationDelegate conformance

FirebaseAuth.podspec, FirebaseAuth/Tests/Unit/SwiftAPI.swift
#13634 addressed the warning so we should be able to go back to building with `-warnings-as-errors`.
Fix #13704 
#no-changelog
=> [Infra] Switch back to building Auth with `-warnings-as-errors`

Firestore/CHANGELOG.md, Firestore/Example/Firestore.xcodeproj/project.pbxproj, Firestore/core/src/local/globals_cache.h, Firestore/core/src/local/leveldb_globals_cache.cc, Firestore/core/src/local/leveldb_globals_cache.h, Firestore/core/src/local/leveldb_key.cc, Firestore/core/src/local/leveldb_key.h, Firestore/core/src/local/leveldb_persistence.cc, Firestore/core/src/local/leveldb_persistence.h, Firestore/core/src/local/memory_globals_cache.cc, Firestore/core/src/local/memory_globals_cache.h, Firestore/core/src/local/memory_persistence.cc, Firestore/core/src/local/memory_persistence.h, Firestore/core/src/local/persistence.h, Firestore/core/test/unit/local/globals_cache_test.cc, Firestore/core/test/unit/local/globals_cache_test.h, Firestore/core/test/unit/local/leveldb_globals_cache_test.cc, Firestore/core/test/unit/local/memory_globals_cache_test.cc
Internal change to Firestore.
Prepare persistence of session token. This will be used in future work to support database name resuse.
=> SessionToken persistence implementation

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/CountTokensRequest.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Made the `totalBillableCharacters` property of `CountTokensResponse` an optional value (`Int?`) since it's not always populated.
=> [Vertex AI] Optional `CountTokensResponse.totalBillableCharacters`

FirebaseVertexAI/Sources/Constants.swift, FirebaseVertexAI/Sources/Errors.swift, FirebaseVertexAI/Sources/GenerativeAIRequest.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/VertexLog.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Added a log message to direct developers to the Firebase Console if the Vertex AI in Firebase API is not enabled.
#no-changelog
=> [Vertex AI] Add Firebase Vertex AI API enablement logging

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerativeAIRequest.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Updated the default request timeout to 180 seconds in `RequestOptions`. Previously the platform-defined default for `URLRequest` (60 seconds at the time of writing) was used.
=> [Vertex AI] Set default request timeout to 180 seconds

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerateContentError.swift, FirebaseVertexAI/Sources/PartsRepresentable+Image.swift, FirebaseVertexAI/Tests/Unit/PartsRepresentableTests.swift
Removed the `ImageConversionError` enum from the public API. Devs can continue to handle image conversion errors by looking for the `GenerateContentError.promptImageContentError` case.
=> [Vertex AI] Remove `ImageConversionError` from public API

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Removed the `CountTokensError` enum. Errors are now reported directly instead of being wrapped in `CountTokensError.internalError`.
#no-changelog
=> [Vertex AI] Remove `CountTokensError` enum

FirebaseVertexAI/Sources/GenerativeAIService.swift
- Updated the the log message when `firebasevertexai.googleapis.com` is not enabled to direct developers _solely_ to the Firebase Console.
- ~~In `DEBUG` builds, this situation is now a `fatalError` instead of an error log. This will quickly alert developers to the problem during development.~~
- ~~To avoid crashing released apps, the message remains an error log in release builds.~~
- `fatalError` approach breaks unit tests, always log at the error level.
#no-changelog
=> [Vertex AI] Update log message when API is not enabled

FirebaseAuth.podspec, FirebaseFunctions.podspec, FirebaseStorage.podspec, Package.swift
Fix #13729 
This should be a functional no-op for Firebase since GTMSessionFetcher 4 only restricts iOS version support to a subset of Firebase's.
=> Add compatibility for GTMSessionFetcher 4

FirebaseVertexAI/Sources/VertexAI.swift
Removed the `NSObject` superclass from `VertexAI` since the SDK is available in Swift only.
#no-changelog
=> [Vertex AI] Remove `NSObject` superclass from `VertexAI`

FirebaseVertexAI/Sample/VertexAISample.xcodeproj/project.pbxproj, Package.swift
Renamed the library name from `FirebaseVertexAI-Preview` to just `FirebaseVertexAI` in Package.swift. Updated the sample app to use the new framework name.
#no-changelog
=> [Vertex AI] Remove `-Preview` suffix in SPM library name

.github/workflows/auth.yml
#no-changelog
The latest Facebook SDK release requires Xcode 16 - see https://github.com/facebook/facebook-ios-sdk/issues/2480
=> Update some auth tests to Xcode 16

FirebaseAppDistribution/Sources/FIRFADApiService.m
The only issue I found was in a log message, so it seems backward compatible and safe to merge.
=> Fix all FirebaseAppDistribution typos

FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/SettingsViewController.swift
The enum appears to be unused externally, so it seems reasonable to proceed with the fix. Please let me know if you think otherwise. Thank you!
=> Fix enum case name in the Authentication example

Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m
Seems like these typos are not referenced outside. Please double check and let me know otherwise.
Thanks
=> Fix crashlytics objc test files typos

Crashlytics/Crashlytics/Components/FIRCLSApplication.h, Crashlytics/Crashlytics/Handlers/FIRCLSException.mm
All changes are backward compatible and just in comments
=> Fix crashlytics code docs

FirebaseAuth/Tests/SampleSwift/ObjCApiTests/FIRAuthApiTestsBase.m, FirebaseAuth/Tests/Unit/GetProjectConfigTests.swift, FirebaseAuth/Tests/Unit/RPCBaseTests.swift
All changes are in log messages and comments and backward compatible
=> Enhance FirebaseAuthCode quality

.github/workflows/zip.yml
Fix zip failure #13737 building Auth quickstart related to Facebook dependency. See #13745.
=> Fix zip auth test

scripts/build.sh
The iPhone 16 simulator running iOS 18.0 is currently available on both the [macOS 14](https://github.com/actions/runner-images/blob/22a8b4c4acd38579dd6bd5c2fcb5b7c492161ea7/images/macos/macos-14-arm64-Readme.md?plain=1#L238) and [macOS 15](https://github.com/actions/runner-images/blob/22a8b4c4acd38579dd6bd5c2fcb5b7c492161ea7/images/macos/macos-15-arm64-Readme.md?plain=1#L167) GitHub runner images (when using Xcode 16). 
#no-changelog
=> [Infra] Switch to the iPhone 16 sim on Xcode 16

FirebaseCore/Tests/Unit/FIRAppTest.m
All the changes are comments, but of them was a name of a method which was commented out already. Please double check. 
Thanks
=> Fix FirebaseCore tests comments

FirebaseDatabase/Tests/Unit/FTreeSortedDictionaryTests.m
A minor typo for a local assert comment.
=> Docs: improve comments of the FirebaseDatabase

FirebaseDatabase/Tests/Unit/FSyncPointTests.m
Another typo in a test method that is not referenced anywhere.
=> Fix FirebaseDatabase sync  point test file content

FirebaseDatabase/Tests/Resources/syncPointSpec.json
This was very tiny but the quality matters and Xcode was underling it in red.
=> Fix a little typo in a comment of a json resource

FirebaseCore/Tests/SwiftUnit/FirebaseAppTests.swift
I couldn't find any reference to this function anywhere in the code, so it seems safe to change and merge. Please double check.
Thanks.
=> Fix FirebaseCore swift unit tests function names

FirebaseDatabase/Tests/Unit/FRangeMergeTest.m
The typo was repeated but non of their functions referenced anywhere. Please double check and tell me if anything else should be considered
Thanks
=> Fix FirebaseDatabase integration test files content

FirebaseInAppMessaging/Sources/Analytics/FIRIAMClearcutUploader.m, FirebaseInAppMessaging/Sources/DefaultUI/ImageOnly/FIRIAMImageOnlyViewController.m, FirebaseInAppMessaging/Sources/DefaultUI/Modal/FIRIAMModalViewController.m, FirebaseInAppMessaging/Sources/DefaultUI/README.md
All of these changes are comments and documentations. Please let me know if all can be merged.
Thanks
=> Docs: enhance firebase in app messaging comments

Firestore/CHANGELOG.md, Firestore/Example/Firestore.xcodeproj/project.pbxproj, Firestore/core/src/local/globals_cache.h, Firestore/core/src/local/leveldb_globals_cache.cc, Firestore/core/src/local/leveldb_globals_cache.h, Firestore/core/src/local/leveldb_key.cc, Firestore/core/src/local/leveldb_key.h, Firestore/core/src/local/leveldb_persistence.cc, Firestore/core/src/local/leveldb_persistence.h, Firestore/core/src/local/memory_globals_cache.cc, Firestore/core/src/local/memory_globals_cache.h, Firestore/core/src/local/memory_persistence.cc, Firestore/core/src/local/memory_persistence.h, Firestore/core/src/local/persistence.h, Firestore/core/test/unit/local/globals_cache_test.cc, Firestore/core/test/unit/local/globals_cache_test.h, Firestore/core/test/unit/local/leveldb_globals_cache_test.cc, Firestore/core/test/unit/local/memory_globals_cache_test.cc
=> Reapply "SessionToken persistence implementation (#13684)" (#13719)

FirebasePerformance/Tests/Unit/Configurations/FPRConfigurationsTest.m, FirebasePerformance/Tests/Unit/FPRNetworkTraceTest.m, FirebasePerformance/Tests/Unit/Gauges/FPRGaugeManagerTests.m, FirebasePerformance/Tests/Unit/Instruments/FIRHTTPMetricTests.m, FirebasePerformance/Tests/Unit/Timer/FIRTraceTest.m
These were causing warnings in unit tests
#no-changelog
=> Fix Performance Unit Test Warnings around UserDefaults

FirebaseMessaging/Sources/FIRMessaging+ExtensionHelper.m, FirebaseMessaging/Sources/FIRMessaging.m
=> [Infra] Sync messaging with recent 1P infra changes

FirebaseFunctions/Sources/Functions.swift, FirebaseFunctions/Sources/HTTPSCallable.swift, FirebaseFunctions/Tests/CombineUnit/HTTPSCallableTests.swift, FirebaseFunctions/Tests/Unit/FunctionsTests.swift
* Combined the two nearly identical `Functions.callFunction(…)` methods into one
* Updated `Functions.urlWithName(_:)` to return an actual `URL`; renamed the method to `functionURL(for:)`
* Refactored `HTTPSCallable` to store a function’s actual URL
* Removed `HTTPSCallable.EndpointType`
* Updated tests
=> Refactored Duplicate Methods in `Functions`

FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift, FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift, FirebaseAuth/Tests/Unit/FIROAuthProviderTests.m, FirebaseAuth/Tests/Unit/RPCBaseTests.swift
This PR eliminates the possibility of multiple AuthBackendRPCImplementation instances other than in test code.
It's a possible fix for https://github.com/firebase/firebase-ios-sdk/issues/13761
(Also eliminates an Objective-C unit test that was relying upon the broken old code to succeed on GHA.
=> [Auth] Address possible race condition

FirebaseMessaging/CHANGELOG.md
All changes are in the change log file and safe to merge.
=> Docs: enhance FirebaseMessaging change log

FirebaseMessaging/Tests/UnitTests/FIRMessagingAuthKeychainTest.m
Both properties are function scoped.
=> Test: enhance FirebaseMessaging unit tests

FirebaseInAppMessaging/Sources/Runtime/FIRIAMRuntimeManager.m
It wasn't referenced out side of the file
=> Fix: static constant name in FirebaseInAppMessaging runtimes

FirebaseInAppMessaging/Sources/Flows/FIRIAMMessageClientCache.m, FirebaseInAppMessaging/Sources/Private/Flows/FIRIAMMessageClientCache.h, FirebaseInAppMessaging/Sources/Runtime/FIRIAMRuntimeManager.m, FirebaseInAppMessaging/Tests/Unit/FIRIAMMessageClientCacheTests.m
I tried to cover all references to this property in all source and test files. Please double check so nothing left behind.
Thanks
=> Fix a property name in FirebaseInAppMessaging

FirebaseDatabase/Tests/Integration/FEventTests.m
These two were left behind and are not referenced externally.
=> Fix FirebaseDatabase integration test leftovers

FirebasePerformance/CHANGELOG.md, FirebasePerformance/Sources/Instrumentation/FPRNetworkTrace.m
Paired with @PolinaGo on this issue to resolve it.
Fix #13581
=> Fix a crash related to thread sanitization on variables in FPRNetworkTrace class.

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/CountTokensRequest.swift, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Added `systemInstruction`, `tools` and `generationConfig` to the `CountTokensRequest` [body](https://cloud.google.com/vertex-ai/generative-ai/docs/reference/rest/v1beta1/projects.locations.publishers.models/countTokens#request-body). These fields are now included in the `totalTokens` and `totalBillableCharacters` counts.
=> [Vertex AI] Add sysInstructs, tools, genConfig to `countTokens`

FirebaseVertexAI/Sources/FunctionCalling.swift, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift
Added integration tests for `countTokens` with images (inline base64 and Firebase Storage) and function calling. As a side-effect these tests verify our `Encodable` implementations for these types.
#no-changelog
=> [Vertex AI] Add image / function call count tokens integration tests

FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
All references were locally and updated.
=> Fix: typos of the FirebaseRemoteConfig source code

FirebasePerformance/Tests/Unit/Configurations/FPRRemoteConfigFlagsTest.m
Not referenced from anywhere. Safe to merge.
=> Test: enhance FirebasePerformance Unit tests

FirebasePerformance/Sources/Common/FPRDiagnostics_Private.h
A simple typo in a property documentation. The original referenced type spell was ok.
=> docs: fix common sources comments

FirebasePerformance/Tests/TestApp/Source/ViewControllers/NetworkConnectionViewController.m
Fix some log messages. no backward impacts.
=> Fix: FirebasePerformance TestApp log messages in the source code

FirebasePerformance/Sources/AppActivity/FPRSessionManager+Private.h
A simple typo in the comments referencing a type. The original type spell was correct.
=> Docs: fix app activity comments

FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
>  * Read the contribution guidelines (CONTRIBUTING.md).
>  * If this has been discussed in an issue, make sure to link to the issue here.
>    If not, go file an issue about this **before creating a pull request** to discuss.
Issue: https://github.com/firebase/firebase-ios-sdk/issues/13773 
I did not copy the listeners nor use DispatchQueue.sync to keep the same logic and style of code.
>  * Make sure all existing tests in the repository pass after your change.
>  * If you fixed a bug or added a feature, add a new test to cover your code.
This change solves data-racing issue when listener can be added at same time when it is enumerated in completion handler.
Please …
=> Wrap _listeners access with _realtimeLockQueue in fetchLatestConfig completionHandler

FirebaseCore/Sources/FIROptionsInternal.h, FirebaseFirestoreInternal.podspec, scripts/check_imports.swift
=> Updated podspec for internal FirebaseCore header

.github/workflows/vertexai.yml
Updated the `vertexai` workflow job `sample` to build the app on:
- macOS 13 / Xcode 15.2
- macOS 14 / Xcode 15.4
- macOS 15 / Xcode 16
#no-changelog
=> [Vertex AI] Sample app CI for Xcode 16

Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
The variable name was scoped in the function and doesn't referenced outside
=> Test: enhance Firestore integration tests

.github/workflows/abtesting.yml, .github/workflows/appdistribution.yml, .github/workflows/auth.yml, .github/workflows/core.yml, .github/workflows/core_internal.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/dynamiclinks.yml, .github/workflows/firebase_app_check.yml, .github/workflows/firestore.yml, .github/workflows/functions.yml, .github/workflows/inappmessaging.yml, .github/workflows/installations.yml, .github/workflows/messaging.yml, .github/workflows/mlmodeldownloader.yml, .github/workflows/performance.yml, .github/workflows/remoteconfig.yml, .github/workflows/sessions.yml, .github/workflows/spm.yml, .github/workflows/storage.yml, .github/workflows/vertexai.yml, scripts/build.sh
- Update all spm Xcode 16 jobs to run on macos-15
- Restore visionOS testing
- Xcode 16 pod lib lint test will follow in a later PR
See https://github.com/actions/runner-images/issues/10703
#no-changelog
=> Xcode_16 will soon require macos-15 in GHA

FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatController.swift, FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatStorage.swift, FirebaseCore/Internal/Sources/HeartbeatLogging/_ObjC_HeartbeatController.swift, FirebaseCore/Internal/Tests/Integration/HeartbeatLoggingIntegrationTests.swift, FirebaseCore/Internal/Tests/Unit/HeartbeatControllerTests.swift, FirebaseCore/Internal/Tests/Unit/HeartbeatStorageTests.swift
=> [CoreInternal] Add async flush method

FirebaseVertexAI/Sample/ChatSample/Views/ErrorDetailsView.swift
Replaced the `CustomStringConvertible` extensions on `HarmCategory` and `HarmProbability` in the sample app with custom `displayValue` properties. This fixes the warning `Extension declares a conformance of imported type 'HarmCategory' to imported protocol 'CustomStringConvertible'; this will not behave correctly if the owners of 'FirebaseVertexAI' introduce this conformance in the future`.
As the warning describes, this also allows us to customize the `description` in the SDK by conforming to `CustomStringConvertible` for those types.
#no-changelog
=> [Vertex AI] Replace sample `CustomStringConvertible` extensions

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sample/ChatSample/Views/ErrorDetailsView.swift, FirebaseVertexAI/Sources/Safety.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Replaced the `HarmCategory` enum with a struct to prevent breaking changes when new values are added (since switch statements must be exhaustively checked in Swift). Added support for `HARM_CATEGORY_CIVIC_INTEGRITY`.
#no-changelog
=> [Vertex AI] Use `struct` instead of `enum` for `HarmCategory`

FirebaseCore/Extension/FIRHeartbeatLogger.h, FirebaseCore/Sources/FIRHeartbeatLogger.m, FirebaseCore/Tests/Unit/FIRHeartbeatLoggerTests.m
Successor to #13850 which added async flush method at the CoreInternal level. This PR adds it at the Core level. Next is migrating Auth to use this new API.
#no-changelog
=> [Core] Add async flush method

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sample/ChatSample/Views/ErrorDetailsView.swift, FirebaseVertexAI/Sources/Safety.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Replaced the `SafetyRating.HarmProbability` enum with a struct to prevent breaking changes when new values are added (since switch statements must be exhaustively checked in Swift). This follows the same design pattern as https://github.com/firebase/firebase-ios-sdk/pull/13728 (`HarmCategory`).
#no-changelog
=> [Vertex AI] Use `struct` instead of `enum` for `HarmProbability`

FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift, FirebaseAuth/Tests/Unit/AuthBackendRPCImplementationTests.swift, FirebaseCore/Extension/FIRHeartbeatLogger.h, FirebaseCore/Sources/FIRHeartbeatLogger.m, FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenOperationsTest.m
=> [Auth] Use async flush method to get header value

FirebaseVertexAI/Sources/Protocols/Internal/CodableProtoEnum.swift, FirebaseVertexAI/Sources/Safety.swift
Extracted common Protocol Buffer enum to Swift struct decoding logic into a protocol `DecodableProtoEnum` with default implementations. The implementation pattern and error messages are common across several of these enums.
Updated `HarmCategory` and `HarmProbability` to use the new protocol in this PR and it will simplify migrating `FinishReason` and `BlockReason`.
#no-changelog
=> [Vertex AI] Extract common protobuf enum to struct decoding logic

FirebaseVertexAI/Sources/Protocols/Internal/CodableProtoEnum.swift, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift
Added a protocol `EncodableProtoEnum` similar to `DecodableProtoEnum` (added in https://github.com/firebase/firebase-ios-sdk/pull/13859) that provides a default `Encodable` implementation for Swift structs representing Protobuf enums. Before the default encoding produced invalid JSON for `HarmCategory` (refactored as a struct in https://github.com/firebase/firebase-ios-sdk/pull/13854), e.g.:
```
"category": {
"raw_value": "HARM_CATEGORY_DANGEROUS_CONTENT"
}
```
This PR resolves the nested object with a `raw_value` issue and produces:
```
"category":"HARM_CATEGORY_DANGEROUS_CONTENT"
```
The integration tests have been updated to make use of `SafetySetting` (including `HarmCategory`) to catch encoding issues.
#no-changelog
=> [Vertex AI] Add `EncodableProtoEnum` protocol and fix encoding

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/Safety.swift, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift
Refactored `HarmBlockThreshold` as a struct and added the new `.off` threshold, which turns off the safety filter.
#no-changelog
=> [Vertex AI] Refactor `HarmBlockThreshold` as a struct and add `.off`

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Replaced the `BlockReason` enum with a struct to prevent breaking changes when new values are added (since switch statements must be exhaustively checked in Swift). Added the new values `blocklist` and `prohibitedContent`.
=> [Vertex AI] Refactor `BlockReason` as a `struct` and add new values

FirebaseVertexAI/Sources/FunctionCalling.swift, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift
Replaced the `FunctionCallingConfig.Mode` enum with a struct. This _should_ likely never have been switched over and thus not be a breaking change (omitting changelog entry).
Moved documentation from the `mode` and `allowedFunctionNames` properties to the constructor since the properties are internal.
Used all three modes in the integration test to verify that the backend accepts them. They are no-ops in the `auto` and `none` cases but the backend would reject them if not encoded properly.
#no-changelog
=> [Vertex AI] Refactored `FunctionCallingConfig.Mode` as a `struct`

FirebaseVertexAI/Sources/Types/Public/Schema.swift, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift
Replaced the `StringFormat` and `IntegerFormat` enums in `Schema` with structs. These _should_ likely never have been switched over and thus not be a breaking change (omitting changelog entry). Added an integration test to verify encoding.
#no-changelog
=> [Vertex AI] Refactor `StringFormat` and `IntegerFormat` as structs

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/Constants.swift, FirebaseVertexAI/Sources/Errors.swift, FirebaseVertexAI/Sources/GenerativeAIRequest.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Switch to the new `firebasevertexai.googleapis.com` API. Both new and existing users must perform the [Build with Gemini](https://console.firebase.google.com/project/_/genai/) onboarding flow in the Firebase Console to use the updated API.
Note: If https://console.developers.google.com/apis/api/firebasevertexai.googleapis.com/overview shows Not Found or Permission Denied then the new API is not yet live. Please check back after the Firebase 11.4.0 launch.
=> [Vertex AI] Switch to `firebasevertexai.googleapis.com` API

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift, FirebaseVertexAI/Sources/FunctionCalling.swift, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift
Refactored the function calling APIs to align with the other platforms. Specifically:
- Made the `Tool` initializer internal in favour of a new new type method `functionDeclarations(_:)`.
- Made the `FunctionCallingConfig` initializer and `FunctionCallingConfig.Mode` enum internal in favour of type methods `auto()`, `any(allowedFunctionNames:)` and `none()` that return a `FunctionCallingConfig`.
=> [Vertex AI] Refactor function calling APIs

ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
- Removed the Vertex AI SDK from the zip build (`zip: false`).
- Re-ordered the `FirebaseVertexAI` pod to come after the `Firebase` pod to ensure it is not a dependency.
- Set `releasing: false` so it is not printed in the list when calling `swift run --package-path ReleaseTooling firebase-releaser --publish true --log-only true --git-root <release_dir>`
- The pod could be manually pushed by running `pod trunk push --skip-tests --synchronous   ~/.cocoapods/repos/spec-staging/FirebaseVertexAI/11.4.0/FirebaseVertexAI.podspec.json` if the timing works out.
#no-changelog
=> [Vertex AI] Remove from zip build

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift
Using the Auth sample app, enrolling account with TOTP MFA crashes. With this fix, it does not crash (and enrollment succeeds).
=> [Auth] Fix crash when using TOTP MFA auth

FirebaseFunctions/Sources/Internal/FunctionsContext.swift, FirebaseFunctions/Tests/Unit/ContextProviderTests.swift, SharedTestUtilities/AppCheckFake/FIRAppCheckFake.m
* `FunctionsContextProvider.getContext(options:_:)` calls `AppCheckInterop.getLimitedUseToken(completion:)`, an *optional* protocol method
* When the method is not implemented, its completion handler doesn’t get called
* This closure is responsible for leaving the dispatch group, and when it’s not called, the group waits longer than needed
* This change introduces an explicit check for whether the method is implemented
* It also adds a test which makes sure the method doesn’t exceed the .1s time limit
=> Fixed `DispatchGroup`’s Excessive Wait in `FunctionsContext`

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sample/ChatSample/Views/ErrorDetailsView.swift, FirebaseVertexAI/Sample/ChatSample/Views/ErrorView.swift, FirebaseVertexAI/Sources/Safety.swift, FirebaseVertexAI/Sources/VertexLog.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Added the [`HarmSeverity`](https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/GenerateContentResponse#HarmSeverity) enum and added the properties `probabilityScore`, `severity`, `severityScore` and `blocked` to [`SafetyRating`](https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/GenerateContentResponse#SafetyRating).
=> [Vertex AI] Add `HarmSeverity` enum and `SafetyRating` properties

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/Safety.swift, FirebaseVertexAI/Tests/Integration/IntegrationTests.swift
Added the [`HarmBlockMethod`](https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/SafetySetting#HarmBlockMethod) enum and added the [`method`](https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/SafetySetting) property to `SafetySetting`. Verified encoding when both methods are provided, as well as when `method` is omitted, in the integration test.
Aligned with Android / JS on `method` being optional with no default value (https://github.com/firebase/firebase-android-sdk/pull/6379 and https://github.com/firebase/firebase-js-sdk/pull/8567).
=> [Vertex AI] Add `HarmBlockMethod` enum and `method` property

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Added [`blockReasonMessage`](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/GenerateContentResponse#PromptFeedback) to `PromptFeedback`.
=> [Vertex AI] Add `blockReasonMessage` to `PromptFeedback`

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sample/ChatSample/Views/ErrorDetailsView.swift, FirebaseVertexAI/Sample/ChatSample/Views/ErrorView.swift, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
Renamed `CandidateResponse` to `Candidate` to align with the [Android](https://github.com/firebase/firebase-android-sdk/blob/8869a14aeddfa2da17855938039cac4255fe4d8a/firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Candidate.kt#L29) and [Flutter](https://github.com/firebase/flutterfire/blob/b3822b4db1f982bf2b216d7129c55947201dbb45/packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_api.dart#L281) SDKs.
=> [Vertex AI] Rename `CandidateResponse` to `Candidate`

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerationConfig.swift, FirebaseVertexAI/Tests/Unit/GenerationConfigTests.swift
Added `presencePenalty` and `frequencyPenalty` to `GenerationConfig`.
=> [Vertex AI] Add `presencePenalty` and `frequencyPenalty`

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/Chat.swift, FirebaseVertexAI/Sources/CountTokensRequest.swift, FirebaseVertexAI/Sources/FunctionCalling.swift, FirebaseVertexAI/Sources/GenerateContentError.swift, FirebaseVertexAI/Sources/GenerateContentRequest.swift, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Sources/GenerationConfig.swift, FirebaseVertexAI/Sources/GenerativeAIRequest.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/JSONValue.swift, FirebaseVertexAI/Sources/ModelContent.swift, FirebaseVertexAI/Sources/PartsRepresentable+Image.swift, FirebaseVertexAI/Sources/PartsRepresentable.swift, FirebaseVertexAI/Sources/Safety.swift, FirebaseVertexAI/Sources/Types/Internal/InternalPart.swift, FirebaseVertexAI/Sources/Types/Public/Part.swift, FirebaseVertexAI/Sources/Types/Public/Schema.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/Unit/GenerationConfigTests.swift, FirebaseVertexAI/Tests/Unit/JSONValueTests.swift, FirebaseVertexAI/Tests/Unit/PartTests.swift, FirebaseVertexAI/Tests/Unit/PartsRepresentableTests.swift, FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
Added `@available(iOS 15.0, macOS 12.0, macCatalyst 15.0, tvOS 15.0, watchOS 8.0, *)` annotations to all public types. In some cases, this increases the macOS minimum from 11.0 to 12.0.
=> [Vertex AI] Increase macOS minimum to 12.0

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerateContentResponse.swift, FirebaseVertexAI/Sources/GenerationConfig.swift
Made the `GenerationConfig` properties `internal` to align with the [Android SDK](https://github.com/firebase/firebase-android-sdk/blob/2dd9beb5525a5bcadb436ab118cda11945d4a5d5/firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt#L78-L87) (access levels were already aligned in all other files). Updated the documentation and moved it into the parameters since the properties are no longer `public` (DocC links will not work). This [PDF](https://github.com/user-attachments/files/17405071/GenerationConfig.Docs.pdf) of the generated DocC may be easier to read.
=> [Vertex AI] Make `GenerationConfig` properties internal

FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift, FirebaseVertexAI/Tests/Unit/Snippets/FirebaseAppSnippetsUtil.swift, FirebaseVertexAI/Tests/Unit/Snippets/FunctionCallingSnippets.swift, FirebaseVertexAI/Tests/Unit/Snippets/README.md, FirebaseVertexAI/Tests/Unit/Snippets/StructuredOutputSnippets.swift, FirebaseVertexAI/Tests/Unit/TestUtilities/BundleTestUtil.swift
Switched to using a `GoogleService-Info.plist` file in the snippets "tests". This should be more familiar to anyone used to running the integration tests suite compared to setting environment variables.
- Added a `deleteDefaultAppForSnippets` helper method for common cleanup in during test tear down.
- Added `BundleTestUtil` since we need to access the `Bundle` differently for SPM and CocoaPods.
- Updated the other unit tests to use this to avoid duplicated code.
#no-changelog
=> [Vertex AI] Use `GoogleService-Info.plist` in snippets tests

FirebaseVertexAI/CHANGELOG.md
Added a changelog entry for the Vertex AI in Firebase GA release.
=> [Vertex AI] Add GA changelog entry

FirebaseVertexAI/Tests/Unit/Snippets/ChatSnippets.swift, FirebaseVertexAI/Tests/Unit/Snippets/TextSnippets.swift
Added snippets for `generateContent`, `generateContentStream` in `GenerativeModel` and `sendMessage`, `sendMessageStream` in `Chat`.
#no-changelog
=> [Vertex AI] Add text-only `generateContent` and Chat snippets

FirebaseVertexAI/CHANGELOG.md
- Removed extraneous double GA announcement.
- Removed the note that the "`data` case in the `Part` enum has been renamed to `inlineData`" (it's now `InlineDataPart` and listed below).
- Fixed typo.
=> [Vertex AI] Changelog fixes

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
The crashing frame is on `objc_release_x0` so I'm thinking that that the instance is being over-released.
```
Thread 24 Queue 295: com.google.GoogleConfigService.FIRRemoteConfig (serial) [Crashed]:
0    libobjc.A.dylib                          0x1897da370     objc_release_x0 + 16
1    CoreFoundation                           0x18c495394     __CFBasicHashReplaceValue + 415
2    CoreFoundation                           0x18c493d04     CFDictionarySetValue + 207
3    CFNetwork                                0x18d9409bc     HTTPHeaderDict::setValue(HTTPHeaderKeyMixedValue const&, HTTPHeaderValueMixedValue const&) + 143
4    CFNetwork                                0x18d94082c     HTTPMessage::setHeaderFieldStringValue(__CFString const*, __CFString const*) + 99
5    CFNetwork …
```
=> [Config] Mark two `RCNConfigSettings` properties `atomic`

Firestore/core/test/unit/credentials/firebase_app_check_credentials_provider_test.mm
I haven't found any references to this, but please double-check if possible. Thanks!
=> Firestore: review app check credentials provider tests

Firebase.podspec, FirebaseCore.podspec, FirebaseCore/CHANGELOG.md, FirebaseCore/Extension/FIRHeartbeatLogger.h, FirebaseCoreExtension.podspec
Fixing the issue causing the regression in https://github.com/firebase/flutterfire/issues/13527#issuecomment-2427643680 that was introduced in #13853
=> [CoreExtension] Remove `NS_SWIFT_UNAVAILABLE` attribute that caused breaking change

.github/workflows/database.yml, .github/workflows/remoteconfig.yml, .github/workflows/storage.yml
Fix #13964
This seems to improve the stability of the Storage integration tests and RC watchOS test flakiness.
More investigation is still needed for the RTDB integration tests.
=> Tweaks for flaky tests

FirebaseVertexAI/Tests/TestApp/VertexAITestApp.xcodeproj/project.pbxproj
Reduced the deployment targets from iOS 17.2 / macOS 14.2 to iOS 15.0 / macOS 12.0 to match the SDK.
#no-changelog
=> [Vertex AI] Fix deployment targets for TestApp

FirebaseAuth/Sources/Swift/Auth/AuthDataResult.swift, FirebaseAuth/Sources/Swift/Auth/AuthTokenResult.swift, FirebaseAuth/Sources/Swift/AuthProvider/EmailAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/FacebookAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/GameCenterAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/GitHubAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/GoogleAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/OAuthCredential.swift, FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthCredential.swift, FirebaseAuth/Sources/Swift/AuthProvider/TwitterAuthProvider.swift, FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift, FirebaseAuth/Sources/Swift/SystemService/AuthAppCredential.swift, FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift, FirebaseAuth/Sources/Swift/User/AdditionalUserInfo.swift, FirebaseAuth/Sources/Swift/User/User.swift, FirebaseAuth/Sources/Swift/User/UserInfoImpl.swift, FirebaseAuth/Sources/Swift/User/UserMetadata.swift
The static var does not compile in Swift 6 due to shared mutable state. To
work around, you can use a constant or a computed var. To standardize things,
I chose to go with a constant.
This should not affect how the types conform to NSSecureCoding as a constant
can be used to implement a protocol getter-only property. See
https://stackoverflow.com/a/38281420/9331576
#no-changelog
=> [Auth] Use constants for 'supportsSecureCoding' implementation

FirebaseFunctions/Sources/Internal/FunctionsContext.swift, FirebaseFunctions/Tests/Unit/ContextProviderTests.swift
* Introduced `FunctionsContextProvider.context(options:)`, an async / await version of `getContext(options:_:)`
* Added tests
=> Async `FunctionsContextProvider.context(options:)`

FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, scripts/build.sh
Set the `-parallel-testing-enabled` flag to `NO` in `xcodebuild` for the `vertexai / testapp-integration` tests. The integration tests likely shouldn't run in parallel and the output produced by parallel testing (the default in new Xcode projects) seems to be unsupported by `xcpretty` (https://github.com/xcpretty/xcpretty/issues/295). This fixes the logs, which now show [passing tests](https://github.com/firebase/firebase-ios-sdk/actions/runs/11565777796/job/32193359823?pr=13985#step:7:261).
#no-changelog
=> [Vertex AI] Disable xcodebuild parallel testing

FirebaseFunctions/Sources/Functions.swift, FirebaseFunctions/Sources/HTTPSCallable.swift, FirebaseFunctions/Tests/Unit/FunctionsTests.swift
* Introduced an async / await version of `callFunction` which takes advantage of `FunctionsContextProvider`’s async `context(options:)`
* Refactored `GTMSessionFetcher` setup to minimize code duplication
* Added tests
=> Async Function Calling

FirebaseCore/Extension/FIRAppInternal.h, FirebaseCore/Extension/FIRComponent.h, FirebaseCore/Extension/FIRComponentContainer.h, FirebaseCore/Extension/FIRComponentType.h, FirebaseCore/Extension/FIRHeartbeatLogger.h, FirebaseCore/Extension/FIRLibrary.h, FirebaseCore/Extension/FIRLogger.h, FirebaseCore/Extension/FirebaseCoreInternal.h, Gemfile
A custom module map was too difficult. I couldn't get CocoaPods to respect the custom module map and stopped when I started to spin on things. I switched to guarding the headers against being included twice. It seems promising so far. I also tried with using `#pragma once` but that didn't work because (my guess) is that the problem is _not_ that the _same_ header is being included twice, it's that two different headers with the same content are _both_ being included (once in FirebaseCore and once in FirebaseCoreExtension).
Test cases and their results below:
1.  Below Podfile uses the current state and fails when building docs.
```
platform :ios, '13.0'
source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source …
```
=> [Infra] Only compile core extension headers once

FirebaseAuth/Sources/Swift/Backend/RPC/CreateAuthURIRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/GetOOBConfirmationCodeRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Enroll/FinalizeMFAEnrollmentRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Enroll/StartMFAEnrollmentRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/SignIn/FinalizeMFASignInRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/SignIn/StartMFASignInRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Unenroll/WithdrawMFARequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/RevokeTokenRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SecureTokenRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SetAccountInfoRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/VerifyPhoneNumberRequest.swift, FirebaseAuth/Sources/Swift/Backend/VerifyClientRequest.swift, FirebaseAuth/Sources/Swift/User/UserProfileUpdate.swift, FirebaseAuth/Tests/Unit/SetAccountInfoTests.swift
This should be a no-op. Moving to `private` and `let`s where applicable. I'm working on moving these types to structs and thought this would be a good cleanup opportunity to minimize mutability.
#no-changelog
=> [Auth] Prefer immutable properties and private access level in `*Request` types

FirebaseDatabase/Tests/Helpers/FTestContants.h, FirebaseDatabase/Tests/Integration/FEventTests.m, scripts/run_database_emulator.sh
First time the integration tests have passed on CI in days. I'm not sure if it's luck or the newer emulator. Either way, this should merge.
#no-changelog
=> Update to a more recent rtdb emulator version

Gemfile, Gemfile.lock
This PR worked through integration testing of CocoaPods 1.16.*, finding issues with 1.16.0 and 1.16.1 before settling on 1.16.2
=> CocoaPods 1.16.2

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
Instances are now cached by the the Firebase App `name` and the Vertex AI `location`. Previously Vertex AI instances were re-used if the `location` matched, even if they were intended for different Firebase Apps.
=> [Vertex AI] Fix caching of Vertex AI instances

.github/workflows/spm.yml, Package.swift
I enabled this for CocoaPods a while back and it works pretty well. Incrementally extending this to FirebaseAuth x SPM.
Example of usage:
https://github.com/firebase/firebase-ios-sdk/blob/ae2554220afb03a5d6fc389c28a86061a12c7caa/FirebaseAuth/Sources/Swift/Auth/Auth.swift#L282-L290
#no-changelog
=> [Infra] Disable Auth deprecations warnings in SPM CI

FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/OtherAuthMethodControllers/PasswordlessViewController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExampleUITests/AuthenticationExampleUITests.swift
test to verify email link sent successfully
=> Adding UI Test for Passwordless Flow [fdl deprecation]

Crashlytics/run
Changed argument order since the paths argument should be in the end of the arguments list. This fixes #13965
=> Fixing upload-symbols run script argument order

FirebaseAuth/Sources/Swift/Backend/RPC/VerifyAssertionResponse.swift
Based on some examples I found, it looks like this value should be JSON string. I did a test in playgrounds and it looks like it can be casted to `[String:Sendable]`
#no-changelog
=> [Auth] Fix casting error in Swift 6

FirebaseVertexAI/Sources/Errors.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/Types/Internal/Errors/BackendError.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Renamed the internal type `RPCError` to `BackendError`. Although it is internal, the name appears when printing the error. The name `BackendError` was chosen since the SDK is making JSON-REST over HTTP calls rather than RPCs (at least not directly) and it also differentiates from other HTTP errors not produced by the Vertex AI backend and network errors.
This move and rename is being done separately from functionality changes to make the diffs readable.
#no-changelog
=> [Vertex AI] Renamed `RPCError` to `BackendError`

FirebaseMessaging/CHANGELOG.md, FirebaseMessaging/Sources/Token/FIRMessagingTokenFetchOperation.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenOperationsTest.m
Currently, when token fetch fails, a generic and misleading message like this is shown:
> Invalid fetch response, expected 'token' or 'Error' key
After this PR, the actual failure reason returned from the server will be logged and returned to the client.
This is expected to fix issue #13997.
#no-changelog
=> When token fetch fails, return the failure reason to the client.

FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/AuthProvider/FederatedAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift, FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift, FirebaseAuth/Sources/Swift/MultiFactor/MultiFactorResolver.swift, FirebaseAuth/Sources/Swift/User/User.swift
=> [Docs] Fix DocC warnings in FirebaseAuth

Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h, Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlyticsReport.h
=> [Docs] Fix DocC warnings in FirebaseCrashlytics

Crashlytics/CHANGELOG.md, FirebaseMessaging/CHANGELOG.md, FirebaseRemoteConfig/CHANGELOG.md
Updated `Unreleased` to `11.5.0` in changelog entries in preparation for the next release.
=> [Release] Update `Unreleased` changelog entries for 11.5.0

FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Replaced `NSError` objects that originated from the `generative-ai-swift` SDK (`domain: "com.google.generative-ai"`).
#no-changelog
=> [Vertex AI] Replace legacy errors in `GenerativeAIService`

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/Types/Public/Schema.swift
Removed the `"double"` format hint in `Schema.double()` since it is not enforced by the model. Developers should continue to decode the data produced into `Double` values to avoid losing precision where available.
Additionally, this works around a temporary backend issue where `format` is not accepted for numeric types. `Unable to submit request because one or more response schemas specified incorrect schema type field. For schema with format, schema type should be STRING. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/control-generated-output` (see #13977 for more details).
Note: This PR does not resolve the issue for `float()`; consider using `double()` until #13977 is resolved in the backend.
=> [Vertex AI] Remove `format` for `double()` `Schema`

.github/workflows/health-metrics-presubmit.yml
=> [Infra] Migrate health-metrics-presubmit.yml to actions/upload-artifact@v4

.github/workflows/remoteconfig.yml, FirebaseRemoteConfig/SwiftNew/UserDefaultsManager.swift
=> [Config] Consolidate getters and setters UserDefaultsManager.swift

FirebaseRemoteConfig/SwiftNew/UserDefaultsManager.swift
`objc_sync_enter` shouldn't be used on value types (`[String: UserDefaults]`) because a struct's address is not stable (https://stackoverflow.com/a/70897304/9331576, https://straypixels.net/swift-dictionary-locking/).
I could demonstrate this in a playground using a simplified version of the class:
```swift
import Foundation
class UserDefaultsManager: NSObject {
nonisolated(unsafe) private static var sharedInstanceMap: [String: UserDefaults] = [:]
/// Returns the shared user defaults instance for the given bundle identifier.
///
/// - Parameter bundleIdentifier: The bundle identifier of the app.
/// - Returns: The shared user defaults instance.
static func setValue(_ value: UserDefaults, key: String) -> UserDefaults {
print("enter: \(ObjectIdentifier(Self.sharedInstanceMap as …
```
=> [Config] Prefer NSLock over objc_sync_enter for synchronizing value types

FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift, FirebaseAuth/Sources/Swift/Backend/AuthRPCResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/CreateAuthURIResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/DeleteAccountResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/EmailLinkSignInResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/GetAccountInfoResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/GetOOBConfirmationCodeResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/GetProjectConfigResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/GetRecaptchaConfigResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Enroll/FinalizeMFAEnrollmentResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Enroll/StartMFAEnrollmentResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/SignIn/FinalizeMFASignInResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/SignIn/StartMFASignInResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Unenroll/WithdrawMFAResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/ResetPasswordResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/RevokeTokenResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SecureTokenResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SendVerificationTokenResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SetAccountInfoResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SignInWithGameCenterResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SignUpNewUserResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/VerifyAssertionResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/VerifyCustomTokenResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/VerifyPasswordResponse.swift, FirebaseAuth/Sources/Swift/Backend/RPC/VerifyPhoneNumberResponse.swift, FirebaseAuth/Sources/Swift/Backend/VerifyClientResponse.swift, FirebaseAuth/Tests/Unit/AuthBackendTests.swift
=> [Auth] Migrate setFields behavior to Response initializer

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift
The Vertex AI backend now includes the `responseSchema` (from `GenerationConfig`; see #13813) in token counts. Although there are no SDK changes, I've added a changelog entry to describe the difference.
=> [Vertex AI] Fix `testCountTokens_jsonSchema` integration test

.github/workflows/functions.yml
Updated the `functions` workflow to use `macos-15` for Xcode 16 jobs. Xcode 16.x is no longer available in macos-14 GitHub runner images resulting in [an error](https://github.com/firebase/firebase-ios-sdk/actions/runs/11719824650/job/32662363694#step:4:7) first noticed in #14044.
#no-changelog
=> [Infra] Update functions workflow to use macOS 15 for Xcode 16 jobs

.github/workflows/storage.yml
Updated the `storage` workflow to use `macos-15` for Xcode 16 jobs. Xcode 16.x is no longer available in macos-14 GitHub runner images resulting in [an error](https://github.com/firebase/firebase-ios-sdk/actions/runs/11738278551/job/32700496142#step:6:7) first noticed in #14044.
#no-changelog
=> [Infra] Update storage workflow to use macOS 15 for Xcode 16 jobs

FirebasePerformance/Sources/Instrumentation/UIKit/FPRUIViewControllerInstrument.m
related to: #13067
Using the reference here: https://forums.developer.apple.com/forums/thread/682621
#no-changelog
=> Change deprecated keyWindow to new API

scripts/style.sh
Since the code generator keeps overwriting the formatted code, Peter requested we exempt the generated code folder from style checks.
=> Exempt the Data Connect FriendlyFlix Generated Code from style scripts

.github/workflows/core_extension.yml
Updated the `core_extension ` workflow to use `macos-15` for Xcode 16 jobs. Xcode 16.x is no longer available in macos-14 GitHub runner images resulting in [an error](https://github.com/firebase/firebase-ios-sdk/actions/runs/11740029572/job/32705760729#step:5:7) first noticed in #14044.
#no-changelog
=> [Infra] Update core_extension workflow to use macOS 15 for Xcode 16

.github/workflows/firebase_app_check.yml
=> [Infra] Update firebase_app_check workflow to use macOS 15 for Xcode 16

.github/workflows/database.yml
Updated the `database ` workflow to use `macos-15` for Xcode 16 jobs. Xcode 16.x is no longer available in `macos-14` GitHub runner images resulting in [an error](https://github.com/firebase/firebase-ios-sdk/actions/runs/11740015069/job/32705718110#step:5:7) first noticed in #14044.
#no-changelog
=> [Infra] Update database workflow to use macOS 15 for Xcode 16

.github/workflows/mlmodeldownloader.yml
Updated the `mlmodeldownloader` workflow to use `macos-15` for Xcode 16 jobs. Xcode 16.x is no longer available in `macos-14` GitHub runner images resulting in [an error](https://github.com/firebase/firebase-ios-sdk/actions/runs/11737614583/job/32698694865#step:7:8) first noticed in #14044.
#no-changelog
=> [Infra] Update mlmodeldownloader workflow to use macOS 15 for Xcode 16

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/User/User.swift
The logging out was happening because the `User.init(coder:)` implementation in Firebase 11 was returning nil for cases where it previously hadn't in previous major versions.
Firebase 11 returned nil when any of the following was nil:
https://github.com/firebase/firebase-ios-sdk/blob/4e5fbe892e9e74c68725e54fdde5c28dc0fb60ba/FirebaseAuth/Sources/Swift/User/User.swift#L1706-L1715
But Firebase 10.29.0 returned nil in only 2 cases:
https://github.com/firebase/firebase-ios-sdk/blob/eca84fd638116dd6adb633b5a3f31cc7befcbb7d/FirebaseAuth/Sources/User/FIRUser.m#L360-L362
PR #9046 started encoding an app ID key to the user's archived format and that was first released in 8.11.0, so when updating from < 8.11 to 11+, the user instance would fail decoding with the early exit since the app ID couldn't …
=> [Auth] Restore User decoding to pre-11 behavior

.github/workflows/performance.yml
Updated the `performance` workflow to use `macos-15` for Xcode 16 jobs. Xcode 16.x is no longer available in `macos-14` GitHub runner images resulting in [an error](https://github.com/firebase/firebase-ios-sdk/actions/runs/11737629354/job/32698734516#step:5:7) first noticed in #14044.
#no-changelog
=> [Infra] Update performance workflow to use macOS 15 for Xcode 16

.github/workflows/dynamiclinks.yml
Updated the `dynamiclinks` workflow to use `macos-15` for Xcode 16 jobs. Xcode 16.x is no longer available in `macos-14` GitHub runner images resulting in [an error](https://github.com/firebase/firebase-ios-sdk/actions/runs/11739114135/job/32702977046#step:5:7) first noticed in #14044.
#no-changelog
=> [Infra] Update dynamiclinks workflow to use macOS 15 for Xcode 16

FirebaseAuth/Sources/Swift/User/User.swift
While investigating #14026 I found the following logic inconsistency after a keychain error in `internalGetTokenAsync`. It was potentially signing out when Firebase 10 did not.
I'm not sure how this could cause #14026, but we should keep the logic consistent.
I'm also open to suggestions about a cleaner solution that doesn't require the new flag.
Here's the Firebase 10 version:
```
- (void)internalGetTokenForcingRefresh:(BOOL)forceRefresh
callback:(nonnull FIRAuthTokenCallback)callback {
[_tokenService fetchAccessTokenForcingRefresh:forceRefresh
callback:^(NSString *_Nullable token,
NSError *_Nullable error, BOOL tokenUpdated) {
if (error) {
[self signOutIfTokenIsInvalidWithError:error];
callback(nil, error);
return;
}
if (tokenUpdated) {
if (![self updateKeychain:&error]) {
callback(nil, …
```
=> [auth] Fix logic inconsistency between 10.x and 11.x

.github/workflows/auth.yml
Updated the `quickstart` job in the `auth` workflow to run on `macos-15`. This matches the environment changes in https://github.com/firebase/quickstart-ios/pull/1630. This should resolve the [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/11775396507/job/32795766930#step:6:33) in https://github.com/firebase/firebase-ios-sdk/issues/14044.
#no-changelog
=> [Infra] Run Auth quickstart on macOS 15

FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SendVerificationTokenRequest.swift, FirebaseAuth/Sources/Swift/Utilities/AuthErrorUtils.swift, FirebaseAuth/Sources/Swift/Utilities/AuthRecaptchaVerifier.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/OtherAuthMethodControllers/PhoneAuthViewController.swift, FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift, FirebaseAuth/Tests/Unit/GetRecaptchaConfigTests.swift, FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
This is a patch on main branch based of branch rce-phone-tests.  All reviews has been done previously.  Please emphasis on the merge.
Suggestion: compare the diff with against a diff between rce-phone-tests and main using a pull request.
=> Adding rCE support for phone auth flows.

.github/workflows/shared-swift.yml
Updated the `shared-swift` workflow to use `macos-15` for Xcode 16 jobs. Xcode 16.x is no longer available in `macos-14` GitHub runner images resulting in [an error](https://github.com/firebase/firebase-ios-sdk/actions/runs/11721697510/job/32662428308#step:4:5) first noticed in #14044.
#no-changelog
=> [Infra] Update shared-swift workflow to use macOS 15 for Xcode 16

.github/workflows/messaging.yml
Updated the `messaging` workflow to use `macos-15` for Xcode 16 jobs. Previously `pod-lib-lint` was skipping the Xcode 16 tests because of the multi-`matrix` + `include` approach (they should have been failing since Xcode 16 is no longer available in the `macos-14` runner images).
#no-changelog
=> [Infra] Update messaging workflow to use macOS 15 for Xcode 16

.github/workflows/firestore.yml, FirebaseCore/Sources/Public/FirebaseCore/FIRTimestamp.h
Timestamp is an immutable class with no mutable state.
#no-changelog
=> [Core] Make Timestamp Sendable

.github/workflows/zip.yml, scripts/zip_quickstart_test.sh
Updated the zip workflow to use `macos-15` for Xcode 16 jobs. Xcode 16.x is no longer available in macos-14 GitHub runner images resulting in [an error](https://github.com/firebase/firebase-ios-sdk/actions/runs/11716343768/job/32676678150#step:7:10) first noticed in #14044.
#no-changelog
=> [Infra] Update zip workflow to use macOS 15 for Xcode 16 jobs

FirebaseAuth/Sources/Swift/AuthProvider/AuthCredential.swift, FirebaseAuth/Sources/Swift/AuthProvider/EmailAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/FacebookAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/GameCenterAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/GitHubAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/GoogleAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/OAuthCredential.swift, FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthCredential.swift, FirebaseAuth/Sources/Swift/AuthProvider/TwitterAuthProvider.swift, FirebaseAuth/Sources/Swift/Utilities/AuthRecaptchaVerifier.swift
These classes have no mutable state so they should meet the semantic requirements of Sendable. In Firebase 12, we should refactor to _checked_  Sendable. We can't currently do so without a breaking change because of the fact that the classes are `open` (Sendable classes may not be `open`).
Resolves:
Because the APIs return the `AuthCredential` superclass, `AuthCredential` needs to be marked unchecked Sendable. All of it's subclasses need to then be marked unchecked Sendable or a warning will occur that the sendability of the superclass means the subclass should also explicitly mark itself as unchecked Sendable.
I added some API improvement ideas to the Firebase 12 gdoc.
#no-changelog
=> [Auth] Mark *Credential classes as Sendable

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json, ReleaseTooling/CarthageJSON/FirebaseVertexAIBinary.json
Updated the Carthage artifacts for the M156 / https://github.com/firebase/firebase-ios-sdk/releases/tag/11.5.0.
#no-changelog
=> [Release] Carthage updates for M156 / 11.5.0

FirebaseAuth/Sources/Swift/Backend/IdentityToolkitRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SecureTokenRequest.swift
These fixes address global mutable state errors. These are mutable so the Auth sample app can toggle between different hosts. I've so far tried to avoid using `nonisolated(unsafe)`, but I couldn't find a simpler way to address them for now.
If we introduce any global actors, we can synchronize them on a global actor. Until there is a need for that though, I feel it's fine to ignore the warnings via this PR.
#no-changelog
=> [Auth] Ignore concurrency warnings for global vars made for testing

.github/workflows/zip.yml
We reverted back to using the much slower `macos-13` runner images in https://github.com/firebase/firebase-ios-sdk/pull/13562 because of frequent failures due to running out of disk space. This may no longer be an issue now that GitHub has limited `macos-14` runners to Xcode 15.x. Testing on CI.
#no-changelog
=> [Infra] Use macos-14 for the zip build

FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift, FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift, FirebaseAuth/Sources/Swift/User/User.swift, FirebaseAuth/Sources/Swift/User/UserProfileChangeRequest.swift
I unintentionally pushed to main (wasn't on a local branch). Usually, it stops me. I didn't force push but I saw `remote: Bypassed rule violations for refs/heads/main:`.
#no-changelog
=> [Auth] Revert unintentional commits on main

FirebaseAuth/Sources/Swift/Utilities/AuthDefaultUIDelegate.swift
Method's Implementation uses a lot of main actor isolated APIs, so I think it makes sense to isolate the entire method on the main actor.
The caller of this API is in a DispatchQueue.main.async {} which is isolated on the main actor so no call sites need to change. 
Other no-op changes were to make the class final and switch the method from a class method to a static method.
#no-changelog
=> [Auth] Synchronize static method of AuthDefaultUIDelegate on main actor

FirebaseCombineSwift.podspec, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift, ReleaseTooling/Sources/FirebaseManifest/Pod.swift, ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
Added the `FirebaseCombineSwift` pod to the `FirebaseManifest` but specified as `releasing: false, zip: false`. Updated the `Pod` initializer to store `podVersion` if specified (previously ignored) and updated `Manifest.versionString(_:)` to use the `podVersion` (was intended for including `FirebaseAuthTestingSupport` and `FirebaseFirestoreTestingSupport` in the Manifest but not needed).
Note: The `combine` workflow is currently [failing](https://github.com/firebase/firebase-ios-sdk/actions/runs/11812265595/job/32907175474#step:7:88) (https://github.com/firebase/firebase-ios-sdk/issues/14106) because the release tooling did not update its dependency on `FirebaseCore` to the new version in https://github.com/firebase/firebase-ios-sdk/pull/14104 and the version requirements are now …
=> [Release] Add `FirebaseCombineSwift` to `FirebaseManifest`

FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/Auth/AuthDispatcher.swift, FirebaseAuth/Tests/Unit/AuthDispatcherTests.swift, FirebaseAuth/Tests/Unit/AuthTests.swift
Shared singleton is problematic in Swift 6.
#no-changelog
=> [Auth] Remove AuthDispatcher singleton, prefer DI

.github/workflows/api_diff_report.yml, .github/workflows/firestore.yml
Updated the `API Diff Report` and `firestore` workflows to use Python 3.11 instead of 3.10. Python 3.10 will be removed from GitHub runner images on 2024-11-18: https://github.com/actions/runner-images/issues/10812
#no-changelog
=> [Infra] Update workflows from Python 3.10 to 3.11

.github/workflows/cocoapods-integration.yml, .github/workflows/notice_generation.yml, .github/workflows/release.yml, ReleaseTooling/Sources/ManifestParser/GHAMatrixSpecCollector.swift, ReleaseTooling/Sources/ManifestParser/main.swift
Attempting to exclude `FirebaseCombineSwift.podspec` in `GHAMatrixSpecCollector` to resolve an [error](https://github.com/firebase/firebase-ios-sdk/actions/runs/11831032339/job/32992295914) in https://github.com/firebase/firebase-ios-sdk/issues/14106. Added workflow_dispatch options in multiple workflows to allow them to be trigger manually from https://github.com/firebase/firebase-ios-sdk/actions.
#no-changelog
=> [Infra] Exclude pods that aren't releasing in GHAMatrixSpecCollector

FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift, FirebaseAuth/Sources/Swift/Backend/AuthBackendRPCIssuer.swift, FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift
Addresses a couple places where AuthBackend is being sent across concurrency domains. The class is immutable and should be ok to mark Sendable. It does have a dependency on GTMSessionFetcher so preconcurrency imports are being used for those imports to suppress warnings that those type are not sendable.
e.g. `Sending 'backend' risks causing data races`
#no-changelog
=> [Auth] Make AuthBackend and related types Sendable

.github/workflows/prerelease.yml, .github/workflows/release.yml
#no-changelog
Fixes #14127
Same approach as in #13745
=> [Infra] Run Auth QS with Xcode 16 to resolve Facebook SDK breaking change

FirebaseAuth/Tests/SampleSwift/AuthenticationExample/CustomViews/MFALoginView.swift
Fixes crash on when `dismiss()` is called. UI actions need to happen on the MainActor.
#no-changelog
=> [Auth] Perform view dismiss on MainActor

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Auth/Auth.swift
In 10.x, the ivar _currentUser was not synchronized and use within the implementation. With this PR, the new ivar should be managed just like in 10.x. The public var is now synchronized. Note, if you search for `currentUser {` in 10.29, you can see that the synchronized current user is not used anywhere within the implementation: https://github.com/firebase/firebase-ios-sdk/blob/10.29.0/FirebaseAuth/Sources/Auth/FIRAuth.m
Fix for some scenarios in #13231 → https://github.com/firebase/firebase-ios-sdk/issues/13231#issuecomment-2356432490. Still investigating other cases.
=> [Auth] Get 'currentUser' on Auth worker queue

FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/Auth/AuthComponent.swift
Related to #14141. Breaking this into its own PR for easier review.
Fix for some scenarios in #13231 that are related to upgrading to 11.x and prewarming.
=> [Auth] Schedule keychain access after prewarming

FirebaseRemoteConfig/Tests/Swift/README.md
Commit 1674a6b9b43387b7d2044d08868a33e2d7e76d20 moved bunch of `FirebaseRemoteConfig` files. This PR adjusts sources to changes.
=> Update `FirebaseRemoteConfig` references

.github/workflows/performance.yml, scripts/build.sh
Related to #11903
#no-changelog
=> [Infra] Migrate away from macos-12 in performance.yml

FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift, FirebaseAuth/Sources/Swift/Backend/AuthRequestConfiguration.swift
`AuthRequestConfiguration` will eventually need to be Sendable. Gradually addressing the low hanging fruit based on its usage.
#no-changelog
=> [Auth] Mark AuthRequestConfiguration as final and reduce its mutability

FirebaseAuth/Tests/Unit/GetRecaptchaConfigTests.swift, FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
=> resolve merge conflict when rce-main rebase from main

.github/workflows/performance.yml, FirebasePerformance/Tests/Unit/Timer/FPRCounterListTest.m, scripts/build.sh
When `xcodebuild test` fails due to a crash ([example](https://github.com/firebase/firebase-ios-sdk/actions/runs/11862154195/job/33061011258?pr=14131#step:6:893)), instead of a typical test failure, the exit code is `0` (success). These show up as passing in our CI jobs. Added a regex check to detect this scenario.
#no-changelog
=> [Infra] Add check for unexpected test failures in build.sh

.github/workflows/inappmessaging.yml
Trying the FIAM tests job on macos-13 since Xcode 14.x is still available there.
#no-changelog
=> [Infra] Use macos-13 + Xcode 14 in inappmessaging workflow

FirebaseAuth/Sources/Swift/Storage/AuthUserDefaults.swift, FirebaseAuth/Sources/Swift/SystemService/AuthStoredUserManager.swift, FirebaseAuth/Tests/Unit/AuthUserDefaultsTests.swift
Methods don't throw, so remove the `throws` keyword.
#no-changelog
=> [Auth] Remove unnecessary throws on internal methods

FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
=> fix Audit mode fallback failure

Firestore/CHANGELOG.md, Firestore/Swift/Source/Codable/ServerTimestamp.swift
=> [Firestore] Add conditonal Sendability conformance to ServerTimestamp

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/User/UserInfoImpl.swift
The class names was changed from `FIRUserInfoImpl` to `UserInfoImpl`, but the unarchiving older copies (pre name change) requires knowing the original ObjC name. The rest of the direct/transitive types from the `User` class's `init?(coder:)` look okay.
We actually do this for other classes, I just had to make the connection that the class wasn't being decoded because the pre-11 archive didn't have a blob mapping to "UserInfoImpl". The blob was mapping to "FIRUserInfoImpl".
https://github.com/firebase/firebase-ios-sdk/blob/700fd6803d50275be326c356b400704f2ea8b481/FirebaseAuth/Sources/Swift/SystemService/AuthAppCredential.swift#L18-L19
Fix #14011
=> [Auth] Add objc attribute to UserInfoImpl so legacy decoding works

FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
=> Update PhoneAuthProvider.swift addressing comments

.github/workflows/firestore.yml
Prevent PRs like https://github.com/firebase/firebase-ios-sdk/pull/14173 from being subject to the firestore required check. This will need to be checked in to test.
#no-changelog
=> [Infra] Don't require firestore check on docs changed

FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift, FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Enroll/StartMFAEnrollmentRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/SignIn/StartMFASignInRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/Proto/Phone/AuthProtoStartMFAPhoneRequestInfo.swift, FirebaseAuth/Sources/Swift/Backend/RPC/SendVerificationTokenRequest.swift, FirebaseAuth/Sources/Swift/Utilities/AuthErrorUtils.swift, FirebaseAuth/Sources/Swift/Utilities/AuthRecaptchaVerifier.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/OtherAuthMethodControllers/PhoneAuthViewController.swift, FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift, FirebaseAuth/Tests/Unit/GetRecaptchaConfigTests.swift, FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift, FirebaseAuth/Tests/Unit/RPCBaseTests.swift, FirebaseAuth/Tests/Unit/StartMFASignInRequestTests.swift
#no-changelog
Added reCAPTCHA enterprise support for phone sign in and SMS as second factor sign in and enrollment flows.
changes log PR has been raised directly to main to avoid merging conflicts https://github.com/firebase/firebase-ios-sdk/pull/14171
=> reCAPTCHA enterprise support on phone auth and phone MFA

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/User/UserInfoImpl.swift
Address https://github.com/firebase/firebase-ios-sdk/issues/14011#issuecomment-2500281393
If a `UserInfoImpl` instance fails to decode, the entire `[String: UserInfoImpl]` collection (below snippet) will fail to decode, which will make the `user.providerData` property `nil`.
https://github.com/firebase/firebase-ios-sdk/blob/2176e99cc68856131241e584c1a1f22668c846e3/FirebaseAuth/Sources/Swift/User/User.swift#L1736-L1737
The below snippet is the `GetAccountInfoResponseProviderUserInfo` response object for an account with email and phone providers enabled. The `phone` provider does not have a `federatedID` and therefore its corresponding `UserInfoImpl` instance does not have a `uid`.  It's possible a more useful default could be given, but will have to further investigate this. cc: …
=> [Auth] Add default values for decoding nil properties in UserInfoImpl

FirebaseVertexAI/Sources/Types/Internal/Imagen/ImageGenerationInstance.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImageGenerationInstanceTests.swift
Added an encodable type `ImageGenerationInstance` that is passed in `instances[]` in a [`predict`](https://cloud.google.com/vertex-ai/generative-ai/docs/reference/rest/v1/projects.locations.publishers.models/predict#request-body) request. The schema ([download](https://storage.mtls.cloud.google.com/google-cloud-aiplatform/schema/predict/instance/vision_generative_model_1.0.0.yaml)) supports other fields, such as `image` and `mask`, but we are only using `prompt` at this time.
<details>
<summary>VisionGenerativeModel Instance Schema Reference</summary>
```
title: VisionGenerativeModel
type: object
required:
- prompt
properties:
prompt:
type: string
description: >
The text prompt for guiding how vision model generate the images.
This field is required for both generation and editing.
image: …
```
=> [Vertex AI] Add ImageGenerationInstance for input to predict call

FirebaseVertexAI/Sources/Types/Internal/Imagen/ImageGenerationOutputOptions.swift, FirebaseVertexAI/Sources/Types/Internal/Imagen/ImageGenerationParameters.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImageGenerationOutputOptionsTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImageGenerationParametersTests.swift
Added an encodable type `ImageGenerationParameters`, and a nested `ImageGenerationOutputOptions` type, that is passed in `parameters` in a [`predict`](https://cloud.google.com/vertex-ai/generative-ai/docs/reference/rest/v1/projects.locations.publishers.models/predict#request-body) request. The included parameters are from the `VisionGenerativeModel` schema ([download](https://storage.mtls.cloud.google.com/google-cloud-aiplatform/schema/predict/params/vision_generative_model_1.0.0.yaml)); see the [API reference](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/imagen-api#parameter_list) for more details.
<details>
<summary>VisionGenerativeModel Parameters Schema Reference</summary>
```
title: VisionGenerativeModel
type: object
properties:
sampleCount:
type: number …
```
=> [Vertex AI] Add ImageGenerationParameters for input to predict call

Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h
Update the documentation on the `recordError:userInfo` method.
#no-changelog
=> Update the method documentation of recordError

FirebaseVertexAI/Sources/Types/Internal/Imagen/DecodableImagenImage.swift, FirebaseVertexAI/Sources/Types/Internal/Imagen/ImageGenerationResponse.swift, FirebaseVertexAI/Sources/Types/Internal/Imagen/InternalImagenImage.swift, FirebaseVertexAI/Sources/Types/Internal/Imagen/RAIFilteredReason.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenImage.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenImageRepresentable.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImageGenerationResponseTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/InternalImagenImageTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/RAIFilteredReasonTests.swift
Added a type `ImageGenerationResponse` for decoding the [`PredictResponse`](https://cloud.google.com/vertex-ai/generative-ai/docs/reference/rest/v1/PredictResponse) from an image generation request.
Added `ImagenImage` and `ImagenImageRepresentable`, which are analogous to [`Part`](https://github.com/firebase/firebase-ios-sdk/blob/16381c753c8ff2fe2900fd75b050ac27dacda2ef/FirebaseVertexAI/Sources/Types/Public/Part.swift#L17-L21) and [`PartsRepresentable`](https://github.com/firebase/firebase-ios-sdk/blob/16381c753c8ff2fe2900fd75b050ac27dacda2ef/FirebaseVertexAI/Sources/PartsRepresentable.swift#L17-L22) for `GenerativeModel`. The types we vend in the public API will conform to `ImagenImageRepresentable`, allowing them to be used as input to other operations like image upscaling and image …
=> [Vertex AI] Add ImageGenerationResponse for decoding PredictResponse

FirebaseVertexAI/Sources/GenerativeAIRequest.swift, FirebaseVertexAI/Sources/Types/Internal/Imagen/ImageGenerationInstance.swift, FirebaseVertexAI/Sources/Types/Internal/Imagen/ImageGenerationOutputOptions.swift, FirebaseVertexAI/Sources/Types/Internal/Imagen/ImageGenerationParameters.swift, FirebaseVertexAI/Sources/Types/Internal/Imagen/ImageGenerationRequest.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImageGenerationRequestTests.swift
Added an `ImageGenerationRequest` that conforms to `GenerativeAIRequest` (for use with our existing [`GenerativeAIService`](https://github.com/firebase/firebase-ios-sdk/blob/16381c753c8ff2fe2900fd75b050ac27dacda2ef/FirebaseVertexAI/Sources/GenerativeAIService.swift). This makes a [`PredictRequest`](https://cloud.google.com/vertex-ai/generative-ai/docs/reference/rest/v1/projects.locations.endpoints/predict#imagen:generate-image) to generate images. #14221
#no-changelog
=> [Vertex AI] Add `ImageGenerationRequest` for Imagen

FirebaseVertexAI/Sources/GenerationConfig.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/Types/Internal/InternalPart.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImageGenerationResponse.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/Unit/GenerationConfigTests.swift, FirebaseVertexAI/Tests/Unit/PartTests.swift
Added an `ImagenModel` class with support for generating images using Imagen 3. #14221
- Stopped encoding JSON fields as snake_case in `GenerativeAIService` (Imagen requires the parameters to be camelCase, Gemini supports both)
- Fixed encoding issues that were found after making this transition (will need to audit all field names though).
- Added an integration test to verify basic image generation functionality.
#no-changelog
=> [Vertex AI] Add `ImagenModel` with `generateImages` functions

.github/workflows/vertexai.yml, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTestUtils.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/VertexAITestApp.xcodeproj/project.pbxproj
Updated the `testGenerateImage_inlineData` integration test to only run during nightly scheduled cron jobs or when the workflow is initiated manually. #14221
- Added `workflow_dispatch` option to allow it to be started manually.
- Updated the test to check the image size instead of using Gemini to verify the contents.
- This should be more deterministic and will make it easier to split out the Imagen tests into a separate file.
- For this PR, I tested the integration test manually by specifying the `VTXIntegrationImagen` environment variable in Xcode.
#no-changelog
=> [Vertex AI] Run Imagen integration tests on cron schedule only

FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenAspectRatio.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenGenerationConfig.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenImageFormat.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift
- Added an `ImagenGenerationConfig` type for configuring image generation details (number of images, aspect ratio, image format, etc.) that is accepted in `generateImages()` calls.
- Added `ImagenAspectRatio` and `ImagenImageFormat` types to limit the values to those accepted by the model. Updated the 
- Updated the integration test to check that the config is used.
#14221
#no-changelog
=> [Vertex AI] Add `ImagenGenerationConfig` to `generateImages()`

.github/workflows/auth.yml
=> [infra][auth] auth ci to Xcode 16.1

FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift, FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift, FirebaseAuth/Sources/Swift/SystemService/AuthAppCredentialManager.swift, FirebaseAuth/Sources/Swift/SystemService/AuthNotificationManager.swift, FirebaseAuth/Tests/Unit/AuthBackendTests.swift, FirebaseAuth/Tests/Unit/AuthTests.swift, FirebaseAuth/Tests/Unit/CreateAuthURITests.swift, FirebaseAuth/Tests/Unit/DeleteAccountTests.swift, FirebaseAuth/Tests/Unit/EmailLinkSignInTests.swift, FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift, FirebaseAuth/Tests/Unit/GetAccountInfoTests.swift, FirebaseAuth/Tests/Unit/GetOOBConfirmationCodeTests.swift, FirebaseAuth/Tests/Unit/GetProjectConfigTests.swift, FirebaseAuth/Tests/Unit/OAuthProviderTests.swift, FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift, FirebaseAuth/Tests/Unit/RPCBaseTests.swift, FirebaseAuth/Tests/Unit/ResetPasswordTests.swift, FirebaseAuth/Tests/Unit/RevokeTokenTests.swift, FirebaseAuth/Tests/Unit/SendVerificationCodeTests.swift, FirebaseAuth/Tests/Unit/SetAccountInfoTests.swift, FirebaseAuth/Tests/Unit/SignInWithGameCenterTests.swift, FirebaseAuth/Tests/Unit/SignUpNewUserTests.swift, FirebaseAuth/Tests/Unit/UserTests.swift, FirebaseAuth/Tests/Unit/VerifyAssertionTests.swift, FirebaseAuth/Tests/Unit/VerifyClientTests.swift, FirebaseAuth/Tests/Unit/VerifyCustomTokenTests.swift, FirebaseAuth/Tests/Unit/VerifyPasswordTests.swift, FirebaseAuth/Tests/Unit/VerifyPhoneNumberTests.swift
Fixes unit tests running locally with Xcode 16.1
I was seeing numerous crashes related to checkedContinuations in async contexts and cleaned up test infra to address.
More investigation needed on the library changes in the first few files to get the tests working. See #14232
=> Auth Unit Test Fixes

FirebaseVertexAI/Sources/Types/Internal/Imagen/ImageGenerationParameters.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenSafetySettings.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImageGenerationParametersTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImageGenerationRequestTests.swift
Added an `ImagenSafetySettings` type to allow configuration of the [safety filter level](https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen#safety-filters), [person generation](https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen#content-filtering-params), and whether to [include filter reasons](https://cloud.google.com/vertex-ai/generative-ai/docs/image/responsible-ai-imagen#safety-categories). Removed the `seed` parameter since it won't be in the initial release. #14221
#no-changelog
=> [Vertex AI] Add `ImagenSafetySettings` type and param

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift, FirebaseAuth/Sources/Swift/MultiFactor/MultiFactorSession.swift
Fix https://github.com/invertase/react-native-firebase/issues/8177
=> [auth] Fix Multi-factor session crash on second Firebase app

FirebaseAuth/Sources/Swift/SystemService/AuthNotificationManager.swift, FirebaseAuth/Sources/Swift/Utilities/AuthCondition.swift, FirebaseAuth/Tests/Unit/AuthNotificationManagerTests.swift
Create AuthCondition powered by AsyncStream to provide the task to task triggering to replace the callback scheme implemented with `withUnsafeContinuation`.
Successor to #14223
=> AuthNotificationManager from continuation to AsyncStream

.github/workflows/remoteconfig.yml, FirebaseRemoteConfig/SwiftNew/ConfigContent.swift, FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
Follow up to #14175 
Add AtomicConfig class for the config variables enables atomic accesses to support multiple namespace usage of RemoteConfig.
This allows the removal of the workaround for multi-namespace test failures in RCNRemoteConfigTest.m introduced in #14175
=> [rc-swift] Fix atomic config accesses

Firestore/Swift/Source/PropertyWrapper/FirestoreQuery.swift
This PR addresses the following errors in Swift 6 mode:
```swift
// FirestoreQuery.swift
@available(iOS 14.0, macOS 11.0, macCatalyst 14.0, tvOS 14.0, watchOS 7.0, *)
@propertyWrapper
public struct FirestoreQuery<T>: DynamicProperty {
@StateObject private var firestoreQueryObservable: FirestoreQueryObservable<T>
// <--snip-->
public var wrappedValue: T {
firestoreQueryObservable.items // 💥 Main actor-isolated property 'firestoreQueryObservable' can not be referenced from a nonisolated context
}
/// A binding to the request's mutable configuration properties
@MainActor @preconcurrency public var projectedValue: Configuration {
get {
firestoreQueryObservable.configuration // 💥 Main actor-isolated property 'firestoreQueryObservable' can not be referenced from a nonisolated context
} …
```
=> [Firestore] Label '@MainActor' isolated APIs of 'FirestoreQuery'

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h
=> [rc] Mark ConfigUpdateListenerRegistration Sendable

FirebaseRemoteConfig/Sources/Private/RCNConfigFetch.h, FirebaseRemoteConfig/Sources/RCNConfigFetch.m, FirebaseRemoteConfig/Tests/Unit/RCNPersonalizationTest.m, FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
This is going into the `rc-swift` branch for the RC Swift port. The typedefs interfere with translation into Swift. The typedef is defined in a private header so should be OK to remove.
#no-changelog
=> [Config] Move away from private typedef

FirebaseRemoteConfig/Sources/Private/RCNConfigFetch.h, FirebaseRemoteConfig/Sources/RCNConfigFetch.m, FirebaseRemoteConfig/Tests/Swift/ObjC/FetchMocks.m, FirebaseRemoteConfig/Tests/Unit/RCNPersonalizationTest.m, FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
=> [Config] Move away from private typedef (1)

Firestore/Example/Tests/Integration/API/FIRQueryTests.mm, Firestore/core/src/model/base_path.h
Document ID supports strings and well as long integers in the format of "id" . When sorting documents by document ID, it should be sorted in the following order:
1. Long (numeric order)
2. String (lexicographic order)
#no-changelog
=> Fix: sort document reference by long type id

FirebaseMessaging/Apps/Shared/LiveActivityView.swift
Fixed a repeated typo. No reference found outside the file.
=> [FirebaseMessaging] fix: typo in the word `formatted`

FirebaseMessaging/Apps/README.md
Add the missing `i` in the readme file.
=> [FirebaseMessaging] docs: enhance the readme text

FirebaseStorage/Sources/Internal/StorageInternalTask.swift
Xcode 16.2: <img width="1114" alt="Screenshot 2024-12-18 at 12 28 25 PM" src="https://github.com/user-attachments/assets/b18cdf68-b00b-4afc-b558-865fa0ffa041" />
#no-changelog
=> [Storage] Add preconcurrency attribute to class

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift, FirebaseAuth/Sources/Swift/Utilities/AuthErrorUtils.swift, FirebaseAuth/Sources/Swift/Utilities/AuthErrors.swift, FirebaseAuth/Tests/Unit/AuthBackendTests.swift
Fix #14052
Thanks to @amirandalibi for the bulk of the rationale and specification in #14052
=> [auth] Fix handling of cloud blocking function errors

FirebaseRemoteConfig/SwiftNew/ConfigDBManager.swift, FirebaseRemoteConfig/SwiftNew/DatabaseActor.swift, FirebaseRemoteConfig/Tests/SwiftUnit/ConfigDBManagerTest.swift
Add AI generated tests for ConfigDBManager
Fix two issues they discovered:
- UnInitialized `isNewDatabase`
- Race conditions with delete operations
=> Add AI generated tests for ConfigDBManager

Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
Adding explanation on how memory allocation is made and the reason it will not have buffer overflow.
#no-changelog
=> add explanation of how alloc works

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.m, Crashlytics/Crashlytics/Helpers/FIRCLSAllocate.c, Crashlytics/Crashlytics/Helpers/FIRCLSFile.m, Crashlytics/Crashlytics/Helpers/FIRCLSUtility.m, Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m, Crashlytics/Shared/FIRCLSByteUtility.m, Crashlytics/Shared/FIRCLSMachO/FIRCLSMachOBinary.m, Crashlytics/UnitTests/FIRCLSCompactUnwindTests.m, Crashlytics/UnitTests/FIRCLSDwarfTests.m, Crashlytics/UnitTests/FIRCLSFileTests.m, Crashlytics/UnitTests/FIRCLSLoggingTests.m
=> Change malloc to calloc

FirebaseRemoteConfig/SwiftNew/ConfigDBManager.swift, FirebaseRemoteConfig/Tests/SwiftUnit/ConfigDBManagerOrigTest.swift
Converts RCNConfigDBManagerTests.m to Swift. Plan to delete the ObjC file after all library sources are Swift.
TBD: merging and naming for ConfigDBManagerTests.swift (AI generated) and ConfigDBManagerOrigTests.swift (converted from ObjC test file)
=> [rc-swift] RCNConfigDBManagerTests.m to swift

Crashlytics/Crashlytics/Helpers/FIRCLSAllocate.c, Crashlytics/Crashlytics/Helpers/FIRCLSFile.m, Crashlytics/Crashlytics/Helpers/FIRCLSUtility.m, Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m, FirebaseSessions/SourcesObjC/NanoPB/FIRSESNanoPBHelpers.h, FirebaseSessions/SourcesObjC/NanoPB/FIRSESNanoPBHelpers.m
https://github.com/firebase/firebase-ios-sdk/issues/14209
#no-changelog
=> fix comment and migrate to calloc for session

.github/workflows/firestore-nightly.yml, .github/workflows/firestore.yml
Fix the following error from the `setup-python` steps by upgrading Python from 3.7 to 3.11, which is what all of the other `setup-python` steps use:
```
Version 3.7 was not found in the local cache
##[error]The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
#no-changelog
=> Bump Python version from 3.7 to 3.11 in GitHub Actions workflows

FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenPersonFilterLevel.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenSafetyFilterLevel.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImageGenerationParametersTests.swift
- Renamed `ImagenSafetySettings.PersonGeneration` to `ImagenPersonFilterLevel` since it does not control whether people are generated, only whether they get filtered out after generation.
- Renamed `ImagenSafetySettings.SafetyFilterLevel` to `ImagenSafetyFilterLevel` to align with other platforms.
- Removed `includeFilterReason` since we've decided to hardcode it to `true` (when `false`, [no feedback is provided](https://cloud.google.com/vertex-ai/generative-ai/docs/image/generate-images#safety-filters) when images are filtered).
#14221
#no-changelog
=> [Vertex AI] Refactor `ImagenSafetySettings`

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
Fix #14242 
If the flag is set we will bypass RCE flow and treat it similar to RCE enablement status off.
Ran PhoneAuthProvider tests with emulator and verified that this error no longer occurs.
=> Update RCE flow to skip checking status if appVerificationDisabledForTesting is set

FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift
Possible fix for `https://github.com/firebase/firebase-ios-sdk/issues/14196` until the SDK is fully synchronized with structured concurrency.
=> [Auth] Make two string properties atomic

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h
I downloaded last Xcode 15 version, Xcode 15.4, to test and found that adding Sendable to the closure params created a warning when the call site inherited an isolation domain (main actor, global actor, etc.). The warning is more disruptive to Xcode 15 users since Xcode 15 does not include Swift 6 language version.
In Xcode 16, the same warning appears for Swift 5 users and is an error in Swift 6.
Conclusion– no new warnings for Xcode 15. New warnings for Xcode 16 where newly Sendable completion handler will warn about changing properties belonging to other isolation domains (see screenshot). New warnings are errors in Swift 6 mode in Xcode 16.
Fixes #14257
=> [Config] Conditionally mark closures as Sendable for Xcode 16

FirebaseVertexAI/Sources/Types/Internal/Imagen/ImagenGenerationRequest.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenGenerationResponse.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenGenerationRequestTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenGenerationResponseTests.swift
- Renamed `ImageGenerationResponse` to `ImagenGenerationResponse` (Imagen vs. Image).
- Although it is is internal, renamed `ImageGenerationRequest` to match.
- Renamed the `raiFilteredReason` property to `filteredReason`.
#14236
#no-changelog
=> [Vertex AI] Rename `ImageGenerationResponse` to `ImagenGenerationResponse`

docs/firebase-api-guidelines.md
The header tags don't work in GitHub flavored markdown.
#no-changelog
=> [Docs] Follow-up to #14325

Firestore/CHANGELOG.md, Firestore/core/src/util/string_format.h, Firestore/core/test/unit/util/string_format_test.cc
This PR fixes the following use-after-free bug detected by the test [`TEST(StringFormatTest, Pointer)`](https://github.com/firebase/firebase-ios-sdk/blob/c092c02dd2840782132e61dfc77558729bf63450/Firestore/core/test/unit/util/string_format_test.cc#L79) when run under ASAN:
```
11: =================================================================
11: ==22796==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f2c74931b50 at pc 0x7f2c778fb42e bp 0x7ffd9a727650 sp 0x7ffd9a726df8
11: READ of size 12 at 0x7f2c74931b50 thread T0
11:     #0 0x7f2c778fb42d in memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:115
11:     #1 0x7f2c76f68754 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> …
```
=> Firestore: string_format.h: fix use-after-free bug when internally formatting strings

Firestore/core/test/unit/util/string_format_apple_test.mm
Add a test for formatting an objective-c `Class` object in`string_format_apple_test.mm`. The test suite previously covered formatting Objective-C _objects_, but not the specific override for formatting `Class` objects. With this PR, the tests were improved to also cover this missing case.
#no-changelog
=> Firestore: add a test for formatting an objective-c Class objects

FirebaseRemoteConfig/Tests/SwiftUnit/UserDefaultsManagerTests.swift
This did require some tweaking and I did add two tests. Commented out tests that were generated but used private APIs. I'm in favor of deleting the tests instead of making the tested API internal, but wanted to surface this in case there are other views.
#no-changelog
=> [Config] Add generated tests for UserDefaultsManagerTests.swift

FirebaseVertexAI/Sources/Types/Internal/Imagen/ImagenImageRepresentable.swift, FirebaseVertexAI/Sources/Types/Internal/Imagen/InternalImagenImage.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenFileDataImage.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenGenerationResponse.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenInlineDataImage.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenFileDataImageTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenInlineDataImageTests.swift
Updated the `ImagenImageRepresentable` and `_ImagenImage` visibility from `public` to `internal` since they are not needed until the SDK supports operations that accept images as input (e.g., upscaling or editing). This will reduce the API surface that needs to be reviewed in the API proposal for image generation.
Note: Renamed `_ImagenImage` to `_InternalImagenImage` and `ImagenImageRepresentable._imagenImage` to `ImagenImageRepresentable._internalImagenImage`. Although these are no longer public symbols, this is my proposed naming for when we do expose them publicly.
#14221
#no-changelog
=> [Vertex AI] Make `ImagenImageRepresentable` internal

Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
#no-changelog
Adding test cases for sorting strings when special characters are included.
Other SDKs requires fix:
Java: https://github.com/googleapis/java-firestore/pull/1967
Node: https://github.com/googleapis/nodejs-firestore/pull/2275 
Android: https://github.com/firebase/firebase-android-sdk/pull/6615 
Web: https://github.com/firebase/firebase-js-sdk/pull/8691
=> FIX: sort strings in UTF-8 encoded byte order

FirebaseRemoteConfig/SwiftNew/ConfigExperiment.swift, FirebaseRemoteConfig/Tests/SwiftUnit/ConfigExperimentOrigTests.swift
=> [Config] Port ConfigExperiment tests

FirebaseMessaging/CHANGELOG.md, FirebaseMessaging/Sources/Token/FIRMessagingTokenDeleteOperation.m, FirebaseMessaging/Sources/Token/FIRMessagingTokenFetchOperation.m
We are using `defaultSessionConfiguration` as the HTTP session configuration for FCM registration token operations. https://github.com/firebase/firebase-ios-sdk/blob/a34d7ae4ed3ce143bc22d57cbda9e9341fee3df6/FirebaseMessaging/Sources/Token/FIRMessagingTokenFetchOperation.m#L111C65-L111C92
As a result, HTTP requests and responses are cached in the `Cache.db` file.
This probably isn't a security risk. Other apps cannot access the file, and even if someone got the FCM registration token, they couldn't do anything with it. They cannot just send notifications with the token alone. https://firebase.google.com/docs/cloud-messaging/auth-server
But still, caching the HTTP requests and responses are unnecessary. We don't use the cache in any way.
Fix #14352
=> Don't cache FCM registration token operations.

FirebaseRemoteConfig/Swift/CustomSignals.swift, FirebaseRemoteConfig/SwiftNew/ConfigConstants.swift, FirebaseRemoteConfig/SwiftNew/ConfigSettings.swift, FirebaseRemoteConfig/SwiftNew/RemoteConfig.swift, FirebaseRemoteConfig/SwiftNew/UserDefaultsManager.swift, FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
After rebasing `rc-swift` on latest `main`, this PR reimplements custom signals changes from #13976 and Sendable changes from #14314
=> [rc-swift] Custom Signals and Sendable

Firestore/core/src/nanopb/byte_string.cc, Firestore/core/test/unit/nanopb/byte_string_test.cc, Firestore/core/test/unit/util/executor_test.cc, Firestore/core/test/unit/util/schedule_test.cc
See https://github.com/firebase/firebase-ios-sdk/pull/14347#issuecomment-2608188338 for how this came to my attention.
#no-changelog
=> Firestore: add some 'NOLINT(build/include_order)' comments to make lint happy

Firestore/core/include/firebase/firestore/timestamp.h, Firestore/core/src/timestamp.cc, Firestore/core/src/util/firestore_exceptions.h
This PR removes some vestigial cruft pertaining to STLPort, whose support was dropped in July 2021 (3.5 years ago at the time of writing) in https://github.com/firebase/firebase-cpp-sdk/pull/510.
#no-changelog
=> Firestore: Remove vestigial mentions of STLport

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h
Fix https://github.com/firebase/firebase-ios-sdk/issues/14257
Manually tested, crash before, crash free after fix.
=> [Config] Mark `addOnConfigUpdateListener` as `Sendable`

FirebaseRemoteConfig/SwiftNew/ConfigContent.swift, FirebaseRemoteConfig/SwiftNew/ConfigRealtime.swift, FirebaseRemoteConfig/SwiftNew/RemoteConfig.swift
=> [Config] Follow-up to #14309

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/ActionCode/ActionCodeSettings.swift, FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift, FirebaseAuth/Sources/Swift/Backend/RPC/GetOOBConfirmationCodeRequest.swift, FirebaseAuth/Sources/Swift/Utilities/AuthErrorUtils.swift, FirebaseAuth/Sources/Swift/Utilities/AuthErrors.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Models/AuthMenu.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AccountLinkingViewController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AuthViewController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/OtherAuthMethodControllers/PasswordlessViewController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExampleUITests/AuthenticationExampleUITests.swift, FirebaseAuth/Tests/Unit/GetOOBConfirmationCodeTests.swift, FirebaseAuth/Tests/Unit/ObjCAPITests.m, FirebaseAuth/Tests/Unit/RPCBaseTests.swift, FirebaseAuth/Tests/Unit/SwiftAPI.swift
Firebase Auth relies on Firebase Dynamic Links (FDL) for mobile out-of-band email action flows. As FDL is deprecated, we're introducing a new solution, Firebase Hosting links,  to replace FDL usage in Firebase Auth.
Add a new `ActionCodeSettings.linkDomain` property to customize the Firebase Hosting link domain that is used in out-of-band email action flows.
Migration guide and public documentations will be available after the SDK release.
=> [Auth] Add ActionCodeSettings.linkDomain and deprecate ActionCodeSettings.dynamicLinkDomain

Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_IntegrationTests_iOS.xcscheme, Firestore/core/src/nanopb/byte_string.cc, Firestore/core/test/unit/nanopb/byte_string_test.cc
Now xcodebuild fails with:
Error:     Restarting after unexpected exit, crash, or test timeout in PipelineTests.testCreatePipeline(); summary will include totals from previous launches.
=> Undo xcscheme change to fix CI error

FirebaseVertexAI/README.md
Removed the outdated README message about Vertex AI in Firebase being in Public Preview and fixed the SPM product name.
Context: Vertex AI in Firebase became GA in the https://github.com/firebase/firebase-ios-sdk/releases/tag/11.4.0.
#no-changelog
=> [Vertex AI] Remove outdated `Preview` notice from README

FirebaseVertexAI/Tests/TestApp/Tests/Integration/ImagenIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/VertexAITestApp.xcodeproj/project.pbxproj
- Split Imagen integration tests into a separate file and updated to use [Swift Testing](https://developer.apple.com/documentation/testing/).
- Added a test to validate image generation into GCS.
- Added a test to validate behaviour when all generated images are filtered out.
#14221
#no-changelog
=> [Vertex AI] Add Imagen integration tests for GCS and filtering

FirebaseVertexAI/Sources/APIVersion.swift, FirebaseVertexAI/Sources/GenerativeAIRequest.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/Unit/APIVersionTests.swift, FirebaseVertexAI/Tests/Unit/RequestOptionsTest.swift, FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
Added an internal constructor for `RequestOptions` that supports specifying an API version (e.g., `v1` or `v1beta`).
See [go/firebase-vertex-set-api-version](https://goto.corp.google.com/firebase-vertex-set-api-version) (Google-internal only) for more details.
#14405
#no-changelog
=> [Vertex AI] Add internal `apiVersion` parameter to `RequestOptions`

FirebaseAuth/Tests/SampleSwift/AuthenticationExample/AppDelegate.swift
As is, adding a new line within the function's implementation will give it an awkward indentation. This small change fixes it.
#no-changelog
=> [NFC] Update spacing in FirebaseAuth's sample app delegate

FirebaseFirestoreInternal.podspec, Firestore/CHANGELOG.md, Firestore/Example/Podfile, Firestore/Example/ProtobufCpp.podspec, Package.swift
Upgrade the gRPC version to pick up the fix mentioned in https://github.com/firebase/firebase-ios-sdk/issues/14323#issuecomment-2585008944
=> Update to gRPC 1.69.0

FirebaseVertexAI/Sources/Types/Public/Part.swift
Added documentation for the public constructor and properties in `InlineDataPart`. These were listed as undocumented in our [reference docs](https://firebase.google.com/docs/reference/swift/firebasevertexai/api/reference/Structs/InlineDataPart).
<details>
<summary>Xcode-rendered Docs</summary>
`InlineDataPart`
`init(data:mimeType:)`
</details>
#no-changelog
=> [Vertex AI] Add documentation for `InlineDataPart`

Firebase.podspec, FirebaseAuth.podspec, FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Backend/RPC/GetOOBConfirmationCodeRequest.swift, FirebaseCore.podspec, Package.swift
Make a CocoaPods and Swift PM patch release for a build warning in FirebaseAuth that released in 11.8.0
=> Prepare 11.8.1

CoreOnly/NOTICES, FirebaseDatabase.podspec, FirebaseDatabase/CHANGELOG.md, FirebaseDatabase/LICENSE, FirebaseDatabase/Sources/Core/FPersistentConnection.m, FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDatabase.h, FirebaseDatabase/Sources/Realtime/FWebSocketConnection.h, FirebaseDatabase/Sources/Realtime/FWebSocketConnection.m, FirebaseDatabase/Sources/Utilities/FStringUtilities.m, FirebaseDatabase/Sources/third_party/SocketRocket/FSRWebSocket.h, FirebaseDatabase/Sources/third_party/SocketRocket/FSRWebSocket.m, FirebaseDatabase/Sources/third_party/SocketRocket/LICENSE, FirebaseDatabase/Sources/third_party/SocketRocket/NSData+SRB64Additions.h, FirebaseDatabase/Sources/third_party/SocketRocket/NSData+SRB64Additions.m, FirebaseDatabase/Sources/third_party/SocketRocket/aa2297808c225710e267afece4439c256f6efdb3, FirebaseDatabase/Sources/third_party/SocketRocket/fbase64.c, FirebaseDatabase/Sources/third_party/SocketRocket/fbase64.h, FirebaseDatabase/Tests/Integration/FData.m, FirebaseDatabase/Tests/Integration/FIRDatabaseQueryTests.m, Package.swift
Fix connection failure issue introduced in 10.27.0 by restoring the Socket Rocket implementation instead of `NSURLSessionWebSocket`. 
Note that this may expose a Thread Performance Checker Warning (#12883)
Fixes #14188, #13877, #13855, #13529
=> Restore socket rocket

FirebaseDatabase/CHANGELOG.md, FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDataSnapshot.h
=> [Database] Mark 'FIRDataSnapshot' as Sendable

Firestore/core/src/util/firestore_exceptions.h
firebase-cpp-sdk has some issues compiling absl-dependent code on Android; therefore, remove the dependency on absl from firestore_exceptions.h, as it was before #14348.
See https://github.com/firebase/firebase-ios-sdk/pull/14348/files/1989942cffe222e986230c1539908a9fd105360c#r1950085884
#no-changelog
=> firestore_exceptions.h: remove dependency on absl to set FIRESTORE_HAVE_EXCEPTIONS

FirebaseVertexAI/Sources/CountTokensRequest.swift, FirebaseVertexAI/Sources/GenerateContentResponse.swift
Fixed a decoding issue in `CountTokensResponse`. This needs a custom decoder now to handle the case when `promptTokensDetails` is `nil`.
#no-changelog
=> [Vertex AI] Fix `CountTokensResponse` decoding

FirebaseVertexAI/Sources/Types/Internal/Imagen/ImagenConstants.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenGenerationResponse.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenImagesBlockedError.swift, FirebaseVertexAI/Sources/VertexLog.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/ImagenIntegrationTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenGenerationResponseTests.swift
Added an error that is thrown when all images are blocked and `ImagenGenerationResponse.images` would be empty. Throws a `DecodingError` if the `ImagenGenerationResponse` contains no images and there's no filtered reason provided.
#14221
#no-changelog
=> [Vertex AI] Add `ImagenImagesBlockedError`

FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenInlineImage.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenGenerationResponseTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenInlineImageTests.swift
Added error handling for decoding a `ImagenInlineImage` a base64-encoded string. Now throws a `DecodingError` instead of calling `fatalError`.
#14221
#no-changelog
=> [Vertex AI] Add error handling for decoding `ImagenInlineImage` from b64

FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift
Added integration tests for the new modality-specific token usage metrics added in #14406.
Note: Added a tolerance (`accuracy`) of `1` on the candidate and total token counts since they can differ between runs due to trailing whitespace tokens. This is not the case for prompt token counts which are deterministic since they are provided as input.
#no-changelog
=> [Vertex AI] Add integration tests for modality usage metrics

FirebaseMessaging/CHANGELOG.md, FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m, FirebaseMessaging/Sources/Token/FIRMessagingTokenStore.m
`unarchiveObjectWithData` is [deprecated](https://developer.apple.com/documentation/foundation/nskeyedunarchiver/1413894-unarchiveobjectwithdata). Move the codebase to use the new and more secure `NSKeyedUnarchiver` APIs.
This PR only modifies the API used; it does not affect behavior.
This is expected to fix #14424.
=> Migrate FCM codebase to new NSKeyedUnarchiver APIs.

FirebaseFunctions/Sources/Internal/FunctionsContext.swift, FirebaseFunctions/Tests/Unit/ContextProviderTests.swift, FirebaseFunctions/Tests/Unit/FunctionsTests.swift
Currently, the Functions SDK does not pass the App Check placeholder token for cases where the App Check integration fails to fetch an App Check token.
Before:
After:
=> [Functions] Pass placeholder app check tokens on error

FirebaseFunctions/Sources/Callable+Codable.swift, FirebaseFunctions/Tests/Integration/IntegrationTests.swift, FirebaseFunctions/Tests/Unit/FunctionsTests.swift
=> Streamable functions - Continuation of #14395

Firestore/Example/Firestore.xcodeproj/project.pbxproj
#no-changelog
This PR would fix this error when open Firestore tests in Xcode.
=> Specify Swift Version in Firestore test settings

FirebaseVertexAI/Sources/FirebaseInfo.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
- Add google-app-id to Vertex AI requests
- Add FirebaseInfo struct to package Firebase data used by Vertex AI
Going to merge with the actual header change and test commented out. Will do the uncomments in a subsequent PR.
#no-changelog
=> Add google-app-id to Vertex AI requests

FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Follow up to #14479 
Temporarily disable header change until ready to proceed with backend.  
This PR can be reverted when ready to proceed.
=> [vertex-ai] Disable google-app-id

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json, ReleaseTooling/CarthageJSON/FirebaseVertexAIBinary.json
Updated the Carthage artifacts for the M160 / https://github.com/firebase/firebase-ios-sdk/releases/tag/11.9.0.
<details>
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseABTestingBinary.json" "11.9.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAdMobBinary.json" "11.9.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "11.9.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsOnDeviceConversionBinary.json" "11.9.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppCheckBinary.json" "11.9.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppDistributionBinary.json" "11.9.0"
binary …
```
=> [Release] Carthage updates for M160 / 11.9.0

FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift
Added an integration test for `Chat.sendMessageStream`, which transitively tests `GenerativeModel.generateContentStream`.
#no-changelog
=> [Vertex AI] Add integration test for `generateContentStream`

.github/workflows/vertexai.yml, FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Tests/Unit/MockURLProtocol.swift, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
- Add Swift 6 testing to CI
- Update unit tests to build in Swift 
- Add Changelog note
- Workaround remaining warning(s) see below
- A first pass at fixing the warning is in #14504
=> [VertexAI] Add Swift 6 testing to CI

.github/workflows/prerelease.yml
Updated the `buildup_SpecsTesting_repo` job to run on `macos-15` instead of `macos-14`. This resolves the failure in [`buildup_SpecsTesting_repo (FirebaseVertexAI, false)`](https://github.com/firebase/firebase-ios-sdk/actions/runs/13559317720/job/37932304944#step:5:539) from #14505.
Note: The `prerelease` workflow was not invoked by this PR but passed [manually](https://github.com/firebase/firebase-ios-sdk/actions/runs/13571327172/job/37937874410).
#no-changelog
=> [CI] Run `buildup_SpecsTesting_repo` job on `macos-15`

Crashlytics/CHANGELOG.md
Fix a simple typo in the change log. No more issues in the Crashlytics files
=> [Crashlytics] docs: fix a typo in the change log

FirebaseInAppMessaging/Sources/Analytics/FIRIAMClearcutUploader.m
Fix a simple typo in Firebase In App Messaging source file. The change is backward compatible
=> docs: fix the word `equivalent`

FirebaseInAppMessaging/Sources/Analytics/FIRIAMAnalyticsEventLoggerImpl.m
Fix a typo in a static constant name. I couldn't see any use of this static property. Please double check and let me know if we should update elsewhere related to this property as well.
Thanks
=> chore: remove unused `user defaults key for remove user property time in seconds` property

FirebaseFunctions/Sources/Functions.swift, FirebaseFunctions/Sources/Internal/FunctionsSerializer.swift
* The method no longer returns an optional
* Changed `AnyObject` to `Any`
=> Refactored `FunctionsSerializer.decode(_:)`

FirebaseFunctions/Sources/Internal/FunctionsSerializer.swift
* Fewer reference types
* Fewer mutable objects
=> Refactored `FunctionsSerializer.encode(_:)`

scripts/build.sh
The build script is reused by DataConnect which needs a min deployment target of 15.0. Without this, some integration tests are failing due to version check.
FYI -
Workflow definition where the build script is invoked
https://github.com/firebase/data-connect-ios-sdk/blob/main/.github/workflows/spm.yml#L77
Error -> 
https://github.com/firebase/data-connect-ios-sdk/actions/runs/13660926083/job/38191785059?pr=43#step:7:1814
=> Add DataConnect product definition to build.sh

.github/workflows/generate_issues.yml
I'll handle check failure in subsequent PR.
#no-changelog
=> [Infra] Update `generate_issues.yml` to give GITHUB_TOKEN write permissions for issues.

FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/GenerativeModel.swift
Refactored `GenerativeModel.generateContentStream(...)` to use [`init(_:bufferingPolicy:_:)`](https://developer.apple.com/documentation/swift/asyncthrowingstream/init(_:bufferingpolicy:_:)) (`AsyncStream.Continuation` approach) instead of [`init(unfolding:)`](https://developer.apple.com/documentation/swift/asyncthrowingstream/init(unfolding:)) to resolve the Swift 6 warning "`Capture of responseIterator with non-Sendable type AsyncThrowingStream<GenerateContentResponse, Error>`" discussed in #14503.
#no-changelog
=> [Vertex AI] Refactor generateContentStream to fix Swift 6 warning

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Swift/Codable.swift, FirebaseRemoteConfig/Swift/Value.swift, FirebaseRemoteConfig/Tests/Swift/SwiftAPI/Codable.swift
Fix #14368
Relevant: https://github.com/firebase/firebase-ios-sdk/pull/9084#issue-1077876345
I did not update the following APIs because I wasn't able to get a test case working (See be0616a3f9b772947da3edca8e8b9e43d85842b1). I think it's reasonable to limit the scope of exposing the `FirebaseData*coder`s in the public API since it needs some re-thinking).
- https://github.com/firebase/firebase-ios-sdk/blob/ea8fb07f37a3dc647bb494a7a6b17b9eb6f78c26/FirebaseRemoteConfig/Swift/Codable.swift#L31-L40
- https://github.com/firebase/firebase-ios-sdk/blob/ea8fb07f37a3dc647bb494a7a6b17b9eb6f78c26/FirebaseRemoteConfig/Swift/Value.swift#L25-L30
=> [Config] Add encoder and decoder param to public codable APIs

.github/workflows/abtesting.yml, .github/workflows/auth.yml, .github/workflows/core.yml, .github/workflows/crashlytics.yml, .github/workflows/mlmodeldownloader.yml, .github/workflows/remoteconfig.yml, .github/workflows/sessions.yml, .github/workflows/vertexai.yml
I only added this fix to the workflows that failed in the nightly testing report. It's possible we may want to extend it to all workflows until GitHub's runners consistently have the sims we need.
Fix #14542
=> [Infra] Install visionOS sims to workflows that couldn't find it

FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/VertexAITestApp.xcodeproj/project.pbxproj, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
- Added a new GenerateContentIntegrationTests test suite, which runs a `generateContent` test against the Vertex AI (`v1` and `v1beta`) API, as well as the Developer API (`v1beta`).
- Refactored the `VertexAI` component to use one static method `vertexAI(app:location:)`, where `app` is optional, to reduce code and documentation duplication.
- Removed the internal `VertexAI.developer(...)` API in favour of calling `VertexAI.vertexAI(app:location:apiConfig:)` (also internal -- I think we should consider renaming to differentiate it from the public API) directly in the integration tests.
- I removed this for now since it didn't reduce it didn't reduce the boilerplate in the integration test. This can be revisited when we have a public API surface.
#no-changelog
=> [Vertex AI] Parameterize integration tests for Vertex and Dev API

Crashlytics/Crashlytics/Components/FIRCLSApplication.h, Crashlytics/Crashlytics/Components/FIRCLSApplication.m
deprecated the use `[UIApplication openURL:]` and useless method
#no-change
=> remove useless method

FirebaseRemoteConfig/Swift/Codable.swift
Successor to https://github.com/firebase/firebase-ios-sdk/pull/14525
After thinking about https://github.com/firebase/firebase-ios-sdk/pull/14525#discussion_r1983609998 more, I don't think the consolidated signature is worth the potential of a breaking change. Besides assigning functions to variables, there are some possible other potentials of breaking: https://forums.swift.org/t/pitch-adding-new-parameters-w-default-values-should-not-break-api/66847
Also, improved documentation clarity.
=> [Config] Split Codable APIs up and improve doc comments

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/CountTokensRequest.swift, FirebaseVertexAI/Sources/FunctionCalling.swift, FirebaseVertexAI/Sources/GenerationConfig.swift, FirebaseVertexAI/Sources/Safety.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenGenerationConfig.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseVertexAI/Sources/Types/Public/Part.swift, FirebaseVertexAI/Sources/VertexAI.swift
Updated DocC links in the Vertex AI in Firebase SDK to refer to resources on the Firebase documentation site (`https://firebase.google.com/docs/vertex-ai`), instead of Google Cloud, where equivalent pages are available.
=> [Vertex AI] Update DocC links to Firebase docsite where available

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
The `role` property in `ModelContent` is now ignored (explicitly set to `nil`) in system instructions. This aligns with the [Vertex AI](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/system-instructions#gemini-system-instructions-code-samples-drest) documentation (and the [Developer API](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/system-instructions#gemini-system-instructions-code-samples-drest)). This works around an issue where the `role` is counted in the prompt token count in `countTokens(...)` but is not in `generateContent(...)`. No code changes are required for developers.
Note: Although not shown in this PR, system instructions are used in most of the integration tests.
=> [Vertex AI] Set `ModelContent.role` to `nil` in system instructions

.github/workflows/firebase_app_check.yml, .github/workflows/release.yml
- Bump release tests to macos-15 to address vertexai macos-14 only warning
- Ensure visionos simulator is available for appcheck tests
Fix #14559
=> Fix nightlies

FirebaseFunctions/CHANGELOG.md, FirebaseRemoteConfig/CHANGELOG.md, FirebaseVertexAI/CHANGELOG.md
=> [Release] Version changelog entries for 10.10.0

.github/workflows/core_internal.yml, FirebaseCore/Internal/Tests/Integration/HeartbeatLoggingIntegrationTests.swift, FirebaseCore/Internal/Tests/Unit/HeartbeatControllerTests.swift, FirebaseCore/Internal/Tests/Unit/HeartbeatStorageTests.swift
=> [Swift 6] Add Swift 6 testing for CoreInternal

.github/workflows/notice_generation.yml, .github/workflows/prerelease.yml
I noticed our prerelease tags hadn't been moved in awhile. I think the workflow needs permissions. So does `notice_generation.yml` for it to generate a pull request.
=> [Infra] Add write permissions to notice_generation.yml and prerelease.yml

FirebaseVertexAI/Sources/FirebaseInfo.swift, FirebaseVertexAI/Sources/GenerativeAIService.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
#no-changelog
Follow up to #14568
=> [vertex-ai] Rename googleAppID to firebaseAppID

FirebaseVertexAI/Tests/Unit/vertexai-sdk-test-data/mock-responses, FirebaseVertexAI/Tests/Unit/vertexai-sdk-test-data/mock-responses/developerapi, FirebaseVertexAI/Tests/Unit/vertexai-sdk-test-data/mock-responses/vertexai
Added placeholder files for the [`vertexai`](https://github.com/FirebaseExtended/vertexai-sdk-test-data/tree/bdf8af9e8f34157a31faeb712822f12e6feab31a/mock-responses/vertexai) and [`developerapi`](https://github.com/FirebaseExtended/vertexai-sdk-test-data/tree/bdf8af9e8f34157a31faeb712822f12e6feab31a/mock-responses/developerapi) folders from the https://github.com/FirebaseExtended/vertexai-sdk-test-data repo. Since the subfolders are now referenced in [`Package.swift`](https://github.com/firebase/firebase-ios-sdk/blob/3bc52e3fc1086b7477a645a1ed2cc4a6d59b185b/Package.swift#L1321), the previous placeholder at [`mock-responses`](https://github.com/firebase/firebase-ios-sdk/blob/3bc52e3fc1086b7477a645a1ed2cc4a6d59b185b/FirebaseVertexAI/Tests/Unit/vertexai-sdk-test-data/mock-responses) no …
=> [Vertex AI] Add placeholders for `vertexai-sdk-test-data` files

Firestore/CHANGELOG.md, Firestore/core/src/local/leveldb_index_manager.cc, Firestore/core/src/model/field_index.cc, Firestore/core/src/model/field_index.h
The crash was triggered by recent changes in standard library. In C++ priority queue library, it forces the item inside the queue to have strict order, which means when A > B, B < A is true. 
Reference  standard library code:
```C++
template <class _Tp, class _Up>
_LIBCPP_CONSTEXPR_SINCE_CXX14 _LIBCPP_HIDE_FROM_ABI bool operator()(_Tp& __x, _Up& __y) {
bool __r = __comp_(__x, __y);
if (__r)
__do_compare_assert(0, __y, __x);
return __r;
}
```
However, in customized compare function for FieldIndex, it only compares sequence_number and collection_group, which leads to two Field Index could potentially evaluate to equal. 
Hence this PR add a unique identifier to the field index to make sure they will never evaluate to equal. 
The fix can be verified by running `Firestore_Tests_iOS` in Xcode. …
=> Fix priority queue assertion which enforce the item to have strict order

FirebaseFunctions/Sources/Functions.swift, FirebaseFunctions/Sources/FunctionsError.swift, FirebaseFunctions/Sources/HTTPSCallableOptions.swift, FirebaseFunctions/Sources/Internal/FunctionsContext.swift
Added to each commit message is the corresponding snippet of code that it fixed.
Recommend ignoring whitespace: https://github.com/firebase/firebase-ios-sdk/pull/14597/files?diff=unified&w=1
#no-changelog
=> [Swift 6] Address low-hanging Swift concurrency errors in Functions

FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatStorage.swift, FirebaseCore/Internal/Sources/Utilities/AtomicBox.swift
Plan: Add AtomicBox to each module as needed as part of addressing Swift 6 warnings. Then, when we move to Xcode 16, delete all definitions of AtomicBox apart from the one defined in this PR, in FirebaseCoreInternal. Reason being is that Xcode 16 gives us Swift 6 support for `internal import FirebaseCoreInternal` in other product SDKs that can then get `AtomicBox`.
#no-changelog
=> [Swift 6] Add AtomicBox to CoreInternal

FirebaseAuth/Sources/Swift/Auth/Auth.swift
This property is a var but never mutated. Changing to let. Found while exploring Swift 6 changes.
#no-changelog
=> [NFC] Unmutated vars

Firestore/Source/API/FIRPipelineBridge+Internal.h, Firestore/Source/API/FIRPipelineBridge.mm, Firestore/Source/Public/FirebaseFirestore/FIRPipelineBridge.h, Firestore/Swift/Source/SwiftAPI/Expressions.swift, Firestore/Swift/Source/SwiftAPI/Stages.swift, Firestore/Swift/Tests/Integration/PipelineTests.swift, Firestore/core/src/api/aggregate_expressions.cc, Firestore/core/src/api/aggregate_expressions.h, Firestore/core/src/api/expressions.cc, Firestore/core/src/api/expressions.h, Firestore/core/src/api/ordering.cc, Firestore/core/src/api/ordering.h, Firestore/core/src/api/pipeline_result.h, Firestore/core/src/api/pipeline_snapshot.h, Firestore/core/src/api/stages.cc, Firestore/core/src/api/stages.h, Firestore/core/src/remote/datastore.cc, Firestore/core/src/remote/remote_objc_bridge.cc, Firestore/core/src/remote/remote_objc_bridge.h
1. Add stages and expressions in C++
2. Use FSTUserDataReader to read constants
=> Add C++ stages/expressions and Constant value support

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseVertexAI/Sources/VertexLog.swift
Added a warning message to the initializers of `GenerativeModel` and `ImagenModel` that is logged when the provided model name does not start with the expected prefix (`"gemini-"` for `GenerativeModel` and `"imagen-"` for `ImagenModel`). The warning message includes a link to the documentation for supported models.
Note: No error is thrown in case the naming scheme is changed in the future, though we would want to update the logic/message at that time.
=> [Vertex AI] Log warning for unsupported model names

Crashlytics/UnitTests/FIRCLSUtilityTests.m
* consolidates tests to make them easier to follow
* switches from `strcpy` to `snprintf` because `check.sh` complains about `strcpy`
I was hoping CI would run the tests because my machine is too old to run a new enough Xcode version.
=> consolidate FIRCLSRedactUUID tests for clarity

FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
The model name checks introduced in #14610 were checking that the model resource name, not the model name, started with `gemini-` or `imagen-`. This resulted in the log warning always being emitted since the model resource name (e.g., `projects/my-project-id/locations/us-central-1/publishers/google/models/gemini-2.0-flash`) never starts with `gemini-`.
This PR moves the check into `VertexAI` before the model name is converted to a model resource name. Also updated the parameter names in the `GenerativeModel` and `ImagenModel` constructors to be `modelResourceName` instead of `name` to _reduce_ confusion.
#no-changelog
=> [Vertex AI] Fix unsupported model name check introduced in #14610

Firestore/core/src/core/filter.h, Firestore/core/src/core/query.cc, Firestore/core/src/core/query.h, Firestore/core/test/unit/util/thread_safe_memoizer_testing.cc, Firestore/core/test/unit/util/thread_safe_memoizer_testing.h
This PR addresses some minor feedback in https://github.com/firebase/firebase-ios-sdk/pull/14300, the refactor of `ThreadSafeMemoizer` to fix the apparent "memory leak" detected by Xcode.
The changes are as follows:
1. Rename `CountingFunc::Next()` to `CountingFunc::NextFuncReturnValue()`.
2. Use `const` vectors for memoized values; that is, change `std::shared_ptr<std::vector<T>>` to `std::shared_ptr<const std::vector<T>>`.
3. Remove an obsolete inline comment about an implementation choice pertaining to the _old_ implementation of ThreadSafeMemoizer.
=> Firestore: minor tweaks to ThreadSafeMemozier code in response to code review feedback

FirebaseVertexAI/Sources/Types/Internal/APIConfig.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/CountTokensIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Utilities/InstanceConfig.swift, FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift, FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenGenerationRequestTests.swift, FirebaseVertexAI/Tests/Unit/Types/Internal/APIConfigTests.swift, FirebaseVertexAI/Tests/Unit/Types/Internal/Requests/CountTokensRequestTests.swift, FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
Updated `CountTokensIntegrationTests` and `GenerateContentIntegrationTests` to test against the `staging` endpoint in addition to the existing `prod` tests. This will allow us to catch any regressions before backend builds reach `prod`.
#no-changelog
=> [Vertex AI] Add integration tests for staging endpoint

.github/workflows/vertexai.yml
=> [Infra] Remove Xcode 15 CI

FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m
#no-changelog
See internal cl/744033535
=> [FCM] Fix cases of multiple stubs on the same method on a mock

.github/workflows/abtesting.yml
Reverts firebase/firebase-ios-sdk#14651
Temporary revert until Xcode 16.3 is ubiquitous
=> [Infra] Revert "Start Xcode 16.3 in CI"

FirebaseVertexAI/Tests/TestApp/Tests/Integration/CountTokensIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Utilities/IntegrationTestUtils.swift
- Fixed the `isEqual(to:accuracy:)` method in the `Numeric` extension
- This allowed the test to fail when token counts changed by 1
- Updated the `generateContentEnum` test with the count from the current tokenizer
- Migrated the `countTokens_jsonSchema` test to Swift Testing and parameterized to run in all supported environments
#no-changelog
=> [Vertex AI] Fix `countTokens` integration tests

.github/workflows/sessions.yml, FirebaseSessions/Sources/ApplicationInfo.swift, FirebaseSessions/Sources/EventGDTLogger.swift, FirebaseSessions/Sources/FirebaseSessions.swift, FirebaseSessions/Sources/GoogleDataTransport+GoogleDataTransportProtocol.swift, FirebaseSessions/Sources/Installations+InstallationsProtocol.swift, FirebaseSessions/Sources/Logger.swift, FirebaseSessions/Sources/NetworkInfo.swift, FirebaseSessions/Sources/SessionGenerator.swift, FirebaseSessions/Sources/SessionStartEvent.swift, FirebaseSessions/Sources/Settings/SettingsCacheClient.swift, FirebaseSessions/Sources/Settings/SettingsDownloadClient.swift, FirebaseSessions/Tests/TestApp/Shared/MockSubscriberSDK.swift, FirebaseSessions/Tests/Unit/Mocks/MockApplicationInfo.swift, FirebaseSessions/Tests/Unit/Mocks/MockInstallationsProtocol.swift, FirebaseSessions/Tests/Unit/Mocks/MockNetworkInfo.swift, FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
My plan: In the first pass, I'm going to use the explicit `internal` as a marker that I've audited the import. After I'm done migrating the `implementationOnly` -> `internal`, I can audit the un-prefixed `import` we have remaining as those may need to be marked `internal` or `public` (or are unused). After that audit, we can turn on internal by default.
#no-changelog
=> [Sessions] Migrate to import access modifiers

FirebaseFunctions/CHANGELOG.md, FirebaseFunctions/Sources/HTTPSCallable.swift, FirebaseFunctions/Tests/Integration/IntegrationTests.swift, FirebaseFunctions/Tests/ObjCIntegration/FIRIntegrationTests.m, FirebaseFunctions/Tests/Unit/FunctionsTests.swift
ObjC regression tests (after deflaking): https://github.com/firebase/firebase-ios-sdk/actions/runs/14314286364/job/40119407605?pr=14667
Fix #14653
=> [Functions] 'call' API's completion handler should be called on the main thread

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/ActionCode/ActionCodeInfo.swift, FirebaseAuth/Sources/Swift/ActionCode/ActionCodeURL.swift
Fix issue https://github.com/firebase/firebase-ios-sdk/issues/14664.
I was able to reproduce. Already tested and it's working.
=> Changed languageCode to lang in ActionCodeURL

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/ActionCode/ActionCodeInfo.swift, FirebaseAuth/Tests/Unit/AuthTests.swift
Fix for https://github.com/firebase/firebase-ios-sdk/issues/14665.
=> Changed actionCodeOperation types

.github/workflows/abtesting.yml, .github/workflows/analytics.yml, .github/workflows/appdistribution.yml, .github/workflows/archiving.yml, .github/workflows/auth.yml, .github/workflows/check.yml, .github/workflows/client_app.yml, .github/workflows/cocoapods-integration.yml, .github/workflows/combine.yml, .github/workflows/core.yml, .github/workflows/core_extension.yml, .github/workflows/core_internal.yml, .github/workflows/crashlytics.yml
This change adds the `workflow_dispatch` trigger to the following workflow files:
- .github/workflows/abtesting.yml
- .github/workflows/analytics.yml
- .github/workflows/appdistribution.yml
- .github/workflows/archiving.yml
- .github/workflows/auth.yml
- .github/workflows/check.yml
- .github/workflows/client_app.yml
- .github/workflows/cocoapods-integration.yml
- .github/workflows/combine.yml
- .github/workflows/core.yml
- .github/workflows/core_extension.yml
- .github/workflows/core_internal.yml
- .github/workflows/crashlytics.yml
This allows these workflows to be manually triggered in addition to their existing triggers.
=> [Infra] Add `workflow_dispatch` trigger to enable manual dispatch of workflows.

.github/workflows/core.yml, .github/workflows/core_extension.yml, .github/workflows/core_internal.yml, FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift
=> [Infra] Move 'core' workflow to Xcode 16

.github/workflows/functions.yml, FirebaseFunctions/Sources/Functions.swift
=> [Infra] Move 'functions' workflow to Xcode 16

.github/workflows/api_diff_report.yml, .github/workflows/danger.yml, .github/workflows/database.yml, .github/workflows/dynamiclinks.yml, .github/workflows/firebase_app_check.yml, .github/workflows/firebasepod.yml, .github/workflows/functions.yml, .github/workflows/generate_issues.yml, .github/workflows/health-metrics-presubmit.yml, .github/workflows/inappmessaging.yml, .github/workflows/installations.yml, .github/workflows/messaging.yml, .github/workflows/mlmodeldownloader.yml, .github/workflows/performance-integration-tests.yml, .github/workflows/performance.yml, .github/workflows/remoteconfig.yml, .github/workflows/sessions-integration-tests.yml, .github/workflows/sessions.yml, .github/workflows/shared-swift.yml, .github/workflows/spectesting.yml, .github/workflows/spm.yml, .github/workflows/storage.yml, .github/workflows/symbolcollision.yml, .github/workflows/update-cpp-sdk-on-release.yml, .github/workflows/watchos-sample.yml
Follow-up to #14682. Synced local main and realized Jules missed a good bit of updates.
#no-changelog
=> [Infra] Follow-up to #14682

.github/workflows/mlmodeldownloader.yml, FirebaseMLModelDownloader/Sources/DeviceLogger.swift, FirebaseMLModelDownloader/Sources/DownloaderUserDefaults.swift, FirebaseMLModelDownloader/Sources/LocalModelInfo.swift, FirebaseMLModelDownloader/Sources/ModelDownloadTask.swift, FirebaseMLModelDownloader/Sources/ModelDownloader.swift, FirebaseMLModelDownloader/Tests/Integration/ModelDownloaderIntegrationTests.swift, FirebaseMLModelDownloader/Tests/Unit/ModelDownloaderUnitTests.swift
=> [Infra] Move 'mlmodeldownloader' workflow to Xcode 16

.github/workflows/performance.yml
=> [Infra] Move 'performance' workflow to Xcode 16

FirebaseVertexAI/Sources/GenerativeModel.swift, FirebaseVertexAI/Sources/Types/Internal/Requests/CountTokensRequest.swift, FirebaseVertexAI/Sources/VertexAI.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/CountTokensIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Utilities/InstanceConfig.swift, FirebaseVertexAI/Tests/Unit/ChatTests.swift, FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift, FirebaseVertexAI/Tests/Unit/Types/Internal/Requests/CountTokensRequestTests.swift
Added support for `countTokens` using the Developer API through the Vertex AI in Firebase (`firebasevertexai.googleapis.com`) backend. This combination is an edge case where the model resource name (e.g., `projects/my-project/models/gemini-2.0-flash`) in the `countTokens` request URL differs from the resource name in the request field [`CountTokensRequest.generateContentRequest.name`](https://ai.google.dev/api/tokens#request-body). The integration tests have been updated to perform a `countTokens` request using both `firebasevertexai.googleapis.com` (Vertex AI and Developer API) and `generativelanguage.googleapis.com` (Developer API only) to ensure no regressions.
#no-changelog
=> [Vertex AI] Add `countTokens` support for Developer API via VinF

FirebaseVertexAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/ImagenIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/TestHelpers.swift, FirebaseVertexAI/Tests/TestApp/VertexAITestApp.xcodeproj/project.pbxproj
Avoid password request overflows to the backend
#no-changelog
=> Minimize signins in VertexAI integration tests

FirebaseSessions/Tests/TestApp/Shared/AppQualityDevAppApp.swift
Fixes runtime exception: `SwiftUI/App.swift:132: Fatal error: apps must be value types; AppQualityDevAppApp is a class.`
This exception was obscured in this failing log: https://github.com/firebase/firebase-ios-sdk/actions/runs/14370249342/job/40291840387?pr=14698
#no-changelog
=> [Sessions] Fix test app crash

.github/workflows/firestore.yml, Firestore/Swift/Source/Codable/DocumentID.swift
=> [Infra] Move 'firestore' workflow to Xcode 16

Firestore/CHANGELOG.md, Firestore/Example/Tests/Integration/API/FIRQueryTests.mm, Firestore/core/src/core/field_filter.cc, Firestore/core/src/core/not_in_filter.cc, Firestore/core/test/unit/core/query_test.cc
Server does not include `null` values into the query results when calling on `isNotEqualTo` or `notIn` filters.  SDK should be consistent with it.
=> fix: remove null value inclusion from `isNotEqualTo` and `notIn` filter results

.github/workflows/storage.yml, FirebaseStorage/Sources/Internal/StorageTokenAuthorizer.swift, FirebaseStorage/Sources/Storage.swift, FirebaseStorage/Sources/StorageUploadTask.swift, scripts/build.sh
=> [Infra] Migrate Storage CI to Xcode 16

FirebaseVertexAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/SchemaTests.swift, FirebaseVertexAI/Tests/TestApp/VertexAITestApp.xcodeproj/project.pbxproj
=> [vertexai] File for Schema integration tests

.github/workflows/messaging.yml
Attempting to fix the CI failure from the messaging nightly (#14661) which is attempting to run on `macos-13`: https://github.com/firebase/firebase-ios-sdk/actions/runs/14438577257/job/40483828819
#no-changelog
=> [Infra] Remove `macos-13` from `messaging-cron-only` job

FirebaseVertexAI/Sources/Types/Public/Schema.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/SchemaTests.swift
Add support for `title`, `propertyOrdering`, `minimum` and `maximum` schema specifications,
`title` and `propertyOrdering` are only hints so we only test that they get recognized. `propertyOrdering` did do the right thing when I examined the generated JSON in the debugger.
#no-changelog Changelog will come after a series of Schema PRs
=> [VertexAI] Add minimum, maximum, title, and propertyOrdering to schema

scripts/xcresult_logs.py
Added `--legacy` to the invocation of `xcresulttool` to temporarily fix the following error: 
```
xcrun xcresulttool get --path /Users/runner/Library/Developer/Xcode/DerivedData/FirebaseCombineSwift-gkzikpntrmtrlteyoawsixkbxldq/Logs/Test/Test-FirebaseCombineSwift-Unit-integration-2025.04.15_07-24-19-+0000.xcresult --format json
Error: This command is deprecated and will be removed in a future release, --legacy flag is required to use it.
Usage: xcresulttool get object [--legacy] --path <path> [--id <id>] [--version <version>] [--format <format>]
See 'xcresulttool get object --help' for more information.
```
Note: We'll need to find an alternative eventually since "command is deprecated and will be removed in a future release".
(cherry picked from commit …
=> [Infra] Add `--legacy` flag to `xcresulttool`

.github/workflows/firestore.yml, scripts/build.sh
=> [Infra] Fail on Xcode 15 builds

FirebaseVertexAI/Tests/TestApp/Tests/Integration/CountTokensIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Utilities/InstanceConfig.swift
Temporarily disabled the Developer API integration test configurations that are using the Firebase proxy; failing due to a backend issue.
#no-changelog
=> [Vertex AI] Temporarily disable proxied Dev API integration tests

FirebaseVertexAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Utilities/InstanceConfig.swift
Re-enabled Developer API integration tests through the staging proxy.
#no-changelog
=> [Vertex AI] Re-enable Developer API staging integration tests

Package.swift
Update Firestore binaries for the 11.12.0 release.
#no-changelog
=> [Release] Firestore binaries for `11.12.0`

.github/workflows/database.yml, scripts/xcresult_logs.py
PR #14717 didn't cover the following codepath: https://github.com/firebase/firebase-ios-sdk/blob/3636aa7b7d5793584c0757897fd59a7059053f20/scripts/xcresult_logs.py#L220-L229
In this case the `--legacy` flag wasn't getting added, resulting in the failures in #14661 (e.g., https://github.com/firebase/firebase-ios-sdk/actions/runs/14510030575/job/40734103865#step:10:9303). Moving the `--legacy` flag into `xcresulttool_json(...)` should fix the remaining failures.
#no-changelog
=> [Infra] Move `--legacy` flag into `xcresulttool_json` function

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json, ReleaseTooling/CarthageJSON/FirebaseVertexAIBinary.json
Updated the Carthage artifacts for the M163 / https://github.com/firebase/firebase-ios-sdk/releases/tag/11.12.0.
<details>
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseABTestingBinary.json" "11.12.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAdMobBinary.json" "11.12.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "11.12.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppCheckBinary.json" "11.12.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppDistributionBinary.json" "11.12.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" "11.12.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashly …
```
=> [Release] Carthage updates for M163 / 11.12.0

FirebaseVertexAI/CHANGELOG.md, FirebaseVertexAI/Sources/ModalityTokenCount.swift, FirebaseVertexAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseVertexAI/Tests/TestApp/Tests/Utilities/InstanceConfig.swift, FirebaseVertexAI/Tests/Unit/Types/ModalityTokenCountTests.swift
Decodes `ModalityTokenCount.tokenCount` as `0` when it is not returned in the response. This fixes #14745.
Context: When the backend sets a `tokenCount` of `0` for a `ContentModality` in a `ModalityTokenCount`, the `tokenCount` field is omitted from the JSON response since `0` is the default value. This results in a `DecodingError.keyNotFound` when decoding the `tokenCount`.
#no-changelog
=> [Vertex AI] Fix decoding `ModalityTokenCount` when `tokenCount` is 0

.github/workflows/abtesting.yml, .github/workflows/appdistribution.yml, .github/workflows/auth.yml, .github/workflows/common.yml, .github/workflows/core.yml, .github/workflows/core_internal.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/dynamiclinks.yml, .github/workflows/firebase_app_check.yml, .github/workflows/inappmessaging.yml, .github/workflows/installations.yml, .github/workflows/messaging.yml, .github/workflows/mlmodeldownloader.yml, .github/workflows/performance.yml, .github/workflows/remoteconfig.yml, .github/workflows/sessions.yml, .github/workflows/shared-swift.yml, .github/workflows/storage.yml, .github/workflows/vertexai.yml
Create a re-usable workflow for our spm jobs. This helps consolidate our Xcode/macos testing strategy for our spm jobs.
#no-changelog
=> [Infra] Create common SPM-focused reusable workflow

FirebaseRemoteConfig/Swift/PropertyWrapper/RemoteConfigValueObservable.swift
The `-[FIRRemoteConfig configValueForKey:]` has been called twice in situations where this could have been avoided and an already existing local variable could be used instead.
=> Re-use local variable to avoid extra `FIRRemoteConfig` accesses in `RemoteConfigValueObservable`

.github/workflows/abtesting.yml, .github/workflows/appdistribution.yml, .github/workflows/auth.yml, .github/workflows/common_catalyst.yml, .github/workflows/core.yml, .github/workflows/core_internal.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/firebase_app_check.yml, .github/workflows/installations.yml, .github/workflows/messaging.yml, .github/workflows/mlmodeldownloader.yml, .github/workflows/performance.yml, .github/workflows/remoteconfig.yml, .github/workflows/sessions.yml, .github/workflows/storage.yml
=> [Infra] Add re-usable workflow for catalyst jobs

Firestore/Example/Tests/Integration/API/FIRCompositeIndexQueryTests.mm, Firestore/Example/Tests/Integration/API/FIRQueryTests.mm, Firestore/Example/Tests/Util/FSTIntegrationTestCase.h, Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm, Firestore/Swift/Tests/Integration/QueryIntegrationTests.swift, Firestore/Swift/Tests/Integration/VectorIntegrationTests.swift
Ports https://github.com/firebase/firebase-android-sdk/pull/6841 to iOS.
#no-changelog
=> Improve the integration test coverage for online vs offline comparisons.

.github/workflows/auth.yml, .github/workflows/common.yml, .github/workflows/database.yml, .github/workflows/functions.yml, .github/workflows/installations.yml, .github/workflows/messaging.yml, .github/workflows/performance.yml, .github/workflows/remoteconfig.yml, .github/workflows/sessions.yml, .github/workflows/shared-swift.yml, .github/workflows/spm.yml, .github/workflows/storage.yml, .github/workflows/symbolcollision.yml
Especially focusing on integration tests
=> Run more CI on Xcode 16.3

FirebaseAI/Sources/FirebaseAI.swift, FirebaseAI/Tests/TestApp/Tests/Utilities/InstanceConfig.swift, FirebaseAI/Tests/TestApp/VertexAITestApp.xcodeproj/project.pbxproj, FirebaseAI/Tests/Unit/VertexComponentTests.swift, Package.swift, scripts/build.sh
- Added a new `library` for `FirebaseAI` to the public `products` in `Package.swift`.
- Re-ordered Package.swift to put `FirebaseAI` in alphabetical order (`FirebaseVertexAI` kept nearby but will be removed in a breaking change).
- Updated the integration test app to depend on the new library.
- Renamed the internal static function `firebaseAI` to `createInstance` in `FirebaseAI`.
- This was intended for the previous PR but missed it in my local client. This addresses the Gemini finding in #14765:
**Naming Consistency**: The naming of the internal initializer `firebaseAI(app:location:apiConfig:)` in `FirebaseAI.swift` is a bit confusing, as it shares the same name as the public API. Consider renaming the internal initializer to something more descriptive, like `createFirebaseAIInstance`.
=> [Firebase AI] Add Swift package product library `FirebaseAI`

FirebaseAI/Sources/AILog.swift, FirebaseAI/Sources/FirebaseAI.swift, FirebaseAI/Sources/GenerateContentResponse.swift, FirebaseAI/Sources/GenerativeAIService.swift, FirebaseAI/Sources/GenerativeModel.swift, FirebaseAI/Sources/ModalityTokenCount.swift, FirebaseAI/Sources/Protocols/Internal/CodableProtoEnum.swift, FirebaseAI/Sources/Safety.swift, FirebaseAI/Sources/Types/Internal/ProtoDate.swift, FirebaseAI/Sources/Types/Public/Imagen/ImagenGenerationResponse.swift, FirebaseAI/Sources/Types/Public/Imagen/ImagenImageFormat.swift, FirebaseAI/Sources/Types/Public/Schema.swift
=> Renames for console logging

FirebaseFunctions/Sources/Functions.swift, FirebaseFunctions/Sources/Internal/FunctionsSerializer.swift
Note: module is not yet 100% Swift 6 compliant.
1. This was the first error I sought to fix.
2. I added `@MainActor` so the compiler enforces that the completion handler can only be called on the main actor. This address the error in step 1.
3. The new `@MainActor` attribute needed to bubble up to signature of a function that called the first one.
4. Next, the compiler enforces the completion is only called on main actor.
5. That's fixable by wrapping in a main queue dispatch block.
6. The next appears back in the first function that was changed. The source of the error is that line 487 returns a `HTTPSCallableResult` which is not Sendable, so sending it could cause data races.
7. It doesn't seem safe to mark `HTTPSCallableResult` as Sendable (it would have to be unchecked) because it …
=> [Functions] Address more Swift 6 warnings

FirebaseAI/README.md, FirebaseAI/Sample/README.md, FirebaseAI/Sources/Constants.swift, FirebaseAI/Sources/FirebaseAI.swift, FirebaseAI/Sources/FirebaseInfo.swift, FirebaseAI/Sources/GenerativeModel.swift, FirebaseAI/Sources/Types/Internal/APIConfig.swift, FirebaseAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseAI/Tests/Unit/GenerativeModelTests.swift, FirebaseAI/Tests/Unit/README.md, FirebaseAI/Tests/Unit/Snippets/README.md
Also remove the no longer tested Swift 5.x specific code
#no-changelog
=> [Firebase AI] More naming updates

FirebaseAI/Sources/GenerateContentResponse.swift, FirebaseAI/Tests/Unit/Types/CitationMetadataTests.swift, FirebaseAI/Tests/Unit/Types/CitationTests.swift
Added support for decoding `CitationMetadata` in the format returned by Google AI in addition to the existing Vertex AI support. They differ in the name of the citations field (`citationSources` in Google AI and `citations` in Vertex AI).
#no-changelog
=> [Firebase AI] Add handling for Google AI-formatted `CitationMetadata`

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/Components/FIRCLSContext.h, Crashlytics/Crashlytics/Components/FIRCLSContext.m, Crashlytics/Crashlytics/Controllers/FIRCLSContextManager.h, Crashlytics/Crashlytics/Controllers/FIRCLSContextManager.m, Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m, Crashlytics/UnitTests/FIRCLSContextManagerTests.m, Crashlytics/UnitTests/FIRCLSOnDemandModelTests.m, Crashlytics/UnitTests/FIRRecordExceptionModelTests.m, Crashlytics/UnitTests/Mocks/FIRCLSMockReportManager.m
Covert `dispatch_group_wait `to use `promise` to avoid blocking on main
Profiling and verified `FIRCLSContextInit` is gone from main call stack trace: https://screenshot.googleplex.com/8hPfVTxvxnh9X2b
Related issues: #13675 #13232
=> Make Crashlytics context Init unblocking main

.github/workflows/firestore.yml
Update build tests for Xcode 16.3 especially after report in #14643
=> [Firestore] Update CI tests to Xcode 16.3

FirebaseAI/Sources/AILog.swift, FirebaseAuth/Sources/Swift/User/User.swift, FirebaseAuth/Tests/Unit/ActionCodeURLTests.swift, FirebaseFunctions/Sources/Callable+Codable.swift, FirebaseFunctions/Sources/Functions.swift, FirebaseFunctions/Sources/HTTPSCallable.swift, scripts/style.sh
Fixed the `style.sh` script to run on Linux. The `check` workflow now runs on Ubuntu and was ignoring Swift style issues since the script checked `"$system" == 'Darwin'`.
#no-changelog
=> Investigate swiftformat on Linux CI

.github/workflows/combine.yml, FirebaseCombineSwift/Tests/Integration/Storage/StorageIntegration.swift, scripts/build.sh
Trying to fix the failures in the Combine nightlies. I've tried but have been unable to reproduce.
Update –– Was reproducing a crash locally. Traced it back to an assertion Combine API that was checking for errors. The 18.4 sim's networking is flaky and the pipeline assertion crashes the testing suite. Moving down to 18.3.1 sim for testing.
Fix #14787
=> [Infra] Use 18.3.1 simulator for Combine integration tests

FirebaseAI.podspec, FirebaseAI/Tests/Unit/ChatTests.swift, FirebaseAI/Tests/Unit/Fakes/AppCheckInteropFake.swift, FirebaseAI/Tests/Unit/GenerativeModelGoogleAITests.swift, FirebaseAI/Tests/Unit/GenerativeModelTests.swift, FirebaseAI/Tests/Unit/GenerativeModelVertexAITests.swift, FirebaseAI/Tests/Unit/TestUtilities/GenerativeModelTestUtil.swift, Package.swift
Split `GenerativeModelTests` into `GenerativeModelGoogleAITests` and `GenerativeModelVertexAITests` to test against the two sets of [mock responses](https://github.com/FirebaseExtended/vertexai-sdk-test-data/tree/main/mock-responses) for the Google AI and Vertex AI backends.
#no-changelog
=> [Firebase AI] Add `GenerativeModel` tests using Dev API mock responses

FirebaseAI/CHANGELOG.md, FirebaseAI/Sources/GenerateContentResponse.swift, FirebaseAI/Sources/Safety.swift, FirebaseAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseAI/Tests/Unit/GenerativeModelVertexAITests.swift
Added handling for empty `SafetyRating` values in responses. This may occur during image generation using `gemini-2.0-flash-exp` where the backend (Vertex AI only) returns additional empty `SafetyRating` objects in the `safetyRatings` array (i.e., `{}, {}, {}, {}`). See https://github.com/FirebaseExtended/vertexai-sdk-test-data/pull/37 for more details.
=> [Firebase AI] Add workaround for invalid SafetyRatings in response

Crashlytics/CHANGELOG.md, FirebaseRemoteConfig/CHANGELOG.md
Removed AI changelog versioning bump as that is being handled in #14805
=> [Release] Changelogs bump for M164

FirebaseAI/Sources/FirebaseAI.swift, FirebaseAI/Sources/GenerateContentResponse.swift, FirebaseAI/Sources/GenerativeModel.swift, FirebaseAI/Sources/ModelContent.swift, FirebaseAI/Tests/TestApp/Sources/Constants.swift, FirebaseAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseAI/Tests/Unit/GenerativeModelVertexAITests.swift
Added support for [Gemma models](https://ai.google.dev/gemma/docs/get_started#models-list) in the Firebase AI SDK when using the [Gemini Developer API](https://ai.google.dev/gemma/docs/core/gemma_on_gemini_api).
Note: These models are primarily intended for [testing](https://ai.google.dev/gemma/docs/get_started#gemma-in-ais).
#no-changelog
=> [Firebase AI] Add support for Gemma models with Developer API

FirebaseAI/Sources/Constants.swift, FirebaseAI/Tests/TestApp/Sources/Constants.swift, FirebaseAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, scripts/quickstart_spm_xcodeproj.sh
Updated the error domain (for use with `NSError`) from `com.google.firebase.vertexai` to `com.google.firebase.firebaseai` to reflect the new SDK name.
Notes:
- Updated integration tests to use Gemma 4B instead of 27B (seems to have better availability).
- Updated `scripts/quickstart_spm_xcodeproj.sh` to set `FIREBASECI_USE_LATEST_GOOGLEAPPMEASUREMENT`.
#no-changelog
=> [Firebase AI] Update error domain constant for renamed SDK

FirebaseAuth/Sources/Swift/ActionCode/ActionCodeInfo.swift, FirebaseAuth/Sources/Swift/ActionCode/ActionCodeOperation.swift, FirebaseAuth/Sources/Swift/ActionCode/ActionCodeSettings.swift, FirebaseAuth/Sources/Swift/ActionCode/ActionCodeURL.swift, FirebaseCore/Internal/Sources/Utilities/FIRAllocatedUnfairLock.swift
Going to use the TODO tag `TODO(Swift 6 Breaking)` to keep track of Swift 6 related breaking changes that should be made.
#no-changelog
=> [Auth] Add Swift 6 conformance to `FirebaseAuth/Sources/Swift/ActionCode/` directory

.github/workflows/functions.yml, FirebaseFunctions/Sources/Callable+Codable.swift, FirebaseFunctions/Sources/FunctionsError.swift, FirebaseFunctions/Sources/HTTPSCallable.swift, FirebaseFunctions/Sources/Internal/FunctionsSerializer.swift, FirebaseFunctions/Tests/Integration/IntegrationTests.swift, FirebaseSharedSwift/Sources/third_party/FirebaseDataEncoder/FirebaseDataEncoder.swift
This PR gets Function to complete Swift 6 support.
Note: I did add a TODO in the Functions error handling. In theory, it should be okay, but in practice, it will be hard to get checked Sendable until `FunctionsSerializer` no longer returns `Any`. This appears feasible but it will take some more investigation and I'd prefer to circle back to it to focus on others areas of Swift 6 compliance.
Reasoning for changes in `FirebaseFunctions/Sources/HTTPSCallable.swift`: 
- The `sending` param attribute does not bridge to ObjC. Even passing an immutable type from ObjC crashed the integration tests. To workaround, I'm marking the existing signature ObjC-only and adding a new Swift-only function with the `sending` param. It should otherwise match the existing signature and not be a break to Swift 5 …
=> [Functions] Complete Swift 6 support

Firestore/Swift/Source/SwiftAPI/Stages.swift
In SPM, the Swift `FirebaseFirestore` actually depends on `FirebaseFirestoreInternalWrapper`, not `FirebaseFirestoreInternal`.
#no-changelog
=> [Firestore] On SPM, import FirebaseFirestoreInternalWrapper

FirebaseAuth/Sources/Swift/SystemService/AuthAPNSToken.swift, FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift, FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenType.swift, FirebaseAuth/Sources/Swift/SystemService/AuthAppCredential.swift, FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift, FirebaseAuth/Tests/Unit/AuthAPNSTokenManagerTests.swift, FirebaseAuth/Tests/Unit/AuthTests.swift, FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
Incremental progress. Adding some TODOs for follow-up work. 
#no-changelog
=> [Auth] Add Swift 6 conformance to `FirebaseAuth/Sources/Swift/SystemService/` directory

.github/workflows/firebaseai.yml, scripts/build.sh
- Added a step in the `testapp-integration` job of the `firebaseai` workflow to upload the raw `xcodebuild` log on failure to help with debugging.
- Context: `xcbeautify` filters out a lot of the important details in parameterized Swift Testing-based tests.
- Split the `xcodebuild.log` into `build` and `test` logs. The test log is a fraction of the size so it's easier to see the test failures when split.
- Followed the `xcbeautify` guidance for piping the output https://github.com/cpisciotta/xcbeautify#usage.
#no-changelog
=> [Firebase AI] Upload `xcodebuild` logs in integration tests

.github/workflows/firebaseai.yml, FirebaseAI/CHANGELOG.md
Updated `FirebaseAI` changelog to use the latest wording.
=> [Firebase AI] Update CHANGELOG entry wording

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/Auth/AuthComponent.swift, FirebaseAuth/Sources/Swift/Storage/AuthKeychainServices.swift, FirebaseAuth/Sources/Swift/Storage/AuthKeychainStorage.swift, FirebaseAuth/Sources/Swift/Storage/AuthKeychainStorageReal.swift, FirebaseAuth/Sources/Swift/Storage/AuthUserDefaults.swift, FirebaseAuth/Tests/Unit/AuthKeychainServicesTests.swift, FirebaseAuth/Tests/Unit/AuthTests.swift, FirebaseAuth/Tests/Unit/Fakes/FakeAuthKeychainStorage.swift, FirebaseAuth/Tests/Unit/UserTests.swift
Also, remove some unused code and some light refactoring 
Fix #14835
#no-changelog
=> [Auth] Conform 'AuthKeychainServices' to 'Sendable'

FirebaseSessions/Sources/SessionInitiator.swift, FirebaseSessions/Tests/Unit/Mocks/MockSubscriber.swift
=> [Sessions] Remove Swift 5.9 guard statements

FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift, FirebaseAuth/Sources/Swift/MultiFactor/MultiFactorInfo.swift, FirebaseAuth/Sources/Swift/MultiFactor/MultiFactorSession.swift, FirebaseAuth/Sources/Swift/MultiFactor/Phone/PhoneMultiFactorInfo.swift, FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPMultiFactorInfo.swift
=> [Auth] More Swift 6 progress

Dangerfile
Updated the `Dangerfile` to set the label `api: firebaseai` when there are changes in the `FirebaseAI` or `FirebaseVertexAI` directories.
#no-changelog
=> [CI] Update `Dangerfile` to set `api: firebaseai` label

.github/workflows/remoteconfig.yml
I propose doing the following:
- on macos-14, test with Xcode 16.2 (represents min. macos x min. Xcode)
- on macos-15, test with latest Xcode available on runners
#no-changelog
=> [Infra] Update Xcode versions in remoteconfig.yml

.github/workflows/firebaseai.yml, scripts/quickstart_spm_xcodeproj.sh
Updated the `quickstart_spm_xcodeproj.sh` script to replace the `minimumVersion` requirement for the `firebase-ios-sdk` SPM dependency to a `branch` requirement. This is used to test that the `FirebaseAI` quickstart builds against the PR's branch or `main` for scheduled jobs. 
#no-changelog
=> [Firebase AI] Run quickstart build test using branch

FirebaseAnalytics.podspec, FirebaseAnalyticsCoreWrapper/dummy.m, FirebaseAnalyticsCoreWrapper/include/dummy.h, FirebaseAnalyticsIdentitySupportWrapper/dummy.m, FirebaseAnalyticsIdentitySupportWrapper/include/dummy.h, FirebaseAnalyticsOnDeviceConversionWrapper/dummy.m, FirebaseAnalyticsWithoutAdIdSupportWrapper/dummy.m, GoogleAppMeasurement.podspec, Package.swift, SwiftPM-PlatformExclude/FirebaseAnalyticsCoreWrap/dummy.m, SwiftPM-PlatformExclude/FirebaseAnalyticsCoreWrap/include/dummy.h
The new subspecs: Default, Core, and IdentitySupport.
The previous subspecs that are now deprecated: AdIdSupport (use IdentitySupport) and WithoutAdIdSupport (use Core).
#no-changelog
=> New and clearer FirebaseAnalytics subspecs

ReleaseTooling/Template/README.md
=> [Infra] Update template README with new min. supported Xcode version

ReleaseTooling/Sources/ZipBuilder/CocoaPodUtils.swift
This should pull in the new `GoogleAdsOnDeviceConversion.xcframework` in the `FirebaseAnalytics/` of the `Firebase.zip`. Without this PR, `GoogleAdsOnDeviceConversion` is not found when doing a transitive dependency search because the dictionary used to store the dependency graph is keyed by root specs names instead of subspec names, which the dependency names being indexed are the subspec names. The fix was index with the root spec name instead of the subspec name.
Debug commands:
- For building Analytics:
```
swift run --package-path ReleaseTooling zip-builder \
--pods FirebaseAnalytics \
--platforms ios
--local-podspec-path /Users/nickcooke/Developer/firebase-ios-sdk \
--custom-spec-repos https://github.com/firebase/SpecsStaging.git https://github.com/firebase/SpecsDev.git \ …
```
=> [Infra] Fix logic used to find transitive dependencies

.github/workflows/abtesting.yml, .github/workflows/appdistribution.yml, .github/workflows/auth.yml, .github/workflows/common.yml, .github/workflows/common_cocoapods.yml, .github/workflows/core.yml, .github/workflows/core_extension.yml, .github/workflows/core_internal.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/dynamiclinks.yml, .github/workflows/firebase_app_check.yml, .github/workflows/firebaseai.yml, .github/workflows/functions.yml, .github/workflows/inappmessaging.yml, .github/workflows/messaging.yml, .github/workflows/performance.yml, .github/workflows/remoteconfig.yml, .github/workflows/sessions.yml, .github/workflows/shared-swift.yml, .github/workflows/storage.yml, .github/workflows/vertexai.yml, FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m
I'd like to refactor down our workflows to:
- consolidate where we are still using CocoaPods
- standardize Xcode versioning strategy across all workflows (See [comment](https://github.com/firebase/firebase-ios-sdk/pull/14869#issue-3077394150))
- reduce the amount of custom Xcode configuration (ideally it will only be done in a few files)
For follow-up work, there are a couple products's workflows that still need to be migrated.
=> [Infra] Common cocoapods pod lib lint job

.github/workflows/installations.yml
=> [Infra] Make firebaseinstallations.yml use reusable CocoaPods workflow

README.md, SwiftPackageManager.md
=> [Docs] Update min. Xcode version in README.md and SwiftPackageManager.md

FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift
Re-added the `import Foundation` in `SecureTokenService.swift` to resolve an error when building in google3 (stricter enforcement of directly importing what we use). Context: `Foundation` is needed for `NSObject` in `SecureTokenService`.
#no-changelog
=> [Auth] Re-add `import Foundation` in `SecureTokenService.swift`

FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m
Added a skip to the test because the stubbing of an already stubbed method is setting off alarms with other tooling.
https://github.com/firebase/firebase-ios-sdk/issues/14922
=> Skip test due to being a bad test

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAIBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json, ReleaseTooling/CarthageJSON/FirebaseVertexAIBinary.json
Updated the Carthage artifacts for the M165 / https://github.com/firebase/firebase-ios-sdk/releases/tag/11.14.0.
<details>
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseABTestingBinary.json" "11.14.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAIBinary.json" "11.14.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAdMobBinary.json" "11.14.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "11.14.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsOnDeviceConversionBinary.json" "11.14.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppCheckBinary.json" "11.14.0"
binary …
```
=> [Release] Carthage updates for M165 / 11.14.0

Carthage.md
Added `FirebaseAIBinary.json` and `FirebaseVertexAIBinary.json` to the `Cartfile` sample.
#no-changelog
=> [Firebase AI] Add Firebase AI Logic SDK to Carthage docs

FirebaseAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift
Since Gemini 1.5 Pro is now [retired](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions#expandable-1), upgraded to Gemini 2.0 Flash in the integration tests.
Note: Only found one instance of a Gemini 1.x model in the tests.
#no-changelog
=> [Firebase AI] Upgrade Gemini 1.x models in integration tests 

Firestore/core/test/unit/util/async_queue_test.cc
I’ve reviewed the codebase for any references to this typo and couldn’t find any. However, if this test name is being used externally, such as in CI filters, dashboards, scripts, or other tools, please let me know so I can make the necessary updates.
Thanks!
=> fix: a typo in CanSchedule`Operations`WithRespectsToShutdownState

FirebaseABTesting.podspec, FirebaseAppCheck.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCore/CHANGELOG.md, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestoreInternal.podspec, FirebaseFirestoreTestingSupport.podspec, FirebaseInstallations.podspec, FirebaseMLModelDownloader.podspec, FirebaseMessaging.podspec, FirebasePerformance.podspec, FirebaseRemoteConfig.podspec, FirebaseSessions.podspec, Package.swift
=> [Infra] Remove C99 language standard settings

ExchangeTokensRequestTests.swift, FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/Backend/AuthRequestConfiguration.swift, FirebaseAuth/Sources/Swift/Backend/IdentityToolkitRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/ExchangeTokenRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/ExchangeTokenResponse.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/AppManager.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Models/AuthMenu.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AuthViewController.swift, FirebaseAuth/Tests/Unit/IdentityToolkitRequestTests.swift
This PR introduces a new API for exchanging tokens with Firebase, supporting multi-tenancy through a `TenantConfig` struct. Key changes include:
*   **New `Auth` class:**
*   Provides a factory method `auth(app: FirebaseApp, tenantConfig: TenantConfig)` to create an `Auth` instance with a specific tenant configuration.
*   **`exchangeToken` function:**
*   Added an `async` function `exchangeToken(_ idToken: String, idpConfigId: String)` to handle token exchange asynchronously.
*   **`TenantConfig` struct:**
*   Defines the configuration for a specific tenant, including `location` and `tenantId`.
* **`AuthExchangeToken` struct:**
* Defines the structure of the token returned after the exchange.
*   Added `Auth` class with static method `auth(app: FirebaseApp, tenantConfig: TenantConfig) -> …
=> implementing regionalized auth and exchangeToken

FirebaseAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseAI/Tests/TestApp/Tests/Utilities/InstanceConfig.swift
Updated the Firebase AI Logic integration tests to cover the [`global`](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/locations#global-endpoint) endpoint in addition to the default (`us-central1`). Developers can use the `global` endpoint by specifying it as the location when using the Vertex AI backend:
```
let ai = FirebaseAI.firebaseAI(backend: .vertexAI(location: "global"))
```
#no-changelog
=> [Firebase AI] Add integration tests for `global` endpoint

FirebaseAI/CHANGELOG.md, FirebaseAI/Sources/Types/Internal/Requests/CountTokensRequest.swift, FirebaseAI/Tests/TestApp/Tests/Integration/CountTokensIntegrationTests.swift, FirebaseAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift, FirebaseAI/Tests/Unit/GenerativeModelVertexAITests.swift
Deprecated the `totalBillableCharacters` property on `CountTokensResponse` the concept of billable characters does not apply to Gemini 2.0 series models and newer. Billing is based on the token count returned in `totalTokens`. This property will always be `nil` for the Gemini Developer API backend. While it may be present for the Vertex AI backend, it should not be used for billing calculations. Resolves #14934.
=> [Firebase AI] Deprecate `CountTokensResponse.totalBillableCharacters`

FirebaseCore/Sources/FIROptions.m, FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h
Mentioned here: https://firebase.google.com/docs/dynamic-links/ios/create#specifying-a-custom-url-scheme-for-dynamic-links
=> [Core] Deprecate '-[FIROptions deepLinkURLScheme]' API

FirebaseCore/CHANGELOG.md, FirebaseCore/Sources/FIROptions.m, FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h, docs/FirebaseOptionsPerProduct.md
These have been deprecated since Firebase 10.4
=> [Core] Remove `Options.androidClientID` and `Options.trackingID`

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Swift/ActionCode/ActionCodeSettings.swift, FirebaseAuth/Sources/Swift/Backend/RPC/GetOOBConfirmationCodeRequest.swift, FirebaseAuth/Tests/Unit/GetOOBConfirmationCodeTests.swift, FirebaseAuth/Tests/Unit/ObjCAPITests.m, FirebaseAuth/Tests/Unit/RPCBaseTests.swift, FirebaseAuth/Tests/Unit/SwiftAPI.swift
Note, there is a public enum error case that maps to the `dynamicLinkDomain` that we never deprecated. It seems possible to deprecate cases individually, so I think we could do that as well?
=> [Auth] Remove 'ActionCodeSettings.dynamicLinkDomain'

ExchangeTokenRequestTests.swift, FirebaseAuth/Sources/Swift/Auth/Auth.swift, FirebaseAuth/Sources/Swift/Backend/AuthRequestConfiguration.swift, FirebaseAuth/Sources/Swift/Backend/RPC/IdentityPlatform/ExchangeTokenRequest.swift, FirebaseAuth/Sources/Swift/Backend/RPC/IdentityPlatform/ExchangeTokenResponse.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/AppManager.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Models/AuthMenu.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AuthViewController.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExampleUITests/AuthenticationExampleUITests.swift, FirebaseAuth/Tests/SampleSwift/AuthenticationExampleUITests/SettingsUITests.swift, FirebaseAuth/Tests/Unit/ExchangeTokenRequestTests.swift
This PR introduces support for Regional GCIP (R-GCIP) within the Firebase Auth iOS SDK. Developers can now initialize an `Auth` instance tied to a specific tenant ID and location.
The key changes are:
-   **New `TenantConfig` Struct:** A `Sendable` struct `TenantConfig` has been added to hold the `tenantId` and `location` (defaulting to "prod-global").
-   **New `Auth` Factory Method:** A new static method `Auth.auth(app: FirebaseApp, tenantConfig: TenantConfig)` allows initialization with R-GCIP parameters.
-   **Updated `AuthRequestConfiguration`:** The internal `AuthRequestConfiguration` class now includes `location` and `tenantId` properties, populated during initialization if a `TenantConfig` is provided.
These changes enable applications to work with regionalized Firebase …
=> Add support for R-GCIP tenant configuration

FirebaseStorage/CHANGELOG.md, FirebaseStorage/Sources/StorageMetadata.swift, FirebaseStorage/Tests/ObjCIntegration/ObjCAPITests.m
For Firebase 12 consideration:
- https://github.com/firebase/firebase-ios-sdk/issues/14834#issuecomment-3014652856
=> [Storage] Remove unused, long-deprecated 'StorageMetadata.storageReference' API`

FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
Error message suggested to not call `stopMocking` so I removed the call.
#no-changelog
=> [Infra] Fix RC nightly failure

Jules.md, agents.md
Add a baseline agents.md file for improved Jules and gemini CLI behaviour.
=> Create agents.md file for AI agent context

FirebaseAuth.podspec, FirebaseAuth/Tests/SampleSwift/AuthenticationExample.xcodeproj/project.pbxproj, FirebaseCore/CHANGELOG.md, FirebaseFunctions.podspec, FirebaseStorage.podspec, Package.swift
=> [Infra] Update `gtm-session-fetcher` to `~> 3.4, < 6.0`

FirebaseSessions/Sources/EventGDTLogger.swift, FirebaseSessions/Sources/GoogleDataTransport+GoogleDataTransportProtocol.swift, FirebaseSessions/Sources/SessionCoordinator.swift, FirebaseSessions/Tests/Unit/SessionCoordinatorTests.swift
=> [Infra] Sessions Xcode 26 beta warnings

FirebaseDatabase/Tests/Integration/FData.m
Disables testDeepUpdatesWork and testServerIncrementOverflowAndTypeCoercion in FData.m due to flakiness.
Comments updated to include TODO.
Ref: https://github.com/firebase/firebase-ios-sdk/issues/15103
Tests pass locally with the RTDB emulator running. Not sure what's going on when running on CI.
=> [Infra] Disable flaky integration tests

Firebase.podspec, Firestore/CHANGELOG.md
Restore after accidental removal in #15015
=> Restore pod Firebase/Firestore for tvOS

FirebaseSessions/Sources/Settings/SettingsCacheClient.swift
Hey there!
Found a raw print in my app, and turns out that this is located in Firebase code. I propose to use standard debug log here.
=> Do not log using raw print in SettingsCacheClient

Crashlytics/CHANGELOG.md, FirebaseAuth/CHANGELOG.md, Firestore/CHANGELOG.md
Per [b/434932656](https://b.corp.google.com/issues/434932656),
This updates the changelogs for the 12.1.0 release.
Will wait until tomorrow, just in case there's any last minute changes by EOD.
=> Update changelogs for 12.1.0

FirebaseInAppMessaging/Sources/Runtime/FIRIAMActionURLFollower.m, FirebaseInAppMessaging/Tests/Unit/FIRIAMActionUrlFollowerTests.m, FirebaseMessaging/Sources/FIRMessaging.m
Fixes a crash that occurs when launching an app linked with `FirebaseMessaging` and `FirebaseInAppMessaging` on iOS 18 devices or simulators when built with Xcode 26 Beta 4.
The crash was caused by referencing the symbol `NSUserActivityTypeBrowsingWeb`, which appears to be unavailable or unresolved at runtime when using the combination of Xcode 26 and iOS 18. Attempting to access this symbol directly results in a dyld crash:
```
dyld[27074]: Symbol not found: _NSUserActivityTypeBrowsingWeb
Referenced from: <7CB71490-F307-3C6E-853C-925749317C78> /private/var/containers/Bundle/Application/C7665515-F4B5-4EAA-B560-774A439A4F1E/Rulebook-Dev.app/Rulebook-Dev.debug.dylib
Expected in:     <050203DD-7488-307D-A999-E587314B041A> /System/Library/Frameworks/CoreServices.framework/CoreServices
Symbol …
```
=> [FirebaseMessaging] Fix crash on Xcode 26 + iOS 18

FirebaseInAppMessaging/Sources/Runtime/FIRIAMActionURLFollower.m, FirebaseInAppMessaging/Tests/Unit/FIRIAMActionUrlFollowerTests.m, FirebaseMessaging/CHANGELOG.md, FirebaseMessaging/Sources/FIRMessaging.m
=> [FirebaseMessaging] Fix Xcode 26 symbol crash

FirebaseAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift
Removed the `.civicIntegrity` safety setting from the Gemini `generateImage` integration test. [`HARM_CATEGORY_CIVIC_INTEGRITY`](https://cloud.google.com/vertex-ai/generative-ai/docs/reference/rest/v1beta1/HarmCategory#:~:text=HARM_CATEGORY_CIVIC,This%20item%20is%20deprecated!) is now deprecated on Vertex AI but requests are only rejected when using the `gemini-2.0-flash-preview-image-generation` model.
Note: I kept the `.civicIntegrity` setting enabled for the rest of the tests so that we get notified when it's deprecated in the Gemini Developer API as well. At that time we should mark the symbol deprecated in the SDK.
#no-changelog
=> [Firebase AI] Remove `.civicIntegrity` from `generateImage` test

FirebaseAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift, FirebaseAI/Tests/TestApp/Tests/Utilities/InstanceConfig.swift
- Added integration tests to verify that calls succeed in limited-use mode
- Verified manually that the TTL is 5 minutes
- Disabled the staging and proxy bypass integration test configs to reduce resource utilization
#no-changelog
=> [Firebase AI] Add App Check Limited-Use mode integration tests

ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift, ReleaseTooling/Sources/ZipBuilder/ModuleMapBuilder.swift
The module maps created by our XCFramework tooling use the spec name rather than the module name (some specs configure this via `s.module_name`). For example, `gRPC-C++.podspec` sets a module name of `grpcpp`. The problem with using `gRPC-C++` as a module name is that is contains invalid characters (`-`, `+`) in the module map language.
Plan: 
Fix https://github.com/google/grpc-binary/issues/22
=> fix(tooling): Use module name over spec name in XCFramework module maps

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/FIRRemoteConfig.m, FirebaseRemoteConfig/Sources/RCNConfigFetch.m
See resolved comment for explanation.
Fixes #15087
=> fix(config): Address race condition from concurrent network session recreation

FirebaseAuth/Tests/SampleSwift/AuthenticationExampleUITests/AuthenticationExampleUITests.swift, FirebaseAuth/Tests/SampleSwift/SwiftApiTests/PasskeyTests.swift, FirebaseAuth/Tests/Unit/GetAccountInfoTests.swift, FirebaseAuth/Tests/Unit/SetAccountInfoTests.swift
Adding End-to-End UI Tests in Authentication Example for Passkey
=> End-to-End UI Tests in Authentication Example for Passkey

FirebaseAI/CHANGELOG.md, FirebaseAI/Sources/FirebaseAI.swift, FirebaseAI/Sources/FirebaseInfo.swift, FirebaseAI/Sources/GenerativeAIService.swift, FirebaseAI/Sources/GenerativeModel.swift, FirebaseAI/Sources/Types/Public/Imagen/ImagenModel.swift, FirebaseAI/Tests/Unit/ChatTests.swift, FirebaseAI/Tests/Unit/GenerativeModelVertexAITests.swift, FirebaseAI/Tests/Unit/TestUtilities/GenerativeModelTestUtil.swift
Per [b/440086625](https://b.corp.google.com/issues/440086625),
This moves the `useLimitedUseAppCheckTokens` property into `FirebaseInfo`. This allows us to avoid needing to propagate down the parameter through model classes, since `FirebaseInfo` is already passed down.
For additional context, see [this discussion](https://github.com/firebase/firebase-ios-sdk/pull/15099#discussion_r2286330939) from the implementation PR.
Note that this PR also updates the `CHANGELOG.md` and docs on `useLimitedUseAppCheckTokens` to reflect the changes Rachel made internally. They now also point to the web page that will go live shortly before the release, which will contain a section detailing limited-use tokens and their usage.
#no-changelog
=> [FAL] Move useLimitedUseAppCheckTokens property into FirebaseInfo + Update docs

.github/workflows/abtesting.yml, .github/workflows/auth.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/firestore.yml, .github/workflows/functions.yml, .github/workflows/inappmessaging.yml, .github/workflows/messaging.yml, .github/workflows/performance.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/remoteconfig.yml, .github/workflows/storage.yml, .github/workflows/zip.yml
Remove unused env vars.
- firebase-ios-sdk:
```console
nickcooke@nickcooke-mac2 firebase-ios-sdk (nc/unused-env) % git grep -E "testing_repo|signin_secret|testing_repo_dir"
.github/workflows/generate_issues.yml:    - '.github/actions/testing_report_generation**'
.github/workflows/generate_issues.yml:      uses: ./.github/actions/testing_report_generation/
.github/workflows/generate_issues.yml:      uses: ./.github/actions/testing_report_generation/
```
- quickstart:
```console
nickcooke@nickcooke-mac2 quickstart-ios (main) % git grep -E "testing_repo|signin_secret|testing_repo_dir"
nickcooke@nickcooke-mac2 quickstart-ios (main) % 
```
=> chore(ci): Remove unused env vars in .github/workflows/[pre]release.yml

.github/workflows/abtesting.yml, .github/workflows/auth.yml, .github/workflows/common_quickstart.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/firestore.yml, .github/workflows/functions.yml, .github/workflows/inappmessaging.yml, .github/workflows/installations.yml, .github/workflows/messaging.yml, .github/workflows/performance.yml, .github/workflows/remoteconfig.yml, .github/workflows/storage.yml
It's not a red diff, but is cleaner. I've added more functionality like automatic uploads of failed quickstart folders and we have a central Xcode configuration hook for quickstart tests.
#no-changelog
=> refactor(ci): Introduce common, re-usable quickstart workflow

CONTRIBUTING.md, README.md, scripts/setup_check.sh, scripts/style.sh
clang-format is used to style code. There's a bug where new versions on homebrew boot the older version off. The check CI workflow fails as a result and we need to periodically bump clang-format to the new version.
```console
git grep --name-only "clang-format@20" | xargs sed -i '' "s/clang-format@20/clang-format@21/"
```
#no-changelog
=> fix(ci): Update to clang-format@21

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAIBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
Updated the Carthage JSON artifacts for the https://github.com/firebase/firebase-ios-sdk/releases/tag/12.2.0.
#no-changelog
=> [Release] Update Carthage artifacts for 12.2.0

Crashlytics/UnitTests/Mocks/FIRCLSMockFileManager.m
Reverts firebase/firebase-ios-sdk#15183
Unfortunately didn't make a difference.
=> Revert "[Infra] Attempt to reduce Crashlytics testing flake"

.github/workflows/zip.yml
This is a nice option when needing to iterate on the quickstart part of the zip workflow. A previous run ID can be used to get the zip artifact. This way, we don't have to wait hours for a new zip each commit.
This will be very helpful for testing https://github.com/firebase/quickstart-ios/pull/1666
#no-changelog
=> feat(ci): Add support for using previous zip run artifact

cmake/external/abseil-cpp.cmake
Update the absl-cpp package dependency to contain the fix for 
```
c++: error: unsupported  option '-msse4.1' for target 'arm64-apple-darwin24.6.0'
```
reference: https://github.com/abseil/abseil-cpp/commit/26ee072e14dea17fa8870d47cd7e8b4cc1c95e93
and to be consistent with SPM and cocoapods dependency.
=> Update the absl-cpp version used in cmake

.github/workflows/firebaseai.yml, scripts/build.sh
Added quickstart and integration test runs on macOS 26 / Xcode 26 for Firebase AI Logic. Updated `build.sh` to use `"iPhone 16e"` with Xcode 26 where `"iPhone 16"` isn't installed by default.
#no-changelog
=> [Firebase AI] Add macOS / Xcode 26 CI testing

FirebaseAI/Sources/Tool.swift, FirebaseAI/Sources/Types/Internal/Tools/URLContext.swift, FirebaseAI/Sources/Types/Public/URLContextMetadata.swift, FirebaseAI/Sources/Types/Public/URLMetadata.swift
Updated the `URLContext` struct to be internal instead of public. It doesn't need to be exposed publicly yet since it has no properties and should be initialized using `Tool.urlContext()` instead.
#no-changelog
=> [Firebase AI] Make `URLContext` struct internal

FirebaseAI/Sources/GenerateContentResponse.swift, FirebaseAI/Sources/Tool.swift, FirebaseAI/Sources/Types/Public/URLContextMetadata.swift, FirebaseAI/Sources/Types/Public/URLMetadata.swift
Inspired by https://github.com/firebase/firebase-js-sdk/pull/9254 and (internal) [go/alf-urlcontext-refdocs](https://goto.google.com/alf-urlcontext-refdocs)
=> [AI] API docs for URLContext

.github/workflows/abtesting.yml, .github/workflows/auth.yml, .github/workflows/common_quickstart.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/firestore.yml, .github/workflows/inappmessaging.yml, .github/workflows/installations.yml, .github/workflows/messaging.yml, .github/workflows/performance.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/remoteconfig.yml, .github/workflows/storage.yml, scripts/check_secrets.sh, scripts/setup_quickstart_spm.sh, scripts/test_quickstart.sh
=> feat(infra): Add script to set up SPM-based quickstarts

FirebaseAI/Sources/GenerateContentResponse.swift, FirebaseAI/Tests/Unit/Types/GenerateContentResponseTests.swift
Follow on to https://github.com/firebase/firebase-ios-sdk/pull/15262 now that urlContext tool support has been added
This pull request refines the `isEmpty` logic within the `Candidate` struct of the Firebase AI SDK. It specifically updates the `isEmpty` computed property to account for `urlContextMetadata`, preventing `Candidate` objects from being incorrectly identified as empty when they contain relevant URL context information. This change ensures more accurate content generation responses and is accompanied by new unit tests to validate the updated behavior.
* **Candidate.isEmpty logic update**: The `isEmpty` computed property in the `Candidate` struct has been updated to include `urlContextMetadata` in its evaluation, ensuring that candidates with this metadata are no longer …
=> [AI] Update empty parts check for urlContextMetadata

docs/AsyncStreams/api-design-proposal.md, docs/AsyncStreams/swift-async-sequence-api-design.md
This PR adds the design document for #15349
=> Swift AsyncSequence APIs for real-time streams: design document

.github/workflows/auth.yml, .github/workflows/common_cocoapods_cron.yml
Fix some of #15359. Failures are unrelated, only affects cron jobs.
#no-changelog
=> fix(ci): Change how FIREBASE_CI is enabled

FirebaseAI/CHANGELOG.md
Updates the changelogs for fai since the PR for adding live API support got in.
It seems they got accidentally pushed into the `12.3.0` section too.
=> chore(m172): Update changelogs

.github/workflows/spm.yml
This failed in the nightly issue. I recently added steps to upload the xcodebuild log on failure, and am extending that functionality to this job. Now, all main jobs (with the exception of the shared package resolution job) should upload a build log on failure for easier debugging.
#no-changelog
=> chore(ci): Upload build log in spm.yml job

FirebaseAI/Tests/Unit/TestUtilities/FirebaseAI+DefaultAPIConfig.swift
It looks like the extension of `FirebaseAI` was missing an `@available` quantifier that matched `FirebaseAI`, and this was causing a compile error. This PR adds that `@available` marker to the extension.
#no-changelog
=> fix(ai): Add missing available to extension

FirebaseAI/Sources/AILog.swift, FirebaseAI/Sources/Types/Internal/Live/LiveSessionService.swift
I found that in certain edge case situations, errors could end up not propagating up during the initial setup of a live session. While fixing said error, I realized that the setup process could actually be cleaned up a decent amount. While this could cause issues if the model ever sent messages out of order (ie; a message before setupComplete), this doesn't seem like something we should necessarily design around. Furthermore, separating the setup process into a more iterative async style approach not only makes things easier to read (and reason about), but also solves various edge case error propagation issues.
The change has been tested on a local device, and seems to be working perfectly; existing functionality works, and the errors that were previously not being propagated are now …
=> fix(ai): Fix error propagation during setup

FirebasePerformance/CHANGELOG.md, FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m, FirebasePerformance/Tests/Unit/FPRTraceBackgroundActivityTrackerTest.m
Replace async notification observer registration with synchronous registration
to eliminate timing-dependent crashes when objects are deallocated quickly.
Fixes #14273 ([Link](https://github.com/firebase/firebase-ios-sdk/issues/14273))
The FPRTraceBackgroundActivityTracker class had a race condition during initialization where notification observers were registered asynchronously using dispatch_async(dispatch_get_main_queue()). This created a timing window where the tracker object could be deallocated before the async block executed, causing crashes when the block tried to call addObserver: with a deallocated self reference.
The crash occurred when:
- FPRTraceBackgroundActivityTracker is created
- Async observer registration is queued to main thread
- Object is deallocated before async …
=> Fix #14273: Prevent race condition crash in FPRTraceBackgroundActivityTracker
