firebase/firebase-ios-sdk

- Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
- Firebase/DynamicLinks/Utilities/FDLUtilities.m
> Fix for issue where matchesshortlinkformat was returning true for all links.

- Firestore/Swift/Tests/API/BasicCompileTests.swift
This shows the baseline state for the qualified names at which users see Timestamp.
> Show qualified usage of Timestamp

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
- Firestore/Source/API/FIRFirestore.mm
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/delayed_constructor.h
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/delayed_constructor_test.cc
- scripts/check.sh
This is useful for embedding C++ objects of type `T` inside Objective-C objects when `T` has no default constructor or is not a movable type. It works by allocating space for T with `std::aligned_storage` and then adding an `Init()` method that uses placement new to later construct the object in the allocated space.
See class comments for more detail and restrictions.
> Add DelayedConstructor<T>

- FirebaseFirestore.podspec
This removes one of the blockers for tvOS support for Firestore mentioned in #10.
> Exclude sub-packages of abseil that are problematic

- Firestore/Source/Public/FIRCollectionReference.h
- Firestore/Source/Public/FIRDocumentChange.h
- Firestore/Source/Public/FIRDocumentReference.h
- Firestore/Source/Public/FIRDocumentSnapshot.h
- Firestore/Source/Public/FIRFieldValue.h
- Firestore/Source/Public/FIRFirestore.h
- Firestore/Source/Public/FIRGeoPoint.h
- Firestore/Source/Public/FIRQuery.h
- Firestore/Source/Public/FIRQuerySnapshot.h
- Firestore/Source/Public/FIRSnapshotMetadata.h
- Firestore/Source/Public/FIRTimestamp.h
- Firestore/Source/Public/FIRTransaction.h
> b/62961699: Use :nodoc: to prevent methods from showing up in reference docs.

- GoogleUtilities/Example/Tests/Logger/GULLoggerTest.m
- GoogleUtilities/Logger/GULLogger.m
- GoogleUtilities/Logger/Private/GULLogger.h
- logic to count error and warning messages added to GULLogger (https://github.com/firebase/firebase-ios-sdk/pull/1201 used as a base)
> GULLogger - count errors and warnigns

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
- Firestore/Example/Tests/Core/FSTViewTests.mm
- Firestore/core/include/firebase/firestore/timestamp.h
- Firestore/core/src/firebase/firestore/core/view_snapshot.h
- Firestore/core/src/firebase/firestore/core/view_snapshot.mm
- Firestore/core/src/firebase/firestore/timestamp.cc
- Firestore/core/src/firebase/firestore/util/status.cc
- Firestore/core/src/firebase/firestore/util/status.h
- Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
- Firestore/core/test/firebase/firestore/testutil/xcgmock.h
- Firestore/core/test/firebase/firestore/testutil/xcgmock_test.mm
This defines a means of using gmock matchers in XCTest tests.
This makes it easy to fix tests currently depending on e.g. `NSArray` values and `XCTAssertEqualObjects` to instead use something else. It's better to fix the test to
```c++
XC_ASSERT_THAT(accum, ElementsAre(viewSnapshot1));
```
Instead of:
```
XCTAssertEqual(accum, (std::vector<ViewSnapshot>(viewSnapshot1)));
```
... or the even worse:
```
XCTAssertTrue(accum == std::vector<ViewSnapshot>(viewSnapshot1));
```
> Add xcgmock

- Firestore/CHANGELOG.md
- Firestore/Example/App/iOS/Images.xcassets/AppIcon.appiconset/Contents.json
- Firestore/Example/App/macOS_example/AppDelegate.m
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm
The prior implementation happened to work but only because it made implicit assumptions about the structure of the bundles we load.
In particular, by looking for `@"gRPCCertificates.bundle/roots"` the code was assuming the iOS bundle layout for the app was in effect, but this doesn't work on macOS, in which app/framework bundles have an additional `Contents/Resources` in the path.
This change gets rid of the implicit mapping of the bundle structure onto the directory structure and instead opens the nested `gRPCCertificates.bundle` itself as a resource, making this code portable without having to understand the bundle layout under the covers.
Fixes #2604. Should also remove the need for the workaround in #2177.
> Rework gRPC certificate loading one last time

- Example/InstanceID/Tests/FIRInstanceIDTest.m
- Firebase/InstanceID/FIRInstanceID+Testing.h
- Firebase/InstanceID/FIRInstanceID.m
Before there's this strange handler created to finish some logic of defaultTokenWithHandler: and it is only defined and passing in defaultTokenWithHandler: at two places, where the rest of the defaultTokenWithHandler: calls are not. This could cause issue because it contains critical token refresh code. Move the logic inside defaultTokenWithHandler: so it's always triggered and more readable.
So merge repetitive code and move inside defaultTokenWithHandler: and after that I notice fetchDefaultToken call is simply just calling defaultTokenWithHandler:, so remove it too as there are too many layers of calling default token.
> Ensure token refresh notification is triggered any time a new token is refreshed. b/77662386

- Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.h
- Firestore/core/src/firebase/firestore/local/memory_mutation_queue.h
- Firestore/core/src/firebase/firestore/local/memory_query_cache.h
- Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.h
Strictly speaking this doesn't address the retain cycle reported in #2564, but I found these while digging into it.
> Avoid retain cycles in parent pointers

- Firestore/core/src/firebase/firestore/local/CMakeLists.txt
- Firestore/core/src/firebase/firestore/local/document_key_reference.cc
- Firestore/core/src/firebase/firestore/local/document_key_reference.h
- Firestore/core/src/firebase/firestore/local/local_serializer.cc
- Firestore/core/src/firebase/firestore/local/memory_mutation_queue.h
- Firestore/core/src/firebase/firestore/local/memory_mutation_queue.mm
- Firestore/core/src/firebase/firestore/local/reference_set.cc
- Firestore/core/src/firebase/firestore/local/reference_set.h
- Firestore/core/src/firebase/firestore/nanopb/nanopb_string.cc
- Firestore/core/src/firebase/firestore/nanopb/nanopb_util.h
- Firestore/core/src/firebase/firestore/remote/serializer.cc
- Firestore/core/src/firebase/firestore/remote/serializer.h
Each commit explains what it's after.
> Clean up warnings in the Firestore project

- Firestore/core/src/firebase/firestore/timestamp.cc
- Firestore/core/src/firebase/firestore/util/status.cc
- scripts/cpplint.py
I discovered that when archiving a build you end up with undefined symbols if you only `#include <iosfwd>`.
This adds a IWYU check and fixes the cases I already broke.
> Add missing #include <ostream>

- scripts/cpplint.py
This handles [`#include <iostream>`](https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/core/test/firebase/firestore/testutil/xcgmock.h#L26) in xcgmock.h.
The previous implementation failed because it required `<iosfwd>` to be included from headers, even though `<iostream>` or `<ostream>` is sufficient.
This essentially changes the algorithm to ensure that individual entities have their headers covered rather than compiling a list of required headers. The latter is no longer computable if we allow this flexibility.
> Rework the IWYU test to handle types with multiple valid sources

- Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
- Firebase/InstanceID/FIRIMessageCode.h
- Firebase/InstanceID/FIRInstanceIDCheckinService.m
- Firebase/InstanceID/FIRInstanceIDCheckinStore.m
- Firebase/InstanceID/FIRInstanceIDKeyPairStore.m
- Firebase/InstanceID/FIRInstanceIDKeychain.m
- Firebase/InstanceID/FIRInstanceIDStore.m
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
For some users using Firebase 5.17.0, they fall into a condition where checkin is deleted right after the new one is fetched, causing checkin and token are kept being refreshed during app start. (#2438)
Also adjust a few debug logs to make it more easy to understand.
> fix race condition that checkin can be deleted right after fetched (#2438)

- Firebase/Core/FIRApp.m
- FirebaseCore.podspec
#2624:
- use `@synchronized(self)` to fix thread safety.
> FIRApp: thread safety fixes

- Firestore/Example/GoogleBenchmark.podspec
- Firestore/Example/GoogleTest.podspec
- Firestore/Example/LibFuzzer.podspec
- Firestore/Example/ProtobufCpp.podspec
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/core/test/firebase/firestore/FSTGoogleTestTests.mm
This is a grab bag of minor fixes that can be made independently of the major project file overhaul required to enable unit tests working under macOS.
> Prepare for macOS test support

- GoogleUtilities/Example/Tests/Logger/GULLoggerTest.m
- GoogleUtilities/Logger/GULLogger.m
- don't set global queue as a target for GULLoggerCounterQueue. `dispatch_barier_async` on a global queue behaves as just `dispatch_async`, so the counter could be updated concurrently.
> GULLogger: logged issue counting concurrency issue fix

- Firestore/Example/Tests/Model/FSTFieldValueTests.mm
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Source/API/FIRDocumentSnapshot.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/Core/FSTQuery.mm
- Firestore/Source/Model/FSTFieldValue.h
- Firestore/Source/Model/FSTFieldValue.mm
- Firestore/core/src/firebase/firestore/model/field_value.h
- Firestore/core/src/firebase/firestore/model/transform_operations.h
Previously, we checked for FSTFieldValue subtypes via:
`[value isKindOfClass:[FSTStringValue class]]`
Now, we check via a new type parameter on FSTFieldValue, i.e.:
`[value type] == FSTFieldValueTypeString`
This should enable easier transition to C++.
(Slightly) more context: go/firestore-cpp-fieldvalue
>  Eliminate 'instanceof' checks for FSTFieldValue 

- FirebaseFirestore.podspec
iOS unit/integration tests pass.
Working on tvOS tests separately.
> Upgrade gRPC-C++ to 0.0.8, enabling experimental tvOS support

- Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
Fix a missing comma build warning that's an error in internal build system.
Confirmed to remove warning and fix blaze build.
> Fix build warning

- .travis.yml
This enables testing that the decryption steps work correctly.
I'll revert this change once we see that working.
> Temporarily enable testing the branch for #2664

- Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.h
- Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
The update is an intermediate step for #2591. To update `FIRMessagingRemoteNotificationsProxy` implementation with `GoogleUtilities` we need reliable set of tests.
- `FIRMessagingRemoteNotificationsProxyTests` updated to use only public API of `FIRMessagingRemoteNotificationsProxy`. This will allow to reuse the same tests for the updated implementation.
> FIRMessagingRemoteNotificationsProxy - test only public API with no assumptions on implementation

- Firebase/Auth/Source/AuthProviders/OAuth/FIROAuthCredential_Internal.h
- Firebase/Auth/Source/AuthProviders/OAuth/FIROAuthProvider.m
- Firebase/Auth/Source/Public/FIROAuthCredential.h
- Firebase/Auth/Source/Public/FIROAuthProvider.h
It's added to public header by mistake.
Developers are not supposed to use it, and they currently have no way to use it.
> Remove pendingToken from public API. 

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Integration/API/FIRListenerRegistrationTests.mm
- Firestore/core/src/firebase/firestore/api/document_reference.mm
Fixes #2682.
The issue here is that if you run code like this:
```swift
db.document('foo/bar').addSnapshotListener(...);
```
Callbacks to the implementation of addSnapshotHandler can happen after the DocumentReference has been released. The problem is that internally we were pointing at the underlying C++ DocumentReference via raw pointer which could cause use-after-free.
The fix is to copy the interesting state into the Converter such that it no longer depends on the lifetime of the DocumentReference.
> Fix use-after-free in DocumentReference::AddSnapshotListener

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Integration/API/FIRListenerRegistrationTests.mm
- Firestore/core/src/firebase/firestore/api/document_reference.mm
Cherry-pick of https://github.com/firebase/firebase-ios-sdk/commit/8ef6cf80bee255f9ce81460422986eb29cb7eb52
> Fix use-after-free in DocumentReference::AddSnapshotListener (#2686)

- GoogleDataTransport/GoogleDataTransport/Classes/GDTClock.m
- GoogleDataTransport/GoogleDataTransport/Classes/GDTStorage.m
- GoogleDataTransport/GoogleDataTransport/Classes/GDTUploadCoordinator.h
- GoogleDataTransport/GoogleDataTransport/Classes/GDTUploadCoordinator.m
- GoogleDataTransport/GoogleDataTransport/Classes/Public/GDTPrioritizer.h
- GoogleDataTransport/Tests/Common/Fakes/GDTUploadCoordinatorFake.m
- GoogleDataTransport/Tests/Integration/GDTIntegrationTest.m
- GoogleDataTransport/Tests/Unit/GDTUploadCoordinatorTest.m
Forced uploads should be defined as an additional upload condition, as opposed to constructing an ad-hoc upload package. This allows the prioritizer and uploader to do housekeeping more easily.
Address a race condition during high-priority event sending in which a package can be asked for whilst the storage is still asking the prioritizer to deprioritize events that have already been removed from disk.
> Make high priority events force an upload via upload conditions

- Firestore/fuzzing/leveldb_fuzzer.cc
- Firestore/fuzzing/serializer_fuzzer.cc
This is to fix OSS-Fuzz build:
* silence warnings about unused return values (warnings are treated as errors in the build);
* temporarily comment out a test that relied on the old serializer API.
> Make fuzzing compile

- GoogleDataTransport.podspec
- GoogleDataTransport/GoogleDataTransport/Classes/GDTConsoleLogger.m
- GoogleDataTransport/GoogleDataTransport/Classes/Private/GDTConsoleLogger.h
Wrote a quick console logging function that will log to the console in debug mode.
> Remove the GULLogger dependency

- Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
- Firestore/Source/API/FIRDocumentChange+Internal.h
- Firestore/Source/API/FIRDocumentChange.mm
- Firestore/Source/API/FIRQuerySnapshot.mm
- Firestore/core/src/firebase/firestore/api/document_change.h
- Firestore/core/src/firebase/firestore/api/document_change.mm
- Firestore/core/src/firebase/firestore/api/document_reference.h
- Firestore/core/src/firebase/firestore/api/query_snapshot.h
- Firestore/core/src/firebase/firestore/api/query_snapshot.mm
* Create C++ api::DocumentChange class.
* Make FIRDocumentChange a wrapper over DocumentChange.
* Moved documentChangesForSnapshot helper from FIRDocumentChange to
where it's used in QuerySnapshot. I think this is cleaner.
> Port FIRDocumentChange to C++.

- GoogleUtilities/Example/Tests/Logger/GULLoggerTest.m
- GoogleUtilities/Logger/GULLogger.m
- GoogleUtilities/Logger/Private/GULLogger.h
Temporary revert #2601, #2610 and #2627 until a final approval.
> Revert "GULLogger - count errors and warnigns"

- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/Public/FIRMessaging.h
Should use shouldEstablishDirectChannel property instead.
> Remove deprecated API to connect direct channel

- Firebase/Auth/Source/Auth/FIRAuth.m
FIRAppAssociationRegistration is soon to be deprecated and has already been replaced by FIRComponent.
> Remove unused import

- Firebase/Core/FIRApp.m
In favor of build-time warning from Firebase.h
> Remove missing analytics runtime warning

- FirebaseInAppMessaging.podspec
- InAppMessaging/Example/Podfile
Developers will need to continue to include Firebase/Core or update to including Firebase/Analytics in their Podfile to continue to use FIAM features that depend on FirebaseAnalytics.
> Remove implicit Analytics dependency from FIAM

- FirebaseDynamicLinks.podspec
Developers will need to continue to include `Firebase/Core` or update to including `Firebase/Analytics` in their Podfile to continue to use DynamicLinks features that depend on FirebaseAnalytics.
> Remove implicit Analytics dependency from DynamicLinks

- Example/Auth/Tests/FIRAuthTests.m
- Firebase/Auth/Source/Auth Provider/Email/FIREmailAuthProvider.m
- Firebase/Auth/Source/Auth Provider/FIRAuthProvider.m
- Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
APIs already removed in #2723. This PR cleans up the remaining bits
> Remove support for deprecated API for Firebase 6

- Example/InstanceID/Tests/FIRInstanceIDTest.m
- Firebase/InstanceID/FIRInstanceID+Private.h
- Firebase/InstanceID/FIRInstanceID.m
- Firebase/InstanceID/Private/FIRInstanceID_Private.h
- Firebase/InstanceID/Public/FIRInstanceID.h
- Firebase/Messaging/FIRMessaging.m
- FirebaseInstanceID.podspec
Remove deprecated token API as requested in #2761. Use instanceIDWithHandler: instead.
> remove deprecated token API

- Example/Podfile
- FirebaseAuth.podspec
- FirebaseCore.podspec
- FirebaseDatabase.podspec
- FirebaseDynamicLinks.podspec
- FirebaseFirestore.podspec
- FirebaseFunctions.podspec
- FirebaseInAppMessaging.podspec
- FirebaseInAppMessagingDisplay.podspec
- FirebaseInstanceID.podspec
- FirebaseMessaging.podspec
- FirebaseStorage.podspec
- Firestore/Example/Podfile
And update all dependents to require at least 6.0.0.
To pass `pod lib lint` tests it was also necessary to bump FirebaseInstanceID to 4.0.0 and FirebaseInAppMessaging to 0.14.0 on https://github.com/firebase/SpecsStaging
Leaf pods will get their versions updated when we cut the release branch.
> Bump FirebaseCore to 6.0.0

- FirebaseInstanceID.podspec
While not true for Development Pods, published pods need to include private headers in the list of public headers for Xcode to make them Private instead of Project.
Pushing this to SpecsStaging fixes the regression in the FirebaseMessaging pod lib lint test.  Verified in https://travis-ci.org/firebase/firebase-ios-sdk/jobs/517555143
> Private headers need to also be part of public

- Example/DynamicLinks/Tests/FDLURLComponentsTests.m
- Firebase/DynamicLinks/Public/FDLURLComponents.h
Remove deprecated Dynamic Links API for M47.
> Remove deprecated API in FDLURLComponents.

- Firestore/Source/API/FIRDocumentReference.mm
- Firestore/Source/API/FIRFirestoreSource+Internal.h
- Firestore/Source/API/FIRFirestoreSource.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/Core/FSTFirestoreClient.mm
- Firestore/core/src/firebase/firestore/api/document_reference.h
- Firestore/core/src/firebase/firestore/api/document_reference.mm
- Firestore/core/src/firebase/firestore/api/source.h
Note that the public type must continue to exist, but it should only exist for the public Objective-C API.
> Port FIRFirestoreSource to C++ Source

- Firestore/Source/Local/FSTLevelDB.mm
Use of NSDocumentsDirectory (or NSApplicationSupportDirectory) is
forbidden there.
Fixes #2735.
Note that this now creates a new compile error for watchOS, but this is intended since we haven't undertaken support for that yet.
> Use NSCachesDirectory for database storage on tvOS

- Firestore/Source/Public/FIRFirestore.h
Too many places refer to calling `enableLogging` and actually removing this method would be net harmful.
Resolves issues raised in discussing #2762.
> Undeprecate +[FIRFirestore enableLogging:]

- Firebase/Core/CHANGELOG.md
Fix #2750
Document externally visible 6.0.0 FirebaseCore changes.
Stop putting release date in release notes.
> M47 FirebaseCore release notes

- Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents+Private.h
- Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m
- Firebase/DynamicLinks/FIRDynamicLinks+Private.h
In the internal Dynamic Links build, the FDLComponents directory does not have access to the higher level headers.
> Fix 1P build issue

- Firebase/Core/FIRAnalyticsConfiguration.m
- Firebase/Core/FIRConfiguration.m
Related to #2728
Required to fix 1p
> Fix headers imports moved private

- Firebase/InstanceID/FIRInstanceID+Private.h
Needed to fix 1p. The initializer was removed along with FIRInstanceID+Testing
> InstanceID - Add private initializer used by Swift 1p tests

- Firebase/DynamicLinks/FIRDynamicLinks.m
This PR gets DynamicLinks building and testing both internally and externally. 
Sorry for the churn. I've pre-verified this one on the internal build and test infrastructure.
The travis failure is addressed separately in #2796.
> FIRErrorCodeDurableDeepLinkFailed is for 3P only

- Firestore/Source/API/FIRFirestore.mm
This fixes a warning added by #2786.
> Move collectionGroup method out of the Internal category

- Firebase/Core/FIRAnalyticsConfiguration.m
- Firebase/Core/Private/FIRAnalyticsConfiguration.h
Restore single argument version of setAnalyticsCollectionEnabled until clients can migrate to the Analytics version.
> Temporarily restore setAnalyticsCollectionEnabled

- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/API/FIRFirestore+Internal.h
- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/API/FIRWriteBatch.mm
- Firestore/core/src/firebase/firestore/api/firestore.h
1. Fix primeBackend so it uses an isolated FIRFirestore* instance. I ran into
an issue where tests that try to change .settings would fail if they were the
very first test run, since primeBackend had already configured the client and
so settings could no longer be changed.
2. FIRFirestore.client was incorrectly typed / commented as non-null.
> Fix a couple small issues I tripped over today.

- Firestore/Example/Tests/Core/FSTViewTests.mm
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/Core/FSTQuery.h
- Firestore/Source/Core/FSTQuery.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/core/src/firebase/firestore/core/filter.h
- Firestore/core/src/firebase/firestore/core/relation_filter.cc
Note:
* This includes a partial port of array-contains for Filters because
this silenced a warning about an unhandled case
* There's some sensitivity to the order of the cases that I didn't
bother to figure out; instead I just made it match what came before.
> Port FSTRelationFilterOperator to C++ Filter::Operator

- FirebaseAuth.podspec
- FirebaseMessaging.podspec
- GoogleUtilities.podspec
Bump GoogleUtilities to 5.8.0 internally after doing public push of 5.7.0 to address #2807
> GoogleUtilities to 5.8.0

- Firestore/Source/API/FIRFieldPath.mm
- Firestore/core/src/firebase/firestore/model/CMakeLists.txt
- Firestore/core/src/firebase/firestore/model/field_path.cc
- Firestore/core/src/firebase/firestore/model/field_path.h
The first commit is a cherry-pick of my first attempt (384ccd81a).
The second commit reworks it to do the validation in a FromSegments() method that is only called from the public API.
> Take 2: Move input validation logic from FIRFieldPath to model::FieldPath. (#2727)

- Releases/update-versions.py
Tests should have already been run.  Avoid any unnecessary configuration or delay in release process.
> Skip tests on pod repo push

- ZipBuilder/README.md
These were introduced in #2545 but were accidentally removed in a bad merge.
> Add detailed instructions for building the Zip.

- Releases/update-versions.py
We currently tag it locally but don't push it to remote like we do with the other tags.
> Push `firebase_version` tag after creating it.

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Source/API/FIRFirestore.mm
- Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/error_apple.h
- Firestore/core/src/firebase/firestore/util/error_apple.mm
- Firestore/core/src/firebase/firestore/util/status.cc
- Firestore/core/src/firebase/firestore/util/status.h
- Firestore/core/src/firebase/firestore/util/status_apple.mm
- Firestore/core/src/firebase/firestore/util/status_posix.cc
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/status_apple_test.mm
- Firestore/core/test/firebase/firestore/util/status_test.cc
If we're going to convert all our internal error plumbing to `util::Status` we can't lose diagnostic information for iOS users.
Fixes b/130349574.
> Tunnel underlying NSErrors through C++ Status

- GoogleDataTransport/GoogleDataTransport/Classes/GDTReachability.h
- GoogleDataTransport/GoogleDataTransport/Classes/GDTReachability.m
- GoogleDataTransport/GoogleDataTransport/Classes/GDTUploadCoordinator.m
- GoogleDataTransport/GoogleDataTransport/Classes/Private/GDTReachability_Private.h
- GoogleDataTransport/GoogleDataTransport/Classes/Public/GDTPrioritizer.h
- GoogleDataTransport/Tests/Integration/GDTIntegrationTest.m
- GoogleDataTransport/Tests/Integration/Helpers/GDTIntegrationTestPrioritizer.m
- GoogleDataTransport/Tests/Unit/GDTTestCase.m
- GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/GDTCCTPrioritizer.m
- GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/GDTCCTUploader.m
Upload conditions can now be determined based on the network connectivity.
> Implement reachability and upload conditions

- Firestore/Source/API/FIRDocumentReference.mm
- Firestore/core/src/firebase/firestore/api/document_reference.h
- Firestore/core/src/firebase/firestore/api/document_reference.mm
I *think* the intention was that the user_data.h types should be used as the representation of parsed user data that can be passed down from the public API to the api:: layer, so this PR "fixes" api::DocumentReference to accept ParsedSetData and ParsedUserData in SetData() / UpdateData() instead of taking the list of mutations. This is consistent with the approach I took in the api::WriteBatch port.
Sidenote: Prior to this change, SetData() / UpdateData() were actually identical methods just with different names.
> Make api::DocumentReference accept ParsedSetData / ParsedUserData.

- Firestore/core/.clang-format
- Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.h
- Firestore/core/test/firebase/firestore/FSTGoogleTestTests.mm
- Firestore/core/test/firebase/firestore/local/index_manager_test.h
- Firestore/core/test/firebase/firestore/local/index_manager_test.mm
- Firestore/core/test/firebase/firestore/remote/watch_change_test.mm
Context: https://github.com/firebase/firebase-ios-sdk/pull/2844/files#r276370766
Fix pointer alignment once-and-for-all?
> Set DerivePointerAlignment=false for Firestore cpp files.

- Firebase/InstanceID/FIRIMessageCode.h
- Firebase/InstanceID/FIRInstanceIDCheckinStore.m
This is a prevention fix for #2438 because we still couldn't reproduce. But users are facing race condition where checkin plist file is deleted after a new checkin is written to the file. So we move the plist deletion call to the first step of resetting checkin during app start. Because FIRInstanceID init call should be always before first checkin call got issued. 
Also add two more logs which helps provide the timeline when checkin plist file is written or read.
> fix race condition checkin is deleted before writing during app start

- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/API/FIRFirestoreSettings.mm
- Firestore/Source/Core/FSTFirestoreClient.mm
- Firestore/Source/Local/FSTLRUGarbageCollector.h
- Firestore/Source/Local/FSTLRUGarbageCollector.mm
- Firestore/Source/Public/FIRFirestoreSettings.h
- Firestore/core/src/firebase/firestore/api/settings.cc
- Firestore/core/src/firebase/firestore/api/settings.h
We learned in #2846 that the current implementation isn't an effective way to disable GC, because the empty commit itself was failing.
Also make the linkage of kFIRFirestoreCacheSizeUnlimited explicitly extern "C". This previously had no fixed linkage in the header and only accidentally worked because the implementation had C++ linkage.
Move internal `CacheSizeUnlimited` to `api::Settings` and the definition of `kFIRFirestoreCacheSizeUnlimited` into the Objective-C language binding.
Move the rest of the `FIRFirestoreSettings` defaults to `api::Settings` as well.
> Make disabling GC prevent even scheduling it

- GoogleDataTransport/Library/Private/GDTConsoleLogger.h
- GoogleDataTransport/Library/Private/GDTReachability_Private.h
- GoogleDataTransport/Library/Private/GDTStorage_Private.h
- GoogleDataTransport/Library/Private/GDTTransformer_Private.h
- GoogleDataTransport/Library/Public/GDTUploader.h
- GoogleDataTransport/Tests/Integration/GDTIntegrationTest.m
- GoogleDataTransport/Tests/Integration/Helpers/GDTIntegrationTestPrioritizer.h
- GoogleDataTransport/Tests/Integration/Helpers/GDTIntegrationTestPrioritizer.m
- GoogleDataTransport/Tests/Integration/Helpers/GDTIntegrationTestUploader.h
- GoogleDataTransport/Tests/Integration/Helpers/GDTIntegrationTestUploader.m
- GoogleDataTransport/Tests/Lifecycle/GDTLifecycleTest.m
- GoogleDataTransport/Tests/Lifecycle/Helpers/GDTLifecycleTestPrioritizer.h
- GoogleDataTransport/Tests/Lifecycle/Helpers/GDTLifecycleTestPrioritizer.m
- GoogleDataTransport/Tests/Lifecycle/Helpers/GDTLifecycleTestUploader.h
- GoogleDataTransportCCTSupport/Library/Protogen/nanopb/cct.nanopb.h
- GoogleDataTransportCCTSupport/ProtoSupport/Protos/cct.proto
- Adds a _Nonnull nullability annotation
- Removes all umbrella header imports
- Adds a 0-value field for a proto enum, along with new generated code
Additional changes may be needed for GDT CCT support library.
> Fix headers for copybara import for GDT

- FirebaseFunctions.podspec
- Functions/Example/GoogleService-Info.plist
- Functions/Example/IntegrationTests/FIRIntegrationTests.m
I based this on the similar functionality in Firestore. The tests still use the emulator if you don't replace the plist. I tested with a plist manually. I didn't change the automated tests to use this, but may do that in a subsequent PR.
> Change Functions test app to allow testing against prod, using a GoogleService-Info.plist

- FirebaseAuth.podspec
- FirebaseCore.podspec
- FirebaseInstanceID.podspec
- FirebaseMessaging.podspec
- GoogleUtilities.podspec
- GoogleUtilities/CHANGELOG.md
Also bump major version, since this is technically a breaking change.
The special case ios 6 and ios 7 code can be cleaned up in subsequent PRs.
This is a candidate for cherry-pick to Firebase 6.
> GoogleUtilities min ios version from 6 to 8

- Firebase/Auth/Source/Auth/FIRAuth.m
- Firebase/Auth/Source/AuthProvider/Phone/FIRPhoneAuthProvider.m
- Firebase/Auth/Source/Public/FIRAuth.h
- Firebase/Auth/Source/Storage/FIRAuthKeychain.h
- Firebase/Auth/Source/Storage/FIRAuthKeychain.m
- Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
Fix https://github.com/firebase/firebase-ios-sdk/issues/2747
> Fix clang analyzer warnings for Firebase Auth.

- GoogleDataTransport/GDTLibrary/GDTDataFuture.m
- GoogleDataTransport/GDTLibrary/GDTEvent.m
- GoogleDataTransport/GDTLibrary/GDTStorage.m
- GoogleDataTransport/GDTLibrary/GDTStoredEvent.m
- GoogleDataTransport/GDTLibrary/Public/GDTDataFuture.h
- GoogleDataTransport/GDTLibrary/Public/GDTEvent.h
- GoogleDataTransport/GDTLibrary/Public/GDTStoredEvent.h
- GoogleDataTransport/GDTLibrary/Public/GoogleDataTransport.h
- GoogleDataTransport/GDTTests/Integration/Helpers/GDTIntegrationTestUploader.m
- GoogleDataTransport/GDTTests/Unit/GDTStorageTest.m
- GoogleDataTransport/GDTTests/Unit/GDTStoredEventTest.m
- GoogleDataTransport/GDTTests/Unit/Helpers/GDTEventGenerator.m
This will make future refactoring of GDTStorage much easier. Having the framework utilize a data future instead of raw file URLs will be easier to manage because future storage systems might not have file URLs (e.g. sqlite)
> Implement a type of future for GDT stored NSData

- ZipBuilder/Sources/ZipBuilder/CocoaPod.swift
- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/URL+Utils.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
This adds a top level folder for GoogleSignIn to include it in the zip
file, since Invites was removed.
There are likely a few incorrect references to "specs" and "subspecs" still, but this is functional and we can clean those up after as needed.
> Add GoogleSignIn to Zip file.

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/core/src/firebase/firestore/objc/CMakeLists.txt
- Firestore/core/src/firebase/firestore/objc/objc_class.h
- Firestore/core/src/firebase/firestore/objc/objc_class.mm
- Firestore/core/src/firebase/firestore/objc/objc_compatibility.h
- Firestore/core/test/firebase/firestore/objc/CMakeLists.txt
- Firestore/core/test/firebase/firestore/objc/objc_class_test.cc
- Firestore/core/test/firebase/firestore/objc/objc_class_test_helper.h
- Firestore/core/test/firebase/firestore/objc/objc_class_test_helper.mm
This makes it possible to safely embed pointers to Objective-C objects in plain C++, without needing any additional PIMPL indirection.
> Add objc::Handle and OBJC_CLASS

- Firestore/core/src/firebase/firestore/api/document_snapshot.h
- Firestore/core/src/firebase/firestore/api/document_snapshot.mm
The function its delegating to is returning a const reference already.
> Make `api::DocumentSnapshot::document_id()` return a const reference.

- Example/Core/Tests/FIRAppTest.m
- Firebase/Core/FIRApp.m
> FIRApp - validate app name using NSCharacterSet

- Example/Storage/Tests/Unit/FIRStorageReferenceTests.m
- Firebase/Storage/CHANGELOG.md
- Firebase/Storage/FIRStorageUploadTask.m
> FIRStorageUploadTask - fix crash in `isContentToUploadValid`

- Firestore/Source/API/FIRFirestore.mm
- Firestore/core/src/firebase/firestore/util/log.h
- Firestore/core/src/firebase/firestore/util/log_apple.mm
On iOS this still delegates to FIRLogger under the covers.
> Use portable util/log.h instead of FIRLogger

- Firebase/Auth/Source/Auth/FIRAuthDataResult_Internal.h
- Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential_Internal.h
- Firebase/Auth/Source/Public/FIRAuthDataResult.h
- Firebase/Auth/Source/Public/FIROAuthCredential.h
Removing this from the public API for the Firebase 6 release.
> Put secret and oauth credentials into the private headers for now.

- .travis.yml
- scripts/install_prereqs.sh
This will help prevent issues like #2920 and allows us to collect
metrics on PRs.
Travis already protects secrets from being exposed to PRs originating from forks: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
> Extract secrets on PRs coming from the same repo.

- CocoapodsIntegrationTest/Gemfile
CocoaPods 1.7.0.rc.1 has a regression (https://github.com/CocoaPods/CocoaPods/issues/8765) that breaks the Database and Firestore static library builds (via leveldb-library and gRPC)
> Fix cron tests by disallowing CocoaPods 1.7.0.rc.1

- Example/Core/Tests/FIRAppTest.m
OCMOCK_ANY is only for object arguments.
I verified that the tests now pass and fail along with the corresponding changes in FIRApp
This was exposed as a build warning in the macOS test build. I'm not sure why the other platforms were warning-free.
> Fix data collection switch unit tests

- Firestore/Source/API/FIRFirestore.mm
We removed the code that wrote to `instances` in #1525 but didn't clean up the notification handler that cleaned instances up on app deletion.
> Remove unused FIRFirestore instances dictionary

- .travis.yml
- Example/Core/Tests/FIROptionsTest.m
- FirebaseCore.podspec
- scripts/if_changed.sh
FirebaseCore now has a test_spec and supports working with `pod gen`.  Default instructions will be updated once other pods are updated and https://github.com/square/cocoapods-generate/pull/19 lands.
`pod lib lint` runs into https://github.com/CocoaPods/CocoaPods/issues/8173, but it doesn't prevent its success.
> Add FirebaseCore test_spec

- cmake/podspec_cmake.rb
Fixes CMake build broken by #2943.
> When expanding all subspecs, exclude test specs

- .travis.yml
The plain travis cmake build has been deleted since #2482 and we missed that adding test_specs to FirebaseCore in #2943 broke them.
@wilhuff Feel free to merge, copy, discard or whatever works best with the cmake fixes you're doing.
> Restore cmake build inadvertently deleted in #2482

- Example/Podfile
- Firestore/Example/Podfile
Close #2780 
SpecsStaging was scrubbed in https://github.com/firebase/SpecsStaging/commit/84ab45534ecc8d9482d523f7e5f859038c254c4e
The other SpecsStaging references in this repo are left for preliminary M48 changes.
> Update Podfiles after 6.0.0 release

- CMakeLists.txt
- Firestore/core/test/firebase/firestore/objc/CMakeLists.txt
- cmake/cc_rules.cmake
Fix a bunch of policy warnings (and make them errors where possible).
Also make `cc_binary` not add its binaries as tests. The benefit of this is that benchmarks won't run (though they will still build).
> CMake fixes

- Firestore/Example/Benchmarks/CMakeLists.txt
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Podfile
- Firestore/core/src/firebase/firestore/util/ordered_code.cc
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/ordered_code_benchmark.mm
- Firestore/core/test/firebase/firestore/util/string_apple_benchmark.mm
- scripts/cpplint.py
Endianness detection in OrderedCode was broken. Thankfully it just cost an
extra load rather than any functional problem.
Also, I looked into fixing the unaligned loads in SkipToNextSpecialByte by
reading the initial bytes up to the alignment boundary separately but this is a
minor win only on large strings and a loss otherwise.
16 bytes: 16% slower
256 bytes: ~same
32 KB: 8% faster
I've included the benchmark so I'm not tempted to do this again.
This change can't be submitted until #2966 is submitted, otherwise the CMake test cycle will be much slower.
> Ordered code fixes

- GoogleDataTransport/GDTLibrary/GDTEvent.m
- GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
- GoogleDataTransport/GDTLibrary/Private/GDTUploadPackage_Private.h
- GoogleDataTransport/GDTLibrary/Public/GDTUploadPackage.h
- GoogleDataTransport/GDTLibrary/Public/GDTUploader.h
- GoogleDataTransport/GDTTests/Integration/Helpers/GDTIntegrationTestPrioritizer.m
- GoogleDataTransport/GDTTests/Lifecycle/Helpers/GDTLifecycleTestPrioritizer.m
- GoogleDataTransport/GDTTests/Unit/GDTUploadCoordinatorTest.m
- GoogleDataTransport/GDTTests/Unit/GDTUploadPackageTest.m
- GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestPrioritizer.m
- GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestUploader.m
This will help the library deal with lifecycle events better, since blocks don't serialize well with NSSecureCoding. Using delegate callbacks to ensure that an upload is always completed seems to be the only way to address this lifecycle issue.
> Expand the upload package capabilities

- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
- ZipBuilder/Sources/ZipBuilder/main.swift
Use the already existing outputDir specified by the command line
parameters as the output directory for build logs (for frameworks that
are compiled).
This will help our CI system be able to fetch the build logs easier.
> Use outputDir for build logs.

- Firebase/InAppMessaging/Analytics/FIRIAMClearcutLogger.m
Fixes https://github.com/firebase/firebase-ios-sdk/issues/2988, where nil instance ID was being inserted into an NSDictionary.
> Early return from sending analytics events if instance ID is nil

- GoogleDataTransport/GDTLibrary/GDTStorage.m
- GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
- GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
- GoogleDataTransport/GDTLibrary/Private/GDTUploadCoordinator_Private.h
- GoogleDataTransport/GDTLibrary/Public/GDTPrioritizer.h
- GoogleDataTransport/GDTLibrary/Public/GDTUploader.h
- GoogleDataTransport/GDTTests/Common/Categories/GDTUploadCoordinator+Testing.m
- GoogleDataTransport/GDTTests/Integration/Helpers/GDTIntegrationTestPrioritizer.m
- GoogleDataTransport/GDTTests/Integration/Helpers/GDTIntegrationTestUploader.m
- GoogleDataTransport/GDTTests/Lifecycle/GDTLifecycleTest.m
- GoogleDataTransport/GDTTests/Lifecycle/Helpers/GDTLifecycleTestPrioritizer.m
- GoogleDataTransport/GDTTests/Lifecycle/Helpers/GDTLifecycleTestUploader.m
- GoogleDataTransport/GDTTests/Unit/GDTUploadCoordinatorTest.m
- GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestPrioritizer.m
- GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestUploader.h
- GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestUploader.m
Refactors the GDTPrioritizer and GDTUploader interfaces, which caused some cascading changes.
- The removal of -unprioritizeEvents means that the logic was moved to an implementation of packageDelivered:successful:
- NSSecureCoding doesn't need a full implementation for GDTUploadCoordinator
- The upload coordinator doesn't track next upload times and doesn't run a completion block anymore. This prevents some lifecycle issues from occurring when restoring blocks.
- An implementor of GDTUploader now determines the appropriate time for an upload. A timer will run in GDTUploadCoordinator and regularly trigger -readyToUploadWithConditions in each uploader instance.
- Forcing an upload isn't as much a thing now. It simply triggers an upload attempt for that target with the 'High' priority …
>  Remove state management from the upload coordinator

- Gemfile
- Gemfile.lock
CocoaPods 1.6.2 fixes a pod lib lint bug with json podspecs and testspec's.
cocoapods-generate 1.5.0 enables pod gen to include local podspecs as dependencies in the generated Xcode project
> Update to CocoaPods 1.6.2 and CocoaPods generate to 1.5.0

- GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
- GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
- GoogleDataTransport/GDTLibrary/Private/GDTUploadCoordinator.h
- GoogleDataTransport/GDTTests/Common/Categories/GDTUploadCoordinator+Testing.m
- GoogleDataTransport/GDTTests/Unit/GDTTestCase.m
- GoogleDataTransport/GDTTests/Unit/GDTUploadCoordinatorTest.m
- GoogleDataTransport/GDTTests/Unit/GDTUploadPackageTest.m
- GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestPrioritizer.h
- GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestPrioritizer.m
This avoids a lot of housekeeping and situations in which two packages could be created by a prioritizer that have overlapping events in them.
> Ensure that only one package per target should ever be in flight

- scripts/check.sh
I noticed that non-master branch testing was still failing in https://travis-ci.org/firebase/firebase-ios-sdk/builds/533073316.
I debugged in a series of new branches prefixed with pb-travis-test. See recent runs at https://travis-ci.org/firebase/firebase-ios-sdk/builds
The pb-travis-test6 run demonstrates a successful first run with logging enabled.
> Fix check script for 1st travis run on non-master branch

- Package.swift
Also remove Environment's public header setting since all of its headers are private.
The travis runs are killable after the check phase.
> Add reachability build

- Firestore/core/src/firebase/firestore/remote/grpc_connection.cc
This brings us to parity with Android (https://github.com/firebase/firebase-android-sdk/blob/47d41b9dc17cd95a7799f672f5cc14f1747642ec/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java#L114) and addresses #2987.
> Enable gRPC Keepalives at 30s of inactivity.

- Example/Firebase.xcodeproj/project.pbxproj
- Firebase/InstanceID/FIRIMessageCode.h
- Firebase/InstanceID/FIRInstanceID.m
- Firebase/InstanceID/FIRInstanceIDBackupExcludedPlist.m
- Firebase/InstanceID/FIRInstanceIDCheckinPreferences.m
- Firebase/InstanceID/FIRInstanceIDCheckinService.m
- Firebase/InstanceID/FIRInstanceIDDefines.h
- Firebase/InstanceID/FIRInstanceIDKeyPairStore.m
- Firebase/InstanceID/FIRInstanceIDKeyPairUtilities.m
- Firebase/InstanceID/FIRInstanceIDStringEncoding.m
- Firebase/InstanceID/FIRInstanceIDTokenFetchOperation.m
- Firebase/InstanceID/FIRInstanceIDTokenOperation.m
- Firebase/InstanceID/FIRInstanceIDUtilities.m
- Firebase/InstanceID/FIRInstanceIDVersionUtilities.m
Remove the _FIRInstanceIDDevAssert which is supposed to be running only for debug mode. And it crashes the app when there's an error occurred. However, we already have error checking at the same time so there's no need to assert anything. Remove all the assertion logic to simplify the code base.
For assertion on condition that is already checked in code, remove the assertion.
For assertion on conditions that is not checked, remove the assertion and add a check and log with error or debug log.
This partially resolves the crash in #3018 but we are still investigating reason causing the error to occur.
> kill assertion code

- .travis.yml
- InAppMessaging/Example/Tests/FIRIAMClearcutUploaderTests.m
We [made FIAM tests non-required](https://github.com/firebase/firebase-ios-sdk/commit/dd0ae1de4ccc17c9c7cd441f14816c851d1b4257#diff-354f30a63fb0907d4ad57269548329e3) due to some flake in `FIRIAMClearcutUploaderTests`. After some testing on a debugging PR, I'm not seeing the flake anymore. I'm not certain what changed, but I did see that our Travis CI Xcode config was recently updated. This PR adds FIAM tests back to the required set.
- Also re-enabled a unit test that had been disabled.
> Make FIAM tests required for Travis CI build to pass

- Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
Other issue that have touched this is #401.
The error shown in  my logs is:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not create RMQ database at path /var/mobile/Containers/Data/Application/F0DD20A3-DA44-4033-8736-A371A2725EC1/Library/Application Support/Google/FirebaseMessaging/rmq2.sqlite, error: 23 - authorization denied'
*** First throw call stack:
(0x1e1a03758 0x1e0c0bd00 0x1e1919434 0x1e23f3754 0x102e05da8 0x102e04460 0x102e0968c 0x102ddd594 0x102ddce84 0x102ddc364 0x1e14158f4 0x1e1417788 0x102ddc2d0 0x102dba238 0x102dba0f0 0x102db9be8 0x102db99cc 0x102da0d94 0x102d9f3f4 0x102d9ef50 0x102d9ee7c 0x1032b66cc 0x1032b6510 0x102cb22d8 0x102cbb9cc 0x102cbdbc8 0x20e8db0c8 0x20e8dc890 0x20e8e22b0 0x20e175e20 0x20e17e7e8 0x20e175a88 …
```
> Disable data protection when opening the Rmq2PersistentStore

- Firestore/Example/Tests/Integration/API/FIRArrayTransformTests.mm
- Firestore/Example/Tests/Integration/API/FIRNumericTransformTests.mm
- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
- scripts/run_firestore_emulator.sh
... and re-enable tests that now work against it.
b/112104025 remains the major source of outstanding disabled tests.
@ryanpbrewster FYI
> Upgrade the emulator we use for integration testing to 1.4.6

- Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.mm
- scripts/cpplint.py
There are too many false positives to mark with NOLINT:
* BOOL is type in Win32
* BOOL is used as an identifier in the nanopb API
* YES and NO should be used when calling Objective-C APIs
* YES and NO are in the instructions for using NSDefaults
Leaving this check in place makes it impossible to change files that currently include these violations.
> Remove checks for boolean migration

- .travis.yml
- Example/Storage/Tests/Integration/FIRStorageIntegrationTests.m
- FirebaseStorage.podspec
- scripts/build.sh
- scripts/check.sh
- scripts/if_changed.sh
- scripts/install_prereqs.sh
- Add unit and integration test specs for FirebaseStorage.
- Add a complete Storage build and test rule.
- Extend an integration test timeout to fix a flake running `pod lib lint` locally.
- Fix build warnings in integration test source.
- Update integration tests to handle `1mb.dat` in either the main bundle or the the test target bundle.
- Run integration tests on all builds in the repo including PRs - only external PRs will not run them now.
- The old build environment is still supported.
- It will be removed when all pods have transitioned to test_specs and `pod gen`.
- For now, see the instructions at https://github.com/firebase/firebase-ios-sdk/blob/master/Functions/README.md.
> Add test_spec for FirebaseStorage

- .travis.yml
- Example/Database/Tests/Helpers/FDevice.m
- Example/Database/Tests/Helpers/FEventTester.m
- Example/Database/Tests/Helpers/FTestHelpers.m
- Example/Database/Tests/Helpers/SenTest+FWaiter.h
- Example/Database/Tests/Helpers/SenTest+FWaiter.m
- Example/Database/Tests/Integration/FData.m
- Example/Database/Tests/Integration/FIRDatabaseQueryTests.m
- Example/Database/Tests/Integration/FIRDatabaseTests.m
- Example/Database/Tests/Integration/FTransactionTest.m
- Example/Database/Tests/Unit/FTrackedQueryManagerTest.m
- Example/Database/Tests/third_party/Base64.m
- Example/Storage/Tests/Integration/FIRStorageIntegrationTests.m
- FirebaseDatabase.podspec
- scripts/build.sh
- scripts/if_changed.sh
- scripts/install_prereqs.sh
- Add unit and integration test specs for FirebaseDatabase.
- Add a complete Database build and test rule.
- Fix build warnings in test source.
- Update integration tests to handle 1mb.dat in either the main bundle or the the test target bundle.
- Run integration tests on all builds in the repo including PRs - only external PRs will not run them now.
- The old build environment is still supported.
- It will be removed when all pods have transitioned to test_specs and pod gen.
- For now, see the instructions at https://github.com/firebase/firebase-ios-sdk/blob/master/Functions/README.md.
> Add test_specs and fix test build warnings for Database

- .travis.yml
- Example/InstanceID/Tests/FIRInstanceIDAPNSInfoTest.m
- Example/InstanceID/Tests/FIRInstanceIDAuthKeyChainTest.m
- Example/InstanceID/Tests/FIRInstanceIDAuthServiceTest.m
- Example/InstanceID/Tests/FIRInstanceIDCheckinServiceTest.m
- Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
- Example/InstanceID/Tests/FIRInstanceIDKeyPairStoreTest.m
- Example/InstanceID/Tests/FIRInstanceIDStoreTest.m
- Example/InstanceID/Tests/FIRInstanceIDTest.m
- Example/InstanceID/Tests/FIRInstanceIDTokenInfoTest.m
- FirebaseInstanceID.podspec
- scripts/if_changed.sh
- Add unit test spec for InstanceID.
- Add a complete InstanceID build and test rule.
- Fix build warnings in test source.
- Fix tests for running on 32 bit simulators
- Remove redundant test
- The old build environment is still supported.
- It will be removed when all pods have transitioned to test_specs and pod gen.
- For now, see the instructions at https://github.com/firebase/firebase-ios-sdk/blob/master/Functions/README.md.
>  Add InstanceID test_spec

- Firestore/core/src/firebase/firestore/model/database_id.cc
- Firestore/core/src/firebase/firestore/model/database_id.h
- Firestore/core/test/firebase/firestore/model/database_id_test.cc
This makes it possible to use `DatabaseId` freely and naturally throughout instead of passing it with raw pointers as we currently do. Updates to usage and tests are coming in another PR.
> Make DatabaseId a cheap value type

- Example/Core/Tests/FIRBundleUtilTest.m
- Firebase/Core/FIRBundleUtil.m
Expected: Import the same GoogleService-Info.plist to app extension target and call FIRApp configure and succeed.
Currently: [FIRApp configure] return error:
[Firebase/Core][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'com.google.firebase.extensions.dev'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
> fix the typo error that cause bundle identifier checking failed for app extension

- Firebase/Auth/Source/Auth/FIRAuth.m
- Firebase/Auth/Source/Auth/FIRAuthDataResult.m
- Firebase/Auth/Source/Auth/FIRAuthDataResult_Internal.h
I investigated all FIRAuthDataResult usages in the Frebase Auth. There are two distinct ways to generate it.
Method 1:
FIRAuthResultCallback completion = ^(FIRUser * _Nullable user,
NSError * _Nullable error) {
FIRAuthDataResult *result =
[[FIRAuthDataResult alloc] initWithUser:user
additionalUserInfo:info];
callback(result, error); // Some calls callback(result, nil);
}
Method 2:
FIRAuthResultCallback completion = ^(FIRUser * _Nullable user,
NSError * _Nullable error) {
FIRAuthDataResult *result = user ?
[[FIRAuthDataResult alloc] initWithUser:user
additionalUserInfo:info] : nil;
callback(result, error);
}
I believe the second way is better for two reasons:
1. We don't need to change the public API to make user a nullable object.
2. When user is null, this means an error is occurred. So …
> In case user is nil, we don't generate FIRAuthResult.

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
- Firestore/Example/Tests/Model/FSTFieldValueTests.mm
- Firestore/core/src/firebase/firestore/model/field_value.h
- Firestore/core/test/firebase/firestore/model/field_value_test.cc
- Firestore/core/test/firebase/firestore/testutil/testutil.h
Also, split userdata converter tests out of FSTFieldValue tests.
Equality and comparison tests are not yet ported.
> Rewrite FieldValue tests to match the Android port

- scripts/install_prereqs.sh
The `pod repo update` command is necessary to make sure the CocoaPods repo is up-to-date.  It was mistakenly deleted in #3023 and that combined with today's Firebase 6.1.0 release caused travis breakages.
> Restore necessary pod repo update's

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
A companion to change to #3055 because Firestore still maintains a post-`pod install` project.
> Update Firestore.xcodeproj for CocoaPods 1.7

- .travis.yml
Testing via `pod lib lint` for FirebaseInstanceID has been very flaky so far.
This PR splits up the tests to make it easier to find the problems and resolve via retries. It also moves the `--use-libraries` and `--use-modular-headers` variations to the cron job since those should rarely fail independently.
The result should be faster and more reliable tests - and allow us to incrementally improve them, without suffering from too many flakes.
> Deflake and speedup iid tests

- FirebaseFirestore.podspec
- Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm
gRPC-C++ 0.0.9 is changing the certificate bundle name to gRPCCertificates-Cpp.bundle to allow gRPC-C++ to coexist with the Objective-C gRPC CocoaPod. Without this the bundles collide and cause build errors.
Note that we allow all the configuration variation in here to avoid this being a breaking change for our users who may be assembling projects by hand.
This change depends upon grpc/grpc#19082 and the release of gRPC-C++ 0.0.9, which hasn't happened yet.
> Handle new cert bundle name in gRPC-C++

- Example/Auth/Sample/FacebookAuthProvider.m
- scripts/build.sh
The Auth_ApiTests started failing in CI after the migration to CocoaPods 1.7.0.
- Migrate from deprecated Facebook API
- Start running the Auth_ApiTests on internal PRs - only exclude them for forks.
> Fix Auth post-submit CI build break

- Firestore/core/src/firebase/firestore/model/field_value.cc
- GoogleDataTransport/GDTLibrary/GDTPlatform.m
- GoogleDataTransport/GDTLibrary/Public/GDTPlatform.h
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
For some reason, style.sh is doing stuff to code that has previously passed the style.sh check.
> Reformat the repo

- scripts/build.sh
This overflows the logs in travis and makes it impossible to tell if
anything is actually going wrong.
> Remove --warn-uninitialized from CMake builds

- Firestore/core/src/firebase/firestore/remote/connectivity_monitor_noop.cc
Make the no-op connectivity monitor accept worker queue by a shared
pointer (a followup to #3004).
> Fix compilation error in non-Apple builds.

- .travis.yml
- Firebase/Core/FIRApp.m
- scripts/check.sh
Travis style checking was broken in #3020. This PR does a proper fix. See tests in pb-tmp* in recent runs at https://travis-ci.org/firebase/firebase-ios-sdk/builds. 
It may be helpful to see the delta from before #3020 ` git diff bad992edb3cbb4295d216941cb2571961b2a1da0 -- scripts/check.sh`
> Restore style checking on travis

- .travis.yml
- GoogleUtilities.podspec
- GoogleUtilities/Example/Tests/Network/GULNetworkTest.m
- GoogleUtilities/Example/Tests/Network/third_party/GTMHTTPServer.m
- GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
- GoogleUtilities/README.md
- scripts/if_changed.sh
Update GoogleUtilities development process to use CocoaPods testspec's and `pod gen`.
> GoogleUtilities to testspec and pod gen

- .travis.yml
- Example/Messaging/Tests/FIRMessagingAnalyticsTest.m
- Example/Messaging/Tests/FIRMessagingClientTest.m
- Example/Messaging/Tests/FIRMessagingDataMessageManagerTest.m
- Example/Messaging/Tests/FIRMessagingExtensionHelperTest.m
- Example/Messaging/Tests/FIRMessagingPendingTopicsListTest.m
- Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
- Example/Messaging/Tests/FIRMessagingRmqManagerTest.m
- FirebaseMessaging.podspec
- scripts/build.sh
- scripts/if_changed.sh
- scripts/install_prereqs.sh
- Add unit test spec for Messaging.
- Add a complete Messaging build and test rule.
- Testing is done via the `pod gen` generated workspace.
- Merge iOS 8 test fixes from @maksymmalyhin's #3094
- Fix build warnings in test source.
- The old build environment is still supported.
- It will be removed when all pods have transitioned to test_specs and pod gen.
- For now, see the instructions at https://github.com/firebase/firebase-ios-sdk/blob/master/Functions/README.md.
- Use `--local-sources=./` with `pod gen` to include local InstanceID in workspace: 
- ` pod gen FirebaseMessaging.podspec --local-sources=./ --auto-open`
> Add test_spec for FCM

- .travis.yml
By moving the rarely failing `--use-libraries` and `--use-modular-headers` testing to cron.
> Speed up regular testing

- Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.m
Running locally - `pod lib lint FirebaseInAppMessaging.podspec`
```
-> FirebaseInAppMessaging (0.15.0)
- NOTE  | xcodebuild:  note: Using new build system
- NOTE  | [iOS] xcodebuild:  note: Planning build
- NOTE  | [iOS] xcodebuild:  note: Constructing build description
- NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
- WARN  | xcodebuild:  /Users/paulbeusterien/gh4/firebase-ios-sdk/Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.m:59:22: warning: 'messageClicked:' is deprecated [-Wdeprecated-declarations]
- NOTE  | xcodebuild:  /Users/paulbeusterien/gh4/firebase-ios-sdk/Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h:338:72: note: 'messageClicked:' has been explicitly marked deprecated here …
```
> Fix FIAM pod lib lint issue

- Gemfile
- Gemfile.lock
CocoaPods 1.7.1 released today.
I don't expect any of its fixes to impact Firebase.
> CocoaPods 1.7.1

- scripts/module_map.rb
To enable the the zip builder to be more robust across CocoaPods versions
> Add script to generate a module map from a podspec

- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/Core/FSTQuery.h
- Firestore/Source/Core/FSTQuery.mm
- Firestore/Source/Core/FSTView.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/core/src/firebase/firestore/api/query_core.h
- Firestore/core/src/firebase/firestore/api/query_core.mm
- Firestore/core/src/firebase/firestore/core/query.h
This cleans up a warning you get about a bad cast when building in 32-bit mode. It also makes the limit have a portable type, where previously it was `NSInteger` which doesn't exist outside Apple platforms.
> Change limit to an int32 to match the backend

- Firestore/Source/API/FIRGeoPoint.mm
This fixes a warning I introduced in #3044.
The issue is that the header declares `-compare:` to be a part of the `Internal` category but the current state defines that method in the main `@implementation`. This moves the definition into the category to match the declaration.
> Fix -[FIRGeoPoint compare:] analysis warning

- Firebase/InAppMessaging/Analytics/FIRIAMClearcutLogStorage.h
- Firebase/InAppMessaging/Analytics/FIRIAMClearcutLogStorage.m
- Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m
- InAppMessaging/Example/Tests/FIRIAMClearcutUploaderTests.m
Fix #3046.
- Add a test specific cache file for logStorage so that tests don't fail because of stuff in the cache from other tests. Thanks to @ryanwilson for the suggestion and helper file implementation!
- Set up the `self.mockTimeFetcher currentTimestampInSeconds` stub before the mock is passed to other functions.
- Stop calling `scheduleNextSend` in the initializer since the first zero-delayed log can happen logs to happen to soon.
- Remove early exit from `scheduleNextSend` since it can cause logs to get dropped if the first zero-length log is scheduled, the next real log gets scheduled, but the log has already been dropped because of no packets available.
- Multiple spelling and wording fixes.
> Fix FIAM test flakes and exposed library bugs

- .travis.yml
- Example/Podfile
- Firestore/Example/Podfile
- InAppMessaging/Example/Podfile
- InAppMessagingDisplay/Example/Podfile
- SymbolCollisionTest/Podfile
- scripts/build.sh
- scripts/install_prereqs.sh
- scripts/pod_lib_lint.rb
Using the CDN makes the travis sub-jobs 1-4 minutes faster
Also:
- Create a pod_gen shell function to consolidate all usages of `pod gen`
- Clean up references to no longer needed SpecsStaging
- For GoogleDataTransport, use default `pod gen` workspace to be consistent and because the `pod gen` options `--gen-directory` and `--local-sources` do not work when combined.
> Use CocoaPods CDN

- Firestore/core/src/firebase/firestore/api/write_batch.h
Other `api` classes have that.
> Add a getter for Firestore pointer to api::WriteBatch

- Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential.m
- Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m
Facebook requires use of its official SDK for mobile and doesn't allow web based flows.
This is on par with Android implementation.
> Raise exception when log into Facebook using OAuth. 

- Firebase/InstanceID/FIRInstanceIDCheckinService.m
The timezone proto key passed in is in wrong format.
> correct timezone proto key

- Firestore/Source/API/FIRGeoPoint.mm
- Firestore/Source/API/FSTUserDataConverter.mm
- Firestore/Source/API/converters.h
- Firestore/Source/API/converters.mm
- Firestore/Source/Model/FSTFieldValue.h
- Firestore/Source/Model/FSTFieldValue.mm
... based on things learned porting Timestamps.
There's no good way to include conversions equivalent to toGeoPoint in
FIRTimestamp, so pull out separate conversion functions that match other
similar things.
Also clean up leftover references to `FIRGeoPoint` internally.
> Clean up GeoPoint port to C++

- Firestore/core/src/firebase/firestore/util/warnings.h
Also rework warnings.h to group by warning rather than compiler. Most warnings categories are supported by one compiler or Clang/GCC as a pair. This organization makes it possible to add just the one entry for those cases with an else that applies to all the other compilers.
There's no usage of this added in this PR, but there's a bunch of Abseil headers that don't compile cleanly without this that I use in later PRs.
> Add support for suppressing -Wcomma

- Firestore/third_party/abseil-cpp/absl/copts/GENERATED_AbseilCopts.cmake
- Firestore/third_party/abseil-cpp/absl/copts/GENERATED_copts.bzl
- Firestore/third_party/abseil-cpp/absl/copts/copts.py
These warnings are issued when building the `absl_time` library.
Note that `copts.py` is the master file, the rest are generated.
Note that the equivalent warnings don't apply in the Xcode build: we were already building absl_time there and the warnings are looser in our podspec anyway.
> Disable warnings in the Abseil build

- Example/Auth/AuthSample/Podfile
- Example/Podfile
- Firestore/Example/Podfile
- InAppMessaging/Example/Podfile
- InAppMessagingDisplay/Example/Podfile
- SymbolCollisionTest/Podfile
- scripts/install_prereqs.sh
- scripts/pod_lib_lint.rb
Disables CocoaPods CDN. Context:
https://github.com/firebase/firebase-ios-sdk/issues/3165
https://github.com/firebase/firebase-ios-sdk/commit/52e42c0fe77fab956603a3159a626bee5506af9b
> Disable CocoaPods CDN in pod installs (#3165)

- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
- Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm
- Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
- Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
- scripts/run_firestore_emulator.sh
This includes fixes for:
* All the field escaping tests
* `testCanWriteVeryLargeBatches`
* `testWritesWithIndirectlyNestedArraysSucceed`
All tests now pass. I've left isRunningAgainstEmulator in the source
even though there are now no callers.
@ryanpbrewster FYI
> Upgrade to Firestore Emulator 1.5.0

- Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.m
- Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h
- Firebase/InAppMessaging/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m
- Firebase/InAppMessaging/RenderingObjects/FIRInAppMessagingRenderingPrivate.h
- Firebase/InAppMessagingDisplay/Banner/FIDBannerViewController.m
- Firebase/InAppMessagingDisplay/Card/FIDCardViewController.m
- Firebase/InAppMessagingDisplay/ImageOnly/FIDImageOnlyViewController.m
- Firebase/InAppMessagingDisplay/Modal/FIDModalViewController.m
They never needed to be public, plan is to eventually remove and hide them in a private header.
> Deprecate initializers for FIAM view model objects

- FirebaseFirestore.podspec
- Firestore/CMakeLists.txt
- Firestore/Example/Tests/Model/FSTFieldValueTests.mm
- Firestore/Example/Tests/Model/FSTMutationTests.mm
- Firestore/Source/API/CMakeLists.txt
- Firestore/Source/API/FIRFieldPath.mm
- Firestore/Source/API/FIRFieldValue.mm
- Firestore/Source/CMakeLists.txt
- Firestore/Source/Model/CMakeLists.txt
- Firestore/Source/Model/FSTDocumentKey.mm
- Firestore/Source/Model/FSTFieldValue.h
- Firestore/Source/Model/FSTFieldValue.mm
- Firestore/Source/Model/FSTMutation.mm
- Firestore/core/src/firebase/firestore/api/CMakeLists.txt
- Firestore/core/src/firebase/firestore/model/CMakeLists.txt
- Firestore/core/src/firebase/firestore/model/field_value.cc
- Firestore/core/src/firebase/firestore/model/field_value.h
- Firestore/core/src/firebase/firestore/model/field_value.mm
- Firestore/core/src/firebase/firestore/model/transform_operations.h
- Firestore/core/test/firebase/firestore/model/field_value_test.cc
- Firestore/core/test/firebase/firestore/testutil/xcgmock.h
- Firestore/third_party/Immutable/CMakeLists.txt
- Firestore/third_party/Immutable/FSTArraySortedDictionary.m
- Firestore/third_party/Immutable/FSTArraySortedDictionaryEnumerator.m
- Firestore/third_party/Immutable/FSTImmutableSortedDictionary.h
- Firestore/third_party/Immutable/FSTImmutableSortedDictionary.m
- Firestore/third_party/Immutable/FSTTreeSortedDictionary.m
This includes a temporary change that makes the C++ `ServerTimestamp` include an Objective-C `FSTFieldValue*` as its previous value (0f6b330). This change will be reverted in the big switchover.
> Migrate FSTServerTimestampValue to FSTDelegateValue

- Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm
This fixes #3184, where under some circumstances some bundles have no
CFBundleIdentifier in their Info.plist.
> Defend against nil bundle identifiers

- Firebase/Storage/FIRStorageListTask.m
Fixes:
in firebase-ios-sdk/Firebase/Storage/FIRStorageListTask.m:73
Logic error: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
> Fixing Analysis issue in Storage

- Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m
This is likely a breaking change and an error should be logged instead.
> Revert "Raise exception when log into Facebook using OAuth.  (#3138)"

- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsSingleOperationPromiseCache.h
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsSingleOperationPromiseCache.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
The changes required to make sure that no parallel requests to register a FID or generate an auth token for the same app are performed.
> FIRInstallationsIDController - guarantee a single ongoing FID or AuthToken request

- Firebase/InAppMessaging/Runtime/FIRIAMSDKModeManager.m
Use the more appropriate `numberWithInteger:` rather than `numberWithInt:` to silence warnings.
> Silence InAppMessaging warnings on Xcode 11

- Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
- Firestore/Source/API/FIRDocumentSnapshot.mm
- Firestore/Source/Core/FSTQuery.mm
- Firestore/core/src/firebase/firestore/timestamp.cc
* remove C++11 library feature from `Timestamp` (which is supposed to be "portable");
* fix return type mismatch (`bool` vs `BOOL`);
* fix typo in function name.
> Fix small compilation and linter issues

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
- Firestore/Example/Tests/API/FSTAPIHelpers.mm
- Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
- Firestore/Example/Tests/Core/FSTQueryTests.mm
- Firestore/Example/Tests/Core/FSTViewSnapshotTest.mm
- Firestore/Example/Tests/Core/FSTViewTests.mm
- Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
- Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
- Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
- Firestore/Example/Tests/Local/FSTRemoteDocumentCacheTests.mm
- Firestore/Example/Tests/Model/FSTDocumentSetTests.mm
- Firestore/Example/Tests/Model/FSTDocumentTests.mm
- Firestore/Example/Tests/Model/FSTMutationTests.mm
- Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/Util/FSTHelpers.h
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Source/Local/FSTLocalSerializer.mm
- Firestore/Source/Model/FSTDocument.h
- Firestore/Source/Model/FSTDocument.mm
- Firestore/Source/Model/FSTMutation.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/core/src/firebase/firestore/model/document.h
- Firestore/core/test/firebase/firestore/remote/watch_change_test.mm
- Firestore/core/test/firebase/firestore/util/objc_compatibility_apple_test.mm
This is an almost entirely mechanical change that does the substitution.
> Migrate FSTDocumentState to C++ DocumentState

- Firebase/Messaging/FIRMessagingExtensionHelper.m
The build is currently broken in Xcode 11 because of this.
> Handle newly removed `userInfo` property on tvOS.

- Firebase/Core/FIRApp.m
- Firebase/Core/FIRBundleUtil.m
- Firebase/Core/FIRLogger.m
- Firebase/Core/Private/FIRAppInternal.h
- Firebase/Core/Private/FIRLogger.h
- Firebase/Core/Private/FIROptionsInternal.h
- Firebase/Core/Public/FIRConfiguration.h
- FirebaseCore.podspec
- Package.swift
- Sources/firebase-test/main.swift
Initial successful build of FirebaseCore with SPM.
SPM issues:
- Doesn't support private headers
- Doesn't support public header references from current pod
- Need to figure out versioning strategy and implementation with SPM
- SPM has bugs with `define` implementation for setting up build flags
> Build Core with SPM

- README.md
Travis uses 0.35.7 (tied to macOS 10.13), released 2018-10-11.
Latest homebrew shipped version is 0.40.9, released 2019-05-27.
This pins us back to 0.35.7.
> Update instructions for getting swiftformat

- Firebase/Auth/Source/Auth/FIRAuth.m
- Firebase/Auth/Source/User/FIRUser.m
1. set auth after getting user from shared keychain
2. fix a type bug
https://github.com/firebase/firebase-ios-sdk/issues/3197
> Fix keychain issues

- Firebase/Core/FIRApp.m
The FIAM static library build was still failing because it was linking the old CoreDiagnostics framework from the Analytics pod.
I added the symbols back to make the linker happy. They don't need values because the old CoreDiagnostics should not execute since the new CoreDiagnostics is in place now.
This PR should be reverted once there is a public FirebaseAnalytics that no longer includes the CoreDiagnostics.framework.
> Fix linker issue with deprecated CoreDiagnostics

- Firestore/CHANGELOG.md
Note that this changelog does not include your recent Swift Codable changes because we can't release them yet.
> Update CHANGELOG for Firestore v1.4.1

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/core/src/firebase/firestore/model/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/vector_of_ptr.h
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/vector_of_ptr_test.cc
The idea is to make equality by pointed-to-value fully encapsulated in things like `Query::filters_`.
This is a separate change from implementing filters to make it straightforward to review. We can add additional operations as required as we need them.
> Add a vector of pointers type

- Firebase/InAppMessaging/Data/FIRIAMFetchResponseParser.m
- Firebase/InAppMessaging/Data/FIRIAMMessageDefinition.h
- Firebase/InAppMessaging/Data/FIRIAMMessageDefinition.m
- Firebase/InAppMessaging/DisplayTrigger/FIRIAMDisplayTriggerDefinition.h
- Firebase/InAppMessaging/DisplayTrigger/FIRIAMDisplayTriggerDefinition.m
- Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.h
- Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.m
- Firebase/InAppMessaging/Flows/FIRIAMFetchFlow.h
- Firebase/InAppMessaging/Flows/FIRIAMFetchFlow.m
- Firebase/InAppMessaging/Flows/FIRIAMFetchOnAppForegroundFlow.m
- Firebase/InAppMessaging/Flows/FIRIAMMessageClientCache.h
- Firebase/InAppMessaging/Flows/FIRIAMMessageClientCache.m
- Firebase/InAppMessaging/Runtime/FIRIAMRuntimeManager.m
- InAppMessaging/Example/Tests/FIRIAMFetchFlowTests.m
There were two issues:
1. App launch FIAMs come through with a `fiamTrigger` param in the payload (as opposed to the `event` param for general analytics events) and we were only validating messages with a `fiamTrigger` of `ON_FOREGROUND`.
2. We needed to add a flow to check for app launch FIAMs at the appropriate time-- after the initial app launch fetch occurs and messages are retrieved and stored into the cache.
> Fix bug where app launch messages weren't appearing on iOS

- CMakeLists.txt
- cmake/podspec_cmake.rb
- cmake/podspec_rules.cmake
Essentially this makes it such that `PODS_TARGET_SRCROOT` is available for substitution in values derived from CocoaPods xcconfig settings
There's also a few misc fixes:
* Handle differences between CocoaPod and CMake dependency names
* Allow podspec-sourced libraries to compile with looser settings to match Xcode defaults
> CMake fixes for GoogleDataTransport

- cmake/external/grpc.cmake
gRPC packages 0.3.7-dev from 2016 in its own third_party directory and
builds it into libraries produced by CMake. Firestore depends on 0.3.9.2
via external dependency.
Firestore checks in its nanopb-generated sources for compatibility with
CocoaPods, where running the generator at build time on remote users'
machines is perilous. This means that Firestore's generated code must
match the version of nanopb available in CocoaPods.
Unfortunately, generated code from 0.3.7-dev and 0.3.9.2 are not
compatible with each other so we can't just downgrade the Firestore
CMake build to match gRPC and use its copy.
This change excludes gRPC's copy of nanopb until we get this fixed
upstream.
> Work around duplicate nanopb symbols in gRPC build

- scripts/pod_lib_lint.rb
After #3166, The Firestore pod lib lint tests started failing with
`/Users/travis/.travis/functions: line 524:  2896 Terminated: 15          travis_jigger "${!}" "${timeout}" "${cmd[@]}"`
despite still returning a green build status.
Googling `travis_jigger` shows some inconclusive issues with travis_wait.
I don't think `pod_lib_lint.rb` needs to do `pod repo update` but if so it should be done before the script runs so that travis jobs with multiple `pod lib lint` invocations only do it once.
> pod repo update is incompatible with travis_wait

- Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
- Firestore/Source/API/FIRCollectionReference.mm
- Firestore/Source/API/FIRDocumentReference.mm
- Firestore/Source/API/FIRDocumentSnapshot.mm
- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/core/src/firebase/firestore/api/input_validation_apple.mm
- Firestore/core/src/firebase/firestore/objc/objc_compatibility.h
- Firestore/core/src/firebase/firestore/util/error_apple.mm
- Firestore/core/src/firebase/firestore/util/hard_assert_apple.mm
- Firestore/core/src/firebase/firestore/util/path.h
- Firestore/core/src/firebase/firestore/util/string_apple.h
- Firestore/core/test/firebase/firestore/remote/datastore_test.mm
- Firestore/core/test/firebase/firestore/testutil/app_testing.mm
- Firestore/core/test/firebase/firestore/util/string_apple_test.mm
This makes it match the convention we've established for other
converters of this type. `WrapNSString` was perhaps the earliest of these
that we wrote and the convention hadn't yet been established.
Other examples:
https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Source/API/converters.h
https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/core/src/firebase/firestore/local/leveldb_util.h
> Rename WrapNSString to MakeNSString

- Firebase/Auth/Source/Backend/FIRAuthRequestConfiguration.h
- Firebase/Storage/Public/FIRStorageListResult.h
It can cause build warnings in Swift code.
From  https://developer.apple.com/documentation/objectivec/nsobject/1418641-init
> In terms of nullability, callers can assume that the NSObject implementation of init() does not return nil.
> Unavailable init methods should not be nullable

- GoogleUtilities/Logger/GULLogger.m
- GoogleUtilities/Logger/Public/GULLoggerLevel.h
ifndef guard the GULLoggerLevel enum.
Quite often, usually on every first compile step, I run into these kind of errors:
```
In file included from /Users/ened/git/com.company.app/ios/Pods/GoogleUtilities/GoogleUtilities/Logger/GULLogger.m:20:
/Users/ened/git/com.company.app/ios/Pods/GoogleUtilities/GoogleUtilities/Logger/Public/GULLoggerLevel.h:20:28: error: redefinition of 'GULLoggerLevel'
typedef NS_ENUM(NSInteger, GULLoggerLevel) {
^
In file included from /Users/ened/git/com.company.app/ios/Pods/GoogleUtilities/GoogleUtilities/Logger/GULLogger.m:15:
In file included from /Users/ened/git/com.company.app/ios/Pods/GoogleUtilities/GoogleUtilities/Logger/Private/GULLogger.h:19:
/Users/ened/git/com.company.app/build/ios/Profile-iphoneos/GoogleUtilities/GoogleUtilities.framework/Headers/GULLog …
```
> Import GULLoggerLevel.h via public framework header

- FirebaseFirestore.podspec
- Firestore/Example/Podfile
This removes the need to munge the pods project after the fact and makes
it so that customers can click through to our headers too.
> Put the need to include Firestore/Source/Public in the podspec

- Firebase/Storage/CHANGELOG.md
- Firebase/Storage/FIRStorage.m
- Firebase/Storage/Public/FIRStorage.h
Obj-C/Swift lets you call the init-method on Storage, even though our users are supposed to use the factory methods. While `[[FIRStorage alloc] init]` results in a compile error (due to our usage of NS_UNAVAILABLE), `[FIRStorage new]` does not. This PR makes sure that we crash the process early on, and not further down the line as reported in https://github.com/firebase/firebase-ios-sdk/issues/3282
Fixes https://github.com/firebase/firebase-ios-sdk/issues/3282
> Ensure Storage initializer doesn't get called

- Example/Core/Tests/FIROptionsTest.m
- Firebase/Core/FIROptions.m
- Firebase/Core/Public/FIROptions.h
This is a PR required for the application extensions support:
- a property `FIROptions.appGroupID` added which can be used by Firebase SDKs to share data between the application and the app extensions.
> FIROptions.appGroupID introduced

- Firestore/CHANGELOG.md
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests_macOS.xcscheme
- Firestore/Example/Tests/Integration/API/FIRNumericTransformTests.mm
- Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
- Firestore/Example/Tests/Model/FSTMutationTests.mm
- Firestore/Example/Tests/Model/transform_operations_test.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Model/FSTMutation.h
- Firestore/Source/Model/FSTMutation.mm
- Firestore/core/src/firebase/firestore/model/field_mask.cc
- Firestore/core/src/firebase/firestore/model/field_mask.h
- Firestore/core/src/firebase/firestore/model/field_transform.h
- Firestore/core/src/firebase/firestore/model/field_value.cc
- Firestore/core/src/firebase/firestore/model/field_value.h
- Firestore/core/src/firebase/firestore/model/transform_operations.h
- Firestore/core/src/firebase/firestore/model/transform_operations.mm
- Firestore/core/test/firebase/firestore/model/field_value_test.cc
Port of https://github.com/firebase/firebase-android-sdk#564 and https://github.com/firebase/firebase-js-sdk/pull/1928
The PR changes what we store in a BaseMutation. With the changes here, every transform operation computes what it needs to store in the BaseMutation. For Numeric increment, this is either an existing numeric value or the IntegerValue.of(0), replacing all invalid base values at time of creation.
> Store the coerced base value in the BaseMutation

- Firebase/InAppMessagingDisplay/Card/FIDCardViewController.m
- InAppMessagingDisplay/Example/FiamDisplaySwiftExample/CardMessageViewController.swift
Bug fix where text color wasn't taking effect for the card message's body text
> In card message: set the text color on the body text view

- GoogleUtilities/AppDelegateSwizzler/README.md
Hey,
Just a 'micro-pr' to add a missing semi-colon on the `AppDelegateSwizzler` readme, makes it valid now when copying into a header file.
> [docs] add missing semicolon

- GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h
- GoogleUtilities/CHANGELOG.md
- GoogleUtilities/Common/GULLoggerCodes.h
- GoogleUtilities/Logger/Public/GULLoggerLevel.h
- GoogleUtilities/Network/Private/GULNetworkMessageCode.h
- GoogleUtilities/Reachability/Private/GULReachabilityMessageCode.h
This is causing issues when building an XCFramework. This work relates to #3144
> Add explicit Foundation import.

- FirebaseInstallations/Source/Library/FIRInstallations.m
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Library/Public/FIRInstallations.h
- FirebaseInstallations/Source/Library/Public/FIRInstallationsAuthTokenResult.h
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
Firebase Installations changes:
- `[FIRInstallations installations]` added
- API docs for public methods and classes added
- some cleanup and fixes
> Firebase Installations- missing API and API docs

- FirebaseInstallations/Source/Library/FIRInstallations.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
Firebase Installations: 
- request auth token on each initialization to prevent unwanted FID garbage collection (if the server does not get any request with a FID during 18 months, then FID and all related data will be deleted).
> Firebase Installations - eagerly request auth token

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Podfile
- scripts/build.sh
- scripts/sync_project.rb
Ever since we added multiple platforms, removing a file has been broken. It succeeds for the first platform and then fails on a subsequent one. This fixes that issue.
Also, rewrite target synchronization to make more sense. Essentially now there's one diff between the filesystem and the groups and then an explicit diff is done between project files and target contents.
> Fix and rewrite sync_project.rb

- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
Fix for flaky tests. Flakiness was introduced by #3308 by starting a background operation on FIRInstallations initialization.
> Firebase Installations - fix flaky tests

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- scripts/check.sh
- scripts/sync_project.rb
This fixes macOS and tvOS builds such that they no longer need to explicitly link against the built FirebaseFirestore framework, which is good because this wasn't working right: changes to the framework would take two builds to get tests to actually see them.
The mechanism here is to amend the `.xcconfig` files that CocoaPods plugs into the project, just after it generates them. This avoids the need to actually modify the `project.xcodeproj` file, which reduces the potential for conflicts.
Going forward all manual modifications to the project's configuration will be handled this way to avoid needing special project configuration.
This also moves us incrementally closer to be being able to use test specs and cocoapods-generate. There's too much custom configuration yet (and several other …
>  Add an -all_load linker flag to all example apps

- GoogleUtilities/Network/GULMutableDictionary.m
Fixes one of the issues revealed by the crash #3183.
Motivation:
When a mutable dictionary adds or removes an object it accesses the object to call methods like `hash` and `isEqual:`, also, removing the object from the dict may trigger the object deallocation. `GULMutableDictionary` performs these operations on a background thread, which put an **implicit** requirement on the object methods implementations to be thread-safe (see [the crash](https://github.com/firebase/firebase-ios-sdk/issues/3183#issuecomment-507860199) description caused by a not thread-safe `GULObjectSwizzler` stored in `GULMutableDictionary`) . This thread-safety requirement limits the usage of `GULMutableDictionary`,  and does not look like an intended thing. 
This PR fixes it by replacing  `dispatch_async` by …
> GULMutableDictionary: use `dispatch_sync` instead of `async`.

- Firebase/DynamicLinks/FIRDynamicLinks.m
- Firebase/InstanceID/FIRInstanceID.m
This is the open source part of b/137222285.
The implementation in FirebaseCore can be removed after the closed source part is done.
> Stop calling deprecated sendLogsWithServiceName

- scripts/run_firestore_emulator.sh
This just brings us up-to-date without any functional changes as far as
the SDK is concerned.
> Upgrade to Firestore Emulator 1.6.1

- GoogleUtilities.podspec
- GoogleUtilities/CHANGELOG.md
- GoogleUtilities/Network/GULMutableDictionary.m
Reverts firebase/firebase-ios-sdk#3322
Reverting it so far to better validate impact on Analytics first.
> Revert "GULMutableDictionary: use `dispatch_sync` instead of `async`."

- Firestore/Example/Benchmarks/FSTLevelDBBenchmarkTests.mm
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Benchmarks_iOS.xcscheme
- Firestore/Example/Podfile
- scripts/sync_project.rb
This change:
* Makes it possible to build the benchmarks in Xcode (by adding a scheme)
* Manages configuration for benchmarks and fuzz tests via `sync_project.rb`
* Fixes the fuzz tests by passing `-fsanitize=fuzzer`. The old method of passing `-fsanitize-coverage=trace-pc-guard` is no longer supported by LibFuzzer.
> Manage configuration for benchmarks and fuzz tests and fix them

- Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
This causes a breakage with internal tests.
> Fix unaccessible init in FDL tests.

- scripts/build.sh
Removing DerivedData can be costly, especially on Firestore build retries.
Since this is only known to help flakes related to coverage data collection, this PR moves the `rm` to the only place we're currently collection coverage.
> Handle coverage flakiness more locally

- .travis.yml
The database travis stage stopped running after a typo from #3115.  
The unit tests have continued to run from the deprecated xcodeproject test, but not the integration tests.
This PR restores the stage.
> Restore Database integration tests

- FirebaseInstallations/Source/Library/FIRInstallations.m
- FirebaseInstallations/Source/Library/FIRInstallationsErrorUtil.h
- FirebaseInstallations/Source/Library/FIRInstallationsErrorUtil.m
- FirebaseInstallations/Source/Library/FIRSecureStorage.h
- FirebaseInstallations/Source/Library/FIRSecureStorage.m
- FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Library/Public/FIRInstallationsErrors.h
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
This is the first part of the error related changes. I am breaking the changes into parts to simplify the review:
- make sure all errors reported by SDK are in `FirebaseInstallationsErrorDomain` domain.
- retry Auth Token request on HTTP 500
- send proper `sdkVersion` to the server
> Firebase Installations - error reporting and API errors handling

- Firestore/Example/Podfile
This doesn't handle adding/removing files reliably when the version of
the pod doesn't change. That means incremental installation is
essentially not useful in combination with development pods.
> Disable incremental installation

- Firestore/core/src/firebase/firestore/local/leveldb_migrations.cc
This is just to make the failure more obvious (otherwise, the call to `std::stoi` fails).
> Assert version is read successfully from LevelDB

- Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
- Firestore/Example/Tests/SpecTests/json/orderby_spec_test.json
- Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
This brings in the new spec tests with the exception of
"Array-contains queries support resuming" (iOS doesn't support array-contains yet) and
"Latency-compensated updates are included in query results" (underlying bug is not yet fixed).
> Update Spec tests

- AddNewPod.md
Both CocoaPods and SwiftPM typically expect headers to be nested in the Sources directory.
Thanks @dmandar for catching this.
> Headers are part of Sources

- scripts/run_firestore_emulator.sh
This just brings us up-to-date without any functional changes as far as
the SDK is concerned.
> Upgrade to Firestore Emulator 1.6.2

- Firestore/CHANGELOG.md
- scripts/make_release_notes.py
Translates from CHANGELOG markdown to release notes markdown.
`scripts/make_release_notes.py Firestore/CHANGELOG.md` generates exactly what @morganchen12 manually put together in the latest release note snippet.
> Add a release notes generator

- Firestore/core/src/firebase/firestore/immutable/sorted_map_iterator.h
- Firestore/core/src/firebase/firestore/util/statusor_internals.h
Added a couple of missing `noexcept` specifiers. While it probably won't affect performance much, it certainly won't hurt.
> Make sure all move operations are marked noexcept

- Gemfile
- Gemfile.lock
1.7.5 fixes a Swift flag issue that shows up in Xcode 11 beta 4 - https://github.com/CocoaPods/CocoaPods/issues/9013
> CocoaPods 1.7.5

- .travis.yml
- scripts/pod_lib_lint.rb
The modification is required to support `FirebaseInstallations` tests which require a particular version of `FirebaseInstanceID` to test migration.
- `./scripts/pod_lib_lint.rb.`: a parameter `--ignore-local-specs` introduced to specify the local podspecs to be ignored (publicly available versions will be used instead).
> pod_lib_lint.rb - argument to ignore specified local podspecs

- Firestore/core/src/firebase/firestore/core/array_contains_filter.h
- Firestore/core/src/firebase/firestore/core/key_field_filter.h
Some classes derived from `FieldFilter` declare a `=default` default
constructor. This actually makes the constructor deleted, because the
base class has no default constructor, resulting in a compilation
warning.
> Remove `=default`ed constructors resulting in deleted constructors.

- .travis.yml
- scripts/pod_lib_lint.rb
Fixes #3416.
- comment out `social_media_url` in the linted podspec to fix #3416
- make sure the script fails if `pod lib lint` fails (converts silent failures like [this](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/562678041) to visible failures like [this](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/562705029))
> pod_lib_lint.rb improvements

- Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
- Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
Without `has_sdk_name == true` the field `sdk_name` is ignored.
> CoreDiagnostics: set missing flag `has_sdk_name` for heartbeats.

- Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
- Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
* CoreDiagnostics: set missing flag `has_sdk_name` for heartbeats.
* Validate `has_sdk_name` in tests.
> CoreDiagnostics: set missing flag `has_sdk_name` for heartbeats. (#3422)

- Firestore/Source/Core/FSTQuery.mm
- Firestore/core/src/firebase/firestore/core/query.cc
- Firestore/core/src/firebase/firestore/core/query.h
- Firestore/core/test/firebase/firestore/core/query_test.cc
This removes the ambiguity between the `Filter` class and the `Filter` method.
I'm not sure if there's a C++ convention for how to name methods that operate on an immutable object to produce a new, modified immutable object, but in Swift [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/#name-according-to-side-effects) produce this name and it reads pretty well. Of course there's a limit to how well Swift API guidelines can apply to C++ because C++ does not have argument labels, but this part seems to apply cleanly. Thoughts?
> Rename Query::Filter to Query::AddingFilter

- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
- FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.m
- delete existing IID on the default app installation delete
- use IID as FID only for the default app
> Firebase Installations: delete IID on default app installation delete.

- Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
- use boolean operation to calculate `isSentEventHeartbeat` (instead of a bitwise) - fixes the [comment](https://github.com/firebase/firebase-ios-sdk/pull/3422#discussion_r306943125)
> CoreDiagnostics tests code style.

- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/core/src/firebase/firestore/core/transaction.h
- Firestore/core/src/firebase/firestore/core/transaction.mm
Based on Android [port](https://github.com/firebase/firebase-android-sdk/pull/628).
Added checks in Transaction for checking user errors.
> Only retry transactions on non-permanent errors

- .travis.yml
Split and rename cron sub-job to mitigate timeout failures
Remove if_changed checks from cron jobs
Remove unnecessary install_prereqs invocations.
> Split a cron sub-job to mitigate timeout failures

- Example/Core/Tests/FIRAppTest.m
- Firebase/Core/FIRApp.m
- Firebase/Core/FIRCoreDiagnosticsConnector.m
- Firebase/Core/Private/FIRCoreDiagnosticsConnector.h
It is needed to send reliable heartbeats even if an application is not relaunched for a long time.
> FirebaseApp: send Core Diagnostics data on appDidBecomeActive

- FirebaseInstallations/Source/Library/FIRInstallations.m
- installations requests auth token on init. We would not like to request it before FirebaseApp has been configured. Let's use `FIRInstantiationTimingLazy`. We need to consider updating our components system to provide an App Configured call back.
> FIRInstallations: use lazy initialization 

- Example/Auth/Tests/FIRAuthTests.m
- Firebase/Auth/Source/Auth/FIRAuth.m
This makes the behavior consistent between iOS and Android for `additionalUserInfo` of an anonymous sign-in. Right now the iOS SDK is returning `"password"` (email sign-in) as the `providerID` but I think `nil` would be more appropriate and matches Android.
Also added a test.
Fixes firebase/firebase-ios-sdk#3450
> providerID should be nil in additionalUserInfo for signInAnonymouslyWithCompletion:

- Example/Auth/Tests/FIRUserTests.m
- Firebase/Auth/Source/User/FIRUser.m
Fixes #3445 ("signInProvider property of FIRAuthTokenResult returns nil")
I added a test to `Example/Auth/Tests/FIRUserTests.m`. This only tests email and password sign-in.
> fix for signInProvider property of FIRAuthTokenResult returning nil

- Interop/FirebaseComponentSystem.md
Hey 👋 
Nothing major, just some small syntax fixes & setting the code block languages to enable syntax highlighting. 
Came across these docs today when migrating from [`kFIRAppReadyToConfigureSDKNotification` to `[library configureWithApp]`](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Core/FIRApp.m#L409-L421).
(Thanks for documenting the internals, it's been super helpful whilst I'm working on `react-native-firebase` 🎉)
- Documentation changes only.
- Documentation changes only.
> [docs] fix syntax errors & enable highlighting

- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
`XCTAssertLessThanOrEqual(exp1, exp2)` errors when `exp1 > exp2`.
> Fix flaky integration test

- GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
This should better detect mobile vs. wifi connectivity, which is important because telemetry data should not be uploaded over mobile (except after 24h).
> Simplify the wifi vs. mobile data connection code.

- Firestore/Example/Podfile
This reverts commit d3ba21f87adfcab576a719344413e75ea9210593.
#3356 disabled incremental installation because I observed that when changing branches, files that were added and removed weren't necessarily reflected in the Xcode build and this caused the build to fail with missing source files or missing symbols.
Since then I conducted a series of experiments using the `xcodebuild` command-line and confirmed that CocoaPods is actually doing the right thing. What I was observing was that the Xcode UI still doesn't always pick up changes to the underlying generated project. Restarting Xcode after a branch change forces it to pick these changes up and then interactive builds work too.
> Revert "Disable incremental installation"

- Firestore/Example/Podfile
This cuts incremental pod install time down from ~120 seconds to ~25.
If we ever need to jointly develop features with Core or Auth again we
can re-add these entries temporarily.
> Remove the rest of Firebase as development pods

- Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
We have a few methods in FIRMessagingRemoteNotificationsProxy.m doesn't follow objective C naming convention, also they can be confused with the run time methods with "_" in the naming.
b/65217183
Tested: Analytics logging is working after swizzling.
> rename a few methods and properties to fit in the readability

- Example/Database/Tests/Unit/FLevelDBStorageEngineTests.m
- Firebase/Database/third_party/SocketRocket/FSRWebSocket.m
Fixes #3189
Successfully run unit tests on Catalyst with Xcode 11 beta 5
> Update Database for Catalyst

- Example/InstanceID/Tests/FIRInstanceIDKeyPairMigrationTest.m
With this change the IID unit tests run on Catalyst after adding Keychain Sharing Capability.
> IID unit test update for Catalyst

- .travis.yml
- Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
- FirebaseCoreDiagnostics.podspec
- GoogleDataTransport.podspec
- GoogleDataTransport/GDTLibrary/GDTConsoleLogger.m
- GoogleDataTransport/GDTLibrary/GDTPlatform.m
- GoogleDataTransport/GDTLibrary/GDTReachability.m
- GoogleDataTransport/GDTLibrary/GDTStorage.m
- GoogleDataTransport/GDTLibrary/GDTTransformer.m
- GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
- GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
- GoogleDataTransport/GDTLibrary/Public/GDTConsoleLogger.h
- GoogleDataTransport/GDTLibrary/Public/GoogleDataTransport.h
- GoogleDataTransport/GDTTests/Unit/GDTTransformerTest.m
- GoogleDataTransport/GDTTests/Unit/GDTUploadPackageTest.m
- GoogleDataTransportCCTSupport.podspec
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
* Remove asserts and replace with GDTLogs
Should infrequently log to the console in !NDEBUG builds instead of asserting.
* Remove tests that check for assertions.
> Remove asserts and replace with GDTLogs (#3535)

- GoogleDataTransport/GDTLibrary/GDTStorage.m
- GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
Fixes 3547, in theory. This code all goes away/changes with the sqlite refactor, so making it safe is probably sufficient for now. No one was able to reproduce locally, most likely because this is a lifecycle issue.
> Make ivar references safer

- Firebase/Auth/Source/Public/FIRAuth.h
- Firebase/Auth/Source/Public/FIRAuthErrors.h
- Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
- Firebase/Auth/Source/Utilities/FIRAuthInternalErrors.h
- Firebase/Auth/Source/Utilities/FIRAuthURLPresenter.h
- Firebase/Auth/Source/Utilities/FIRAuthWebView.h
- Firebase/Auth/Source/Utilities/FIRAuthWebView.m
- Firebase/Auth/Source/Utilities/FIRAuthWebViewController.m
WKWebView was introduced in iOS 8 and is the only WebView option for Catalyst.
Builds and passes unit tests for Catalyst.
> Migrate Auth from UIWebView to WKWebView

- GoogleDataTransport/GDTLibrary/GDTStorage.m
- GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
- GoogleDataTransport/GDTTests/Unit/GDTClockTest.m
- GoogleDataTransport/GDTTests/Unit/GDTEventTest.m
- GoogleDataTransport/GDTTests/Unit/GDTStorageTest.m
- GoogleDataTransport/GDTTests/Unit/GDTUploadPackageTest.m
Fix Build issues for GDT on Catalyst
This enables building for dependent pods and the tests.
> Build GDT for Catalyst

- .travis.yml
- Example/Auth/AuthSample/AuthSample.xcodeproj/project.pbxproj
- scripts/build.sh
The first Travis phase started failing yesterday because of an Auth backend issue.
- Restore travis success
- Move Auth integration tests to the Auth specific phase
- Fix AuthSample xcproject issue for deleting file
- Recomment integration test runs while backend is broken.
> Run Auth integration tests only in Auth travis phase

- Example/Messaging/Tests/FIRMessagingServiceTest.m
- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingClient.m
- Firebase/Messaging/FIRMessagingCodedInputStream.m
- Firebase/Messaging/FIRMessagingConnection.m
- Firebase/Messaging/FIRMessagingContextManagerService.m
- Firebase/Messaging/FIRMessagingDataMessageManager.m
- Firebase/Messaging/FIRMessagingDefines.h
- Firebase/Messaging/FIRMessagingDelayedMessageQueue.m
- Firebase/Messaging/FIRMessagingPubSub.m
- Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
- Firebase/Messaging/FIRMessagingRmqManager.m
- Firebase/Messaging/FIRMessagingSecureSocket.m
- Firebase/Messaging/FIRMessagingSyncMessageManager.m
- Firebase/Messaging/FIRMessagingTopicOperation.m
- Firebase/Messaging/FIRMessagingVersionUtilities.m
Remove _FIRMessagingDevAssert that are only called if a DEBUG flag, which is never set in both debug/production build. Most of the assert logics are already been checked in the code, for the ones that are not, we replace it with a debugLog.
Also remove a few macros that are either not used at all or barely used.
> kill debug assert and unnecessary macros

- Firestore/CHANGELOG.md
Just double-checking: we've made a bunch of changes on master but none of those changes result in user-visible behavioral changes. We're still obligated to release, right?
> Update CHANGELOG for Firestore v1.4.4

- Example/Messaging/Tests/FIRMessagingInstanceTest.swift
- Example/Messaging/Tests/FIRMessagingTest.m
- Firebase/Messaging/CHANGELOG.md
- Firebase/Messaging/FIRMessaging.m
- FirebaseMessaging.podspec
This fixes #3411. Test fails before the code change, and succeeds
afterwards.
> Ensure Messaging instance is usable after FIRApp's `delete`

- Firestore/Swift/Source/Codable/third_party/FirestoreDecoder.swift
- Firestore/Swift/Tests/Codable/FirestoreEncoderTests.swift
Very small addition to swift Firestore.Decoder() that allows a `Timestamp` to be decoded as a `Date`. This is import because Firestore now returns all dates as timestamps, and this allows clients to continue to use `Date` objects in their models. Please see #627
> Allow decoding Timestamp as a Date

- ZipBuilder/Sources/ZipBuilder/HashCalculator.swift
The `unsafeBytes` method has different parameters from Swift 4.2 -> 5, this should work for both.
> Fix Zip builder in Xcode 10.1

- Firebase/InAppMessagingDisplay/FIRIAMDefaultDisplayImpl.m
- the change to mitigate the issue #3558: avoid crashing even if the resource bundle is not found.
Fixes: #3558.
> FIRIAMDefaultDisplayImpl: validate bundleURL to prevent crash.

- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
The problem was essentially that each test instance was deleting the
documents directory which contains all persistent data for all
instances.
Unfortunately our tests aren't entirely deterministic and rarely one
test would overlap with another. When this happened the setup code for
the next test would delete the data out from underneath the previous
one.
Before this fix we'd see frequent travis failures and I would see an
occasional local failure (1 out of ~5 runs). With this fix I've seen no
failures in 30 cycles.
> Fix flakiness in Firestore integration tests

- .travis.yml
There's currently a nontrivial TSAN issue with LevelDB that causes these
to fail. Resolution of that issue is tracked as b/139669731. Once that
is resolved, we can revert this change.
> Disable Firestore xcodebuild with tsan

- GoogleDataTransport/CHANGELOG.md
- GoogleDataTransport/GDTLibrary/GDTStorage.m
- GoogleDataTransport/GDTLibrary/Private/GDTStorage_Private.h
- GoogleDataTransport/GDTLibrary/Public/GDTPlatform.h
- GoogleDataTransport/GDTTests/Lifecycle/GDTLifecycleTest.m
- GoogleDataTransport/GDTTests/Unit/GDTStorageTest.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
Fixes 3625.
Fixes 3623.
Backgrounding causes GDTStorage to exhibit a couple of issues:
- a deadlock when `-[NSKeyedArchiver archivedData...]` is called in the background in `-[GDTStorage storeEvent:]`
- multiple background tasks being created, at least 1 per call to `-storeEvent`, without sufficient state management or checks for background task ID validity
> Fix backgrounding in GDTStorage

- GoogleDataTransport/GDTLibrary/GDTPlatform.m
- GoogleDataTransport/GDTLibrary/GDTStorage.m
- GoogleDataTransport/GDTLibrary/GDTTransformer.m
- GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
- GoogleDataTransport/GDTLibrary/Private/GDTStorage_Private.h
- GoogleDataTransport/GDTTests/Unit/GDTStorageTest.m
Also deletes a test that can't be run now.
Fixes #3625 
I believe there's still an issue on iOS 13 beta 5 on device, but I think it's an issue in iOS. I created a reduced test case, you see the entirety of the code and the warning below. The warning does not occur on a device that's iOS 12.
> More safely manage background tasks

- ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift
The zip file and Carthage distribution use different modulemaps - use
the correct one for Carthage. Will address #3578 once this is used in
generating the next Carthage release.
> Use different modulemap for Carthage.

- Firestore/core/src/firebase/firestore/api/document_snapshot.h
- Firestore/core/src/firebase/firestore/api/firestore.h
- Firestore/core/src/firebase/firestore/api/listener_registration.h
- Firestore/core/src/firebase/firestore/api/write_batch.h
- Firestore/core/src/firebase/firestore/core/event_manager.h
- Firestore/core/src/firebase/firestore/core/query_listener.h
- Firestore/core/src/firebase/firestore/core/view_snapshot.h
- Firestore/core/src/firebase/firestore/model/document_map.h
- Firestore/core/src/firebase/firestore/objc/objc_class.h
- Firestore/core/src/firebase/firestore/util/nullability.h
This will make it such that nullability macros can survive even after we remove `OBJC_CLASS`.
> Factor out nullability.h

- FirebaseDatabase.podspec
- FirebaseFirestore.podspec
This can only be merged once we push the corresponding leveldb pod https://github.com/firebase/leveldb-library-podspec/pull/9.
> Upgrade LevelDB to 1.22

- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingContextManagerService.m
Fix the issue local timezone message is not logged with "notification_open". b/137177917
Local timezone message is sent down ahead of time in hidden message ("content-available") and device schedule a local notification from the info provided by such hidden message.
When we schedule a local notification, the APNS payload inside "aps" key is copied over to the scheduled local notification. And when the local notification is delivered, device mistakenly thinks it's a duplicate message because it contains both gcm.message_id and "aps" payload. It thinks it's passed down in both direct channel and APNS channel.
In general, the APNS payload should not be copied over because we schedule local notification ONLY based on FCM payload, that is provided with "gcm.notification" prefix keys.
> fix why local timezone message is never logged

- .travis.yml
- FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNTestUtilities.h
- scripts/if_changed.sh
Set up CI for Remote Config and make fixes for successful `pod lib lint` tests
- Fix warnings
- Ignore deprecations
- Fix tests that were dependent upon running in Pacific time zone
- Fix travis-only test failure relying upon non-deterministic NSDictionary factory types
> Start RemoteConfig CI and fix/ignore warnings

- FirebaseFirestore.podspec
- Firestore/CHANGELOG.md
- Firestore/core/src/firebase/firestore/remote/connectivity_monitor_apple.mm
In #3467, we changed the connectivity monitor to take callbacks from
SCNetworkReachability on the main thread but didn't make the
corresponding change to enqueue the notification back onto Firestore's
worker.
Bump Firestore to v1.4.5.
> Fix connectivity monitor redispatching.

- Firestore/core/src/firebase/firestore/remote/connectivity_monitor_apple.mm
In #3467, we changed the connectivity monitor to take callbacks from
SCNetworkReachability on the main thread but didn't make the
corresponding change to enqueue the notification back onto Firestore's
worker.
Fixes #3661.
> Fix connectivity monitor redispatching

- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
- ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
- ZipBuilder/Sources/ZipBuilder/main.swift
This never really worked that well, and isn't used since we're now
building the zip file on Kokoro. Quick iterations can be handled with
changing the `podsToInstall` variable leaving this code outdated and
unnecessary.
> Remove support for cached zip builds.

- ZipBuilder/Sources/ZipBuilder/main.swift
This should prevent unintentional overrides during CI runs.
> Rename carthage directory when there's no RC number

- scripts/run_firestore_emulator.sh
No functional changes for us, but does keep us up-to-date.
> Upgrade Firestore emulator to 1.8.0

- Firebase/DynamicLinks/CHANGELOG.md
- Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m
- FirebaseDynamicLinks.podspec
- Releases/Manifests/6.8.0.json
Cherry-pick #3723 to M55 (6.8.0) and add FDL to the release.
> Add FDL to M55

- .travis.yml
- Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_IntegrationTests_iOS.xcscheme
- Firestore/core/src/firebase/firestore/core/view.cc
This was caused by running under Asan with XCode 11. Apparently, previous versions of XCode cannot catch it (which is why Travis is passing, apparently).
Also:
* enable "Detect use of stack after return" option for Asan. AFAIU, it can only be enabled in the scheme. It's already enabled for unit tests, this PR additionally enables it for integration tests;
* make Asan failures fail Travis build. They were originally not considered blocking due to false positives. I haven't seen those for some time, and worst case scenario, we can revert this change.
> Fix accessing a destroyed object

- Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
- Firestore/Source/Local/FSTLocalStore.mm
This was introduced during porting in #2213.
This would manifest as a slight memory leak of documents removed from a view when running with persistence disabled.
> Fix removal of view references in FSTLocalStore

- Example/Database/Tests/Integration/FOrderByTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
- FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
- Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift
- README.md
Update the formatters now that we're checking with the Travis Xcode 10.3 image.
Make resulting source changes.
Update the instructions so this update process is easier the next time they change.
> Update formatters for the Xcode 10.3 Travis image

- .travis.yml
- FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
Even after #3681, flakes continued to persist in Remote Config travis runs. My best guess is that the Travis switch from Xcode 10.1 to Xcode 10.3 made the flakes occur more often.
I turned on logging by adding `--verbose` to the `pod_lib_lint` commands and discovered a bunch of extra activity during test runs before a time out flake.  See the commit details for more information about debugging.
When I was open sourcing and verifying the unit tests, I was overaggressive about fixing a crash from a main thread check.  Instead of disabling the main thread check, I disabled the whole clean-up function.   This PR adjusts that to only remove the assertion.
Even though the fix is a library change, it should be a no-op to clients, since the assert has been historically ifdef'd out in release mode …
> Fix Remote Config travis flakes

- Gemfile
- Gemfile.lock
Stop getting cocoapods-generate from a github tag now that 1.6.0 has released with the `--platforms` option.
> cocoapod-generate 1.6.0 released

- Firebase/Core/FIRComponentContainer.m
This is causing an issue in #3728. Hopefully this will fix it, but no
repro is available yet to test. There's still an underlying race
condition where a `creationBlock` could be called twice for a component
that is supposed to cache the instance returned, but that should be
addressed in a follow up PR.
> Gate access to cached instances.

- Firestore/core/src/firebase/firestore/core/event_manager.h
- Firestore/core/src/firebase/firestore/core/event_manager.mm
- Firestore/core/src/firebase/firestore/core/sync_engine_callback.h
- Firestore/core/src/firebase/firestore/remote/stream.mm
Here, the error actually has to be copied because it is passed to more than one listener. Currently, this doesn't make a difference because `util::Status` has no move constructor.
Also, make the relevant method take the status by const reference.
> Fix erroneous move

- Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h
Follow up to #3656 in a comment I missed.
> Fix comment for initializer for `FIRInAppMessagingAction` after deprecation

- Example/Core/Tests/FIRComponentContainerTest.m
- Example/Core/Tests/FIRTestComponents.h
- Example/Core/Tests/FIRTestComponents.m
This ensures that no deadlocking occurs when fetching from the
container, and when a delete occurs.
> Add ComponentContainer tests for dependencies.

- SymbolCollisionTest/Podfile
The cron tests failed last night. See https://travis-ci.org/firebase/firebase-ios-sdk/jobs/581517301
With the Firebase 6.8.0 release, GoogleMobileVision is now incorporated into FirebaseML and the old GMV pod is no longer compatible.
> Fix symbol collision failure introduced by 6.8.0 release

- Firebase/DynamicLinks/CHANGELOG.md
FDL changelog was modified in both release and master branches. The version from master was used to generate changelog for Firebase site:
- cherry pick #3781 
- cherry pick #3785
> Release 6.8.0 cherry pick: conflicting Dynamic Links changelog changes.

- Example/InstanceID/Tests/FIRInstanceIDCheckinServiceTest.m
- Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
- Example/InstanceID/Tests/FIRInstanceIDStoreTest.m
- Example/InstanceID/Tests/FIRInstanceIDTokenOperationsTest.m
- Firebase/InstanceID/CHANGELOG.md
- Firebase/InstanceID/FIRInstanceIDCheckinPreferences+Internal.h
- Firebase/InstanceID/FIRInstanceIDCheckinPreferences_Private.h
- Firebase/InstanceID/FIRInstanceIDCheckinService.h
- Firebase/InstanceID/Private/FIRInstanceID+Private.h
Fix #3796
- Fix imports in Private headers. 
- Stop referencing an internal typedef from a private header.
> Fix header issues exposed by :generate_multiple_pod_projects

- Firestore/core/src/firebase/firestore/model/field_path.cc
- Firestore/core/src/firebase/firestore/model/field_path.h
VS2015 apparently has trouble with a `constexpr`-qualified array. Changing this back to the largely equivalent `const char*` form works fine.
> Tweak code that breaks older versions of Visual Studio

- Firestore/core/src/firebase/firestore/remote/stream.mm
This is in response to #3817. This is also more consistent with other platforms (e.g., Android [does](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AbstractStream.java#L147) log the error).
The resulting log message look like this:
```
2019-09-11 14:44:03.939778-0400 Firestore_Example_iOS[30490:61949945] 6.8.1 - [Firebase/Firestore][I-FST000001] WriteStream (7f92506abd20) Stream error: 'Not found: No document to update: <document id here, omitted>'
2019-09-11 14:45:01.067452-0400 Firestore_Example_iOS[30490:61949544] 6.8.1 - [Firebase/Firestore][I-FST000001] WriteStream (7f9212de8040) Stream error: 'Permission denied: Missing or insufficient permissions.'
```
> Log stream errors

- Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
porting over from [Android](https://github.com/firebase/firebase-android-sdk/pull/779).
Yet another unknown culprit
> Port persistence spec test

- ZipBuilder/Sources/ZipBuilder/main.swift
This should help alleviate CI issues we're seeing.
> Allow Zip build to continue if Carthage fails.

- Example/Messaging/Tests/FIRMessagingContextManagerServiceTest.m
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingContextManagerService.m
- Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
> Mute FCM deprecated warnings with Xcode 11 and min iOS >= 10

- ZipBuilder/Sources/ZipBuilder/FileManager+Utils.swift
- ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
- ZipBuilder/Sources/ZipBuilder/main.swift
This will allow CI to give a directory on a volume that has more storage
space, allowing the build to succeed.
> Add argument for build root override.

- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
... Hopefully :)
The M56 release candidate unfortunately added a prefix to headers, likely due to the `standardizedFileURL` changing to a different path for the one set of URLs but we didn't use it previously.
When building on the same volume, this is a no-op, but hopefully this fixes the issue working on CI where the filesystem is on a different volume and aliased away.
> Fix file prefix on CI.

- ZipBuilder/Package.swift
It's named `ReleasePackager` instead of `ZipBuilder` since we should change the name now that it packages Zip and Carthage builds.
> Add a product to the SwiftPM manifest.

- FirebaseCoreDiagnostics.podspec
- GoogleDataTransportCCTSupport.podspec
This fixes #3911 by explicitly stating the dependency on `nanopb` along with the version.
> Fix nanopb dependencies for CoreDiagnostics.

- FirebaseABTesting.podspec
- FirebaseFirestore.podspec
- FirebaseMessaging.podspec
- FirebaseRemoteConfig.podspec
To ensure that we get the fix in Protobuf 3.9.2 for #3851
> Use at least Protobuf 3.9.2

- Firebase/InAppMessaging/Runtime/FIRIAMRuntimeManager.m
This fixes the same issue as setting the `messageDisplayComponent `where the value could have been set before the SDK was initialized. I encountered this when trying to set `messageDisplaySuppressed` on `FIRInAppMessaging` after `[FIRApp configureApp]` to be able to suppress message display during onboarding and UI tests.
> Set suppressMessageDisplay on displayExecutor

- .travis.yml
- Example/Core/App/iOS/FIRAppDelegate.m
- Example/Database/Tests/Unit/FLevelDBStorageEngineTests.m
- scripts/build.sh
- Update default travis builds to Xcode 11
- Update Core and Database unit tests for minor issues
- Disable FIAM(#3948) and GDT(#3947) in addition to Firestore(#3949) until their Xcode 11 issues get resolved
- Stop doing static library build via Xcode project. It's a source of flakes and static library builds are sufficiently tested by `pod lib lint`
> Travis to Xcode 11.0

- .travis.yml
- Example/Core/App/iOS/FIRAppDelegate.m
- scripts/build.sh
- scripts/if_changed.sh
- scripts/install_prereqs.sh
- Split FIAM from FIAM display to separate stages
- Split iOS and iPad to separate stages
- Stop running static library tests from xcodebuild. `pod lib lint` tests are sufficient for that
- Require FIAM tests to pass for overall run to pass
- Xcode 11 build issue remains. See #3948
There's now enough time in each stage for travis_retry to eliminate flakes.
> Make FIAM tests more robust in Travis

- .travis.yml
- Example/InstanceID/Tests/FIRInstanceIDKeyPairMigrationTest.m
- GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORClockTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCOREventTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORStorageTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORUploadPackageTest.m
- scripts/build.sh
Fix #3947 
TARGET_OS_MACCATALYST is always defined in Xcode 11. It's just 0 for iOS builds. This bug was causing GDT to build incorrectly on Xcode 11 for ios versions 10 and under.
> Fix Catalyst define checks

- Firestore/Swift/Source/Codable/CodableErrors.swift
- Firestore/Swift/Source/Codable/DocumentReference+Codable.swift
- Firestore/Swift/Source/Codable/FieldValue+Encodable.swift
- Firestore/Swift/Source/Codable/SelfDocumentId.swift
- Firestore/Swift/Tests/Codable/FirestoreEncoderTests.swift
- Firestore/third_party/FirestoreEncoder/FirestoreEncoder.swift
Also rewrite the FirestoreEncoderTests using a more concise set of
assertions.
> Provide better error messages when encoding is not available

- GoogleUtilities/CHANGELOG.md
- GoogleUtilities/Logger/GULLogger.m
For whatever reason, `GULLogBasic` crashes when running a test plan with Localization Screenshots enabled. I can't figure out exactly why this throws but even assigning `logMsg = message;` triggers the same crash, leading me to believe that `message` is invalid at that point (even though the debugger can print the value).
Fixes #3928.  Thanks again @abotkin-cpi for the sample project, made it easy to track down!
I avoided copying in the regular path since we don't copy to begin with and it's working as expected.
> Fix unit testing crash with localization on

- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
- cmake/external/boringssl.cmake
The as-of-yet-unreleased Clang 10 adds some new warnings which make the CMake build fail (due to `-Werror`):
* BoringSSL build now fails because some of its C code contains fallthroughs in switch statements that aren't properly annotated. This wasn't an issue before because previous versions of Clang ignored `-Wimplicit-fallthrough` in C mode;
* serializer test contains an expression that produces the following warning:
```
/src/firebase-ios-sdk/Firestore/core/test/firebase/firestore/remote/serializer_test.cc:446:29:
error: implicit conversion from 'std::__1::numeric_limits<long>::type' (aka 'long') to 'double'
changes value from 9223372036854775807 to 9223372036854775808 [-Werror,
-Wimplicit-int-float-conversion]
```
Fixes:
* upgrade the version of BoringSSL used to the latest master. …
> Fix CMake build with Clang 10

- Firestore/Source/Public/FIRDocumentChange.h
As of Swift 5, the Swift compiler now distinguishes between [frozen and non-frozen enums](https://github.com/apple/swift-evolution/blob/master/proposals/0192-non-exhaustive-enums.md), and issues warnings if you don't handle possible future cases for non-frozen enums.
Making `DocumentChangeType` a frozen enum allows developers to avoid adding `@unknown default` this to all usages like this:
```swift
switch change.type {
case .added:
print("New document: \(change.document.data())")
case .modified:
print("Modified document: \(change.document.data())")
case .removed:
print("Removed document: \(change.document.data())")
@unknown default:
fatalError()
}
```
We haven't seen this previously because the Swift 5 compiler running in Swift 4 mode does not emit the warning. I tried upgrading the …
> Make FIRDocumentChange a closed enum

- Firebase/InAppMessaging/Analytics/FIRIAMClearcutLogStorage.m
- Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m
- Firebase/InAppMessaging/Flows/FIRIAMActivityLogger.m
- Firebase/InAppMessaging/Flows/FIRIAMDisplayCheckOnAppForegroundFlow.m
- Firebase/InAppMessaging/Flows/FIRIAMFetchOnAppForegroundFlow.m
- Firebase/InAppMessagingDisplay/Banner/FIDBannerViewController.m
- Firebase/InAppMessagingDisplay/FIDBaseRenderingViewController.h
- Firebase/InAppMessagingDisplay/FIDBaseRenderingViewController.m
- Firebase/InAppMessagingDisplay/FIDRenderingWindowHelper.m
Two key fixes:
- Throw both `UIScene` and `UIApplication` lifecycle notifications
- Update `UIWindow` creation logic to initialize based on a foregrounded scene (if iOS 13 is available)
Fixes https://github.com/firebase/firebase-ios-sdk/issues/3524 with the exception around concerns with opening URL from a scene. From testing, though, current URL opening logic still works as intended.
> Update FIAM for iOS 13 Scene lifecycle paradigm

- .travis.yml
- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h
- GoogleDataTransport/GDTCORTests/Lifecycle/GDTCORLifecycleTest.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m
Checking `applicationState` while not on the  main thread results in a crash. Revert to using notifications and a flag to track this, but with a single source of truth.
Fixes #3973.
> Fix main thread crashing issue, reenable tests.

- GoogleDataTransportCCTSupport/CHANGELOG.md
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
Should address one possible issue with #3893 
Specifically [reports of a nil argument](https://github.com/firebase/firebase-ios-sdk/issues/3893#issuecomment-536433050)
> Address possibly nil country codes

- FirebaseInstallations/Source/Library/FIRInstallationsItem.m
- copy last 4 bits of UUID to the FID prefix (they were cut in the previous implementation).
> FirebaseInstallations FID generation: don't cut UUID

- Firebase/Database/CHANGELOG.md
- Firebase/Database/third_party/SocketRocket/FSRWebSocket.m
This PR modifies the log line that caused the crash in #3950.
There are probably better fixes, but this is safe and isolated. The upstream library seems to be unmaintained at this point. 
Fixes #3950
> Remove log argument that causes SocketRocket crash

- Firebase/Core/FIRComponentContainer.m
Reported in #3967. Users sometimes seeing a crash when multiple threads
concurrently try to create Firestore instances. By inspection I found
that there's a race here where two threads can check for presence in the
cache, see nothing, proceed to creation, both store a value in the cache,
and both return their copies. This would lead to two Firestores being
created for a single App.
This replaces `dispatch_sync` on a serial queue with good old
`@synchronized` blocks. `dispatch_sync` will self-deadlock if called
from a thread already on the queue while `@synchronized` allows
recursion.
No new tests are added because several tests like
`testDependencyDoesntBlock` already cover this case.
Fixes #3967. Could possibly address #3778, though the error doesn't seem like it should arise from this.
> Fix race condition in FIRComponentContainer instance creation

- Example/Core/Tests/FIRLoggerTest.m
- GoogleUtilities/Example/Tests/Logger/GULLoggerTest.m
These should be replaced when we fully migrate to os_log.
Close #128
> Delete unused commented asl tests

- .travis.yml
- Releases/update-versions.py
Now that Protobuf 3.10.0 has been published, Firebase shouldn't need to ignore any warnings, except for Firestore which will fail `pod lib lint` without `--allow-warnings` because it has `-Wno` options in its podspec.
Fixes #2665
> Remove --allow-warnings from tests

- Firestore/core/src/firebase/firestore/local/leveldb_key.cc
- Firestore/core/src/firebase/firestore/local/leveldb_key.h
- Firestore/core/test/firebase/firestore/local/leveldb_key_test.cc
This PR adds encode/decode functionality to store keys for the RemoteDocumentReadTime index in LevelDB.
The proposed format of the entries is:
Key: Collection Path, Read Time
Value: List of Document Ids
> Add RemoteDocumentReadTimeKey to LevelDb

- .travis.yml
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Podfile
- scripts/build.sh
- scripts/sync_project.rb
This adds logic to the Firestore `Podfile` that allows it to install only one platform at a time, making it possible to run builds from the command-line again with Xcode 10.2+.
This uses the `PLATFORM` environment variable we set in our Travis configuration to limit which targets are modified by `pod install`. This makes the selected platform work but leaves the other platforms in a broken state.
The default with `PLATFORM` unset is `all`, which makes development continue to work as usual for now.
Fixes #3949
> Build Firestore with Xcode 11

- .travis.yml
- Firebase.podspec
- Firebase/Firebase/.cocoapods.yml
- Firebase/Firebase/CHANGELOG.md
- Firebase/Firebase/NOTICES
- Firebase/Firebase/README.md
- Firebase/Firebase/Sources/Firebase.h
- Firebase/Firebase/Sources/module.modulemap
- Firebase/Firebase/Tests/FirebasePodTest/FirebasePodTest.xcodeproj/project.pbxproj
- Firebase/Firebase/Tests/FirebasePodTest/FirebasePodTest/AppDelegate.swift
- Firebase/Firebase/Tests/FirebasePodTest/FirebasePodTest/Assets.xcassets/AppIcon.appiconset/Contents.json
- Firebase/Firebase/Tests/FirebasePodTest/FirebasePodTest/Assets.xcassets/Contents.json
- Firebase/Firebase/Tests/FirebasePodTest/FirebasePodTest/Base.lproj/LaunchScreen.storyboard
- Firebase/Firebase/Tests/FirebasePodTest/FirebasePodTest/Base.lproj/Main.storyboard
- Firebase/Firebase/Tests/FirebasePodTest/FirebasePodTest/Info.plist
- Firebase/Firebase/Tests/FirebasePodTest/FirebasePodTest/SceneDelegate.swift
- Firebase/Firebase/Tests/FirebasePodTest/FirebasePodTest/ViewController.swift
- Firebase/Firebase/Tests/FirebasePodTest/Podfile
- scripts/build.sh
- scripts/check_whitespace.sh
- scripts/if_changed.sh
- scripts/install_prereqs.sh
- scripts/style.sh
Introduces Firebase pod support, Firebase.h and Firebase module support for tvOS and macOS.
Broken `pod try` functionality is removed.
Integration tests were added in #4020 and merged here.
> Add Firebase Pod to the repo

- Firestore/core/src/firebase/firestore/local/CMakeLists.txt
- Firestore/core/src/firebase/firestore/local/query_engine.h
- Firestore/core/src/firebase/firestore/local/simple_query_engine.cc
- Firestore/core/src/firebase/firestore/local/simple_query_engine.h
This PR just adds SimpleQueryEngine, but leaves it unused for now.
Port of https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/local/simple_query_engine.ts and https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/local/query_engine.ts
> Add SimpleQueryEngine

- Example/InstanceID/Tests/FIRInstanceIDTest.m
- Example/InstanceID/Tests/FIRInstanceIDTokenManagerTest.m
- Firebase/InstanceID/FIRInstanceID.m
- Firebase/InstanceID/FIRInstanceIDTokenManager.h
- Firebase/InstanceID/FIRInstanceIDTokenManager.m
If they don't have the same prefix, refresh the token from backend with the current IID.  This helps with backward compatibility when we adopt FIS
> Always check if IID and token are consistent

- Example/InstanceID/Tests/FIRInstanceIDBackupExcludedPlistTest.m
- Example/Messaging/Tests/FIRMessagingDataMessageManagerTest.m
- Example/Messaging/Tests/FIRMessagingRmqManagerTest.m
- Example/Messaging/Tests/FIRMessagingSyncMessageManagerTest.m
- Firebase/InstanceID/FIRIMessageCode.h
- Firebase/InstanceID/FIRInstanceIDBackupExcludedPlist.m
- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessagingRmq2PersistentStore.h
- Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
- Firebase/Messaging/FIRMessagingRmqManager.h
- Firebase/Messaging/FIRMessagingRmqManager.m
We used to store files in document folder (more than 2 years ago) and had migration logic that if document folder exist, move the content to application folder. 
Remove the migration logic since the majority of the users already store data in the application folder. The data we wrote in the disks are plist file and cached non-ack mcs channel message IDs, which are not critical information even if a very old user still kept the document folder (who hasn't opened his app for more than 2 years).
Also remove production code that is only used for testing, should expose the method through category instead.
> Remove migration logic from document folder to application folder

- FirebaseInstallations/Source/Library/FIRInstallationsItem.h
- FirebaseInstallations/Source/Library/FIRInstallationsItem.m
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredRegistrationError.h
- FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredRegistrationError.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsStoredItemTests.m
- FirebaseInstallations/Source/Tests/Utils/XCTestCase+DateAsserts.h
- FirebaseInstallations/Source/Tests/Utils/XCTestCase+DateAsserts.m
- the stored FIS registration error expiring in 24h (see go/fis-ios-error-handling for details)
This is a follow up on #4024.
> FIS: stored registration error timeout

- GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
- GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTFLLUploader.m
Fixes #4039
Fixes #4027
Also fixes an issue with an implicit `self` retain by making it explicit.
> Fix sanitizer issues

- FirebaseInstallations/Source/Library/Errors/FIRInstallationsHTTPError.h
- FirebaseInstallations/Source/Library/Errors/FIRInstallationsHTTPError.m
- FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
- logic to retry API request on response HTTP 500 was moved to the API service and applied to all requests.
> FIRInstallationsAPIService: Retry API request on HTTP 500.

- Example/Core/Tests/FIRComponentContainerTest.m
- Example/Messaging/Tests/FIRInstanceIDWithFCMTest.m
- Example/Messaging/Tests/FIRMessagingTest.m
- Firebase/Core/FIRApp.m
- Firebase/Core/FIRComponentContainer.m
- Firebase/Core/Private/FIRComponentContainerInternal.h
- Firebase/InstanceID/FIRInstanceID.m
- Firebase/Messaging/FIRMessaging.m
The container instantiation could happen at the wrong time, before all
components have been added to the container. This fixes it, and also
moves IID to use the proper instantiation timing instead of relying on
the `configureWithApp:` call. This is part continuation of #3147, where
I'll be fixing the rest of the SDKs in follow up PRs.
Edit: Further work...
This moves the instantiation of components to after the FirebaseApp is
completely configured and assigned, as it should be. This also exposed
a recursive issue with IID calling the Messaging singleton, which in
turn called IID and instantiated multiple instances.
A change was made to break the cycle: the Messaging `isAutoInitEnabled`
call was changed to a static method vs an instance method, allowing IID
to call it during initialization …
> Fix container instantiation timing, IID startup.

- FirebaseFirestore.podspec
- Firestore/Swift/Tests/API/BasicCompileTests.swift
See #4035: a certain combination of pods can lead to a broken build. The underlying issue is that CocoaPods generate a header map that includes headers from _all_ the pods in a project. A header map maps short file names to full paths and is unable to handle collisions; thus, in a CocoaPods-based build, if one pod contains a header with a common name, and the other pod tries to import a header with the same short name by relying on header maps (without specifying a longer path), the header from one pod may end up getting erroneously picked up by the other pod.
In that particular case, `SVGKit` is relying on header maps and trying to import `Document.h`, which, for reasons described above, happens to pick up `document.h` from Firestore. However, since header maps cannot handle collisions, …
> Firestore podspec: avoid adding Firestore headers to sources

- Firebase/Auth/Source/Utilities/FIRAuthDefaultUIDelegate.m
Solve item #3 for https://github.com/firebase/firebase-ios-sdk/issues/3521
> Use UIApplication.connectedScenes on iOS 13

- FirebaseInstallations/Source/Library/Errors/FIRInstallationsHTTPError.h
- FirebaseInstallations/Source/Library/Errors/FIRInstallationsHTTPError.m
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
- If HTTP 401 or 404 is received on token refresh API request then the installation is deleted and a new one is created and registered (see go/fis-ios-sdk-design#heading=h.4ylovir3dwsk for more details)
cc @ankitaj224
> FirebaseInstallations: re-generate Installation on HTTP 401 and 404 

- .travis.yml
We've had at least three regressions of Xcode 11 code not building successfully in Xcode 10. This PR makes sure builds still succeed on the current minimum supported Xcode version.
> Add Xcode 10 testing back

- Firestore/CHANGELOG.md
- Firestore/core/src/firebase/firestore/core/firestore_client.h
- Firestore/core/src/firebase/firestore/core/firestore_client.mm
Ports the fix from https://github.com/firebase/firebase-android-sdk/commit/0213e1e81bf9bc61806496cb07ba1797c2628acf, but using the logic of the Web client (https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/core/firestore_client.ts#L184)
> Fix potential race during client initialization

- Example/InstanceID/Tests/FIRInstanceIDTest.m
- Example/InstanceID/Tests/FIRInstanceIDTokenInfoTest.m
- Firebase/InstanceID/CHANGELOG.md
- Firebase/InstanceID/FIRInstanceID.m
- Firebase/InstanceID/FIRInstanceIDTokenInfo.h
- Firebase/InstanceID/FIRInstanceIDTokenInfo.m
- Firebase/InstanceID/FIRInstanceIDTokenManager.m
This API is used to fetch token directly from server. Right now if APNS info is not changed, the client will simply use cached token.
We should also check token freshness, which checks if IID and token is consistent or if app version has changed, etc. This helps us migrate to FIS. (b/140506963)
> tokenWithAuthorizedEntity: method should also check if token is fresh

- Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/core/test/firebase/firestore/testutil/app_testing.h
- Firestore/core/test/firebase/firestore/testutil/app_testing.mm
Also avoid priming the backend when running tests against the emulator.
#no-changelog
> Ensure that projectIDs are validated

- Firestore/core/src/firebase/firestore/local/memory_persistence.cc
- Firestore/core/src/firebase/firestore/local/memory_persistence.h
This removes the requirement to include reference_delegate.h in consuming tests.
#no-changelog FTW
> Move all ReferenceDelegate handling to .cc file

- Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
- Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
- Firestore/Example/Tests/Local/FSTRemoteDocumentCacheTests.mm
- Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.h
- Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.mm
- Firestore/core/src/firebase/firestore/local/local_store.mm
- Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.h
- Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.mm
- Firestore/core/src/firebase/firestore/local/remote_document_cache.h
This adds the readTime argument to RemoteDocumentCache.Add() and persists in MemoryRemotedocumentCached and its LevelDB counterpart.
References:
- https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java#L43
- https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java#L38
Note that I did not implement the DocumentIterable that Android uses to hide the `std::pair` in the memory-backed implementation since it seemed overly complex in C++.
> Persist ReadTime in RemoteDocumentCache

- scripts/sync_project.rb
Use base_configuration_reference.real_path rather than path
real_path has the correct value after a pod deintegrate/pod install
cycle, while path has some nearly correct value. No idea why these are
different.
#no-changelog
> Make sync_project work after pod deintegrate

- Firestore/core/src/firebase/firestore/model/base_path.h
- Firestore/core/src/firebase/firestore/model/document_key.cc
- Firestore/core/src/firebase/firestore/model/document_key.h
- Firestore/core/src/firebase/firestore/model/resource_path.h
- Firestore/core/src/firebase/firestore/util/comparison.h
This came up while I was investigating the effect of new C++ serializers on performance. When writing large batches, one of the hottest functions turned out to be `firebase::firestore::util::operator==(const DocumentKey& lhs, const DocumentKey& rhs)`, accounting for 15-20% of total CPU time. There are two reasons why comparing keys is currently not very efficient:
* `BasePath::CompareTo`, to which this comparison eventually resolves, mistakenly uses the general-purpose `util::Compare` function rather than the more efficient `util::CompareContainer`;
* the default implementation of `Comparable::operator==` results in two comparisons per element ("less-than" followed by "greater-than"), even though one would be sufficient.
Fixing these issues results in 8-10% CPU time improvement when …
> Optimize `DocumentKey` comparisons

- FirebaseCoreDiagnosticsInterop.podspec
- Interop/CoreDiagnostics/Public/FIRCoreDiagnosticsData.h
- scripts/if_changed.sh
So they're not added to the size of every implementation file that includes them.
Update if_changed.sh to be more accurate for CoreDiagnostics changes and to make changes to itself testable.
> Stop using statics in header

- FirebaseInstallations/Source/Library/SecureStorage/FIRInstallationsKeychainUtils.m
- use `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly` instead.
> FIS Keychain: Replace deprecated `kSecAttrAccessibleAlwaysThisDeviceOnly`

- Example/InstanceID/Tests/FIRInstanceIDAuthKeyChainTest.m
- Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
- Example/InstanceID/Tests/FIRInstanceIDFakeKeychain.m
- Firebase/InstanceID/FIRInstanceIDAuthKeyChain.h
- Firebase/InstanceID/FIRInstanceIDAuthKeyChain.m
- Firebase/InstanceID/FIRInstanceIDCheckinStore.m
- Firebase/InstanceID/FIRInstanceIDKeyPairStore.m
- Firebase/InstanceID/FIRInstanceIDKeychain.m
- Firebase/InstanceID/FIRInstanceIDTokenStore.m
#4167 user reports getting IID becomes nil when a token exists. We suspect this is due to a security issue while keychain access level is set to kSecAttrAccessibleAlwaysThisDeviceOnly that is deprecated in iOS 13. Neitherless we should update it to kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly since app only works in foreground so this is the proper access.
Also remove a parameter to set a optional access level for keychain cuz this parameter was never used.
> update keychain access level

- Example/Messaging/Tests/FIRMessagingDataMessageManagerTest.m
- Example/Messaging/Tests/FIRMessagingRmqManagerTest.m
- Example/Messaging/Tests/FIRMessagingSyncMessageManagerTest.m
- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingClient.m
- Firebase/Messaging/FIRMessagingConnection.h
- Firebase/Messaging/FIRMessagingConnection.m
- Firebase/Messaging/FIRMessagingDataMessageManager.m
- Firebase/Messaging/FIRMessagingDelayedMessageQueue.m
- Firebase/Messaging/FIRMessagingRmqManager.h
- Firebase/Messaging/FIRMessagingRmqManager.m
- Firebase/Messaging/FIRMessagingSyncMessageManager.m
b/142357385 People find the app stuck on RMQ database write operation as they are on main thread.
Moving all the write operations off main thread.
Some of the sync methods used to return a value, it is used to tell the operation succeed and print error if not. We will remove those return value and print error inside the method.
There are other return values are not used at all by the parent class. Remove those and make them async method.
Also refactor the method scanWithRmqMessageHandler: which is very interesting. It has two callbacks as parameters, each is used on different occasions. This function reads data from database, instead of return the results at once, it triggers callback per row of database read. This used to work because database operation is blocking, so client just …
> move database operation off main thread

- Functions/CHANGELOG.md
- Functions/FirebaseFunctions/FUNSerializer.m
This fixes #4164.
```
pod lib lint --sources=https://cdn.cocoapods.org/ --analyze FirebaseFunctions.podspec
-> FirebaseFunctions (2.5.1)
- NOTE  | xcodebuild:  note: Using new build system
- NOTE  | xcodebuild:  note: Planning build
- NOTE  | xcodebuild:  note: Constructing build description
- NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
FirebaseFunctions passed validation.
```
> Only assign errors if parameter is non-NULL.

- scripts/check_whitespace.sh
It is needed to be able to commit notices files without modifications.
#no-changelog
> check_whitespaces.sh: ignore notice files

- Firestore/core/test/firebase/firestore/remote/datastore_test.cc
Previously it was possible for tasks on the async queue to outlive the 
instance of the DatastoreTest which could crash or cause TSAN violations.
This fixes a flake that appeared in the AuthOutlivesDatastore test case.
Also improve readability of the error classification tests
> Prevent race conditions in DatastoreTest

- Firestore/core/src/firebase/firestore/util/executor_libdispatch.h
- Firestore/core/src/firebase/firestore/util/executor_libdispatch.mm
After a `TimeSlot` executes, it deletes itself and removes itself from `ExecutorLibdispatch`'s `schedule_`. The `DelayedOperation` still referred to this now freed address. If another `TimeSlot` is scheduled, operator `new` happens to allocate a `TimeSlot` that reuses the address, and the
`DelayedOperation` is subsequently canceled, this will cancel the new task before it has run.
This change fixes this by using a dedicated counter for `TimeSlot`s that effectively isn't reused. Note that while it is possible for the counter to wrap around, this would take tens of years of continuous execution to happen and require cancelation of a `TimeSlot` created tens of years ago to create the possibility of collision which is a sufficiently impractical problem as to be ignorable.
This fixes a flake …
> Don't use the address of a TimeSlot as a key for removal

- .travis.yml
#4053 introduced a travis failure for Messaging.  The issue is suspected to be test only.
This PR allows the failure to continue while being investigated (#4236) while allowing the overall build to go green.
> Allow failures in FirebaseMessaging

- .travis.yml
- scripts/pod_lib_lint.rb
Fix #1744
Now that we're using CocoaPods 1.8.x, we can take advantage of the new `--analyze` option to run the Xcode analyzer on presubmits.
This PR adds it, along with disabling for FIAM(#4163), Functions(#4164) and Firestore(#4165).
#no-changelog
> Add --analyze to pod lib lint tests

- .travis.yml
All of the travis Xcode 10.2 builds started failing today without a change from our end.  Update to the travis 10.3 config for Xcode 10 testing.
#no-changelog
> Test with Xcode 10.3 instead of 10.2

- CMakeLists.txt
- Firestore/Example/GoogleBenchmark.podspec
- Firestore/core/src/firebase/firestore/remote/CMakeLists.txt
- cmake/external/benchmark.cmake
CMake 3.5.1 is the version required by the latest versions of gRPC and Google Benchmark. See discussion google/benchmark#613.
Remove version check around find_package(XCTest).
Also, add a dependency on objc protos that was missing but somehow implicitly being added before.
#no-changelog
> Require CMake 3.5.1; upgrade Google Benchmark to 1.5.0

- CMakeLists.txt
- cmake/archive_options.cmake
Silence warnings in Abseil that we're never going to care about (since upstream doesn't).
Also silence useless ranlib warnings like this:
```
/Applications/Xcode-11.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: external/src/grpc-build/libgrpc.a(iomgr_uv.cc.o) has no symbols
```
#no-changelog
> Make the CMake build warning free

- FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
- FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
- FirebaseRemoteConfig/Sources/RCNConfigSettings.m
- FirebaseRemoteConfig/Sources/RCNFetch.m
- FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.h
- FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNUserDefaultsManagerTests.m
Fixes internal bug: 143622863. We activate only if fetched data has not resulted in a data change. We track this using the last time the ETag was changed (corresponds to a real change to the RC template). 
This change also mirrors current android behavior.
> Do not activate if fetch returns NO_CHANGE

- Firestore/core/src/firebase/firestore/local/CMakeLists.txt
- Firestore/core/src/firebase/firestore/model/CMakeLists.txt
- Firestore/core/src/firebase/firestore/nanopb/CMakeLists.txt
- Firestore/core/src/firebase/firestore/remote/CMakeLists.txt
- Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
Now that we depend upon gRPC 1.24+ (and it no longer includes nanopb) we
no longer need any build order workarounds.
Fixes b/111328563. #no-changelog
> Remove workarounds for nanopb ODR violations

- Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.cc
- Firestore/core/test/firebase/firestore/nanopb/pretty_printing_test.cc
`{` and `}` are metacharacters and need to be escaped to be used as literals.
Without this, the tests log warnings like this:
```
Regular expression "<Write 0x[0-9A-Fa-f]+>: {
update_mask {
}
}" is not a valid POSIX Extended regular expression.
```
and all the matches fail.
> Get tests passing on Linux

- Firestore/Example/App/CMakeLists.txt
- Firestore/Example/Tests/Integration/CMakeLists.txt
- Firestore/Example/Tests/Util/CMakeLists.txt
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Example/Tests/Util/XCTestCase+Await.h
- Firestore/Example/Tests/Util/XCTestCase+Await.mm
- Firestore/Protos/CMakeLists.txt
- Firestore/Source/CMakeLists.txt
- Firestore/core/src/firebase/firestore/core/CMakeLists.txt
- Firestore/core/src/firebase/firestore/local/CMakeLists.txt
- Firestore/core/src/firebase/firestore/nanopb/CMakeLists.txt
- Firestore/core/src/firebase/firestore/remote/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
- cmake/cc_rules.cmake
This implements a bunch of the feedback I called for in #4276, plus
* Fixed `objc_framework`'s header copying
* Added an `objc_test` rule to reduce verbosity
* Added `GoogleService-Info.plist` as a resource to the example get tests that needed it working
* Worked around categories not loading in `XCTest+Await`
* Added Objective-C unit tests for `API` as well
Note that this is based on and intends to merge into #4276. We'll deal with other merges after.
> Get integration tests fully working under CMake

- Firebase/Storage/FIRStorage.m
- fixes from cl/278915086 applied
> FIRStorage.callbackQueue fixes

- CoreOnly/Tests/FirebasePodTest/Podfile
dependent pods need to come from the repo also, so that version updates stay in sync across pods.
> Fix FirebasePod test

- CoreOnly/Tests/FirebasePodTest/Podfile
- FirebaseInstanceID.podspec
Fix a bug in the Firebase Pod tests
Exposed in the post-submit tests after #4323 
Also make a note that the FirebaseCore dependency version needs to be updated in the next release.
> Fix test bug

- Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m
- https://github.com/firebase/firebase-ios-sdk/issues/4308
Sending the proposed patch by admins. Wondering still if it's a good idea though.
> Keeps a strong reference for handling dynamic deeplinks

- Firebase/Core/CHANGELOG.md
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
In conjunction with cl/279764850 and the next Analytics release, this addresses #4110
> Add arm64e to the zip build

- Example/Podfile
- FirebaseCore.podspec
- FirebaseInstallations.podspec
- FirebaseInstanceID.podspec
- FirebaseMessaging.podspec
- FirebaseRemoteConfig.podspec
- GoogleUtilitiesComponents.podspec
- InAppMessaging/Example/Podfile
OCMock caused unit tests to fail in seven libraries.
This PR locks the dependency to 3.4.0 while we investigate.
#no-changelog
> Lock OCMock to 3.4 while investigating test failures with 3.5.0

- Example/InstanceID/Tests/FIRInstanceIDStoreTest.m
- Example/InstanceID/Tests/FIRInstanceIDTest.m
- Example/Messaging/Tests/FIRMessagingConnectionTest.m
- FirebaseInstanceID.podspec
- FirebaseMessaging.podspec
> Fix a few misuse of OCMock in Messaging and InstanceID

- .travis.yml
Fix the `/Users/travis/.travis/functions: line 109: pip: command not found` that broke all travis builds starting yesterday.
> Xcode 11.1 instead of 11.2

- Example/Database/Tests/Integration/FData.m
- Firebase/Database/Api/FIRServerValue.m
- Firebase/Database/Api/FIRServerValue_unreleased.h
- Firebase/Database/Core/FRepo.m
- Firebase/Database/Core/FServerValues.h
- Firebase/Database/Core/FServerValues.m
- Firebase/Database/Core/FSyncTree.m
* Definition is currently in an "unreleased" extension to FIRServerValues
* Functions that resolve server values now need access to any existing snapshot; please help ensure that this is not done wastefully.
* Tests are added to FData.m (integration tests); please let me know if a more appropriate place exists.
* Some tests are renamed to make it clear that ServerValues != timestamps
> Add +[FIRServerValues increment:]

- scripts/binary_to_array.py
Visual Studio 2017 runs creates its CMake output directory in a location
outside the git checkout, which causes the check for a current git
repository to fail.
> Fix completely out-of-source CMake builds

- Firestore/core/src/firebase/firestore/remote/CMakeLists.txt
- Firestore/core/test/firebase/firestore/local/lru_garbage_collector_test.cc
Reshuffling our dependencies in #4279 broke the build; apparently the
Linux linker is less forgiving than the one on macOS.
> Fix the Linux build

- Firestore/core/src/firebase/firestore/remote/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/executor_std.cc
- Firestore/core/test/firebase/firestore/local/lru_garbage_collector_test.cc
There's an unused variable that makes fuzz build fail due to `-WError`.
> Fix fuzz build

- ZipBuilder/Sources/ZipBuilder/FileManager+Utils.swift
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
- ZipBuilder/Sources/ZipBuilder/URL+Utils.swift
This separates the frameworks built for Carthage from the frameworks
built for the zip file.
> Fix Carthage CD overriding the Zip build.

- Firestore/core/src/firebase/firestore/core/sync_engine_callback.h
- Firestore/core/src/firebase/firestore/core/user_data.cc
- Firestore/core/src/firebase/firestore/immutable/llrb_node.h
- Firestore/core/src/firebase/firestore/immutable/llrb_node_iterator.h
- Firestore/core/src/firebase/firestore/local/leveldb_lru_reference_delegate.cc
- Firestore/core/src/firebase/firestore/local/memory_lru_reference_delegate.cc
- Firestore/core/src/firebase/firestore/remote/grpc_streaming_reader.cc
- Firestore/core/src/firebase/firestore/remote/remote_store.h
- Firestore/core/src/firebase/firestore/remote/watch_stream.h
- Firestore/core/src/firebase/firestore/remote/write_stream.h
- Firestore/core/src/firebase/firestore/util/executor_std.cc
- Firestore/core/src/firebase/firestore/util/log_stdio.cc
These fixes allow Firestore to build on Linux with IWYU checks:
* include some headers that are used, mostly `absl/memory/memory.h`;
* add some virtual destructors;
* fix one cyclic dependency;
* fix one potential case of ODR violation.
> Fix several small linter issues

- Firestore/core/src/firebase/firestore/util/comparison.h
Looks like there's a compiler bug preventing the correct generation of an implicit copy constructor in certain circumstances.
> Fix Linux build with GCC 4.8.5

- Firestore/core/src/firebase/firestore/api/settings.cc
- Firestore/core/src/firebase/firestore/api/settings.h
Looks like Visual Studio 2015 has trouble with `constexpr` arrays:
```cpp
constexpr char Foo[] = "abc";
```
but not with `constexpr` pointers to `char`:
```cpp
constexpr const char* Foo = "abc";
```
> Fix compilation with older versions of Visual Studio

- ZipBuilder/ZipBuilderV2Plan.md
Can potentially address #4284.
Implementation occurring in https://github.com/firebase/firebase-ios-sdk/tree/pb-any-zip
#no-changelog
> Zip Builder V2 Plan

- ZipBuilder/Sources/ZipBuilder/FileManager+Utils.swift
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
- ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
- ZipBuilder/Sources/ZipBuilder/main.swift
Use a unique temp folder per run so that multiple Zip Builder's can coexist on the same build/dev machine.
Add -keepBuildArtifacts option to keep the temp folder around. By default it will be deleted after a successful run.
Also integrate the cache into the temp folder since it is rebuilt every run anyway.
#no-changelog
> Support concurrent Zip Builder runs

- GoogleUtilitiesComponents.podspec
This issue was fixed previously and there's no need to lock versions now.
#no-changelog Updating pod's test dependency.
> Update GUComponents OCMock dependency.

- Firebase/Core/CHANGELOG.md
- ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift
- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/FirebasePods.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
- ZipBuilder/Template/README.md
Get rid of the name adjustments for the Firebase pods and always calling them by the full name - eg "FirebaseAnalytics" instead of "Analytics". T he rename only increased complexity in both implementation and usage.
#no-changelog
> Simplify Firebase pod naming

- CMAKE.md
- CMakeLists.txt
This cuts the full rebuild-and-test time from 2m7s to 38s on Linux.
Also, boringssl now uses nasm on Windows rather than yasm so update instructions.
> Add ccache support to our CMakeLists.txt.

- .travis.yml
- Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.m
- Update card message creation method to require portrait image to be non-null
- In calling method, return `nil` if imageData isn't present
- Always instantiate an action button for a card message
#fixes #4163
> Fix FIAM --analyze nullability issues

- Example/Core/Tests/FIRAppTest.m
- Firebase/Core/FIRApp.m
- Firebase/Core/FIROptions.m
Some extensions have an entry point that gets called multiple times.
Instead of having to check if a default app has already been configured,
allow multiple `configure` calls if and only if it's in an extension and
the FIROptions contents are identical.
> Allow multiple `configure` calls in an extension.

- Firebase/Auth/Source/Auth/FIRAuth.m
- GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
- GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h
- GoogleUtilities/Common/GULLoggerCodes.h
- GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
Seems there is issue with the building system for https://github.com/firebase/firebase-ios-sdk/pull/3925
Started a new PR.
> Handle UISceneDelegate changes in Auth

- Example/Core/Tests/FIRAppTest.m
- Example/Core/Tests/Swift/FIRAppTests.swift
- Example/Core/Tests/Swift/FirebaseCore-iOS-Unit-swift-unit-Bridging-Header.h
- Firebase/Core/FIRApp.m
- FirebaseCore.podspec
- add "swift" flag to `firebaseUserAgent` when Swift runtime detected
- tests
> Add "swift" flag to `firebaseUserAgent`

- ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Doing the full `pod install` can take a long time especially with a slow network.
This speeds up a Firebase build by three minutes on a fast connection and much more on a slow one.
#no-changelog
> Speed up zip builder development iteration

- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
For libraries with Resources, the blank line was missing in the text version (ok in markdown):
```
- AppAuth.framework
- GTMAppAuth.framework
- GTMSessionFetcher.framework
- GoogleSignIn.framework
You'll also need to add the resources in the Resources
directory into your target's main bundle.
- FirebaseInAppMessaging.framework
```
to 
```
- AppAuth.framework
- GTMAppAuth.framework
- GTMSessionFetcher.framework
- GoogleSignIn.framework
You'll also need to add the resources in the Resources
directory into your target's main bundle.
- FirebaseInAppMessaging.framework
```
#no-changelog
> Fix Zip README blank line separator

- .travis.yml
Disable pod lib lint testing with `--use-libraries` now that Core has Swift tests - introduced in #4448.  The cron tests [started failing](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/621899598). 
Filed a CocoaPods feature request(https://github.com/CocoaPods/CocoaPods/issues/9392) to add support for selective test spec testing. 
#no-changelog
> Disable use-libraries pod-lib-lint tests for Core

- Firebase/Database/CHANGELOG.md
The only change (https://github.com/firebase/firebase-ios-sdk/pull/4328) is not yet exposed in the Public API and blocked on the backend rollout.
> Updating Database Changelog

- Firestore/Protos/cpp/firestore/local/target.pb.cc
- Firestore/Protos/cpp/firestore/local/target.pb.h
- Firestore/Protos/nanopb/firestore/local/target.nanopb.cc
- Firestore/Protos/nanopb/firestore/local/target.nanopb.h
- Firestore/Protos/protos/firestore/local/target.proto
See https://github.com/firebase/firebase-android-sdk/blob/47def6d06943fb41ec21b0cf936421195b590ec4/firebase-firestore/src/proto/google/firebase/firestore/proto/target.proto#L84
> [Index-Free] Add Last Limbo Free Snapshot Version to Target Proto

- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/ModuleMapBuilder.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
- ZipBuilder/Sources/ZipBuilder/main.swift
This is a speedup and prerequisite for supporting local podspec's.
See embedded comments below for more detail on the implementation.
#no-changelog
> ZipBuilder: Get dependencies from the Podfile.lock

- Firestore/CHANGELOG.md
The only potentially changelog-worthy change in this list is #4418, but I don't think it has any practical effect that users can see or act on so it's probably not worth noting yet.
> Update CHANGELOG for Firestore v1.8.2

- Example/InstanceID/Tests/FIRInstanceIDTest.m
- Firebase/InstanceID/FIRInstanceID+Private.m
- Firebase/InstanceID/FIRInstanceID.m
- Firebase/InstanceID/Private/FIRInstanceID_Private.h
- use cached value of FID to be returned by `-[FIRInstanceID appInstanceID:]` instead of blocking thread waiting for `FirebaseInstallations` response.
b/145993195
> Make -[FIRInstanceID appInstanceID:] safe to be called from any thread

- ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift
Make sure json files keep same names despite new Zip directory structure names.
> Update Carthage for new Zip layout

- GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
- GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
- check on `UIScene.delegate` before swizzling
b/146216242
> Fix crash in Scene delegate swizzling when delegate is nil

- FirebaseInstallations/Source/Library/FIRInstallations.m
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.h
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStore.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsStoreTests.m
- use `FIROptions.appGroupID` as a user defaults suite name to keep secure storage in sync between the host app and extensions
> FirebaseInstallations - extensions support

- FirebaseInstallations.podspec
- FIS uses heartbeat code from Firebase Core, so it should require proper version of it.
#no-changelog
> FirebaseInstallations: require Core version with heartbeat

- Firestore/core/src/firebase/firestore/core/sync_engine.cc
- Firestore/core/src/firebase/firestore/remote/remote_event.h
GCC shows a "chosen constructor is explicit in copy-initialization" that
shouldn't occur. Also, since we're now explicitly instantiating these
values, add type aliases in RemoteEvent.
This effectively a port of cl/286120322 with cleanup.
> Work around spurious errors in GCC 4.8

- README.md
Summarize the state of #3144
#no-changelog
> Update README for Catalyst

- .travis.yml
This can be reverted when #4565 is fixed.
#no-changelog
> Disable broken Auth Api Tests

- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
I haven't come up with a way to fix the warnings about include order of
pb_encode.h here.
> Fix lint warnings spotted by google3's linter

- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
If the method `-[FIRInstallationsIDController getInstallationItem]` is called multiple times while SDK is waiting for response for Create FID API request then other Create FID API requests with the same FID may be sent which. If such requests are sent then FIS server will treat the duplicated requests as FID conflict and reply with a new FID which will replace initial one.
> FitebaseInstallations: fix create FID race condition

- ZipBuilder/Package.swift
This also fixes the ZipBuilder build warnings.
Verified that a release build matches M61 as expected.
#no-changelog
> Update swift-protobuf dependency

- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
Reverts firebase/firebase-ios-sdk#4576
The PR is to be reverted because:
- the test introduced in #4576 was incorrect and didn't reflect a real world scenario. With actual usage this type of race condition does not occur. 
- the fix introduces another issue(b/147230513) .
> Revert "FitebaseInstallations: fix create FID race condition"

- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Source/API/FIRDocumentSnapshot.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/API/FSTUserDataConverter.mm
- Firestore/Swift/Tests/Codable/FirestoreEncoderTests.swift
- Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.cc
- Firestore/core/src/firebase/firestore/nanopb/byte_string.cc
- Firestore/core/src/firebase/firestore/nanopb/byte_string.h
- Firestore/core/src/firebase/firestore/remote/grpc_completion.cc
- Firestore/core/src/firebase/firestore/remote/grpc_completion.h
- Firestore/core/src/firebase/firestore/remote/grpc_stream.cc
- Firestore/core/src/firebase/firestore/remote/grpc_stream.h
- Firestore/core/src/firebase/firestore/remote/grpc_unary_call.cc
- Firestore/core/src/firebase/firestore/remote/grpc_unary_call.h
- Firestore/core/src/firebase/firestore/util/async_queue.cc
- Firestore/core/test/firebase/firestore/local/lru_garbage_collector_test.cc
- Firestore/core/test/firebase/firestore/local/persistence_testing.cc
- Firestore/core/test/firebase/firestore/nanopb/byte_string_test.cc
- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
See individual commits for descriptions.
The only ~serious issues are:
* ba75105 Fixes a leaking stream token on every mutation acknowledgement
* 6a34b23 Fixes leaking ByteStrings; clang wasn't using the by-value assignment operator correctly
* f5f7980 Fixes leaking GrpcCompletions during shutdown.
With these changes in place, it's possible to get a relatively clean run of Instruments > Leaks during the integration tests, though occasionally the spec tests kick up a bunch of spurious leaks. Given that we're rewriting these in C++ I'm not inclined toward actually addressing this now.
> Miscellaneous fixes

- Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c
- Crashlytics/Crashlytics/Handlers/FIRCLSSignal.h
- Crashlytics/Crashlytics/Unwind/Dwarf/FIRCLSDwarfExpressionMachine.c
- Crashlytics/Crashlytics/Unwind/Dwarf/FIRCLSDwarfExpressionMachine.h
- Crashlytics/Crashlytics/Unwind/Dwarf/FIRCLSDwarfUnwind.h
- Crashlytics/Crashlytics/Unwind/Dwarf/FIRCLSDwarfUnwindRegisters.h
Running `clang-format` exposed some places where headers needed to be imported.
> Fix Crashlytics C imports

- Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m
- Crashlytics/Crashlytics/FIRCLSURLSession/Tasks/FIRCLSURLSessionDataTask.m
There are two deprecation warnings, one on macOS and one Catalyst. We are tracking these here:
b/147357475
b/133755970
> Crashlytics ignore deprecation warnings on macOS and Catalyst

- Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m
- Crashlytics/Crashlytics/DataCollection/FIRCLSDataCollectionArbiter.m
- Crashlytics/Crashlytics/FIRCrashlytics.m
- Crashlytics/Crashlytics/Models/FIRCLSSettings.h
- Crashlytics/Crashlytics/Models/FIRCLSSettings.m
- Crashlytics/Crashlytics/Settings/FIRCLSSettingsOnboardingManager.h
- Crashlytics/UnitTests/FIRCLSDataCollectionArbiterTest.m
- Crashlytics/UnitTests/FIRCLSReportManagerTests.m
- Crashlytics/UnitTests/FIRCLSSettingsTests.m
In response to a tip from @maksymmalyhin https://github.com/firebase/firebase-ios-sdk/pull/4610#issuecomment-572124334, allow for both types of imports depending on what cocoapods configuration is being used.
> Crashlytics allow for both types of Promise imports

- scripts/check.sh
In implementing the fallback for old PRs in #4614 I changed the default
for interactive use of check.sh. This fixes it so that if you just run
check.sh with no arguments it evaluates only the diff against master.
#no-changelog
> Flip the default to diffing against master

- CoreOnly/Sources/Firebase.h
- CoreOnly/Tests/FirebasePodTest/Podfile
- Firebase.podspec
This will allow developers to include `pod 'Firebase/Crashlytics'` and import it with `@import Firebase;`
> Crashlytics add to subspec and Firebase.h

- FirebaseCore/CHANGELOG.md
- FIS related explanation added to eventually appear on the [devisite](https://firebase.google.com/support/release-notes/ios).
- release version and milestone updated
> FirebaseCore changelog M62

- Crashlytics/Crashlytics/Unwind/Compact/FIRCLSCompactUnwind.h
When building for `arm64`, the `FIRCLSFeatures` header is required for processing `FIRCLSCompactUnwind`.
#no-changelog
> Crashlytics fix header import ordering issue

- Crashlytics/Crashlytics/Unwind/Compact/FIRCLSCompactUnwind.h
- Releases/Manifests/6.15.0.json
- Include GoogleUtilities in the release manifest.
- Fix header import issue in Crashlytics (#4649)
> Cherry-picks for M62.

- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
GoogleToolboxForMac sometimes has quotes around it in `Podfile.lock`, causing the parsing of versions to fail.
> Remove extra quotes when parsing versions and names.

- FirebaseInstallations.podspec
This won't run because the required version of InstanceID doesn't work
on watchOS (and watchOS doesn't have XCTests). This is a blocker for
publishing the pod.
#no-changelog
> Don't run unit test spec on watchOS.

- GoogleUtilities.podspec
- GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
- GoogleUtilities/CHANGELOG.md
- GoogleUtilities/CMakeLists.txt
- GoogleUtilities/Environment/GULSecureCoding.m
- GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
- GoogleUtilities/Example/Tests/Network/GULNetworkTest.m
- GoogleUtilities/Example/Tests/Network/third_party/GTMHTTPServer.m
- GoogleUtilities/Example/Tests/Reachability/GULReachabilityCheckerTest.m
- GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
- GoogleUtilities/Example/Tests/Swizzler/GULSceneDelegateSwizzlerTest.m
- GoogleUtilities/ISASwizzler/GULObjectSwizzler.m
- GoogleUtilities/ISASwizzler/GULSwizzledObject.m
- GoogleUtilities/LICENSE
- GoogleUtilities/Logger/GULLogger.m
- GoogleUtilities/MethodSwizzler/GULSwizzler.m
- GoogleUtilities/NSData+zlib/GULNSData+zlib.m
- GoogleUtilities/Network/GULMutableDictionary.m
- GoogleUtilities/Network/GULNetwork.m
- GoogleUtilities/Network/GULNetworkConstants.m
- GoogleUtilities/Network/GULNetworkURLSession.m
- GoogleUtilities/Reachability/GULReachabilityChecker.m
- GoogleUtilities/SceneDelegateSwizzler/GULSceneDelegateSwizzler.m
Standardize to repo-relative imports and add a GoogleUtilities specific license that includes the third_party isAppEncrypted code in the library.
Googlers: See also cl/289117496
> GoogleUtilities - Standardize imports and add LICENSE

- .travis.yml
- CMakeLists.txt
- scripts/install_prereqs.sh
Reuse object files from unchanged sources between builds.
This brings a rebuild of the Firestore CMake build down from 20 min 37 sec,  to 9 min 13 sec:
* Before: https://travis-ci.org/firebase/firebase-ios-sdk/jobs/635423433
* After: https://travis-ci.org/firebase/firebase-ios-sdk/jobs/635295223
#no-changelog
> Cache ccache output

- Interop/FirebaseComponentSystem.md
`s/<SDK>WithApp/<SDK>ForApp/g`
Note: this doesn't affect `initWithApp:` since that's an internal method.
#no-changelog
> Fix public method names.

- scripts/if_changed.sh
> if_changed.sh: add InstanceID and Installations to all dependent SDKs

- Firebase/Messaging/FIRMessagingExtensionHelper.m
The crash was reviled by macOS test (e.g. see the [build](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/637250784?utm_medium=notification&utm_source=github_status)). The crash leads to the tests hanging which looks like a timeout in Travis.
> Fix FIRMessagingExtensionHelper crash when `attachment == nil`

- Firestore/Source/Public/FIRDocumentChange.h
This should fix a documentation generation bug that's causing
FIRDocumentChange to appear to be undocumented.
/cc @markarndt
> Put comments directly above enum definition

- README.md
The new Beta FirebaseCrashlytics SDK supports these platforms, in addition to iOS
#no-changelog
> Add Crashlytics to list of tvOS, macOS, and Catalyst Supported SDKs

- Example/InstanceID/Tests/FIRInstanceIDTest.m
- Example/Messaging/Tests/FIRMessagingInstanceTest.swift
- FirebaseCore/CHANGELOG.md
- FirebaseInstallations.podspec
- FirebaseInstallations/CHANGELOG.md
- FirebaseInstallations/Source/Library/FIRInstallations.m
- FirebaseInstallations/Source/Library/FIRInstallationsLogger.h
- FirebaseInstallations/Source/Library/FIRInstallationsLogger.m
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.h
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Library/Public/FIRInstallations.h
- FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
- FirebaseRemoteConfig/Tests/Unit/FIRRemoteConfigComponentTest.m
Do validation of missing `FIROptions` fields at configuration as other Firebase SDKs do:
- throw in case of missing `FIROptions.APIKey`:
- the parameter is required by Auth, Dynamic links, Firestore, etc.
- this parameter was not required by the old InstanceID version, so there  is a slight chance there are projects that will have to missing `APIKey` after updating
- throw in case of missing `FIROptions.GCMSenderID`: 
- this parameter is already validated by Firebase Core
- use `FIROptions.GCMSenderID` instead of  `FIROptions.projectID` (when unavailable)
See #4692 for additional details.
> Firebase Installations: validation of FIROptions parameters

- Example/InstanceID/Tests/FIRInstanceIDTokenOperationsTest.m
- use mock `FIRInstallations` instead of a real object in `FIRInstanceIDTokenOperationsTest`
> IID: fix flaky tests

- README.md
This has lead to confusion in the past, including #4708
#no-changelog
> Ignore console step for macOS/tvOS/Catalyst builds

- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
This will allow installing pre-release versions since CocoaPods
complains otherwise. Note: this removes any version validation since
we're hardcoding the expected version as the version to install.
Also add `CustomDebugStringConvertible` support to `VersionedPod` for nicer printing when debugging.
#no-changelog
> Use pre-release versions from release manifests.

- GoogleDataTransportCCTSupport/CHANGELOG.md
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTCompressionHelper.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTFLLUploader.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTCompressionHelper.h
Also address a small bug in FLL whereby the compressed data was used no matter what (even if nil because of compression failure).
Currently, no Firebase SDKs are using the CCT backend (except older versions).
> Add compression to CCT

- Crashlytics/LICENSE
- FirebaseCrashlytics.podspec
Adds the Apache license, and clarifies that the license below applies to `dwarf.h`
#no-changelog
> Crashlytics update LICENSE file for libunwind

- .travis.yml
The Crashlytics quickstart test started consistently failing here after https://github.com/firebase/quickstart-ios/pull/871 even though the test doesn't fail in the quickstart repo.
More investigation is required.  In the meantime, this PR disables the test to restore green travis runs.
The QUICKSTART should be reenabled when #4729 is fixed.
Note that the before_install is not necessary as long as Crashlytics doesn't need anything there.
> Disable Crashlytics quickstart testing

- .github/workflows/core.yml
- .github/workflows/dynamiclinks.yml
- .github/workflows/storage.yml
- .github/workflows/zip.yml
- scripts/setup_bundler.sh
- Add a cron job for storage to insure it runs at least once a day
- More specific name for the zip builder cron job
- Setup the bundler in a separate script
- Standardize existing GHA yml files
#no-changelog
> GHA cron updates

- SymbolCollisionTest/Podfile
- SymbolCollisionTest/SymbolCollisionTest.xcodeproj/project.pbxproj
The tests weren't catching duplicate symbol errors - there were silent warnings generated.
- Add `-all_load` to generate linker errors and test failures
- Test local podspecs now that the Firebase pod is open source
- Disable Google Pods that have problems
- Add Installations
- Comment Crashlytics pending #4746
Currently failing until #4744 lands
> Symbol Collision Test Fixes

- Crashlytics/Crashlytics/Controllers/FIRCLSNetworkClient.m
- Crashlytics/Crashlytics/Models/FIRCLSFileManager.m
> Crash preventation

- Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.m
- Crashlytics/Crashlytics/Components/FIRCLSContext.m
- Crashlytics/Crashlytics/Components/FIRCLSCrashedMarkerFile.c
- Crashlytics/Crashlytics/Components/FIRCLSGlobals.h
- Crashlytics/Crashlytics/Components/FIRCLSHost.m
- Crashlytics/Crashlytics/Components/FIRCLSProcess.c
- Crashlytics/Crashlytics/Components/FIRCLSUserLogging.h
- Crashlytics/Crashlytics/Components/FIRCLSUserLogging.m
- Crashlytics/Crashlytics/FIRCLSURLSession/FIRCLSURLSessionAvailability.h
- Crashlytics/Crashlytics/FIRCrashlytics.m
- Crashlytics/Crashlytics/Handlers/FIRCLSException.mm
- Crashlytics/Crashlytics/Handlers/FIRCLSHandler.m
- Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c
- Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c
- Crashlytics/Crashlytics/Helpers/FIRCLSAllocate.h
- Crashlytics/Crashlytics/Helpers/FIRCLSDefines.h
- Crashlytics/Crashlytics/Helpers/FIRCLSInternalLogging.c
- Crashlytics/Crashlytics/Helpers/FIRCLSUtility.m
- Crashlytics/Crashlytics/Models/FIRCLSInternalReport.h
- Crashlytics/Crashlytics/Models/FIRCLSInternalReport.m
- Crashlytics/Crashlytics/Models/FIRCLSReport.m
- Crashlytics/UnitTests/FIRCLSCompactUnwindTests.m
- Crashlytics/UnitTests/FIRCLSDwarfTests.m
- Crashlytics/UnitTests/FIRCLSInternalReportTests.m
- Crashlytics/UnitTests/FIRCLSLoggingTests.m
- Crashlytics/UnitTests/FIRCLSProcessReportOperationTests.m
- Crashlytics/UnitTests/FIRCLSReportManagerTests.m
- Crashlytics/UnitTests/FIRCLSReportTests.m
- SymbolCollisionTest/Podfile
- Resolves symbol collisions https://github.com/firebase/firebase-ios-sdk/issues/4746
Old and New SDK are not compatible in the same app, but symbol collisions are not a great way to discover that. Going to add a warning when both SDKs are included.
> Crashlytics resolve symbol collisions with old SDK

- Crashlytics/Crashlytics/Public/FIRCrashlytics.h
Including multiple crash reporters tends to cause issues with registering exception handlers. Making this a warning so that we don't break builds. Putting in the public header so that zip install / Carthage users get the same warning.
Related to https://github.com/firebase/firebase-ios-sdk/pull/4753
> Crashlytics add warning about including new and old SDK

- FirebaseCore/Tests/Unit/FIROptionsTest.m
Currently these tests rely on other tests to be run first in order for
`kFIRLibraryVersionID` to be assigned. If run alone, these tests crash.
This will prevent that from occurring.
Also fixes b/147988498.
> Fix tests to run individually.

- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordAdapter.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordAdapter.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordApplication.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordApplication.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordBase.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordBase.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordBinaryImage.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordBinaryImage.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordExecutable.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordExecutable.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordFrame.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordFrame.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordHost.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordHost.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordIdentity.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordIdentity.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordKeyValue.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordKeyValue.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordProcessStats.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordProcessStats.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordRegister.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordRegister.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordRuntime.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordRuntime.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordSignal.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordSignal.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordStorage.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordStorage.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordThread.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordThread.m
As part of the design to move the reporting upload to use GoogleDataTransport, the Crashlytics SDK needs the ability to read the persisted crash files on the device. Then the data can be used to populate the nanopb models which will be used for uploading.
Tests executed:
Unit tests for iOS, tvOS, macOS
(New unit tests will be added right after this PR is merged)
TODOs (after this PR):
1. Handle macOS crashes as other clsrecords are involved (ie .clsrecord.symbolicated)
> Add the ability to read persisted (.clsrecord) crash files

- scripts/build.sh
- scripts/install_prereqs.sh
- scripts/setup_bundler.sh
This includes a bunch of fixes that come primarily from the fact that our Travis build is configured by the environment while so far we've been trending toward configuring GHA explicitly.
Specifically:
* This makes it possible to invoke `install_prereqs.sh` with command-line arguments;
* Ensures that bundler is up-to-date by invoking `setup_bundler.sh` from `install_prereqs.sh`;
* Adds Linux build support to `install_prereqs.sh` and `build.sh`; and
* Converts Firestore CMake builds to use `ninja` instead of `make` for a ~20% improvement in build time.
These changes should make it straightforward to port any Travis build that requires `install_prereqs.sh` to GHA:
```yaml
xcodebuild:
runs-on: macos-latest
strategy:
matrix:
target: [iOS, tvOS, macOS]
steps:
- uses: actions/checkout@v2
- …
```
> Prepare build scripts for building Firestore on GitHub Actions

- Crashlytics/CHANGELOG.md
Crashlytics is doing an out of band release for beta.3 to fix https://github.com/firebase/firebase-ios-sdk/pull/4786
Later, I will open a PR for the following changes that will be released with the other Firebase SDKs in a following release:
- [fixed] Fixed symbol collisions with the legacy Fabric Crashlytics SDK and added a warning not to include both (#4753, #4755)
- [fixed] Added preventative crash prevention checks (#4661)
> Update Crashlytics CHANGELOG for beta.3 out of band release

- Crashlytics/CHANGELOG.md
4.0.0-beta.3 was out of band. This CHANGELOG should be shipped with the next normal release
> Crashlytics CHANGELOG 4.0.0-beta.4

- .github/workflows/core.yml
Parallelize the `pod lib lint` platform runs with `matrix`
Inspired by #4752 by @wilhuff
#no-changelog
> Use matrix for Core GHA

- Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.h
- Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m
- Crashlytics/Crashlytics/FIRCrashlytics.m
- Crashlytics/UnitTests/FIRCLSReportManagerTests.m
- Crashlytics/UnitTests/Mocks/FIRCLSMockReportManager.h
- Crashlytics/UnitTests/Mocks/FIRCLSMockReportManager.m
- Crashlytics/UnitTests/Mocks/FIRMockGDTCoreTransport.h
- Crashlytics/UnitTests/Mocks/FIRMockGDTCoreTransport.m
1. Initialize and pass GDTCoreTransport to FIRCLSReportManager
2. Create mock class for GDTCoreTransport (for future unit tests)
3. Clean up initializers in FIRCLSMockReportManager
> Initialize and pass GDTCoreTransport  to FIRCLSReportManager

- Example/Messaging/Tests/FIRInstanceIDWithFCMTest.m
- Example/Messaging/Tests/FIRMessagingDataMessageManagerTest.m
- Example/Messaging/Tests/FIRMessagingHandlingTest.m
- Example/Messaging/Tests/FIRMessagingLinkHandlingTest.m
- Example/Messaging/Tests/FIRMessagingRmqManagerTest.m
- Example/Messaging/Tests/FIRMessagingServiceTest.m
- Example/Messaging/Tests/FIRMessagingSyncMessageManagerTest.m
- Example/Messaging/Tests/FIRMessagingTest.m
- Example/Messaging/Tests/FIRMessagingTestUtilities.h
- Example/Messaging/Tests/FIRMessagingTestUtilities.m
- Example/Messaging/Tests/FIRTestsAssertionHandler.h
- Example/Messaging/Tests/FIRTestsAssertionHandler.m
- Example/Messaging/Tests/XCTestCase+FIRMessagingRmqManagerTests.h
- Example/Messaging/Tests/XCTestCase+FIRMessagingRmqManagerTests.m
- Firebase/Messaging/FIRMessagingRmqManager.h
- Firebase/Messaging/FIRMessagingRmqManager.m
- tests for the deadlock b/148389485
- fix for the deadlock b/148389485
- test fixes to support async `FIRMessagingRmqManager` database removing
- `FIRTestsAssertionHandler` to override default assertion handler for a specific class
> FCM: async remove database in FIRMessagingRmqManager

- Firebase/InstanceID/CHANGELOG.md
- Firebase/InstanceID/FIRInstanceIDCheckinService.m
The logging ID also uses simple random number generator that confuse people #4444. Since it's not used, remove it from logging.
> Stop sending logging ID as it is no longer used in backend

- FirebaseRemoteConfig/Sources/RCNFetch.m
- FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
> Do not continue with fetch if we do not get a valid IID.

- Firebase.podspec
- Firebase/Messaging/CHANGELOG.md
> Update Firebase podspec for watchOS

- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
- ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
- ZipBuilder/Sources/ZipBuilder/ModuleMapBuilder.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Continue xcframework started in #4737 and the rw-zip-xcframeworks branch
- Merges and updates the static library framework build from https://github.com/firebase/firebase-ios-sdk/compare/rw-zip-xcframeworks
- Add a -dynamic boolean option and build xcframeworks created with `use_frameworks!` in the Podfile.  Note that static_framework Pods are still built statically.
- Update the static framework module map generation for the xcframework file hierarchy.
I've verified the xcframeworks comprised of static framework builds works for the Storage quickstart for iOS and Catalyst.
Future steps:
- More substantial testing
- Update path processing for pods with resources
- Resolve remaining dynamic issues disucssed in #4737 - perhaps related to `static_framework` Pods?
I need to work on some other …
> Static library framework build for xcframeworks zip

- Crashlytics/Crashlytics/Models/FIRCLSSettings.h
- Crashlytics/Crashlytics/Models/FIRCLSSettings.m
- Crashlytics/UnitTests/FIRCLSSettingsTests.m
Add the ability to read from settings whether crash reports should be upload to legacy endpoint or the GoogleDataTransport endpoint.
> Add ability to read to report_upload_variant from settings

- .github/workflows/check.yml
Based on [the docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths), `paths` should be used for excluding only when it's also specifying which paths to include. Otherwise, `paths-ignore` should be used.
> Fix ignore paths for Check

- FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m
Imports from other pods should use module import syntax
#no-changelog
> Fix import path for copybara

- Firebase/Messaging/CHANGELOG.md
- Firebase/Messaging/FIRMessagingPendingTopicsList.h
- Firebase/Messaging/FIRMessagingPendingTopicsList.m
- Firebase/Messaging/FIRMessagingPubSub.m
This reverts commit b7fec9e2b82ef91fe4a2422d2f409cfd58c9b4fe.
Revert #4826 out of M64. It should have more testing before being merged.
> Revert "Use secure encoding for messaging's pending topics (#4826)"

- .github/workflows/zip.yml
The nested folder regex did not work as expected.
#no-changelog
> Actually don't run zip on markdown changes.

- ZipBuilder/Sources/ZipBuilder/FileManager+Utils.swift
This will make all temp directories sit under the `ZipRelease` directory instead of being in the temp directory itself with a long name.
#no-changelog
> Provide cleaner temporary directories.

- Firestore/Source/API/FSTFirestoreComponent.mm
- Firestore/core/src/firebase/firestore/api/firestore.cc
- Firestore/core/src/firebase/firestore/api/firestore.h
- Firestore/core/src/firebase/firestore/core/firestore_client.cc
- Firestore/core/src/firebase/firestore/core/firestore_client.h
- Firestore/core/src/firebase/firestore/util/async_queue.cc
- Firestore/core/src/firebase/firestore/util/async_queue.h
- Firestore/core/src/firebase/firestore/util/executor_std.cc
- Firestore/core/src/firebase/firestore/util/executor_std.h
- Firestore/core/src/firebase/firestore/util/filesystem.h
- Firestore/core/test/firebase/firestore/testutil/async_testing.cc
- Firestore/core/test/firebase/firestore/util/async_queue_libdispatch_test.mm
- Firestore/core/test/firebase/firestore/util/async_queue_test.cc
- Firestore/core/test/firebase/firestore/util/async_queue_test.h
Fixes for issues discovered in the Unity desktop build (#4795)
Ensure that Firestore properly shuts down when the Unity AppDomain is unloaded. Improper shutdown manifested as a crash the next time Firestore was used because the LevelDB database files were still locked by the prior instance.
AppDomain unload differs from typical iOS termination because we want Dispose to be synchronous so that we signal shutdown is complete by the time Dispose returns. Without this, there's a race between shutdown in the current domain and startup in the next domain. This poses a problem though because disposers are run on the main thread, and callbacks from Firestore's async operations also typically run on the main thread. This means that by default there's no great way to implement Dispose without …
> Cherry-pick #4795 for the release-6.16 branch

- Firestore/core/src/firebase/firestore/util/bits.h
This is a cherry-pick of #4836 for release-6.17.0.
This fixes builds on 32-bit Windows in google3 after cl/291012718, which added `#include <ciso646>` to `absl/base/options.h`.
This has no effect on any Apple platform so it doesn't warrant a respin of any iOS release candidates.
> Fix bits.h when compiled by MSVC after including <ciso646> (#4836)

- Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
This is a follow up to: https://github.com/firebase/firebase-ios-sdk/pull/4793
1. Map the read values from user key value, error and log .clsrecords into the Report nanopb models
2. Add TODOs to track potential logic that we have to move from protobuilder into the SDK
The next related PR will be to add unit tests for protobuilder logic that has been moved into the SDK.
> Map the read values from user key value, error and log .clsrecords into the Report nanopb model

- Firestore/Example/Podfile
- Firestore/Swift/Tests/API/BasicCompileTests.swift
This makes it possible to build and test on a release branch before the
Firebase pod is released.
> Drop Firestore's Podfile dependency on Firebase

- .github/workflows/firestore.yml
- scripts/if_changed.sh
- scripts/run_firestore_emulator.sh
The emulator now sends resume tokens, which exercises more of the system.
In particular, this means that resuming queries now uses the index-free
query engine.
> Upgrade Firestore emulator to 1.10.4

- Firestore/Example/Podfile
- scripts/build.sh
- scripts/install_prereqs.sh
This hasn't worked in a long time and is just clutter at this point.
> Drop support for building Firestore with Xcode 8

- Firebase/CoreDiagnostics/CHANGELOG.md
- Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
- GoogleDataTransportCCTSupport/CHANGELOG.md
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTNanopbHelpersTest.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.m
iOS seems to do this when the buffer becomes > 16320 bytes.
> Set mutable data ref lengths, otherwise iOS will 0 out the buffer

- .github/workflows/core.yml
- .github/workflows/dynamiclinks.yml
- .github/workflows/firestore.yml
- .github/workflows/storage.yml
Use travis_retry to avoid failures on iOS simulator flakes
Add storage and dynamic links cron job tests for `--use-libraries` and `--use-modular-headers`
cc: @schmidt-sebastian @wilhuff @dmandar 
#no-changelog
> Always retry pod lib lint

- GoogleDataTransportCCTSupport/CHANGELOG.md
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTCompressionHelper.m
Fix new analyzer warning from Xcode 11.4
- WARN  | [iOS] xcodebuild:  /Users/paulbeusterien/gh/firebase-ios-sdk/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTCompressionHelper.m:48:8: warning: Although the value stored to 'retCode' is used in the enclosing expression, the value is never actually read from 'retCode'
> Fix Xcode 11.4 analyze error

- scripts/build.sh
- scripts/install_prereqs.sh
Use `xcpretty-travis-formatter` to group output. It's not perfect, but it's an improvement.
Here's an example: https://travis-ci.org/firebase/firebase-ios-sdk/jobs/647887643 (note the Build, Test, and Warnings groups).
> Add a travis output filter

- Firestore/Source/API/FIRDocumentReference.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/core/src/firebase/firestore/api/document_reference.cc
- Firestore/core/src/firebase/firestore/api/document_reference.h
- Firestore/core/src/firebase/firestore/api/document_snapshot.h
- Firestore/core/src/firebase/firestore/api/query_core.cc
- Firestore/core/src/firebase/firestore/api/query_core.h
- Firestore/core/src/firebase/firestore/api/query_snapshot.h
- Firestore/core/src/firebase/firestore/core/event_manager.cc
- Firestore/core/src/firebase/firestore/core/event_manager.h
- Firestore/core/src/firebase/firestore/core/firestore_client.cc
- Firestore/core/src/firebase/firestore/core/firestore_client.h
- Firestore/core/src/firebase/firestore/core/query_listener.cc
- Firestore/core/src/firebase/firestore/core/query_listener.h
- Firestore/core/src/firebase/firestore/core/sync_engine.cc
- Firestore/core/src/firebase/firestore/core/sync_engine.h
- Firestore/core/src/firebase/firestore/core/view_snapshot.h
- Firestore/core/src/firebase/firestore/immutable/sorted_set.h
- Firestore/core/src/firebase/firestore/util/status.h
- Firestore/core/test/firebase/firestore/core/event_manager_test.cc
- Firestore/core/test/firebase/firestore/core/query_listener_test.cc
- Firestore/core/test/firebase/firestore/immutable/sorted_set_test.cc
- Firestore/core/test/firebase/firestore/util/status_test.cc
Fix a bunch of issues that make it hard to pervasively use forward declarations in our code.
Also, remove some dead code.
> Prep for forward declarations

- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordFrame.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordFrame.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
- Crashlytics/ProtoSupport/Protos/crashlytics.options
- Crashlytics/ProtoSupport/Protos/crashlytics.proto
- Crashlytics/Protogen/nanopb/crashlytics.nanopb.c
- Crashlytics/Protogen/nanopb/crashlytics.nanopb.h
- Crashlytics/UnitTests/FIRCLSReportAdapterTests.m
- Sets the fields in the `Exception` part of the app execution.
- Also fixes the analysis issue with `signalProto`
Does not fill in symbolicated files or importance for symbolicated.
> Crashlytics GDT fill in Exception part of Proto

- FirebaseCore/CHANGELOG.md
- ZipBuilder/Sources/ZipBuilder/ModuleMapBuilder.swift
Fix #4819 
Include transitive library and framework dependencies in generated module maps since they may not be pulled in if the dependency is not referenced as a module.
This change causes the following modulemap diffs from the 6.17.0 binary distribution:
```
/var/folders/mk/9ccbvq8x00q20q0f7mfxbtrw00bzqz/T/ZipRelease/96E84341-22B2-426D-A8B2-922AC87656B0/Firebase  $ diff -r  ~/Downloads/Firebase-6.17.0/ ./ | grep -v differ | grep -v nib
diff -r /Users/paulbeusterien/Downloads/Firebase-6.17.0/FirebaseABTesting/FirebaseABTesting.framework/Modules/module.modulemap ./FirebaseABTesting/FirebaseABTesting.framework/Modules/module.modulemap
4a5,9
>   link framework "Foundation"
>   link framework "Security"
>   link framework "SystemConfiguration"
>   link framework "UIKit"
>   link "z"
diff -r …
```
> Include transitive deps in module maps

- FirebaseRemoteConfig/CHANGELOG.md
- FirebaseRemoteConfig/Sources/RCNConfigDBManager.h
- FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
- FirebaseRemoteConfig/Sources/RCNConfigSettings.m
- FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.h
- FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNUserDefaultsManagerTests.m
Addresses b/148386739, #4677 , #4734. Backgroubd: We explicitly disable backup of the sqlite database. Hence upon restore, we do not have any data. This causes a fetch to be made, but we send the last eTag (which is saved in userdefaults and cannot be opted out of backup) along with the fetch request which causes the RC backend to send a NO_CHANGE back. Fix is to identify if the database is gone, and if so, reset the userdefaults.
> Reset RC per-instance userdefaults if config database was not found.

- Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m
- Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.h
- Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.m
- Crashlytics/Crashlytics/Models/FIRCLSFileManager.h
- Crashlytics/Crashlytics/Models/FIRCLSFileManager.m
- Crashlytics/Crashlytics/Operations/Reports/FIRCLSPackageReportOperation.m
- Crashlytics/UnitTests/FIRCLSFileManagerTests.m
- Crashlytics/UnitTests/FIRCLSReportManagerTests.m
- Crashlytics/UnitTests/FIRCLSReportUploaderTests.m
The report manager has the ability to send to two different endpoints.
The old legacy flow for a report goes through the following states/folders:
1. active - .clsrecords optimized for crash time persistence
2. processing - .clsrecords with attempted symbolication
3. prepared-legacy - .multipartmime of compressed .clsrecords
The legacy flow for a report goes through the following states/folders:
1. active - .clsrecords optimized for crash time persistence
2. processing - .clsrecords with attempted symbolication
3. prepared - .clsrecords moved from processing with no changes
The code was designed so the report processing workflows are not dramatically different from one another. The design will help avoid having a lot of conditional code blocks throughout the codebase.
> Add the ability to send to the new and legacy crash reporting endpoint

- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
More context at https://github.com/CocoaPods/CocoaPods/issues/8891
With this change the Firestore xcframework and its dependencies successfully build
#no-changelog
> Build xcframeworks for pods with resources

- FirebaseCore/Sources/FIRApp.m
- FirebaseCore/Sources/FIRComponentContainer.m
- FirebaseCore/Sources/Private/FIRComponentContainerInternal.h
- FirebaseCore/Tests/Unit/FIRAppTest.m
- FirebaseCore/Tests/Unit/FIRComponentContainerTest.m
> FIRApp: don't create new component instances while deleting the app

- ZipBuilder/Sources/ZipBuilder/FileManager+Utils.swift
> Make Zip Builder temp dirs sortable and understandable with timestamp

- Firestore/CHANGELOG.md
Note that this change includes changes to the internal C++ API making it unsuitable for a patch version.
> Update CHANGELOG for Firestore v1.11.0

- FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m
- FirebaseInAppMessaging/Sources/Data/FIRIAMMessageDefinition.m
- FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
- FirebaseInAppMessaging/Sources/Private/Data/FIRIAMMessageDefinition.h
- FirebaseInAppMessaging/Sources/Public/FIRInAppMessagingRendering.h
- FirebaseInAppMessaging/Sources/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m
- FirebaseInAppMessaging/Sources/RenderingObjects/FIRInAppMessagingRenderingPrivate.h
- FirebaseInAppMessaging/Tests/Unit/FIRIAMDisplayExecutorTests.m
- FirebaseInAppMessaging/Tests/Unit/FIRIAMFetchResponseParserTests.m
- FirebaseInAppMessaging/Tests/Unit/TestJsonDataFromFetch.txt
Reverts firebase/firebase-ios-sdk#4820
> Data bundles for FIAM

- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
New test was failing to compile on some platforms with 
```
FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m:196:31: error: called object type 'id' is not a function or function pointer
.ignoringNonObjectArgs()
```
Being explicit about types fixes the issue
#no-changelog
> Fix portability of new test

- FirebaseRemoteConfig/Sources/RCNConfigExperiment.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
> Ignore deprecation warnings for FIRExperimentController.updateExperiments(serviceOrigin:events:policy:lastStartTime:payloads:)

- GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTPrioritizer.h
This will need to be excluded in the merge, but is required to get GDTCCTSupport linting.
```
- ERROR | xcodebuild:  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTPrioritizer.h:37:35: error: unknown type name 'GDTCORStoredEvent'
```
> Forward declare class to fix linting.

- GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTPrioritizer.h
This reverts commit 64bbf378bb509e20ba97af731971906f008301c9.
Turns out it was a `pod cache` problem.
> Revert "Forward declare class to fix linting. (#4935)"

- FirebaseCore.podspec
This is required since `watchOS` doesn't have `XCTest` available.
#no-changelog
> Specify platforms for Swift unit tests

- FirebaseCore/Sources/FIRApp.m
- FirebaseCore/Tests/Unit/FIRAppTest.m
Collect stats on Firebase usage by Apple platform (b/146507104).
> FIRApp: add apple platform to firebaseUserAgent

- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
Fix radioacesstechnology api deprecated for ios 12.0 or newer
> Fix radioacesstechnology api deprecated for ios 12.0 or newer

- .github/workflows/datatransport.yml
- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTNanopbHelpers.h
1 Wrap SCNetworkReachabilityFlags in GDTCORPlatform.
2 Fix Catalyst warning in GDTCORPlatform.
> Wrap SCNetworkReachabilityFlags and fix Catalyst warning

- README.md
These changes just update the README to fix the broken watchOS sample link.
> Update README.md to fix broken watchOS sample link

- CMakeLists.txt
- cmake/cc_rules.cmake
- cmake/compiler_setup.cmake
- cmake/external_rules.cmake
- scripts/binary_to_array.py
This makes it possible to embed the Firestore CMake build contained in this repo in the public C++ CMake build.
This is enough to get the firebase-cpp-sdk build working with tests disabled. More changes may be required for tests enabled.
> Fixes for compatibility with builds in firebase-cpp-sdk

- Crashlytics/Crashlytics/Settings/Operations/FIRCLSOnboardingOperation.m
- Crashlytics/Shared/FIRCLSConstants.m
New DNS to facilitate backend migration
> Crashlytics move Update call from api. to update.

- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
Restore Firestore build after #4940 broke it because of the abseil dependency.
With this change, a zip with xcframeworks for all the Podfile dependencies of the Firestore quickstart now build.
The quickstart fails to build because FirebaseUI does not have an umbrella header necessary for Swift module imports.  The proper way to build static libs in CocoaPods with modular headers is the `use_modular_headers!` option but that does now work with Firestore because gRPC does not work with them. See https://github.com/grpc/grpc/issues/20631 and https://github.com/CocoaPods/CocoaPods/issues/9023.
Next step is to investigate the feasibility of fixing https://github.com/CocoaPods/CocoaPods/issues/9023. In the meantime sending the PR here to checkpoint.
Here is the json file for the Firestore …
> Restore Firestore build in xcframework branch

- Firestore/core/src/firebase/firestore/remote/connectivity_monitor.cc
- Firestore/core/src/firebase/firestore/remote/connectivity_monitor.h
- Firestore/core/src/firebase/firestore/remote/connectivity_monitor_apple.mm
Attempt to fix https://github.com/firebase/firebase-ios-sdk/issues/4905
> Checks for connectivity when App is moving to foreground.

- FirebaseABTesting.podspec
- FirebaseABTesting/Sources/FIRExperimentController.m
- FirebaseABTesting/Sources/Public/FIRExperimentController.h
- FirebaseABTesting/Tests/Unit/FIRExperimentControllerTest.m
- FirebaseInAppMessaging.podspec
- FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m
- FirebaseInAppMessaging/Sources/Data/FIRIAMMessageDefinition.m
- FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
- FirebaseInAppMessaging/Sources/Flows/FIRIAMMessageClientCache.m
- FirebaseInAppMessaging/Sources/Flows/FIRIAMMsgFetcherUsingRestful.m
- FirebaseInAppMessaging/Sources/Private/Data/FIRIAMMessageDefinition.h
- FirebaseInAppMessaging/Sources/Public/FIRInAppMessagingRendering.h
- FirebaseInAppMessaging/Sources/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m
- FirebaseInAppMessaging/Sources/RenderingObjects/FIRInAppMessagingRenderingPrivate.h
- FirebaseInAppMessaging/Tests/Integration/DefaultUITestApp/Podfile
- FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/Podfile
- FirebaseInAppMessaging/Tests/Unit/FIRIAMDisplayExecutorTests.m
- FirebaseInAppMessaging/Tests/Unit/FIRIAMFetchFlowTests.m
- FirebaseInAppMessaging/Tests/Unit/FIRIAMFetchResponseParserTests.m
- FirebaseInAppMessaging/Tests/Unit/FIRIAMMessageClientCacheTests.m
- FirebaseInAppMessaging/Tests/Unit/TestJsonDataFromFetch.txt
Supports experimental Firebase in-app messages (cross-functional with Firebase AB Testing).
Adds functionality to the ABT SDK:
- A method that cleans up old experiments that are no longer running
- A method that directly activates an experiment
FIAM SDK changes:
- Parses experimental metadata from FIAM backend, attaches the experiment payload to `InAppMessageDisplayMessage`
- On message fetch, cleans up experiments that are no longer running
- On message impression, sets the experiment to be activated
- ~~Removes deprecated initializers for message subclasses (internal bug ID 134409779).~~ Removed this for now, looks like the UI test app uses them
> Support AB testing of Firebase In-App Messages

- FirebaseStorage.podspec
Firebase Core watch OS support was added in M62 (FirebaseCore 6.6.0) by #4016
#no-changelog
> FirebaseStorage.podspec - update Core dependency version to one supporting watchOS

- Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.m
- Crashlytics/Crashlytics/Models/FIRCLSInternalReport.m
With the new GDT changes, Analytics might not be called because the logic is to detect certain crash files in a directory. However, in the GDT workflow, that directory may be moved or deleted. The fix is to check whether a report has a crash before any processing. 
Verified a "clx" event is sent when Google Analytics is included in the project after a crash has occurred.
> Fix issue where Crash Free Users does not work with new GDT changes

- CMakeLists.txt
- scripts/build.sh
This really needs to be set on the command-line if it's to be effective,
and setting it here breaks downstream projects that include
firebase-ios-sdk as a subdirectory.
> Remove setting CMAKE_BUILD_TYPE in CMakeLists.txt

- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/FileManager+Utils.swift
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
- ZipBuilder/Sources/ZipBuilder/ModuleMapBuilder.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Take advantage of new CocoaPods 1.9.0 functionality to use static frameworks instead of static libs to build zip.  It now can build Swift pods, but still more to figure out for managing bridging headers.
The static library `pod install` is still necessary for calculating the module map dependencies.
Also some additional minor improvements:
- Use dashes instead of colons in temp file name so command line completion works
- Only adjust signing for building Catalyst library
- Stop assuming that arm64 is always built
- Support xcframeworks that don't have all possible slices built
- Handle umbrella header specification for non-Firebase pods
- Delete no longer necessary code for copying symbolic linked header directories - because Headers are not links in the framework build.
Future tasks:
- …
> Use static frameworks to build zip

- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
- GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h
- Switch watchOS applicationDelegate to WKExtensionDelegate
- sharedApplicationForBackgroundTask shared WKExtension in watchOS instead of UIApplication
- TODO: Implement beginBackgroundTaskWithName and endBackgroundTask for watchOS
> Switch watchOS applicationDelegate to WKExtensionDelegate

- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
Build Swift modules for zip distributions.  Swift libraries need to include a .swiftmodule directory in the Modules directory of the framework.  This PR sets it up:
The resulting xcframeworks now can be dragged and dropped into the Firestore quickstart and it runs correctly for iOS and Catalyst.
#no-changelog
> Add Swift module support to ZipBuilder

- Firestore/Protos/CMakeLists.txt
The `firebase_firestore_protos_libprotobuf` library contains protoc-generated code. Compile with standard flags rather than Firestore's default of `-Wall -Wextra -Werror`.
This avoids errors like these:
```
Firestore/Protos/cpp/google/firestore/v1/firestore.pb.cc:1669:11: error: ‘void* memset(void*, int, size_t)’ offset [57, 61] from the object at ‘google::firestore::v1::_ListDocumentsRequest_default_instance_’ is out of the bounds of referenced subobject ‘google::firestore::v1::ListDocumentsRequest::mask_’ with type ‘google::firestore::v1::DocumentMask*’ at offset 48 [-Werror=array-bounds]
1669 |   ::memset(&mask_, 0, static_cast<size_t>(
|   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1670 |       reinterpret_cast<char*>(&show_missing_) -
|       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
> Fix compilation under Linux/GCC 9.2.1 in Release mode

- .github/workflows/zip.yml
- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
Fix nightly GHA build that started failing after repo switched to CocoaPods 1.9.0.
Remove the specification from the zip builder so it uses the CocoaPods installed by scripts/setup_bundler.sh.
> Fix nightly zip GHA build

- Firebase.podspec
- FirebaseCore.podspec
- FirebaseCoreDiagnostics.podspec
- FirebaseCrashlytics.podspec
- FirebaseFirestore.podspec
- FirebaseInAppMessaging.podspec
- FirebaseRemoteConfig.podspec
- GoogleDataTransport.podspec
- GoogleDataTransportCCTSupport.podspec
- Releases/Manifests/6.19.0.json
- release branch content
- Firebase Crashlytics GDT dependency versions update (to fix the [build failure](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/660719553?utm_medium=notification&utm_source=github_status))
#no-changelog
> Merge release 6.19.0

- FirebaseFirestore.podspec
In #4985 we added support for listening to
`UIApplicationWillEnterForegroundNotification` notifications to better
handle situations where we may have missed callbacks from
`SCNetworkReachabilitySetCallback` while Firestore was in the background.
Fixes #5065.
@paulb777, should we cherry-pick this into the `release-6.19` branch and bump Firestore to 1.11.2?
> Explicitly state Firestore's dependency on UIKit

- Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m
- Crashlytics/Crashlytics/Settings/FIRCLSSettingsOnboardingManager.h
- Crashlytics/Crashlytics/Settings/FIRCLSSettingsOnboardingManager.m
Scenario:
1. Developer has automatic data collection disabled inside the app plist
2. A crash occurred
3. The app relaunches and the developer calls sendUnsentReport
Result:
1. The crash report does not get uploaded because there's a race condition:
-  Settings is triggered async
-  The report is not uploaded because the org id from settings is not available
Validation:
1. E2E scenario 
2. Unit tests
3. Verified even when FIRCrashlytics.sendUnsentReport is on the main thread, waiting for the semaphore is not on the main thread.
> b/151167694 - sendUnsentReport might not upload until the second time the API is called

- FirebaseInAppMessaging.podspec
- FirebaseInAppMessaging/Sources/Flows/FIRIAMMsgFetcherUsingRestful.m
We've made a product decision to not clean these up for now.
Impact: if a user stops an experiment via the console, all events will continue to be striped with the CUP for that experiment.
Also fixed the version number for the ABT dependency, which somehow got reverted. FIAM should update on minor ABT releases.
> Remove cleanup of experiments that are no longer running

- GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORFlatFileStorage.h
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORLifecycle.h
- GoogleDataTransport/GDTCORTests/Common/Categories/GDTCORFlatFileStorage+Testing.h
- GoogleDataTransport/GDTCORTests/Common/Categories/GDTCORFlatFileStorage+Testing.m
- GoogleDataTransport/GDTCORTests/Integration/GDTCORIntegrationTest.m
- GoogleDataTransport/GDTCORTests/Lifecycle/GDTCORLifecycleTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m
Renames GDTCORStorage to GDTCORFlatFileStorage to be more descriptive of the actual functionality and because of potential confusion due to the creation of GDTCORStorageProtocol.
> Rename GDTCORStorage to GDTCORFlatFileStorage

- GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m
- GoogleDataTransport/GDTCORLibrary/GDTCORTransport.m
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORConsoleLogger.h
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
This could be because of changes to NSCoding w.r.t. transitioning from GDTCORStoredEvent to GDTCOREvent.
Fixes #5082
> Don't attempt to create data if the event's fileURL is nil.

- ZipBuilder/README.md
- ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift
- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/FirebaseBuilder.swift
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
- ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
- ZipBuilder/Sources/ZipBuilder/main.swift
- ZipBuilder/Template/README.md
Update and refactor Carthage build for the xcframework changes.
Carthage does not yet support xcframeworks, so this should generate the same build as before for Carthage.
In the refactor, Carthage builds and adaptations are pushed lower in the process to avoid complicated adjustments in the higher level functions that had to reach down to make changes into low-level generated build artifacts.
Both zip and Carthage share the same compile phases, but then separately package to xcframeworks and frameworks. Carthage rebuilds FirebaseCoreDiagnostics with the right flags and skips including the Catalyst slice.
Fix #4917
> Zip Carthage refactor

- ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
- ZipBuilder/Sources/ZipBuilder/ResourcesManager.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Storing resources in the frameworks embedded in the xcframework was causing a crash when the resources were moved to the top of the folder since there were three copies instead of one.
This PR refactors the resource to build them into Carthage frameworks from the start and at the top of an xcframework (so there's only one copy) that can be then moved out to the enclosing folder for the Firebase zip distribution.
> Zip Resource handling for xcframeworks

- scripts/localize_podfile.swift
Fix travis cron failure at https://travis-ci.org/github/firebase/firebase-ios-sdk/jobs/661826491
FirebaseAuth is a quickstart dependency of the Functions quickstart via FirebaseUI so we need to ensure we get the local podspec when we get the local Firebase podspec.
> FirebaseAuth should be in implicit pod list

- ZipBuilder/README.md
- ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift
- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/FileManager+Utils.swift
- ZipBuilder/Sources/ZipBuilder/FirebaseBuilder.swift
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
- ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
- ZipBuilder/Sources/ZipBuilder/ModuleMapBuilder.swift
- ZipBuilder/Sources/ZipBuilder/ResourcesManager.swift
- ZipBuilder/Sources/ZipBuilder/Zip.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
- ZipBuilder/Sources/ZipBuilder/main.swift
- ZipBuilder/Template/FrameworkMaker.entitlements
- ZipBuilder/Template/FrameworkMaker.xcodeproj/project.pbxproj
- ZipBuilder/Template/README.md
Update the distribution of source pods in the zip distribution from frameworks to xcframeworks.  The result is that the community-supported Catalyst support is now available via the zip distribution in addition the CocoaPods.
Everything in this PR has already been reviewed and the plan is to merge this from the command line to avoid squashing the individual PRs on the xcframework-master branch.
The release notes will be updated after this merges to master.
#no-changelog
> Update the zip distribution from frameworks to xcframeworks

- FirebaseInAppMessaging.podspec
- FirebaseInAppMessaging/Sources/Analytics/FIRIAMClearcutLogger.m
- FirebaseInAppMessaging/Sources/FIRInAppMessaging.m
- FirebaseInAppMessaging/Sources/FIRInAppMessagingPrivate.h
- FirebaseInAppMessaging/Sources/Flows/FIRIAMClientInfoFetcher.m
- FirebaseInAppMessaging/Sources/Flows/FIRIAMMsgFetcherUsingRestful.m
- FirebaseInAppMessaging/Sources/Private/Analytics/FIRIAMClientInfoFetcher.h
- FirebaseInAppMessaging/Sources/Runtime/FIRIAMRuntimeManager.m
- FirebaseInAppMessaging/Sources/Runtime/FIRIAMSDKRuntimeErrorCodes.h
- FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/Podfile
- FirebaseInAppMessaging/Tests/Unit/FIRIAMClearcutLoggerTests.m
- FirebaseInAppMessaging/Tests/Unit/FIRIAMClientInfoFetcherTests.m
- FirebaseInAppMessaging/Tests/Unit/FIRIAMMsgFetcherUsingRestfulTests.m
This is an initial FIS integration step, using FID and the FIS token in place of where we are currently using IID and the IID token.
Will follow up with another PR to replace all usages of `iid` or `instanceID` to avoid confusion-- this one has already gotten fairly large.
Next step is to only use FIS token in the server request, see internal bug #148729615.
#fixes #3887
> Use FIRInstallations SDK to fetch FID and FIS token, send those values in requests to FIAM backend

- Firebase.podspec
The FirebaseAuth's version was updated without updating the Firebase/Auth subspec causing travis failures.
> Fix Firebase/Auth version

- FirebaseRemoteConfig.podspec
- FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
It appeared that RC tests had ARC disabled.
- enabled ARC
- fixed issues and warnings
> Remote Config: enable ARC for tests.

- Crashlytics/UnitTests/FIRCLSSettingsTests.m
Ensure the settings directory gets cleared in between runs.
Ran CI ~5 times with the last change and the tests pass. Added a debug log in case the issue still occurs.
> Attempt to fix intermittent failing Crashlytics settings tests in CI

- FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
Fixes #5098.
Accessing `FIRHeartbeatInfo` implies accessing file system which may be a slow operation. The changes move all `FIRHeartbeatInfo` related operations to a background queue.
> Installations: access FIRHeartbeatInfo from a background thread

- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTPrioritizer.h
The prioritizer currently does not maintain state between app restarts. It's possible for GDTCORStorage to have references to stored events that the prioritizer doesn't know about--this (sort of) fixes that. Ultimately, the prioritizer asking storage for events is probably the only reasonable solution long-term.
> Make the prioritizer save state between app launches

- Firebase/CoreDiagnostics/CHANGELOG.md
- Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
- GoogleDataTransportCCTSupport/CHANGELOG.md
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTNanopbHelpers.h
Reverts #5059 
There's a subtle bug (currently unknown) that's causing events to not be decodable by the server.
> Revert "Address a few potential security issues (#5059)"

- Firebase.podspec
Merging the 6.20.0 release into master
> Merge release 6.20.0

- .github/workflows/core.yml
- .github/workflows/datatransport.yml
- .github/workflows/messaging.yml
- .github/workflows/storage.yml
- GoogleDataTransport/GDTCORTests/Unit/GDTCORStorageTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORUploadCoordinatorTest.m
- scripts/test_catalyst.sh
This is a start at adding Catalyst to GHA CI.
Building and unit tests are enabled for GDT and Storage.
Building is enabled for Core and Messaging.
One test had to be disabled in GDT for Catalyst because it didn't seem like an easy port and it relies upon the NSKeyedArchiver which is going away.
A future task is to figure out how to run tests for testspecs that have `requires_app_host` enabled.
[FirebaseCore](https://github.com/firebase/firebase-ios-sdk/runs/512270812?check_suite_focus=true) and [FirebaseMessaging](https://github.com/firebase/firebase-ios-sdk/runs/512270895?check_suite_focus=true) fail with:
```
Testing failed:
Unable to load standard library for target 'x86_64h-apple-ios13.1-macabi'
Testing cancelled because the build failed.
** TEST FAILED **
```
Specifying only the …
> Add Catalyst testing for GHA

- FirebaseInAppMessaging/Resources/FIRInAppMessageDisplayStoryboard.storyboard
- FirebaseInAppMessaging/Sources/DefaultUI/Banner/FIRIAMBannerViewController.m
- Removes storyboard constraint (at build time) that pins top level UI elements to the top layout guide
- Adds programmatic constraint that pins them to the bottom of the status bar
#fixes #4714 
After fix:
Before fix:
> In banner view, pin top elements to the bottom of the status bar

- Crashlytics/Crashlytics/Models/FIRCLSSettings.m
- Crashlytics/Crashlytics/Settings/Models/FIRCLSApplicationIdentifierModel.h
- Crashlytics/Crashlytics/Settings/Models/FIRCLSApplicationIdentifierModel.m
- Crashlytics/UnitTests/FIRCLSSettingsTests.m
- Crashlytics/UnitTests/Mocks/FABMockApplicationIdentifierModel.h
- Crashlytics/UnitTests/Mocks/FABMockApplicationIdentifierModel.m
Sometimes devs will change the app version without making a codechange. In these cases, clear the cache just in case so we register the build.
> Crashlytics cache key app version

- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
- GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
- GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h
- GoogleDataTransport/GDTCORTests/Unit/GDTCORClockTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCOREventTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORStorageTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORUploadCoordinatorTest.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
Fixes #5086
Hopefully this catches all the deprecation warnings.
cc: @paulb777 Together, we need to write some test automation that sets the deployment version of all targets to the highest OS version for any particular platform.
> Fix deprecation warnings by consolidating coding calls

- GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m
- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
- GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
- GoogleDataTransport/GDTCORLibrary/Private/GDTCOREvent_Private.h
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h
- GoogleDataTransport/GDTCORTests/Integration/GDTCORIntegrationTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCOREventTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORStorageTest.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORUploadPackageTest.m
- GoogleDataTransport/GDTCORTests/Unit/Helpers/GDTCOREventGenerator.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTNanopbHelpersTest.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Unit/Helpers/GDTCCTEventGenerator.m
Apparently, since iOS 8, it's possible for the app's bundle to change directories as often as every launch. This is a mechanism that's hopefully slightly more robust against that, as data is supposed to carry over, the UUID component of the app's absolute directory might just change.
> Refactor event fileURLs to be derived

- FirebaseDynamicLinks.podspec
Fixes #5139.
I cannot find usage of the removed Apple frameworks.
> Dynamic Links: cleanup Apple framework dependencies

- GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
- GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m
- GoogleDataTransport/GDTCORLibrary/GDTCORTransport.m
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage.h
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer.h
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORPrioritizer.h
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORTransport.h
- GoogleDataTransport/GDTCORTests/Integration/Helpers/GDTCORIntegrationTestPrioritizer.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m
Currently, the onComplete block of sendXEvent:onComplete: is invoked when the event bytes are written to disk. However, if the app crashes before a lifecycle event occurs (trigger GDTCORStorage to serialize to disk), that event is effectively lost because the metadata has all been lost. This change triggers the saving of state of GDTCORStorage and prioritizers (if they implement it) if an onComplete block has been given.
> Libraries should save state if a completion block is requested

- Firestore/core/src/firebase/firestore/api/collection_reference.cc
- Firestore/core/src/firebase/firestore/api/collection_reference.h
Primarily for consistency with [`DocumentReference::document_id`](https://github.com/firebase/firebase-ios-sdk/blob/aeb4def61d42b74fc8a3834c35ab105b80258d50/Firestore/core/src/firebase/firestore/api/document_reference.h#L57). Note that `BasePath::last_segment` [returns a const reference](https://github.com/firebase/firebase-ios-sdk/blob/aeb4def61d42b74fc8a3834c35ab105b80258d50/Firestore/core/src/firebase/firestore/model/base_path.h#L71-L74).
> Make `api::CollectionReference::collection_id` return a const reference

- Firebase.podspec
- FirebaseRemoteConfig.podspec
- FirebaseRemoteConfig/CHANGELOG.md
- Releases/Manifests/6.21.0.json
> Remove RC from M67

- FirebaseRemoteConfig.podspec
- FirebaseRemoteConfig/CHANGELOG.md
- FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
- FirebaseRemoteConfig/Sources/RCNConfigSettings.m
- FirebaseRemoteConfig/Sources/RCNFetch.m
- FirebaseRemoteConfig/Tests/Sample/Podfile
- FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m
- FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m
Reverts firebase/firebase-ios-sdk#5096
We have to revert it so far because AB Testing backend is not ready for the migration at the moment.
> Revert "Migrate from using IID SDK for Remote Config to the new FIS SDK"

- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
- Modify Platform switch in sharedApplicationForBackgroundTask and isAppExtension.
- Change notification name for watchOS in GDTCORApplication init. 
- Add notification listener for extension app for iOS, tvOS, watchOS
> Modify watchOS platform notification name

- Carthage.md
Clarify the instructions here - you can put the scripts wherever you want, as long as the path in the Build Phase matches up
> Clarify Crashlytics Carthage run and upload-symbols placement

- GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORUploadCoordinatorTest.m
- GoogleDataTransport/GDTCORTests/Unit/Helpers/GDTCOREventGenerator.m
Fixes an issue where the upload coordinator removes events from disk when the upload was unsuccessful and should be retried in the future.
> Only delete events when package was successfully delivered

- GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORUploadCoordinatorTest.m
- GoogleDataTransport/GDTCORTests/Unit/Helpers/GDTCOREventGenerator.m
* Only delete events when package was successfully delivered
* Add unit test to check that retrying a package delivery doesn't delete an event file
> Only delete events when package was successfully delivered (#5172)

- .github/workflows/dynamiclinks.yml
- .github/workflows/storage.yml
- scripts/decrypt_gha_secret.sh
This PR updates the storage GHA workflow to work on PRs from both the main repo and forked repos by disabling the tests that depend upon secrets when the associated environment variable is not set.
It would be nice to do this at the job level, but I wasn't able to find a way. 
The change is verified here for the main repo and in #5179 for a forked repo.
> GHA for PRs from GitHub forks

- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
- Change sharedWKExtensionForBackgroundTask to sharedNSProcessInfo on watchOS for using api performExpiringActivityWithReason usingBlock
- Add static variable sSemaphoreQueue and sBackgroundIdentifierToSemaphoreMap
- Add class methods for mapping GDTCORBackgroundIdentifier to task semaphores
> Handle tasks with semaphores on watchOS Platform

- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Unit/Helpers/GDTCCTEventGenerator.m
1. Fixes the event  generator such that derived event fileURL will now be non-nil
2. Removes reachability check for integration tests since being locally connected via LAN but not connected to the internet would cause the test disabling check to pass. Instead, we attempt an actual NSURLRequest to a WAN target and set the value based on the success of that request.
> Address GDT test issues

- GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
- GoogleDataTransport/GDTCORLibrary/GDTCORUploadPackage.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Unit/Helpers/GDTCCTEventGenerator.m
The header and API in question should be considered hidden. An alternative would be expose the API in the private header .
A race condition existed in the upload package itself--it should hand copies of itself and not self to prevent asynchronous mutation whilst a different queue is also executing an asynchronous mutation. One alternative would be to create mutable an immutable variants of the package. This could manifest as an EXC_BAD_ACCESS in GDTCCTPrioritizer.m
> Fix a couple of race conditions and module import of a private header

- Firebase/CoreDiagnostics/CHANGELOG.md
- Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
- GoogleDataTransportCCTSupport/CHANGELOG.md
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTNanopbHelpers.h
This reverts commit b41410d149a5ad4f6a46b2f3a0ca91c17637af3b.
The reason for reverting is that the original revert seems to have been a red herring.
> Revert "Revert "Address a few potential security issues (#5059)" (#5121)

- .travis.yml
Remove travis check stage in favor of the GHA version
It is now currently broken on travis because of missing `pip`:
From https://travis-ci.org/github/firebase/firebase-ios-sdk/jobs/666963230
```
$ pip install flake8
/Users/travis/.travis/functions: line 109: pip: command not found
The command "pip install flake8" failed and exited with 127 during .
```
> Remove travis check stage

- Firestore/core/src/firebase/firestore/util/log_stdio.cc
This is for consistency with [iOS](https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/Logger/GULLogger.m#L66) and [C++ RTDB](https://github.com/firebase/firebase-cpp-sdk/blob/master/database/src/include/firebase/database.h#L175).
> Change C++ default log level to `kLogLevelNotice`

- Firebase/InstanceID/FIRInstanceIDCheckinStore.m
Confirm the plist count is no longer needed. This might be legacy code form GCM.
> we no longer need to check the plist count for older version of library

- Firestore/core/include/firebase/firestore/firestore_errors.h
- Firestore/core/src/firebase/firestore/util/status_apple.mm
- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
- Firestore/core/test/firebase/firestore/util/status_apple_test.mm
Making it a scoped enumeration, coupled with the fact that `firebase::Future::error()` returns a plain `int`, imposes a lot of casting.
> Revert `Error` back to an unscoped enumeration

- FirebaseStorage.podspec
- FirebaseStorage/Tests/Integration/FIRStorageIntegrationTests.m
- FirebaseStorage/Tests/SwiftIntegration/StorageIntegration.swift
- scripts/build.sh
Ports the 25 [Storage Integration Tests](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseStorage/Tests/Integration/FIRStorageIntegrationTests.m) to Swift. The PR can be a basis for additional Swift integration tests and Swift API improvements.
The Swift tests are also added to a new testspec and the GHA CI.
The code is essentially a 1-1 translation from the Objective C. Any suggestions to make it more Swifty appreciated.
> Storage Integration Tests to Swift

- Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
Also, maybe I should resign from software engineering
From `man calloc`, which was not the source I used (dumb).
```
void *
calloc(size_t count, size_t size);
```
> Fix calloc calls, which had the argument order reversed

- Firebase/Database/Core/FRepo.m
- Firebase/Database/Core/FServerValues.h
- Firebase/Database/Core/FServerValues.m
- Firebase/Database/Core/FSyncTree.m
Based on fix https://github.com/firebase/firebase-js-sdk/pull/2499 to bug https://github.com/firebase/firebase-js-sdk/issues/2487
Micro-benchmarking showed that N writes in succession led to N^2 performance when calcuating the resolved write tree for those writes (thankfully only at the subpath in this SDK). This change matches the optimization in JS that mitigated a 20% performance regression.
> Change FServerValues to just-in-time read from SyncTrees.

- Firebase.podspec
- FirebaseABTesting.podspec
- FirebaseAuth.podspec
- FirebaseCore.podspec
- FirebaseDatabase.podspec
- FirebaseDynamicLinks.podspec
- FirebaseFirestore.podspec
- FirebaseFirestoreSwift.podspec
- FirebaseFunctions.podspec
- FirebaseInstallations.podspec
- FirebaseInstanceID.podspec
- FirebaseMessaging.podspec
- FirebaseRemoteConfig.podspec
- FirebaseStorage.podspec
Remove most platform references from podspec summaries and descriptions.
These haven't been kept up-to-date and are better documented by the podspec platform specifications themselves and the repo README.
> Remove platforms from podspec summaries

- Crashlytics/Protogen/nanopb/crashlytics.nanopb.c
- FirebaseCrashlytics.podspec
- GoogleDataTransport.podspec
- GoogleDataTransportCCTSupport.podspec
GoogleDataTransport >= 5.1.1
GoogleDataTransportCCTSupport >= 2.0.2
#no-changelog
> Update GDT dependencies for Crashlytics

- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
- GoogleDataTransport/GDTCORLibrary/GDTCORReachability.m
- GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORReachability_Private.h
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORReachability.h
- Wrap reachabilityRef and ReachabilityFlags in GDTCORPlatform
- Define reachabilityRef and ReachabilityFlags for watchOS and set default flag value equal to wifi only for uploader checking. Leave unknown for networkinfo populating in log event.
> Set networkReachabilityFlags on watchOS

- Crashlytics/Crashlytics/Settings/Models/FIRCLSApplicationIdentifierModel.m
The settings call is needed so the SDK knows that an app update needs to happen.
> Trigger settings call even when build version changes without the code changing

- Firebase/InstanceID/CHANGELOG.md
- Firebase/InstanceID/FIRInstanceID.m
This fixes crash if passing a nil handler
> add missing return when delete token handler is nil

- FirebaseStorageSwift/Sources/SwiftAPIExtension.swift
Follows recommended formatting from https://nshipster.com/swift-documentation/ and kept consistent with FirebaseFirestoreSwift.
Content is adapted from https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseStorage/Sources/Public/FIRStorageReference.h
Looks like this in Xcode:
> Add API docs for FirebaseStorageSwift

- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Sources/FIRStorageReference.m
This should fix an occasional flake I was seeing in [testUnauthenticatedSimpleGetDataTooSmall](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseStorageSwift/Tests/Integration/StorageIntegration.swift#L328) where the expectation was getting fulfilled twice.
> Only fail a StorageTask once

- FirebaseStorageSwift/Sources/SwiftAPIExtension.swift
- FirebaseStorageSwift/Tests/Integration/StorageIntegration.swift
Make the APIs that return a monitoring/management task `@discardableResult` to prevent the need for assignments to underscore when a task isn't needed.
This is comparable to [Firestore APIs like setData](https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Swift/Source/Codable/Transaction%2BWriteEncodable.swift#L54).
> Make APIs returning monitoring tasks discardable

- Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
- On-device symbolication happens upon next startup, not during crash. These files are unique because they end in `.symbolicated` instead of `.clsrecord`. We need to collect and upload these files for GDT in addition to the `.clsrecord` files
> Crashlytics collect on-device symbolication for GDT

- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTPrioritizerTest.m
EXC_BAD_ACCESS comes from ivar access of a nil object.
Fixes #5264
> Fix a possible crash in encoding when sharedInstance is nil

- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
- GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTPrioritizerTest.m
EXC_BAD_ACCESS comes from ivar access of a nil object.
Fixes #5264
> Fix a possible crash in encoding when sharedInstance is nil (#5267)

- Firestore/core/src/firebase/firestore/remote/remote_event.cc
Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/2847).
Curious to know if it is still worth it `reserve()` the vector ahead of time, even if we can't guarantee that it'll be fully filled.
> Only check for active targets in GetTargetIds

- FirebaseInAppMessaging.podspec
In #2312 you added InAppMessaging to the repo and [here][1] you check if this is running on simulator using `GoogleUtilities`.
This adds `GoogleUtilities` explicitly to `FirebaseInAppMessaging.podspec` fixing #5282
[1]: https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessaging/Sources/Runtime/FIRInAppMessaging%2BBootstrap.m#L105
> Explicitly state InAppMessaging's dependency on GoogleUtilities

- Firebase.podspec
- FirebaseFirestore.podspec
- Releases/Manifests/6.22.0.json
M68 Firestore includes a change to an internal header used by the
Firestore C++ SDK that isn't backwards compatible. Naming this 1.11.3
would allow older Firestore C++ installs for iOS to upgrade to this
version which would break them.
Numbering this 1.12.0 prevents automatic upgrades within the
patch-level.
> Bump Firestore to 1.12.0

- ZipBuilder/README.md
- ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
- ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
- ZipBuilder/Sources/ZipBuilder/main.swift
Fix #5287
- Handle new file structure of Swift module maps in Xcode 11.4
- Add `-buildDependencies false` option to skip building dependencies of requested pods
- Update README to help ZipBuilder users choose the right Xcode version
- Fixed a crash from bad URL construction when both `-outputDir` and `-zipPods` options were used
Xcode 11.4 adds a `Project` subdirectory to Swift module maps that needs to be similarly merged when constructing .xcframeworks.
The `-buildDependencies false` flag will be useful for those who want to build add-on's to the default zip or Carthage distributions without the time consuming building of all the transitive dependencies.
> Handle Xcode 11.4 changes to Swift module maps

- Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m
- Crashlytics/Crashlytics/Models/FIRCLSFileManager.h
- Crashlytics/Crashlytics/Models/FIRCLSFileManager.m
- Crashlytics/Crashlytics/Models/FIRCLSSettings.h
- Crashlytics/Crashlytics/Models/FIRCLSSettings.m
- Crashlytics/UnitTests/FIRCLSSettingsTests.m
- When collect_reports is false, Crashlytics currently doesn't start up at all. We want to continue to fetch settings in this situation, but never upload crash reports
> Collect reports refetch

- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
- Firestore/Example/Tests/SpecTests/json/collection_spec_test.json
- Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/SpecTests/json/orderby_spec_test.json
- Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
- Firestore/Example/Tests/SpecTests/json/query_spec_test.json
- Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
- Firestore/Example/Tests/SpecTests/json/resume_token_spec_test.json
- Firestore/Example/Tests/SpecTests/json/write_spec_test.json
This PR picks up changes to the spec tests.  Notable changes include:
- https://github.com/firebase/firebase-js-sdk/pull/2790, which renamed the "limboDocs" key in the JSON objects to "activeLimboDocs".
- https://github.com/firebase/firebase-js-sdk/pull/2843, which changed the JSON generation for spec tests to generate "stable" JSON, where the keys are always sorted.
This PR is a port of the same change in the Android SDK: https://github.com/firebase/firebase-android-sdk/pull/1401
> Update spec tests from changes in the firebase-js-sdk respository

- .travis.yml
All of the `pod lib lint` runs started failing yesterday on the travis Xcode 11.3 travis configs with ruby errors like https://travis-ci.org/github/firebase/firebase-ios-sdk/jobs/672106386
Backing up to Xcode 11.0 fixes the build.
#no-changelog
> Switch travis from Xcode 11.3 to 11.0

- FirebaseCore/Sources/Public/FIRApp.h
Currently it mentions that the calls are thread-safe. While technically true, `configure` should only be called from the main thread to ensure all SDKs are configured by the time they are used.
> Update comments on `configure` call.

- README.md
See badges at https://github.com/firebase/firebase-ios-sdk/tree/pb-gha-badges#firebase-ios-open-source-development
One approval and fyi for others should be sufficient for this one.
#no-changelog
> Update GHA badge list

- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Last night's zip build cron job failed because of a bug exposed by #5329 updating the `GoogleUtilities` version locally.  We were getting the podspec name from the podname without truncating subspec's from the podname.
Also fixed a warning from `pod install` if a subspec install was requested without a version along with a request to install the base spec with a version.
I also added a check to only allow `-buildDependencies false` option when `-zipPods` is used since it does not make sense (nor work) for Firebase product builds.
> Three ZipBuilder Fixes

- FirebaseInstallations/REQUIRED_FIREBASE_OPTIONS_IOS.md
Created public documentation that can be linked to from error messages thrown if client-side lenient format checks of Firebase options fail.
b/153238875
https://docs.google.com/document/d/1iuA_LsX650KVlrwS6bN-eVUUQIv_cgKmqMxI7lMGFao/
> Created REQUIRED_FIREBASE_OPTIONS_IOS.md

- GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m
- GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
Check for nil eventIDs in the encoder case and checks for nil before adding the event ID to a collection.
> More safely handle event IDs in migrations

- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTPrioritizer.h
- GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTPrioritizerTest.m
This effectively makes it impossible to access the event sets in an unsynchronized way.
Fixes #5312
> Remove accessors for prioritizer internals

- Example/Messaging/Sample/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme
- Example/Messaging/Sample/Sample/AppDelegate.swift
- Example/Messaging/Sample/Sample/ContentView.swift
- Example/Messaging/Sample/Sample/Identity.swift
- Example/Messaging/Sample/Sample/SceneDelegate.swift
- Firebase/InstanceID/FIRInstanceID.m
- Firebase/InstanceID/FIRInstanceIDConstants.h
- Firebase/InstanceID/FIRInstanceIDConstants.m
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingConstants.h
- Firebase/Messaging/FIRMessagingConstants.m
Fix #5338: When a token is deleted by calling `deleteToken` method, messaging doesn't trigger FIRMessagingRegistrationTokenRefreshedNotification notification or calling the FIRMessagingDelegate `messaging:didReceiveRegistrationToken:` method.
Hence the token parameter in the delegate API `messaging:didReceiveRegistrationToken:`should be nullable, a change we might need to get in the next breaking change API.
Update:
I also cleanup the code and realize IID send out two notifications  (kFIRInstanceIDDefaultGCMTokenNotification, kFIRInstanceIDTokenRefreshNotification) when fcm token is updated. Sometimes it calls one, while other time it calls the other. These two notifications are essentially doing the exactly the same thing. So I replaced one that is not in the public API of IID.
Note: I …
> fix an issue that delete token does not trigger token refresh notification or delegate

- Carthage.md
- FirebaseCore/CHANGELOG.md
- ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift
Fix #5276. Carthage can fail to install if two binary installs include the same framework. This PR factors Protobuf.framework out of the several bundles it was included in into a single Carthage bundle. 
The instructions are updated to describe when the new `FirebaseProtobufBinary.json` must now be included in the Cartfile.
> Workaround Carthage Protobuf parallel install issue

- FirebaseCore/CMakeLists.txt
- Firestore/Example/Benchmarks/remote_document_cache_benchmark.mm
- Firestore/Example/Tests/Integration/API/FIRListenerRegistrationTests.mm
- Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
- Firestore/Example/Tests/Integration/FSTSmokeTests.mm
- Firestore/Example/Tests/Util/FSTEventAccumulator.mm
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Source/API/FIRCollectionReference.mm
- Firestore/Source/API/FIRFieldPath.mm
- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/API/FIRFirestoreSettings.mm
- Firestore/Source/API/FIRGeoPoint.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/API/FIRTimestamp.m
- Firestore/Source/API/FSTFirestoreComponent.mm
- Firestore/Source/API/FSTUserDataConverter.mm
- Firestore/Source/CMakeLists.txt
- GoogleUtilities/CMakeLists.txt
- Interop/Auth/CMakeLists.txt
- Interop/CoreDiagnostics/CMakeLists.txt
- cmake/cc_rules.cmake
CMake has built-in support for building Framework bundles (briefly: bundles of libraries, associated headers, and resources) but this doesn't work well for our needs.
1. In CMake 3.5.1 (our earliest supported CMake version) it doesn't copy headers properly at build time.
2. Even up to CMake 3.15.5 (the current version I'm testing with), CMake doesn't handle link-line multiplicity correctly. CMake passes the static library location within the framework and this seems to cause the linker to mishandle Objective-C metaclass information resulting in duplicate symbols. Building with `-framework` flags works correctly but there's no way to convince CMake to build this way without considerable additional complexity.
Previously we partially worked around the latter problem by building some …
> Stop using built-in CMake Framework support

- Firestore/CHANGELOG.md
Also fix the version entry for the previous release. The last Firestore
release was 1.12.0, not 1.11.3.
> Update CHANGELOG for Firestore v1.12.1

- GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m
- GoogleDataTransport/GDTCORLibrary/GDTCORUploadPackage.m
- GoogleDataTransport/GDTCORLibrary/Private/GDTCORUploadPackage_Private.h
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORUploadPackage.h
- GoogleDataTransport/GDTCORTests/Unit/GDTCORUploadPackageTest.m
GDTCORUploadPackages would call targetToStorage in -initWithTarget. When this method was running during app terminate, this would cause a deadlock because calling targetToStorage is re-entrant while GDTCORRegistrar is sending lifecycle events to all the instances it's tracking.
NSTimer's invalidate method is also called whenever a package is completed, retried, or expired, without regard to the presence of a package handler.
A unit test is added to ensure that GDTCORUploadPackage's are not leaked by a retain
TSAN caught no issues
Fixes #5360
> Don't leak upload packages or deadlock on lifecycle events

- FirebaseRemoteConfig.podspec
- FirebaseRemoteConfig/CHANGELOG.md
- FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
- FirebaseRemoteConfig/Sources/RCNConfigSettings.m
- FirebaseRemoteConfig/Sources/RCNFetch.m
- FirebaseRemoteConfig/Tests/Sample/Podfile
- FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m
- FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m
Reverts firebase/firebase-ios-sdk#5159
Server side support is expected to be rolled out by the end of the week (b/152426175).
> Revert "Revert "Migrate from using IID SDK for Remote Config to the new FIS SDK""

- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/GDTCCTServiceExtension/Info.plist
- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/GDTCCTServiceExtension/NotificationService.swift
- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/GDTCCTWatchOSIndependentTestAppWatchKitExtension/ExtensionDelegate.swift
- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/GDTCCTWatchOSIndependentTestAppWatchKitExtension/GDTCCTWatchOSIndependentTestAppWatchKitExtension.entitlements
- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/GDTCCTWatchOSIndependentTestAppWatchKitExtension/InterfaceController.swift
- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/GDTCCTWatchOSIndependentTestAppWatchKitExtension/NotificationController.swift
- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/GDTCCTWatchOSTestApp.xcodeproj/project.pbxproj
- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/Podfile
- Add new target ServiceExtension for watchOS independent test app
- Integrate firebase cloud messaging into ServiceExtension to test remote notification
- Add generating high priority event in ServiceExtension to test GDT functionality in watch app extension.
> Add notification service extension target in gdtcct watch test app

- GoogleDataTransportCCTSupport.podspec
- GoogleDataTransportCCTSupport/CHANGELOG.md
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
- GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTPrioritizer.h
- GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTPrioritizerTest.m
Cherry picks #5352 onto release-6.22.0 for an ad-hoc release.
Increments GDTCCT patch version to v2.0.3
Fixes #5312
> Cherry pick: Remove accessors for prioritizer internals onto 6.22.0

- Firebase/Database/Public/FIRServerValue.h
> Fix typo in header comment

- .github/workflows/messaging.yml
Also do #5409 disabling for cron mac tests since they have the same keychain hang.
A better fix would be to fix or disable the specific tests that need the keychain.
> Always skip macos tests

- Firestore/README.md
- scripts/lldb/firestore.py
There are some particular pain points debugging Firestore today because contents of variables are obscured due to information hiding and shared representation techniques we use. Also, we use elements of the Abseil library to supplement what's available in the C++11 standard library.
Taken together, these make our default experience in LLDB and the Xcode debugger quite painful: getting the path of a document currently takes 5 clicks. This change pulls the document path into the summary line, making it available with no clicks.
Only a small handful of types are included (see individual commits).
When printing a `FIRDocumentSnapshot`, here was before:
```
(lldb) p *snapshot
(FIRDocumentSnapshot) $1 = {
NSObject = {
isa = FIRDocumentSnapshot
}
_snapshot = {
firestore_ = …
```
> Add LLDB type summaries for Firestore types

- GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
Put back the runtime checking for UIApplication sharedApplication, without which will cause compile error in ios extension.
> Fix SharedApplication unavailable in extension

- Firestore/CHANGELOG.md
- Firestore/core/src/remote/grpc_connection.cc
This matches the [Android](https://github.com/firebase/firebase-android-sdk/blob/205b52314bfc1b6bac44958e5411134d6003a85c/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreCallCredentials.java#L55) and [JS](https://github.com/firebase/firebase-js-sdk/blob/ed9a7be7d5f65aa37c0c478021b15bd18166a515/packages/firestore/src/platform_browser/webchannel_connection.ts#L96) SDKs and works around a limitation in gRPC, whereby it silently drops credentials if the connection isn't using TLS. In Firestore's case, developers routinely run against an emulator on the local host with TLS disabled (because requiring developers to provision certificates for local development is too onerous).
Fixes #5072.
> Manually specify the authorization header

- FirebaseAppDistribution/Sources/FIRAppDistribution.m
- FirebaseAppDistribution/Sources/FIRAppDistributionAuthPersistence.m
- FirebaseAppDistribution/Sources/FIRAppDistributionMachO.m
- FirebaseAppDistribution/Sources/FIRAppDistributionMachOSlice.m
- FirebaseAppDistribution/Sources/Private/FIRAppDistribution+Private.h
- FirebaseAppDistribution/Sources/Private/FIRAppDistributionAuthPersistence+Private.h
- FirebaseAppDistribution/Sources/Private/FIRAppDistributionMachO+Private.h
- FirebaseAppDistribution/Sources/Private/FIRAppDistributionMachOSlice+Private.h
* Remove NSLog statements from AuthPersistence
* Add error pointers to all calls into AuthPersistence
* Add logging to calling methods based on errors bubbled up but do not bubble errors up to the user
* Add TODO's for adding in the FIRLogger
* Running locally e2e - will post screen grab
* N/A
> Cleanup logging and error handling for initial auth persistence implementation

- Crashlytics/CHANGELOG.md
- Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
> Fix unchecked malloc

- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthProvider.m
- FirebaseAuth/Sources/SystemService/FIRAuthAppCredentialManager.m
- FirebaseAuth/Sources/SystemService/FIRAuthNotificationManager.m
- FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m
- FirebaseAuth/Sources/Utilities/FIRAuthDefaultUIDelegate.m
- FirebaseAuth/Sources/Utilities/FIRAuthWebView.m
Fix #5437
Suppress deprecation warnings in Auth when targeting iOS versions up to iOS 13.
> Suppress deprecation warnings in Auth

- Firestore/core/src/util/log_apple.mm
- Firestore/core/test/unit/FSTGoogleTestTests.mm
- Firestore/core/test/unit/util/bits_test.cc
- Firestore/core/test/unit/util/log_test.cc
Previously, a crash in a GoogleTest test would register as happening prior to XCTest being being fully set up, which would cause CI to report the error as a simulator startup failure. This made GoogleTest failures harder to diagnose, especially if it was due to flakes. Deferring error reporting until XCTest has started running prevents this error.
This makes it less likely we'll need to fall back on the backstop established in #4867.
Unfortunately, this makes it possible for other XCTest cases to precede FSTGoogleTestTests in the execution order, and the integration tests enable logging. This also fixes a test that broken when that happens.
Note that this was reviewed as a part of #4912, but that massive PR is flawed and I don't want to rescue it in-place. Instead this pulls out one of …
> Fix GoogleTest failure mechanism on CI

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Podfile
- scripts/sync_project.rb
The tests in this target are already covered by `Firestore_IntegrationTests_iOS` and also run on the other platforms through the other platform variants of this target.
Also remove an explicit override of `CLANG_WARN_COMMA` in the `Firestore_Example_macOS` target. This should have been cleaned up earlier--no other targets have this setting.
> Remove the Firestore_SwiftTests_iOS target

- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/GDTCCTServiceExtension/NotificationService.swift
- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/GDTCCTWatchOSCompanionTestAppExtension/InterfaceController.swift
- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/GDTCCTWatchOSIndependentTestAppWatchKitExtension/InterfaceController.swift
Change `customPrioritizationParams` to `customBytes`, according to https://github.com/firebase/firebase-ios-sdk/pull/4534
> Fix networkinfo population in GDTCCT watchos testapp events

- Carthage.md
fix #5472
Use brackets instead of parens for consistency
> Crashlytics correct Info.plist path for Carthage instructions

- scripts/install_prereqs.sh
#5301 broke the InstanceID cron tests that depended on the dash not being in the switch.
See https://travis-ci.org/github/firebase/firebase-ios-sdk/jobs/680094682
> Fix InstanceID cron build regression

- FirebaseMessaging.podspec
- FirebaseMessaging/Tests/IntegrationTests/FIRMessagingTokenRefreshTests.swift
The tests do not build for macos because of their use of NSNotification.
See https://travis-ci.org/github/firebase/firebase-ios-sdk/jobs/680094689
- ERROR | [OSX] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/FirebaseMessaging/Tests/IntegrationTests/FIRMessagingTokenRefreshTests.swift:61:10: error: type 'NSNotification.Name' has no member 'MessagingRegistrationTokenRefreshed'
> Turn off Messaging Swift Tests for macos

- Firestore/Protos/CMakeLists.txt
- Firestore/Protos/README.md
Fix the `generate_protos` alias to actually depend on the other targets. Without that, CMake considered these sources and then couldn't find them.
> Fix generate_protos

- .travis.yml
- CoreOnly/Tests/FirebasePodTest/Podfile
- Firebase.podspec
- FirebaseCore.podspec
- FirebaseCore/CHANGELOG.md
- FirebaseCoreDiagnostics.podspec
- FirebaseCrashlytics.podspec
- FirebaseFirestore.podspec
- FirebaseInAppMessaging.podspec
- FirebaseInAppMessaging/Tests/Integration/DefaultUITestApp/Podfile
- FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/Podfile
- Firestore/Example/Podfile
- GoogleDataTransportCCTSupport.podspec
- SymbolCollisionTest/Podfile
- scripts/build.sh
- scripts/localize_podfile.swift
- scripts/pod_lib_lint.rb
- scripts/test_catalyst.sh
Fix #5191 
See https://github.com/google/nanopb-podspec/pull/13 for a description of the new nanopb CocoaPods versioning scheme.
Updates test infrastructure to test preliminary versions of Analytics pod structure (but not functional) changes.
See #5455 for the corresponding no-op nanopb code gen changes.
Googlers - see also cl/308045137
#no-changelog
> Update nanopb to 0.3.9.5 (CocoaPods 1.30905.0)

- FirebaseFirestoreSwift.podspec
- Firestore/Swift/Source/Combine/DocumentReference+Combine.swift
This currently fails `pod lib lint` but seems to work in usage. Opened the PR so folks can continue to work on it today if desired, or I'll continue tomorrow.
> Initial dummy publisher for Combine experimentation.

- FirebaseAuth/Tests/Sample/Podfile
- FirebaseMessaging/Apps/Sample/Podfile
Fix build failures caused by needing pre-released nanopb and FirebaseAnalytics
#no-changelog
> Integration tests need SpecStaging

- GoogleDataTransportCCTSupport/GDTCCTWatchOSTestApp/Podfile
Fix GDTCCTWatchOSTestApp pod build failure caused by nanopb update https://github.com/firebase/firebase-ios-sdk/pull/4264, ref. https://github.com/firebase/firebase-ios-sdk/pull/5483
#no-changelog
> Update Podfile for GDTCCTWatchOSTestApp

- Firestore/Swift/Source/Combine/Query+Combine.swift
Proposal for a snapshot publisher.
Sample code:
Without Combine:
```swift
listenerRegistration = db.collection("books").addSnapshotListener { (querySnapshot, error) in
guard let documents = querySnapshot?.documents else {
print("No documents")
return
}
self.books = documents.compactMap { queryDocumentSnapshot -> Book? in
return try? queryDocumentSnapshot.data(as: Book.self)
}
}
```
With snapshot publisher:
```swift
db.collection("books")
.snapshotPublisher()
.map { querySnapshot in
return querySnapshot.documents.compactMap { queryDocumentSnapshot -> Book? in
return try? queryDocumentSnapshot.data(as: Book.self)
}
}
.replaceError(with: noBooks)
.assign(to: \.books, on: self)
```
I also added an extension to make mapping "easier":
```swift
db.collection("books") …
```
> Proposal for a snapshot publisher

- Firestore/Swift/Source/Combine/Query+Combine.swift
Here are two proposals for a publisher for Query.getDocuments().
There are two versions, one yielding `QuerySnapshot`s, the other one yielding `DocumentSnapshot`s.
Here is a code snippet using the traditional APIs:
```swift
db.collection("books").getDocuments { (querySnapshot, error) in
guard let documents = querySnapshot?.documents else {
print("No documents")
return
}
self.books = documents.compactMap { queryDocumentSnapshot -> Book? in
return try? queryDocumentSnapshot.data(as: Book.self)
}
}
```
Here is how this looks with the publisher yielding `QuerySnapshot`s:
```swift
let noBooks = [Book]()
db.collection("books").getDocuments()
.map { querySnapshot in
querySnapshot.documents.compactMap { (queryDocumentSnapshot) in
return try? queryDocumentSnapshot.data(as: Book.self)
}
} …
```
> Introduce Query.getDocument() publisher

- .github/workflows/auth.yml
- .github/workflows/core.yml
- .github/workflows/crashlytics.yml
- .github/workflows/datatransport.yml
- .github/workflows/dynamiclinks.yml
- .github/workflows/firebasepod.yml
- .github/workflows/firestore.yml
- .github/workflows/interop.yml
- .github/workflows/messaging.yml
- .github/workflows/storage.yml
- Gemfile
- Gemfile.lock
- scripts/test_catalyst.sh
And force GHA jobs to rerun when Gemfile changes Ruby infrastructure
Also make Catalyst tests build-only since they started failing on GHA after it updated from Xcode 11.3.1 to 11.4.1 last night. I can't repro locally:
```
+ xcodebuild test -configuration Debug -workspace gen/FirebaseStorage/FirebaseStorage.xcworkspace -scheme FirebaseStorage-Unit-unit ARCHS=x86_64h VALID_ARCHS=x86_64h SUPPORTS_MACCATALYST=YES -sdk macosx '-destination platform="OS X"' TARGETED_DEVICE_FAMILY=2 CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
+ xcpretty
xcodebuild: error: Failed to build workspace FirebaseStorage with scheme FirebaseStorage-Unit-unit.
Reason: Cannot test target “FirebaseStorage-Unit-unit” on “My Mac”: FirebaseStorage-Unit-unit does not support any of My Mac’s …
```
> Update pod gen version and address GHA Catalyst failures

- FirebaseAppDistribution.podspec
- FirebaseAppDistribution/Sources/FIRAppDistribution.m
- FirebaseAppDistribution/Sources/FIRAppDistributionAuthPersistence.m
- FirebaseAppDistribution/Sources/FIRAppDistributionKeychainUtility.m
- FirebaseAppDistribution/Sources/FIRAppDistributionMachO.m
- FirebaseAppDistribution/Sources/Private/FIRAppDistributionAuthPersistence+Private.h
- FirebaseAppDistribution/Sources/Private/FIRAppDistributionKeychainUtility+Private.h
- FirebaseAppDistribution/Sources/Private/FIRAppDistributionMachOSlice+Private.h
- FirebaseAppDistribution/Tests/Unit/FIRAppDistributionAuthPersistenceTests.m
- FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
* Add persistence to keychain with error handling
* Add a wrapper around the keychain interactions to facilitate unit testing
* Add unit tests for FIRAppDistributionAuthPersistence
* Added unit tests for FIRAppDistributionAuthPersistence
* Ran end to end locally to ensure that basic functionality works on device
> Persist auth information to the iOS keychain

- FirebaseMessaging/CHANGELOG.md
- FirebaseMessaging/Sources/FIRMessaging.m
- FirebaseMessaging/Sources/FIRMessagingClient.m
- FirebaseMessaging/Sources/FIRMessagingDataMessageManager.m
- FirebaseMessaging/Sources/FIRMessagingPubSub.m
- FirebaseMessaging/Sources/FIRMessagingTopicOperation.m
- FirebaseMessaging/Sources/NSError+FIRMessaging.h
- FirebaseMessaging/Sources/NSError+FIRMessaging.m
- FirebaseMessaging/Tests/UnitTests/FIRMessagingDataMessageManagerTest.m
- FirebaseMessaging/Tests/UnitTests/FIRMessagingServiceTest.m
Currently Messaging returns a NSError with an internal error code (integer) and they don't mean anything to developers and very hard to track the cause. e.g. when subscribing to a empty topic, it returns error code 8.
Add failure reason to each error to what went wrong.
Also remove unused the error code.
At some point we should deprecate the FIRMessagingErrorCode as many is unused and not very useful for developers to debug.
> Add failure reason to messaging NSError 

- Carthage.md
Set executable permission on `run` and `upload-symbols` after downloading Carthage versions
From usability feedback in #5527
> Set executable permission for Crashlytics scripts

- FirebaseCore/Sources/FIRBundleUtil.m
- FirebaseCore/Tests/Unit/FIRBundleUtilTest.m
> FIRApp bundle ID validation: allow exact match for extensions

- Gemfile.lock
Enable publishing interdependent pods without waits or manual intervention
#no-changelog
> Update cocoapods-trunk for --synchronous

- FirebaseAuth/Tests/Unit/FIRPhoneAuthProviderTests.m
From cl/309950830:
Change mix of OCMock2/OCMock3 syntax OCMStub([[foo ignoringNonObjectArgs] blah])... to straight OCMock3 syntax OCMStub([foo blah]).ignoringNonObjectArgs() in anticipation of OCMock preventing mix of syntax (https://github.com/erikdoe/ocmock/pull/391#issuecomment-623738479)
#no-changelog
> Pure OCMock3 syntax

- .github/workflows/functions.yml
- .github/workflows/inappmessaging.yml
The check job does not exist in the inappmessaging and functions jobs.
I'm not sure how these passed on the original PR.
They fail with 
"The workflow is not valid. The workflow must contain at least one job with no dependencies."
See https://github.com/firebase/firebase-ios-sdk/actions/runs/100454370
Fix Functions quickstart by adding custom URL setup from https://github.com/firebase/quickstart-ios/blob/master/scripts/install_prereqs/functions.sh
#no-changelog
> Delete non-existent needs

- FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
- FirebaseInAppMessaging/Tests/Unit/FIRIAMDisplayExecutorTests.m
Fix for internal bug #155959022 to not count clicks if an in-app messaging campaign has no URL to follow.
> Only log the URL follow event in messageClicked:withAction: if there's a URL to follow

- GoogleDataTransport.podspec
- GoogleDataTransport/CHANGELOG.md
- GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m
Calling the new GDTCORRootDirectory() function ensures that the directory needed is created before an attempt to write is made.
Fixes #5549
> Fixes the count file not being found

- FirebaseRemoteConfig/CHANGELOG.md
- FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
Fix #4740 
Insure that minimumFetchInterval setting is applied before fetching.  Otherwise there will be indeterministic behavior when trying to verify console changes in an app.
I've verified in a sample and will work on adding a unit test.
I'd like to get the review going since I'd like to get this fix in M71.
> Fix race condition between setting developer mode and config fetch

- Firestore/core/include/firebase/firestore/timestamp.h
It is a well-known issue that `<windows.h>` Windows header defines macros `min` and `max`, causing compilation errors for code that uses `std::min/max`, `std::numeric_limits::min/max`, etc While users may work around the issue by defining the `NOMINMAX` macro before including Windows headers, this PR adds some preprocessor directives to temporarily undefine these macros then restore their previous values. While the relevant pragmas are non-standard, they are implemented in all Firestore-supported compilers (Visual Studio, Clang, GCC).
> Make sure `timestamp.h` compiles even in presence of `min` and `max` macros

- Crashlytics/CHANGELOG.md
- Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
This will fix the crash in #5565 and hopefully give devs a breadcrumb of sorts to identify the null field.
> Fix NSNull crash in string encode

- FirebaseRemoteConfig/CHANGELOG.md
- FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
Migrate `fetchAndActivateWithCompletionHandler:` implementation from using the deprecated `activateFetched` API to the async `activateWithCompletionHandler:`
Working on integration tests, I was getting a deadlock in `activateFetched` so thought it would be good to move this forward.
> Migrate FetchAndActivate from deprecated implementation

- Firestore/core/src/util/async_queue.cc
- Firestore/core/test/unit/util/async_queue_test.cc
This helps avoid deadlock during shutdown.
> Avoid blocking access to the AsyncQueue during Dispose

- FirebaseABTesting/Tests/Integration/ABTQA.xcodeproj/project.pbxproj
- FirebaseABTesting/Tests/Integration/ABTQA.xcodeproj/xcshareddata/xcschemes/ABTQA.xcscheme
- FirebaseABTesting/Tests/Integration/ABTQA/AppDelegate.swift
- FirebaseABTesting/Tests/Integration/ABTQA/Assets.xcassets/AppIcon.appiconset/Contents.json
- FirebaseABTesting/Tests/Integration/ABTQA/Assets.xcassets/Contents.json
- FirebaseABTesting/Tests/Integration/ABTQA/Base.lproj/LaunchScreen.storyboard
- FirebaseABTesting/Tests/Integration/ABTQA/Base.lproj/Main.storyboard
- FirebaseABTesting/Tests/Integration/ABTQA/GoogleService-Info.plist
- FirebaseABTesting/Tests/Integration/ABTQA/Info.plist
- FirebaseABTesting/Tests/Integration/ABTQA/SceneDelegate.swift
- FirebaseABTesting/Tests/Integration/ABTQA/ViewController.swift
- FirebaseABTesting/Tests/Integration/Podfile
Adds an integration testing app that fetches an A/B tested parameter from Remote Config using development versions of the RC and ABT SDKs. There is also functionality to fire custom events to Analytics.
Links up to an existing Firebase project, but API keys in `GoogleService-Info.plist` are obfuscated.
#no-changelog
> Add end to end integration tests with RC+ABT

- FirebaseStorage/Tests/SwiftIntegration/StorageIntegration.swift
Adding several swift integration tests to FirebaseStorage
• Attempt to get metadata from an file without having permission
• Attempt to delete non-existing file
• Upload blank .jpg file to storage container
• Get file using [`write(toFile: completion:)`](https://github.com/firebase/firebase-ios-sdk/blob/b6cd99e30a9ad87d3f933bfef62ec4d7c0d78cd5/FirebaseStorage/Sources/Public/FIRStorageReference.h#L219) with a non-null `completion`
> Added StorageIntegration swift tests

- GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORStorageProtocol.h
- GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORStorageFake.m
- GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m
This could allow most singletons to no longer need NSCoding, they just store the individual fields they need with an appropriately unique key.
#no-changelog
> Provide an arbitrary data persistence mechanism on storage instances

- FirebaseInstallations/CHANGELOG.md
- FirebaseInstallations/Source/Library/Errors/FIRInstallationsHTTPError.m
- FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsHTTPErrorTests.m
- remove extra information from the log
- improve formatting
Example:
> FIS - make server error logs more readable

- FirebaseInstallations/CHANGELOG.md
- FirebaseInstallations/Source/Library/FIRInstallations.m
- FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m
> FIS: disable Auth token auto fetch

- Firestore/Source/Public/FIRFirestore.h
Update docs to match JS/Android (see [reasoning](https://github.com/firebase/firebase-ios-sdk/pull/5660#issue-421065592)).
Rewrapped lines to the 100 character mark for `addSnapshotsInSyncListener` and `terminateWithCompletion` as well.
> Update comment for addSnapshotsInSyncListener

- FirebaseRemoteConfig/CHANGELOG.md
- FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
- FirebaseRemoteConfig/Sources/Public/FIRRemoteConfig.h
- FirebaseRemoteConfig/Tests/FakeConsole/FakeConsoleTests.swift
- FirebaseRemoteConfig/Tests/SwiftAPI/APITests.swift
Adds an activate API with a changed parameter in the callback. It replaces a deprecated API that set an internal error if there was no change.
Fixes #3586 
The integration test infrastructure is implemented in #5633 
Googlers: See accompanying API proposal.
> Better completion callback for activate

- FirebaseRemoteConfig/Tests/Unit/RCNConfigSettingsTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNThrottlingTests.m
Fix imports in unit tests that have not yet been ported from v1 to v2
This addresses deleted file reference presubmit errors after copybara
> Import updates in unported tests

- FirebaseInAppMessaging/CHANGELOG.md
- FirebaseInAppMessaging/Sources/Runtime/FIRIAMRuntimeManager.m
We integrated FIS a few months ago, but never changed the log message that devs use to grab a token for testing FIAM on device.
> Change log message to reference FID instead of IID

- .travis.yml
All Quickstarts except Installations have been migrated to GHA - remove from travis.
> Update travis for GHA QS migration

- GoogleDataTransport/CHANGELOG.md
- GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m
- GoogleDataTransport/GDTCORLibrary/Public/GDTCORStorageProtocol.h
Needed to find storage instances internal _and_ external to this library.
#no-changelog
> Add a global function to get storage instances

- FirebaseStorage/Tests/Integration/FIRStorageIntegrationTests.m
- FirebaseStorage/Tests/SwiftIntegration/StorageIntegration.swift
- FirebaseStorageSwift/Tests/Integration/StorageIntegration.swift
This PR adds storage integration tests to test [the `callbackQueue` property of Firebase Storage](https://firebase.google.com/docs/reference/swift/firebasestorage/api/reference/Classes/Storage#callbackqueue).
**`FIRStorageIntegrationTests.m`**
• `testGetDataWithCustomCallbackQueue:`
**`SwiftIntegration/StorageIntegration.swift`**
•  `testSimpleGetDataWithCustomCallbackQueue()`
•  Removed unnecessary syntax in `testSimpleGetDataTooSmall()` 
#no-changelog
> Added storage integration tests for testing custom callback

- FirebaseDynamicLinks/CHANGELOG.md
- FirebaseDynamicLinks/Sources/FIRDynamicLinks.m
- FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m
Fix for b/154589338
Most of the times, when the app is cold started, we are making api calls to:
https://firebasedynamiclinks-ipv4.googleapis.com/v1
https://firebasedynamiclinks-ipv6.googleapis.com/v1
Until we get a successful response. But sometimes, if the device doesn’t have support for v6 endpoint and if the v4 endpoint doesn’t retrieve a valid dynamic link, it will return error. This mostly happens when user directly goes to App Store and installs an app which has fdl sdk integrated.
For dynamic links, we want the app to retrieve the pending dynamic link on the very first start of the app after install so that 3p developers can deeplink to a particular page in the app. If the pending links retrieval failed during the first start, there is no point in retrying the retrieval during …
> Fixing unwanted pending dynamic links checks on subsequent app restarts
