firebase/firebase-ios-sdk

AuthSamples/Samples.xcodeproj/project.pbxproj
Example/Auth/Tests/FIRSetAccountInfoResponseTests.m
Example/Auth/Tests/FIRSignUpNewUserResponseTests.m
Example/Auth/Tests/FIRVerifyAssertionResponseTests.m
Example/Auth/Tests/FIRVerifyClientResponseTests.m
Example/Auth/Tests/FIRVerifyCustomTokenResponseTests.m
Example/Auth/Tests/FIRVerifyPasswordResponseTests.m
Example/Auth/Tests/FIRVerifyPhoneNumberResponseTests.m

so the Auth Sample app no longer crashes on the settings view.

Adds GoogleService-Info_multi.plist to the Auth Sample

---

Firebase/Core/FIROptions.h

Be more explicit that the constructor is not a factory method.

Update FIROptions initializer documentation

---

Firebase/Core/FIROptions.m
FirebaseDev.podspec

Updating version for an upcoming release

---

AuthSamples/SwiftSample/ViewController.swift

Adds the "update phone number" option to swift sample app.
Fixes some minor typos.

Add update phone number action to swift app

---

AuthSamples/SwiftSample/ViewController.swift

Modifies sample app to remove warnings concerning APIs that were deprecated in iOS8.

Fixes warnings about APIs deprecated in iOS8

---

Example/Auth/Tests/FIRUserTests.m

Adds NSSecureCoding unit tests for FIRUser.

Adds NSSecureCoding unit tests for FIRUser

---

Firebase/Messaging/FIRMessaging.m
Firebase/Messaging/FIRMessagingConstants.h
Firebase/Messaging/FIRMessagingConstants.m

Hey @rsattar Please review this fix for #88

Fix Messaging doc

---

README.md
ROADMAP.md

Add ROADMAP.md

---

ROADMAP.md

Stablize -> Stabilize
Insure -> Ensure

Fix typos in ROADMAP.md

---

Firebase/Database/Persistence/FPruneForest.m

Fix comment in FPruneForest

---

AuthSamples/ApiTests/FirebaseAuthApiTests.m

This PR only modify the functional tests for Firebase Auth. https://github.com/firebase/firebase-ios-sdk/issues/117

Enables open-sourced functional tests run on other infrastructure.

---

Firebase/Core/FIROptions.m

Updating the version for the upcoming 4.0.4 release

Version update

---

Firebase/Auth/FirebaseAuth.podspec
FirebaseCommunity.podspec

Fix travis error introduced by #121

Fix macOS pod spec lint warning regression

---

Firebase/Auth/Source/Public/FIRAdditionalUserInfo.h
Firebase/Auth/Source/Public/FIRAuthDataResult.h

Fixes small reference documentation mistakes

---

AuthSamples/Sample/AppManager.h
AuthSamples/Sample/AppManager.m
AuthSamples/Sample/GoogleAuthProvider.m
AuthSamples/Sample/MainViewController.m
AuthSamples/Sample/SettingsViewController.m
AuthSamples/Samples.xcodeproj/project.pbxproj

Enables auth sample app to use multiple Firebase Apps.

---

Example/Core/Tests/FIRAppTest.m
Example/Shared/FIRSampleAppUtilities.m
Firebase/Core/FIRApp.m
Firebase/Core/FIRNetwork.m
Firebase/Core/FIRNetworkURLSession.m
Firebase/Core/FIROptions.m
Firebase/Core/FIRReachabilityChecker.m
Firebase/Core/FIRURLSchemeUtil.m
Firebase/Core/Private/FIRLogger.h
Firebase/Core/Public/FIRApp.h
Firebase/Core/Public/FIROptions.h

clang-format version 5.0.0 (tags/google/stable/2017-06-22)

Formatting updates based on the latest clang-format

---

Firebase/Auth/Source/Public/FIRActionCodeSettings.h

Add FIR_SWIFT_NAME for ActionCodeSettings.

---

README.md

See the comment at https://stackoverflow.com/a/45472783/556617

Improve confusing FirebaseCommunity pod usage instructions

---

README.md

An example of why waiting for travis is a good idea even for trivial PR's

remove trailing space

---

AuthSamples/Samples.xcodeproj/project.pbxproj
AuthSamples/SwiftSample/Stubs.swift
Firebase/Auth/Source/Public/FIRActionCodeSettings.h

Also fixes colon alignment in a header.

Adds Swift stub calls for Auth 4.1.0 new features to verify the API.

---

Firebase/Core/FIROptions.m

The PR will be resolved with a merge instead of a squash to keep the release branch hashes in the master branch history

Core should be 4.0.5

---

Example/Auth/Tests/FIRGetOOBConfirmationCodeResponseTests.m
Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/FIRAuthErrorUtils.h
Firebase/Auth/Source/FIRAuthErrorUtils.m
Firebase/Auth/Source/RPCs/FIRAuthBackend.m

Also fixed the public error name string for the error.

Handles MISSING_EMAIL error from server.

---

.travis.yml
AuthSamples/Samples.xcodeproj/project.pbxproj
Example/Firebase.xcodeproj/project.pbxproj

Update Firebase.xcodeproj with CocoaPods 1.3.1 perf improvements

---

Firebase/Auth/Source/Public/FIRActionCodeSettings.h
Firebase/Auth/Source/Public/FIRAuth.h
Firebase/Auth/Source/Public/FIRUser.h
Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeRequest.h

Makes minor improvements to the reference docs.

Small improvements to reference docs

---

Firebase/Database/Core/FPersistentConnection.m

This is for Google-internal issue https://b.corp.google.com/issues/64680856

Including bandwidth usage in error message for queries without indexes

---

AuthSamples/Samples.xcodeproj/project.pbxproj
Example/Auth/Tests/FIRAuthBackendRPCImplementationTests.m
Example/Auth/Tests/FIRFakeBackendRPCIssuer.m
Example/Auth/Tests/FIRGetProjectConfigRequestTests.m
Example/Auth/Tests/FIRGetProjectConfigResponseTests.m
Example/Firebase.xcodeproj/project.pbxproj
Firebase/Auth/Source/RPCs/FIRAuthBackend.h
Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Firebase/Auth/Source/RPCs/FIRAuthRPCRequest.h
Firebase/Auth/Source/RPCs/FIRGetProjectConfigRequest.h
Firebase/Auth/Source/RPCs/FIRGetProjectConfigRequest.m
Firebase/Auth/Source/RPCs/FIRGetProjectConfigResponse.h
Firebase/Auth/Source/RPCs/FIRGetProjectConfigResponse.m
Firebase/Auth/Source/RPCs/FIRIdentityToolkitRequest.m
Firebase/Auth/Source/RPCs/FIRSecureTokenRequest.m

Adds get Auth domain RPC and related unit tests.

Add get Auth domain RPC

---

Firebase/Auth/CHANGELOG.md
Firebase/Auth/Source/FIRAuth_Internal.h
Firebase/Auth/Source/Public/FIRAuth.h

Also move an unused public method into private header.

Updates Auth ChangeLog for the next release.

---

Firebase/Database/CHANGELOG.md

Update Changelog for 4.0.2 release.

---

FirebaseCommunity.podspec

Merge (not squash) release-4.1.1 branch back to master

Update FirebaseCommunity to 0.1.1

---

AuthSamples/Sample/MainViewController.m
Example/Auth/Tests/FIRApp+FIRAuthUnitTests.m
Example/Auth/Tests/FIRPhoneAuthProviderTests.m
Firebase/Auth/FirebaseAuth.podspec
Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/FIRAuthURLPresenter.m
Firebase/Auth/Source/FIRAuth_Internal.h
Firebase/Auth/Source/Public/FIRAuth.h
Firebase/Auth/Source/Public/FIRPhoneAuthProvider.h
Firebase/Auth/Source/RPCs/FIRAuthBackend.h
Firebase/Auth/Source/RPCs/FIRAuthBackend.m
FirebaseCommunity.podspec

Adds app verification alternative to verify phone number flow.

Adds app verification alternative

---

Firebase/Auth/Source/FIRAuthURLPresenter.m
Firebase/Auth/Source/FIRAuth_Internal.h
Firebase/Auth/Source/Public/FIRPhoneAuthProvider.h

Fixes Auth build when module is disabled

---

Firebase/Core/FIRAnalyticsConfiguration.m
Firebase/Core/FIRApp.m
Firebase/Core/FIROptions.m
Firebase/Core/Private/FIRLogger.h

FIRAnalyticsConfiguration.m - 88 
FIRApp.m - 208
FIROptions.m - 496
+ running style.sh on FIRLogger.h

Equivalent functionality changes to reduce FirebaseCore by 792 bytes

---

Example/Auth/Tests/FIRPhoneAuthProviderTests.m
Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
Firebase/Auth/Source/FIRAuthErrorUtils.h
Firebase/Auth/Source/FIRAuthErrorUtils.m
Firebase/Auth/Source/FIRAuthInternalErrors.h
Firebase/Auth/Source/Public/FIRAuthErrors.h

Adds error handling for errors returned from the response URL during a reCAPTCHA app verification flow.

ReCAPTCHA verification error handling

---

Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Firebase/Auth/Source/RPCs/FIRAuthRequestConfiguration.h

Adds internal method to FIRAuth which will be accessed within AuthUI via an extension.

Adds ability to track Firebase Auth UI per request

---

Example/Auth/Tests/FIRPhoneAuthProviderTests.m
Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m

Also rewrites phone number auth reCAPTCHA tests to work on all iOS versions.

Adds a check for custom scheme in plist for phone number auth reCAPTCHA.

---

Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m

Adds event ID validation to the verify phone number via reCAPTCHA flow.  Waiting for PR 256 to land before updating unit tests.

Adds event ID validation to verify phone number

---

Example/Auth/Sample/UserInfoViewController.m
Firebase/Auth/Source/FIRUserMetadata.h
Firebase/Auth/Source/FIRUser_Internal.h
Firebase/Auth/Source/Public/FIRUser.h
Firebase/Auth/Source/Public/FirebaseAuth.h

Removes user meta from public API

---

Example/Auth/Sample/MainViewController.m
Example/Auth/Sample/UserInfoViewController.m
Example/Auth/SwiftSample/Stubs.swift
Example/Auth/Tests/FIRUserTests.m
Firebase/Auth/Source/FIRUser.m
Firebase/Auth/Source/FIRUserMetadata.m
Firebase/Auth/Source/FIRUserMetadata_Internal.h

Also
- Adds Swift stubs for the new API.
- Shows the `isNewUser` bit in the sample app.

Saves user metadata in keychain.

---

Example/Auth/Tests/FIRPhoneAuthProviderTests.m
Firebase/Auth/Source/FIRAuthErrorUtils.m
Firebase/Auth/Source/FIRAuthInternalErrors.h
Firebase/Auth/Source/Public/FIRAuthErrors.h

Disambiguates known errors possibly returned by verifyPhoneNumber:UIDelegate:completion:

Disambiguates known errors from web context

---

Example/Auth/Tests/FIRAuthTests.m
Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/FIRAuth_Internal.h
Firebase/Auth/Source/FIRUser.m

It is also applied more consistently now, which fixes #249.

Simplifies logic to post auth state change notifications.

---

Firestore/Example/Tests/Integration/API/FIRDatabaseTests.m

This ports a missing test from Android and the Web.

Adding test for merge with server timestamp

---

.github/ISSUE_TEMPLATE.md

and consolidate "library"/"product" to "component"

Add Firestore to issue template

---

Firebase/Auth/Source/Public/FIRAuthErrors.h

Fixes reference docs for FIRAuthErrorUserInfoEmailKey.

Fixes reference docs

---

Example/Auth/Sample/MainViewController.m
Firebase/Auth/README.md

New user popup

---

Example/Auth/Sample/MainViewController.m

new user popup toggle

---

Firebase/Core/FIROptions.m
FirebaseCommunity.podspec

Update Core and Community versions for Firebase 4.4.0 release

---

README.md

Improvements based on feedback in #367

Clarify README for SDK development versus usage

---

Firebase/Core/FIRApp.m
Firebase/Core/Private/FIRAppInternal.h

This isn't referenced anywhere internally or externally. #381

Remove unused internal function.

---

Firebase/Auth/CHANGELOG.md
Firebase/Auth/FirebaseAuth.podspec

Only some internal cleanups were made, no API changes.

Updates the change log for Auth release 4.3.1

---

Example/Auth/SwiftSample/ViewController.swift

Updates the sign-in, reauth and link with credential methods on Swift Sample to use the recommended Auth Result paradigm.

Improve swift sample app

---

Firebase/Core/third_party/FIRAppEnvironmentUtil.m

Fixing a bug where isFromAppStore would return YES for TestFlight apps

Fixing AppStore detection

---

Firestore/Source/Remote/FSTDatastore.m

Port the logic from Android / web to delay backoff reset until the first successful write on the stream.
Unfortunately there's no test since we don't have a mechanism to verify backoff delays presently (and creating one and porting it to the other platforms doesn't seem like an optimal use of time).

b/67423356: Exponential backoff on writes should back off until the first successful write

---

Example/Messaging/Tests/FIRMessagingServiceTest.m

Corresponds with internal pr 174266938

Update messaging test for upcoming InstanceID changes

---

.travis.yml

- Update Xcode 8.3 to 9.1
- Disable open simulator line since not sure how to update and isn't needed for other projects
- Add allow-warnings for pod spec lint until #390 gets fixed

Update travis to Xcode 9.1

---

Example/Auth/Tests/FIRPhoneAuthProviderTests.m

Fixes code style

---

Firebase/Core/FIRLogger.m

I'm definitely open to suggestions on the actual argument being passed in.

Add argument for forcing STDERR output in FIRLogger.

---

Example/tvOSSample/Podfile
Firebase/Storage/FIRStorageUtils.m

Fix Storage compilation.

---

Example/tvOSSample/Podfile
Example/tvOSSample/tvOSSample.xcodeproj/project.pbxproj
Example/tvOSSample/tvOSSample/Base.lproj/Main.storyboard
Example/tvOSSample/tvOSSample/DatabaseViewController.swift

It's a sample app that allows you to increment or decrement a number by 1. Updates simultaneously across multiple Apple TVs!

Add Database sample app

---

Firebase/Messaging/FIRMessagingDataMessageManager.m

Sync with internal cl/175752797

Remove unused code from Messaging

---

Example/tvOSSample/tvOSSample.xcodeproj/project.pbxproj

Hopefully fixing an issue with Paul's build.

Hopefully fix the Xcode project.

---

Example/Auth/Sample/MainViewController.m
Example/Auth/Tests/FIRAuthTests.m
Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/Public/FIRAuth.h

Adds AuthDataResult to the "create user" action.

Add Auth Data Result to createUserWithEmail

---

Firebase/Core/FIROptions.m
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseDatabase.podspec
FirebaseFirestore.podspec
FirebaseMessaging.podspec
FirebaseStorage.podspec

cc: @OleksiyA @wilhuff @protocol86 @schmidt-sebastian

Update component versions for Firebase 4.7.0

---

README.md
patch/FirebaseAnalytics.h

And make the CocoaPods 1.4.0 requirement more visible

Instructions for static library interop with Analytics

---

FirebaseFirestore.podspec
Firestore/CHANGELOG.md
Firestore/Example/Podfile
Firestore/Source/Auth/FSTCredentialsProvider.m

We now use the internal core functionality instead. There should be no functionality changes due to this PR.
b/67450476

Remove dependency on FirebaseAuth

---

Firestore/Source/Public/FIRCollectionReference.h
Firestore/Source/Public/FIRDocumentReference.h
Firestore/Source/Public/FIRFirestore.h
Firestore/Source/Public/FIRWriteBatch.h

Clarify lack of guarantee in FIRWriteBatch completion

---

Firebase/Core/FIROptions.m
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseDatabase.podspec
FirebaseFirestore.podspec
FirebaseMessaging.podspec
FirebaseStorage.podspec
README.md

This PR should be MERGED not squashed

Release 4.7.0

---

Example/Podfile

Core is now 4.7.0

---

Firebase/Messaging/FIRMessaging.m
Firebase/Messaging/FIRMessagingContextManagerService.m
Firebase/Messaging/FIRMessagingRmq2PersistentStore.m

Fix FCM build warnings introduced in Xcode 9

---

Example/Core/Tests/FIRAppTest.m
Example/Core/Tests/FIRLoggerTest.m
Example/Core/Tests/FIROptionsTest.m
Firebase/Core/FIRApp.m

This is just running ./scripts/style.sh. Please merge as I am currently traveling.

Running scripts/style.sh

---

Firestore/CHANGELOG.md
Firestore/Example/SwiftBuildTest/main.swift
Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.m
Firestore/Source/API/FIRWriteBatch.m
Firestore/Source/Public/FIRWriteBatch.h

See b/69807713 and https://github.com/firebase/firebase-ios-sdk/issues/478
Added new test case.
See mini-proposal go/firwritebatchcommit

Revisit commit method in FIRWriteBatch

---

Firestore/Example/SwiftBuildTest/main.swift
Firestore/Source/API/FIRDocumentSnapshot.m
Firestore/Source/Public/FIRDocumentSnapshot.h

I missed these in the merge between the nullable and the SnapshotOptions PR.

Adding missing SnapshotOptions method

---

Example/Podfile
Firebase/Core/FIROptions.m
Firebase/Messaging/FIRMessaging.m
Firebase/Messaging/FIRMessagingContextManagerService.m
Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseDatabase.podspec
FirebaseFirestore.podspec
FirebaseMessaging.podspec
FirebaseStorage.podspec
Firestore/Example/Podfile

Release 4.8.0

---

Example/Auth/Tests/FIRVerifyPasswordRequestTest.m
Firebase/Auth/Source/RPCs/FIRCreateAuthURIResponse.m
Firebase/Auth/Source/RPCs/FIRDeleteAccountResponse.m
Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeResponse.m
Firebase/Auth/Source/RPCs/FIRResetPasswordResponse.m
Firebase/Auth/Source/RPCs/FIRSetAccountInfoResponse.m
Firebase/Auth/Source/RPCs/FIRSignUpNewUserResponse.m
Firebase/Auth/Source/RPCs/FIRVerifyAssertionResponse.m
Firebase/Auth/Source/RPCs/FIRVerifyCustomTokenResponse.m
Firebase/Auth/Source/RPCs/FIRVerifyPasswordResponse.m

Fixes indentation and removes unused imports.

Internal code clean up

---

FirebaseFirestore.podspec
Firestore/Example/Firestore.xcodeproj/project.pbxproj

* Add all .mm files in Firestore/core to the build (which matches
log_apple.mm).
* Exclude log_stdio.cc
* Add log_test.cc to the project

Use the log_apple.mm logger from C++ on iOS

---

Firebase/Core/FIRLogger.m

This is necessary for internal build system.

Add Private path to FIRVersion.h import

---

Firebase/Core/third_party/FIRAppEnvironmentUtil.h
Firebase/Core/third_party/FIRAppEnvironmentUtil.m
FirebaseCore.podspec
cmake/FindFirebaseCore.cmake

Remove FIRAppEnvironmentUtil's sharedApplication

---

Example/Auth/ApiTests/AuthCredentialsTemplate.h
Example/Auth/ApiTests/FirebaseAuthApiTests.m

Adds new API test to Firebase Auth.

Adds new API tests for Firebase Auth

---

Example/Core/Tests/FIRAppTest.m
Example/Core/Tests/FIROptionsTest.m
Firebase/Core/FIROptions.m
Firebase/Core/Public/FIROptions.h

Remove deprecated FIROptions constructor

---

.travis.yml

update Travis to Xcode 9.2

---

Example/Auth/Sample/MainViewController.m
Firebase/Auth/Source/FIRAuth.m

Adds AddtionalUserInfo (isNewUser) to phone number sign-in.

Adds AdditionalUserInfo to Phone Auth

---

Firebase/Core/FIRApp.m
Firebase/Core/FIRErrors.m
Firebase/Core/Private/FIRErrors.h

Delete unused private FIRCreateError

---

Example/Auth/Tests/FIRAuthTests.m
Firebase/Auth/Source/FIRAuth.m

Adds check for isNewUser to phone auth unit tests.

Amends phone auth unit tests

---

scripts/style.sh

Add a test-only option to style.sh
This can be used from a `.git/hooks/pre-commit` like
```
#!/bin/sh
#
./scripts/style.sh test-only
if [ $? -ne 0 ]
then 
echo "Commit rejected"
exit 1
fi
```

Add test-only option to style.sh

---

Example/Podfile
Firebase/Core/FIROptions.m
FirebaseDatabase.podspec
FirebaseFirestore.podspec
FirebaseStorage.podspec
Firestore/Example/Podfile

Updated the version numbers of pods which are being released in 4.8.1

Version bump for 4.8.1 Release

---

Firebase/Auth/CHANGELOG.md
Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/API/FIRQueryTests.m
Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
Firestore/Protos/FrameworkMaker.xcodeproj/project.pbxproj
Firestore/Protos/build-protos.sh
Firestore/Protos/objc/firestore/local/MaybeDocument.pbobjc.m
Firestore/Protos/objc/firestore/local/Mutation.pbobjc.m
Firestore/Protos/objc/firestore/local/Target.pbobjc.m
Firestore/Protos/objc/google/api/HTTP.pbobjc.m
Firestore/Protos/objc/google/firestore/v1beta1/Common.pbobjc.m
Firestore/Protos/objc/google/firestore/v1beta1/Document.pbobjc.m
Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbobjc.m
Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.h
Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.m
Firestore/Protos/objc/google/firestore/v1beta1/Query.pbobjc.m
Firestore/Protos/objc/google/firestore/v1beta1/Write.pbobjc.m
Firestore/Protos/objc/google/rpc/Status.pbobjc.m
Firestore/Protos/objc/google/type/Latlng.pbobjc.m
Firestore/Source/Local/FSTLocalDocumentsView.m

This is to revert the header import changes.

Merge master into 4.8.1

---

Firestore/core/src/firebase/firestore/model/field_value.cc

This really should have been a part of #678, sorry.

Use Comparator in FieldValue.

---

scripts/style.sh

This should fix the recent travis failures since config.h.in was pushed. Will squash/merge when travis goes green.

style.sh - output unformatted files in test-only and ignore generated config.h

---

Firebase/Storage/FIRStorageErrors.m

Fixing spelling in FIRStorageErrors

---

FirebaseFirestore.podspec

This is a fix for https://github.com/firebase/firebase-ios-sdk/issues/702

Properly publish Abseil sources as a part of the podspec

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/core/src/firebase/firestore/model/CMakeLists.txt
Firestore/core/src/firebase/firestore/model/database_id.cc
Firestore/core/src/firebase/firestore/model/database_id.h
Firestore/core/test/firebase/firestore/model/CMakeLists.txt
Firestore/core/test/firebase/firestore/model/database_id_test.cc

Part of the C++ migration.
Unit test
n/a

Firestore DatabaseId in C++

---

Example/Messaging/Tests/FIRMessagingServiceTest.m
Firebase/Messaging/FIRMessaging.m
Firebase/Messaging/FIRMessagingPubSub.h
Firebase/Messaging/FIRMessagingPubSub.m
Firebase/Messaging/FIRMessagingTopicOperation.m

Added functionality not exposed in public header yet. I would leave to next FCM SDK owner to expose this functionality (and follow any required review process).
Bugs:
72701086
us make Firebase APIs better, please propose …

[FCM] Add completion handler to subscribe/unsubscribe topic actions

---

Firestore/Source/Core/FSTFirestoreClient.mm

Fixes #745.
Let me know if I should add a test.

fix null block execution crash

---

FirebaseFirestore.podspec

We've been refactoring and the podspec didn't keep up
/cc @lukegeiger

Make sure Firestore/core/include is in FirebaseFirestore.podspec

---

Firebase/Auth/Source/FIRUser.m
Firebase/Auth/Source/Public/FIRUser.h

Fix firebaes typo

---

Firebase/Auth/CHANGELOG.md

Updates Changelog for Firebase Auth.

Updates version of Firebase Auth in Changelog

---

Example/Podfile
Firebase/Core/FIROptions.m
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseFirestore.podspec
FirebaseMessaging.podspec
Firestore/Example/Podfile

Version bumps for 4.9.0

---

Firestore/Example/Tests/Util/FSTHelpers.mm

vector reference invalidated after re-size. replaced with list.

fix flaky test

---

Firebase/Core/FIRConfiguration.m

Forgot to remove the implementation in #760 - sorry about that.

Remove deprecated implementation - fixes build.

---

Example/Core/Tests/FIRTestCase.m

Missed this as well in the breaking changes updates :(

Fixed Core test's missing constant.

---

Example/Core/Tests/FIROptionsTest.m

Actually fixes them this time, I swear.

Fixes FIROptions tests - again.

---

Example/Podfile
Firebase/Auth/CHANGELOG.md
Firebase/Core/FIROptions.m
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseFirestore.podspec
FirebaseMessaging.podspec
Firestore/Example/Podfile

Firebase 4.9.0 has published.  Update the versions in master.

Release 4.9.0

---

FirebaseFirestore.podspec

This is my proposed fix for your #799 PR

Don't expose abseil headers as public headers

---

Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt

Was failing the cmake build on linux.

Don't build firebase_firestore_testutil_apple on non-apple platforms.

---

Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/FIRAuthAPNSTokenManager.m
Firebase/Auth/Source/FIRAuthNotificationManager.m
Firebase/Auth/Source/FIRAuthSerialTaskQueue.m
Firebase/Auth/Source/FIRAuthURLPresenter.m
Firebase/Auth/Source/FIRSecureTokenService.m
Firebase/Auth/Source/FIRUser.m

Fixes clang warnings for Auth.

Fixes clang warnings for Auth

---

Firebase/Auth/CHANGELOG.md

Updates the Auth changelog in preparation for pending release.

Update changelog for release

---

.travis.yml
scripts/if_changed.sh

Parallelize the Travis run using build stages - part 2

---

.travis.yml
scripts/if_changed.sh

Not yet ready for review
https://docs.travis-ci.com/user/build-stages/
This will run source checks first (style, lint) and then if all pass,
kick off all platforms and builds in parallel.

Parallelize the Travis run using build stages

---

Firestore/core/src/firebase/firestore/remote/serializer.cc

Wraps the string encode method.

Partial wrapping of pb_ostream_t (pt2)

---

Firebase/Auth/CHANGELOG.md

Updates Changelog for 4.5.0 release

---

Firestore/core/src/firebase/firestore/remote/serializer.cc

Wraps encoding nested messages.

Partial wrapping of pb_ostream_t (pt3)

---

Firestore/CHANGELOG.md

Update CHANGELOG for Firestore v0.10.4

---

Carthage.md

Add instruction to delete Firebase.framework from link

---

Firestore/core/src/firebase/firestore/remote/serializer.cc

Wraps encoding of FieldValue's. At this point, raw pb_ostream_t structs
aren't used outside of Writer, except during creation of a Writer.

Partial wrapping of pb_ostream_t (pt5)

---

Example/Auth/Sample/MainViewController.m
Firebase/Auth/CHANGELOG.md
Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/FIRAuthProvider.m
Firebase/Auth/Source/Public/FIREmailAuthProvider.h
Firebase/Auth/Source/Public/FIRFacebookAuthProvider.h
Firebase/Auth/Source/Public/FIRGitHubAuthProvider.h
Firebase/Auth/Source/Public/FIRGoogleAuthProvider.h
Firebase/Auth/Source/Public/FIRPhoneAuthProvider.h
Firebase/Auth/Source/Public/FIRTwitterAuthProvider.h

- Adds missing constants for the sign-in method related to each auth provider.
- Updates the sample app.

Add sign in method constants

---

Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/src/firebase/firestore/remote/serializer.h

Move creation of pb_ostream_t's into Writer

---

scripts/style.sh

If we merge this it should fix the travis build.

Account for differences between find and git output

---

Firestore/core/src/firebase/firestore/immutable/CMakeLists.txt
Firestore/core/src/firebase/firestore/util/CMakeLists.txt
Firestore/core/src/firebase/firestore/util/firebase_assert.h
Firestore/core/src/firebase/firestore/util/status.cc
Firestore/core/src/firebase/firestore/util/status.h
Firestore/core/src/firebase/firestore/util/statusor.cc
Firestore/core/src/firebase/firestore/util/statusor.h
Firestore/core/src/firebase/firestore/util/statusor_internals.h
Firestore/core/test/firebase/firestore/util/CMakeLists.txt
Firestore/core/test/firebase/firestore/util/status_test.cc
Firestore/core/test/firebase/firestore/util/status_test_util.h
Firestore/core/test/firebase/firestore/util/statusor_test.cc

These were adapted from tensorflow

Add Status and StatusOr

---

scripts/style.sh

The preceeding ./ was removed from each file but the patterns were not updated. Update blacklist patterns accordingly.
test run.
n/a

fix style.sh

---

Firestore/CHANGELOG.md

backtick-escape code block

---

Firebase/Storage/Public/FIRStorageMetadata.h
Firestore/Source/Model/FSTDocumentKey.mm

As per go/deprecate-download-url.

Deprecate StorageMetadata.downloadURLs

---

Firestore/core/src/firebase/firestore/local/leveldb_transaction.cc
scripts/cpplint.py

This breaks the build under Xcode 8.2.
/cc @paulb777

Clean up usages of std::make_unique that crept in

---

Firebase/Core/FIRLogger.m
Firebase/Core/Private/FIRLogger.h

Add Logger Service for Swizzler

---

Example/Auth/Sample/MainViewController.m
Example/Auth/Tests/FIRUserTests.m
Firebase/Auth/Source/FIRAuthTokenResult.m
Firebase/Auth/Source/FIRAuthTokenResult_Internal.h
Firebase/Auth/Source/FIRUser.m
Firebase/Auth/Source/Public/FIRAuthTokenResult.h
Firebase/Auth/Source/Public/FIRUser.h
Firebase/Auth/Source/Public/FirebaseAuth.h

Adds client API to parse claims from the ID token.

Custom claims client api

---

Firestore/CHANGELOG.md

I looked through the recent changes and everything user-facing was already captured. Thanks team!

Updating Firestore Changelog for v0.11.0

---

Firebase/Storage/CHANGELOG.md

Adding release notes for v2.2.0

Updating Firebase Storage Changelog for v2.2.0

---

Firebase/Auth/CHANGELOG.md

Updates auth changelog in anticipation of next release.

Updates change log

---

Firebase/Auth/CHANGELOG.md
Firebase/Auth/Source/Public/FIRAuthTokenResult.h

Updates changelog in preparation for pending release.

Updates changelog

---

Example/Auth/Tests/FIRAuthTests.m
Firebase/Auth/Source/FIRAuth.m

Adds support for deep links in the email/link sign-in API.  This issue was brought forward by issue #974.
Amends unit tests.

Adds support for deep link to Email/Link sign-In

---

Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
Firestore/Example/Tests/Model/FSTMutationTests.mm
Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
Firestore/Example/Tests/Util/FSTHelpers.mm
Firestore/Source/API/FSTUserDataConverter.h
Firestore/Source/API/FSTUserDataConverter.mm
Firestore/Source/Core/FSTTransaction.h
Firestore/Source/Model/FSTMutation.h
Firestore/Source/Model/FSTMutation.mm
Firestore/Source/Remote/FSTSerializerBeta.mm
Firestore/core/src/firebase/firestore/model/CMakeLists.txt
Firestore/core/src/firebase/firestore/model/field_mask.h
Firestore/core/test/firebase/firestore/model/CMakeLists.txt
Firestore/core/test/firebase/firestore/model/field_mask_test.cc

This is part of the C++ migration.
unit and integration test pass.
n/a

port FieldMask to C++

---

Firebase/Auth/CHANGELOG.md

updates the changelog for pending release

---

Firebase/Messaging/Public/FIRMessaging.h

The description doesn't make sense any more once we expose to public.

Fix the comments for subscribe to topic

---

Firebase/Messaging/Public/FIRMessaging.h

Fix nullability warning with new Messaging API (#1029)

---

Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/src/firebase/firestore/remote/serializer.h
Firestore/core/src/firebase/firestore/util/status.h
Firestore/core/test/firebase/firestore/remote/serializer_test.cc

Deserializing not handled yet.
Note that the serializing case is fairly uninteresting, as assuming
valid input is passed in, there's no real reason why it should fail (and
if it does fail, it indicates a gross violation of our understanding of
the system.)

Add error handling for serializer (for serializing case only)

---

Firebase/Messaging/FIRMessagingPubSub.h
Firebase/Messaging/Public/FIRMessaging.h

add NS_ASSUME_NONNULL macros to messaging

---

Example/Auth/Sample/MainViewController.m
Firebase/Auth/Source/Public/FIRAuth.h

Minor enhancements to recently added sample app features.

Minor enhancements

---

Firebase/Database/Core/FPersistentConnection.m

This is the same fix as cr/144245929 (internal).
This PR prevents the "ConcurrentModificationExecption" by separating the iteration and
removal from outstandingPuts. The race can occur when new writes are added while
we are closing the connection.
Fixes: https://github.com/firebase/firebase-ios-sdk/issues/1019

Fixing concurrent modification when we cancel transactions

---

FirebaseCore.podspec

This allows the functionalities defined in that class being exposed.

exposing FIRAppEnvironmentUtil functionalities

---

Example/Auth/Tests/FIRUserTests.m
Example/Podfile
Firebase/Auth/CHANGELOG.md
Firebase/Auth/Source/FIRUser.m
Firebase/Core/FIROptions.m
FirebaseAuth.podspec
FirebaseCore.podspec
Firestore/Example/Podfile

Merging the Firebase 4.13.0 release branch into master.

Release 4.13.0

---

Example/Core/Tests/FIRAppEnvironmentUtilTest.m
Firebase/Core/third_party/FIRAppEnvironmentUtil.m

This change will include minor versions in the version number reporting.

Fix version number reporting for minor versions.

---

Firebase/Auth/Source/Public/FIRAuthTokenResult.h

Fix bad type annotation in claims

---

Firestore/Example/Tests/Util/FSTDispatchQueueTests.mm
Firestore/Example/Tests/Util/FSTEventAccumulator.mm
Firestore/Source/Model/FSTMutation.mm
Firestore/core/src/firebase/firestore/util/error_apple.h

Addresses items in issue #1143.

Clean up warnings in Firestore

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/Example/Podfile

The primary change is to the `Podfile`. The change to the `pbxproj` comes from running `pod update` after.

Prep Firestore Podfile for multiple platforms

---

Firestore/core/src/firebase/firestore/immutable/llrb_node.h
Firestore/core/src/firebase/firestore/immutable/sorted_map_iterator.h

* fix multiline comments by subst /* ... */ for //
* fix unreachable case in a switch statement

Fix build breakages under linux (gcc)

---

scripts/push-pods.sh

Add summary of outstanding issues to enable `pod repo push` and `pod lib lint` without warnings.
cc: @protocol86, @mcg, @schmidt-sebastian

pod lib lint status

---

Example/Auth/Tests/FIRUserTests.m
Firebase/Auth/Source/FIRUser.m

Adds fix for base64URL encoding of IDToken.

Fixes base64URL encoding

---

Firestore/core/src/firebase/firestore/model/CMakeLists.txt
Firestore/core/src/firebase/firestore/model/document.h
Firestore/core/src/firebase/firestore/model/field_value.cc
Firestore/core/src/firebase/firestore/model/field_value.h
Firestore/core/src/firebase/firestore/model/maybe_document.h
Firestore/core/test/firebase/firestore/model/field_value_test.cc

This is part of the #1135 to make PR smaller.

Update `FieldValue` For Porting `Mutation`s to C++

---

scripts/push-pods.sh

- Push to cpdc-internal
- Clear the cache so the right version of the version gets linted
- Update warning status

Updates for push-pods script

---

Example/Auth/Sample/MainViewController.m
Example/Auth/SwiftSample/ViewController.swift
Example/Auth/Tests/FIRAuthTests.m
Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/Public/FIRAuth.h

Adds new callback to creatUserWithEmailPAssword: which results in a breaking change.

Adds new callback to createUserWithEmail: API (breaking change)

---

Example/Auth/Sample/MainViewController.m
Example/Auth/SwiftSample/ViewController.swift
Example/Auth/Tests/FIRAuthTests.m
Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/FIRUser.m
Firebase/Auth/Source/Public/FIRAuth.h
Firebase/Auth/Source/Public/FIRUser.h
Functions/FirebaseFunctions/Public/FirebaseFunctions.h

Will merge and retag when https://travis-ci.org/firebase/firebase-ios-sdk/builds/371566951 goes green.

Three cherry picks for release-5.0.0

---

Example/Auth/Sample/SettingsViewController.m
Example/Auth/Tests/FIRPhoneAuthProviderTests.m
Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/FIRAuthSettings.m
Firebase/Auth/Source/Public/FIRAuth.h
Firebase/Auth/Source/Public/FIRAuthSettings.h
Firebase/Auth/Source/Public/FirebaseAuth.h
Firebase/Auth/Source/RPCs/FIRAuthBackend.m

Adds phone auth testing. (disableAppVerification) (#1192)

Cherry pick #1192 to release-5.0.0 

---

Example/Core/Tests/FIRLoggerTest.m
Firebase/Core/FIRLogger.m
Firebase/Core/Private/FIRLogger.h

It will be added back in at a later date.

Remove logging count for this release.

---

Firebase/Auth/Source/FIRAuthErrorUtils.m

Fixes typo: recieve -> receive

Fixes typo in public facing error message

---

Firestore/Source/Core/FSTFirestoreClient.mm

This was causing Travis to fail the style lint check.

Fix Firestore style issue.

---

Example/Firebase.xcodeproj/project.pbxproj

Fix #1224 for Firebase build and get increased test coverage.

Add -all_load to Firebase unit test runs

---

Example/Podfile
Firestore/Example/Podfile

Disable pre-release repos in advance of merging release-5.0.0 branch to master.

Disable pre-release repos

---

Example/Auth/ApiTests/FirebaseAuthApiTests.m

Fixes API tests to accommodate breaking changes

Fixes API tests for breaking changes

---

Firebase/Auth/CHANGELOG.md

Please let me know if there's anything I missed.

Update unreleased changes in CHANGELOG.

---

Firestore/core/test/firebase/firestore/util/executor_test.cc

There were several public member functions in Executor interface that weren't exercised in unit tests.

Firestore C++: add missing tests for Executor

---

Firebase/Core/FIRLogger.m
Firebase/Core/FIRVersion.m
Firebase/Core/Private/FIRVersion.h
Firestore/Source/API/FIRFirestoreVersion.h
Firestore/Source/API/FIRFirestoreVersion.mm
Firestore/Source/Remote/FSTDatastore.mm

cherry-pick #1223 for 5.0.1 release

Eliminate duplicate symbol in CocoaPods -all_load build (#1223)

---

Example/Core/Tests/FIRLoggerTest.m
Firebase/Core/FIRLogger.m
Firebase/Core/Private/FIRLogger.h

cherry pick #1263 to 5.0.1 to keep FirebaseCore consistent across repos.

Add MLKit to FIRLogger constants. (#1263)

---

Firestore/core/src/firebase/firestore/nanopb/reader.h
Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/src/firebase/firestore/remote/serializer.h
Firestore/core/test/firebase/firestore/remote/serializer_test.cc

Still TODO:
- non-empty
- NoDocument
- ErrorHandling

 [De]serialize empty Document instances

---

Firestore/core/src/firebase/firestore/remote/serializer.cc

Mostly to make existing methods a bit more general to support followup
PR (which will allow encoding/decoding documents with contents.)

Refactoring serializer.cc

---

Firestore/core/src/firebase/firestore/geo_point.cc
Firestore/core/src/firebase/firestore/remote/serializer.cc

There are codes not build internally. This is a fix upstream.

fix build for Firestore copybara import

---

Firebase/Messaging/FIRMessaging.m
Firebase/Messaging/FIRMessagingContextManagerService.m
Firebase/Messaging/FIRMessagingReceiver.m

Adding "-Wdeprecated-declarations" to remove the deprecation warning.

add macro to remove deprecated warning

---

Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/test/firebase/firestore/remote/serializer_test.cc

Still TODO:
- NoDocument
- ErrorHandling

[De]serialize non-empty Document instances

---

Firestore/core/test/firebase/firestore/remote/serializer_test.cc

Roughly s/google::firebase::v1beta1/v1beta1/g

Add namespace alias for v1beta1

---

Firebase/Core/FIRApp.m

Cherry-picking a change from master.

Add a constant for the Functions service.

---

Firestore/core/include/firebase/firestore/CMakeLists.txt
Firestore/core/include/firebase/firestore/collection_reference.h
Firestore/core/include/firebase/firestore/document_change.h
Firestore/core/include/firebase/firestore/document_reference.h
Firestore/core/include/firebase/firestore/document_snapshot.h
Firestore/core/include/firebase/firestore/event_listener.h
Firestore/core/include/firebase/firestore/field_path.h
Firestore/core/include/firebase/firestore/field_value.h
Firestore/core/include/firebase/firestore/firestore.h
Firestore/core/include/firebase/firestore/firestore_errors.h
Firestore/core/include/firebase/firestore/listener_registration.h
Firestore/core/include/firebase/firestore/query.h
Firestore/core/include/firebase/firestore/query_snapshot.h
Firestore/core/include/firebase/firestore/set_options.h
Firestore/core/include/firebase/firestore/settings.h
Firestore/core/include/firebase/firestore/snapshot_metadata.h
Firestore/core/include/firebase/firestore/transaction.h
Firestore/core/include/firebase/firestore/write_batch.h

- 198063502 Address comment upstream. by zxu <zxu>
- 197942352 Fix style upstream and fix destination depot in copybara. by zxu <zxu>
- 197925542 Fix headers with change from GitHub, see the current diff... by zxu <zxu>
- 197922012 Implement ListenerRegistration::Remove(). by zxu <zxu>
- 197713382 Implement more on listener class and implement ListenerRe... by zxu <zxu>
- 196551381 Implement more on listener class and implement the Docume... by zxu <zxu>
- 196276752 Implement the SnapshotMetadata with inline methods and (n... by zxu <zxu>
- 195841793 Implement the wrapper class for callback (EventListener). by zxu <zxu>
- 194112388 Add Android-Wrapper for DocumentReference's non-callback ... by zxu <zxu>
- 192445183 Add Android-Wrapper for Firestore's remaining methods. by zxu <zxu>
- …

Firestore project: Import of API interfaces.

---

Example/Podfile
Firebase/Core/FIRApp.m
Firebase/Core/FIROptions.m
Firebase/Messaging/FIRMessaging.m
FirebaseCore.podspec
FirebaseDatabase.podspec
FirebaseFirestore.podspec
FirebaseMessaging.podspec
Firestore/Example/Podfile
scripts/push-pods.sh
scripts/update-tags.sh

Merging the release branch into master.

Release 5.1.0

---

Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/FIRAuthAppDelegateProxy.m
Firebase/Auth/Source/FIRAuthDefaultUIDelegate.m

Checks for an App Extension before calling `[UIApplication sharedApplication]`.

App extension check

---

Firebase/Auth/CHANGELOG.md
FirebaseAuth.podspec

Should be cherry picked along with #1358 to release-5.2.0

Changelog for FirebaseAuth 5.0.1

---

Firestore/core/src/firebase/firestore/util/CMakeLists.txt
Firestore/core/src/firebase/firestore/util/string_util.h
Firestore/core/test/firebase/firestore/util/CMakeLists.txt

Cleans up a few minor things I noticed while doing other work.

Build cleanup

---

Firestore/CHANGELOG.md

These releases had no user visible changes.

Update changelog for 0.12.1 and 0.12.3

---

Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_FuzzTests_iOS.xcscheme

This change shows up every time I click "Run Tests" in XCode. I'm inclined to just commit it.

Adding AppCode schema for Fuzzer tests

---

Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
Firestore/Example/Tests/SpecTests/json/listen_spec_test.json

This adds the spec tests for https://github.com/firebase/firebase-ios-sdk/pull/1379
#1379 needs to be merged for these to pass. This PR is intended to reduce the size of the parent PR.

Adding EventAggregator spec tests

---

Firebase/Core/FIRLogger.m

Disable sanitizer race condition error

---

Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_FuzzTests_iOS.xcscheme
Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
Firestore/Example/Tests/Core/FSTViewTests.mm
Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
Firestore/Example/Tests/Util/FSTHelpers.h
Firestore/Example/Tests/Util/FSTHelpers.mm
Firestore/Source/Core/FSTSyncEngine.mm
Firestore/Source/Core/FSTView.mm
Firestore/Source/Local/FSTLocalStore.mm
Firestore/Source/Remote/FSTRemoteEvent.h
Firestore/Source/Remote/FSTRemoteEvent.mm
Firestore/Source/Remote/FSTRemoteStore.h
Firestore/Source/Remote/FSTRemoteStore.mm
Firestore/Source/Remote/FSTWatchChange.mm

This combines https://github.com/firebase/firebase-ios-sdk/pull/1379 & https://github.com/firebase/firebase-ios-sdk/pull/1380

 Merge: Refactor Remote Event

---

Carthage.md

This is discussed in [issue 1006](https://github.com/firebase/firebase-ios-sdk/issues/1006).

Added comment about Carthage build phase

---

Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
Firestore/Example/Tests/Local/FSTLevelDBTransactionTests.mm
Firestore/Source/Local/FSTLevelDB.h
Firestore/Source/Local/FSTLevelDB.mm
Firestore/Source/Local/FSTLevelDBMutationQueue.h
Firestore/Source/Local/FSTLevelDBMutationQueue.mm
Firestore/Source/Local/FSTLevelDBQueryCache.h
Firestore/Source/Local/FSTLevelDBQueryCache.mm
Firestore/core/src/firebase/firestore/local/CMakeLists.txt

Fix a few minor issues encountered while doing other LevelDB work.

Minor LevelDB cleanups

---

FirebaseFirestore.podspec
Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/Example/ProtobufCpp.podspec
Firestore/Source/Remote/FSTDatastore.mm
scripts/check_test_inclusion.py
scripts/sync_project.rb

This is the changes I requested against #1343 in PR form. Sorry for the delay.

Fixups to rsgowman/protobuf_cpp

---

Example/Messaging/Tests/FIRMessagingPubSubTest.m
Firebase/Messaging/FIRMessaging.m
Firebase/Messaging/FIRMessagingPubSub.h
Firebase/Messaging/FIRMessagingPubSub.m

Fix the issue https://github.com/firebase/firebase-ios-sdk/issues/1397

Corrected the deprecation warning when subscribing to or  unsubscribing from a topic

---

Example/Auth/Tests/FIRUserTests.m
Firebase/Auth/CHANGELOG.md
Firebase/Auth/Source/FIRUser.m

Promote users to non-anonymous status even when linking account w/o pw

---

Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm

I've added a bunch of helpers and some comments to the tests. Hopefully this is a little more clear. 
The final test is still large. My intention was to have something that exercised many of the cases together in addition to the smaller tests that exercise smaller scenarios. However, if you think it's an issue I can probably break it up into a 2-3 smaller tests.
There are still 2 tests that add multiple targets in a single transaction. One of them verifies that if we collect more than the number of targets added, we get those targets plus whatever is next. The other verifies that if we collect less than the number of targets added, we don't get anything additional. The large tests that exercise more typical usage do not include multiple targets in a single transaction.

Clean up LRU tests

---

Firebase/Database/Api/FIRDatabaseQuery.m
Firebase/Database/Persistence/FLevelDBStorageEngine.m
Firebase/Database/Snapshot/FIndexedNode.m

Fix undefined behavior sanitizer issues in RTDB

---

Firebase/Auth/CHANGELOG.md
Firebase/Auth/Source/FIRUser.m

Fix bad JWT parsing

---

Firebase/Messaging/FIRMessaging.m
Firebase/Messaging/FIRMessagingConnection.h
Firebase/Messaging/FIRMessagingConnection.m
Firebase/Messaging/FIRMessagingSecureSocket.m

Remove the heartbeat logic that is only used by test app.

Remove heartbeat timestamp

---

Example/Core/Tests/FIRNetworkTest.m
Example/Firebase.xcodeproj/xcshareddata/xcschemes/AllUnitTests_iOS.xcscheme

Turning on the sanitizers in #1447 made the tests too flaky on Travis.

Disable sanitizers

---

Firestore/Source/Remote/FSTOnlineStateTracker.h
Firestore/Source/Remote/FSTOnlineStateTracker.mm
Firestore/Source/Remote/FSTRemoteStore.mm

Port of https://github.com/firebase/firebase-js-sdk/pull/864

Improves "Could not reach Firestore backend." log message.

---

Firestore/CMakeLists.txt
Firestore/core/test/firebase/firestore/util/CMakeLists.txt
Firestore/third_party/abseil-cpp/CMakeLists.txt
cmake/FindGMock.cmake
cmake/external/googletest.cmake

Also add FindGMock to Find gmock after installation

Install googletest during CMake build

---

Firebase/Messaging/CHANGELOG.md

[Obligatory](https://media.giphy.com/media/PJoLp4gDIqjYs/giphy.gif)

Change 2015 to 2018 in CHANGELOG

---

Firestore/CHANGELOG.md
Firestore/Example/SwiftBuildTest/main.swift
Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
Firestore/Source/API/FIRFieldValue+Internal.h
Firestore/Source/API/FIRQuery+Internal.h
Firestore/Source/Public/FIRFieldValue.h
Firestore/Source/Public/FIRQuery.h

Also remove test code that was combining multiple array contains
queries since those were disallowed in
https://github.com/firebase/firebase-ios-sdk/commit/0ec836f9ca71b27fa54a11ae9e07e60b8c5cc002

Expose array transforms and array contains queries.

---

.travis.yml
Firestore/CHANGELOG.md
Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests_iOS.xcscheme
Firestore/core/src/firebase/firestore/local/local_serializer.cc
Firestore/core/test/firebase/firestore/remote/serializer_test.cc
scripts/build.sh

This will initially fail to verify that #1517 can be detected in CI.
Note: not yet ready for review.

Fix Firestore when compiled with Xcode 8.3

---

Firestore/core/src/firebase/firestore/core/CMakeLists.txt
Firestore/core/src/firebase/firestore/core/filter.cc
Firestore/core/src/firebase/firestore/core/filter.h
Firestore/core/src/firebase/firestore/core/query.cc
Firestore/core/src/firebase/firestore/core/query.h
Firestore/core/src/firebase/firestore/core/relation_filter.cc
Firestore/core/src/firebase/firestore/core/relation_filter.h
Firestore/core/src/firebase/firestore/model/field_value.cc
Firestore/core/src/firebase/firestore/model/field_value.h
Firestore/core/test/firebase/firestore/core/query_test.cc
Firestore/core/test/firebase/firestore/testutil/testutil.h

And RelationFilter subclass.
Used to implement the next step in core::Query.

 Initial (incomplete) implementation of f:f:core::Filter

---

Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
Firestore/Source/Local/FSTLocalDocumentsView.mm

... and clean up an error it exposes.

Remove the exclusive tag from the Firestore spec tests

---

Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
Firestore/Source/Local/FSTLocalStore.mm

Port of firebase/firebase-js-sdk#1015
Addresses #1548.

Allow remote updates from watch to heal a cache with synthesized deletes in it

---

Firestore/Source/Local/FSTQueryData.mm

Include sequence number in FSTQueryData hash and isEqual

---

Carthage.md

This addresses missing documentation identified in https://github.com/firebase/firebase-ios-sdk/issues/1571
Strictly a documentation change, but I'd love any feedback so the wording is helpful and informative to future users.
_Does not apply_

Mention additional libraries may be necessary for Carthage installs

---

Firestore/Example/Tests/Local/FSTLevelDBLRUGarbageCollectorTests.mm
scripts/cpplint.py
scripts/lint.sh

fix import pattern and add a presubmit check

fix import pattern

---

scripts/build.sh

* Run fuzz testing with `FUZZING_TARGET="NONE"` to compile only and do not run fuzzing.

Add Fuzz Test to travis Firestore-iOS-xcodebuild

---

Firestore/CHANGELOG.md

Realized I forgot a changelog entry. :-/

Add changelog entry for delete WriteResult fix (d9f116).

---

Firebase/Core/FIRApp.m

Address https://github.com/firebase/firebase-ios-sdk/issues/10#issuecomment-408879743

Don't log warning about Analytics for tvOS or macOS

---

Firebase/Core/FIROptions.m
FirebaseCore.podspec
FirebaseFirestore.podspec
Releases/Manifests/5.6.0.json

Prepare 5.6.0 Firebase release

Add 5.6 json

---

Firebase/Core/FIROptions.m
FirebaseCore.podspec
FirebaseFirestore.podspec

This was unintentional and should be reverted immediately.

Revert version bump from #1657

---

.travis.yml

See https://docs.travis-ci.com/user/reference/osx/#os-x-version

Bump travis to Xcode 9.4.1

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.mm
Firestore/core/src/firebase/firestore/util/CMakeLists.txt
Firestore/core/src/firebase/firestore/util/filesystem.h
Firestore/core/src/firebase/firestore/util/filesystem_apple.mm
Firestore/core/test/firebase/firestore/util/CMakeLists.txt
Firestore/core/test/firebase/firestore/util/filesystem_test.cc

Note that this is not yet portable beyond Apple platforms, but it's also not yet linked into anything beyond Xcode and CMake tests so that's not required yet.

Initial filesystem implementation

---

Firestore/Example/FuzzTests/FuzzingTargets/FSTFuzzTestFieldPath.mm

Fuzz test `pathWithDotSeparatedString`.

Fuzz test internal method in FIRFieldPath

---

.travis.yml
scripts/pod_lib_lint.sh

Address recent network flakiness in travis's pod lib lint runs

Add retry for travis pod lib lint

---

Firestore/Example/FuzzTests/FuzzingResources/LevelDb/leveldb.dictionary
Firestore/fuzzing/CMakeLists.txt
Firestore/fuzzing/leveldb_fuzzer.cc

* Test creating LevelDB key objects.

Adding Fuzzing Test Target LevelDb

---

Example/Podfile
Firebase/Core/FIROptions.m
FirebaseCore.podspec
FirebaseFirestore.podspec
Firestore/Example/Podfile

Update versions for Release 5.6.0

---

.opensource/project.json

Add .opensource

---

Firebase/Storage/CHANGELOG.md

Update Changelog for 3.0.1 Storage Release

Update Changelog for 3.0.1 Storage Release

---

.opensource/project.json

Also removed the comments since they look bad in the GitHub UI.

Remove bad trailing comma

---

Firebase/Messaging/FIRMessagingDataMessageManager.h
Firebase/Messaging/FIRMessagingDataMessageManager.m
Firebase/Messaging/FIRMessagingRmq2PersistentStore.m

Fixing Messaging part of #1735

Fix analyze issues in Messaging

---

Firebase/Auth/Source/FIRAuthDataResult.m
Firebase/Auth/Source/FIRAuthDataResult_Internal.h
Firebase/Auth/Source/FIRAuthDefaultUIDelegate.m
Firebase/Auth/Source/FIRAuthErrorUtils.m
Firebase/Auth/Source/FIRAuthWebUtils.h
Firebase/Auth/Source/FIRAuthWebUtils.m
Firebase/Auth/Source/RPCs/FIRAuthBackend.h
Firebase/Auth/Source/RPCs/FIRAuthBackend.m

Fix analyze issus in Auth. See #1735

Fix analyze issues in Auth

---

Firebase/Database/Core/FPersistentConnection.m
Firebase/Database/FIRDatabaseReference.m
Firebase/Database/Public/FIRDatabaseReference.h
Firebase/Database/third_party/FImmutableSortedDictionary/FImmutableSortedDictionary/FLLRBEmptyNode.m
Firebase/Database/third_party/FImmutableSortedDictionary/FImmutableSortedDictionary/FLLRBValueNode.m
Firebase/Database/third_party/SocketRocket/FSRWebSocket.m
Firebase/Storage/FIRStorage.m
Firebase/Storage/FIRStorageObservableTask.m

Fix analyze issues in Storage and Database. See #1735

Fix analyze issues in Storage and Database

---

Example/Storage/Tests/Unit/FIRStoragePathTests.m
Firebase/Storage/FIRStorageDeleteTask.m
Firebase/Storage/FIRStorageDownloadTask.m
Firebase/Storage/FIRStorageGetDownloadURLTask.m
Firebase/Storage/FIRStorageGetMetadataTask.m
Firebase/Storage/FIRStorageUpdateMetadataTask.m
Firebase/Storage/FIRStorageUploadTask.m
Firebase/Storage/Private/FIRStorageTask_Private.h

Feel free to merge after approval

Revert "Merge pull request #1721 from morganchen12/assign"

---

Firebase/Storage/Private/FIRStorageTask_Private.h

Minimal fix for #1565. Confirmed integration tests pass.

Minimal fix for #1565

---

Firebase/Storage/CHANGELOG.md

Now fixing #1565 with #1747 instead of #1721

Update Release Note

---

Functions/FirebaseFunctions/FUNError.h
Functions/FirebaseFunctions/FUNError.m
Functions/FirebaseFunctions/FUNSerializer.m

Fix analyze issues in Functions. See #1735

Fix analyze of FirebaseFunctions

---

FirebaseFirestore.podspec

Update Firestore's leveldb-library dependency version

---

Firebase/Auth/Source/FIRAuth.m
Firebase/Auth/Source/FIRAuthErrorUtils.h
Firebase/Auth/Source/FIRAuthErrorUtils.m
Firebase/Auth/Source/FIRUser.m
Firebase/Auth/Source/FIRUser_Internal.h
Firebase/Auth/Source/RPCs/FIRAuthRPCResponse.h

Finish project started in #1740 and verify a clean analyze build of Auth

Fix rest of Auth analyze issues

---

Firestore/Protos/CMakeLists.txt

This fixes the totally clean build once and for all.

Split protoc and nanopb python generation

---

Firebase/Core/FIRApp.m

This will log the source and value of the `dataCollectionDefaultEnabled` flag.
This is for Issue #1768.

Log to console Data Collection flag value and source

---

Example/Podfile
Firebase/Core/FIROptions.m
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseDatabase.podspec
FirebaseFirestore.podspec
FirebaseFunctions.podspec
FirebaseMessaging.podspec
FirebaseStorage.podspec
Firestore/Example/Podfile
Releases/Manifests/5.8.0.json
Releases/update-versions.py

Merging the 5.8.0 release into master

Release 5.8.0

---

Example/Firebase.xcodeproj/project.pbxproj

Including the Info.plist in the Resource Bundle was previously a warning. Now it's an error.

Fix tvOS build with Xcode 10

---

Example/Auth/Tests/FIRGetOOBConfirmationCodeRequestTests.m
Firebase/Auth/Source/FIRAuthErrorUtils.h
Firebase/Auth/Source/FIRAuthErrorUtils.m
Firebase/Auth/Source/FIRAuthInternalErrors.h
Firebase/Auth/Source/Public/FIRActionCodeSettings.h
Firebase/Auth/Source/Public/FIRAuthErrors.h
Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeRequest.h
Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeRequest.m

Add supporting of custom fdl domain

Add supporting of custom fdl domain

---

Example/Auth/Tests/FIRGetOOBConfirmationCodeRequestTests.m
Firebase/Auth/Source/FIRAuthErrorUtils.h
Firebase/Auth/Source/FIRAuthErrorUtils.m
Firebase/Auth/Source/FIRAuthInternalErrors.h
Firebase/Auth/Source/Public/FIRActionCodeSettings.h
Firebase/Auth/Source/Public/FIRAuthErrors.h
Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeRequest.h
Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeRequest.m

Reverts firebase/firebase-ios-sdk#1810

Revert "Add supporting of custom fdl domain"

---

Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
Firebase/Auth/Source/FIRAuthErrorUtils.m
Firebase/Auth/Source/FIRAuthInternalErrors.h
Firebase/Auth/Source/FIRAuthWebUtils.h
Firebase/Auth/Source/Public/FIRPhoneAuthProvider.h
Firebase/Messaging/FIRMessagingSecureSocket.m
Firestore/Protos/build_protos.py
Firestore/core/src/firebase/firestore/local/local_serializer.h
Firestore/core/test/firebase/firestore/util/grpc_stream_tester.h
scripts/cpplint.py

Only change typo in comments. Preparing for the c bara sync.

fix common typo

---

GoogleUtilities.podspec

Releasing GULUserDefaults and static library build warning fixes.

Bump minor version for next GoogleUtilities release

---

Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
Firestore/Source/Model/FSTMutation.h
Firestore/Source/Model/FSTMutation.mm
Firestore/Source/Remote/FSTSerializerBeta.h
Firestore/Source/Remote/FSTSerializerBeta.mm
Firestore/Source/Remote/FSTStream.mm
Firestore/core/src/firebase/firestore/remote/stream_objc_bridge.mm

On the other platforms we fill in commit time for delete mutations. Update iOS to match.

Non-optional commit time

---

Functions/Example/FirebaseFunctions.xcodeproj/project.pbxproj

To fix a red highlighted file in the Xcode project view

Remove a non-existent, unneeded file from xcode project

---

Firestore/core/src/firebase/firestore/util/filesystem.h
Firestore/core/src/firebase/firestore/util/filesystem_common.cc
Firestore/core/src/firebase/firestore/util/filesystem_detail.h
Firestore/core/src/firebase/firestore/util/filesystem_posix.cc

Also reimplement `RecursivelyDeleteDir` in terms of the iterator.

Implement a directory iterator

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/core/src/firebase/firestore/util/filesystem.h
Firestore/core/src/firebase/firestore/util/filesystem_common.cc
Firestore/core/src/firebase/firestore/util/filesystem_detail.h
Firestore/core/src/firebase/firestore/util/filesystem_posix.cc
Firestore/core/src/firebase/firestore/util/filesystem_win.cc

Port DirectoryIterator to Windows

---

Firestore/CHANGELOG.md

This is the iOS port of
https://github.com/firebase/firebase-android-sdk/pull/49

Backporting reviewer suggested comments from cl/214509458

---

Firebase/InAppMessagingDisplay/CHANGELOG.md
Firebase/InAppMessagingDisplay/CHNAGELOG.md

Start tracking the change history.

add changelog for fiam display

---

Firestore/Source/API/FIRFirestore.mm
Firestore/Source/API/FIRFirestoreSettings.mm
Firestore/Source/Core/FSTFirestoreClient.h
Firestore/Source/Core/FSTFirestoreClient.mm
Firestore/Source/Local/FSTLRUGarbageCollector.h
Firestore/Source/Public/FIRFirestoreSettings.h
Firestore/Swift/Tests/API/BasicCompileTests.swift

Add the public API changes and connect the settings to actually running LRU GC. Set LRU to use the default parameters.
Merge base is into the other LRU branch.

Wire up LRU GC

---

Firestore/CHANGELOG.md

The actual changes include:
* Addition of the UnknownDocument type
* Changes in support of using gRPC C++
* Fixing the fuzzer under Xcode 10
* Synchronization with google3
* Schema migration to ensure sentinel rows exist
* Fixes for Window support
None of these seem to warrant actually calling out.

Update CHANGELOG for Firestore v0.13.6

---

scripts/if_changed.sh
scripts/pod_lib_lint.sh

Now that FirebaseAnalyticsInterop 1.1.0 is public

Restore pod lib lint testing to public

---

Firebase/DynamicLinks/CHANGELOG.md
Firebase/DynamicLinks/FIRDLDefaultRetrievalProcessV2.m
Firebase/DynamicLinks/FIRDynamicLinks.m
FirebaseDynamicLinks.podspec

Include c99 compatible fix in Firebase 5.11.0 so that FDL works with Unity

DynamicLinks patch version for c99 compatibility fix

---

GoogleUtilities.podspec

Update version to deliver the #1970 fix for #1964

Bump GoogleUtilities patch version to deliver fix for #1964

---

Firestore/Source/Local/FSTMemoryPersistence.mm

Silence a recently added implicit conversion warning.

Remove warning

---

Example/Podfile
Firestore/Example/Podfile
Releases/update-versions.py

Changing the internal testing repo links

Changing the internal testing repo

---

Firestore/CHANGELOG.md

To be submitted when main PR goes in

Held Write Acks Changelog

---

InAppMessagingDisplay/Example/InAppMessagingDisplay-UITests/InAppMessagingDisplayUITestsBase.swift

Two more travis timeout flakes today in InAppMessagingDisplayModalViewUITests

Address travis timeout flakes

---

Example/Auth/Sample/AppManager.m
Example/Auth/Sample/SettingsViewController.m

Fix auth multi app support

---

Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm

fix a typo in integration test

fix a typo in integration test

---

Firebase/Storage/Private/FIRStorageDownloadTask_Private.h
Firebase/Storage/Private/FIRStorageObservableTask_Private.h
Firebase/Storage/Private/FIRStorageTaskSnapshot_Private.h

Previously this was working due to import order in another file, we should explicitly declare dependencies.

Fix Storage private imports.

---

Firebase/DynamicLinks/CHANGELOG.md

Update changelog for Dynamic Links to v 3.4.0

Update changelog for Dynamic Links to v 3.4.0

---

Firestore/core/src/firebase/firestore/local/local_serializer.cc
Firestore/core/src/firebase/firestore/local/local_serializer.h
Firestore/core/src/firebase/firestore/model/CMakeLists.txt
Firestore/core/src/firebase/firestore/model/field_mask.h
Firestore/core/src/firebase/firestore/model/mutation.cc
Firestore/core/src/firebase/firestore/model/mutation.h
Firestore/core/src/firebase/firestore/model/mutation_batch.cc
Firestore/core/src/firebase/firestore/model/mutation_batch.h
Firestore/core/src/firebase/firestore/model/precondition.h
Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/src/firebase/firestore/remote/serializer.h
Firestore/core/test/firebase/firestore/local/local_serializer_test.cc
Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Firestore/core/test/firebase/firestore/testutil/testutil.h

Also involves porting:
- MutationBatch (partial)
- LocalSerializer::[En|De]codeMutationBatch
- Serializer::[En|De]codeMutation
- Serializer::[En|De]codePrecondition
- Serializer::[En|De]codeDocumentMask

Port last remaining local serializer test.

---

Firestore/CHANGELOG.md

https://github.com/firebase/firebase-android-sdk/pull/207

Backport changelog fixups

---

GoogleDataLogger/GoogleDataLogger/Classes/GDLUploadCoordinator.h
GoogleDataLogger/GoogleDataLogger/Classes/GDLUploadCoordinator.m
GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLUploadCoordinator_Private.h
GoogleDataLogger/Tests/Unit/Categories/GDLUploadCoordinator+Testing.h
GoogleDataLogger/Tests/Unit/Categories/GDLUploadCoordinator+Testing.m
GoogleDataLogger/Tests/Unit/GDLTestCase.m
GoogleDataLogger/Tests/Unit/GDLUploadCoordinatorTest.m

This is a thread safe class to manage the different GDLUploader implementations.

Implement the upload coordinator

---

.travis.yml
scripts/build.sh

Successor to #2276 and #2282 
travis_retry ran without noticeable time degradation with no flakes. I'll monitor subsequent builds for successful flake recovery.

Use travis_retry to minimize flakes

---

Example/Podfile
Firestore/Example/Podfile
scripts/pod_lib_lint.sh

Now that Firebase 5.16.0 is public, comment SpecStaging CI workaround

Stop using SpecStaging

---

.travis.yml
scripts/pod_lib_lint.sh

Enabled by https://github.com/firebase/SpecsStaging/commit/88ecf17d0bd799ed147c7689723d4c41387a98c3

Start pod lib lint CI for FIAM

---

Example/Firebase.xcodeproj/project.pbxproj
Gemfile.lock

Also pull in Auth TV OS unit test target fixes from #2091.

Update CI to use CocoaPods 1.6.0

---

.travis.yml
Firebase/InAppMessagingDisplay/FIRIAMDefaultDisplayImpl.m
Firebase/InAppMessagingDisplay/Public/FIRIAMDefaultDisplayImpl.h
InAppMessagingDisplay/Example/InAppMessagingDisplay-Sample.xcodeproj/project.pbxproj
scripts/build.sh
scripts/if_changed.sh
scripts/install_prereqs.sh

Fixes travis regression along with https://github.com/firebase/SpecsStaging/commit/1109ced7a9ecb0d3821920fad4c530f7726582c1
Fixes InAppMessaging's Sample's HEADER_SEARCH_PATH setting
Cleans up InAppMessaging and InAppMessagingDisplay's travis configuration

Fix import references to other pod's headers to fix pod lib lint

---

.travis.yml

Apple will require Xcode 10 for app submissions starting March 2019

Move Xcode 9.4 tests to cron

---

Firebase/InAppMessaging/CHANGELOG.md
Firebase/InAppMessagingDisplay/CHANGELOG.md

Release notes for callbacks feature

Add FIAM M44 release notes

---

Functions/Example/Tests/FUNSerializerTests.m

Fix unit tests so that they pass on an iPhone 4s simulator

Fix Functions unit tests for 32bit targets

---

Example/Podfile
Firebase/Core/FIROptions.m
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseDynamicLinks.podspec
FirebaseFirestore.podspec
FirebaseFunctions.podspec
FirebaseInAppMessaging.podspec
FirebaseInAppMessagingDisplay.podspec
FirebaseMessaging.podspec
Firestore/Example/Podfile
GoogleUtilities.podspec
Releases/Manifests/5.18.0.json
SymbolCollisionTest/Podfile

Merging the 5.18.0 release into master.

Release 5.18.0

---

Functions/Backend/index.js
Functions/Example/IntegrationTests/FIRIntegrationTests.m

Tested locally. CI is on the way in #1864

Fix Functions IntegrationTests for 32bit architectures

---

Functions/CHANGELOG.md

Updates for v2.3.0, including changes from PR 2329.

Update release notes for Functions.

---

ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
ZipBuilder/Sources/ZipBuilder/Subspec.swift
ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift

Now that Apple requires Xcode 10.1+ to submit to the App Store, we
can package the Zip file using Xcode 10.1.

Use `CaseIterable` from Xcode 10+.

---

FirebaseInstanceID.podspec

This is really a minor change, not a patch.

Bump the minor version.

---

README.md

Add xcov instructions in README

---

Firestore/CHANGELOG.md

Update CHANGELOG for Firestore v1.1.0

---

Firebase/InAppMessagingDisplay/CHANGELOG.md

FIAM release notes for M45

---

Firestore/core/test/firebase/firestore/model/mutation_test.cc

...and add placeholders for numeric transform tests

Implement PatchingDeletedDocumentsDoesNothing test

---

GoogleUtilities.podspec
GoogleUtilities/CHANGELOG.md

Planning to publish Tuesday, March 12

GoogleUtilities 5.4.0

---

GoogleUtilities.podspec
GoogleUtilities/CHANGELOG.md
GoogleUtilities/Logger/GULLogger.m

Fix GULResetLogger API breakage

---

Firebase/InstanceID/CHANGELOG.md

InstanceID changelog update

---

ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
ZipBuilder/Sources/ZipBuilder/Subspec.swift

Not ready for merge
@ryanwilson The build ran for three hours before I killed it and made the small tweak in the second commit.  I'll try again overnight. If possible would you see if there's something obvious wrong in my changes and try a build yourself?

Changes to build m45 zip

---

InAppMessaging/Example/Tests/FIRIAMClearcutUploaderTests.m

Disable two flaky tests in FIAM while seeking fix.

Disable flaky tests in FIAM

---

Example/Auth/ApiTests/FacebookAuthTests.m

Reverts firebase/firebase-ios-sdk#2547

Revert "Disable Facebook API tests"

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj

This is what you get when you `pod install` using 1.6.1

Upgrade project to CocoaPods 1.6.1

---

README.md

- Update macOS/tvOS installation instructions
- Add tvOS for Messaging
- Add macOS for Firestore

Update tvOS and macOS README

---

Carthage.md

Update Carthage instructions for FirebaseMLNLSmartReplyBinary

---

Firestore/core/src/firebase/firestore/model/field_value.h
Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/src/firebase/firestore/remote/serializer.h
Firestore/core/test/firebase/firestore/remote/serializer_test.cc

Still TODO: ServerTimestamp and Reference.

Add support to [de]serialize missing FV types to the remote serializer

---

Firebase/Core/FIRApp.m

Improve invalid app name error message based on feedback in #2609

Improve error message

---

Firebase/DynamicLinks/CHANGELOG.md

Update FDL CHANGELOG for M46.

---

.travis.yml
scripts/build.sh

This has a logical dependency on #2641 and #2643, but in order to get Travis to run I haven't declared these as dependent. Once I've verified that travis runs I'll change the target branch so it's clearer what's changing.

Build Firestore macOS on Travis

---

Example/Messaging/Tests/FIRMessagingDataMessageManagerTest.m
Firebase/Messaging/FIRMessagingCheckinService.h
Firebase/Messaging/FIRMessagingRmq2PersistentStore.m

cherry-pick #2673 to the release-5.20.0 branch

fix typo in iOS target (#2673)

---

Example/Messaging/Tests/FIRMessagingDataMessageManagerTest.m
Example/Podfile
Firebase/Core/FIROptions.m
Firebase/Messaging/FIRMessagingCheckinService.h
Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseDynamicLinks.podspec
FirebaseFirestore.podspec
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
Firestore/Example/Podfile
Releases/Manifests/5.20.0.json
SymbolCollisionTest/Podfile

Merging the 5.20.0 release into master

Release 5.20.0

---

Example/Podfile
FirebaseFirestore.podspec
Firestore/CHANGELOG.md
Firestore/Example/Podfile
SymbolCollisionTest/Podfile

Firebase 5.20.1 FirebaseFirestore 1.2.1

Versions for 5.20.1

---

ZipBuilder/README.md

Added some instructions to build the zip. Will expand further with releasing information.

Add quick instructions for building the Zip.

---

GoogleUtilities.podspec

Bump GoogleUtilities version to 5.6.0

---

GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
GoogleUtilities/Common/GULLoggerCodes.h
GoogleUtilities/Example/GoogleUtilities.xcodeproj/project.pbxproj
GoogleUtilities/Example/Podfile
GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m

Fix issue described [here](https://github.com/firebase/firebase-ios-sdk/pull/2725#pullrequestreview-223000308) to fix master

Fix changes conflict to fix build

---

Firebase/Auth/CHANGELOG.md
Firebase/InstanceID/CHANGELOG.md
Firebase/Messaging/CHANGELOG.md

Changelog updates for Messaging, Auth and InstanceID

---

GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.h
GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m

 `pod lib lint GoogleUtilities.podspec` warnings fixes

---

Firebase/Database/CHANGELOG.md
Firebase/Database/FIRDatabaseReference.m
Firebase/Database/Public/FIRDatabaseReference.h

Remove deprecated RTDB API

---

Firestore/Source/API/FIRFieldPath.mm
Firestore/core/src/firebase/firestore/model/CMakeLists.txt
Firestore/core/src/firebase/firestore/model/field_path.cc
Firestore/core/src/firebase/firestore/model/field_path.h

Reverting due to broken integration test.

Revert "Move input validation logic from FIRFieldPath to model::FieldPath. (#2727)"

---

Firestore/Source/Model/FSTFieldValue.h
Firestore/Source/Model/FSTFieldValue.mm

c++ properties don't mix well with obj-c properties.

Fix FSTDelegateValue: property -> ivar

---

Firebase/DynamicLinks/CHANGELOG.md

FDL release notes for M47

---

Firebase/InstanceID/FIRInstanceID+Private.h
Firebase/InstanceID/Private/FIRInstanceID_Private.h
scripts/if_changed.sh

- Initializer `-[FIRInstanceID initPrivately]` moved to FIRInstanceID_Private.h
- `if_change.sh` fixed to check InstanceID

InstanceID - podspec lint fix

---

ZipBuilder/FirebaseSDKs.proto
ZipBuilder/Sources/ZipBuilder/FirebaseSDKs.pb.swift

These were added internally. The `FirebaseSDKs.pb.swift` file was auto-generated.

Update FirebaseSDKs.textproto with new fields.

---

scripts/check_filename_spaces.sh

This fixes the issues I mentioned in my review of #2821. It works because it only checks files known to git, avoiding catching build output and other temporary files. The downside is that you won't see a error with `check.sh` until you've done a `git add` or `git commit`.
This is also 10 times faster because `git ls-files` only considers its internal storage which is much faster than traversing the filesystem.

Proposed improvements to space checking

---

GoogleDataTransport/Library/Private/GDTUploadCoordinator_Private.h

Fix a single missing header change

---

Example/Firebase.xcodeproj/project.pbxproj
Example/Messaging/App/iOS/NotificationService/Info.plist
Example/Messaging/App/iOS/NotificationService/NotificationService.h
Example/Messaging/App/iOS/NotificationService/NotificationService.m
Example/Podfile
Firebase/Auth/Source/Auth/FIRAuth.m
Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h
GoogleUtilities/AppDelegateSwizzler/README.md
GoogleUtilities/Example/GoogleUtilities.xcodeproj/xcshareddata/xcschemes/Example_iOS.xcscheme
GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m

GULAppDelegateSwizzler - proxy APNS methods separately (#2835)

---

Functions/Example/IntegrationTests/FIRIntegrationTests.m
Functions/FirebaseFunctions/FIRFunctions.m
Functions/FirebaseFunctions/FUNError.m

Tweak Functions error messages to be consistent with Android and C++.

---

Firestore/Source/API/FIRDocumentReference+Internal.h
Firestore/Source/API/FIRDocumentReference.mm
Firestore/Source/API/FIRFirestore.mm
Firestore/Source/API/FIRWriteBatch+Internal.h
Firestore/Source/API/FIRWriteBatch.mm
Firestore/core/src/firebase/firestore/api/document_reference.h
Firestore/core/src/firebase/firestore/api/document_reference.mm
Firestore/core/src/firebase/firestore/api/document_snapshot.h
Firestore/core/src/firebase/firestore/api/firestore.h
Firestore/core/src/firebase/firestore/api/firestore.mm
Firestore/core/src/firebase/firestore/api/write_batch.h
Firestore/core/src/firebase/firestore/api/write_batch.mm

* Create api::WriteBatch "port" of FIRWriteBatch.
* Make FIRWriteBatch a wrapper around an api::WriteBatch (and a FSTUserDataConverter for parsing input).

Port FIRWriteBatch.

---

Firebase/Storage/Public/FIRStorageMetadata.h

Hey,
Just a small PR to fix a typo in the code comments.
Thanks

[storage] small typo in code comments

---

Firebase/InstanceID/FIRIMessageCode.h
Firebase/InstanceID/FIRInstanceIDCheckinStore.m
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
GoogleUtilities.podspec
GoogleUtilities/CHANGELOG.md

Cherry-picks for M47 RC5

---

Firestore/Example/App/GoogleService-Info.plist
Firestore/Source/Public/FIRFirestore.h

Adding documentation for WriteBatch size limit 

---

ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
ZipBuilder/Sources/ZipBuilder/ResourcesManager.swift
ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
ZipBuilder/Sources/ZipBuilder/main.swift

- Removes framework-specific code for resources
- Embeds all resources into .framework folders first to prep for
Carthage
- Extracts all resources into existing zip structure
- Fixes missing resources from cached OSS framework

Fix Resources issues with builder.

---

.gitignore
Firestore/Example/Tests/Integration/API/FIRArrayTransformTests.mm
Firestore/Example/Tests/Integration/API/FIRNumericTransformTests.mm
scripts/build.sh
scripts/run_firestore_emulator.sh

This is a re-attempt of #2664 that doesn't rely on actually talking to a live backend and thus doesn't need a real project ID or a secrets file containing that.

Run Firestore integration tests against the emulator

---

scripts/build.sh

Ensure Firestore emulator is shut down on build failure

---

SymbolCollisionTest/Podfile

Fix SymbolCollision Test

---

ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift

This was tracked internally at b/131769324.

Use correct framework names in README.

---

ZipBuilder/Sources/ZipBuilder/CocoaPod.swift

Adds new SDKs that were introduced with M47 (Firebase 6.0.0).

Add new SDKs to zip builder.

---

.travis.yml
scripts/check.sh

Successful here: https://travis-ci.org/firebase/firebase-ios-sdk/jobs/530398757
Obsoletes #2974.

Fix check.sh when running a push build with a single commit

---

Firestore/Source/API/FIRTimestamp.m
Firestore/core/include/firebase/firestore/geo_point.h
Firestore/core/src/firebase/firestore/geo_point.cc
Firestore/core/src/firebase/firestore/model/field_value.cc
Firestore/core/src/firebase/firestore/model/field_value.h
Firestore/core/test/firebase/firestore/model/field_value_test.cc

Add a few missing things:
* `ToString` and `operator<<` to GeoPoint
* `ToString` and `operator<<` to FieldValue
* `Hash`
* Fix `ServerTimestamp`'s `previous_value` to be a `FieldValue`

Flesh out C++ FieldValue

---

GoogleUtilities.podspec
GoogleUtilities/CHANGELOG.md

- changelog
- version bump to 6.1.0

GoogleUtilities 6.1.0

---

.travis.yml
scripts/build.sh

Hopefully in the future it will become more obvious what the real problem is.
Fixes #2982

Attempt to move GDT's integration test to the allowed_failures section

---

Firebase/InAppMessaging/Runtime/FIRIAMActionURLFollower.m

Found this while I was debugging a different issue.

Fix typo in log message.

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
Firestore/core/test/firebase/firestore/local/local_serializer_test.cc
Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Firestore/core/test/firebase/firestore/util/CMakeLists.txt
Firestore/core/test/firebase/firestore/util/filesystem_test.cc
Firestore/core/test/firebase/firestore/util/status_apple_test.mm
Firestore/core/test/firebase/firestore/util/status_test.cc
Firestore/core/test/firebase/firestore/util/status_testing.h

Consolidate status testing

---

Firebase/Auth/Source/Public/FIRAuth.h
Firebase/Auth/Source/Public/FIRUserMetadata.h
Firebase/InstanceID/Public/FIRInstanceID.h

There are causing the internal linter to complain each time, let's just fix them 😄

Fix common typos.

---

scripts/pod_local_deps.rb

This implements my idea for pulling dependency information from the podspecs themselves.

Add a script to print the local dependencies of a given podspec file.

---

.travis.yml

Saw that increasing the timeout didn't work... back to the flake debugging coal mines for me.

Fiam make nonrequired

---

Example/Firebase.xcodeproj/project.pbxproj

Change to iOS 8.0 to align with our sdk.

Update sample app deployment target to iOS 8.0

---

GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
GoogleUtilities/SwizzlerTestHelpers/GULRuntimeClassSnapshot.m

GoogleUtilities unit tests on iOS 8

---

Firestore/core/src/firebase/firestore/api/document_reference.mm
Firestore/core/src/firebase/firestore/model/database_id.cc
Firestore/core/src/firebase/firestore/model/database_id.h

A couple of very small issues I noticed:
- `DatabaseId` could easily use a pointer to `const` in its implementation;
- fix local variables naming style.

Very small fixes

---

GoogleDataTransport/generate_project.sh
GoogleDataTransportCCTSupport/ProtoSupport/generate_cct_protos.sh
GoogleDataTransportCCTSupport/generate_project.sh

Just for easier future refactoring/renaming/directory moving

Make pod gen related scripts git repo dir relative

---

Firebase/Messaging/Public/FIRMessaging.h

Fix >100 character line

---

scripts/build.sh

Clean the derived data between builds to help reduce flakiness

---

Example/Firebase.xcodeproj/project.pbxproj
Example/Firebase.xcodeproj/xcshareddata/xcschemes/InstanceID_Tests_iOS.xcscheme
Example/Firebase.xcodeproj/xcshareddata/xcschemes/InstanceID_Tests_tvOS.xcscheme
Example/Firebase.xcodeproj/xcshareddata/xcschemes/Messaging_Tests_tvOS.xcscheme
Example/Storage/Tests/Integration/FIRStorageIntegrationTests.m
Example/Storage/Tests/Unit/FIRStorageDeleteTests.m
Example/Storage/Tests/Unit/FIRStorageListTests.m
Firebase/Storage/CHANGELOG.md
Firebase/Storage/FIRStorageConstants.m
Firebase/Storage/FIRStorageListResult.m
Firebase/Storage/FIRStorageListTask.m
Firebase/Storage/FIRStorageReference.m
Firebase/Storage/FIRStorageUtils.m
Firebase/Storage/Private/FIRStorageConstants_Private.h
Firebase/Storage/Private/FIRStorageListResult_Private.h
Firebase/Storage/Private/FIRStorageListTask.h
Firebase/Storage/Private/FIRStorageUtils.h
Firebase/Storage/Public/FIRStorageConstants.h
Firebase/Storage/Public/FIRStorageListResult.h
Firebase/Storage/Public/FIRStorageReference.h
Firebase/Storage/Public/FirebaseStorage.h
Firestore/Source/Local/FSTLocalStore.mm
Firestore/core/src/firebase/firestore/remote/connectivity_monitor_noop.cc

Port of https://github.com/firebase/firebase-android-sdk/pull/458

Storage: Add List API

---

scripts/lib/source.py

In https://github.com/firebase/firebase-ios-sdk/pull/3161#discussion_r293878143 I said I did this but I pushed without committing and didn't realize it. This is the promised fix.

Actually change to NotImplementedError

---

scripts/check_lint.py

A follow up based on your "ick" in https://github.com/firebase/firebase-ios-sdk/pull/3161#discussion_r293813493. This removes any special handling for finding python binaries. If you install `flake8` in a location that's not on the `PATH` we'll no longer try to find it for you.

Require flake8 to actually be on the path.

---

Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h
Firebase/InAppMessagingDisplay/Public/FIRIAMDefaultDisplayImpl.h

100% documentation PR, no actual code changes :)

Clean up documentation to conform to Jazzy doc style

---

Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m

… (#3208)
This reverts commit 393d06071005c9c454e678da9d55a1e73e048473.

Cherry-pick a reverted Auth PR

---

Firestore/Source/API/FIRDocumentSnapshot.mm

A follow-up to https://github.com/firebase/firebase-ios-sdk/pull/3178#discussion_r294047458.

Remove NSLog call in FIRDocumentSnapshot

---

FirebaseInstallations/Source/Library/FIRInstallations.m
FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.h
FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.h
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsSingleOperationPromiseCache.h
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsSingleOperationPromiseCache.m
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsStatus.h
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m

The is a next part of iOS Firebase Installations implementation.
The PR contains implementation of deleting installation (locally and on the server).

Delete Installation implementation

---

FirebaseInstallations/Source/Library/FIRInstallationsItem.m
FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsItemTests.m

Next part of FIS.
The PR contains basic integration tests for the public API (so far only for local run) and the related fixes (basically for issues like [this](https://memegen.googleplex.com/6648128930840576) 😄)

Integration Tests and fixes

---

FirebaseInstallations/Source/Library/FIRSecureStorage.h
FirebaseInstallations/Source/Library/FIRSecureStorage.m
FirebaseInstallations/Source/Tests/Unit/FIRSecureStorageTests.m

Firebase Installation:
- in-memory cache on top of Keychain added to mitigate slow Keychain access.

FIS: In-memory cache for Keychain

---

GoogleDataTransport/GDTLibrary/GDTPlatform.m

GoogleDataTransport app extensions support:
- begin/end background tasks only when supported.

GoogleDataTransport - recover app extensions support

---

Example/InstanceID/Tests/FIRInstanceIDTest.m
Firebase/InstanceID/CHANGELOG.md
Firebase/InstanceID/FIRInstanceID.m
Firestore/Swift/Source/Codable/third_party/FirestoreEncoder.swift

Fix token fetch not invoking callback for unchanged token

---

Firebase/InAppMessaging/FIRCore+InAppMessaging.m
Firebase/InAppMessagingDisplay/FIRCore+InAppMessagingDisplay.m

I deleted the wrong lines in FIAM in #3250. This fixes that.

Fix FIAM build break

---

GoogleUtilities.podspec

Version bump for GoogleUtilities release 6.2.1.

GoogleUtilities bump version to 6.2.1

---

Example/Auth/AuthSample/Podfile
Example/Podfile
Firestore/Example/Podfile
InAppMessaging/Example/Podfile
InAppMessagingDisplay/Example/Podfile
SymbolCollisionTest/Podfile
scripts/install_prereqs.sh
scripts/pod_lib_lint.rb

Fix #3165 
See http://blog.cocoapods.org/CocoaPods-1.7.2/

Reenable CocoaPods CDN

---

Firebase/Core/Private/FIRAppInternal.h
Firebase/Firebase/Public/Firebase.h
Functions/FirebaseFunctions/FIRFunctions.m
Functions/FirebaseFunctions/FUNContext.m
Package.swift
Sources/firebase-test/main.swift

Fix firebase-test target regression
Builds Functions for spm
Functions quickstart requires FirebaseUI so this is not much more than build tested so far.;

spm functions

---

FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
FirebaseInstallations/Source/Library/Public/FIRInstallations.h
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m

FirebaseInstallations - send notification when a Firebase installation is created or deleted.

FirebaseInstallations - sending of FIRInstallationIDDidChangeNotification

---

GoogleUtilities.podspec
GoogleUtilities/CHANGELOG.md

Version bump for a patch release.

Bump GoogleUtilities version 6.2.2

---

Firestore/core/src/firebase/firestore/nanopb/writer.cc
Firestore/core/src/firebase/firestore/timestamp.cc
Firestore/core/test/firebase/firestore/model/field_value_test.cc
Firestore/core/test/firebase/firestore/timestamp_test.cc

Fix a bunch of warnings and errors that have crept in when compiling under VS 2017.

Fix the build on Windows

---

Firestore/Example/Tests/Core/FSTQueryTests.mm
Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
Firestore/Source/API/FIRFirestore.mm
Firestore/Source/Core/FSTQuery.h
Firestore/Source/Core/FSTQuery.mm
Firestore/Source/Remote/FSTSerializerBeta.mm
Firestore/core/src/firebase/firestore/api/firestore.h
Firestore/core/src/firebase/firestore/api/firestore.mm
Firestore/core/src/firebase/firestore/core/query.cc
Firestore/core/src/firebase/firestore/core/query.h
Firestore/core/src/firebase/firestore/local/local_documents_view.mm
Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/src/firebase/firestore/util/equality.h
Firestore/core/src/firebase/firestore/util/string_apple.h
Firestore/core/src/firebase/firestore/util/vector_of_ptr.h
Firestore/core/test/firebase/firestore/core/query_test.cc
Firestore/core/test/firebase/firestore/local/CMakeLists.txt
Firestore/core/test/firebase/firestore/testutil/testutil.h
Firestore/core/test/firebase/firestore/util/objc_compatibility_apple_test.mm

... and clean up the implementation in preparation for filling it out.

Implement collection groups in C++ Query

---

AddNewPod.md
README.md

Here's a first draft. Let me know what you think.

Docs update and directory structure proposal

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
Firestore/Source/API/FIRDocumentChange.mm

Fix FIRDocumentChange returning incorrect values for not found

---

Firebase/Core/CHANGELOG.md
Firebase/Storage/CHANGELOG.md

Minor version update since it's an API fix of a completely broken API

Storage for M52

---

Firebase/InAppMessagingDisplay/CHANGELOG.md

M52 release notes for headful SDK

---

FirebaseDynamicLinks.podspec

This was causing `pod repo push` to fail in the release process

Add missing GoogleUtilities version dependencies

---

FirebaseInstallations/Source/Library/FIRInstallations.m
FirebaseInstallations/Source/Library/FIRInstallationsItem.h
FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStore.h
FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredAuthToken.h
FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredItem.h
FirebaseInstallations/Source/Library/Public/FIRInstallations.h
FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
FirebaseInstallations/Source/Tests/Utils/FIRInstallations+Tests.h

Preparing FIS to be merged to master as an independent SDK:
- remove outdated TODOs
- small tests improvements
- API docs
- typos

FirebaseInstallations - cleanup

---

Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
GoogleDataTransport/GDTTests/Unit/GDTUploadCoordinatorTest.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m

- Don't upload if there's no network
- Explicitly compare pointers to nil
- Fix a minor memory leak
- Address some analyzer issues

Cherry pick some bug and analyzer fixes

---

Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm
Firestore/Example/Tests/Integration/API/FIRFirestoreSourceTests.mm
Firestore/Example/Tests/Integration/API/FIRListenerRegistrationTests.mm
Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
Firestore/Source/API/FIRDocumentReference.mm
Firestore/Source/API/FIRQuery.mm
Firestore/Source/API/FIRQuerySnapshot.mm
Firestore/Source/Core/FSTFirestoreClient.h
Firestore/Source/Local/FSTLevelDB.mm
Firestore/core/src/firebase/firestore/api/document_reference.mm
Firestore/core/src/firebase/firestore/objc/objc_compatibility.h

Remove several imports that appear to be unused.

Remove extraneous imports

---

FirebaseInstallations/Source/Library/FIRInstallationsLogger.h
FirebaseInstallations/Source/Library/FIRInstallationsLogger.m
FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredAuthToken.m
FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredItem.m

- debug logging added to `FIRInstallationsAPIService` and `FIRInstallationsIDController`
- some typos fixed
Other debug logs will be added as needed.

FirebaseInstallations: debug logging

---

GoogleDataTransport/GDTLibrary/GDTClock.m
GoogleDataTransport/GDTLibrary/GDTDataFuture.m
GoogleDataTransport/GDTLibrary/Public/GDTDataFuture.h
GoogleDataTransport/GDTTests/Unit/GDTClockTest.m
GoogleDataTransport/GDTTests/Unit/GDTDataFutureTest.m

From pre-release-6.2.0 to master

Consolidate bug fixes without podspec version changes

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/FSTTransactionTests.mm
Firestore/core/src/firebase/firestore/core/transaction.h
Firestore/core/src/firebase/firestore/core/transaction.mm

Porting over from [web](https://github.com/firebase/firebase-js-sdk/pull/1980).
I think this test might occasionally flake, but I'm not sure what steps I can take to discover it.

Fix preconditions in transactions

---

Firebase/Auth/CHANGELOG.md
Firebase/CoreDiagnostics/CHANGELOG.md
Firebase/DynamicLinks/CHANGELOG.md
Firebase/InAppMessaging/CHANGELOG.md
Firebase/InAppMessagingDisplay/CHANGELOG.md
Firebase/InstanceID/CHANGELOG.md
Firebase/Messaging/CHANGELOG.md
Functions/CHANGELOG.md

Makes changelogs more fit for consumption via `scripts/make_release_notes.py`.

Clean up changelogs

---

Firebase/InstanceID/FIRIMessageCode.h
Firebase/InstanceID/FIRInstanceID.m

Fix crash in FIRInstanceID

---

Firestore/Example/Podfile

Fixes symptoms observed in CocoaPods/CocoaPods#9060, which doesn't seem like a CocoaPods bug.

Fix sync_project when running under bundler

---

Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m

Fix for https://github.com/firebase/firebase-ios-sdk/pull/3208

Add assertion for Facebook generic IDP flow

---

Firestore/Example/Tests/Util/FSTHelpers.h
Firestore/Source/API/FSTUserDataConverter.h
Firestore/Source/Local/FSTLocalStore.mm
Firestore/Source/Local/FSTQueryData.mm
Firestore/Source/Model/FSTDocument.h
Firestore/Source/Model/FSTDocument.mm
Firestore/Source/Model/FSTMutation.h
Firestore/Source/Remote/FSTSerializerBeta.h
Firestore/Source/Remote/FSTSerializerBeta.mm
Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift
Firestore/core/src/firebase/firestore/api/document_change.mm
Firestore/core/src/firebase/firestore/api/document_snapshot.h
Firestore/core/src/firebase/firestore/core/field_filter.cc
Firestore/core/src/firebase/firestore/core/user_data.h
Firestore/core/src/firebase/firestore/core/view_snapshot.mm
Firestore/core/src/firebase/firestore/model/precondition.h
Firestore/core/src/firebase/firestore/model/snapshot_version.cc
Firestore/core/src/firebase/firestore/model/snapshot_version.h
Firestore/core/src/firebase/firestore/util/hashing.h
Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Firestore/core/test/firebase/firestore/util/hashing_test.cc

Each commit says what it does.

A grab bag of misc fixes

---

Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
GoogleDataTransport/GDTLibrary/GDTConsoleLogger.m
GoogleDataTransport/GDTLibrary/GDTPlatform.m
GoogleDataTransport/GDTLibrary/GDTReachability.m
GoogleDataTransport/GDTLibrary/GDTStorage.m
GoogleDataTransport/GDTLibrary/GDTTransformer.m
GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
GoogleDataTransport/GDTLibrary/Public/GDTConsoleLogger.h
GoogleDataTransport/GDTLibrary/Public/GoogleDataTransport.h
GoogleDataTransport/GDTTests/Unit/GDTTransformerTest.m
GoogleDataTransport/GDTTests/Unit/GDTUploadPackageTest.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m

Should infrequently log to the console in !NDEBUG builds instead of asserting.
Fixes 3530

Remove asserts and replace with GDTLogs

---

Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.c
Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.h
Firebase/CoreDiagnostics/ProtoSupport/Protos/firebasecore.proto

None of these fields were collecting information, but they shouldn't be in the proto until they're used.

Remove fields that are currently unused.

---

FirebaseCoreDiagnostics.podspec
GoogleDataTransport.podspec
GoogleDataTransportCCTSupport.podspec

Results of a command line merge

Release 6.6.0 - GDT Patch update

---

Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
Firebase/DynamicLinks/FIRDynamicLinks.m

Add support for initializing custom domains without Core. 

---

GoogleDataTransport/GDTLibrary/GDTPlatform.m

Fix tvOS 13 build break

---

GoogleDataTransport/GDTLibrary/GDTStorage.m
GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
GoogleDataTransport/GDTTests/Unit/GDTClockTest.m
GoogleDataTransport/GDTTests/Unit/GDTEventTest.m
GoogleDataTransport/GDTTests/Unit/GDTStorageTest.m
GoogleDataTransport/GDTTests/Unit/GDTUploadPackageTest.m

I squashed and merged the wrong PR
Reverts firebase/firebase-ios-sdk#3525

Revert "Build GDT for Catalyst"

---

GoogleDataTransport/GDTLibrary/GDTStorage.m
GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
GoogleDataTransport/GDTTests/Unit/GDTClockTest.m
GoogleDataTransport/GDTTests/Unit/GDTEventTest.m
GoogleDataTransport/GDTTests/Unit/GDTStorageTest.m
GoogleDataTransport/GDTTests/Unit/GDTUploadPackageTest.m

Reverts firebase/firebase-ios-sdk#3560
The changes LGTM.

Revert "Revert "Build GDT for Catalyst""

---

Firestore/Example/Tests/SpecTests/json/limit_spec_test.json

Update spec tests from JS master.

Update spec tests

---

FirebaseABTesting/Sources/FIRExperimentController.m
FirebaseABTesting/Sources/Public/FIRLifecycleEvents.h

Fix a typo

---

Firebase/Messaging/FIRMessagingCodedInputStream.m

Fix recent analyzer regressions

---

scripts/make_release_notes.py

Renders
```
- [changed] Cleaned up the documents, unused macros, and folders. (#3490, #3537, #3556, #3498)
- [changed] Updated the header path to pod repo relative. (#3527)
- [fixed] Fix singleton functionality after a FirebaseApp is deleted and recreated. (#3411)
```
as
```
* {{changed}} Cleaned up the documents, unused macros, and folders. ([#3490](//github.com/firebase/firebase-ios-sdk/issues/3490), [#3537](//github.com/firebase/firebase-ios-sdk/issues/3537), [#3556](//github.com/firebase/firebase-ios-sdk/issues/3556), [#3498](//github.com/firebase/firebase-ios-sdk/issues/3498))
* {{changed}} Updated the header path to pod repo relative. ([#3527](//github.com/firebase/firebase-ios-sdk/issues/3527))
* {{fixed}} Fix singleton functionality after a FirebaseApp is deleted and recreated. …
```

Update make_release_notes to support list of issues

---

.travis.yml

Building the swift file added in #3579 fails with the --use-libraries test in the cron job.

Fix cron breakage triggered by new Swift tests

---

Example/Auth/AuthSample/Podfile
Example/Podfile

Fix CI until FirebaseAuth supports GoogleSignIn 5.

Lock GoogleSignIn to major version 4

---

Firebase/InAppMessagingDisplay/FIRIAMDefaultDisplayImpl.m

FIRIAMDefaultDisplayImpl: return earlier when bundleURL == nil

---

Firebase/InAppMessagingDisplay/FIRIAMDefaultDisplayImpl.m

Release 6.7.0 cherry pick: FIRIAMDefaultDisplayImpl: return earlier when bundleURL == nil

---

Firestore/Source/API/FSTFirestoreComponent.mm

Addresses the EXC_BAD_ACCESS hit in https://github.com/firebase/firebase-ios-sdk/issues/3606

Provide a helpful error if FIROptions.projectID is missing.

---

Example/Auth/AuthSample/Podfile
Example/Auth/Sample/GoogleAuthProvider.m
Example/Podfile

Add support of GSI 5

---

Firebase/InAppMessagingDisplay/FIRIAMDefaultDisplayImpl.m

Addresses #3558, see [Maksym's last comment](https://github.com/firebase/firebase-ios-sdk/issues/3558#issuecomment-522042183).

Fetch view resource bundle in main thread for thread safety

---

Firebase/InAppMessagingDisplay/FIRIAMDefaultDisplayImpl.m

Cherry pick 6.7.0: Fetch view resource bundle in main thread for thread safety.

---

GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTLibrary/GDTStorage.m
GoogleDataTransport/GDTLibrary/Private/GDTStorage_Private.h
GoogleDataTransport/GDTLibrary/Public/GDTPlatform.h
GoogleDataTransport/GDTTests/Lifecycle/GDTLifecycleTest.m
GoogleDataTransport/GDTTests/Unit/GDTStorageTest.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m

6.7.0 Cherry pick: Fix backgrounding in GDTStorage #3627

---

GoogleDataTransport/GDTLibrary/GDTPlatform.m
GoogleDataTransport/GDTLibrary/GDTStorage.m
GoogleDataTransport/GDTLibrary/GDTTransformer.m
GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
GoogleDataTransport/GDTLibrary/Private/GDTStorage_Private.h
GoogleDataTransport/GDTTests/Unit/GDTStorageTest.m

Cherry pick #3633 to 6.7.0 release

More safely manage background tasks (#3633)

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/FSTTransactionTests.mm
Firestore/Source/Core/FSTFirestoreClient.mm
Firestore/Source/Core/FSTSyncEngine.mm
Firestore/core/src/firebase/firestore/core/transaction_runner.h
Firestore/core/src/firebase/firestore/core/transaction_runner.mm
Firestore/core/src/firebase/firestore/remote/exponential_backoff.cc
Firestore/core/src/firebase/firestore/remote/exponential_backoff.h
Firestore/core/src/firebase/firestore/util/async_queue.cc
Firestore/core/src/firebase/firestore/util/async_queue.h

Porting from [Android](https://github.com/firebase/firebase-android-sdk/pull/698) and [web](https://github.com/firebase/firebase-js-sdk/pull/2063).

Retrying transactions with backoff

---

Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/src/firebase/firestore/remote/serializer.h
Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Firestore/core/test/firebase/firestore/testutil/testutil.h

Also, some light cleanup of the serializer and tests.

Add serializer support for transform mutations

---

.travis.yml

This reverts commit 6f537bf10a43833bac343e65ff5b4ca7d0c78771.

Revert "Disable Firestore xcodebuild with tsan (#3628)"

---

FirebaseFirestore.podspec
Firestore/CHANGELOG.md

Did a command line merge to resolve conflicts and get the diffs clean

Merge 6.7.0 patch 1

---

Firestore/core/src/firebase/firestore/local/local_serializer.cc
Firestore/core/src/firebase/firestore/model/CMakeLists.txt
Firestore/core/src/firebase/firestore/model/mutation.cc
Firestore/core/src/firebase/firestore/model/mutation.h
Firestore/core/src/firebase/firestore/model/mutation_batch.cc
Firestore/core/src/firebase/firestore/model/mutation_batch.h
Firestore/core/src/firebase/firestore/model/mutation_batch_result.cc
Firestore/core/src/firebase/firestore/model/mutation_batch_result.h
Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/test/firebase/firestore/local/local_serializer_test.cc

Also complete C++ local serializer support for mutation batches.

Complete implementation of C++ MutationBatch

---

FirebaseRemoteConfig.podspec
FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m

Cherry pick #3717 to fix Remote Config `pod spec lint`

6.8.0 cherry pick RemoteConfig #3717

---

ZipBuilder/Sources/ZipBuilder/CocoaPod.swift
ZipBuilder/Sources/ZipBuilder/main.swift

This removes some unnecessary code due to previously duplicated
frameworks, woo!

Update packaging of MLKit pods.

---

Firestore/Source/Public/FIRCollectionReference.h
Firestore/Swift/Source/Codable/CollectionReference+WriteEncodable.swift
Firestore/Swift/Source/Codable/Transaction+WriteEncodable.swift
Firestore/Swift/Source/Codable/WriteBatch+WriteEncodable.swift
Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift

I hit a bunch of minor snags while implementing firebase/quickstart-ios#787.

Fixes for the Codable API

---

FirebaseABTesting/Sources/FIRExperimentController.m

Iterate from array copy in `latestExperimentStartTimestampBetweenTimestamp:andPayloads:`

---

Firebase/Core/FIRComponentContainer.m
FirebaseABTesting/Sources/FIRExperimentController.m

Release 6.8.0: cherry pick of #3764 and #3766

---

Firebase/DynamicLinks/CHANGELOG.md

Update FDL CHANGELOG

---

Firebase/Storage/CHANGELOG.md
Firebase/Storage/FIRStorageUploadTask.m

Fix SIGSEGV in callback after block is nil'd

---

Firebase/DynamicLinks/CHANGELOG.md
Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m

Follow up to #3722 and #3723 for UIWebViewDelegate in addition to UIWebView

Remove UIWebViewDelegate references

---

InAppMessaging/Example/Tests/FIRIAMFetchResponseParserTests.m

To sync up with internal repo.

Fix typos in FIRIAMFetchResponseParserTests

---

GoogleDataTransport.podspec

Remove app_spec from GDT

---

GoogleDataTransport.podspec
GoogleDataTransport/GDTTestApp/app.swift
GoogleDataTransport/GDTTestApp/gdthelpers.swift
GoogleDataTransport/GDTTestApp/viewcontroller.swift

Also address GDT renaming in the test app.

Enable app_specs and monkey test if GDT_DEV is 1

---

Firestore/Source/Local/FSTLocalStore.mm

If there is a chance that a limbo resolution fails for a document that no longer exists, we could get into a state where we write a document into the RemoteDocumentCache with a snapshot version of zero. By re-ordering the statements, we make sure this does not happen
Port of firebase/firebase-android-sdk#802

Change the order of checks in applyRemoteEvent()

---

Example/Core/Tests/FIRAppTest.m
Example/Core/Tests/FIROptionsTest.m
Firebase/Core/FIRApp.m
Firebase/Core/FIROptions.m
Firebase/Core/Private/FIROptionsInternal.h
Metrics/Tests/MetricsTests/example_report.json

fixed "expiclitlySet" typo.

---

GoogleUtilities/Network/GULMutableDictionary.m

Fix GULMutableDictionary keyed subscript methods

---

Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
Firestore/Example/Tests/SpecTests/json/collection_spec_test.json
Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
Firestore/Example/Tests/SpecTests/json/orderby_spec_test.json
Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
Firestore/Example/Tests/SpecTests/json/query_spec_test.json
Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
Firestore/Example/Tests/SpecTests/json/resume_token_spec_test.json
Firestore/Example/Tests/SpecTests/json/write_spec_test.json

Porting from [android](https://github.com/firebase/firebase-android-sdk/pull/810).

Rename spec test functions

---

Firestore/Source/Public/FIRDocumentSnapshot.h

Fix typos in FIRDocumentSnapshot.h

---

Firestore/Source/Public/FIRDocumentSnapshot.h

Better fix for typos in FIRDocumentSnapshot.h

---

Firestore/third_party/FirestoreEncoder/JSONEncoder.swift
Firestore/third_party/FirestoreEncoder/LICENSE
Firestore/third_party/FirestoreEncoder/METADATA

From
https://github.com/apple/swift/commit/3391b746d9fb36d7bbf428bdc3f5f69e2bb9ac6f
pulled with the tag swift-DEVELOPMENT-SNAPSHOT-2019-09-04-a.
This is an initial import that we intend to modify heavily to implement an entirely different kind of serialization.
Note that this does not build yet and is not part of any podspec that would otherwise deliver to an end user so this can't conflict with the standard library in its current form.

Pristine copy of JSONEncoder.swift

---

GoogleUtilities/Example/Tests/Network/GULNetworkTest.m
GoogleUtilities/Network/GULNetworkURLSession.m

Currently,  GULNetworking doesn't receive the data when sending a POST request. 
Tracked internally at b/141712804

Fix Networking to receive data for POST requests

---

Firebase/InAppMessagingDisplay/ImageOnly/FIDImageOnlyViewController.m
Firebase/InAppMessagingDisplay/Modal/FIDModalViewController.m

For Modal and ImageOnly messages
Fixes #3948

Factor in space for top safe area insets into max height calculations

---

GoogleDataTransportCCTSupport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m
GoogleDataTransportCCTSupport/GDTCCTTests/Integration/GDTFLLIntegrationTest.m

Hopefully this should reduce flakiness.

Allow for multiple uploads during CCT Test.

---

Firebase/Database/CHANGELOG.md
Firebase/Database/third_party/SocketRocket/FSRWebSocket.m
FirebaseDatabase.podspec
Releases/Manifests/6.10.0.json

Cherrypicked to fix an iOS 13 issue.

Cherrypick #3983 and include Database in release.

---

Releases/update-versions.py

This should work, but the M58 release lead should confirm.

Simplify update-versions script with --use-json

---

Firestore/core/src/firebase/firestore/core/query.cc
Firestore/core/src/firebase/firestore/core/query.h
Firestore/core/test/firebase/firestore/core/query_test.cc

Ports https://github.com/firebase/firebase-js-sdk/pull/2166

Add Query.MatchesAllDocuments()

---

Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Benchmarks_iOS.xcscheme
Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
Firestore/core/src/firebase/firestore/local/leveldb_lru_reference_delegate.mm
Firestore/core/src/firebase/firestore/local/local_store.mm
Firestore/core/src/firebase/firestore/local/memory_lru_reference_delegate.cc
Firestore/core/src/firebase/firestore/local/query_data.cc
Firestore/core/src/firebase/firestore/local/query_data.h
Firestore/core/src/firebase/firestore/remote/remote_store.mm

Port of https://github.com/firebase/firebase-js-sdk/pull/2148

Add QueryData.with() helpers

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj

Occasionally Xcode will save these out--I can't predict when.

Project updates for recently added/moved files

---

Firestore/Swift/Source/Codable/ExplicitNull.swift
Firestore/Swift/Tests/Codable/FirestoreEncoderTests.swift
Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift
Firestore/third_party/FirestoreEncoder/FirestoreEncoder.swift
scripts/style.sh

Also, minor tweaks to style.sh reflecting an updated source layout.
* Firestore/Port was removed some time ago
* The encoder moved from Firestore/Swift/Source/third_party to
Firestore/third_party/FirestoreEncoder

Fix formatting that was somehow ignored

---

.travis.yml
GoogleDataTransport.podspec
GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
GoogleDataTransportCCTSupport.podspec
GoogleDataTransportCCTSupport/CHANGELOG.md
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTFLLUploader.m
GoogleDataTransportCCTSupport/GDTCCTTestApp/app.swift

This PR is for an out of band release.
GDT: 3.0.0 -> 3.0.1
GDTCCT: 1.2.0 -> 1.2.1

Cherry pick GDT and GDTCCT fixes into release-6.10.0

---

Firebase/Core/CHANGELOG.md

I'm not sure there's a better place to put Firebase pod release notes ...

FirebaseCore M58 release notes

---

Example/InstanceID/Tests/FIRInstanceIDTest.m
Example/Messaging/Tests/FIRInstanceIDWithFCMTest.m
Firebase/InstanceID/FIRInstanceID.m

- IID implementation updated to reflect the changes from master

FirebaseInstallation: merge master into FIS integration branch

---

Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential.m
Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential_Internal.h
Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m
Firebase/Auth/Source/Backend/FIRAuthBackend.m
Firebase/Auth/Source/Backend/RPC/FIRVerifyAssertionRequest.h
Firebase/Auth/Source/Backend/RPC/FIRVerifyAssertionRequest.m
Firebase/Auth/Source/Public/FIRAuthErrors.h
Firebase/Auth/Source/Public/FIROAuthProvider.h
Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.h
Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
Firebase/Auth/Source/Utilities/FIRAuthInternalErrors.h

Reverts firebase/firebase-ios-sdk#4071

Revert "Add OIDC nonce support"

---

.travis.yml

Disable until the issues discussed in #4084 and #4085 are resolved.

Disable Xcode 8.3 tests

---

Firestore/CHANGELOG.md
Firestore/core/src/firebase/firestore/core/firestore_client.h
Firestore/core/src/firebase/firestore/core/firestore_client.mm

This is a cherry-pick of #4091 into the release-6.11.0 branch.

Fix potential race during client initialization (#4091)

---

.travis.yml
Dangerfile

Fixes PRs not being auto-tagged and changelog checking always warning even if a changelog was modified.
Also fixes an issue where danger would error on PRs from forks.
#no-changelog

Fix issue where danger filepath match wasn't matching anything

---

Dangerfile

Reduce bot spam where it's unhelpful.

[danger] Don't check changelogs on non-source changes

---

.travis.yml

Like https://travis-ci.org/firebase/firebase-ios-sdk/jobs/599808570

Add travis_retry to mitigate impact of GDTCCT flakes

---

.travis.yml

- needed to fix failures like this https://travis-ci.org/firebase/firebase-ios-sdk/jobs/600742613
#no-changelog

Travis: install particular version of clang-format and swiftformat.

---

.travis.yml

Today the Xcode 10.1 configuration started using Xcode 9.4.1
See https://travis-ci.org/firebase/firebase-ios-sdk/builds/600755091

Switch to Xcode 10.2 since travis 10.1 config is broken

---

README.md

Update README for Firebase pod for mac/tv

---

Firebase/Auth/CHANGELOG.md
FirebaseRemoteConfig/CHANGELOG.md
Firestore/CHANGELOG.md
scripts/make_release_notes.py

Update changelogs for M58

---

ZipBuilder/Sources/UpdateFirebasePod/FirebasePod.swift
ZipBuilder/Sources/UpdateFirebasePod/LaunchArgs.swift
ZipBuilder/Sources/UpdateFirebasePod/main.swift
scripts/style.sh

These didn't get flagged with your last PR.

style.sh generated changes

---

FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIIDStoreTests.m

- the fix with tests
- some minor refactoring and tests cleanup
b/143211972

FIS: Make sure refreshed auth token is stored to the storage.

---

Firestore/core/src/firebase/firestore/local/local_store.mm
Firestore/core/test/firebase/firestore/local/remote_document_cache_test.mm
Firestore/core/test/firebase/firestore/testutil/testutil.h

The tests are all just broken in the branch.

Unit test fixes

---

Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
Firestore/Source/API/FIRQuery+Internal.h
Firestore/Source/API/FIRQuery.mm
Firestore/core/src/firebase/firestore/api/query_core.mm

Now that the method signature requires an `NSArray`, the type check should be an assertion.

Change id to NSArray<id> for IN queries

---

kokoro/README.md
kokoro/macos_external/continuous.sh

Whitespace violation and missing license header

Fix formatting breakage

---

Firebase.podspec
FirebaseCore.podspec

FirebaseCore version bump to 6.3.3

---

Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential.m
Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential_Internal.h
Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m
Firebase/Auth/Source/Backend/FIRAuthBackend.m
Firebase/Auth/Source/Backend/RPC/FIRVerifyAssertionRequest.h
Firebase/Auth/Source/Backend/RPC/FIRVerifyAssertionRequest.m
Firebase/Auth/Source/Public/FIRAuthErrors.h
Firebase/Auth/Source/Public/FIROAuthProvider.h
Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.h
Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
Firebase/Auth/Source/Utilities/FIRAuthInternalErrors.h

Release 6.12.0: cherry pick of #4220

---

Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
Firestore/core/src/firebase/firestore/core/user_data.cc

Port of firebase/firebase-android-sdk#643.
Also make error messages align with Android's.

Disallow empty document fields

---

FirebaseAuth.podspec

Release 6.12.0: Revert Auth podspec version bump.

---

Firebase.podspec
scripts/check_whitespace.sh

- Firebase.podspec FirebaseAuth pod version reverted
- cherry-pick #4231

6.12.0: Firebase.podspec FirebaseAuth pod version reverted, cherry-pick #4231

---

Firestore/Source/API/FIRQuery.mm
Firestore/Source/Public/FIRQuery.h

See the linked CL for details.
#no-changelog

Update header docs based on feedback in cr/278458897

---

Carthage.md

Clarify an ambiguous Carthage instruction

---

.travis.yml
FirebaseInstallations.podspec
FirebaseInstallations/Source/Library/FIRInstallations.m

- throw and exception if FIS is used with an incompatible IID version.
b/144091500

FIS: IID incompatible version exception.

---

Firestore/Example/GoogleTest.podspec
Firestore/core/test/firebase/firestore/immutable/sorted_map_test.cc
Firestore/core/test/firebase/firestore/local/leveldb_index_manager_test.cc
Firestore/core/test/firebase/firestore/local/leveldb_query_cache_test.cc
Firestore/core/test/firebase/firestore/local/leveldb_remote_document_cache_test.cc
Firestore/core/test/firebase/firestore/local/memory_index_manager_test.cc
Firestore/core/test/firebase/firestore/local/memory_query_cache_test.cc
Firestore/core/test/firebase/firestore/local/memory_remote_document_cache_test.cc
Firestore/core/test/firebase/firestore/local/query_cache_test.h
Firestore/core/test/firebase/firestore/local/remote_document_cache_test.h
Firestore/core/test/firebase/firestore/util/async_queue_libdispatch_test.mm
Firestore/core/test/firebase/firestore/util/async_queue_std_test.cc
Firestore/core/test/firebase/firestore/util/executor_libdispatch_test.mm
Firestore/core/test/firebase/firestore/util/executor_std_test.cc
cmake/external/googletest.cmake

TYPED_TEST_CASE and friends have been renamed TYPED_TEST_SUITE.
#no-changelog

Upgrade GoogleTest to 1.10.0

---

Firestore/CHANGELOG.md

Add a changelog entry on `Protobuf` removal.

---

Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential.m
Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential_Internal.h
Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m
Firebase/Auth/Source/Backend/FIRAuthBackend.m
Firebase/Auth/Source/Backend/RPC/FIRVerifyAssertionRequest.h
Firebase/Auth/Source/Backend/RPC/FIRVerifyAssertionRequest.m
Firebase/Auth/Source/Public/FIRAuthErrors.h
Firebase/Auth/Source/Public/FIROAuthProvider.h
Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.h
Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
Firebase/Auth/Source/Utilities/FIRAuthInternalErrors.h

Reverts firebase/firebase-ios-sdk#4220

Revert "Revert "Add OIDC nonce support""

---

Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
Firestore/Source/API/FIRQuery.mm
Firestore/Source/API/FSTUserDataConverter.h
Firestore/Source/API/FSTUserDataConverter.mm
Firestore/core/src/firebase/firestore/core/user_data.cc
Firestore/core/src/firebase/firestore/core/user_data.h

Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/2346) and [android](https://github.com/firebase/firebase-android-sdk/pull/970).

Allow querying for arrays in IN queries

---

README.md

Added link to missing tools required to start contributing.
#no-changelog

Add cocoapods-generate to dev instructions

---

Firebase/Auth/CHANGELOG.md

Reflecting changes in cr/280280161.

Update Auth changelog

---

FirebaseCore.podspec
GoogleUtilities.podspec

Update versions for heartbeat PR

---

InAppMessaging/Example/Podfile
InAppMessagingDisplay/Example/Podfile

Fix Podfile issue exposed by version changes in #4098

Fix CI regression in FIAM from Google Utilities changes

---

Example/Core/Tests/FIRComponentContainerTest.m

Fix #4343 incorrect OCMock test.

---

scripts/run_firestore_emulator.sh

This fixes several flakes in the integration tests.

Upgrade Firestore emulator to 1.10.2

---

.travis.yml
Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
FirebaseCoreDiagnostics.podspec
GoogleDataTransport.podspec
GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h
GoogleDataTransportCCTSupport.podspec
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTFLLUploader.m
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTFLLUploaderTest.m
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.h
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.m

- cherry pick #4196
- CoreDiagnostic version bump 1.1.2

Cherry pick of #4196 to 6.13.0 for patch CoreDiagnostics release

---

.travis.yml
Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
FirebaseCoreDiagnostics.podspec
GoogleDataTransport.podspec
GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h
GoogleDataTransportCCTSupport.podspec
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTFLLUploader.m
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTFLLUploaderTest.m
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.h
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.m

- cherry pick #4362
- bump CoreDiagnostic version 1.1.2

Cherry pick of #4196 to 6.13.1 for patch CoreDiagnostics release

---

.travis.yml
scripts/build.sh
scripts/if_changed.sh
scripts/install_prereqs.sh

Incremental step towards reducing backlogs by merging commonly associated builds
#no-changelog

travis job consolidation for Core, GDT, and FIAM

---

GoogleUtilitiesComponents/Tests/GULCCComponentContainerTest.m

Fixes #4350 following the same as #4346
#no-changelog

Fix incorrect OCMock usage

---

FirebaseInstallations.podspec
FirebaseInstallations/Source/Tests/Unit/FIRSecureStorageTests.m

Fix OCMock issues with FIS

---

ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift

Add an option to specify the architectures for the slices in the framework binaries.
#no-changelog

Add archs option to ZipBuilder

---

ZipBuilder/Sources/ZipBuilder/ModuleMapBuilder.swift

By sorting framework and library lists

Make module map build deterministic

---

ZipBuilder/ZipBuilderV2Plan.md

Zip Builder V2 Doc with Implementation summary

---

ZipBuilder/README.md
ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
ZipBuilder/Sources/ZipBuilder/FirebaseBuilder.swift
ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
ZipBuilder/Sources/ZipBuilder/main.swift
ZipBuilder/ZipBuilderV2Plan.md

Add the -zipPods option documented at https://github.com/firebase/firebase-ios-sdk/blob/master/ZipBuilder/ZipBuilderV2Plan.md
A subsequent PR will review classes, comments, and variables for proper distinguishing between Firebase-specific and generic pods -> zipped binary frameworks.
Testing: Validated -zipPods for an input json file and validated the Firebase build still had the correct structure.

ZipBuilder: -zipPods option

---

ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
ZipBuilder/Sources/ZipBuilder/FirebasePods.swift
ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift

Since this file is specific to Firebase Pods.  
Note that the singular version is not a good option since it would be confused with THE Firebase pod.

Rename CocoaPod.swift to FirebasePods.swift

---

Example/Core/Tests/FIRAppTest.m
Firebase/Core/CHANGELOG.md
Firebase/Core/FIRApp.m
Firebase/Core/FIROptions.m

Lazily register for Core's user agent

---

Firebase/Core/CHANGELOG.md

What if anything should be added for the heartbeat and Swift logging changes?

M61 Core Changelog

---

Firebase/InAppMessaging/CHANGELOG.md

Hoping to get https://github.com/firebase/firebase-ios-sdk/pull/4446 in before the freeze.

In-App Messaging CHANGELOG for M61

---

Firebase/Core/FIRHeartbeatInfo.m

Fix non-standard import

---

ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift
ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
ZipBuilder/Sources/ZipBuilder/FileManager+Utils.swift
ZipBuilder/Sources/ZipBuilder/FirebasePods.swift
ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
ZipBuilder/Sources/ZipBuilder/HashCalculator.swift
ZipBuilder/Sources/ZipBuilder/ModuleMapBuilder.swift
ZipBuilder/Sources/ZipBuilder/ResourcesManager.swift
ZipBuilder/Sources/ZipBuilder/URL+Utils.swift
ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift

Package visibility is sufficient.

ZipBuilder: Remove unnecessary public's

---

Firestore/Example/Tests/Util/FSTHelpers.h
Firestore/Example/Tests/Util/FSTHelpers.mm

Some of these need changes for Index-Free, but they are unused, so I'd rather remove them.

Remove unused test helpers

---

ZipBuilder/README.md

Flush out Zip Builder release docs

---

Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h

Add NS_SWIFT_NAME for FIRInAppMessagingCampaignInfo

---

GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m

Release 6.14.0 cherry pick of #4498

---

Example/Podfile
Firebase.podspec
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseDatabase.podspec
FirebaseDynamicLinks.podspec
FirebaseFirestore.podspec
FirebaseInAppMessaging.podspec
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
FirebaseRemoteConfig.podspec
FirebaseStorage.podspec
Firestore/Example/Podfile
GoogleDataTransportCCTSupport.podspec
GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
Releases/Manifests/6.14.0.json
Releases/update-versions.py
SymbolCollisionTest/Podfile
ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift

Release 6.14.0

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
Firestore/Source/API/FIRDocumentSnapshot.mm
Firestore/Source/API/FIRFirestore.mm
Firestore/core/src/firebase/firestore/api/collection_reference.cc
Firestore/core/src/firebase/firestore/api/collection_reference.h
Firestore/core/src/firebase/firestore/api/document_reference.cc
Firestore/core/src/firebase/firestore/api/document_snapshot.cc
Firestore/core/src/firebase/firestore/api/document_snapshot.h
Firestore/core/src/firebase/firestore/api/firestore.cc
Firestore/core/src/firebase/firestore/api/firestore.h
Firestore/core/src/firebase/firestore/api/query_snapshot.cc
Firestore/core/src/firebase/firestore/core/firestore_client.cc
Firestore/core/src/firebase/firestore/core/transaction.h
Firestore/core/src/firebase/firestore/core/transaction_runner.cc
Firestore/core/src/firebase/firestore/core/transaction_runner.h
Firestore/core/src/firebase/firestore/model/document.h
Firestore/core/src/firebase/firestore/model/document_key.h
Firestore/core/src/firebase/firestore/model/field_path.cc
Firestore/core/src/firebase/firestore/model/field_path.h
Firestore/core/src/firebase/firestore/model/field_value.cc
Firestore/core/src/firebase/firestore/model/field_value.h
Firestore/core/src/firebase/firestore/model/resource_path.cc
Firestore/core/src/firebase/firestore/model/resource_path.h
Firestore/core/src/firebase/firestore/model/transform_operation.h
Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/src/firebase/firestore/remote/serializer.h
Firestore/core/src/firebase/firestore/util/executor_std.h
Firestore/core/test/firebase/firestore/model/field_value_test.cc
Firestore/core/test/firebase/firestore/testutil/testutil.h

This is everything we've found required to support C++ and Unity based on iOS M61.

Cherry-picks for Firestore 1.8.3

---

README.md

Improve pod gen instructions

---

.travis.yml
FirebaseInstallations.podspec
FirebaseInstanceID.podspec
scripts/if_changed.sh

- FirebaseInstallation version bump to 1.0.0
- `if_changed.sh` updated to reflect IID->FIS dependency
#no-changelog

FirebaseInstallations: prepare IID with FIS dependency for release

---

GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m
GoogleDataTransport/GDTCORLibrary/GDTCORSqlite.m
GoogleDataTransport/GDTCORLibrary/GDTCORStoredEvent.m
GoogleDataTransport/GDTCORLibrary/Public/GDTCOREvent.h
GoogleDataTransport/GDTCORLibrary/Public/GDTCORStoredEvent.h
GoogleDataTransport/GDTCORTests/Unit/GDTCORSqliteTest.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORStoredEventTest.m
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/Helpers/GDTCCTEventGenerator.m

Change custom prioritization dictionary to bytes

---

CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_6_1_frameworks/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_6_1_staticLibs/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_frameworks/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_multiprojects_frameworks/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_multiprojects_staticLibs/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_staticLibs/Podfile

The cron tests started failing last night https://travis-ci.org/firebase/firebase-ios-sdk/builds/628010790
#no-changelog

Update the cron tests for FirebaseInstallations

---

scripts/style.sh

- suggest the brew formula from README
#no-changelog

style.sh: update clang-format formula in suggestions

---

.travis.yml

Travis: don't run FIS integration tests on forks

---

.github/workflows/actions.yml
scripts/check.sh

#no-changelog
Initial GitHub Actions proof of concept.
No rush to merge unless someone is ready to continue ...

Start GitHub Actions

---

.travis.yml

Reverts firebase/firebase-ios-sdk#4566

Revert "Disable broken Auth Api Tests"

---

ZipBuilder/README.md

Fix outdated command name in ZipBuilder docs

---

AddNewPod.md

#no-changelog: Developer docs update.

Add formatting for directories.

---

FirebaseCore/CMakeLists.txt
scripts/if_changed.sh

Fix cmake build regression

---

GoogleDataTransport.podspec
GoogleDataTransport/generate_project.sh
GoogleDataTransportCCTSupport.podspec
GoogleDataTransportCCTSupport/generate_project.sh

Disable project generation for watchOS

---

.github/workflows/cron.yml

No check job in cron

---

scripts/check.sh

Sometimes PRs have been cut from so long ago that there's no merge base
with master in the shallow clone that Travis makes. In this case, fall
back on just checking everything.
This specifically is meant to fix #4602 which is currently failing because of this problem.
/cc @wu-hui

Have check.sh fallback to checking everything

---

Firebase/Messaging/CHANGELOG.md
FirebaseInstallations/CHANGELOG.md

- mention a new FIS dependency with the API Key restriction details
- FIS changelog header format consistent with [FirebaseCore](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCore/CHANGELOG.md)

FirebaseMessaging changelog: FirebaseInstallations

---

Firebase/InstanceID/CHANGELOG.md
Firebase/Messaging/CHANGELOG.md
FirebaseRemoteConfig/CHANGELOG.md

- InstanceID changelog update
- Remote Config changelog update 
- Messaging changelog update (applied suggestion from cl/288732006)

Changelogs for IID-dependent SDKs with FIS details

---

scripts/style.sh

#no-changelog Just a style script update.

Fix `vendor` directory being included in style.sh

---

Example/InstanceID/IntegrationTests/FIRInstanceIDIntegrationTests.m

IID: re-enable deleteID test

---

.travis.yml
Dangerfile
scripts/if_changed.sh
scripts/install_prereqs.sh
scripts/make_release_notes.py

Update scripts to support running CI for Crashlytics.

Enable CI for Crashlytics

---

FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseCoreDiagnostics.podspec
FirebaseCrashlytics.podspec
FirebaseInstallations.podspec
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
GoogleDataTransportCCTSupport.podspec
GoogleUtilities.podspec

Update podspec dependencies for M62

---

CoreOnly/Sources/Firebase.h
CoreOnly/Tests/FirebasePodTest/Podfile
Firebase.podspec

Cherry-pick into the M62 release

Crashlytics add to subspec and Firebase.h (#4634)

---

scripts/if_changed.sh

Crashlytics is in currently located in the `Crashlytics` directory.

Fix if_changed script for Crashlytics

---

Example/Messaging/Tests/FIRMessagingContextManagerServiceTest.m

Fixes failures like [this](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/636182151).
#no-changelog

Messaging: fix distant future date in the tests.

---

Crashlytics/Crashlytics/Helpers/FIRCLSAllocate.c
Crashlytics/Crashlytics/Helpers/FIRCLSFile.m
Crashlytics/Crashlytics/Helpers/FIRCLSUtility.m
Crashlytics/Shared/FIRCLSByteUtility.m
Crashlytics/Shared/FIRCLSMachO/FIRCLSMachOBinary.m

After mallocs, check if the allocations were successful.
The change is a clone from the private repository:
https://github.com/FirebasePrivate/firebase-ios-sdk/pull/595

(Crashlytics) Fix VeraCode scanner issue for: "LOW: Unchecked Error Condition"

---

Firebase.podspec
FirebaseAnalyticsInterop.podspec
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseCoreDiagnostics.podspec
FirebaseCoreDiagnosticsInterop.podspec
FirebaseCrashlytics.podspec
FirebaseDatabase.podspec
FirebaseFirestore.podspec
FirebaseInAppMessaging.podspec
FirebaseInstallations.podspec
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
FirebaseStorage.podspec
Firestore/Example/Podfile
GoogleDataTransport.podspec
GoogleDataTransportCCTSupport.podspec
GoogleUtilities.podspec
Releases/Manifests/6.15.0.json
SymbolCollisionTest/Podfile

#no-changelog
Rebased onto master to update author emails for CLA

Merging the 6.15.0 release into master

---

Firestore/Example/Tests/Integration/FSTTransactionTests.mm
Firestore/Protos/cpp/google/firestore/v1/write.pb.cc
Firestore/Protos/cpp/google/firestore/v1/write.pb.h
Firestore/Protos/nanopb/google/firestore/v1/write.nanopb.cc
Firestore/Protos/nanopb/google/firestore/v1/write.nanopb.h
Firestore/Protos/protos/google/firestore/v1/write.proto
Firestore/core/src/firebase/firestore/core/transaction.cc
Firestore/core/src/firebase/firestore/model/CMakeLists.txt
Firestore/core/src/firebase/firestore/model/mutation.h
Firestore/core/src/firebase/firestore/model/verify_mutation.cc
Firestore/core/src/firebase/firestore/model/verify_mutation.h
Firestore/core/src/firebase/firestore/remote/serializer.cc
Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Firestore/core/test/firebase/firestore/testutil/testutil.h

Porting from [JS](https://github.com/firebase/firebase-js-sdk/pull/2436/files) and [Android](https://github.com/firebase/firebase-android-sdk/pull/1107/files)

Add verify support

---

.travis.yml
Example/InstanceID/Tests/FIRInstanceIDTest.m
Example/Messaging/Tests/FIRMessagingContextManagerServiceTest.m
Example/Messaging/Tests/FIRMessagingInstanceTest.swift
FirebaseInstallations.podspec
FirebaseInstallations/CHANGELOG.md
FirebaseInstallations/Source/Library/FIRInstallations.m
FirebaseInstallations/Source/Library/FIRInstallationsLogger.h
FirebaseInstallations/Source/Library/FIRInstallationsLogger.m
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.h
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
FirebaseInstallations/Source/Library/Public/FIRInstallations.h
FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
FirebaseRemoteConfig/Tests/Unit/FIRRemoteConfigComponentTest.m

- cherry-pick FIS changes (#4683)
- cherry-pick FCM tests fix (#4667)

M62 patch release: cherry pick Firebase Installations changes (#4683)

---

Carthage.md

Add instructions on how to get Crashlytics via Carthage.
#no-changelog

Add Crashlytics to Carthage documentation

---

Carthage.md

XCode -> Xcode

---

GoogleDataTransport/GDTCORLibrary/GDTCORConsoleLogger.m
GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m
GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m
GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
GoogleDataTransport/GDTCORLibrary/GDTCORReachability.m
GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m
GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m
GoogleDataTransport/GDTCORLibrary/GDTCORTransport.m
GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
GoogleDataTransport/GDTCORLibrary/GDTCORUploadPackage.m
GoogleDataTransport/GDTCORLibrary/Public/GDTCORConsoleLogger.h
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTFLLPrioritizer.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTFLLUploader.m
GoogleDataTransportCCTSupport/GDTCCTTestApp/app.swift

This is to help adopters understand what the state of the library is

Add extensive debug logging

---

Crashlytics/CHANGELOG.md

Reviewer: @RelaxedPear
Change: https://github.com/firebase/firebase-ios-sdk/pull/4669

Crashlytics 4.0.0-beta.2 CHANGELOG

---

ZipBuilder/Sources/ZipBuilder/FirebasePods.swift
ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift

This resulted in a proper Zip build for me using the latest release manifests.

Ignore FIAMDisplay in Zip file.

---

README.md

Badges for GitHub Actions

---

FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m
FirebaseInAppMessaging/Sources/Data/FIRIAMMessageDefinition.m
FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
FirebaseInAppMessaging/Sources/Private/Data/FIRIAMMessageDefinition.h
FirebaseInAppMessaging/Sources/Public/FIRInAppMessagingRendering.h
FirebaseInAppMessaging/Sources/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m
FirebaseInAppMessaging/Sources/RenderingObjects/FIRInAppMessagingRenderingPrivate.h
FirebaseInAppMessaging/Tests/Unit/FIRIAMDisplayExecutorTests.m
FirebaseInAppMessaging/Tests/Unit/FIRIAMFetchResponseParserTests.m
FirebaseInAppMessaging/Tests/Unit/TestJsonDataFromFetch.txt

data bundles for consolidated sdk

---

FirebaseInAppMessaging/Sources/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m

added pragma statement to ignore initWithMessageID deprecation warning

---

GoogleUtilities/CHANGELOG.md

GoogleUtilities - add version to the changelog.

GUL changelog 6.5.1

---

Firebase.podspec
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseCrashlytics.podspec
FirebaseFirestore.podspec
FirebaseInAppMessaging.podspec
FirebaseInAppMessagingDisplay.podspec
Firestore/Example/Podfile
GoogleDataTransport.podspec
GoogleDataTransportCCTSupport.podspec
GoogleUtilities.podspec
Releases/Manifests/6.16.0.json

Merge release 6.16.0

---

CMakeLists.txt
Firestore/Example/Tests/SpecTests/CMakeLists.txt
Firestore/core/src/firebase/firestore/local/leveldb_target_cache.cc
Firestore/core/test/firebase/firestore/core/field_filter_test.cc
cmake/cc_rules.cmake

Also, fix the build when you configure it with a relative path.
All issues were exposed trying to build Firestore on GitHub Actions.
#no-changelog

Fix the Linux build under GCC 7.4.0

---

ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift

Green CI for xcframework-master branch

---

GoogleDataTransport/GDTCORLibrary/Public/GDTCORTargets.h
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTPrioritizer.h
GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTUploader.h
GoogleDataTransportCCTSupport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTPrioritizerTest.m
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTUploaderTest.m

The same object will now manage all 3 backends

Consolidate the CCT, FLL, and new CSH backends

---

CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_6_1_frameworks/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_6_1_staticLibs/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_frameworks/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_multiprojects_frameworks/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_multiprojects_staticLibs/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_staticLibs/Podfile
Crashlytics/Crashlytics/DataCollection/FIRCLSDataCollectionArbiter.m

Fixes https://github.com/firebase/firebase-ios-sdk/issues/4785

Crashlytics fix import declaration of FIRApp.h

---

README.md

Remove the deleted CRON tag, add GDT and Zip
#no-changelog

Update README badges for GitHub Actions

---

FirebaseCore/Sources/FIRHeartbeatInfo.m
FirebaseCore/Tests/Unit/FIRHeartbeatInfoTest.m

use 1 less 0 so that it sends every day as per to once in 100 days

fix heartbeat

---

.github/workflows/check.yml
.github/workflows/firestore.yml
scripts/setup_check.sh

Add a GitHub Actions workflow for Firestore

---

GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m
GoogleDataTransport/GDTCORLibrary/GDTCORTransport.m
GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage.h
GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer.h
GoogleDataTransport/GDTCORLibrary/Public/GDTCORTransport.h
GoogleDataTransport/GDTCORTests/Unit/GDTCORStorageTest.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORTransformerTest.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORTransportTest.m

Add a storage completion handler to the event transport pipeline

---

GoogleDataTransport/GDTTestApp/app.swift
GoogleDataTransport/GDTTestApp/ios/Main.storyboard
GoogleDataTransportCCTSupport/GDTCCTTestApp/ios/Main.storyboard

Fixed iOS testapp dark mode

---

.github/workflows/zip.yml

Don't run zip workflow on markdown changes.

---

Firebase/Messaging/CHANGELOG.md
Firebase/Messaging/FIRMessagingPendingTopicsList.h
Firebase/Messaging/FIRMessagingPendingTopicsList.m
Firebase/Messaging/FIRMessagingPubSub.m

Use secure encoding for messaging's pending topics

---

FirebaseFirestore.podspec

Firestore 1.10.1 version update

---

.travis.yml

Remove:
* pod-lib-lint
* cmake builds
* Xcode 11 xcodebuild
* Xcode 11 sanitizers
What remains:
* Xcode 11 quickstart
* Xcode 10.3 xcodebuild

Remove most Firestore builds from Travis

---

.github/workflows/core.yml
.github/workflows/datatransport.yml
.travis.yml

Remove travis jobs now running in GHA

---

.github/workflows/core.yml
.github/workflows/datatransport.yml

Fix cron bug introduced in #4846

Dashes in pod lib lint options

---

.github/workflows/dynamiclinks.yml

only ios for FDL

---

Firebase/CoreDiagnostics/CHANGELOG.md
Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
Firebase/CoreDiagnostics/generate_project.sh
FirebaseCoreDiagnostics.podspec
GoogleDataTransportCCTSupport/CHANGELOG.md
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m

Also make FIRCoreDiagnostics project generable again
Fixes #4871 
Fixes #4872

Fix checking the result of malloc

---

GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORStorageTest.m

Fixes #4546
Thanks @plu for the test case!

Fixes appWillTerminate not running on GDTStorage's queue

---

Firebase.podspec
FirebaseCore.podspec
FirebaseCrashlytics.podspec
FirebaseDynamicLinks.podspec
FirebaseFirestore.podspec
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
FirebaseRemoteConfig.podspec
GoogleDataTransport.podspec
GoogleDataTransportCCTSupport.podspec
Releases/Manifests/6.17.0.json

Merge 6.17.0

---

FirebaseRemoteConfig.podspec
FirebaseRemoteConfig/CHANGELOG.md

Update OCMock version to 3.5 in RC podspec.

---

Firestore/core/src/firebase/firestore/core/sync_engine.cc
Firestore/core/src/firebase/firestore/immutable/sorted_set.h

This is porting https://github.com/firebase/firebase-js-sdk/issues/2620.

Add union_with to sorted set.

---

Firestore/CHANGELOG.md
Firestore/Example/Benchmarks/remote_document_cache_benchmark.mm
Firestore/core/src/firebase/firestore/core/target_id_generator.cc
Firestore/core/src/firebase/firestore/core/target_id_generator.h
Firestore/core/src/firebase/firestore/local/leveldb_persistence.cc
Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.cc
Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.h
Firestore/core/src/firebase/firestore/local/leveldb_target_cache.cc
Firestore/core/src/firebase/firestore/model/document_map.h
Firestore/core/src/firebase/firestore/model/field_mask.h
Firestore/core/src/firebase/firestore/remote/grpc_stream.cc
Firestore/core/src/firebase/firestore/util/CMakeLists.txt
Firestore/core/src/firebase/firestore/util/background_queue.cc
Firestore/core/src/firebase/firestore/util/background_queue.h
Firestore/core/test/firebase/firestore/local/leveldb_lru_garbage_collector_test.cc
Firestore/core/test/firebase/firestore/local/leveldb_remote_document_cache_test.cc
Firestore/core/test/firebase/firestore/local/memory_lru_garbage_collector_test.cc

This is a port of https://github.com/firebase/firebase-android-sdk/pull/559.
This results in a mean speedup across all benchmarks of ~30%.

Decode documents in a background thread

---

FirebaseInAppMessaging/CHANGELOG.md

M65 changelog for FIAM SDK

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Makes the new issue page a lot less uniform.

Add emoji to issue titles

---

Dangerfile

This can then be used in conjunction with eventually adding comments with diffs, etc.
#no-changelog

Add a label when a public API changes

---

ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
ZipBuilder/Sources/ZipBuilder/ModuleMapBuilder.swift

With these changes, it's now possible to build FirebaseUI with the ZipBuilder

Zip Builder support for dependencies through subspecs

---

GoogleDataTransport/README.md
GoogleDataTransportCCTSupport/README.md

Has more and more accurate instructions

Update READMEs for GDT

---

GoogleDataTransport/README.md
GoogleDataTransportCCTSupport/README.md

Fixed some incorrect instructions

Fix README for GDT and GDTCCT

---

Firestore/core/include/firebase/firestore/firestore_version.h

This comment isn't particularly valuable and also creates problems with generated documentation.

Remove extraneous comment

---

Firebase.podspec
FirebaseCore.podspec
FirebaseCoreDiagnostics.podspec
FirebaseFirestore.podspec
FirebaseInAppMessaging.podspec
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
FirebaseRemoteConfig.podspec
GoogleDataTransport.podspec
GoogleDataTransportCCTSupport.podspec
GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTPrioritizer.h
Releases/Manifests/6.18.0.json

Merging the 6.18.0 release into master

---

Example/tvOSSample/Podfile
README.md

minor fix in the README and tvOS podfile

---

CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_6_1_frameworks/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_6_1_staticLibs/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_frameworks/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_multiprojects_frameworks/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_multiprojects_staticLibs/Podfile
CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_staticLibs/Podfile
SymbolCollisionTest/Podfile

Fix failures in[ last night's cron](https://travis-ci.org/firebase/firebase-ios-sdk/builds/658065823)
#no-changelog

Add FirebaseABTesting to travis cron tests

---

Gemfile
Gemfile.lock

CocoaPods 1.9.1

---

Firebase/CoreDiagnostics/CHANGELOG.md
Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
GoogleDataTransportCCTSupport/CHANGELOG.md
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTNanopbHelpers.h

Eliminates use of memcpy and malloc

Address a few potential security issues

---

Example/Messaging/Sample/iOS/Environment.swift
GoogleUtilities/CHANGELOG.md
GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m

Update environment checks

---

FirebaseFirestore.podspec
Firestore/CHANGELOG.md

This is a cherry-pick of #5067 for the release-6.19.0 branch.

Explicitly state Firestore's dependency on UIKit

---

Firestore/fuzzing/fieldpath_fuzzer.cc
Firestore/fuzzing/leveldb_fuzzer.cc
Firestore/fuzzing/resourcepath_fuzzer.cc

It was broken by our transition to avoid Abseil types in signatures.

Fix fuzz build

---

Firebase.podspec

As mentioned in #5089 - thanks @wilhuff!

Bump Firestore version in Firebase.podspec

---

FirebaseABTesting/CHANGELOG.md

Update M66 CHANGELOG

---

scripts/if_changed.sh

Will run Crashlytics tests when there are changes to our dependency

Add Crashlytics to if_changed for GoogleDataTransport changes

---

GoogleUtilities.podspec
GoogleUtilities/CHANGELOG.md

Planning to publish this Monday

GoogleUtilities 6.5.2

---

GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m

Uploaders weren't always retrying in all the situations they should've been, so this hopefully addresses that. Also does a slight readability refactor.

The uploader should retry when there's an error

---

Crashlytics/CHANGELOG.md

Crashlytics changelog v4.0.0-beta.6

---

FirebaseCrashlytics.podspec
GoogleDataTransport.podspec
GoogleDataTransport/CHANGELOG.md
GoogleDataTransportCCTSupport.podspec
GoogleDataTransportCCTSupport/CHANGELOG.md

Update GDT versions, deps, and CHANGELOGs

Update GDT versions, deps, and CHANGELOGs

---

SymbolCollisionTest/Podfile

Fix cron test failure - https://travis-ci.org/github/firebase/firebase-ios-sdk/jobs/663802684
#no-changelog

Fix missing path specs for pods in repo

---

GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m
GoogleDataTransport/GDTCORLibrary/GDTCORTransport.m
GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage.h
GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer.h
GoogleDataTransport/GDTCORLibrary/Public/GDTCORPrioritizer.h
GoogleDataTransport/GDTCORLibrary/Public/GDTCORTransport.h
GoogleDataTransport/GDTCORTests/Integration/Helpers/GDTCORIntegrationTestPrioritizer.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
GoogleDataTransportCCTSupport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m

Cherry picks #5147 onto release-6.21.0

---

.github/workflows/datatransport.yml

Add travis retry to catalyst tests

---

Example/Database/Tests/Integration/FData.m

Add new tests from JS SDK to test online behavior.

Add additional tests

---

.github/workflows/storage.yml

Make secret environment variables job scoped to make the actions more DRY
Tested on forked PR in #5190
#no-changelog

Refactor GHA secret environment variables

---

Firebase/CoreDiagnostics/CHANGELOG.md
GoogleDataTransport/CHANGELOG.md
GoogleDataTransportCCTSupport/CHANGELOG.md

Updates CHANGELOGs using the suggested format

Update GDT associated CHANGELOGs

---

.github/workflows/firestore.yml

Add missing needs to Firestore GHA

---

AddNewPod.md

AddNewPod updates

---

Firestore/Example/Tests/SpecTests/FSTSpecTests.mm

This is a port of the following PR in the Android SDK: https://github.com/firebase/firebase-android-sdk/pull/1367

Add ability to selectively run spec tests via an environment variable.

---

Firestore/Example/Tests/SpecTests/FSTSpecTests.mm

This is a port of the following PR in the Android SDK: https://github.com/firebase/firebase-android-sdk/pull/1373.

Log the total pass and skip count after running all spec tests

---

Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTNanopbHelpersTest.m

Also:
- add a test, confirmed failing without these changes
- rename variable to better represent what it is

getByte into the actual buffer, not into the byte array struct

---

FirebaseCore/CHANGELOG.md
ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift

Fix unincluded umbrella warnings

---

.github/workflows/danger.yml
.travis.yml

Move Danger job from Travis to GitHub Actions.
#no-changelog

Run Danger from GHA

---

Firebase/InstanceID/CHANGELOG.md
Firebase/InstanceID/FIRInstanceID.m

Cherry-picked for M68 release.

add missing return when delete token handler is nil (#5247)

---

Example/Database/Tests/Integration/FData.m
Firebase/Database/Api/FIRServerValue.m
Firebase/Database/Api/FIRServerValue_unreleased.h
Firebase/Database/Core/FRepo.m
Firebase/Database/Core/FServerValues.h
Firebase/Database/Core/FServerValues.m
Firebase/Database/Core/FSyncTree.m

For eventually merging fixes after adding new tests.

[Feature launch] Re-add increment operator

---

Firebase.podspec

Bumped the Firebase pod for MLKit.

---

FirebaseStorageSwift/Tests/Integration/StorageIntegration.swift
Firestore/third_party/FirestoreEncoder/FirestoreDecoder.swift
Firestore/third_party/FirestoreEncoder/FirestoreEncoder.swift
README.md
scripts/setup_check.sh

Update swiftformat to 0.44.6

---

GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m

Fix format error in Debug log.

Fix GDTCORLogDebug format in GDTCORPlatform

---

Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m

Crashlytics collect on-device symbolication for GDT (#5266)

---

scripts/check_cmake_files.py
scripts/lib/checker.py
scripts/lib/git.py
scripts/make_release_notes.py
scripts/setup_check.sh

Fix a number of python3 related issues that have crept in.

Python 3 compatibility fixes

---

Firebase.podspec

Remove MLKit from M68 release.

---

ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift

Append framework name to Carthage plist bundleID

---

Firebase.podspec
FirebaseCore.podspec
FirebaseCoreDiagnostics.podspec
FirebaseCrashlytics.podspec
FirebaseFirestore.podspec
FirebaseInAppMessaging.podspec
FirebaseInstanceID.podspec
Releases/Manifests/6.22.0.json

Merging the 6.22.0 release into master

---

Example/Messaging/Sample/Sample/ContentView.swift
Example/Messaging/Sample/Sample/Identity.swift
Example/Messaging/Sample/Sample/SceneDelegate.swift

Moved the buttons out of the list, added a navigation title, and made
Identity have optional properties since it's more appropriate (vs an
empty string).

UI changes for the sample app.

---

GoogleUtilities/Environment/SecureStorage/GULKeychainStorage.m
GoogleUtilities/Environment/SecureStorage/GULKeychainUtils.m
GoogleUtilities/Example/Tests/Environment/GULKeychainStorageTests.m

- use modular style import for public headers

GoogleUtilities: fix public header imports

---

GoogleDataTransport/GDTCORLibrary/GDTCORConsoleLogger.m
GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m
GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORLifecycle.m
GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
GoogleDataTransport/GDTCORLibrary/GDTCORReachability.m
GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m
GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m
GoogleDataTransport/GDTCORLibrary/GDTCORTransport.m
GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
GoogleDataTransport/GDTCORLibrary/GDTCORUploadPackage.m
GoogleDataTransport/GDTCORLibrary/Public/GDTCORConsoleLogger.h
GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/Helpers/GDTCCTEventGenerator.m
GoogleDataTransportCCTSupport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.m

Handle events that fail to write or are missing and add logging levels

---

ZipBuilder/Template/README.md

Inspired by https://stackoverflow.com/questions/61209161/integrate-firebase-crashlytics-beta-sdk-in-ios-project-without-pods/61217246#61217246
#no-changelog

Add Xcode 11.0 requirement to zip README

---

README.md

More badges and some s/iOS/Apple/

---

Firestore/Example/Tests/Integration/FSTTransactionTests.mm

Porting from [web](https://github.com/firebase/firebase-js-sdk/pull/2888).

Fix flaky transaction tests
