firebase/firebase-ios-sdk

README.md
GHA got skipped on #5381 somehow
=> Trailing space

Carthage.md
=> Carthage doc fix until 6.23.0 release

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Auth/FIRAuth.m, FirebaseAuth/Tests/Unit/FIRAuthUseUserAccessGroupTests.m
=> Synchronize useUserAccessGroup

.github/workflows/messaging.yml
Fix build breakage. I'm not sure how/why this worked in #5358
#no-changelog
=> Fix issues in Messaging GHA yml file

.github/workflows/messaging.yml, Example/Messaging/Sample/Sample.xcodeproj/project.pbxproj, Example/Messaging/Sample/Sample/ContentView.swift, scripts/build.sh
The plist file location was wrongly specified and also need to generate the plist file for test app to build.
Also add a preview for UserSettings for easy debugging.
=> Fix messaging GHA failure

FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
add NSLocalizedString() to user-facing strings to fix https://github.com/firebase/firebase-ios-sdk/issues/5255
=> add NSLocalizedString()

GoogleDataTransport/GDTCORLibrary/GDTCORReachability.m
=> Move reachability flags initialization to +initialize from +load

scripts/build_zip.sh
=> Fix zip nightly build to work with SpecStaging

Firestore/README.md
Prefer the emulator by default but give alternate instructions for prod.
=> Update integration testing docs

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/FIRCLSUserDefaults/FIRCLSUserDefaults.m
=> Fix UB in defaults loading

Firestore/Example/Podfile
=> Fix Firestore build broken by M70 version changes

.github/workflows/datatransport.yml, scripts/build.sh, scripts/install_prereqs.sh
Draft build GDTCCT watchos test apps in GHA
#no-changelog
=> Build GDTCCT watchOS test apps in GHA

FirebaseAppDistribution/Sources/FIRAppDistribution.m
1. Making sure there is a single instance of a UI Window that we use to display the initial UI alert and the sign in alert
2. Making sure that the UI Window is cleaned up correctly to avoid the stale UI window freezing the entire app.
=> Cleaning up App Distribution UI window

FirebaseAppDistribution/Sources/FIRAppDistribution.m, FirebaseAppDistribution/Sources/Private/FIRAppDistribution+Private.h, FirebaseAppDistribution/Sources/Public/FIRAppDistribution.h
Add in the ability (temporarily) for customers to set the client id. 
* Tested e2e locally
=> Add in a setter for clientID to allow overrides

.travis.yml
These were ported over to GHA already.
#no-changelog
=> Remove Storage cron tests from Travis

.github/workflows/firestore.yml, .github/workflows/messaging.yml, scripts/check_secrets.sh
=> Fixes for GHA from a forked repo

GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m
=> Print out counter error message.

FirebaseAppDistribution/Sources/FIRAppDistributionAuthPersistence.m
https://developer.apple.com/documentation/security/keychain_services/keychain_items/restricting_keychain_item_accessibility
=> Making sure keychain is accesible after first unlock even if app is in background

AddNewPod.md
=> Add some missing steps to AddNewPod instructions

.github/workflows/remoteconfig.yml, scripts/test_quickstart.sh
Add Swift RemoteConfig Quickstart tests.
=> Add Swift Quickstart tests

.github/workflows/functions.yml
=> Update the path to Functions.

AddNewPod.md
=> Instructions for initial pod launch

Firestore/Swift/Source/Codable/CodableErrors.swift, Firestore/Swift/Tests/Codable/FirestoreEncoderTests.swift, Firestore/third_party/FirestoreEncoder/FirestoreDecoder.swift
=> Spelling error in FirestoreDecodingError

Firestore/Example/Firestore.xcodeproj/project.pbxproj, Firestore/core/src/util/defer.h, Firestore/core/src/util/filesystem_posix.cc, Firestore/core/src/util/filesystem_win.cc, Firestore/core/src/util/string_apple.h, Firestore/core/test/unit/model/field_value_test.cc, Firestore/core/test/unit/util/defer_test.cc, Firestore/core/test/unit/util/filesystem_test.cc, Firestore/core/test/unit/util/string_apple_test.mm
Also, use it in a few places where it helps.
=> Add defer, a general facility for ad-hoc RAII.

Firestore/core/src/remote/stream.cc
=> Bump stream closing log to WARN.

CoreOnly/NOTICES
=> Update notices for M71.

.github/workflows/dynamiclinks.yml, scripts/setup_quickstart.sh
Test and debug DynamicLinks quickstart running on GHA.
=> Add DynamicLinks quickstart tests.

Carthage.md
=> Firestore no longer requires a resource bundle

Firebase.podspec
=> Remove MLKit from the M71 release

FirebaseMessaging/Tests/UnitTests/FIRMessagingClientTest.m
We should add an expectation to make sure test is completed for all async methods.
#no-changelog
=> fix tests with OCMock 3.6

.github/workflows/database.yml, .travis.yml, Example/Database/Tests/Integration/FData.m, Example/Database/Tests/Unit/FLevelDBStorageEngineTests.m, scripts/build.sh, scripts/install_prereqs.sh
Migrate RTDB CI to GHA
Disable two flaky integration tests that got flaky on travis with emulator switch and even more flaky on GHA.
Disable an always failing macOS unit test related to floating point double underflow
=> Migrate RTDB to GHA

FirebaseCore/Sources/FIRApp.m
Quick PR to fix a code comment typo, thanks!
N/A
N/A
=> chore: fix code comment typo

.github/workflows/installations.yml, .travis.yml, scripts/setup_quickstart.sh
Also delete some additional unneeded travis-specific code.
=> Migrate Installations to GHA

.travis.yml, Gemfile, scripts/install_prereqs.sh
All testing of quickstarts and tests that require secrets are now in GHA
=> Delete unused travis code

GoogleDataTransport/CHANGELOG.md, GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
=> Change upload coordinator to not block main thread

Firebase.podspec, Releases/update-versions.py
To avoid confusion with Swift Package Manager
=> CocoaPods-specific tag for the Firebase pod

Firebase/Database/CHANGELOG.md, Firebase/Database/Persistence/FLevelDBStorageEngine.m
Fixes https://github.com/firebase/firebase-ios-sdk/issues/5686
=> Don't crash RTDB SDK if version file is empty

Example/Database/Tests/Helpers/FIRFakeApp.m, Example/Database/Tests/Helpers/FTestHelpers.m, Example/Database/Tests/Integration/FConnectionTest.m, Firebase/Database/Api/FIRDatabaseComponent.m, Firebase/Database/Api/FIRDatabaseConfig.h, Firebase/Database/Api/FIRDatabaseConfig.m, Firebase/Database/CHANGELOG.md, Firebase/Database/Core/FPersistentConnection.m, Firebase/Database/FIRDatabaseConfig_Private.h, Firebase/Database/Realtime/FConnection.h, Firebase/Database/Realtime/FConnection.m, Firebase/Database/Realtime/FWebSocketConnection.h, Firebase/Database/Realtime/FWebSocketConnection.m, Firebase/Database/third_party/SocketRocket/FSRWebSocket.h, Firebase/Database/third_party/SocketRocket/FSRWebSocket.m
Port of https://github.com/firebase/firebase-android-sdk/pull/1610
=> Add GMPID header to the RTDB SDK

Firestore/CHANGELOG.md, Firestore/core/src/auth/firebase_credentials_provider_apple.mm
Port of https://github.com/firebase/firebase-js-sdk/pull/3184
=> Refetch token if attempt was invalidated

.github/workflows/installations.yml, FirebaseCore/Sources/Private/FIRComponentContainer.h, FirebaseCore/Sources/Private/FIRLibrary.h
=> Fix has_include filename

FirebaseCore/CHANGELOG.md, FirebaseDynamicLinks/CHANGELOG.md, FirebaseRemoteConfig/CHANGELOG.md, FirebaseStorage/CHANGELOG.md, Firestore/CHANGELOG.md
cc: @eldhosembabu @chliangGoogle @wilhuff @karenyz @schmidt-sebastian
=> M73 (6.27.0) Core Changelog and version updates

GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m, GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorageIterator.m, GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m, GoogleDataTransport/GDTCORLibrary/Private/GDTCORFlatFileStorage.h, GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m, GoogleDataTransport/GDTCORTests/Unit/Helpers/GDTCOREventGenerator.h, GoogleDataTransport/GDTCORTests/Unit/Helpers/GDTCOREventGenerator.m
Resolves many TODOs in the flat file storage system
Bug fixes found by unit tests are also included.
Doesn't remove any code that has now been made duplicate.
#no-changelog because this is a feature branch
=> Store events using the flat file storage system

.github/workflows/abtesting.yml
Add ABTesting framework testing.
=> Add ABTesting framework testing.

.github/workflows/installations.yml, scripts/setup_quickstart_framework.sh
This will add multiple framework testing.
=> Add Installations framework testing.

.github/workflows/messaging.yml
Add Messaging framework testing.
=> Add Messaging framework testing.

.github/workflows/core.yml, .github/workflows/installations.yml
Other workflows will be updated once this one tested on Private repo.
=> Run GHA Installation jobs only for public repo or for a PR

FirebaseABTesting/Tests/Unit/ABTFakeFIRAConditionalUserPropertyController.h, FirebaseCore/Sources/FIRConfigurationInternal.h, FirebaseInstallations/Source/Library/Private/FirebaseInstallationsInternal.h, GoogleUtilities/SceneDelegateSwizzler/GULSceneDelegateSwizzler.m, scripts/check.sh, scripts/check_imports.swift
Verify functional and style of imports and includes.
=> Initial check imports script

GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m, GoogleUtilities/Environment/Private/GULAppEnvironmentUtil.h, GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
=> GoogleUtilities: cleanup iOS 6-7 compatibility conditions

ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
pods specified in the json that included subspec were ignored when the buildDependencies option was false.
#no-changelog
=> Fix buildDependencies false and subspecs

.github/workflows/storage.yml
Add Storage framework testing.
=> Add Storage framework testing.

.github/workflows/spm.yml, Package.swift, Tests/firebase-test/main.swift
=> SPM CI with swift test instead of swift run

GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m, GoogleDataTransport/GDTCORLibrary/Public/GDTCOREvent.h
Also update GDTCOREvent target types to GDTCORTarget
#no-changelog because this is a feature review branch
=> Remove initializer annotations

.github/workflows/database.yml, scripts/build_non_firebase_sdks.sh
Add Database framework testing.
=> Add Database framework testing.

.github/workflows/crashlytics.yml
Add Crashlytics Framework testing.
=> Add Crashlytics framework testing.

FirebaseCoreDiagnostics.podspec, FirebaseCrashlytics.podspec, FirebaseInAppMessaging.podspec, GoogleDataTransport.podspec, GoogleDataTransportCCTSupport.podspec
#no-changelog
cc: @visumickey @samedson
=> Update versions and dependencies

scripts/check_imports.swift
Add main func, add ErrorLog class, and eliminate two globals
=> Cleanups for check_imports.swift

GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.m, GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORStorageFake.m
=> GDT: Fix test storage type mismatches

Firestore/core/src/remote/serializer.cc
This occasionally causes crashes in tests on Forge when running against the emulator.
b/159911572
=> Work around rare WatchChange.result_type == 0

FirebaseCrashlytics.podspec, FirebaseInAppMessaging.podspec, FirebaseInstanceID.podspec, FirebaseMessaging.podspec, FirebaseRemoteConfig.podspec
=> Fix FIS private path

Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
=> Fix header style issue caught by copybara

.github/workflows/dynamiclinks.yml
Testing Dynamiclink framework workflow.
=> Add DynamicLinks framework testing.

.github/workflows/auth.yml
[Auth quickstart](https://github.com/firebase/quickstart-ios/tree/master/authentication) is updated and objc quickstart is removed.
=> Update auth pod test

.github/workflows/remoteconfig.yml
[RemoteConfig quickstart](https://github.com/firebase/quickstart-ios/tree/master/config) is updated and objc quickstart is removed.
=> Update RemoteConfig workflow.

FirebaseDynamicLinks/Tests/Sample/FDLBuilderTestAppObjC/AppDelegate.m, FirebaseDynamicLinks/Tests/Sample/Podfile
Current state of sample app has Import issues and the pod generation was failing to resolve GoogleUtilities dependency.
- Changed to use proper import
- Added GoogleUtilities dependency in pod file to make the pod install working
=> FDL Sample App: Fixing imports and Pod file 

scripts/setup_quickstart_framework.sh
This update will be submitted after [update_add_framework_script](https://github.com/firebase/quickstart-ios/pull/1004) is submitted.
=> Update scripts due to the change of add_framework tool.

FirebaseDynamicLinks/CHANGELOG.md
=> Update DL Changelog for 5941

FirebaseABTesting/Sources/ABTConditionalUserPropertyController.h, FirebaseABTesting/Sources/ABTExperimentPayload.m, FirebaseABTesting/Sources/FIRExperimentController.m, FirebaseABTesting/Tests/Unit/ABTConditionalUserPropertyControllerTest.m, FirebaseABTesting/Tests/Unit/ABTExperimentPayloadTest.m, FirebaseABTesting/Tests/Unit/FIRExperimentControllerTest.m, FirebaseABTesting/Tests/Unit/Utilities/ABTTestUtilities.m, FirebaseRemoteConfig/Sources/RCNDevice.m
Use repo-relative imports for new ABT header
Fix RC Maltese bug
(These issues came up migrating recent changes to internal build system)
=> ABT Path fixes and RC Maltese bug fix

scripts/build_zip.sh
=> Don't allow script to erase repo

.github/workflows/zip.yml
=> Migrate remoteconfig zip test to zip workflow.

FirebaseInAppMessaging/CHANGELOG.md, FirebaseInAppMessaging/Sources/Public/FIRInAppMessagingRendering.h
=> Fix inaccurate doc comment

scripts/check.sh
=> Ease diagnosis of origin of check failures

.github/workflows/zip.yml
Checkout will reset the workspace and remove artifacts downloaded. Put it first to fix this issue.
=> Move checkout first which will reset the workspace.

FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m
=> remove test that is dependent on other tests

GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m, GoogleDataTransport/GDTCORLibrary/Private/GDTCORUploadCoordinator.h, GoogleDataTransport/GDTCORTests/Common/Categories/GDTCORUploadCoordinator+Testing.m
A quick fix (mitigation) of b/160969496
=> [GDTCORUploadCoordinator startTimer]: don't restart timer if already started

FirebaseDynamicLinks/CHANGELOG.md, FirebaseDynamicLinks/README.md
For Dynamic links iOS SDK, we don't have a place to communicate the latest changes in the release to 3p developers. 
Adding a readme.md file to inform developers on the recent changes in SDK release and other info that developers should be aware of.
=> Create Readme.md file for having release notes

GoogleDataTransport/CHANGELOG.md, GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m, GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m, GoogleDataTransport/GDTCORLibrary/Private/GDTCORUploadCoordinator.h, GoogleDataTransport/GDTCORTests/Common/Categories/GDTCORUploadCoordinator+Testing.m, GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m
Cherry pick:
- #6032 - a critical issue fix (b/160969496)
- #6010 - testing of b/160969496 was done with this change so I feel it's safer to cherry pick it as well
=> Release 6.28.0 - GDT cherry pick of #6010 and #6032

Firestore/CHANGELOG.md, Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm, Firestore/Source/API/FIRFirestore.mm
Cherry-pick of #6041 to the 6.28.0 release branch.
=> Add #include for config.h to get the value for HAVE_LIBDISPATCH (#6041)

Firebase.podspec, FirebaseCore.podspec, FirebaseFirestore.podspec, Releases/Manifests/6.28.1.json
- version bumps to accommodate a Firestore patch release with #6042
=> M75.1 version bumps

LICENSE
License was never filled in it seems, figured it warrants a PR
Shouldn't be an earth shattering change.
=> License was never filled in it seems, figured it warrants a PR

Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
This change adds an integration test to verify that listener callbacks occur on the main thread. This test verifies behavior that would have caught the bug fixed by #6041.
#no-changelog
=> Add an integration test for callbacks on the main thread.

Carthage.md, Rome.md, ZipBuilder/Sources/ZipBuilder/FirebasePods.swift, ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
=> Remove deprecated ML pods from Zip and docs

.github/workflows/zip.yml, scripts/remove_data.sh
=> Update artifacts name

Example/watchOSSample/Podfile, FirebaseMessaging/Tests/UnitTests/FIRMessagingContextManagerServiceTest.m
#no-changelog as it's not a release change.
=> Messaging: fix a warning in macOS build and sample podfile file path

FirebaseABTesting/CHANGELOG.md, FirebaseAuth/CHANGELOG.md, FirebaseInAppMessaging/CHANGELOG.md, FirebaseRemoteConfig/CHANGELOG.md
Changelog and version updates for M76 after adding preliminary Swift Package support for ABTesting and RemoteConfig.
=> M76 changelog updates - ABT, Auth, FIAM, RC

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/Components/FIRCLSContext.m
A minimally intrusive patch for fixing #6048.
=> Fix potential strlen crash on NULL betaToken

FirebaseAppDistribution/CHANGELOG.md, FirebaseAppDistribution/README.md
* Add in a CHANGELOG file with our initial release
* Add in a README with a few getting started instructions.
=> Create changelog and readme in preparation for release.

FirebaseMessaging/Tests/UnitTests/FIRMessagingTest.m
=> fix leakage in NSInvocation

FirebaseAppDistribution/Sources/FIRAppDistributionMachO.m
=> Change slices property from copy to strong

FirebaseAppDistribution/Sources/FIRAppDistribution.m, FirebaseAppDistribution/Sources/FIRFADApiService.m, FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
* Change error handlers to return BOOL instead of void
* Update the name of the error mapper to reflect what it is doing.
#no-changelog
=> Change error handlers to return bool values instead of void

Package.swift
Make FirebaseRemoteConfig and FirebaseDatabase available to SPM clients
#no-changelog
=> Publish SPM products for RC and DB

FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
Continue #6108. I didn't save the file in my editor :P
=> one more internal ABT import fix

scripts/check_no_module_imports.sh
=> Fix check breakage from when GHA was out

.github/workflows/appdistribution.yml, FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m, README.md
Add Github action for App Distribution
=> Add github action for App Distribution

FirebaseABTesting/Tests/Integration/ABTQA/AppDelegate.swift, FirebaseCore/Tests/SwiftUnit/FirebaseAppTests.swift, FirebaseMessaging/Apps/Sample/Sample/SceneDelegate.swift, FirebaseMessaging/Apps/Sample/iOS/NotificationsController.swift, FirebaseRemoteConfig/Tests/FakeConsole/FakeConsoleTests.swift, FirebaseRemoteConfig/Tests/SwiftAPI/APITests.swift, FirebaseRemoteConfig/Tests/SwiftAPI/RemoteConfigConsole.swift, FirebaseStorage/Tests/SwiftIntegration/StorageIntegration.swift, FirebaseStorageSwift/Tests/Integration/StorageIntegration.swift, scripts/style.sh
=> Updates for bumping swiftformat to 0.44.17

.github/workflows/check.yml, .github/workflows/firestore.yml, scripts/check.sh, scripts/setup_check.sh
=> Configure Python 3 in some GitHub workflows.

HeadersImports.md
Update documentation to minimize Swift PM `#if`ing for client public header access.
=> Update recommended public header location

scripts/style.sh
=> Ignore SwiftPM gen'd files in style

Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m, Crashlytics/ProtoSupport/proto_generator.py, Crashlytics/Protogen/nanopb/crashlytics.nanopb.h, FirebaseInAppMessaging/Analytics/Protogen/nanopb/fiam.nanopb.h, FirebaseInAppMessaging/ProtoSupport/nanopb_build_protos.py, FirebaseInAppMessaging/Sources/Analytics/Protogen/nanopb/fiam.nanopb.h, GoogleDataTransport/GDTCCTLibrary/GDTCCTNanopbHelpers.m, GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m, GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h, GoogleDataTransport/ProtoSupport/proto_generator.py, Package.swift, scripts/check_imports.swift
Along with the corresponding https://github.com/paulb777/nanopb/commits/spm2
#no-changelog
=> Remove #if SWIFT_PACKAGE checks for nanopb

FirebaseAuth/Sources/Storage/FIRAuthKeychainServices.m, FirebaseAuth/Tests/Unit/FIRAuthKeychainServicesTests.m
=> Fix bug where multiple keychain entries would result in user persistence failure

Package.swift
=> Fix spm build warning

GoogleDataTransport/GDTCORLibrary/Internal/GoogleDataTransportInternal.h, scripts/check_imports.swift
Enabled by new structure from #6177 
#no-changelog
=> GDT remove @import

FirebaseFirestore.podspec
Address podspec part of #6072 review
#no-changelog
=> Remove non-existent Firestore/Protos/objc from podspec

Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
Fix build failure introduced by #6177 
#no-changelog
=> Fix CoreDiagnostics test regression

FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
Update copy to match https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZbPKf0YveMKq/files/MCEJu8Y2hyDScXYH49rqoPbxr79Y22Z7Pt8 comment 9.
screenshot: 
#no-changelog App Distribution has not yet been released.
=> Update UIAlert copy.

FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
* Add NSLocalizedStrings to the UIAlert component
#no-changelog App Distribution is not yet public
=> Add localized strings to the UIAlert

GoogleUtilities/Logger/GULLogger.m
Companion to internal cl/324658298
=> Reset debug mode on GGULResetLogger

Package.swift
- Update top comment
- Reorganize target order to put Firebase targets first
=> Package.swift cleanup

GoogleUtilities/CHANGELOG.md, GoogleUtilities/Environment/SecureStorage/GULKeychainStorage.m, GoogleUtilities/Tests/Unit/Environment/GULKeychainStorageTests.m
=> GULKeychainStorage: use dictionary instead of NSCache

FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking+Private.h, FirebaseDynamicLinks/Sources/GINInvocation/GINArgument.m, scripts/check_imports.swift
=> Enable check_imports presubmit for FDL

.github/workflows/check.yml, .github/workflows/firestore.yml, FirebaseMessaging/Tests/IntegrationTests/FIRMessagingTokenRefreshTests.swift, Firestore/third_party/FirestoreEncoder/FirestoreDecoder.swift, Mintfile, README.md, scripts/check_imports.swift, scripts/setup_check.sh, scripts/style.sh
Use mint to install a specific version of swiftformat
Add GHA caching of swiftformat
Update swiftformat to 0.45.3
#no-changelog
=> Update swiftformat and control its version via mint

Firestore/Swift/Source/Codable/CollectionReference+WriteEncodable.swift, Firestore/third_party/FirestoreEncoder/FirestoreDecoder.swift, Mintfile, README.md, scripts/style.sh
Update swiftformat to 0.45.5 to resolve [regression](https://github.com/nicklockwood/SwiftFormat/issues/697) @wilhuff found in #6229 review.
=> Update and apply swiftformat fix

Package.swift
=> Use nanopb repo instead of personal fork

FirebaseAppDistribution.podspec, FirebaseAppDistribution/CHANGELOG.md
Update version of App Distribution from 0.0.1 to 0.9.0
=> Update version of App Distribution from 0.0.1 to 0.9.0

Firebase.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFunctions.podspec, FirebaseRemoteConfig.podspec, FirebaseStorage.podspec, GoogleUtilities.podspec, Releases/Manifests/6.30.0.json
=> Update versions for Release 6.30.0

Package.swift
=> Switch from personal to Firebase forks

.github/workflows/auth.yml, FirebaseAuth.podspec, FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Auth/FIRAuth.m, FirebaseAuth/Sources/MultiFactor/FIRMultiFactor+Internal.h, FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h, FirebaseAuth/Sources/Public/FirebaseAuth/FIRGameCenterAuthProvider.h, FirebaseAuth/Sources/SystemService/FIRAuthAPNSTokenManager.h, FirebaseAuth/Sources/SystemService/FIRAuthAPNSTokenManager.m, FirebaseAuth/Sources/SystemService/FIRAuthAppCredentialManager.m, FirebaseAuth/Sources/SystemService/FIRAuthNotificationManager.h, FirebaseAuth/Sources/SystemService/FIRAuthNotificationManager.m, FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.h, FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m, FirebaseAuth/Sources/Utilities/FIRAuthDefaultUIDelegate.h, FirebaseAuth/Sources/Utilities/FIRAuthDefaultUIDelegate.m, README.md
This is a redo of #5585, which was a re-implementation of #4632. This
ignores any changes to GoogleUtilities, those will be done in a later
PR to create a common KeyedArchiver utility.
Credit goes to @hohteri for doing this work in the first place! Let's finally land this thing 😄
=> watchOS support for FirebaseAuth.

.github/workflows/crashlytics.yml, .travis.yml, FirebaseCrashlytics.podspec
In addition to  #6263
#no-changelog
=> Unit tests don't run for watchOS

FirebaseRemoteConfig/Tests/Sample/Podfile
See https://github.com/firebase/firebase-ios-sdk/runs/1001821418?check_suite_focus=true
#no-changelog
=> Fix cron build failure

AddNewPod.md
#no-changelog Just updating documentation
=> Fix FirebasePods link

CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_6_1_frameworks/Podfile, CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_6_1_staticLibs/Podfile, CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_frameworks/Podfile, CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_multiprojects_frameworks/Podfile, CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_multiprojects_staticLibs/Podfile, CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_staticLibs/Podfile
#no-changelog updating integration test podfiles in preparation for App Distribution initial launch.
=> Add App Distribution to all integration test environments

Package.swift
=> Update SPM Analytics for 6.31.0

FirebaseStorage.podspec
=> Remove out of date comment

.github/workflows/spm.yml
The SPM tests were distributed in #6271
=> Delete done TODO

GoogleDataTransport/GDTCORTests/Unit/GDTCORClockTest.m
=> GDTCORClockTest: decrease expected timestamp accuracy to fix test flakes

Carthage.md
#no-changelog updating documentation
=> Add AppDistribution to Carthage documentation.

Firebase.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCrashlytics.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFirestoreSwift.podspec, FirebaseInAppMessaging.podspec, FirebaseInstallations.podspec, GoogleDataTransport.podspec, Package.swift, Releases/Manifests/6.31.0.json
=> Merging the 6.31.0 release into master

FirebaseAppDistribution/CHANGELOG.md
=> Clean up change log.

FirebaseAppDistribution.podspec, FirebaseAppDistribution/CHANGELOG.md
* Bump podspec version for release patch
* Add release patch to changelog
=> Bump the podspec version and changelog version for release patch

Firestore/core/src/remote/grpc_connection.cc
=> Fix documentation warning surfaced in Xcode from grpc

ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
Fix #6349 
Thanks to https://stackoverflow.com/a/53759319/556617
=> Fix bitcode generation for Swift frameworks

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthCredential.h
=> Fix internal source documentation

.github/workflows/release.yml
Add releasing tests for iOS sdks.
=> Add release tests.

Package.swift, SwiftPackageManager.md
=> Add Analytics for 6.32.0 SPM

README.md
This matches other package managers.
=> Add SwiftPM instructions to base README.md

Firebase.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseFirestore.podspec, Package.swift, Releases/Manifests/6.32.0.json, SwiftPackageManager.md
=> Merging the 6.32.0 release into master

scripts/run_firestore_emulator.sh
Updating emulator version to v1.11.7 to include support for != queries.
=> Update firestore emulator version in tests

FirebaseCore/Sources/FIRApp.m, FirebaseCore/Sources/Private/FIRAppInternal.h
=> Remove deprecated sendLogsWithServiceName

CoreOnly/Sources/Firebase.h, Firebase.podspec
Fix #4900. Fix #6417.
#no-changelog
=> Remove deprecated pods from Firebase.h and Firebase.podspec

Package.swift
After #6444 released to spm on the 6.32-spm-beta branch
=> Merge SPM Info.plist fix to master

HeadersImports.md
This now reflects how the current directories are actually configured.
cc @paulb777 please take a look when you're back from vacation.
=> Fix incorrect docs on public headers

GoogleDataTransport/CHANGELOG.md, GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m, GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer_Private.h, GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCORPlatform.h, GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORApplicationFake.h, GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORApplicationFake.m, GoogleDataTransport/GDTCORTests/Unit/GDTCORTransformerTest.m
=> GDTTransformer: fix background tasks handling 

Firebase.podspec
Merge M79.1 (6.32.2) patch into master.
=> Patch update for Analytics. (#6460)

.github/workflows/release.yml, scripts/release_testing_setup.sh, scripts/setup_quickstart.sh
This update is prepared for released candidate nightly testing.
=> Update release workflow

FirebaseAuth/Sources/Auth/FIRAuth_Internal.h, FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h
Add the auth emulator entrypoint to the public API in a prerelease branch.
=> Add auth emulator to public API in prerelease branch.

Package.swift
=> SPM M80(6.33.0) Analytics update

SwiftPackageManager.md
This is for developers not integrating with Xcode.
Fixes #6357
=> Update instructions for manual Package manifests.

SwiftPackageManager.md
=> Document workaround for Xcode 12 GM SPM binary device install bug

GoogleDataTransport/README.md
=> GDT readme: log level configuration

SwiftPackageManager.md
=> Update SPM docs to current version

Firebase.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCrashlytics.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFunctions.podspec, Package.swift, Releases/Manifests/6.33.0.json
=> Merging the 6.33.0 release into master

Package.swift
It's time for better spm release tooling ....
#no-changelog
=> Fix SPM version

.github/workflows/abtesting.yml, .github/workflows/auth.yml, .github/workflows/core.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/dynamiclinks.yml, .github/workflows/firestore.yml, .github/workflows/functions.yml, .github/workflows/inappmessaging.yml, .github/workflows/installations.yml, .github/workflows/remoteconfig.yml, .github/workflows/spm.yml, .github/workflows/storage.yml
=> Use Xcode 12 in CI instead of the beta

.github/workflows/prerelease.yml, scripts/release_testing_setup.sh
=> Update versions automation

FirebasePerformance.podspec.json
Enable more shared test and release processes between binary and source pods.
#no-changelog
=> Add Performance podspec

Firebase.podspec
Follow on to #6517 to finish updating the minimum versions in Firebase.podspec for Firebase 7 release.
#no-changelog
=> Firebase 7 Firebase.podspec versions

Package.swift, SwiftPackageManager.md
=> 6.34.0 updates for SwiftPM

FirebaseInstallations.podspec, FirebaseInstallations/CHANGELOG.md, FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.h, FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.m, FirebaseInstallations/Source/Library/FIRInstallationsItem.h, FirebaseInstallations/Source/Library/FIRInstallationsItem.m, FirebaseInstallations/Source/Library/FIRInstallationsLogger.h, FirebaseInstallations/Source/Library/FIRInstallationsLogger.m, FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m, FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m, FirebaseInstallations/Source/Tests/Fixture/APIRegisterInstallationResponseSuccessNoFID.json, FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m, FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m, FirebaseInstallations/Source/Tests/Unit/FIRInstallationsItemTests.m, FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.h, FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.m, Releases/Manifests/6.34.0.json
Cherry pick of #6570 to M81 (6.34.0)
=> M81 FIS cherry pick of #6570

FirebaseAppDistribution/README.md
* link to https://firebase.google.com/docs/app-distribution/set-up-alerts in readme
=> Add link to App Distribution docs page

FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
- cherry pick "FIS: don't log anything on success validation (#6635)"
#no-changelog
=> Cherry pick #6635 to master

SymbolCollisionTest/Podfile
=> Update Symbol Collision Test for Firebase 7

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Tests/Sample/Sample/SettingsViewController.m, FirebaseCore/CHANGELOG.md, FirebaseCore/Sources/FIRApp.m, FirebaseCore/Sources/FIRLogger.m, FirebaseCore/Sources/FIROptions.m, FirebaseCore/Sources/FIRVersion.m, FirebaseCore/Sources/Private/FirebaseCoreInternal.h, FirebaseCore/Sources/Public/FirebaseCore/FIRVersion.h, FirebaseCore/Sources/Public/FirebaseCore/FirebaseCore.h, FirebaseCore/Tests/Unit/FIROptionsTest.m, FirebaseInstallations/CHANGELOG.md, FirebaseStorage/CHANGELOG.md, SwiftPMTests/swift-test/main.swift, SwiftPMTests/version-test/versionTest.m
- Makes FIRVersion API public
- Adds docs for deleted version APIs in #6634
- Update ObjC and Swift tests
API review document is under review
=> Public Version API

FirebaseAuth/README.md
=> Update the sample project link.

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
Confirmed through unit test that it is now running on main thread
Fixes #5897
=> Call fetchAndActivate completion handler on main thread

FirebaseAuth/Tests/Sample/README.md
=> Remove duplicate section for instructions.

Example/InstanceID/Tests/FIRInstanceIDTest.m, Firebase/InstanceID/CHANGELOG.md, Firebase/InstanceID/FIRInstanceID+Private.m, Firebase/InstanceID/FIRInstanceID.m, Firebase/InstanceID/Private/FIRInstanceID+Private.h, Firebase/InstanceID/Private/FIRInstanceID_Private.h
=> Remove deprecated -[FIRInstanceID appInstanceID:]

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Backend/FIRAuthBackend.m, FirebaseAuth/Tests/Sample/Sample/SettingsViewController.m, FirebaseCore/CHANGELOG.md, FirebaseCore/Sources/FIRApp.m, FirebaseCore/Sources/FIRLogger.m, FirebaseCore/Sources/FIROptions.m, FirebaseCore/Sources/FIRVersion.m, FirebaseCore/Sources/Public/FirebaseCore/FIRVersion.h, FirebaseCore/Tests/Unit/FIROptionsTest.m, FirebaseDatabase/Sources/Api/FIRDatabase.m, FirebaseDynamicLinks/Sources/FIRDynamicLinks.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMClientInfoFetcher.m, FirebaseInstallations/CHANGELOG.md, FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m, FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m, FirebaseMessaging/Sources/FIRMessaging.m, FirebaseStorage/CHANGELOG.md, FirebaseStorage/Sources/FIRStorageTokenAuthorizer.m, SwiftPMTests/swift-test/main.swift, SwiftPMTests/version-test/versionTest.m
Use a C function for the Version API
=> C API for Firebase Version

FirebaseDynamicLinks/Sources/FIRDynamicLinks.m
=> Provide version for FDL 1P builds

GoogleDataTransport/GDTCCTWatchOSTestApp/GDTCCTWatchOSIndependentTestAppWatchKitExtension/ExtensionDelegate.swift
=> Fix CI/regression - update for change FCM API

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h, FirebaseRemoteConfig/Sources/RCNConfigExperiment.h
=> Update API documentation referencing removed methods

FirebaseInAppMessaging/Sources/Data/FIRIAMRenderingEffectSetting.m, FirebaseInAppMessaging/Sources/DefaultUI/Banner/FIRIAMBannerViewController.m, FirebaseInAppMessaging/Sources/Private/Data/FIRIAMRenderingEffectSetting.h, FirebaseInAppMessaging/Tests/Integration/DefaultUITestApp/FiamDisplaySwiftExample/CommonMessageTestVC.swift, FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/InAppMessaging_Example_iOS_SwiftUITests/InAppMessaging_Example_iOS_SwiftUITests.swift
Resolves Issue: https://github.com/firebase/firebase-ios-sdk/issues/6707
=> Change instances of 'dimiss' to 'dismiss'

.github/workflows/database.yml, .github/workflows/firestore.yml, .github/workflows/functions.yml
=> Re-enable quickstart testing for FirebaseUI apps

Firebase.podspec, FirebaseMLCommon.podspec.json, FirebaseMLModelInterpreter.podspec.json, FirebaseMLVision.podspec.json, FirebasePerformance.podspec.json
Merge back 7.0 podspec fixes back to master
#no-changelog
=> Misc podspec fixes for Firebase 7

.travis.yml
Fix for failures like https://travis-ci.org/github/firebase/firebase-ios-sdk/jobs/735746869
#no-changelog
=> Travis GoogleUtilities :  skip Swift tests when --use-libraries

FirebaseInstallations/API_KEY_RESTRICTIONS.md, GoogleUtilities/CHANGELOG.md
=> FIS docs: whitelist -> allowlist

.github/workflows/abtesting.yml, .github/workflows/appdistribution.yml, .github/workflows/auth.yml, .github/workflows/core.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/datatransport.yml, .github/workflows/dynamiclinks.yml, .github/workflows/firestore.yml, .github/workflows/functions.yml, .github/workflows/installations.yml, .github/workflows/instanceid.yml, .github/workflows/messaging.yml, .github/workflows/remoteconfig.yml, .github/workflows/spm.yml, .github/workflows/storage.yml, .github/workflows/zip.yml
=> Only run schedule actions on the main repo

ReleaseTooling/Sources/ZipBuilder/FirebaseBuilder.swift, ReleaseTooling/Sources/ZipBuilder/LaunchArgs.swift
Follow up to #6772 
#no-changelog
=> Source updates for ReleaseTooling rename

.github/workflows/firestore.yml, .github/workflows/storage.yml
=> Fix CI after #6777

scripts/build_zip.sh
=> Fix typo to fix zip cron

Gemfile, Gemfile.lock
CocoaPods 1.10.0 released yesterday. Update CI to use it.
=> Update to CocoaPods 1.10.0

Package.swift
=> M82 SPM Analytics update

.github/workflows/zip.yml, ReleaseTooling/Sources/ZipBuilder/LaunchArgs.swift, scripts/build_zip.sh
- Fix backwards argument check
- Add carthage build to nightly
- Update the zip build command
#no-changelog
=> Restore zip cron test

FirebaseDynamicLinks/Sources/FIRDynamicLinks.m, FirebaseDynamicLinks/Tests/Sample/Podfile
=> 7.0.0 cherry-pick: Fixed broken callback to AppDelegate (#6800)

.github/workflows/firestore.yml, .github/workflows/storage.yml, Package.swift, ReleaseTooling/Sources/FirebaseReleaser/Push.swift, ReleaseTooling/Sources/FirebaseReleaser/main.swift
Moving already reviewed PRs to master to maximize pre-release testing 
#no-changelog
=> Merge release-7.0 branch to master

.github/workflows/firestore.yml, .github/workflows/storage.yml
=> Update cron tests for new Swift product names

Package.swift
Merge #6805 to keep CI working on master now that the 7.0 SPM artifacts have changed
=> Merge SPM updates back to master to fix CI

README.md, ROADMAP.md
=> Readme and Roadmap updates

ReleaseTooling/Sources/FirebaseManifest/Pod.swift
=> Fix typo on publish command

SwiftPackageManager.md
=> Update SPM instructions for 7.0

ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
=> Fix publish order - RemoteConfig is a dependency of Performance

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelInterpreterBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLVisionBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseProtobufBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage updates for 7.0.0

.github/ISSUE_TEMPLATE/bug_report.md
Now that Firebase 7.0.0 is a single Firebase version
#no-changelog
=> Remove Component version from issue template

.github/workflows/check.yml
=> Fix cache for check workflow

Crashlytics/Crashlytics/Components/FIRCLSContext.m, Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.m, Crashlytics/Crashlytics/DataCollection/FIRCLSDataCollectionArbiter.m, Crashlytics/Crashlytics/FIRCrashlytics.m, Crashlytics/Crashlytics/Helpers/FIRCLSDefines.h, Crashlytics/Crashlytics/Models/FIRCLSSettings.m, Crashlytics/Crashlytics/Settings/FIRCLSSettingsOnboardingManager.m, Crashlytics/Crashlytics/Settings/Operations/FIRCLSDownloadAndSaveSettingsOperation.m, Crashlytics/Crashlytics/Settings/Operations/FIRCLSNetworkOperation.m, Crashlytics/Shared/FIRCLSConstants.h, Crashlytics/Shared/FIRCLSConstants.m, Crashlytics/UnitTests/FIRCLSDataCollectionArbiterTest.m, Crashlytics/UnitTests/FIRCLSSettingsTests.m, FirebaseCore/Sources/FIRVersion.m, FirebaseCrashlytics.podspec
=> Change the Crashlytics version constant to read from FIRCore instead of from a build flag.

Crashlytics/Crashlytics/Components/FIRCLSContext.m
=> Get rid of an additional import of FIRVersion that I missed deleting

FirebasePerformance.podspec.json
=> Update podspec for Performance 7.0.1 patch

FirebasePerformance.podspec.json
=> Update podspec for Performance 7.0.1 patch (master cherry-pick)

Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m, FirebaseDynamicLinks/Sources/Logging/FDLLogging.m, Firestore/core/test/unit/util/ordered_code_test.cc, GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m, README.md, scripts/setup_check.sh, scripts/style.sh
- `./scripts/style.sh` clang-format version updated
- `clang-format 11` changes applied
#no-changelog
=> Update clang-format to 11

FirebaseDatabase/Sources/Core/FRepoInfo.m
Fix for integration test failures in #5916's CI
#no-changelog
=> Fix infinite loop exposed in integration tests

FirebaseDatabase/Tests/Helpers/FIRFakeApp.h
=> Fix RTDB test build warnings

Crashlytics/CHANGELOG.md, FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/Auth/FIRAuth.m, FirebaseMessaging/CHANGELOG.md, FirebaseMessaging/Sources/FIRMessagingRemoteNotificationsProxy.m, Firestore/CHANGELOG.md, GoogleDataTransport/CHANGELOG.md, GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m, GoogleUtilities/CHANGELOG.md, GoogleUtilities/Tests/Unit/Swizzler/GULAppDelegateSwizzlerTest.m, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
- cherry pick of #6863
- GDT 8.0.1 added to the release
=> Release 7.1.0 cherry picks

Package.swift
=> 7.1.0 SPM Analytics

FirebaseSegmentation.podspec, FirebaseSegmentation/Sources/FIRSegmentationComponent.m, FirebaseSegmentation/Sources/SEGContentManager.m, FirebaseSegmentation/Sources/SEGDatabaseManager.m, FirebaseSegmentation/Sources/SEGSegmentationConstants.m, FirebaseSegmentation/Tests/Unit/SEGContentManagerTests.m, FirebaseSegmentation/Tests/Unit/SEGInitializationTests.m
=> Update to 7.x and fix some build errors

.github/workflows/segmentation.yml, FirebaseSegmentation.podspec
Add cross-platform support and set up GitHub Actions CI
First part of fixing #6703
=> Segmentation tvOS, macOS, and CI

Crashlytics/Crashlytics/DataCollection/FIRCLSDataCollectionArbiter.m, Crashlytics/Crashlytics/Models/FIRCLSSettings.m, Crashlytics/UnitTests/FIRCLSDataCollectionArbiterTest.m, Crashlytics/UnitTests/FIRCLSSettingsTests.m
=> Rename CRASHLYTICS_INTERNAL to CRASHLYTICS_1P

.github/workflows/segmentation.yml, FirebaseSegmentation/Tests/Sample/Podfile, FirebaseSegmentation/Tests/Sample/SegmentationSampleApp.xcodeproj/project.pbxproj, FirebaseSegmentation/Tests/Sample/SegmentationSampleApp/Info.plist, scripts/build.sh, scripts/install_prereqs.sh
=> Update sample app for Firebase 7 and add build test to CI

ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift, ReleaseTooling/Sources/ZipBuilder/main.swift
Should fix cron failure at https://github.com/firebase/firebase-ios-sdk/runs/1389501861?check_suite_focus=true
=> ZipBuilder Spelling Fix

GoogleUtilities.podspec, GoogleUtilities/CHANGELOG.md, GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
=> Fix unrecognized selector for isiOSAppOnMac on early iOS 14 betas

FirebaseRemoteConfig/Tests/SwiftSample/RemoteConfigSwiftSample/ContentView.swift
=> Add Fetch button to Swift app.

FirebaseAuth/Sources/Public/FirebaseAuth/FIROAuthProvider.h
Fix some typos in FIROAuthProvider public docs.
=> Fix documentation typos in FIROAuthProvider.

ReleaseTooling/Template/README.md
Needed for arm64 simulator support.
=> Move minimum zip requirement to Xcode 12.0

scripts/check_imports.swift
- allow `<>` imports in test files
#no-changelog
=> Adjust check_imports.swift for test files

.github/workflows/mlmodeldownloader.yml
This is causing a nightly failure at the moment. cc @manjanac
=> Swift pods don't need ---use-libraries.

.github/actions/testing_report_generation/Dockerfile, .github/actions/testing_report_generation/Gemfile, .github/actions/testing_report_generation/Gemfile.lock, .github/actions/testing_report_generation/action.yml, .github/actions/testing_report_generation/app.rb, .github/actions/testing_report_generation/template.md, .github/workflows/generate_issues.yml
This will post issues on a testing repo for testing purpose before it is prepared to be reviewed.
=> Add Nightly Report Generation.

.github/workflows/google-utilities.yml, README.md
=> Migrate GoogleUtilities CI to GHA

.github/workflows/functions.yml
=> Migrate Functions CI to GHA

.github/workflows/google-utilities-components.yml, README.md
=> Migrate GoogleUtilitiesComponents CI to GHA

.github/workflows/core-diagnostics.yml, README.md
=> Migrate CoreDiagnostics to gha

.github/workflows/inappmessaging.yml, .travis.yml
=> Migrate FIAM CI to GHA

.github/workflows/cocoapods-integration.yml, README.md
=> Migrate CocoaPods integration tests to GHA

Package.swift
FIRAnalyticsConnector is now included in FirebaseAnalytics 
#no-changelog
=> SPM Analytics 7.2.0

FirebaseStorage/CHANGELOG.md, FirebaseStorage/Sources/FIRStorageDeleteTask.m, FirebaseStorage/Sources/FIRStorageDownloadTask.m, FirebaseStorage/Sources/FIRStorageGetDownloadURLTask.m, FirebaseStorage/Sources/FIRStorageGetMetadataTask.m, FirebaseStorage/Sources/FIRStorageListTask.m, FirebaseStorage/Sources/FIRStorageUpdateMetadataTask.m, FirebaseStorage/Sources/FIRStorageUploadTask.m
Fix #7051 
General case follow up to #3786
=> Verify block is still alive before calling it in task callbacks

AppleSilicon.md, README.md
Added README about Apple silicon Macs
#no-changelog
=> Added README about Apple silicon Macs

AppleSilicon.md
=> Fix links in Apple silicon docs.

AppleSilicon.md
Add CocoaPods requirement
#no-changelog
=> Add CocoaPods requirement

AppleSilicon.md
=> Fix patch/major instructions.

AppleSilicon.md
I didn't want to just leave it until after the Podfile changes in case people missed it, but open to suggestions on how to make this more clear.
=> Add ObjC instruction

GoogleDataTransport.podspec
Bump up version for #7064.
Reference to FirebasePerformance's changes https://github.com/FirebasePrivate/firebase-ios-sdk/pull/734#pullrequestreview-542951310
=> Bump up GoogleDataTransport version to 8.1.0

AppleSilicon.md, Firebase.podspec, FirebaseABTesting.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCoreDiagnostics.podspec, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFirestoreSwift.podspec, FirebaseFunctions.podspec, FirebaseInAppMessaging.podspec, FirebaseInstallations.podspec, FirebaseInstanceID.podspec, FirebaseMLCommon.podspec.json, FirebaseMLModelInterpreter.podspec.json, FirebaseMLVision.podspec.json, FirebaseMessaging.podspec, FirebasePerformance.podspec.json, FirebaseRemoteConfig.podspec, FirebaseStorage.podspec, FirebaseStorageSwift.podspec, Package.swift, README.md, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
Will wait for publishing, but needs to be merged right after publishing so our release notes have a live link to point to.
=> Merge release 7.2.0

Functions/Backend/package.json
=> Update Functions emulator to fix CI regression

README.md
Added details about watchOS Crashlytics support
=> Update README.md for Crashlytics watchOS

FirebaseAppDistribution/Sources/FIRAppDistribution.m, FirebaseAppDistribution/Sources/FIRAppDistributionUIService.h, FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
=> Fix AppDistro spm build for non-iOS platforms

README.md
=> Some minor README cleanups

LICENSE
=> Restore License copyright

Firebase.podspec, FirebaseABTesting.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCoreDiagnostics.podspec, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFirestoreSwift.podspec, FirebaseFunctions.podspec, FirebaseInAppMessaging.podspec, FirebaseInstallations.podspec, FirebaseInstanceID.podspec, FirebaseMLCommon.podspec.json, FirebaseMLModelInterpreter.podspec.json, FirebaseMLVision.podspec.json, FirebaseMessaging.podspec, FirebaseRemoteConfig.podspec, FirebaseStorage.podspec, FirebaseStorageSwift.podspec, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
Run CI on release branch after SpecStaging pushes
=> Update versions for Release 7.3.0

ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
Fix the toggling of the Carthage flag between the two Core Diagnostics builds.
=> Fix Carthage metrics

FirebaseAuth/Sources/Backend/FIRAuthBackend.m, FirebaseAuth/Sources/Backend/RPC/FIRGetProjectConfigResponse.h, FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h, FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuthErrors.h, FirebaseAuth/Sources/Public/FirebaseAuth/FIRUser.h, FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m, FirebaseAuth/Sources/Utilities/FIRAuthInternalErrors.h, FirebaseAuth/Tests/Unit/FIRGetOOBConfirmationCodeResponseTests.m, FirebaseAuth/Tests/Unit/FIRGetProjectConfigResponseTests.m
=> Replace "whitelist" with "allowlist" in Auth source code.

FirebaseDynamicLinks/CHANGELOG.md, FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.h, FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.m, FirebaseDynamicLinks/Sources/FIRDynamicLinks.m, FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLinks.h, FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinkNetworkingTests.m, FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m
=> Add Dynamic Links PR to 7.3.0 release with Changelog update

Carthage.md
=> Carthage discontinuation warning to Readme

Package.swift
=> Update SPM analytics for 7.3.0

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelInterpreterBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLVisionBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseProtobufBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Update 7.3.0 Carthage jsons

.github/workflows/archiving.yml, CocoapodsIntegrationTest/TestEnvironments/Cocoapods_multiprojects_frameworks/Podfile, CocoapodsIntegrationTest/TestEnvironments/Cocoapods_multiprojects_staticLibs/Podfile, CoreOnly/Tests/FirebasePodTest/Podfile, Dangerfile, SymbolCollisionTest/Podfile
=> Add Perf to Danger and misc integration tests

Package.swift
Follow up to #7108
#no-changelog
=> Update nanopb for SwiftPM

.github/workflows/generate_issues.yml, FirebaseSegmentation/Tests/Sample/Podfile
Fix nightly segmentation failure and add performance to the report 
The segmentation failure did not show up in #7149. @granluo, any ideas why?
=> Fix nightly segmentation and include performance in report

FirebaseCore.podspec, FirebaseCore/Tests/Unit/FIRAppTest.m
=> FIRApp tests fixes

.github/workflows/performance.yml, scripts/gha-encrypted/qs-performance.plist.gpg
Added quickstart and catalyst worflows.
=> Add perf related workflows.

FirebaseDynamicLinks/CHANGELOG.md, FirebaseDynamicLinks/Sources/FIRDynamicLinks.m, FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m
Fix regression introduced in #5853 discovered with internal testing.  see b/175119564
Internal testing at cl/347068008
Opinions about whether we should publish this in a 7.3.1 for CocoaPods?
=> Callback should be on main thread

README.md
=> Update README for perf open source

.github/workflows/crashlytics.yml
=> Disable macos cron tests

ReleaseTooling/Sources/ZipBuilder/Platform.swift, ReleaseTooling/Sources/ZipBuilder/main.swift
=> Add a flag to skip building for Catalyst

Firebase/InstanceID/CHANGELOG.md
Not sure if this is the correct release number.
=> Update changelog for iid release

FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m
=> Fix typo in test

ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
=> Enable FIAM tvos slice in zip build

FirebaseInAppMessaging.podspec, FirebaseInAppMessaging/Sources/Analytics/FIRIAMClearcutLogStorage.m, FirebaseInAppMessaging/Sources/Analytics/FIRIAMClearcutUploader.m, FirebaseInAppMessaging/Sources/DefaultUI/Banner/FIRIAMBannerViewController.m, FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMBaseRenderingViewController.m, FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMRenderingWindowHelper.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMActivityLogger.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayCheckOnAppForegroundFlow.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMFetchOnAppForegroundFlow.m
=> Make FIAM tvOS minimum version consistent with Firebase

Gemfile, Gemfile.lock
=> Update to CocoaPods 1.10.1

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/RCNConfigExperiment.m, FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
=> Remote Config: Revert to previous nil check on experiment JSON

Package.swift
=> SPM Analytics for 7.4.0

Firestore/CHANGELOG.md
=> Add changelog for #7288

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelInterpreterBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLVisionBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseProtobufBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage update for 7.4.0

.github/workflows/analytics.yml, FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
And very preliminary CI
#no-changelog
=> Initial Analytics podspecs in repo

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 7.5.0 podspec.json files
=> Analytics 7.5.0

Package.swift
Confirmed in Analytics QS and CI.
Will rebase to master after #7315 merges
#no-changelog
=> Use external repo for GoogleAppMeasurement SPM dependency

cmake/GoogleUtilities.cmake
Address comment at https://github.com/firebase/firebase-ios-sdk/pull/7315#pullrequestreview-573565799
#no-changelog
=> Remove redundant BUILD_INTERFACE

Package.swift
Swift Package Manager is now in beta
#no-changelog
=> Delete out-of-date comment

Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.m
=> Fix comments for performance improvements

FirebaseDatabase/CHANGELOG.md, FirebaseDatabase/Sources/Core/FRepo.m, FirebaseDatabase/Sources/Core/FSyncTree.h, FirebaseDatabase/Sources/Core/FSyncTree.m, FirebaseDatabase/Tests/Integration/FIRDatabaseQueryTests.m
=> RTDB query gets should not send server requests for listened-to data

FirebaseDynamicLinks/Sources/Logging/FDLLogging.m, FirebaseMLModelDownloader/Sources/FileDownloader.swift, FirebaseMLModelDownloader/Sources/ModelInfoRetriever.swift, FirebaseMLModelDownloader/Tests/Unit/ModelDownloaderUnitTests.swift, Firestore/core/test/unit/util/ordered_code_test.cc, GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
A couple suggestions on how to improve `ModelDownloadTask` to have a better validation.
=> Improve ModelDownloadTask tests

FirebaseDynamicLinks/Sources/FIRDynamicLinks.m, FirebaseDynamicLinks/Sources/Utilities/FDLUtilities.h, FirebaseDynamicLinks/Sources/Utilities/FDLUtilities.m
Addressing https://github.com/firebase/firebase-ios-sdk/issues/6756
=> Rewording "whitelist" in comments and function names.

Crashlytics/Crashlytics/DataCollection/FIRCLSDataCollectionArbiter.m, Crashlytics/Shared/FIRCLSConstants.m, Crashlytics/UnitTests/FIRCLSConstantsTest.m, Crashlytics/UnitTests/FIRCLSDataCollectionArbiterTest.m
=> Remove changes for Crashlytics 1P from the repo

ReleaseTooling/Sources/FirebaseReleaser/Push.swift
Push closed source podspecs to SpecsStaging to allow version updates to happen before official publish and keep CI working.
#no-changelog
=> Keep Release CI Functional using SpecsStaging

.github/workflows/prerelease.yml, .github/workflows/release.yml
Fixes https://github.com/firebase/firebase-ios-sdk/issues/7266
=> Add Nightly and Release workflows for FirebasePerformance.

.github/ISSUE_TEMPLATE/feature_request.md, ROADMAP.md
Updates after today's discussion
#no-changelog
=> More Roadmap updates

Package.swift
=> Update SwiftPM for M88 7.5

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
=> Analytics 7.5.0 RC1

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Cherry picking to the release branch.
=> Update Analytics podspec to RC1 (#7385)

ReleaseTooling/Sources/ZipBuilder/main.swift
=> Fix --pods option to work with --disable-build-dependencies

Firebase.podspec, FirebaseABTesting.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCoreDiagnostics.podspec, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFirestoreSwift.podspec, FirebaseFunctions.podspec, FirebaseInAppMessaging.podspec, FirebaseInstallations.podspec, FirebaseInstanceID.podspec, FirebaseMLCommon.podspec.json, FirebaseMLModelInterpreter.podspec.json, FirebaseMLVision.podspec.json, FirebaseMessaging.podspec, FirebasePerformance.podspec, FirebaseRemoteConfig.podspec, FirebaseStorage.podspec, FirebaseStorageSwift.podspec, Package.swift, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
=> Merging the 7.5.0 release into master

Package.swift
=> Merge 7.5.1 changes to master

.github/workflows/test_coverage.yml, scripts/code_coverage_report/generate_code_coverage_report/Sources/CoverageReportGenerator/CoverageReportParser.swift
Trigger the code coverage workflow when a PR is created. Fix a bug and remove redundant comments.
=> Update coverage workflow

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
No Analytics source changes for M89.
=> Analytics 7.6.0

ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
=> Add Perf tvOS slice to zip distribution

Firestore/CHANGELOG.md
Addressing feedback from #7421.
=> Tweak the changelog message for a fixed crash

FirebaseAuth/Sources/SystemService/FIRSecureTokenService.m, FirebaseAuth/Sources/User/FIRUser.m
Add some debug logging to help figure out why an expired token is sometimes being returned in #6521.
=> Add debug logging around token expiration

FirebaseMLModelDownloader/Sources/CustomModel.swift, FirebaseMLModelDownloader/Sources/DeviceLogger.swift, FirebaseMLModelDownloader/Sources/DownloaderUserDefaults.swift, FirebaseMLModelDownloader/Sources/FileDownloader.swift, FirebaseMLModelDownloader/Sources/LocalModelInfo.swift, FirebaseMLModelDownloader/Sources/ModelDownloadConditions.swift, FirebaseMLModelDownloader/Sources/ModelDownloadTask.swift, FirebaseMLModelDownloader/Sources/ModelDownloader.swift, FirebaseMLModelDownloader/Sources/ModelFileManager.swift, FirebaseMLModelDownloader/Sources/ModelInfoRetriever.swift, FirebaseMLModelDownloader/Sources/RemoteModelInfo.swift, FirebaseMLModelDownloader/Sources/TelemetryLogger.swift, FirebaseMLModelDownloader/Tests/Integration/ModelDownloaderIntegrationTests.swift, FirebaseMLModelDownloader/Tests/Unit/ModelDownloaderUnitTests.swift
=> Add documentation + other minor fixes.

FirebaseMLModelDownloader/Sources/DeviceLogger.swift, FirebaseMLModelDownloader/Sources/ModelDownloadTask.swift, FirebaseMLModelDownloader/Sources/ModelDownloader.swift, FirebaseMLModelDownloader/Sources/ModelFileManager.swift, FirebaseMLModelDownloader/Sources/ModelInfoRetriever.swift, FirebaseMLModelDownloader/Sources/TelemetryLogger.swift, FirebaseMLModelDownloader/Sources/proto/firebase_ml_log_sdk.pb.swift, FirebaseMLModelDownloader/Sources/proto/firebase_ml_log_sdk.proto, FirebaseMLModelDownloader/Tests/Integration/ModelDownloaderIntegrationTests.swift, FirebaseMLModelDownloader/Tests/Unit/ModelDownloaderUnitTests.swift
=> Final fixes

FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
=> The network connection should be stubbed instead of using OCMExpect

Firestore/core/src/core/sync_engine.cc, Firestore/core/src/local/leveldb_target_cache.cc, Firestore/core/src/local/leveldb_target_cache.h, Firestore/core/src/local/local_store.cc, Firestore/core/src/local/local_store.h, Firestore/core/src/local/memory_target_cache.cc, Firestore/core/src/local/memory_target_cache.h, Firestore/core/src/local/target_cache.h, Firestore/core/src/model/model_fwd.h, Firestore/core/src/remote/remote_event.h, Firestore/core/test/unit/local/leveldb_target_cache_test.cc, Firestore/core/test/unit/local/local_store_test.cc, Firestore/core/test/unit/local/local_store_test.h
Corresponding Android port: https://github.com/firebase/firebase-android-sdk/pull/2342
=> Bundles LocalStore change

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
No Analytics source changes for M90.
=> Analytics 7.7.0

FirebaseCore/CHANGELOG.md
=> Release notes update to add zip Catalyst simulator support

Firestore/Example/Firestore.xcodeproj/project.pbxproj
This was done by running scripts/sync_project.rb, and should have been included in #7444 (but it was forgotten).
=> Update project.pbxproj for bundle_spec_test.json that was added in #7444

ReleaseTooling/DEVELOP.md, ReleaseTooling/Sources/FirebaseReleaser/Push.swift, ReleaseTooling/Sources/FirebaseReleaser/main.swift
Change release process to stage releases to a public repo instead of a private one.
=> Stage to SpecsStaging instead of cpdc

.github/workflows/analytics.yml, .github/workflows/prerelease.yml, CoreOnly/Tests/FirebasePodTest/Podfile, Example/watchOSSample/Podfile, FirebaseAuth/Tests/Sample/Podfile, FirebaseDynamicLinks/Tests/Sample/Podfile, FirebaseInAppMessaging/Tests/Integration/DefaultUITestApp/Podfile, FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/Podfile, FirebaseMessaging/Apps/AdvancedSample/Podfile, FirebaseMessaging/Apps/Sample/Podfile, FirebasePerformance/Tests/FIRPerfE2E/Podfile, FirebaseRemoteConfig/Tests/Sample/Podfile, Firestore/Example/Podfile, SymbolCollisionTest/Podfile, scripts/build.sh, scripts/create_spec_repo/Sources/SpecRepoBuilder/main.swift, scripts/localize_podfile.swift, scripts/pod_lib_lint.rb, scripts/test_archiving.sh, scripts/test_catalyst.sh
Incorporate SpecsDev along with SpecsStaging into CI
#no-changelog
=> Incorporate SpecsDev

.github/workflows/zip.yml, Firebase.podspec, FirebaseABTesting.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCoreDiagnostics.podspec, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFirestoreSwift.podspec, FirebaseFunctions.podspec, FirebaseInAppMessaging.podspec, FirebaseInstallations.podspec, FirebaseInstanceID.podspec, FirebaseMLModelDownloader.podspec, FirebaseMessaging.podspec, FirebasePerformance.podspec, FirebaseRemoteConfig.podspec, FirebaseStorage.podspec, FirebaseStorageSwift.podspec, ReleaseTooling/DEVELOP.md, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift, ReleaseTooling/Sources/FirebaseReleaser/Push.swift, ReleaseTooling/Sources/FirebaseReleaser/main.swift
Now that the release process is open, release branches can be merged back to master earlier and more often ...
=> Release 7.7 Merge

Package.swift
This really should be part of the automated update versioning script ... but I really need to get to perf :P
#no-changelog
=> Bump version for SPM

docs/firebase_in_libraries.md
=> Clarify FirebaseAnalytics is still static only

Package.swift
Merge 7.7 SPM update to master
=> Bump version for SPM (#7572)

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage 7.7.0 update

SwiftPackageManager.md
Some minor doc tweaks.
#no-changelog
=> Swift Package Manager doc updates

ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift
=> Automatically update SPM version variable

README.md
Initial repo instructions for developing Firebase with Swift Package Manager
#no-changelog
=> Initial SPM instructions for Firebase itself

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 7.8.0 podspec.json files
=> Analytics 7.8.0

Functions/Backend/package.json, Functions/README.md
Fix #7657 
#no-changelog Integration testing change only
=> Update firebase-admin version for Functions integrations tests

Package.swift
Accompanied AppMeasurement change in https://github.com/google/GoogleAppMeasurement/pull/4
=> Update SwiftPM for M91 Analytics 7.8.0

Package.swift
Cherry-picked to the release branch.
* Update SwiftPM for M91 Analytics 7.8.0
Accompanied AppMeasurement change in https://github.com/google/GoogleAppMeasurement/pull/4
* Update GoogleAppMeasurement Dep
=> Update SwiftPM for M91 Analytics 7.8.0 (#7673)

.github/workflows/release.yml, FirebaseMLModelDownloader.podspec, FirebaseMLModelDownloader/Apps/Sample/Podfile
Address nightly failure in the mlmodeldownloader workflow. See #7644
#no-changelog
=> Add missing GDT dep to MLDownloader

Firebase.podspec, FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json, Package.swift
Hopefully addresses #7695. 
Next steps:
Post release
#no-changelog
=> Firebase Analytics M91.1 update

Example/WatchDemo/WatchDemo.xcodeproj/project.pbxproj, Example/WatchDemo/WatchDemo/ContentView.swift, Example/WatchDemo/WatchDemoWatchKitExtension/ContentView.swift
=> add auth and storage to demo app 

Firebase.podspec, FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json, Package.swift
Merge M91.1 patch release to master.
=> Firebase Analytics M91.1 update (#7710)

Package.swift
This still needs to go through API review before being published.
=> Hide DatabaseSwift for M92.

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 7.9.0 podspec.json files
=> Analytics 7.9.0

.swiftpm/xcode/xcshareddata/xcschemes/Firebase-Package.xcscheme, Package.swift
Also update scheme for recent new targets added.
=> Resolve new SPM package install warning

.github/workflows/database.yml, FirebaseDatabase.podspec, FirebaseDatabase/Sources/Realtime/FWebSocketConnection.m, FirebaseDatabase/Tests/Helpers/FIRFakeApp.m
=> Fix pod lib lint for watchOS + add CI test

.github/workflows/spm.yml, SwiftPMTests/swift-test/main.swift
And run SPM platform tests on PRs instead of only cron jobs
=> Fix SPM Catalyst test

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
=> Analytics 7.9.0 RC1

CoreOnly/Tests/FirebasePodTest/Podfile
Add the more recently added pods to the general pod install CI test.
A subsequent task would be to add usages of their APIs to the source
#no-changelog
=> Add missing pods to Pod Test

FirebaseAnalytics.podspec.json
=> Analytics 7.9.0 RC1 fix

Firestore/core/src/timestamp_internal.cc
Introduced in #7717 
#no-changelog
=> Fix recently introduced build warning

CoreOnly/Tests/FirebasePodTest/FirebasePodTest/AppDelegate.swift
Follow up to [#7746](https://github.com/firebase/firebase-ios-sdk/pull/7746). Imported Firebase Swift APIs to `FirebasePodTest`'s `AppDelegate`.
#no-changelog
=> Import Firebase Swift APIs into FirebasePodTest source.

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
=> Analytics 7.9.0 RC2

ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
Add Swift pod to release tooling.
=> Add FirebaseInAppMessagingSwift to release tooling

Package.swift
=> Version dependencies are required in production

Package.swift
=> Merge 7.9.1 to master

.github/workflows/analytics.yml
=> Sources for pod spec lint

CocoapodsIntegrationTest/TestEnvironments/Cocoapods_multiprojects_frameworks/Podfile, CocoapodsIntegrationTest/TestEnvironments/Cocoapods_multiprojects_staticLibs/Podfile
Fix cocoapods-integration-tests failure in #7797
=> Fix nightly CocoaPods integration tests

.github/workflows/segmentation.yml, FirebaseSegmentation/Tests/Sample/Podfile
Fix the Segmentation failure in #7797 
It was not seeing the nanopb in SpecsDev required by the podspecs in master.
=> Fix Segmentation sample nightly testing failure

.github/workflows/zip.yml
=> Nightly zip should use SpecsDev

CoreOnly/Sources/Firebase.h
This was introduced in #7719 to fix a warning that was generated when using Remote Config on Catalyst, however, the PR was not using the correct preprocessor macro for Mac Catalyst.
This is validated by the system-provided `TargetConditionals.h` header which states:
```
*  TARGET_OS_*
*  These conditionals specify in which Operating System the generated code will
*  run.  Indention is used to show which conditionals are evolutionary subclasses.
*
*  The MAC/WIN32/UNIX conditionals are mutually exclusive.
*  The IOS/TV/WATCH conditionals are mutually exclusive.
*
*
*      TARGET_OS_WIN32           - Generated code will run under 32-bit Windows
*      TARGET_OS_UNIX            - Generated code will run under some Unix (not OSX)
*      TARGET_OS_MAC             - Generated code will run …
```
=> Use correct preprocessor macro for Mac Catalyst

Firestore/core/CMakeLists.txt, Firestore/fuzzing/CMakeLists.txt, Firestore/fuzzing/serializer_fuzzer.cc
=> Fix fuzzer build failure

Firebase.podspec, FirebaseABTesting.podspec, FirebaseAnalyticsSwift.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCoreDiagnostics.podspec, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFirestoreSwift.podspec, FirebaseFunctions.podspec, FirebaseInAppMessaging.podspec, FirebaseInAppMessagingSwift.podspec, FirebaseInstallations.podspec, FirebaseInstanceID.podspec, FirebaseMLModelDownloader.podspec, FirebaseMessaging.podspec, FirebasePerformance.podspec, FirebaseRemoteConfig.podspec, FirebaseStorage.podspec, FirebaseStorageSwift.podspec, Package.swift, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
7.10.0 is now staged to SpecsStaging
=> Update versions for Release 7.10.0

README.md
Perf and FIAM now support tvOS
=> Update platform support list

README.md
adds a little more color to the README!
=> README syntax highlighting for code blocks

.github/workflows/watchos-sample.yml, Example/watchOSSample/Podfile, Example/watchOSSample/SampleWatchApp.xcodeproj/project.pbxproj, Firebase.podspec, scripts/build.sh, scripts/install_prereqs.sh
Add Firebase pod support for watchOS for Remote Config and RTDB.
Address discussion at https://github.com/firebase/firebase-ios-sdk/pull/7656#issuecomment-813437060
Update the sample to test the Firebase pod.
Add sample build test to CI
=> Firebase pod support for watchOS for RC and RTDB

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage updates for 7.10.0

SwiftPackageManager.md
Fixes: https://github.com/firebase/firebase-ios-sdk/issues/7764
=> Fix upload-symbols help documentation

scripts/release_testing_setup.sh
Update a pattern to remove spaces.
=> Fix release workflow.

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/RCNDevice.m
=> Return FirebaseVersion as FIRRemoteConfigPodVersion

Firebase.podspec, FirebaseAnalytics.podspec.json, FirebaseAnalyticsWithoutAdIdSupportWrapper/dummy.m, FirebaseAnalyticsWithoutAdIdSupportWrapper/include/dummy.h, GoogleAppMeasurement.podspec.json, Package.swift, SwiftPM-PlatformExclude/FirebaseAnalyticsWithoutAdIdSupportWrap/dummy.m, SwiftPM-PlatformExclude/FirebaseAnalyticsWithoutAdIdSupportWrap/include/dummy.h
Analytics 7.11.0 podspec.json files, SPM, and Firebase podspec updates.
=> Analytics 7.11.0

Firebase.podspec, FirebaseAnalytics.podspec.json, FirebaseAnalyticsSwift.podspec, FirebaseAnalyticsWithoutAdIdSupportWrapper/dummy.m, FirebaseAnalyticsWithoutAdIdSupportWrapper/include/dummy.h, GoogleAppMeasurement.podspec.json, Package.swift, SwiftPM-PlatformExclude/FirebaseAnalyticsWithoutAdIdSupportWrap/dummy.m, SwiftPM-PlatformExclude/FirebaseAnalyticsWithoutAdIdSupportWrap/include/dummy.h
Cherry-picking #7900 into the 7.11 release branch.
cc @moemcd 
#no-changelog
=> Analytics 7.11.0 (#7900)

FirebaseRemoteConfig/CHANGELOG.md, FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h, FirebaseRemoteConfig/Sources/RCNConfigFetch.m, FirebaseRemoteConfig/Sources/RCNConfigSettings.m, FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
=> Only update fetch throttle interval for server errors

ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
Will need to verify that this includes the correct Analytics subspecs - but it should.
#no-changelog
=> Fix zip build with new Analytics subspecs.

Firebase.podspec, FirebaseCore/CHANGELOG.md
=> Remove AdMob subspec

FirebaseInAppMessaging.podspec
=> Fix FIAM resources for CocoaPods

Firebase/InstanceID/Public/FIRInstanceID.h, FirebaseABTesting/Sources/Public/FirebaseABTesting/FIRLifecycleEvents.h, FirebaseAppDistribution/Sources/Public/FirebaseAppDistribution/FIRAppDistribution.h, FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h, FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuthErrors.h, FirebaseAuth/Sources/Public/FirebaseAuth/FIREmailAuthProvider.h, FirebaseAuth/Tests/Unit/FIRAuthAppCredentialManagerTests.m, FirebaseDatabase/Sources/Api/Private/FTypedefs_Private.h, FirebaseDatabase/Sources/Core/FWriteTree.m, FirebaseDatabase/Tests/Integration/FIRDatabaseTests.m, FirebaseInAppMessaging.podspec, FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallations.h, FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessaging.h, FirebasePerformance/Sources/Public/FIRHTTPMetric.h, FirebasePerformance/Sources/Public/FIRPerformance.h, FirebasePerformance/Tests/Unit/Instruments/FPRNSURLSessionInstrumentTest.m, Firestore/Source/Public/FirebaseFirestore/FIRFirestore.h, Firestore/Source/Public/FirebaseFirestore/FIRFirestoreSettings.h, Firestore/Source/Public/FirebaseFirestore/FIRQuery.h, Firestore/core/src/util/error_apple.h, Functions/FirebaseFunctions/Public/FirebaseFunctions/FIRError.h, Interop/Analytics/Public/FIRInteropParameterNames.h, README.md, ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift, scripts/setup_check.sh, scripts/style.sh
These have all landed in `master` already.
- Fix FIAM resources for CocoaPods
- Fix zip build for new Analytics subspecs
- Update to clang-format 12 so CI passes on this branch
#no-changelog
=> Cherry-picks for M94

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage update for M94 - 7.11.0

.github/workflows/test_coverage.yml
Reference:
pull request actions and merge:
https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request
=> Skip test_coverage when a PR is closed

README.md
Preview: https://github.com/firebase/firebase-ios-sdk/blob/mm/appcheck-badge/README.md
#no-changelog
=> App check status badge in readme

FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheck.h, FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckDebugProvider.h, FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckProvider.h, FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckProviderFactory.h, FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckToken.h, FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRDeviceCheckProvider.h, FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRDeviceCheckProviderFactory.h
=> App Check Jazzydoc comment edits

FirebaseCombineSwift/Tests/Integration/Storage/StorageIntegration.swift
Hat tip to https://heckj.github.io/swiftui-notes/#patterns-testing-and-debugging
Signed-off-by: Peter Friese <peter@peterfriese.de>
=> Another take on verifying expected errors.

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 8.0.0 podspec.json files
=> Analytics 8.0.0

FirebaseCore.podspec, cmake/external/GoogleUtilities.cmake
Fixes [build failure](https://github.com/firebase/firebase-ios-sdk/runs/2456501007?check_suite_focus=true).
=> Firestore cmake: update GoogleUtilities version to 7.4.0

FirebaseAnalytics.podspec.json
=> Make sure that CocoaPods sees dependency collisions with AdMob

SwiftPackageManager.md
This PR just updates the SwiftPackageManager readme to reflect WatchOS support for RealtimeDB
=> Update readme to reflect WatchOS support for Realtime Database

FirebaseAppCheck/Sources/AppAttestProvider/Storage/FIRAppAttestKeyIDStorage.h, FirebaseAppCheck/Sources/AppAttestProvider/Storage/FIRAppAttestKeyIDStorage.m, FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.h, FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.m, FirebaseAppCheck/Sources/Core/Storage/FIRAppCheckStorage.h, FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestKeyIDStorageTests.m
• Implements `FIRAppAttestKeyIDStorage`
• Adds tests
[b/186653653](b/186653653)
=> Implement app attest key ID storage

Package.swift
Analytics SPM changes for 8.0.0.
=> Analytics SPM 8.0.0

FirebaseCore/Sources/FIRVersion.m
Confirmed this builds warning free
#no-changelog
=> Simplify version processing

Firestore/core/src/core/sync_engine.cc
These are the SyncEngine changes for the FieldValue migration.
=> SyncEngine changes for FieldValue migration

Firestore/Example/Firestore.xcodeproj/project.pbxproj, Firestore/core/src/core/array_contains_any_filter.cc, Firestore/core/src/core/array_contains_any_filter.h, Firestore/core/src/core/array_contains_filter.cc, Firestore/core/src/core/array_contains_filter.h, Firestore/core/src/core/field_filter.cc, Firestore/core/src/core/field_filter.h, Firestore/core/src/core/in_filter.cc, Firestore/core/src/core/in_filter.h, Firestore/core/src/core/key_field_filter.cc, Firestore/core/src/core/key_field_filter.h, Firestore/core/src/core/key_field_in_filter.cc, Firestore/core/src/core/key_field_in_filter.h, Firestore/core/src/core/key_field_not_in_filter.cc, Firestore/core/src/core/key_field_not_in_filter.h, Firestore/core/src/core/not_in_filter.cc, Firestore/core/src/core/not_in_filter.h, Firestore/core/src/local/local_store.cc, Firestore/core/test/unit/nanopb/nanopb_util_test.cc
Please compare to https://github.com/firebase/firebase-android-sdk/tree/master/firebase-firestore/src/main/java/com/google/firebase/firestore/core
=> FieldFilter changes for Protobuf migration

FirebaseDatabaseSwift.podspec, Package.swift, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
#no-changelog since it'll wait until next release to formalize.
=> Prepare RTDB Swift for release.

FirebaseAppCheck/Apps/FIRAppCheckTestApp/FIRAppCheckTestApp/AppDelegate.swift, FirebaseAppCheck/Apps/FIRAppCheckTestApp/Podfile, FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m, FirebaseAppCheck/Sources/Core/Utils/FIRAppCheckCryptoUtils.h, FirebaseAppCheck/Sources/Core/Utils/FIRAppCheckCryptoUtils.m, FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestProviderTests.m, FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckCryptoUtilsTests.m
- hash challenge with SHA256
- add App Attest provider to the test app
- minor cleanup
b/186437900
#no-changelog
=> App Check App Attest initial handshake adjustments

Firestore/core/src/local/leveldb_remote_document_cache.cc, Firestore/core/src/local/leveldb_remote_document_cache.h, Firestore/core/src/local/memory_remote_document_cache.cc, Firestore/core/src/local/memory_remote_document_cache.h, Firestore/core/src/local/remote_document_cache.h, Firestore/core/test/unit/local/remote_document_cache_test.cc, Firestore/core/test/unit/local/remote_document_cache_test.h
RemoteDocumentCache changes for Protobuf migration.
=> RemoteDocumentCache changes

Firestore/Example/Tests/API/FSTAPIHelpers.mm, Firestore/Example/Tests/API/FSTUserDataReaderTests.mm, Firestore/Example/Tests/Integration/FSTDatastoreTests.mm, Firestore/Example/Tests/SpecTests/FSTSpecTests.mm, Firestore/Example/Tests/Util/FSTHelpers.h, Firestore/Example/Tests/Util/FSTHelpers.mm
This migrates the Spec Tests and the integration tests to Protobuf
=> Objective-C Test Changes

README.md
=> Special instructions no longer necessary for Apple Silicon

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/Components/FIRCLSProcess.c, Crashlytics/Crashlytics/Components/FIRCLSProcess.h, Crashlytics/Crashlytics/Handlers/FIRCLSHandler.m
=> Remove unused method

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c
=> Change variable logged when handler unable to be installed

Crashlytics/Crashlytics/Helpers/FIRCLSFile.m
=> Spelling fixes in FIRCLSFile.m

Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c, Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c, Crashlytics/Crashlytics/Handlers/FIRCLSSignal.h
=> Propogate signals after handling

Firestore/Example/Firestore.xcodeproj/project.pbxproj, Firestore/core/src/bundle/bundle_callback.h, Firestore/core/src/bundle/bundle_document.h, Firestore/core/src/bundle/bundle_loader.cc, Firestore/core/src/bundle/bundle_loader.h, Firestore/core/src/bundle/bundle_serializer.cc, Firestore/core/src/bundle/bundle_serializer.h, Firestore/core/src/remote/serializer.cc, Firestore/core/src/remote/serializer.h, Firestore/core/test/unit/bundle/bundle_serializer_test.cc
Please see Android for any datatype changes.
=> Remaining Bundle changes

Crashlytics/CHANGELOG.md, Crashlytics/Crashlytics/Components/FIRCLSUserLogging.m
Fixes a potential race condition as identified in #8102
=> Synchronize access to active path

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 8.1.0 podspec.json files.
=> Analytics 8.1.0

FirebaseDatabase.podspec, scripts/code_coverage_report/generate_code_coverage_report/Package.swift, scripts/code_coverage_report/generate_code_coverage_report/Sources/CoverageReportGenerator/CoverageReportParser.swift, scripts/code_coverage_report/generate_code_coverage_report/Sources/Utils/ShellUtils.swift
This shell wrapper will be applied to the incremental code coverage as well.
=> Applied shell wrapper to the current code coverage.

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> M97 carthage files update

.swiftpm/xcode/xcshareddata/xcschemes/StorageUnit.xcscheme, FirebaseStorage/Tests/Unit/FIRStorageReferenceTests.m
=> Fix Xcode 12.5 analyze issue in Storage unit tests

.swiftpm/xcode/xcshareddata/xcschemes/AuthUnit.xcscheme, FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m, FirebaseAuth/Tests/Unit/FIRFakeBackendRPCIssuer.h, FirebaseAuth/Tests/Unit/FIRFakeBackendRPCIssuer.m
=> Fixed analyze issues introduced in Xcode 12.5

FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m
=> Add check to address 8210 review

FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m
=> Fix style issue from quick merge of 8214

.github/workflows/zip.yml
Fix #8207
Facebook SDK 11 added `FBSDKCoreKit_Basics`
#no-changelog
=> Add new Facebook SDK dependency pod

Firebase.podspec, FirebaseAnalytics.podspec.json, FirebaseCore/CHANGELOG.md, GoogleAppMeasurement.podspec.json, Package.swift
I'm planning to publish 8.1.1 for CocoaPods and SPM once this PR is reviewed, passes CI, and merges.
=> Cherry-pick Analytics PR and update versions and release notes for 8.1.1

.github/workflows/spm.yml
=> Speed up SPM CI by reducing full Firebase rebuilds

ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
=> Carthage update for 8.1.1

Firebase.podspec, FirebaseCore/CHANGELOG.md, Package.swift
Merge 8.1.1 specific changes back to master
=> Merge 8.1.1 to master

FirebaseSegmentation/Sources/SEGDatabaseManager.m
=> Fix inconsistent type assignment detected by Xcode 12.5 analyzer

FirebaseInAppMessaging/CHANGELOG.md, FirebaseInAppMessaging/iOS/Resources/FIRInAppMessageDisplayStoryboard.storyboard
Addresses constraint errors in #8205.
Fix #8205
=> Add dummy constraint to card view to fix Autolayout missing constraints

FirebaseMessaging/CHANGELOG.md, FirebaseMessaging/Sources/FIRMessagingContextManagerService.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingContextManagerServiceTest.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingUtilitiesTest.m
=> Ensure sound is assigned with right type

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
=> M98 Analytics

FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift
Fix #8259
Fix the Combine Auth tests that need another mock after #8196
=> Fix newly failing auth combine test

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
This reverts commit 500ea2d38452e5f8a01d3d17a87976574a8983c3.
Cherry-pick to release-8.2 branch
=> Revert "Support Unity generated Podfiles (#8193)" (#8284)

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> M98 carthage update

scripts/build_non_firebase_sdks.sh
This should fix the CI issue in #8290 
I'm surprised this didn't come up before ...
=> Fix Swift version for zip tests

Firebase.podspec
Fixes https://github.com/firebase/firebase-ios-sdk/issues/8310
=> Update AppCheck subspec dependency to support macOS / tvOS

Crashlytics/CHANGELOG.md, FirebaseCrashlytics.podspec, Package.swift
Fix #8137 
Add missing dependency that could cause build failures.
=> Add missing Crashlytics dependency

.github/workflows/test_coverage.yml
Thanks Yifan for pointing out the issue on the test coverage workflow
The code coverage is comparing a merge commit to the common commit of a PR and the target branch. This will involve changes between this common commit and the latest commit of the target branch. This update will switch the common commit of the PR to the latest commit on the target branch.
Update indent of the workflow.
=> Update base commit of code coverage

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 8.3.0 podspec.json files
=> Analytics 8.3.0

Package.swift
Analytics SPM changes for 8.3.0
=> Analytics SPM 8.3.0

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json, Package.swift
Update Analytics Podspec and SPM changes for 8.3.0
=> Update Analytics 8.3.0

CONTRIBUTING.md
Improvements to the Contributing doc. Some sections are commented out and some TODO's are added. Lmk what you think of those sections and we can work on expanding on them gradually.
#no-changelog
=> Improvements to the Contributing doc

README.md
=> Update docs for Mac keychain sharing

FirebaseFunctions.podspec, Functions/Tests/Unit/Swift/FunctionsAPITests.swift
Swift API build tests for Functions library
#no-changelog
=> Functions API build tests

FirebaseInstallations.podspec, FirebaseInstallations/Source/Tests/Unit/Swift/InstallationsAPITests.swift
=> Installations API build tests

.github/workflows/abtesting.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/zip.yml
=> Update abt gha to test legacy qs

.github/workflows/storage.yml
=> Update storage workflow

SymbolCollisionTest/Podfile
=> Restore GoogleMLKit to Symbol Collision test

FirebaseCore/Tests/SwiftUnit/CoreAPITests.swift
=> Core API build tests

.github/workflows/prerelease.yml
I misplaced the environment variable in #8358 and the prerelease workflow failed in #8364.
This should fix.
=> Fix nightly prerelease failure

Crashlytics/CHANGELOG.md, FirebaseAppCheck.podspec, FirebaseAppCheck/CHANGELOG.md, FirebaseCrashlytics.podspec, FirebaseInstallations.podspec, FirebaseInstallations/CHANGELOG.md, Package.swift
Plan is to:
- merge this PR
- wait for clean nightlies
- then publish GDT & GUL minor releases
Fixes #8334
=> Bump Promises dependency

.github/workflows/functions.yml, .github/workflows/installations.yml
Seen in Installations and Functions workflow nightlies
#no-changelog
Fixes #8364
=> Fix nightly Swift API failures

FirebaseCore/CHANGELOG.md, Package.swift
=> Bump GoogleAppMeasurement dependency to 8.3.1

FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
Add dummy class to conform to AppCheck protocol
#no-changelog
=> Update swift API tests

Firebase.podspec, FirebaseABTesting.podspec, FirebaseAnalyticsSwift.podspec, FirebaseAppCheck.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCoreDiagnostics.podspec, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseDatabaseSwift.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFirestoreSwift.podspec, FirebaseFunctions.podspec, FirebaseInAppMessaging.podspec, FirebaseInAppMessagingSwift.podspec, FirebaseInstallations.podspec, FirebaseMLModelDownloader.podspec, FirebaseMessaging.podspec, FirebasePerformance.podspec, FirebaseRemoteConfig.podspec, FirebaseStorage.podspec, FirebaseStorageSwift.podspec, Package.swift, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
M100 Release version bumps.
#no-changelog
=> Update versions for Release 8.4.0

FirebaseStorage/CHANGELOG.md, FirebaseStorage/Sources/FIRStorage.m
=> Allow http when using emulator

FirebaseStorage/CHANGELOG.md
=> Fix bad version number in changelog

Crashlytics/Shared/FIRCLSNetworking/FIRCLSFABNetworkClient.m, FirebaseAppDistribution/Sources/FIRFADApiService.m, FirebaseAuth/Sources/Auth/FIRAuth.m, FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthProvider.m, FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m, FirebaseAuth/Sources/Backend/FIRAuthBackend.m, FirebaseAuth/Sources/SystemService/FIRSecureTokenService.m, FirebaseAuth/Sources/User/FIRUser.m, FirebaseCore/Sources/FIRApp.m, FirebaseDatabase/Sources/Api/Private/FTypedefs_Private.h, FirebaseDatabase/Tests/Integration/FData.m, FirebaseDatabase/Tests/Integration/FOrder.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMClientInfoFetcher.m, FirebaseInAppMessaging/Sources/Runtime/FIRIAMRuntimeManager.m, FirebaseMessaging/Sources/FIRMessaging.m, FirebaseMessaging/Sources/Token/FIRMessagingAuthService.m, FirebasePerformance/Tests/Unit/Instruments/FPRNSURLSessionInstrumentTest.m, FirebaseRemoteConfig/Sources/RCNConfigFetch.m, FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m, FirebaseStorage/Sources/FIRStorageObservableTask.m
=> Update to clang-format 12.0.1

FirebaseAppCheck.podspec
Should fix https://github.com/firebase/firebase-ios-sdk/runs/3083903668?check_suite_focus=true
Test run: https://github.com/firebase/firebase-ios-sdk/actions/runs/1037955080
=> Bump App Check version to 8.5.0-beta

.github/workflows/spm.yml, FirebaseInAppMessaging/Sources/DefaultUI/Banner/FIRIAMBannerViewController.h, FirebaseInAppMessaging/Sources/DefaultUI/Card/FIRIAMCardViewController.h, FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMBaseRenderingViewController.h, FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.h, FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMRenderingWindowHelper.h, FirebaseInAppMessaging/Sources/DefaultUI/ImageOnly/FIRIAMImageOnlyViewController.h, FirebaseInAppMessaging/Sources/DefaultUI/Modal/FIRIAMModalViewController.h, FirebaseInAppMessaging/Sources/Private/Flows/FIRIAMDisplayCheckOnAnalyticEventsFlow.h, FirebaseInAppMessaging/Sources/Private/Flows/FIRIAMDisplayExecutor.h, FirebaseInAppMessaging/Sources/Private/Flows/FIRIAMFetchOnAppForegroundFlow.h, FirebaseInAppMessaging/Sources/Private/Flows/FIRIAMMessageClientCache.h, FirebaseInAppMessaging/Sources/Private/Runtime/FIRIAMFetchFlow.h, FirebaseInAppMessaging/Sources/Private/Runtime/FIRIAMRuntimeManager.h, FirebaseInAppMessaging/Sources/Public/FirebaseInAppMessaging/FIRInAppMessaging.h, FirebaseInAppMessaging/Sources/Public/FirebaseInAppMessaging/FIRInAppMessagingRendering.h, FirebaseInAppMessaging/Sources/Runtime/FIRIAMActionURLFollower.m, FirebaseInAppMessaging/Swift/Source/CustomInAppMessageDisplayViewModifier.swift, FirebaseInAppMessaging/Swift/Source/SwiftUIPreviewHelpers.swift, SwiftPMTests/swift-test/main.swift, scripts/build.sh
=> Fix tvOS SPM tests

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
Carthage release for M100 8.4.0.
#no-changelog
=> Update Carthage M100 release.

Firestore/core/src/api/query_core.cc
This fixes the last leak in the field value port.
=> Fix leak in reference value parsing

FirebaseDatabase.podspec, FirebaseDatabase/Tests/Unit/Swift/DatabaseAPITests.swift, Package.swift, SwiftPMTests/swift-test/main.swift, scripts/build.sh
=> Database API build tests

scripts/check.sh, scripts/check_firestore_core_api_absl.py, scripts/check_imports.swift
Also add exception to check_imports.swift to exclude cmake build directories.
=> Add script to check for absl reference from Firestore/core/api

FirebaseStorageSwift/Sources/AsyncAwait.swift
Note that iOS 15 also covers Catalyst
#no-changelog
=> Fix AsyncAwait build for macos and tvos

Gemfile, Gemfile.lock
=> Update to CocoaPods 1.10.2

SwiftPMTests/swift-test/main.swift
=> Add AppCheck to SwiftPM tests

.github/workflows/spm.yml, Package.swift, SwiftPMTests/objc-import-test/objc-header.m, SwiftPMTests/objc-import-test/objc-module.m
Also:
- add AppCheck to swift import tests
- add AppCheck to objc import tests
#no-changelog
=> Run spm workflow when changes in SwiftPMTests/*

.github/workflows/database.yml, scripts/spm_test_schemes/DatabaseUnitSwift.xcscheme
Enable SPM testing of DatabaseUnitSwift other than as part of the full Firebase-package.
#no-changelog
=> Add DatabaseUnitSwift scheme and add it to GHA

.github/workflows/app_check.yml
=> Add `spm` workflows to AppCheck GHA

FirebaseDynamicLinks/CHANGELOG.md, FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FDLURLComponents.h, FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLinks.h
=> Move Dynamic Links to API_UNAVAILABLE

.github/workflows/test_coverage.yml
Will test from a fork after submit.
For #7476
=> Check fork PRs before running coverage

.github/workflows/zip.yml
Fixes the `zip` auth qs [failure](https://github.com/firebase/firebase-ios-sdk/runs/3251416294?check_suite_focus=true#step:8:319) from https://github.com/firebase/firebase-ios-sdk/issues/8471#issuecomment-893449537
#no-changelog
=> Add FBAEMKit to auth qs zip build

Firebase.podspec, FirebaseABTesting.podspec, FirebaseAnalytics.podspec.json, FirebaseAnalyticsSwift.podspec, FirebaseAppCheck.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCoreDiagnostics.podspec, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseDatabaseSwift.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFirestoreSwift.podspec, FirebaseFunctions.podspec, FirebaseInAppMessaging.podspec, FirebaseInAppMessagingSwift.podspec, FirebaseInstallations.podspec, FirebaseMLModelDownloader.podspec, FirebaseMessaging.podspec, FirebasePerformance.podspec, FirebaseRemoteConfig.podspec, FirebaseStorage.podspec, FirebaseStorageSwift.podspec, GoogleAppMeasurement.podspec.json, Package.swift, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
=> Update versions for Release 8.6.0

FirebaseAuth/CHANGELOG.md, Firestore/CHANGELOG.md
=> CHANGELOG updates for M102

FirebasePerformance/Sources/Common/FPRDiagnostics.h, FirebasePerformance/Tests/Unit/Common/FPRDiagnosticsTest.m
=> Fix perf assert macro

SwiftPackageManager.md
=> Update Swift Package Manager doc

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage M102

ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift
Up until now, the release tooling only bumped the podspecs of open source libraries.
Since the podspecs for the close source libraries (`FirebaseAnalytics` and `GoogleAppMeasurement`) are in `JSON`, the  tooling had to be slightly adjusted to bump the versions in that file type.
#no-changelog
=> Version bump Analytics specs with release tooling

Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
=> Fix Firestore test build on Xcode 13

.github/workflows/storage.yml, FirebaseStorageSwift/Sources/AsyncAwait.swift
- Fix watchOS build issue for Xcode 13 and FirebaseStorageSwift and watchOS
- Add watchOS CI for FirebaseStorage
#no-changelog
=> Add CI for watchOS and Firebase Storage

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 8.7.0 podspec.json files
Fixes #7577
=> Analytics 8.7.0

FirebaseAuth/Tests/Sample/Sample/ApplicationDelegate.m
See firebase/quickstart-ios#1157
#no-changelog
=> Fix Facebook Login for test app

Crashlytics/Crashlytics/Controllers/FIRCLSExistingReportManager.m, Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.m, FirebaseDynamicLinks/Tests/Unit/FDLURLComponentsTests.m, FirebaseRemoteConfig/Sources/RCNConfigContent.h
Just found the typo while investigating the unrelated crashed in Crashlytics.
=> Typo fixed

Gemfile, Gemfile.lock
=> CocoaPods 1.11.2

FirebaseAppCheck/CHANGELOG.md, FirebaseAppCheck/Sources/Core/APIService/FIRAppCheckAPIService.m, FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckAPIServiceTests.m
=> [AppCheck] Add support for bundle ID-based API Key Restrictions

Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.h, Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.m, Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m, Crashlytics/Crashlytics/Helpers/FIRCLSCallStackTree.m, Crashlytics/Crashlytics/Helpers/FIRCLSDefines.h, Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m, Crashlytics/UnitTests/Mocks/FIRCLSMockMXCPUExceptionDiagnostic.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXCallStackTree.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXCrashDiagnostic.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXDiagnosticPayload.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXDiskWriteExceptionDiagnostic.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXDiskWriteExceptionDiagnostic.m, Crashlytics/UnitTests/Mocks/FIRCLSMockMXHangDiagnostic.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXHangDiagnostic.m, Crashlytics/UnitTests/Mocks/FIRCLSMockMXMetadata.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMetricKitManager.m
=> Fix compiler checks for xcode 13

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 8.8.0 podspec.json files
=> Analytics 8.8.0

Package.swift
Analytics 8.8.0 Package.swift file
=> Analytics SPM 8.8.0

Crashlytics/Crashlytics/Controllers/FIRCLSExistingReportManager.m, Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.h, Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.m, Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m, Crashlytics/Crashlytics/Helpers/FIRCLSCallStackTree.m, Crashlytics/Crashlytics/Helpers/FIRCLSDefines.h, Crashlytics/Crashlytics/Models/FIRCLSFileManager.h, Crashlytics/Crashlytics/Models/FIRCLSFileManager.m, Crashlytics/Crashlytics/Models/FIRCLSSettings.m, Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m, Crashlytics/UnitTests/Mocks/FIRCLSMockMXCPUExceptionDiagnostic.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXCallStackTree.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXCrashDiagnostic.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXDiagnosticPayload.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXDiskWriteExceptionDiagnostic.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXDiskWriteExceptionDiagnostic.m, Crashlytics/UnitTests/Mocks/FIRCLSMockMXHangDiagnostic.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMXHangDiagnostic.m, Crashlytics/UnitTests/Mocks/FIRCLSMockMXMetadata.h, Crashlytics/UnitTests/Mocks/FIRCLSMockMetricKitManager.m
=> Upload fatal MK reports on the next run of the app

Crashlytics/Crashlytics/Handlers/FIRCLSException.mm
The fix for https://github.com/firebase/firebase-ios-sdk/issues/8671#event-5344539601
=> Fix issue with null reason

Crashlytics/CHANGELOG.md
=> Update changelog for #8671

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage JSON updates for M105

FirebaseAuth/CHANGELOG.md
=> Update changelog for email link MFA support.

ReleaseTooling/Template/README.md
=> Improve zip integration docs for Swift

.github/workflows/check.yml, CONTRIBUTING.md, Crashlytics/Shared/FIRCLSNetworking/FIRCLSFABNetworkClient.m, FirebaseAppDistribution/Sources/FIRFADApiService.m, FirebaseAuth/Sources/Auth/FIRAuth.m, FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthProvider.m, FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m, FirebaseAuth/Sources/Backend/FIRAuthBackend.m, FirebaseAuth/Sources/SystemService/FIRSecureTokenService.m, FirebaseAuth/Sources/User/FIRUser.m, FirebaseCore/Sources/FIRApp.m, FirebaseDatabase/Tests/Integration/FData.m, FirebaseDatabase/Tests/Integration/FOrder.m, FirebaseInAppMessaging/Sources/Flows/FIRIAMClientInfoFetcher.m, FirebaseInAppMessaging/Sources/Runtime/FIRIAMRuntimeManager.m, FirebaseMessaging/Sources/FIRMessaging.m, FirebaseMessaging/Sources/Token/FIRMessagingAuthService.m, FirebaseRemoteConfig/Sources/RCNConfigFetch.m, FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m, FirebaseStorage/Sources/FIRStorageObservableTask.m, README.md, scripts/setup_check.sh, scripts/style.sh
Fix #8737 
GHA dropped clang-format@12, so `brew upgrade clang-format` to 13 and make corresponding source updates.
=> Update to clang-format@13

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 8.9.1 podspec.json files
=> Analytics 8.9.1

Package.swift
Update SPM for Analytics 8.9.1
=> Analytics SPM 8.9.1

Firebase.podspec, Package.swift
=> Firebase version updates for 8.9.1

Firestore/CHANGELOG.md, Firestore/core/src/credentials/firebase_app_check_credentials_provider_apple.mm
Fixes https://github.com/firebase/firebase-ios-sdk/issues/8895
=> Check for AppCheck's existance before subscribing

HeartbeatLogging/Sources/HeartbeatController.swift, HeartbeatLogging/Sources/HeartbeatInfo.swift, HeartbeatLogging/Sources/HeartbeatStorage.swift, HeartbeatLogging/Sources/JSONCoder.swift, HeartbeatLogging/Sources/PersistentStorage.swift, HeartbeatLogging/Tests/Integration/HeartbeatLoggingIntegrationTests.swift, HeartbeatLogging/Tests/Unit/HeartbeatControllerTests.swift, HeartbeatLogging/Tests/Unit/HeartbeatStorageTests.swift
- Added unit tests for `HeartbeatController` and `HeartbeatStorage`
- Reworked some areas to improve testability
- Resolved some TODO's from previous PR's and added some TODOs to think about in future PRs
#no-changelog
=> [Heartbeat Logging] Controller and Storage Unit tests

Firebase.podspec, FirebaseFirestore.podspec, Firestore/CHANGELOG.md, Firestore/core/src/credentials/firebase_app_check_credentials_provider_apple.mm
- Cherry pick #8898 
- Cherry pick #8900 
- Update Firestore podspec and Changelog version to 8.9.1
=> Cherry picks and versions for Firestore 8.9.1

Firebase.podspec, FirebaseFirestore.podspec, Firestore/CHANGELOG.md
Most of 8.9.1 was already in master. This PR brings back the rest.
=> Merge 8.9.1 back to master

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage 8.9.1

Firestore/Swift/Source/PropertyWrapper/FirestoreQuery.swift
=> Fix doc typos in FirestoreQuery.swift

Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm, Firestore/Source/API/FSTFirestoreComponent.mm
=> Remove unused 'using' declarations

Firestore/Example/Tests/API/FIRFieldPathTests.mm, Firestore/Example/Tests/API/FIRFirestoreTests.mm, Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm, Firestore/Example/Tests/API/FSTAPIHelpers.mm, Firestore/Example/Tests/API/FSTUserDataReaderTests.mm, Firestore/Example/Tests/Integration/API/FIRBundlesTests.mm, Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm, Firestore/Example/Tests/Integration/API/FIRValidationTests.mm, Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm, Firestore/Example/Tests/Integration/FSTDatastoreTests.mm, Firestore/Example/Tests/SpecTests/FSTSpecTests.mm, Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h, Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm, Firestore/Example/Tests/Util/FIRFirestore+Testing.h, Firestore/Example/Tests/Util/FSTHelpers.mm, Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm, Firestore/core/src/api/query_core.cc, Firestore/core/src/timestamp_internal.cc
These changes fix the build when this code is copied into google3.
#no-changelog
=> Get rid of util and testutil namespace aliases

FirebaseCore/CHANGELOG.md
Mention community support for Combine in the changelog for 8.10.0
=> Add Combine to changelog

Firestore/Example/Firestore.xcodeproj/project.pbxproj, Firestore/core/src/remote/firebase_metadata_provider.h, Firestore/core/src/remote/grpc_adapt/grpc_cpp_adaption.h, Firestore/core/src/remote/grpc_adapt/grpc_swift_misc.h, Firestore/core/test/unit/nanopb/message_test.cc, Firestore/core/test/unit/remote/datastore_test.cc, Firestore/core/test/unit/remote/grpc_stream_test.cc, Firestore/core/test/unit/remote/grpc_stream_tester.cc, Firestore/core/test/unit/remote/grpc_streaming_reader_test.cc, Firestore/core/test/unit/remote/grpc_unary_call_test.cc, Firestore/core/test/unit/remote/stream_test.cc
This fixes the CMake build for me.
=> Make CMake project compile

FirebasePerformance/CHANGELOG.md, FirebaseRemoteConfig/CHANGELOG.md
=> Update CHANGELOGs for 8.10.0

Firebase.podspec, FirebaseABTesting.podspec, FirebaseAnalytics.podspec.json, FirebaseAnalyticsSwift.podspec, FirebaseAppCheck.podspec, FirebaseAppDistribution.podspec, FirebaseAuth.podspec, FirebaseCore.podspec, FirebaseCoreDiagnostics.podspec, FirebaseCrashlytics.podspec, FirebaseDatabase.podspec, FirebaseDatabaseSwift.podspec, FirebaseDynamicLinks.podspec, FirebaseFirestore.podspec, FirebaseFirestoreSwift.podspec, FirebaseFunctions.podspec, FirebaseInAppMessaging.podspec, FirebaseInAppMessagingSwift.podspec, FirebaseInstallations.podspec, FirebaseMLModelDownloader.podspec, FirebaseMessaging.podspec, FirebasePerformance.podspec, FirebaseRemoteConfig.podspec, FirebaseStorage.podspec, FirebaseStorageSwift.podspec, GoogleAppMeasurement.podspec.json, Package.swift, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
=> Update versions for Release 8.10.0

.github/ISSUE_TEMPLATE/bug_report.md
This is to call out specific platform issues. Open to suggestions but this seemed like the smallest possible change to get the extra information.
=> Add platform flag to environment description.

README.md
=> updated Linking word in README

FirebaseDynamicLinks/Sources/Utilities/FDLUtilities.m, FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m
Added back the regex to check for more than one path in short url.
=> Fixing the short url logic

FirebaseCore/CHANGELOG.md
=> Update FirebaseCore CHANGELOG for 8.10.0

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage M108

FirebaseInAppMessaging/CHANGELOG.md
Updating changelog to reflect fix for #8907
=> Updating changelog to reflect fix for #8907

FirebaseAuth/Sources/SystemService/FIRSecureTokenService.h, FirebaseAuth/Sources/SystemService/FIRSecureTokenService.m, FirebaseAuth/Sources/User/FIRUser.m, FirebaseAuth/Tests/Unit/FIRAuthTests.m, FirebaseAuth/Tests/Unit/FIRUserTests.m
Creating a new remote `passthrough` branch, and transferring the changes from `yunmiao-passthrough` to this branch.
=> Move passthrough changes onto "passthrough" branch.

SwiftDashboard.md
- Functions async/await completed in #8959
- RC should consider Codable #9075 
- SwiftUI Interop is n/a for Storage
- Update Storage Error Code implementation status
- Firestore should consider more property wrappers
=> Swift Dashboard Updates

SwiftDashboard.md
=> Fix roadmap link from Swift Modernization Dashboard

scripts/generate_access_token.sh, scripts/setup_bundler.sh
=> Update remote `generate_access_token` script

FirebaseAuth/CHANGELOG.md, FirebaseAuth/Sources/AuthProvider/OAuth/FIROAuthProvider.m, FirebaseAuth/Tests/Unit/FIROAuthProviderTests.m
=> Add multi-tenancy support to generic OAuth providers.

Firestore/Source/Public/FirebaseFirestore/FIRDocumentReference.h, Firestore/Source/Public/FirebaseFirestore/FIRTransaction.h, Firestore/Source/Public/FirebaseFirestore/FIRWriteBatch.h
=> Improve documentation for merge behavior

FirebaseDatabase/CHANGELOG.md, FirebaseDatabase/Sources/Utilities/FUtilities.m
=> Fix RTDB crash from race

Firestore/Source/Public/FirebaseFirestore/FIRDocumentReference.h, Firestore/Source/Public/FirebaseFirestore/FIRTransaction.h, Firestore/Source/Public/FirebaseFirestore/FIRWriteBatch.h
See https://github.com/googleapis/nodejs-firestore/pull/1648
=> Update wording for merge message

ReleaseTooling/README.md
=> Fix ZipBuilder option in README

FirebaseFunctionsSwift/Sources/Codable/Callable+Codable.swift
=> Update Functions Swift public API docs

FirebaseAuth/Sources/SystemService/FIRSecureTokenService.m, FirebaseAuth/Sources/User/FIRUser.m
=> Fix an issue with user persistence when no refresh token is present.

FirebaseStorageSwift/Sources/AsyncAwait.swift
Avoid `typealias` in favor of implicit typing
=> Remove unnecessary typealias

FirebaseAuth/Sources/SystemService/FIRSecureTokenService.m, FirebaseAuth/Tests/Unit/FIRUserTests.m
Return a `FIRAuthErrorCodeUserMismatch` error if there is a user ID mismatch after refreshing the ID token with the `CustomTokenProviderDelegate`.
#no-changelog
=> Handle user ID mismatch

scripts/health_metrics/README.md
Add the description of explicit platform, iOS, to the doc.
=> Update size measurement doc

scripts/health_metrics/generate_code_coverage_report/Sources/Utils/MetricsServiceRequest.swift
Update endpoint of the Metrics Service
=> Update endpoint of the Metrics Service

Crashlytics/Crashlytics/Components/FIRCLSContext.h, Crashlytics/Crashlytics/Components/FIRCLSContext.m, Crashlytics/Crashlytics/Controllers/FIRCLSReportManager_Private.h, Crashlytics/Crashlytics/Handlers/FIRCLSException.h, Crashlytics/Crashlytics/Handlers/FIRCLSException.mm, Crashlytics/Crashlytics/Handlers/FIRCLSHandler.h, Crashlytics/Crashlytics/Handlers/FIRCLSHandler.m, Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c, Crashlytics/Crashlytics/Handlers/FIRCLSMachException.h
Removes unused code.
#no-changelog
=> Code clean-up

Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRStackFrame.h
=> Fix Crashlytics docs typo

Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.m
Updates the determination of a MetricKit file path.
#no-changelog
=> Update path determination

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage update for 8.11.0

.github/workflows/app_check.yml, FirebaseAppCheck/CHANGELOG.md, FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift, Package.swift
=> Fix SPM AppCheck build for watchOS

.github/workflows/abtesting.yml, .github/workflows/auth.yml, .github/workflows/core.yml, .github/workflows/crashlytics.yml, .github/workflows/database.yml, .github/workflows/installations.yml, .github/workflows/mlmodeldownloader.yml, .github/workflows/remoteconfig.yml
=> Add missing watchOS CI

FirebaseAuth/Tests/Sample/ApiTests/FIRAuthApiTestsBase.h, FirebaseAuth/Tests/Sample/ApiTests/PhoneMultiFactorTests.swift, FirebaseAuth/Tests/Sample/SwiftApiTests/AccountInfoTests.swift, FirebaseAuth/Tests/Sample/SwiftApiTests/AnonymousTests.swift, FirebaseAuth/Tests/Sample/SwiftApiTests/EmailPasswordTests.swift, FirebaseAuth/Tests/Sample/SwiftApiTests/FacebookTests.swift, FirebaseAuth/Tests/Sample/SwiftApiTests/GoogleTests.swift, FirebaseAuth/Tests/Sample/SwiftApiTests/TestsBase.swift, scripts/style.sh
I also tried to style the Auth Sample, but some of the callbacks get ugly. 
#no-changelog
=> Style Auth Integration Tests

FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h, FirebaseAuth/Tests/Sample/AuthSample.xcodeproj/project.pbxproj, FirebaseAuth/Tests/Sample/SwiftApiTests/SwiftAPI.swift, FirebaseAuth/Tests/Sample/SwiftApiTests/SwiftApi.swift, SwiftDashboard.md
=> Add Swift API coverage tests for Auth

Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.h
=> Increase binary image count

.github/workflows/zip.yml
=> Run zip ci earlier to make sure it finishes

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 8.12.0 podspec.json files
=> Analytics 8.12.0

Package.swift
Analytics SPM changes for 8.12.0
=> Analytics SPM 8.12.0

Crashlytics/Crashlytics/Components/FIRCLSApplication.h, Crashlytics/Crashlytics/Controllers/FIRCLSExistingReportManager.h, Crashlytics/Crashlytics/Controllers/FIRCLSManagerData.h, Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m, Crashlytics/Crashlytics/DataCollection/FIRCLSDataCollectionToken.h, Crashlytics/Crashlytics/FIRCLSUserDefaults/FIRCLSUserDefaults.m, Crashlytics/Crashlytics/Helpers/FIRCLSCallStackTree.h, Crashlytics/Crashlytics/Helpers/FIRCLSUtility.m, Crashlytics/Crashlytics/Models/FIRCLSInternalReport.h, Crashlytics/Crashlytics/Models/Record/FIRCLSRecordBase.h, Crashlytics/Crashlytics/Private/FIRStackFrame_Private.h, Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h, Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlyticsReport.h, Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRExceptionModel.h, Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRStackFrame.h, Crashlytics/Crashlytics/Settings/Operations/FIRCLSDownloadAndSaveSettingsOperation.h, Crashlytics/Shared/FIRCLSByteUtility.h, Crashlytics/Shared/FIRCLSUUID.h, FirebaseCore/Sources/Private/FIRAppInternal.h, FirebaseCore/Sources/Private/FIRComponent.h, FirebaseCore/Sources/Private/FIRComponentContainer.h, FirebaseCore/Sources/Private/FIRCoreDiagnosticsConnector.h, FirebaseCore/Sources/Private/FIRDependency.h, FirebaseCore/Sources/Private/FIRLibrary.h, FirebaseCore/Sources/Private/FIRLogger.h, FirebaseCore/Sources/Private/FIROptionsInternal.h, Interop/Analytics/Public/FIRAnalyticsInterop.h, Interop/Analytics/Public/FIRAnalyticsInteropListener.h, Interop/Analytics/Public/FIRInteropParameterNames.h
=> update docs to reference swift > objc

Firestore/core/src/index/index_entry.cc, Firestore/core/src/index/index_entry.h
=> Add IndexEntry

Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.m
=> Update recorded MetricKit timestamp to reflect framework updates.

FirebaseFunctions/Tests/Unit/FIRFunctionsTests.m, FirebaseFunctionsSwift/Sources/Functions.swift, FirebaseFunctionsSwift/Tests/Unit/FunctionsTests.swift, FirebaseFunctionsSwift/Tests/Unit/SerializerTests.swift
Checkpoint unit test progress and a few other fixes
#no-changelog
=> Start porting unit tests

.github/workflows/functions.yml, .github/workflows/spectesting.yml, FirebaseAppCheckInterop.podspec, FirebaseCoreInternal.podspec, FirebaseFunctionsSwift.podspec, FirebaseFunctionsSwift/Sources/FunctionsSerializer.swift, FirebaseFunctionsSwift/Tests/Unit/SerializerTests.swift
- Ports Functions serializer tests to Swift 
- Implements UInt64 encoding
- Miscellaneous other fixes and cleanups
#no-changelog
=> Port serializer tests and fix exposed issues

Firestore/CHANGELOG.md, Firestore/core/src/core/firestore_client.cc
This reverts commit a026e3d08eb2833777a867ad2378c203353987e3.
=> Revert "Re-establish streams when App Check token expires. (#9233)"

Firebase.podspec, FirebaseCore.podspec, FirebaseFirestore.podspec, FirebaseFirestoreSwift.podspec, Firestore/CHANGELOG.md, Package.swift, ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
Also updating the Firebase zip builder manifest which wasn't done.
#no-changelog
=> Merging the 8.12.1 release into master

scripts/health_metrics/get_updated_files.sh
Discovered in https://github.com/firebase/firebase-ios-sdk/runs/5189995710?check_suite_focus=true#step:3:39
=> Fix improper spacing in bash script.

HeartbeatLogging/Sources/HeartbeatsPayload.swift, HeartbeatLogging/Tests/Unit/HeartbeatStorageTests.swift
- Run style script on the branch
- Add two TODOs
**Context**
The [`platform-logging-main`](https://github.com/firebase/firebase-ios-sdk/tree/platform-logging-main) is new and was created off of master and then the 12 (approved) heartbeat-related commits from [`heartbeats-main`](https://github.com/firebase/firebase-ios-sdk/tree/heartbeats-main) were cherry-picked into it. 
The end goal was to have a feature branch with the heartbeat work that was cleanly rebased onto master (rather than merged like in `heartbeats-main`). See clean comparison now: https://github.com/firebase/firebase-ios-sdk/compare/platform-logging-main
=> [Heartbeat Logging] Style branch and add two TODOs

Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.m, Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c, Crashlytics/Crashlytics/Handlers/FIRCLSMachException.h, Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m
=> Update MetricKit exception name and code name determination

.github/workflows/core-diagnostics.yml, .github/workflows/dynamiclinks.yml, .github/workflows/firebasepod.yml, .github/workflows/firestore.yml, .github/workflows/functions.yml
=> Move some crons earlier

Firestore/core/src/remote/grpc_connection.cc
Manually tested against Prod backend.
=> Change cloud resource prefix

SwiftDashboard.md
Reviewed some async/await APIs, removed ABTesting since it's not a public API.
Will improve text formatting when auditing the rest.
#no-changelog
=> Partial update to Swift dashboard

CocoapodsIntegrationTest/TestEnvironments/Cocoapods_multiprojects_frameworks/Podfile
=> Add missing pod to Podfile

FirebaseFunctions/Sources/FunctionsComponent.swift
=> Update Functions component system for interop

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> [Release] M112 Carthage Update

FirebaseStorage/Sources/FIRStorage.m
=> Deprecated GTMSessionFetcher macro

FirebaseCore/Sources/Public/FirebaseCore/FIRApp.h, FirebaseCore/Sources/Public/FirebaseCore/FIRConfiguration.h, FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h, SwiftDashboard.md
=> Update Core's docs to be Swift first.

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json, Package.swift
=> Analytics 8.14.0

Gemfile, Gemfile.lock
=> Update to CocoaPods 1.11.3

Firestore/Source/API/FIRFilter+Internal.h, Firestore/Source/API/FIRFilter.mm, Firestore/Source/API/FIRQuery.mm, Firestore/core/src/api/query_core.cc, Firestore/core/src/api/query_core.h, Firestore/core/src/bundle/bundle_serializer.cc, Firestore/core/src/core/array_contains_any_filter.cc, Firestore/core/src/core/array_contains_filter.cc, Firestore/core/src/core/field_filter.cc, Firestore/core/src/core/field_filter.h, Firestore/core/src/core/filter.h, Firestore/core/src/core/in_filter.cc, Firestore/core/src/core/key_field_filter.cc, Firestore/core/src/core/key_field_filter.h, Firestore/core/src/core/key_field_in_filter.cc, Firestore/core/src/core/key_field_not_in_filter.cc, Firestore/core/src/core/not_in_filter.cc, Firestore/core/src/core/operator.h, Firestore/core/src/core/query.cc, Firestore/core/src/core/query.h, Firestore/core/src/remote/serializer.cc, Firestore/core/src/remote/serializer.h, Firestore/core/test/unit/testutil/testutil.cc
#no-changelog
Add FIRFilter inside Soure/API, which is first change towards future support of composite filters and disjunctions.
=> Create FIRFilter in API folder

scripts/make_release_notes.py
"Update now" they say, "security update required".
=> make release notes script depend use python3

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage 8.14

FirebaseAppCheckInterop.podspec, FirebaseAuthInterop.podspec, FirebaseCoreExtension.podspec, FirebaseMessagingInterop.podspec, FirebaseStorage.podspec, FirebaseStorageObjC.podspec, FirebaseStorageSwift/Sources/Storage.swift, FirebaseStorageSwift/Sources/StorageComponent.swift, Package.swift
=> Update storage-v9 branch for CoreExtension

FirebaseAuth/Tests/Sample/README.md
=> Fix 404s and remove missing SwiftSample references

Firestore/core/src/core/key_field_not_in_filter.cc
=> Fix wrong type in key_field_not_in_filter.cc

FirebaseFirestore.podspec, Package.swift
Reverts firebase/firebase-ios-sdk#9486
=> Revert "Upgrade grpc and abseil for SPM and cocoapods"

FirebaseCore/Extension/FIRAppInternal.h, FirebaseCore/Extension/FIRHeartbeatLogger.h, FirebaseCore/Internal/Tests/Unit/HeartbeatStorageTests.swift, FirebaseCore/Sources/FIRApp.m, FirebaseCore/Sources/FIRHeartbeatLogger.m, FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h, FirebaseCore/Tests/Unit/FIRHeartbeatLoggerTest.m
I will open up PRs of the product SDK integration once this is merged.
#no-changelog
=> [Heartbeat Logging] Add heartbeat logger to `FIRApp` and manage `FIRHeartbeatLogger` instances

FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallations.h, FirebasePerformance/Sources/Public/FirebasePerformance/FIRHTTPMetric.h, FirebasePerformance/Sources/Public/FirebasePerformance/FIRPerformance.h, Firestore/Source/API/FIRFilter+Internal.h, Firestore/Source/Public/FirebaseFirestore/FIRFirestore.h, Firestore/Source/Public/FirebaseFirestore/FIRQuery.h, README.md, scripts/setup_check.sh, scripts/style.sh
Related to clang-format not managing brew versioning properly. See https://github.com/llvm/llvm-project/issues/49340
#no-changelog
=> [Infra] Bump clang-format to v14

FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallations.h, FirebasePerformance/Sources/Public/FirebasePerformance/FIRHTTPMetric.h, FirebasePerformance/Sources/Public/FirebasePerformance/FIRPerformance.h, Firestore/Source/API/FIRFilter+Internal.h, Firestore/Source/Public/FirebaseFirestore/FIRFirestore.h, Firestore/Source/Public/FirebaseFirestore/FIRQuery.h, README.md, scripts/setup_check.sh, scripts/style.sh
Will fix `check` failures for PRs into `v9b`.
#no-changelog
=> [Infra] Cherry-pick clang format bump (#9527) to `v9b`

Firestore/core/src/core/field_filter.cc
=> Fix hard_assert in field_filter.cc

.github/workflows/app_check.yml, .github/workflows/core.yml, .github/workflows/core_extension.yml, .github/workflows/core_internal.yml, FirebaseAppCheck.podspec, FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m, FirebaseAppCheck/Sources/Core/APIService/FIRAppCheckAPIService.h, FirebaseAppCheck/Sources/Core/APIService/FIRAppCheckAPIService.m, FirebaseAppCheck/Sources/DebugProvider/FIRAppCheckDebugProvider.m, FirebaseAppCheck/Sources/DeviceCheckProvider/FIRDeviceCheckProvider.m, FirebaseAppCheck/Tests/Integration/FIRDeviceCheckAPIServiceE2ETests.m, FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckAPIServiceTests.m, FirebaseCore.podspec, FirebaseCore/Extension/FIRAppInternal.h, FirebaseCore/Extension/FIRHeartbeatLogger.h, FirebaseCore/Internal/Sources/HeartbeatLogging/_ObjC_HeartbeatsPayload.swift, FirebaseCore/Tests/Unit/FIRHeartbeatLoggerTests.m, FirebaseCoreInternal.podspec, HeartbeatLoggingTestUtils/Sources/HeartbeatLoggingTestUtils.swift, Package.swift
=> [Heartbeat Logging] Migrate AppCheck from using `FIRHeartbeatInfo` to `FIRHeartbeatLogger`

FirebaseAppCheck/Sources/AppAttestProvider/Storage/FIRAppAttestKeyIDStorage.h, FirebaseAppCheck/Sources/Core/Storage/FIRAppCheckStorage.h, FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheck.h, FirebaseAuth/Sources/Auth/FIRAuthDispatcher.h, FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.h, FirebaseAuth/Tests/Sample/Sample/AppManager.m, FirebaseInAppMessaging/Sources/Runtime/FIRIAMActionURLFollower.m, FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallations.h, FirebaseMessaging/Sources/FIRMessagingRmqManager.h, Firestore/Example/Tests/API/FSTAPIHelpers.h, Firestore/core/src/util/filesystem.h
=> fix returns typo

.github/workflows/installations.yml, FirebaseInstallations.podspec, FirebaseInstallations/Source/Library/FIRInstallations.m, FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.h, FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m, FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.h, FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m, FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m, FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m, FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
=> [Heartbeat Logging] Migrate Installations from using `FIRHeartbeatInfo` to `FIRHeartbeatLogger`

Firestore/Source/Public/FirebaseFirestore/FIRCollectionReference.h, Firestore/Source/Public/FirebaseFirestore/FIRDocumentChange.h, Firestore/Source/Public/FirebaseFirestore/FIRDocumentReference.h, Firestore/Source/Public/FirebaseFirestore/FIRDocumentSnapshot.h, Firestore/Source/Public/FirebaseFirestore/FIRFieldValue.h, Firestore/Source/Public/FirebaseFirestore/FIRFirestore.h, Firestore/Source/Public/FirebaseFirestore/FIRFirestoreErrors.h, Firestore/Source/Public/FirebaseFirestore/FIRFirestoreSettings.h, Firestore/Source/Public/FirebaseFirestore/FIRListenerRegistration.h, Firestore/Source/Public/FirebaseFirestore/FIRLoadBundleTask.h, Firestore/Source/Public/FirebaseFirestore/FIRQuery.h, Firestore/Source/Public/FirebaseFirestore/FIRQuerySnapshot.h, Firestore/Source/Public/FirebaseFirestore/FIRSnapshotMetadata.h, Firestore/Source/Public/FirebaseFirestore/FIRTimestamp.h, Firestore/Source/Public/FirebaseFirestore/FIRTransaction.h, Firestore/Source/Public/FirebaseFirestore/FIRWriteBatch.h, SwiftDashboard.md
=> Update Firestore's public headers to use Swift class names.

.github/workflows/firestore.yml
=> [Cleanup] Remove outdated comment in `firestore.yml`

Crashlytics/UnitTests/FIRCLSOnDemandModelTests.m
=> Fixes flutter test failures

FirebaseAppCheck/Sources/AppAttestProvider/API/FIRAppAttestAttestationResponse.m, FirebaseAppCheck/Sources/Core/APIService/FIRAppCheckAPIService.m, FirebaseAppCheck/Sources/Core/APIService/FIRAppCheckToken+APIResponse.m, FirebaseAppCheck/Tests/Fixture/AppAttestAttestationResponseSuccess.json, FirebaseAppCheck/Tests/Fixture/DeviceCheckResponseMissingTimeToLive.json, FirebaseAppCheck/Tests/Fixture/FACTokenExchangeResponseSuccess.json, FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckAPIServiceTests.m
Context in b/228096351.
cc: @weixifan 
#no-changelog
=> [AppCheck, v9] Update endpoint and response parsing logic

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json
Analytics 8.15.0 podspec.json files
=> Analytics 8.15.0

FirebaseCore/Extension/FIRHeartbeatLogger.h, FirebaseMessaging/Sources/FIRMessaging.m, FirebaseMessaging/Sources/Token/FIRMessagingTokenDeleteOperation.h, FirebaseMessaging/Sources/Token/FIRMessagingTokenDeleteOperation.m, FirebaseMessaging/Sources/Token/FIRMessagingTokenFetchOperation.h, FirebaseMessaging/Sources/Token/FIRMessagingTokenFetchOperation.m, FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.h, FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.m, FirebaseMessaging/Sources/Token/FIRMessagingTokenOperation.h, FirebaseMessaging/Sources/Token/FIRMessagingTokenOperation.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingTestUtilities.m, FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenOperationsTest.m
=> [Heartbeat Logging] Migrate Messaging from using `FIRHeartbeatInfo` to `FIRHeartbeatLogger`

Package.swift
Analytics 8.15.0 for Swift Package Manager.
=> Analytics SPM 8.15.0

.github/workflows/prerelease.yml, .github/workflows/zip.yml, scripts/setup_quickstart_framework.sh
Fix zip workflow for new Storage quickstart directory structure
#no-changelog
=> Add legacy for storage in zip and prerelease workflows

Crashlytics/Crashlytics/Helpers/FIRCLSLogger.m, FirebaseABTesting/Sources/FIRExperimentController.m, FirebaseAppCheck/Sources/Core/FIRAppCheckLogger.m, FirebaseAppDistribution/Sources/FIRFADLogger.m, FirebaseAuth/Sources/Auth/FIRAuth.m, FirebaseCore/Sources/FIRLogger.m, FirebaseCore/Tests/Unit/FIRLoggerTest.m, FirebaseDatabase/Sources/Utilities/FUtilities.m, FirebaseDynamicLinks/Sources/Logging/FDLLogging.m, FirebaseInAppMessaging/Sources/DefaultUI/FIRCore+InAppMessagingDisplay.m, FirebaseInAppMessaging/Sources/FIRCore+InAppMessaging.m, FirebaseInstallations/Source/Library/FIRInstallationsLogger.m, FirebaseMessaging/Sources/FIRMessagingLogger.m, FirebasePerformance/Sources/FPRConsoleLogger.m, FirebaseStorage/Sources/FIRStorageLogger.m, Firestore/core/src/util/log_apple.mm
Reduce confusion about deprecated Firebase pod
=> Remove slashes from log messages

FirebaseCore/Sources/FIRApp.m, FirebaseCore/Tests/Unit/FIRAppTest.m
=> [Heartbeat Logging] Add logging within `FirebaseCore`

.github/workflows/performance-integration-tests.yml, FirebasePerformance/Tests/FIRPerfE2E/Podfile
=> [Perf] Add missing `FirebaseCoreInternal` pod to testing Podfile

.github/ISSUE_TEMPLATE/bug_report.md, .github/actions/testing_report_generation/action.yml, SharedTestUtilities/FIRSampleAppUtilities.m, scripts/check_firestore_core_api_absl.py, scripts/create_spec_repo/Sources/SpecRepoBuilder/main.swift, scripts/health_metrics/generate_code_coverage_report/README.md, scripts/health_metrics/pod_test_code_coverage_report.sh
=> Fix GitHub capitalization across repo

FirebaseInAppMessagingSwift.podspec
=> Restore beta for FIAM Swift podspec

FirebaseFunctions/Sources/FunctionsError.swift, FirebaseFunctions/Tests/ObjCIntegration/FIRIntegrationTests.m, FirebaseFunctions/Tests/ObjCIntegration/ObjCAPITests.m
=> Remove Objective-C Error APIs for Functions

.github/workflows/combine.yml
=> [skip ci] Speed up presubmits

FirebaseAuth/Tests/Sample/Podfile
=> [Infra] Fix Auth sample app when pod updating

.github/workflows/spectesting.yml
A revert of #9491
Fix #9313
#no-changelog
=> [Infra] Reenable `specstesting/specs_testing` workflow

FirebaseFunctions/Sources/FunctionsError.swift, FirebaseFunctions/Tests/Unit/FunctionsAPITests.swift, FirebaseStorage/Sources/StorageError.swift, FirebaseStorage/Tests/Unit/StorageAPITests.swift
=> Restore StorageErrorDomain and error tests

Carthage.md, ReleaseTooling/Template/README.md
=> Update binary install instructions for disabling AdId

FirebaseDynamicLinks/CHANGELOG.md, FirebaseDynamicLinks/Sources/FIRDynamicLinks.m
Crash Fix: Async/await violation for Dynamic Links
Related issue : https://github.com/firebase/firebase-ios-sdk/issues/9612
=> Fdl async await crash fix

FirebaseAppCheck/CHANGELOG.md, FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckDebugProvider.h
=> [AppCheck] Improve documentation for retrieving a debug token

SwiftDashboard.md
These should all be checks after #9594
=> Update Swift Doc Scrub status

SymbolCollisionTest/Podfile
=> Update Symbol Collision tests for new 9.x pods

SwiftDashboard.md
Swift Dashboard Updates for planned state of the 9.0.0 release.
=> Swift Dashboard Updates - 9.0.0

.github/workflows/functions.yml, .github/workflows/storage.yml, .github/workflows/zip.yml, Crashlytics/Protogen/nanopb/crashlytics.nanopb.c, FirebaseCore/Extension/FIRAppInternal.h, FirebaseDatabase/Sources/Api/FIRDatabase.m, FirebaseDynamicLinks/Sources/FIRDynamicLinks.m, scripts/check_whitespace.sh
=> Address v9, resolved, and obsolete TODO's

scripts/check_imports.swift
=> Review and update check imports script

FirebaseCore.podspec, Gemfile
=> [FirebaseCore] Update headers in `FirebaseCore.podspec`

FirebaseAnalytics.podspec.json, FirebaseAnalyticsOnDeviceConversion.podspec.json, FirebaseAnalyticsOnDeviceConversionWrapper/dummy.m, FirebaseAnalyticsOnDeviceConversionWrapper/include/dummy.h, GoogleAppMeasurement.podspec.json, GoogleAppMeasurementOnDeviceConversion.podspec.json, Package.swift, SwiftPMTests/analytics-import-test/analytics-import.swift, SwiftPMTests/analytics-import-test/firebase-import.swift
Analytics 9.0.0 release for CocoaPods and Swift Package Manager.
=> Analytics 9.0.0

FirebaseFunctions/Sources/Functions.swift, FirebaseStorage/Sources/Storage.swift
=> Refactor to remove `__` APIs in Swift

FirebaseAppDistribution.podspec
=> [Infra] Remove unused comment from `FirebaseAppDistribution.podspec`

Package.swift
=> Update SPM deps to latest for 9.0.0

ReleaseTooling/Template/README.md
=> [skip ci] Update zip Readme for current platform support

SwiftDashboard.md
=> Green checks

FirebaseAppCheck.podspec, FirebaseCrashlytics.podspec, FirebaseInstallations.podspec, FirebaseMLModelDownloader.podspec, Package.swift, ReleaseTooling/Template/README.md
#no-changelog 
Will merge instead of squash so future merges from release-9.0 diff correctly.
=> Sync Release 9.0 branch to master

FirebaseFunctions/Sources/Functions.swift, FirebaseFunctions/Sources/FunctionsError.swift, FirebaseFunctions/Sources/HTTPSCallable.swift, FirebaseStorage/Sources/AsyncAwait.swift, FirebaseStorage/Sources/Storage.swift, FirebaseStorage/Sources/StorageDownloadTask.swift, FirebaseStorage/Sources/StorageError.swift, FirebaseStorage/Sources/StorageListResult.swift, FirebaseStorage/Sources/StorageObservableTask.swift, FirebaseStorage/Sources/StorageReference.swift, FirebaseStorage/Sources/StorageTask.swift, FirebaseStorage/Sources/StorageTaskSnapshot.swift, FirebaseStorage/Sources/StorageUploadTask.swift
See Paul's comments in cl/443496184 for background.
#no-changelog
=> Update Storage and Functions header comments to Swift markdown

FirebaseStorage/Sources/StorageUploadTask.swift
=> Fix an issue with StorageUploadTask.resume accidentally using Download.

FirebaseStorage/Sources/StorageUploadTask.swift
Cherry-pick #9717 to release-9.0 branch
=> Cherry-pick 9717 to release-9.0

ReleaseTooling/Template/README.md
=> [v9] Improve clarity of zip integration instructions

Crashlytics/run, FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h, FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m, FirebaseAuth/Tests/Unit/FIRUserTests.m, FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.h, FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FDLURLComponents.h, Firestore/Protos/nanopb_cpp_generator.py, Firestore/core/src/local/leveldb_key.h, Firestore/core/src/remote/remote_store.cc, Firestore/core/src/util/filesystem.h, Firestore/core/test/unit/local/mutation_queue_test.h, Firestore/core/test/unit/remote/grpc_stream_tester.h
Fix "the the" typos and library misspelling
#no-changelog
=> Fix "the the" typos

Carthage.md, ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> Carthage 9.0.0 + instruction update

scripts/setup_quickstart.sh, scripts/setup_quickstart_framework.sh
=> v9 quickstarts have merged to master

.github/workflows/archiving.yml, scripts/test_archiving.sh
Fix nightly archiving after move to macos12 in #9745
=> Archive workflow now needs xcpretty

FirebaseAuth.podspec, FirebaseFunctions.podspec, FirebaseStorageInternal.podspec
- Addresses https://github.com/firebase/firebase-ios-sdk/pull/9774#pullrequestreview-965220567
- `Package.swift` in `master`: https://github.com/firebase/firebase-ios-sdk/blob/master/Package.swift#L165-L169
#no-changelog
=> [v9.1] Partial revert "[v9.1] Bump GTMSessionFetcher dep to >1.7.2 (#9774)"

FirebaseAnalytics.podspec.json, FirebaseCoreDiagnostics.podspec, FirebaseCrashlytics.podspec, FirebaseFirestore.podspec, FirebaseInAppMessaging.podspec, FirebaseMessaging.podspec, FirebaseMessaging/Apps/Sample/Podfile, FirebasePerformance.podspec, GoogleAppMeasurement.podspec.json, Package.swift
Update to nanopb 0.3.9.9 (semantic 2.30909.0) 
Fix #9587
=> Update to nanopb 2.30909.0

.github/workflows/generate_issues.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml
Address in_progress workflows in #9795
=> Move some jobs earlier to make more likely to finish

FirebaseAnalytics.podspec.json, GoogleAppMeasurement.podspec.json, Package.swift
=> Analytics 9.1.0

Crashlytics/Crashlytics/Controllers/FIRCLSExistingReportManager.m, Crashlytics/Crashlytics/FIRCrashlytics.m, Crashlytics/Crashlytics/Models/FIRCLSOnDemandModel.m, Crashlytics/Crashlytics/Private/FIRCLSOnDemandModel_Private.h, Crashlytics/UnitTests/FIRCLSOnDemandModelTests.m, Crashlytics/UnitTests/Mocks/FIRCLSMockFileManager.m, Crashlytics/UnitTests/Mocks/FIRCLSMockOnDemandModel.h, Crashlytics/UnitTests/Mocks/FIRCLSMockOnDemandModel.m, Crashlytics/UnitTests/Mocks/FIRCLSMockReportUploader.m
=> Fix Catalyst Flaky Test

Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.m, Crashlytics/UnitTests/FIRCLSReportUploaderTests.m, Crashlytics/UnitTests/Mocks/FIRMockGDTCoreTransport.h, Crashlytics/UnitTests/Mocks/FIRMockGDTCoreTransport.m
Added forgotten semaphore_signal calls at early return
=> Fix possible deadlock in urgent state of report uploader

ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json, ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json, ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json, ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json, ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json, ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json, ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json, ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json, ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json, ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json, ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json, ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json, ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json, ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json, ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
=> [Release] M116 Carthage Update
