firebase/firebase-ios-sdk

FirebaseMessaging/CHANGELOG.md
FirebaseMessaging/Sources/FIRMMessageCode.h
FirebaseMessaging/Sources/FIRMessagingContextManagerService.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingContextManagerServiceTest.m

This fixes b/156310608 also as the UILocalNotification doesn't properly process "%", where it escape it in notification title and body.
Also UILocalNotification is deprecated, so use them for iOS 10 above.

use UNNotificationRequest to schedule local notification for iOS 10 and above

---

FirebaseAuth/Sources/Auth/FIRAuth.m
FirebaseAuth/Sources/AuthProvider/OAuth/FIROAuthProvider.m
FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m
FirebaseAuth/Tests/Sample/ApiTests/FIRAuthApiTestsBase.h
FirebaseAuth/Tests/Sample/E2eTests/FIRAuthE2eTestsBase.h
FirebaseAuth/Tests/Sample/Sample/AppManager.m
FirebaseAuth/Tests/Sample/Sample/ApplicationDelegate.m
FirebaseAuth/Tests/Sample/Sample/FacebookAuthProvider.m
FirebaseAuth/Tests/Sample/Sample/GoogleAuthProvider.m
FirebaseAuth/Tests/Sample/Sample/MainViewController+App.m
FirebaseAuth/Tests/Sample/Sample/MainViewController+Auth.h
FirebaseAuth/Tests/Sample/Sample/MainViewController+Email.h
FirebaseAuth/Tests/Sample/Sample/MainViewController+Email.m
FirebaseAuth/Tests/Sample/Sample/MainViewController+GameCenter.h
FirebaseAuth/Tests/Sample/Sample/MainViewController+GameCenter.m
FirebaseAuth/Tests/Sample/Sample/MainViewController+Google.m
FirebaseAuth/Tests/Sample/Sample/MainViewController+MultiFactor.m
FirebaseAuth/Tests/Sample/Sample/MainViewController+OAuth.m
FirebaseAuth/Tests/Sample/Sample/MainViewController+OOB.h
FirebaseAuth/Tests/Sample/Sample/MainViewController.m
FirebaseAuth/Tests/Sample/Sample/SettingsViewController.m
FirebaseAuth/Tests/Sample/Sample/UserInfoViewController.m
FirebaseAuth/Tests/Sample/Sample/UserTableViewCell.m
FirebaseAuth/Tests/Unit/FIRAuthTests.m
FirebaseAuth/Tests/Unit/FIROAuthProviderTests.m
FirebaseAuth/Tests/Unit/FIRPhoneAuthProviderTests.m
scripts/check_no_module_imports.sh

Simple name for public headers in the library
Module imports for public headers from dependencies like:
```
#if SWIFT_PACKAGE
@import FirebaseCore;
#else
#import <FirebaseCore/FIRApp.h>
#import <FirebaseCore/FIROptions.h>
#endif
```
Also restore Sample to master until we're ready to get it working with SPM

Standardize headers for SPM and Auth

---

Firestore/core/include/firebase/firestore/firestore_errors.h

This is for consistency with other Firebase C++ SDKs.

Add `Error::kErrorNone` as a synonym for `kErrorOk`

---

Crashlytics/Crashlytics/Helpers/FIRCLSFile.h

Crashlytics add missing headers for builds

---

FirebaseCore/Tests/Unit/Swift/FirebaseConfigurationTests.swift
FirebaseCore/Tests/Unit/Swift/FirebaseOptionsTests.swift

Adding swift unit tests for [FirebaseConfiguration](https://firebase.google.com/docs/reference/swift/firebasecore/api/reference/Classes/FirebaseConfiguration) & [FirebaseOptions](https://firebase.google.com/docs/reference/swift/firebasecore/api/reference/Classes/FirebaseOptions)
**Fun facts** 🥳 
`FirebaseConfigurationTests` have ~80% coverage
`FirebaseOptionsTests` have ~60% coverage
#no-changelog

Added Core Config & Options swift tests

---

GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORStorageEventSelector.m
GoogleDataTransport/GDTCORLibrary/Private/GDTCORFlatFileStorage.h
GoogleDataTransport/GDTCORLibrary/Public/GDTCORStorageEventSelector.h
GoogleDataTransport/GDTCORTests/Common/Categories/GDTCORFlatFileStorage+Testing.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m

#no-changelog because more changes are incoming.
Essentially, this change is to allow the storing of events to the filesystem in 3 ways:
- A direct write of a GDTCOREvent to the root data path, using the eventID as the filename. This will allow fast finding of events by target.
- A symbolic link to the direct write that allows fast finding of events via the mappingID.
- A symbolic link to the direct write that allow fast finding of events via the qosTier.

Implement helpers for storing and finding events

---

FirebaseRemoteConfig/Sources/RCNConfigConstants.h
FirebaseRemoteConfig/Sources/RCNConfigSettings.m
FirebaseRemoteConfig/Sources/RCNDevice.h
FirebaseRemoteConfig/Sources/RCNDevice.m

Currently we are sending an "internal" SDK version that is never updated. Using `FIRRemoteConfigPodVersion` to reflect actual SDK version usage
Tracked in internal bug 157147675
This change only affects internal logging #no-changelog

Send pod SDK version instead of hardcoded value in RC fetch request

---

FirebaseRemoteConfig/CHANGELOG.md
FirebaseRemoteConfig/Sources/Public/FIRRemoteConfig.h

This PR splits #5710 between the Swift usability and the typedef deprecation since the typedef deprecation will require an API review process.
Stop using typedefs for completion blocks in public APIs so that Xcode is more usable in Swift:
There is no change/impact on Objective C usability.

Better Swift API completion usability

---

GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorageIterator.m
GoogleDataTransport/GDTCORLibrary/Private/GDTCORFlatFileStorageIterator.h
GoogleDataTransport/GDTCORLibrary/Public/GDTCORStorageProtocol.h
GoogleDataTransport/GDTCORTests/Common/Categories/GDTCORFlatFileStorage+Testing.m
GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORStorageFake.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m

#no-changelog because more changes are incoming.
This change expands the storage protocol API so that prioritizers don't need to exist. An uploader can complete the following by itself:
- Find the storage instance for the target it cares about
- Query storage if there are events
- Get an event iterator and process the events to construct a request
- Store uploader state using the library data API

Expand the storage protocol and provide an event iterator

---

FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m

In InAppMessaging, card messages require images.
However, in some situation, This SDK fails to parse API response from Firebase then imageURL set to `nil` even displaying type is Card.
If you upload images with non-ascii file names from Firebase console, This SDK can't parse image URLs. (`NSURL` fails to initialize from strings with non-ascii characters).
https://github.com/firebase/firebase-ios-sdk/blob/dbe900774974e36332decb75d1ba842e7faa2130/FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m#L295
I hit this situation.  So I'd like to add an assertion on a development environment.
Added assertion when hit such a situation to notice the problems.

Add assertion when in app message is in invalid state

---

FirebaseAppDistribution/Sources/FIRAppDistribution.m
FirebaseAppDistribution/Sources/FIRAppDistributionAuthPersistence.m

1. Added a Getter for isTesterSignedIn and lazy initialized the auth state in the get method
2. Also added auth state lazy initialization logic in signInTester
3. Also added a log message for when we don't find the auth state in the keychain

Lazy initialize auth state

---

FirebaseAppDistribution/Sources/FIRFADLogger.m

Add NSLog to go along with FIRLogBasic so we are logging even running outside of the simulator to help debug customer issues during the EAP

Add NSLogv to help debug end user issues

---

GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORStorageEventSelector.m
GoogleDataTransport/GDTCORLibrary/Private/GDTCORFlatFileStorage.h
GoogleDataTransport/GDTCORLibrary/Public/GDTCORStorageEventSelector.h
GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m

No more symlinks to try and speed searching. Just get a directory's contents and check the filename, which will contain metadata about the event.
#no-changelog because it's parter of a larger change

Refactor event saving and searching

---

FirebaseStorage/CHANGELOG.md
FirebaseStorage/Sources/FIRStorageListResult.m
FirebaseStorage/Tests/Integration/FIRStorageIntegrationTests.m

Storage crashes with an assert because "hasPrefix" returns false if the prefix is empty. I decided to just remove the assert since it is not part of Android: https://github.com/firebase/firebase-android-sdk/blob/29a1573ac1c6b7765aa6ed95ceafc95ec3b670f0/firebase-storage/src/main/java/com/google/firebase/storage/ListResult.java#L43

Allow list() at root

---

Firestore/core/src/util/executor_std.cc

This fixes an ASAN issue discovered internally on Linux (b/158746726).

Use immediate rather than min time to avoid overflow

---

Crashlytics/CHANGELOG.md
FirebaseCrashlytics.podspec

This linker flag creates a section in the binary containing the Info.plist.
- Swift Package Manager can't set `OTHER_LD_FLAGS` as of now
- This may be unnecessary
Took a look at the old codebase - I believe it was a mistake to add this to the cocoapod in the first place. The use case for this rule is creating a section in the binary when no Info.plist is present, but there will always be an Info.plist in the bundle for iOS / macOS / tvOS apps.
This rule is used for upload-symbols so that it can read its own version. Since upload-symbols is binary only, there's no Info.plist, so this linker rule is necessary.
We must have just accidentally applied the linker rule to the SDK too.

Remove Crashlytics OTHER_LD_FLAGS for Swift Package Manager

---

GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m
GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h
GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m

Current GDT implementation returns "iPhone". With this change, the device model identified would be iPhoneA,B (Eg. iPhone 8,1).
can …

Update the device model identified by GDTCCTLibrary to be more detailed and in parity with Clearcut.

---

GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m
GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
GoogleDataTransport/GDTCORLibrary/Private/GDTCORFlatFileStorage.h
GoogleDataTransport/GDTCORLibrary/Public/GDTCOREvent.h
GoogleDataTransport/GDTCORLibrary/Public/GDTCORStorageProtocol.h
GoogleDataTransport/GDTCORTests/Common/Fakes/GDTCORStorageFake.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m

The upload coordinator will signal an expiration check whenever the app foregrounds.
#no-changelog because this is a feature branch

Implement events and batch expirations

---

.github/workflows/auth.yml
scripts/build_non_firebase_sdks.sh
scripts/setup_quickstart_framework.sh

This will can be used to generate a customized set of non Firebase frameworks to test some Quickstarts. E.g. Auth Quickstart reqeust FBSDKLogin frameworks.

Add scripts to generate non firebase sdks for zip testing.

---

GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m

Having the device model as a state variable gets the value of deviceModel to be set to "Unknown" everytime called, but the actual model extraction block will be called just once. So the first time, deviceModel will extract the right value and subsequent time will just return "Unknown".
This fix to make it a static variable to not lose the value extracted.
* If you fixed a bug or added a …

Make the deviceModel to be a static variable to avoid overwrites.

---

Functions/Example/IntegrationTests/FIRIntegrationTests.m
Functions/Example/TestUtils/FUNFakeInstanceID.m
Functions/Example/Tests/FIRFunctionsTests.m
Functions/Example/Tests/FUNContextProviderTests.m
Functions/Example/Tests/FUNSerializerTests.m
Functions/FirebaseFunctions/FIRFunctions+Internal.h
Functions/FirebaseFunctions/FIRFunctions.m
Functions/FirebaseFunctions/FIRHTTPSCallable+Internal.h
Functions/FirebaseFunctions/FIRHTTPSCallable.m
Functions/FirebaseFunctions/FUNContext.m
Functions/FirebaseFunctions/FUNError.h
Functions/FirebaseFunctions/FUNError.m
Functions/FirebaseFunctions/FUNInstanceIDProxy.m
Functions/FirebaseFunctions/FUNSerializer.m
Functions/FirebaseFunctions/FUNUsageValidation.m
Package.swift
Sources/firebase-test/main.swift
scripts/change_headers.swift
scripts/check_imports.swift
scripts/check_no_module_imports.sh

- Run ./scripts/change_headers.swift to update all Functions library and unit tests to be repo-relative
- Turn on Swift Package Manager build and CI
#no-changelog - Will be part of a global M74 changelog

Functions: Repo-relative headers and SPM

---

SymbolCollisionTest/Podfile

The ML pods should be restored when #5746 is fixed.

Disable ML to workaround symbol collision test issues

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
Firestore/Example/Tests/SpecTests/FSTMockDatastore.h
Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
Firestore/core/src/core/firestore_client.cc
Firestore/core/src/core/firestore_client.h
Firestore/core/src/remote/datastore.cc
Firestore/core/src/remote/datastore.h
Firestore/core/src/remote/remote_store.cc
Firestore/core/src/remote/remote_store.h
Firestore/core/test/unit/remote/datastore_test.cc

This is a follow up to https://github.com/firebase/firebase-ios-sdk/pull/4985 and addresses an additional problem that I saw in the test app. If the SDK was already in the background and we were in a backoff phase, the SDK waited for the backoff to finish before reconnecting, which could take up to a minute. This PR plumbs the connectivity handler through to RemoteStore and resets the backoff when a connectivity change occurred.
cc @wu-hui  
Fixes https://github.com/firebase/firebase-ios-sdk/issues/5783

Reset backoff when connectivity status changes

---

FirebaseMessaging/CHANGELOG.md
FirebaseMessaging/Sources/FIRMessagingPubSub.m

Fix warning exposed by Xcode 12

---

Crashlytics/Crashlytics/Helpers/FIRCLSInternalLogging.c

Resolves #5903 
I had a more complicated change earlier, but settled on this. The file is never closed, so this will work, and should be better than using a queue or semaphore.

Crashlytics: Add dispatch_once for opening sdk log file

---

FirebaseCore/CHANGELOG.md
FirebaseCore/Sources/FIROptions.m
FirebaseCore/Tests/Unit/FIROptionsTest.m

Make [FIROptions defaultOptions] thread safe

---

Firestore/Example/Tests/Integration/FSTTransactionTests.mm

TSAN uncovered cases where we were reading values in the transaction
thread that were set on the main thread and were unprotected by lock. In
practice this is unlikely to cause an harm, but it's good to keep TSAN
clean for when there are real issues.

Fix TSAN violations in FSTTransactionTests

---

Firestore/Source/API/FIRFirestore.mm
Firestore/core/src/util/executor_std.cc
Firestore/core/test/unit/util/executor_test.cc

Under some circumstances, the Executor can be accessed by a user task that's running during shutdown. The specific case I observed was if a task that manipulated an idle timer happened to run during shutdown, it would cause a deadlock because the Executor was still holding its lock while trying to join the user threads.

Avoid deadlock during shutdown on Linux/Windows

---

GoogleDataTransport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h
Package.swift

The sources in GDTCCTLibrary weren't being built due to the error in Package.swift below.
TODO: explore ways to better consolidate nanopb imports
Next: Investigate options for testing SPM builds
#no-changelog

Fix GDTCCT SPM build

---

FirebaseABTesting/Tests/Unit/ABTConditionalUserPropertyControllerTest.m

It looks like there was one test failure left in #5890.
This PR fixes the overflow that was causing it.

Fix test overflow

---

FirebaseDynamicLinks/CHANGELOG.md
FirebaseDynamicLinks/Sources/FIRDLDefaultRetrievalProcessV2.m

Adding plist property"FirebaseDeepLinkPasteBoardRetrievalEnabled" to enable/disable fetching dynamic links from PasteBoard.
With iOS 14, when ever the PasteBoard contents are accessed, a pop up will be displayed. So for FDL clients who doesn't need the deeplinking based on PasteBoard contained dynamic link, can use this property to disable PasteBoard access there by not having a PastBoard access system popup.

Adding plist property 'FirebaseDeepLinkPasteboardRetrievalEnabled'

---

Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
Firestore/Example/Tests/Integration/API/FIRListenerRegistrationTests.mm
Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
Firestore/Example/Tests/Util/XCTestCase+Await.h
Firestore/Example/Tests/Util/XCTestCase+Await.mm
Firestore/core/src/api/query_core.cc
Firestore/core/src/core/event_listener.h

This fixes a test flake observed very rarely in internal testing, where the callback starts processing, checks to see if it's muted, sees that it's not, and proceeds; meanwhile the test calls remove, and deletes state to which the listener was referring and by the time the callback happens in user code the listener callback now refers to the deleted state.

Have ListenerRegistration::Remove block until callbacks are complete

---

FirebaseAuth/Tests/Sample/Sample/MainViewController+Internal.h
FirebaseAuth/Tests/Sample/Sample/MainViewController+OAuth.m

Update the sample app to generate a random nonce for the Sign in with Apple flow, to minimize developer setup needed to test Sign in with Apple in the sample app.
Nonce generation same as sample code in https://firebase.google.com/docs/auth/ios/apple.

Update the sample app to use a random nonce in the Sign in with Apple flow

---

ROADMAP.md

I followed the link in `ROADMAP.md` and accidentally opened a regular issue without a template in https://github.com/firebase/firebase-ios-sdk/issues/6007. Changing the link should prevent this from happening in the future.
If you believe this link might change often in the future, an alternative would be https://github.com/firebase/firebase-ios-sdk/issues/new/choose.

Edit Feature Request link to link to the template

---

GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m

Fixes the following issue. It it possible that a batch expiration time is shorter than an event expiration time. With the old implementation in this case when the batch expires it will lead to removing all the events in it disregarding the event expiration time. 
The proposed fix:
- check batches for expiration first
- remove expired batches and move events from them back to the main location (unconditionally) 
- check and remove expired events from the main location (expired events from expired batches will also be there)

GDTCORFlatFileStorage: keep not expired events when expired batch removed

---

FirebaseABTesting.podspec
FirebaseABTesting/Sources/ABTConditionalUserPropertyController.m
FirebaseABTesting/Sources/FIRExperimentController.m
FirebaseABTesting/Sources/FIRLifecycleEvents.m
FirebaseABTesting/Tests/Unit/ABTConditionalUserPropertyControllerTest.m
FirebaseABTesting/Tests/Unit/FIRExperimentControllerTest.m
FirebaseABTesting/Tests/Unit/Utilities/ABTTestUtilities.m
FirebaseInAppMessaging.podspec
FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m
FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
FirebaseInAppMessaging/Tests/Unit/FIRIAMDisplayExecutorTests.m
FirebaseRemoteConfig.podspec
FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
FirebaseRemoteConfig/Sources/RCNConfigExperiment.m
FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
Package.swift
Tests/firebase-test/main.swift
scripts/change_headers.swift
scripts/check_imports.swift

Run ./scripts/change_headers.swift to update all ABT source to be repo-relative
Turn on Swift Package Manager build and CI
#no-changelog - Will be updated in M76 release process

ABTesting - Repo-relative imports and SwiftPM

---

FirebaseABTesting/Tests/Unit/Utilities/ABTTestUtilities.m
Package.swift

Thanks to https://forums.swift.org/t/finding-swift-package-manager-resources/38058/6 handle resources for SPM unit tests
#no-changelog

Turn on ABT unit tests with SPM

---

FirebaseRemoteConfig/Sources/FIRConfigValue.m
FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
FirebaseRemoteConfig/Sources/Private/FIRRemoteConfig_Private.h
FirebaseRemoteConfig/Sources/Private/RCNConfigFetch.h
FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
FirebaseRemoteConfig/Sources/RCNConfigContent.m
FirebaseRemoteConfig/Sources/RCNConfigValue_Internal.h
FirebaseRemoteConfig/Sources/RCNConstants3P.m
FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.m
FirebaseRemoteConfig/Tests/FakeUtils/Bridging-Header.h
FirebaseRemoteConfig/Tests/FakeUtils/FetchMocks.m
FirebaseRemoteConfig/Tests/Unit/RCNConfigAnalyticsTest.m
FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m
FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
FirebaseRemoteConfig/Tests/Unit/RCNConfigSettingsTest.m
FirebaseRemoteConfig/Tests/Unit/RCNConfigTest.m
FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m
FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfig+FIRAppTest.m
FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
FirebaseRemoteConfig/Tests/Unit/RCNThrottlingTests.m
Package.swift
Tests/firebase-test/main.swift
scripts/change_headers.swift
scripts/check_imports.swift

- Run ./scripts/change_headers.swift to update all RC source to be repo-relative
- Turn on Swift Package Manager build and CI
- Update three tests that require resources to use SPM bundle on ifdef
#no-changelog - Will be updated in M76 release process

RC: Repo-relative imports and SwiftPM

---

.github/workflows/performance-integration-tests.yml
.github/workflows/performance.yml

Add yml files for triggering Firebase Performance related tests on `private` repository `perf` branch.
Firebase Performance is currently on private repository only, and `private` repository `master` branch is in sync with `public` repository `master` branch. Any changes to `master` branch needs to happen on `public` repository only.
On private repository, currently Firebase Performance is working on a branch called `perf`, we have scheduled cron job for running tests to validate the most recent changes. 
However, `on.schedule` will run on `master` branch only: See [reference to on.schedule](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule).
In order to trigger jobs on `perf` branch, we need to add yml files to master branch, and enable its …

Enable cron job schedule for Firebase Performance tests on private repository

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
Firestore/Source/API/FIRFirestore.mm

`FIRFirestore.mm` was updated in #5920 to use a non-libdispatch executor if `HAVE_LIBDISPATCH` is false; however, the `config.h` header file that defines `HAVE_LIBDISPATCH` was neither directly nor indirectly included, causing the `#if HAVE_LIBDISPATCH` statement to unconditionally evaluate to false. The effect of this was that callbacks from Firestore in iOS were changed to run on a non-main thread and should have been run on the main thread.

Add #include for config.h to get the value for HAVE_LIBDISPATCH.

---

.travis.yml
GoogleUtilities.podspec
GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h
GoogleUtilities/CHANGELOG.md

Fix #6047 
Repo-relative imports don't work from .h files that are imported from other pods (even though it works in development pods.)

Fix import regression when mixing 6.7.0 with earlier Firebase versions

---

SymbolCollisionTest/Podfile

Prevent future issues like 
https://stackoverflow.com/questions/62885369/using-googlemlkit-0-61-0-thru-cocoapods-is-downgrading-firebase-libs-to-6-20-0/62897677
Make sure that the latest Firebase and GoogleMLKit install and build together.
#no-changelog

Add MLKit to SymbolCollision test

---

FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/Utilities/FIRAuthURLPresenter.m

Probably fixes #5979. Without a repro, who knows.
Fixes an issue where if an attempt to present a web URL via SFSafariViewController happened while there was already a URL being presented the error handler callback would be invoked on the wrong thread.
Also added some copies when moving blocks around.

Fix multithreaded _completion access

---

Firestore/CHANGELOG.md

The only change since 6.28.0 is #6024 since #6041 was cherry-picked as #6042.

Update CHANGELOG for Firestore v1.16.3

---

.github/workflows/abtesting.yml
.github/workflows/auth.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/inappmessaging.yml
.github/workflows/installations.yml
.github/workflows/messaging.yml
.github/workflows/remoteconfig.yml
.github/workflows/storage.yml
.github/workflows/zip.yml

Remove all zip testings from sdk workflows since these testings are compacted in zip workflows.
e.g. https://github.com/firebase/firebase-ios-sdk/actions/runs/175398687

Remove zip testings from sdk workflows

---

FirebaseAppDistribution/Sources/FIRAppDistributionAppDelegateInterceptor.m
FirebaseAppDistribution/Sources/FIRFADLogger.m
FirebaseAppDistribution/Sources/Private/FIRFADApiService+Private.h

* Add support for dynamic url schemes in the format appdistribution-<app id without colons>
* Fix crash when launching an app directly via a URL scheme
* Fix a crash on iOS 10 simulator caused by calling NSLogv twice
* Remove uses of NSLog
* Fix warnings

Add support for dynamic url schemes and fix two crashes

---

GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
GoogleDataTransport/GDTCCTTests/Unit/GDTCCTNanopbHelpersTest.m
GoogleDataTransport/GDTCCTTests/Unit/Helpers/GDTCCTEventGenerator.m
GoogleDataTransport/GDTCORLibrary/GDTCORClock.m
GoogleDataTransport/GDTCORLibrary/Public/GDTCORClock.h
GoogleDataTransport/GDTCORTests/Unit/GDTCORClockTest.m
GoogleDataTransport/GDTCORTests/Unit/GDTCOREventTest.m

Fixes b/161747889
- `GDTCORClock.uptime` actual time units aligned with method names
- `GDTCCTNanopbHelpers` - assign actual milliseconds to `..._uptime_ms` proto fields
- tests

GDT: fix time units for the request and events uptime

---

FirebaseAppDistribution/Sources/FIRAppDistribution.m
FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
FirebaseAppDistribution/Sources/Private/FIRAppDistribution+Private.h
FirebaseAppDistribution/Sources/Private/FIRAppDistributionUIService.h
FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m

* Mapping sign in flow errors to app distribution errors. 
* Also renaming AppDelegateInterceptor to FIRAppDistributionUIService

Error code mapping and DelegateInterceptor refactoring

---

FirebaseABTesting/Sources/Private/FirebaseABTestingInternal.h
FirebaseInAppMessaging.podspec
FirebaseRemoteConfig.podspec
FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
FirebaseRemoteConfig/Sources/RCNConfigExperiment.m
FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m

I previously only did a partial transition of repo-relative FirebaseABTesting imports, but didn't notice because the failure don't show up until running `pod spec lint`.
This PR finishes the transition.
Running tests locally because of broken GHA today.

Fix internal ABT imports

---

Firestore/core/test/unit/util/ordered_code_test.cc

Exception is thrown even in Release config. There was nothing catching the expected thrown exception. 
This was causing the "firestore_util_test" to fail, specifically "OrderedCodeInvalidEncodingsTest.NonCanonical".
Catching the expected exception now.

fix ordered code unit test for Release build

---

FirebaseAppDistribution/Sources/FIRAppDistribution.m
FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
FirebaseAppDistribution/Sources/Private/FIRAppDistributionUIService.h
FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m

https://github.com/firebase/firebase-ios-sdk/pull/6099 
* Making sure we return granular errors during sign in persistence. 
* Also fixing some naming and comment issues

Feedback from PR#6099 

---

.github/workflows/abtesting.yml
.github/workflows/auth.yml
.github/workflows/crashlytics.yml
.github/workflows/firestore.yml
.github/workflows/inappmessaging.yml
.github/workflows/installations.yml
.github/workflows/messaging.yml
.github/workflows/performance.yml
.github/workflows/remoteconfig.yml
.github/workflows/storage.yml

This is to reset the time of testing since zip testing are now in the zip workflow and will be run after zip built.

Update testing time.

---

ZipBuilder/Template/README.md

To ease users who google the error message encountered when installing Firebase-SDK-iOS manually and do not have frameworks automatically linking added the precise error string to tie their error to the solution presented. …

Added the actual error string that is intermittently encountered during manual install of Firebase SDK iOS

---

FirebaseAppDistribution.podspec
FirebaseAppDistribution/Sources/FIRAppDistribution.m
FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
FirebaseAppDistribution/Tests/Unit/FIRFADApiServiceTests.m

* Remove TODO
* dispatch_async consistently within methods
* Add in OCMVerify calls to make sure that mocks are called or not called
#no-changelog This is en encapsulation of a bunch of code review feedback from https://github.com/firebase/firebase-ios-sdk/pull/6126

Respond to code review feedback

---

FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m

Swizzling tests recently start failing after xcode version update. It reported the subclass mock of NotificationCenter was recreated by KVO. Mock singleton method the same way as it mock other class such as FIRMessaging, proxy class seems resolve the issue.

fix messaging breakage

---

GoogleUtilities/Tests/Unit/Swizzler/GULAppDelegateSwizzlerTest.m

Fixes #6140
#no-changelog for tests fixes.

GULAppDelegateSwizzlerTest: use OCMClassMock for application to avoid mock conflicts with KVO

---

FirebaseAppDistribution/Sources/FIRAppDistribution.m
FirebaseAppDistribution/Sources/FIRAppDistributionUIService.h
FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m

* Initializing UIWindow using initWithWindowScene for ios 13 
* Also making sure we only reset window in the App delegate if a registration flow is in progress.
#no-changelog this is being merged into another branch

Initializing UIWindow using initWithWindowScene for ios 13 and removing UI code from main FIRAppDistribution.m

---

FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m

This fixes an issue where displaying the UI window, resetting the UI state and then displaying the window again causes an error.
#no-changelog

Unset window.rootViewController when resetting UI

---

Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
Crashlytics/ProtoSupport/proto_generator.py
Crashlytics/Protogen/nanopb/crashlytics.nanopb.h
FirebaseInAppMessaging/Analytics/Protogen/nanopb/fiam.nanopb.h
FirebaseInAppMessaging/ProtoSupport/nanopb_build_protos.py
FirebaseInAppMessaging/Sources/Analytics/Protogen/nanopb/fiam.nanopb.h
GoogleDataTransport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h
GoogleDataTransport/ProtoSupport/proto_generator.py
Package.swift
scripts/check_imports.swift

Reverting since it breaks Firestore build.
Will explore making Firestore's usage of nanopb consistent with rest of Firebase by using qualified nanopb imports instead of vice versa.
#no-changelog

Revert "Remove #if SWIFT_PACKAGE checks for nanopb (#6163)"

---

Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
Crashlytics/Protogen/nanopb/crashlytics.nanopb.h
GoogleDataTransport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h
Package.swift

This is the right way to do #6162. Nothing about the CocoaPods implementation is changed and no `#if SWIFT_PACKAGE` tests are needed.
I updated the nanopb SPM implementation so that all the existing Firebase nanopb imports would be supported.
In addition to Crashlytics and GDT, Firestore is validate with this change in #6072
See https://github.com/paulb777/nanopb/tree/spm2

Import nanopb without touching CocoaPods imports

---

FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m

When running on an iOS 13 device, but not using scenes, fallback to initWithFrame.
#no-changelog - the App Distribution SDK is not yet released

Add fallback for iOS 13 when not using scenes

---

.github/workflows/spm.yml

The SPM workflow takes over 45 minute with Firestore.
This PR changes it to only test iOS on PRs and leave the other platforms for the cron job.

Speedup SPM presubmit

---

Package.swift

It looks like SPM doesn't clone all of a repo's commits. See https://github.com/firebase/firebase-ios-sdk/runs/937613345
This PR resolves the failure and restores CI.
#no-changelog

Resolve spm CI git error

---

FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m
FirebaseInstallations/Source/Tests/Utils/FIRTestKeychain.m
GoogleUtilities/Tests/Unit/Utils/GULTestKeychain.m

The CocoaPods 1.10 beta exposed this issue. I'm not sure why this didn't fail with 1.9, but it's definitely a test issue.
#no-changelog

Add missing <TargetConditionals.h> before TARGET_OS_OSX test

---

scripts/check_lint.py

cpplint currently fails opaquely (just returning exit code 1) if run under python3. Force this to run under python 2 while we figure out why.
#no-changelog

Temporarily run cpplint under python2

---

Firebase.podspec
FirebaseABTesting.podspec
FirebaseAppDistribution.podspec
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseCoreDiagnostics.podspec
FirebaseCrashlytics.podspec
FirebaseDatabase.podspec
FirebaseDynamicLinks.podspec
FirebaseFirestore.podspec
FirebaseFunctions.podspec
FirebaseInAppMessaging.podspec
FirebaseInstallations.podspec
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
FirebaseRemoteConfig.podspec
FirebaseStorage.podspec
GoogleDataTransport.podspec

Restructuring the public headers looks to be  safe and non-impactful, but updating the required dependencies in an abundance of caution to minimize the test and support footprint.
#no-changelog

Update podspec dependencies for 6.30.0

---

FirebaseAppDistribution/Sources/FIRAppDistribution.m

Update the web view url to point to appdistribution.firebase.dev.
#no-changelog App Distribution is not live

Change to appdistribution.firebase.dev from partnerdash.google.com

---

.github/workflows/spm.yml
FirebaseAnalyticsWrapper/Public/FirebaseAnalytics/FIRAnalytics+AppDelegate.h
FirebaseAnalyticsWrapper/Public/FirebaseAnalytics/FIRAnalytics.h
FirebaseAnalyticsWrapper/Public/FirebaseAnalytics/FIREventNames.h
FirebaseAnalyticsWrapper/Public/FirebaseAnalytics/FIRParameterNames.h
FirebaseAnalyticsWrapper/Public/FirebaseAnalytics/FIRUserPropertyNames.h
FirebaseAnalyticsWrapper/Public/FirebaseAnalytics/FirebaseAnalytics.h
Package.swift
scripts/check_copyright.sh
scripts/style.sh

Initial implementation of Swift Package Manager and FirebaseAnalytics
- Successfully ran the SPM tests for iOS (we don't currently support CI for single platform targets)
- Ran the Analytics Objective C and Swift Quickstarts with the `-ObjC` workaround
- Clients must add `-ObjC` to `Other Linker Flags`
- Before Xcode12 beta 4, clients may need to manually add the system frameworks and libraries
- Details at https://forums.swift.org/t/swiftpm-binary-linker-questions/39100
- Added the Analytics public headers to make them available for SPM clients and disabled checks for them
- Disabled `swift build` CI since it is macOS only and is a pure subset of the `xcodebuild` testing
#no-changelog

SPM - Initial Analytics

---

FirebaseAppDistribution.podspec

Rollback podfile to point at live releases to facilitate EAP testing off of master.
#no-changelog App Distribution is not yet included in the public release

Update podfile to point to live releases for EAP customers

---

FirebaseInstallations/CHANGELOG.md
FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m

FirebaseInstallations: use ephemeral NSURLSession to prevent caching of request/response

---

GoogleUtilities/CHANGELOG.md
GoogleUtilities/Environment/SecureStorage/GULKeychainStorage.m
GoogleUtilities/Tests/Unit/Environment/GULKeychainStorageTests.m

Reverts firebase/firebase-ios-sdk#6224
The change was mistaken. `NSCache` is in-memory only and does never store data to disk, so can be safely used as a cache here.

Revert "GULKeychainStorage: use dictionary instead of NSCache"

---

FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsBackoffController.m
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsBackoffControllerTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m

- 403 - unrecoverable
- 401 and 404 - no backoff as they are auto-recoverable by the SDK
- connection errors - no backoff
- 429, 5xx - maximum backoff interval 30 min
- tests

FIS backoff adjustments and tests

---

Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
FirebaseCoreDiagnostics.podspec
Package.swift

- Repo-relative headers
- SPM Diagnostics logging
- SPM build
- Skipping standard directory structure because of upcoming deprecation
Verified deploymentType running the Analytics quickstart:

Add SPM support for CoreDiagnostics

---

GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCORLibrary/GDTCORClock.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORClockTest.m

- use Foundation instead of CoreFoundation API to get the system time zone, because `CFTimeZoneCopySystem()` and `CFTimeZoneCopyDefault()` don't respect current daylight offset.
Context: b/159368113.

GDTCORClock: use NSTimeZone to get a timezone with respect of daylight

---

Firestore/Swift/CHANGELOG.md
Firestore/Swift/Source/Codable/ServerTimestamp.swift
Firestore/Swift/Tests/Codable/FirestoreEncoderTests.swift

This turns out not to actually work because `NSDate` does not conform to `Codable`. Users can supply their own extensions that make `NSDate` conform to `Codable` and also supply an extension like this one to make `NSDate` conform to `ServerTimestampWrappable`.
Add a test that verifies ServerTimestamps of Swift `Date` actually work. The equivalent test for `NSDate` does not compile.

Remove the extension that makes NSDate ServerTimestampWrappable.

---

FirebaseAppDistribution/Sources/FIRAppDistribution.m
FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m

When the version (or build) of the current app is different than the version or build of the latest release, show the prompt to update to the latest version.
#no-changelog app distibution is not released yet

[App Distribution] Show new build alert when version (or build) changes

---

CoreOnly/Sources/Firebase.h
CoreOnly/Tests/FirebasePodTest/Podfile
Dangerfile
Firebase.podspec
FirebaseAppDistribution.podspec
ZipBuilder/Sources/ZipBuilder/FirebasePods.swift

Check off a few updates for SDK launch readiness:
- Update the Dangerfile
- Update the Firebase.h header file
- Update the Firebase.podspec file
#no-changelog This is part of the App Distribution initial launch

Update Dangerfile, Firebase.h, and Firebase.podspec for launch readiness

---

.travis.yml

Skip travis `pod lib lint` test_spec executions since they're not supported with watchOS and these tests are redundant with GHA testing.
#no-changelog

Skip pod lib lint tests now that watchos is coming

---

GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m

Fix a clang-tidy issue - http://clang.llvm.org/extra/clang-tidy/checks/readability-inconsistent-declaration-parameter-name.html

Fix clang-tidy

---

GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransport/GDTCCTTests/Unit/GDTCCTUploaderTest.m
GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCORTargets.h

- "unhide" code annotated with `copybara:...` introduced in #6254 to improve readability and prevent potential future refactoring issues.
#no-changelog

GDT: revert cc_scub annotations

---

.github/workflows/abtesting.yml
.github/workflows/auth.yml
.github/workflows/core.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/functions.yml
.github/workflows/inappmessaging.yml
.github/workflows/installations.yml
.github/workflows/remoteconfig.yml
.github/workflows/spm.yml
.github/workflows/storage.yml
.swiftpm/xcode/xcshareddata/xcschemes/ABTestingUnit.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/AuthUnit.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/CoreUnit.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/DatabaseUnit.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/Firebase-Package.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/Firebase.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/FirebaseAuth.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/FirebaseCore.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/FirebaseCrashlytics.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/FirebaseFunctions.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/FirebaseInstallations.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/FirebaseStorage.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/FirebaseStorageSwift.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/RemoteConfigUnit.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/StorageUnit.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/objc-import-test.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/swift-test.xcscheme

Migrate SwiftPM testing to the more granular workflows.
The six existing unit tests are supported by manually creating their schemes in the Xcode UI and then committing them.
For the libraries that have not yet set up Swift PM unit testing, it's a build only test for now.
#no-changelog

Add distributed SPM CI builds and tests

---

FirebaseAppDistribution/Sources/FIRAppDistributionRelease.m
FirebaseAppDistribution/Sources/Public/FIRAppDistributionRelease.h

Add isExpired to FIRAppDistributionRelease to allow the user to verify that the Release's download URL is not expired
#no-changelog App Distribution is not released yet

[App Distribution] Add isExpired to FIRAppDistributionRelease

---

FirebaseMessaging/CHANGELOG.md
FirebaseMessaging/Sources/Public/FIRMessaging.h

Messaging - no typedefs in public APIs

---

SymbolCollisionTest/Podfile

The Symbol Collision test was failing in CI because the GoogleUtilitiesComponents version specified in SpecsStaging is not findable outside of new test infra.
#no-changelog

Get GoogleUtilitiesComponents from HEAD in symbol collision test

---

Crashlytics/CHANGELOG.md
Firebase/CoreDiagnostics/CHANGELOG.md
FirebaseAuth/CHANGELOG.md
FirebaseCore.podspec
FirebaseCore/CHANGELOG.md
FirebaseCoreDiagnostics.podspec
FirebaseInstallations/CHANGELOG.md

The referenced https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md will be created later this week.

M78 Changelogs - SwiftPM and watchOS updates

---

Crashlytics/CHANGELOG.md
Crashlytics/Crashlytics/Controllers/FIRCLSNetworkClient.m

Fixes #5984.
NSURLSessionTask's original request is [documented as nullable](https://developer.apple.com/documentation/foundation/urlsessiontask/1411572-originalrequest).

Fix occasional NSURLSessionTask creation crash

---

Firebase.podspec

Update Firebase umbrella podspec for AppDistribution only supporting iOS platform and requiring at least 9.0
#no-changelog

AppDistribution is only available for iOS

---

FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRFederatedAuthProvider.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRGameCenterAuthProvider.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRMultiFactor.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRPhoneAuthProvider.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRUser.h

Improve Xcode usability of accessing APIs from Swift:
From 
to 
- Enabled clang-format where it was disabled
- Removed unnecessary `API_AVAILABLE(ios(8.0))`

Auth - no typedefs in public APIs

---

Firebase/InstanceID/CHANGELOG.md
Firebase/InstanceID/FIRInstanceID.m
Firebase/InstanceID/FIRInstanceIDAuthKeyChain.h
Firebase/InstanceID/FIRInstanceIDAuthKeyChain.m
Firebase/InstanceID/FIRInstanceIDConstants.h
Firebase/InstanceID/FIRInstanceIDConstants.m
Firebase/InstanceID/FIRInstanceIDStore.h
Firebase/InstanceID/FIRInstanceIDStore.m
Firebase/InstanceID/FIRInstanceIDTokenManager.h
Firebase/InstanceID/FIRInstanceIDTokenManager.m
Firebase/InstanceID/FIRInstanceIDTokenStore.h
Firebase/InstanceID/FIRInstanceIDTokenStore.m
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
FirebaseMessaging/CHANGELOG.md

When we release Messaging that removes InstanceID dependency, Messaging will handle FCM token on its own. However, developers might still depend on both Messaging and InstanceID, each has its own cache for token, but share the same storage(keychain). We need to add a method in InstanceID to listen to a notification from Messaging for token refresh, if that happens, InstanceID will update its cache, but not storage, as Messaging already updated it. 
We want developers to adopt this version before hand as we can't re-enforce iid version once messaging remove it from its dependency. So I updated the new version of messaging to depend on at least this version of IID.
Manual tested in the chen/fm-master branch which has the latest version of Messaging without IID dependency.
Add/delete token …

Update InstanceID to listen to a notification from Messaging

---

Package.swift

Fix #6280 
Intrinsics are not available in SwiftUI preview builds. The updated abseil disables the build error for the no intrinsic case of int128.h in addition to the intrinsic case.
See https://github.com/firebase/abseil-cpp/commit/d30bd7751ce343a05fca6413de0dec062163e5e9
#no-changelog

Update abseil for SwiftUI preview build fix

---

FirebaseAuth/CHANGELOG.md
FirebaseCore/CHANGELOG.md

An extra parentheses prevented the link from rendering properly.

Fix rendering of link in M78

---

ZipBuilder/Sources/oss-manifest-generator/main.swift

The file was mistakenly checked in on the first release branch commit.
#no-changelog

Restore master version of oss-manifest-generator

---

FirebaseAppDistribution/CHANGELOG.md
FirebaseAppDistribution/Sources/Public/FIRAppDistribution.h
FirebaseAppDistribution/Sources/Public/FIRAppDistributionRelease.h

Fixes some comments not being doc comments and updates verbiage.

Update doc comments for release

---

Crashlytics/CHANGELOG.md
Crashlytics/Crashlytics/FIRStackFrame.m
Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRStackFrame.h

Added a public method to allow stack frames to be created from addresses, as requested in https://github.com/firebase/firebase-ios-sdk/issues/5975.

Made public a method to create a stack frame from address.

---

FirebaseAppDistribution/CHANGELOG.md
FirebaseAppDistribution/Sources/FIRFADApiService.m

Customers with restricted api keys reported being unable to see new build alerts and saw repeated prompts for login
* Added x-ios-bundle-identifier for api keys restricted to ios apps

App distribution add bundle header

---

FirebaseAppDistribution.podspec
FirebaseAppDistribution/CHANGELOG.md
FirebaseAppDistribution/Sources/FIRFADApiService.m

* [fixed] Bug for customers with restricted API keys unable to fetch releases (#6346).

App distribution patch for restricted api keys

---

Firebase.podspec

This is a partial rollback of #6337 
Since Google-Mobile-Ads-SDK 7.64 requires a minimum of iOS 9, we should hold off until the Firebase 7 major breaking change.

Avoid forcing a breaking AdMob change

---

Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h

Found some extremely minor typos whilst snooping around implementing FlutterFire Crashlytics, so thought I'd send a quick PR 😅 thanks!

chore: fix minor code doc typos

---

CoreOnly/Sources/Firebase.h
FirebaseCore/CHANGELOG.md

now that SPM supports same public header path as CocoaPods
It seems the ifdef around FirebaseCore.h contributed to an Xcode build race condition where the app could try to build before FirebaseCore.
Fix #6341

Restore Firebase.h to pre-6.28.0 style

---

CoreOnly/Sources/Firebase.h
Firebase.podspec
FirebaseCore/CHANGELOG.md

Targeting publishing Monday morning to provide a fix for a Xcode race condition build failure. (#6341)

Prepare for 6.31.1

---

Crashlytics/CHANGELOG.md
Crashlytics/Crashlytics/Components/FIRCLSProcess.c
Crashlytics/Crashlytics/Helpers/FIRCLSUtility.h
Crashlytics/Crashlytics/Helpers/FIRCLSUtility.m
Crashlytics/UnitTests/FIRCLSUtilityTests.m

It's possible that the binary image data loaded from the OS includes the device's UDID. This makes a best effort at redacting that data before the crash report is written to disk.

redact UDID information from binary image data

---

cmake/compiler_setup.cmake

This option doesn't work with C++, and even though the clang compiler
ignores it, clangd does not, and this causes syntax highlighting
failures in CLion.

Remove -fmodules from CMake C++ compilation flags.

---

.swiftpm/xcode/xcshareddata/xcschemes/Firebase-Package.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/version-test.xcscheme
Package.swift
SwiftPMTests/version-test/versionTest.m

Add the correct Firebase version to the SwiftPM builds and add a test.
Note that the single versioning across Firebase products matches the zip and Carthage distribution versioning but not CocoaPods. All will be unified in Firebase 7.0.  See #6295.
Proposing to cherry pick to the 6.32.0 branch

Fix SwiftPM versioning

---

FirebaseCore/CHANGELOG.md
Package.swift

Define the system framework and system library dependencies. This resolves undefined symbol issues for system dependencies.
Fix #6408. Fix #6413.

SPM - define system dependencies

---

FirebaseDynamicLinks/CHANGELOG.md
FirebaseDynamicLinks/Sources/FIRDLDefaultRetrievalProcessV2.h
FirebaseDynamicLinks/Sources/FIRDLDefaultRetrievalProcessV2.m
FirebaseDynamicLinks/Sources/FIRDLRetrievalProcessFactory.h
FirebaseDynamicLinks/Sources/FIRDLRetrievalProcessFactory.m
FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.h
FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.m
FirebaseDynamicLinks/Sources/FIRDynamicLinks+FirstParty.h
FirebaseDynamicLinks/Sources/FIRDynamicLinks+Private.h
FirebaseDynamicLinks/Sources/FIRDynamicLinks.m
FirebaseDynamicLinks/Sources/Logging/FDLLogging.h
FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinkNetworkingTests.m
FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m

Removing client id usage in api call and respective checks
FDL SDK was using client id passed in FIROptions to make API calls. From backend side, we no longer needs client id to be sent. So removing the client id usage in FDL SDK along with parameter no null checks.
-Removed the usage of Client id from FIROptions.
-Removed non null parameter checks for client id.
-Deprecated 1p API method setUpWithLaunchOptions::apiKey:clientID:urlScheme:userDefaults: and added setUpWithLaunchOptions::apiKey:urlScheme:userDefaults:
-Removed Client id usage in Unit tests.

Removing client id usage in api call and respective checks

---

.github/workflows/abtesting.yml
.github/workflows/auth.yml
.github/workflows/core.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/functions.yml
.github/workflows/inappmessaging.yml
.github/workflows/installations.yml
.github/workflows/remoteconfig.yml
.github/workflows/spm.yml
.github/workflows/storage.yml
Package.swift
scripts/build.sh

Several fixes to SPM test infrastructure
- Test failures weren't reported in GHA because they weren't propagated through xcpretty
- Fixed above by using build.sh with its `set -euo pipefail` setup
- Use matrix for spm cron runs
- Add Catalyst to the test matrix
- Start running SPM tests for Installations (fixed scheme)
- Start running SPM tests for FIAM (fixed scheme)
- Define subset of passing tests for non-iOS platforms in spm.yml
- Add iOS condition for Analytics binary library dependencies
#no-changelog

SPM test infra fixes

---

Firebase.podspec
FirebaseCore/CHANGELOG.md
README.md

Address https://github.com/firebase/firebase-ios-sdk/issues/4558#issuecomment-690355011

Add Firebase pod support for Auth/Crashlytics watchOS

---

Package.swift

Fix #6360
Confirmed that the pb-spm-info-plist branch fixes the bug.  After merging, I'll confirm the update flow work for the 6.32-spm-beta branch.

SPM: Add Info.plist to binary Analytics frameworks

---

FirebaseCore/CHANGELOG.md
ZipBuilder/Sources/ZipBuilder/CarthageUtils.swift
ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift

Fix #5562 
Tested in #6444 and 
```
$ diff -r ~/zip-m77/2020-08-05T09-21-45/CarthageFirebase/ CarthageFirebase/ | grep "Only in"
Only in CarthageFirebase/FirebaseAnalytics/FIRAnalyticsConnector.framework: Info.plist
Only in CarthageFirebase/FirebaseAnalytics/FirebaseAnalytics.framework: Info.plist
Only in CarthageFirebase/FirebaseAnalytics/GoogleAppMeasurement.framework: Info.plist
Only in CarthageFirebase/: FirebaseAppDistribution
Only in CarthageFirebase/FirebaseMLModelInterpreter/FirebaseMLCommon.framework: Info.plist
Only in CarthageFirebase/FirebaseMLModelInterpreter/FirebaseMLModelInterpreter.framework: Info.plist
Only in CarthageFirebase/FirebaseMLModelInterpreter/TensorFlowLiteC.framework: Info.plist
Only in CarthageFirebase/FirebaseMLVision/FirebaseMLCommon.framework: Info.plist …
```

Add Info.plist to Carthage binary frameworks

---

FirebaseCore/CHANGELOG.md
Package.swift

Fix #6449 
Update SPM dependencies to address platform build warnings from specifying a lower iOS minimum iOS version than what is supported by Xcode. See details in discussion at https://forums.swift.org/t/minimum-ios-version-xcode-12-and-build-warnings/40224/5.
All dependencies are fixed except gtm-session-fetcher (for Auth, Storage and Functions) which is addressed at https://github.com/google/gtm-session-fetcher/pull/202

SPM: Fix platform build warnings

---

scripts/release_testing_setup.sh

This change is due to an error observed in a nightly test log: 
```
++ git tag -f -a nightly-test-6.32.1 -m 'release testing'
Updated tag 'nightly-test-6.32.1' (was ec290f2a5)
++ git push origin nightly-test-6.32.1
To https://github.com/firebase/firebase-ios-sdk.git
! [rejected]            nightly-test-6.32.1 -> nightly-test-6.32.1 (already exists)
error: failed to push some refs to 'https://github.com/firebase/firebase-ios-sdk.git'
```
Tag updated to a remote should be removed first.
Will uncomment line 31 after review to avoid unexpected issues.
`# git push origin --delete "${tag_version}" `

Remove tag before add

---

FirebaseAppDistribution/CHANGELOG.md
FirebaseAppDistribution/Sources/FIRFADApiService.m
FirebaseAppDistribution/Tests/Unit/FIRFADApiServiceTests.m

Parse the error object to log more extensive information when users receive an error from our API.

Update the API service to log the returned message from the API

---

Crashlytics/run

Fixes a small typo `cSYMs` -> `dSYMs`.
Reference: https://developer.apple.com/documentation/xcode/building_your_app_to_include_debugging_information

Fix typo: cSYMs -> dSYMs

---

Crashlytics/CHANGELOG.md

4.6.1 is releasing with just the Unreleased changes

Update Crashlytics CHANGELOG with 4.6.0 released changes

---

GoogleDataTransport/GDTCCTTests/Unit/GDTCCTUploaderTest.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORTransformerTest.m

- `XCAssert` maros family doesn't use `self` reference in Xcode 12 any more, so using `XCAssert...` in blocks doesn't require  `weakSelf`. Added `__unused ` modifier to silent the Xcode 12 warnings that fail `pod lib lint`. 
#no-changelog

GDT tests: Xcode 12 fixes

---

FirebaseStorage/Sources/FIRStorageTask_Private.h
FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageTaskSnapshot.h

Me again 😅 , found another minor typo so sending this quick fix. Thanks!
N/A
N/A

docs(storage): fix minor typo in code docs

---

Firestore/core/test/unit/FSTGoogleTestTests.mm

The bridge from GoogleTest to XCTest recorded failures using `recordFailureWithDescription:inFile:atLine:expected:`, which has been deprecated.
#no-changelog

Fix FSTGoogleTestTests under Xcode 12

---

GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m

Related to #6482 and #6483
- Keep Xcode 10 compatibility so far as we still verify it on Travis.

GDT: remove pre Xcode 10 availability checks

---

SwiftPackageManager.md

Since it's out of beta, let's just mention Xcode 12.

Update Xcode 12 requirement for SwiftPM docs.

---

FirebaseAnalyticsWrapper/include/dummy.h
Package.swift
scripts/check_copyright.sh

Fix #6503 
Adds a dummy header so the SPM-generated umbrella won't give a warning.
Fixes copyrights in FirebaseAnalyticsWrapper directory.
Disregard the CI failure since the failing test is pending the 6.33.0 CocoaPods publish.
#no-changelog

Fix SPM analytics warning introduced yesterday

---

CoreOnly/Sources/Firebase.h

And simplify warning message so it works for any package manager.
Eliminate the warning since it is not currently possible to solve for macOS, tvOS and watchOS and missing Analytics support is documented.
See https://github.com/firebase/firebase-ios-sdk/issues/4557#issuecomment-695011515
For Firebase 7, consider completely eliminating these for iOS as well.
cc: @christibbs @chliangGoogle @eldhosembabu @visumickey @karenyz

Generate missing Analytics warning only for iOS

---

FirebaseDynamicLinks/Sources/FIRDynamicLinks+FirstParty.h

Most FirstParty users will still need to use methods from FIRDynamicLinks.h
(shouldHandleDynamicLinkFromCustomSchemeURL:/dynamicLinkFromCustomSchemeURL: etc.).
Arguably, including both headers looks odd, hence add the IWYU pragma so that it's sufficient
to include only the FirstParty header.

Add IWYU pragma to FIRDynamicLinks+FirstParty/FIRDynamicLinks

---

Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRStackFrame.h

This is because Jazzy generates HTML from the header file, and `<missing>` is not valid HTML
#no-changelog

Update FIRStackFrame header to generate HTML correctly for Reference Docs

---

.github/workflows/remoteconfig.yml
scripts/generate_access_token.sh

Update to latest google-auth-library-swift with the needed fix at https://github.com/googleapis/google-auth-library-swift/pull/39 to fix [test breakage](https://github.com/firebase/firebase-ios-sdk/runs/1142644469?check_suite_focus=true).
#no-changelog

Update dependent Swift repo to fix CI breakage

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
Firestore/Example/Tests/SpecTests/json/recovery_spec_test.json
Firestore/Example/Tests/SpecTests/json/write_spec_test.json

Port of https://github.com/firebase/firebase-android-sdk/pull/2000 (that's right - 2000!)

Import Spec tests

---

GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m

This should fix test flakes like [this](https://github.com/firebase/firebase-ios-sdk/runs/1153709908?check_suite_focus=true)
#no-changelog

GDTCORFlatFileStorageTest size limit tests: use timeout proportional to the number of events

---

FirebaseRemoteConfig/CHANGELOG.md
FirebaseRemoteConfig/Sources/RCNConfigFetch.m

Fix #6522
Even though `[error localizedDescription]` is never supposed to return nil, it seems that it sometime does.  See https://stackoverflow.com/a/34684861/556617.
This change avoids a crash when that happens.

Fix a rare RC crash

---

.github/workflows/abtesting.yml
.github/workflows/appdistribution.yml
.github/workflows/archiving.yml
.github/workflows/auth.yml
.github/workflows/core.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/datatransport.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/functions.yml
.github/workflows/inappmessaging.yml
.github/workflows/instanceid.yml
.github/workflows/messaging.yml
.github/workflows/remoteconfig.yml
.github/workflows/storage.yml
.swiftpm/xcode/xcshareddata/xcschemes/Firebase-Package.xcscheme

This reduces the duplication in each of the workflow files. This also
will make archive testing with SwiftPM more straightforward.

Refactoring archive testing to a single yml file.

---

GoogleDataTransport.podspec
GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage+Promises.m
GoogleDataTransport/GDTCORLibrary/GDTCORUploadBatch.m
GoogleDataTransport/GDTCORLibrary/Private/GDTCORFlatFileStorage+Promises.h
GoogleDataTransport/GDTCORLibrary/Private/GDTCORUploadBatch.h
GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCORStorageProtocol.h

The next PR from promise refactoring series (b/160018519). 
- promise based API for `GDTCORFlatFileStorage` that will be used in `GDTCCTUploadOperation`
Tests to be fixed and updated in the next PRs.
#no-changelog

GDTCORStorage: promise API wrapper

---

FirebaseRemoteConfig/CHANGELOG.md
FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h

API review approved, tracked in internal b/144366943

Change lastFetchTime to be readonly

---

GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCORLibrary/GDTCORDirectorySizeTracker.m
GoogleDataTransport/GDTCORTests/Unit/GDTCORDirectorySizeTrackerTests.m

Fixes #6540
- replace [URLWithString:](https://developer.apple.com/documentation/foundation/nsurl/1572047-urlwithstring) with [fileURLWithPath](https://developer.apple.com/documentation/foundation/nsurl/1410828-fileurlwithpath) (the later one was originally supposed to be used). `URLWithString:` fails to create a URL for paths that contain symbols like a whitespace which is a valid path symbol.

GDTCORDirectorySizeTracker: fix NSURL constructor

---

Firestore/core/src/remote/firebase_metadata_provider_apple.mm

Any non-zero heartbeat value is immediately reset to zero upon retrieval. Thus, should the network request containing the heartbeat value and the user agent string fail, the previous logic would prevent us from sending the user agent string until the next day (when the heartbeat once again returns a non-zero value). Until this is resolved, always send the user agent string, regardless of the heartbeat value. The associated increase in bandwidth usage is minor (~1.2% in _total_ traffic from running the full suite of Firestore integration tests, which represent the worst-case scenario because they recreate the streams much more often than a typical application).

Always send the user agent regardless of the heartbeat value

---

Firestore/core/src/util/exception.cc
Firestore/core/src/util/exception.h
Firestore/core/src/util/firestore_exceptions.h

Move FirestoreInternalError to firebase::firestore to match FirestoreException in Android.
When importing this into google3, we'll have to delete the Android-specific version of this type.

Make FirestoreException a type defined by Firestore/core

---

FirebaseABTesting/CHANGELOG.md
FirebaseABTesting/Sources/FIRExperimentController.m
FirebaseABTesting/Sources/Public/FirebaseABTesting/FIRExperimentController.h
FirebaseABTesting/Tests/Unit/FIRExperimentControllerTest.m
FirebaseRemoteConfig/CHANGELOG.md
FirebaseRemoteConfig/Sources/RCNConfigExperiment.m
FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m

Also remove usages in RC, using the new method with completion handler.
Fixes #6543.

Remove deprecated method in ABT public header

---

Example/InstanceID/IntegrationTests/FIRInstanceIDIntegrationTests.m
Example/InstanceID/Tests/FIRInstanceIDResultTest.m
Example/InstanceID/Tests/FIRInstanceIDTest.m
Firebase/InstanceID/CHANGELOG.md
Firebase/InstanceID/FIRInstanceID+Private.m
Firebase/InstanceID/FIRInstanceID.m
Firebase/InstanceID/FIRInstanceIDUtilities.m
Firebase/InstanceID/Public/FIRInstanceID.h
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
FirebaseMessaging/CHANGELOG.md
FirebaseMessaging/Sources/FIRMessaging.m
FirebaseMessaging/Sources/FIRMessagingClient.m
FirebaseMessaging/Sources/FIRMessagingPubSub.m
FirebaseMessaging/Sources/FIRMessagingTopicOperation.m
FirebaseMessaging/Tests/IntegrationTests/FIRMessagingTokenRefreshTests.swift
FirebaseMessaging/Tests/UnitTests/FIRInstanceIDWithFCMTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingClientTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingHandlingTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingServiceTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingTestUtilities.h
FirebaseMessaging/Tests/UnitTests/FIRMessagingTestUtilities.m

Adding deprecation warnings that are documented in the token API review doc.

Add InstanceID deprecation warning

---

.github/workflows/abtesting.yml
.github/workflows/appdistribution.yml
.github/workflows/auth.yml
.github/workflows/core.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/datatransport.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/installations.yml
.github/workflows/instanceid.yml
.github/workflows/messaging.yml
.github/workflows/remoteconfig.yml
.github/workflows/storage.yml
.travis.yml
FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinkNetworkingTests.m
FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m
Gemfile
Gemfile.lock

Now that static framework's are off by default, make sure we still test when it is turned back on.
Remove `--use-modular-headers` testing since it is mostly redundant with `--use-static-frameworks` and no longer a recommended option.
All tests passed before turning cron back on
Note that the `--use-static-framework` pod lib lint option is introduced in CocoaPods 1.10
#no-changelog

Add static-framework testing to CI

---

FirebaseInstallations/CHANGELOG.md
FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.h
FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.m
FirebaseInstallations/Source/Library/FIRInstallationsItem.h
FirebaseInstallations/Source/Library/FIRInstallationsItem.m
FirebaseInstallations/Source/Library/FIRInstallationsLogger.h
FirebaseInstallations/Source/Library/FIRInstallationsLogger.m
FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
FirebaseInstallations/Source/Tests/Fixture/APIRegisterInstallationResponseSuccessNoFID.json
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
FirebaseInstallations/Source/Tests/Unit/FIRInstallationsItemTests.m
FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.h
FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.m

Related to #6563. 
- more detailed validation of `FIRInstallationsItem` read from storage to catch a potential data corruption (e.g. manual modifications of Keychain item on macOS, etc.)
- validation of `FIRInstallationsItem` before sending registration request.

FIS: Additional FIRInstallationsItem validation

---

Firebase.podspec
FirebaseCore.podspec
FirebaseCrashlytics.podspec
FirebaseFirestore.podspec
FirebaseInstallations.podspec
FirebaseInstallations/CHANGELOG.md
FirebaseRemoteConfig.podspec
FirebaseStorage.podspec
GoogleDataTransport.podspec
Package.swift
Releases/Manifests/6.34.0.json
SwiftPackageManager.md

Enabling to CI to succeed by providing correctly versioned Analytics and Performance binary podspecs in [SpecStaging](https://github.com/firebase/SpecsStaging). The Analytics podspecs actually point to the previous version's binaries.
I'll remove the test-only commit before merging this.
#no-changelog

Merge 6.34.0

---

FirebaseRemoteConfig/Tests/FakeConsole/FakeConsoleTests.swift
FirebaseRemoteConfig/Tests/SwiftAPI/APITests.swift
FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m

Separating this from the actual API removal PR for #6546
- Remove tests for deprecated methods
- Update other tests to no longer call deprecated methods

Clean up usage of deprecated methods in unit tests

---

FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/Auth/FIRAuth.m
FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRUser.h
FirebaseAuth/Sources/User/FIRUser.m
FirebaseAuth/Tests/Sample/Sample/MainViewController+User.m
FirebaseAuth/Tests/Unit/FIRAuthTests.m
FirebaseAuth/Tests/Unit/FIRUserTests.m

Remove deprecated APIs `dataForKey`,`fetchProvidersForEmail:completion`, `signInAndRetrieveDataWithCredential:completion`, `reauthenticateAndRetrieveDataWithCredential:completion`, `linkAndRetrieveDataWithCredential:completion`.
Fix #6544

Remove deprecated auth APIs

---

ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift

- Default minimum iOS version to 10
- Don't build GoogleUtilitiesComponents
#no-changelog

ZipBuilder Firebase 7 updates

---

FirebaseRemoteConfig/CHANGELOG.md
FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h

This aligns with behavior on other platforms: [JS](https://github.com/firebase/firebase-js-sdk/blob/master/packages/remote-config/src/value.ts#L49), [Android](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigGetParameterHandler.java#L260)
Fixes #6188.

Change numberValue to be nonnull

---

FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/Auth/FIRAuth_Internal.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h

Add auth emulator support `useEmulatorWithHost:port` to public API.
Implementation added in #6402

Add auth emulator support to public API.

---

FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m

Prevent message ` [Firebase/Installations][I-FIS002004] Stored installation validation error: (null)` from being logged when everything is ok.
#no-changelog

FIS: don't log anything on success validation

---

FirebaseCore/CHANGELOG.md
FirebaseCore/Sources/FIROptions.m
FirebaseCore/Sources/Private/FIROptionsInternal.h
FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h
FirebaseCore/Tests/SwiftUnit/FirebaseAppTests.swift
FirebaseCore/Tests/SwiftUnit/FirebaseOptionsTests.swift

This was unintentionally surfaced from the ObjC header and should be
removed.
Note: although the existing initializer doesn't work, this is still a
breaking change.
Fixes #5728 
Following recommendations from https://developer.apple.com/videos/play/wwdc2020/10680

Remove the `FirebaseOptions()` bare initializer.

---

scripts/check_imports.swift

Generates check error for an issue discovered in GDT in #6638
#no-changelog

Update check_imports check

---

FirebaseABTesting.podspec
FirebaseCore.podspec
FirebaseCore/CHANGELOG.md
FirebaseInAppMessaging.podspec
FirebaseInstallations.podspec
FirebaseInstanceID.podspec
FirebaseRemoteConfig.podspec
FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m
HeadersImports.md

Stop using CocoaPods private headers to be more consistent with Swift Package Manager.
Instead internal API's between repo pods should be referenced with repo-relative imports.
FirebaseCore Private's are kept for now because of internal non-Firebase client usage via CocoaPods (Flutter for example)

Stop using CocoaPods private headers

---

FirebaseAppDistribution/CHANGELOG.md
FirebaseAppDistribution/Sources/FIRAppDistribution.m
FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m

Check for an Unauthenticated error and sign out the Tester from the fetchNewLatestRelease.

Add check for unauthenticated error and sign out in fetchNewLatestRelease

---

.github/workflows/zip.yml
ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift

The ZipBuilder was crashing on Firebase 7 because it was trying to load an unspecified ML pod from the CDN with a dependency on an old version of FirebaseCore and then failing to `pod install`. This change specifies the versions of the closed source pods via the found Firebase pod.
Also fixing a build warning on a case return type.

Fix ZipBuilder crash and warning

---

FirebaseCoreDiagnostics.podspec
FirebaseCrashlytics.podspec
FirebaseFirestore.podspec
FirebaseInAppMessaging.podspec
GoogleDataTransport.podspec

Part of #6549 
This is a podspec only change for nanopb to restrict the iOS versions supported and to eliminate the Xcode 12 build warning.
See also https://github.com/google/nanopb-podspec/pull/16
@no-changelog

Bump nanopb to fix Xcode 12 warning

---

FirebaseCore/Sources/Private/FirebaseCoreInternal.h

I missed an update in converting FIRVersion from private to public in #6651 that led to a post-submit build break in Firestore.

Fix breakage from #6651

---

FirebaseCore/Sources/FIRComponentContainerInternal.h
FirebaseCore/Sources/Private/FIRComponentContainer.h
FirebaseCore/Sources/Private/FIRLibrary.h
FirebaseCore/Sources/Private/FirebaseCoreInternal.h
FirebaseCore/Tests/Unit/FIRAppTest.m
FirebaseCore/Tests/Unit/FIRComponentContainerTest.m
FirebaseCore/Tests/Unit/FIRTestComponents.m
Gemfile

Remove unnecessary imports and convert to forward `@class` declarations where possible.
#no-changelog

Simplify FirebaseCore imports

---

FirebaseABTesting/Sources/ABTConstants.h

Noticed while working on copybaras
The Foundation import is required for the subsequent `NSString` usages.
#no-changelog

Missing Foundation import

---

Crashlytics/Shared/FIRCLSFABHost.m

Hi,
I used Crashlytics with CocoaPods(Deployment Target iOS 13), will happen a warning.
The `UI_USER_INTERFACE_IDIOM()` was deprecated. And I changed it.
---
Part of the used Podfile.
```Podfile
platform :ios, '13.0'
use_frameworks!
target 'App' do
pod 'Firebase/Crashlytics'
end
post_install do | pi |
pi.pods_project.targets.each do | t |
t.build_configurations.each do | config |
config.build_settings ['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
end
end
end
```
Thanks.

UI_USER_INTERFACE_IDIOM() was deprecated in iOS 14

---

Package.swift

Fix #6606
Speed up Swift Package Manager initialization by using copies of three of the dependency repositories that have substantially smaller git metadata.
Here's an approximate difference in time for a git clone for one of them:
```
$ time git clone git@github.com:paulb777/grpc.git Cloning into 'grpc'... remote: Enumerating objects: 35, done. remote: Counting objects: 100% (35/35), done. remote: Compressing objects: 100% (11/11), done. remote: Total 463922 (delta 25), reused 24 (delta 24), pack-reused 463887 Receiving objects: 100% (463922/463922), 200.91 MiB | 29.75 MiB/s, done. Updating files: 100% (9270/9270), done.
real 0m25.445s user 1m29.526s sys 0m5.475s
vs
time git clone git@github.com:paulb777/grpc2.git Cloning into 'grpc2'... remote: Enumerating objects: 9066, done. remote: …
```

Speedup SwiftPM

---

Example/InstanceID/Tests/FIRInstanceIDTokenOperationsTest.m

`FIRInstanceIDTokenOperationsTest.m:219:10: error: capturing 'operation' strongly in this block is likely to lead to a retain cycle [-Werror,-Warc-retain-cycles]`
#no-changelog

Fix an IID google3 build error

---

Firebase/InstanceID/FIRInstanceID.m
FirebaseMessaging/CHANGELOG.md

Fixes #6553.
There's a small chance the APNS token is returned from Apple with a delay so the first token request was sent without the apns token info. However, the retry logic didn't really trigger a second request, so fixed that.

Fix an issue notification is not received during app first install

---

FirebaseMessaging/Tests/UnitTests/FIRMessagingPendingTopicsListTest.m

```
FIRMessagingPendingTopicsListTest.m:122:13: error: capturing 'self' strongly in this block is likely to lead to a retain cycle [-Werror,-Warc-retain-cycles]
XCTAssertEqual(pendingTopics.numberOfBatches, 1);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
#no-changelog

Fix retain cycle build issue

---

GoogleDataTransport.podspec
GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m

GoogleDataTransport: deprecated API conditions

---

GoogleDataTransport/CHANGELOG.md
GoogleUtilities/CHANGELOG.md

This was written to the wrong CHANGELOG. Whoops!

Fixed CHANGELOG location.

---

FirebaseStorage/CHANGELOG.md
FirebaseStorage/Sources/FIRStorageUtils.m
FirebaseStorage/Tests/Unit/FIRStorageListTests.m

NSQueryParams doesn't encode `+` to `%2B`, which breaks the List API since it treats `+` as space. 
Note that other Storage APIs don't rely on query param encoding. There is already an integration tests that verifies that users can up and download files with `+` signs. 
Fixes b/170259897

Support paths with + in List API

---

FirebaseAuth/Sources/AuthProvider/OAuth/FIROAuthProvider.m

When using the auth emulator, disable generic OAuth checks for Facebook and Apple sign in. This is to add support for the auth emulator in FirebaseUI, which should not launch any IDP-provided SDKs so that real accounts are not required.
Launching generic OAuth with the auth emulator launches an emulated widget, and does NOT connect to the actual IDP.

Disable generic OAuth checks for Facebook and Apple when using the auth emulator.

---

Firestore/core/src/local/leveldb_target_cache.cc
Firestore/core/test/unit/local/leveldb_target_cache_test.cc
Firestore/core/test/unit/local/target_cache_test.cc

Although still not sure of underlying cause, this should make https://github.com/firebase/firebase-ios-sdk/issues/6644 stopping crashing.

Log warning instead of failing SDK when discovering dangling target.

---

FirebaseCore/CHANGELOG.md
Package.swift
SwiftPM-PlatformExclude/FirebaseAnalyticsWrap/dummy.m
SwiftPM-PlatformExclude/FirebaseAnalyticsWrap/include/dummy.h
SwiftPM-PlatformExclude/FirebaseDatabaseWrap/dummy.m
SwiftPM-PlatformExclude/FirebaseDatabaseWrap/include/dummy.h
SwiftPM-PlatformExclude/FirebaseDynamicLinksWrap/dummy.m
SwiftPM-PlatformExclude/FirebaseDynamicLinksWrap/include/dummy.h
SwiftPM-PlatformExclude/FirebaseFirestoreSwiftWrap/dummy.m
SwiftPM-PlatformExclude/FirebaseFirestoreSwiftWrap/include/dummy.h
SwiftPM-PlatformExclude/FirebaseFirestoreWrap/dummy.m
SwiftPM-PlatformExclude/FirebaseFirestoreWrap/include/dummy.h
SwiftPM-PlatformExclude/FirebaseFunctionsWrap/dummy.m
SwiftPM-PlatformExclude/FirebaseFunctionsWrap/include/dummy.h
SwiftPM-PlatformExclude/FirebaseInAppMessagingWrap/dummy.m
SwiftPM-PlatformExclude/FirebaseInAppMessagingWrap/include/dummy.h
SwiftPM-PlatformExclude/FirebaseRemoteConfigWrap/dummy.m
SwiftPM-PlatformExclude/FirebaseRemoteConfigWrap/include/dummy.h
SwiftPackageManager.md

Fix #6584 
This seems to work for building along with a build warning if a product is selected that doesn't support watchOS.
Testing is an open question since XCTest is not supported and the SPM `.testTarget` automatically tries to link XCTest and fails even if XCTest is not used.
Also manually confirmed the Analytics, Storage, and Firestore quickstarts still run for iOS with SPM.

Initial SPM building for watchOS

---

FirebaseDatabase/CHANGELOG.md
FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m

Disable deprecation warning

---

FirebaseRemoteConfig/CHANGELOG.md
FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
FirebaseRemoteConfig/Sources/RCNConfigExperiment.h
FirebaseRemoteConfig/Sources/RCNConfigExperiment.m
FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m

Ensure that activate completion is called after `updateExperiments` finishes executing
Fixes #3687

Use completion handler when updating experiments after activation

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm
Firestore/Source/API/FIRDocumentSnapshot.mm
Firestore/Source/API/FIRFirestoreSettings.mm
Firestore/Source/Public/FirebaseFirestore/FIRFirestoreSettings.h
Firestore/core/src/api/settings.cc
Firestore/core/src/api/settings.h
Firestore/core/src/model/field_value_options.h

Snapshots will now always include `FIRTimestamp` values. Use `[FIRTimestamp dateValue]` to convert to `NSDate` if required.
`timestampsInSnapshotsEnabled` was deprecated in Firebase 5.16.0 (January 22, 2019) and has defaulted to true since then.
Projects that have not enabled `timestampsInSnapshotsEnabled` have logged a warning since Firebase 4.12.0 (April 10, 2018).
/cc @var-const Note that this is also a breaking change for the C++ SDK, but only because it currently forces timestamps in snapshots to true. We could remove that in advance of importing M82 without a problem (since `timestampsInSnapshotsEnabled` already defaults to true). Existing users will be unaffected because the dependency on this pod only floats on patch levels.

Remove support for setting timestampsInSnapshotsEnabled

---

FirebaseRemoteConfig/README.md
FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
FirebaseRemoteConfig/Tests/Unit/RCNUserDefaultsManagerTests.m

Minor RC cleanup

---

GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m
GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader2.m
GoogleDataTransport/GDTCCTLibrary/Private/GDTCCTUploadOperation.h
GoogleDataTransport/GDTCCTLibrary/Private/GDTCCTUploader.h
GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.h
GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.m
GoogleDataTransport/GDTCCTTests/Unit/GDTCCTUploaderTest.m
GoogleDataTransport/GDTCORLibrary/GDTCORRegistrar.m
GoogleDataTransport/GDTCORLibrary/Internal/GDTCORStorageProtocol.h

Next uploading refactoring step b/160018519.
- express entire upload operation in a single chain of async steps bound with promises
- remove code not required any more
Next steps:
- break down URL request steps
- error handling
- fix tests
#no-changelog

GDT: wrap and bind upload operation using promises

---

Firebase/InstanceID/CHANGELOG.md
Firebase/InstanceID/FIRInstanceIDTokenManager.m
FirebaseMessaging/CHANGELOG.md

It was introduced when we start calling the token call without passing a handler: Fix #6669
Also the changelog for the whole change should be in IID not messaging.

Missing iid handler checking cause crash

---

ZipBuilder/Sources/FirebaseReleaser/Tags.swift
ZipBuilder/Sources/FirebaseReleaser/main.swift

Port the update tag process from update-versions.sh
Add a verification step to insure that published Firebase tags do not get deleted.

Add update-tags release process

---

ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift

#no-changelog
The first code chunk is a bit complicated to continue supporting the `-templateDir` option while adding the new more powerful `-repoDir` option.
The map suggestion is nice and makes the code much cleaner. Thanks @maksymmalyhin

Address #6747 review comments

---

GoogleUtilities.podspec
GoogleUtilities/CHANGELOG.md
GoogleUtilities/Environment/URLSessionPromiseWrapper/GULURLSessionDataResponse.h
GoogleUtilities/Environment/URLSessionPromiseWrapper/GULURLSessionDataResponse.m
GoogleUtilities/Environment/URLSessionPromiseWrapper/NSURLSession+GULPromises.h
GoogleUtilities/Environment/URLSessionPromiseWrapper/NSURLSession+GULPromises.m
GoogleUtilities/Tests/Unit/Environment/NSURLSession+GULPromisesTests.m
SharedTestUtilities/URLSession/FIRURLSessionOCMockStub.h
SharedTestUtilities/URLSession/FIRURLSessionOCMockStub.m

Promise wrapper for NSURLSession to be used in FIS, GDT and other SDKs

GoogleUtilities: NSURLSession promise extension

---

Firestore/Example/Tests/Integration/FSTDatastoreTests.mm

Xcode 12 changed the XCTest assertions to be macros that no longer implicitly depended on `self`. It seems as if Xcode 12.1 has made -Wunused-lambda-capture part of our default warnings and this breaks Objective-C++ code that lambda captures `self` only for its implicit use with the XCTest macros.
This isn't common, so just suppress the warning by forcing `self` to appear used regardless of whether XCTest assertions reference `self` or not.

Prevent test build errors under Xcode 12.1

---

ZipBuilder/Sources/FirebaseManifest/FirebaseManifest.swift
ZipBuilder/Sources/FirebaseReleaser/Push.swift
ZipBuilder/Sources/FirebaseReleaser/Tags.swift
ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift

- Fix cron test failure from bad logic when `-templateDir` option was set without `-repoDir`
- More usage of Swift filter function
- Correct GoogleUtilities releasing attribute (broken after 7.0.0 RC was built)
#no-changelog

Some Release tooling cleanup

---

ReleaseTooling/Sources/FirebaseReleaser/Tags.swift
ReleaseTooling/Sources/FirebaseReleaser/main.swift

- `pod repo update` before checking the master spec repo for existing tags
- Comments for `--log-only` option
#no-changelog

Address two comments from last week's PRs

---

Package.swift

FirebaseStorageSwift and FirebaseFirestoreSwift continue to be in beta and are marked accordingly for SwiftPM users.
#no-changelog

Missing SwiftPM beta annotations

---

Firestore/CHANGELOG.md
Firestore/core/src/remote/serializer.cc

The root of the issue is that when serializing a singular filter, it is being treated as a unary filter before it is definitively established whether it is a unary filter or a field filter. The leak is caused by always serializing the unary filter's field path field for equality and non-equality filters -- if the filter's value turns out not to be NaN or null, the serialization code switches the filter's type to a field filter without clearing the partially-initialized unary filter. `pb_release` would not free the `unary_filter.field.field_path` member variable because it would consider the object not to be a unary filter.
Also a small refactoring to make the function easier to digest.

Fix a memory leak introduced in #6418

---

Crashlytics/CHANGELOG.md
Crashlytics/run

- Remove handling for the API Key
- Fixes https://github.com/firebase/quickstart-unity/issues/714

Crashlytics update run script to quote all arguments passed

---

FirebaseStorage/CHANGELOG.md
FirebaseStorage/Sources/FIRStorage.m
FirebaseStorage/Sources/FIRStorageDownloadTask.m
FirebaseStorage/Sources/FIRStorageTask.m
FirebaseStorage/Sources/FIRStorageUploadTask.m
FirebaseStorage/Sources/FIRStorageUtils.h
FirebaseStorage/Sources/FIRStorageUtils.m
FirebaseStorage/Sources/FIRStorage_Private.h
FirebaseStorage/Tests/Unit/FIRStorageTests.m
FirebaseStorage/Tests/Unit/FIRStorageUtilsTests.m

GTMSessionsFetchers retry timeout doesn't match the API expectation that our request deadline enforces. This PR relies on the internal logic in GTMSessionsFetcher to estimate what a good GTMSessionsFetcher retryInterval would be given the user specified deadlines.
See also cs/google3/third_party/objective_c/gtm_session_fetcher/Source/GTMSessionFetcher.m;l=3148

Adjust Storage Timeouts to GTM's retry interval

---

ReleaseTooling/Sources/FirebaseReleaser/Push.swift
ReleaseTooling/Sources/FirebaseReleaser/main.swift
scripts/build_zip.sh

Generate commands to publish a release to CocoaPods trunk.
Companion to internal cl/338150153.
Running with 
```
--publish true
--log-only true
--git-root /path/to/firebase-ios-sdk
```
generates
```
pod trunk push --skip-tests --synchronous   ~/.cocoapods/repos/cpdc-internal-firebase/Specs/GoogleUtilities/7.0.0/GoogleUtilities.podspec.json
pod trunk push --skip-tests --synchronous   ~/.cocoapods/repos/cpdc-internal-firebase/Specs/GoogleDataTransport/8.0.0/GoogleDataTransport.podspec.json
pod trunk push --skip-tests --synchronous   ~/.cocoapods/repos/cpdc-internal-firebase/Specs/FirebaseCoreDiagnostics/7.0.0/FirebaseCoreDiagnostics.podspec.json
pod trunk push --skip-tests --synchronous   ~/.cocoapods/repos/cpdc-internal-firebase/Specs/FirebaseCore/7.0.0/FirebaseCore.podspec.json
pod trunk …
```

Add publish option to release tooling

---

Functions/CHANGELOG.md
Functions/Example/IntegrationTests/FIRIntegrationTests.m
Functions/Example/Tests/FIRFunctionsTests.m
Functions/FirebaseFunctions/FIRFunctions+Internal.h
Functions/FirebaseFunctions/FIRFunctions.m
Functions/FirebaseFunctions/Public/FirebaseFunctions/FIRFunctions.h
Functions/README.md

[Googlers: see API review here](https://docs.google.com/document/d/1cSIcGCW2QR1OLHX4RDCVNhpBUolnG6tfNpJBR2pn1aM/edit#)
JS implementation for reference:
https://github.com/firebase/firebase-js-sdk/pull/3825
* Added new unit tests
* See above

Add custom domain support to callable functions

---

FirebaseDynamicLinks/CHANGELOG.md
FirebaseDynamicLinks/Sources/FIRDynamicLinks.m
FirebaseDynamicLinks/Tests/Sample/Podfile

Fixed broken callback to AppDelegate after retrieving a dynamic link during fresh app start.
The AppDelegate call was broken in PR : https://github.com/firebase/firebase-ios-sdk/pull/6517
- Reverting to the old implementation of dynamic link passing to App delegate with changes to remove iOS 9 checks.
- Using new method instead of the deprecated one.
- Clean up in the sample app pod file.

Fixed broken callback to AppDelegate

---

Package.swift

Update SPM Analytics

---

GoogleDataTransport.podspec
GoogleDataTransport/CHANGELOG.md

We already check for warnings in our CI and should avoid causing failures if future versions of Xcode introduce warnings.
More context at https://github.com/flutter/flutter/issues/68813

Stop failing on warnings

---

ReleaseTooling/Sources/FirebaseReleaser/Tags.swift

Only do the safety check (and `pod repo update`) once.
#no-changelog

Speed up retagging

---

ReleaseTooling/Sources/Utils/FileManager+Utils.swift

Last night's zip cron build failed after GoogleUserMessaging(an AdMob dependency) released a pod with a binary xcframework.
#no-changelog

Update zip builder to handle xcframeworks from binary pods

---

ReleaseTooling/Sources/FirebaseReleaser/Tags.swift

Post-release 7.0 merge to master 
Only #6806 is left to merge back
#no-changelog

Post-release 7.0 merge to master 

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm

Remove support for running against Hexa, which we haven't done in years. Integration tests will now assume a local emulator by default.
Once imported into google3, this will make it significantly easier to run integration tests against cls from third-parties because this will be able to use the emulator we're already running rather than requiring us to build hexa again.

Run integration tests against the emulator by default.

---

.github/workflows/firestore.yml
Firestore/core/test/unit/FSTGoogleTestTests.mm

Exposed by GHA updating from Xcode 11.7 to 12.0.1
#no-changelog

Update Firestore macOS build for Xcode 12

---

Firestore/core/src/remote/datastore.cc
Firestore/core/src/remote/datastore.h
Firestore/core/src/remote/stream.cc
Firestore/core/test/unit/remote/datastore_test.cc

Remove usages of "whitelist" in Firestore.

---

FirebaseFirestore.podspec
FirebaseStorage.podspec
FirebaseStorage/CHANGELOG.md
Firestore/CHANGELOG.md
Package.swift

Fix #6850 
It seems that it's not necessary with modern Xcode versions to explicitly link `MobileCoreServices` and its linkage is problematic because it causes build warnings with CocoaPods (but not Swift Package Manager).
- MobileCoreServices is used in FirebaseStorage and FirebaseDatabase, but not Firestore
- Only the FirebaseStorage and Firestore podspecs were specifying it
- We saw no issues from FirebaseDatabase including MobileCoreServices but not adding an explicit linkage
- With Firebase 7 updating to a minimum iOS version of 10, we're seeing build warnings even though the docs say MobileCoreServices is not deprecated until iOS 12.

Remove explicit MobileCoreServices from podspecs

---

FirebaseMessaging/Tests/UnitTests/FIRMessagingPendingTopicsListTest.m

Fix warning building unit tests exposed by GHA moving to Xcode 12
#no-changelog - Unit test build issue only

Fix warning introduced with Xcode 12

---

GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m

Fixes #6855.
- use ephemeral URL session since non of cacheing is required for upload. The ephemeral URL session is "cheaper" to instantiate and use
- lazy initialize the URL session to avoid extra work at pre-main time

GDTCCTUploader: lazy initialize url session, use ephemeral session

---

SymbolCollisionTest/Podfile

Fix #6655 not that a Firebase 7 compatible version of GoogleMLKit has published
#no-changelog

Restore GoogleMLKit to SymbolCollision testing

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
Firestore/core/src/api/query_core.cc
Firestore/core/src/core/field_filter.cc

Porting from [Web](https://github.com/firebase/firebase-js-sdk/pull/3960) and [Android](https://github.com/firebase/firebase-android-sdk/pull/2115).

Allow null/NAN values in filters

---

Gemfile
Gemfile.lock

pod gen 2.0.1 released that fixes the [CocoaPods 1.10.x interoperability issue](https://github.com/square/cocoapods-generate/pull/69)

Back to a released version of pod gen

---

Package.swift

When reading through the Package.swift file I noticed there is inconsistency of platform definitions and there are many unnecessary `.some` optional cases.
I propose this small improvement to unify target definitions and improve readability.

Remove unnecessary some keywords from Package.swift

---

Crashlytics/Shared/FIRCLSConstants.m
FirebaseCrashlytics.podspec

Fix `pod spec lint` issue. Public headers should not be accessed repo-relatively.
Also fixed missed test_spec target updates from 7.0.0 relelase.

Crashlytics build fix

---

FirebaseAuth/Sources/Auth/FIRAuth.m
FirebaseMessaging/Sources/FIRMessagingRemoteNotificationsProxy.m
GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
GoogleUtilities/Tests/Unit/Swizzler/GULAppDelegateSwizzlerTest.m

Since iOS 7 it is possible to execute the code in the background for iOS apps that receive silent push notifications. Once such push (most likely containing the `content-available` flag) is received, if the application is in the background, it has 30 seconds to complete the background activity and tell iOS that it's done by calling the `completion` block. More info [on application(_:didReceiveRemoteNotification:fetchCompletionHandler:) here](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application)
We discovered that on iOS 14 calling the completion block multiple times is leading to a crash. Based on my limited debugging capabilities, it looks like the API is now using dispatch groups to trace the moment when the completion is called, and in the …

FCM: Fix crash on iOS 14 when multiple app delegate completion methods are called

---

Crashlytics/CHANGELOG.md
FirebaseMessaging/CHANGELOG.md
Firestore/CHANGELOG.md
GoogleDataTransport/CHANGELOG.md

We need to update the process for managing Changelogs. In the meantime, here are updates for 7.1.0.

Update Changelogs for 7.1.0

---

FirebaseCore/CHANGELOG.md
FirebaseCore/Sources/FIRApp.m
FirebaseCore/Sources/FIRFirebaseUserAgent.m
FirebaseCore/Tests/Unit/FIRAppTest.m

Fixes #6902.
- defer initialization of Firebase user agent
- move CoreDiagnostics call to a background thread

FIRApp optimize config time

---

scripts/generate_access_token.sh

Suggested workaround for security vulnerability listed at,
https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w
The following error can be spotted in the github workflow logs (example: https://github.com/firebase/firebase-ios-sdk/runs/1382322482?check_suite_focus=true, remote_config(iOS)->"Generate Access Tokens.."),
```
The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

replace set-env with github env file workflow

---

Crashlytics/Crashlytics/Components/FIRCLSContext.m
Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.m
Crashlytics/Crashlytics/DataCollection/FIRCLSDataCollectionArbiter.m
Crashlytics/Crashlytics/FIRCrashlytics.m
Crashlytics/Crashlytics/Helpers/FIRCLSDefines.h
Crashlytics/Crashlytics/Models/FIRCLSSettings.m
Crashlytics/Crashlytics/Settings/FIRCLSSettingsOnboardingManager.m
Crashlytics/Crashlytics/Settings/Operations/FIRCLSDownloadAndSaveSettingsOperation.m
Crashlytics/Crashlytics/Settings/Operations/FIRCLSNetworkOperation.m
Crashlytics/Shared/FIRCLSConstants.h
Crashlytics/Shared/FIRCLSConstants.m
Crashlytics/UnitTests/FIRCLSDataCollectionArbiterTest.m
Crashlytics/UnitTests/FIRCLSSettingsTests.m
FirebaseCrashlytics.podspec

Revert changes in Crashlytics version - as it's causing an issue with the version associated with the crash upload

---

.github/workflows/zip.yml
ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
ReleaseTooling/Sources/ZipBuilder/main.swift
scripts/build_non_firebase_sdks.sh

This should fix #6973. Was accidentally enabled when migrating the argument names.
#no-changelog

Disable build dependencies.

---

GoogleDataTransport.podspec
GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCORLibrary/GDTCORDirectorySizeTracker.m
GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
GoogleDataTransport/GDTTestApp/Bridging-Header.h
GoogleDataTransport/GDTTestApp/EventCleanupPerfTest.swift
GoogleDataTransport/GDTTestApp/app.swift
GoogleDataTransport/GDTTestApp/ios/Main.storyboard
GoogleDataTransport/GDTTestApp/viewcontroller.swift

Fixes #6995. 
- use internal `@autoreleasepool` in path enumeration cycles to ensure memory cleanup on each iteration 
- call `checkForExpirations` only once per storage even if storage associated with several targets
- test app updates to profile the issue
Memory spike reduced from ~150MB to ~2MB for ~20k test events.
Profiler traces available at go/apple-gdt-sdk-issue-6995.

GDT storage cleanup: optimizations for big amount of pending events

---

.travis.yml

Now that we no longer support Xcode10 and GHA is running Xcode 12, use travis for Xcode 11 testing until its turndown at the end of the year.
#no-changelog

Use travis for Xcode 11 testing

---

ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift

Note: this requires Xcode 12.2 to build. Thankfully, if run an older
system it will just ignore the arm64 flag and build it normally.
#no-changelog yet - unsure when we'll be using this.

Add arm64 slice for Catalyst builds.

---

Crashlytics/CHANGELOG.md
FirebaseCrashlytics.podspec

Context:
https://github.com/firebase/firebase-ios-sdk/issues/6882
Believe this is a safe change but going to test just in case.

Crashlytics bump down to iOS 9 Deployment Target

---

Firestore/CHANGELOG.md
Firestore/core/src/local/leveldb_lru_reference_delegate.cc
Firestore/core/src/local/leveldb_lru_reference_delegate.h
Firestore/core/src/local/leveldb_target_cache.cc
Firestore/core/src/local/leveldb_target_cache.h
Firestore/core/src/local/lru_garbage_collector.cc
Firestore/core/src/local/lru_garbage_collector.h
Firestore/core/src/local/memory_lru_reference_delegate.cc
Firestore/core/src/local/memory_lru_reference_delegate.h
Firestore/core/src/local/memory_target_cache.cc
Firestore/core/src/local/memory_target_cache.h
Firestore/core/src/local/target_cache.h
Firestore/core/test/unit/local/leveldb_target_cache_test.cc
Firestore/core/test/unit/local/lru_garbage_collector_test.cc
Firestore/core/test/unit/local/target_cache_test.cc

This works around a crash during LRU by not converting the Target Proto into Target Models, and instead only using the Target ID and the LastListenSequenceNumber for serialization. It is the more complicated version of https://github.com/firebase/firebase-ios-sdk/pull/7026, but it doesn't orphan data on disk. 
Fix: #6721

GC targets without deserializing Target model

---

Crashlytics/CHANGELOG.md
Crashlytics/Crashlytics/Components/FIRCLSHost.h
Crashlytics/Crashlytics/Components/FIRCLSHost.m
Crashlytics/Crashlytics/Components/FIRCLSProcess.c

Crashlytics add support for x86 apps running on Rosetta 2

---

Firestore/core/test/unit/FSTGoogleTestTests.mm

I added case to support tests that are skipped in google test so Xcode does not show them as fails.
I also removed use of deprecated unarchiveObjectWithFile method, however this needs to be tested. 
scripts/check.sh did not show any problems, but I do not know if edited code is being tested anywhere and I was not able to run any google tests which would use the edited code flow (in Xcode GUI, I specified unit tests to run, disabled selected tests, and so on, but each call of the edited method failed because of empty 'filePath' in both code versions).

Googletest - Xcode integration improvements

---

FirebaseAppDistribution/CHANGELOG.md
FirebaseAppDistribution/Sources/FIRFADApiService.m
FirebaseAppDistribution/Tests/Unit/FIRFADApiServiceTests.m

When an error occurs, the response data will be nil. This causes a crash because we are trying to parse the response as JSON. Instead, return a generic error message if the response is nil.
Fixes #6996

[App Distribution] Fix crash caused by response being nil

---

GoogleDataTransport/CHANGELOG.md
GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
GoogleDataTransport/GDTCCTLibrary/Private/GDTCCTUploader.h
GoogleDataTransport/GDTCCTTests/Unit/GDTCCTUploaderTest.m

Prototype reference: https://github.com/FirebasePrivate/firebase-ios-sdk/pull/731

Expose upload URLs so that perf can stop instrumenting these URLs.

---

.github/workflows/auth.yml
FirebaseAuth.podspec
FirebaseAuth/CHANGELOG.md
FirebaseAuth/Tests/Unit/FIRAuthNotificationManagerTests.m
FirebaseAuth/Tests/Unit/FIRAuthTests.m
FirebaseAuth/Tests/Unit/FIRAuthURLPresenterTests.m

The Catalyst cron tests failed last night. See #7024. This fixes that failure and does a few more cleanups.
- Update Auth unit tests for changes from #7050 
- Always run multi-platform unit tests in CI instead of only in cron job
- remove iOS 8 and 9 specific unit testing
- Changelog update for #7050

Fix Catalyst tests for #7050

---

Crashlytics/Crashlytics/Helpers/FIRCLSFCRAnalytics.m

The old logs were too nebulous for customers and devrel.
#no-changelog

Crashlytics improve logging for Analytics integration

---

AppleSilicon.md

This is going to be included in the 7.2 merge but should be merged ahead of time for docs linking to it.

Cherry-pick AppleSilicon instructions.

---

AppleSilicon.md

Right now CocoaPods will treat the `M1` as a beta designation, pulling in `7.X` over `7.X-M1`. The only way at the moment to pull in the proper M1 version is to explicitly specify it. We'll need to look into a way we can do this in a more user friendly way.

Update instructions to ensure M1 version is used

---

README.md

It appears to not be required for every configuration, but probably easier to specify,
as Xcode 12 and cocoapods 1.10 are generally available and will avoid developer
experience surprises 
https://firebase.google.com/support/release-notes/ios#performance-monitoring
Docs only change
Docs only change

docs(README): note Xcode >=12 / cocoapods >= 1.10 required

---

FirebaseInAppMessaging/CHANGELOG.md
FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMRenderingWindowHelper.m

These UIWindow factory methods aren't going to win any beauty contests but this should fix #6803

Use initWithFrame: to create the in-app message window in non-UIScene apps

---

Firestore/CHANGELOG.md
Firestore/core/src/local/leveldb_lru_reference_delegate.cc
Firestore/core/src/local/memory_lru_reference_delegate.cc

`/Users/paulbeusterien/gh6/firebase-ios-sdk/Firestore/core/src/local/leveldb_lru_reference_delegate.cc:150:31: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]`

Fix integer conversion loss warnings for size_t to int

---

.swiftpm/xcode/xcshareddata/xcschemes/Firebase-Package.xcscheme
FirebaseAppDistribution/Sources/FIRAppDistribution.m
FirebaseAppDistribution/Sources/FIRAppDistributionUIService.h
FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
Package.swift
SwiftPMTests/objc-import-test/objc-header.m
SwiftPMTests/objc-import-test/objc-module.m
SwiftPMTests/swift-test/main.swift

This reverts #7091 and solves the AppDistro macOS/tvOS test failures by adjusting the tests and test targets instead of the libraries themselves.
Also add similar platform based import testing for Analytics.

Manage platform dependent tests in test targets

---

.github/workflows/datatransport.yml

This ensures the iPhone 11 Pro simulator is available.

Use Xcode 12.0 for watchOS test app

---

.github/workflows/spm.yml
Package.swift
SwiftPMTests/objc-import-test/objc-header.m
SwiftPMTests/objc-import-test/objc-module.m
SwiftPMTests/swift-test/main.swift

By specifying iOS in the package manifest, it includes Analytics but the
Analytics xcframework doesn't have a Catalyst slice.
#no-changelog

Remove Analytics Catalyst tests.

---

FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.h
FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.m
FirebaseDynamicLinks/Sources/FIRDynamicLinks+FirstParty.h
FirebaseDynamicLinks/Sources/FIRDynamicLinks.m
FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLinks.h
FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinkNetworkingTests.m
FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m

- **Description**: Dynamic links can be validated against a block/allow list, which is defined server side in the Firebase Console. This verification should apply to both short and long dynamic links, and be supported by both iOS and Android SDKs.
- **What’s expected**: It’s expected that both iOS and Android will verify both kinds of dynamic link, and if it passes the verification rules defined server side, allow the link to be processed.
- **What’s observed**: On iOS, long dynamic links are not verified, and it’s possible for a link that doesn’t pass the "allowed link" rules to be treated as verified. Short dynamic links are verified, that’s not an issue. This also isn’t an issue on Android, which verifies both short and long dynamic links.
- **Proposed solution**: Ensure the error …

Manually created dynamic links should be subject to allowed/blocked check

---

ReleaseTooling/Sources/ZipBuilder/CarthageUtils.swift
ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift

- Add Info.plist to all static framework builds since SPM needs them in binary xcframeworks
- Fix the version in generated Info.plist's
- Simplify shell command logging to eliminate or make more rare a race condition crash
Tested by verifying zip and Carthage directory diffs
#no-changelog

Info.plist fixes

---

ReleaseTooling/Sources/ZipBuilder/CarthageUtils.swift

Carthage does not support xcframeworks, so disable Carthage release generation for CocoaPods that wrap a binary xcframework. This currently disables AdMob and FirebasePerformance.

Don't generate Carthage for xcframeworks

---

Firestore/core/src/util/secure_random_openssl.cc

This is masked when using OpenSSL (which includes it for us) but causes the build to be broken with BoringSSL.

Add missing #include <cstdlib>, required for abort().

---

.github/workflows/performance-integration-tests.yml

Currently integration test is triggered on private GitHub repo only. 
As we move forward to public GitHub repo, adding a new workflow to trigger integration test on master branch of public repo only.
We keep the private repo integration test for now until we make the first release from public GitHub repo.

Add integration test for Firebase Performance on Public repository

---

FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m

Noticed in https://stackoverflow.com/questions/65227891/where-to-find-c-nserror-userinfo-dictionary
#no-changelog

Fix typo in Auth Error string

---

Crashlytics/Crashlytics/Models/FIRCLSInternalReport.h
Crashlytics/Crashlytics/Models/FIRCLSInternalReport.m
Crashlytics/Shared/FIRCLSConstants.h
Crashlytics/Shared/FIRCLSConstants.m

These were extra references that confuse us into thinking this value is still needed, when it's not.
#no-changelog

Crashlytics move more references to orgID

---

Crashlytics/Crashlytics/Models/FIRCLSInternalReport.h
Crashlytics/Crashlytics/Models/FIRCLSInternalReport.m
Crashlytics/Shared/FIRCLSConstants.h
Crashlytics/Shared/FIRCLSConstants.m

Reverts firebase/firebase-ios-sdk#7150
Issues in CI: https://github.com/firebase/firebase-ios-sdk/issues/7154
#no-changelog

Revert "Crashlytics move more references to orgID"

---

FirebaseDynamicLinks.podspec
FirebaseDynamicLinks/CHANGELOG.md
FirebaseDynamicLinks/Sources/FIRDynamicLinks.m
FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m
Package.swift

The 7.3.0 release had a regression where an FDL callback could occur off the main thread.
This prepares a 7.3.1 release with the fix for the CocoaPods and SPM distributions that I propose to publish on Tuesday.

7.3.1 release for FDL regression fix

---

GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m

If an upload coordinator gets created during `+load` calls, it can end up running its immediately, while +load calls are still running. It's generally a bad idea to be splitting off threads while +load calls are still running.
The upload coordinator checks every 30 seconds, and doesn't really need to run right away. Since it's easy to transitively create an upload coordinator from other calls that happen during +load, we'll just push off the initial run of the timer slightly. That makes it less likely to interfere (or deadlock) with other load calls.
See #7171 for an example of a problem solved by this change.
* If …

Delay GDTCORUploadCoordinator timer initial run

---

README.md

Provide an alternative approach for Catalyst development when a Signing Certificate is not available
#no-changelog

Alternative Catalyst development option

---

Firestore/core/src/remote/firebase_metadata_provider.cc
Firestore/core/src/remote/firebase_metadata_provider.h

VS2015 does not support declaring `static constexpr char[]` members of classes.
#no-changelog

Fix FirebaseMetadataProvider under VS2015

---

ReleaseTooling/README.md

This is the first of a series of ZipBuilder PRs that will be pushed unreviewed to the `zip-v3` branch where it will wait for a review before merging to master.
- Update instructions for Xcode usage
- Clarify the difference between `--zip-pods` option and building a Firebase distribution
- Make it clearer that Carthage building is only supported for Firebase distributions

Zip Builder README fixes

---

.github/workflows/zip.yml
ReleaseTooling/README.md
ReleaseTooling/Sources/ZipBuilder/main.swift
scripts/build_non_firebase_sdks.sh
scripts/build_zip.sh

Make finding the repo root automatic to eliminate the need to specify the `--repo-dir` option.

Eliminate repo-dir option

---

ReleaseTooling/DEVELOP.md
ReleaseTooling/README.md
ReleaseTooling/Sources/ZipBuilder/main.swift

Split README.md into DEVELOP.md so that README.md is focused on users and DEVELOP.md is on development and Firebase release management.
Also, makes a few tweaks to the `--help` output.

Zip docs organization

---

ReleaseTooling/README.md
ReleaseTooling/Sources/ZipBuilder/main.swift

Making it easier to use the zip-builder from the command line. 
Now the common use case should be one option: `--pods <list of pods to build>
#no-changelog

Add --pods option

---

ReleaseTooling/Sources/ZipBuilder/main.swift

`Binaries` is more descriptive than `staging`
#no-changelog

Rename top level zip directory

---

FirebaseStorage/CHANGELOG.md
FirebaseStorage/Sources/FIRStorageReference.m
FirebaseStorage/Tests/Unit/FIRStorageListTests.m

Fix #7197 
Adds missing return.
Adds missing `listAll` unit test (that fails without this change)

Prevent 2nd listAll callback

---

Example/InstanceID/Tests/FIRInstanceIDTest.m
Firebase/InstanceID/CHANGELOG.md
Firebase/InstanceID/FIRInstanceID.m
FirebaseMessaging/Apps/Shared/ContentView.swift
FirebaseMessaging/Apps/Shared/SceneDelegate.swift

When messaging updates token and notifying InstanceID, instanceID should first check to see the token from Messaging is different than the one in local cache or in the database. 
This extra check helps reduce storage writing in the future when we remove InstanceID and handle token completely from Messaging.

Check token is different from cache and storage before  updating it 

---

Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
FirebaseCore.podspec
FirebaseCore/Sources/FIRApp.m
FirebaseCore/Sources/Private/FIRAppInternal.h
FirebaseCore/Tests/Unit/FIRAnalyticsConfigurationTest.m
FirebaseCore/Tests/Unit/FIRAppTest.m
FirebaseCoreDiagnostics.podspec

- replace deprecated OCMock methods by notification XCTExpectations
- remove unused `kFIRAppDiagnosticsNotification` internal constant

Core: fix and cleanup notification center tests

---

Firestore/Example/FuzzTests/FuzzingResources/Serializer/Corpus/ConvertTextToBinary.sh
Firestore/Example/LibFuzzer.podspec

Now that the LLVM project has completed its migration to git, the svn checkouts are now failing.
Also fix an incidental issue that arose while testing locally--I have homebrew installed in `$HOME/homebrew` and the fuzzer build was failing to find `protoc` as a result.

Migrate libFuzzer from svn to git

---

FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/AuthProvider/OAuth/FIROAuthProvider.m
FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m
FirebaseAuth/Tests/Unit/FIROAuthProviderTests.m
FirebaseAuth/Tests/Unit/FIRPhoneAuthProviderTests.m

After OAuth provisioning is deferred, the client ID may still be provided in the plist file after Google Sign-in is enabled. Therefore, the presence of the client ID itself is not enough to determine whether to use the client ID or the app ID in generic IDP and phone auth reCAPTCHA fallback flows. Instead, we need to check first if the reverse client ID is registered as a custom URL scheme.

Check if reverse client ID is a registered URL scheme before setting callback scheme

---

FirebaseAuth/Sources/Backend/RPC/FIREmailLinkSignInRequest.m

Similar to https://github.com/firebase/firebase-ios-sdk/pull/6142/files

Enable multi tenancy for email link sign in

---

Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift

Prompted by #7242.
This shows that property wrappers like `@DocumentID` can be used in custom Codable methods, and produce results essentially identical to `testSelfDocumentID`.
#no-changelog

Verify that @DocumentID works with custom Codable methods.

---

GoogleDataTransport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.m

Open source version of cl/350236632.
#no-changelog

GDT test server: stop server on dealloc only if running

---

SwiftPackageManager.md

Add instructions for where to find Crashlytics run scripts for Swift Package Manager installation.

Update SwiftPackageManager.md with instructions for Crashlytics SPM

---

FirebasePerformance.podspec

Confirmed that this fix enables publishing the podspec:
```
$ pod repo push --skip-tests --use-json  cpdc-internal-firebase  FirebasePerformance.podspec --sources=sso://cpdc-internal/firebase.git,https://cdn.cocoapods.org
Validating spec
-> FirebasePerformance (7.4.0)
- WARN  | url: The URL (https://twitter.com/Firebase) is not reachable.
- NOTE  | xcodebuild:  note: Using new build system
- NOTE  | xcodebuild:  note: Building targets in parallel
- NOTE  | [iOS] xcodebuild:  note: Planning build
- NOTE  | [iOS] xcodebuild:  note: Constructing build description
- NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in …
```

Add missing source to Perf podspec

---

FirebaseInAppMessaging/CHANGELOG.md

I'm recommending deferring announcing FIAM tvOS because of issues like #7271 and until it is added to CI

Pull FIAM tvos from 7.4 release notes

---

SwiftPackageManager.md

Add a missing '/' into the Run Script for Swift Package Manager installation. I needed it for my build.

Small text change to SwiftPackageManager.md

---

Firestore/Source/API/FIRQuery.mm

Firebase introduced `arrayContainsAny` and `queryWhereField:in` in 2019. This PR adds support to NSPredicate for these queries

Support NSPredicate CONTAINS and IN with new filter queries

---

Firebase.podspec

When the Firebase pod was installed and other Firebase pods installed directly (not via subspec with `Firebase/`, the Firebase module was not getting installed for tvOS and macOS. 
This should be a rare bug in practice, but it was exposed by a crash in the ZipBuilder when Firebase.h was not installed after a tvOS installation.
#no-changelog

Firebase pod fix for tvOS and macOS

---

ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift

FIAM tvOS support is pending CI configuration.
Also, the zip builder needs to add support for different resources for different platforms. FIAM has a different storyboard for tvOS and iOS.

Revert "Enable FIAM tvos slice in zip build (#7261)"

---

.travis.yml

Remove GDT from travis testing since it has been getting especially flaky with timeout failures in advance of the travis turndown.
#no-changelog

Remove GDT from travis

---

Firestore/core/src/model/transform_operation.cc

The previous implementation only deleted the first instance of the ArrayRemove element appearing in the document array. This PR removes all appearances of the ArrayRemove element from the document array.
#no-changelog

Iterate through all elements of target array for FieldValue::ArrayRemove

---

ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift

Workaround for crash exposed by different tvOS installation. Fixed in #7284 
Keep the workaround longer term to be conservative about preferring the installation form the first platform (iOS) instead of the last (tvOS).
#no-changelog

ZipBuilder workaround

---

Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
FirebaseCore/CHANGELOG.md

This was previously used to help determine if Firebase should switch to
using dynamic frameworks, but now developers have the option themselves.
Fixes #7310

Remove dynamic framework count from diagnostics.

---

Firestore/Example/Tests/Integration/API/FIRQueryTests.mm

This triggers the `-Wobjc-dictionary-duplicate-keys` warning, causing the compilation to fail when `-Werror` is used. Introduced in #6871.
#no-changelog

Fix a duplicate key in test data

---

Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m

Hello. We see the code referenced here blocking the main thread at startup and causing our watchdog system to kill the app. Synchronously waiting for filesystem operations to complete from the main thread can be safely removed.

Twitter dont block main on file ops

---

.github/workflows/release.yml
.github/workflows/spm.yml
.github/workflows/symbolcollision.yml
.github/workflows/zip.yml

SPM tests should not run when `GoogleAppMeasurement.podspec.json` or other `Google` files are changed.
Changing `Gemfile` should trigger all workflows.

More GHA consistency

---

Firestore/Protos/CMakeLists.txt

CMAKE_CROSSCOMPILING is the standard variable to be set when you are building for a platform that is incompatible with the one you are running on. Checking if this is set allows Firestore to use external protoc in the case of cross-compiling (e.g. arm64 mac builds on an x64 mac) in addition to the current cases of building for mobile.

When building protoc, also check if CMAKE_CROSSCOMPILING is set.

---

FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/Backend/FIRAuthBackend.m

Allow http schemes when using the auth emulator

---

FirebaseCombineSwift/README.md
FirebaseCombineSwift/Sources/Auth/Auth+Combine.swift
FirebaseCombineSwift/Sources/Auth/MultiFactorResolver+Combine.swift
FirebaseCombineSwift/Sources/Auth/PhoneAuthProvider+Combine.swift
FirebaseCombineSwift/Tests/Unit/Auth/SignInWithCredentialTests.swift
FirebaseCombineSwift/Tests/Unit/FirebaseCombineSwift-unit-Bridging-Header.h

Proposal for Combine support to authenticate with Firebase using third-party credentials.
```swift 
func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error?) {
// ...
if let error = error {
// ...
return
}
guard let authentication = user.authentication else { return }
let credential = GoogleAuthProvider.credential(withIDToken: authentication.idToken,
accessToken: authentication.accessToken)
Auth.auth()
.signIn(withCredential: credential)
.mapError { $0 as NSError }
.tryCatch(handleError)
.sink { /* ... */ } receiveValue: {  /* ... */  }
.store(in: &subscriptions)
}
private func handleError(_ error: NSError) throws -> AnyPublisher<AuthDataResult, Error> {
guard isMFAEnabled && error.code == AuthErrorCode.secondFactorRequired.rawValue
else { throw error } …
```

Combine Support: Sign in with 3rd party credentials

---

Crashlytics/generate_project.sh

When I pod gen, it gives me this error. Updating our main script to pod gen to remove watchOS.
```
Generating FirebaseCrashlytics in `gen/FirebaseCrashlytics`
Creating stub application
Writing Podfile
Installing...
[!] The platform of the target `App-watchOS` (watchOS 6.0) is not compatible with `FirebaseCrashlytics/unit (7.4.0)`, which does not support `watchOS`.
```

Remove watchOS for Crashlytics Pod Gen

---

FirebaseDatabase/Sources/FIRDatabaseReference.m
FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDatabaseReference.h

The goal is to have the overload show up on the API documentation. This matches all other overloads.

Add getData overload to DatabaseReference

---

ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
ReleaseTooling/Sources/FirebaseManifest/Pod.swift
ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift
ReleaseTooling/Sources/FirebaseReleaser/Tags.swift
ReleaseTooling/Sources/ZipBuilder/CocoaPodUtils.swift

Now that GoogleUtilities and GoogleDataTransport have their own repos and release processes
#no-changelog

Remove ReleaseTooling special casing for non-Firebase pods

---

.github/workflows/crashlytics.yml
Crashlytics/UnitTests/FIRCLSProcessReportOperationTests.m

Fixes https://github.com/firebase/firebase-ios-sdk/issues/7154 so we can run macOS nightly unit tests.
- Root cause was a previously deleted test happened to do the teardown and cleanup that this test depended on: https://github.com/firebase/firebase-ios-sdk/commit/5c1a83dd0f7d24b26e5c7174de9f291a8976a191#diff-9e4e9c85fb337baa24ba87256cddd232a6d714bbea09cf7256eed27170928fd0L56-L57
#crashfixit2021 #no-changelog

Fix Crashlytics macOS cron test

---

.github/workflows/release.yml
.github/workflows/zip.yml
scripts/build_non_firebase_sdks.sh
scripts/create_spec_repo/Sources/SpecRepoBuilder/main.swift

The nightly tests were building the FirebaseSwift pods for Firebase 6.x because they weren't updated to include the beta version specification now required with Firebase 7.x.
This went unnoticed until a FirebaseUI regression firebase/FirebaseUI-iOS#936 occurred yesterday exposing this.
Fix #7389

Fix build_non_firebase_sdks.sh for 7.x Swift pods

---

AppleSilicon.md

7.5.0 unified the FirebaseAnalytics M1 and standard CocoaPods distribution into a single xcframework that supports both.

Update Apple Silicon instructions

---

Package.swift

Fix #7405 
Initially run tests with "test" tags in GoogleUtilities and GoogleAppMeasurement repos before updating their versions.
If tests pass, planning to push to release-7.5 branch and tag a 7.5.1 release just for SPM distro.
See also https://github.com/google/GoogleUtilities/pull/7 and https://github.com/google/GoogleAppMeasurement/pull/3

Update to namespaced GoogleUtilities

---

FirebaseInAppMessaging/Resources/FIRInAppMessageDisplayStoryboard.storyboard

Fixes an issue raised in #7334.

Background view for card message should clip subviews to its bounds

---

ReleaseTooling/Sources/ZipBuilder/ResourcesManager.swift

Fix #7414
The zip distribution included both matching `GoogleSignIn.bundle` and `GoogleSignIn.bundle.bundle`
#no-changelog

Stop creating redundant bundle

---

FirebaseAuth/Sources/Utilities/FIRAuthDefaultUIDelegate.h

This needs to be TARGET_OS_WATCH (also see the corresponding .m file, where it actually already is TARGET_OS_WATCH)
#no-changelog

Fix import for watchOS

---

FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
FirebaseInAppMessaging/Tests/Unit/FIRIAMDisplayExecutorTests.m

[Closes #7309]
* Added an extra check on `messageDisplaySuppressed`’s value just before the message is displayed on screen
* Added the `testNoRenderingIfMessageDisplayIsSuppressedDuringImageLoading` test method that covers the scenario where `messageDisplaySuppressed` is set to `YES` after the message’s image started loading but before the message is displayed
* Added support for async image loading in `FIRIAMDisplayExecutorTests`, and a new test message `m6` whose image is loaded asynchronously; existing test messages’ behavior is left unchanged

[#7309] Fixed messageDisplaySuppressed Ignored on Slow Networks

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
Firestore/core/src/util/async_queue.cc

If a user calls terminate and immediately disposes their reference to Firestore, it's possible that while termination is in process, the last remaining reference (more precisely, shared pointer) to Firestore is in a listener. When that listener is destroyed as part of the termination, it leads to `api::Firestore` being destroyed. Importantly, termination happens on the worker queue. The destructor of `api::Firestore` calls `Dispose` which presumes it's not called from the worker queue and tries to enqueue work, leading to a failing assertion and a crash.
The solution is simply to remove the sequential order checks when the queue enters/is in restricted mode. There is a legitimate case where the Firestore destructor can run on the worker queue, as the original issue shows. The complexity …

Fix a crash that happens when Firestore is being terminated when the last shared pointer to it is in a listener

---

.github/workflows/zip.yml
scripts/build_zip.sh

An attempt to add a [manual trigger](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) for zip GHA workflow. 
I was not able to test the trigger itself as the "Run workflow" button didn't appear for me. I guess the change has to land to the default branch to be picked up by GHA.

GHA zip workflow: add manual trigger

---

.github/workflows/test_coverage.yml

Previously in post submit, pod test jobs will not run since their dependency job, `check`, does not run and their `if` conditions are overridden by `needs`.  This was discussed [here](https://github.com/actions/runner/issues/491). To make `if` with a higher priority than `needs`, [Job status check functions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions) are added here. `always()` here will omit the result of `needs` jobs but will wait until dependency jobs finish.

Update to enable pod tests in post submit tests.

---

ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift

Restore manifest version until 7.6.0 release publishes.
The version update needs to be in the release branch only until we make the release process fully public to keep the nightly zip.yml running.

Restore master manifest version

---

Crashlytics/CHANGELOG.md
Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.m

Fix a race condition involving binary images being changed.

---

FirebaseInAppMessaging/CHANGELOG.md
FirebaseInAppMessaging/Resources/FIRInAppMessageDisplayStoryboard.storyboard
FirebaseInAppMessaging/Sources/DefaultUI/Banner/FIRIAMBannerViewController.m
FirebaseInAppMessaging/Sources/DefaultUI/Card/FIRIAMCardViewController.m
FirebaseInAppMessaging/Sources/DefaultUI/ImageOnly/FIRIAMImageOnlyViewController.m
FirebaseInAppMessaging/Sources/DefaultUI/Modal/FIRIAMModalViewController.m

- Announces the in-app message title over VoiceOver at display time
- Improves accessibility labels
- Announces close button as the last accessible VoiceOver element (so it's easier to find)

Better VoiceOver experience for in-app messages

---

FirebaseDatabase/CHANGELOG.md
FirebaseDatabase/Sources/third_party/SocketRocket/FSRWebSocket.m

Fix for cl/355486726 - g3 build error:
```
error: variable length array used [-Werror,-Wvla]
uint8_t buffer[bufferSize];
^~~~~~~~~~
```

RTDB FSRWebSocket: suppress diagnostic error

---

HeadersImports.md
Interop/FirebaseComponentSystem.md

As we made header searching more consistent between CocoaPods and SPM, private headers imported from other Firebase libraries are now specified with the CocoaPods `source_files` attribute.
Clarify that C++ internal headers should still be specified with `preserve_paths` to avoid namespace collisions in the generated client Xcode workspace.
Note that this has the downside of losing navigation to the header by filename in Xcode for which the workaround is using the file type.

Improve internal header documentation

---

.github/workflows/generate_issues.yml
.github/workflows/mlmodeldownloader.yml

- Use secret
- Static frameworks instead of modular headers
- Move next to similar regular pod lib lint tests
- Enable issue reporting for failures

Fix Downloader nightly

---

Crashlytics/Crashlytics/Components/FIRCLSUserLogging.h
Crashlytics/Crashlytics/Components/FIRCLSUserLogging.m
Crashlytics/Crashlytics/FIRCrashlytics.m
Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h
Crashlytics/UnitTests/FIRCLSLoggingTests.m

The key/value logging API atomically writes out changes to
disk. If you set several keys and values consecutively, this
generates a large number of file io operations.
Add an API that accepts an NSDictionary of keys and values
that are written together, reducing the number of file io
ops.

Add Crashlytics bulk key/value logging API

---

ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift

Fix #7500 
The version update did not end up correct after 7.6.0 published. Restoring here to fix the nightly tests.

Update Firebase version in zip manifest

---

Crashlytics/Crashlytics/Components/FIRCLSProcess.c
Crashlytics/Crashlytics/Models/FIRCLSSymbolResolver.m

These logs were either ill-formatted, or went to console log (particularly "Image not found", which shows up way too much).
#no-changelog

Crashlytics move some noisy logs out of devs logs

---

Carthage.md
ReleaseTooling/Sources/ZipBuilder/CarthageUtils.swift

Carthage Protobuf special casing is no longer needed now that only one Firebase library depends upon it (Performance).
Also update the version info in the Carthage docs.

Remove Carthage Protobuf special casing

---

.gitignore
FirebaseMLModelDownloader/Sources/ModelDownloader.swift
FirebaseMLModelDownloader/Sources/ModelFileManager.swift
FirebaseMLModelDownloader/Tests/Integration/ModelDownloaderIntegrationTests.swift

- fix call handlers on the main queue
- fix `listDownloadedModels` method for real devices
- use a subfolder named "com.firebase.FirebaseMLModelDownloader" to store models
- `getModel()`: fail fast with a specific error when model name is empty

ML model downloader fixes

---

.github/workflows/remoteconfig.yml

This fixes the fork CI issue for the remoteconfig/remoteconfig workflow that showed up in #7507.  The failure still exists for the `test_coverage` workflow. See #7476
#no-changelog

Disable token test on forks

---

.github/workflows/installations.yml
.github/workflows/mlmodeldownloader.yml

Fixes issues visible at https://github.com/paulb777/firebase-ios-sdk/actions?query=event%3Aschedule++
- MLDownloader and Installations run cron tests on a forked repo
- Some MLDownloader tests that require secrets were running on a fork
The failure still exists for the test_coverage workflow. See #7476

Don't run cron jobs on forks

---

.github/workflows/abtesting.yml
.github/workflows/remoteconfig.yml
Example/watchOSSample/Podfile
Example/watchOSSample/SampleWatchAppWatchKitExtension/ExtensionDelegate.swift
FirebaseABTesting.podspec
FirebaseABTesting/CHANGELOG.md
FirebaseRemoteConfig.podspec
FirebaseRemoteConfig/CHANGELOG.md
README.md

ABTesting is a hard dependency so enable it as well.
Testing: I'm able to get config value without any changes using the watchOS sample app.

Enable watchOS for Remote Config and ABTesting

---

ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift

Fix #7519 
Verified by GHA manual trigger at https://github.com/firebase/firebase-ios-sdk/actions/runs/563946483
#no-changelog

Fix Swift module map regression

---

FirebaseCombineSwift/Sources/Auth/User+Combine.swift
FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift
FirebaseCombineSwift/Tests/Unit/Credentials.swift

Associates a user account from a third-party identity provider with this user.
```swift
Auth().currentUser
.link(withCredential: credential)
// Handle completion
} receiveValue: { authResult in
// Handle AuthDataResult 
}
```

Combine Support: Link user from a third-party provider

---

Package.swift

Firebase was updated to version 7.6.0 but the SPM version was still on 7.5.0, so I opened this PR to fix it.

Update Firebase SPM version to 7.6.0

---

Package.swift

Cherry-pick #7531 to fix the version logged with Swift Package Manager in 7.6.0
After merging, we'll need to move the 7.6.0 tag to finish the fix.

Update Firebase SPM version to 7.6.0 (#7531)

---

FirebaseCombineSwift/Sources/Auth/User+Combine.swift
FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift

Renews the user's authentication tokens by validating a fresh set of credentials supplied by the user  and returns additional identity provider data.
```swift
Auth().currentUser
.reauthenticate(with: googleCredential)
/* Handle completion */
} receiveValue: { authResult in
/* Handle result */
}
```

Combine Support: Renew the user authentication

---

Functions/CHANGELOG.md
Functions/Example/Tests/FIRFunctionsTests.m
Functions/FirebaseFunctions/FIRFunctions.m

* Fixes #7537
* Fixes #7538
* Updated unit tests
* This technically could be considered a breaking change however the original implementation was a bug. The API is meant to be `useEmulator("locahost", 1234)` but right now it requires `useEmulator("http://localhost", 1234)`

Fix FIRFunctions.useEmulatorWithHost scheme

---

FIRDynamicLinkTest.m
FirebaseDynamicLinks/CHANGELOG.md
FirebaseDynamicLinks/Sources/FIRDynamicLink.m
FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLink.h
FirebaseDynamicLinks/Tests/Sample/FDLBuilderTestAppObjC/AppDelegate.m
FirebaseDynamicLinks/Tests/Sample/FDLBuilderTestAppObjC/SceneDelegate.m

Adding "utmParametersDictionary" api to FIRDynamicLink.
This new property will enable 3p developers to fetch the Utm parameters associated with a Firebase Dynamic Link.
Related Issue: https://github.com/firebase/firebase-ios-sdk/issues/6730
API Review Doc : https://docs.google.com/document/d/1NDBjiuCQEs3vnaPGfYKK2cdvJMIsJqukRtrZf8wsWCk (Approved)

Adding "utmParametersDictionary" api to FIRDynamicLink

---

FirebaseABTesting/CHANGELOG.md

ABTesting needs analytics to function, and analytics currently doesn't work on watchOS. So clarify that in the chagnelog.

update abtesting changelog

---

.github/workflows/zip.yml

Use Xcode 12.2 to build the zip and built the first real RC via GHA. See https://github.com/firebase/firebase-ios-sdk/actions/runs/579356249. 
I noticed that FirebaseAnalytics hasn't been built for Carthage since 7.4.0 and will follow up on that in a subsequent PR.
#no-changelog

Automate Release zip build

---

FirebaseCore/Sources/FIRApp.m

This isn't actually needed since the class won't be available on platforms it doesn't support.
#no-changelog

Remove unnecessary platform check

---

FirebaseMLModelDownloader.podspec
FirebasePerformance.podspec
FirebasePerformance/CHANGELOG.md
FirebasePerformance/Sources/FPRClient.m
FirebasePerformance/Sources/FPRProtoUtils.h
FirebasePerformance/Sources/FPRProtoUtils.m
FirebasePerformance/Tests/Unit/FPRProtoUtilsTest.m
FirebaseSegmentation.podspec

Follow up fix for #6557 for Performance, MLModelDownloader, and Segmentation, that were not yet on master when the original 7.0.0 update was made.
Also fix exposed Catalyst build problem with mobile connectivity header. 
Fix #7569

Completely stop forcing static frameworks

---

FirebaseCombineSwift/Sources/Auth/User+Combine.swift
FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift

Disassociates a user account from a third-party identity provider with this user.
```swift
authResult.user
.unlink(fromProvider: PhoneAuthProviderID)
/* Handle completion */
} receiveValue: { user in
/* Handle user */
}
```

Combine Support: Disassociate user account from 3P IdP

---

scripts/check_imports.swift

As discussed in https://github.com/firebase/firebase-ios-sdk/pull/7547#discussion_r580442313, this patch makes sure that bridging headers may use angle-bracket imports.
#no-changelog

Treat bridging headers as test-related

---

ReleaseTooling/Sources/FirebaseManifest/Pod.swift
ReleaseTooling/Sources/FirebaseReleaser/Push.swift

- Now that they contain xcframeworks, Analytics pods no longer need to `--skip-import-validation`
- Fix the staging location path
#no-changelog

Publish command updates

---

Example/InstanceID/Tests/FIRInstanceIDTest.m
FirebaseMessaging/CHANGELOG.md

Also update the messaging changelog to be in sync with g3.

Cleanup bad uses of andDo blocks

---

Crashlytics/Crashlytics/Components/FIRCLSUserLogging.m

Adds the number of keys truncated to the log messages when more than 64 custom keys are logged.
#no-changelog

Log number of custom keys truncated

---

.github/workflows/abtesting.yml
.github/workflows/analytics.yml
.github/workflows/appdistribution.yml
.github/workflows/auth.yml
.github/workflows/cocoapods-integration.yml
.github/workflows/core-diagnostics.yml
.github/workflows/core.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firebasepod.yml
.github/workflows/firestore.yml
.github/workflows/functions.yml
.github/workflows/google-utilities-components.yml
.github/workflows/inappmessaging.yml
.github/workflows/installations.yml
.github/workflows/instanceid.yml
.github/workflows/messaging.yml
.github/workflows/remoteconfig.yml
.github/workflows/segmentation.yml
.github/workflows/spm.yml
.github/workflows/storage.yml
.github/workflows/symbolcollision.yml

We've seen failures due to exceeding runner quotas like in https://pipelines.actions.githubusercontent.com/j2BGE4MixlTkonbjtnV0hDUtoNpdgVvQlS8sb5i8v29RVeS3Ql/_apis/pipelines/1/runs/36340/signedlogcontent/127?urlExpires=2021-02-25T15%3A55%3A15.1079359Z&urlSigningMethod=HMACV1&urlSignature=5sLdJesREUk770wMXDma%2Bf22B0fzG6Jev6G3erARncU%3D
```
2021-02-25T07:31:10.2366438Z ##[section]Starting: Request a runner to run this job
2021-02-25T07:31:11.6955148Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'macos-latest'
2021-02-25T07:31:11.7553471Z Can't find any online and idle self-hosted runner in current repository's organization/enterprise account that matches the required labels: 'macos-latest'
2021-02-25T07:31:11.9342577Z The agent …
```

Spread out cron jobs

---

CoreOnly/Sources/Firebase.h
FirebasePerformance/CHANGELOG.md

Firebase Performance does not require inclusion of Analytics. Fixes #7487

Remove the warning when Analytics is not included

---

Firestore/core/src/util/firestore_exceptions.h

This is a port of CL 354562822. Original description: "It seems as if policy checks in Abseil fail on Android even when compiling against non-STLPort C++ runtimes."
#no-changelog

Don't use Abseil exceptions checks on Android

---

FirebaseRemoteConfig/CHANGELOG.md
FirebaseRemoteConfig/Sources/RCNConfigFetch.m
FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m

Currently `updateExperimentsWithResponse` is being called on fetches for all namespaces, causing issues with experiment exposures as `fireperf` fetch requests are incorrectly updating experiment data
Tracked internally in b/179461119

Only update experiments for firebase namespace

---

FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift

Fix `testLinkAndRetrieveDataProviderAlreadyLinked`

Fix for the failed test testLinkAndRetrieveDataProviderAlreadyLinked

---

FirebaseCombineSwift/Sources/Auth/User+Combine.swift
FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift

```swift
user.sendEmailVerification(with: actionCodeSettings)
/* Handle completion */
} receiveValue: { _ in
/* No type */
}
```
```swift
user.sendEmailVerification()
/* Handle completion */
} receiveValue: { _ in
/* No type */
}
```

Combine support to send verification email

---

Crashlytics/CHANGELOG.md
Crashlytics/Crashlytics/Controllers/FIRCLSExistingReportManager.h
Crashlytics/Crashlytics/Controllers/FIRCLSExistingReportManager.m
Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m
Crashlytics/Crashlytics/Private/FIRCLSExistingReportManager_Private.h
Crashlytics/UnitTests/FIRCLSExistingReportManagerTests.m
Crashlytics/UnitTests/FIRCLSReportManagerTests.m

If the developer turns automatic collection off, they run the risk of filling up disk space with unsent reports if they never call send/deleteUnsentReports. In addition, having too many unsent reports can cause performance problems when trying to find the newest unsent report.
This change limits the number of unsent reports to 4 to match Android: https://github.com/firebase/firebase-android-sdk/blob/e65f4876ff61b5791986c249b21cb094c37bd29e/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonConstants.java#L61

Limit the number of unsent reports on disk to prevent disk filling

---

Firestore/core/src/local/leveldb_persistence.cc

This triggers a warning in newer versions of GCC and causes compilation to fail with `-Werror`.
#no-changelog

Fix a signed/unsigned comparison

---

Firestore/core/src/remote/grpc_root_certificates_generated.h
Firestore/core/src/util/secure_random_arc4random.cc
Package.swift
scripts/cpplint.py

Fix #7552 
The future Apple toolchain is more strict about a few things that impact Firestore and its dependencies:
- Requires usage of stdlib.h instead of cstdlib for some declarations like https://github.com/google/boringssl/commit/061a7f5596c4125fc4bead14ebb37cf51d2ae627
- Requires all headers specified by SPM to build (wasn't the case previously and the packages included some test headers)
- More strict about C++ headers being in extern C - see https://github.com/firebase/leveldb/commit/e4e8ab44a2781a3656b4b5852e71c07fd18fecfa
- Associated PRs
- https://github.com/firebase/leveldb/pull/2
- https://github.com/firebase/boringSSL-SwiftPM/pull/1
- https://github.com/firebase/abseil-cpp-SwiftPM/pull/2
- https://github.com/firebase/grpc-SwiftPM/pull/1
#no-changelog - will be invisible to …

Future Apple toolchain fixes

---

.github/workflows/mlmodeldownloader.yml

- needed to investigate nightly failures like [this](https://github.com/firebase/firebase-ios-sdk/actions/runs/613185286)

ML downloader: enable verbose logging to investigate flaky tests

---

scripts/third_party/travis/retry.sh

It looks like in most of the cases if the 2nd attempt fails, the 3rd one fails as well. Let's try avoid extra retries and see if we have more flakes.

CI: try only 2 times

---

.github/workflows/analytics.yml
.github/workflows/spm.yml
.swiftpm/xcode/xcshareddata/xcschemes/Firebase-Package.xcscheme
FirebaseAnalyticsSwift.podspec
FirebaseAnalyticsSwift/CHANGELOG.md
FirebaseAnalyticsSwift/Sources/Analytics+SwiftUI.swift
Package.swift
SwiftPM-PlatformExclude/FirebaseAnalyticsSwiftWrap/dummy.m
SwiftPM-PlatformExclude/FirebaseAnalyticsSwiftWrap/include/dummy.h
SwiftPMTests/analytics-import-test/analytics-import.swift

This is a new FirebaseAnalyticsSwift SDK that adds native Swift
extensions for FirebaseAnalytics, starting with a SwiftUI screen view
function.
#no-changelog
**TODO**:

FirebaseAnalytics SwiftUI API for `screen_view`

---

.github/workflows/spm.yml

This should have been reverted in a previous PR.

Undo accidental commenting out of cron job.

---

CoreOnly/Sources/Firebase.h
FirebaseRemoteConfig/CHANGELOG.md

Fix #7693
Don't generate a warning for missing Analytics when including Performance for Catalyst.
Relatedly and separately  the Perf and RC teams should work out the strategy for these warnings on iOS. See #7487

Don't generate missing Analytics warning on Catalyst

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
scripts/create_spec_repo/Sources/SpecRepoBuilder/main.swift
scripts/release_testing_setup.sh

The release workflow will run from the latest release branch of the SDK repo.
The prerelease workflow will run from the head of the master branch.
Pods tested in release workflow will  source from 
[SpecsTesting repo](https://github.com/FirebasePrivate/SpecsTesting)
[SpecsStaging repo](https://github.com/firebase/SpecsStaging)
cdn
Pods tested in prerelease workflow will source from
[SpecsReleasing repo](github.com/FirebasePrivate/SpecsReleasing)
[SpecsDev](github.com/firebase/SpecsDev.git)
[SpecsStaging repo](https://github.com/firebase/SpecsStaging)
cdn

Update release/prerelease workflows.

---

Firebase.podspec

This makes Analytics consistent with the other libraries by enabling self-contained CocoaPods patch releases.
#no-changelog

Enable Analytics patch updates with Firebase pod update

---

.github/workflows/prerelease.yml
FirebaseFirestore.podspec

Fix `pod spec lint` failure introduced in #7717 and caught in nightly #7726.
`- NOTE | xcodebuild: FirebaseFirestore/Firestore/core/src/bundle/bundle_serializer.h:33:10: fatal error: 'Firestore/third_party/nlohmann_json/json.hpp' file not found`

Add missing new header to Firestore podspec

---

FirebaseInAppMessagingSwift.podspec

Without the beta specifier, Firebase 6.x is specified and fails because it is static.
Our `pod lib lint` and `pod gen` tests don't catch this because they override the version specifier to use the local podspecs.
Verified this fixes with a `pod gen` without `-local-sources=./`

Fix FIAM Swift podspec

---

Firestore/core/src/model/mutable_document.cc
Firestore/core/src/model/mutable_document.h

This ports MutableDocument from Android: https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/model/MutableDocument.java

Mutable Documents

---

FirebaseABTesting.podspec
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseCrashlytics.podspec
FirebaseDatabase.podspec
FirebaseInstallations.podspec
FirebaseInstanceID.podspec
FirebaseMessaging.podspec
FirebaseRemoteConfig.podspec
FirebaseStorage.podspec
FirebaseStorageSwift.podspec

Background is that we need a different set of platforms for libraries and tests when the library supports watchOS since tests aren't supported with watchOS and CocoaPods even with Xcode 12.5.
Current plan is for watchOS CI to be SPM only

Consistent podspec minimum version management

---

.github/workflows/abtesting.yml
.github/workflows/analytics.yml
.github/workflows/appdistribution.yml
.github/workflows/auth.yml
.github/workflows/cocoapods-integration.yml
.github/workflows/core-diagnostics.yml
.github/workflows/core.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firebasepod.yml
.github/workflows/firestore.yml
.github/workflows/functions.yml

Move some cron jobs later to prevent flake notification emails from disrupting evenings.

Move cron jobs later

---

FirebaseRemoteConfig/CHANGELOG.md
FirebaseRemoteConfig/Sources/FIRRemoteConfigComponent.m
FirebaseRemoteConfig/Sources/RCNConfigFetch.m
FirebaseRemoteConfig/Tests/Unit/FIRRemoteConfigComponentTest.m

If `projectID` is missing the fetch request can't succeed, so we can fail the request before sending it to the server. This is causing some downstream issues (tracked in b/167621250)

Throw exception when projectID is missing from FIROptions

---

Firestore/core/src/timestamp_internal.cc

This isn't worth a respin on its own, but if there is an RC2, please pull this in as well to fix a Firestore warning regression.

Fix recently introduced build warning (#7745)

---

FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m
FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMRenderingWindowHelper.h
FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMRenderingWindowHelper.m

[Closes #7791]
* Removed `FIRIAMRenderingWindowHelper`’s `UIWindowForImageOnlyView` method whose body was identical to `UIWindowForModalView`’s
* Renamed `UIWindowForModalView` to `windowForBlockingView` and `UIWindowForBannerView` to `windowForNonBlockingView`, respectively, to clarify their purpose

[#7791] Removed Duplicate Code in IAM

---

.github/workflows/zip.yml

This reverts commit a7ada99447d7763b498c0f0887455c7890bc269e.
#7807 was the wrong way to add the SpecsDev repo to the zip CI build.   See #7797
@granluo Would you take a look?

Revert "Nightly zip should use SpecsDev (#7807)"

---

FirebaseMessaging/Sources/FIRMessagingUtilities.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingCheckinStoreTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenOperationsTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenStoreTest.m

The unit test is using a different path of plist file than the production code causing the test failed as it is checking the path of production code instead of unit test path. This fixes [#7797](https://github.com/firebase/firebase-ios-sdk/issues/7797)

fix breakage in FM tests

---

README.md

Adding a section in the readme to point to the docs for a source of truth on firebase's platform support.

Update README with Firebase platform support info

---

.travis.yml
FirebaseMessaging.podspec
FirebaseMessaging/Sources/FIRMessaging.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingPendingTopicsListTest.m

Fix #7834 
Fix the nightly test failure caused by missing unspecified header:
- NOTE  | [watchOS] xcodebuild:  FirebaseMessaging/FirebaseMessaging/Sources/FIRMessaging.m:29:9: note: did not find header 'Source/Library/Public/FirebaseInstallations/FirebaseInstallations.h' in framework 'FirebaseInstallations' (loaded from '/Users/runner/Library/Developer/Xcode/DerivedData/App-egulcarutpujhtfyjnzoycquvdim/Build/Products/Release-watchsimulator/FirebaseInstallations')
Remove IID from the podspec
#no-changelog

Fix pod spec lint and remove extraneous IID refs

---

.github/workflows/spm.yml
Package.swift
scripts/build.sh

Fix #7784 
While its sufficient to update Swift Package Manager versions to update the dependencies to fix #7784, this PR enforces the minimum dependency versions for the fixes for the future async/await toolchain.
The PR also makes dependency version management more robust by limiting the Firestore dependency updates to patch versions and SwiftProtobuf to minor versions.
Also adds an iOS device build test to catch device specific build problems like what showed up in #7777 earlier.

Firmer SPM dependency versions and iOS device build check

---

FirebaseMessaging/CHANGELOG.md
FirebaseMessaging/Sources/FIRMessagingCode.h
FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.h
FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.m
FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.h
FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m
FirebaseMessaging/Sources/Token/FIRMessagingTokenStore.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingAPNSInfoTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingAuthKeychainTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenInfoTest.m

Also use GULSecureCoding to encode/decode. This partially fixes #3686.
Tested with previously installed app and fcm token is persisted correctly.

Replace NSCoding with NSSecureCoding

---

SharedTestUtilities/FIRSampleAppUtilities.m

[`openURL:`](https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl?language=objc) has been deprecated since the introduction iOS 10. Replaced its use with [`openURL:options:completionHandler:`](https://developer.apple.com/documentation/uikit/uiapplication/1648685-openurl?language=objc), passing in empty options and a `nil` completion handler.
Noticed this in the GHA logs while working on #7788.
This should eliminate the deprecation warning when testing. 
#no-changelog

FIRSampleAppUtilities: Replace deprecated method.

---

FirebaseAuthTestingSupport.podspec
FirebaseCombineSwift.podspec
FirebaseCombineSwift/Sources/Auth/MultiFactor+Combine.swift
FirebaseCombineSwift/Sources/Auth/PhoneAuthProvider+Combine.swift
FirebaseCombineSwift/Tests/Unit/Auth/PhoneAuthProviderTests.swift
FirebaseTestingSupport/Auth/Sources/FIRPhoneAuthProviderFake.m
FirebaseTestingSupport/Auth/Sources/Public/FirebaseAuthTestingSupport/FIRPhoneAuthProviderFake.h
FirebaseTestingSupport/Auth/Tests/PhoneAuthProviderFakeTests.swift

I've changed the way `Publishers` are tested to avoid bloating the codebase with tests already implemented on `FirebaseAuth`.  Now, `Publishers` are tested to full fill the expectation that relative methods are called properly. Please leave me your feedback on this strategy to apply to the next PRs.
```swift
let provider = PhoneAuthProviderFake()
provider.verifyPhoneNumberHandler = { completion in
completion(nil, FIRAuthErrorUtils.missingPhoneNumberError(withMessage: ""))
}
provider.verifyPhoneNumber(with: "", uiDelegate: nil)
if case let .failure(error as NSError) = completion {
XCTAssertEqual(error.code, AuthErrorCode.missingPhoneNumber.rawValue)
expectation.fulfill()
}
} receiveValue: { verificationID in
XCTFail("💥 result unexpected")
} …
```

Combine: PhoneAuthProvider + MultiFactor Publishers

---

.github/workflows/combine.yml
.swiftpm/xcode/xcshareddata/xcschemes/Firebase-Package.xcscheme
FirebaseCombineSwift.podspec
FirebaseCombineSwift/Sources/Storage/StorageReference+Combine.swift
FirebaseCombineSwift/Tests/Unit/Storage/StorageReferenceTests.swift
Package.swift
scripts/check_imports.swift

Use Result type FirebaseStorageSwift APIs for Storage Combine Implementation.
And some podspec cleanups and CI infrastructure fixes.
FYI, I'm just starting to kick the tires on Combine, so let me know if I'm missing anything here.

Use Result type APIs for Storage Combine

---

FirebaseMessaging/CHANGELOG.md
FirebaseMessaging/Sources/FIRMessagingCode.h
FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.h
FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.m
FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.h
FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m
FirebaseMessaging/Sources/Token/FIRMessagingTokenStore.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingAPNSInfoTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingAuthKeychainTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenInfoTest.m

Reverts firebase/firebase-ios-sdk#7831
Looks like this is the one breaks the Encoding/Decoding as the GULSecureCoding doesn't offer overwriting the class. Considering the code change is significant, it's less risk to revert this change and fix the secure coding on top of the original implementation. (preferably after breaking change and let the large refactor of token code settle for a while)

Revert "Replace NSCoding with NSSecureCoding"

---

.github/workflows/storage.yml
scripts/build.sh

Miscellaneous Storage CI cleanups
- Run unit tests from `pod lib lint`
- Remove a duplicate test
- Test FirebaseStorageSwift with `--no-modular-headers` option on cron
#no-changelog

Run unit tests from pod lib lint

---

FirebaseCombineSwift/Sources/Storage/StorageReference+Combine.swift

Futures expect a result type, so no reason to deconstruct and reconstruct

Combine Storage: Futures are Results

---

scripts/build.sh
scripts/code_coverage_report/code_coverage_file_list.json
scripts/update_xcode_target.rb

The Storage integration tests have been silently failing ever since 7.0.0 after the GoogleServiceInfo.plist does not get found because FirebaseCore is linked dynamically as a separate bundle instead of statically into the app. https://github.com/firebase/firebase-ios-sdk/runs/2294766037?check_suite_focus=true#step:7:475
This fix uses a ruby script to update the Test Container app with the GoogleService-Info.plist so that it gets found at initialization.
Also, stop running Firestore test_coverage CI on script changes.
See successful Storage integration test logs at https://github.com/firebase/firebase-ios-sdk/runs/2308057031?check_suite_focus=true

Fix Storage Integration Test CI

---

Firestore/core/src/bundle/bundle_reader.cc

Fixes an issue when building for Windows where this std::min line fails to infer the template type.
#no-changelog

Force the template argument of std::min to prevent Windows build error.

---

FirebaseRemoteConfig/Sources/RCNDevice.m

This was causing a failure in publishing the RemoteConfig pod.
#no-changelog

Use private header import for FIRVersion.h

---

Firebase/InstanceID/Public/FIRInstanceID.h
FirebaseABTesting/Sources/Public/FirebaseABTesting/FIRLifecycleEvents.h
FirebaseAppDistribution/Sources/Public/FirebaseAppDistribution/FIRAppDistribution.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuthErrors.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIREmailAuthProvider.h
FirebaseAuth/Tests/Unit/FIRAuthAppCredentialManagerTests.m
FirebaseDatabase/Sources/Api/Private/FTypedefs_Private.h
FirebaseDatabase/Sources/Core/FWriteTree.m
FirebaseDatabase/Tests/Integration/FIRDatabaseTests.m
FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallations.h
FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessaging.h
FirebasePerformance/Sources/Public/FIRHTTPMetric.h
FirebasePerformance/Sources/Public/FIRPerformance.h
FirebasePerformance/Tests/Unit/Instruments/FPRNSURLSessionInstrumentTest.m
Firestore/Source/Public/FirebaseFirestore/FIRFirestore.h
Firestore/Source/Public/FirebaseFirestore/FIRFirestoreSettings.h
Firestore/Source/Public/FirebaseFirestore/FIRQuery.h
Firestore/core/src/util/error_apple.h
Functions/FirebaseFunctions/Public/FirebaseFunctions/FIRError.h
Interop/Analytics/Public/FIRInteropParameterNames.h
README.md
scripts/setup_check.sh
scripts/style.sh

clang-format 11 has disappeared from brew causing the style check in the check CI workflow to fail.
This PR upgrades to clang-format 12.0.0 which does some weird things with lines including `NS_SWIFT_NAME` including disregarding the 100 character line length.
clang-format bugs reported at https://bugs.llvm.org/show_bug.cgi?id=49995 and https://bugs.llvm.org/show_bug.cgi?id=49996
Any suggestions here would be appreciated.

Update to clang-format 12

---

FirebaseCore/Sources/FIRLogger.m
FirebaseCore/Sources/Private/FIRLogger.h
FirebaseCore/Tests/Unit/FIRLoggerTest.m
FirebasePerformance/Sources/FPRConsoleLogger.h
FirebasePerformance/Sources/FPRConsoleLogger.m

Firebase 8.0.0 progress on #2505.
kFIRLoggerMLKit and kFIRLoggerPerf no longer have google3 references and are updated.
The MLKit one is removed (b/146429345) and the Perf declaration is migrated.

Continue FIRLoggerService client migration

---

CoreOnly/Sources/Firebase.h
Firebase.podspec
FirebaseCore/CHANGELOG.md

Fix #7487 and fix #7832
- Stop generating warnings for not including Analytics
- Remove deleted FirebaseML umbrella headers and remove them from Firebase podspec
- Remove InstanceID umbrella header
- Remove GoogleMobileAds umbrella header
- Remove Fabric umbrella header
podspec version updates will be done separately using the standard script after 7.11.0 is published

Firebase.h updates for 8.0.0

---

CoreOnly/NOTICES

Update done by reviewing output of old google3 script, removing many transitive Firebase ML dependencies, removing some other dependencies that get linked in when building on google3, adding a missing entry for the FirebaseEncoder, and updating the BoringSSL License.
I opened #7918 describing an idea to automate this process. In the meantime, we'll need to manually review when third_party dependencies are changed.

Update NOTICES for Firebase 8.0.0

---

FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.h

This was commented out so it wasn't caught.
#no-changelog

Remove git merging code

---

FirebaseMessaging/Tests/UnitTests/FIRMessagingServiceTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingTest.m

This *pop*ped up during copybara imports.
#no-changelog

Remove unbalanced clang format pop

---

Crashlytics/Crashlytics/Components/FIRCLSContext.h
Crashlytics/Crashlytics/Components/FIRCLSContext.m
Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m
Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.m
Crashlytics/Crashlytics/Models/FIRCLSInstallIdentifierModel.h
Crashlytics/Crashlytics/Models/FIRCLSInstallIdentifierModel.m
Crashlytics/Crashlytics/Models/Record/FIRCLSRecordIdentity.h
Crashlytics/Crashlytics/Models/Record/FIRCLSRecordIdentity.m
Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.h
Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
Crashlytics/UnitTests/FIRCLSInstallIdentifierModelTests.m
Crashlytics/UnitTests/FIRCLSReportAdapterTests.m
Crashlytics/UnitTests/FIRRecordExceptionModelTests.m

This ensures we always call the `installationIDWithCompletion` during upload when we are already collecting crash data. Before we did this process at startup.
This moves the install_uuid out of the `.clsrecord` files and into the proto.
#no-changelog

Rotate Crashlytics Install UUID during upload instead of startup

---

FirebaseAppCheck/Sources/Core/APIService/FIRAppCheckAPIService.m
FirebaseAppCheck/Sources/Core/FIRAppCheck.m
FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckAPIServiceTests.m

Re-enable app check platform logging

---

Crashlytics/Crashlytics/Components/FIRCLSContext.h
Crashlytics/Crashlytics/Components/FIRCLSHost.m

Using this method to filter: https://github.com/google/GoogleUtilities/blob/main/GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m#L267
We're going to convert this on the backend instead of in the SDK. The advantage is we may want details like catalyst vs normal macOS at a later date.

Crashlytics send Firebase Apple Platform for filtering

---

FirebaseDatabase/Sources/Login/FIRDatabaseConnectionContextProvider.h
FirebaseDatabase/Sources/Login/FIRDatabaseConnectionContextProvider.m

Add missing protocol to fix Xcode 12.5 warning

---

SymbolCollisionTest/Podfile

Fix recent nightly symbol collision failure. See #7921
Restoration is tracked in #7953 
#no-changelog

Disable GoogleMLKit until it updates to GDT 9

---

Package.swift

This includes the same artifact as 7.11.0 but put into the proper .zip format (with zip on the command line instead of Finder's compress menu option).
#no-changelog

FirebaseAnalytics 7.11.1 release.

---

ReleaseTooling/Sources/ZipBuilder/Platform.swift
ReleaseTooling/Sources/ZipBuilder/main.swift

This is a more flexible approach to allowing different Firebase pods with different platform version support than #7956.
It's safe because the actual build minimum version is controlled by the podspec. The minimum version that is being disregarded here was only for insuring a full installation had a consistent minimum version.

Disable CocoaPods minimum version install testing for Firebase zip build

---

FirebaseAppCheck/Sources/AppAttestProvider/API/FIRAppAttestAPIService.h
FirebaseAppCheck/Sources/AppAttestProvider/API/FIRAppAttestAPIService.m
FirebaseAppCheck/Sources/AppAttestProvider/DCAppAttestService+FIRAppAttestService.h
FirebaseAppCheck/Sources/AppAttestProvider/DCAppAttestService+FIRAppAttestService.m
FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m
FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestService.h
FirebaseAppCheck/Sources/AppAttestProvider/Storage/FIRAppAttestKeyIDStorage.h
FirebaseAppCheck/Sources/AppAttestProvider/Storage/FIRAppAttestKeyIDStorage.m
FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.h
FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.m
FirebaseAppCheck/Sources/DeviceCheckProvider/API/FIRDeviceCheckAPIService.m
FirebaseAppCheck/Sources/DeviceCheckProvider/FIRDeviceCheckProvider.m
FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppAttestProvider.h
FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestProviderTests.m

Moving App Check App Attest changes from private repo to a feature branch. Original PR: https://github.com/FirebasePrivate/firebase-ios-sdk/pull/761.

App Attest provider: attestation sequence

---

FirebaseAnalytics.podspec.json
FirebaseAppCheck.podspec
FirebaseAppDistribution.podspec
FirebaseAuth.podspec
FirebaseCore.podspec
FirebaseCoreDiagnostics.podspec
FirebaseDynamicLinks.podspec
FirebaseFunctions.podspec
FirebaseInAppMessaging.podspec
FirebaseInstallations.podspec
FirebaseMLModelDownloader.podspec
FirebaseMessaging.podspec
FirebasePerformance.podspec
FirebaseRemoteConfig.podspec
FirebaseStorage.podspec
GoogleAppMeasurement.podspec.json
Package.swift

To minimize testing matrix in Firebase 8.x +
GoogleUtilities 7.4+
Protobuf 3.15+
GTMSessionFetcher 1.5+
GoogleUtilities SPM 7.4 update is deferred until its tagged
#no-changelog

Bump floating minor dependency versions to latest minimum

---

FirebaseCore/Sources/FIRApp.m
FirebaseCore/Sources/FIRHeartbeatInfo.m
FirebaseCore/Sources/Private/FIRAppInternal.h
FirebaseCore/Tests/Unit/FIRHeartbeatInfoTest.m
Package.swift

This should mitigate heartbeat files being wiped due to tvOS cache being
invalidated. Fixes #6662
#no-changelog

Migrate to UserDefaults based heartbeat on tvOS

---

FirebaseRemoteConfig/CHANGELOG.md
FirebaseRemoteConfig/Sources/RCNConfigContent.m

`_configLoadFromDBSemaphore = dispatch_semaphore_create(1)` causes the later `dispatch_semaphore_wait` call in `checkAndWaitForInitialDatabaseLoad()` to never be blocked, so it's possible to return a config before we finish loading from the DB.
Removing `dispatch_semaphore_signal` from `loadPersonalization` as its success/failure should not impact RC returning a config
fixes #7424

Block calls to get config until DB load completes

---

FirebaseDynamicLinks/CHANGELOG.md
FirebaseDynamicLinks/Sources/FIRDLJavaScriptExecutor.m

Manually tested fix on M1 machine and it successfully ran without crashing. 
Fixes #7618

DynamicLinks: Skip retrieving web locale when running targeting below iOS14 (only on simulator & Apple Silicon)

---

.github/workflows/firestore.yml

Firestore takes over an hour on presubmit.
https://github.com/firebase/firebase-ios-sdk/runs/2456478584?check_suite_focus=true
This is to limit the platform and intend to shorten the presubmit processing time.

Update firestore podspec presubmit to ios platform

---

.github/workflows/zip.yml
ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift

Continue #7983 fixing to handle an iOS 11 minimum version pod
This extends the hack a bit more and my test case now successfully builds.
Most of this code should delete soon when we move Carthage to xcframework support
This PR successfully builds the zip and the structure diff looks reasonable. See comments.
The quickstarts are failing and that looks related to the new Analytics structure introduced in 7.11.0

Continue iOS 11 zip builder fix

---

FirebaseCore/Sources/Private/FIRHeartbeatInfo.h
FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenOperationsTest.m

~~Add to test setup to use platform specific heartbeat storage APIs.~~
Revised approach: Mock `FIRHeartbeatInfo` to avoid side effects of using GULHeartbeatDateStorable objects. 
Breakage due to:
GoogleUtilites [#23](https://github.com/google/GoogleUtilities/pull/23) and firebase-ios-sdk #7893 for context.
Fixes FirebaseMessaging Failure in #7993.
cc @chliangGoogle 
#no-changelog

FirebaseMessaging: Mock FIRHeartbeatInfo in test

---

Firestore/core/src/bundle/bundle_serializer.cc

This is part of #7904. It will break the feature branch, but I am planning to send out small reviewable chunks with an end goal of a feature branch that passes CI.
This PR changes the Bundle serializer to serialize into NanoPB.

BundleSerializer changes for Protobuf migration

---

Crashlytics/Crashlytics/Components/FIRCLSApplication.h
Crashlytics/Crashlytics/Components/FIRCLSApplication.m
Crashlytics/Crashlytics/Components/FIRCLSHost.m

We need to split off iPad
#no-changelog

Add iPadOS as split out in Crashlytics Platform

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/core/src/nanopb/fields_array.h
Firestore/core/src/nanopb/message.h
Firestore/core/src/nanopb/nanopb_util.h
Firestore/core/test/unit/nanopb/nanopb_util_test.cc

This is part of #7904. It will break the feature branch, but I am planning to send out small reviewable chunks with an end goal of a feature branch that passes CI.
This PR adds a couple of new classes and methods that are used in the FieldValue port.  
Example usage:
- `SharedMessage` is a shared pointer around `Message`, which allows a single Protobuf value to be used in multiple classes. This makes it possible for a Query and a Target to contain the same Filter and Bounds. See https://github.com/firebase/firebase-ios-sdk/pull/7904/files?file-filters%5B%5D=.cc&file-filters%5B%5D=.h&file-filters%5B%5D=.mm&file-filters%5B%5D=.txt#diff-ca2b3b9278f6b19636908d4f2da32d8657081510e6ffb60b823d5766992bf263R87
- `SetRepeatedField` simplifies initialization of nanopb repeated fields. See …

NanoPB utilities for FieldValue migration

---

.github/workflows/abtesting.yml
.github/workflows/appdistribution.yml
.github/workflows/core-diagnostics.yml
.github/workflows/core.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/inappmessaging.yml
.github/workflows/installations.yml
.github/workflows/messaging.yml
.github/workflows/mlmodeldownloader.yml
.github/workflows/remoteconfig.yml
.github/workflows/storage.yml

To catch issues from new Xcode versions sooner. 
Most of these were added when the default was Xcode 11 and 12 was needed for SPM

Run CI with default GHA Xcode version

---

Firestore/core/src/model/transform_operation.cc
Firestore/core/src/model/transform_operation.h

These are two files from https://github.com/firebase/firebase-ios-sdk/pull/7904 that should be able to be reviewed relatively independently. Most of the missing functions are in review here: https://github.com/firebase/firebase-ios-sdk/pull/7991 (such as `IsArray`.
This PR changes all FieldTransforms to use Protobuf directly. It follows the code on Android: https://github.com/firebase/firebase-android-sdk/tree/master/firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation

FieldValue changes for transform_operation

---

Firestore/core/src/local/local_store.cc
Firestore/core/src/local/local_store.h
Firestore/core/test/unit/local/local_store_test.cc

This is also part of https://github.com/firebase/firebase-ios-sdk/pull/7904. It is also best compared to Android. 
Android's `ImmutableSortedMap<DocumentKey, Document>` is a DocumentMap in this PR. `ImmutableSortedMap<DocumentKey, MutableDocument>` is a MutableDocumentMap.

LocalStore changes for Protobuf migration

---

FirebaseMessaging/CHANGELOG.md

Since the Firebase 8 will not have IID as part of its repo, developers will not be able to include InstanceID in the podfile to keep using InstanceID. They will have to migrate to new token APIs. Adjust the changelog to reflect this change.

Adjust the Messaging changelog after we remove iid from github

---

FirebaseCore/CHANGELOG.md
Package.swift
SwiftPackageManager.md

This is to avoid an issue with newer APIs being unable to compile when
building for device while this manifest targets iOS 10.
See https://github.com/firebase/firebase-ios-sdk/issues/7785#issuecomment-831959399
for more details on the issue and a reproduction. This should be
re-evaluated if Xcode ever fixes the issue.
This will need to be cherry-picked onto the `release-8.0` branch.

Bump the minimum SwiftPM iOS version to 11.

---

Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
Firestore/core/test/unit/bundle/bundle_loader_test.cc
Firestore/core/test/unit/core/query_listener_test.cc
Firestore/core/test/unit/core/view_snapshot_test.cc
Firestore/core/test/unit/core/view_test.cc
Firestore/core/test/unit/local/leveldb_key_test.cc
Firestore/core/test/unit/local/lru_garbage_collector_test.h
Firestore/core/test/unit/local/query_engine_test.cc
Firestore/core/test/unit/model/document_set_test.cc
Firestore/core/test/unit/model/transform_operation_test.cc
Firestore/core/test/unit/remote/remote_event_test.cc
Firestore/core/test/unit/remote/watch_change_test.cc
Firestore/core/test/unit/testutil/view_testing.cc
Firestore/core/test/unit/testutil/view_testing.h

This is part of #7904. It will break the feature branch, but I am planning to send out small reviewable chunks with an end goal of a feature branch that passes CI.
This PR contains the test files that only have "mechanical refactor" changes.
- No more DocumentState. Instead we use `SetHasLocalMutations`/`SetHasCommittedMutations`. `
- No more MaybeDocument. Instead we now have MutableDocument.
- No more MaybeDocumentMap. Instead just DocumentMap. 
- A Document is now a const wrapper on top of MutableDocument. Hence, some callsites change to `->`

Test Refactor for Protobuf-backed FieldValue

---

Package.swift

Crashlytics was inadvertently deleted from SPM product list.
Restoring here.
And another +1 for more SPM tests ...
#no-changelog

Restore Crashlytics to SPM

---

Firestore/Source/API/FIRDocumentSnapshot.mm
Firestore/Source/API/FIRQuery.mm
Firestore/Source/API/FIRTransaction.mm
Firestore/Source/API/FSTFirestoreComponent.mm
Firestore/Source/API/FSTUserDataReader.h
Firestore/Source/API/FSTUserDataReader.mm

This changes the code in the iOS API to directly read from and write to Protobuf.

Changes in the iOS API for FieldValue migration

---

.github/workflows/combine.yml
FirebaseCombineSwift.podspec
FirebaseCombineSwift/Sources/Storage/StorageReference+Combine.swift
FirebaseCombineSwift/Tests/Integration/Storage/StorageIntegration.swift
scripts/build.sh

Port Swift Storage integration tests to Combine.
Reviewer notes:
- Please especially review the proposed minor API improvement proposal improvements
- Refer to the [Swift Storage integration tests](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseStorageSwift/Tests/Integration/StorageIntegration.swift) for the non-Combine version of these tests.
- I skipped the progress tests since I didn't find a good way to do those in Combine
- I'm looking for a better way to do the expected failure tests
- I'll follow up with CI after initial reviews
To run the tests yourself
-  Use a GoogleService-Info.plist with Auth and Storage enabled. 
- `pod gen FirebaseCombineSwift.podspec --auto-open --local-sources=./ --platforms=ios`
- Add the GoogleService-Info.plist to the AppHost Target
- …

Port Storage Integration tests to Combine

---

Firestore/core/src/model/transform_operation.cc
Firestore/core/test/unit/model/mutation_test.cc

The elements added in an ArrayUnion should be added in order.

Preserve order in ArrayUnion

---

Firestore/Source/API/FIRQuery.mm
Firestore/core/src/local/local_documents_view.cc
Firestore/core/src/local/local_documents_view.h

LocalDocumentsView is now responsible for applying all mutations to MutableDocuments and returning them as `Document`s which can no longer be mutated.
Android link: https://github.com/firebase/firebase-android-sdk/blob/7be699f74d6effca46e765d22bd7635d78d17253/firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java

LocalDocumentsView FieldValue migration

---

FirebaseCore/CHANGELOG.md
README.md
SwiftPackageManager.md

This is alongside the 8.0.0 release - officially committing to support
of SwiftPM as a release mechanism for Firebase.

Mark SwiftPM support as Official.

---

Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
Firestore/Source/API/FIRTransaction.mm
Firestore/core/src/api/document_reference.cc
Firestore/core/src/api/firestore.cc
Firestore/core/src/api/write_batch.cc
Firestore/core/src/model/resource_path.cc
Firestore/core/src/util/exception.cc

* Throw more specific exceptions when the error is due to bad input (backport of cr/359824564) (note that this only applies to the Unity build);
* Always log exceptions to make sure they make it into the log (regardless of exception handling by the user and any potential issues with the exception propagation mechanism).
#no-changelog

Minor error handling improvements

---

cmake/podspec_rules.cmake

The cmake build assumes that the `sed` command is installed on the system; however, this is often not true on Windows. If the `sed` command is absent then the `FIRFirestore_VERSION` preprocessor variable is silently set to the empty string, which causes `firestore_version.cc` to fail to build.
This PR simply forces cmake to fail loudly if `sed` is not available, which is far easier to diagnose than the inevitable obscure downstream build failure.
Fixes #8066

Fail the cmake build if reading the version from the podspec fails

---

.swiftpm/xcode/xcshareddata/xcschemes/FirebaseMLModelDownloaderUnit.xcscheme

Fix #8063 
The MLModelDownloader Unit Test scheme was inadvertently deleted in #8060 leading to a nightly failure. Restoring here.

Restore FirebaseMLModelDownloaderUnit.xcscheme

---

Firestore/Source/API/FIRQuery.mm
Firestore/core/src/core/user_data.cc
Firestore/core/src/model/delete_mutation.cc
Firestore/core/src/model/delete_mutation.h
Firestore/core/src/model/mutation.cc
Firestore/core/src/model/mutation.h
Firestore/core/src/model/mutation_batch.cc
Firestore/core/src/model/mutation_batch.h
Firestore/core/src/model/object_value.cc
Firestore/core/src/model/object_value.h
Firestore/core/src/model/patch_mutation.cc
Firestore/core/src/model/patch_mutation.h
Firestore/core/src/model/precondition.cc
Firestore/core/src/model/precondition.h
Firestore/core/src/model/set_mutation.cc
Firestore/core/src/model/set_mutation.h
Firestore/core/src/model/verify_mutation.cc
Firestore/core/test/unit/model/object_value_test.cc

I recommend comparing to Android: https://github.com/firebase/firebase-android-sdk/tree/master/firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation

Protobuf-backed Mutations

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/core/test/unit/testutil/testutil.cc
Firestore/core/test/unit/testutil/testutil.h

These are the test util changes of the larger migration PR (https://github.com/firebase/firebase-ios-sdk/pull/7904)

TestUtil methods that create Protobuf

---

Firestore/core/src/core/firestore_client.cc
Firestore/core/src/core/view.cc
Firestore/core/src/core/view.h

Should be compared to Android. These classes now use Document as the new immutable document type.

Protobuf changes for View/FirestoreClient

---

Firestore/core/src/model/server_timestamp_util.cc
Firestore/core/src/model/server_timestamp_util.h
Firestore/core/src/model/value_util.cc
Firestore/core/src/model/value_util.h

This is part of #7904. It will break the feature branch, but I am planning to send out small reviewable chunks with an end goal of a feature branch that passes CI.
This PR adds a couple of new utilities that are used in the FieldValue port (and changes some signatures). They are all based on Android:  https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java  
The PR also adds logic to treat zero-length strings/bytes the same as `null` bytes and strings, as nanopb uses both representations.

ValueUtil changes for FieldValue migration

---

Carthage.md
ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json

This PR is the resulting build distribution from the fixes in #8084
Fix #7039
Fix #7576
Will publish the Carthage update when #8084 and this PR are approved.
Testing:
Unzipped the archive from https://github.com/firebase/firebase-ios-sdk/actions/runs/845683211
Edited the json files in a local directory:
Edited the sample in Carthage.md like
Verified `carthage update` succeeded.

Update Carthage distribution for 8.0.0

---

ReleaseTooling/DEVELOP.md
ReleaseTooling/Sources/ZipBuilder/FirebaseBuilder.swift
ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
ReleaseTooling/Sources/ZipBuilder/main.swift
scripts/build_zip.sh

Follow up to #8084 to remove the `--enable-carthage-build` option and always build Carthage when building a Firebase zip distribution.
The other open comment in #8084 about the plist generation file requires more thought since it is being used both for xcframework builds and for the special Firebase framework that we're still assembling for Carthage.
Companion CL is cl/374299027

Always build Carthage with Firebase zip distributions

---

FirebaseCombineSwift/Sources/Auth/Auth+Combine.swift
FirebaseCombineSwift/Sources/Auth/GameCenterAuthProvider+Combine.swift
FirebaseCombineSwift/Sources/Auth/MultiFactor+Combine.swift
FirebaseCombineSwift/Sources/Auth/MultiFactorResolver+Combine.swift
FirebaseCombineSwift/Sources/Auth/OAuthProvider+Combine.swift
FirebaseCombineSwift/Sources/Auth/PhoneAuthProvider+Combine.swift
FirebaseCombineSwift/Sources/Auth/User+Combine.swift
FirebaseCombineSwift/Sources/Core/Core.swift
FirebaseCombineSwift/Sources/Functions/HTTPSCallable+Combine.swift
FirebaseCombineSwift/Sources/Storage/StorageReference+Combine.swift

- Reviewed and cleaned up some of the documentation
- Tried to standardize/cleanup some of the`#if` compilation logic
- `FirebaseCombineSwift` now conditionally builds for all platforms (mainly had to get watchOS compiling)
- Removed remaining `weak` references to `self` after reading [this note](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCombineSwift/DECISIONS.md#using-capture-lists) from `FirebaseCombineSwift/DECISIONS.md`
#no-changelog

FirebaseCombineSwift: Docs & API cleanup

---

FirebaseInAppMessaging/CHANGELOG.md
FirebaseInAppMessaging/Sources/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m
FirebaseInAppMessaging/Tests/Unit/FIRIAMDisplayExecutorTests.m

Fixes #8081 .
Adds unit test coverage for all message initializers.

Fix setting of in-app message type in `FIRInAppMessagingImageOnlyDisplay` initializer

---

FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m
FirebaseAppCheck/Sources/Core/FIRAppCheck.m
FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestProviderTests.m
FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckTests.m

- prevent concurrent App Attest handshake operations
- prevent concurrent token refresh operations for any provider (on the App Check Core level)
#no-changelog

App Check: prevent concurrent token requests

---

.github/workflows/zip.yml

The simplified Carthage directory structure introduced in #8093 caused the `find` command used to extract the zip archive to fail since it now also matched all the Carthage zips.
- Fix the `find` issue
- Always run the quickstart tests on zip builder PRs to catch subtle problems like this on presubmit. Also, the qs tests are the only tests we have of using the zip builder for non-Firebase release builds.

Fix zip qs test build regression

---

Crashlytics/CHANGELOG.md
Crashlytics/Crashlytics/Components/FIRCLSApplication.m

`UI_USER_INTERFACE_IDIOM` reports iOS when it's an iOS-only app running on an iPad.

Crashlytics fix os_name check for iPads

---

FirebaseMessaging/Apps/AdvancedSample/Podfile
FirebaseMessaging/Apps/Sample/Podfile
FirebaseMessaging/Apps/Sample/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme
FirebaseMessaging/Apps/Shared/AppDelegate.swift
FirebaseMessaging/CHANGELOG.md
FirebaseMessaging/Sources/FIRMessagingAnalytics.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingAnalyticsTest.m

This fixes #8128 and #7707. Internal bug: b/157964197.
When app is completely closed and user taps on notification to open the app, the client SDK does not correctly capture the state to log notification open.
Also add analytics to sample app.
Added unit test and tested sending when app is closed, now notification_open is logged on analytics debug view console.

Fix an issue that notification open is not logged when app is closed

---

.github/workflows/test_coverage.yml

GITHUB_REF will get a 'merge' branch due to pull_request , instead of a `master` branch.  
`github.head_ref` could fetch the merged branch, e.g. `master`. 
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

Update merge branch in the Metrics Service

---

ReleaseTooling/Sources/FirebaseReleaser/main.swift
ReleaseTooling/Sources/Utils/Date+Utils.swift

Prints time marks for `swift run firebase-releaser` command like:
```
Started at: 2021-05-25, 11:47:05 PM
... 
Finished at: 2021-05-30, 2:53:45 PM. Duration: 111 h 6 min. 40 sec.
```
#no-changelog

Print FirebaseReleaser duration

---

.github/workflows/test_coverage.yml

According to [`github` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context), `github.head_ref` refers to the head branch which is what we work on. `github.base_ref` is the targeted branch the PR is going to be merged into.

Fix code coverage branch

---

FirebaseAppCheck/Sources/AppAttestProvider/API/FIRAppAttestAPIService.m
FirebaseAppCheck/Sources/AppAttestProvider/Errors/FIRAppAttestRejectionError.h
FirebaseAppCheck/Sources/AppAttestProvider/Errors/FIRAppAttestRejectionError.m
FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m
FirebaseAppCheck/Sources/Core/APIService/FIRAppCheckAPIService.m
FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.h
FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.m
FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckHTTPError.h
FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckHTTPError.m
FirebaseAppCheck/Sources/Core/FIRAppCheck.m
FirebaseAppCheck/Sources/Core/FIRAppCheckLogger.h
FirebaseAppCheck/Sources/Core/FIRAppCheckLogger.m
FirebaseAppCheck/Sources/DebugProvider/FIRAppCheckDebugProvider.m
FirebaseAppCheck/Sources/DebugProvider/FIRAppCheckDebugProviderFactory.m
FirebaseAppCheck/Sources/DeviceCheckProvider/FIRDeviceCheckProvider.m
FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestAPIServiceTests.m
FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestProviderTests.m
FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckTests.m

- reset stored attestation data on attestation rejection from Firebase backend
- outdated TODOs removed
- `kFIRLoggerAppCheckMessageCodeUnknown` replaced by specific unique codes in log messages

App Check App Attest: handle attestation rejection

---

Crashlytics/CHANGELOG.md
Crashlytics/Crashlytics/Components/FIRCLSApplication.m

Fix deprecation warning when minimum deployment version is iOS 13+

---

FirebaseMessaging/Tests/UnitTests/FIRMessagingAnalyticsTest.m

In rare case the test is running when app is not in foreground, falling into the default application state where it checks if notification is a display one. So set the sample notification with valid display format to ensure tests are always passing.
#no-changelog

Set valid format of notification sample

---

.github/workflows/app_check.yml
FirebaseAppCheck/Sources/AppAttestProvider/DCAppAttestService+FIRAppAttestService.h
FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m
FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestProviderTests.m
FirebaseAppCheck/Tests/Unit/AppAttestProvider/Storage/FIRAppAttestArtifactStorageTests.m
FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckIntegrationTests.m
FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckStorageTests.m

Fix #8175
Fix AppCheck Catalyst build and add CI.  This fixes a regression building the zip.
Interestingly, this failure does not repro on Xcode 12.5

Fix AppCheck Catalyst build on Xcode 12.4

---

scripts/code_coverage_report/generate_code_coverage_report/Package.swift
scripts/code_coverage_report/generate_code_coverage_report/Sources/IncrementalCoverageReportGenerator/main.swift
scripts/code_coverage_report/generate_code_coverage_report/Sources/Utils/JSONParser.swift

The IncrementalCoverageReportGenerator will input 'git diff' JSON from #8160 and xcresult bundles from the [test_coverage workflow](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/test_coverage.yml), e.g. artifacts from [a workflow run](https://github.com/firebase/firebase-ios-sdk/actions/runs/882836165).

Generate a JSON file with newly added lines not covered by tests.

---

FirebaseAnalytics.podspec.json
GoogleAppMeasurement.podspec.json

Unity generates Podfiles like:
```
target 'UnityFramework' do
pod 'Google-Mobile-Ads-SDK', '~> 8.2'
end
target 'Unity-iPhone' do
end
use_frameworks!
```
This is problematic because it asks to link static framework into a dynamic framework and also linked directly to the app. There will then be two copies of the static framework which can cause non-deterministic behavior. Details at https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md.
In theory, CocoaPods should treat static frameworks the same, whether or not they're source or binary. However, it turns out that adding `"static_framework": true` to the podspec will cause a binary framework to only get linked into the dynamic framework and not the app.

Support Unity generated Podfiles

---

Firestore/Example/Tests/Util/FSTHelpers.mm
Firestore/Source/API/FIRDocumentSnapshot.mm
Firestore/Source/API/FSTUserDataReader.mm
Firestore/core/src/api/document_snapshot.cc
Firestore/core/src/api/document_snapshot.h
Firestore/core/src/core/view.cc
Firestore/core/src/local/local_serializer.cc
Firestore/core/src/local/local_store.cc
Firestore/core/src/model/mutable_document.h
Firestore/core/test/unit/bundle/bundle_serializer_test.cc
Firestore/core/test/unit/local/remote_document_cache_test.cc

This PR reduces some implicit copies of ObjectValue that can be replaced with std::move. The only remaining callsites of ObjectValue copy-constructor are now in tests (and it is quite difficult to fix there).

Reduce ObjectValue copies

---

Package.swift

We missed updating the SPM distribution to GDT 9 in the 8.0.0 release. The GDT breaking change API isn't relevant for Firebase, but the 9.0.1 update will fix GDT analyze issues.

Update SPM distro to GDT 9

---

FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m
FirebaseInAppMessaging/Tests/Unit/FIRIAMFetchResponseParserTests.m
FirebaseInAppMessaging/Tests/Unit/TestJsonDataFromFetch.txt

Firebase user can set action button's text color on firebase console for Firebase InAppMessaging. But the parser is ignoring button text color.
This PR fixes a issues of parsing data of modal message.

Fix lack of parse for fiam modal action button

---

FirebasePerformance/CHANGELOG.md
FirebasePerformance/Sources/AppActivity/FPRSessionDetails.m
FirebasePerformance/Sources/Instrumentation/FPRNetworkTrace.m
FirebasePerformance/Sources/Timer/FIRTrace.m

Make a copy of sessionDetails to avoid the risk of losing object during acting on notification of sessionID change.

---

FirebaseDynamicLinks/CHANGELOG.md
FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.m

Fixed analyze issue introduced in Xcode 12.5

---

.swiftpm/xcode/xcshareddata/xcschemes/ABTestingUnit.xcscheme
FirebaseABTesting/CHANGELOG.md
FirebaseABTesting/Sources/ABTExperimentPayload.m
FirebaseABTesting/Sources/Private/ABTExperimentPayload.h

Fix analyze issue introduced in Xcode 12.5

---

Firestore/Source/API/FIRQuery.mm
Firestore/core/src/api/query_core.cc
Firestore/core/src/api/query_core.h
Firestore/core/src/bundle/bundle_serializer.cc
Firestore/core/src/core/array_contains_any_filter.cc
Firestore/core/src/core/array_contains_any_filter.h
Firestore/core/src/core/array_contains_filter.cc
Firestore/core/src/core/array_contains_filter.h
Firestore/core/src/core/field_filter.cc
Firestore/core/src/core/field_filter.h
Firestore/core/src/core/in_filter.cc
Firestore/core/src/core/in_filter.h
Firestore/core/src/core/key_field_filter.cc
Firestore/core/src/core/key_field_filter.h
Firestore/core/src/core/key_field_in_filter.cc
Firestore/core/src/core/key_field_in_filter.h
Firestore/core/src/core/key_field_not_in_filter.cc
Firestore/core/src/core/key_field_not_in_filter.h
Firestore/core/src/core/not_in_filter.cc
Firestore/core/src/core/not_in_filter.h
Firestore/core/src/nanopb/message.h
Firestore/core/src/remote/serializer.cc
Firestore/core/test/unit/testutil/testutil.cc

This fixes a memory leak when we fail Query validation. 
The old flow was:
- Create nanopb struct
- Validate Query
- If valid, wrap in Message
This PR creates the Message first and then validates.

Wrap Protobuf for Query Filters in Messages

---

ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift
ReleaseTooling/Sources/Utils/String+Utils.swift

When the release tooling [iterates through all of the defined `Pods`](https://github.com/firebase/firebase-ios-sdk/blob/5aaf38c022718421c389cfafa4fe2776227966d2/ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift#L74), it uses the `range(of:)` String API to find the first occurrence of the `pod` and then bumps the versioning. Because the API only finds the first occurrence, each pod will only get versioned bumped once. Because the `FirebaseAnalytics` substring now occurs in two places (after PR #7900 added `'FirebaseAnalytics/WithoutAdIDSupport'`):  
https://github.com/firebase/firebase-ios-sdk/blob/acf106a33d50e893f85a8563a19557b3df6110d1/Firebase.podspec#L37
and 
https://github.com/firebase/firebase-ios-sdk/blob/acf106a33d50e893f85a8563a19557b3df6110d1/Firebase.podspec#L72 …

Fix versioning bug in release tooling

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
Firestore/Source/API/FIRCollectionReference.mm
Firestore/Source/API/FIRDocumentReference.mm
Firestore/Source/API/FIRFirestore.mm

Currently, the error would look like `Document references must have an even number of segments, but has 0`.
Fixes #8218.

Explicitly check that document and collection IDs given to the public API aren't empty

---

FirebaseStorage/CHANGELOG.md
FirebaseStorage/Sources/FIRStorageComponent.m
FirebaseStorage/Tests/Integration/FIRStorageIntegrationTests.m
FirebaseStorage/Tests/Unit/FIRStorageComponentTests.m

This re-uses the same logic that RTDB uses to ensure that repeated invocations of the Storage factory function return the same instance for the same bucket.
Fixes https://github.com/firebase/firebase-ios-sdk/issues/8109

Cache FirebaseStorage instances

---

Firestore/core/src/remote/grpc_connection.cc

This is a backport of cr/377421930.
#no-changelog

Fix a data race in `GrpcConnection` when retrieving the language token.

---

.github/workflows/functions.yml
Functions/CHANGELOG.md
Functions/Example/Tests/FIRFunctionsTests.m
Functions/FirebaseFunctions/FIRFunctions.m
Functions/FirebaseFunctions/FIRFunctionsComponent.h
Functions/FirebaseFunctions/FIRFunctionsComponent.m
Functions/FirebaseFunctions/FIRFunctions_Private.h
Functions/FirebaseFunctions/Public/FirebaseFunctions/FIRFunctions.h
Functions/Tests/CombineUnit/HTTPSCallableTests.swift

Cache Functions instances by app

---

FirebaseAnalytics.podspec.json

FirebaseAnalyics.podspec.json failed to validate because the Base subspec did not depend on GoogleAppMeasurement.
This PR eliminates that unnecessary podspec.
I'm not sure why this issue wasn't caught before. Two possibilities: `pod spec lint` is non-deterministic or something about FirebaseAnalytics.xcframework changed to introduce a build dependency on GoogleAppMeasurement in a blank project.

Eliminate invalid subspec

---

Crashlytics/Crashlytics/Controllers/FIRCLSAnalyticsManager.h

We use forward declarations instead, so the header isn't needed. In addition, this was giving errors in the flutter plugin https://github.com/FirebaseExtended/flutterfire/pull/5900
```
@protocol FIRAnalyticsInterop;
@protocol FIRAnalyticsInteropListener;
```
#no-changelog

Crashlytics remove unnecessary Analytics header

---

FirebaseInstallations/Source/Library/FIRInstallations.m

Update confusing error message now that IID has been removed.
Context at https://stackoverflow.com/questions/68049548/firebaseinstallations-will-not-work-correctly-with-current-version-of-firebase-i
#no-changelog

Update FIS IID error message

---

FirebaseAppDistribution/CHANGELOG.md
FirebaseAppDistribution/Sources/FIRAppDistribution.m
FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m

Check for an Unauthorized error and sign out the Tester from the fetchNewLatestRelease.

[App Distribution] Reset sign in flag on unauthorized error

---

FirebaseAnalytics.podspec.json
GoogleAppMeasurement.podspec.json

This reverts commit 500ea2d38452e5f8a01d3d17a87976574a8983c3.
Adding the `static_framework` attribute causes some Podfiles to start to fail to install.  An example is the [Firebase Functions Quickstart](https://github.com/firebase/quickstart-ios/tree/master/functions).  More details internally at b/191680865.
The fix is already deployed to SpecsStaging, and this PR should still be cherry-picked to the release-8.2 after merging.

Revert "Support Unity generated Podfiles (#8193)"

---

FirebaseAppCheck/CHANGELOG.md
FirebaseAppCheck/Sources/AppAttestProvider/Storage/FIRAppAttestArtifactStorage.h
FirebaseAppCheck/Sources/AppAttestProvider/Storage/FIRAppAttestArtifactStorage.m
FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.h
FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.m
FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrors.m
FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckHTTPError.m
FirebaseAppCheck/Sources/Core/FIRAppCheck.m
FirebaseAppCheck/Sources/Core/Storage/FIRAppCheckStorage.m
FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheck.h
FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckErrors.h
FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FirebaseAppCheck.h
FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestAPIServiceTests.m
FirebaseAppCheck/Tests/Unit/AppAttestProvider/Storage/FIRAppAttestArtifactStorageTests.m
FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckAPIServiceTests.m
FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckStorageTests.m
FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckTests.m
FirebaseAppCheck/Tests/Unit/DeviceCheckProvider/FIRDeviceCheckAPIServiceTests.m
FirebaseAppCheck/Tests/Unit/Swift/AppCheckTests.swift

- Added Public Get Token API for 3P use
- Refactored `AppCheckTests.m` to share testing infra between new public get token API and interop get token API
- Added API-reviewed error enum
- Add error handling for keychain related errors
- Add tests for above addition
b/190653133

App Check: Token API for 3P  use

---

FirebaseStorage/Sources/FIRStorage.m
FirebaseStorage/Sources/FIRStorageDownloadTask.m

Fixes #8294, probably.
It's unclear to me exactly what the original implementation did, though it's likely it [slept](https://github.com/google/gtm-session-fetcher/blob/main/Source/GTMSessionFetcher.m#L2055) the thread instead of allowing other closures to execute first.

Punt pause task to the end of the queue

---

FirebaseAppCheck/Sources/Core/FIRAppCheck.m
FirebaseAuth/Sources/Auth/FIRAuth.m
FirebaseCore/Sources/FIRApp.m
FirebaseDatabase/Sources/Api/FIRDatabase.m
FirebaseInstallations/Source/Library/FIRInstallations.m

Changing exception messages to be more Swift oriented.
Follow-up PR to conversation from https://github.com/firebase/firebase-ios-sdk/pull/8266#discussion_r656615037

Swift first exception messages

---

Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
Firestore/core/src/model/object_value.cc

When the new size of a fields map is less than the old size, we currently leak memory. This PR removes the memory allocated for the "overflow" entries.

Don't leak memory when all fields are deleted

---

Firestore/Example/Tests/Integration/FSTTransactionTests.mm
Firestore/core/src/core/transaction_runner.cc
Firestore/core/src/core/transaction_runner.h

Porting from [android](https://github.com/firebase/firebase-android-sdk/pull/2764).

Standardize transaction retries to attempts

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/zip.yml
scripts/remove_data.sh
scripts/setup_quickstart.sh
scripts/setup_quickstart_framework.sh
scripts/test_quickstart_framework.sh

Update zip, release, and prerelease workflows for new crashlytics qs location
Please also review https://github.com/firebase/quickstart-ios/pull/1209
We really need to define a set of self-contained functions in the quickstart repo that can be called without side-effects or knowing directory structures.
Fix #8302

Update more workflows for new crashlytics qs location

---

Firestore/CHANGELOG.md
Firestore/core/src/util/exception_apple.mm
Firestore/core/src/util/log_apple.mm

Currently, any UTF-8 characters outside the ascii set may be encoded incorrectly.

Fix the handling of Unicode characters in log and assertion messages

---

FirebaseCore/CHANGELOG.md
Package.swift

Cherrypicking latest [8.3.1 patch commit](../commit/ed87539cda9cfb3a3de1be22354c6e74760db91b) from [`release-8.3`](../commits/release-8.3) branch to keep `master` in sync for M100.
#no-changelog

Cherrypick 8.3.1 SPM patch into master

---

.travis.yml

Something about #8351 caused travis infra to fail.  See https://travis-ci.org/github/firebase/firebase-ios-sdk/jobs/774672431 
Since travis is going away and these tests are running on GHA, deleting to get travis green again.
Note `pod lib lint` is still running for FIAM on travis.
#no-changelog

Turn off failing travis FIAM tests

---

FirebaseAppCheck/CHANGELOG.md
FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
FirebaseAppDistribution/Sources/FIRAppDistributionUIService.h
FirebaseAppDistribution/Sources/Public/FirebaseAppDistribution/FIRAppDistribution.h
FirebaseDynamicLinks/CHANGELOG.md
FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLinks.h
FirebaseInAppMessaging/CHANGELOG.md
FirebaseInAppMessaging/Sources/DefaultUI/Banner/FIRIAMBannerViewController.h
FirebaseInAppMessaging/Sources/DefaultUI/Card/FIRIAMCardViewController.h
FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMBaseRenderingViewController.h
FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.h
FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMRenderingWindowHelper.h
FirebaseInAppMessaging/Sources/DefaultUI/ImageOnly/FIRIAMImageOnlyViewController.h
FirebaseInAppMessaging/Sources/DefaultUI/Modal/FIRIAMModalViewController.h
FirebaseInAppMessaging/Sources/Private/Flows/FIRIAMDisplayCheckOnAnalyticEventsFlow.h
FirebaseInAppMessaging/Sources/Private/Flows/FIRIAMDisplayExecutor.h
FirebaseInAppMessaging/Sources/Private/Flows/FIRIAMFetchOnAppForegroundFlow.h
FirebaseInAppMessaging/Sources/Private/Flows/FIRIAMMessageClientCache.h
FirebaseInAppMessaging/Sources/Private/Runtime/FIRIAMFetchFlow.h
FirebaseInAppMessaging/Sources/Private/Runtime/FIRIAMRuntimeManager.h
FirebaseInAppMessaging/Sources/Public/FirebaseInAppMessaging/FIRInAppMessaging.h
FirebaseInAppMessaging/Sources/Public/FirebaseInAppMessaging/FIRInAppMessagingRendering.h
FirebaseInAppMessaging/Sources/Runtime/FIRIAMActionURLFollower.m
FirebaseInAppMessaging/Swift/Source/CustomInAppMessageDisplayViewModifier.swift
FirebaseInAppMessaging/Swift/Source/SwiftUIPreviewHelpers.swift
Functions/Tests/CombineUnit/HTTPSCallableTests.swift
SharedTestUtilities/FIRSampleAppUtilities.h

Fix Xcode 13 beta 3 build issues

---

.travis.yml
FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m

Bump travis from unsupported Xcode 11 to Xcode 12.5
Fix uncovered Auth analyze issue.
Disable Firestore testing since it is too slow to complete and is fully ported to GitHub Actions
#no-changelog

Bump travis to 12.5

---

FirebasePerformance/Sources/FPRClient.m
FirebasePerformance/Sources/FPRNanoPbUtils.h
FirebasePerformance/Sources/FPRNanoPbUtils.m
FirebasePerformance/Sources/Instrumentation/FPRNetworkTrace.h
FirebasePerformance/Sources/Instrumentation/FPRNetworkTrace.m
FirebasePerformance/Tests/Unit/FPRNanoPbUtilsTest.m

Similar to how Objective-C classes are converted to protos, this PR converts Objective-C classes to Nanopb struct.
Please refer to [FPRProtoUtils.h](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebasePerformance/Sources/FPRProtoUtils.h), [FPRProtoUtils.m](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebasePerformance/Sources/FPRProtoUtils.m), and [FPRProtoUtilsTest.m](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebasePerformance/Tests/Unit/FPRProtoUtilsTest.m)

Convert Objective-C Classes to Nanopb

---

Package.swift
scripts/build.sh
scripts/setup_spm_test_app_measurement.sh

Use GoogleAppMeasurement main branch instead of release tag for CI.  This enables us to use CI for release tagging without tagging the GoogleAppMeasurement repository until release and avoid needing to make last minute commits to the firebase repo to update to the new tag. b/194422721

Use GoogleAppMeasurement main branch instead of release tag for CI

---

Firebase.podspec

tvOS support was only installable directly from the FirebasePerformance pod. This PR enables support via the Firebase pod as well.

Add missing tvOS subspec support in Firebase pod for Performance

---

FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuthAPNSTokenType.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuthUIDelegate.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRFederatedAuthProvider.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRMultiFactor.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRMultiFactorAssertion.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRMultiFactorInfo.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRMultiFactorResolver.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRMultiFactorSession.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRPhoneAuthCredential.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRPhoneAuthProvider.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRPhoneMultiFactorAssertion.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRPhoneMultiFactorGenerator.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRPhoneMultiFactorInfo.h
FirebaseAuth/Sources/Public/FirebaseAuth/FIRUser.h
FirebaseAuth/Sources/Public/FirebaseAuth/FirebaseAuth.h

Need to add headerdoc comments with platform availability where it's limited before merging this PR.

Auth: Remove all #ifs in favor of API_UNAVAILABLE

---

FirebaseDatabase/Tests/Unit/Swift/DatabaseAPITests.swift

There were some compiler errors from Xcode13b4.
They were mainly related to updates to Swift Concurrency
- `async` was replaced with `Task`
- Cannot captured vars from a sync context in an async context
#no-changelog

Get Database Swift API Test building on Xcode13b4

---

FirebaseMessaging/CHANGELOG.md
FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessagingExtensionHelper.h

remove platform version check from Messaging header

---

.github/workflows/auth.yml
.github/workflows/installations.yml
.github/workflows/mlmodeldownloader.yml

Fixes some failures from https://github.com/firebase/firebase-ios-sdk/issues/8471#issuecomment-893449537.

Configure macOS test keychain for keychain dependent workflows

---

FirebaseInAppMessaging.podspec
FirebaseInAppMessaging/Swift/Source/SwiftUIPreviewHelpers.swift
FirebaseInAppMessagingSwift.podspec

Fixes the [failure](https://github.com/firebase/firebase-ios-sdk/runs/3250028778?check_suite_focus=true) from https://github.com/firebase/firebase-ios-sdk/issues/8471#issuecomment-893449537.

FirebaseInAppMessagingSwift: explicitly import UIKit

---

.github/workflows/auth.yml
.github/workflows/installations.yml
.github/workflows/mlmodeldownloader.yml

The keychain setup fixes in #8496 should also be done for the cron jobs.
Fix #8471

Apply keychain fixes to cron tests

---

FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m

[Closes #8482]
* Fixed a bug where an invalid image URL string in an in-app message crashed the client app
* A URL string is considered invalid if the `[NSURL URLWithString:]` method produces `nil`

[#8482] Fixed Crash Caused by Invalid IAM Image URL

---

FirebaseDatabase/Sources/Core/FSyncTree.m

Fixes #8357 
The issue was that `node` property of `FCacheNode` pokes one level deeper than needed in this case: (FCacheNode.m:66)
```
- (id<FNode>)node {
return self.indexedNode.node;
}
```
us make Firebase APIs better, …

Fix getData crashing in offline

---

README.md

Fix #8514 
There are no longer special instructions for Apple Silicon Macs. The standard distributions now work for all Macs.

There are no longer special instructions for Apple Silicon Macs

---

FirebaseMessaging/Apps/Sample/Sample.xcodeproj/project.pbxproj
FirebaseMessaging/CHANGELOG.md
FirebaseMessaging/Sources/Token/FIRMessagingAuthService.h
FirebaseMessaging/Sources/Token/FIRMessagingAuthService.m
FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingAuthServiceTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenManagerTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenOperationsTest.m

This fixes #8491.
There's a race condition when checkin sometimes not reset properly during app first install, then delete token request contains an old chekcin that causes token is not deleted properly.

Fix race condition where checkin is not reset properly when app first installed

---

FirebaseMessaging/Tests/UnitTests/FIRMessagingExtensionHelperTest.m

This breaks the tests internally.
#no-changelog

Should verify mock object after expect

---

FirebaseMessaging/Tests/UnitTests/FIRMessagingAuthServiceTest.m
FirebaseMessaging/Tests/UnitTests/FIRMessagingExtensionHelperTest.m

Fixes #8525. #no-changelog
We need to adjust unit test after we fixed the checkin issue. When we moved the checkinStore under authService, the stub parameter no longer take effect so we should use [OCMArg any] instead for the stub method to be triggered.

Fix nightly build

---

scripts/pod_lib_lint.rb

With CocoaPods 1.10.2, it's no longer necessary to remove the Twitter URL in the `pod_lib_lint` script. 
See https://github.com/CocoaPods/CocoaPods/pull/10398

Remove pod_lib_lint script workaround

---

Functions/CHANGELOG.md
Functions/Example/Tests/FIRFunctionsTests.m
Functions/Example/Tests/FUNContextProviderTests.m
Functions/FirebaseFunctions/FUNContext.m

Fixes https://github.com/FirebaseExtended/flutterfire/issues/6794 for Apple platforms.
b/197236400

Functions: don't send dummy FAC token

---

SwiftPackageManager.md

fixes #8533
Updates the spm installation instructions.
Currently the Build phase outlined for dsym upload produces an extra `/` before `SourcePackages`
New path that will be output:
n/a

Fix double '/' in path produced by spm sample crashlytics build script

---

FirebaseDatabase/CHANGELOG.md
FirebaseDatabase/Sources/Core/FPersistentConnection.m

Database: fix App Check token refresh

---

.github/workflows/abtesting.yml
.github/workflows/auth.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/functions.yml
.github/workflows/inappmessaging.yml
.github/workflows/installations.yml
.github/workflows/messaging.yml
.github/workflows/performance.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/remoteconfig.yml
.github/workflows/storage.yml
scripts/test_quickstart.sh

The Unit/UI tests are currently failing in some of the quickstarts as documented in firebase/quickstart-ios#1260. The API of the quickstart test.sh has changed to require a TEST environment variable to disable the unit test run.
This PR makes the corresponding update for this repo.
#no-changelog

Update quickstart tests based on quickstart-ios/issues/1260

---

.github/workflows/prerelease.yml

This will trigger `update_SpecsTesting_repo` job in postsubmit. 
The other jobs will still run nightly.

Enable prerelease in postsubmit

---

FirebaseAuth/Sources/SystemService/FIRSecureTokenService.h
FirebaseAuth/Sources/SystemService/FIRSecureTokenService.m
FirebaseAuth/Sources/User/FIRUser.m
FirebaseAuth/Tests/Unit/FIRAuthTests.m
FirebaseAuth/Tests/Unit/FIRUserTests.m

Handle the case when refreshToken is null for Custom Auth. 
If refresh token is absent, we won't send a getAccountInfoRequest to populate FIRUser fields. Instead, a FIRUser is created from a Firebase ID token, with only the user_id field populated from the ID token.
#no-changelog

Handle the case when refreshToken is null

---

.github/workflows/health_metrics.yml

Reference:
https://github.community/t/how-to-detect-a-pull-request-from-a-fork/18363

Skip binary measurement job for fork

---

FirebasePerformance/CHANGELOG.md
FirebasePerformance/Sources/FPRClient.m

* https://github.com/firebase/firebase-ios-sdk/issues/8423
Log level from most verbose to least verbose is: 
> Debug, Info, Notice, Warning, Error
With those 5, levels, `Notice`, `Warning`, and `Error` logs will show even without `-FIRDebugEnabled` being set. Due to that, `FPRLogError(kFPRClientPerfNotConfigured, @"Dropping event since data collection is disabled.");` will spam log if gauge metrics are being collected (if they are being collected, they are firing on a timer, like every second). With this PR, only when `-FIRDebugEnabled` is set, will those log message show up in logs, if you are lucky enough to be selected for sampling in the first place (more on this below).
Reproducing this issue was difficult at first because of sampling. Long before gauge metrics collection start, in …

FirePerf: use FPRLogDebug instead of FPRLogError for logging events when FirePerf is disabled

---

Functions/Example/Tests/FIRFunctionsTests.m

Looks like we still need to do the weak self bit to avoid a fatal buildtime warning that occurs when copybara'ing into g3. 
#no-changelog

Add back fix for g3 warnings

---

Functions/Example/Tests/FIRFunctionsTests.m

I missed one warning!
#no-changelog

Add back fix for g3 warnings (pt 2)

---

FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m
FirebaseAuth/Tests/Unit/FIRPhoneAuthProviderTests.m

For phone auth app verification, if the push notification is not received before the timeout, fall back to reCAPTCHA for app verification.
[Google-internal bug: b/198507858]

Fall back to reCAPTCHA verification in phone auth if push notification is not received

---

.github/workflows/abtesting.yml
.github/workflows/auth.yml
.github/workflows/crashlytics.yml
.github/workflows/database.yml
.github/workflows/dynamiclinks.yml
.github/workflows/firestore.yml
.github/workflows/functions.yml
.github/workflows/inappmessaging.yml
.github/workflows/messaging.yml
.github/workflows/performance.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/remoteconfig.yml
.github/workflows/storage.yml
.github/workflows/zip.yml
scripts/remove_data.sh

Removing a secret from a workflow that is no longer used in the objc quickstart testing.
Comment with some context below:
> So it looks like account in FIREGSignInInfo.h doesn't get tested anymore. Related to b/140411106 which is marked obsolete. And FWIW, these tests were in the legacy ObjC Auth quickstart.
#no-changelog

Remove potentially unnecessary secret from workflows

---

.github/workflows/update-cpp-sdk-on-release.yml

Whenever a  release is published (except for CocoaPods-* releases), trigger the C++ SDK to do an iOS dependency update, pulling latest deps from public Cocoapods HEAD.
It requests a token that has access to firebase-cpp-sdk and uses that token to trigger the C++ update-dependencies workflow.
(Android equivalent is here: https://github.com/firebase/firebase-android-sdk/pull/2977)

Add workflow to update Firebase C++ SDK deps when iOS SDK release is published

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
Firestore/core/src/api/document_snapshot.cc
Firestore/core/src/model/mutable_document.cc
Firestore/core/src/model/mutable_document.h

Do not consider MutableDocument's state for DocumentSnapshot comparison

---

FirebaseDynamicLinks/CHANGELOG.md
FirebaseDynamicLinks/Sources/Utilities/FDLUtilities.m
FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m

[FDL] Refactoring and fixing url validation
- Refactored the existing code to use Regex to validate FDL URL formats.
- Added checks to make sure the 'link' query param is having an http/https prefix input.
== This is going to be breaking the existing SDK's unintended behavior to support links with non http/https content. The existing SDK was constructing the Dynamic link eventhough the backend response to resolve the link is not successfull.
- Added support for URL(s) with Query string starting with '?' alone. Previously it was supporting '/?' formats only. This fixes https://github.com/firebase/firebase-ios-sdk/issues/7087
- Added more test cases to be in sync with FDL backend validation.
- Removed invalid test inputs and corrected few test cases to make the input in proper format.

[FDL] Refactoring and fixing url validation

---

FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenManagerTest.m

_Figured I'd leave a write up since this flake took me awhile..._
**The reason for the flake:** 
`FIRMessagingTokenManager` enqueues operations on an internally managed NSOperation queue. Sometimes, operations enqueued by one test haven't run yet by the time the test has completed. 
> **Some context**
> Specifically, three out of the four tests from `FIRMessagingTokenManagerTest.m` call:
> ```objc
> [_messaging.tokenManager resetCredentialsIfNeeded];
> ```
> which–**for some test code paths**–kicks off an async token delete operation. Prior to calling `resetCredentialsIfNeeded`, 
we set up some stubs and expects that will later be verified after `resetCredentialsIfNeeded` is called. 
When a token deletion operation starts, it calls the shared instance of Installations. In cases where the …

[Messaging] Fix flaky `FIRMessagingTokenManagerTest` tests

---

FirebaseDynamicLinks/CHANGELOG.md
FirebaseDynamicLinks/Sources/FIRDLJavaScriptExecutor.m

Fix #8694
Our CI missed this because it doesn't do a device build

Fix device-only build warning

---

Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
Firestore/Source/API/FIRCollectionReference.mm
Firestore/Source/API/FIRDocumentReference.mm
Firestore/Source/API/FIRDocumentSnapshot.mm
Firestore/Source/API/FIRFieldPath.mm
Firestore/Source/API/FIRFirestore+Internal.h
Firestore/Source/API/FIRFirestore.mm
Firestore/Source/API/FIRFirestoreSettings.mm
Firestore/Source/API/FIRQuery.mm
Firestore/Source/API/FIRWriteBatch.mm
Firestore/Source/API/FSTFirestoreComponent.mm
Firestore/Source/API/FSTUserDataReader.mm
Firestore/Source/API/FSTUserDataWriter.mm

This would conflict with any definition of a `util` namespace imported from a header. While this applies to other aliases as well, `util` is the one most likely to clash and the one that has actually caused problems.
#no-changelog

Don't define a `util` namespace alias in the global namespace.

---

FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/Backend/FIRAuthBackend.m
FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.h
FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m
FirebaseAuth/Tests/Unit/FIRAuthBackendRPCImplementationTests.m

Add `NSUnderlyingError ` to `FIRAuthInternalErrorCodeUnexpectedErrorResponse` errors.

Improve error logging for FIRAuthInternalErrorCodeUnexpectedErrorResponse errors

---

.github/workflows/health_metrics.yml

Found binary size reports have more question marks than expected. 
This seemed to be caused by binary size data which were not uploaded properly, since `needs:check` kept the binary data job from being run in post submits, which uploaded binary data to Metrics Service. The lack of data in base commits eventually lead to questions marks in reports.
The `check` job is helping check changing files in a PR and so to determine jobs to be run and this is not applicable in post submit and `always()` will run the binary job regardless of `needs:check`.

Enable binary data upload in post submit

---

.github/workflows/zip.yml

PR #8543 specifically leaves the zip build on macOS-latest (vs macOS-11) so that the build has access to the oldest supported Xcode (12.2 as of now) to avoid bitcode-incompatibility
However, macOS-latest is currently transitioning to macOS-11 which will lead to build failures as macOS-11 does not have access to Xcode 12.2
migration plan:
https://github.com/actions/virtual-environments/issues/4060
macOS-11 without Xcode 12.2:
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode
macOS-10.15 still has Xcode 12.2:
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode
This pins the zip build to macOS-10.15 in order to maintain Xcode 12.2 access
I rely on @paulb777's keen eyes here

build(release, zip): pin zip build to macOS-10.15

---

FirebaseAuth/Sources/Backend/FIRAuthBackend.m
FirebaseAuth/Sources/Backend/RPC/FIREmailLinkSignInResponse.h
FirebaseAuth/Sources/Backend/RPC/FIREmailLinkSignInResponse.m
FirebaseAuth/Sources/Backend/RPC/FIRVerifyAssertionResponse.h
FirebaseAuth/Sources/Backend/RPC/FIRVerifyPasswordResponse.h

Motivation of this pull request is to support MFA with email link sign in. Unfortunately, firebase-ios-sdk does not support email link sign in with MFA even if the document mentioned as supported (https://cloud.google.com/identity-platform/docs/ios/mfa). This issue is already reported in https://github.com/firebase/firebase-ios-sdk/issues/7770
I found a reason of this issue and fix it as follows:
- Store `mfaInfo` in `FIREmailLinkSignInResponse`.
- [here](https://github.com/firebase/firebase-ios-sdk/compare/master...0x0c:feature/support-mfa-with-email-link-signin?expand=1#diff-636a0b9aac20361cfebaf481eae8a0cf4c1943c52850348529236761c09baa41R33) and [here](https://github.com/firebase/firebase-ios-sdk/compare/master...0x0c:feature/support-mfa-with-email-link-signin?expand=1#diff-ac59cabb48dc …

Support multi-factor authentication with email link sign in

---

FirebaseCore/CHANGELOG.md
Package.swift

Planning to publish an 8.8.1 only SPM release after LGTMs.
I'll merge to master and make a similar CocoaPods update for 8.9.0 - less urgent since `pod update` always updates to latest when updating Firebase.
Additional context at #8636

Force GoogleUtilities and GDT update for SPM

---

FirebaseCore/CHANGELOG.md
Package.swift

After publishing the 8.8.1 tag and SPM distribution, merge back to master.

Merge 8.8.1 to master

---

.github/workflows/update-cpp-sdk-on-release.yml

This can prevent a race condition when the update is triggered before the Cocoapods main branch is updated.

Wait for Cocoapods update to be complete before updating C++ SDK.

---

FirebaseDatabase/CHANGELOG.md
FirebaseDatabase/Sources/Utilities/FUtilities.m
FirebaseDatabase/Tests/Unit/FUtilitiesTest.m

Fix #8874 
Change logic to only replace the last match in the URL string instead of all of them

Fix URL handling bug when path is a substring of host

---

Firebase.podspec
FirebaseCore.podspec
ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
ReleaseTooling/Sources/ZipBuilder/CocoaPodUtils.swift

Update FirebaseCore to get version right and version in Manifest so zip build succeeds
Also fix zip builder to handle the mixed Firebase patch versions that occur when building a zip release for a Firebase patch release.
Fix #8885 
#no-changelog

Core and zip updates for 8.9.1 - Fix zip builder for patch distributions

---

Firestore/Source/API/FSTUserDataWriter.mm

These missing includes don't fix the build here, but they fix it when this code is copied into google3.
#no-changelog

Fix imports in FSTUserDataWriter.mm

---

Firestore/core/src/local/local_write_result.h
Firestore/core/src/local/query_result.h

These missing includes don't fix the build here, but they fix it when this code is copied into google3.
#no-changelog

Add some missing includes to local_write_result.h and query_result.h

---

FirebaseRemoteConfig/CHANGELOG.md
FirebaseRemoteConfig/Sources/RCNConfigDBManager.m

Fix RC db flags

---

CMakeLists.txt

This fixes a flurry of "ld: warning: pointer not aligned at address" warnings that reportedly fail the build of the C++ SDK.
Here are some customer reports of these warnings affecting builds:
- https://github.com/firebase/firebase-cpp-sdk/issues/712
- https://github.com/firebase/firebase-unity-sdk/issues/83

CMakeLists.txt: add -DPB_NO_PACKED_STRUCTS=1 to the nanopb compiler flags

---

FirebasePerformance/CHANGELOG.md
FirebasePerformance/Sources/AppActivity/FPRSessionDetails.m
FirebasePerformance/Tests/Unit/FPRSessionDetailsTest.m

Fixes #8691
FPRSessionDetails contains the details about the current session. Whenever a trace is created, they take a copy of the session. But the session copy was not taking in the sessionStartTime which could lead to a situation where a check on the session expiration duration could cause a crash. The fix is to make sure the copy contains the same sessionStart time as the original session details object.

Perf return session length return type

---

Firestore/core/src/util/log_stdio.cc

I guess nobody tried logging messages at "info" level before 🤷 
#no-changelog

log_stdio.cc: add missing switch block for kLogLevelNotice

---

.github/workflows/functions.yml
.github/workflows/spm.yml
FirebaseFunctions/Tests/SwiftIntegration/IntegrationTests.swift
FirebaseTestingSupport/Functions/Sources/FIRFunctionsFake.m
FirebaseTestingSupport/Functions/Sources/Public/FirebaseFunctionsTestingSupport/FIRFunctionsFake.h
Package.swift
scripts/spm_test_schemes/FunctionsIntegration.xcscheme
scripts/spm_test_schemes/FunctionsSwiftIntegration.xcscheme

- Translate https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseFunctions/Tests/Integration/FIRIntegrationTests.m to Swift
- Add SPM targets for the integration tests
- Add FIRFunctionsFake.m to workaround the `init` function not bridging to Swift because of its parameters using forward declarations and to use the existing Objective C fake implementations
Future PRs will:
- Add a CocoaPods test_spec for the Swift integration tests
- Add async/await variations of the tests
- Review API coverage
- Prepare for Codable PR integration - See #8854

Port Functions integration tests to Swift

---

FirebaseFunctions/Sources/Public/FirebaseFunctions/FIRHTTPSCallable.h
FirebaseFunctions/Tests/SwiftIntegration/APITests.swift

- Add build test coverage for Functions Public API surface not included in integration tests
- Remove no longer necessary clang-format directive

Public Functions Swift API build test coverage

---

README.md

* Update the anchors to navigate to the sections below, in the same page, instead of going to a different page.
Currently, the anchors to the installation subsections in the main README in the entry page (https://github.com/firebase/firebase-ios-sdk) is using a wrong syntax, that opens the README file on the `master` branch (https://github.com/firebase/firebase-ios-sdk/blob/master/README.md#standard-pod-install), instead of jumping in the same page (https://github.com/firebase/firebase-ios-sdk#standard-pod-install)
Below is a video that shows the after and before fix behaviors.
https://user-images.githubusercontent.com/9660181/141672246-f7c7dbf8-e55e-4bcc-97b7-bb334dbe711d.mp4
* Relink the `Swift Package Manager` anchor to the section below, instead of the file.
Because the file link is …

[Doc Only] Update installation subsection anchors

---

.github/workflows/health-metrics-presubmit.yml

This is to fix #8985 
Reports will not be posted to PRs rooted from master in presubmirs, but data will still be uploaded in postsubmits.

Stop posting reports in PRs not from master

---

FirebaseFunctions/Sources/Public/FirebaseFunctions/FIRHTTPSCallable.h

Similar changes are needed for the Codable APIs introduced in #8854
#no-changelog

Update Functions public API docs for FCM Token instead of IID

---

HeartbeatLogging/Sources/AnyEncoder+AnyDecoder.swift
HeartbeatLogging/Sources/Heartbeat.swift
HeartbeatLogging/Sources/HeartbeatController.swift
HeartbeatLogging/Sources/HeartbeatInfo.swift
HeartbeatLogging/Sources/HeartbeatPayload.swift
HeartbeatLogging/Sources/HeartbeatStorage.swift
HeartbeatLogging/Sources/Storage.swift
HeartbeatLogging/Sources/StorageFactory.swift
HeartbeatLogging/Sources/Weak.swift
HeartbeatLogging/Sources/WeakContainer.swift
HeartbeatLogging/Tests/Unit/HeartbeatControllerTests.swift
HeartbeatLogging/Tests/Unit/HeartbeatStorageTests.swift

Refactored library to improve testability and clarity.
Key Changes:
- All of the heartbeat logging logic (whether or not to log) is now in `HeartbeatController`
- Moved `HeartbeatInfo`'s visibility to internal and decoupled it's internal dependencies.
-  Motivation: `HeartbeatInfo` represents stored heartbeats. Its structure is optimized for storage requirements (limit on write) and differs significantly from the structure the heartbeats will be in when they are sent.
- Added a new public model called `HeartbeatsPayload` 
- Allows type safe encoding into header string.
- Added instance management system to `HeartbeatStorage` (tests for `HeartbeatStorage` are a WIP)
-  Motivation: Multiple instances of `HeartbeatStorage` with the same identifier should share the same instance.

Refactor library and add WIP controller tests

---

HeartbeatLogging/Sources/HeartbeatInfo.swift
HeartbeatLogging/Sources/Storage.swift
HeartbeatLogging/Tests/Unit/StorageTests.swift

This PR adds tests for the wrapper classes used to read and write from file system and user defaults.
#no-changelog

[Heartbeat Logging] - Add underlying storage tests

---

GoogleUtilitiesComponents.podspec

Fix #9021 
Bump version to 1.1.0 to update published minimum iOS version from 8.0 to 10.0.
Restore s.static_framework = true, so that the library is an exact match to 1.0.0 except for minimum iOS version.
This should technically be a major version update, but doing a minor version since the only CocoaPods dependent, MLKitCommon, which has always required iOS 10.0 and the minor update will get the fix with publishing only this pod and only a `pod update` from users.
Checks:
`git diff UtilitiesComponents-1.0.0 -- GoogleUtilitiesComponents`
` git diff UtilitiesComponents-1.0.0 -- GoogleUtilitiesComponents.podspec`
`~/.cocoapods/repos/cocoapods (master) $ git grep GoogleUtilitiesComponents`

Update for GoogleUtilitiesComponents 1.1.0 release

---

Package.swift

Context at https://stackoverflow.com/questions/70109984/firebase-spm-brings-lots-of-warning-under-ios15/70113338#70113338
#no-changelog

Update required SPM abseil dep

---

.github/workflows/spm.yml
SwiftPM-PlatformExclude/FirebaseAnalyticsWithoutAdIdSupportWrap/dummy.m
SwiftPM-PlatformExclude/FirebaseAnalyticsWrap/dummy.m

Fix #9029
We missed updating two warnings when enabling Analytics multi-platform support in 8.9.0.  In the meantime, these warnings can be safely disregarded.

Fix analytics warnings building for macOS/tvOS with SPM

---

.github/workflows/spm.yml
FirebaseCore/CHANGELOG.md
Package.swift
SwiftPackageManager.md

For some reason this still works in a project, but Xcode gets confused
and doesn't autocomplete the module appropriately. This should fix it
for tvOS and macOS.
Also cleaned up a few references to Analytics only being available on
iOS.

Fix Analytics SwiftPM platform availability.

---

.github/workflows/update-cpp-sdk-on-release.yml

Updated version of the script requires the "requests" module, which needs to be explicitly installed.

Install Python dependencies before running trigger_workflow script.

---

FirebaseStorageSwift/Sources/Result.swift
FirebaseStorageSwift/Sources/StorageError.swift
FirebaseStorageSwift/Tests/Integration/StorageAsyncAwait.swift
FirebaseStorageSwift/Tests/Integration/StorageIntegration.swift

Initial thoughts about a Swift Error enum for Firebase Storage.
Thoughts about this approach and recommendations for next steps appreciated.
This implementation takes advantage that most of the APIs that return error codes also have a Result API so that the Result implementation can map the Objective C error to a Swift error.
When implementing the tests, I realized that the auto-generated async APIs hide the Result version so the strategy does not work for both supporting async/await and Swift error codes.
Swift error codes may need to wait until we can do a breaking release and fully wrap and hide all of the Objective C APIs in favor of a purely Swift API.

Swift Error Enum for Storage

---

FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m

Fix for issue #8907 InApp message is shown every new session (timestamp of the impression record is always 0 seconds).

Fix for issue #8907 InApp message is shown every new session 

---

ReleaseTooling/Package.swift
ReleaseTooling/Sources/PodspecsTester/InitializeSource.swift
ReleaseTooling/Sources/PodspecsTester/main.swift

This is to set up spec testing before running. 
The [SpecsTesting repo](https://github.com/firebase/SpecsTesting) and [SDK repo](https://github.com/firebase/firebase-ios-sdk) to the head of a PR will be added to local through [checkout](https://github.com/actions/checkout).
A testing tag will be added to the local sdk repo.
All podspecs in the local sdk repo will be updated with a new git to the local sdk repo and a testing tag pointing to the head of head of a PR.
TODO for setup:
These updated podspecs will be copied to the local spec repo located in `${HOME}/.cocoapods`.

Set up specs testing

---

FirebaseInAppMessaging/iOS/FirebaseInAppMessaging_iOS.m
SwiftPMTests/objc-import-test/objc-header.m
SwiftPMTests/objc-import-test/objc-module.m

Was working on something else and realized `TARGET_OS_TVOS` was a typo.
```
grep -rl 'TARGET_OS_TVOS' ./ | xargs sed -i '' 's/TARGET_OS_TVOS/TARGET_OS_TV/'
```
#no-changelog

Fix `TARGET_OS_TVOS` typos

---

FirebaseMessaging/Tests/UnitTests/FIRMessagingExtensionHelperTest.m

The flaky test requires internet access. I think it's easiest to increase the expectation timeout time by a few seconds but would like to verify this works.
**Update** I was not able to repro the flaky behavior seen in the nightlies. I still think it may be worth it to extend expectation wait time and see if this test flakes again in nightlies.
#no-changelog

Fix flaky messaging test

---

.github/workflows/combine.yml
FirebaseCombineSwift/Tests/Unit/Auth/OAuthProviderTests.swift
FirebaseCombineSwift/Tests/Unit/Auth/SignInWithGameCenterTests.swift

- Fix `combine` regression from #9069
- Run `combine` on dependency source changes
#no-changelog

Fix build errors in `FirebaseCombineSwift`

---

FirebaseRemoteConfig.podspec
FirebaseRemoteConfig/Tests/SwiftAPI/AsyncAwaitTests.swift

The minimum versions in the podspec cause `pod install` and build warnings.  Also using `@available` is consistent with the rest of Firebase.

Control async/await testing from source instead of podspec

---

scripts/spm_test_schemes/CoreUnit.xcscheme

When developing `FirebaseCore` with SPM, I commonly try to build `FirebaseCore` in Xcode and get: 
So I tweaked the scheme to allow for running (building) the library.
#no-changelog

Make `CoreUnit` scheme buildable

---

ReleaseTooling/Sources/PodspecsTester/InitializeSource.swift

Updated podspecs will be copied to a local `.cocoapods` dir, so when podspec testing is run and source to the specstesting spec repo, the latest dependencies will be from the head of a PR.

Specstesting Copy files to `.cocoapods` dir

---

FirebaseAuth/Sources/Backend/RPC/FIRSecureTokenRequest.h
FirebaseAuth/Sources/Backend/RPC/FIRSecureTokenRequest.m
FirebaseAuth/Sources/SystemService/FIRSecureTokenService.h
FirebaseAuth/Sources/SystemService/FIRSecureTokenService.m
FirebaseAuth/Tests/Unit/FIRSecureTokenRequestTests.m

Removing the unused Secure Token Service authorization code flow, as it is never invoked anywhere and is just dead code. In addition, the authorization code flow is deprecated on the backend.
#no-changelog non-user-visible refactoring

Remove unused STS auth code flow.

---

FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h

`FIRAuthStateListener` has no definition nor other references, so is safe to remove.
#no-changelog non-user-visible refactoring

Remove reference to non-existent protocol.

---

SwiftDashboard.md

See https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfig?authuser=0 for an example where almost every API references an Objective C type or call even though the APIs themselves are Swift

Add Swift Doc Scrub to dashboard

---

FirebaseDatabase.podspec
FirebaseDatabase/LICENSE
FirebaseFirestore.podspec
Firestore/LICENSE

Update the LICENSE file specified by the RTDB and Firestore podspecs to include licenses for included third_party code.
The structure is the standard Firebase license followed by the other licenses.

Fix CocoaPods license files for RTDB and Firestore

---

FirebaseAnalyticsSwift.podspec
FirebaseCombineSwift.podspec
FirebaseDatabaseSwift.podspec
FirebaseFunctionsSwift.podspec
FirebaseMLModelDownloader.podspec
FirebaseSharedSwift.podspec
FirebaseStorageSwift.podspec

Bump the `swift_version` spec property to `5.3` (the Swift version associated with Firebase's minimum supported Xcode– 12.2).
#no-changelog

Bump `swift_version` to 5.3 for all podspecs

---

.github/workflows/functions.yml
FirebaseFunctions.podspec
FirebaseFunctionsSwift.podspec

- Use environment variable to enable Functions test_specs. 
- Disable macOS tests with TODO which fail on CI but run locally
- Reenable `pod spec lint` test now that 8.11.0 is staged
#no-changelog

Enable functions test specs and pod spec lint

---

ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift

When the ` --minimum_ios_version` option is >= 11.0, don't build 32 bit targets for iOS.
Additional internal context at go/nc_lib_iosx

Don't build 32 bit archs for >= iOS 11

---

.github/workflows/core.yml
.github/workflows/heartbeat_logging.yml
FirebaseCore.podspec
HeartbeatLogging/Sources/HeartbeatsPayload.swift
HeartbeatLoggingTestUtils/Sources/HeartbeatLoggingTestUtils.swift
Package.swift

**Context**
Compressing heartbeats payloads reduces size and should help reduce bandwidth when sending in requests
**Experiments**
| payload type | not gzipped  (bytes) | gzipped (bytes) |
| --- | --- | --- |
| small | 75 | 85 |
| large | 490 | 171 |
#no-changelog

[Heartbeat Logging] Add compression for heartbeats payloads

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/Source/Public/FirebaseFirestore/FIRDocumentReference.h
Firestore/Source/Public/FirebaseFirestore/FIRTransaction.h
Firestore/Source/Public/FirebaseFirestore/FIRWriteBatch.h
Firestore/core/src/bundle/bundle_serializer.cc
Firestore/core/test/unit/bundle/bundle_reader_test.cc

Nodejs Firestore creates a bundle with missing "seconds" and "nanos" properties when no documents or queries are added to the bundle. These should be valid to load, so this PR adds this ability.

Don't fail on empty bundles

---

.github/performance-integration-tests-prewarm.yml

b/211905617
According to https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule, 
> Scheduled workflows run on the latest commit on the default or base branch. 
Thus a PR to master branch is required to have the E2E pipeline automatically test the prototype for us.
Currently set to every 2 hours. Alternatively could keep the 4 hours interval and use the old `performance-integration-tests.yml` file instead of making a new one.

`schedule` integration tests to run on prewarm feature branch

---

FirebaseAuth/Sources/Backend/FIRAuthBackend.m
FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuthErrors.h
FirebaseAuth/Sources/SystemService/FIRSecureTokenService.m
FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.h
FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m
FirebaseAuth/Sources/Utilities/FIRAuthInternalErrors.h
FirebaseAuth/Tests/Unit/FIRUserTests.m

Add `FIRAuthErrorCodeUnsupportedPassthroughOperation` and `FIRAuthErrorCodeTokenRefreshUnavailable` as part of passthrough support.
API Proposal: go/firebase-auth-passthrough-sdk-api
#no-changelog

Define new error codes for passthrough errors

---

FirebaseInAppMessaging/CHANGELOG.md
FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m

Fix: Duplicate messages can occur when two campaigns are triggered by different events in In-App Messaging #9070
The flags to prevent multiple calling of inapp message was set after image downloading and so if two events are fired simultaneously, the second message display will be called prior to flag set. So adjusted the flag.

Fix : Duplicate messages can occur when two campaigns are triggered by different events

---

FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h

Fix #9087
Currently, the file `FIROptions.h` includes an example key that triggers security systems. A better solution can be to describe the key and not include one.
```
/**
* An iOS API key used for authenticating requests from your app, e.g.
* @"AIzaSyDdVgKwhZl0sTTTLZ7iTmt1r3N2cJLnaDk", used to identify your app to Google servers.
*/
@property(nonatomic, copy, nullable) NSString *APIKey NS_SWIFT_NAME(apiKey);
```

[Security] Change APIKey documentation

---

FirebaseMessaging/Apps/SwiftUISample/Podfile
FirebaseMessaging/Apps/SwiftUISample/SwiftUISample.xcodeproj/project.pbxproj
FirebaseMessaging/Apps/SwiftUISample/SwiftUISample.xcodeproj/xcshareddata/xcschemes/SwiftUISample.xcscheme
FirebaseMessaging/Apps/SwiftUISample/SwiftUISample/Assets.xcassets/AccentColor.colorset/Contents.json
FirebaseMessaging/Apps/SwiftUISample/SwiftUISample/Assets.xcassets/AppIcon.appiconset/Contents.json
FirebaseMessaging/Apps/SwiftUISample/SwiftUISample/Assets.xcassets/Contents.json
FirebaseMessaging/Apps/SwiftUISample/SwiftUISample/ContentView.swift
FirebaseMessaging/Apps/SwiftUISample/SwiftUISample/Info.plist
FirebaseMessaging/Apps/SwiftUISample/SwiftUISample/Preview Content/Preview Assets.xcassets/Contents.json
FirebaseMessaging/Apps/SwiftUISample/SwiftUISample/SwiftUISample.entitlements
FirebaseMessaging/Apps/SwiftUISample/SwiftUISample/SwiftUISampleApp.swift
FirebaseMessaging/CHANGELOG.md
FirebaseMessaging/Sources/FIRMessaging.m
FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.m

This fixes #8738.
The current implementation assumes APNS token is returned from apple system always after a new FCM token is fetched and stored during app install.
Seems like APNS token can be returned faster than that and currently the client only sends out request updating APNS token with FCM token when a cached FCM token exists.
Now update the logic to if no cached token exists and a new APNS token is set, always send a request to backend to update the FCM token with the apns token.
- Added a SwiftUI test app that uses the latest SwiftUI lifecycle
- Removed a redundant apns token key

Fix an issue that apns token is not sent during app fresh install

---

scripts/health_metrics/get_updated_files.sh

`common_commit` was the common ancestor of a target branch and base branch. This cannot be applied to fork. This variable block the workflow of spec testing on fork. This variable is not used in any workflows, and will be removed to unblock the workflow.
```
git diff --name-only remotes/origin/${GITHUB_BASE_REF} ${GITHUB_SHA} 
```
should be sufficient for spec testing on fork, where `remotes/origin/${GITHUB_BASE_REF}` is generally the `master` branch while `GITHUB_SHA` is a merge commit from a fork repo.

Enable checking diff on fork.

---

Firebase.podspec

[FirebaseMLModelDownloader.podspec](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseMLModelDownloader.podspec) supports osx as a target however the subspec in `Firebase.podspec` does not, this leads to build errors when adding the following as a dependency in podspecs:
```ruby
s.dependency 'Firebase/MLModelDownloader'
```
A work around for now is do just depend on an exact version of the ML pod directly e.g.:
```ruby
s.dependency 'FirebaseMLModelDownloader', '~> 8.10.0-beta'
```
I've tested ML Model Downloader pod does work on macOS, via a Flutter macOS app that downloads/deletes models:
- it builds without issues and downloading our test model works fine
* None

fix: `Firebase` podspec missing ML Model Downloader for macOS

---

Firebase.podspec

The deployment targets defined in https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAppCheck.podspec#L20-L23 are not reflected in the [`AppCheck` subspec](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase.podspec#L102-L104) in the main `Firebase` podspec. This PR updates them to match.
* N/A
* N/A

fix: issue where deployment targets for subspec `AppCheck` in `Firebase` podspec does not match `FirebaseAppCheck` podspec

---

FirebaseDatabase/Sources/Api/FIRDatabaseQuery.m
FirebaseDatabase/Sources/Utilities/FNextPushId.h
FirebaseDatabase/Sources/Utilities/FNextPushId.m
FirebaseDatabase/Tests/Unit/FNextPushIdTest.m

This is an attempt at fixing #8790. It's not very polished yet, and the test is currently too slow (loops over all single unicode character strings).

Attempt at fixing issue with getting next and previous push id

---

Firestore/CHANGELOG.md
Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
Firestore/core/src/local/local_store.cc
Firestore/core/test/unit/local/local_store_test.cc

This fixes a problem where the SDK receives an existence filter mismatch and clears the mapping of documents to targets, but does not receive another snapshot that also clears the snapshot version (i.e. the device went in the background and did was not able to actually process a re-run of the query).
The change that this PR makes is that we always reset the lastLimboFreeSnapshot version to 0 if we get a target mismatch.
Addresses #3249
Port of https://github.com/firebase/firebase-android-sdk/pull/3267

Clear the lastLimboFreeSnapshot version on existence filter mismatch

---

ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
ReleaseTooling/Sources/ZipBuilder/TargetPlatform.swift
ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
ReleaseTooling/Sources/ZipBuilder/main.swift

#9142 broke the Firebase zip distribution build because the Firebase build changed the minimum iOS version to 14 just for building.
This PR fixes that regression while still fixing the issue #9142 resolved. It also makes the 32 bit build management a bit more robust.

Fix 32bit Firebase Distro build regression

---

FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h

Fix #9201 
Clarify that FirebaseOptions APIs do not work for Analytics. Update rest of file to be Swifty.
#no-changelog

FirebaseOptions docs: Swift and Analytics exception

---

SharedTestUtilities/FIROptionsMock.m

While experimenting, I changed this file in #9084 but ended up faking instead of mocking for RC.
The FirebaseCore unit tests depend on the old values.

Restore SharedTestUtilities after breakage

---

FirebaseAuth/Tests/Sample/ApiTests/FacebookAuthTests.m
FirebaseAuth/Tests/Sample/ApiTests/GoogleAuthTests.m
FirebaseAuth/Tests/Sample/SwiftApiTests/AccountInfoTests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/AnonymousTests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/EmailPasswordTests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/FacebookTests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/GoogleTests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/TestsBase.swift

New tests succeed here: https://github.com/firebase/firebase-ios-sdk/runs/4823864218?check_suite_focus=true#step:7:749
#no-changelog

Add async/await variations for Auth Swift API tests

---

FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m
FirebaseInAppMessaging/Sources/Data/FIRIAMMessageDefinition.m
FirebaseInAppMessaging/Sources/Private/Data/FIRIAMMessageDefinition.h
FirebaseInAppMessaging/Tests/Unit/FIRIAMDisplayExecutorTests.m
FirebaseInAppMessaging/Tests/Unit/FIRIAMFetchFlowTests.m
FirebaseInAppMessaging/Tests/Unit/FIRIAMFetchResponseParserTests.m
FirebaseInAppMessaging/Tests/Unit/FIRIAMMessageClientCacheTests.m
FirebaseInAppMessaging/Tests/Unit/TestJsonDataWithTestMessageFromFetch.txt

refs: #9126 
`FIRIAMFetchResponseParser` is better not to ignore appData for test message. This PR fixes #9126 problems particaly but not completely.

pass appData for In-App Messaging's test message

---

FirebaseAuth/CHANGELOG.md
FirebaseAuth/Sources/SystemService/FIRSecureTokenService.m
FirebaseAuth/Tests/Unit/FIRAuthTests.m
FirebaseAuth/Tests/Unit/FIRUserTests.m

Partial fix for #6521, where the callback for `getIDToken` appears to sometimes be invoked hours after the method is called if the app goes into the background.
Not sure if this is the best fix, but this should at least alleviate some cases of this happening. For the remainder, developers can catch the token expiration error from the backend and request a new token.

Partial fix for expired ID token issue

---

FirebaseInAppMessaging/CHANGELOG.md

updating change log wrt https://github.com/firebase/firebase-ios-sdk/pull/9134

updating change log

---

FirebasePerformance/CHANGELOG.md
FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m

Adding 2 hidden metrics to `_fs`, regardless of RC flag `fpr_prewarm_detection`:
* `_fsapc`: ActivePrewarm counter. if ActivePrewarm identifies an app start as prewarmed, `_fsapc` of 1 will be added, otherwise a `_fsapc` of 0 will b added.
* `_fsddc`: Double dispatch counter. If double dispatch identifies an app as prewarmed, `_fsddc` of 1 will be added; if double dispatch identifies as not-prewarmed, 0 will be added; if double dispatch is disabled by developers through plist, then no custom metric will be added.

Fireperf: prewarm counters

---

Crashlytics/CHANGELOG.md
Crashlytics/Crashlytics/Components/FIRCLSUserLogging.m
Crashlytics/Crashlytics/FIRCrashlytics.m
Crashlytics/Crashlytics/FIRCrashlyticsReport.m
Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h
Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlyticsReport.h
Crashlytics/UnitTests/FIRCrashlyticsReportTests.m

Fixes a bug where setting a custom key's value to nil or passing nil as a user ID did not clear the value as expected.
Resolves #9241, #9212

Fixes a bug in custom key and user ID logging

---

Firestore/CHANGELOG.md
Firestore/core/src/core/order_by.cc

There have been multiple reports of crashes with the message "Trying to compare documents on fields that don't exist". However, debugging these crashes has been fruitless. This PR updates the assertion message to contain additional information to help with future debugging.
Some of the issue reports of this crash include #9258, #8661, #7082, and #5238.

Firestore: Add more details to the assertion failure in OrderBy::Compare()

---

FirebaseCombineSwift/Sources/Functions/HTTPSCallable+Combine.swift
FirebaseFunctions/Tests/CombineUnit/HTTPSCallableTests.swift
FirebaseFunctionsSwift/Sources/Functions.swift
Package.swift
SwiftPMTests/swift-test/main.swift

Port the Functions combine tests to depend on the FirebaseFunctionsSwift instead of FirebaseFunctions
cc: @peterfriese

Combine tests ported to depend on Swift Functions

---

Firestore/core/src/local/leveldb_key.cc
Firestore/core/src/model/field_index.h
Firestore/core/src/util/ordered_code.cc

This inconsistency was found during a copybara of this code into google3. Googlers can see cl/428004925 for details.
No code or functionality is changed by this PR; merely the names of some function/method parameters.
#no-changelog

Fix occurrences of inconsistent parameter names between declaration and definition

---

Firestore/core/src/local/leveldb_document_overlay_cache.cc
Firestore/core/test/unit/local/document_overlay_cache_test.cc

There were several latent bugs in `LevelDbDocumentOverlayCache` where it first searched the LevelDb database for an entry with a given key prefix, but then failed to ensure that the document key encoded in the LevelDb key was exactly equal to the requested key.
This resulted in at least two bugs:
1. `GetOverlay()` would incorrectly return the overlay for some document in a subcollection if the requested document did not have an overlay.
2. `SaveOverlays()` would delete the overlay for some document in a subcollection if the document with the given DocumentKey did not have an overlay.
Googlers see b/210002758 for details.
#no-changelog

Fix bugs in LevelDbDocumentOverlayCache where it failed to check for equality of the DocumentKey

---

FirebasePerformance/CHANGELOG.md
FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m
FirebasePerformance/Tests/Unit/FPRAppActivityTrackerTest.m

b/220342323
Reading `ActivePrewarm` in `appDidBecomeActiveNotification` always results in `null`. Presumably Apple deletes the `ActivePrewarm` env variable some time after `didFinishLaunching`, which is the latest callback I have confirmed where reading `ActivePrewarm` works. 
Move reading `ActivePrewarm` to `+load()`.
Additionally switch to using `@avaiable(iOS 13, *)` for version and platform checks. This aligns Hub, and is similar to Firebase App Monitoring (cl/424623478).
* Perhaps remove `didFinishLaunching` callback and the code for double dispatch as we learned it did not work well.

Fireperf: fix ActivePrewarm

---

FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMBaseRenderingViewController.h

Fix a small typo in code docs for FIRIAMBaseRenderingViewController.

Fix typo in FIRIAMBaseRenderingViewController

---

Firestore/core/src/local/leveldb_document_overlay_cache.cc
Firestore/core/src/local/leveldb_document_overlay_cache.h
Firestore/core/src/local/leveldb_key.cc
Firestore/core/src/local/leveldb_key.h
Firestore/core/test/unit/local/leveldb_document_overlay_cache_test.cc
Firestore/core/test/unit/local/leveldb_key_test.cc

The `LevelDbDocumentOverlayCache` class was added in In #9345, but with recognized performance issues. This PR improves the performance of `GetOverlays(ResourcePath, ...)` from θ(N), where `N` is the total size of the table, to θ(m(log(m)), where `m` is the number of overlays returned. 
This index implementation is directly based on the implementation for the `RemoveOverlaysForBatchId()` method, as implemented in #9386. See that PR for a deeper explanation of the implementation details.
This PR introduces the class `LevelDbDocumentOverlayIndexKey`, which is used as the base class for all index keys in the `document_overlays` table. As of this PR, it has two subclasses: `LevelDbDocumentOverlayLargestBatchIdIndexKey` (modified in this PR to subclass it) and …

Improve performance of LevelDbDocumentOverlayCache::GetOverlays(ResourcePath, ...)

---

Firestore/core/src/local/document_overlay_cache.h
Firestore/core/src/local/leveldb_document_overlay_cache.cc
Firestore/core/src/local/leveldb_document_overlay_cache.h
Firestore/core/src/local/leveldb_key.cc
Firestore/core/src/local/leveldb_key.h
Firestore/core/src/local/memory_document_overlay_cache.cc
Firestore/core/src/local/memory_document_overlay_cache.h
Firestore/core/src/model/document_key.cc
Firestore/core/src/model/document_key.h
Firestore/core/test/unit/local/leveldb_document_overlay_cache_test.cc
Firestore/core/test/unit/local/leveldb_key_test.cc

The `LevelDbDocumentOverlayCache` class was added in In #9345, but with recognized performance issues. This PR improves the performance of `GetOverlays(absl::string_view)` from θ(N), where `N` is the total size of the table, to θ(m(log(m)), where `m` is the number of overlays returned.
A similar optimization was implemented for `GetOverlays(ResourcePath)` in #9401 and for `RemoveOverlaysForBatchId()` in #9386.
Googlers see b/210002758 for details.
#no-changelog

Improve performance of LevelDbDocumentOverlayCache::GetOverlays(absl::string_view)

---

Firestore/Example/Firestore.xcodeproj/project.pbxproj
Firestore/core/src/local/document_overlay_cache.h
Firestore/core/src/local/leveldb_document_overlay_cache.cc
Firestore/core/src/local/leveldb_document_overlay_cache.h
Firestore/core/src/local/local_serializer.cc
Firestore/core/src/local/memory_document_overlay_cache.cc
Firestore/core/src/local/memory_document_overlay_cache.h
Firestore/core/src/model/model_fwd.h
Firestore/core/src/model/overlay.cc
Firestore/core/src/model/overlay.h
Firestore/core/test/unit/local/document_overlay_cache_test.cc
Firestore/core/test/unit/model/overlay_test.cc

The `Overlay` class was added in #9301, creating a new namespace `firestore::model::mutation`. This was done because the [`Overlay` class in the Android SDK](https://github.com/firebase/firebase-android-sdk/blob/d6df524d4ba800a5a3bd42162ce711093290053b/firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Overlay.java) (from which it was ported) is in a similarly-named Java package. It turns out, however, that these two SDKs merely use different file/package/namespace layouts and the `Overlay` class should have been added into the existing namespace `firestore::model`. This PR moves the `Overlay` class into that correct location.
Googlers see b/210002758 for details.
#no-changelog

Move firestore::model::mutation::Overlay into its parent namespace

---

Firebase.podspec
FirebaseABTesting.podspec
FirebaseAppCheck.podspec
FirebaseAppDistribution.podspec
FirebaseAuth.podspec
FirebaseAuthTestingSupport.podspec
FirebaseCore/CMakeLists.txt
FirebaseCrashlytics.podspec
FirebaseDatabase.podspec
FirebaseDynamicLinks.podspec
FirebaseFirestore.podspec
FirebaseFirestoreTestingSupport.podspec
FirebaseFunctions.podspec
FirebaseFunctionsTestingSupport.podspec
FirebaseInAppMessaging.podspec
FirebaseInstallations.podspec
FirebaseMessaging.podspec
FirebasePerformance.podspec
FirebaseRemoteConfig.podspec
FirebaseRemoteConfigSwift.podspec

I tripped CI in https://github.com/firebase/firebase-ios-sdk/pull/9373 to see what work needed to be done to get this ready for merging into `v9`.  
Here is some context:
1. Add a `swift_version` to all pods that depend on `FirebaseCore`. The FirebaseCore's podspec was changed to include the swift heartbeat code. Because of the presence of Swift in the spec source, CocoaPods will consider FirebaseCore to be a Swift pod. Swift pods should specify a `swift_version` to avoid a linting warning. [Example failure](https://github.com/firebase/firebase-ios-sdk/runs/5279145928?check_suite_focus=true#step:4:369) from #9373. 
I've set the `swift_version` to `5.3`.
3. Firestore CI will build all of FirebaseCore via CMake. Currently, the Swift heartbeat code has not been configured to build via CMake. …

[Heartbeat Logging] Update FirebaseCore dependents for heartbeat logging changes

---

Firestore/Swift/Source/Codable/DocumentSnapshot+ReadDecodable.swift

Fix #9437 by renaming a variable to avoid symbol resolution ambiguity on Xcode 12.4 (and perhaps other versions too).

Renamed variable to avoid symbol resolution ambiguity with Xcode 12.4

---

SwiftDashboard.md

Codable changes:
- FDL -> n/a
- Msg -> n/a (cc chliang@)
This also means the Codable row is complete.
SwiftUI Lifecycle:
- AppDistro -> n/a
- Perf -> ❌  to research more prewarming and app startup
SwiftUI Interop:
- Core -> n/a
- ApC -> n/a
- FDL -> n/a
- Firestore -> ✔ (for the property wrapper, nothing else to address there likely outside more property wrappers)
- Functions -> n/a
- Installations -> n/a
- Messaging -> n/a
- MLModelDownloader -> n/a
- RC -> n/a

Update Swift dashboard from further audits

---

SwiftDashboard.md

Reduced the amount of whitespace and tried better alignment for
plaintext editing.
Moved the following products property wrappers to n/a:
- Analytics
- AppCheck
- AppDistro
- Core
- Crashlytics
- FDL
- Functions
- FIAM
- Installations
- Mssaging
- MLModelDownloader
- Perf
- Storage
Docs scrub marked as complete for MLModelDownloader (that's it
unfortunately)

Updated to the Swift dashboard

---

docs/resources/firebase_from_dynamic_framework.svg
docs/resources/firebase_from_static_framework.svg

Use the ![Display Rich Diff](https://user-images.githubusercontent.com/1097316/159016089-1ebf22a3-b97a-49d0-9c2d-1dd4519e7736.png) button for a visual difference.
Light mode is unaffected.

Add white background to drawings for improved dark mode readability

---

FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.m

[Closes #9275]
* Specified `InstallationsErrorDomain` as the `NS_SWIFT_NAME` of FirebaseInstallations’s `kFirebaseInstallationsErrorDomain`
⚠️ Breaking Changes: Based on the [issue](https://github.com/firebase/firebase-ios-sdk/issues/9275), this PR should land in Firebase v9.

[#9275] Added Swift Name to `kFirebaseInstallationsErrorDomain`

---

Firestore/Protos/CMakeLists.txt
Firestore/Protos/build_protos.py
Firestore/core/CMakeLists.txt

Fix cmake build for macOS 12.3 where `python` no longer exists.

---

FirebaseStorageSwift/Sources/AsyncAwait.swift
FirebaseStorageSwift/Sources/StorageReference.swift
FirebaseStorageSwift/Tests/Integration/StorageAsyncAwait.swift

Explicit async/await implementations for previous implicit ones

---

FirebaseInstallations/CHANGELOG.md
FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.m
FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallationsErrors.h
FirebaseInstallations/Source/Tests/Unit/Swift/InstallationsAPITests.swift

Followup to #9395 to fix #9275.  
- NS_SWIFT_NAME in header instead of .m
- Add a test
- Release note

Swiftify symbol name for Swift

---

.github/workflows/spectesting.yml

I'm thinking this should speed up CI since these are failing on `v9` anyway.
Disabled and added `v9` TODO to re-enable when merging into `master`.
#no-changelog

Disable `specs_testing` on `v9`.

---

Firestore/CHANGELOG.md
Firestore/core/src/core/query.cc

Improve the assertion failure message in `Query::Comparator()` to also include the result of calling `ToString()`. This may help find the root cause of https://github.com/firebase/firebase-ios-sdk/issues/9258.

Include ToString() in Firestore's Query::Comparator() assertion failure message

---

Firestore/core/src/index/index_entry.h
Firestore/core/src/local/leveldb_index_manager.h

These inconsistencies cause warnings when the code is copied into google3 via copybara.
#no-changelog

Fix inconsistent argument names in .h/.cc files

---

FirebasePerformance/CHANGELOG.md
FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m
FirebasePerformance/Sources/Configurations/FPRConfigurations.h
FirebasePerformance/Tests/Unit/FPRAppActivityTrackerTest.m

Remove the double dispatch code from the pre-warm detection.
The remote config flag will now contain just 3 states:
1. Disable all app starts
2. Active prewarm enabled/Disabled
3. Send all app starts

Remove the double dispatch code from the pre-warm detection.

---

.github/workflows/firestore.yml
FirebaseCore/CMakeLists.txt
FirebaseCore/Extension/FIRAppInternal.h
FirebaseCore/Extension/FIRHeartbeatLogger.h
FirebaseCore/Sources/FIRApp.m
FirebaseCore/Sources/FIRHeartbeatLogger.m

Fixes Firestore CMake CI failues on `v9b`. 
Added a macro to avoid building symbols from new Swift `HeartbeatCoreInternal` module. See comment with context:
https://github.com/firebase/firebase-ios-sdk/blob/614e311d223e3c58bf329258bd86252e78bba8d5/FirebaseCore/CMakeLists.txt#L34-L41
I `ifdef`'d all symbols related to the Swift `FirebaseCoreInternal` module. This is a slightly better bandaid than what I had before.
- I believe this issue surfaced in #9531 when I cherry-picked the `clang-format14` update (which styled a Firestore file).
- This issue is causing Firestore CI failures in #9512.
#no-changelog

[v9, Infra] Fix `FirebaseCore` CMake build error for Firestore CI

---

Firestore/CHANGELOG.md
Firestore/core/src/core/order_by.cc

Modify `OrderBy::Compare()` to test for the key field path using `field_.IsKeyFieldPath()` instead of `field_ == FieldPath::KeyFieldPath()`.
This is an attempted fix for https://github.com/firebase/firebase-ios-sdk/issues/9258, which reports sporadic crashes with an assertion message like the following:
```
FIRESTORE INTERNAL ASSERTION FAILED: Trying to compare documents on fields that don't exist; field_path=__name__, lhs=users/16451, rhs=users/16451, value1.has_value()=false, value2.has_value()=false
```
This fix is based on the following code in `OrderBy::Compare()`:
https://github.com/firebase/firebase-ios-sdk/blob/82f163bd86566f83c5d7572a1c2c0024a04eb4dc/Firestore/core/src/core/order_by.cc#L70-L77
When `__name__` is the field being compared then `field_ == FieldPath::KeyFieldPath()` …

order_by.cc: Use IsKeyFieldPath() instead of == FieldPath::KeyFieldPath()

---

FirebaseStorage.podspec
FirebaseStorageSwift/Sources/StorageObservableTask.swift
FirebaseStorageSwift/Tests/Unit/StorageAPITests.swift

- After verifying in `master` branch, add build tests for Storage Swift APIs.
- Fix two StorageObservableTask signature issues
- Mark the v9 breaking changes
- Build new tests in both SPM and CocoaPods

Storage Swift API tests and fixes

---

FirebasePerformance/Tests/Unit/Configurations/FPRRemoteConfigFlagsTest.m

Fix a regression test failure introduced by the new exception introduced in #9552 
It preserves the previous (probably unintended behavior) of passing nil to `[[FPRRemoteConfigFlags alloc] initWithRemoteConfig:`
Now an unconfigured initWithRemoteConfig: is throwing instead of returning nil.

Fix perf test regression from recent RC change

---

.github/workflows/app_check.yml
.github/workflows/core.yml
.github/workflows/core_extension.yml
.github/workflows/core_internal.yml
FirebaseAppCheck.podspec
FirebaseCore.podspec
FirebaseCoreInternal.podspec

We don't need to publish the `HeartbeatLoggingTestingUtils.podspec` so I'm removing the TODO's that mention plans to publish it.
See discussion here: https://github.com/firebase/firebase-ios-sdk/pull/9543#discussion_r839079133
#no-changelog

[v9, Cleanup] Remove irrelevant comments

---

FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/AccountInfoTests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/AnonymousTests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/EmailPasswordTests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/FacebookTests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/GoogleTests.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/SwiftAPI.swift
FirebaseAuth/Tests/Sample/SwiftApiTests/TestsBase.swift
FirebaseCore/Tests/SwiftUnit/CoreAPITests.swift
FirebaseDatabase/Tests/Unit/Swift/DatabaseAPITests.swift
FirebaseFunctions/CHANGELOG.md
FirebaseFunctions/Sources/Callable+Codable.swift
FirebaseFunctions/Sources/HTTPSCallable.swift
FirebaseFunctions/Tests/Integration/IntegrationTests.swift
FirebaseFunctions/Tests/Unit/FunctionsAPITests.swift
FirebaseInstallations/Source/Tests/Unit/Swift/InstallationsAPITests.swift
FirebaseMessaging/Tests/UnitTestsSwift/FIRMessagingAPITest.swift
FirebaseRemoteConfigSwift/Tests/SwiftAPI/AsyncAwaitTests.swift
FirebaseRemoteConfigSwift/Tests/SwiftAPI/Codable.swift
FirebaseRemoteConfigSwift/Tests/SwiftAPI/Value.swift
FirebaseStorage/CHANGELOG.md
FirebaseStorageSwift/Sources/AsyncAwait.swift
Firestore/Swift/Source/AsyncAwait/CollectionReference+AsyncAwait.swift
Firestore/Swift/Source/AsyncAwait/Firestore+AsyncAwait.swift
Firestore/Swift/Source/Codable/DocumentReference+ReadDecodable.swift
Firestore/Swift/Tests/API/BasicCompileTests.swift
Firestore/Swift/Tests/Integration/AsyncAwaitIntegrationTests.swift

This bumps the required compiler version to 5.5.2 which was included in
Xcode 13.2, where backporting was first introduced.
This breaks less developers and enables developers who aren't using
these APIs to still compile using Xcode 13.0 and 13.1.
As far as I can tell, the only breakage this includes now is developers
who are using Xcode 13.0 or 13.1, targeting iOS 15 and using one of
these 7 APIs. It will result in a compiler error and they'll have to
either use the completion handler version or upgrade to Xcode 13.2+ to
fix the compilation error.
Fixes #9483.

Enable async/await APIs for iOS 13, etc.

---

Firestore/core/src/local/local_documents_view.h
Firestore/core/src/local/local_store.cc
Firestore/core/src/local/local_store.h
Firestore/core/test/unit/local/counting_query_engine.cc
Firestore/core/test/unit/local/counting_query_engine.h
Firestore/core/test/unit/local/query_engine_test.cc

Create and populate the `DocumentOverlayCache` instance variables of `LocalStore` and `LocalDocumentsView`, in preparation for actually using them.
This change has no effects on runtime behavior, but the instance variables in question will get used later on once the rest of overlays are ported from the Android SDK.
Googlers see b/210002758 for details.
#no-changelog

Wire DocumentOverlayCache into LocalStore and LocalDocumentsView

---

FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
FirebaseAppDistribution/Sources/Public/FirebaseAppDistribution/FIRAppDistribution.h
FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallationsErrors.h
FirebaseInstallations/Source/Tests/Unit/Swift/InstallationsAPITests.swift
FirebaseMessaging/Sources/FIRMessaging.m
FirebaseMessaging/Sources/NSError+FIRMessaging.h
FirebaseMessaging/Sources/NSError+FIRMessaging.m
FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessaging.h
FirebaseMessaging/Tests/UnitTestsSwift/FIRMessagingAPITest.swift
FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h
Firestore/Source/Public/FirebaseFirestore/FIRFirestoreErrors.h
Firestore/Swift/Tests/API/BasicCompileTests.swift

Use NS_ERROR_ENUM where possible for Firebase SDKs. This is a breaking change for Swift users that greatly improves error handling:
```swift
// Completion Handlers
messaging.unsubscribe(fromTopic: topic) { error in
if let error = error {
// Missing: domain check. Need to publicize the domain.
switch UInt((error as NSError).code) {    // old
case MessagingError.timeout.rawValue:     // old
tryAgain()
default:
print("Couldn't unsubscribe.")
}
return
}
// no error
}
// async/await
do {
try await messaging.unsubscribe(fromTopic: topic)
// Missing: domain check. Need to publicize the domain.
} catch let error as NSError where MessagingError(rawValue: UInt(error.code)) == .timeout {  // old
// timeout
} catch {
print("Couldn't unsubscribe.")
}
// Installations
do {
_ = try await …
```

Swift Error Improvements

---

FirebaseCombineSwift/Sources/Auth/Auth+Combine.swift
FirebaseCombineSwift/Sources/Firestore/Firestore+Combine.swift
FirebaseCombineSwift/Sources/Functions/Functions+Combine.swift
FirebaseCombineSwift/Sources/Storage/Storage+Combine.swift
FirebaseCore/Sources/FIRApp.m

This PR adds a Swift component for Firebase Combine, so that Combine will be included in the user agent.
This is a replacement for PR #9363 and contains all code already discussed there, and addresses the most recent comments/
#no-changelog

Register Combine modules with Swift component system

---

Firestore/CHANGELOG.md
Firestore/Source/Public/FirebaseFirestore/FIRFirestore.h
Firestore/Swift/Source/AsyncAwait/Firestore+AsyncAwait.swift
Firestore/Swift/Tests/Integration/AsyncAwaitIntegrationTests.swift

Hopefully fixes https://github.com/firebase/firebase-ios-sdk/issues/9426.

Fix nil async/await import error

---

.github/workflows/auth.yml
FirebaseAuth.podspec
FirebaseAuth/Sources/Auth/FIRAuth.m
FirebaseAuth/Sources/Auth/FIRAuth_Internal.h
FirebaseAuth/Sources/Backend/FIRAuthBackend.m
FirebaseAuth/Sources/Backend/FIRAuthRequestConfiguration.h
FirebaseAuth/Sources/Backend/FIRAuthRequestConfiguration.m
FirebaseAuth/Sources/User/FIRUser.m
FirebaseAuth/Tests/Sample/Podfile
FirebaseAuth/Tests/Unit/FIRAuthBackendRPCImplementationTests.m
FirebaseAuth/Tests/Unit/FIRFakeBackendRPCIssuer.h
FirebaseAuth/Tests/Unit/FIRFakeBackendRPCIssuer.m
Package.swift

- Migrated Auth's use of v1 heartbeat API to v2 heartbeat API
- Added two unit tests to assert that the request contains expected heartbeat payload information
The `FIRAuthBackendRPCIssuerImplementation` class made it rather difficult to add tests so I tried to do so in the least invasive way possible to get some coverage. It might be worth investigating what a refactor could like there to more easily inject dependencies of the class.
#no-changelog

[Heartbeat Logging] Migrate Auth from using `FIRHeartbeatInfo` to `FIRHeartbeatLogger` 
