- Example/Messaging/App/AppDelegate.swift
This demonstrates the simple property, `shouldEstablishDirectChannel`, that can be set to `true` to have Firebase Messaging manage a direct, socket-based channel to the FCM server. This allows for direct "data" messages to be sent from the server to the SDK.
> Enable direct channel in the sample app

- AuthSamples/ApiTests/AuthCredentialsTemplate.h
- AuthSamples/ApiTests/FirebearApiTests.m
- AuthSamples/Sample/AuthCredentialsTemplate.h
- AuthSamples/Samples.xcodeproj/project.pbxproj
In addition to fixing ApiTests and using the official term "Custom Auth", this PR also puts all of ApiTests' credentials including test user names into its own template, so developers won't need to bother with them if them don't expect ApiTests would be affected.
> Fixes ApiTests and separates its credentials from Sample

- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
Maybe it was already swizzled, or some other issue. Either way, it would be good to log this error, as it might help us / developers diagnose an issue.
> Log an error if for some reason we can't add a method to a class

- Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.h
- Firebase/Auth/Source/FIRAuthErrorUtils.m
Adds reference docs error documentation to FIRPhoneAuthProvider.
Also fixes small typo in FIRAuthErrorUtils.
> Update FIRPhoneAuthProvider reference docs

- AuthSamples/Sample/MainViewController.m
These errors were already being logged in the sample app's console but are now made more obvious by displaying a popup.
Also changes the title for the manual tests in the sample app to "Automated" tests, which better describes their function.
> Adds friendly error messages to phone auth sample

- Firebase/Auth/Source/FIRAuth.m
- Firebase/Core/FIRApp.m
- Firebase/Core/FIROptions.h
Error messages should include Swift references on top of the
Objective-C references.
Fixes issue #39
> Update error messages to be Swift friendly.

- AuthSamples/Podfile
- AuthSamples/Sample/ApplicationDelegate.m
- AuthSamples/Sample/MainViewController.m
- AuthSamples/Sample/SettingsViewController.m
- AuthSamples/Samples.xcodeproj/project.pbxproj
This fixes Auth Sample app import paths for external dependencies and private headers. There should no longer be two builds, one for GOOGLE3 and one for the rest of the world.
> Fixes Auth Sample app import paths.

- Firebase/Firebase/module.modulemap
- FirebaseDev.podspec
As I couldn't use Firebase as a dependency app, I followed [a CocoaPods developer advice suggesting to remove the modulemap file](https://github.com/CocoaPods/CocoaPods/issues/6138#issuecomment-258960994) to see if it worked. It did and I was able to build a Pod using Firebase as a dependency. 
It creates this diff in the module map of the pod. Not 100% sure it's correct (especially as FirebaseDev might not be a good module name), but probaly worth a discussion.
```diff
1c1,3
< module Firebase {
---
> framework module FirebaseDev {
>   umbrella header "FirebaseDev-umbrella.h"
> 
3,4c5,6
<   header "Firebase.h"
< }
\ No newline at end of file
---
>   module * { export * }
> }
```
> Remove modulemap for usage as a Pod dependency

- Firebase/Database/Api/FIRDatabase.h
FIRDatabase's initializer is inherited from NSObject and causes subtle bugs if called. See #31 for more information about this change
> mark FIRDatabase init unavailable

- Example/Auth/Tests/FIRAuthTests.m
- Example/Auth/Tests/FIRSignUpNewUserResponseTests.m
- Firebase/Auth/Source/FIRAuth.m
- Firebase/Auth/Source/FIRAuthErrorUtils.m
- Firebase/Auth/Source/FIRAuthErrors.h
- Firebase/Auth/Source/Private/FIRAuthErrorUtils.h
- Firebase/Auth/Source/Private/FIRAuthInternalErrors.h
Adds appropriate error handling for missing email in the createUserWithEmail:password:completion: flow.
Also fixes a few typos.
> Handle missing email error

- Example/Auth/Tests/FIRAuthTests.m
master and the macOS branch were inconsistent about naming of kPassword and kFakePassword. I fixed the compile failure by making it kFakePassword. Auth team may want to revisit.
With this change All iOS and MacOS unit tests succeed.
> Fix build break from macOS - Auth merge

- Example/Firebase.xcodeproj/project.pbxproj
This got lost in the transfer to new Xcode targets. The reasons why Messaging iOS has a specific bundle id is that this bundle is whitelisted for internal Google development, making it easier for folks that work on FCM to test with this app.
> Restore bundle ID and dev team for Messaging iOS

- Firebase/Messaging/Public/FIRMessaging.h
The header comments are directly reflected in Firebase documentation, so this improves that as well.
> Fix formatting inconsistencies in Messaging header

- Firebase/Auth/Source/FIRAuth.h
- Firebase/Auth/Source/FIRAuth.m
Adds error documentation pertaining to phone authentication to the signInAndRetrieveDataWithCredential:completion: method
> Documents phone auth with reference docs

- Firebase/Auth/Source/FIRUser.m
Encodes and decodes the phone number property of FIRUser.
Fixes #67
> Add phone number property to NSSecureCoding

- Example/Auth/Tests/FIRAuthTests.m
- Example/Auth/Tests/FIRUserTests.m
- Firebase/Auth/Source/FIRAuth.m
- Firebase/Auth/Source/FIRUser.m
- Firebase/Auth/Source/FirebaseAuth.h
- Firebase/Auth/Source/Private/FIRAuth_Internal.h
- Firebase/Auth/Source/RPCs/FIRAuthBackend.m
- Firebase/Core/FIRAppEnvironmentUtil.m
- Firebase/Core/FIRNetworkURLSession.m
- Firebase/Core/FIRReachabilityChecker.m
- Firebase/Database/Core/FPersistentConnection.m
- Firebase/Database/Core/FRepo.m
- Firebase/Database/Persistence/FLevelDBStorageEngine.m
- Firebase/Database/Realtime/FWebSocketConnection.m
- Firebase/Database/third_party/SocketRocket/FSRWebSocket.m
- Firebase/Storage/FIRStorageUtils.m
The #if check added in the macOS PR was depending on the pch inserted into the CocoaPods build to import TargetConditionals.h and define the TARGET_OS's. 
This PR makes the build succeed outside of CocoaPods by importing Foundation wherever the TARGET_OS is checked.
> Add Foundation import so TARGET_OS_IOS (or other TARGET_OS_*) gets defined

- Firebase/Auth/Source/RPCs/FIRAuthBackend.m
This is for the backend to log in the same way as in other platforms.
> Adds client version header to Firebase Auth server requests.

- README.md
As we are adding in support for things like macOS which can't (yet) be officially supported, added a section in the README making clear that we want to allow community-support efforts like this to exist, but that these efforts don't imply or infer that Firebase will be officially providing documentation, technical support, etc. for these efforts.
Also demote the specific SDK sections by one level, making the README a bit more parseable.
> Add section explaining community supported efforts

- AuthSamples/Sample/FacebookAuthProvider.m
- AuthSamples/Sample/GoogleAuthProvider.m
This is to make the code more flexible in other build environments.
> Uses framework imports for GoogleSignIn, FBSDKCoreKit, and FBSDKLoginKit

- .travis.yml
- AuthSamples/Podfile
- AuthSamples/Samples.xcodeproj/project.pbxproj
- AuthSamples/SwiftSample/AppDelegate.swift
- AuthSamples/SwiftSample/ViewController.swift
- Example/Firebase.xcodeproj/project.pbxproj
- Example/Messaging/App/iOS/AppDelegate.swift
- Example/Messaging/App/iOS/MessagingViewController.swift
- Example/Messaging/App/iOS/NotificationsController.swift
- Example/Podfile
- Firebase/Auth/FirebaseAuth.podspec
- Firebase/Core/FirebaseCore.podspec
- Firebase/Database/FirebaseDatabase.podspec
- Firebase/Messaging/FirebaseMessaging.podspec
- Firebase/Storage/FirebaseStorage.podspec
- FirebaseCommunity.podspec
- README.md
Renamed to better delineate the purpose of the FirebaseCommunity pod as opposed to the Firebase pod.  See the [README](https://github.com/firebase/firebase-ios-sdk/blob/master/README.md) for more details.
> Rename FirebaseDev to FirebaseCommunity

- Firebase/Database/Realtime/FWebSocketConnection.m
This should be a safe change since the timer function 'nop' is only ever run after the WebSocket is initialized.
This works around potential issues in the WebSocket layer after we close the connection and should address Google-internal issue: https://b.corp.google.com/issues/62363018
> Not sending messages to closed websocket connections

- Firebase/Auth/Source/FIRAuth.m
Adds UIKit import to FIRAuth implementation. UIApplicationDidBecomeActiveNotification is used by this class so UIKit should be explicitly imported.
> Add UIKit import to FIRAuth implementation

- Example/Database/Tests/Integration/FEventTests.m
- Example/Database/Tests/Unit/FLevelDBStorageEngineTests.m
- Firebase/Database/Persistence/FLevelDBStorageEngine.m
NSJSONSerialization parses long values as doubles and returns NSNumber that are backed by doubles to the users. For NSNumbers that can be stored as longs, we can overwrite this behavior by re-running the initialization step.
This addresses https://github.com/firebase/firebase-ios-sdk/issues/91.
> Fixing parsing for double numbers

- .travis.yml
Hopefully helps avoid the `no output received in the last 10m` error that occasionally happens on travis.
> Use verbose pod lib lint in travis

- .travis.yml
200 is too much easily scroll up to check otherwise successful test runs for 65 error codes
> Change pod spec lint verbose tail to 40

- Example/Storage/Tests/Unit/FIRStorageMetadataTests.m
- Firebase/Storage/FIRStorageMetadata.m
Adding the missing size parameter to StorageMetadata.
As per Google internal issue: https://b.corp.google.com/issues/38041797
> Adding size to Storage's NSDictionary representation

- Example/Core/Tests/FIRAppTest.m
- Firebase/Core/FIRApp.m
- Firebase/Core/Private/FIRAppInternal.h
This lets other SDKs check if the default `FIRApp` is set up without
accessing it, which causes unnecessary log messages to appear.
> Add method to check if `defaultApp` is configured.

- Example/Database/Tests/Unit/FLevelDBStorageEngineTests.m
The "extremeDouble" tests for the iOS RTDB SDK rely on the fact that NSJSONSerialization can't correctly handle tiny double values. This has been fixed in iOS 11 and the tests fail.
I don't believe the tests add value in iOS 11 and hence I disabled them.
> Disabling NSJSON edge case test on iOS 11

- Example/Core/App/iOS/FIRAppDelegate.m
- Firebase/Core/FIRLogger.m
- Fixing the FIRLogger init cost by moving the  initialization of sMessageCodeRegex under #ifdef DEBUG
- Adding [FIRApp configure] to the Core example app to make Core changes testing easier
> Fixing FIRLogger init cost

- Example/Database/Tests/Unit/FLevelDBStorageEngineTests.m
- Firebase/Database/Persistence/FLevelDBStorageEngine.h
- Firebase/Database/Persistence/FLevelDBStorageEngine.m
We currently fail the RTDB startup if the level DB cache is corrupted (https://github.com/firebase/firebase-ios-sdk/issues/144)
Since this is just a cache file, this PR introduces code that tries to deletes the invalid cache in order to recover. 
I have also tested this manually by corrupting the cache in the Simulator.
> Purge persistence cache if we can't load from it

- Example/Database/Tests/Unit/FLevelDBStorageEngineTests.m
Another test started failing in Xcode 9 beta 4. Please confirm that it's the same situation as the last bug you fixed.
> Disable another test that depended on broken pre-iOS 11 small doubles

- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessaging+FIRApp.m
Currently Messaging will use the most recent FIRApp configured which
isn't obvious. This will limit it to only the default FIRApp.
> Configure Messaging for default FIRApp only.

- Firebase/Messaging/Public/FIRMessaging.h
This is a slight tweak to the block comment describing `-retrieveFCMTokenForSenderID:completion:`, to more explicitly mention that this can be used to support the scenario of allow multiple senders to send notifications to the same client app.
> Add comment about how multiple senders are supported

- .clang-format
- Example/Core/App/macOS/main.m
- Example/Core/Tests/FIRAppAssociationRegistrationUnitTests.m
- Example/Core/Tests/FIRAppTest.m
- Firebase/Core/FIRLogger.m
Consider this as a feature request :-).
> Prevent clang-format from merging short functions into a single line

- AuthSamples/Sample/AppManager.m
- AuthSamples/Sample/SettingsViewController.m
Because the umbrella header isn't accessible in other build environment.
> Adjusts header imports in Auth sample to avoid FirebaseCore.h

- AuthSamples/Sample/ApplicationDelegate.m
- AuthSamples/Sample/ApplicationTemplate.plist
- AuthSamples/Sample/MainViewController.m
- Firebase/Auth/Source/FIRActionCodeSettings.m
- Firebase/Auth/Source/Public/FIRActionCodeSettings.h
- Sets default iOS bundle ID for action code settings.
- Allows the Auth sample to handle in-app action code on iOS 8-.
- Adds an entry in the Auth sample app to verify email in app.
> Action code fixes and improvements

- AuthSamples/Sample/MainViewController.m
- Firebase/Auth/CHANGELOG.md
- Firebase/Auth/Source/FIRAuth.m
- Firebase/Auth/Source/Public/FIRAuth.h
Also allow in-app action code handling to cancel and leave the code in pasteboard.
> Adds the missing FIRActionCodeOperationRecoverEmail.

- Firebase/Auth/Source/FIRAuth.m
- Firebase/Auth/Source/FIRAuth_Internal.h
- Firebase/Core/FIRApp.m
- Firebase/Core/Private/FIRAppInternal.h
- Firebase/Database/Api/FIRDatabase.m
- Firebase/Database/Login/FAuthTokenProvider.h
- Firebase/Database/Login/FAuthTokenProvider.m
- Firebase/Database/Public/FIRDatabase.h
SDKs that want to listen for the internal Auth notifications needed
to copy the notification strings to their own SDK instead of relying
on Auth's definition in order to avoid a dependency on Auth. By moving
them to Core, SDKs can use the constants without taking on another
dependency.
> Move Auth notification constant into Core.

- AuthSamples/Sample/MainViewController.m
- Example/Auth/Tests/FIRGetOOBConfirmationCodeResponseTests.m
- Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Also allows the Auth sample app to test all combination of `handleCodeInApp` and continue URL.
> Fixes an incorrect assumption of Auth server error message.

- Firebase/Messaging/FIRMessaging.m
This addresses #125, where a developer is setting `.shouldEstablishDirectChannel` in a background thread, and getting a main thread sanitization issue in Xcode 9.
> Ensure auto-connect logic is always in main thread

- Firebase/Database/CHANGELOG.md
- Firebase/Storage/CHANGELOG.md
Adding changelog for the vX.0.1 release. This also backfills the changelog with the data from the previous release trains.
> Adding ChangeLogs for Storage and Database

- Firebase/Core/FIRApp.m
There should be a visible error when the Bundle ID is not correctly configured in the project. It was (inadvertently?) converted to an (off-by-default) Info message around January 2017.
Thanks to @ryanwilson for helping to track this down.
> Wrong Bundle ID should be a visible error

- Firebase/Core/FIRBundleUtil.m
- Firebase/Core/Private/FIRBundleUtil.h
Remove `relevantBundleIdentifiers` method that isn't used anywhere.
> Clean up FIRBundleUtil.

- Example/Database/Tests/Integration/FIRDatabaseTests.m
- Firebase/Database/Api/FIRDatabase.m
When a FIRApp is deleted in Core, it should also be deleted from
the instances array in Database.
See #160 for more details.
> Delete app from Database when deleted in Core.

- Firebase/Firebase/FirebaseCommunity.h
This will prevent users from having to specifically import Fabric or
Crashlytics into their projects when already importing Firebase.
> Add Crashlytics and Fabric to Firebase umbrella header.

- BuildFrameworks/FrameworkMaker.xcodeproj/project.pbxproj
- BuildFrameworks/build.swift
CocoaPods now uses macOS suffix instead of OSX
> Updates to the manual build process for CocoaPods 1.3.1

- Example/Database/Tests/Integration/FIRDatabaseTests.m
Deleting the defaultApp causes issues between the other tests. Remove
the portion of the test deleting the defaultApp will alleviate the
issue.
> Fix failing Database integration tests.

- Example/Auth/Tests/FIRAuthBackendRPCImplementationTests.m
- Example/Auth/Tests/FIRSendVerificationCodeRequestTests.m
- Example/Auth/Tests/FIRSendVerificationCodeResponseTests.m
- Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
- Firebase/Auth/Source/FIRAuthErrorUtils.h
- Firebase/Auth/Source/FIRAuthErrorUtils.m
- Firebase/Auth/Source/FIRAuthInternalErrors.h
- Firebase/Auth/Source/Public/FIRAuthErrors.h
- Firebase/Auth/Source/RPCs/FIRAuthBackend.m
- Firebase/Auth/Source/RPCs/FIRSendVerificationCodeRequest.h
- Firebase/Auth/Source/RPCs/FIRSendVerificationCodeRequest.m
Add reCAPTCHA token to sendVerificationCode Request.
Updates unit test and error handling for new reCAPTCHA flow.  More error handling to come.
> Adds reCAPTCHA Token

- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingConstants.h
- Firebase/Messaging/FIRMessagingConstants.m
This seems to be a holdover from some old code, and it's not being used anywhere in the component. Plus it's better not to be saving anything in `[NSUserDefaults standardUserDefaults]` as that is the developer/app's domain.
I kept the printing of the library version to the console, and renamed the messaging code while I was in there to be something meaningful ("000" → "PrintLibraryVersion").
> Don't write library version to NSUserDefaults

- Firebase/Core/FIROptions.m
Bump the FirebaseCore version as part of the next Firebase release.
> Bump FirebaseCore Version to 4.0.6

- Example/Auth/Tests/FIRGetProjectConfigRequestTests.m
- Firebase/Auth/Source/RPCs/FIRGetProjectConfigRequest.m
Quick fix to the getProjectConfig request URL.
> fixes request URL

- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessagingTopicOperation.m
This should address the issue filed at: https://github.com/firebase/quickstart-ios/issues/242, where a topic name containing a `%` character was failing. It turns out that the topic name was never being url-encoded.
> Encode the topic name when subscribing

- AuthSamples/Samples.xcodeproj/project.pbxproj
- Example/Auth/Tests/FIRAuthURLPresenterTests.m
- Example/Auth/Tests/FIRGetProjectConfigRequestTests.m
- Example/Firebase.xcodeproj/project.pbxproj
- Firebase/Auth/FirebaseAuth.podspec
- Firebase/Auth/Source/FIRAuthDefaultUIDelegate.m
- Firebase/Auth/Source/FIRAuthErrorUtils.h
- Firebase/Auth/Source/FIRAuthErrorUtils.m
- Firebase/Auth/Source/FIRAuthInternalErrors.h
- Firebase/Auth/Source/FIRAuthURLPresenter.h
- Firebase/Auth/Source/FIRAuthURLPresenter.m
- Firebase/Auth/Source/Public/FIRAuthErrors.h
- Firebase/Auth/Source/Public/FIRAuthUIDelegate.h
- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessagingTopicOperation.m
- FirebaseCommunity.podspec
Adds FIRAuthURLPresenter which allows Firebase Auth to present a URL using SFSafariViewController.  Support for UIWebView will be added in a later diff.
> Add FirAuthUrlPresenter

- Example/Auth/Tests/FIRAuthAPNSTokenManagerTests.m
- Example/Auth/Tests/FIRAuthAppDelegateProxyTests.m
- Example/Auth/Tests/FIRPhoneAuthProviderTests.m
- Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
- Firebase/Auth/Source/FIRAuth.m
- Firebase/Auth/Source/FIRAuthAPNSTokenManager.h
- Firebase/Auth/Source/FIRAuthAPNSTokenManager.m
- Firebase/Auth/Source/FIRAuthAppDelegateProxy.h
- Firebase/Auth/Source/FIRAuthAppDelegateProxy.m
- Firebase/Auth/Source/FIRAuthErrorUtils.h
- Firebase/Auth/Source/FIRAuthErrorUtils.m
- Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Also removes the server request in case the token is missing.
> Swizzles APNs token error app delegate method for faster turnaround.

- Example/Auth/Tests/FIRPhoneAuthProviderTests.m
- Firebase/Auth/Source/FIRAuth_Internal.h
Removes canHandleURL from FIRAuthInternal and makes small modification to FIRPhoneAuthProvider unit test.
> Removes canHandleURL from FIRAuthInternal

- Firebase/Core/Private/FIRLogger.h
Wrap the FIRLogger functions in an extern "C" when being compiled as C++.
> Ensure that FIRLogger functions are compiled as C

- Example/Auth/Tests/FIRAuthURLPresenterTests.m
- Firebase/Auth/Source/FIRAuthURLPresenter.m
- Firebase/Auth/Source/Public/FIRPhoneAuthProvider.h
- kinda works on iOS 8-;
- calls back with cancellation error correctly on 'Done' button;
- cleans up upon completion.
> Fixes Auth URL presenter:

- Example/Storage/Tests/Integration/FIRStorageIntegrationTests.m
- Example/Storage/Tests/Unit/FIRStorageMetadataTests.m
- Example/Storage/Tests/Unit/FIRStorageUpdateMetadataTests.m
- Firebase/Storage/FIRStorageMetadata.m
- Firebase/Storage/FIRStorageUpdateMetadataTask.m
- Firebase/Storage/Private/FIRStorageMetadata_Private.h
This ports the recent change in Android to the iOS API and allows users to remove custom metadata.
> Firebase Storage: Allowing metadata to be cleared

- Firebase/Database/Api/FIRDatabase.m
This fixes an issue with https://github.com/firebase/firebase-ios-sdk/commit/6e00706604c3452ad44fc401e4195e0462da1db1.
> Fixing the session identifier for non-default apps

- .travis.yml
PR builds will be unaffected by this change, but this should free up the build queue for all projects under the firebase org
See same code from https://github.com/firebase/firebase-js-sdk
https://github.com/firebase/firebase-js-sdk/blob/cd49e2b733346c8767ec4182d98be2bbfd6bcf8d/.travis.yml#L46-L48
> Refactor .travis.yml to only run branch builds for the master branch

- Firebase/Core/FIRLogger.m
- Firebase/Core/Private/FIRLogger.h
Add an Objective C wrapper for FIRLoggerBasic so that FIRLogger can be weakly linked.
This will allow FirebaseCommunity to use a recent version of InstanceID
> Enable FIRLogger to be weakly linked

- Example/Auth/Tests/FIRAuthURLPresenterTests.m
- Example/Auth/Tests/FIRUserTests.m
- Firebase/Auth/FirebaseAuth.podspec
- Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
- Firebase/Auth/Source/FIRAuthDefaultUIDelegate.h
- Firebase/Auth/Source/FIRAuthDefaultUIDelegate.m
- Firebase/Auth/Source/FIRAuthURLPresenter.m
- Firebase/Auth/Source/FIRAuthWebView.h
- Firebase/Auth/Source/FIRAuthWebView.m
- Firebase/Auth/Source/FIRAuthWebViewController.h
- Firebase/Auth/Source/FIRAuthWebViewController.m
- FirebaseCommunity.podspec
Also (hopefully) fixes thread safety issues in presenting Auth web content.
> Implements web view for presenting Auth web content on iOS 7 and 8.

- Example/Messaging/Tests/FIRMessagingFakeSocket.m
- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessagingDefines.h
- Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
This removes the `FIRMessaging_FAIL` macro which was using `__builtin_trap()`, and replaced with `NSAssert` calls. These `NSAssert` calls may not get called in release builds, and so we also log them with FIRLogger error messages.
The RMQ database open error result code is now parsed and included in the error message to help us identify causes for #199 .
> Remove FIRMessaging_FAIL macro, log result code

- Firebase/Auth/Source/AuthProviders/OAuth/FIROAuthCredential.h
- Firebase/Auth/Source/AuthProviders/OAuth/FIROAuthCredential.m
- Firebase/Auth/Source/AuthProviders/OAuth/FIROAuthProvider.m
> Fixes nullability and removed redundant property for FIROAuthCredential.

- Example/Auth/Tests/FIRPhoneAuthProviderTests.m
- Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
Exposes event ID via extension only for testing the successful flow.
> Modifies unit tests to accommodate event ID check

- BuildFrameworks/README.md
> Document minimum CocoaPods version for BuildFrameworks

- Firebase/Database/Api/FIRDatabase.m
This fixes the crash in:
Error log:
```
2017-09-14 21:57:45.555 Alosra[40901:8313494] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM removeObjectForKey:]: key cannot be nil'
*** First throw call stack:
(
0   CoreFoundation                      0x0000000103c1db0b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x0000000103682141 objc_exception_throw + 48
2   CoreFoundation                      0x0000000103bb73b4 -[__NSDictionaryM removeObjectForKey:] + 676
3   Alosra                              0x0000000101fc15e8 __29+[FRepoManager disposeRepos:]_block_invoke + 554
4   libdispatch.dylib                   0x00000001062ce05c _dispatch_client_callout + 8
5   libdispatch.dylib                   0x00000001062abde6 …
```
> Don't delete apps that don't exist

- Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
- Firebase/Auth/Source/FIRAuthDefaultUIDelegate.h
- Firebase/Auth/Source/FIRAuthURLPresenter.h
- Firebase/Auth/Source/FIRAuthURLPresenter.m
- Firebase/Auth/Source/FIRAuthWebView.h
- Firebase/Auth/Source/FIRAuthWebViewController.h
- Firebase/Auth/Source/FIRAuthWebViewController.m
- Firebase/Auth/Source/Public/FIRAuthUIDelegate.h
Adds comments and makes small code cleanup changes.
> Add missing comments

- Firebase/Core/FIRLogger.m
Some combinations of iOS version, simulator/device, and Xcode version
result in duplicate logs. This should remove duplicate logs while
ensuring that all Firebase related logs are still shown.
> Remove duplicate logging issue.

- Firebase/Messaging/FIRMessagingClient.m
- Firebase/Messaging/FIRMessagingConstants.h
- Firebase/Messaging/FIRMessagingConstants.m
This fixes a bug in the automatic direct channel logic, where a failure to get checkin info from the Instance ID SDK was resulting in a non-retrying failure, causing the automatic connection logic to not retry connecting. Checkin info is fetched once every 24 hours (since the last time the app was launched).
A listener is added for a new notification that will be fired from Instance ID. When that notification is fired, `FIRMessagingClient` will re-attempt to connect.
> Fix app launch MCS connection issue

- Firebase/Messaging/FIRMessaging+FIRApp.m
The previous message was worded in a way as to imply that the FIRAppDelegateProxyEnabled key **should** be set to NO, disabling swizzling. This clarifies that message, indicating that this is for developers who would prefer to manually integrate the SDK.
> Clarify FCM SDK swizzling notice

- Example/Auth/Sample/UserInfoViewController.m
- Example/Auth/Tests/FIRUserMetadataTests.m
- Example/Auth/Tests/FIRUserTests.m
- Example/Firebase.xcodeproj/project.pbxproj
- Firebase/Auth/Source/FIRUser.m
- Firebase/Auth/Source/FIRUserMetadata.m
- Firebase/Auth/Source/FIRUserMetadata_Internal.h
- Firebase/Auth/Source/Public/FIRUser.h
- Firebase/Auth/Source/Public/FIRUserMetadata.h
- Firebase/Auth/Source/Public/FirebaseAuth.h
- Firebase/Auth/Source/RPCs/FIRGetAccountInfoResponse.h
- Firebase/Auth/Source/RPCs/FIRGetAccountInfoResponse.m
Adds new API that exposes user metadata on the FIRUserObject.
> User meta data

- Example/Firebase.xcodeproj/project.pbxproj
Stubs.swift was in both the Auth_Example and Auth_SwiftSample build targets.
This PR removes it from Auth_Example. 
Note that Stubs.swift is still broken and a future PR should be done to add the Auth_SwiftSample build to travis.
The other changes are the result of using CocoaPods 1.3.1 instead of something earlier.
> Remove Stubs.swift from Auth_Example build target

- Example/Auth/SwiftSample/Stubs.swift
Removes metadata from swift sample until it is made public again.
> Removes metadata from swift sample

- Example/Messaging/App/iOS/NotificationsController.swift
- Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
- Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
FCM's swizzling of the user notification center currently swizzles only one of the two optional delegate methods (`userNotificationCenter:willPresentNotification:withCompletionHandler:`), but not the other (`userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:`).
The `didReceiveNotificationResponse`, if implemented by the delegate, is the sole receiver of _all_ user action on a notification, including simply tapping on the notification itself. Prior to this change, if the developer had implemented `didReceiveNotificationResponse`, then FCM would not be able to collect this event for analytics.
Additionally, I changed the logic in `FIRMessagingRemoteNotificationsProxy` to check whether these methods are actually implemented before swizzling them. It was always …
> Swizzle additional user notifications method, and only swizzle if methods are implemented

- Firestore/CHANGELOG.md
- Firestore/Example/SwiftBuildTest/main.swift
- Firestore/Source/Public/FIRSnapshotMetadata.h
Fixes b/67332554
Note that this is a breaking change for Swift users of the API.
> Add an NS_SWIFT_NAME for FIRSnapshotMetadata

- Firestore/Source/API/FIRFirestore.m
This is consistent with the rest of the error messages.
> Update error messages with new Swift syntax

- Firestore/CHANGELOG.md
- Firestore/Example/SwiftBuildTest/main.swift
- Firestore/Source/Public/FIRListenerRegistration.h
- Firestore/Source/Public/FIRSetOptions.h
Adding the last missing NS_SWIFT_NAME. This, along with https://github.com/firebase/firebase-ios-sdk/commit/4dd7ec8e4d6243820d4f877ccfd76c5b4a076dd5, is a breaking change.
> Adding NS_SWIFT_NAME for FIRListenerRegistration

- Firebase/Core/Private/FIRAppInternal.h
See https://stackoverflow.com/questions/44473146/this-function-declaration-is-not-a-prototype-warning-in-xcode-9 for context
> Fix a warning that shows up in Xcode 9

- Firebase/Auth/Source/FIRAuth.m
- Firebase/Auth/Source/FIRAuthGlobalWorkQueue.h
- Firebase/Auth/Source/FIRAuthURLPresenter.m
- Firebase/Core/FIRAppAssociationRegistration.m
- Firebase/Core/Private/FIRAppAssociationRegistration.h
Removes new Xcode warnings in XCode 9.1 and still builds and runs on unit tests in Xcode 8.3
Warnings related to using iOS 9+ APIs remain.
> Fix warnings exposed by Xcode 9.1 in Auth

- Firestore/Source/Core/FSTTypes.h
- Firestore/Source/Remote/FSTDatastore.m
- Firestore/Source/Remote/FSTExponentialBackoff.h
- Firestore/Source/Remote/FSTExponentialBackoff.m
- Firestore/Source/Util/FSTDispatchQueue.h
- Firestore/Source/Util/FSTDispatchQueue.m
Fix “This function declaration is not a prototype” warning in Xcode 9.1
More context at https://stackoverflow.com/questions/44473146/this-function-declaration-is-not-a-prototype-warning-in-xcode-9
> Fix warnings exposed by Xcode 9.1 in Firestore source

- Firebase/Messaging/FIRMessagingLogger.h
- Firebase/Messaging/FIRMessagingLogger.m
- Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
- Firebase/Messaging/FIRMessagingUtilities.h
- Firebase/Messaging/FIRMessagingUtilities.m
- Firebase/Messaging/FIRMessagingVersionUtilities.h
- Firebase/Messaging/FIRMessagingVersionUtilities.m
Four warnings still remain for API mismatches.
> Add void's to eliminate Xcode 9.1 warnings in FCM

- Firestore/Source/API/FIRListenerRegistration.m
When the listener registration holds references to the internal listener and async listener, getting a Firestore document creates a retain cycle that shows up in the Xcode Memory Graph. Setting them to nil when the listener is removed should break the cycle.
> Release listener references on remove in FSTListenerRegistration

- Firebase/Core/FIRAppAssociationRegistration.m
- Firebase/Core/Private/FIRAppAssociationRegistration.h
- Firebase/Database/Core/Utilities/FIRRetryHelper.h
- Firebase/Database/Core/Utilities/FIRRetryHelper.m
Context at https://stackoverflow.com/questions/44473146/this-function-declaration-is-not-a-prototype-warning-in-xcode-9
> Fix warnings exposed by Xcode 9.1 in RTDB

- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.m
Addressing Lint warning:
Incorrect XCTest assertion parameter order. The parameters should be inverted. See go/xctest-tips for more information.. Use // NOLINT or // NOLINTNEXTLINE to skip this (or any expected) lint error.
//depot/google3/third_party/firebase/ios/Source/Firestore/Example/Tests/Integration/API/FIRDatabaseTests.m:173
> Fixing XCTAssertEqual order

- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.m
- Firestore/Example/Tests/Integration/API/FIRListenerRegistrationTests.m
- Firestore/Example/Tests/Integration/FSTDatastoreTests.m
- Firestore/Source/Core/FSTFirestoreClient.h
- Firestore/Source/Core/FSTFirestoreClient.m
- Firestore/Source/Remote/FSTRemoteStore.h
- Firestore/Source/Remote/FSTRemoteStore.m
This is mostly a straightforward port from Android (cr/163517033).
The only difference is that I am clearing the onlineStateDelegate in 'shutdown', since that races with the localStore teardown during shutdown. Without this, 'shutdown' invokes the initial listener callbacks when Level DB is no longer available.
(Do we want to do the same on Android and not call the listeners during the shutdown phase?).
> Adding goOnline/goOffline to the RemoteStore

- BuildFrameworks/build.swift
Fix #366 
The Xcode 9 Swift compiler is less tolerant of complex Swift errors than Xcode 8. This PR implements a  workaround.
Google the following to see multiple examples:
`./build.swift:143:10: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions`
> Fix Xcode 9 too complex error in build.swift

- Example/Messaging/App/iOS/AppDelegate.swift
- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/Public/FIRMessaging.h
This new delegate method will be called generally once per app start, to always provide a current token. This token may change over time. This simpler method makes integration much simpler, as:
* Developers no longer have to check for a current token using the `.fcmToken` property, and also check for token changes using the `-messaging:didRefreshRegistrationToken:` delegate method.
* There is a single code path for when a token is available, making operations that depend on a token being available easier to implement. For example, this is the right method to always upload your FCM token to your application server, or to subscribe to topics, etc.
> Add simpler delegate method for FCM tokens

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Integration/API/FIRValidationTests.m
- Firestore/Source/API/FSTUserDataConverter.m
With this change indirectly nested arrays are allowed. We still disallow directly nested arrays.
Fixes internal bug b/66253451.
> Fix validation of nested arrays to allow indirect nesting

- Example/Auth/Sample/MainViewController.m
Added automation for phone manual test.
> Adds automated test for manual phone sign-in

- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.m
- Firestore/Example/Tests/Integration/API/FIRTypeTests.m
- Firestore/Source/API/FIRDocumentReference.m
- Firestore/Source/API/FIRQuery.m
* Ports the test for the fix I made for Android for DocumentReference objects in arrays (bug not present in iOS).
* Implements isEqual on FIRQuery and FIRDocumentReference.
> Add isEqual() and port DocumentReference array test.

- Example/Auth/Sample/Images.xcassets/AppIcon.appiconset/Contents.json
- Example/Auth/Sample/MainViewController.m
- Firebase/Auth/Source/FIRAuthAppDelegateProxy.m
- Firebase/Auth/Source/FIRAuthURLPresenter.m
Also fixes a crash in the Auth sample app in an error case.
This addresses *Auth* part of #385 .
>  Silences unguarded availability warnings in Auth.

- .travis.yml
The -I option to `git grep` indicates to skip binary files.  A introduced png file in #396 was causing at travis failure.
> Don't fail travis tests if a binary file has a trailing space

- .travis.yml
Travis was logging `pod lib lint`, but not marking the run as a failure, because the tail command reset the command's return code.
> Catch failures from pod lib lint in travis

- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.m
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
- Firestore/Example/Tests/SpecTests/json/write_spec_test.json
- Firestore/Source/Remote/FSTRemoteStore.m
This ensures FSTRemoteStore always tries to connect at least twice before surfacing an FSTOnlineStateFailed event to external code (which may trigger gets to fail, cached data to be surfaced, etc.).
> Port of fix for b/67042460 (retry more often before considering client offline)

- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.m
- Firestore/Example/Tests/Integration/API/FIRValidationTests.m
- Firestore/Source/API/FIRDocumentReference.m
- Firestore/Source/API/FIRTransaction.m
- Firestore/Source/API/FIRWriteBatch.m
- Firestore/Source/API/FSTUserDataConverter.h
- Firestore/Source/API/FSTUserDataConverter.m
This is a port of https://github.com/firebase/firebase-js-sdk/pull/248
> Allowing field deletes with merge-enabled sets

- Firestore/Firestore.podspec
The redundant $(inherited) was causing `pod install/update` to generate a warning
> Fix pod update warning

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
While #414 removed unnecessary cruft, I messed up the testing and it didn't fix the CocoaPods warning.
The warning was a result of extra double quotes around $(inherited) in the tests' HEADER_SEARCH_PATHS
> Really fix pod update warning

- Firebase/Auth/Source/FIRUser.m
Handles possible errors after linking phone number.
Also sets anonymous ivar to NO if linking succeeded; if there is an error while storing the user in the keychain after linking the ivar is left as NO since the user in memory would no longer be an anonymous user.
Fixes issue #421
> Handle errors after Phone Number Linking

- Firebase/Database/Api/FIRDataSnapshot.m
- Firebase/Database/Api/FIRMutableData.m
- Firebase/Database/Public/FIRDataSnapshot.h
- Firebase/Database/Public/FIRMutableData.h
So 
for childSnapshot in snapshot.children {
you don't need to cast each child. Each cild is already known as DataSnapshot
> Enumerator using generic. Cleaner for .. in .. loop in Swift

- Firebase/Core/Private/FIRLogger.h
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Podfile
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
This ended up trickier than it should have been so I pulled it out of my main change.
`FSTIntegrationTestCase` calls `FIRSetLoggerLevel` which wasn't protected in an `extern "C"` block to force C linkage. That fix is included here.
Additionally, it seems as if previously the tests were getting their link to on `FIRSetLoggerLevel` transitively by depending on Firestore. Changing to Objective-C++ has somehow broken that (or fixed it, depending on your perspective).
BUG b/69089200
CC @mikehaney24
> Make FSTIntegrationTestCase Objective-C++

- Example/Storage/Tests/Integration/FIRStorageIntegrationTests.m
- Example/Storage/Tests/Unit/FIRStorageMetadataTests.m
- Firebase/Storage/FIRStorageConstants.m
- Firebase/Storage/FIRStorageMetadata.m
- Firebase/Storage/Private/FIRStorageConstants_Private.h
- Firebase/Storage/Public/FIRStorageMetadata.h
The MD5 Hash is part of the Android & Web implementation, but not exposed in iOS. 
This was already approved in the original API review.
> Adding the MD5 hash to FIRStorageMetadata

- Firebase/Database/Snapshot/FEmptyNode.m
This is intended to reduce the crashes reported in https://github.com/firebase/firebase-ios-sdk/issues/281
> Using deferred init to ensure that we init FEmptyNode only once

- Example/Firebase.xcodeproj/project.pbxproj
- Example/Firebase.xcodeproj/xcshareddata/xcschemes/AllUnitTests_tvOS.xcscheme
- Example/Firebase.xcodeproj/xcshareddata/xcschemes/Auth_Example_tvOS.xcscheme
- Example/Firebase.xcodeproj/xcshareddata/xcschemes/Auth_Tests_tvOS.xcscheme
- Example/Firebase.xcodeproj/xcshareddata/xcschemes/Database_Example_tvOS.xcscheme
- Firebase/Auth/Source/FIRAuthAPNSTokenManager.m
Verified the three AllUnitTest targets build and run with no failures
TARGET_OS_TV is defined - to 0
> Various build and test fixes

- Example/Auth/Sample/MainViewController.m
Removes the headful sign-in label from the Sample App as it is no longer in use.
> Removes unused label from sample app

- Example/Auth/Sample/MainViewController.m
- Example/Auth/Tests/FIRAuthTests.m
- Firebase/Auth/Source/FIRAdditionalUserInfo.m
- Firebase/Auth/Source/FIRAdditionalUserInfo_Internal.h
- Firebase/Auth/Source/FIRAuth.m
- Firebase/Auth/Source/Public/FIRAuth.h
Adds `AuthDataResult` to the completion of anonymous sign as part of an effort to supplement all sign-in methods with `AdditionalUserInfo`.
> Adds AuthDataResult to anonymous sign in

- Firestore/Example/Tests/GoogleTest/FSTGoogleTestTests.mm
- Firestore/Example/Tests/Tests-Info.plist
Unfortunately, using `__attribute__((constructor))` doesn't really work
because it races with all other constructors run pre-main. As a result
it's possible for a test's constructor to run after registration.
NSPrincipalClass gets instantiated only after all constructors have run.
> Use NSPrincipalClass as the most reliable way to find tests.

- Firestore/Example/Tests/Local/FSTRemoteDocumentCacheTests.m
- Firestore/Source/Local/FSTLevelDBRemoteDocumentCache.mm
Minor optimization (which is already present in the ts code).
http://b/36351543
> Use a prefix scan when fetching documents matching a query.

- Firestore/README.md
Firebase.xcworkspace exists in /Example while Firestore.xcworkspace exists in /Firestore/Example. We actually want the developer to open Firestore.xcworkspace.
us make Firebase APIs better, please propose your change in a …
> Fix a wrong file name in README.md

- Firebase/Auth/Source/FIRAuth.m
- Firebase/Database/Api/FIRDatabase.m
- Firebase/Database/Login/FAuthTokenProvider.m
- Firebase/Messaging/FIRMessaging+FIRApp.m
- Firebase/Storage/FIRStorageTokenAuthorizer.m
- Firestore/Source/Auth/FSTCredentialsProvider.m
- Firestore/Source/Public/FIRQuery.h
- Firestore/test/core/util/autoid_test.cc
Standardize imports of FIRAppInternal.h since it is now a published private header from Core
@salqadri  discovered the reference from Firestore was breaking the build when it was brought it to the Podfile via 
` pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'`
Also fix a few other FirebaseCore privates and two style issues.
> FIRAppInternal.h is a published private header

- Firestore/Source/Auth/FSTCredentialsProvider.h
- Firestore/Source/Auth/FSTCredentialsProvider.m
- Firestore/Source/Auth/FSTEmptyCredentialsProvider.h
- Firestore/Source/Auth/FSTUser.h
- scripts/style.sh
Change `scripts/style.sh` to filter out excluded sources more precisely.
Also add the ability to format just specific files or files changed since some branch.
Fixes [b/69924409](http://b/69924409).
/cc @rsgowman
> Allow clang-format to find Firestore/Source/Auth

- Firebase/Auth/Source/FIRAuth.m
- Firebase/Core/FIRApp.m
- Firebase/Core/Private/FIRAppInternal.h
This is to allow firestore to not require an explicit dependency on
auth.
(See https://github.com/firebase/firebase-ios-sdk/pull/505 for more context.)
> Include UID when sending (internal) auth state change notifications

- Firestore/CHANGELOG.md
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Local/StringViewTests.mm
- Firestore/Source/Local/StringView.h
NSStrings are utf16, so NSString::length returns the number of utf16
characters present in the string. When the string is entirely made up of
US-ASCII characters, everything's fine. But when characters requiring 16
bits are present, the size calculations were incorrect.
Fixed by calculating the length based on the destination character set
(i.e. UTF8).
b/69843038
> Fix StringView to properly convert NSStrings

- README.md
With Firebase 4.7.0, open source pods integrate with the official release Firebase pods and FirebaseCommunity is gone,  so it's no longer to explicitly add FirebaseInstanceID to the Podfile since it's an explicit dependency of FirebaseMessaging.
> Remove no longer necessary FirebaseCommunity/Messaging workaround

- Firebase/Messaging/FIRMessaging.m
FCM SDK version function should only return the semantic version string instead of prefixing a "fcm-", this way IID can adjust the parameter prefix.
> FCM version function should return only the semantic version 

- Firestore/Source/Remote/FSTStream.m
This is a follow-up PR to https://github.com/firebase/firebase-ios-sdk/pull/510.
I believe the race condition also exists for stream messages in general (and not just stream closes). While it is unlikely that we will receive a stream message from a stream we deemed idle, we should still suppress all callbacks as we do on the Web and Android.
> Ignoring stream messages for closed streams

- Example/Analytics_Tests_iOS/Analytics_Tests_iOS.m
- Example/Analytics_Tests_iOS/DeprecatedHeaderTest.m
- Example/Analytics_Tests_iOS/Info.plist
- Example/Firebase.xcodeproj/project.pbxproj
- Example/Firebase.xcodeproj/xcshareddata/xcschemes/AllUnitTests_iOS.xcscheme
- Example/Firebase.xcodeproj/xcshareddata/xcschemes/Analytics_Tests_iOS.xcscheme
- Example/Firebase.xcodeproj/xcshareddata/xcschemes/Core_Example_iOS.xcscheme
- Example/Podfile
Add an Analytics test target and include it in AllUnitTests_iOS
Initially it is only being used to insure that the Analytics deprecated headers still exist.
> Add Analytics test target and build tests for deprecated headers

- Firebase/Auth/Source/Public/FIRAdditionalUserInfo.h
- Firebase/Auth/Source/Public/FIRAuth.h
- Firebase/Auth/Source/Public/FIRAuthDataResult.h
- Firebase/Auth/Source/Public/FIRAuthErrors.h
- Firebase/Auth/Source/Public/FIREmailAuthProvider.h
- Firebase/Auth/Source/Public/FIRFacebookAuthProvider.h
- Firebase/Auth/Source/Public/FIRGitHubAuthProvider.h
- Firebase/Auth/Source/Public/FIRGoogleAuthProvider.h
- Firebase/Auth/Source/Public/FIROAuthProvider.h
- Firebase/Auth/Source/Public/FIRPhoneAuthProvider.h
- Firebase/Auth/Source/Public/FIRTwitterAuthProvider.h
- Firebase/Auth/Source/Public/FIRUser.h
@c and inline HTML tags were causing errors during doc generation
> Updating the Auth header comments for Jazzy syntax

- .gitignore
- CMAKE.md
- CMakeLists.txt
- Firestore/CMakeLists.txt
- Firestore/core/CMakeLists.txt
- cmake/external/firestore.cmake
All projects are now ExternalProjects. This kind of superbuild setup is the recommended way to build a projects and its dependencies in a single pass.
This makes it much easier to build them all in a single pass.
> Rework the top-level cmake build to be a superproject

- Firestore/Source/Public/FirebaseFirestore.h
Add a second umbrella header so that the Firebase module will include the Firestore umbrella header in source builds.
Changing Firebase.h to check for Firestore-umbrella.h would not work because umbrella headers only get generated by CocoaPods when `use_frameworks!` is specified and the name of the umbrella header may or may not be qualified by a target if the Podfile specifies multiple Apple targets.
More details internally at b/70281259
> Add FirebaseFirestore.h to fix Firebase module in source build

- Example/Auth/Tests/FIRAuthAPNSTokenManagerTests.m
- Example/Auth/Tests/FIRAuthDispatcherTests.m
- Example/Auth/Tests/FIRAuthTests.m
- Example/Auth/Tests/FIRAuthURLPresenterTests.m
- Example/Auth/Tests/FIRPhoneAuthProviderTests.m
- Example/Auth/Tests/FIRUserTests.m
Close #406
This timeout test failure has occurred twice again today. Most recently on #543's [travis run](https://travis-ci.org/firebase/firebase-ios-sdk/builds/313602740)
cc: @wilhuff
> Double auth unit test timeout to address travis flakiness

- Firebase/Core/third_party/FIRAppEnvironmentUtil.m
This can save a small amount of memory during startup time.
> Add an Info.plist flag to disable App Store Sandbox check.

- Firestore/third_party/abseil-cpp/absl/base/CMakeLists.txt
- Firestore/third_party/abseil-cpp/absl/base/internal/endian.h
- Firestore/third_party/abseil-cpp/absl/base/internal/endian_test.cc
- Firestore/third_party/abseil-cpp/absl/base/internal/unaligned_access.h
This imports a few more files from abseil-cpp.
This change started on abseil-mirror and the first commit (cd17b85587d1a827389ea1e18d0ce5622606cd5f) moves abseil-mirror forward.
The subsequent changes layer back on our local changes and add the endian stuff to the build.
The last change (3bc5488644b8a5042079ffcf91e852bedc24d572) is the only real diff.
>  Import absl/base/internal/endian.h

- Firestore/Source/API/FIRQuery+Internal.h
- Firestore/Source/API/FIRQuery.m
helper methods were wrongly put under FIRQuery instead of FIRQuery (Internal). Moved there and fixed warnings.
> Fix new warnings w.r.t. predicate query change

- Example/Auth/Sample/MainViewController.m
Adds nil check for completion handlers to avoid crashes.
> Add nil check for completion handlers

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Integration/API/FIRQueryTests.m
- Firestore/Example/Tests/SpecTests/FSTSpecTests.m
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.m
- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Source/Core/FSTFirestoreClient.h
- Firestore/Source/Core/FSTFirestoreClient.m
- Firestore/Source/Core/FSTSyncEngine.h
- Firestore/Source/Core/FSTSyncEngine.m
- Firestore/Source/Core/FSTTypes.h
- Firestore/Source/Core/FSTView.h
- Firestore/Source/Core/FSTView.m
- Firestore/Source/Remote/FSTRemoteStore.m
[Port of: https://github.com/firebase/firebase-js-sdk/pull/358]
* Plumbs FSTOnlineState changes through to views.
* View sets this.current to false on FSTOnlineStateFailed, triggering
isFromCache=true events. It will automatically be returned to true
once the listen is reestablished and we get a new CURRENT message.
* Updated tests (and added one new one) to verify behavior.
* Unifies setOnlineStateToUnknown, setOnlineStateToHealthy, and
updateAndBroadcastOnlineState into a single updateOnlineState
method.
* Split disableNetwork into (public) disableNetwork and
(private) disableNetworkWithTargetOnlineState methods..
* Some miscellaneous comment cleanup.
> b/68276665: Raise isFromCache=true events when offline

- Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.m
This should address a crash that happens when a debugger is attached.
> Fixing return type of verifySnapshotWithResolvedTimestamps

- Firestore/Example/Tests/Integration/API/FIRQueryTests.m
- Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.m
- Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.m
- Firestore/Example/Tests/Util/FSTEventAccumulator.h
- Firestore/Example/Tests/Util/FSTEventAccumulator.m
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Example/Tests/Util/XCTestCase+Await.h
- Firestore/Example/Tests/Util/XCTestCase+Await.m
- Firestore/Source/Remote/FSTRemoteStore.m
* Adds and uses `FSTIntegrationTestCase` helpers:
* `completionExpectationWithName` returns a completion block that will fulfill an expectation when it is called (so you can call [self awaitExpectations] to await it).
* `enableNetwork` / `disableNetwork` - synchronous wrappers around the underlying SDK calls.
* Removes the (no-longer-used) `errorEventHandler` on `FSTEventAccumulator`.
> Mikelehen completion waiter

- .gitignore
- Firestore/Example/SwiftBuildTest/main.swift
- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.m
- Firestore/Example/Tests/Integration/API/FIRListenerRegistrationTests.m
- Firestore/Example/Tests/Integration/API/FIRQueryTests.m
- Firestore/Source/API/FIRFirestore.m
- Firestore/Source/Public/FIRFirestore.h
- Firestore/Source/Remote/FSTRemoteStore.m
Add `enableNetworkWithCompletion` and `disableNetworkWithCompletion` to the public interface for `FIRFirestore`.
b/70348588
> Expose network management

- Firestore/Example/SwiftBuildTest/main.swift
- Firestore/Example/Tests/API/FIRQueryTests.m
- Firestore/Example/Tests/Integration/API/FIRQueryTests.m
Fix warnings introduced by recent changes on this branch.
> Clean up warnings

- Firestore/Example/Tests/Core/FSTEventManagerTests.m
- Firestore/Example/Tests/Core/FSTQueryListenerTests.m
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.m
- Firestore/Source/Core/FSTEventManager.h
- Firestore/Source/Core/FSTEventManager.m
- Firestore/Source/Core/FSTFirestoreClient.m
- Firestore/Source/Core/FSTSyncEngine.h
- Firestore/Source/Core/FSTSyncEngine.m
- Firestore/Source/Core/FSTView.h
- Firestore/Source/Core/FSTView.m
- Firestore/Source/Remote/FSTRemoteStore.h
- Firestore/Source/Remote/FSTRemoteStore.m
FYI- I've gone with applyOnlineStateChange on iOS / Web (to be consistent with applyRemoteEvent, etc.) but handleOnlineStateChange on Android (to be consistent with handleListenEvent, etc.).  I'm not sure why the platforms diverged in naming but I don't want to try to clean it up in this PR.
> Rename all the onlineStateChanged methods to applyOnlineStateChange.

- Firestore/Source/API/FIRFirestore.m
Note that lazy initialization is required because we allow the user to
assign to settings after instantiation before any methods are used.
Also bring method naming closer to the android port.
Fixes #532.
> Fix races in lazy initialization of the client in FIRFirestore

- Firebase/Core/CHANGELOG.md
This matches [Firestore's changelog](https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/CHANGELOG.md) and will replace the internal version.
> Add changelog for Core.

- README.md
- test.sh
Also remove OS specifier for iOS tests to support Xcode 9.
> Update README for tvOS and include in travis

- Firebase/Core/FIRLogger.m
This fixes a race condition where a caller calls FIRSetLoggerLevel and
then checks FIRIsLoggableLevel immediately after.
> Run FIRSetLoggerLevel and FIRIsLoggableLevel on the same thread

- FirebaseCore.podspec
- cmake/FindFirebaseCore.cmake
This prevents the dependencies of FirebaseCore's dependencies from
bleeding into its interface.
The proximate benefit of avoiding this is that FirebaseCore no longer
ends up depending on ColorSync.framework which became a top-level system
framework in 10.13. This makes it possible to build against the
resulting FirebaseCore.framework on macOS 10.12 using Xcode 9 (with the
macOS 10.13 SDK).
> Disable autolink when building FirebaseCore

- Firestore/Source/Remote/FSTRemoteStore.m
Add log line to log pending writes remaining when the network is disabled. Requested by API review.
> Log pending writes when we disable the network

- scripts/style.sh
This is why running with a workspace where all files were committed wasn't generating any change.
> Fix scripts/style.sh diffs relative to branch name

- Example/Auth/ApiTests/FirebaseAuthApiTests.m
Adds API test for updating email of an Email/Password user.
> Adds API Test for Email Update

- Firebase/Core/third_party/FIRAppEnvironmentUtil.m
When supporting iOS 8 and above, we can now safely use NSProcessInfo
on iOS as well as the Mac. This removes a dependency on UIKit for Core.
> Move to NSProcessInfo for systemVersion.

- Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.m
- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.m
- Firestore/Source/API/FIRFirestore.m
This ports the changes from Android, as we cannot guarantee how many events a series of offline writes produces.
The rest of this PR is running ./scripts/style.sh
> Fixing potential race in ServerTimestamp tests

- Example/Auth/App/GoogleService-Info.plist
- Example/Core/App/GoogleService-Info.plist
- Example/Core/Tests/FIROptionsTest.m
- Example/Core/Tests/FIRTestCase.m
- Example/Database/App/GoogleService-Info.plist
- Example/Messaging/App/GoogleService-Info.plist
- Example/Storage/App/GoogleService-Info.plist
- Example/Storage/Tests/Unit/FIRStorageTests.m
> Removing an obsolete setting from plist files

- Firestore/Protos/FrameworkMaker.xcodeproj/project.pbxproj
- Firestore/Protos/build-protos.sh
- Firestore/Protos/objc/firestore/local/MaybeDocument.pbobjc.m
- Firestore/Protos/objc/firestore/local/Mutation.pbobjc.m
- Firestore/Protos/objc/firestore/local/Target.pbobjc.m
- Firestore/Protos/objc/google/api/HTTP.pbobjc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Common.pbobjc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Document.pbobjc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbobjc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.h
- Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Query.pbobjc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Write.pbobjc.m
- Firestore/Protos/objc/google/rpc/Status.pbobjc.m
- Firestore/Protos/objc/google/type/Latlng.pbobjc.m
This is a follow-up to #467: make the protoc-generated outputs also use fully qualified imports.
There's a corresponding change to our copybara import script to remove all the special casing for the proto headers.
/cc @zxu123
> Fully qualify protoc-generated outputs

- cmake/external/leveldb.cmake
Note that this diff is small once you exclude whitespace changes:
https://github.com/firebase/firebase-ios-sdk/compare/wilhuff/leveldb-windows?expand=1&w=1
> Actually exclude leveldb on Windows

- scripts/style.sh
Should we enforce that people use version 6 clang-format? :-)
> Add version check to style.sh to make sure folks are running the same version.

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Integration/API/FIRQueryTests.m
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/Local/FSTLocalDocumentsView.m
Previously, only the last mutation would actually be visible. (Mutations would not actually be discarded, but you wouldn't be able to actually see them until the client came online again.)
> Fix FSTLocalDocumentsView to allow multiple mutations while offline

- Firebase/Auth/CHANGELOG.md
Updates the Auth ChangeLog for next release.
> Updates Auth ChangeLog

- Firebase/Core/CHANGELOG.md
- FirebaseCore.podspec
Update missing version bump for M21.1 for FirebaseCore.
> Update Core info for M21.1

- Firestore/Protos/FrameworkMaker.xcodeproj/project.pbxproj
- Firestore/Protos/build-protos.sh
- Firestore/Protos/objc/firestore/local/MaybeDocument.pbobjc.m
- Firestore/Protos/objc/firestore/local/Mutation.pbobjc.m
- Firestore/Protos/objc/firestore/local/Target.pbobjc.m
- Firestore/Protos/objc/google/api/HTTP.pbobjc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Common.pbobjc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Document.pbobjc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbobjc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.h
- Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Query.pbobjc.m
- Firestore/Protos/objc/google/firestore/v1beta1/Write.pbobjc.m
- Firestore/Protos/objc/google/rpc/Status.pbobjc.m
- Firestore/Protos/objc/google/type/Latlng.pbobjc.m
This reverts commit bc74670afec651c3f912cb6b7e54f5b68bd507f5.
#626 broke the import into google3 where the build doesn't use framework imports.
> Revert "Fully qualify protoc-generated outputs (#626)"

- Firestore/Source/Remote/FSTStream.m
[Cherry Pick of https://github.com/firebase/firebase-ios-sdk/pull/656 for release branch]
closeWithFinalState: assumes delegate != nil, but that is not true if when
startWithdelegate: was called we entered backoff (performBackoffWithDelegate:)
and so self.delegate did not get assigned yet.
We could rework the code to make the assertion hold, but per offline
discussion this assert doesn't represent an invariant that we care about
and so I'm just removing it.
> Remove over-aggressive closeWithFinalState: delegate assert.

- FirebaseAuth.podspec
This version was missed in the M21.1 version bump PR.
> Increase FirebaseAuth version for M21.1

- Example/Core/Tests/FIROptionsTest.m
- Firebase/Core/FIROptions.m
Instead of relying on `[[NSBundle mainBundle] infoDictionary]` directly, create a new method to call directly from tests to inject a specific `infoDictionary`. The existing call will use `[[NSBundle mainBundle] infoDictionary]` so no functionality has changed.
This should fix issues with partial mocks with unit tests from #661
> Inject infoDictionary to fix flakey tests.

- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.m
- Firestore/Source/API/FIRDocumentSnapshot.m
Cherry-pick for crashing issue
> Fix issue @morganchen12 discovered where we weren't properly creating FIRQueryDocumentSnapshot instances. (#662)

- FirebaseFirestore.podspec
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
Also exclude assert_stdio from the Xcode build.
We forgot to include this in #612.
> Add assert_test to the Xcode build

- Firestore/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/string_printf.cc
- Firestore/core/test/firebase/firestore/util/autoid_test.cc
- Firestore/core/test/firebase/firestore/util/string_printf_test.cc
- cmake/CompilerSetup.cmake
... and fix warnings it turns up, mostly around signed/unsigned comparison/conversion.
> Enable warnings in the CMake build

- Firestore/core/src/firebase/firestore/util/assert_stdio.cc
- Firestore/core/src/firebase/firestore/util/string_printf.h
- Firestore/core/test/firebase/firestore/util/assert_test.cc
- scripts/style.sh
Also some style.sh tweaks; see commits for details.
> Fix C++ lint errors

- Firestore/core/src/firebase/firestore/remote/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/remote/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- cmake/utils.cmake
The idea here is to reduce the verbosity of creating CMake rules and to ensure they're uniform and to simplify how platform-specific libraries are declared (so that I can declare more of them).
> Add a cc_library to the CMake build

- Firestore/Example/Tests/Local/FSTLocalSerializerTests.m
- Firestore/Example/Tests/Local/FSTQueryCacheTests.m
- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.m
- Firestore/Example/Tests/SpecTests/FSTMockDatastore.m
- Firestore/Example/Tests/SpecTests/FSTSpecTests.m
- Firestore/Source/Core/FSTListenSequence.h
- Firestore/Source/Core/FSTListenSequence.m
- Firestore/Source/Core/FSTSyncEngine.m
- Firestore/Source/Core/FSTTypes.h
- Firestore/Source/Local/FSTLevelDBQueryCache.mm
- Firestore/Source/Local/FSTLocalSerializer.m
- Firestore/Source/Local/FSTLocalStore.m
- Firestore/Source/Local/FSTMemoryQueryCache.m
- Firestore/Source/Local/FSTQueryCache.h
- Firestore/Source/Local/FSTQueryData.h
- Firestore/Source/Local/FSTQueryData.m
- Firestore/Source/Remote/FSTRemoteStore.m
Adds sequence numbers to queries. Includes marshaling back and forth from a proto. Also, levelDB query cache will now remember and persist the highest sequence number it has seen.
This is a stepping stone towards garbage collection and allows us to start ordering queries.
> Listen sequence numbers

- Firestore/Example/Tests/API/FIRCollectionReferenceTests.m
- Firestore/Example/Tests/API/FIRDocumentReferenceTests.m
- Firestore/Example/Tests/API/FIRDocumentSnapshotTests.m
- Firestore/Example/Tests/API/FIRFieldPathTests.m
- Firestore/Example/Tests/API/FIRFieldValueTests.m
- Firestore/Example/Tests/API/FIRGeoPointTests.m
- Firestore/Example/Tests/API/FIRQuerySnapshotTests.m
- Firestore/Example/Tests/API/FIRQueryTests.m
- Firestore/Example/Tests/API/FIRSnapshotMetadataTests.m
- Firestore/Example/Tests/API/FSTAPIHelpers.h
- Firestore/Example/Tests/API/FSTAPIHelpers.m
- Firestore/Example/Tests/Model/FSTFieldValueTests.m
- Firestore/Example/Tests/Remote/FSTDatastoreTests.m
- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.m
- Firestore/Example/Tests/SpecTests/FSTSpecTests.m
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.m
- Firestore/Example/Tests/Util/FSTHelpers.m
- Firestore/Source/API/FIRCollectionReference.mm
- Firestore/Source/API/FIRDocumentChange+Internal.h
- Firestore/Source/API/FIRDocumentReference.m
- Firestore/Source/API/FIRDocumentSnapshot.m
- Firestore/Source/API/FIRQuery.m
- Firestore/Source/API/FIRQuerySnapshot.m
- Firestore/Source/API/FIRSetOptions.m
- Firestore/Source/API/FIRSnapshotMetadata.m
Clean up import order and type:
* Tests should import the header of the class under test first
* Framework imports should be in < > (i.e. those that import FirebaseFirestore/FIRFoo.h)
* Group framework imports together
* Use forward declarations where possible (Objective-C does not have the problems C++ does)
Also:
* Simplify the isEqual implementations to just use `&&` instead of manually implementing short-circuiting
* Remove pessimistic instance checks--self comparison is rare in practice
* Fix equality in FIRSetOptions
> Cleanup imports and isEqual

- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingContextManagerService.m
- Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
Don't use @available so it still builds on Xcode 8 unlike the reverted #546. 
Close #390
> Disable Messaging build warnings

- README.md
Improve README.md based on use case from #702
> README - FirebaseCore source pod must be included with all source pods

- Firebase/Auth/Source/Public/FIREmailAuthProvider.h
Updating `Firebase/Auth` from version `3.10.0` to `4.8.1` in a Swift project caused an error along the lines of "`FIREmailPasswordAuthProviderID` was replaced by `FIREmailAuthProviderID `".
Making this change caused another error along the lines of "`FIREmailAuthProviderID ` was replaced by `EmailAuthProviderID `", hence this PR.
* If you fixed a bug or added a feature, add a new test …
> Fix incorrect deprecation message

- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Source/Core/FSTView.m
[PORT OF https://github.com/firebase/firebase-js-sdk/pull/470]
Context: I made a previous change to raise isFromCache=true events when the
client goes offline. As part of this change I added an assert for
"OnlineState should not affect limbo documents", which it turns out was not
valid because:
* When we go offline, we set the view to non-current and call
View.applyChanges().
* View.applyChanges() calls applyTargetChange() even though there's no target
change and it recalculates limbo documents.
* When the view is not current, we consider no documents to be in limbo.
* Therefore all limbo documents are removed and so applyChanges() ends up
returning unexpected LimboDocumentChanges.
Fix: I've modified the View logic so that we don't recalculate limbo documents
(and generate …
> Fix b/72502745: OnlineState changes cause limbo document crash.

- Firestore/core/src/firebase/firestore/model/field_value.cc
- Firestore/core/src/firebase/firestore/model/field_value.h
- Firestore/core/src/firebase/firestore/util/assert_stdio.cc
- Firestore/core/test/firebase/firestore/core/target_id_generator_test.cc
- Firestore/core/test/firebase/firestore/model/field_value_test.cc
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/comparison_test.cc
- Firestore/core/test/firebase/firestore/util/log_test.cc
- cmake/CompilerSetup.cmake
* Move -fvisibility-inlines-hidden from common_flags to cxx_flags
This option isn't supported by C (and causes the build to fail under
at least rodete).
Manifested error was:
```
-- Looking for include file openssl/rand.h
-- Looking for include file openssl/rand.h - not found
CMake Error at core/src/firebase/firestore/util/CMakeLists.txt:94 (message):
No implementation for SecureRandom available.
-- Configuring incomplete, errors occurred!
```
which is completely misleading. :(
￼
* Fix exception include for std::logic_error
Was causing compiler error on (at least) rodete.
(http://en.cppreference.com/w/cpp/error/logic_error suggests that
stdexcept is the correct header.)
￼
* Remove 'const' from vector contents.
vectors cannot contain const objects as the contained objects are
required to …
> Fix a number of c++ build errors

- Firestore/core/src/firebase/firestore/model/timestamp.cc
- Firestore/core/src/firebase/firestore/model/timestamp.h
Should have caught this during review, but cpplint caught it.
> Use fixed-sized types

- .travis.yml
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/iterator_adaptors.h
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/iterator_adaptors_test.cc
- cmake/CompilerSetup.cmake
This allows us to straightforwardly define iterators on properties of the elements sequence. I need this specifically for enumerating the keys of the pairs in an `ArraySortedMap`.
Note that 42749ce contains the scrubbed code and the subsequent changes are fixups.
>  Import iterator_adaptors from google3

- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
Required to link the test on rodete.
> Add absl_strings to firebase_firestore_util_test dependencies

- Firestore/Example/Tests/Model/FSTDocumentSetTests.mm
- Firestore/Source/Model/FSTDocumentSet.h
- Firestore/Source/Model/FSTDocumentSet.mm
- Firestore/core/test/firebase/firestore/immutable/array_sorted_map_test.cc
- Firestore/third_party/Immutable/FSTArraySortedDictionary.m
- Firestore/third_party/Immutable/FSTImmutableSortedDictionary.h
- Firestore/third_party/Immutable/FSTImmutableSortedDictionary.m
- Firestore/third_party/Immutable/FSTImmutableSortedSet.h
- Firestore/third_party/Immutable/FSTImmutableSortedSet.m
- Firestore/third_party/Immutable/FSTTreeSortedDictionary.m
- Firestore/third_party/Immutable/Tests/FSTArraySortedDictionaryTests.m
- Firestore/third_party/Immutable/Tests/FSTTreeSortedDictionaryTests.m
This is dead code.
I think it was probably useful in the RTDB because of the way it notified of changes, but we give changes with indexes in Firestore so I think we don't need it.
Do we need to keep this? More importantly, do we need to port it to C++?
> Remove predecessor{Key,Object,Document} etc

- Firebase/Messaging/FIRMessaging.m
Allow FCMToken to be reset by IID to nil (before it must be a valid string). This is important when user deleteToken and deleteID, FCMToken should be reset as well.
When autoInitEnable is set back on, trigger token refresh directly without checking FCM token is nil. (Although we fixed the issue FCMToken can't be set to nil, but this just one step safer)
> Allow FCMToken to be reset

- Firestore/Example/Tests/Util/XCTestCase+Await.mm
I'm doing this to:
1) Experimentally see if it improves the flakiness we've been seeing in the Query Conformance Tests.
2) Insulate us from the fact that GRPC seems to take a /minimum/ of 10 seconds to reconnect (at least in some cases) after a connection failure.
I've opened b/72864027 to revisit this in the future.
> Increase expectation timeout to 25 seconds.

- Firestore/third_party/abseil-cpp/CMakeLists.txt
- Firestore/third_party/abseil-cpp/absl/base/CMakeLists.txt
- Firestore/third_party/abseil-cpp/absl/base/attributes.h
- Firestore/third_party/abseil-cpp/absl/base/config.h
- Firestore/third_party/abseil-cpp/absl/base/internal/endian.h
- Firestore/third_party/abseil-cpp/absl/base/internal/raw_logging.cc
- Firestore/third_party/abseil-cpp/absl/base/internal/raw_logging.h
- Firestore/third_party/abseil-cpp/absl/base/internal/unaligned_access.h
- Firestore/third_party/abseil-cpp/absl/base/log_severity.h
- Firestore/third_party/abseil-cpp/absl/base/macros.h
- Firestore/third_party/abseil-cpp/absl/meta/type_traits.h
- Firestore/third_party/abseil-cpp/absl/meta/type_traits_test.cc
- Firestore/third_party/abseil-cpp/absl/strings/CMakeLists.txt
- Firestore/third_party/abseil-cpp/absl/strings/string_view.h
- Firestore/third_party/abseil-cpp/absl/strings/string_view_test.cc
Update to bf7fc9986e20f664958fc227547fd8d2fdcf863e
This only updates the components that were already present.
> Update abseil-cpp to a new upstream

- Firebase/Core/Public/FIRConfiguration.h
Removes `FIRLogLevel`, the property, and Xcode 7 support (non-class property version of the singleton).
> Remove Deprecations from FIRConfiguration.

- Firestore/core/src/firebase/firestore/model/field_path.h
Xcode prior to 8.3 does not accept an explicitly defaulted constructor
(`= default`) for the purposes of default initializing a const object.
This fixes a build failure under Xcode 8.2:
Firestore/core/src/firebase/firestore/model/field_path.cc:144:26: error: default initialization of an object of const type 'const firebase::firestore::model::FieldPath' without a user-provided default constructor
static const FieldPath empty_path;
> Explicitly specify the default constructor to FieldPath

- Firestore/Source/Public/FIRFirestore.h
Redirecting the call to the right location for logging across Firebase.
> Update deprecation message for Firestore.

- Firestore/core/src/firebase/firestore/model/CMakeLists.txt
- Firestore/core/src/firebase/firestore/model/base_path.h
- Firestore/core/src/firebase/firestore/model/field_path.cc
- Firestore/core/src/firebase/firestore/model/field_path.h
- Firestore/core/src/firebase/firestore/model/field_value.cc
- Firestore/core/src/firebase/firestore/model/field_value.h
- Firestore/core/src/firebase/firestore/model/resource_path.cc
- Firestore/core/src/firebase/firestore/model/resource_path.h
- Firestore/core/test/firebase/firestore/model/field_path_test.cc
- Firestore/core/test/firebase/firestore/model/resource_path_test.cc
- cmake/FindNanopb.cmake
- cmake/external/nanopb.cmake
* Fix nanopb (in cmake build)
Look for binaries in the src dir (since that's where we build now.) This
error would be masked if a previous build had completed prior to
switching nanopb to build out of src.
Also, don't patch the protoc path multiple times. This could be
triggered by (eg) 'make && make clean && make'.
* Add resource_path.{h,cc} to the cmake build
* Fix signed/unsigned int comparison warnings
* Ensure FieldValue tag_ is initialized during cp/mv ctor.
Otherwise, the assignment operator attempts to deallocate based on the
(uninitialized) tag_ variable, posssibly leading to segfaults.
* Fix tests that throw exceptions.
The (previous) tests checked to ensure that an abort() occurs, but if
ABSL_HAVE_EXCEPTIONS is defined on non-macos (which is currently the
default) then the …
> cmake build fixes

- .travis.yml
- Firestore/core/src/firebase/firestore/model/CMakeLists.txt
- Firestore/core/src/firebase/firestore/model/base_path.h
- Firestore/core/src/firebase/firestore/model/field_path.cc
- Firestore/core/src/firebase/firestore/model/field_path.h
- Firestore/core/src/firebase/firestore/model/field_value.h
- Firestore/core/src/firebase/firestore/model/resource_path.cc
- Firestore/core/src/firebase/firestore/model/resource_path.h
- Firestore/core/test/firebase/firestore/model/field_path_test.cc
- Firestore/core/test/firebase/firestore/model/resource_path_test.cc
- Firestore/test.sh
- cmake/FindNanopb.cmake
- cmake/external/nanopb.cmake
Let Travis catch issue relevant to style and build error.
> Let Travis run for `CMake` test and `lint.sh`

- Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.h
- Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
- Firestore/core/test/firebase/firestore/auth/firebase_credentials_provider_test.mm
This avoids any problems with callsbacks retaining pointers to objects destroyed by a C++ destructor and also avoids any coupling with the auth notification queue.
> Use a shared_ptr/weak_ptr handoff on FirebaseCredentialsProvider

- Firebase/Core/FIRMutableDictionary.m
- Firebase/Core/FIRNetworkURLSession.m
- Firebase/Core/FIROptions.m
CocoaPods is moving to enable CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF by
default, so enabled it in the project and update the code accordingly.
Blocks within the library implementation direct touch ivars back properties
as part of updating state with doing the work the public access to the
property requires, so use self-> notation to make it an explicit
capture of self instead of an implicit one.
Description thanks to https://github.com/google/gtm-session-fetcher/pull/111
This change will need to be made beyond Core across Firebase open source.
cc: @schmidt-sebastian, @protocol86, @wilhuff, @chliangGoogle
> Fix Core CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF warnings

- Firestore/core/include/firebase/firestore/document_reference.h
- Firestore/core/include/firebase/firestore/event_listener.h
- Firestore/core/include/firebase/firestore/firestore.h
Incomplete, and what does exist in still slightly vague. It's expected
that this will change.
> Strawman C++ API

- Firebase/Core/FIROptions.m
This was picked up in the static analysis tool - we should be explicitly checking `nil` instead of using `!` to do our check if the object is valid or not.
> Move to explicit nil check for conditionals.

- Firestore/core/src/firebase/firestore/model/field_value.cc
- Firestore/core/src/firebase/firestore/model/field_value.h
- Firestore/core/test/firebase/firestore/model/field_value_test.cc
This will complete all sorts of FieldValue.
Part of the C++ migration.
Unit test PASS
n/a
> Update FieldValue of type Reference

- Firebase/Core/Public/FIRApp.h
This wrapper code was only there for Xcode 7 support since Xcode 8 came with the first version of Objective-C that supported class properties.
> Remove compatibility shim for Xcode 7.

- Firebase/Auth/CHANGELOG.md
Auth 4.4.1 was comments only and it looks like the CHANGELOG got off by one since then.
> Fix off-by-one error in Auth changelog

- Firestore/Source/Remote/FSTStream.mm
Actually ignore events on inactive streams, rather than just logging that we're going to.
Other delegate methods already have checks. This one has a check, but previously ignored it other than logging.
I believe this should fix https://github.com/firebase/firebase-ios-sdk/issues/772
>  Ignore events on inactive streams

- Firebase/Core/Public/FIRApp.h
This can be removed at the next breaking change.
```
Test Suite 'All tests' passed at 2018-02-14 12:16:24.406.
Executed 401 tests, with 0 failures (0 unexpected) in 16.931 (18.144) seconds
```
> Remove UIKit dependency in FIRApp.

- README.md
Add code markup to a few paths for consistency.
> Update README.md with code markup

- FirebaseFirestore.podspec
- Firestore/core/src/firebase/firestore/remote/serializer.cc
- cmake/CompilerSetup.cmake
In order to use different cflags for abseil, this patch splits it out into a subspec within the pod.
The cmake side of things "just works" since Firestore/CMakeLists.txt includes abseil before setting our compiler flags.
Clang's doc on -Wcomma: http://clang.llvm.org/docs/DiagnosticsReference.html#wcomma (which isn't terribly useful).
A more useful discussion on -Wcomma from the code review that added it: https://reviews.llvm.org/D3976
> Enable -Wcomma for our build; disable it for abseil.

- FirebaseAuth.podspec
- FirebaseCore.podspec
- FirebaseDatabase.podspec
- FirebaseFirestore.podspec
- FirebaseMessaging.podspec
- FirebaseStorage.podspec
Now that 1.4.0 has been out for awhile, stop allowing beta usage
> Require official 1.4.0 for min CocoaPods version

- FirebaseFirestore.podspec
- Firestore/core/src/firebase/firestore/remote/serializer.cc
absl includes code like this:
```
void fn(std::initializer_list<absl::string_view> pieces) {
...
for (const absl::string_view piece : pieces) total_size += piece.size();
```
clang objects, suggesting that a reference should be used instead, i.e.:
```
for (const absl::string_view& piece : pieces) total_size += piece.size();
```
But:
a) we don't want to touch absl code
b) string_views are cheap to copy (and absl recommends copying
string_views rather than taking references as it may result in smaller
code)
c) some brief, naive benchmarking suggests there's no significant
different in this case (i.e. (b) is correct.)
Note that -Wrange-loop-analysis is already exlicitly enabled in our
cmake build.
> Disable -Wrange-loop-analysis for abseil

- Firestore/Example/Tests/API/FIRFirestoreTests.mm
- Firestore/Source/API/FIRFirestore.mm
> Delete stale Firestore instances after FIRApp is deleted.

- Firestore/Example/Tests/Integration/FSTStreamTests.mm
- Firestore/Source/Remote/FSTStream.mm
In the interest of going for the PRs-based-on-PRs world record, I additionally would like to replace some of our race condition leniency with stricter asserts. I've traced the call sites for each assert and feel pretty confident that they should be safe now.
> Add stricter assertions regarding stream state.

- Firestore/Example/Tests/Integration/FSTStreamTests.mm
- Firestore/Source/Remote/FSTStream.mm
... to dispatch GRPC callbacks directly onto the Firestore worker queue.
This saves a double-dispatch and simplifies our logic.
> Use -[GRPCCall setResponseDispatchQueue]

- Firestore/core/src/firebase/firestore/remote/serializer.cc
The 'unsigned' portion was misleading, as these varints work with both
signed and unsigned integers. (The 'signed' varints also work with both
signed and unsigned integers, but use zig-zag encoding so that negative
numbers are encoded more efficiently. Note that 'signed' varints aren't
used in the Value proto, so won't appear in the serializer class for at
least the short term.)
Added some docstrings to help disambiguate this.
> [En|De]codeUnsignedVarint -> [En|De]codeVarint

- Firestore/Source/Auth/FSTCredentialsProvider.mm
- Firestore/Source/Remote/FSTRemoteStore.mm
- Firestore/Source/Util/FSTAsyncQueryListener.mm
Xcode has starting warning about us implicitly retaining self references
within blocks. (Some of these instances could cause retain cycles.)
This PR addresses these issues.
> Fix implicit retain self warnings

- Firestore/core/test/firebase/firestore/remote/datastore_test.cc
Reduces noise while running valgrind so that I can see the leaks that
I'm introducing. :/
> Fix trivial mem leak in the test suite

- Firestore/Example/Tests/API/FSTAPIHelpers.mm
- Firestore/Example/Tests/Core/FSTQueryTests.mm
- Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
- Firestore/Example/Tests/Integration/FSTStreamTests.mm
- Firestore/Example/Tests/Model/FSTFieldValueTests.mm
- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
- Firestore/Example/Tests/Util/FSTHelpers.h
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/API/FIRFirestore+Internal.h
- Firestore/Source/API/FIRFirestore.mm
- Firestore/core/src/firebase/firestore/model/database_id.cc
- Firestore/core/src/firebase/firestore/model/database_id.h
- Firestore/core/test/firebase/firestore/core/database_info_test.cc
- Firestore/core/test/firebase/firestore/model/database_id_test.cc
Avoids temporary NSStrings that just preserve the old API.
It's not always obvious when constructing NSStrings that they must be copies or not; this avoids the ambiguity by making the arguments `string_views` and thus obviously safe.
>  Avoid wrapping and rewrapping NSStrings when constructing DatabaseId

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests.xcscheme
- Firestore/Example/Tests/API/FIRFirestoreTests.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Source/Auth/FSTCredentialsProvider.mm
- Firestore/core/CMakeLists.txt
- Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.h
- Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
- Firestore/core/src/firebase/firestore/auth/user.h
- Firestore/core/test/firebase/firestore/auth/firebase_credentials_provider_test.mm
- Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
- Firestore/core/test/firebase/firestore/testutil/app_testing.h
- Firestore/core/test/firebase/firestore/testutil/app_testing.mm
- Firestore/test.sh
We got ourselves into a fairly broken state with the last few PRs:
1.  `FIRFirestoreTests` added in #809 uses an expectations API added in Xcode 8.3 (but release builds are still built with 8.2)
2.  However, it wasn't actually added to the project and wasn't running. If it had been we'd have known that...
3.  `auth::User` added in #804 didn't handle the unauthenticated state correctly
In addition to fixing the above, this change:
* Factors out the logic for creating an FIRApp into testutil
* Uses it in the tests for `FirebaseCredentialsProvider`, making them enabled by default
* Adds a test case for the nil UID
* Fixes `Firestore/test.sh` to only run CMake tests once, and make it re-runnable locally
/cc @paulb777 This is a launch blocker
> Fix Firestore tests for M22

- Firestore/Source/Remote/FSTStream.h
This warning was introduced in PR #784 by changing the `FSTStream` initializer but without updating the NS_UNAVAILABLE-marked parent initializers in subclasses.
> Avoid warnings about failing to override a designated initializer

- Firebase/Auth/Source/Public/FIRUser.h
> add FIRUser behavior to documentation

- Firestore/core/src/firebase/firestore/remote/serializer.cc
Since we can't decode a value before knowing it's type, I've pulled the
tag handling out of these methods.
More context over here:
https://github.com/firebase/firebase-ios-sdk/pull/829
> Refactor [En|De]codeVarint to be symetric wrt tags

- Carthage.md
- README.md
First draft of Carthage summary and instructions.
This PR is the first phase of addressing #9.
> Initial Carthage distribution instructions

- Firestore/Example/Tests/SpecTests/FSTMockDatastore.h
- Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/Core/FSTFirestoreClient.mm
/cc @mikelehen futures on iOS!
> Suggested fixes for cpp/port_auth

- .travis.yml
- Example/tvOSSample/tvOSSample/AppDelegate.swift
- Example/tvOSSample/tvOSSample/AuthLoginViewController.swift
- Example/tvOSSample/tvOSSample/AuthViewController.swift
- Example/tvOSSample/tvOSSample/DatabaseViewController.swift
- Example/tvOSSample/tvOSSample/EmailLoginViewController.swift
- Example/tvOSSample/tvOSSample/StorageViewController.swift
- Firestore/Example/SwiftBuildTest/main.swift
- scripts/style.sh
Format swift sources using [SwiftFormat](https://github.com/nicklockwood/SwiftFormat) when using `scripts/style.sh`. This fixes https://github.com/firebase/firebase-ios-sdk/issues/839.
Note SwiftFormat also fixes a few common coding problems. Most notably, it removes `weak` qualifiers from IBOutlets -- since iOS 6 this is no longer recommended.
The tool is imperfect, unfortunately:
* It doesn't implement line wrapping at a fixed length
* It fails when sorting imports (I've disabled this)
However, something is better than nothing and the result is largely in-line with Google's swift style guide.
This change adds a requirement that you have `swiftformat` installed if you're building on macOS.
> Auto-style swift sources

- Example/Shared/FIRSampleAppUtilities.m
- Firebase/Core/FIRApp.m
- Firebase/Core/FIROptions.m
- Firebase/Core/Private/FIRAppInternal.h
- Firebase/Storage/FIRStorageObservableTask.m
- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
- Firestore/Source/Core/FSTFirestoreClient.mm
Adds reporting of the FirebaseCore version as part of the useragent.
> Report FirebaseCore version

- cmake/external/googletest.cmake
- cmake/external/leveldb.cmake
- cmake/external/nanopb.cmake
- cmake/external/protobuf.cmake
Exception: grpc. Due to it's use of git submodules, it's not completely
trivial to convert it (though probably wouldn't be too much more work.)
This reduces the build time and *might* help address build failures on travis.
> Convert cmake build to (mostly) use urls rather than git clones

- Firestore/core/src/firebase/firestore/remote/serializer.cc
- Firestore/core/src/firebase/firestore/remote/serializer.h
- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
This will likely only apply for proto messages that use 'oneof's.
(Because we need to serialize these manually.)
> Eliminate TypedValue and serialize direct from FieldValue to bytes.

- FirebaseFirestore.podspec
Add missing nanopb directory to podspec.  
Otherwise imports of headers in Protos/nanopb fail to compile.
> Fix Firestore podspec overlay build

- Firebase/Messaging/FIRMessagingPendingTopicsList.m
The reference of topic handlers that is used to add completion handler was released unexpectedly, using topic handler directly instead of the reference.
> Fix the issue completion handler is not triggered in subscribeToTopic.

- Firestore/Example/Tests/Core/FSTQueryTests.mm
- Firestore/Example/Tests/Core/FSTViewTests.mm
- Firestore/Example/Tests/Model/FSTPathTests.mm
- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Source/API/FIRCollectionReference.mm
- Firestore/Source/API/FIRDocumentReference.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/Core/FSTQuery.h
- Firestore/Source/Core/FSTQuery.mm
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTLevelDBRemoteDocumentCache.mm
- Firestore/Source/Local/FSTLocalDocumentsView.mm
- Firestore/Source/Local/FSTMemoryMutationQueue.mm
- Firestore/Source/Local/FSTMemoryRemoteDocumentCache.mm
- Firestore/Source/Model/FSTPath.h
- Firestore/Source/Model/FSTPath.mm
- Firestore/Source/Remote/FSTRemoteStore.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/core/src/firebase/firestore/model/base_path.h
- Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
- Firestore/core/test/firebase/firestore/testutil/testutil.cc
- Firestore/core/test/firebase/firestore/testutil/testutil.h
This CL is part of the dissection of the grand RP#865.
* Added temporary converters between FSTBarPath and BarPath, for Bar = {Field, Resource}. The converters are to be removed once all FSTBarPath is ported to BarPath.
* Replace all parameter/return types of FSTBarPath to BarPath in FSTQuery, and change the rest of code accordingly by adding conversions.
* The replacement is restricted to FSTQuery only in order to make the PR small. Eventually all FSTBarPath will be replaced. But I don't want the replacement leaked into other place (e.g. replacing parameter type to avoid conversion in methods not of FSTQuery) to avoid increase the complexity of this PR for review.
Part of the C++ migration.
unit and integration tests pass.
n/a
> add converters and port paths to FSTQuery

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Core/FSTEventManagerTests.mm
- Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
- Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/Util/FSTDispatchQueueTests.mm
- Firestore/Source/Core/FSTEventManager.mm
- Firestore/Source/Core/FSTFirestoreClient.mm
- Firestore/Source/Core/FSTTypes.h
- Firestore/Source/Core/FSTView.mm
- Firestore/Source/Remote/FSTOnlineStateTracker.h
- Firestore/Source/Remote/FSTOnlineStateTracker.mm
- Firestore/Source/Remote/FSTRemoteStore.h
- Firestore/Source/Remote/FSTRemoteStore.mm
- Firestore/Source/Remote/FSTStream.mm
- Firestore/Source/Util/FSTDispatchQueue.h
- Firestore/Source/Util/FSTDispatchQueue.mm
[Port of https://github.com/firebase/firebase-js-sdk/commit/0fa319e5e019dd0d40ab441d2ff9f8f6d4724e43]
* Refactored FSTOnlineState tracking out of FSTRemoteStore and into new
FSTOnlineStateTracker component.
* Added a 10 second timeout to transition from OnlineState.Unknown to
OnlineState.Offline rather than waiting indefinitely for the stream to
succeed or fail.
* Removed hack to run SpecTests using an FSTDispatchQueue that wrapped
dispatch_get_main_queue(). This was incompatible with [FSTDispatchQueue
runDelayedCallbacksUntil:] since it queues work and blocks waiting for
it to complete. Now spec tests create / use a proper FSTDispatchQueue.
* Added a SpecTest to verify OnlineState timeout behavior.
* Misc cleanup:
* Renamed FSTOnlineState states: Failed => Offline, Healthy => Online
* …
> Add 10 second timeout waiting for connection before client behaves as-if offline.

- Firestore/Example/Tests/Model/FSTDocumentKeyTests.mm
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Source/API/FIRCollectionReference.mm
- Firestore/Source/API/FIRDocumentReference.mm
- Firestore/Source/API/FIRDocumentSnapshot.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/Core/FSTQuery.mm
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/Source/Local/FSTLevelDBKey.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTLevelDBQueryCache.mm
- Firestore/Source/Local/FSTLevelDBRemoteDocumentCache.mm
- Firestore/Source/Local/FSTLocalDocumentsView.mm
- Firestore/Source/Local/FSTMemoryMutationQueue.mm
- Firestore/Source/Local/FSTMemoryRemoteDocumentCache.mm
- Firestore/Source/Local/FSTReferenceSet.mm
- Firestore/Source/Model/FSTDocument.mm
- Firestore/Source/Model/FSTDocumentKey.h
- Firestore/Source/Model/FSTDocumentKey.mm
- Firestore/Source/Remote/FSTRemoteStore.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/core/src/firebase/firestore/model/resource_path.h
- Firestore/core/test/firebase/firestore/testutil/testutil.h
This CL is part of the dissection of the grand RP#865.
Replace all parameter/return types of FSTBarPath to BarPath in FSTDocumentKey, and change the rest of code accordingly by adding/removing conversions, where Bar in {Field, Resource}.
The replacement is restricted to FSTDocumentKey only in order to make the PR small. Eventually all FSTBarPath will be replaced. But I don't want the replacement leaked into other place (e.g. replacing parameter type to avoid conversion in methods not of FSTQuery) to avoid increase the complexity of this PR for review.
Part of the C++ migration.
unit and integration tests pass.
n/a
> port paths to FSTDocumentKey

- Example/Auth/Sample/MainViewController.m
- Example/Auth/Tests/FIRAuthTests.m
- Example/Auth/Tests/FIREmailLinkRequestTests.m
- Example/Auth/Tests/FIREmailLinkSignInResponseTests.m
- Example/Auth/Tests/FIRGetOOBConfirmationCodeRequestTests.m
- Example/Firebase.xcodeproj/project.pbxproj
- Firebase/Auth/Source/AuthProviders/EmailPassword/FIREmailAuthProvider.m
- Firebase/Auth/Source/AuthProviders/EmailPassword/FIREmailPasswordAuthCredential.h
- Firebase/Auth/Source/AuthProviders/EmailPassword/FIREmailPasswordAuthCredential.m
- Firebase/Auth/Source/FIRAuth.m
- Firebase/Auth/Source/Public/FIRAuth.h
- Firebase/Auth/Source/Public/FIREmailAuthProvider.h
- Firebase/Auth/Source/RPCs/FIRAuthBackend.h
- Firebase/Auth/Source/RPCs/FIRAuthBackend.m
- Firebase/Auth/Source/RPCs/FIRCreateAuthURIResponse.h
- Firebase/Auth/Source/RPCs/FIREmailLinkSignInRequest.h
- Firebase/Auth/Source/RPCs/FIREmailLinkSignInRequest.m
- Firebase/Auth/Source/RPCs/FIREmailLinkSignInResponse.h
- Firebase/Auth/Source/RPCs/FIREmailLinkSignInResponse.m
- Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeRequest.h
- Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeRequest.m
Adds email link sign-in API to Firebase Authentication.
> Adds Email link sign-in

- Firestore/test.sh
- scripts/build.sh
- test.sh
This is a preparatory step for getting higher resolution timing data out of travis and also for parallelizing the travis build.
For the moment this is functionally equivalent to what came before.
> Factor out a universal build script

- .travis.yml
- scripts/check_copyright.sh
- scripts/check_whitespace.sh
- scripts/lint.sh
- scripts/style.sh
Use revision ranges in all source checking commands. Cumulative time for all checks down from 16s to 0.3s.
Other cleanup:
* Factor out scripts so they can be tested stand-alone
* Group all source checks first to fail builds without building
> Speed up source checks in Travis

- Firestore/core/src/firebase/firestore/model/field_value.cc
- Firestore/core/src/firebase/firestore/model/field_value.h
- Firestore/core/src/firebase/firestore/remote/serializer.cc
- Firestore/core/test/firebase/firestore/model/field_value_test.cc
- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
These can (recursively) contain other FieldValues.
> [De]Serialize FieldValue map_values ("Objects")

- Firestore/CHANGELOG.md
- Firestore/Source/Remote/FSTDatastore.mm
- Firestore/Source/Remote/FSTStream.mm
This is a more minimal alternative to #887.
> Minimal fix for b/74357976.

- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Remote/FSTDatastore.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/Source/Remote/FSTStream.mm
This fixes a known instance of memory corruption where in
FSTLevelDBMutationQueue, the NSString view was retained for later, and
the incorrect user was used, causing b/74381054.
gRPC does not necessarily copy its string arguments and if our hostname
were configured to a non-default one it's possible that we could corrupt
the host cache too.
All remaining usages of util::WrapNSStringNoCopy are obviously safe:
passed into logging or other known transient usages.
> Copy all C++ strings to NSString where they're not obviously safe

- Firestore/core/src/firebase/firestore/remote/serializer.cc
Wraps the varint based encode methods.
> Partial wrapping of pb_ostream_t (pt1)

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
- Firestore/Example/Tests/SpecTests/json/write_spec_test.json
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTMemoryMutationQueue.mm
Port of: https://github.com/firebase/firebase-js-sdk/pull/559
Fixes #772
getNextMutationBatchAfterBatchId() was not respecting
highestAcknowledgedBatchId and therefore we were resending writes after the
network was disabled / re-enabled.
> Fix MutationQueue issue resulting in re-sending acknowledged writes.

- Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
- Firestore/core/src/firebase/firestore/util/ordered_code.cc
- Firestore/core/test/firebase/firestore/immutable/array_sorted_map_test.cc
Steps to reproduce:
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
make -j
```
> Fix test failures that occur during prod build

- Firestore/core/src/firebase/firestore/remote/serializer.cc
Uses a custom pb_ostream_t. Previously used a stack allocated 1k buffer.
> Allow serializing arbitrary length FieldValues

- Firestore/core/src/firebase/firestore/remote/serializer.cc
Wraps encoding of FieldValue "Objects" (i.e. map<string, FieldValue>'s)
and their entries (i.e. pair<string, FieldValue>'s)
> Partial wrapping of pb_ostream_t (pt4)

- Firestore/Example/Tests/Integration/FSTStreamTests.mm
- Firestore/Example/Tests/Util/FSTDispatchQueueTests.mm
- Firestore/Source/Remote/FSTStream.mm
- Firestore/Source/Util/FSTDispatchQueue.h
- Firestore/Source/Util/FSTDispatchQueue.mm
Track operation in progress FSTDispatchQueue and allow dispatchAsync onto the worker queue even from the same queue if an operation is not in progress. Fixes #753.
This fixes a corner case that happens when users pass us an object and we retain that object in a block submitted to the worker queue for processing. Users are not obligated to retain that object themselves. This can lead to the object's destructor (or dealloc or deinit) being called on the Firestore worker thread. If that destructor makes Firestore API calls (most likely ListenerRegistration.remove but any are possible) this will trigger the assertion.
> Defend against users making API calls during deinit

- Firestore/core/src/firebase/firestore/core/target_id_generator.cc
- Firestore/core/src/firebase/firestore/core/target_id_generator.h
- Firestore/core/src/firebase/firestore/model/CMakeLists.txt
- Firestore/core/src/firebase/firestore/model/types.h
This prevents a core -> local -> core dependency
> Move core/types.h to model to prevent dependency cycle

- Firebase/Auth/Source/FIRAuth.m
- scripts/style.sh
Adds exception for invalid parameter when handleCodeInApp is not set to true, because an authentication action should always be handled in the app.
> Adds exception for invalid parameter

- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
I renamed these during code review iterations but missed the string constants.  Fortunately we would have noticed when we actually used them in a spec test (the method would throw and fail the test).
> Fix FSTTimerID strings in spec tests to match constants used in web.

- Firestore/Source/Remote/FSTDatastore.mm
- Firestore/Source/Remote/FSTStream.mm
- Firestore/core/src/firebase/firestore/auth/credentials_provider.h
- Firestore/core/src/firebase/firestore/auth/empty_credentials_provider.cc
- Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
- Firestore/core/src/firebase/firestore/auth/token.cc
- Firestore/core/src/firebase/firestore/auth/token.h
- Firestore/core/src/firebase/firestore/util/error_apple.h
- Firestore/core/test/firebase/firestore/auth/credentials_provider_test.cc
- Firestore/core/test/firebase/firestore/auth/empty_credentials_provider_test.cc
- Firestore/core/test/firebase/firestore/auth/firebase_credentials_provider_test.mm
- Firestore/core/test/firebase/firestore/auth/token_test.cc
Rather than a token plus error code/msg.
This eliminates the concept of an "invalid" token, though an unauthenticated token is still possible.
> Change CredentialsProvider::TokenListener to use StatusOr<Token>

- Firebase/Core/Public/FIRApp.h
- Firebase/Core/Public/FIROptions.h
This notifies developers that synchronous file I/O occurs on certain calls to `FIRApp` and `FIROptions`.
> Add file I/O usage to Core documentation.

- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
- Firestore/Example/Tests/SpecTests/json/resume_token_spec_test.json
- Firestore/Source/Remote/FSTExponentialBackoff.h
- Firestore/Source/Remote/FSTExponentialBackoff.mm
- Firestore/Source/Remote/FSTStream.mm
- Firestore/Source/Util/FSTDispatchQueue.mm
This re-enables the assert we removed for the 4.11.0 release and ports the proper fix (https://github.com/firebase/firebase-js-sdk/pull/564).
> Fix for b/74749605: Cancel pending backoff operations when closing streams.

- Firestore/core/src/firebase/firestore/remote/serializer.cc
- Firestore/core/src/firebase/firestore/remote/serializer.h
- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
* Rename Writer::Encode* methods to Writer::Write*
* Rename: s/stream/writer/ (approximately)
but only where it applies to Writer (rather than pb_ostream_t).
> Renames in serializer to reflect recent changes

- Firestore/Example/Tests/Local/FSTQueryCacheTests.mm
fix a typo caused in the merge a2a109b (https://github.com/firebase/firebase-ios-sdk/pull/963/commits/a2a109ba9773f5b7eae325d92b58dddc83c27a4b)
n/a
n/a
n/a
> fix a typo that breaks build

- Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
- Firestore/Source/API/FIRTransaction.mm
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/Source/Core/FSTTransaction.h
- Firestore/Source/Core/FSTTransaction.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Remote/FSTDatastore.h
- Firestore/Source/Remote/FSTDatastore.mm
- Firestore/Source/Remote/FSTRemoteEvent.h
- Firestore/Source/Remote/FSTRemoteEvent.mm
- Firestore/Source/Remote/FSTRemoteStore.mm
- Firestore/Source/Remote/FSTSerializerBeta.h
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/Source/Remote/FSTWatchChange.h
- Firestore/Source/Remote/FSTWatchChange.mm
Part of the C++ migration. Now `FSTDocumentKey` is replaced by `firebase::firestore::model::DocumentKey` in `Remote/*`.
unit and integration tests pass.
n/a
> port C++ `DocumentKey` to `Remote/*`

- README.md
Improve docs after feedback at https://twitter.com/mxcl/status/977576224276058112
> Improve macOS/tvOS installation instructions

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Source/Remote/FSTOnlineStateTracker.h
- Firestore/Source/Remote/FSTOnlineStateTracker.mm
Port of https://github.com/firebase/firebase-js-sdk/pull/592 (plus renamed watchStreamTimer => onlineStateTimer for consistency)
FSTOnlineStateTracker was reverting to OnlineState Unknown on every stream attempt
rather than remaining Offline once the offline heuristic had been met (i.e. 2
stream failures or 10 seconds). This means that getDocument() requests made while
offline could be delayed up to 10 seconds each time (or until the next backoff
attempt failed).
> Fix issue that could cause offline get()s to wait up to 10 seconds.

- Firestore/CMakeLists.txt
- Firestore/Protos/CMakeLists.txt
This is motivated by wanting to use libprotobuf in the project too, but
it's also sensible by itself.
> Only add nanopb proto headers to the -I path when depending on the nanopb protos

- Firestore/Example/Tests/Core/FSTSyncEngine+Testing.h
- Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
- Firestore/Source/API/FIRCollectionReference.mm
- Firestore/Source/API/FIRDocumentReference+Internal.h
- Firestore/Source/API/FIRDocumentReference.mm
- Firestore/Source/API/FIRDocumentSnapshot+Internal.h
- Firestore/Source/API/FIRDocumentSnapshot.mm
- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/API/FSTUserDataConverter.h
- Firestore/Source/API/FSTUserDataConverter.mm
- Firestore/Source/Core/FSTQuery.h
- Firestore/Source/Core/FSTQuery.mm
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/Source/Core/FSTTransaction.h
- Firestore/Source/Core/FSTTransaction.mm
- Firestore/Source/Core/FSTView.h
- Firestore/Source/Core/FSTView.mm
- Firestore/Source/Core/FSTViewSnapshot.mm
- Firestore/Source/Model/FSTMutationBatch.mm
- Firestore/Source/Remote/FSTRemoteStore.h
- Firestore/Source/Remote/FSTRemoteStore.mm
- Firestore/Source/Remote/FSTStream.h
- Firestore/Source/Remote/FSTWatchChange.mm
- Firestore/core/src/firebase/firestore/model/base_path.h
- Firestore/core/src/firebase/firestore/model/database_id.h
- Firestore/core/src/firebase/firestore/model/document_key.h
Part of the C++ migration. Now `FSTDocumentKey` is replaced by `firebase::firestore::model::DocumentKey` in the rest of Firestore code, excluding `Model` containers class.
Audited all references by `git grep FSTDocumentKey[^A-Z] | grep -v enumerateObjectsUsingBlock | grep -v enumerateKeysAndObjectsUsingBlock | grep -v "Local/FSTLevelDBKey" | grep -v "Model/FSTDocumentKey"`.
unit and integration tests pass.
n/a
> port C++ DocumentKey to the rest of Firestore code

- Firestore/Source/Model/FSTDocumentKey.mm
- Functions/.clang-format
- Functions/Example/FirebaseFunctions/FIRAppDelegate.h
- Functions/FirebaseFunctions/Public/FIRHTTPSCallable.h
1. Manually fixed a line line in Functions that was >100 chars with clang-format disabled.
2. Removed the custom .clang-format for Functions, which only affected one line.
3. Re-ran style.sh, which just removed one blank line in a Firestore file.
> Fix some formatting issues.

- Firestore/core/src/firebase/firestore/immutable/CMakeLists.txt
- Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
- Firestore/core/src/firebase/firestore/immutable/llrb_node.h
- Firestore/core/src/firebase/firestore/immutable/sorted_map.h
- Firestore/core/src/firebase/firestore/immutable/sorted_map_base.cc
- Firestore/core/src/firebase/firestore/immutable/sorted_map_base.h
- Firestore/core/src/firebase/firestore/immutable/tree_sorted_map.h
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/comparator_holder.h
- Firestore/core/test/firebase/firestore/immutable/CMakeLists.txt
- Firestore/core/test/firebase/firestore/immutable/array_sorted_map_test.cc
- Firestore/core/test/firebase/firestore/immutable/sorted_map_test.cc
- Firestore/core/test/firebase/firestore/immutable/testing.h
- Firestore/core/test/firebase/firestore/immutable/tree_sorted_map_test.cc
This is a start toward the full implementation of the immutable sorted map in C++. It
* Defines `TreeSortedMap` to complement the existing `ArraySortedMap`
* Leaves much of `TreeSortedMap` unimplemented though; that will come in another PR.
* Defines the `SortedMap` wrapper type that delegates to the correct underlying implementation
* Practically though this only ever uses arrays now
* Defines common testing infrastructure for all three implementations
* Move some the tests that apply to all implementations from `array_sorted_map_test.cc` to `sorted_map_test.cc`. There aren't many yet though.
Note that the structure of these classes is somewhat awkward but this works around limitations in the C++ language. In particular:
* We need these types to be cheaply copyable
* Polymorphic behavior …
> Initial TreeSortedMap and SortedMap in C++

- Firestore/Example/Tests/Local/FSTLevelDBMutationQueueTests.mm
- Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
- Firestore/Example/Tests/Local/FSTQueryCacheTests.mm
- Firestore/Example/Tests/Local/FSTRemoteDocumentCacheTests.mm
- Firestore/Example/Tests/Local/FSTRemoteDocumentChangeBufferTests.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTLevelDBQueryCache.mm
- Firestore/Source/Local/FSTLevelDBRemoteDocumentCache.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Local/FSTMemoryMutationQueue.mm
- Firestore/Source/Local/FSTMemoryQueryCache.mm
- Firestore/Source/Local/FSTMemoryRemoteDocumentCache.mm
- Firestore/Source/Local/FSTMutationQueue.h
- Firestore/Source/Local/FSTPersistence.h
- Firestore/Source/Local/FSTQueryCache.h
- Firestore/Source/Local/FSTRemoteDocumentCache.h
- Firestore/Source/Local/FSTRemoteDocumentChangeBuffer.mm
Removes usages of `FSTWriteGroup` in `FSTMutationQueue`, `FSTQueryCache`, and `FSTRemoteDocumentCache` APIs.
The changes are mostly mechanical at this stage, although there is some consideration in the tests for what operations should be lumped into a single transaction vs changing the meaning of the test by inspecting results before committing. Theoretically, only tests that involve restarting some component should need to rely on committing changes before inspecting.
> Remove some usages of FSTWriteGroup

- Firestore/Example/Tests/Local/FSTLevelDBQueryCacheTests.mm
- Firestore/Example/Tests/Local/FSTLevelDBRemoteDocumentCacheTests.mm
- Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
- Firestore/Example/Tests/Local/FSTMemoryQueryCacheTests.mm
- Firestore/Example/Tests/Local/FSTMemoryRemoteDocumentCacheTests.mm
- Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
- Firestore/Example/Tests/Local/FSTQueryCacheTests.mm
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
- Firestore/Source/Core/FSTFirestoreClient.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTLevelDBQueryCache.mm
- Firestore/Source/Local/FSTLevelDBRemoteDocumentCache.mm
- Firestore/Source/Local/FSTLocalStore.h
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Local/FSTMemoryMutationQueue.mm
- Firestore/Source/Local/FSTMemoryQueryCache.mm
- Firestore/Source/Local/FSTMemoryRemoteDocumentCache.mm
- Firestore/Source/Local/FSTMutationQueue.h
- Firestore/Source/Local/FSTQueryCache.h
- Firestore/Source/Local/FSTRemoteDocumentCache.h
There was no longer logic in any of these shutdown methods, so now they are gone:
- FSTRemoteDocumentCache
- FSTQueryCache
- FSTMutationQueue
- FSTLocalStore
In particular, this makes it more obvious that none of the above own the persistence layer, as none of them were responsible for freeing resources associated with persistence.
> Remove unused shutdown methods

- Firestore/core/test/firebase/firestore/timestamp_test.cc
Some Timestamp tests check that constructor fails if given values beyond
the supported (pretty wide) range. In case Timestamp is created from
chrono::time_point, the time_point's underlying duration is
implementation-defined and may overflow when tests try to set it to
a value beyond Timestamp supported range. To work around this, make
these tests not run if time_point cannot represent boundary values on
this platform. For example, on OS X, time_point has microseconds
precision, so the tests may run, but on Linux, time_point has
nanoseconds precision, which would overflow.
> C++ migration: fix some Timestamp tests failing on Linux.

- Firestore/core/src/firebase/firestore/util/status.cc
- Firestore/core/src/firebase/firestore/util/status.h
Fix undefined symbol build issue on optimized internal build
```
Undefined symbols for architecture x86_64:
"std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::operator<<<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
firebase::firestore::util::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, firebase::firestore::util::Status const&) in libutil.a(status_4f26d5dc4d6a6a2916fcdabc61c4b805.o)
ld: symbol(s) not found for architecture x86_64
```
> Fix optimized build missing symbol issue

- Example/Messaging/Tests/FIRMessagingPendingTopicsListTest.m
- Example/Messaging/Tests/FIRMessagingRegistrarTest.m
- Example/Messaging/Tests/FIRMessagingServiceTest.m
- Firebase/Messaging/FIRMessagingClient.h
- Firebase/Messaging/FIRMessagingClient.m
- Firebase/Messaging/FIRMessagingPendingTopicsList.h
- Firebase/Messaging/FIRMessagingPendingTopicsList.m
- Firebase/Messaging/FIRMessagingPubSub.h
- Firebase/Messaging/FIRMessagingPubSub.m
- Firebase/Messaging/FIRMessagingRegistrar.h
- Firebase/Messaging/FIRMessagingRegistrar.m
- Firebase/Messaging/FIRMessagingTopicOperation.h
- Firebase/Messaging/FIRMessagingTopicOperation.m
- Firebase/Messaging/FIRMessagingTopicsCommon.h
- Firebase/Messaging/NSError+FIRMessaging.h
- Firebase/Messaging/Public/FIRMessaging.h
* These methods are pre-existed internally, we are exposing them to public.
* I simplify the completion to a NSError instead of enum results. I used an error code to specify the operation is canceled result.
> Adding a new topic subscription/unsubcription with completion handler method

- Firebase/Auth/Source/Public/FIRUser.h
Removes deprecation message for getIDTokenWithCompletion: and getIDTokenForcingRefresh:completion.  This methods are not being deprecated.
> Removes deprecation messages getIDToken APIs

- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessagingTopicOperation.m
When subscription failed, we used to log only a plain message which is not helpful if we want to debug server issues.
> improve logging when subscription failed

- Firebase/Messaging/Public/FIRMessaging.h
The internal header had `NS_ASSUME_NONNULL_BEGIN/END` but the public header does not.
> Fix nullability warning with new Messaging API

- Functions/FirebaseFunctions/Public/FIRError.h
[THIS IS A BREAKING CHANGE]
The `FIR` prefix should be removed from `FIRFunctionsErrorCode`. This does just that.
> [BREAKING] Remove FIR prefix on FIRFunctionsErrorCode

- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/Public/FIRMessaging.h
Simplify the shouldEstablishDirectChannel property and remove remoteMessageDelegate property.
> Remove deprecated remoteMessageDelegate

- Example/Core/Tests/FIRLoggerTest.m
FIRLoggerTests depend on C functions in FIRLogger only built with #ifdef DEBUG
Addresses internal b/77335272
> Enable Core Unit Tests to run in a Release config

- Firestore/core/src/firebase/firestore/geo_point.cc
- Firestore/core/src/firebase/firestore/util/comparison.cc
Since we now include cmath rather than math.h, isnan is now named
std::isnan.
> Fix build on linux due to isnan not being present.

- Example/Core/Tests/FIRAppTest.m
- Example/Core/Tests/FIROptionsTest.m
- Example/Core/Tests/FIRTestCase.m
- Firebase/Core/CHANGELOG.md
- Firebase/Core/FIRApp.m
- Firebase/Core/FIRConfiguration.m
- Firebase/Core/FIROptions.m
- Firebase/Core/Public/FIRApp.h
- Firebase/Core/Public/FIRConfiguration.h
- Firebase/Core/Public/FIROptions.h
- Firebase/Core/third_party/FIRAppEnvironmentUtil.m
This change introduces breaking changes for the next major Firebase release. It removes deprecated methods, the dependency on UIKit, and removes Xcode 7 support.
> Core Breaking API Changes

- Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
- Firestore/core/src/firebase/firestore/util/firebase_assert.h
Remove a duplicate macro definition and clean up an extra `const` clang-tidy complains about.
> Minor cleanups to firebase_assert.h

- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
This makes it easier to write an async queue library that depends upon the log/assert implementation, without needing to know which it one it is.
This makes it possible for `firebase_firestore_util_async_queue_libdispatch` to depend upon `${FIREBASE_FIRESTORE_UTIL_LOG}`.
> Make it easier to consume sub-libraries within util

- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
- Firebase/Messaging/Public/FIRMessaging.h
Remove the deprecated data message callback.
Also fix the issue swizzling was not setup properly for recommended data message callback. When swizzling is enabled, the recommended data message callback should trigger message tracking.
> remove deprecated data message callback 

- Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
- Firestore/Source/API/FIRFieldValue+Internal.h
- Firestore/Source/API/FIRFieldValue.mm
- Firestore/Source/API/FSTUserDataConverter.mm
Port of https://github.com/firebase/firebase-js-sdk/commit/b14678002bf6e8cc9ebd7561efbafe29315ceb8e and https://github.com/firebase/firebase-js-sdk/commit/b14678002bf6e8cc9ebd7561efbafe29315ceb8e.
> Small cleanup to UserDataConverter / FieldValue sentinel code to make adding more FieldValue sentinels easier.

- Example/Messaging/Tests/FIRMessagingServiceTest.m
- Firebase/Messaging/FIRMessagingPubSub.h
- Firebase/Messaging/FIRMessagingPubSub.m
Also ignore the nonnull warning when intentionally passing a nil parameter.
> Options should be nullable for subscription

- Firestore/third_party/abseil-cpp/absl/base/inline_variable_test.cc
- Firestore/third_party/abseil-cpp/absl/base/inline_variable_test_a.cc
- Firestore/third_party/abseil-cpp/absl/base/inline_variable_test_b.cc
- Firestore/third_party/abseil-cpp/absl/base/internal/identity.h
- Firestore/third_party/abseil-cpp/absl/base/internal/inline_variable.h
- Firestore/third_party/abseil-cpp/absl/base/internal/inline_variable_testing.h
- Firestore/third_party/abseil-cpp/absl/types/bad_optional_access.cc
- Firestore/third_party/abseil-cpp/absl/types/bad_optional_access.h
- Firestore/third_party/abseil-cpp/absl/types/optional.cc
- Firestore/third_party/abseil-cpp/absl/types/optional.h
- Firestore/third_party/abseil-cpp/absl/utility/utility.h
Based on abseil version bf7fc99, the same version as the other imported abseil libraries. Import abseil::optional and dependency files.
> carbon-copy of the `optional`-relevant src from abseil

- Example/Storage/Tests/Integration/FIRStorageIntegrationTests.m
- Example/Storage/Tests/Unit/FIRStorageMetadataTests.m
- Firebase/Storage/CHANGELOG.md
- Firebase/Storage/FIRStorageErrors.m
- Firebase/Storage/FIRStorageGetDownloadURLTask.m
- Firebase/Storage/FIRStorageGetMetadataTask.m
- Firebase/Storage/FIRStorageMetadata.m
- Firebase/Storage/FIRStorageReference.m
- Firebase/Storage/FIRStorageUpdateMetadataTask.m
- Firebase/Storage/FIRStorageUploadTask.m
- Firebase/Storage/Private/FIRStorageConstants_Private.h
- Firebase/Storage/Private/FIRStorageErrors.h
- Firebase/Storage/Private/FIRStorageGetDownloadURLTask.h
- Firebase/Storage/Private/FIRStorageGetDownloadURLTask_Private.h
- Firebase/Storage/Public/FIRStorageMetadata.h
- Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
This PR removes download URL handling from FIRStorageMetadata and adds a new Download URL Task that is then used in FIRStorageReference.
> Removing FirebaseStorage.downloadURL

- Firestore/CHANGELOG.md
- Firestore/Example/SwiftBuildTest/main.swift
- Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
- Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
- Firestore/Source/API/FIRDocumentChange+Internal.h
- Firestore/Source/API/FIRDocumentChange.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/API/FIRQuerySnapshot.mm
- Firestore/Source/Public/FIRQuery.h
- Firestore/Source/Public/FIRQuerySnapshot.h
Instead of calling
addSnapshotListener(
options:QueryListenOptions.includeQueryMetadataChanges()
.includeDocumentMetadataChanges())
call
addSnapshotListener(includeMetadataChanges:true)
Also change `QuerySnapshot.documentChanges()` into a method which
optionally takes `includeMetadataChanges:true`. By default even when
listening to a query with `inlcudeMetadataChanges:true` metadata-only
document changes are suppressed because they're confusing.
> Replace `QueryListenOptions` with simple booleans

- Firestore/core/src/firebase/firestore/local/leveldb_transaction.cc
Change Next() to avoid advancing past the end of either iterator by only
advancing if !advanced and if the iterator is still valid.
If Next() is called after the last entry is deleted, SyncToTransaction()
returns false indicating it hasn't advanced but at that point is_valid_
is false. Previously Next() would then attempt to advance one of the
underlying iterators and if it was the mutations_iter_ would advance
past the end, which would cause the next UpdateCurrent() to dereference
random memory.
> Fix iteration past end in LevelDBTransaction::Iterator

- Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
Rewrites local store tests so that documents are added to existing targets as a means of getting them into the cache. This replaces the existing mechanism of pretending that documents come in as part of limbo document resolution. This paves the way for handling limbo resolution specially with different GC schemes.
> Rewrite some LocalStore tests

- Example/Core/Tests/FIRAppEnvironmentUtilTest.m
- Example/Firebase.xcodeproj/project.pbxproj
- Firebase/Core/third_party/FIRAppEnvironmentUtil.m
Since we moved to a new `systemVersion` implementation, we need to match the previous functionality's output.
> Match previous systemVersion functionality

- Firebase/Auth/Source/FIRUser.m
Adds documentation for the parseIDToken function which proved to be a little tricky due to its use of Apple's NSJSONSerialization API's.
> Adds documentation for parseIdToken

- FirebaseAuth.podspec
- FirebaseCore.podspec
- FirebaseDatabase.podspec
- FirebaseFirestore.podspec
- FirebaseFunctions.podspec
- FirebaseMessaging.podspec
- FirebaseStorage.podspec
Update the seven podspecs for Firebase 5
They're deployed for internal testing at https://cpdc-eap.git.corp.google.com/io2018/ along with preliminary versions of the Firebase, FirebaseAnalytics, and FirebaseInstanceID pods.
To try out, update Podfile with 
```
source 'sso://cpdc-eap/io2018'
source 'https://github.com/CocoaPods/Specs.git'
```
> podspec updates for Firebase 5

- Firebase/Auth/Source/FIRUser.m
Fixes error handling when parsing ID Tokens. Ideally the token parsing should never generate an error.  This is in the unlikely event that one does occur.
> Fixes error handling when parsing tokens.

- scripts/build.sh
In CMake build of Firestore, configure CTest so that upon failure, it
prints out the full log of the failing test(s).
> Firestore Travis: ensure CTest outputs the log on failure.

- Firestore/Example/Tests/Integration/API/FIRFirestoreSourceTests.mm
Instead of calling
```
setData(["a": "b"], options: SetOptions.merge())
```
call
```
setData(["a": "b"], merge: true)
```
Add the usage missed in PR #1098
> Replace the `SetOptions` object with a simple boolean (cont.)

- Firestore/core/src/firebase/firestore/immutable/CMakeLists.txt
- Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
- Firestore/core/src/firebase/firestore/immutable/llrb_node.h
- Firestore/core/src/firebase/firestore/immutable/llrb_node_iterator.h
- Firestore/core/src/firebase/firestore/immutable/sorted_map.h
- Firestore/core/src/firebase/firestore/immutable/sorted_map_iterator.h
- Firestore/core/src/firebase/firestore/immutable/tree_sorted_map.h
- Firestore/core/test/firebase/firestore/immutable/sorted_map_test.cc
- Firestore/core/test/firebase/firestore/immutable/testing.h
- Firestore/core/test/firebase/firestore/immutable/tree_sorted_map_test.cc
This differs from the `NSEnumerator` Objective-C implementation and the `Iterator` Android implementation because C++ iterators don't self terminate, instead you create an explicit end-state iterator and iterate up to the point where the current iterator is the same as the end.
This deviation in implementation is worthwhile because it allows our immutable maps to be used in C++11 range-based for loops.
> Implement iterators for our immutable maps

- Example/Messaging/Tests/FIRMessagingTest.m
Replaced the private invocation method with the pubic one:  getArgument:atIndex:. The public one was causing bad memory access due to unnecessary nullify mocking object.
> replace the private OCMock method with a public one

- .travis.yml
because of url validation failures today
> Temporarily disable pod lib lint

- Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/Source/Core/FSTView.h
- Firestore/Source/Remote/FSTRemoteEvent.h
- Firestore/Source/Remote/FSTRemoteEvent.mm
Attempts to filter out what would be no-op writes to target-document and document-target indexes for documents that have already been associated with a target. The criteria used are:
* the target is not a limbo-resolution target
* the change is an update, not a reset
I am asserting that the associated view exists, which I *think* is ok based on the work done in the remote store to only pass along events for listens that have been issued and are still live. By filtering out limbo resolution, we should just be left with targets for which we have a live view.
> Filter out document updates from target association changes

- Firebase/Messaging/FIRMessagingClient.m
- Firebase/Messaging/FIRMessagingRegistrar.m
This fixes a bug that when we delete IID, IID refreshes new checkin info and FCM stops querying the checkin if checkin exists. And this causes FCM using staled checkin info and not able to receive data message.
There was a check to see if a valid checkin info existed before query checkin. This is not a proper check because when checkin is refreshed, checkin info do existed, but we still need to perform the query to get the latest checkin. So remove the check.
Also remove some extra tryToLoadValidCheckinInfo check since the function it's called after that will trigger the tryToLoadValidCheckinInfo check anyway.
> Should always query the latest checkin info from InstanceID

- Firestore/core/src/firebase/firestore/model/field_value.cc
Should check `object_map.end()` instead of `copy.end()` after a suggested refactoring. Interestingly, the unset memory matches the empty object `FieldValue` and thus test still pass even with the bug, if not checking unallocated memory access...
> fix a bug caught by asan failure

- Example/Firebase.xcodeproj/project.pbxproj
- Firebase/Auth/Source/FIRAuthNotificationManager.m
Disable a tvOS deprecated API and disable FIRAuthNotificationManagerTests.m for tvOS
This along with https://github.com/google/google-toolbox-for-mac/issues/162 is necessary to get `pod lib lint FirebaseAuth.podspec` to succeed without warnings.
> Eliminate an Auth tvOS build warning

- Firebase/Auth/Source/FIRAuthWebUtils.h
- Firebase/Auth/Source/FIRAuthWebUtils.m
Adding FIRAuthWebUtils was a last minute add to #1175 and it somehow passed travis - perhaps due to lingering state.
This PR fixes the master build break.
> Remove unnecesary function that broke build

- Example/Auth/Sample/MainViewController.m
- Example/Auth/Tests/FIRAuthTests.m
- Example/Auth/Tests/FIRUserTests.m
- Firebase/Auth/Source/FIRAuth.m
- Firebase/Auth/Source/Public/FIRAuth.h
Introduces first set of Auth breaking changes; adds the FIRAuthDataResult to most of the original authentication methods and deprecates the corresponding "AndRetrieve" methods.
> First pass of Auth breaking changes

- Firebase/Core/FIRNetworkURLSession.m
- Firebase/Database/FViewProcessor.m
- Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
Fix the following issues when running `pod lib lint` with Xcode 9.3:
```
-> FirebaseCore (5.0.0)
- WARN  | [OSX] xcodebuild:  FirebaseCore/Firebase/Core/FIRNetworkURLSession.m:240:1: warning: implementing unavailable method [-Wdeprecated-implementations]
- NOTE  | [OSX] xcodebuild:  /Applications/Xcode9.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLSession.h:710:1: note: method 'URLSessionDidFinishEventsForBackgroundURLSession:' declared here
```
```
-> FirebaseDatabase (5.0.0)
- WARN  | [iOS] xcodebuild:  FirebaseDatabase/Firebase/Database/FViewProcessor.m:200:107: warning: enum values with underlying type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' …
```
> Fix new Xcode 9.3 warnings

- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Source/Local/FSTLevelDBQueryCache.mm
- Firestore/Source/Local/FSTLocalDocumentsView.mm
- Firestore/Source/Local/FSTLocalSerializer.h
- Firestore/Source/Local/FSTLocalSerializer.mm
- Firestore/Source/Local/FSTLocalStore.h
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Local/FSTMemoryQueryCache.mm
- Firestore/Source/Local/FSTQueryCache.h
- Firestore/Source/Local/FSTQueryData.h
- Firestore/Source/Local/FSTQueryData.mm
- Firestore/core/src/firebase/firestore/model/snapshot_version.h
This is part of the C++ migration. Replace `FSTSnapshotVersion` by C++ `SnapshotVersion` in the `Local` modulo.
Integration and unit test pass.
n/a
> Port `SnapshotVersion` for `Local`

- Firestore/Example/Tests/Integration/FSTStreamTests.mm
- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
- Firestore/Example/Tests/SpecTests/FSTMockDatastore.h
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/Source/Local/FSTLocalSerializer.mm
- Firestore/Source/Remote/FSTDatastore.h
- Firestore/Source/Remote/FSTRemoteEvent.h
- Firestore/Source/Remote/FSTRemoteEvent.mm
- Firestore/Source/Remote/FSTRemoteStore.mm
- Firestore/Source/Remote/FSTSerializerBeta.h
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/Source/Remote/FSTStream.h
- Firestore/Source/Remote/FSTStream.mm
- Firestore/Source/Remote/FSTWatchChange.h
- Firestore/core/src/firebase/firestore/model/snapshot_version.h
This is part of the C++ migration. Replace `FSTSnapshotVersion` by C++ `SnapshotVersion` in the `Remote` modulo.
Integration and unit test pass.
n/a
> Port `SnapshotVersion` for `Remote`

- Firebase/Auth/Source/FIRUser.m
- Firebase/Auth/Source/Public/FIRUser.h
getToken:completion: and getTokenForcingRefresh:completion: have been deprecated for quite some time and will be removed in the next breaking change.
> Removes deprecated getToken APIs

- Functions/FirebaseFunctions/Public/FirebaseFunctions.h
Add an explicit Functions umbrella header so that Functions is included in the Firebase module.
Fixes internal issue: b/78594146
> Add explicit Functions umbrella

- .travis.yml
From Dominic at Travis support:
Thanks for the update and sending these instances of your issue.
To hopefully prevent this from happening, could you try to pre-start the simulator as soon as possible in your build e.g. as the first line in the "before_install" of your .travis.yml file?
Here's a snippet that should do it:
before_install:
- npm install ios-sim -g
- ios-sim start --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-7, 10.2"
Note that you'll need to replace the device type id and iOS version with the one you need in your build. This way the simulator will have more time to warm up and it will possibly make your builds more stable.
> Try recommended stability improvements and restoring pod lib lint

- Firebase/Core/FIRLogger.m
This isn't needed anymore due to the minimum required version being bumped to iOS 8.
> Remove iOS 7 Simulator check from FIRLogger.

- Example/Auth/Sample/MainViewController.m
- Example/Auth/Tests/FIRPhoneAuthProviderTests.m
- Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
- Firebase/Auth/Source/Public/FIRPhoneAuthProvider.h
Removes the deprecated verifyPhoneNumber:completion: API in favor of verifyPhoneNumber:UIDelegate:completion:
> Remove deprecated verify phone number

- Firebase/Auth/Source/Public/FIRAuth.h
- Firebase/Auth/Source/Public/FIRUser.h
Adds deprecation messages for linkWithCredential:completion and reauthenicateWithCredential:completion:  
Also corrects the deprecation messages for other deprecated APIs where part of the message was being repeated.
> Adds and modifies deprecation messages

- Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/Source/Remote/FSTRemoteEvent.h
- Firestore/Source/Remote/FSTRemoteEvent.mm
Moves filtering of updates onto the `FSTTargetMapping` subclasses. 
Splits the tests of synthesized deletes and update filtering into a few different tests for each of the specific cases.
> Port the feedback from the Java port

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/core/src/firebase/firestore/model/base_path.h
- Firestore/core/src/firebase/firestore/model/database_id.h
- Firestore/core/src/firebase/firestore/model/document_key.h
- Firestore/core/src/firebase/firestore/timestamp.cc
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/hashing.h
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/hashing_test.cc
This is good enough to make it possible for Objective-C types defining `-hash` to contain C++ types that aren't otherwise hashable.
I needed something like this because `FSTDocumentKeySet` is a member used in `-hash` methods. When replaced with `DocumentKeySet` where that's an `immutable::SortedSet<DocumentKey>` I started down the path of defining a `.Hash()` function as we've done elsewhere. Unfortunately, `immutable::SortedSet` is generic, and it felt wrong to burn in the assumption that its parameter also defined a `.Hash()` member. This would make `immutable::SortedSet<int>` invalid.
Note that this implementation isn't any better or worse than our existing `-hash` implementations. Once we've ported most of the composite types to C++ I believe we'll probably be able to delete most, if …
> Define a general hashing utility in C++

- Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
- Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
- Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
- Firestore/Example/Tests/Local/FSTQueryCacheTests.mm
- Firestore/Example/Tests/Model/FSTDocumentTests.mm
- Firestore/Example/Tests/Model/FSTMutationTests.mm
- Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
- Firestore/Example/Tests/SpecTests/FSTMockDatastore.h
- Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
- Firestore/Example/Tests/Util/FSTHelpers.h
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Source/API/FSTUserDataConverter.h
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/Source/Core/FSTTransaction.mm
- Firestore/Source/Local/FSTLocalSerializer.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Local/FSTQueryData.mm
- Firestore/Source/Model/FSTDocument.h
- Firestore/Source/Model/FSTDocument.mm
- Firestore/Source/Model/FSTMutation.h
- Firestore/Source/Model/FSTMutation.mm
- Firestore/Source/Model/FSTMutationBatch.h
- Firestore/Source/Model/FSTMutationBatch.mm
- Firestore/Source/Remote/FSTRemoteStore.mm
- Firestore/core/src/firebase/firestore/model/precondition.h
This is part of the C++ migration. Replace `FSTSnapshotVersion` by C++ SnapshotVersion in the rest of all modulo except in `FSTDocumentVersionDictionary` which require `FSTImmutableSortedDictionary` equivalent.
```
git grep FSTSnapshotVersion
Firestore/Source/Core/FSTSnapshotVersion.h:@interface FSTSnapshotVersion : NSObject <NSCopying>
Firestore/Source/Core/FSTSnapshotVersion.h:- (NSComparisonResult)compare:(FSTSnapshotVersion *)other;
Firestore/Source/Core/FSTSnapshotVersion.mm:#import "Firestore/Source/Core/FSTSnapshotVersion.h"
Firestore/Source/Core/FSTSnapshotVersion.mm:@implementation FSTSnapshotVersion
Firestore/Source/Core/FSTSnapshotVersion.mm:  static FSTSnapshotVersion *min;
Firestore/Source/Core/FSTSnapshotVersion.mm:    min = [FSTSnapshotVersion …
```
> Port `SnapshotVersion` for the rest Firestore modulo

- Firestore/core/src/firebase/firestore/remote/serializer.cc
- Firestore/core/src/firebase/firestore/remote/serializer.h
- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
This is more interesting than the serializing case, as we should expect
to see occasional corruption of our input byte vector.
> Add error handler for serializer (for deserializing cases)

- Firestore/Example/Tests/Integration/API/FIRCursorTests.mm
"micros" could underflow or overflow if the test was run at the wrong time... So I Reworked the test with hardcoded timestamps (based on if micros was "5") as I don't think making it time-dependent gains us interesting additional coverage.
> b/78539022: Fix test at risk of range violation errors depending on time-of-day.

- Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
- Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Local/FSTQueryData.h
- Firestore/Source/Local/FSTQueryData.mm
- Firestore/Source/Remote/FSTRemoteStore.mm
This PR is a part of the LRU garbage collection work. Ensure that we write a new sequence number when we get a new resume token for a target.
> Bump sequence numbers when receiving a new resume token

- Firestore/Source/Remote/FSTRemoteEvent.mm
method definition for 'filterUpdatesUsingExistingKeys:' not found
There are no abstract methods in Objective-C so the base class needs an
implementation.
> Fix warning on FSTTargetMapping mentioned in #1210

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Podfile
This change prepares for building/testing Firestore as a static library. It fixes the errors encountered putting together #1056, but does not yet add any direct support for building the static version of Firestore--that will come separately.
Concretely, this change:
* Fixes the integration tests that were broken in #1150: I left references to targets that longer exist
* Removes the OCMock and leveldb dependencies from the integration tests; they're not needed
* Flattens the Podfile, making test targets independent from the example app
* Adds a workaround that prevents dependency duplication between the app and tests, resolving the duplicate class warnings that would otherwise be seen in this configuration.
Further discussion of the underlying issue is here …
> Prepare Firestore for use as a static library

- Firebase/Core/FIRLogger.m
- Firebase/Core/FIRVersion.m
- Firebase/Core/Private/FIRVersion.h
- Firestore/Source/API/FIRFirestoreVersion.h
- Firestore/Source/API/FIRFirestoreVersion.mm
- Firestore/Source/Remote/FSTDatastore.mm
When FirebaseCore and FirebaseFirestore were built with `-all_load` in `Other Linker Flags`, a duplicate symbol would be generated like (see below). 
This is the result of CocoaPods generating a C file with the symbol {pod_name}VersionString defined. Both FirebaseCore and FirebaseFirestore had another definition of that symbol. This PR renames that symbol to FIR{component}VersionString.
This is internal issue b/79210503.
```
duplicate symbol _FirebaseFirestoreVersionString in:
/Users/paulbeusterien/Library/Developer/Xcode/DerivedData/InvitesExample-enffqvylwclnvzempzhnwxxyzblj/Build/Products/Debug-iphonesimulator/FirebaseFirestore/FirebaseFirestore.framework/FirebaseFirestore(FIRFirestoreVersion.o)
/Users/paulbeusterien/Library/Developer/Xcode/DerivedData/InvitesExample-enffqvylwclnvzempzh …
```
> Eliminate duplicate symbol in CocoaPods -all_load build

- Functions/Example/FirebaseFunctions.xcodeproj/project.pbxproj
Source control project file without CocoaPods for easier merging and management.
The downside is to avoid committing a dirty project file after doing development.
> Check in deintegrated Functions Xcode project file

- Firestore/Example/Tests/Integration/API/FIRArrayTransformTests.mm
- Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
- Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
- Firestore/Example/Tests/Util/FSTEventAccumulator.h
- Firestore/Example/Tests/Util/FSTEventAccumulator.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/Model/FSTMutation.mm
- Firestore/core/src/firebase/firestore/model/transform_operations.h
This brings iOS into parity with the result of https://github.com/firebase/firebase-js-sdk/pull/763.
NOTE: I ported awaitLocalEventWithName / awaitRemoteEventWithName to FSTEventAccumulator but actually getting rid of the helpers in FIRArrayTransformTests and FIRServerTransformTests would have added significant boilerplate (because FSTEventAccumulator makes you pass a name for the events it awaits). So it's only a half-hearted port and I'm half tempted to revert it. Let me know what you think?
> Backport array contains / transform improvements from Web.

- Firestore/core/src/firebase/firestore/util/executor_libdispatch.mm
- Firestore/core/src/firebase/firestore/util/executor_std.cc
- Firestore/core/src/firebase/firestore/util/executor_std.h
- Firestore/core/test/firebase/firestore/util/async_tests_util.h
This should prevent weird bugs due to system time readjustments. Because
operations are scheduled relative to now, the fact that the resulting
timepoint isn't in Unix epoch shouldn't matter.
> Firestore C++: in AsyncQueue, use steady_clock instead of system_clock.

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
Make the GoogleTests folder rooted at `Firestore/core/test/firebase/firestore` and make each subfolder the obviously corresponding subdirectory. This will make it much easier to add C++ tests to the project because 'Add files to "Firestore"' will now open the actual folder and files not current present in that group will be a different color.
A follow on PR will add a whole bunch of tests we've added but failed to add to the project.
> Align folders with actual test locations in the Firestore project

- Example/Core/Tests/FIRAppTest.m
- Example/Messaging/Tests/FIRMessagingTest.m
- Firebase/Core/FIRApp.m
- Firebase/Core/Private/FIRAppInternal.h
- Firebase/Core/Public/FIRApp.h
- Firebase/Messaging/FIRMessaging+FIRApp.m
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessaging_Private.h
NOTE: This shouldn't be public until all SDKs conform to the setting.
This allows developers to enable/disable all collection at compile time and override it at runtime.
> Add global data collection switch. 

- .travis.yml
There's an unreleased change in Core that Messaging relies on, but Travis currently pulls in the publicly released version of Core causing the linting to fail. This should be re-enabled once either a) Core is released, or b) we support pointing to local pods for dependencies on Travis - whichever of the two come first.
An issue will be opened to re-enable the linting.
> Temporarily disable Messaging pod lints

- Example/Core/Tests/FIROptionsTest.m
- Firebase/Core/FIROptions.m
Also update FIROption version that was not done in the 5.0.0 release.
There will be a conflict when 5.0.1 merges in.
> Test Core's build version matches FIROption version

- Firebase/Messaging/FIRMessaging.m
get token method will be externally deprecated soon but internally we still use it. Adding macro to ignore the warning.
> Ignore deprecated warning of get token method

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/status.cc
- Firestore/core/src/firebase/firestore/util/string_format.cc
- Firestore/core/src/firebase/firestore/util/string_format.h
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/comparison_test.cc
- Firestore/core/test/firebase/firestore/util/string_format_test.cc
The new StringFormat takes a simple format string but uses C++ varargs to avoid all the `.c_str()` values and `"%" PRId64` format specifiers.
This is a preparatory step for implementing `HARD_ASSERT` to match the other Firestore ports.
This does not use ostream-style formatters in the way that `CHECK` and `DCHECK` do within google3; rather there's still a vastly simplified format string. The result is something that will port easily to the Android and JS SDKs.
All uses of `StringPrintf` (except those in the implementation of `firebase_assert.h`) have been converted to the new form.
I attempted to make `FormatArg` automatically invoke `ToString()` if the value declared it, but was stymied by lifetime issues for the resulting string. This can't be done in the `FormatArg` constructor, but …
> Add a C++ native StringFormat

- Firestore/Source/API/FIRFirestore.mm
... instead of relying on HARD_ASSERTS in resource_path.cc to catch
them.
This fixes an integration test broken in #1304.
> Directly validate collection and document paths

- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessaging.m
When subscribeToTopic or unsubscribeFromTopic are called, they should
not be passed in with the prefix "/topic/". Calling those functions with
a string prefixed with "/topic/" will now print a warning.
> Warn when topic format is incorrect.

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- scripts/check_copyright.sh
- scripts/sync_project.rb
This uses `xcodeproj`--the same library used by Cocoapods--to keep the filesystem's list of tests in sync with the Xcode project.
I've done this because Firestore has hundreds of tests, and manually adding these to the project for each platform we support is a righteous pain. I did this by hand for the macOS-specific targets and I don't want to have to do it again for the tvOS and watchOS platforms.
@paulb777 I don't know if the other projects are interested in this. Firestore is somewhat unique for the sheer volume of tests and the number of project changes we're making during the C++ rewrite.
> Add a test synchronization script

- Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
- Firestore/core/src/firebase/firestore/util/string_format.h
Change #1313 broke logging of Objective-C objects that don't directly extend from `NSObject`.
> Fix Objective-C logging

- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingContextManagerService.m
Minor: Add a macro to suppress deprecated warning 
I only added one error code for both because it's essentially one call with callback, one without, so having two error codes for this add no extra debug information.
> Adding new error code to topic format error

- Firebase/Messaging/FIRMessaging.m
This ensures that existing behavior still works - InstanceID can sometimes fetch stored values before `FirebaseApp.configure()` is called, causing the global flag to be `NO`. Will file an issue shortly.
> Temporary fix for Messaging's data collection bit

- Firebase/Messaging/FIRMessaging.m
* Temporary fix for Messaging's data collection bit
This ensures that existing behavior still works - InstanceID can sometimes fetch stored values before `FirebaseApp.configure()` is called, causing the global flag to be `NO`. Will file an issue shortly.
* Remove extra whitespaces
Thanks, GitHub editor.
* Fix method being called
> Temporary fix for Messaging's data collection bit (#1334)

- Firestore/Example/LibFuzzer.podspec
* The libFuzzer pod does not include the `main()` function to allow the pod to be built independently.
* Fuzzing applications must provide both the `main()` function and the `LLVMFuzzerTestOneInput` function. The `main()` function should call `fuzzer::FuzzerDriver(...)` similar to the original `FuzzerMain.cpp`.
> Added .podspec file for libFuzzer

- Firestore/core/src/firebase/firestore/remote/serializer.cc
- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Normally, this would be unexpected, as only a single entry in the Value
proto *should* be present. However, the proto docs state that parsers
should be able to handle repeated fields. (In the case of repeated
fields, the last one "wins".)
> Allow repeated entries in Value proto.

- .travis.yml
They were disabled in #1277 because of an unreleased Core change, but the Core version is public now.
> Re-enable Messaging lints

- Firebase/Core/CHANGELOG.md
We also forgot a few changes in here, updating now so it's up to date.
> Update Core CHANGELOG for M26

- Firestore/CHANGELOG.md
We released v0.12.2 (as part of Firebase 5.1.0) but didn't adjust the changelog entry.
> Fix changelog

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/hashing.h
- Firestore/core/src/firebase/firestore/util/string_format.h
- Firestore/core/src/firebase/firestore/util/type_traits.h
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/hashing_test.cc
- Firestore/core/test/firebase/firestore/util/string_format_apple_test.mm
- Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm
A number of template-related errors have crept into the Firestore C++ codebase that happened to work in Xcode 9.3 and 9.4 but don't work on earlier versions.
Tested with Xcode 8.3.3 and 9.2.
Fixes #1366.
> Fix Firestore compilation under Xcode < 9.2

- FirebaseCore.podspec
- FirebaseFirestore.podspec
Fix #1369.
The CocoaPods [packager](https://github.com/CocoaPods/cocoapods-packager) does not process preprocessor flags specified in `OTHER_CFLAGS` and will fail to build. FirebaseCore should be consistent and define them in `GCC_PREPROCESSOR_DEFINITIONS` anyways.
> Consistent specification of preprocessor options in podspecs to work with the CocoaPods packager

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/path.cc
- Firestore/core/src/firebase/firestore/util/path.h
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/path_test.cc
I can't believe it's 2018 and I'm writing this code, but here I am...
Note that `std::filesystem` is not available yet but no version of it has yet been released with Xcode. There is a version of `std::experimental::filesystem` available in llvm-6.0 that I kicked the tires on, but this doesn't really even matter because we're targeting C++11 systems.
I've chosen not to mirror the proposed standard primarily because it's significantly more complicated than I need. I just need to be able to put paths together and do the equivalent of `dirname(1)`.
> Add pathname manipulation utilities

- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
PB_LAST_FIELD is required by nanopb, but was missed in the test. Without
this, undefined behaviour results. (Either manifesting itself as fine
(i.e. if there's zeros following) or segfaults.)
> Fix undefined behaviour in test.

- Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_FuzzTests_iOS.xcscheme
- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
- Firestore/Source/API/FSTUserDataConverter.mm
The validation for set(data, mergeFields:...) rejected field paths that pointed to field deletes/transforms since these are stripped from the update data. This PR checks the field mask (for field deletes) and the list of field transforms (for server timestamps) to validate mergeFields.
This is a port of https://github.com/FirebasePrivate/firebase-android-sdk/pull/2
> Allowing field deletes using merge fields

- Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_FuzzTests_iOS.xcscheme
- Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
- Firestore/Example/Tests/Core/FSTViewTests.mm
- Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
- Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
- Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/Util/FSTHelpers.h
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/Source/Core/FSTView.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Remote/FSTRemoteEvent.h
- Firestore/Source/Remote/FSTRemoteEvent.mm
- Firestore/Source/Remote/FSTRemoteStore.h
- Firestore/Source/Remote/FSTRemoteStore.mm
- Firestore/Source/Remote/FSTWatchChange.mm
This is a port of https://github.com/firebase/firebase-js-sdk/pull/784. This PR also ports the test runner changes from https://github.com/firebase/firebase-js-sdk/pull/812.
Spec test updates for this change are in a separate PR #1380 (to keep this PR somewhat sane).
Not that with the spec tests included in this PR the unit tests don't pass. They pass with #1380 merged in.
As this is my first larger PR after the C++ migration, there's likely some very general feedback that I should address before it makes sense to look at all the details.
> Refactor Remote Event

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/status.cc
- Firestore/core/src/firebase/firestore/util/status.h
- Firestore/core/src/firebase/firestore/util/status_apple.mm
- Firestore/core/src/firebase/firestore/util/statusor.h
- Firestore/core/src/firebase/firestore/util/strerror.cc
- Firestore/core/src/firebase/firestore/util/strerror.h
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/status_test.cc
- Firestore/core/test/firebase/firestore/util/status_test_util.h
- Firestore/core/test/firebase/firestore/util/strerror_test.cc
This change:
* Adds `StrError`, a port of `//base/strerror`.
* Adds `Status::FromErrno`, which seems like a reasonable path forward without requiring us to bring in the google3-internal (and deprecated) concept of error spaces.
* Adds `Status::FromNSError`, which is useful for converting errors from e.g. `NSFileManager` to canonical codes.
> Create Status objects from errno

- cmake/FindNanopb.cmake
- cmake/FindProtobuf.cmake
- cmake/external/grpc.cmake
- cmake/external/nanopb.cmake
- cmake/external/protobuf.cmake
This includes:
* Build protobuf with cmake instead of autotools
* Build the nanopb protoc plugin with cmake
* Windows build compatibility changes
> Fix protobuf/nanopb builds on Windows

- Example/Core/Tests/FIRLoggerTest.m
- Firebase/Core/FIRLogger.m
This was previously used in an iOS 7 comparison that was removed in
Firebase version 5.0.0.
> Remove unused static logging variable.

- Firestore/core/src/firebase/firestore/nanopb/reader.cc
- Firestore/core/src/firebase/firestore/nanopb/reader.h
- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
* A substream should not be closed if `pb_make_string_substream()` failed to create it and returned false.
* Fixed a potential wrong error message.
> Avoid closing unintialized substreams 

- Firebase/Messaging/FIRMessaging.m
Client had a feature that it queues up the topic requests when token is not available. And when token is regenerated, client will sync all pending topic requests and send them to server. This is consistent with Android.
Apparently this feature exists, but we did a unnecessary checking if token doesn't exist, client simply returns without queue up topic requests.
> remove the token check for topic subscription/unsubscription

- Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
@wilhuff let me know what you think of this kind of refactor, and I'll go ahead and make the change for the rest of the tests.
> Sample of LRU test refactor

- Example/Messaging/Tests/FIRMessagingServiceTest.m
- Firebase/Messaging/FIRMessaging.m
When token is not available and developer is trying to subscribe/unsubscribe a topic, we should add a warning letting them know that the operation will be suspended. When developer gets a new token, the operation will resume with completion handler triggered.
> add a warning message that the topic operation is suspended without a token

- Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
- Firestore/Source/Remote/FSTRemoteEvent.h
- Firestore/Source/Remote/FSTRemoteStore.mm
This ports one line from https://github.com/firebase/firebase-js-sdk/commit/96a10922ffdf3f986b1183070a2ccf15bed331fa that I missed during the port and addresses a potential memory leak.
> Removing the target state on stream error

- Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_FuzzTests_iOS.xcscheme
- Firestore/Source/Core/FSTSyncEngine.mm
Remove usage of eager garbage collector for tracking limbo document references. Instead, if we remove the last reference to a limbo document, do the cleanup directly.
When combined with #1410 we will be able to remove `FSTGarbageCollector` and `FSTEagerGarbageCollector`.
Not sure what's up with the fuzz testing changes, they appear auto-generated @minafarid
> Remove Limbo Document GC

- FirebaseFunctions.podspec
- Functions/CHANGELOG.md
- Functions/Example/Tests/FIRFunctionsTests.m
- Functions/FirebaseFunctions/FIRFunctions.m
- Functions/FirebaseFunctions/Public/FIRFunctions.h
- Add a Functions constructor that allows setting a Cloud Functions region.
- Add a method to set an Cloud Functions emulator origin to use for local testing.
- Update the change log.
- Update the version number for the next release.
> Add a couple of new small Functions APIs.

- Firestore/core/src/firebase/firestore/local/local_serializer.h
- Firestore/core/test/firebase/firestore/local/local_serializer_test.cc
- Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Were showing up in xcode build (but not cmake build)
> Fix a few implicit converstion warnings

- Firestore/core/src/firebase/firestore/local/local_serializer.cc
- Firestore/core/src/firebase/firestore/nanopb/reader.cc
- Firestore/core/src/firebase/firestore/nanopb/reader.h
- Firestore/core/src/firebase/firestore/remote/serializer.cc
Rather than decoding the type, and then the contents, decode them both at once.
> Refactor nanopb decoding methods

- Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
See #1451 for why this workaround is needed.
> Disable failing didReceiveRemoteNotification tests(#1451)

- Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Hopefully work around #1261, which looks like a bug in GTMSessionFetcher's session reuse logic.
> Force GTMSessionFetcher to not reuse NSURLSessions

- Example/Core/Tests/FIRAnalyticsConfigurationTest.m
- Example/Core/Tests/FIRAppTest.m
- Example/Core/Tests/FIRLoggerTest.m
- Firebase/Core/FIRLogger.m
This includes NSNotificationCenter and NSUserDefaults to prevent
flaky tests and unit tests interfering with each other.
> Better mocking for Core Unit Tests

- Example/Core/Tests/FIRComponentContainerTest.m
- Example/Core/Tests/FIRComponentTypeTest.m
- Example/Core/Tests/FIRTestComponents.h
- Example/Core/Tests/FIRTestComponents.m
- Example/Firebase.xcodeproj/project.pbxproj
- Firebase/Core/FIRApp.m
- Firebase/Core/FIRComponent.m
- Firebase/Core/FIRComponentContainer.m
- Firebase/Core/FIRComponentType.m
- Firebase/Core/FIRDependency.m
- Firebase/Core/Private/FIRAppAssociationRegistration.h
- Firebase/Core/Private/FIRAppInternal.h
- Firebase/Core/Private/FIRComponent.h
- Firebase/Core/Private/FIRComponentContainer.h
- Firebase/Core/Private/FIRComponentContainerInternal.h
- Firebase/Core/Private/FIRComponentRegistrant.h
- Firebase/Core/Private/FIRComponentType.h
- Firebase/Core/Private/FIRCoreConfigurable.h
- Firebase/Core/Private/FIRDependency.h
This puts in place the system that will allow SDKs to register with
Core and retrieve functionalities provided by other SDKs.
>  Add FirebaseCore component interoperability.

- Example/Auth/Tests/FIRAuthTests.m
- Example/Auth/Tests/FIRPhoneAuthProviderTests.m
- Example/Auth/Tests/FIRUserTests.m
- Firebase/Auth/Source/FIRAuthErrorUtils.h
- Firebase/Auth/Source/FIRAuthErrorUtils.m
- Firebase/Auth/Source/FIRAuthInternalErrors.h
- Firebase/Auth/Source/FIRUser.m
- Firebase/Auth/Source/Public/FIRAuthErrors.h
- Fixes a potential crash when decoding malformed JWTs with less than three components.
- Improves error messaging when decoding JWTs.
- Removes deprecated usage of `[NSError new]` in tests.
~~Do not merge before #1448.~~
Pending API review.
> Add informative error to JWT parse failures

- Example/Messaging/Tests/FIRMessagingTest.m
- Firebase/Messaging/FIRMessaging+FIRApp.m
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessaging_Private.h
There's a race condition when fcm is reading global data flag  before global data flag is set in the FIRMessaging+FIRApp category class.
Fix it by reading the global data flag from FIRApp directly. 
Also remove FCMSenderID completely because it is not used in FCM, but instanceID only.
> Fix the race condition of global data flag and fcm auto init enabled flag

- Firestore/Example/FuzzTests/FSTFuzzTestsPrincipal.mm
* Initialize a static Serializer object to be used in fuzz testing.
* Call `Serializer::DecodeFieldValue` with the fuzzing inputs.
> Fuzz test Serializer to decode FieldValue

- Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/json/collection_spec_test.json
- Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/SpecTests/json/orderby_spec_test.json
- Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
- Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
- Firestore/Example/Tests/SpecTests/json/resume_token_spec_test.json
- Firestore/Example/Tests/SpecTests/json/write_spec_test.json
This PR changes the spec tests to treat watch snapshots as separate messages, which allows us to apply resume token on a per-target basis.
Port of firebase/firebase-js-sdk#969 /  https://github.com/FirebasePrivate/firebase-android-sdk/pull/95
This also pulls in Greg's recent Spec test changes that haven't been ported (this are comment/tag-only changes in the generated JSON).
> Add spec test support for target-scoped resume tokens

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTMemoryMutationQueue.mm
- Firestore/Source/Local/FSTMutationQueue.h
This is a building block for eliminating quadratic behavior found recently when recomputing the view for large batches.
>  Add allMutationsAffectingDocumentKeys to FSTMutationQueue

- Firestore/core/src/firebase/firestore/immutable/CMakeLists.txt
- Firestore/core/src/firebase/firestore/immutable/sorted_map.h
- Firestore/core/src/firebase/firestore/immutable/sorted_set.h
I had a silly bug where I forgot to reassign an immutable set with the result of an `insert` operation, would have been happy if the compiler pointed it out sooner.
> C++: for immutable data structures, forbid ignoring result of insert/erase

- Example/Auth/Tests/FIRAuthTests.m
- Example/Auth/Tests/FIRUserTests.m
- Example/Firebase.xcodeproj/project.pbxproj
- Example/Firebase.xcodeproj/xcshareddata/xcschemes/Auth_Tests_tvOS.xcscheme
- Remove umbrella header from FIRAuthTests.m
- Fix incorrect import of .m in FIRUserTests.m
- Fix resulting travis breaks on tvOS and macOS
- On macOS, use -ObjC linking flag
- On tvOS, add -framework FirebaseAuth to the test link options.
There has been a recent CocoaPods ruby dependency that is causing FirebaseAuth to no longer be generated for the Pods-Auth_Tests_*.debug.xcconfig OTHER_LD_FLAG overrides.  The two changes above fix the issue. More investigation is required to determine if this is a CocoaPods bug, but this PR fixes the changes for now.
> Remove one more umbrella header import in Auth Tests

- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingContextManagerService.m
- Firebase/Messaging/FIRMessagingReceiver.m
- Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
- Firebase/Messaging/FIRMessagingUtilities.h
- Firebase/Messaging/FIRMessagingUtilities.m
This should make FCM compilable inside app extensions as requested by #1490
> avoid calling [UIApplication sharedApplication] in app extensions

- CMakeLists.txt
- cmake/CompilerSetup.cmake
- cmake/external/FirebaseCore.cmake
- cmake/external/GoogleUtilities.cmake
- cmake/external/c-ares.cmake
- cmake/external/firestore.cmake
- cmake/external/googletest.cmake
- cmake/external/grpc.cmake
- cmake/external/leveldb.cmake
- cmake/external/nanopb.cmake
- cmake/external/protobuf.cmake
- cmake/external/zlib.cmake
This change fixes two long-standing issues that have bugged me:
* The top-level CMakeLists.txt needed to keep the included modules in topologically sorted order
* Some of the modules had nearly all of their logic in an else branch
The difference is best examined with a whitespace insensitive diff, e.g. with
https://github.com/firebase/firebase-ios-sdk/compare/wilhuff/cmake-reorg?w=1
> Reorganize cmake dependencies

- Firestore/CMakeLists.txt
- Firestore/Protos/CMakeLists.txt
- Firestore/core/src/firebase/firestore/local/CMakeLists.txt
- Firestore/core/src/firebase/firestore/nanopb/CMakeLists.txt
- Firestore/core/src/firebase/firestore/remote/CMakeLists.txt
- cmake/FindGRPC.cmake
- cmake/FindLevelDB.cmake
- cmake/FindNanopb.cmake
- cmake/SanitizerOptions.cmake
- cmake/external/c-ares.cmake
- cmake/external/firestore.cmake
- cmake/external/googletest.cmake
- cmake/external/grpc.cmake
- cmake/external/leveldb.cmake
- cmake/external/nanopb.cmake
- cmake/external/protobuf.cmake
- cmake/external/zlib.cmake
- cmake/xcodebuild.cmake
This is a grab-bag of cleanup changes that I've pulled out of a larger sequence that converts the build to use add_subdirectory instead of installing intermediates or implementing find_package in terms of the build tree.
The change to the PREFIX makes it less noisy to add_subdirectory into these directories. Note that the prefix is still included because the CMake default is to add `$target-prefix` otherwise. This way you can refer to, e.g. the grpc sources as `${FIREBASE_BINARY_DIR}/src/grpc`.
> Firestore CMake cleanup

- Firestore/Example/Tests/Core/FSTQueryTests.mm
- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
- Firestore/Example/Tests/Util/FSTHelpers.h
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/Core/FSTQuery.h
- Firestore/Source/Core/FSTQuery.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
Rather than previously inlining it in the calling code. This is to unify
filter creation across platforms.
(This change involves altering FSTFilter from a protocol to an abstract
class.)
> Move creation of FSTFilter objects to static create method on FSTFilter.

- GoogleUtilities.podspec
- GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
- GoogleUtilities/Example/Tests/Environment/GULAppEnvironmentUtilTest.m
- GoogleUtilities/Network/GULNetworkURLSession.m
And disable iOS6 since it has many more unresolved errors 
- see  `pod lib lint GoogleUtilities.podspec --use-libraries` (or b/111429140)
The `--use-libraries` option is necessary because frameworks default to a minimum iOS version of 8.
This was caught in the nightly cron travis testing.
> Restore iOS7 to GoogleUtilities

- Firestore/core/src/firebase/firestore/nanopb/reader.cc
- Firestore/core/src/firebase/firestore/nanopb/tag.h
Visual Studio flags use of this variable as an uninitialized read.
I think the issue is that `Tag` has managed to be a POD type, so it's not initialized.
An alternative would be to give a `Tag` a default constructor that initializes the fields to zero values explicitly.
WDYT?
> Suppress uninitialized read error under VS2017

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/FuzzTests/FuzzingResources/Serializer/Corpus/ConvertTextToBinary.sh
- Firestore/Example/Podfile
* Added `! ProtoCompiler` as a Pod dependency to use the `protoc` binary.
* Modified the `ConvertTextToBinary.sh` script to use the `protoc` binary from the Pod.
* Removed an unused src for protos.
> Fuzz testing uses protoc from a pod dependency

- Firestore/CMakeLists.txt
- cmake/external/leveldb.cmake
CMake support landed in google/leveldb:master a while ago.
This cuts down on the nasty cmake to make bridge and makes it possible to use LevelDB on Windows when that lands.
> Use CMake to build LevelDB

- Firestore/CMakeLists.txt
- scripts/if_changed.sh
This looks huge but it's basically just a merge of master and #1531 plus just this commit:
710867b890e94742a4676fcb6a185be940a1ffa5.
> Implement a CMake build for FirebaseAuthInterop

- Firestore/CHANGELOG.md
> Update changelog to mention performance improvements in write batches

- Firestore/CMakeLists.txt
FirebaseAuthInterop isn't defined as a target under linux (since it
comes from the podfiles) so defining a source file for the target causes
cmake to error.
> Fix broken build under linux

- Firestore/Source/Local/FSTLevelDBMigrations.mm
Replace fallthrough comments with `ABSL_FALLTHROUGH_INTENDED`, allowing clean building with -Wimplicit-fallthrough.
> Eliminate -Wimplicit-fallthrough triggers

- FirebaseFirestore.podspec
Under recent cocoapods I've seen this cause the sed command to be
commented out and not run.
> Prevent the comment in the prepare_command from interfering

- Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
- Firestore/Source/Core/FSTSyncEngine.mm
**Note:** I wrote C++ code so please review carefully.
[Port of [firebase/firebase-js-sdk#1014](https://github.com/firebase/firebase-js-sdk/pull/1014)]
This fixes an issue occurring when a limbo target receives a documentUpdate,
then a global snapshot, and then a CURRENT. Because there was a global
snapshot before the CURRENT, WatchChangeAggregator has no pending document
updates and calls SyncEngine.remoteKeysForTarget to see if we previously got any
document from the backend for the target. See:
https://github.com/firebase/firebase-js-sdk/blob/6905339235ad801291edc696dd75a08e80647f5b/packages/firestore/src/remote/watch_change.ts#L422
Prior to this change, remoteKeysForTarget returned empty because
it relies on our Views to track the contents of the target, and we don't
have Views for …
> b/72533250: Fix issue with limbo resolutions triggering incorrect manufactured deletes.

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
- Firestore/Source/Local/FSTLevelDB.mm
- Firestore/Source/Local/FSTLevelDBMigrations.h
- Firestore/Source/Local/FSTLevelDBMigrations.mm
- Firestore/core/src/firebase/firestore/local/leveldb_transaction.cc
- Firestore/core/src/firebase/firestore/local/leveldb_transaction.h
This is a force fix for potential existence filter mismatches caused by
firebase/firebase-ios-sdk#1548
The essential problem is that when resuming a query, the server is
allowed to forget deletes. If the number of incorrectly synthesized
deletes matches the number of server-forgotten deletes then the
existence filter can give a false positive, preventing the cache from
self healing.
Dropping the query cache clears any client-side resume token which
prevents a false positive existence filter mismatch.
Note that the remote document cache and mutation queues are unaffected
so any cached documents that do exist will still work while offline
Port of https://github.com/firebase/firebase-js-sdk/pull/1019
> Add a schema migration that drops the query cache

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
- Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/json/collection_spec_test.json
- Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/SpecTests/json/orderby_spec_test.json
- Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
- Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
- Firestore/Example/Tests/SpecTests/json/resume_token_spec_test.json
- Firestore/Example/Tests/SpecTests/json/write_spec_test.json
- Firestore/Source/Core/FSTSyncEngine.mm
- Firestore/Source/Local/FSTLevelDB.mm
- Firestore/Source/Local/FSTLevelDBMigrations.h
- Firestore/Source/Local/FSTLevelDBMigrations.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/core/src/firebase/firestore/local/leveldb_transaction.h
This includes cherry-picks for all the fixes required to fix #1548.
> Prepare Firestore release 0.12.6

- Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_FuzzTests_iOS.xcscheme
- Firestore/Example/FuzzTests/FSTFuzzTestsPrincipal.mm
* Read the fuzzing target from a `FUZZING_TARGET` environment variable. Example usage:
```bash
xcodebuild \
-workspace Firestore.xcworkspace \
-scheme Firestore_FuzzTests_iOS \
-destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.3' \
FUZZING_TARGET='SERIALIZER' test
```
* Write crashing inputs to `NSTemporaryDirectory()`
> Multiple fuzz testing targets

- Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
- Firestore/Example/Tests/Local/FSTLevelDBLRUGarbageCollectorTests.mm
- Firestore/Example/Tests/Local/FSTLevelDBQueryCacheTests.mm
- Firestore/Example/Tests/Local/FSTMemoryQueryCacheTests.mm
- Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.h
- Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.mm
- Firestore/Example/Tests/Local/FSTQueryCacheTests.mm
- Firestore/Source/Local/FSTLevelDB.mm
- Firestore/Source/Local/FSTLevelDBQueryCache.h
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Local/FSTMemoryQueryCache.mm
- Firestore/Source/Local/FSTQueryCache.h
In my LRU change, I broke `FSTQueryCache` initialization while simultaneously altering the code so the tests for this feature still passed. This happened because `FSTLevelDB` started returning the same instance of `FSTLevelDBQueryCache` each time `queryCache` was called, rather than creating a new one. I noticed the error in attempting to port the code. 
So, I have rewritten the tests for restarting the persistence layer, made them specific to `FSTLevelDBQueryCache`, as well as fixed the bug.
Base branch is `lru`.
> Fix preserving query cache metadata

- Firestore/core/src/firebase/firestore/core/query.h
- Firestore/core/src/firebase/firestore/local/local_serializer.cc
- Firestore/core/src/firebase/firestore/local/local_serializer.h
- Firestore/core/src/firebase/firestore/local/query_data.cc
- Firestore/core/src/firebase/firestore/local/query_data.h
- Firestore/core/src/firebase/firestore/model/resource_path.h
- Firestore/core/src/firebase/firestore/nanopb/reader.cc
- Firestore/core/src/firebase/firestore/nanopb/reader.h
- Firestore/core/src/firebase/firestore/nanopb/writer.cc
- Firestore/core/src/firebase/firestore/nanopb/writer.h
- Firestore/core/src/firebase/firestore/remote/serializer.cc
- Firestore/core/src/firebase/firestore/remote/serializer.h
- Firestore/core/test/firebase/firestore/local/local_serializer_test.cc
- Firestore/core/test/firebase/firestore/testutil/testutil.h
Only a single (narrow) path is supported. i.e. the only QueryData that
can be encoded/decoded is the one in the test. Straying from the path
leads to abort()s.
>  Partial [en|de]coding of QueryData via the local serializer

- GoogleUtilities.podspec
After #1595 lands, I'll merge this PR, tag, and push GoogleUtilities 5.2.1
> Bump GoogleUtilities patch version to publish #1595

- .gitignore
- CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
Also allow the build to succeed with no SSL.
> Allow CMake to build Firestore with OpenSSL

- Firestore/core/src/firebase/firestore/util/executor_std.h
Under VS2017 the existing code triggers an assertion about accessing the front of the `scheduled_` queue after it's empty.
> Tolerate the schedule becoming empty in Schedule::PopBlocking

- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/remote/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- cmake/cc_rules.cmake
Our current platform-specific libraries have a bunch of problems that this PR solves.
Added a `cc_select` rule, which declares a proper CMake INTERFACE library representing each portability grouping and makes the chosen implementation a dependency of the rule. This makes it possible to refer to these as regular library dependencies (including referring to them out of declaration order). This eliminates the special variables per-grouping, makes the choice much more concise to specify, and mirrors the way we can use `select()` in bazel/blaze.
Also added support for just directly using Objective-C++ sources in our libraries, filtering them out if they don't apply.
Finally, merged the async queue and executor libraries to fix the potential for confusion during testing on macOS: …
> Simplify/normlaize CMake platform libraries

- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
I'll soon be adding `util_filesystem` that works similarly to and is a peer of `util_async` and `util_random`.
`util_filesystem_win` needs access to `string_win.{h,cc}` so these need to move out of the high-level `util` library. I can't make string_win part of the existing `util_base` target though because it uses `HARD_ASSERT`.
I don't see much value in keeping `util_base` and `util_log` separate and if I combine them I can move string_win into there.
> Combine firebase_firestore_util_base and _log

- Firestore/core/src/firebase/firestore/util/path.cc
- Firestore/core/src/firebase/firestore/util/path.h
- Firestore/core/test/firebase/firestore/util/path_test.cc
Paths now hold their platform-specific string values. On Windows, portable pathnames are UTF-16 stored in `wchar_t` arrays, but there's no `absl::wstring_view`, so filesystem APIs can't be designed to operate on `absl::string_view`.
Also, using `string_view` doesn't really save any copies in practice. For example, I need `Dirname` to create directories recursively and that needs a null-terminated string for each `mkdir` call, forcing the caller to copy.
Another option would be to have both `Path` and `PathView`. This would avoid all unnecessary copies at the expense of a more complicated implementation. Since we don't use the filesystem that intensively I'm okay with just keeping this simpler.
> Rewrite Path to use native path character type

- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
This should resolve #1591.  We were inadvertantly decoding the WriteResult as
having an updateTime of 0 which caused it to be older than the version of the
document in the RemoteDocumentsCache. Therefore we kept the old version in
the cache instead of persisting the deleted document. This caused the document
to reappear in the query results until we resolved it via a limbo resolution.
FYI- I tried to write a spec test but:
1. A writeAck step has only a single version number that's used for both the WriteResponse commitTime as well as the WriteResult updateTime (https://github.com/firebase/firebase-ios-sdk/blob/af0e5fca4c2c236c08df499e16f8a7fc6c0126f9/Firestore/Example/Tests/SpecTests/FSTSpecTests.mm#L325).
2. The iOS spec tests test at the model layer instead of the proto layer (they …
> Fixes decoding WriteResults for deletes (with no updateTime).

- scripts/build.sh
Fuzz tests automatically enable ASAN which cannot be combined with TSAN. This PR avoids running fuzz tests when TSAN is enabled. Otherwise, some travis jobs like [this](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/410988626) will fail.
> Travis to avoid fuzz tests with tsan

- Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
- Firestore/core/test/firebase/firestore/auth/firebase_credentials_provider_test.mm
If a user depends on Firebase/Firestore without depending on Firebase/Auth the `auth` instance we get is `nil`. `nil`-dispatch is still in effect here so the observed behavior is that Firestore cannot connect because we never get a token.
This should address the "Couldn't connect to Firestore backend" issues observed reproducing our fix for #1591 at master.
This implementation is intentionally minimal to make it palatable to the release that we're assembling right now. Further work is required on master to make this better over the long term.
> Make FirebaseCredentialsProvider tolerate a missing FirebaseAuth

- Firestore/Example/Tests/Local/FSTLevelDBKeyTests.mm
- Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
Minor but noisy change that prepares for converting from the API in FSTLevelDBKey.h to leveldb_key.h.
> Convert FSTLevelDBMutationQueue.userID to std::string

- Firestore/Example/Tests/Local/FSTLevelDBKeyTests.mm
- Firestore/Source/Local/FSTLevelDBKey.h
- Firestore/Source/Local/FSTLevelDBKey.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTLevelDBQueryCache.mm
- Firestore/core/src/firebase/firestore/local/leveldb_key.cc
- Firestore/core/src/firebase/firestore/local/leveldb_key.h
- Firestore/core/src/firebase/firestore/local/leveldb_transaction.cc
- Firestore/core/src/firebase/firestore/local/leveldb_transaction.h
- Firestore/core/src/firebase/firestore/util/string_util.h
- Firestore/core/test/firebase/firestore/local/leveldb_key_test.cc
Note, this PR looks like it deletes a ton of code, but it was actually copied/reworked during #937. This PR completes the migration of this method and deletes the old copy.
> Migrate [LevelDBKey descriptionForKey:] to DescribeKey()

- GoogleUtilities.podspec
- GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
- GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h
- GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h
This PR changes GULAppDelegateSwizzler so that `+[UIApplication sharedApplication]` is not called within app extensions.
Buganizer - b/112202764
> Fix GoogleUtilities so that it compiles in app extensions.

- Firestore/core/test/firebase/firestore/fuzzing/CMakeLists.txt
- cmake/cc_rules.cmake
* Created `cc_fuzz_test` build rule that automatically:
- Searches for `Fuzzer` package (libFuzzer or whatever is provided by
OSS Fuzz).
- Adds dependency of `Fuzzer`.
- Copies the dictionary file and corpus directory to the target binary
destination directory with the appropriate name.
* Modified fuzzing targets to use `cc_fuzz_test` rule.
* Confirmed that fuzzing works both locally and through OSS Fuzz docker images.
> Add cc_fuzz_test build rule

- Firebase/Core/FIRApp.m
To reduce confusion on questions like https://stackoverflow.com/questions/51627290/5-4-1-firebase-corei-cor000022-firebase-analytics-is-not-available/51737237
> Make missing analytics a warning instead of error

- Firestore/core/src/firebase/firestore/util/status.cc
- Firestore/core/src/firebase/firestore/util/status.h
- Firestore/core/test/firebase/firestore/util/status_test.cc
This makes it easy to wrap an underlying error in a higher-level one,
similar to the way Java exception chaining works.
Note that this intentionally diverges from upstream. The intent is that
this expresses a high-level concern so we can migrate to some common
status if one is ever released.
This is a follow-up to #1620.
> Add Status::CausedBy

- Firestore/third_party/abseil-cpp/absl/base/macros.h
We compile with -Werror -Wcomma and this gets flagged in that mode.
> Fix abseil compilation error that occurs in release mode

- CMakeLists.txt
- Firestore/Example/Benchmarks/CMakeLists.txt
- Firestore/Example/Benchmarks/string_apple_benchmark.mm
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/string_apple.cc
- Firestore/core/src/firebase/firestore/util/string_apple.h
- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
- Firestore/core/test/firebase/firestore/util/string_apple_test.mm
- cmake/external/benchmark.cmake
It turns out that `-[NSString UTF8String]` is almost assuredly copying the data into an autoreleased `NSData` and then returning a pointer into that buffer rather than exposing any internal state.
This change reimplements MakeString by bridging to CFString and then using CFString functions to copy directly into a std::string, saving a copy. Also, added a benchmark to show that this really works. Indeed, before:
```
Running Release/Firestore/Example/Benchmarks/firebase_firestore_util_string_apple_benchmark
Run on (8 X 2900 MHz CPU s)
CPU Caches:
L1 Data 32K (x4)
L1 Instruction 32K (x4)
L2 Unified 262K (x4)
L3 Unified 8388K (x1)
-----------------------------------------------------
Benchmark              Time           CPU Iterations
----------------------------------------------------- …
```
> Reimplement util::MakeString(NSString*)

- Firestore/Example/Benchmarks/string_apple_benchmark.mm
- Firestore/Example/Tests/API/FSTAPIHelpers.mm
- Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
- Firestore/Example/Tests/Integration/FSTStreamTests.mm
- Firestore/Example/Tests/Util/FSTHelpers.h
- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/API/FIRFirestore+Internal.h
- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/API/FSTFirestoreComponent.mm
- Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
- Firestore/core/src/firebase/firestore/auth/token.cc
- Firestore/core/src/firebase/firestore/auth/token.h
- Firestore/core/src/firebase/firestore/auth/user.cc
- Firestore/core/src/firebase/firestore/auth/user.h
- Firestore/core/src/firebase/firestore/core/database_info.cc
- Firestore/core/src/firebase/firestore/core/database_info.h
- Firestore/core/src/firebase/firestore/model/database_id.cc
- Firestore/core/src/firebase/firestore/model/database_id.h
Many of our types, especially ones written early on in the C++ migration, take string-like parameters as `absl::string_view`, which allows the widest range of possible values in, including views of `NSString`.
However, benchmarking in #1673 has shown that wrapping an `NSString` with an `absl::string_view` turns out not to be a cheap operation at all so this latitude isn't actually helping.
Meanwhile, using `absl::string_view` for these parameters forces a copy from all callers, even if the caller could naturally move a `std::string` into the new value.
This PR cleans up all the types that were using `MakeStringView` of an `NSString` to just `MakeString` and changes the implementations to just take `std::string` by value. There are plenty of other usages of `MakeStringView` that I'll …
> Replace uses of absl::string_view in constructor parameters with std::string

- Firebase/Messaging/FIRMessaging.m
This ensure the aync persist is complete before continue. This should fix the flakiness of integration tests.
> ensure NSUserDefaults is synchronized after setting values

- scripts/style.sh
Mostly I just want to create this PR to find out what travis is using...  but it may be useful to merge as well?
Travis output:
```
$ ./scripts/style.sh test-only $TRAVIS_COMMIT_RANGE
Found: clang-format version 7.0.0 (tags/google/stable/2018-04-24)
```
> Log style.sh clang-format version.

- Firestore/Example/Tests/Core/FSTQueryTests.mm
Ensure b/112521956 cannot happen (makes sure we don't partially match against objects in the array)
[port of https://github.com/firebase/firebase-js-sdk/pull/1115]
> Tweak array-contains test for partial object matches.

- Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
- Firestore/Source/Remote/FSTRemoteStore.mm
[Port of https://github.com/firebase/firebase-js-sdk/pull/972]
No functional changes. Just renames, moves, added comments, etc.
* pendingWrites => writePipeline
* canWriteMutations renamed canAddToWritePipeline
* commitBatch => addBatchToWritePipeline
* lastBatchSeen removed since we can compute it on demand from
writePipeline.
* Removed cleanUpWriteStreamState and instead inlined it in
disableNetworkInternal since I didn't like the non-symmetry with
cleanUpWatchStreamState which is called every time the stream closes.
* Misc. comment cleanup.
> Refactor pendingWrites / write pipeline.

- Firestore/core/src/firebase/firestore/local/leveldb_transaction.cc
- Firestore/core/src/firebase/firestore/local/leveldb_transaction.h
* absl::string_view should be passed by value
* use absl::StrCat and friends for concatenation
* use C++11 range-based for loops
* avoid sign conversion
> Clean up warnings in leveldb_transaction.cc

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Podfile
- Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
- Firestore/Example/Tests/Local/FSTLevelDBQueryCacheTests.mm
- Firestore/Example/Tests/Local/FSTLevelDBTransactionTests.mm
- Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.h
- Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/Core/FSTFirestoreClient.mm
- Firestore/Source/Local/FSTLevelDB.h
- Firestore/Source/Local/FSTLevelDB.mm
- Firestore/Source/Local/FSTMemoryPersistence.mm
- Firestore/Source/Local/FSTPersistence.h
- Firestore/core/src/firebase/firestore/local/CMakeLists.txt
- Firestore/core/src/firebase/firestore/local/leveldb_util.cc
- Firestore/core/src/firebase/firestore/local/leveldb_util.h
- Firestore/core/test/firebase/firestore/local/CMakeLists.txt
- Firestore/core/test/firebase/firestore/local/leveldb_util_test.cc
This is a stepping stone toward moving most of FSTLevelDB to C++. This PR focuses mostly on rearranging the callers of `-[FSTPersistence start]` to use `util::Status` and moves the guts to C++ where possible.
> Use new filesystem routines in FSTLevelDB

- Firestore/Source/Remote/FSTExponentialBackoff.mm
[Port of https://github.com/firebase/firebase-js-sdk/pull/1132]
Note: We actually have a not-yet-used c++ implementation of exponential backoff too.  I tried to update it, but it was hard. So I'm punting on that for the moment and will do that in a separate PR later.
> Make backoff account for already-elapsed time.

- .travis.yml
- scripts/install_prereqs.sh
Stages, even when cut off early with if_cron, still take about two
minutes to run. The fuzz_test stage was waiting for all tests to
complete before starting, which was artificially adding two minutes to
every build.
Use a different method to keep this visually distinct from the rest.
> Run fuzzing in the test stage

- Example/Auth/Tests/FIRAuthTests.m
The header is unnecessary and causes issues with internal build systems.
> Delete unnecessary umbrella header import

- Example/Firebase.xcodeproj/project.pbxproj
The Auth_Tests_tvOS started failing with CocoaPods 1.6.0.beta1. 
It turns out that we were already getting "implemented in both" errors with CocoaPods 1.5.3 and just getting lucky.
This PR fixes the test config to get rid of the "implemented in both" loading errors.
> Fix Auth_Tests_tvOS build config

- Example/Firebase.xcodeproj/project.pbxproj
Reverting #1717 since for an unknown reason the travis build fails on master even though it passes locally and even passed in the travis PR run.
Will revisit closer to updating to CocoaPods 1.6.0
> Revert "Fix Auth_Tests_tvOS build config (#1717)"

- Example/Storage/Tests/Unit/FIRStoragePathTests.m
- Firebase/Storage/FIRStorageDeleteTask.m
- Firebase/Storage/FIRStorageDownloadTask.m
- Firebase/Storage/FIRStorageGetDownloadURLTask.m
- Firebase/Storage/FIRStorageGetMetadataTask.m
- Firebase/Storage/FIRStorageUpdateMetadataTask.m
- Firebase/Storage/FIRStorageUploadTask.m
- Firebase/Storage/Private/FIRStorageTask_Private.h
> Fix assign default on fetcherCompletion

- .gitignore
- CMAKE.md
- cmake/podspec_rules.cmake
Also, remove the need to use `bundler` when cocoapods is available system-wide.
/cc @a-maurice
> Update CMake build instructions

- .travis.yml
- scripts/fuzzing_ci.sh
* Travis kills jobs if they did not produce any output for 10 minutes, so we cannot run fuzzing for longer than 10 minutes.
* We can print out the fuzzing logs, but travis limits the logs to 4 mb (which we will definitely exceed is most fuzzing targets because we print assertion error messages).
* We limit the `FUZZING_DURATION` to 570 seconds (9.5 minutes) in the `/scripts/fuzzing_ci.sh` script.
> Fix Travis fuzz testing

- GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h
Mark the -sharedApplication method's return type as nullable.
Partial fix for https://github.com/firebase/firebase-ios-sdk/issues/1735
> Fix nullability analysis error in GULAppDelegateSwizzler

- Firestore/Example/Tests/SpecTests/FSTLevelDBSpecTests.mm
- Firestore/Example/Tests/SpecTests/FSTMemorySpecTests.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.h
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
- Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
- Firestore/Example/Tests/SpecTests/json/write_spec_test.json
Restart the persistence layer when a spec test calls for a restart. Port of https://github.com/firebase/firebase-js-sdk/pull/1129
> Start restarting persistence in spec tests

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/API/FIRListenerRegistration.mm
- Firestore/Source/API/FSTUserDataConverter.mm
- Firestore/Source/Core/FSTQuery.h
- Firestore/Source/Core/FSTQuery.mm
- Firestore/core/test/firebase/firestore/testutil/app_testing.h
- Firestore/third_party/Immutable/FSTTreeSortedDictionary.m
- scripts/sync_project.rb
Fixes #1743.
Note that some analyze errors remain in abseil-cpp sources. I'll see if we can get these fixed upstream.
> Fix analyze issues in Firestore

- Firebase/Database/Public/FIRDatabase.h
Originally added by https://github.com/firebase/firebase-ios-sdk/pull/48 to prevent incorrect usage of `FIRDatabase`, but was incorrectly added as a class method rather than an instance method.
> Fixes incorrect declaration of the init method

- Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests_iOS.xcscheme
- Firestore/core/src/firebase/firestore/util/executor_libdispatch.h
- Firestore/core/src/firebase/firestore/util/executor_libdispatch.mm
The original idea was for the destructor of `ExecutorLibdispatch` to turn any scheduled operations into no-ops (because whatever is scheduled in libdispatch cannot be truly canceled). This was removed in #1240; looking at the discussion, apparently the rationale was this _"classes that schedule delayed operations are already supposed to clear them on shutdown, so clearing them one more time is redundant and may mask logic errors"_. However, it looks like this situation can be easily triggered when running unit tests by just setting a breakpoint -- it will lead to a `TimeSlot`'s execution that tries to access the executor after it's already destroyed.
> Fix crash in `ExecutorLibdispatch` when running unit tests

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
- Firestore/Source/Remote/FSTOnlineStateTracker.mm
- Firestore/Source/Remote/FSTRemoteStore.mm
[Port of https://github.com/firebase/firebase-js-sdk/pull/1197]
1. Changed MAX_WATCH_STREAM_FAILURES to 1 per conversation with @wilhuff and
@jdimond.
2. Fixed a "race" where when a get() triggered a watch stream error, we'd
restart the stream, then get() would remove its listener, and so we had no
listener left once the watch stream was "opened". Without a listen to send
we'd be stuck in Offline state (even though we should be Unknown whenever
we have no listens to send), resulting in the next get() returning data
from cache without even attempting to reach the backend.
> Offline get() improvements.

- Firestore/core/src/firebase/firestore/remote/exponential_backoff.cc
- Firestore/core/src/firebase/firestore/remote/exponential_backoff.h
[Port of https://github.com/firebase/firebase-js-sdk/pull/1132]
> Make C++ exponential backoff account for already-elapsed time.

- Firestore/core/src/firebase/firestore/remote/grpc_stream.cc
- Firestore/core/test/firebase/firestore/remote/grpc_stream_test.cc
By default, `StartCall` in gRPC C++ client would wait until the initial server metadata is received, after which the corresponding tag will come back from the completion queue. It can alternatively be configured so that initial server metadata is only received together with the first write operation, effectively making `StartCall` a synchronous operation. The benefit is that Firestore streams won't have to wait for a network roundtrip before they consider themselves open. It is also consistent with the other platforms.
> gRPC C++: don't wait for initial server metadata during `GrpcStream::Start`

- Example/Database/Tests/Integration/FData.m
- Example/Database/Tests/Integration/FIRDatabaseQueryTests.m
Travis is failing repeatedly today on the Database Integration tests. This failure also came up a few weeks ago
```
Failing tests:
-[FData testParentDeleteShadowsChildListenersWithNonDefaultQuery]
** TEST FAILED **
```
I saw this running locally:
```
Test Case '-[FData testParentDeleteShadowsChildListenersWithNonDefaultQuery]' started.
2018-09-11 17:20:49.288167-0700 Database_Example_iOS[47616:5115899] *** Assertion failure in -[XCTestCase(Failures) _enqueueFailureWithDescription:inFile:atLine:expected:breakWhenDequeued:](), /Library/Caches/com.apple.xbs/Sources/XCTest_Sim/XCTest-14100/Sources/XCTestFramework/Core/XCTestCase+Failures.m:60
2018-09-11 17:20:49.288482-0700 Database_Example_iOS[47616:5115899] *** Assertion failure in -[XCTestCase(Failures) …
```
> ifdef out flaky Database Integration Tests

- GoogleUtilities.podspec
- GoogleUtilities/Example/GoogleUtilities.xcodeproj/project.pbxproj
- GoogleUtilities/Example/Tests/User Defaults/GULUserDefaultsTests.m
- GoogleUtilities/UserDefaults/GULUserDefaults.m
- GoogleUtilities/UserDefaults/Private/GULUserDefaults.h
This is a workaround for NSUserDefaults crashing when setting values
in the background in some situations on iOS 11. This uses the C API
in order to avoid an NSNotification firing (which a class eventually
tries to update the UI from the thread that set the value).
> Add GULUserDefaults to GoogleUtilities.

- Firestore/Example/App/GoogleService-Info.plist
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/README.md
This brings iOS into line with the other platforms that also test against prod by default and brings Firestore iOS into line with the other iOS projects which require a similar configuration.
> Allow GoogleServices-Info.plist to configure Firestore integration tests

- Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
- Firestore/Source/Local/FSTLevelDBQueryCache.mm
- Firestore/core/src/firebase/firestore/local/leveldb_key.cc
- Firestore/core/src/firebase/firestore/local/leveldb_key.h
- Firestore/core/src/firebase/firestore/local/leveldb_migrations.cc
- Firestore/core/src/firebase/firestore/nanopb/reader.cc
- Firestore/core/src/firebase/firestore/nanopb/reader.h
DO NOT MERGE.
Port of https://github.com/firebase/firebase-js-sdk/pull/1149
I believe this needs to be merged with other ports first before being merged to master. Otherwise, we will continue to hold write acks. But, might as well get this one reviewed now and merge others into it.
> Drop acknowledged mutations in schema migration

- .travis.yml
- GoogleUtilities.podspec
- GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
- GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
- GoogleUtilities/Network/GULNetworkURLSession.m
Fix #1829.  
If `use_frameworks!` was not included in a Podfile and a static library build is done, Xcode uses the minimum iOS version of 6 to build GoogleUtilities generating several warnings for iOS 7 APIs.  This PR adds `@availability` checks to eliminate the warnings.
Also drop Xcode 8 testing since Xcode 8 doesn't support `@availability` and we dropped pre-Xcode 8 support in July when the AppStore started requiring Xcode 9 for submissions.
There is a client requirement to be installable for iOS 6 despite its functionality gaps.
> Fix GoogleUtilities warnings in static library installs

- Firestore/core/src/firebase/firestore/util/executor_libdispatch.mm
- Firestore/core/test/firebase/firestore/util/executor_libdispatch_test.mm
There is a deadlock that is triggered while running integration tests in XCode 10 (previous versions of XCode seem to work fine). During integration test case shutdown, two executors used in Firestore, the worker executor and the user executor, happen to be destroyed at the same time on each other's dispatch queues (worker executor is being destroyed on the main queue, which is also the user queue, and user executor is being destroyed on the worker queue). Each calls `RunSynchronized` in its destructor, with the result that they deadlock. The fix uses `std::atomic` as the synchronization mechanism instead.
Tested -- ran integration tests under TSan in XCode 10 with no issues.
> Fix deadlock in `ExecutorLibdispatch` destructor

- FirebaseInAppMessagingDisplay.podspec
use 0.12.0 since it's derived from version 0.11.0 of FirebaseInAppMessaging.
> tune fiam display sdk version

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/API/FSTUserDataConverter.mm
- Firestore/Source/Model/FSTMutation.mm
We currently drop empty objects when during set({merge: true}) since we only add leaf nodes to the field mask. We need to consider an empty object a leaf node.
Port of firebase/firebase-js-sdk#1202
> Don't drop empty object during merge

- Example/Auth/README.md
- Example/Auth/Sample/ApplicationDelegate.m
- Example/Auth/Sample/MainViewController.m
- Example/Auth/Sample/MainViewController.xib
- Example/Auth/Sample/SettingsViewController.xib
- Example/Auth/Sample/UserInfoViewController.xib
Multiple tiny fixes to auth sample app
- On iPhone X, once you tap into Settings view or UserInfo view, you can't get back because the "Done" button is overlapped under status bar. Fixed by adding a root navigation controller and use the default back button.
- There is an empty bar at the top to sample app console. Removed.
- A README title indent fix.
> Sample app update

- Firestore/Protos/CMakeLists.txt
- Firestore/Protos/README.md
- Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.h
- Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.m
- scripts/build.sh
All proto targets (objc, cpp, nanopb) now depend on the proto sources,
so they'll be rebuilt if the proto sources change.
Also updated Firestore/Protos/README.md to reflect recent changes.
Also update travis config to build the protos. (Previously, cpp and
nanopb were rebuilt, since they're used in the cmake build. But objc was
not since it's not actually depended on by anything in cmake.)
Also rebuild the objc protos.
> Fix building of objc protos

- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingReceiver.m
- Firebase/Messaging/FIRMessaging_Private.h
- Firebase/Messaging/Public/FIRMessaging.h
Also removed initWithMessage: method that is not used in source code and tests.
> add message ID to direct channel message

- FirebaseAuth.podspec
- FirebaseFirestore.podspec
- FirebaseStorage.podspec
These pods depend on FirebaseCore's interop APIs that were introduced
in FirebaseCore version 5.1. This wasn't picked up before since
CocoaPods automatically matched the largest minor version available but
the podspec should accurately represent the version requirements.
> Fix Core version requirement.

- FirebaseFirestore.podspec
- Firestore/Source/Local/FSTLRUGarbageCollector.mm
- Firestore/core/src/firebase/firestore/remote/datastore.mm
- Firestore/core/src/firebase/firestore/remote/grpc_stream.cc
- Firestore/core/src/firebase/firestore/remote/stream.mm
- cmake/compiler_setup.cmake
This is enforced via CI in some cases, so make it enforced in all of Firestore.
> Enforce field initialization order

- Example/Messaging/Tests/FIRMessagingReceiverTest.m
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingReceiver.h
- Firebase/Messaging/FIRMessagingReceiver.m
- Firebase/Messaging/FIRMessaging_Private.h
- Firebase/Messaging/Public/FIRMessaging.h
- FirebaseMessaging.podspec
Add a new boolean value that control whether to use direct channel callback for all iOS versions. This partially resolves the issue #1409. 
We are separating the callback between apns and direct channel. Right now for iOS 10 and above, direct channel message delivered at FIRMessagingDelegate, while for iOS 9 and below, they were delivered at UIApplicationDelegate. To not break existing behavior, if user likes to receive direct channel callback using FIRMessagingDelegate instead of UIApplicationDelegate for all ios versions, they can now set the boolean value useMessagingDelegateForDirectChannel to true.
> Add a boolean value on whether to use direct channel callback for all ios versions

- cmake/compiler_setup.cmake
-Wreorder is not a valid cflag on at least linux/gcc.
> Move -Wreorder to cxxflag (instead of common, which impacts cflags)

- Example/Auth/Sample/MainViewController.m
UnlinkFromFacebook and UnlinkFromEmailPassword both accidentally unlink from Google
> UnlinkFromFacebook and UnlinkFromEmailPassword both accidentally unlink from Google

- Firestore/core/src/firebase/firestore/util/filesystem.h
- Firestore/core/src/firebase/firestore/util/filesystem_posix.cc
- Firestore/core/test/firebase/firestore/util/filesystem_test.cc
> Add GetFileSize to filesystem.h

- Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
- Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.mm
- Firestore/Source/Local/FSTLRUGarbageCollector.h
- Firestore/Source/Local/FSTLRUGarbageCollector.mm
- Firestore/Source/Local/FSTLevelDB.mm
- Firestore/Source/Local/FSTMemoryMutationQueue.h
- Firestore/Source/Local/FSTMemoryMutationQueue.mm
- Firestore/Source/Local/FSTMemoryPersistence.h
- Firestore/Source/Local/FSTMemoryPersistence.mm
- Firestore/Source/Local/FSTMemoryQueryCache.h
- Firestore/Source/Local/FSTMemoryQueryCache.mm
- Firestore/Source/Local/FSTMemoryRemoteDocumentCache.h
- Firestore/Source/Local/FSTMemoryRemoteDocumentCache.mm
These methods will be used to determine if we should run LRU collection.
> Implement byteSize methods on lru delegates for use in GC threshold

- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
Port of firebase/firebase-js-sdk#1259 except I didn't use EventAccumulator
since it hits the default timeout. I just manually do the listener.
> Add priming logic to integration tests to avoid backend cold start issues.

- Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.h
- Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
- Firestore/Example/Tests/Local/FSTLevelDBLRUGarbageCollectorTests.mm
- Firestore/Example/Tests/Local/FSTMemoryLRUGarbageCollectorTests.mm
- Firestore/Source/Local/FSTLevelDB.mm
- Firestore/Source/Local/FSTMemoryPersistence.mm
- Firestore/Source/Local/FSTMemoryRemoteDocumentCache.h
- Firestore/Source/Local/FSTMemoryRemoteDocumentCache.mm
While working on a schema migration to add sentinel rows, I noticed we don't actually drop them, even after removing the associated document. I've fixed that, and updated the test to verify that the sentinel rows for the removed documents are gone.
> Make sure we actually drop the sentinel rows

- Firestore/Example/Tests/Local/FSTLevelDBTransactionTests.mm
- Firestore/Source/Local/FSTLevelDBQueryCache.mm
- Firestore/core/src/firebase/firestore/util/comparison.cc
- Firestore/core/src/firebase/firestore/util/comparison.h
- scripts/cpplint.py
In the spirit of automating myself out of a job.
> Add a lint check for const references to absl::string_view

- Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
- Firestore/Source/Local/FSTLevelDB.mm
- Firestore/Source/Local/FSTLevelDBQueryCache.mm
- Firestore/core/src/firebase/firestore/local/leveldb_key.cc
- Firestore/core/src/firebase/firestore/local/leveldb_key.h
- Firestore/core/src/firebase/firestore/local/leveldb_migrations.cc
- Firestore/core/src/firebase/firestore/nanopb/reader.cc
- Firestore/core/src/firebase/firestore/nanopb/reader.h
Ensures that we have a sequence number written down for each document in the remote document cache. We already have the code to sequence numbers for new documents (via target updates, mutations, and limbo resolutions). However, we have never gone back to make sure existing documents have sequence numbers.
This migration will stamp the highest sequence number observed onto each remote document which does not yet have a sentinel row.
> Schema migration to ensure sentinel rows exist

- Firestore/Source/Local/FSTLevelDB.mm
- Firestore/core/src/firebase/firestore/util/filesystem.h
- Firestore/core/src/firebase/firestore/util/filesystem_posix.cc
- Firestore/core/src/firebase/firestore/util/filesystem_win.cc
- Firestore/core/test/firebase/firestore/util/filesystem_test.cc
Also convert FileSize to return size in an int64_t. off_t is
unconditionally defined as a long on Windows, which is 32 bits even
under Win64.
> Implement util::FileSize on Windows

- GoogleUtilities/Network/GULNetworkURLSession.m
Fixes #1917, presumably fixes #1892. Sessions are invalidated on completion and error.
> Invalidate sessions in completion handlers

- Example/Firebase.xcodeproj/project.pbxproj
- Example/Messaging/Tests/FIRMessagingAnalyticsTest.m
- Example/Messaging/Tests/FIRMessagingLinkHandlingTest.m
- Example/Messaging/Tests/FIRMessagingServiceTest.m
- Example/Messaging/Tests/FIRMessagingTest.m
- Firebase/Messaging/FIRMMessageCode.h
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingAnalytics.h
- Firebase/Messaging/FIRMessagingAnalytics.m
- Firebase/Messaging/Public/FIRMessaging.h
- FirebaseAnalyticsInterop.podspec
- FirebaseMessaging.podspec
- Interop/Analytics/Public/FIRInteropEventNames.h
- Interop/Analytics/Public/FIRInteropParameterNames.h
- scripts/pod_lib_lint.sh
- Switch to FIRComponent initialization
- Use FirebaseAnalyticsInterop for Messaging's analytics logging
- Migrate code and tests back from InstanceID
- Port and augment unit tests
> Do Messaging's Analytics logging via Interop

- Firestore/core/src/firebase/firestore/model/field_path.cc
- Firestore/core/src/firebase/firestore/util/comparison.cc
Resolve conflict w.r.t. string and isnan().
This is not yet the change to make the FieldPath portable but a first step to make it build. The change w.r.t. STLPort will be in subsequent PRs.
> fix Firestore C++ g3 build

- GoogleUtilities.podspec
Bump version to publish #1922 leak fixes exposed by Xcode 10 Instruments
> GoogleUtilities to 5.3.1 to publish Xcode 10 leak fixes

- Firestore/core/src/firebase/firestore/model/precondition.cc
- Firestore/core/src/firebase/firestore/model/precondition.h
- Firestore/core/test/firebase/firestore/model/precondition_test.cc
Required by the Mutation objects.
> Allow Precondition::IsValidFor to work with nullptr.

- GoogleUtilities.podspec
Post submit testing found some issues caused by the #1922 in FirebaseAnalytics tests on ios 8.
> Bump version to 5.3.2 to rollback leak fixes

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/LibFuzzer.podspec
- Firestore/Example/Podfile
LibFuzzer uses thread_local, which isn't available until iOS 9.0
This fixes builds under Xcode 10, where the linker is finally enforcing
that running this binary on iOS 8 wouldn't work.
> Fix fuzzer build under Xcode 10

- .travis.yml
- scripts/build.sh
- scripts/style.sh
- Convert travis to Xcode 10 as the primary testing target.
- Add three jobs for continued Xcode 9 testing.
- Split InAppMessaging tests, since simulators fail to start with Xcode 10 and travis and multiple targets invoked from one xcodebuild command.
> Add Xcode 10 travis testing

- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/core/src/firebase/firestore/remote/grpc_connection.h
- Firestore/core/src/firebase/firestore/remote/grpc_connection.mm
This closely mimics the way it is currently done in Objective-C gRPC client by simply using a static string that contains a file path.
> gRPC: add the ability to use a custom SSL certificate in integration tests

- Firestore/Protos/protos/firestore/local/maybe_document.proto
- Firestore/Protos/protos/firestore/local/mutation.proto
- Firestore/Protos/protos/firestore/local/target.proto
Updating the iOS Proto to match Android. This is in preparation for the held write acks removal.
> Adding unknownDocument

- scripts/if_changed.sh
Fix bug introduced in #1887. 
The InAppMessaging travis tests were running even if they had no changes.
> Fix if_changed for addition of InAppMessagingDisplay

- Example/Messaging/Tests/FIRMessagingContextManagerServiceTest.m
- Firebase/Messaging/FIRMessagingContextManagerService.m
Fixed issue https://github.com/firebase/firebase-ios-sdk/issues/1946
> Always use 24-hours locale

- GoogleUtilities/Network/GULNetworkURLSession.m
- GoogleUtilities/Network/Private/GULNetworkMessageCode.h
Fixes #1917 and #1892. This PR takes a more conservative approach, only invalidating at the end of the URL request lifecycle and adds some minor error reporting.
> Fix leak of url sessions in GoogleUtilities

- Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Local/FSTMemoryMutationQueue.mm
- Firestore/Source/Local/FSTMutationQueue.h
Port of https://github.com/firebase/firebase-android-sdk/pull/30
> Change removeMutationBatch to remove a single batch

- GoogleUtilities/Logger/GULLogger.m
Thread sanitizer spots a data race in [`GULSetLoggerLevel`](https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/Logger/GULLogger.m#L105) (full error message [here](https://gist.github.com/var-const/e1f828ab76a9ee078a8cac2f0381e9f4)). This prevents a clean run of Firestore integration tests under TSan.
Following #1390, I'm simply making sanitizer ignore this function. However, note that in both C++ and C, a data race is undefined behavior (the compiler is free to produce code assuming the memory in question is never accessed from more than one thread). I don't know if Objective-C provides any stronger guarantees.
> GULLogger: ignore a data race

- Firestore/core/src/firebase/firestore/remote/datastore.h
- Firestore/core/src/firebase/firestore/remote/datastore.mm
- Firestore/core/test/firebase/firestore/remote/datastore_test.mm
(see [here](https://github.com/firebase/firebase-ios-sdk/pull/1935#discussion_r224900667) and [here](https://github.com/grpc/grpc/issues/16875) for context)
The problem with serializing a domain object immediately is that the resulting `ByteBuffer` is stored in a `std::function` within Auth. `ByteBuffer`s become invalid once gRPC core shuts down, so if Auth happens to outlive Firestore, once the `ByteBuffer`'s destructor is invoked, the app will crash.
> gRPC: in `Datastore`, delay serializing domain object to a `grpc::ByteBuffer` right until the call is started

- Firestore/Example/Tests/Model/FSTMutationTests.mm
- Firestore/Source/Local/FSTLocalDocumentsView.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Model/FSTMutation.h
- Firestore/Source/Model/FSTMutation.mm
- Firestore/Source/Model/FSTMutationBatch.h
- Firestore/Source/Model/FSTMutationBatch.mm
This PR is meant to align the internal APIs for applying mutations with Android/Web. There is some code duplication now, some of which will go away in the held write acks port. In general, I went with the "least amount of work" approach with the PR, as lots of the internal logic will change soon.
> Port Mutation Batch API from Android/Web

- Firestore/Source/Core/FSTFirestoreClient.mm
- Firestore/Source/Local/FSTLRUGarbageCollector.h
- Firestore/Source/Local/FSTLRUGarbageCollector.mm
- Firestore/Source/Local/FSTLevelDB.mm
- Firestore/Source/Local/FSTMemoryPersistence.mm
- Firestore/Source/Util/FSTDispatchQueue.mm
- Firestore/core/src/firebase/firestore/util/async_queue.h
Merge is into LRU branch.
* Fixes scheduling to actually work properly!
* Fixes logging to only use strings because that's all we support
* Includes orphaned documents in the sequence number count. For some workloads (e.g. write heavy with few targets), just looking at a percentage of targets will avoid GC when it should be running
> LRU tweaks

- Example/Podfile
The cron travis tests are getting strange failures where the Storage iOS integration tests are pulling in the mac Cocoa.h when building OCMock.
It turns out that the integration tests do not even need OCMock. Similarly, none of the Database tests use OCMock.
> Remove unnecessary OCMock Podfile dependencies

- Firestore/Protos/cpp/firestore/local/maybe_document.pb.cc
- Firestore/Protos/cpp/firestore/local/maybe_document.pb.h
- Firestore/Protos/nanopb/firestore/local/maybe_document.nanopb.c
- Firestore/Protos/nanopb/firestore/local/maybe_document.nanopb.h
- Firestore/Protos/objc/firestore/local/MaybeDocument.pbobjc.h
- Firestore/Protos/objc/firestore/local/MaybeDocument.pbobjc.m
- Firestore/Protos/objc/firestore/local/Target.pbobjc.h
Regenerate the C++ Proto headers with the UnknownDocument proto change.
> Update Firestore Generated Protos

- Firebase/DynamicLinks/FIRDLDefaultRetrievalProcessV2.m
- Firebase/DynamicLinks/FIRDynamicLinks.m
typeof() is not supported in some C language dialects which causes
issues when integrating FDL in projects that do use non-GNU compiler modes.
For example, this causes problems when building in some versions of Unity
https://github.com/firebase/quickstart-unity/issues/228
> Changed FDL to use compatible __typeof__() operator.

- GoogleUtilities/Network/GULNetworkURLSession.m
Potentially fix #1964.
TAP runs over at cr/217930814.
> Lock reads and writes to session map

- Example/Core/Tests/FIRAppTest.m
- Firebase/Core/FIRApp.m
Some of the diagnostics notifications were missed and not covered by
the data collection flag.
> Wrap diagnostics notification in collection flag check.

- Example/Storage/Tests/Integration/FIRStorageIntegrationTests.m
- Example/Storage/Tests/Unit/FIRStorageDeleteTests.m
- Example/Storage/Tests/Unit/FIRStorageGetMetadataTests.m
- Example/Storage/Tests/Unit/FIRStorageUpdateMetadataTests.m
- Firebase/Storage/FIRStorage.m
- Firebase/Storage/FIRStorageDeleteTask.m
- Firebase/Storage/FIRStorageDownloadTask.m
- Firebase/Storage/FIRStorageGetDownloadURLTask.m
- Firebase/Storage/FIRStorageGetMetadataTask.m
- Firebase/Storage/FIRStorageObservableTask.m
- Firebase/Storage/FIRStorageReference.m
- Firebase/Storage/FIRStorageTask.m
- Firebase/Storage/FIRStorageUpdateMetadataTask.m
- Firebase/Storage/FIRStorageUploadTask.m
- Firebase/Storage/Private/FIRStorageDeleteTask.h
- Firebase/Storage/Private/FIRStorageDownloadTask_Private.h
- Firebase/Storage/Private/FIRStorageGetDownloadURLTask.h
- Firebase/Storage/Private/FIRStorageGetMetadataTask.h
- Firebase/Storage/Private/FIRStorageObservableTask_Private.h
- Firebase/Storage/Private/FIRStorageTask_Private.h
- Firebase/Storage/Private/FIRStorageUpdateMetadataTask.h
- Firebase/Storage/Private/FIRStorageUploadTask_Private.h
- Firebase/Storage/Private/FIRStorage_Private.h
Instead of enforcing that all operations happen on the main queue, this changes the storage SDK to internally queue all operations on a serial queue.
Fixes https://github.com/firebase/firebase-ios-sdk/issues/1888
Fixes https://github.com/firebase/firebase-ios-sdk/issues/1302
> Queue Storage Tasks on separate queue

- Example/Auth/Tests/FIRAuthDispatcherTests.m
The testDispatchAfterDelay test has flaked three times today in the mac travis tests. Try increasing the timeout.
> Increase timeout for testDispatchAfterDelay

- Example/Storage/Tests/Integration/FIRStorageIntegrationTests.m
- Firebase/Storage/CHANGELOG.md
- Firebase/Storage/FIRStorageUtils.m
Fixes https://b.corp.google.com/issues/117819649
> Allow semicolon in file name

- Example/Core/Tests/FIRAppTest.m
- Firebase/Core/FIRApp.m
This was added when the Google pod could configure Firebase but the
Google pod is deprecated and can only work with Firebase 3.X. These
flags and conditional checks can be safely removed.
>  Remove unnecessary notification flag

- Example/Core/Tests/FIRAppTest.m
- Example/Core/Tests/FIROptionsTest.m
- Firebase/Core/FIRApp.m
- Firebase/Core/Private/FIRAppInternal.h
There have been some issues while creating new tests where there is a conflict with mocks of `FIRApp` and `FIROptions`. Instead of relying on internal static variables we should try to use new instances of `FIRApp` and `FIROptions` where possible. Any usages of the singletons and `configure` methods should be explicitly to test those methods.
This also combines the logic of initializing the default app and a custom app with name and options, since they do the same thing but one assigns the static variable `sDefaultApp` and one does not.
> Reduce singleton usage in FIRApp tests.

- FirebaseAuth.podspec
- FirebaseCore.podspec
- FirebaseDatabase.podspec
- FirebaseDynamicLinks.podspec
- FirebaseFirestore.podspec
- FirebaseFunctions.podspec
- FirebaseInAppMessagingDisplay.podspec
- FirebaseMessaging.podspec
- FirebaseStorage.podspec
- scripts/if_changed.sh
Fix #1983
Enforce c99 compliance for Unity compatibility and future portability
Also:
- Sort pod_target_xcconfig keys
- Fix formatting
- Trigger travis for Firestore podspec changes
> Comply with c99 standard

- Firestore/Source/Core/FSTFirestoreClient.mm
- Firestore/Source/Util/FSTClasses.h
`typeof` is only defined if you compile with GNU extensions, while
`__typeof__` is always available.
This is the Firestore equivalent of #1982.
Note that Firestore won't yet build in this mode because among other
things the Objective-C gRPC still uses `typeof`. Once we eliminate that
dependency this might become possible.
> Use C99-compatible __typeof__ instead of typeof

- Example/Podfile
- Firebase/Core/FIROptions.m
- Firebase/Messaging/CHANGELOG.md
- FirebaseCore.podspec
- FirebaseFirestore.podspec
- FirebaseMessaging.podspec
- Firestore/Example/Podfile
- Releases/Manifests/5.11.0.json
Merging the 5.11.0 release into master.
> Release 5.11.0

- Firebase/Auth/CHANGELOG.md
- FirebaseAuth.podspec
- FirebaseCore.podspec
- FirebaseDatabase.podspec
- FirebaseDynamicLinks.podspec
In the Firebase 5.0.0, we lost the SafariServices framework from FirebaseAuth because of an overwrite in the updated podspec.
The issue was reported at https://groups.google.com/forum/#!msg/firebase-talk/oJadY1uGSWY/eWZVoox1CAAJ
- This PR restores the framework.
- Makes all podspec frameworks follow the [docs](https://guides.cocoapods.org/syntax/podspec.html#frameworks).
- Updates Auth release notes (including a few previous missed ones).
I confirmed that the generated Pod targets have the right framework dependencies. As expected, only FirebaseAuth is changed and corrected.
> Restore SafariServices framework

- FirebaseFirestore.podspec
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Source/Core/FSTFirestoreClient.mm
Note that c++0x is how Xcode spells c++11.
Also fix an issue where we were accidentally using a C++14 feature.
> Force Firestore to conform to C99 and C++11

- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
The issue has already been fixed and we are now running integration test with actual server instead of hexa.
> Remove sleep that works around over-aggressive snapshot validation in tests

- Firestore/Example/Tests/Core/FSTViewTests.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Model/FSTDocument.mm
This PR removes all held write batch handling from LocalStore.
This is a direct port of https://github.com/firebase/firebase-android-sdk/pull/34
Test cleanup coming after I port the View changes.
> Removing held write batch handling from LocalStore

- Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Local/FSTMemoryMutationQueue.mm
- Firestore/Source/Local/FSTMutationQueue.h
Port of https://github.com/firebase/firebase-android-sdk/pull/40/files
Removes allMutationBatchesThroughBatchID and highestAcknowledgedBatchID.
> Remove no longer needed MutationBatch methods

- Carthage.md
This PR is about improving the documentation regarding integrating Firebase with Carthage.
Changes:
- There were two inaccuracies in the documentation that I fixed. 
- I also added a link to a support page that explains how to download the config file.
> Updated the Carthage installation instructions

- Carthage.md
- README.md
- Rome.md
First pass at instructions for using Rome to install Firebase.
Note that the instructions are almost basically the same as the zip instructions after copying the frameworks.
And a advantage of Rome over both the zip distribution and Carthage, is that the frameworks, including subspecs are customized to exactly what the app needs.
A second benefit is the Rome creation overhead is much lower than the zip distribution and Carthage.
> Add Rome instructions

- Example/Auth/Tests/FIRAuthDispatcherTests.m
Increase `kMaxDifferenceBetweenTimeIntervals` to attempt frequent travis flake on macOS runs since we switched to Xcode 10:
FIRAuthDispatcherTests
testDispatchAfterDelay, ((timeSinceDispatch < kMaxDifferenceBetweenTimeIntervals) is true) failed
/Users/travis/build/firebase/firebase-ios-sdk/Example/Auth/Tests/FIRAuthDispatcherTests.m:73
```
NSTimeInterval timeSinceDispatch = fabs([dateBeforeDispatch timeIntervalSinceNow]) - kTestDelay;
XCTAssert(timeSinceDispatch < kMaxDifferenceBetweenTimeIntervals);
[expectation fulfill];
```
Also undo #1988 which adjusted the wrong timeout value.
> Attempt to fix frequent Auth Unit Test flake on OSX

- InAppMessagingDisplay/Example/InAppMessagingDisplay-UITests/InAppMessagingDisplayImageOnlyViewUITests.swift
- InAppMessagingDisplay/Example/InAppMessagingDisplay-UITests/InAppMessagingDisplayUITestsBase.swift
The total test time stayed between 29 and 30 minutes.
> Increase timeouts in attempt to eliminate travis flakes

- Example/Messaging/Tests/FIRMessagingAnalyticsTest.m
Address travis flake:
✗ testLogMessage, OCMockObject(FIRMessagingAnalytics): Method logForegroundNotification:{
> Don't rely on test always being in foreground

- Firebase/Core/FIRApp.m
Although SDKs being configured should access the app through the
dictionary being passed in (and soon the `FIRCoreConfigurable`
protocol), the default app should be assigned before notifying SDKs
that Core is ready.
> Assign the default app before posting notifications.

- Firestore/CHANGELOG.md
> Update CHANGELOG for Firestore v0.14.0

- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/json/collection_spec_test.json
- Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/SpecTests/json/orderby_spec_test.json
- Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
- Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
- Firestore/Example/Tests/SpecTests/json/resume_token_spec_test.json
- Firestore/Example/Tests/SpecTests/json/write_spec_test.json
- Firestore/Source/Local/FSTLocalStore.mm
- Firestore/Source/Local/FSTReferenceSet.h
- Firestore/Source/Local/FSTReferenceSet.mm
This imports the Spec test from Web and ports the test runner's held write acks changes.
It also:
1) Fixes a bug in the Held Write Acks branch (some bug also fixed in pending PR https://github.com/firebase/firebase-ios-sdk/pull/2008)
2) Adds logic back to local store to remove references for mutations that matched a query target. This broke two spec tests without held write acks and was not all that fun to track down...
Because of 2, I am sending this to Gil.
> Held Write Ack Removal Spec Tests

- Firebase/Core/FIRApp.m
Explicitly check for `nil` instead of using the `!` operator on the pointer.
> Fix static analysis warning in Core.

- Firestore/CHANGELOG.md
This removes the changelog entry that describes our migration to
gRPC-C++.
> Partially revert "Update CHANGELOG for Firestore v0.14.0 (#2025)"

- Firebase/Core/CHANGELOG.md
This is part of merging master to the release branch instead of cherry-picking some release fixes to keep future merging cleaner.
> Move #2034 into 5.12.0

- Example/Database/Tests/Unit/FPruneForestTest.m
- Example/DynamicLinks/Tests/FIRDLScionLoggingTest.m
- Example/Firebase.xcodeproj/xcshareddata/xcschemes/AllUnitTests_iOS.xcscheme
- Example/Messaging/Tests/FIRMessagingAnalyticsTest.m
- Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m
- Firebase/DynamicLinks/FIRDLDefaultRetrievalProcessV2.m
- Firebase/DynamicLinks/FIRDynamicLinks.m
Clean up analyze issues
From manual run until we get #1744
> Fix analyze errors

- Example/tvOSSample/tvOSSample/AuthViewController.swift
- Example/tvOSSample/tvOSSample/EmailLoginViewController.swift
- GoogleUtilities/CHANGELOG.md
- GoogleUtilities/Network/GULNetworkURLSession.m
- GoogleUtilities/Network/Private/GULNetworkURLSession.h
- Fixes issue where sessions without a background task ID wouldn't be invalidated (#1917, #2060)
- Invalidates sessions immediately upon task completion
- Adds URL cache to some non-background tasks
I'm worried this solution is insufficient for instances of `GULNetworkURLSession` that kick off multiple requests simultaneously since the `_URLSession` ivar will be overridden.
Changes mirrored at cr/220718996
> Invalidate non-background url sessions

- Firestore/Protos/cpp/firestore/local/mutation.pb.cc
- Firestore/Protos/cpp/firestore/local/mutation.pb.h
- Firestore/Protos/nanopb/firestore/local/mutation.nanopb.cc
- Firestore/Protos/nanopb/firestore/local/mutation.nanopb.h
- Firestore/Protos/objc/firestore/local/Mutation.pbobjc.h
- Firestore/Protos/objc/firestore/local/Mutation.pbobjc.m
- Firestore/Protos/protos/firestore/local/mutation.proto
This ports the https://github.com/firebase/firebase-android-sdk/pull/105 `base_writes` field to iOS.
> Adding base_writes proto field

- GoogleUtilities/CHANGELOG.md
- GoogleUtilities/Example/Tests/Swizzler/GULObjectSwizzlerTest.m
- GoogleUtilities/ISASwizzler/GULObjectSwizzler.m
- GoogleUtilities/ISASwizzler/GULSwizzledObject.m
- GoogleUtilities/ISASwizzler/Private/GULObjectSwizzler.h
- GoogleUtilities/SwizzlerTestHelpers/GULProxy.h
- GoogleUtilities/SwizzlerTestHelpers/GULProxy.m
A fix for: https://github.com/firebase/firebase-ios-sdk/issues/1936
GULObjectSwizzler couldn't currently handle ISA Swizzling NSProxy objects - this PR adds logic that deals with that and unit tests that would've failed if this logic weren't present.
The way this is done:
1. Stop depending on the `-[NSObjectProtocol class]` method to determine the class and use a runtime C function as the ObjC method is probably overriden to hide the fact that it is a proxy.
2. If it's a proxy, also swizzle the `-[NSObjectProtocol respondsToSelector:]` method to take into account the new methods we might've added.
Side note: It'd be so nice if there were a canonical way to access the underlying object(s) from an NSProxy.
> Update the GULObjectSwizzler to handle NSProxy objects

- GoogleUtilities.podspec
- GoogleUtilities/CHANGELOG.md
Release fixes for FirebasePerformance crash(#1936) and a memory leak (#2061)
Merging this is contingent upon #2053 merging.
> GoogleUtilities 5.3.5

- Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests_iOS.xcscheme
- Firestore/Example/Tests/API/FSTAPIHelpers.mm
The code in question looks like this:
```cpp
std::string make_string();
absl::string_view foo = make_string(); // Line 2
use_foo(foo);
```
The issue is that `string_view` is a non-owning wrapper. The return value of `make_string` goes out of scope and is destroyed right after line 2, and `foo` is left pointing to deallocated memory.
In this case, the fix is just to assign to a `std::string` directly. If a `string_view` is desirable, code must ensure that the `std::string` it wraps is valid as long as the view exists.
Introduced in #2029. Found running unit tests under ASan.
> Fix `string_view` referring to an out-of-scope string

- GoogleUtilities.podspec
- GoogleUtilities/CHANGELOG.md
- GoogleUtilities/Network/GULNetworkURLSession.m
- GoogleUtilities/Network/Private/GULNetworkURLSession.h
For some reason, Xcode 9 catches these, but not Xcode 10.
> Fix GoogleUtilities nullability regressions

- Firebase/InAppMessagingDisplay/Resources/FIRInAppMessageDisplayStoryboard.storyboard
`adjustsFontForContentSizeCategory` attribute is unsupported in iOS 10.0
> Remove `adjustsFontForContentSizeCategory` from labels in card layout Storyboard

- .travis.yml
> Add pod spec lint testing for Xcode 9

- FirebaseDynamicLinks.podspec
- FirebaseMessaging.podspec
While FirebaseAnalytics only exists on iOS, FirebaseAnalyticsInterop is supported on iOS, tvOS, and macOS.
This change is purely a clean-up since DynamicLinks and Messaging are currently only supported on iOS.
> FirebaseAnalyticsInterop is cross-platform

- FirebaseFirestore.podspec
While gRPC-C++ is in its 0.* versions, any new version could potentially contain breaking changes. Make sure we only upgrade at our own pace.
> Pin gRPC-C++ version to exactly 0.0.5

- FirebaseFirestore.podspec
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm
gRPC-C++ versions up to and including 0.0.3, and also 0.0.5, don't bundle `roots.pem` in the podspec. gRPC-C++ 0.0.4 and, presumably, the currently not-yet-released 0.0.6 do. Firestore currently also bundles this file under the same bundle name, which leads to build errors when both Firestore and gRPC-C++ try to add the file into the build (only shows during archiving).
For transition, this PR:
* renames the Firestore bundle to avoid naming clash;
* changes the loading code so that it first tries to load certificates bundled with gRPC-C++ (versions 0.0.4 and 0.0.6+), but falls back to those bundled with Firestore if necessary.
At a later point, Firestore should be changed to not bundle the certificates altogether.
> Prefer roots.pem from gRPC-C++, but fall back to Firestore bundled ones if necessary

- Example/Firebase.xcodeproj/project.pbxproj
This resolves the annoying Xcode errors that claim `FIRAppInternal.h` can't be found.
It also makes it *much* easier to "Jump to definition" now.
> Add Firebase Source to Header Search Path

- Firestore/core/test/firebase/firestore/util/CMakeLists.txt
grpc_stream_tester.cc relies on f:f:model::DatabaseId, but wasn't
depending on it within the cc_library f_f_remote_test_util rule, causing
the build to fail. (Presumably, a mac specific library indirectly pulls
this in.)
> Fix build under linux/gcc

- Example/Firebase.xcodeproj/project.pbxproj
Reverts firebase/firebase-ios-sdk#2114
See this [comment thread](https://github.com/firebase/firebase-ios-sdk/pull/2114#discussion_r236447015) for the discussion on why I am reverting this PR.
> Revert "Add Firebase Source to Header Search Path"

- Firebase/DynamicLinks/FDLURLComponents/FIRDynamicLinkComponentsKeyProvider.h
- Firebase/DynamicLinks/FDLURLComponents/FIRDynamicLinkComponentsKeyProvider.m
Instead of using `[FIROptions defaultOptions]` we should be using
`FIRApp`'s options. This will allow developers to use custom `FIROptions`
instead of the default named info.plist.
This addresses #2112.
> Avoid using default FIROptions directly.

- Example/DynamicLinks/App/iOS/DL-Info.plist
- Example/DynamicLinks/FDLBuilderTestAppObjC/Info.plist
- Example/DynamicLinks/FDLBuilderTestAppObjC/ViewController.m
- Example/DynamicLinks/FDLBuilderTestAppObjCTests/Info.plist
- Example/DynamicLinks/Tests/FDLURLComponentsTests.m
- Example/DynamicLinks/Tests/FIRDynamicLinkNetworkingTests.m
- Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
- Firebase/DynamicLinks/CHANGELOG.md
- Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m
- Firebase/DynamicLinks/FIRDynamicLinks.m
- Firebase/DynamicLinks/Logging/FDLLogging.h
- Firebase/DynamicLinks/Public/FDLURLComponents.h
- Firebase/DynamicLinks/Utilities/FDLUtilities.h
- Firebase/DynamicLinks/Utilities/FDLUtilities.m
The new API is optional and current API is fully supported.
This reverts commit 46cb564067c3cfb720cf2adc33366ce651c59e17.
can discuss …
> Move to `domainURIPrefix` for FIRDynamicLinkComponents

- scripts/fuzzing_ci.sh
Fuzzing triggers many assertion failures, which generates enormous log output. AFAIK, there is no way to make `NSAssertionHandler` _not_ write to log, and the assertions themselves are valid. Thus, implement a workaround: only output the last part of the logs in Travis, in order to avoid exceeding the log size limit (4 Mb).
> Make fuzzing less verbose to avoid exceeding Travis log limit

- Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
- Firestore/core/src/firebase/firestore/local/leveldb_migrations.cc
- Firestore/core/src/firebase/firestore/local/leveldb_migrations.h
Due to the nature of leveldb, our existing migrations are idempotent already. As with other platforms, this is not a guarantee that they will always be, but in general the issue is largely the same as with migrating protobufs.
> Save schema version on downgrade, add test to verify

- Carthage.md
To accommodate for release 5.14.0.
> Carthage: update the name of certificates bundle

- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogClock.h
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogClock.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogEvent.h
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogEvent.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogProto.h
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogWriter.h
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogWriter.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogger.m
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLLogWriter_Private.h
- GoogleDataLogger/Tests/GDLLogEventTest.m
- GoogleDataLogger/Tests/GDLLogWriterTest.m
> Flesh out the log event and log writer classes

- Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm
When the project is manually configured, it's possible that the certificates file gets added to the main bundle, not the Firestore framework bundle; make sure the bundle can be loaded in that case as well.
> When searching for gRPC certificates, search the main bundle as well

- Firestore/CHANGELOG.md
> Minor tweaks to release note

- GoogleDataLogger.podspec
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogEvent.h
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogEvent.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogWriter.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogger.m
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLLogTransformer.h
- GoogleDataLogger/GoogleDataLogger/DependencyWrappers/GDLConsoleLogger.h
- GoogleDataLogger/GoogleDataLogger/DependencyWrappers/GDLConsoleLogger.m
- GoogleDataLogger/Tests/GDLLogEventTest.m
- GoogleDataLogger/Tests/GDLLogWriterTest.m
> Create a log wrapper and better test GDLLogWriter

- Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
This to fix issue #1451.
Seems like the tests do succeed in local build. Revert the change to see if it still breaks travis.
> fix the unit test #1451

- Firestore/Source/Local/FSTLRUGarbageCollector.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTLevelDBQueryCache.mm
- Firestore/core/src/firebase/firestore/remote/connectivity_monitor_apple.mm
- Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.h
This fixes a few minor leaks:
* In leveldb/lru gc, a retain cycle that would leak once over the lifetime of the app
* In the streams, a retain cycle that would leak once per stream creation (enableNetwork/identity change--not per reconnect)
* In the SCNetworkReachability monitor, we failed to CFRelease the ref, which would leak once over the lifetime of the app
Unit tests and Integration tests now pass cleanly under Instruments.
None of these appear related to #2189, but I couldn't reproduce that specific leak over the course of multiple runs.
> Fix leaks in Firestore

- GoogleDataLogger/GoogleDataLogger/Classes/GDLClock.h
- GoogleDataLogger/GoogleDataLogger/Classes/GDLClock.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLRegistrar.m
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLLogEvent_Private.h
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLRegistrar_Private.h
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLLogBackend.h
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLLogPrioritizer.h
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLLogScorer.h
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLRegistrar.h
- GoogleDataLogger/Tests/GDLRegistrarTest.m
> Create some core infrastructure for backends

- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogEvent.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogWriter.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogger.m
> Implement -hash and -copy of GDLLogEvent, copy on log, and don't assign extensionBytes in log writer

- GoogleDataLogger/GoogleDataLogger/Classes/GDLUploader.h
- GoogleDataLogger/GoogleDataLogger/Classes/GDLUploader.m
- GoogleDataLogger/Tests/GDLLogUploaderTest.m
- GoogleDataLogger/Tests/Helpers/GDLTestBackend.h
- GoogleDataLogger/Tests/Helpers/GDLTestBackend.m
- GoogleDataLogger/Tests/Helpers/GDLTestPrioritizer.h
- GoogleDataLogger/Tests/Helpers/GDLTestPrioritizer.m
Provides some structure for the shared uploader and some helpers that will be used for testing.
> Add some test helpers and structure for new classes

- Firestore/Example/Tests/Util/FSTHelpers.mm
- Firestore/Source/API/FSTUserDataConverter.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/core/src/firebase/firestore/core/user_data.h
- Firestore/core/src/firebase/firestore/core/user_data.mm
- Firestore/core/src/firebase/firestore/model/field_mask.h
- Firestore/core/test/firebase/firestore/model/field_mask_test.cc
- Firestore/core/test/firebase/firestore/testutil/testutil.cc
Rather than a vector.
Port of firebase/firebase-android-sdk#137
> Rework FieldMask to use a (ordered) set of FieldPaths

- .travis.yml
Attempt to fix bundle failure error showing up in recent travis builds:
```
$ bundle --version
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:241:in `bin_path': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
from /usr/local/bin/bundle:22:in `<main>'
```
> Remove rvm specification from travis

- .travis.yml
- GoogleDataLogger/GoogleDataLogger/Classes/GDLAssert.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogEvent.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogStorage.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogWriter.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogger.m
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLAssert.h
- GoogleDataLogger/GoogleDataLogger/DependencyWrappers/GDLConsoleLogger.h
- GoogleDataLogger/Tests/GDLLogEventTest.m
- GoogleDataLogger/Tests/GDLLogStorageTest.m
- GoogleDataLogger/Tests/GDLLogUploaderTest.m
- GoogleDataLogger/Tests/GDLLogWriterTest.m
- GoogleDataLogger/Tests/GDLLoggerTest.m
- GoogleDataLogger/Tests/GDLRegistrarTest.m
- GoogleDataLogger/Tests/GDLTestCase.h
- GoogleDataLogger/Tests/GDLTestCase.m
- GoogleDataLogger/Tests/Helpers/GDLAssertHelper.h
- GoogleDataLogger/Tests/Helpers/GDLAssertHelper.m
In storeLog:, an NSAssert is expected to be triggered in certain cases while running asynchronously on a dispatch_queue. Discovering the currentThread and overriding the NSAssertionHandler with a subclass is not feasible, because NSAsserts are frequently used in Foundation code and in unit tests (XCTestExpectation, for example). A mechanism was needed to know whether or not an error was being experienced, as it's expected for certain cases.
This PR creates a custom assert that allows the calling of a soft-linked block instead of an NSAssert, and an XCTestCase subclass to be used by all subclasses that automatically sets that block to nil at the end of every unit test.
> Create testing infrastructure that simplifies catching exceptions in dispatch_queues

- GoogleDataLogger.podspec
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogStorage.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogWriter.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogger.m
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLLogStorage_Private.h
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLLogWriter_Private.h
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLLogger_Private.h
- GoogleDataLogger/Tests/Fakes/GDLLogStorageFake.h
- GoogleDataLogger/Tests/Fakes/GDLLogStorageFake.m
- GoogleDataLogger/Tests/Fakes/GDLLogWriterFake.h
- GoogleDataLogger/Tests/Fakes/GDLLogWriterFake.m
- GoogleDataLogger/Tests/Fakes/GDLUploaderFake.h
- GoogleDataLogger/Tests/Fakes/GDLUploaderFake.m
- GoogleDataLogger/Tests/GDLLogStorageTest.m
- GoogleDataLogger/Tests/GDLLogWriterTest.m
- GoogleDataLogger/Tests/GDLLoggerTest.m
Some classes have been refactored to allow the injecting of a fake. This has the benefit of allowing tests to be more hermetic without using mocks or swizzling, while also making it easier to refactor the library to move away from the singleton architecture, if that's desirable in the future.
We also make the generated project treat all warnings as errors, and to warn_pedantic.
> Refactor to allow injection of fakes, and take warnings seriously

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
- Firestore/Source/API/FIRTransaction.mm
This makes the iOS behavior match Web and Android, returning a non-nil
snapshot with exists=false, rather than a nil snapshot.
NOTE: This is a potentially breaking change and the intention is to avoid merging it until we're ready to release Firestore 1.x.
> Fix b/119570746: Transaction get returns nil if document does not exist

- Firestore/Source/Local/FSTLevelDB.mm
- GoogleUtilities/CHANGELOG.md
- GoogleUtilities/Example/Tests/UserDefaults/GULUserDefaultsTests.m
- GoogleUtilities/UserDefaults/GULUserDefaults.m
Turns out `TARGET_OS_MAC` is 1 for both macOS *and* iOS, we should be using
`TARGET_OS_OSX` instead.
Tweet with some history: https://twitter.com/gparker/status/836341915037515778
> Fixed macOS conditional check.

- Example/Messaging/Tests/FIRMessagingTest.m
- Example/Podfile
- FirebaseMessaging.podspec
- scripts/pod_lib_lint.sh
Original init method for unit test could return nil object with the new component model.
> use instanceIDForTest for instance init in unit tests

- Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/core/src/firebase/firestore/remote/serializer.cc
This is required for v1 and accepted in v1beta1.
Port of https://github.com/firebase/firebase-js-sdk/pull/1473/commits/4cec9b1c8ca852aeaa0207b12561bd7563eab1fb.
> Include a trailing /documents on root resource paths

- Firestore/Example/Tests/Remote/FSTDatastoreTests.mm
- Firestore/Example/Tests/SpecTests/json/write_spec_test.json
- Firestore/Source/Remote/FSTDatastore.h
- Firestore/Source/Remote/FSTDatastore.mm
- Firestore/Source/Remote/FSTRemoteStore.mm
This corresponds to a server-side change that will be released for the v1 protocol only (see b/119437764).
This is a port of firebase/firebase-js-sdk#1456.
> Treat ABORTED writes as retryable

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/API/FIRDocumentSnapshot.mm
- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/API/FIRFirestoreSettings.mm
- Firestore/Source/Public/FIRFirestoreSettings.h
- Firestore/Swift/Tests/API/BasicCompileTests.swift
The log message we used to log is removed and replaced by deprecating the setting.
> Change timestampsInSnapshots default to true and deprecate the setting.

- Example/Podfile
- Firebase/Core/FIROptions.m
- FirebaseAuth.podspec
- FirebaseCore.podspec
- FirebaseDatabase.podspec
- FirebaseDynamicLinks.podspec
- FirebaseFirestore.podspec
- FirebaseFunctions.podspec
- FirebaseMessaging.podspec
- FirebaseStorage.podspec
- Firestore/Example/Podfile
Note that 5.15.990 is a test only version of the Firebase pod temporarily deployed in https://github.com/firebase/SpecsStaging and intended to be used for development CI until 5.16.0 is public.
> Update FirebaseCore deps to 5.2

- Firestore/core/src/firebase/firestore/model/mutation.cc
- Firestore/core/src/firebase/firestore/model/mutation.h
- Firestore/core/test/firebase/firestore/model/mutation_test.cc
- Firestore/core/test/firebase/firestore/testutil/testutil.h
To enable completion of local serializer testing. Specifically ported:
SetMutation::ApplyToRemoteDocument()
PatchMutation::ApplyToRemoteDocument()
DeleteMutation::ApplyToLocalView()
> Port subset of Mutations

- Firestore/core/src/firebase/firestore/model/field_value.cc
- Firestore/core/src/firebase/firestore/model/field_value.h
- Firestore/core/test/firebase/firestore/model/field_value_test.cc
Replaced the following fields within the FieldValue union with (unique) pointers instead:
* object_value_ (48 bytes)
* server_timestamp_value_ (40)
* string_value_ (32)
* blob_value_ (24)
* reference_value_ (24)
* array_value_ (24)
* timestamp_value_ (16)
* geo_point_value_ (16)
sizeof(FieldValue): 56 -> 16 bytes.
> Reduce size of model::FieldValue

- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogStorage.h
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogStorage.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLRegistrar.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLUploadCoordinator.h
- GoogleDataLogger/GoogleDataLogger/Classes/GDLUploadCoordinator.m
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLLogStorage_Private.h
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLRegistrar_Private.h
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLLogTargets.h
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLLogUploader.h
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLRegistrar.h
- GoogleDataLogger/Tests/Unit/Categories/GDLLogStorage+Testing.m
- GoogleDataLogger/Tests/Unit/Categories/GDLRegistrar+Testing.m
- GoogleDataLogger/Tests/Unit/GDLLogStorageTest.m
- GoogleDataLogger/Tests/Unit/Helpers/GDLTestUploader.h
- Rename fields related to the previous notion of 'backends' to 'uploaders'.
- Add the ability to delete a set of logs by filename, and a conversion method for hashes to files.
- Change the log storage removeLogs method to be log hashes instead of URLs
- Style, and change the completion block to include an error
- Change to sync, since async to adding more async created race condition
- Test new storage methods
- Fix coordinator method declarations
> Enhance the log storage class

- scripts/if_changed.sh
- scripts/install_prereqs.sh
When travis moved from Xcode 10.0 to 10.1, we started getting the following flake in something around 10% of all subjobs.  
The first travis run passed without a substantial slowdown.  I'd like to try this for a week or so, and if it continues to work, follow up with fine tuning.
```
2019-01-03 16:42:24.097 xcodebuild[5587:18556] *** Assertion failure in ROCKRemoteProxy * _Nullable rock_XPCObjectToROCKRemoteProxy(xpc_object_t  _Nonnull __strong, ROCKSessionManager * _Nonnull __strong, NSError * _Nullable __autoreleasing * _Nullable)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/ROCKit/ROCKit-24/ROCKit/ROCKRemoteProxy+ROCK.m:97
** INTERNAL ERROR: Uncaught exception **
Uncaught Exception: Invalid parameter not satisfying: sessionManager
Stack:
Invalid connection: …
```
> Prevent prevalent Xcode 10.1 simulator flake

- scripts/build.sh
- scripts/install_prereqs.sh
Follow on to #2276. The `ROCKRemoteProxy` flake still occurred when resetting for travis job run.  Trying a reset for each xcodebuild now.
> Reset simulators before each xcodebuild

- Firestore/core/src/firebase/firestore/remote/CMakeLists.txt
- Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_generated.cc
For reasons of style compliance.
> Rename the generated byte array containing gRPC root certificates

- Firestore/core/test/firebase/firestore/remote/grpc_stream_test.cc
- Firestore/core/test/firebase/firestore/remote/grpc_streaming_reader_test.cc
- Firestore/core/test/firebase/firestore/remote/grpc_unary_call_test.cc
VS 2017 complains that enumeration members are not valid targets of a
using declaration outside class scope.
> Fix compilation under VS 2017

- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogWriter.h
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLLogStorage_Private.h
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLLogWriter_Private.h
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLLogger_Private.h
- GoogleDataLogger/GoogleDataLogger/Classes/Private/GDLRegistrar_Private.h
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLLogPrioritizer.h
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLLogProto.h
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLLogTransformer.h
- GoogleDataLogger/GoogleDataLogger/DependencyWrappers/GDLConsoleLogger.h
- GoogleDataLogger/Tests/Unit/GDLClockTest.m
- GoogleDataLogger/Tests/Unit/GDLLogWriterTest.m
- GoogleDataLogger/Tests/Unit/GDLRegistrarTest.m
- GoogleDataLogger/generate_project.sh
Add some nullability specifiers, remove a test that won't compile, change the pod gen script.
> Code cleanup

- Functions/Example/FirebaseFunctions.xcodeproj/project.pbxproj
- Functions/Example/Tests/FUNContextProviderTests.m
- Functions/FirebaseFunctions/FUNContext.h
- Functions/FirebaseFunctions/FUNContext.m
This was a regression from previous functionality, but is reverted
mostly to the old functionality. Previously `context` would be `nil` in
the completion handler if no Auth was available, but now `context` still
contains `instanceIDToken` but no `authToken`.
Also cover unit tests for the three states: no auth, auth error, and
valid auth.
This fixes #2292
> Allow Functions to be called without Auth.

- Firestore/Example/Tests/Local/FSTLevelDBMutationQueueTests.mm
- Firestore/Example/Tests/Local/FSTMemoryMutationQueueTests.mm
- Firestore/Example/Tests/Local/FSTMutationQueueTests.h
- Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
- Firestore/Source/Local/FSTLevelDBMutationQueue.h
- Firestore/Source/Local/FSTLevelDBMutationQueue.mm
- Firestore/Source/Local/FSTMemoryMutationQueue.mm
- Firestore/Source/Local/FSTMutationQueue.h
- Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.h
- Firestore/core/src/firebase/firestore/local/memory_mutation_queue.h
- Firestore/core/src/firebase/firestore/local/mutation_queue.h
Adds the `MutationQueue` interface, a port of `FSTMutationQueue`. Ports the mutation queue tests to use the C++ interface. Does not port production usages of `FSTMutationQueue`, that will be in the next PR.
> Add MutationQueue interface

- Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
This is a port of the test from https://github.com/firebase/firebase-android-sdk/pull/215. Thankfully, no special handling is required here.
> Verify large write batches support

- Firestore/CHANGELOG.md
Spooling through history there's lots of porting work here but nothing interesting to a changelog consumer.
> Update CHANGELOG for Firestore v1.0.1

- Firebase/InAppMessaging/Analytics/FIRIAMAnalyticsEventLoggerImpl.h
- Firebase/InAppMessaging/Analytics/FIRIAMAnalyticsEventLoggerImpl.m
- Firebase/InAppMessaging/Runtime/FIRIAMRuntimeManager.m
- Firebase/InAppMessaging/Runtime/FIRIAMSDKSettings.h
- Firebase/InAppMessaging/Runtime/FIRIAMSDKSettings.m
- Firebase/InAppMessaging/Runtime/FIRInAppMessaging+Bootstrap.m
- InAppMessaging/Example/Tests/FIRIAMAnalyticsEventLoggerImplTests.m
- Interop/Analytics/Public/FIRAnalyticsInterop.h
See discussion in cl/230837222.
Previously we had logic to expire the `lastNotification` event after a certain period of time, to invalidate the last notification for conversion tracking purposes.
This PR removes that logic to be consistent with the Android SDK.
> Remove logic to expire last notification analytics settings after a set time interval

- Example/tvOSSample/tvOSSample/StorageViewController.swift
- scripts/style.sh
I'm not really proud of this PR, but it allows my swiftformat 0.38 to work, and should be forward-looking enough to not need to be changed again next week. :-)
> Add more flexible swiftformat version check to scripts/style.sh.

- Firebase/InAppMessaging/Data/FIRIAMFetchResponseParser.h
- InAppMessaging/Example/App/InAppMessaging-Example-iOS/AppDelegate.m
- InAppMessaging/Example/Podfile
- scripts/build.sh
- scripts/install_prereqs.sh
Adds headless In App Messaging build and unit testing to Travis CI.
A follow up PR will add `pod lib lint` testing once the SpecsStaging repo gets set up with its new dependencies.
> Add IAM headless to CI

- Example/DynamicLinks/Tests/FIRDLScionLoggingTest.m
- Example/Messaging/Tests/FIRMessagingAnalyticsTest.m
- FirebaseAnalyticsInterop.podspec
And fix FakeAnalytics test build warnings
Will retarget to master once #2312 merges
> Bump FirebaseAnalyticsInterop version 

- Carthage.md
We referred to this updated text in the [release notes](https://firebase.google.com/support/release-notes/ios#5.16.0) but then failed to actually update them (AFAICS).
> Update gRPC certificate bundles locations for Firebase 5.16

- GoogleDataLogger.podspec
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogEvent.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogStorage.h
- GoogleDataLogger/GoogleDataLogger/Classes/GDLLogStorage.m
- GoogleDataLogger/GoogleDataLogger/Classes/GDLUploadCoordinator.m
- GoogleDataLogger/GoogleDataLogger/Classes/Public/GDLLogProto.h
- GoogleDataLogger/GoogleDataLogger/DependencyWrappers/GDLConsoleLogger.h
- GoogleDataLogger/Tests/Integration/GDLIntegrationTest.m
- GoogleDataLogger/Tests/Integration/Helpers/GDLIntegrationTestPrioritizer.h
- GoogleDataLogger/Tests/Integration/Helpers/GDLIntegrationTestPrioritizer.m
- GoogleDataLogger/Tests/Integration/Helpers/GDLIntegrationTestUploader.h
- GoogleDataLogger/Tests/Integration/Helpers/GDLIntegrationTestUploader.m
- GoogleDataLogger/Tests/Integration/TestServer/GDLTestServer.h
- GoogleDataLogger/Tests/Integration/TestServer/GDLTestServer.m
- GoogleDataLogger/Tests/Unit/GDLLogStorageTest.m
- GoogleDataLogger/Tests/Unit/GDLUploadCoordinatorTest.m
- GoogleDataLogger/Tests/Unit/Helpers/GDLLogExtensionTesterClasses.m
- scripts/build.sh
- Move the -removeLog API to be file-private, it's unused publicly.
- Remove altering of in flight log set, that's done in the onComplete block callback
- Copy the set of logs given to upload so it's not altered while the pipeline is operating on it
- Rename -protoBytes to -transportBytes
> Implement an integration/E2E test of the logging pipeline

- Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.h
- Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.m
- Firebase/InAppMessaging/Public/FIRInAppMessaging.h
- Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h
- Firebase/InAppMessaging/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m
- Firebase/InAppMessaging/Runtime/FIRIAMRuntimeManager.m
- Firebase/InAppMessagingDisplay/Banner/FIDBannerViewController.m
- Firebase/InAppMessagingDisplay/FIDBaseRenderingViewController.h
- Firebase/InAppMessagingDisplay/FIDBaseRenderingViewController.m
- Firebase/InAppMessagingDisplay/FIRIAMDefaultDisplayImpl.m
- Firebase/InAppMessagingDisplay/ImageOnly/FIDImageOnlyViewController.m
- Firebase/InAppMessagingDisplay/Modal/FIDModalViewController.m
- Firebase/InAppMessagingDisplay/Public/FIRIAMDefaultDisplayImpl.h
- Firestore/Swift/Source/Codable/CodableGeoPoint.swift
- InAppMessaging/Example/Tests/FIRIAMDisplayExecutorTests.m
- InAppMessagingDisplay/Example/FiamDisplaySwiftExample/BannerMessageViewController.swift
- InAppMessagingDisplay/Example/FiamDisplaySwiftExample/CommonMessageTestVC.swift
- InAppMessagingDisplay/Example/FiamDisplaySwiftExample/ImageOnlyMessageViewController.swift
- InAppMessagingDisplay/Example/FiamDisplaySwiftExample/ModalMessageViewController.swift
- InAppMessagingDisplay/Example/Podfile
Adds functionality for apps to receive message lifecycle callbacks by registering a delegate that implements a fleshed out `FIRInAppMessagingDisplayDelegate`:
```
// Swift
InAppMessaging.inAppMessaging().delegate = self
```
```
// Objective-C
[FIRInAppMessaging inAppMessaging].delegate = self;
```
Fleshed out `FIRInAppMessagingDisplayDelegate` is now:
`- (void)messageClicked:(FIRInAppMessagingDisplayMessage *)inAppMessage`
`- (void)messageDismissed:(FIRInAppMessagingDisplayMessage *)inAppMessage dismissType:(FIRInAppMessagingDismissType)dismissType`
`- (void)impressionDetectedForMessage:(FIRInAppMessagingDisplayMessage *)inAppMessage`
`- (void)displayErrorForMessage:(FIRInAppMessagingDisplayMessage *)inAppMessage error:(NSError *)error`
TODO: Add unit tests to ensure delegate callbacks …
> Firebase In-app messaging callbacks

- Firebase/InAppMessagingDisplay/Banner/FIDBannerViewController.m
- Firebase/InAppMessagingDisplay/FIDBaseRenderingViewController.h
- Firebase/InAppMessagingDisplay/FIDBaseRenderingViewController.m
- Firebase/InAppMessagingDisplay/ImageOnly/FIDImageOnlyViewController.m
- Firebase/InAppMessagingDisplay/Modal/FIDModalViewController.m
Fix imports to potentially address Travis CI issues.
- Remove duplicate imports of `FIRInAppMessagingRendering.h`
- Use global import of `FIRInAppMessagingRendering.h`
> Fix FIAM Travic CI issues

- Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
- Firestore/Source/API/FIRQuery.mm
Without this, it still fails, but:
a) not until serializing the query, and
b) the error is an internal error, and
c) the error message is quite cryptic and has nothing to do with the problem.
Port of https://github.com/firebase/firebase-android-sdk/pull/138
> Forbid queries endAt an uncommitted server timestamp.

- Firebase/Core/Public/FIRAnalyticsConfiguration.h
Deprecate FIRAnalyticsConfiguration setMinimumSessionInterval due to sessions being started immediately. 
This is being sent early for review, but will not be merged until the feature is rolled out.
> Deprecate setMinimumSessionInterval

- Example/Auth/ApiTests/FirebaseAuthApiTests.m
- Example/Auth/Tests/FIRAuthLifeCycleTests.m
- Example/Auth/Tests/FIRAuthTests.m
- Example/Firebase.xcodeproj/project.pbxproj
Auth unit test case is too large and hard to manage, gonna split it into multiple cases.
> Split Auth unit tests

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Model/FSTFieldValueTests.mm
- Firestore/Source/API/FIRQuery.mm
- Firestore/Source/API/FSTUserDataConverter.mm
- Firestore/Source/Core/FSTView.mm
- Firestore/Source/Core/FSTViewSnapshot.mm
- Firestore/Source/Model/FSTDocument.mm
- Firestore/Source/Remote/FSTSerializerBeta.mm
- Firestore/core/src/firebase/firestore/immutable/sorted_map.h
- Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.mm
- Firestore/core/src/firebase/firestore/model/document_key.h
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/string_format.h
- Firestore/core/src/firebase/firestore/util/string_util.h
- Firestore/core/src/firebase/firestore/util/to_string.h
- Firestore/core/src/firebase/firestore/util/type_traits.h
- Firestore/core/test/firebase/firestore/util/to_string_apple_test.mm
- Firestore/core/test/firebase/firestore/util/to_string_test.cc
- Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm
The motivation is to avoid writing lots of boilerplate for containers.
> Add a ToString function to create human-readable debug descriptions

- Example/Firebase.xcodeproj/project.pbxproj
- Example/Messaging/Tests/FIRInstanceIDWithFCMTest.m
Restore FIRInstanceIDWithFCMTest.m
Add mocking since Messaging singleton no longer available
The test is now part of the Messaging tests instead of the InstanceID tests since Messaging depends on InstanceID.
> Restore FIRInstanceIDWithFCMTest.m

- GoogleUtilities/Logger/GULLogger.m
- GoogleUtilities/Logger/Private/GULOSLogger.m
- scripts/if_changed.sh
Imports for #2431 
Sorry for the double PR's. I'm trying to avoid installing Xcode 8.
> Fix GoogleUtilities regression for Firestore builds 2

- Example/InstanceID/Tests/FIRInstanceIDTest.m
- Example/Messaging/Tests/FIRInstanceIDWithFCMTest.m
- Firebase/InstanceID/FIRInstanceID.m
The singleton is cached and vended from the Core component system, we
shouldn't wrap it in a dispatch_async or cache it with a global variable.
This matches a change internally that has been made and shipped.
> Fix IID singleton usage.

- Example/Messaging/Tests/FIRMessagingTestUtilities.m
- Firebase/Messaging/FIRMessaging.m
- Firebase/Messaging/FIRMessagingPubSub.m
- Firebase/Messaging/FIRMessagingReceiver.h
- Firebase/Messaging/FIRMessagingReceiver.m
- FirebaseMessaging.podspec
This is a fix for #1919:
* `NSUserDefaults` replaced by `GULUserDefaults` in `FirebaseMessaging`
> FirebaseMessaging: `NSUserDefaults` replaced by `GULUserDefaults`

- scripts/build.sh
We don't need to use Xcode's index-while-compiling during builds. Folks have
seen ~8% speedup with builds here.
Seen at https://twitter.com/steipete/status/1100404024224804871
> Disable index-while-compiling in Travis

- GoogleUtilities/Logger/GULASLLogger.m
This should fix the current travis failure and remove the warning.
Although Apple's docs suggest using `asl_release`, it's only available on iOS 8 and above. `asl_free` does the same thing as `asl_release` and since this will be going away eventually, this is fine to deviate from Apple's recommendations this time.
> Fix logger warning on iOS 7.

- Example/Auth/Tests/FIRAuthAppDelegateProxyTests.m
- Example/Firebase.xcodeproj/xcshareddata/xcschemes/AllUnitTests_iOS.xcscheme
A step toward #793:
- collecting of code coverage enabled for target AllUnitTests_iOS target. The collected data will be used to generate a human readable report
- issue with `FIRAuthAppDelegateProxyTests` fixed
A related PR: #2400
This is a fixed version of #2449
> Enable code coverage for AllUnitTests_iOS target

- GoogleUtilities/Example/Tests/Logger/GULASLLoggerTest.m
- GoogleUtilities/Example/Tests/Logger/GULOSLoggerTest.m
- GoogleUtilities/Logger/GULASLLogger.m
- GoogleUtilities/Logger/GULOSLogger.m
* Use `-[NSString initWithFormat:arguments:]` instead of trying to trick the preprocessor macros of all the platforms.
* A couple drive-by warning fixes that `-Weverything` surfaced.
These changes match the ones done internally.
> Resolve issue with char * casting in format string invocation

- Firestore/core/src/firebase/firestore/util/warnings.h
My previous fix to the linux/gcc build was incomplete. -Wdocumentation
is a clang-only flag, so therefore can't be suppressed under gcc.
> Fix build with gcc

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Local/FSTRemoteDocumentCacheTests.mm
- Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.mm
Ports an optimization from Android where we skip parsing documents that are in
subcollections beneath the collection we're querying over.
This should help #2466 at least to a degree.
> Improved query performance in the face of subcollections.

- GoogleUtilities.podspec
- Releases/Manifests/5.18.0.json
This was originally staged for release in 5.18.0 but was pulled out. The podspec was never pushed, so it shouldn't be included in the merge to master.
> Revert GoogleUtilities version bump.

- .travis.yml
As of this month, Apple requires Xcode 10.1 for submissions to the app store
> Stop Xcode 9 testing

- FirebaseInstanceID.podspec
The code was unintentionally released as closed source again, this
is only to push a new version to CocoaPods with the proper podspec.
> Bump the patch version of FirebaseInstanceID.

- Firebase/Database/CHANGELOG.md
- Firebase/Database/third_party/SocketRocket/FSRWebSocket.m
Fix #2485
The _sendFrameWithOpcode function in FSRWebSocket assert for nil at the top but then fails to test it earlier. The [upstream SocketRocket code includes a nil check](https://github.com/facebook/SocketRocket/blame/master/SocketRocket/SRWebSocket.m#L1338).
This PR adds it.
> Add missing nil check

- Firebase/Core/FIRLogger.m
- GoogleUtilities/Example/Tests/Logger/GULOSLoggerTest.m
- GoogleUtilities/Logger/GULASLLogger.m
- GoogleUtilities/Logger/GULLogger.m
- GoogleUtilities/Logger/GULOSLogger.m
- GoogleUtilities/Logger/Private/GULLogger.h
- GoogleUtilities/Logger/Private/GULLoggerSystem.h
Restore GULLogger to the same API that it has used with Firebase 5.x
Fix the regression that messages were not being logged (only the rest of info in log line)
Remove brackets around service names since os_log adds them anyways.
> Restore GULLogger APIs, unit tests, and contents

- GoogleUtilities/Example/Tests/Swizzler/GULRuntimeClassSnapshotTests.m
Delete test with `new`.
This causes build issues in internal system.
Checking for init happens at build time, not runtime.
> Delete test with new

- Example/InstanceID/Tests/FIRInstanceIDCheckinServiceTest.m
- Firebase/InstanceID/FIRInstanceIDCheckinService.h
- Firebase/InstanceID/FIRInstanceIDCheckinService.m
- Send Firebase info in the request header (directly from FIRInstanceIDCheckinService)
This is a replacement for #2500 to address the [comment](https://github.com/firebase/firebase-ios-sdk/pull/2500#discussion_r263894556)
> Add Firebase info to checkin requests (directly from FIRInstanceIDCheckinService) - b/124533860

- Firestore/core/src/firebase/firestore/nanopb/nanopb_string.cc
- Firestore/core/src/firebase/firestore/nanopb/nanopb_string.h
Rather than delete, which technically results in undefined behaviour.
> Use free() for memory allocated with malloc.

- Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
- Firestore/Example/Tests/API/FSTAPIHelpers.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
- Firestore/Source/API/FIRCollectionReference.mm
- Firestore/Source/API/FIRDocumentChange+Internal.h
- Firestore/Source/API/FIRDocumentChange.mm
- Firestore/Source/API/FIRDocumentReference+Internal.h
- Firestore/Source/API/FIRDocumentReference.mm
- Firestore/Source/API/FIRDocumentSnapshot+Internal.h
- Firestore/Source/API/FIRDocumentSnapshot.mm
- Firestore/Source/API/FIRFirestore+Internal.h
- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/API/FIRQuerySnapshot.mm
- Firestore/Source/API/FIRTransaction.mm
- Firestore/Source/API/FSTFirestoreComponent.mm
- Firestore/core/src/firebase/firestore/api/firestore.h
- Firestore/core/src/firebase/firestore/api/firestore.mm
This change includes a number of proposed fixes for #2492:
* Get rid of factory methods duplicating initializers in affected types
* Have `api::Firestore` store a `void*` extension to avoid needing to pass and store extra `FIRFirestore *` references everywhere
* Add `+[FIRFirestore recoverFromFirestore:]` to help deal with the extension
* Fixes a few errors in where category methods are defined
I'm filing this in the form of a PR to avoid prompting you to do this and it not being feasible. Feedback welcome, but by the time I proved this approach could work I was in a mostly done state.
> Feedback for #2492 in the form of a PR

- Firebase/InAppMessagingDisplay/FIDRenderingWindowHelper.m
Fix for the crash in #2498. 
Also tested this in iOS split view, where I thought this might not work-- but it does.
> Instead of using UIApplicationDelegate's window property (optional) to size the UIWindow for in-app messages, use UIScreen bounds

- GoogleUtilities/Logger/GULASLLogger.m
- GoogleUtilities/Logger/GULLogger.m
- GoogleUtilities/Logger/GULOSLogger.m
This fixes an internal error (b/128359839) that causes tests to crash.
> Only assign message validation regex once

- Firestore/core/src/firebase/firestore/model/transform_operations.h
Only seems to impact the mac cmake build (not the xcode build). Linux
build is unaffected since there's an ifdef objc at the top of the file.
> Fix build (unused parameter) under mac/cmake/clang

- Firebase/Auth/Source/RPCs/FIRAuthBackend.m
> Don't create credential when VerifyAssertionResponse is empty

- Firebase/Auth/CHANGELOG.md
- Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Fix #2522.
in case of returnIDPCredential=YES, instead of an error like the following:
```
[response data:] {
"error": {
"code": 400,
"message": "FEDERATED_USER_ID_ALREADY_LINKED",
"errors": [
{
"message": "FEDERATED_USER_ID_ALREADY_LINKED",
"domain": "global",
"reason": "invalid"
}
]
}
}
```
the error message is directly enclosed in the response without a structure:
```
[response data:] {
key: value
...
"errorMessage": "FEDERATED_USER_ID_ALREADY_LINKED",
"kind": "identitytoolkit#VerifyAssertionResponse"
}
```
> extract errorMessage directly from response when server returns 200

- Example/InstanceID/Tests/FIRInstanceIDCheckinServiceTest.m
- Firebase/InstanceID/FIRIMessageCode.h
- Firebase/InstanceID/FIRInstanceIDCheckinService.m
A quick fix for the issue #2534.
- make sure tasks are not submitted to an invalidated NSURLSession
- log an error in case when this may have happened
Looks like there is a race condition involving `FIRInstanceID`/`FIRInstanceIDTokenManager`/`FIRInstanceIDAuthService`/`FIRInstanceIDCheckinService`. I was not able to find a core reason why the issue may happen so far.
The PR just fixes the particular consequence of the race condition to mitigate the impact on users while we are looking for a better solution.
> FIRInstanceIDCheckinService: make sure tasks are not submitted to an invalidated NSURLSession

- Example/InstanceID/Tests/FIRInstanceIDAuthKeyChainTest.m
- Example/InstanceID/Tests/FIRInstanceIDBackupExcludedPlistTest.m
- Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
- Example/InstanceID/Tests/FIRInstanceIDStoreTest.m
- Example/InstanceID/Tests/FIRInstanceIDTokenManagerTest.m
- Firebase/InstanceID/FIRInstanceID.m
- Firebase/InstanceID/FIRInstanceIDBackupExcludedPlist.m
- Firebase/Messaging/FIRMessaging.m
This fix #2544. Also remove a method in FIRMessaging.m that is never called.
> Rename ApplicationSupportDirectory in IID tests

- ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
- ZipBuilder/Sources/ZipBuilder/ShellUtils.swift
- ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
This prevents errors from occurring, and will also ensure that the
most recent version will be included if it was rebuilt.
Also fixes an issue where `pod repo update` wouldn't work with `sso` repos.
> Clean the pod cache before starting.

- Example/Core/Tests/FIRAppTest.m
- Firebase/Core/FIRApp.m
- Use NSScanner instead of NSRegularExpression to validate App ID
> Avoid using  NSRegularExpression in FIRApp (b/65122393)

- .travis.yml
- scripts/check.sh
It's hard to run all checks locally despite the fact that they can typically run very quickly.
Add a script that does everything travis does interactively, and optionally fixes things that can be fixed automatically.
> Add a run-all-checks script

- .travis.yml
- scripts/pod_lib_lint.sh
CocoaPods/CocoaPods#7783 added support for restricting pod lib lint to a limited set of platforms. This shipped with 1.6.0 and we're now up to 1.6.1.
Use this to cut the build time for `pod lib lint FirebaseFirestore.podspec` in individual PRs in half.
> Travis: when linting Firestore, only lint iOS 

- Example/Auth/ApiTests/FacebookAuthTests.m
The Facebook tests are still failing. 
see https://travis-ci.org/firebase/firebase-ios-sdk/jobs/507027358
This reverts commit 2ae939b6ebf6329984695c71514d28d475f62014.
> Revert "Revert "Disable Facebook API tests (#2547)" (#2566)"

- Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
- Firestore/Source/Core/FSTFirestoreClient.mm
- Firestore/Source/Local/FSTLRUGarbageCollector.h
- Firestore/Source/Local/FSTLRUGarbageCollector.mm
- Firestore/Source/Local/FSTLevelDB.mm
- Firestore/Source/Local/FSTMemoryPersistence.mm
- Firestore/Source/Model/FSTDocument.h
- Firestore/Source/Model/FSTDocument.mm
- Firestore/core/src/firebase/firestore/local/CMakeLists.txt
- Firestore/core/src/firebase/firestore/local/leveldb_query_cache.h
- Firestore/core/src/firebase/firestore/local/leveldb_query_cache.mm
- Firestore/core/src/firebase/firestore/local/memory_query_cache.h
- Firestore/core/src/firebase/firestore/local/memory_query_cache.mm
- Firestore/core/src/firebase/firestore/local/query_cache.h
- Firestore/core/src/firebase/firestore/util/CMakeLists.txt
- Firestore/core/src/firebase/firestore/util/objc_compatibility.h
- Firestore/core/test/firebase/firestore/util/objc_compatibility_apple_test.mm
- cmake/cc_rules.cmake
This contains a smattering of fixes required to make this happen, initially prompted by the `static_cast<bool>` to convert from `BOOL` to `bool` in FSTFirestoreClient.
Most notably:
* This includes `objc::EqualTo` and `objc::Hash` functors that make it possible to use `std::unordered_map` with Objective-C key types
* Uses these in MemoryQueryCache
* Changes enumeration interfaces to `std::function` instead of Objective-C block style.
> Eliminate Objective-C BOOL in Firestore/core
