- Firebase.podspec
- FirebaseAnalytics.podspec.json
- GoogleAppMeasurement.podspec.json
> [Analytics] Bump Analytics minimum iOS version to `10.0`

- .github/workflows/zip.yml
This is to fix 
https://github.com/firebase/firebase-ios-sdk/runs/5867959723?check_suite_focus=true#step:7:600
The Quickstart can be built without FirebaseCore, which does not need to be added explicitly.
> Add FirebaseCoreInternal for Firebase 9

- FirebaseFunctions/CHANGELOG.md
- FirebaseStorage/CHANGELOG.md
Fix #9487 
The API proposal is approved. Internally, see go/storage-function-error-variable-deprecations
`StorageErrorDomain` still needs to be added.
> Functions/Storage 9.0.0 release notes updates

- FirebaseStorageInternal.podspec
Close #8750 
- Objective C podspecs should continue to use relative paths for Interop deps to be compatible with SPM
- Swift implemented pods should use the interop pod dependencies
- Only Analytics (no open implementation) and CoreDiagnostics (going away soon) remain in the Interop directory.
> ObjC should use continue to use paths for Interop deps

- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
The zip distro SHOULD include the interop libraries since the libraries built with Swift depend on them.
I've confirmed that the StorageSwiftExample test successfully builds when the Interop libs are linked in (After removing teh `import FirebaseStorageSwift` from the sources.
#no-changelog
> Interop libs should be included in the zip

- Firestore/core/src/remote/datastore.cc
- Firestore/core/src/remote/datastore.h
- Firestore/core/src/remote/grpc_streaming_reader.cc
- Firestore/core/src/remote/grpc_streaming_reader.h
- Firestore/core/test/unit/remote/datastore_test.cc
- Firestore/core/test/unit/remote/grpc_connection_test.cc
- Firestore/core/test/unit/remote/grpc_streaming_reader_test.cc
#no-changelog
For BatchGetDocuments, since the SDK knows the number of document paths in the requests, as soon as the SDK receives all the responses needed, it will fire user callback to save user's waiting time.
> SDK support for logical termination in Firestore BatchGetDocuments

- FirebaseCore/Sources/FIRApp.m
- FirebaseCore/Tests/Unit/FIRAppTest.m
Because of the fact that the `appDidBecomeActive` notification comes after the time when a Firebase app should be configured, it's reasonable to _only_ log a heartbeat upon the `appDidBecomeActive` notification.
#no-changelog
> [HeartbeatLogging] Remove heartbeat trigger for when app is configured

- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h
- FirebaseAuth/Tests/Sample/SwiftApiTests/SwiftAPI.swift
> Fix import bug

- FirebaseAppDistribution.podspec
- FirebaseAppDistribution/CHANGELOG.md
- FirebaseAppDistribution/Sources/FIRAppDistribution.m
- FirebaseAppDistribution/Sources/Public/FirebaseAppDistribution/FIRAppDistribution.h
- FirebaseAppDistribution/Tests/Unit/Swift/AppDistributionAPITest.swift
- Package.swift
Right now we're calling a completion handler with `nil, nil` when
releases are fetched but none are marked as "latest". This is an expected result - no new releases but no errors. When translated to async/await, the result is not an optional, which will crash. This turns the return type into an Optional.
> App Distro: fix async/await issue

- scripts/xcresult_logs.py
This PR fixes the following `UnicodeDecodeError` that sometimes happens in GitHub actions:
```
Traceback (most recent call last):
File "scripts/xcresult_logs.py", line 300, in <module>
main()
File "scripts/xcresult_logs.py", line 67, in main
sys.stdout.write(log)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 421: ordinal not in range(128)
```
e.g. https://github.com/firebase/firebase-ios-sdk/runs/6000587971
#no-changelog
> xcresult_logs.py: Fix potential UnicodeEncodeError

- FirebaseStorage/Sources/StorageMetadata.swift
- FirebaseStorage/Tests/Integration/StorageAsyncAwait.swift
- FirebaseStorage/Tests/Integration/StorageIntegration.swift
- FirebaseStorageInternal/Sources/FIRStorageConstants.m
- FirebaseStorageInternal/Sources/FIRStorageConstants_Private.h
- FirebaseStorageInternal/Sources/FIRStorageMetadata.m
- FirebaseStorageInternal/Sources/Public/FirebaseStorageInternal/FIRStorageMetadata.h
- FirebaseStorageInternal/Tests/Integration/FIRStorageIntegrationTests.m
- FirebaseStorageInternal/Tests/Unit/FIRStorageMetadataTests.m
> Adding Custom-Time to Firebase Storage

- .github/workflows/functions.yml
- CoreOnly/Sources/Firebase.h
- CoreOnly/Tests/FirebasePodTest/FirebasePodTest/AppDelegate.swift
- FirebaseCore/CHANGELOG.md
- FirebaseFunctions.podspec
- FirebaseFunctions/Tests/ObjCIntegration/ObjCPPAPITests.mm
- FirebaseStorage.podspec
- FirebaseStorage/Tests/ObjCIntegration/ObjCAPITests.m
- FirebaseStorage/Tests/ObjCIntegration/ObjCPPAPITests.mm
- Package.swift
- scripts/check_imports.swift
- Fix ObjC++ Firebase.h regression
- Copy and adapt Storage and Functions ObjC API tests for Objective C++
- Several Firebase 9 release notes updates
> Update C++/Obj C++ support for Firebase 9

- FirebaseStorage/Sources/StorageMetadata.swift
- FirebaseStorage/Tests/Integration/StorageAsyncAwait.swift
- FirebaseStorage/Tests/Integration/StorageIntegration.swift
- FirebaseStorageInternal/Sources/FIRStorageConstants.m
- FirebaseStorageInternal/Sources/FIRStorageConstants_Private.h
- FirebaseStorageInternal/Sources/FIRStorageMetadata.m
- FirebaseStorageInternal/Sources/Public/FirebaseStorageInternal/FIRStorageMetadata.h
- FirebaseStorageInternal/Tests/Integration/FIRStorageIntegrationTests.m
- FirebaseStorageInternal/Tests/Unit/FIRStorageMetadataTests.m
#9576 breaks the integration and it looks like the backend does not write customTime into the metadata. Perhaps, because it's missing in `FirebaseStorageContextImpl.java`?
Also, https://cloud.google.com/storage/docs/metadata#custom-time says "You cannot remove Custom-Time once it's been set on an object", so should it be a read-only field?
> Revert "Adding Custom Time to FirebaseStorage (#9576)"

- Firestore/CMakeLists.txt
- Firestore/Example/CMakeLists.txt
- Firestore/Source/CMakeLists.txt
If this new `FIRESTORE_INCLUDE_OBJC` cmake cache variable is set to a false value (e.g. "NO", "OFF") then the `Source` and `Example` subdirectories of Firestore will not be compiled. The default value is true.
This new cmake cache variable will be used by the firebase-cpp-sdk repository to avoid unnecessarily compiling the objective-c sources that it does not use. The immediate motivation is to work around the following compilation error in firebase-cpp-sdk:
```
FIRFirestore.h:147:20: error: unknown attribute 'swift_async' ignored [-Werror,-Wunknown-attributes]
__attribute__((swift_async(none)));  // Disable async import due to #9426.
^
1 error generated.
```
e.g. https://github.com/firebase/firebase-cpp-sdk/runs/6033445422
This problematic usage of `swift_async` was added in …
> Add FIRESTORE_INCLUDE_OBJC cmake cache variable

- Firestore/Protos/CMakeLists.txt
- Firestore/core/CMakeLists.txt
- cmake/external/CMakeLists.txt
- cmake/python_setup.cmake
During cmake builds, instead of using the python interpreter installed locally, use that python interpreter to create a virtualenv for each python script run by cmake. Each virtualenv can then have its own isolated dependencies installed. This removes the dependence on having the correct python libraries installed locally. All you need is a vanilla python 3 interpreter. This also helps fix some unusual python dependency issues when this repository is incorporated into the firebase-cpp-sdk.
Here is an example of the build error in the C++ SDK that this fixes (https://github.com/firebase/firebase-cpp-sdk/runs/6065960193):
```
[ 83%] Generating nanopb sources
google/firestore/v1/document.proto:20:1: warning: Import google/api/annotations.proto is unused.
google/firestore/v1/query.proto:20:1: …
```
> Create individual Python virtualenv's in cmake builds

- FirebaseFunctions/CHANGELOG.md
- FirebaseFunctions/Sources/Functions.swift
- FirebaseFunctions/Sources/HTTPSCallable.swift
- FirebaseFunctions/Tests/Integration/IntegrationTests.swift
- FirebaseFunctions/Tests/ObjCIntegration/ObjCAPITests.m
- FirebaseFunctions/Tests/ObjCIntegration/ObjCPPAPITests.mm
- FirebaseFunctions/Tests/Unit/FunctionsAPITests.swift
Sorry for a late-coming urgent change; AFAICT nobody on the SDK team could staff these changes, so I'm trying to write the change for the top 3 SDKs before I/O freeze.
For context, see [go/cf3v2-crash-landing](http://go/cf3v2-crash-landing).
For API approval, see [go/callable-functions-custom-urls](http://go/callable-functions-custom-urls)
> Add callableWithURL

- FirebaseDatabase/CHANGELOG.md
- FirebaseDatabase/Sources/Api/FIRDatabaseQuery.m
- FirebaseDatabase/Sources/Core/FRepo.m
- FirebaseDatabase/Sources/FIRDatabaseReference.m
- FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDatabaseQuery.h
- FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDatabaseReference.h
- FirebaseDatabase/Tests/Unit/Swift/DatabaseAPITests.swift
Fixes https://github.com/firebase/firebase-ios-sdk/issues/9614
> Make getDataWithCompletionBlock snapshot nullable

- FirebaseFunctions/Sources/Functions.swift
- FirebaseFunctions/Tests/Integration/IntegrationTests.swift
- FirebaseFunctions/Tests/Unit/FunctionsAPITests.swift
> Remove url label. add Codable test

- FirebaseAuth.podspec
- FirebaseFunctions.podspec
- FirebaseStorageInternal.podspec
- Package.swift
`GTMSessionFetcher` was the only dependency that had a pinned minor version that needed updating.
All were updated: 
```console
➜  firebase-ios-sdk git:(nc/dependencies-v9) 
‣ git --no-pager grep "dependency 'GTMSessionFetcher"                                                                                                                                                                                                 (233ms) 
FirebaseAuth.podspec:  s.dependency 'GTMSessionFetcher/Core', '~> 1.7'
FirebaseFunctions.podspec:  s.dependency 'GTMSessionFetcher/Core', '~> 1.7'
FirebaseStorageInternal.podspec:  s.dependency 'GTMSessionFetcher/Core', '~> 1.7'
```
> [v9] Update pinned minor version of `GTMSessionFetcher` dependencies

- FirebaseSharedSwift/CHANGELOG.md
Following offline discussion, it was decided that FirebaseSharedSwift should not have had `-beta` tagging in it's CHANGELOG.
> [v9] Update  `FirebaseSharedSwift/CHANGELOG.md` for v9

- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatController.swift
- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatStorage.swift
- FirebaseCore/Internal/Sources/HeartbeatLogging/StorageFactory.swift
- FirebaseCore/Internal/Tests/Integration/HeartbeatLoggingIntegrationTests.swift
- The name of an app's heartbeats storage file includes the Firebase app ID. Since the Firebase app ID includes the ":" character, the filename also contains a ":". 
This works on Apple's latest filesystem but it's safer to replace each ":" with a "_"
- In practice, this code change will cause the below diff in an app's container:
```diff
📂 Application Support/
└── 📂 google-heartbeat-storage/
-    └── 📄 heartbeats-1:123456789000:ios:abcdefghijklmnop
+    └── 📄 heartbeats-1_123456789000_ios_abcdefghijklmnop
```
- Also, resolved outstanding `TODO`s in FirebaseCoreInternal.
#no-changelog
> [FirebaseCoreInternal] Sanitize app ID used in file system resource

- FirebaseAppCheck.podspec
- FirebaseCrashlytics.podspec
- FirebaseInstallations.podspec
- FirebaseMLModelDownloader.podspec
- Follow-up to #9677
- Bumped `PromisesObjC` to 2.**1**
- Bumped `SwiftProtobuf` to 1.**19**
1. Get the latest `zip` build and inspect its versioned dependency chart in the README
2. `cd` to `firebase-ios-sdk` and grep for each dependency:
```console
git grep 'DEPENDENCY' *.podspec *.podspec.json  
``` 
3. If there is a spec dependency that needs bumping: 
Examples for `PromisesObjC` bumping from `2.0` to `2.1`:
```console
grep -rl "'PromisesObjC', '~> 2.0'" *.podspec | xargs sed -i "" "s/'PromisesObjC', '~> 2.0'/'PromisesObjC', '~> 2.1'/g"
```
#no-changelog
> [v9] Update pinned minor versions for podspecs

- FirebaseDatabase.podspec
- FirebaseDatabase/Tests/Helpers/FTestBase.m
Reenable RTDB integration tests with a real GoogleService-Info.plist that were broken in #6557.
See the added comment for run instructions.
There are still 9 failures because of a race condition:
> Make RTDB integration tests runnable on a real target

- Firestore/CHANGELOG.md
- Firestore/Example/GoogleTest.podspec
- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
- Firestore/core/src/credentials/user.h
- cmake/external/googletest.cmake
Clang started failing with errors that it previously ignored upon upgrading Xcode to 13.3.1. This PR fixes those build errors.
Here are some of the build errors that this PR addresses:
```
Firestore/core/src/credentials/user.h:73:9: error: definition of implicit copy constructor for 'User' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
User& operator=(const User& other) = default;
```
```
gmock/gmock-actions.h:455:3: error: definition of implicit copy constructor for 'PolymorphicAction<testing::
internal::ReturnNullAction>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
GTEST_DISALLOW_ASSIGN_(PolymorphicAction);
```
```
Firestore/Example/Tests/Integration/FSTTransactionTests.mm:541:30: …
```
> Fix build errors in Xcode 13.3.1

- cmake/external/googletest.cmake
In https://github.com/firebase/firebase-ios-sdk/pull/9705, the googletest dependency was changed from downloading a release version to cloning the git repository at a pinned commit from HEAD. To optimize this, the `GIT_SHALLOW` argument was specified to cmake's `ExternalProject_Add()` function. This caused the cloned repository to have a different head commit SHA and confused cmake. To fix this, I just removed the `GIT_SHALLOW` argument since the repository is pretty small and doing a deep clone is not that expensive.
#no-changelog
> googletest.cmake: remove GIT_SHALLOW when cloning

- FirebaseStorage/Sources/StorageListResult.swift
- FirebaseStorage/Sources/StorageMetadata.swift
- FirebaseStorage/Tests/Unit/StorageMetadataTests.swift
- FirebaseStorageInternal/Tests/Integration/FIRStorageIntegrationTests.m
The games team discovered we missed a few NSObject overrides in the Storage Swift API port.
This PR adds them back along with tests that we never had.
> Missing NSObject overrides and tests

- FirebaseStorage/Sources/StorageListResult.swift
- FirebaseStorage/Sources/StorageMetadata.swift
- FirebaseStorage/Tests/Unit/StorageMetadataTests.swift
- FirebaseStorageInternal/Tests/Integration/FIRStorageIntegrationTests.m
- ReleaseTooling/Template/README.md
#9715 and #9720 were implemented on the release-9.0 branch.  This PR merges them back to master.
> Merge 9715 and 9720 to master

- FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h
This is pretty minor but I noticed the discrepancy while reviewing the larger docs update for Firebase 9.
Doc comment doesn't use accurate Swift API names. See below links:
- https://developer.apple.com/documentation/foundation/bundle/1410786-main
- https://developer.apple.com/documentation/foundation/bundle/1418023-bundleidentifier
#no-changelog
> [skip ci] Correct Swift API in `FIROptions.h` doc

- .github/workflows/storage.yml
- FirebaseStorage.podspec
Redundant interop headers in the podspec caused pod-lib-lint to fail in Xcode 13.3.1 but not 13.2.1.
Since this might cause other issues, I'd like to roll into 9.0.0.
The changes are part of #9745 for master branch
> Fix Storage Pod-lib-lint failures on Xcode 13.3.1

- Firestore/CHANGELOG.md
- Firestore/Example/GoogleTest.podspec
- Firestore/Example/Tests/Integration/FSTTransactionTests.mm
- Firestore/core/src/credentials/user.h
- cmake/external/googletest.cmake
These cherry-pick'd fixes will unblock building Firestore from the Games SDK on Xcode 13.3.1.
Cherry-picking the following PRs into `release-9.0`:
- #9705 
- #9712
Also, updated the CHANGELOG to reflect that this fix is going into v9.
cc: @dconeybe @jonsimantov
> [v9] Cherry-pick Firestore build fix for Xcode 13.3.1 into `release-9.0`

- scripts/check_imports.swift
Restore exception removed in #9660 that is still needed in the GDT repo
> Restore check_imports GDT exception

- FirebaseAppDistribution.podspec
- FirebaseCoreDiagnostics.podspec
- FirebaseCrashlytics.podspec
- FirebaseMLModelDownloader.podspec
- FirebaseMessaging.podspec
- FirebasePerformance.podspec
- Package.swift
- Update product podspecs's dependency on GDT to be ≥9.1.4 (released today to fix 9.1.3)
- Will keep clients from pulling in the buggy 9.1.3 version.
- Pinning from a patch means we can't use the optimistic operator `~>`:
```diff
- s.dependency 'GoogleDataTransport', '~> 9.1'
+ s.dependency 'GoogleDataTransport', '>= 9.1.4', '< 10.0.0'
```
#no-changelog
Fixes #9773
> [v9.1] Bump GoogleDataTransport dep to ≥9.1.4

- FirebaseAuth.podspec
- FirebaseFunctions.podspec
- FirebaseStorageInternal.podspec
- Package.swift
Pinning to a patch version means we cannot use CocoaPod's `~>` operator anymore for GTMSessionFetcher.
```diff
-  s.dependency 'GTMSessionFetcher/Core', '~> 1.7'
+  s.dependency 'GTMSessionFetcher/Core', '>= 1.7.2', '< 1.8.0'
```
#no-changelog
Fixes #9753
> [v9.1] Bump GTMSessionFetcher dependency to >1.7.2

- Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h
- Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlyticsReport.h
The build warnings reported in #9331 seem to be related to #4851. There is a non-Firebase header getting linked in that defines a macro `log` which seems to interfere with the `log` in `NS_SWIFT_NAME(log(format:arguments:))` (in the Crashlytics public headers).
I was able to reproduce #9331 and tested 5 workarounds:
1. Don't use `NS_SWIFT_NAME(log(format:arguments:))` and rely on the default ObjC → Swift translation.
-  I expected this to work but for some reason, the default translation wasn't stripping the `with` from `withFormat:` like I thought it would.
3. Use `NS_SWIFT_NAME` but wrap param in double quotes. `NS_SWIFT_NAME("log(format:arguments:)")`
4. Use `NS_SWIFT_NAME` but wrap param in single quotes. `NS_SWIFT_NAME('log(format:arguments:)')`
5. Disable the `log` macro:
```objc …
```
> [Crashlytics] Don't use `NS_SWIFT_NAME` to avoid collision with 3p macro

- scripts/create_spec_repo/Sources/SpecRepoBuilder/main.swift
release/prerelease workflows [failed](https://github.com/firebase/firebase-ios-sdk/issues/9696#issuecomment-1121473660) due to long running time. Speed up `pod repo push` by adding `--skip-import-validation` to pods.
> Speed up `pod repo push`

- Crashlytics/Crashlytics/Controllers/FIRCLSExistingReportManager.m
In response to a customer that was confused about this
#no-changelog
> Crashlytics add more clarifying information to unsent reports log

- .github/workflows/prerelease.yml
Missing ruby setup should fix last macos 12 issue with prerelease workflow
> Ruby setup for prerlease perf test

- scripts/create_spec_repo/Sources/SpecRepoBuilder/main.swift
Add `SpecRepoBuilder.main()`, which was mistakenly removed in the [previous PR](https://github.com/firebase/firebase-ios-sdk/pull/9789/files#diff-56d9e831e359a173355a51a81b46b99cd8282fdab7b615b1f34c66c12637a3eaL390), to trigger the tool.
> Enable run of create_spec_repo

- .github/workflows/update-cpp-sdk-on-release.yml
Because the C++ SDK's update script now requires the zipfile to be present, modify the "update C++ SDK" workflow to ensure that the zip file is present. This should almost always be the case, except in a rare occasion when the GitHub release is created and the zip file added to it afterwards. This will wait up to an hour for the zip file to be available, similar to how it waits up to an hour for the Cocoapod repo to update.
Also, following Postel's Law (accept liberally, emit conservatively), the workflow now handles iOS SDK release version numbers with or without the leading 'v'.
> Add check for zipfile to "update C++ SDK" workflow.

- README.md
These aren't as important now that we have nightly testing report coming into Issues, and this can be confusing for SwiftPM users. Fixes #9805. 
#no-changelog
> Remove build statuses from README

- Crashlytics/Crashlytics/FIRCrashlytics.m
- Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h
https://github.com/firebase/firebase-ios-sdk/discussions/8815
This is an additive API change which should have no effect on existing clients.
> Add Swift API for recording errors with userInfo parameters

- FirebaseInAppMessaging/CHANGELOG.md
- FirebaseInAppMessaging/Sources/Analytics/FIRIAMClearcutLogStorage.m
- FirebaseInAppMessaging/Sources/Flows/FIRIAMActivityLogger.m
- FirebaseInAppMessaging/Sources/Private/Flows/FIRIAMActivityLogger.h
Possible fix for #9816.
Changed unarchiveObjectWithFile with unarchivedObjectOfClass to conform to secure coding practices, and implemented NSSecureCoding.
> Change unarchiveObjectWithFile in FIAM to conform to the secure coding practices

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- ReleaseTooling/Sources/ManifestParser/GHAMatrixSpecCollector.swift
- scripts/create_spec_repo/Sources/SpecRepoBuilder/main.swift
- scripts/release_testing_setup.sh
> Preinstall FirebaseCore for release testing.

- FirebaseStorageInternal/Tests/Integration/FIRStorageIntegrationTests.m
Update Storage Integration Tests to be clear about the behavior of deleting elements from customMetadata.
See context in #9849
> Storage Custom Metadata Deletion

- FirebaseFunctions/Backend/index.js
- FirebaseFunctions/Backend/start.sh
- FirebaseFunctions/CHANGELOG.md
- FirebaseFunctions/Sources/FunctionsError.swift
- FirebaseFunctions/Tests/Integration/IntegrationTests.swift
- FirebaseFunctions/Tests/ObjCIntegration/FIRIntegrationTests.m
Fix #9855 
The `INVLID_ARGUMENT` typo caused #9855. I also noticed a few other typos from porting FUNError.m to FunctionsError.swift.
Added a variation of the react-native integration test that found this issue.
> Fix 9.0.0 Functions Error Code Regressions

- FirebaseStorageInternal/Tests/Integration/FIRStorageIntegrationTests.m
Update test to be consistent with docs.  Verified locally.
See #9849
> Use nil to clear customMetadata

- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Auth/FIRAuth.m
#9622 attempted to fix user logout issues that occur because of [prewarming](https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app/about_the_app_launch_sequence?language=objc#3894431) [[1](https://github.com/firebase/firebase-ios-sdk/issues/8695)][[2](https://sourcediving.com/solving-mysterious-logout-issues-on-ios-15-8b818c089466)] by using the `isProtectedDataAvailable` API to determine if the keychain was accessible.
However, from #9869 it appears that this check may be causing issues. Instead of checking `isProtectedDataAvailable`, we will instead catch keychain errors to determine whether we should listen to the `UIApplicationProtectedDataDidBecomeAvailable` notification.
Fixes #9869
> Try to address prewarming issue by catching keychain errors instead of using `isProtectedDataAvailable`

- scripts/localize_podfile.swift
- This issue surfaced here: https://github.com/firebase/firebase-ios-sdk/pull/9922#issuecomment-1159295509
- The reasoning was that `localize_podfile.swift` pulls in all local pods ending in `.podspec`, but since I merged #9829, closed source pods were being pulled in and you can't use the `:path` operator on a binary pods.
- The quick fix was to ensure that the `:path` is only added for open source pods
- For future work: maybe the `localize_podfile.swift` can live in release tooling so we have once source of truth (FirebaseManifest.swift). 
#no-changelog
> [Infra] Update `localize_podfile.swift`

- FirebaseStorageInternal/Tests/Integration/FIRStorageIntegrationTests.m
For investigations related to #9849 discussions, add a test for initializing StorageMetadata with `initWithDictionary` and then clearing it. Also test the name field.
The test passes in both Firebase 8 and 9.
> Add a StorageMetadata integration test

- cmake/external/snappy.cmake
Firestore's snappy patching in the firebase-cpp-sdk is broken on GitHub Actions runners after upgrading its firebase-ios-sdk dependency from 9.1.0 to 9.2.0 in https://github.com/firebase/firebase-cpp-sdk/pull/1003:
https://github.com/firebase/firebase-cpp-sdk/runs/7023311255
Note that this PR has some special logic in https://github.com/firebase/firebase-cpp-sdk/pull/1003/commits/77f3e708c1505fbf8419effd4481cc19f960b1c3 to remove the patching of the "snappy" library.
The error from the build log is:
```
Performing patch step for 'snappy'
patching file snappy.cc
Assertation failed!
Program: C:\Strawberry\c\bin\patch.exe
File: .\src\patch\2.5.9\patch-2.5.9-src\patch.c, Line 354
Expression: hunk
```
Originally, I was not able to reproduce this locally; however, I was able to reproduce it by …
> When patching snappy for Firestore, add --binary flag to patch command.

- FirebaseCore/CHANGELOG.md
- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
Fix #9937 
We haven't found a way to solve the functionality issues arising from GoogleSignInSwift using a different module name from its pod name, so we won't be able to support from the Firebase distributions in the near term.
> Remove GoogleSignInSwift from binary distros

- cmake/external/nanopb.cmake
- cmake/external/nanopb.patch
- scripts/check_whitespace.sh
This fixes the following cmake build error on machines that lack a python 2.7 interpreter (e.g. a fresh macbook):
```
CMake Error at Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at
least version "2.7")
Call Stack (most recent call first):
Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
Cellar/cmake/3.23.2/share/cmake/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
build/external/src/nanopb/CMakeLists.txt:44 (find_package)
```
when the following command is run:
```
cmake -S . -B build
```
#no-changelog
> Patch nanopb CMakeLists.txt to look for python 3.7 instead of python 2.7

- CMakeLists.txt
The cmake build scripts gain a new cache variable, `FIREBASE_LD_EXECUTABLE`, which, if specified, instructs the C/C++ linking steps to use the specified linker executable instead of the default linker executable (which is `ld` for clang and gcc).
The motivating use case for using a custom linker is to enable using `mold` (https://github.com/rui314/mold), a custom linker that is compatible with, but significantly faster than, the default `ld` linker. For continuous builds and continuous tests, this doesn't really matter and this new cache variable is not intended to be used in this case; however, during build/test cycles the linking time is one of the biggest contributors to the length of such cycles. Reducing the linking time makes local development easier and less distracting. …
> Add FIREBASE_LD_EXECUTABLE cmake cache variable

- FirebaseFunctions/Sources/FunctionsError.swift
As per @paulb777, here is the PR based on the issue I found: Fix https://github.com/firebase/firebase-ios-sdk/issues/9942
**Step 1: Describe your environment**
Xcode version: 13.4.1
Firebase SDK version: 9.3.0
Installation method: CocoaPods
Firebase Component: Functions
Target platform(s): iOS
**Step 2: Describe the problem**
Functions that throw already-exists generate the right HTTP response (seen in Postman as HTTP 409 Conflict). However, in the iOS client bubbles the error to the client as notFound. The commit mentioned below shows the affected areas and includes a fix.
**Steps to reproduce:**
Simple. Just throw the following from a Cloud Function:
throw new functions.https.HttpsError('already-exists', 'Resource exists')
If you have a downloadable sample project that reproduces the …
> alreadyExists returns the wrong code

- Firestore/core/src/api/firestore.h
In https://github.com/firebase/firebase-ios-sdk/pull/9838 a new `max_attempts` argument was added to the `RunTransaction()` method in `Firestore/core/src/api/firestore.h` (an internal API, not an API presented to customers). This new argument was given a default value to avoid breaking the build of the firebase-cpp-sdk.
Now that https://github.com/firebase/firebase-cpp-sdk/pull/966 has been merged, this default argument value can be removed, as all call sites explicitly specify a value for `max_attempts`.
#no-changelog
> Remove default value for `max_attempts` argument to `RunTransaction()`.

- FirebasePerformance/CHANGELOG.md
- FirebasePerformance/Sources/Common/FPRConsoleURLGenerator.m
- FirebasePerformance/Tests/Unit/Common/FPRConsoleURLGeneratorTest.m
The metrics page is getting deprecated. We need to update the URL to the troubleshooting page.
> Update console logging URL

- FirebaseRemoteConfig/CHANGELOG.md
- FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
Similar fix to https://github.com/firebase/firebase-ios-sdk/pull/7604, which only updated the fetch path but not activate
Tracked internally in b/211879339
> Modify activate path to only update experiments for firebase namespace

- FirebasePerformance/Tests/Unit/FPRScreenTraceTrackerTest.m
This is not a clean fix. There is an underlying problem between iOS15 and iOS16.
With iOS15, setting a viewController to `nil` would deallocate it. This does not happen on iOS16 (most likely because of some internal reference holding on to the view controller).
Because of this a unit test fails where we expect no screen trace to be created for inactive view controllers during restart of the application. For the current fix, I have removed the check on the number of active screen traces.
While it might look like a test is commented out, it should work fine in production since deallocation of view controllers would force it go out of memory. In test environment, this was simulated - so the lifecycle events of the VC are not rightly simulated.
#no-changelog
> Fix the failing test on iOS16.

- Firestore/core/src/model/mutation.cc
- Firestore/core/test/unit/model/mutation_test.cc
Fix for https://github.com/firebase/firebase-ios-sdk/issues/9985
Beside this particular fix, this PR also has a fix for MutationTest.VerifyOverlayRoundTrips itself. It has been passing the wrong field mask, and all tests are treating overlay as set mutations as a result. This test fix also uncovered another bug, which is also fixed in this PR.
> Fix Overlay bug with nested field deletion

- .github/workflows/update-cpp-sdk-on-release.yml
This caused an issue with the latest release.
> Update name of file in CPP repo

- FirebaseAuth/Tests/Sample/Podfile
- FirebaseAuth/Tests/Sample/Sample/GoogleAuthProvider.m
M1 Macs require Google Sign-In SDK v6 or greater; bumping the version in the auth test app by following https://developers.google.com/identity/sign-in/ios/quick-migration-guide.
#no-changelog
> Bump Google Sign-In SDK version for Auth sample app.

- FirebaseStorage/Sources/StorageMetadata.swift
Follow up on a review request from #9979
> Create dictionary with compactMap

- FirebaseCore/CHANGELOG.md
- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsBundle.swift
- FirebaseCore/Internal/Sources/HeartbeatLogging/RingBuffer.swift
- FirebaseCore/Internal/Tests/Unit/RingBufferTests.swift
An issue was reported where the issue's crash report suggests an index out of bounds exception in the `RingBuffer` type. This type is used by FirebaseCoreInternal's heartbeat component. `RingBuffer` internally manages an insertion index that is incremented/decremented to always be within the inner array's bounds. In the reported issue, that assumption was being broken for some reason. 
To prevent the crash, the crashing `RingBuffer` API is converted to a throwing method that throws an error if the insertion index is out of bounds. This is gracefully handled in the calling context to reset the ring buffer in an effort to return things to a normal state.
Fixes #10025
> [FirebaseCoreInternal] Guard against invalid indexing into `RingBuffer` type

- FirebaseAuth/Sources/Backend/FIRAuthBackend+MultiFactor.m
- FirebaseAuth/Sources/Backend/FIRAuthBackend.h
- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/Backend/FIRAuthRequestConfiguration.h
- FirebaseAuth/Sources/Backend/FIRAuthRequestConfiguration.m
- FirebaseAuth/Sources/Backend/FIRIdentityToolkitRequest.h
- FirebaseAuth/Sources/Backend/FIRIdentityToolkitRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRGetRecaptchaConfigRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRGetRecaptchaConfigRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRGetRecaptchaConfigResponse.h
- FirebaseAuth/Sources/Backend/RPC/FIRGetRecaptchaConfigResponse.m
- FirebaseAuth/Sources/Backend/RPC/MultiFactor/Enroll/FIRFinalizeMFAEnrollmentRequest.m
- FirebaseAuth/Sources/Backend/RPC/MultiFactor/Enroll/FIRStartMFAEnrollmentRequest.m
- FirebaseAuth/Sources/Backend/RPC/MultiFactor/SignIn/FIRFinalizeMFASignInRequest.m
- FirebaseAuth/Sources/Backend/RPC/MultiFactor/SignIn/FIRStartMFASignInRequest.m
- FirebaseAuth/Sources/Backend/RPC/MultiFactor/Unenroll/FIRWithdrawMFARequest.m
- FirebaseAuth/Tests/Unit/FIRAuthBackendRPCImplementationTests.m
- FirebaseAuth/Tests/Unit/FIRFakeBackendRPCIssuer.m
- FirebaseAuth/Tests/Unit/FIRGetRecaptchaConfigRequestTests.m
- FirebaseAuth/Tests/Unit/FIRGetRecaptchaConfigResponseTests.m
- FirebaseAuth/Tests/Unit/FIRIdentityToolkitRequestTests.m
This PR updates the 4 email auth apis (sign in, sign up, password reset, email link sign in) to support recaptcha enterprise. [go/gcip-recaptcha-client-sdk-api](http://go/gcip-recaptcha-client-sdk-api)
- Implement getRecaptchaConfig API This PR - https://github.com/firebase/firebase-ios-sdk/pull/10038
- New backend error types
- Update backend apis
- Implement recaptcha enterprise verifier
- Wire recaptcha enterprise verifier to email auth flows
> Implement get recaptcha config

- FirebaseAuth/Sources/Backend/RPC/Proto/FIRAuthProtoMFAEnrollment.h
- FirebaseAuth/Sources/Backend/RPC/Proto/FIRAuthProtoMFAEnrollment.m
- FirebaseAuth/Sources/MultiFactor/FIRMultiFactor.m
- FirebaseAuth/Sources/MultiFactor/FIRMultiFactorConstants.m
- FirebaseAuth/Sources/MultiFactor/Phone/FIRPhoneMultiFactorInfo.m
- FirebaseAuth/Tests/Unit/FIRUserTests.m
Internal tracking bug b/240587526
> Fix a bug where phone multi factor id is not correctly retrieved

- FirebaseCore/Internal/Sources/HeartbeatLogging/RingBuffer.swift
While the current code works fine, older Swift toolchains may have trouble with inferring what array the index will be used in. Being more explicit here just makes for safer code in general.
#no-changelog
> [CoreInternal] Add explicit generics typing for Array.Index usage

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Backend/RPC/FIRGetOOBConfirmationCodeRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRGetOOBConfirmationCodeRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRSignUpNewUserRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRSignUpNewUserRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRVerifyPasswordRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRVerifyPasswordRequest.m
- FirebaseAuth/Tests/Unit/FIRGetOOBConfirmationCodeRequestTests.m
- FirebaseAuth/Tests/Unit/FIRSignUpNewUserRequestTests.m
- FirebaseAuth/Tests/Unit/FIRVerifyPasswordRequestTest.m
This PR updates the 4 email auth apis (sign in, sign up, password reset, email link sign in) to support recaptcha enterprise. [go/gcip-recaptcha-client-sdk-api](http://go/gcip-recaptcha-client-sdk-api)
- Implement getRecaptchaConfig API https://github.com/firebase/firebase-ios-sdk/pull/10038
- New backend error types https://github.com/firebase/firebase-ios-sdk/pull/10048
- Update backend apis https://github.com/firebase/firebase-ios-sdk/pull/10063
- Implement recaptcha enterprise verifier
- Wire recaptcha enterprise verifier to email auth flows
> Backend apis

- FirebaseCore/Tests/Unit/FIRAppTest.m
The two tests in this PR have an implicit assumption that they are running *not* running on watchOS. I have therefore excluded them from running on watchOS.
#no-changelog
> [Core] Exclude lifecycle-dependent tests from watchOS

- Gemfile
- scripts/build.sh
Originally, [when the watchOS option in `scripts/build.sh`](https://github.com/firebase/firebase-ios-sdk/blob/a61f7b367b013b8fd9596aa85d6e0de0fad9d5d4/scripts/build.sh#L168-L170) was written, standalone watchOS apps were not yet a thing. So instead, the `--destination` of watchOS schemes ran on an iPhone as a companion target. This works but hid some failures that running on a watchOS destination would have surfaced (see #10085).
#no-changelog
> [Infra] Use watchOS device when using `scripts/build.sh` for watchOS

- .github/workflows/app_check.yml
- .github/workflows/release.yml
I think the failing watchOS workflow in #10088 may be attributed to #10082. I noticed that triggering a global CI run in #10082 did not trigger this workflow. Further investigation revealed that the AppCheck workflow has not triggered on `Gemfile*` changes. This PR adds it as a trigger.
I also did an audit of the other workflows and added `Gemfile*` triggering where necessary so that all workflows that have at least one non-cron job trigger on the `Gemfile*` changes. (I excluded irrelevant workflows like notice generation and code coverage).
#no-changelog
> [Infra] Some workflows haven't been triggered on Gemfile changes

- FirebaseAppCheck/CHANGELOG.md
- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckAvailability.h
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckTests.m
- FirebaseAppCheck/Tests/Unit/DeviceCheckProvider/FIRDeviceCheckProviderTests.m
This PR achieves two things:
1. Resolves recent [AppCheck / watchOS CI issue](https://github.com/firebase/firebase-ios-sdk/pull/10088#issuecomment-1210908096). 
2. `DeviceCheck` now has [beta support for watchOS 9.0+](https://developer.apple.com/documentation/devicecheck) in Xcode 14. This means that we can update AppCheck's DeviceCheck provider to reflect the new availability.
I validated that `app_check / spm (watchOS)`'s underlying script passed locally on Xcode 13.3.1.
> [AppCheck] DeviceCheck provider is supported by watchOS 9.0+

- FirebaseAppCheck/CHANGELOG.md
- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckAvailability.h
Successor PR to #10093 and #10094. This is last PR in the series.
In #10094, availability logic was updated to allow support for DeviceCheck on watchOS 9.0+. This PR allows support for **App Attest** on watchOS 9.0+.
App Attest now has [beta support for watchOS 9.0+](https://developer.apple.com/documentation/devicecheck/dcappattestservice) in Xcode 14. This means that we can update AppCheck's App Attest provider to reflect the new availability.
> [AppCheck] App Attest provider is supported by watchOS 9.0+

- Firestore/CHANGELOG.md
- Firestore/core/src/local/local_documents_view.cc
See similar logic in [Android](https://cs.opensource.google/firebase-sdk/firebase-android-sdk/+/master:firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java;l=173-176?q=LocalDocumentsView.java&ss=firebase-sdk%2Ffirebase-android-sdk) and [Web](https://cs.opensource.google/firebase-sdk/firebase-js-sdk/+/master:packages/firestore/src/local/local_documents_view.ts;l=239-244?q=computeviews&ss=firebase-sdk%2Ffirebase-js-sdk).
This is inserting into a map while its being iterated over. Note that SortedMap
does not guarantee pointer stability. In fact, upon insertion, SortedMap may
[switch](https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/master:Firestore/core/src/immutable/sorted_map.h;l=186-197?q=sorted_map.h&ss=firebase-sdk%2Ffirebase-ios-sdk) …
> Remove erroneous logic in ComputeViews.

- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
Add back off flag to Realtime. If enabled, this will prevent Realtime from working until the app restarts.
Backend will have a new field called featureDisabled added to stream response. If this field is enabled, this will set stop Realtime from working until the next time the app is restarted. The current back off state in the SDK will be represented by the flag gIsBackoffEnabled.
> Realtime rc failsafe

- Firestore/CHANGELOG.md
Added the unreleased CHANGELOG entries from Firestore in preparation for the Firebase 9.5.0 release.
> Update Firestore CHANGELOG for Firebase 9.5.0

- Firestore/CHANGELOG.md
- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Integration/API/FIRIndexingTests.mm
- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/Public/FirebaseFirestore/FIRFirestore.h
- Firestore/core/src/api/firestore.cc
- Firestore/core/src/api/firestore.h
- Firestore/core/src/bundle/bundle_reader.h
- Firestore/core/src/bundle/bundle_serializer.cc
- Firestore/core/src/bundle/bundle_serializer.h
- Firestore/core/src/core/firestore_client.cc
- Firestore/core/src/core/firestore_client.h
- Firestore/core/src/local/leveldb_index_manager.cc
- Firestore/core/src/local/local_store.cc
- Firestore/core/src/local/local_store.h
- Firestore/core/src/local/query_engine.h
- Firestore/core/src/model/field_index.h
- Firestore/core/src/util/json_reader.cc
- Firestore/core/src/util/json_reader.h
- Firestore/core/src/util/set_util.h
- Firestore/core/test/unit/bundle/bundle_serializer_test.cc
- Firestore/core/test/unit/local/counting_query_engine.cc
- Firestore/core/test/unit/local/leveldb_local_store_test.cc
- Firestore/core/test/unit/local/local_store_test.cc
- Firestore/core/test/unit/local/local_store_test.h
- Firestore/core/test/unit/local/query_engine_test.cc
- Firestore/core/test/unit/local/query_engine_test.h
- Firestore/core/test/unit/testutil/CMakeLists.txt
- Firestore/core/test/unit/testutil/testutil.cc
- Firestore/core/test/unit/testutil/testutil.h
Expose client side indexing feature with `FIRFirestore.setIndexConfigurationFromJSON` and `FIRFirestore.setIndexConfigurationFromStream`
> Add setIndexConfiguration for client side indexing

- FirebaseCore/CHANGELOG.md
- FirebaseStorageInternal.podspec
- Package.swift
Limit dependency GTMSessionFetcher version update to < 2.1.0 to avoid a new deprecation warning.
Fix #10055
GTMSessionFetcher deprecated an API used by FirebaseStorageInternal.
- WARN  | xcodebuild:  /Users/paulbeusterien/gh5/firebase-ios-sdk/FirebaseStorageInternal/Sources/FIRStorageTokenAuthorizer.h:35:50: warning: 'GTMFetcherAuthorizationProtocol' is deprecated: implement GTMSessionFetcherAuthorizer instead [-Wdeprecated-declarations]
- NOTE  | xcodebuild:  GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcher.h:644:1: note: 'GTMFetcherAuthorizationProtocol' has been explicitly marked deprecated here
- WARN  | xcodebuild:  /Users/paulbeusterien/gh5/firebase-ios-sdk/FirebaseStorageInternal/Sources/FIRStorageTokenAuthorizer.m:61:1: warning: implementing deprecated …
> Limit GTMSessionFetcher version update to < 2.1.0

- FirebaseAuth/Tests/Sample/E2eTests/BYOAuthTests.m
- FirebaseAuth/Tests/Sample/Sample/MainViewController+AutoTests.m
Changed token URL to point to new test-app. The test app at https://fb-sa-1211.appspot.com/token is not maintained anymore.
> modified url for app engine test-app

- FirebaseCore/CHANGELOG.md
- FirebaseStorageInternal.podspec
- FirebaseStorageInternal/Sources/FIRStorageTokenAuthorizer.h
- FirebaseStorageInternal/Sources/FIRStorageTokenAuthorizer.m
- Package.swift
More term long-term sustainable solution than #10123 to the deprecation warning introduced by GTMSessionFetcher 2.1
> Reenable any GTMSessionFetcher 2.x dependency

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
For CocoaPods-related issues, we request the `Podfile.lock`.
Now, for SwiftPM-related issues, we request the `Package.resolved`. Thanks @rizafran for the idea!
See render template at [here](https://github.com/firebase/firebase-ios-sdk/blob/nc/swiftpm-issue-template/.github/ISSUE_TEMPLATE/BUG_REPORT.yml)
#no-changelog
> [Infra] Add SPM debug info to issue template

- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
- FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m
Currently we are optimistically resetting the retry count in `beginRealtimeStream` immediately after starting the data task, however the request may fail, and the reset retry count causes us to retry infinitely (see internal b/241811665)
- Moving the logic to be handled in the data task delegates and only reset retry count when request has succeeded.
- Removed some duplicate checks in `retryHTTPConnection` because `beginRealtimeStream` has the same checks
- Some minor renaming
Able to repro/verify in the sample app by turning off the device network to generate an error
Ideally this should be covered in a unit test, however there is no existing testing for any of the data task interactions, so it's slightly tricky to add and will be done in a following PR
> [RC] Fix retry logic to respect max retry count

- FirebaseAppCheck/Tests/Integration/FIRDeviceCheckAPIServiceE2ETests.m
- FirebaseAppCheck/Tests/Unit/AppAttestProvider/Storage/FIRAppAttestArtifactStorageTests.m
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckIntegrationTests.m
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckStorageTests.m
- Package.swift
- Intentionally caused by https://github.com/google/GoogleUtilities/pull/75
- While we do lose some coverage on CI, [GoogleUtilities/#75](https://github.com/google/GoogleUtilities/pull/75) makes the macOS keychain behave like the iOS style keychain (which is tested on CI).
- Also cleaned up the `AppCheckUnit` test target in the Package manifest. I think prefer excluding at the test file level to keep things consistent between build systems and the source of truth in the test file.
- Unblocks some of the CI in #10145
#no-changelog
> [AppCheck] Disable tests that use keychain

- FirebaseMLModelDownloader/Tests/Integration/ModelDownloaderIntegrationTests.swift
- FirebaseMLModelDownloader/Tests/Unit/ModelDownloaderUnitTests.swift
- Intentionally caused by https://github.com/google/GoogleUtilities/pull/75
- MLModelDownloader is affected because it depends on Installations (which depends on GoogleUtilities's keychain abstraction)
- While we do lose some coverage on CI, [GoogleUtilities/#75](https://github.com/google/GoogleUtilities/pull/75) makes the macOS keychain behave like the iOS style keychain (which is tested on CI).
- Unblocks some of the CI in #10145
#no-changelog
> [MLModelDownloader] Disable keychain-dependent tests on macCatalyst and macOS

- FirebaseCore/Sources/FIRApp.m
- FirebaseCore/Tests/Unit/FIRAppTest.m
Lifecycle notifications have not been observed on watchOS so watchOS heartbeats are not created. 
The [`WKApplicationDidBecomeActiveNotification`](https://developer.apple.com/documentation/watchkit/wkapplicationdidbecomeactivenotification?language=objc) notification that is being observed it only available on `watchOS 7.0+`.
Our [SPM distribution has watchOS `7.0`](https://github.com/firebase/firebase-ios-sdk/blob/master/Package.swift#L26) as the minimum version but our [CocoaPods specs have `6.0`](https://github.com/firebase/firebase-ios-sdk/search?l=Ruby&q=watchos).
In an effort to maintain compatibility with `watchOS 6.0`, this PR adds support for the following behavior:
- On watchOS 7.0+, heartbeats are captured when the `WKApplicationDidBecomeActiveNotification` is fired.
- On …
> [Core] Support watchOS lifecycle notifications

- FirebaseCore.podspec
In #10112, a `WatchKit` API was added in `FirebaseCore`. It seems that CocoaPods
builds require that `WatchKit` be linked in if watchOS APIs are being used.
The `FirebaseCore.podspec` didn't need to import `WatchKit` before because we weren't using any `WatchKit` APIs.
Fixes #10156
#no-changelog
> [Core] Link `WatchKit` for watchOS in `FirebaseCore.podspec`

- Firestore/CHANGELOG.md
- Firestore/core/src/core/firestore_client.cc
Fix CPU thrashing from the index backfiller, which was being scheduled for execution every 1ms. The fix in this PR is to increase the scheduling period to 1000ms.
This also works around an intermittent crash on Firestore's shutdown, which cause the integration tests in the firebase-cpp-sdk to crash.
This bug was introduced in 9.5.0 by https://github.com/firebase/firebase-ios-sdk/pull/10021.
Googlers see b/244656664 for details.
Fixes #10168
> firestore_client.cc: increase the kRegularBackfillDelay from 1ms to 1000ms

- Firestore/Protos/lib/pretty_printing.py
- Firestore/Protos/nanopb/firestore/bundle.nanopb.cc
- Firestore/Protos/nanopb/firestore/local/maybe_document.nanopb.cc
- Firestore/Protos/nanopb/firestore/local/mutation.nanopb.cc
- Firestore/Protos/nanopb/firestore/local/target.nanopb.cc
- Firestore/Protos/nanopb/google/api/http.nanopb.cc
- Firestore/Protos/nanopb/google/api/resource.nanopb.cc
- Firestore/Protos/nanopb/google/firestore/admin/index.nanopb.cc
- Firestore/Protos/nanopb/google/firestore/v1/common.nanopb.cc
- Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc
- Firestore/Protos/nanopb/google/firestore/v1/firestore.nanopb.cc
- Firestore/Protos/nanopb/google/firestore/v1/query.nanopb.cc
- Firestore/Protos/nanopb/google/firestore/v1/write.nanopb.cc
- Firestore/Protos/nanopb/google/protobuf/any.nanopb.cc
- Firestore/Protos/nanopb/google/protobuf/empty.nanopb.cc
- Firestore/Protos/nanopb/google/protobuf/struct.nanopb.cc
- Firestore/Protos/nanopb/google/protobuf/timestamp.nanopb.cc
- Firestore/Protos/nanopb/google/protobuf/wrappers.nanopb.cc
- Firestore/Protos/nanopb/google/rpc/status.nanopb.cc
- Firestore/Protos/nanopb/google/type/latlng.nanopb.cc
When generating the C++ code from the .proto files, it was discovered that if a proto message happens to have a field named "result", "header", or "tail" then the generated C++ code would fail to compile with an error like this:
```
In file included from firestore.nanopb.cc:22:
pretty_printing.h: In instantiation of ‘std::string firebase::firestore::nanopb::PrintMessageField(...)’:
firestore.nanopb.cc:630:32:   required from here
pretty_printing.h:59:25: error: ‘const class std::__cxx11::basic_string<char>’ has no member named ‘ToString’
59 |   auto contents = value.ToString(indent_level);
|                   ~~~~~~^~~~~~~~
```
The root cause was that the ToString() methods defined local variables named "result", "header", and "tail" which would collide with other local variable names …
> Fix name collision with "result" in pretty printing logic in generated proto code.

- FirebaseMessaging/Sources/Token/FIRMessagingAuthKeychain.m
- FirebaseMessaging/Tests/UnitTests/FIRMessagingAuthKeychainTest.m
This is fix for Messaging to match change made to core here -> https://github.com/google/GoogleUtilities/pull/75
The fix is to avoid auth alerts (popups) on macOS when using Keychain.
Background: go/firebase-macos-keychain-popups
> [Messaging] macOS keychain auth prompt fix

- .gitignore
VSCode's git plugin always wants to commit .build/ folders. This includes those
in subdirectories.
I propose doing a recursive match of all `.build/` folders.
#no-changelog
> [Infra] Commits should exclude .build/ folder from nested dirs

- FirebaseCore/CHANGELOG.md
- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatController.swift
- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsBundle.swift
- FirebaseCore/Internal/Sources/HeartbeatLogging/RingBuffer.swift
Follow-up to #10075. Older Swift versions (< 5.3) do not like referencing the
`Array` type without specifying the generic type for the array. This can result
in a buildtime error when building with a Swift version under 5.3.
Prevents #10171
> [CoreInternal] Add explicit generics typing for Array.Index usage (2)

- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
#10073 exposed an existing bug caused by conflating framework names and pod names, which led to FBLPromises.xcpromises being duplicated in every zip folder, eg
```
Only in Firebase/FirebaseInAppMessaging: FBLPromises.xcframework
Only in Firebase/FirebaseMLModelDownloader: FBLPromises.xcframework
Only in Firebase/FirebaseMessaging: FBLPromises.xcframework
Only in Firebase/FirebasePerformance: FBLPromises.xcframework
Only in Firebase/FirebaseRemoteConfig: FBLPromises.xcframework
Only in Firebase/FirebaseStorage: FBLPromises.xcframework
...
```
This PR fixes the issue by identifying the variable correctly as `frameworksToIgnore` and comparing against frameworks instead of pods.
> Fix zip bloat issue

- Firestore/Source/API/FIRFirestoreSettings.mm
require_constant_initialization is incompatible with extern "C"
ABSL_CONST_INIT uses the require_constant_initialization clang attribute, which is now present in the apple cross compiler. This attribute can only be used in C++.
https://clang.llvm.org/docs/AttributeReference.html#require-constant-initialization-constinit-c-20
Googlers can see cl/473006027 for additional context.
#no-changelog
> FIRFirestoreSettings.mm: remove unnecessary extern "C"

- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Sources/Internal/StoragePath.swift
- FirebaseStorage/Sources/Storage.swift
- FirebaseStorage/Sources/StorageError.swift
- FirebaseStorage/Tests/Unit/StorageReferenceTests.swift
Fix #6974 
Provide a throwing API for failures instead of `fatalError`. Also use a `URL` type for the url parameter instead of `String`
New API `open func reference(for url: URL) throws -> StorageReference` equivalent to
`open func reference(forURL url: String) -> StorageReference` except it throws instead of
erroring.
> Add new throwing reference(for url:URL) API

- FirebaseInAppMessaging/CHANGELOG.md
- FirebaseInAppMessaging/Swift/Source/SwiftUIPreviewHelpers.swift
Removed an unintentional constant named "foo" from the Firebase In-App Messaging Swift API. This constant is not of use to developers (simply containing UIColor.black) and was only added accidentally. Closes #9998.
> FIAM: Remove extraneous `foo` constant in Swift preview helpers

- Firestore/CHANGELOG.md
- Firestore/core/src/util/set_util.h
> Firestore: Fix @param comparator doc compiler warning

- FirebaseFunctions/CHANGELOG.md
- FirebaseFunctions/Sources/Callable+Codable.swift
> Remove unnecessary, unused parameters from API

- FirebaseDynamicLinks/CHANGELOG.md
- FirebaseDynamicLinks/Sources/FIRDynamicLinks.m
- FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLink.h
DynamicLink's initializer was not intended to be publicly available. Marking it as NS_UNAVAILABLE hides it from both ObjC and Swift callers; resolves #10000.
> FDL: Mark FIRDynamicLink's init as NS_UNAVAILABLE

- Firestore/core/src/local/local_store.cc
- Firestore/core/src/model/field_index.h
- Firestore/core/test/unit/local/leveldb_local_store_test.cc
This fixes the following build error on Windows:
```
local_store.cc(681): error C2664: 'void firebase::firestore::util::DiffSets<firebase::firestore::model::FieldIndex,firebase::firestore::local::LocalStore::ConfigureFieldIndexes::<lambda_bf22b4eef787b0dba8fa48c35f79fcdb>>(std::set<firebase::firestore::model::FieldIndex,firebase::firestore::local::LocalStore::ConfigureFieldIndexes::<lambda_bf22b4eef787b0dba8fa48c35f79fcdb>,std::allocator<_Ty>>,std::set<firebase::firestore::model::FieldIndex,firebase::firestore::local::LocalStore::ConfigureFieldIndexes::<lambda_bf22b4eef787b0dba8fa48c35f79fcdb>,std::allocator<_Ty>>,std::function<firebase::firestore::util::ComparisonResult (const firebase::firestore::model::FieldIndex &,const firebase::firestore::model::FieldIndex &)>,std::function<void …
```
> Firestore: Fix Windows build due to decltype of captured lambda

- FirebaseStorage/Sources/Internal/StorageDeleteTask.swift
- FirebaseStorage/Sources/Internal/StorageGetDownloadURLTask.swift
- FirebaseStorage/Sources/Internal/StorageGetMetadataTask.swift
- FirebaseStorage/Sources/Internal/StorageListTask.swift
- FirebaseStorage/Sources/Internal/StorageUpdateMetadataTask.swift
- FirebaseStorage/Sources/StorageDownloadTask.swift
- FirebaseStorage/Sources/StorageMetadata.swift
- FirebaseStorage/Tests/Unit/StorageMetadataTests.swift
- Use `callback?` instead of `if let callback ...`
- Better StorageDownloadTask `enqueue` signature
- Restore non-optional `bucket` property in StorageMetadata
Initializing an unspecified `bucket` property as `""` instead of `nil` when creating `StorageMetadata` with a dictionary was an inadvertent Firebase 9 change from Firebase 8. This PR keeps the Firebase 9 behavior onto Firebase 10.
> Address 9963 review feedback

- FirebaseStorage/Sources/StorageReference.swift
- FirebaseStorage/Tests/Unit/StorageAPITests.swift
Address post-merge #9963 comment
#no-changelog
> Fix inadvertent API change

- FirebaseStorage/Sources/AsyncAwait.swift
- FirebaseStorage/Sources/StorageReference.swift
> Docs update for Extensions and putFile

- ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
- ReleaseTooling/Sources/ZipBuilder/CarthageUtils.swift
- ReleaseTooling/Sources/ZipBuilder/CocoaPodUtils.swift
- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
Fix #10186
Do separate Carthage build for GoogleUtilities instead of FirebaseCoreDiagnostics to enable Platform Logging distinction between Carthage and zip.
> Separate GoogleUtilities Carthage build

- Package.swift
GoogleUtilities 7.9.0 released today. It was an SPM-only release. To ensure developers using the upcoming Firebase 10 always have this fix, the `Package.swift` has been updated to use 7.9.0 as the lower bound for the GoogleUtils dependency. CocoaPods remains unchanged at 7.8.0.
#no-changelog
> [SPM] Bump GoogleUtils lower bound for Firebase 10

- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppAttestProvider.h
- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRDeviceCheckProvider.h
- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRDeviceCheckProviderFactory.h
Noticed some inconsistencies in the platforms that the public AppCheck docs mentioned and the platforms that the SDK actually supports. This PR refines the docs to use [this ](https://firebase.google.com/docs/ios/learn-more) as the source of truth.
#no-changelog
> [AppCheck] Refine public docs

- Firestore/Swift/CHANGELOG.md
- Firestore/Swift/Source/Codable/EncoderDecoder.swift
- Firestore/Swift/Source/Codable/TimestampDecodingStrategy.swift
- Firestore/Swift/Source/Codable/TimestampEncodingStrategy.swift
Removed the `Firestore.Encoder` and `Firestore.Decoder` encoding/decoding strategy type aliases and directly used the types from `FirebaseDataEncoder` and `FirebaseDataDecoder`.
Note: This requires the `TimestampEncoding/DecodingStrategy` extension to be added to `FirebaseDataEncoder/Decoder` instead of `Firestore.Encoder` and `Firestore.Decoder`. This will make the `timestamp` strategy visible to all users of the `FirebaseDataEncoder/Decoder` (that have FirestoreSwift installed), even though `Timestamp` is a Firestore-specific type.
> [Firestore] Remove encoding/decoding strategy type aliases

- Firestore/Swift/Source/Codable/DocumentID.swift
This addresses a late review comment (https://github.com/firebase/firebase-ios-sdk/pull/10167#discussion_r982250978) on #10167, and ensures the error message is rendered on a single line.
Before:
```
2022-09-28 12:49:44.813075+0200 Make It So[29167:1864911] 10.0.0 - [FirebaseFirestoreSwift][I-FST000002] Attempting to initialize or set a @DocumentID property with a non-nil
value: B89FE0DD-7ACB-4D55-9FBE-CFC70512E760. The document ID is managed by Firestore and any
initialized or set value will be ignored. The ID is automatically set
when reading from Firestore."
```
After:
```
2022-09-29 18:41:42.906942+0200 Make It So[91334:3600697] 10.0.0 - [FirebaseFirestoreSwift][I-FST000002] Attempting to initialize or set a @DocumentID property with a non-nil value: 123. The document ID is managed by …
```
> DocumentId property wrapper: Emit error message on a single line

- FirebaseAppDistribution/CHANGELOG.md
- FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
This fixes the issue (#8096) where a scene may not be considered foreground in viewDidAppear.
There can still be issues for apps that have multiple scenes, and the right approach for that would involve using `UISceneDidActivateNotification`.
An example is https://github.com/firebase/firebase-ios-sdk/pull/9169.
> Fix sign in alert shown inconsistently when triggered in viewDidAppear

- FirebaseStorage/Sources/Storage.swift
- scripts/check_imports.swift
- `@_implementationOnly` is used when importing `FirebaseCoreExtension` to
prevent the module from re-exporting `FirebaseCoreExtension`, which is an
internal target.
- Update the `scripts/check_imports.swift` to check `*.swift` files for
importing `FirebaseCoreExtension` without the `@_implementationOnly`
attribute.
#no-changelog
> [Infra] Check for improper FirebaseCoreExtension imports

- FirebaseCore/Sources/FIRApp.m
- FirebaseSessions.podspec
- FirebaseSessions/Sources/FirebaseSessions.swift
Paired with: @jeremyjiang-dev 
- We haven't setup any SDKs with the Sessions SDK as a dependency, so this should not go out to users (unless they specify it directly)
- We've only setup CocoaPods so far (for development), not SPM
- We were using [FunctionsComponent.swift](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseFunctions/Sources/Internal/FunctionsComponent.swift#L24-L33) as a reference. We see there is a protocol and initializer there. Our protocol isn't being called, and I'm not sure where their `functions(...` protocol method is being called
- Is the protocol needed?
- It looks like it's needed as something to pass into the `Component` constructor
#no-changelog
#sessions
> Initial commit of Firebase Sessions SDK

- Firestore/Example/Tests/Integration/API/FIRCountTests.mm
Enable the integration tests for COUNT that were added in https://github.com/firebase/firebase-ios-sdk/pull/10254 now that the RunAggregationQuery RPC has been fully rolled out.
#no-changelog
> Enable COUNT integration tests, now that backend support has rolled out

- FirebaseDynamicLinks/Sources/FIRDynamicLinks.m
Removes comment from Firebase Dynamic Link since it is not longer relevant. Internal bug reference: b/242562229
> removes confusing comment

- .github/workflows/database.yml
- scripts/build.sh
Fix SPM watchOS tests for Xcode 14 CI
The `pod lib lint` watchOS tests remain broken. Details with `--verbose` here https://github.com/firebase/firebase-ios-sdk/actions/runs/3200880464/jobs/5228288507
#no-changelog
> Investigate watchOS CI

- .github/workflows/abtesting.yml
- .github/workflows/auth.yml
- .github/workflows/crashlytics.yml
- .github/workflows/database.yml
- .github/workflows/functions.yml
- .github/workflows/messaging.yml
- .github/workflows/remoteconfig.yml
- .github/workflows/sessions.yml
- .github/workflows/shared-swift.yml
- .github/workflows/storage.yml
`pod lib lint` does not work for watchOS with Xcode 14. See https://github.com/CocoaPods/CocoaPods/issues/11558
This PR disables the tests for now.
Created #10316 to track restoring the tests.
> Disable watchOS pod lib lint tests

- FirebaseCoreExtension.podspec
- FirebaseFirestoreSwift.podspec
- Package.swift
- FirebaseCoreExtension was added as a dependency to FirebaseFirestoreSwift in
#10167. After this was done, FirebaseFirestoreSwift still not have a direct dependency on FirebaseCore. FirestoreSwift directly depended on FirebaseCoreExtension and **transitively** depended on FirebaseCore. We suspect this caused a linker issue that showed up in the [nightlies](https://github.com/firebase/firebase-ios-sdk/issues/10293#issuecomment-1271666340).
It seems that all other SDKs that currently depend on FirebaseCoreExtension
also directly depend on FirebaseCore (with the exception of FirebaseFirestoreSwift):
```shell
➜  firebase-ios-sdk git:(master) ✗ 
‣ git grep -C 5 "dependency 'FirebaseCoreExtension'" *.podspec …
```
> [FirestoreSwift] Add FirebaseCore dependency to avoid linker issues

- Firestore/CHANGELOG.md
Meant to roll this into the other Firestore PRs. The count API PR has the changelog entry under `# Unreleased`; moving it under `# 10.0.0`.
> [Firestore] Update CHANGELOG for new Count API (#10246)

- FirebaseCore/CHANGELOG.md
- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
- ReleaseTooling/Sources/ZipBuilder/TargetPlatform.swift
Apple announced the discontinuation of bitcode support.
This drops the zip distribution size from 367MB to 290MB
> Discontinue bitcode inclusion

- Dangerfile
- FirebaseCore/Sources/Public/FIRTestFile.h
Prevents regression of #10301.
Note that this PR doesn't check which umbrella header is modified, so a change that updates multiple SDKs could still not warn if not all of the requisite umbrella headers were updated.
> Add new danger check

- .github/workflows/firestore.yml
Undo the switch of the Firestore sanitizer builds to run on ubuntu instead of macos, made in https://github.com/firebase/firebase-ios-sdk/pull/9488.
#no-changelog
> Firestore: run sanitizers on macos in addition to ubuntu

- FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
- FirebaseRemoteConfig/Sources/Private/RCNConfigFetch.h
- FirebaseRemoteConfig/Sources/RCNConfigFetch.m
- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
- FirebaseRemoteConfig/Tests/Unit/RCNPersonalizationTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
- FirebaseRemoteConfigSwift/Tests/ObjC/FetchMocks.m
Revert NO_CHANGE fix as part of go/realtime-rc-forward-compatibility
> Revert "Realtime rc no change (#10188)"

- Dangerfile
The change does not correctly flag additions to the umbrella header.
> Revert "Add new danger check (#10338)"

- FirebaseCore/CHANGELOG.md
Added an entry explaining the removal of bitcode in the Firebase 10.1.0 (M123) release.
> Add changelog entry for bitcode removal in Firebase 10.1.0

- FirebaseStorage/Sources/Internal/StorageGetDownloadURLTask.swift
The firebase storage emulator returns JSON that contains a `metadata` object that is empty (implying swift `[String: Any]` type), whereas the cloud API does not (so the current swift `[String: String]` type works for it)
Thus, attempting to get a download URL against the storage emulator fails since the type checking fails though it does work against cloud APIs.
This may be a bug in the firestore emulator, as it may not be emitting JSON correctly,
However following the theory of "be conservative in what you emit, but liberal in what you accept", it seems slightly better to make a patch here so an empty metadata object is okay. I could be wrong! That would require communication direct between firebase-ios-sdk + firebase-tools crew and could easily be sorted out I'm sure.
In the meantime, …
> Tolerate nested JSON objects while getting URL

- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Tests/Unit/StorageMetadataTests.swift
> Test and Changelog for 10370

- FirebaseMessaging/CHANGELOG.md
- FirebaseMessaging/Sources/FIRMessagingUtilities.h
- FirebaseMessaging/Sources/FIRMessagingUtilities.m
- FirebaseMessaging/Tests/UnitTests/FIRMessagingUtilitiesTest.m
Fix for https://github.com/firebase/firebase-ios-sdk/issues/10147
In versions of Xcode prior to Xcode 14, whenever a watch app was created, Xcode always created two targets 
Watch App (contained assets for the app but no code)
Watch Kit Extension (contained the code / logic for the app)
Xcode 14 onwards, no watch kit extension target is created for watchOS apps. There is a consolidated Watch App target that contains both code and assets. 
Firebase Messaging code used to strip out the watch extension suffix and use the watch app bundle ID for FCM registration. Since there is no extension anymore, the code is inadvertently stripping out the last component of the app bundle identifier itself, resulting in an incorrect bundle ID being used for FCM registration. 
This change detects if code is …
> [Messaging] Xcode 14 watchkit extension bundle id fix

- FirebaseSessions.podspec
- FirebaseSessions/Sources/EventGDTLogger.swift
- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/GoogleDataTransport+GoogleDataTransportProtocol.swift
- FirebaseSessions/Sources/Identifiers.swift
- FirebaseSessions/Sources/Logger.swift
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.h
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.m
- FirebaseSessions/Sources/SessionCoordinator.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Sources/Time.swift
- FirebaseSessions/Tests/Unit/IdentifiersTests.swift
- FirebaseSessions/Tests/Unit/InitiatorTests.swift
- FirebaseSessions/Tests/Unit/Mocks/MockGDTLogger.swift
- FirebaseSessions/Tests/Unit/Mocks/MockIdentifierProvider.swift
- FirebaseSessions/Tests/Unit/Mocks/MockTimeProvider.swift
- FirebaseSessions/Tests/Unit/SessionCoordinatorTests.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
- FirebaseSessions/Tests/Unit/TestNanoPBHelpers.swift
- Adds functions for interacting with nanopb. Some parts of this were difficult to do in Swift, so I had to do them in ObjC.
- Adds SessionStartEvent as an abstraction over the proto
- Adds FireLog dependency, and logs events to FireLog
#no-changelog
> [Sessions] Add SessionStartEvent wrapper for building the nanopb proto

- FirebaseSessions.podspec
- FirebaseSessions/Sources/ApplicationInfo.swift
- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.h
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.m
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/Mocks/MockApplicationInfo.swift
- FirebaseSessions/Tests/Unit/SessionCoordinatorTests.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
Adds ApplicationInfo class and fills in parts of ApplicationInfo in the proto
A few fields remain because they need to be moved into a centralized place. These will likely be moved to GoogleUtilities so that Crash, Perf, and Sessions can all share the same code. For example, we moved osName to GoogleUtilities in this PR: https://github.com/google/GoogleUtilities/pull/89
We will attempt to move the following to GoogleUtilities:
- device_model
- network_connection_info
- mcc_mnc - I did fill this in because the code is small, but I will attempt to move it to GoogleUtilities as well
For development_platform_name/version, I had originally thought we would need to fetch these from the Crashlytics SDK because they are set via an API and not read from the environment. This does come with a big …
> [Sessions] Add ApplicationInfo for filling in the proto

- scripts/style.sh
This should fix `check` flakes in GDT repo (see https://github.com/google/GoogleDataTransport/pull/87). The issue seemed to be that the styling paths to be excluded are case-sensitive. This has preivously worked for some time so maybe the GHA runner was configured differently.
Previously experimented with whether this would work in #10423
#no-changelog
> [Infra] Fix ignoring of Mint sources when checking style

- FirebaseAppDistribution/CHANGELOG.md
- FirebaseAppDistribution/Sources/FIRAppDistribution.m
- FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
- FirebaseAppDistribution/Sources/Public/FirebaseAppDistribution/FIRAppDistribution.h
- scripts/make_release_notes.py
> Make App Distribution compatible with swizzling-disabled implementations

- FirebaseSessions/Sources/Identifiers.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/IdentifiersTests.swift
- FirebaseSessions/Tests/Unit/Mocks/MockIdentifierProvider.swift
- Before, Session IDs would persist forever. So the previousSessionID would be set to the last sessionID, even if the app had cold started.
- Now, previousSessionID is only set if the sessionID rolls over in a background-foreground initiation. It is not persisted across runs of the app
#no-changelog
> [Sessions] Fix how Session ID is generated

- ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
Looks like #10424 failed to update the manifest ... and the nightly zip failed as a result.
> Update manifest for 10.2.0

- cmake/external/nanopb.patch
Fix the following build error if the python version is 3.11:
```
Traceback (most recent call last):
File "Firestore/Protos/tmppvd8n0nr.py", line 431, in <module>
main()
File "Firestore/Protos/tmppvd8n0nr.py", line 62, in main
parsed_files = nanopb_parse_files(request, options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "Firestore/Protos/tmppvd8n0nr.py", line 202, in nanopb_parse_files
parsed_files[fdesc.name] = nanopb.parse_file(fdesc.name, fdesc, options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "build/external/src/nanopb/generator/nanopb_generator.py", line 1644, in parse_file
Globals.separate_options = read_options_file(open(optfilename, "rU"))
^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
```
Example: …
> nanopb.patch: fix nanopb `invalid mode: 'rU'` build error in python 3.11

- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
- Firestore/Example/Tests/SpecTests/json/recovery_spec_test.json
Update the spec tests from https://github.com/firebase/firebase-js-sdk/tree/master/packages/firestore/test/unit/specs/ at commit https://github.com/firebase/firebase-js-sdk/commit/9e9ee7ba3383237e0b92ad8183dd0f12640f4f3a.
Note: The spec test changes from https://github.com/firebase/firebase-js-sdk/pull/6624 were manually reverted in this PR because otherwise the tests will fail. This will be fixed, and the spec tests updated, by https://github.com/firebase/firebase-ios-sdk/pull/10437.
#no-changelog
> Firestore: Update spec tests

- CONTRIBUTING.md
- README.md
- scripts/setup_check.sh
- scripts/style.sh
Related to clang-format not managing brew versioning properly. See https://github.com/llvm/llvm-project/issues/49340
#no-changelog
> [Infra] Bump clang-format to v15

- FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m
In the latest Xcode and macOS versions, APNs is now supported in simulators. Before that, phone auth will always fallback to the recaptcha verification flow.
Since FCM doesn't support iOS 16 simulators yet, https://github.com/firebase/firebase-ios-sdk/issues/9968, this change force the phone auth flow fallback to recaptcha in simulators.
> Force to recaptcha verification flow for phone auth in Simulators

- scripts/nanopb/generate_protos.sh
Getting a working `python` command on macOS is non-trivial. This error message helps with that.
Proof the technique works:
> Update nanopb generator script to check for python and help

- FirebaseSessions/ProtoSupport/Protos/sessions.proto
- FirebaseSessions/Protogen/nanopb/sessions.nanopb.c
- FirebaseSessions/Protogen/nanopb/sessions.nanopb.h
Add the proto field containing the development environment that can be used to differentiate Autopush/Staging/Prod for Firelog/backend to differentiate.
#no-changelog
> Add development environment to the proto message ApplicationInfo.

- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.h
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.m
- FirebaseSessions/Sources/SessionStartEvent.swift
This CL does the following:
- Fixes a critical bug where apple_application_info wasn't encoded correctly. This is because we didn't have the oneof that we're choosing specified using which_platform_info.
#no-changelog
> [Sessions] Fix oneof specification for nanopb

- FirebaseSessions/Sources/Development/DevEventConsoleLogger.swift
- FirebaseSessions/Sources/Development/NanoPB+CustomStringConvertible.swift
- FirebaseSessions/Sources/EventGDTLogger.swift
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.h
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.m
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/TestApp/AppQualityDevApp.xcodeproj/xcshareddata/xcschemes/AppQualityDevApp_iOS.xcscheme
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
This CL does the following:
- Moved to https://github.com/firebase/firebase-ios-sdk/pull/10459 ~Fixes a critical bug where apple_application_info wasn't encoded correctly. This is because we didn't have the `oneof` that we're choosing specified using `which_platform_info`.~
- Fixes a critical bug where session_id and other strings were commonly printing as `<NULL>` even after being set. This was due to a string encoding proble.
- This surely impacts other SDKs, including Crashlytics.
- https://stackoverflow.com/questions/33287801/nsstring-datausingencoding-gives-garbage-at-end-of-string-in-ios-9-not-ios
- Adds new tests to SessionStartEventTests so that in addition to ensuring the fields are correct, it encodes and decodes the protos and does the same assertions against the decoded proto. …
> [Sessions] Log events to console command line flag, fix encoding

- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.m
Follow on from https://github.com/firebase/firebase-ios-sdk/pull/10428, we found that the encoding "fix" resulted in explicit null terminators in the backend, which broke parsing and created extra characters in the string. 
- Turns out encoding was correct, and decoding was the problem
- The fix is to revert the encoding change that adds null terminators, and instead ad null terminators to the decoding.
#no-changelog
> [Sessions] Revert broken encoding fix and fix decoding

- FirebaseStorage/Tests/Integration/StorageIntegration.swift
- FirebaseStorage/Tests/ObjCIntegration/FIRStorageIntegrationTests.m
Investigate internal b/258460959. I added tests to confirm the cancelled error code is still returned after a task cancel.
#no-changelog
> Add error code testing after cancel

- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Sources/Internal/StorageDeleteTask.swift
- FirebaseStorage/Sources/Internal/StorageGetDownloadURLTask.swift
- FirebaseStorage/Sources/Internal/StorageGetMetadataTask.swift
- FirebaseStorage/Sources/Internal/StorageListTask.swift
- FirebaseStorage/Sources/Internal/StorageUpdateMetadataTask.swift
- FirebaseStorage/Sources/StorageDownloadTask.swift
- FirebaseStorage/Sources/StorageUploadTask.swift
Use dedicated queue for Storage uploads and downloads instead of global queue. Fixes regression
introduced in 10.0.0 and restores the pre-10.0.0 behavior.
The Storage queue is created at https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseStorage/Sources/Storage.swift#L295
Fix #10487
> Use dedicated queue for Storage instead of global queue

- FirebaseMessaging/CHANGELOG.md
- FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.m
Fixes https://github.com/firebase/firebase-ios-sdk/issues/9968
Xcode 14 supports push notifications on iOS 16 Simulator when running on macOS 13. When these conditions exist, an APNS token is generated but if these conditions don't exist, an APNS token is not generated by iOS. Based on this, the change checks when APNS token is generated and if its running in a simulator. If this exists, the sandbox profile is used for push notifications.
Setup a sample app that ran on a iOS 16.1 simulator running on macOS 13. The APNS token was registered with FCM and I was able to send an alert to the FCM token to which this APNS token was mapped. 
When same setup was run on macOS 12.x, an APNS token doesn't get generated and no FCM token is generated. This is as expected.
> Xcode 14 - support push notifications in iOS simulator

- FirebaseStorage/Sources/Internal/StorageDeleteTask.swift
- FirebaseStorage/Sources/Internal/StorageGetDownloadURLTask.swift
- FirebaseStorage/Sources/Internal/StorageGetMetadataTask.swift
- FirebaseStorage/Sources/Internal/StorageListTask.swift
- FirebaseStorage/Sources/Internal/StorageUpdateMetadataTask.swift
- FirebaseStorage/Sources/StorageDownloadTask.swift
- FirebaseStorage/Sources/StorageReference.swift
- FirebaseStorage/Sources/StorageUploadTask.swift
- Fix Swift 6 errors generated with Build Setting: `Strict Concurrency Checking -> Complete`
- Consistent strong and weak `self` accessing
- Explicit `self` retains where necessary to ensure operations, including server uploads and completion blocks execute
> Fix strict concurrency checking errors

- Firestore/CHANGELOG.md
It looks like MultiDB support was added last week and missed the 10.2.0 release.
> Fix Firestore Changelog for 10.3.0

- FirebaseSessions/Sources/ApplicationInfo.swift
- `deviceSimulatorModel` can work on simulators and devices.
- It will also have similar outputs as `deviceModel` on a device.
Crashlytics will only use `deviceSimulatorModel`, so this PR updates Sessions to do the exact same thing.
#no-changelog
> [Sessions] Use deviceSimulatorModel only for compatibility with Crashlytics

- .github/workflows/performance.yml
Fix a typo that was running the ObjC tests twice and never the Swift tests
Thanks to @sunmou99 for pointing this out
> Run Performance Swift QS tests in CI

- FirebaseSessions/ProtoSupport/Protos/sessions.proto
- FirebaseSessions/Sources/ApplicationInfo.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
`bundle_short_version` is app display version, not the bundle id
#no-changelog
> [Sessions] Replace bundleID with appDisplayVersion

- cmake/external_rules.cmake
- cmake/firebase_utils.cmake
- cmake/python_setup.cmake
This PR modifies cmake builds to fail fast when calling cmake's built-in `execute_process()` function.
By default, `execute_process()` does not check the exit code of the child process. Therefore, if the child process fails then the cmake build process silently ignores the failure and carries on, usually causing strange errors later on. This PR makes it so that the build fails immediately upon execute_process() failing, making it much easier to diagnose the root problem.
> cmake: fail fast when execute_process() fails

- FirebaseSharedSwift/LICENSE
This directory includes Apple and Firebase licenses.
> Include Apache license with and without Runtime Exception

- FirebaseMessaging/CHANGELOG.md
- FirebaseMessaging/Sources/FIRMessaging.m
- FirebaseMessaging/Sources/NSError+FIRMessaging.h
- FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.m
- FirebaseMessaging/Tests/IntegrationTests/FIRMessagingPubSubTest.swift
- FirebaseMessaging/Tests/IntegrationTests/FIRMessagingTokenRefreshTests.swift
- FirebaseMessaging/Tests/UnitTests/FIRMessagingTest.m
FCM SDK should not vend an FCM Token when there is no APNS token available or set. This means SDK will no trigger a registration till an APNS Token is provided. 
Added unit test to check for NSError when declining FCM Token request. 
Tested following scenarios to check for regression - 
- Fresh install of app with keychain cleared.
- Reinstall of app via Xcode
- Fresh install of app with keychain not cleared. 
For each scenario, confirmed that a notification was sent as expected to the vended FCM Token.
> [Messaging] - Decline Registration when there is no APNS Token

- FirebaseSharedSwift/Sources/third_party/FirebaseDataEncoder/FirebaseDataEncoder.swift
- FirebaseSharedSwift/Tests/third_party/DataEncoderTests.swift
- Firestore/Swift/CHANGELOG.md
- Firestore/Swift/Source/Codable/EncoderDecoder.swift
Internal b/262520379
Version 10.x changed the default behavior of coding and decoding `Data` types in Firestore. This PR restores the old behavior by implementing the `blob` data encoding and decoding strategy.
> Restore 9.x Firestore Data Codable behavior

- Example/FirestoreSample/FirestoreSample/GoogleService-Info.plist
- Example/FirestoreSample/firestore.rules
Updates so instructions at https://github.com/firebase/firebase-ios-sdk/blob/master/Example/FirestoreSample/README.md work:
- Dummy GoogleService-Info.plist (unused with emulator)
- Far out date for rules
> Fix build and run issues for Firestore Example

- Crashlytics/UnitTests/FIRCLSCompactUnwindTests.m
- Crashlytics/UnitTests/FIRCLSDwarfTests.m
- Crashlytics/UnitTests/FIRCLSInternalReportTests.m
- Crashlytics/UnitTests/FIRCLSMachO/FIRCLSMachOBinaryTests.m
- Crashlytics/UnitTests/FIRCLSMachO/FIRCLSMachOTests.m
- Crashlytics/UnitTests/FIRCLSMachO/FIRCLSdSYMTests.m
- Crashlytics/UnitTests/FIRCLSProcessReportOperationTests.m
- Crashlytics/UnitTests/FIRCLSReportAdapterTests.m
- Crashlytics/UnitTests/FIRCLSReportManagerTests.m
- Crashlytics/UnitTests/FIRCLSSymbolResolverTests.m
- Crashlytics/UnitTests/FIRCrashlyticsReportTests.m
- FirebaseABTesting/Tests/Unit/Utilities/ABTTestUtilities.m
- FirebaseDatabase/Tests/Unit/FSyncPointTests.m
- FirebasePerformance/Tests/Unit/FPRTestUtils.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
The name of the C function used to access the resource bundle is incorrect. I suspect the C function name changed as a result of reorganizing the target over time. I suggest the `SWIFTPM_MODULE_BUNDLE` macro as it is more future proof.
This was reproducible running `swift test --filter FirebaseRemoteConfigSwift` on `master`. I'm not sure how this didn't surface earlier.
#no-changelog
> [Infra] Favor `SWIFTPM_MODULE_BUNDLE` macro over C function across repo

- FirebaseSharedSwift/Tests/third_party/DataEncoderTests.swift
Small refactor to simplify the error handling in `testDecodingBase64StringAsBlobData` by making it a throwing test. As a side-effect, this will prevent the test from continuing if an earlier step throws (similar to `continueAfterFailure` set to `false`) which may make failures easier to debug.
Updated to use `XCTUnwrap` to explicitly check for optionals when performing type coercion.
Note: Did not refactor other tests in the file to reduce diversion from the original `swift/test/stdlib/TestJSONEncoder.swift` source.
#no-changelog
> [FirestoreSharedSwift] Write base64 decode test as throwing XCTest

- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuthErrors.h
- FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.h
- FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m
- FirebaseAuth/Sources/Utilities/FIRAuthInternalErrors.h
- FirebaseAuth/Tests/Sample/AuthSample.xcodeproj/project.pbxproj
The SDK did not handle the errors returned from a cloud blocking function (auth). The message sent from the backend will now be presented in the NSError.
> added handling of error returned from a blocking cloud function

- scripts/make_release_notes.py
Fixes an issue where updates made in #10212 conflict with standardized release note header sections.
https://github.com/firebase/firebase-android-sdk/pull/4537 moves this change to the Android repo.
> Revert "Include subheaders in script output (#10212)"

- FirebaseAuthExchange/Apps/AuthExchange/AuthExchange/AuthExchangeApp.swift
- FirebaseAuthExchange/Apps/AuthExchange/Podfile
- FirebaseAuthExchange/Apps/ObjcSample/ObjcSample/main.m
- FirebaseAuthExchange/Apps/ObjcSample/Podfile
- FirebaseAuthExchange/Sources/third_party/swift_protobuf/LICENSE
- FirebaseAuthExchange/Sources/third_party/swift_protobuf/METADATA
- FirebaseAuthExchange/Sources/third_party/swift_protobuf/ProtobufDurationUtil.swift
- scripts/check_imports.swift
Added a helper method to deserialize [`google.protobuf.Duration`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration) fields from their JSON representation. This method is derived from [`Google_Protobuf_Duration+Extensions.swift`](https://github.com/apple/swift-protobuf/blob/ab3a58b7209a17d781c0d1dbb3e1ff3da306bae8/Sources/SwiftProtobuf/Google_Protobuf_Duration+Extensions.swift) in the [`swift-protobuf`](https://github.com/apple/swift-protobuf) project.
#no-changelog
<a data-ca-tag href="https://codeapprove.com/pr/firebase/firebase-ios-sdk/10653"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>
> [Auth Exchange] Add Duration parser from swift-protobuf

- Crashlytics/generate_project.sh
- FirebaseSessions/generate_testapp.sh
After running `generate_testapp`, since Crashlytics is now one of the targets, it copies the run and upload-symbols tools from Crashlytics into the root directory of firebase-ios-sdk. To prevent these accidental duplications, this updates the scripts to delete them.
> Delete extra copies of the Crashlytics tools for testapps

- FirebaseMessaging/Apps/SampleStandaloneWatchApp/SampleStandaloneWatchApp.xcodeproj/project.pbxproj
- FirebaseMessaging/Apps/SampleStandaloneWatchApp/SampleStandaloneWatchAppWatchApp/SampleStandaloneWatchAppApp.swift
The sample app should use CocoaPods or Swift Package Manager, but not both. I removed SPM. @aashishpatil-g, let me know if you'd prefer this sample app to use SPM instead.
Fixes #10649
#no-changelog
> [Infra] Remove firebase-ios-sdk package from messaging sample app

- FirebaseSessions/Tests/Unit/SessionCoordinatorTests.swift
This section was missing coverage:
#no-changelog
> Add test for missing SessionCoordinator code coverage

- .github/workflows/health-metrics-release.yml
When I published 10.4.0., I got an email notification regarding the `health-metrics-release.yml` [failing](https://github.com/firebase/firebase-ios-sdk/actions/runs/3943423199).
Looks like `google-github-actions/setup-gcloud` action repo switched from `master` → `main`.
#no-changelog
> [Infra] Fix action name in 'health-metrics-release.yml'

- .github/workflows/update-cpp-sdk-on-release.yml
When I published 10.4.0., I got an email notification regarding the update-cpp-sdk-on-release.yam [failing](https://github.com/firebase/firebase-ios-sdk/actions/runs/3943423218).
I think that version may not be installed on the VM so I pinned the `checkout` action to the major version.
#no-changelog
> [Infra] Update 'actions/checkout' version in 'update-cpp-sdk-on-release.yaml'

- FirebaseSessions/Sources/Public/SessionsSubscriber.swift
Both https://github.com/firebase/firebase-ios-sdk/pull/10704 and https://github.com/firebase/firebase-ios-sdk/pull/10682 requires this change, otherwise Crashlytics and Performance can't access the session id in the payload given by Sessions SDK.
#no-changelog
> change sessionId from the subscriber payload to public

- Crashlytics/CHANGELOG.md
- Crashlytics/Crashlytics/FIRCrashlytics.m
- FirebaseCrashlytics.podspec
- Package.swift
Alternative to https://github.com/firebase/firebase-ios-sdk/pull/10619 where the dependency is required.
Replaces https://github.com/firebase/firebase-ios-sdk/pull/10636
> Add required dependency between Crashlytics and Session

- Crashlytics/Crashlytics/Helpers/FIRCLSDefines.h
- FirebaseAuthExchange/Sources/Models/ExchangeServiceModels.swift
- FirebaseAuthExchange/Tests/Unit/ExchangeServiceModelTests.swift
Added a model for the response to an `ExchangeInstallationAuthTokenRequest` or `ExchangeCustomTokenRequest`.
#no-changelog
> [Auth Exchange] Add a model for an ExchangeTokenResponse

- FirebaseSessions/Sources/Settings/LocalOverrideSettings.swift
#no-changelog
When I put in a Plist value:
When we cast as a String, it returns nil because it isn't a String
Fix is to cast as Double:
> Fix Sessions Local Overrides

- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Sources/Storage.swift
- FirebaseStorage/Sources/StorageUploadTask.swift
- FirebaseStorage/Tests/Integration/StorageIntegration.swift
Fix #10137
Googlers: API proposal at [go/firebase-storage-chunk-size](http://goto.google.com/firebase-storage-chunk-size)
> Add Storage API to limit upload chunk size

- FirebaseMessaging/Sources/NSError+FIRMessaging.h
- FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.m
Fix for https://github.com/firebase/firebase-ios-sdk/issues/10707
Added a check for self within the block. Found some other places in the file and fixed those too. 
#no-changelog
> [Messaging] - Fix crash for strongSelf dereference

- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
We're treating data collection off as SDK not installed
#no-changelog
> Prevent capturing network info when Perf data collection off

- FirebaseAuth/Tests/Sample/ApiTests/FacebookAuthTests.m
- FirebaseAuth/Tests/Sample/SwiftApiTests/FacebookTests.swift
Fix #10738 
Created #10752 to track update of Sample and restoration of tests
> Disable breaking out-of-date Facebook Auth integration tests

- Crashlytics/Crashlytics/Components/FIRCLSContext.m
Fixes #10104.
In `FIRCLSContextInitialize()`,
1.  A instance of the `FIRCLSContextInitData` struct is assigned to `initDataObj`.
2.  The pointer of it is assigned to `initData`.
3.  The `initData` is passed to asynchronous functions and captured by blocks.
4.  Wait the asynchornous processes for 5 seconds.
5.  The `initDataObj` and the properties of it is released as soon as the `FIRCLSContextInitialize` is exited.
`FIRCLSContextRecordMetadata` is called in the asynchronous function, and in the function,
1.  `FIRCLSUnlinkIfExists` and `FIRCLSFileInitWithPath` access the file system.
2.  `FIRCLSContextRecordIdentity` use `initData`.
If either `FIRCLSUnlinkIfExists` or `FIRCLSFileInitWithPath` takes longer than 5 seconds to process, `FIRCLSContextRecordIdentity` access `initData` that was …
> Fix a crash on FIRCLSFileWriteString

- FirebaseRemoteConfig/Sources/RCNConfigContent.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
Compare keyed P13n metadata using `isEqualToDictionary:`. P13n metadata are [stored in dictionaries](https://github.com/firebase/firebase-ios-sdk/blob/48b529dd1598242004948919273486f7416b4b98/FirebaseRemoteConfig/Sources/RCNConfigContent.m#L35-L39), ex. `{"param_key": NSDictionary, "param_key_2": NSDictionary}`.
Comparing as strings raises an exception: `'NSInvalidArgumentException', reason: '-[__NSDictionaryI isEqualToString:]: unrecognized selector sent to instance 0x600003f63f80'
terminating with uncaught exception of type NSException`
#no-changelog
> Compare p13n metadata values as dictionaries.

- FirebaseAuth.podspec
- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Storage/FIRAuthKeychainServices.m
- This keychain interface was missed when auditing Firebase's keychain access leading up to Firebase 9.6.0.
- Related to go/firebase-macos-keychain-popups
- I could not find a better way to do this and resorted to this approach when I started to spin my wheels. I'm open to any better ideas...
Fixes #10582
> [Auth] Add 'kSecUseDataProtectionKeychain' flag to keychain access

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthCredential.h
- FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthCredential.m
- FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthProvider.m
- FirebaseAuth/Sources/Backend/RPC/FIRSignInWithGameCenterRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRSignInWithGameCenterRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRSignInWithGameCenterResponse.h
- FirebaseAuth/Sources/Backend/RPC/FIRSignInWithGameCenterResponse.m
- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Tests/Unit/FIRSignInWithGameCenterTests.m
New verification method `fetchItems(forIdentityVerificationSignature:)` https://developer.apple.com/documentation/gamekit/gklocalplayer/3516283-fetchitems
> Use team player ID, game player ID and fetchItems for signature verification

- Crashlytics/Crashlytics/Components/FIRCLSContext.h
- Crashlytics/Crashlytics/Components/FIRCLSContext.m
- Crashlytics/Crashlytics/Controllers/FIRCLSContextManager.h
- Crashlytics/Crashlytics/Controllers/FIRCLSContextManager.m
- Crashlytics/Crashlytics/Controllers/FIRCLSManagerData.h
- Crashlytics/Crashlytics/Controllers/FIRCLSManagerData.m
- Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.h
- Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m
- Crashlytics/Crashlytics/FIRCrashlytics.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordIdentity.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSRecordIdentity.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
- Crashlytics/UnitTests/FIRCLSContextManagerTests.m
- Crashlytics/UnitTests/FIRCLSOnDemandModelTests.m
- Crashlytics/UnitTests/FIRRecordExceptionModelTests.m
> Update Crashlytics SDK to send Session ID in crash reports

- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
Fixes this bug: https://b.corp.google.com/issues/265943796. There was no checks for background/active connections for the retry method causing it to burn out it's retries when the app is in the background. Adding these checks should prevent this.
> Realtime RC 1P Bug Fix: Add checks for retryHttpConnection method

- FirebaseAppDistribution/Sources/FIRAppDistribution.m
This was errantly updated to the correct new path without updating the host from `appdistribution.firebase.dev`  to `appdistribution.firebase.google.com`.
See [10772](https://github.com/firebase/firebase-ios-sdk/issues/10772)
> Fix tester sign in URL

- FirebaseAuth/Sources/User/FIRUser.m
Remove unused imports (the imported types have been since re-defined in Swift)
#no-changelog
> [auth-swift] Remove commented-out imports

- FirebaseAuth.podspec
- FirebaseAuth/Sources/Public/FirebaseAuth/FirebaseAuth.modulemap
- scripts/build_private_module_map.rb
- A manual module map is unneeded. CocoaPods will generate one. It seems to work fine with the recently added private module map.
- This is nice because achieving interoperability that's on par with SwiftPM does not require any new build files–– just the build script.
#no-changelog
> [auth-swift] Remove `module.modulemap` as it is unneeded

- FirebaseAuth/Sources/Swift/Backend/IdentityToolkitRequest.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/GetAccountInfoRequest.swift
- FirebaseAuth/Sources/Swift/Backend/VerifyClientRequest.swift
- FirebaseAuth/Tests/Unit/FIRIdentityToolkitRequestTests.m
This fixes the one test failure we've had for awhile.
It seems that running the unit tests from Swift will fail with NSInternalInconsistencyException from https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAuth/Sources/Auth/FIRAuth.m#L443 but not when run from Objective C.
This change fixes that problem by not calling `Auth.auth()` too early.
> Fix unit test failure

- FirebaseSessions/README.md
- FirebaseSessions/Sources/Development/DevEventConsoleLogger.swift
- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/SessionCoordinator.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
Updated README: https://github.com/firebase/firebase-ios-sdk/blob/bc76232a4e0bf58daf00b7c3c4640805722d1477/FirebaseSessions/README.md
Example with `-FIRDebugEnabled`
```
[FirebaseSessions][I-SES000000] Version 10.4.0
[FirebaseSessions][I-SES000000] [Settings] Cache is not expired, no fetch will be made.
[FirebaseSessions][I-SES000000] Initiated new Session with ID: 3152c81f3bad4b518c2a1e0b4459509f
[FirebaseSessions][I-SES000000] Logging events using fast QOS due to running on a simulator
[FirebaseSessions][I-SES000000] Printing Session Event due to "-FIRSessionsDebugEvents" command line argument
[FirebaseSessions][I-SES000000] Successfully logged Session Start event to GoogleDataTransport
```
#no-changelog
> [Sessions] Audit logging and update README with strategy

- FirebaseSessions/Sources/Development/NanoPB+CustomStringConvertible.swift
- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Tests/Unit/FirebaseSessionsTests+DataCollection.swift
Before:
```
Session Event:
...
session_sampling_rate: 0.0
...
log_environment: _firebase_appquality_sessions_LogEnvironment(rawValue: 3)
```
After:
```
Session Event:
...
session_sampling_rate: 1.0
...
log_environment: PROD
```
#no-changelog
> Fix Session Event printout for sampling, log_environment

- ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
Stage and release Sessions for 10.6.0 and beyond
Note, the zip release build will fail until Sessions is actually staged.
> Add Sessions to release manifest

- FirebaseMessaging/CHANGELOG.md
- FirebaseMessaging/Sources/FIRMessaging.m
The FirebaseApp.configure() flow triggers a FCM token fetch, which can be racy and occur before we have received and set an APNS token.  The change in this PR validates that we have an APNS token in the configure flow before fetching the FCM token. 
This PR addresses the scenario 1 identified in this comment - https://github.com/firebase/firebase-ios-sdk/issues/10679#issuecomment-1402776795
Should fix https://github.com/firebase/firebase-ios-sdk/issues/10742
> [Messaging] - Validate APNS token in the configure flow

- .spi.yml
Added a Swift Package Index [manifest file](https://swiftpackageindex.com/SwiftPackageIndex/SPIManifest/documentation) that specifies an [external documentation link](https://swiftpackageindex.com/swiftpackageindex/spimanifest/0.15.0/documentation/spimanifest/commonusecases#Configure-a-documentation-URL-for-existing-documentation) to the "Add Firebase to your Apple project" [guide](https://firebase.google.com/docs/ios/setup). This will result in the guide being linked from https://swiftpackageindex.com/firebase/firebase-ios-sdk.
Testing: Validated the manifest file using the [validate-spi-manifest](https://swiftpackageindex.com/swiftpackageindex/spimanifest/0.15.0/documentation/spimanifest/validation) tool.
#no-changelog
> [SPI] Add SPIManifest for external docs link

- FirebaseAuth.podspec
- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/Backend/FIRAuthRequestConfiguration.h
- FirebaseAuth/Sources/Backend/FIRAuthRequestConfiguration.m
- FirebaseAuth/Sources/Backend/FIRIdentityToolkitRequest.m
- FirebaseAuth/Sources/MultiFactor/FIRMultiFactorResolver+Internal.h
- FirebaseAuth/Sources/MultiFactor/FIRMultiFactorResolver.m
- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.h
- FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m
- FirebaseAuth/Tests/Unit/FIRIdentityToolkitRequestTests.m
- FirebaseAuth/Tests/Unit/FIRMultiFactorResolverTests.m
Pass auth instance in request configure and use it to:
1. retrieve the associated tenant ID for requests https://github.com/firebase/firebase-ios-sdk/issues/10748
2. store the associated auth instance in MFA resolver https://github.com/firebase/firebase-ios-sdk/issues/10690
Fix #10748 
Fix #10690
> Multi-app fix

- .spi.yml
Updated the [Swift Package Index](https://swiftpackageindex.com) manifest file (.spi.yml) to specify "Google, Inc." as the [authors](https://swiftpackageindex.com/swiftpackageindex/spimanifest/0.15.0/documentation/spimanifest/manifest/metadata-swift.struct/authors) of the [package](https://swiftpackageindex.com/firebase/firebase-ios-sdk). This matches the authors specified in our [podspecs](https://github.com/firebase/firebase-ios-sdk/blob/6d1e7f5fae50b8a0f2bfc753cf59c835faa0a987/FirebaseCore.podspec#L12).
Testing: Validated the manifest file using the [validate-spi-manifest](https://swiftpackageindex.com/swiftpackageindex/spimanifest/0.15.0/documentation/spimanifest/validation) tool.
#no-changelog
> [SPI] Set "Google" as the author on Swift Package Index

- FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthProvider.m
The method [`fetchItemsForIdentityVerificationSignature:`](https://developer.apple.com/documentation/gamekit/gklocalplayer/3516283-fetchitemsforidentityverificatio) is marked as available only on tvOS 13.5+ in Xcode 13 (tvOS 15 SDK) but was extended to tvOS 13.4.8+ in Xcode 14 (tvOS 16 SDK).
Updated the availability check to limit to tvOS 13.5+ when compiling with Xcode 13.
#no-changelog
> [Auth] Fix FIRGameCenterAuthProvider warning on Xcode 13

- FirebaseAppCheck/Sources/Core/FIRAppCheckSettings.m
Stopped synthesizing a backing instance variable for the `isTokenAutoRefreshEnabled` property in `FIRAppCheckSettings` because it is unused, resulting in a warning when `-Wunused-property-ivar` is enabled. Replaced `@synthesize` with `@dynamic`, which resolves the following error when building in google3 (where this warning is treated as an error):
> FIRAppCheckSettings.m:92:1: error: ivar '_isTokenAutoRefreshEnabled' which backs the property is not referenced in this property's accessor [-Werror,-Wunused-property-ivar]
<details>
<summary>Details</summary>
We are providing the `- (BOOL)isTokenAutoRefreshEnabled` and `- (void)setIsTokenAutoRefreshEnabled:` implementations directly and they are indirectly backed by the `isTokenAutoRefreshEnabledNumber` property.
> You use the `@dynamic` …
> [AppCheck] Fix unused isTokenAutoRefreshEnabled ivar warning

- FirebaseRemoteConfig/Sources/RCNConfigFetch.m
- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
Fix Fetch duplicate error by removing error and leaving a log, moving the completionHandler to the end of didReceiveMessage, and removing unused error code that was breaking a linting test
https://b.corp.google.com/issues/267714994
https://b.corp.google.com/issues/268242388
> Remove Fetch Duplicate error and fix API misuse error

- FirebaseAuth.podspec
- FirebaseAuth/Sources/Auth/FIRAuth_Internal.h
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Sources/Swift/Backend/AuthRequestConfiguration.swift
> [auth-swift] Depend on `CoreExtension` rather than including its sources

- FirebaseAuth/Sources/Swift/Storage/AuthKeychainServices.swift
`FirebaseAuth/Sources/Storage/FIRAuthKeychainServices.m` was ported to `FirebaseAuth/Sources/Swift/Storage/AuthKeychainServices.swift`. Since then, `FIRAuthKeychainServices.m` was updated in #10759. This PR updates the ported logic to match.
#no-changelog
> [auth-swift] Update AuthKeychainServices following #10759

- FirebaseAuth.podspec
- FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Sources/Swift/User/AdditionalUserInfo.swift
- FirebaseAuth/Tests/Unit/FIRAuthSerialTaskQueueTests.m
- FirebaseAuth/Tests/Unit/SwiftAPI.swift
- Build SwiftAPI Tests from CocoaPods
- Fix (Undo) breaking API changes discovered in iOS specific API tests
- API weirdness include `IDToken` and `UIDelegate` parameters that have historically been converted to `idToken` and `uiDelegate` for Swift (noted in spreadsheet)
- Update tests using `MultiFactorAssertion` and `MultiFactorInfo` that were relying on default initializers that should have been unavailable in Objective C (noted in spreadsheet)
- Restore disabled tests from #10819 in FIRAuthSerialTaskQueueTests.m that run for me in both iOS and macOS cc: @mortenbekditlevsen 
- Fixed decoder build warning in AdditionalUserInfo.swift
> [auth-swift] Test improvements

- FirebaseAuth/Sources/Backend/FIRAuthBackend.h
Resolves warning in CP and SPM builds. Removing didn't break the build so I think this is fine.
```
/Users/nickcooke/Developer/firebase-ios-sdk/FirebaseAuth/Sources/Backend/FIRAuthBackend.m:464:17: warning: method definition for 'clientErrorWithServerErrorMessage:errorDictionary:response:' not found [-Wincomplete-implementation]
@implementation FIRAuthBackend
^
/Users/nickcooke/Developer/firebase-ios-sdk/FirebaseAuth/Sources/Backend/FIRAuthBackend.h:179:1: note: method 'clientErrorWithServerErrorMessage:errorDictionary:response:' declared here
+ (nullable NSError *)clientErrorWithServerErrorMessage:(NSString *)serverErrorMessage
^
1 warning generated.
Build complete! (31.62s)
```
#no-changelog
> [auth-swift] Resolve missing implementation warning

- docs/FirebaseOptionsPerProduct.md
Added a note to clarify that `PLIST_VERSION` in `GoogleService-Info.plist` does not refer to the `<plist version="1.0">` declaration in the Property List file.
`PLIST_VERSION` is a field within the `<dict></dict>` in the plist file and is accurately listed as being unused.
#no-changelog
> [Docs] Add note clarifying PLIST_VERSION field

- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
- Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
- Firestore/core/src/api/query_core.cc
> Remove some query restrictions and add integration tests

- Crashlytics/CHANGELOG.md
- FirebaseAppDistribution/CHANGELOG.md
- FirebasePerformance/CHANGELOG.md
- Firestore/CHANGELOG.md
Updated the `Unreleased` CHANGELOG entries to `10.6.0` for the upcoming M128 release.
> [Release] Prepare CHANGELOGs for 10.6.0 release

- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
https://buganizer.corp.google.com/issues/268398841
Pass back server error if it is the 403 API enablement response. didReceiveResponse only has statusCode response while didReceiveData has the actual error message. So in order to know if the error message is the API enablement one, I check if the URL in is the data response.
> Return Server produced error if Http status code is 403 

- .github/workflows/auth.yml
- .github/workflows/health-metrics-presubmit.yml
- .github/workflows/health-metrics-release.yml
- .github/workflows/spectesting.yml
- FirebaseAuth/Sources/Swift/Auth/ActionCodeSettings.swift
- FirebaseAuth/Sources/Swift/AuthProvider/FederatedAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/OAuthCredential.swift
- FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/GetOOBConfirmationCodeRequest.swift
- FirebaseAuth/Sources/Swift/Backend/VerifyClientResponse.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- FirebaseAuth/Tests/Unit/FIRAuthAppCredentialManagerTests.m
- FirebaseAuth/Tests/Unit/FIRPhoneAuthProviderTests.m
- FirebaseAuth/Tests/Unit/FIRVerifyClientRequestTest.m
- FirebaseAuth/Tests/Unit/GetOOBConfirmationCode.swift
- FirebaseAuth/Tests/Unit/OAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/SwiftAPI.swift
pod-lib-lint tests(with --allow-warnings), catalyst, and quickstart tests are now green. 
- Disable unready CI jobs
- Fix two Swift property names that were auto-converted to lower case in ObjC SDK
- TODO: The API tests should test properties as well as methods
- Fix implementation error in VerifyClientResponse.swift exposed by failing unit tests
#no-changelog
> [auth-swift] Initial Green CI

- Crashlytics/CHANGELOG.md
nit: Added a bullet point to the change entry for `10.6.0` to keep the style consistent with previous releases.
> Fix Crashlytics CHANGELOG.md style nit

- .github/workflows/abtesting.yml
- .github/workflows/auth.yml
- .github/workflows/crashlytics.yml
- .github/workflows/database.yml
- .github/workflows/functions.yml
- .github/workflows/messaging.yml
- .github/workflows/remoteconfig.yml
- .github/workflows/sessions.yml
- .github/workflows/shared-swift.yml
- .github/workflows/storage.yml
Fix #10316
Now that CocoaPods is fixed with the release of 1.12.0, restore watchos CI
> Revert "Disable watchOS pod lib lint tests (#10315)"

- .github/workflows/spm.yml
- .github/workflows/zip.yml
- Package.swift
- scripts/check_firestore_symbols.sh
- Creates a workflow job to test for regressions within the `FirebaseFirestore.xcframework` where an unreferenced symbol is introduced.
- Tried writing in Swift but running xcodebuild via `Process` became a flaky headache.
- Unblocks #10896 
- As long as #10896 isn't merged, Firestore contains unlinked symbols. This workflow should pick them up and cause a failure. Once this PR is merged, I will rebase `#10896` on top of `master` and re-run CI. `#10896` should fix the failures. 
- There are some additional edge cases that I will introduce in a separate PR for the purpose of testing against this workflow.
#no-changelog
> [Infra] Add workflow for detecting unlinked Firestore symbols

- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/API/FSTFirestoreComponent.mm
- Some Objective-C symbols within Firestore are unreferenced and therefore aren't linked when using Firestore binary distro.  What this means is that clients would need to use the -ObjC linker flag to force link these symbols. This PR forces the linking to link via a trick C function–– avoiding the need for clients to pass the -ObjC linker flag.
cc: @peterfriese 
#no-changelog
> [Firestore] Programmatically link un-linked symbols

- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Sources/StorageError.swift
- FirebaseStorage/Tests/Integration/StorageAsyncAwait.swift
Historically, FirebaseStorage deconstructs and reconstructs underlying server errors into a different format. With this PR, we also provide the original underlying error via the more standard `NSUnderlyingErrorKey`.
Also add three types of tests:
- Test existing server error reconstruction
- Server error via `NSUnderlyingErrorKey`
- Demonstrate showing the reason for an `.unknown` Swift error (not from server) to help clarify #10889
A more complete solution to #10889 can be addressed with a small breaking change in the next major release.
> Provide server errors via the NSUnderlyingErrorKey

- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
- Firestore/Swift/Tests/Integration/QueryIntegrationTests.swift
> Reorganize OR query test

- FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h
Update Remote Config real-time reference docs to be more description and uniform. #no-changelog
> Update Remote Config real-time config update ref-docs

- Firestore/core/src/nanopb/fields_array.h
fields_array.h: add missing template specializations for bloom filter, added in #10823: google_firestore_v1_ExistenceFilter, google_firestore_v1_BloomFilter, and google_firestore_v1_BitSequence
> fields_array.h: add missing template specializations for bloom filter

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Auth/FIRAuth_Internal.h
- FirebaseAuth/Tests/Unit/FIRAuthUseUserAccessGroupTests.m
- Precursor to making Auth SDK more dependency injection friendly. The goal is to provide an Auth initializer that accepts a passed in keychain storage instance. In order to get there, I need to do some refactoring and am breaking it up into small PRs so the approach is more reviewable.
- This should be a no-op and not change behavior.
#no-changelog
> [auth-swift] Prep for keychain dependency injection (pt. 1)

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/SystemService/FIRAuthAppCredentialManager.h
- FirebaseAuth/Sources/SystemService/FIRAuthAppCredentialManager.m
- Generalize existing initializers that accept keychain wrapper types
#no-changelog
> [auth-swift] Migrate usage of `FIRAuthKeychainServices` to `id<FIRAuthSorage>`

- SymbolCollisionTest/Podfile
MLKit 4.0.0 is compatible with Firebase 10.x. Restore the integration testing and disable it again when discovering MLKit is incompatible with ARCore.
Fix #10359
> Verify MLKit integration with Firebase 10.x

- FirebaseAuth/Sources/Auth/FIRAuth.m
- Auth conforms to Core's library component protocol and implements the `appWillBeDeleted:` API.
- The implementation removes the Auth's instances stored info from the keychain.
- If we are injecting the keychain instance into Auth, we ideally are using the the injected version at cleanup time–– instead of creating this new one for cleanup purposes.
#no-changelog
> [auth-swift] Use stored keychain service at app cleanup

- Crashlytics/UnitTests/FIRCLSExistingReportManagerTests.m
- Nightlies reporting more Crashlytics flakes from over the weekend (#11012). 
- Could not reproduce but adding some logging to better understand the failures.
#no-changelog
> [Infra] Print state of invalid assertion to help identify cause of flake

- Crashlytics/UnitTests/FIRCLSExistingReportManagerTests.m
- A potential hint–– the last three times a test from this file failed in CI, it was the first test run in the file. This may mean another test is leaving some state behind. I'm proposing we copy some of the `tearDown` code into the `setUp` code to enforce a clean artifact directory.
- https://github.com/firebase/firebase-ios-sdk/actions/runs/4485746539/jobs/7889007887#step:5:972
- https://github.com/firebase/firebase-ios-sdk/actions/runs/4528004614/jobs/7974385037#step:5:454
- https://github.com/firebase/firebase-ios-sdk/actions/runs/4528004614/jobs/7974385037#step:5:997
#no-changelog
> [Infra] Remove test artifact directory in test set up

- FirebaseAuth/Sources/Swift/Backend/RPC/VerifyAssertionRequest.swift
- FirebaseAuth/Tests/Unit/VerifyAssertionTests.swift
- I was seeing non-deterministic flakes locally and tracked it down to the `testVerifyAssertionRequestOptionalFields` test method. They were more reproducible when I ran the mentioned test 100-1000 times. The issue is that the test specifies a hardcoded JSON string to compare the firstname/lastname request component, but the implementation dynamically creates the JSON string via the `JSONSerialization.data(withJSONObject:)` API. This API seems to create a JSON string without preserving the given dictionary's given order. While the order doesn't matter in practice, it eliminates the flakes as the hardcoded test string will always match. Interestingly, using `JSONEncoder().encode(_:)` seems to preserve the order as I wasn't able to reproduce when re-running 1k times.
#no-changelog
> [auth-swift] Make request components for deterministic to avoid test flakes

- FirebaseCore/Tests/Unit/FIRBundleUtilTest.m
- FirebaseCore/Tests/Unit/FIROptionsTest.m
Based on internal cl/520042933
> FirebaseCore: Clean up mix of OCMock V2 and V3 syntax

- FirebaseAuth/Tests/Unit/FIRAuthTests.m
> [Auth] Update OCMock 2 syntax to v3 syntax.

- .github/workflows/check.yml
- .github/workflows/firestore.yml
- .github/workflows/update-cpp-sdk-on-release.yml
- Gemfile
- scripts/lib/checker.py
- scripts/lib/git.py
- scripts/make_release_notes.py
- scripts/sync_project.rb
This PR makes the scripts easier to run.
The first change is to `scripts/sync_project.rb` to look up the `ruby` interpreter in the `PATH` rather than hardcoding `/usr/bin/ruby`. For me, personally, this fixed a bug where I wanted it to use `ruby` from homebrew rather than the system `ruby` interpreter.
The second change is to remove the usage of the `six` library from Python scripts. Since everyone should be using Python 3 by now, there is no need for `six`. Also, this removes the requirement that people install this dependency on their local machines and make the scripts usable from a "vanilla" Python distribution.
The third change is to upgrade the Python version used in the GitHub Actions workflows from 3.6/3.7 to the latest, 3.11.
> Scripts cleanup: remove python `six` usage and get `ruby` from `PATH`

- FirebaseCore/CHANGELOG.md
- Package.swift
- scripts/build.sh
- scripts/setup_spm_tests.sh
Increased `swift-tools-version` to `5.6` in `Package.swift` to declare that that the Swift 5.6 toolchain (included in Xcode 13.3) is the minimum version required to build the Firebase package.
Replaced uses of initializers / methods / enums that were deprecated in SPM 5.6.
Note: Xcode 13.3.1+ has been the minimum supported since [Firebase 9.0](https://firebase.google.com/support/release-notes/ios#version_900_-_may_3_2022) but this enforces Xcode 13.3+ in `Package.swift`. However, this does not enforce Xcode 13.3<b>.1</b> specifically since the Swift toolchain version did not change between Xcode 13.3 and 13.3.1.
> [SPM] Require Xcode 13.3+ (Swift 5.6)

- Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c
- FirebaseAuth/Tests/Unit/FIRDeleteAccountResponseTests.m
- FirebaseAuth/Tests/Unit/FIREmailLinkSignInResponseTests.m
- FirebaseAuth/Tests/Unit/FIRRevokeTokenResponseTests.m
- FirebaseAuth/Tests/Unit/FIRSendVerificationCodeResponseTests.m
- FirebaseAuth/Tests/Unit/FIRVerifyClientResponseTests.m
- FirebaseAuth/Tests/Unit/FIRVerifyPasswordResponseTests.m
- FirebaseAuth/Tests/Unit/FIRVerifyPhoneNumberResponseTests.m
- FirebaseMessaging/Sources/FIRMessagingPendingTopicsList.h
succesful -> successful
becuase -> because
#no-changelog
> Fix successful typo

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.h
- FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m
- FirebaseAuth/Tests/Unit/FIRAuthUseUserAccessGroupTests.m
_I recommend viewing the diff without whitespace changes. [See nice diff.](https://github.com/firebase/firebase-ios-sdk/pull/11091/files?diff=unified&w=1)_
The outer `else` clause is unreachable and should be removed. We pass a pointer to `- [FIRAuthStoredUserManager getStoredUserAccessGroupWithError:]` but there is no resulting code path for it be populated.
The implementation of `- [FIRAuthStoredUserManager getStoredUserAccessGroupWithError:]` is pasted below. The only way for the `outError` to be populated is in the `- [FIRAuthUserDefaults dataForKey:error:]` method on line 53.
https://github.com/firebase/firebase-ios-sdk/blob/8badb28bf2727941c3e4b41fab87905de8595ca4/FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m#L52-L60
But, looking at the implementation of `- …
> [Auth] Remove unreachable code

- scripts/style.sh
Added an environment variable to specify the path to the version of `clang-format` used by the `style.sh` script.
#no-changelog
> [Tooling] Add FIR_CLANG_FORMAT_PATH env var to style.sh

- FirebaseRemoteConfig/Sources/RCNConfigFetch.m
Sometimes I still get no underlying error. This will fix it.
Fixes https://github.com/firebase/firebase-ios-sdk/issues/10454
> [RemoteConfig] Expose NSUnderlyingError to client

- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
- ReleaseTooling/Template/METADATA.md
- ReleaseTooling/Template/README.md
- The zip `README.md` has two sections that are populated each release with metadata regarding the release's dependency graph and included versions. Other than those two sections, the zip `README.md` does not change often. So, it's reasonable to break out those sections into a separate `METADATA.md` file.
- For additional context, this change is motivated by b/269421146.
#no-changelog
> [Release Tooling] Separate out dynamic content from zip README.md

- FirebaseCore/CHANGELOG.md
- Package.swift
- SPM only change that was missed in #11066
- We recently bumped to enforce swift-tools-version 5.6, which enforces being explicit about macCatalyst support. #11046
After this merges, I'll create the release branch and cherry-pick this into it.
> [Release] Enable macCatalyst support for Firestore targets

- FirebaseAnalyticsSwift.podspec
- FirebaseAnalyticsSwift/Tests/ObjCAPI/ObjCAPITests.m
- Package.swift
- scripts/spm_test_schemes/AnalyticsObjCAPI.xcscheme
Add build tests for the Analytics Objective C API via CocoaPods and SPM.
#no-changelog
> Analytics ObjC API coverage tests via CocoaPods and SPM

- Crashlytics/CHANGELOG.md
- FirebasePerformance/CHANGELOG.md
- FirebaseSessions/CHANGELOG.md
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/SourcesObjC/NanoPB/FIRSESNanoPBHelpers.h
- FirebaseSessions/SourcesObjC/NanoPB/FIRSESNanoPBHelpers.m
> Free nanopb mallocs when losing references to them

- FirebaseAnalyticsSwift.podspec
- AnalyticsSwift pod doesn't stage because:
```
Validating spec
-> FirebaseAnalyticsSwift (10.9.0)
- ERROR | [iOS] unknown: Encountered an unknown error (Unable to install the `FirebaseAnalyticsSwift` pod, because the `FirebaseAnalyticsSwift-Unit-objc-api-coverage` target in Xcode would have no sources to compile.) during validation.
[!] The `FirebaseAnalyticsSwift.podspec` specification does not validate.
```
- This fix seems to work doing a dry run staging
#no-changelog
> [Infra] Expand file extenstion in 'source' glob

- Package.swift
#no-changelog
This shouldn't have customer impact, but it's worth making sure it's consistent.
Crashlytics identifies MacCatalyst apps as `mac` platform, so doing this to be consistent
> Update Crashlytics CLS_SDK_NAME for macCatalyst

- .github/workflows/zip.yml
- I noticed that the `zip / check_framework_firestore_symbols` workflow was silently failing during the last release cycle due to GoogleAppMeasurement not being published. I had a workaround related to pipefail that involved subshells that I learned was unnecessary. I merged #11094 hoping that it would surface these failures in the next release cycle–– and it did.
- This PR exports the GoogleAppMeasurement env var for the workflow so the `check_framework_firestore_symbols` job always uses latest HEAD of `GoogleAppMeasurement`. 
Fix #11135
> [Infra] Use GoogleAppMeasurement HEAD when checking Firestore binary for unlinked symbols

- Firestore/Swift/Source/AsyncAwait/CollectionReference+AsyncAwait.swift
Fix https://github.com/firebase/firebase-ios-sdk/issues/10640
I would like to propose a Pull Request to add the `@discardableResult` attribute to the async `addDocument` method in CollectionReference. This change would be consistent with the similar change made in PR #10661.
> Add `@discardableResult` to async `addDocument`

- Firestore/Source/Public/FirebaseFirestore/FIRLocalCacheSettings.h
Replaced `instnace` with `instance` and `attemp` with `attempt`.
#no-changelog
> [Firestore] Fix FIRLocalCacheSettings.h typos

- Package.swift
- Did a local diff and this new artifact was not significantly different from RC0 (as expected because only FirestoreSwift has source changes)
- Will move release tags after merging (HEAD `master` is still OK to tag)
- Re-staged this internally using some WIP release tooling improvements 🎉 
#no-changelog
> [Release] Update Package.swift for 10.9.0 release (RC1)

- .github/workflows/spm.yml
- Package.swift
- SwiftPMTests/ClientApp/ClientApp.xcodeproj/project.pbxproj
- SwiftPMTests/ClientApp/ClientApp/Assets.xcassets/AccentColor.colorset/Contents.json
- SwiftPMTests/ClientApp/ClientApp/Assets.xcassets/AppIcon.appiconset/Contents.json
- SwiftPMTests/ClientApp/ClientApp/Assets.xcassets/Contents.json
- SwiftPMTests/ClientApp/ClientApp/ClientApp.entitlements
- SwiftPMTests/ClientApp/ClientApp/ClientApp.swift
- SwiftPMTests/ClientApp/ClientApp/ContentView.swift
- SwiftPMTests/ClientApp/ClientApp/Preview Content/Preview Assets.xcassets/Contents.json
- SwiftPMTests/ClientApp/ClientApp/objc-header-import-test.m
- SwiftPMTests/ClientApp/ClientApp/objc-module-import-test.m
- SwiftPMTests/ClientApp/ClientApp/objcxx-header-import-test.mm
- SwiftPMTests/ClientApp/ClientApp/objcxx-module-import-test.mm
- SwiftPMTests/ClientApp/ClientApp/swift-import-test.swift
- scripts/build.sh
- Add "client" sample app that imports all applicable product in a Swift, Obj-C, and Obj-C++ context.
- Add corresponding multi-platform `spm / client-app` job to test that app builds from the branch's HEAD package state.
- Checked and verified that this would have caught the issue that required 10.8.1 release.
- This also surfaced some other warnings and discrepancies that can now be addressed in subsequent PRs.
- Theres's currently a bug in Xcode versions under 14.3 that will affect this job running on some platforms. The build error looks like:
>  Showing All Messages
/Users/nickcooke/Library/Developer/Xcode/DerivedData/ClientApp-ftiilcvpyjwxxieryciqmiulqnea/SourcePackages/artifacts/googleappmeasurement/GoogleAppMeasurementOnDeviceConversion.xcframework:1:1: While building for macOS, …
> [Infra] Add sample app to test building SPM distro across supported platforms

- Crashlytics/CHANGELOG.md
- FirebaseSessions/Sources/ApplicationInfo.swift
- FirebaseSessions/Sources/Development/DevEventConsoleLogger.swift
- FirebaseSessions/Sources/NetworkInfo.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/SourcesObjC/NanoPB/FIRSESNanoPBHelpers.h
- FirebaseSessions/SourcesObjC/NanoPB/FIRSESNanoPBHelpers.m
- FirebaseSessions/Tests/Unit/ApplicationInfoTests.swift
- FirebaseSessions/Tests/Unit/Mocks/MockApplicationInfo.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
https://developer.apple.com/forums/thread/714876
- Deprecated with no replacement in iOS 16.4.
Currently FirebaseSessions doesn't use this data, as it's still in development, so no customer impact.
TODO
> Remove references to deprecated CTCarrier for Sessions

- docs/AddNewPod.md
- docs/AddNewProduct.md
> New Product Docs - First pass

- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
Port spec test changes from https://github.com/firebase/firebase-js-sdk/pull/7021 (Bundle the readTime and resumeToken into a data structure)
For reference, here is the Android port of the same change: https://github.com/firebase/firebase-android-sdk/pull/4928
#no-changelog
> Firestore Spec Tests: Port JS PR 7021 (bundle the readTime and resumeToken)

- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/json/bundle_spec_test.json
- Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/SpecTests/json/recovery_spec_test.json
Port spec test changes from https://github.com/firebase/firebase-js-sdk/pull/7229 (Optimize local cache sync when resuming a query that had docs deleted).
Note that the integer value of `QueryPurpose::LimboResolution` changed from `2` to `3` in the spec test JSON files as a result of this port and, therefore, some custom logic was added into `FSTSpecTests.mm` to handle this correctly.
For reference, here is the Android port of the same change: https://github.com/firebase/firebase-android-sdk/pull/4929
#no-changelog
> Firestore Spec Tests: Port JS PR 7229 (optimized query resumption using bloom filter)

- Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
- Firestore/Example/Tests/SpecTests/json/bundle_spec_test.json
- Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
- Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
- Firestore/Example/Tests/SpecTests/json/recovery_spec_test.json
Port spec test changes from https://github.com/firebase/firebase-js-sdk/pull/7257 (Firestore: use string values for TargetPurpose enum).
For reference, here is the Android port of the same change: https://github.com/firebase/firebase-android-sdk/pull/4931
#no-changelog
> Firestore Spec Tests: Port JS PR 7257 (use strings for `targetPurpose`)

- FirebaseAppDistribution.podspec
- FirebaseCore.podspec
- FirebaseCrashlytics.podspec
- FirebaseFunctions.podspec
- FirebaseStorage.podspec
Get `pod lib lint` unit tests working on Xcode 14.3
> Xcode 14.3 test_specs always need requires_app_host

- FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
- FirebaseRemoteConfig/Sources/RCNDevice.m
Xcode 14.3 complains about missing void's in parameterless C-style functions
#no-changelog
> Fix Xcode 14.3 RC warnings

- Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.h
- Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.m
- Crashlytics/Crashlytics/Components/FIRCLSContext.m
- Crashlytics/Shared/FIRCLSMachO/FIRCLSMachO.h
- Crashlytics/Shared/FIRCLSMachO/FIRCLSMachO.m
Objective-C blocks may invoke certain methods that attempt to acquire the Objective-C runtime lock. Simultaneously, _dyld_register_func_for_add_image is called once for each image currently part of the program, with its critical section protected by the dyld internal lock. Moreover, the Objective-C runtime frequently accesses dyld, as seen in objc_copyImageNames calling dyld_image_path_containing_address with the Objective-C runtime lock already held https://github.com/apple-oss-distributions/objc4/blob/rel/objc4-838/runtime/objc-runtime-new.mm#L5540.
The lock/unlock policies between dyld and Objective-C runtime appear uncertain and potentially dangerous, making it preferable to avoid using the Objective-C runtime inside dyld callbacks.
These changes aim to enhance the stability and …
> Get rid of objc blocks inside dyld callback

- FirebaseSessions/Sources/Development/DevEventConsoleLogger.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
Follow up on https://github.com/firebase/firebase-ios-sdk/pull/11205
#no-changelog 
```
Session Event:
event_type: SESSION_START
session_data
session_id: 548c1d690b1b4de3ac908bd073971631
first_session_id: 548c1d690b1b4de3ac908bd073971631
session_index: 0
event_timestamp_us: 1683218660000000
firebase_installation_id: edv8erKRTUNDn_TDoVNgZT
data_collection_status
crashlytics: SDK_NOT_INSTALLED
performance: ENABLED
session_sampling_rate: 1.0
application_info
app_id: 1:1080744134505:ios:bbb8009438b93cc673dff8
session_sdk_version: 10.10.0
os_version: 16.2
device_model: iOS Simulator (iPhone)
development_platform_name: <NULL>
development_platform_version: <NULL>
session_sdk_version: 10.10.0
apple_app_info
bundle_short_version: 1.0
app_build_version: 1
network_connection_info
network_type: 1 …
```
> Fill in os_version and app_build_version for Sessions

- FirebaseAppCheck/Sources/Core/FIRAppCheck.m
- FirebaseAppCheck/Sources/Core/FIRAppCheckSettings.h
- FirebaseAppCheck/Sources/Core/FIRAppCheckSettings.m
- FirebaseAppCheck/Sources/Core/TokenRefresh/FIRAppCheckTokenRefresher.h
- FirebaseAppCheck/Sources/Core/TokenRefresh/FIRAppCheckTokenRefresher.m
- FirebaseAppCheck/Sources/GAC/Core/GACAppCheckSettings.h
- FirebaseAppCheck/Sources/GAC/Core/GACAppCheckSettings.m
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckSettingsTests.m
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckTests.m
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckTokenRefresherTests.m
Extracted the non-Firebase-specific implementation details out of `FIRAppCheckSettings` into `GACAppCheckSettings`.
Added a `GACAppCheckTokenAutoRefreshPolicy` enum to represent the tri-state (`nil`/`YES`/`NO`) of auto token refresh enablement in `GACAppCheckSettings`.
This is an alternative approach to PR #11193 that makes `FIRAppCheckSettings` a subclass of `GACAppCheckSettings` to share common code.
#no-changelog
> Extract GACAppCheckSettings from FIRAppCheckSettings

- FirebasePerformance/Sources/FPRNanoPbUtils.m
- FirebasePerformance/Sources/Gauges/Memory/FPRMemoryGaugeCollector.m
- FirebasePerformance/Sources/Instrumentation/Network/Delegates/FPRNSURLConnectionDelegateInstrument.m
- FirebasePerformance/Sources/Instrumentation/Network/Delegates/FPRNSURLSessionDelegateInstrument.m
- FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLConnectionInstrument.m
- FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m
- FirebasePerformance/Sources/Instrumentation/UIKit/FPRUIViewControllerInstrument.m
- Address 14.3 Analyzer issues
<details>
<summary>See the before and after results.</summary>
<br>
- Before
```
bundle exec pod lib lint --sources=https://github.com/firebase/SpecsDev.git,https://github.com/firebase/SpecsStaging.git,https://cdn.cocoapods.org/ --include-podspecs={FirebaseCore.podspec,FirebaseCoreInternal.podspec,FirebaseInstallations.podspec,FirebaseRemoteConfig.podspec,FirebaseABTesting.podspec,FirebaseSessions.podspec,FirebaseCoreExtension.podspec} --analyze FirebasePerformance.podspec --analyze --platforms=ios --skip-tests
-> FirebasePerformance (10.10.0)
- NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
- NOTE  | [iOS] xcodebuild:  note: Metadata extraction skipped. No …
```
> [Performance] Address Xcode 14.3 Analyzer issues

- FirebaseDynamicLinks/Sources/FIRDLJavaScriptExecutor.m
- FirebaseDynamicLinks/Sources/Utilities/FDLUtilities.m
- Address 14.3 Analyzer issues
<details>
<summary>See the before and after results.</summary>
<br>
- Before
```
bundle exec pod lib lint --sources=https://github.com/firebase/SpecsDev.git,https://github.com/firebase/SpecsStaging.git,https://cdn.cocoapods.org/ --include-podspecs={FirebaseCore.podspec,FirebaseCoreInternal.podspec} --analyze FirebaseDynamicLinks.podspec --analyze --platforms=ios --skip-tests
-> FirebaseDynamicLinks (10.10.0)
- NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
- NOTE  | [iOS] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'FirebaseCoreInternal' from project 'Pods')
- WARN  | xcodebuild: …
```
> [Dynamic Links] Address Xcode 14.3 Analyzer issues

- FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m
- FirebaseInAppMessaging/Sources/Data/FIRIAMMessageContentDataWithImageURL.m
- FirebaseInAppMessaging/Sources/Data/FIRIAMMessageDefinition.m
- FirebaseInAppMessaging/Sources/Private/Data/FIRIAMMessageContentDataWithImageURL.h
- FirebaseInAppMessaging/Sources/Private/Data/FIRIAMMessageRenderData.h
- Address 14.3 Analyzer issues
<details>
<summary>See the before and after results.</summary>
<br>
- Before
bundle exec pod lib lint --sources=https://github.com/firebase/SpecsDev.git,https://github.com/firebase/SpecsStaging.git,https://cdn.cocoapods.org/ --include-podspecs={FirebaseCore.podspec,FirebaseCoreInternal.podspec,FirebaseInstallations.podspec,FirebaseABTesting.podspec} --analyze FirebaseInAppMessaging.podspec --analyze --platforms=ios --skip-tests
-> FirebaseInAppMessaging (10.10.0-beta)
- ERROR | [iOS] build_pod: Static Analysis failed. You can use `--verbose` for more information. You can use `--no-clean` to save a reproducible buid environment.
- NOTE  | [iOS] xcodebuild:  note: Building targets in …
> [In App Messaging] Address Xcode 14.3 Analyzer issues

- Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
- Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
- Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
Sync spec tests with changes from https://github.com/firebase/firebase-js-sdk/pull/7285: "Remove the no-android tag from bloom filter spec tests".
The changes in this PR have no effect on this SDK, but serves to keep the spec tests in sync for easier updating in the future.
#no-changelog
> Firestore Spec Tests: Port JS PR 7285 (remove no-android tag from bloom filter tests)

- Crashlytics/CHANGELOG.md
- Crashlytics/Crashlytics/Unwind/Dwarf/FIRCLSDwarfUnwind.c
- Address Analyzer issue surfaced in Xcode Cloud with 14.3:
> Value stored to 'peValue' during its initialization is never read
> FIRCLSDwarfUnwind.c:918  
- This was not reproducible when following the repro instructions in the related [google/GoogleDataTransport/#95](https://github.com/google/GoogleDataTransport/pull/95), but this PR's fix should address it.
Fix #11228
> [Crashlytics] Fix Xcode 14.3 Analyzer issues

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/Auth/AuthComponent.swift
Using unowned saves passing app as a parameter as well as avoiding an unwrap.
Additional context and discussion in #11248
#no-changelog
> [auth-swift] unowned instead of weak for holding app in the component

- AppCheck.podspec
- AppCheck/Tests/Integration/GACDeviceCheckAPIServiceE2ETests.m
- AppCheck/Tests/Unit/AppAttestProvider/GACAppAttestAPIServiceTests.m
- AppCheck/Tests/Unit/AppAttestProvider/GACAppAttestProviderTests.m
- AppCheck/Tests/Unit/AppAttestProvider/Storage/GACAppAttestArtifactStorageTests.m
- AppCheck/Tests/Unit/AppAttestProvider/Storage/GACAppAttestKeyIDStorageTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckAPIServiceTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckIntegrationTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckTimerTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckTokenRefresherTests.m
- AppCheck/Tests/Unit/DeviceCheckProvider/GACDeviceCheckAPIServiceTests.m
- AppCheck/Tests/Unit/DeviceCheckProvider/GACDeviceCheckProviderTests.m
- AppCheck/Tests/Unit/Utils/GACFakeTimer.h
- AppCheck/Tests/Unit/Utils/GACFakeTimer.m
- AppCheck/Tests/Unit/Utils/GACFixtureLoader.h
- AppCheck/Tests/Unit/Utils/GACFixtureLoader.m
- Renamed `FIR`-prefixed symbols to `GAC` in unit tests for the generic (non-Firebase-specific) App Check SDK.
- Removed `SharedTestUtilities/AppCheck*` directories from the `unit_tests` spec sources (imports already changed to `AppCheck/Tests/Utils/AppCheck*`).
#no-changelog
> [App Check] Rename FIR symbols in unit tests for generic SDK

- AppCheck/Sources/AppAttestProvider/GACAppAttestProvider.m
- AppCheck/Sources/Core/APIService/GACAppCheckAPIService.m
- AppCheck/Sources/Core/GACAppCheck.m
- AppCheck/Sources/Core/GACAppCheckLogger.h
- AppCheck/Sources/Core/GACAppCheckLogger.m
- AppCheck/Sources/DebugProvider/GACAppCheckDebugProvider.m
- AppCheck/Sources/DebugProvider/GACAppCheckDebugProviderFactory.m
- AppCheck/Sources/DeviceCheckProvider/GACDeviceCheckProvider.m
Added logging macros as drop-in replacements for the `GAC`/`FIRAppCheckLogger` macros. These are simple wrappers around `NSLog` and are not compiled out based on the desired logging level.
#no-changelog
> Replace GACAppCheckLogger macros with NSLog wrappers

- AppCheck/Sources/Core/GACAppCheck.m
- AppCheck/Sources/Core/Storage/GACAppCheckStorage.h
- AppCheck/Sources/Core/Storage/GACAppCheckStorage.m
- AppCheck/Sources/DebugProvider/GACAppCheckDebugProvider.m
- AppCheck/Tests/Unit/Core/GACAppCheckStorageTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckTests.m
Removed Firebase-specific implementation details (Google App ID and Firebase App Name) from `GACAppCheckStorage`.
#no-changelog
> Remove Firebase-specific implementation in GACAppCheckStorage

- scripts/api_diff_report/pr_commenter.py
Won't create Diff Report until the first commit has an API change.
If the API change got reverted in the following commit, the Diff Report will update with title "No API diff detected".
> Create API Diff Report only when the first commit in PR has an API change

- FirebaseAuth.podspec
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- No more Objective C `.m` files. 
- Public headers are kept around for typedef and global constant backwards compatibility
- Depend on Interop pods instead of headers in the repo
#no-changelog
> [auth-swift] CocoaPods Swift-only sources

- cmake/external/leveldb-1.22_windows_paths.patch
- cmake/external/leveldb_patch.py
There was a small error in the 1.22 patch (needed when building the iOS SDK directly, not within the Firebase C++ SDK build), which is fixed in this PR.
This PR also modifies the leveldb patcher script to use a build stamp file to ensure that leveldb is only patched once, fixing an issue when you run cmake a second time in the same build directory.
> Update leveldb 1.22 patch, and add a fix to avoid patching twice.

- scripts/api_diff_report/api_diff_report.py
A minor bug in the API diff. The report here should be showing `HTTPSCallableOptions` as a new class: https://github.com/firebase/firebase-ios-sdk/pull/11270#issuecomment-1546118031
Fix: Print out the class name as title.
e.g. 
<details>
<summary>
[ADDED] httpsCallable(_:options:)
</summary>
```diff
Swift:
+  @objc(HTTPSCallableWithURL:options:) public func httpsCallable ( _ url : URL , options : HTTPSCallableOptions ) -> HTTPSCallable
```
</details>
<details>
<summary>
[ADDED] httpsCallable(_:options:requestAs:responseAs:encoder:decoder:)
</summary>
```diff
Swift:
+  open func httpsCallable < Request : Encodable , Response : Decodable > ( _ url : URL , options : HTTPSCallableOptions , requestAs : Request . Type = Request . self , responseAs : Response . Type = Response . self , encoder : …
```
> Always print out class name as title if there are changes in the class API

- AppCheck/Sources/AppAttestProvider/API/GACAppAttestAPIService.h
- AppCheck/Sources/AppAttestProvider/API/GACAppAttestAPIService.m
- AppCheck/Sources/AppAttestProvider/GACAppAttestProvider.m
- AppCheck/Tests/Unit/AppAttestProvider/GACAppAttestAPIServiceTests.m
Removed the Firebase-specific identifiers `projectID` and `appID` from `GACAppAttestAPIService` in favour of a generic `resourceName`.
#no-changelog
> Extract Firebase-specific identifiers from GACAppAttestAPIService

- FirebaseAppCheck/Interop/FIRAppCheckInterop.h
- FirebaseAppCheck/Sources/Core/FIRAppCheck.m
- FirebaseFunctions.podspec
- FirebaseFunctions/CHANGELOG.md
- FirebaseFunctions/Sources/Functions.swift
- FirebaseFunctions/Sources/HTTPSCallable.swift
- FirebaseFunctions/Sources/HTTPSCallableOptions.swift
- FirebaseFunctions/Sources/Internal/FunctionsContext.swift
- FirebaseFunctions/Tests/CombineUnit/HTTPSCallableTests.swift
- FirebaseFunctions/Tests/Integration/IntegrationTests.swift
- FirebaseFunctions/Tests/ObjCIntegration/ObjCAPITests.m
- FirebaseFunctions/Tests/ObjCIntegration/ObjCPPAPITests.mm
- FirebaseFunctions/Tests/Unit/FunctionsTests.swift
- SharedTestUtilities/AppCheckFake/FIRAppCheckFake.h
- SharedTestUtilities/AppCheckFake/FIRAppCheckFake.m
* Implement one-time use token for Callable Functions SDK by following the [proposal](https://docs.google.com/document/d/1fZ8w6lIj5rODUQYqr4IUUUodCmcb_aWLS9w2LgLKgdU/edit?resourcekey=0-xnc7HhmtcKf8JPNdGKtCIg#heading=h.ptb4ebwum9vl)
* [proposal ](https://docs.google.com/document/d/1fZ8w6lIj5rODUQYqr4IUUUodCmcb_aWLS9w2LgLKgdU/edit?resourcekey=0-xnc7HhmtcKf8JPNdGKtCIg#heading=h.ptb4ebwum9vl) is waiting for approval
> Firebase App Check One-time Use Tokens for Callable Functions SDK

- Package.swift
Updated the checksum for the `FirebaseFirestore` `binaryTarget` in `Package.swift` (M132 RCO).
#no-changelog
> Update FirebaseFirestore SPM checksum for M132 RC0

- .github/workflows/api_diff_report.yml
During the release cycle, the new version of googleAppMeasurement (https://github.com/google/GoogleAppMeasurement) haven't been released during the release cycle. As a result, `Jazzy` plus `xcodebuild` failed due to dependency issue:
https://github.com/firebase/firebase-ios-sdk/actions/runs/4996800540/jobs/8950788280#step:10:375
We need to add an ENV and use the latest released dependency (configed in master branch) instead.
Test PR - branch abased from `pb-storage-async-progress` branch: 
https://github.com/firebase/firebase-ios-sdk/pull/11302
Workflow run - API doc generated successfully: 
https://github.com/firebase/firebase-ios-sdk/actions/runs/5006429308/jobs/8971699171?pr=11302#step:10:383
> API Diff Report CI set env FIREBASECI_USE_LATEST_GOOGLEAPPMEASUREMENT=1

- AppCheck/Interop/GACAppCheckInterop.h
- AppCheck/Sources/Core/GACAppCheck.m
- AppCheck/Sources/Public/AppCheck/GACAppCheck.h
- AppCheck/Tests/Utils/AppCheckFake/GACAppCheckFake.h
- AppCheck/Tests/Utils/AppCheckFake/GACAppCheckFake.m
Merged the latest `FirebaseAppCheck` changes (from PR #11307) into the generic `AppCheck` SDK.
#no-changelog
> Integrate FirebaseAppCheck changes into AppCheck

- FirebaseCore/Internal/Sources/HeartbeatLogging/Heartbeat.swift
- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatController.swift
- FirebaseDatabase/Sources/Api/FIRDatabaseComponent.m
- FirebaseFunctions/Sources/HTTPSCallableOptions.swift
- FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.h
s/intializer/initializer
#no-changelog
> [Docs] Fix 'intializer' typos in repo

- scripts/api_diff_report/api_info.py
There is an issue capturing the API change, the API change was not caught: https://github.com/firebase/firebase-ios-sdk/pull/11289
This is because we added "customized section headers". This is intentional.
Now, the tool will check all the apis under all the "customized section headers"
Test result: https://github.com/firebase/firebase-ios-sdk/pull/11326#issuecomment-1561687774
> Fix API diff tool not detecting api changes

- AppCheck/Sources/AppAttestProvider/GACAppAttestProvider.m
- AppCheck/Sources/Core/APIService/GACAppCheckAPIService.h
- AppCheck/Sources/Core/APIService/GACAppCheckAPIService.m
- AppCheck/Sources/Core/GACAppCheck.m
- AppCheck/Sources/Core/GACAppCheckSettings.m
- AppCheck/Sources/Core/TokenRefresh/GACAppCheckTokenRefresher.m
- AppCheck/Sources/DebugProvider/GACAppCheckDebugProvider.m
- AppCheck/Sources/DeviceCheckProvider/GACDeviceCheckProvider.m
- AppCheck/Sources/Public/AppCheck/AppCheck.h
- AppCheck/Sources/Public/AppCheck/GACAppCheck.h
- AppCheck/Sources/Public/AppCheck/GACAppCheckSettings.h
- AppCheck/Tests/Integration/GACDeviceCheckAPIServiceE2ETests.m
- AppCheck/Tests/Unit/Core/GACAppCheckAPIServiceTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckSettingsTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckTokenRefresherTests.m
- Removed the unused `appID` property from `GACAppCheckAPIService`.
- Removed heartbeat logging tests from `GACAppCheckAPIServiceTests`.
- Added request hook, additional headers and API key tests to `GACAppCheckAPIServiceTests`.
#no-changelog
> Remove Firebase-specific implementation from GACAppCheckAPIService

- Package.swift
- Adding back the linked frameworks previously part of the _source_ Firestore target before the switch to a _binary_ target.
- This diff matches with pre-10.8.0 linked frameworks: https://github.com/firebase/firebase-ios-sdk/blob/10.7.0/Package.swift#L705-L709
#no-changelog
> [Firestore] Add linked frameworks to Firestore wrapper target

- AppCheck.podspec
- AppCheck/Sources/AppAttestProvider/GACAppAttestProvider.m
- AppCheck/Sources/AppAttestProvider/Storage/GACAppAttestArtifactStorage.h
- AppCheck/Sources/AppAttestProvider/Storage/GACAppAttestArtifactStorage.m
- AppCheck/Tests/Unit/AppAttestProvider/Storage/GACAppAttestArtifactStorageTests.m
- AppCheckInterop.podspec
- FirebaseAppCheck.podspec
Removed the Firebase-specific references `appName` and `appId` from `GACAppAttestArtifactStorage`. They have been moved up one layer into `GACAppAttestProvider`.
#no-changelog
> Extract Firebase-specific symbols from GACAppAttestArtifactStorage

- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Sources/AsyncAwait.swift
- FirebaseStorage/Tests/Integration/StorageAsyncAwait.swift
Fix #10574 
- Add an optional `onProgress` parameter to `putDataAsync`, `putFileAsync`, and `writeAsync`. 
Googlers, see API review at [go/firebase-storage-async-progress](http://goto.google.com/firebase-storage-async-progress)
> Progress closure for async/await APIs

- AppCheck/Sources/AppAttestProvider/API/GACAppAttestAPIService.m
- AppCheck/Sources/AppAttestProvider/GACAppAttestProvider.m
- AppCheck/Sources/Core/APIService/GACAppCheckAPIService.h
- AppCheck/Sources/Core/GACAppCheckSettings.m
- AppCheck/Sources/Public/AppCheck/GACAppAttestProvider.h
- AppCheck/Sources/Public/AppCheck/GACAppCheckProvider.h
- AppCheck/Sources/Public/AppCheck/GACAppCheckSettings.h
- AppCheck/Tests/Unit/AppAttestProvider/GACAppAttestProviderTests.m
- AppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
Removed Firebase-specific dependencies, specifically `FIRApp`, from `GACAppAttestProvider`.
#no-changelog
> Remove FIRApp dependencies from GACAppAttestProvider

- .github/workflows/zip.yml
- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Sources/AsyncAwait.swift
#11289 used Swift language functionality not available in Xcode 13 causing the zip build to break.
Fix #11305
> Fix zip build break

- AppCheck/Sources/DebugProvider/API/GACAppCheckDebugProviderAPIService.h
- AppCheck/Sources/DebugProvider/API/GACAppCheckDebugProviderAPIService.m
- AppCheck/Sources/DebugProvider/GACAppCheckDebugProvider.m
- AppCheck/Sources/Public/AppCheck/GACAppCheckDebugProvider.h
- AppCheck/Tests/Unit/DebugProvider/GACAppCheckDebugProviderAPIServiceTests.m
- AppCheck/Tests/Unit/DebugProvider/GACAppCheckDebugProviderTests.m
- AppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
Removed Firebase-specific symbols and implementation details from the generic App Check Debug Provider (`GACAppCheckDebugProvider`).
#no-changelog
> [App Check] Remove Firebase specifics from Debug Provider

- AppCheck/Sources/DeviceCheckProvider/API/GACDeviceCheckAPIService.h
- AppCheck/Sources/DeviceCheckProvider/API/GACDeviceCheckAPIService.m
- AppCheck/Sources/DeviceCheckProvider/GACDeviceCheckProvider.m
- AppCheck/Sources/Public/AppCheck/GACDeviceCheckProvider.h
- AppCheck/Tests/Integration/GACDeviceCheckAPIServiceE2ETests.m
- AppCheck/Tests/Unit/DeviceCheckProvider/GACDeviceCheckAPIServiceTests.m
- AppCheck/Tests/Unit/DeviceCheckProvider/GACDeviceCheckProviderTests.m
- AppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
Removed Firebase-specific symbols and implementation details from the generic Device Check Provider (`GACDeviceCheckProvider`).
#no-changelog
> [App Check] Remove Firebase specifics from Device Check Provider

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/AuthProvider/OAuthCredential.swift
- FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/AdditionalUserInfoTests.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- FirebaseAuth/Tests/Unit/RPCBaseTests.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
- 15 more AuthTests.swift (25 to go)
- Refactoring to centralize more common constants in `RPCBaseTests`
- Distinguish between `User Doe` and `Google Doe` constants to clean up test sloppiness.
- Fix bug of not propagating fullName from an OAuthCredential to a VerifyAssertionRequest
- A few additional typo fixes
> [auth-swift] AuthTests.swift - 15 more unit tests

- Crashlytics/CHANGELOG.md
- Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.m
- Crashlytics/UnitTests/Data/GoogleService-Info.plist
- Crashlytics/UnitTests/FIRCLSReportUploaderTests.m
This is a modification of https://github.com/firebase/firebase-ios-sdk/pull/10958
Paired on with @wowlocal 
Rotating the Installation ID when uploading in Urgent Mode is not necessary, so this modifies the previous PR to skip rotating the Installation ID when we have the conditions for deadlock.
One problem with this seems to be the isMainThread check. Dispatch Queues in the background are not guaranteed to run in a background thread, so I believe the isMainThread check is true even when run on a background dispatch_queue. This seems to over-count cases where this could deadlock.
> Fixing threading-related hang during initialization in urgent mode

- .github/workflows/auth.yml
- .github/workflows/core.yml
- .github/workflows/core_extension.yml
- .github/workflows/core_internal.yml
- .github/workflows/firebase_app_check.yml
- .github/workflows/installations.yml
Following #11370, the POD_LIB_LINT_ONLY env var is no longer needed. So, removing it from CI scripts.
No remaining references within the repo.
```
➜  firebase-ios-sdk git:(nc/cleanup-gha) 
‣ git grep POD_LIB_LINT_ONLY
➜  firebase-ios-sdk git:(nc/cleanup-gha) 
```
#no-changelog
> [Infra] Remove GHA env var that is no longer needed

- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/Backend/RPC/Proto/FIRAuthProtoMFAEnrollment.h
- FirebaseAuth/Sources/Backend/RPC/Proto/TOTP/FIRAuthProtoFinalizeMFATOTPSignInRequestInfo.h
- FirebaseAuth/Sources/MultiFactor/FIRMultiFactorResolver.m
- FirebaseAuth/Sources/MultiFactor/TOTP/FIRTOTPMultiFactorAssertion+Internal.h
- FirebaseAuth/Sources/MultiFactor/TOTP/FIRTOTPMultiFactorAssertion.m
- FirebaseAuth/Sources/MultiFactor/TOTP/FIRTOTPMultiFactorGenerator.m
- FirebaseAuth/Sources/MultiFactor/TOTP/FIRTOTPMultiFactorInfo.h
- FirebaseAuth/Sources/MultiFactor/TOTP/FIRTOTPMultiFactorInfo.m
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRTOTPMultiFactorGenerator.h
Added Assertion, generator and resolver logic for TOTP MFA.
Updated the backend rpc call finalizeMFASignInRequest to take TOTP parameters.
This PR is an updated version of #11217.
> Added TOTP MFA Assertion logics

- AppCheck/Sources/AppAttestProvider/GACAppAttestProvider.m
- AppCheck/Sources/Core/APIService/GACAppCheckAPIService.m
- AppCheck/Sources/Core/GACAppCheckLogger.h
- AppCheck/Sources/Core/GACAppCheckLogger.m
- AppCheck/Sources/DebugProvider/GACAppCheckDebugProvider.m
The constants in `GACAppCheckLogger` conflict with those in [`FIRAppCheckLogger`](https://github.com/firebase/firebase-ios-sdk/blob/3abef641cd8bbf0893075f683e7dde802e53df15/FirebaseAppCheck/Sources/Core/FIRAppCheckLogger.m#L25-L46).
#no-changelog
> [App Check] Rename symbols in GACAppCheckLogger

- FirebaseMLModelDownloader/Tests/Unit/ModelDownloaderUnitTests.swift
- FirebaseMessaging/Tests/UnitTests/FIRMessagingLinkHandlingTest.m
Address URL unit test failures with the Xcode 15 beta. The Apple APIs will automatically percent-encode spaces.
From the Xcode 15 release notes:
**_Fixed: For apps linked on or after iOS 17 and aligned OS versions, URL parsing has updated from the obsolete RFC 1738/1808 parsing to the same RFC 3986 parsing as URLComponents. This unifies the parsing behaviors of the URL and URLComponents APIs. Now, URL automatically percent- or IDNA-encodes invalid characters to help create a valid URL._**
_- To check if a urlString is strictly valid according to the RFC, use the new URL(string: urlString, encodingInvalidCharacters: false) initializer. This init leaves all characters as they are and will return nil if urlString is explicitly invalid. (93368104)_
> [Xcode 15] Spaces are now valid in URL strings

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/RevokeTokenRequest.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
Add Swift implementations for the two Revoke Token unit tests. This completes the implementation transformation of FIRAuthTests.m to AuthTests.swift
Two Revoke Token implementation questions came up while doing the tests. 
- The old Revoke Token proceeds and the old tests depend on continuing with a nil idToken. I matched this in the Swift implementation
- The Objective C implementation was using the public `getIDToken` instead of `internalGetToken`. This added the requirement to use the main thread internally and made the test implementation difficult. I changed the implementation to use `internalGetToken` and only do the `revokeToken` callback on the main thread.
> [auth-swift] Revoke Token unit tests

- FirebasePerformance/CHANGELOG.md
- FirebasePerformance/Sources/FPRDataUtils.h
- FirebasePerformance/Sources/FPRDataUtils.m
- FirebasePerformance/Sources/FPRNanoPbUtils.m
- FirebasePerformance/Tests/Unit/FPRNanoPbUtilsTest.m
- FirebasePerformance/Tests/Unit/FPRNetworkTraceTest.m
Fixes #11397. Includes 2 changes:
1. Fix the failing unit test for XCode15
2. Remote the CTCarrier dependency since it is deprecated
> Make Firebase Performance XCode 15 compatible.

- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
- Firestore/core/src/remote/remote_event.cc
- Firestore/core/src/util/testing_hooks.h
- Firestore/core/test/unit/util/testing_hooks_test.cc
Update the integration test for the bloom filter to also verify that Watch specified a bloom filter that could be used to avert the full requery.
Googlers see b/274140502 for more details.
This PR is a port of https://github.com/firebase/firebase-js-sdk/pull/7095, and its follow-up improvements in https://github.com/firebase/firebase-js-sdk/pull/7112. The corresponding Android port is https://github.com/firebase/firebase-android-sdk/pull/4768.
#no-changelog
> Update the integration test to verify that bloom filter averted full requery

- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
Pretty self-explanatory so I won't waste anyone's time with a lot of typing here
All of the other error messages have a single period at the end, I assume this one should as well?
> fix duplicated period in realtime remote config error

- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
Cast Listener with __block so changes can be made inside dispatch_async block.
Fixes [bug](https://github.com/firebase/firebase-ios-sdk/issues/11458) reported by user
> Cast listener with __block

- FirebaseDatabase/Tests/Unit/FLevelDBStorageEngineTests.m
The test `testExtremeDoublesAsServerCache` only applies to iOS < 11. Removed the test since our minimum deployment target is already iOS 11. This also resolves the test failure on visionOS.
#no-changelog
> [Database] Remove outdated `FLevelDBStorageEngineTests` test

- FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m
Replaced use of the deprecated `unarchiveObjectWithData:` method with `unarchivedObjectOfClasses:fromData:error:`, available in iOS 11+ (above our minimum deployment target).
#no-changelog
> [Database] Replace deprecated `NSKeyedUnarchiver` method in `FLevelDBStorageEngine`

- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift
Key ordering from `JSONEncoder` is not guaranteed, resulting in test failures when output is compared directly (e.g., [`testDataRequestSuccessWhenHeartbeatsNeedSending`](https://github.com/firebase/firebase-ios-sdk/blob/f0378e9f9ea5d2d131b75d8745c778468b9b2118/FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckAPIServiceTests.m#L125-L135) and [`testRequest_IncludesHeartbeatPayload_WhenHeartbeatsNeedSending`](https://github.com/firebase/firebase-ios-sdk/blob/f0378e9f9ea5d2d131b75d8745c778468b9b2118/FirebaseAuth/Tests/Unit/FIRAuthBackendRPCImplementationTests.m#L421-L448)).
Added the `sortedKeys` output formatting option in debug builds to fix non-deterministic test results while avoiding unnecessary sorting costs in release builds. This resolves #11406 in local testing.
#no-changelog
> [App Check] Fix JSON key ordering in `HeartbeatsPayload`

- FirebaseMessaging/Sources/FIRMessaging.m
- FirebaseMessaging/Sources/FIRMessagingContextManagerService.m
- FirebaseMessaging/Tests/UnitTests/FIRMessagingContextManagerServiceTest.m
Fixed Firebase Messaging build issues in `FIRMessaging.m` and `FIRMessagingContextManagerService.m` when targeting visionOS. Also cleaned up extraneous `@availability` checks for platforms below the current minimum deployment target in these files.
#no-changelog
> [Messaging] Fix build issues on visionOS

- Firestore/CHANGELOG.md
- Package.swift
> [visionOS] Provide support for building Firestore on visionOS

- Firestore/Swift/CHANGELOG.md
- Firestore/Swift/Source/PropertyWrapper/FirestoreQueryObservable.swift
This should fix the RC build on Xcode 13.3.1. The concise optional unwrapping syntax (`if let foo {}`) was shipped with Swift 5.7, but Xcode 13.3.1 shipped with Swift 5.6.
#no-changelog
> [Firestore] Make Swift code compatible with Xcode 13.3.1

- FirebaseAuth/Sources/MultiFactor/TOTP/FIRTOTPMultiFactorInfo.h
Oddly, the type being forward declared in this header is not otherwise defined in either the header or in one of the header's imported headers. Yet, this somehow does not cause a build error locally or in CI. This instead surfaced when copybara'ing FirebaseAuth. 
#no-changelog
> [Auth] Forward declare type in header

- FirebaseCore/CHANGELOG.md
For upcoming 10.12.0 release, this `Package.swift` code was added in order to support visionOS where possible: https://github.com/firebase/firebase-ios-sdk/blob/CocoaPods-10.12.0/Package.swift#L1460-L1474
The new `Platform.visionOS` API is only available on Xcode 15 Beta 2 and later. The only way to gate the APIs use without breaking Xcode 14 SPM users is to wrap it with `#if swift(>=5.9)`. While this protect Xcode 14 use, it breaks Xcode 15 Beta **1** use as the visionOS API was not added there.
> [Docs] Add a release note w.r.t. Xcode 15 Beta 1 support

- FirebaseAuth/Sources/Swift/AuthProvider/EmailAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/FacebookAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/GameCenterAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/GitHubAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/GoogleAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/OAuthCredential.swift
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthCredential.swift
- FirebaseAuth/Sources/Swift/AuthProvider/TwitterAuthProvider.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthWebView.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthWebViewController.swift
Fix warnings like _Attempted to decode a collection type 'NSString' (subclass of 'NSObject') for key 'NS.keys'. 'NSString' requires its subclasses to be explicitly added to the allowed classes list but it is not present. Allowing this has been a source of security issues_ that are shown in Xcode 15 beta 3
Also, added a few missing iOS 13 availability checks.
#no-changelog
> [auth-swift] Fix runtime warnings detected by Xcode 15 b3

- .github/workflows/sessions.yml
- Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.m
- Crashlytics/Crashlytics/Controllers/FIRCLSNotificationManager.m
- Crashlytics/Crashlytics/Helpers/FIRCLSDefines.h
- Crashlytics/Shared/FIRCLSMachO/FIRCLSMachO.m
- Crashlytics/UnitTests/FIRCLSMachO/FIRCLSMachOTests.m
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
Build on top of https://github.com/firebase/firebase-ios-sdk/pull/11498, 
Fixed Firebase Crashlytics SDK build issues for visionOS, along with corresponding unit test changes. This also resolves build issues with the underlying Firebase Sessions SDK.
Get rid of deprecated api warning for visionPro, there are two sets of functions getting deprecated:
- `NXGetLocalArchInfo()` -> `macho_arch_name_for_mach_header()` // for cpu type, subtype and archname
- `getsectbynamefromheader(mach_header, segementName, sectionName)` -> `getsectiondata(mach_header, segementName, sectionName)` // finding the runtime section ref for DWARF or other strategy of unwinding
#no-changelog
> [Crashlytics] update deprecated kernel api for visionPro

- AppCheck/Interop/Public/AppCheckInterop/GACAppCheckInterop.h
- AppCheck/Sources/Core/GACAppCheck.m
- AppCheck/Sources/Public/AppCheck/AppCheck.h
- AppCheck/Sources/Public/AppCheck/GACAppCheck.h
- AppCheck/Sources/Public/AppCheck/GACAppCheckTokenDelegate.h
- AppCheck/Tests/Unit/Core/GACAppCheckTests.m
- AppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
Replaced token refresh notifications via `NSNotificationCenter` with `GACAppCheckTokenDelegate` in the internal App Check SDK.
Firebase App Check (shim SDK) can continue to support the existing `NSNotification`s by providing a `GACAppCheckTokenDelegate` that posts notifications in its `tokenDidUpdate:instanceName:` method.
#no-changelog
> [App Check] Replace token refresh `NSNotification`s with delegate

- AppCheck.podspec
- AppCheck/Tests/Unit/AppAttestProvider/GACAppAttestAPIServiceTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckAPIServiceTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckTokenRefresherTests.m
- AppCheck/Tests/Unit/DebugProvider/GACAppCheckDebugProviderAPIServiceTests.m
- AppCheck/Tests/Unit/DeviceCheckProvider/GACDeviceCheckAPIServiceTests.m
- AppCheck/Tests/Utils/Date/GACDateTestUtils.h
- AppCheck/Tests/Utils/Date/GACDateTestUtils.m
- AppCheck/Tests/Utils/URLSession/GACURLSessionOCMockStub.h
- AppCheck/Tests/Utils/URLSession/GACURLSessionOCMockStub.m
Copied `FIRDateTestUtils` (as `GACDateTestUtils`) and `FIRURLSessionOCMockStub` (as `GACURLSessionOCMockStub`) from the `SharedTestUtilities` directory in the root of the repo into `AppCheck/Tests/Utils/...`. The `SharedTestUtilities` directory won't be available when `AppCheck` is moved into a separate repo.
#no-changelog
> [App Check] Copy SharedTestUtilities for Lite SDK

- AppCheck/Sources/AppAttestProvider/GACAppAttestProvider.m
- AppCheck/Sources/Core/APIService/GACAppCheckAPIService.h
- AppCheck/Sources/Core/APIService/GACAppCheckAPIService.m
- AppCheck/Sources/DebugProvider/GACAppCheckDebugProvider.m
- AppCheck/Sources/DeviceCheckProvider/GACDeviceCheckProvider.m
- AppCheck/Sources/Public/AppCheck/GACAppAttestProvider.h
- AppCheck/Tests/Integration/GACDeviceCheckAPIServiceE2ETests.m
- AppCheck/Tests/Unit/AppAttestProvider/GACAppAttestProviderTests.m
- AppCheck/Tests/Unit/Core/GACAppCheckAPIServiceTests.m
- FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m
- FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestProviderTests.m
Allows clients to override the default base URL for the App Check service (`https://firebaseappcheck.googleapis.com/v1`) with a custom URL (e.g., `https://staging-firebaseappcheck.sandbox.googleapis.com/v1beta`).
#no-changelog
> [App Check] Support custom base URL

- AppCheck/Sources/AppAttestProvider/API/GACAppAttestAPIService.m
Hardcoded the `limited_use` request parameter to `true` in App Check requests for App Attest. This requests a short-lived App Check token with a TTL of 5 minutes.
Note: This feature is only available in the `v1beta` API of App Check.
#no-changelog
> [App Check] Set `limited_use` request param for App Attest

- AppCheck/Sources/AppAttestProvider/API/GACAppAttestAPIService.h
- AppCheck/Sources/AppAttestProvider/API/GACAppAttestAPIService.m
- AppCheck/Sources/AppAttestProvider/GACAppAttestProvider.m
- AppCheck/Sources/Public/AppCheck/GACAppAttestProvider.h
- AppCheck/Tests/Unit/AppAttestProvider/GACAppAttestAPIServiceTests.m
- AppCheck/Tests/Unit/AppAttestProvider/GACAppAttestProviderTests.m
Added a constructor to `GACAppAttestProvider` with a `limitedUse` parameter to enable short-lived tokens. This was hardcoded to `YES` in PR #11544 but the `limited_use` request parameter causes requests to fail when sending to the `v1` App Check API (requires `v1beta`) -- the param is not ignored in `v1`. The existing constructor defaults to `limited_use` being set to `NO`.
Added TODOs to remove or refactor the constructor since the public API may change significantly before the feature launches.
#no-changelog
> [App Check] Add `limitedUse` parameter to `GACAppAttestProvider`

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
- FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthURLPresenter.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthWebUtils.swift
- Start transition of RPC post to async/await calls
- Use `postAA` as an interim function name to do an incremental transition
- Start with the `GetProjectConfigRequest` in `fetchAuthDomain` from this (internal) [link](https://paste.googleplex.com/5238823498809344) from @ryanwilson 
- Also update part of the call tree above `fetchAuthDomain`
> [auth-swift] First internal async-await transtion

- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
The Firestore emulator does not (as of July 14, 2023) send an existence filter when a query is resumed by clients. As a result the client fails to delete documents that were deleted since the query was last run. The emulator will soon be fixed to send the existence filter (Googlers see b/270731363).
There are two bloom filter integration tests, the first of which tried to do as much as it could when running against the emulator and completing successfully if it got that far. That test, though, didn't really validate anything and by it passing it incorrectly implied that the bloom filter logic was validated. This test is now completely skipped when running against the Firestore emulator, which also makes the test simpler and easier to maintain.
These two bloom filter integration tests also …
> Firestore: Disable bloom filter integration tests when using Firestore emulator

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Backend/RPC/FIRGetOOBConfirmationCodeRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRSignUpNewUserRequest.m
- FirebaseAuth/Tests/Unit/FIRAuthTests.m
Note that most of the code are duplicated from the email password sign in flow. Was trying to create a shared helper method but didn't find a good way due to the callback mechanism. Will try to simplify it with async/await after migrate to swift.
> Add reCAPTCHA support to email flows of sign up, send email link, reset password

- .github/workflows/auth.yml
- FirebaseAuth/Sources/Swift/AuthProvider/GameCenterAuthProvider.swift
Add `WarningWorkaround` protocol for Game Center `playerID` which is deprecated in iOS 13.0 but still needed until 13.5 when the `fetchItems` API was introduced.
Reenable CI `pod lib lint` warning checks
> [auth-swift] Game Center playerID warnings; enable CI warnings

- AppCheck/Sources/Core/GACAppCheckLogger.m
- AppCheck/Sources/Public/AppCheck/GACAppCheckLogger.h
- AppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
Replaced the global variable `gGACAppCheckLogLevel` with a class property on a new `GACAppCheckLogger` class.
#no-changelog
> [App Check] Replace `gGACAppCheckLogLevel` with class property

- AppCheck/Sources/AppAttestProvider/GACAppAttestProvider.m
- AppCheck/Sources/Core/Errors/GACAppCheckErrors.m
- AppCheck/Sources/Core/GACAppCheck.m
- AppCheck/Sources/Core/Storage/GACAppCheckStorage.m
Cleaned up or renamed some of the Firebase references in App Check Core (Lite).
#no-changelog
> Cleanup some Firebase references in App Check Core

- FirebaseAuth/Tests/Unit/AuthSerialTaskQueueTests.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift
- FirebaseAuth/Tests/Unit/RPCBaseTests.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
Trigger all RPC fake callbacks with blocks instead of groups.
It makes the code more concise, more straight-line, and more understandable.
> [auth-swift] Unit Tests: RPC faking via blocks instead of groups

- AppCheckCore/Sources/Core/GACAppCheckSettings.m
- AppCheckCore/Sources/Public/AppCheckCore/GACAppCheckSettings.h
- FirebaseAppCheck/Sources/Core/FIRAppCheckSettings.h
- FirebaseAppCheck/Sources/Core/FIRAppCheckSettings.m
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckSettingsTests.m
Added a class `GACAppCheckSettings` that conforms to `GACAppCheckSettingsProtocol` and implemented `FIRAppCheckSettings` as a subclass of it.
#no-changelog
> Implement `FIRAppCheckSettings` as subclass

- FirebaseDynamicLinks/CHANGELOG.md
This was missed in Firebase 10.3.0 because the search for `Unreleased` was case sensitive.
> [Dynamic Links] Fix `unreleased` changelog entry

- AppCheckCore/Sources/AppAttestProvider/GACAppAttestProvider.m
- AppCheckCore/Sources/Core/GACAppCheck.m
- AppCheckCore/Sources/DebugProvider/GACAppCheckDebugProvider.m
- AppCheckCore/Sources/DeviceCheckProvider/GACDeviceCheckProvider.m
- AppCheckCore/Sources/Public/AppCheckCore/GACAppAttestProvider.h
- AppCheckCore/Sources/Public/AppCheckCore/GACAppCheck.h
- AppCheckCore/Sources/Public/AppCheckCore/GACAppCheckDebugProvider.h
- AppCheckCore/Sources/Public/AppCheckCore/GACAppCheckTokenDelegate.h
- AppCheckCore/Sources/Public/AppCheckCore/GACDeviceCheckProvider.h
- AppCheckCore/Tests/Unit/AppAttestProvider/GACAppAttestProviderTests.m
- AppCheckCore/Tests/Unit/Core/GACAppCheckTests.m
- AppCheckCore/Tests/Unit/DebugProvider/GACAppCheckDebugProviderTests.m
- AppCheckCore/Tests/Unit/DeviceCheckProvider/GACDeviceCheckProviderTests.m
- AppCheckCore/Tests/Unit/Swift/AppCheckAPITests.swift
- FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m
- FirebaseAppCheck/Sources/DebugProvider/FIRAppCheckDebugProvider.m
- FirebaseAppCheck/Sources/DeviceCheckProvider/FIRDeviceCheckProvider.m
- FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestProviderTests.m
- FirebaseAppCheck/Tests/Unit/DebugProvider/FIRAppCheckDebugProviderTests.m
- FirebaseAppCheck/Tests/Unit/DeviceCheckProvider/FIRDeviceCheckProviderTests.m
For consistency, renamed both `instanceName` and `storageID` to `serviceName` for consistency. Please feel free to suggest different names. 
In all cases, the `serviceName` is an identifier that differentiates multiple `GACAppCheck` instances such as when there are multiple `FIRApp`s in use, or multiple dependent SDKs (e.g., Firebase and Google Sign-In). This unique identifier ensures their state is not shared in the Keychain or in User Defaults.
#no-changelog
> [App Check] Rename `instanceName` and `storageID` to `serviceName`

- Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.m
- Crashlytics/Crashlytics/Controllers/FIRCLSNotificationManager.m
- Crashlytics/Crashlytics/Helpers/FIRCLSDefines.h
- Crashlytics/Shared/FIRCLSMachO/FIRCLSMachO.m
- Crashlytics/UnitTests/FIRCLSMachO/FIRCLSMachOTests.m
- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/AuthProvider/OAuth/FIROAuthProvider.m
- FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRFederatedAuthProvider.h
- FirebaseAuth/Sources/SystemService/FIRAuthAPNSTokenManager.m
- FirebaseAuth/Sources/SystemService/FIRAuthNotificationManager.m
- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Sources/Utilities/FIRAuthDefaultUIDelegate.m
- FirebaseAuth/Sources/Utilities/FIRAuthURLPresenter.h
- FirebaseAuth/Sources/Utilities/FIRAuthURLPresenter.m
- FirebaseAuth/Sources/Utilities/FIRAuthWebView.h
- FirebaseAuth/Sources/Utilities/FIRAuthWebView.m
- FirebaseAuth/Sources/Utilities/FIRAuthWebViewController.m
- FirebaseAuth/Tests/Unit/FIRAuthAPNSTokenManagerTests.m
- FirebaseAuth/Tests/Unit/FIRAuthURLPresenterTests.m
- FirebaseAuth/Tests/Unit/FIROAuthProviderTests.m
- FirebaseAuth/Tests/Unit/FIRPhoneAuthProviderTests.m
- FirebaseCore/CHANGELOG.md
- FirebaseCore/Tests/Unit/FIRFirebaseUserAgentTests.m
- FirebaseMessaging/Sources/FIRMessaging.m
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
In Xcode 15 beta 5, `TARGET_OS_XR` was replaced with `TARGET_OS_VISION` in ObjC and `os(xrOS)` was replaced with `os(visionOS)` in Swift.
> [visionOS] Replace `TARGET_OS_XR` with `TARGET_OS_VISION`

- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift
YYYY = year according to "Week of year" format
yyyy = regular year, that matches with the year-month-day format
> Fix HeartbeatsPayload using incorrect year format

- FirebaseCore/Internal/Tests/Unit/HeartbeatsPayloadTests.swift
Verified that test fails with pre-#11611 formatter.
#no-changelog
> [CoreInternal] Add regression test for fix in #11611

- Package.swift
Updated the Firestore binary target in `Package.swift` for version `10.13.0`.
#no-changelog
> [Firestore] 10.13.0 SPM update

- ReleaseTooling/Sources/ZipBuilder/ModuleMapBuilder.swift
- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
While header-only internal Interop pods for binary distributions don't need to be built for Objective-C internal dependencies, the included module dependencies are needed for internal Swift implementations like FirebaseStorage and FirebaseFunctions.
However, the module map calculation uses platform-agnostic dependencies for setting up a `Podfile` for its `pod install` . This has the side effect of causing a crash when building the iOS-only ReCaptchaInterop.
That issue should become moot if we address #8945 and switch to dynamic libraries along with `xcodebuild` generated modulemaps for Firebase 11.
> Fix crash building a module map for a product with an iOS-only Interop dependency

- FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift
- FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
> [auth-swift] Implement fake with subclass instead of a library bool

- Firestore/Example/Tests/Integration/API/FIRAggregateTests.mm
- Firestore/Example/Tests/Integration/API/FIRCountTests.mm
- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
- Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
Use a different Firestore instance to delete documents in `testResumingAQueryShouldUseBloomFilterToAvoidFullRequery` instead of a transaction. A transaction is more complicated and subject to re-runs, whereas using a separate Firestore instance is simple.
Also, modify tests to use the new method `[FSTIntegrationTestCase commitWriteBatch]` that previously manually implemented the "expectation" logic to wait for the commit result.
This is a port of https://github.com/firebase/firebase-js-sdk/pull/7415 and https://github.com/firebase/firebase-js-sdk/pull/7486
#no-changelog
> Firestore: FIRQueryTests.mm: Use a different Firestore instance to delete documents instead of a transaction

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Sources/Swift/SystemService/AuthNotificationManager.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthDefaultUIDelegate.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthURLPresenter.swift
- FirebaseAuth/Tests/Unit/AuthNotificationManagerTests.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- FirebaseAuth/Tests/Unit/OAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
- Package.swift
- Address compile time failures for app extensions in Auth.swift (thanks to @ryanwilson for the incantation)
- Similar extension build fix for AuthDefaultUIDelegate.swift
- Fix and simplify implementation and unit tests for AuthNotificationManager
- Fix a unit test flake 
- Disable unit tests for SPM that rely on `UIApplication.shared` being non-zero
> [auth-swift] Fix Extensions build, AuthNotificationManager fixes

- scripts/check_copyright.sh
- Added handling for an empty list of files with invalid copyright declarations.
- This should resolve the CI failure in https://github.com/google/app-check/pull/6.
- Fixed indentation to 2 spaces.
#no-changelog
> [CI] Handle empty list in `check_copyright.sh`

- Firestore/Source/API/FIRQuery.mm
- Firestore/core/src/core/query.cc
- Firestore/core/src/core/query.h
- Firestore/core/test/unit/core/query_test.cc
> Fix: Aggregate query order-by normalization

- FirebaseCore/Sources/FIRApp.m
- FirebaseCore/Tests/Unit/FIRAppTest.m
Within FirebaseCore's implementation, there was a misnomer where the string "fingerprinting"  was incorrectly used to describe parts of the implementation that validates that the Firebase app ID contains a valid bundle ID hash. This validation serves to catch issues with a developer's Firebase options (which are either custom provided or set by the `GoogleService-Info.plist`). The implementation does **not** actually do any _fingerprinting_.  
#no-changelog
> [Core] Fix API misnomer within FIRApp.m

- FirebaseStorage/Sources/Storage.swift
- FirebaseStorage/Sources/StorageDownloadTask.swift
- FirebaseStorage/Sources/StorageObservableTask.swift
- FirebaseStorage/Sources/StorageTask.swift
- FirebaseStorage/Sources/StorageUploadTask.swift
Fixes #11653. I did not document Storage as thread-safe because its properties and `ensureInitialized()` have no thread-safety protections.
> update thread-safety docs on Storage

- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckAvailability.h
- FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
- Updated the `FIR_DEVICE_CHECK_PROVIDER_AVAILABILITY` and `FIR_APP_ATTEST_PROVIDER_AVAILABILITY` API availability macros to reflect the set of supported platforms for [DeviceCheck](https://developer.apple.com/documentation/devicecheck/dcdevice/2891519-supported) (iOS 11+, macOS 10.15+, macCatalyst 13+, tvOS 11+, watchOS 9+) and [App Attest](https://developer.apple.com/documentation/devicecheck/dcappattestservice/3573915-supported) (iOS 14+, macOS 11.3+, macCatalyst 14.5+, tvOS 15+, watchOS 9+).
- Removed the extraneous check for the watchOS 9 SDK now that Xcode 14 is the minimum supported by Firebase.
- Removed the `#if TARGET_OS_IOS` compiler directive in `AppCheckAPITests.swift` since `TARGET_OS_IOS` is only available in Objective-C and was always false.
#no-changelog
> [App Check] Fix App Attest and DeviceCheck API availability

- FirebaseCore/CHANGELOG.md
- FirebaseSessions/Sources/SessionInitiator.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/Library/LifecycleNotifications.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
In Xcode 15 beta 6, `#if os(iOS)` no longer evaluates to true when building for visionOS.
Note: `TARGET_OS_IOS` continues to be defined so Objective-C code is unchanged.
> [visionOS] Fix Sessions SDK build on Xcode 15 beta 6

- FirebaseCombineSwift/Sources/Auth/Auth+Combine.swift
- FirebaseCombineSwift/Sources/Auth/MultiFactor+Combine.swift
- FirebaseCombineSwift/Sources/Auth/MultiFactorResolver+Combine.swift
- FirebaseCombineSwift/Sources/Auth/OAuthProvider+Combine.swift
- FirebaseCombineSwift/Sources/Auth/PhoneAuthProvider+Combine.swift
Firebase 7.2+ requires Xcode 12+, which includes Combine support and Swift 5.3; the `canImport(Combine)` and `swift(>=5.0)` checks should now be extraneous.
#no-changelog
> [Combine] Remove `canImport(Combine)` and `swift(>=5.0)` checks

- FirebaseABTesting/Sources/FIRExperimentController.m
@paulb777 @morganchen12 @karenyz Please take a look! This PR is a follow-up to https://github.com/firebase/firebase-ios-sdk/pull/11379
The above linked PR fixes iterating over an array that can be mutated simultaneously elsewhere, but it only fixes it for the `experiments` array. I have been seeing crashes in my app using FirebaseABTesting on 10.12.0, but for the `payloads` array. 
This file has three locations that iterate over `payloads`, and the two other locations do `[payloads copy]` to avoid this problem, and this is the last callsite of `payloads` in this file without a matching `copy` to avoid this crash.
Fixes:
Text:
```
Fatal Exception: NSGenericException
0  CoreFoundation                 0x9cb4 __exceptionPreprocess
1  libobjc.A.dylib                0x183d0 objc_exception_throw …
```
> Fix mutating array during iteration crash

- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
In Firestore's FIRQueryTests.mm, replace the hand-written SortedStringsNotIn() function with the standard XCTAssertEqualObjects() invoked with NSSet arguments. There was no reason to re-invent the wheel.
#no-changelog
> Firestore: FIRQueryTests.mm: Replace SortedStringsNotIn() custom function

- Crashlytics/Shared/FIRCLSFABHost.m
This method should behave exactly the same as the old code. Here is the GoogleUtilities implementation: https://github.com/google/GoogleUtilities/blob/main/GoogleUtilities/Environment/GULAppEnvironmentUtil.m#L160-L191 This is also consistent with the FirebaseSessions SDK
#no-changelog
> Update Crashlytics to use Google Utilities deviceSimulatorModel

- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Models/AuthProvider.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/UserViewController.swift
Go from first screen shot to second screenshot. The second and third sections are now labeled with headers instead of footers. (Also fix a logic bug introduced in UserViewController.swift in the previous PR)
> [auth-swift] Use headers instead of footers in Sample

- .github/workflows/firestore.yml
- scripts/build.sh
This PR includes a few improvements to Firestore's CI jobs:
* Always trigger Firestore workflow, but change the workflow to skip its jobs if no firestore changes are detected.
* Introduce a new job `check-required-tests` to the workflow to check if all required jobs are successful or skipped. This should be the required check.
* Add parallelization parameters to xcodebuild
* Skip a `build` step with xcodebuild, and only do `test` which triggers `build` anyways. This removes a redundant `build` run. This should be applied to other components as well.
Workflow with firestore change: https://github.com/firebase/firebase-ios-sdk/actions/runs/5932626191/job/16086899587?pr=11708
Workflow without firestore change: https://github.com/firebase/firebase-ios-sdk/actions/runs/5939661290/job/1610652897 …
> Run xcodebuild in parallel for firestore

- .github/workflows/firestore.yml
- scripts/build.sh
* Fix scheduled firestore workflow
* Fix buildcache/ccache for firestore workflow, this should help reduce the workflow runtime to around 30 minutes.
> Fix buildcache/ccache for Firestore workflow

- FirebaseRemoteConfig.podspec
- FirebaseRemoteConfigSwift.podspec
- FirebaseRemoteConfigSwift/Exporter/Exporter.swift
- FirebaseRemoteConfigSwift/Sources/Codable.swift
- FirebaseRemoteConfigSwift/Sources/FirebaseRemoteConfigValueDecoderHelper.swift
- FirebaseRemoteConfigSwift/Sources/PropertyWrapper/RemoteConfigProperty.swift
- FirebaseRemoteConfigSwift/Sources/PropertyWrapper/RemoteConfigValueObservable.swift
- FirebaseRemoteConfigSwift/Sources/Value.swift
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/Codable.swift
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/PropertyWrapperDefaultConfigsTests.swift
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/PropertyWrapperTests.swift
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/Value.swift
- Package.swift
The test specs to test the Swift library code are still part of the `RemoteConfigSwift.podspec`.  I'm leaving them there temporarily to reduce the amount of changes to get this tested across CI. 
I have also left the Swift library sources in the `RemoteConfigSwift` directory. These and the tests mentioned earlier should likely be moved into a reorganized `RemoteConfig` directory.
Different to #11386 in that this PR is aimed to merge the two libraries in a non-breaking way.
---
- The `FirebaseRemoteConfigSwift` pod now exports the `FirebaseRemoteConfig` module and has no APIs.
- The Swift extension sources are added to the `FirebaseRemoteConfig` pod, making it a mixed lang. pod.
- The `FirebaseRemoteConfigSwift` target now exports the `FirebaseRemoteConfig` module and has no APIs.
- …
> [Config] Merge RemoteConfig and its Swift extension in a non-breaking way

- FirebaseFunctions/Tests/Integration/IntegrationTests.swift
- FirebaseSessions/Tests/Unit/RemoteSettingsTests.swift
- FirebaseSessions/Tests/Unit/SessionsSettingsTests.swift
- FirebaseSharedSwift/Tests/Codable/FirebaseDataEncoderTests.swift
[Closes #11736]
* Updated Firebase Functions’s `IntegrationTests` to prevent the testing process from crashing in case of test failure
* Updated `RemoteSettingsTests`, `SessionsSettingsTests`, and `FirebaseFirebaseDataEncoderTests` to generate fewer compiler warnings
> [#11736] Tests Housekeeping

- Firestore/core/src/model/target_index_matcher.cc
- Firestore/core/src/model/target_index_matcher.h
> Add `const` for target index matcher

- FirebaseRemoteConfig/Swift/Codable.swift
- FirebaseRemoteConfig/Swift/SPMSwiftHeaderWorkaround.swift
This is an improvement over the old diff for a few reasons:
- Swift clients will now get a build error if they try to use the property (major improvement)
- Moved it to it's own file as it had nothing to do with the file it was previously in (minor improvement)
- IMO, naming it `__no_op` with a useless function seems a better name than `__do_not_call` that returns an empty string (minor improvement)
- I made the property static to reduce where it's scope of use. (minor improvement)
- The API no longer depends on any types from Foundation (minor improvement)
#no-changelog
> [Config] Lock down no-op API's availability for Swift clients

- FirebaseRemoteConfigSwift/Tests/SwiftAPI/FirebaseRemoteConfigSwift_APIBuildTests.swift
Manually tested against the pending `rc-swift-merged` branch and the build tests passed.
Note– prefixing types with the module name that exports it is a good practice to assert that the API is being exported by the expected module.
Working on this surfaced some small un-Swifty parts of the generated Swift API. I've marked them with TODOs for future Swiftification efforts.
#no-changelog
> [Config] Add Config and ConfigSwift API build tests

- Package.swift
- update URL to point to 10.15.0 resource
- update checksum
#no-changelog
> [Release] Update Package.swift with 10.15.0 RC0 Firestore binary artifact URL

- Crashlytics/Crashlytics/Components/FIRCLSContext.h
- Crashlytics/Crashlytics/Components/FIRCLSContext.m
- Crashlytics/Crashlytics/Controllers/FIRCLSContextManager.m
- Crashlytics/Crashlytics/Helpers/FIRCLSContextInitData.h
- Crashlytics/Crashlytics/Helpers/FIRCLSContextInitData.m
I'm getting a crash during startup using 10.13.0, 10.12.0, 10.3.0 and master.
This happens on an iPad (6th generation) running 16.6.
It happens all the time with our app when the Address Sanitizer is on and Detect use of stack after return is on.
In [FIRCLSContextManager setupContextWithReport:settings:fileManager],
1. A instance of the FIRCLSContextInitData struct is assigned to initDataObj but it's still a struct.
2. The pointer of it is assigned to initData.
3. The initData pointer is passed to asynchronous functions. The pointer is captured by not what it points at.
4. FIRCLSContextInitData returns
5. When the async functions run they try to access the stack and crash.
In this PR I've made FIRCLSContextInitData a class and copy the strings into it instead of storing a pointer to the …
> Fix FIRCLSContextInitData crash

- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
- Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
#no-changelog
ported from: https://github.com/firebase/firebase-js-sdk/pull/7457
> Add test cases for existence filter with updated, removed, added documents

- FirebaseMessaging/CHANGELOG.md
This release note refers to an implementation detail that has no effect on clients.
#no-changelog
> [Docs] Remove unneeded release note

- Crashlytics/Shared/FIRCLSMachO/FIRCLSMachO.m
Relate to this change https://github.com/firebase/firebase-ios-sdk/pull/11515/files
Instead of passing NULL to macho_cpu_type_for_arch_name, we want to pass the slice header address to find correct arch for the dSYM.
#no-changelog
> fix vision pro unit tests

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample.xcodeproj/project.pbxproj
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/SettingsViewController.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExampleUITests/SettingsUITests.swift
Successor PR to #11723
- Implement rest of Settings screen UI
- Implement functionality except for Phone Auth section (needs a device)
- Fix missing implementation of languageCode API
- Fix a few more access specifications in Auth.swift
- Add UI tests for Settings screen
Objective C app screenshot
Swift app screenshot
#no-changelog
> [auth-swift] Sample app Settings screen 2

- FirebaseAppCheck.podspec
- FirebaseAppCheck/Interop/FIRAppCheckProtocol.h
- FirebaseAppCheck/Sources/Core/FIRAppCheck.m
- FirebaseAppCheck/Sources/Core/FIRAppCheckComponent.m
- FirebaseAppCheck/Sources/Core/FIRAppCheckTokenResult.h
- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheck.h
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckIntegrationTests.m
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckTests.m
- Package.swift
- SharedTestUtilities/AppCheckFake/FIRAppCheckFake.h
- SharedTestUtilities/AppCheckFake/FIRAppCheckTokenResultFake.h
Added a protocol named `FIRAppCheckProtocol` to the `FirebaseAppCheckInterop` SDK that duplicates the token fetching public APIs of `FIRAppCheck`. Updated `FIRAppCheck` to publicly conform to `FIRAppCheckProtocol`.
This will allow other SDKs to accept an instance of App Check through a parameter of type `id<FIRAppCheckProtocol>`, while not requiring a hard dependency on `FirebaseAppCheck`.
#no-changelog
> Add `FIRAppCheckProtocol` to `FirebaseAppCheckInterop` SDK

- FirebaseDatabase.podspec
Fix #11811 
After #11660 SharedTestUtilities imports FirebaseAppCheck as a module instead of includes. As a result the unit test build failed because it didn't know where to find the import.
I also updated the library source reference to be consistent with the tests and other Firebase products.
> Fix Database unit test build regression

- FirebaseDatabase/Sources/Api/FIRDatabaseComponent.m
- FirebaseDatabase/Sources/Login/FIRDatabaseConnectionContextProvider.m
- Package.swift
Follow up to #11812 
Changing the podspec to get FirebaseAppCheckInterop via the module means that the module should be imported instead of the headers.
> More fixes for AppCheckInterop

- .github/workflows/firestore.yml
This surfaced in failures in the pending #11806. These changes aren't directly dependent to that PR so they can merge early to prevent potential issues in other branches.
#no-changelog
> [Infra] Break up env-dependent GHA steps into separate job to reduce artifact collisions

- ReleaseTooling/Sources/ZipBuilder/ModuleMapBuilder.swift
This resolves undefined symbol errors when using Firestore via SPM and building a target _for testing_. See issue 11656.
All three are needed. Interestingly, abseil is not. Likewise, there were missing leveldb and nanonpb symbols. I'd like to understand why.
I can't pin the behavior difference to an Xcode 15 release note, but it may be related to [this](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#:~:text=Xcode%20now%20automatically,incremental%20builds.%E2%80%A8%20(99972271)) one.
Some other approaches that may work here (though I think generalizing the current approach may be best):
1.  Add modular imports of these frameworks into Firestore's source. I was not successful at it so far, but I suspect another way to link the missing symbols in is to …
> [Release Tooling] Explicitly FST link direct/transitive deps. in module.modulemap

- CONTRIBUTING.md
- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/SystemService/FIRAuthAppCredentialManager.m
- FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m
- README.md
- scripts/setup_check.sh
- scripts/style.sh
Switched to the Homebrew `clang-format@17` formula since `clang-format@16` is no longer available and ran `scripts/style.sh`.
#no-changelog
> Upgrade to `clang-format` v17

- FirebasePerformance/CHANGELOG.md
- FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m
> Fix Xcode 15 runtime warning

- FirebaseFirestore.podspec
- Firestore/CHANGELOG.md
Downgrade grpc CocoaPods dependency to 1.44.0 (was 1.50.1) as a workaround for a Firestore crash on iOS 12 that happens with with grpc 1.50.0 and newer: https://github.com/firebase/firebase-ios-sdk/issues/11509. Leave the cmake and swift package manager dependencies at 1.50 since they do not experience this crash.
A workaround for this crash is planned to be merged into grpc upstream (https://github.com/grpc/grpc/pull/34416). Once released (and a few other unrelated grpc build issues with Firestore are fixed) the grpc dependency will be re-upgraded to a version that includes the workaround.
Note: This PR effectively reverts #10650.
Fixes #11509
> Firestore: Downgrade grpc CocoaPods dependency to 1.44.0 (was 1.50.1)

- Firestore/CHANGELOG.md
Updated the changelog entry from `Unreleased` to `10.16.0`.
> [Firestore] Update CHANGELOG entry version

- .github/workflows/zip.yml
Fix #11848
The `check_framework_firestore_symbols` depends on SPM and CocoaPods being aligned on gRPC dependency versions.
After #11846, they no longer are. I created #11849 to track realigning the grprc versions and restoring this test.
> Temporarily disable failing test

- Package.swift
> [Release] Test with gRPC 1.44 and absl 20211102

- Package.swift
- Updated the URL to point to the Firestore 10.16.0 binary
- Updated the checksum to match the new binary artifact
#no-changelog
> [Release] Update Package.swift with 10.16.0 RC0 Firestore binaryTarget

- FirebaseAppCheck/Interop/FIRAppCheckProtocol.h
This is a no-op change externally but requires one less transformation for use internally (where modules aren't supported).
#no-changelog
> Switch to `#import <Foundation/Foundation.h>` in `FIRAppCheckProtocol.h`

- FirebaseFirestore.podspec
- Package.swift
Update grpc to 1.49.1 so that we don't have to change the abseil version from 10.15.0 since we don't have the abseil version associated with grpc 1.44.0 available for SPM
> Update grpc to 1.49.1

- FirebaseAuth/Sources/Backend/FIRAuthBackend.h
- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/Backend/RPC/FIRStartPasskeyEnrollmentRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRStartPasskeyEnrollmentRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRStartPasskeyEnrollmentResponse.h
- FirebaseAuth/Sources/Backend/RPC/FIRStartPasskeyEnrollmentResponse.m
- FirebaseAuth/Tests/Unit/FIRStartPasskeyEnrollmentRequestTests.m
- FirebaseAuth/Tests/Unit/FIRStartPasskeyEnrollmentResponseTests.m
Copy of PR https://github.com/firebase/firebase-ios-sdk/pull/11748
1.  Rebased from master to use the most recent changes from FIRAuthBackend.m.
2. Added startPasskeyEnrollmentRequest header and implementation
3. Added startPasskeyEnrollmentResponse header and implementation
4. Implemented the FIRAuthBackend startPasskeyEnrollment method
5. Added unit tests.
Changes different from #11748
* Updated credentialID and userID from NSData to NSString
* Uses the new request init method initWithEndpoint:requestConfiguration: and update the backend call from postWithRequest to callWithRequest.
> [Passkey #1 cloned] start passkey enrollment rpc

- .github/workflows/zip.yml
This reverts commit 02f21660b2c3fa1453a975f3443a753540b2d348.
Fix #11849
I forgot to restore this earlier when we realized that we needed to keep the gRPC versions the same for both CocoaPods and SPM to release.
> Revert "Temporarily disable failing test (#11850)"

- FirebaseAuth/Sources/Backend/FIRAuthBackend.h
- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/Backend/RPC/FIRStartPasskeySignInRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRStartPasskeySignInRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRStartPasskeySignInResponse.h
- FirebaseAuth/Sources/Backend/RPC/FIRStartPasskeySignInResponse.m
- FirebaseAuth/Tests/Unit/FIRStartPasskeySignInRequestTests.m
- FirebaseAuth/Tests/Unit/FIRStartPasskeySignInResponseTests.m
1. Implemented start passkey sign in rpc call
2. Defined startPasskeySignInRequest & Response
3. Added Unit tests
This flow has been tested against backend.
> [passkey #3] startPasskeySignIn RPC call

- FirebaseAuth/Sources/Backend/FIRAuthBackend.h
- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/Backend/FIRAuthRPCResponse.h
- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeyEnrollmentRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeyEnrollmentRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeyEnrollmentResponse.h
- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeyEnrollmentResponse.m
- FirebaseAuth/Tests/Unit/FIRFinalizePasskeyEnrollmentRequestTests.m
- FirebaseAuth/Tests/Unit/FIRFinalizePasskeyEnrollmentResponseTests.m
1. Implemented finalizePasskeyEnrollment rpc call
2. Defined finalizePasskeyEnrollment Request and Response object
3. Added unit tests
> [Passkey #2] finalize passkey enrollment rpc

- .github/actions/notices_generation/Gemfile
- .github/workflows/notice_generation.yml
I erroneously removed cocoapods from the Gemfile in #11899 because it wasn't used for the Gemfile.lock. It is needed for the CI job. I also enabled the CI job to run immediately when it gets changed.
Fix #11901
> Fix notice generation

- FirebaseAuth/Sources/Backend/FIRAuthBackend.h
- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeyEnrollmentResponse.h
- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeySignInRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeySignInRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeySignInResponse.h
- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeySignInResponse.m
- FirebaseAuth/Tests/Unit/FIRFinalizePasskeySignInRequestTests.m
- FirebaseAuth/Tests/Unit/FIRFinalizePasskeySignInResponseTests.m
1. Implemented the call to finalizePasskeySignIn RPC
2. Defined finalizePasskeySignInRequest & Response
3. Added unit tests
This flow has been tested against backend staging endpoint.
> [Passkey #4] finalizePasskeySignIn rpc

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
- FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift
- FirebaseAuth/Sources/Swift/MultiFactor/MultiFactorResolver.swift
- FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPMultiFactorGenerator.swift
- FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift
- FirebaseAuth/Sources/Swift/User/AdditionalUserInfo.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthWebUtils.swift
- FirebaseAuth/Tests/Unit/AuthBackendRPCImplentationTests.swift
- FirebaseAuth/Tests/Unit/CreateAuthURITests.swift
- FirebaseAuth/Tests/Unit/DeleteAccountTests.swift
- FirebaseAuth/Tests/Unit/EmailLinkSignInTests.swift
- FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift
- FirebaseAuth/Tests/Unit/GetAccountInfoTests.swift
- FirebaseAuth/Tests/Unit/GetOOBConfirmationCodeTests.swift
- FirebaseAuth/Tests/Unit/GetProjectConfigTests.swift
- FirebaseAuth/Tests/Unit/RPCBaseTests.swift
- FirebaseAuth/Tests/Unit/ResetPasswordTests.swift
- FirebaseAuth/Tests/Unit/RevokeTokenTests.swift
- FirebaseAuth/Tests/Unit/SendVerificationCodeTests.swift
- FirebaseAuth/Tests/Unit/SetAccountInfoTests.swift
- FirebaseAuth/Tests/Unit/SignInWithGameCenterTests.swift
- FirebaseAuth/Tests/Unit/SignUpNewUserTests.swift
- FirebaseAuth/Tests/Unit/VerifyAssertionTests.swift
- FirebaseAuth/Tests/Unit/VerifyClientTests.swift
- FirebaseAuth/Tests/Unit/VerifyCustomTokenTests.swift
- FirebaseAuth/Tests/Unit/VerifyPasswordTests.swift
- FirebaseAuth/Tests/Unit/VerifyPhoneNumberTests.swift
Rename `post` to `call` to mirror #11681.
I'll do the rest of #11681 in a separate PR
> [auth-swift] post to call rename

- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
These changes are needed to build correct xcframeworks for mixed language CocoaPods. They were informed by work in #11806.
The release tooling [creates custom module maps](https://github.com/firebase/firebase-ios-sdk/pull/4895) for some SDKs (e.g. Firestore). The contents of the custom module map is stored in memory until it is written to disk when the slices of the xcframework are assembled. During this assembly, the release tooling currently makes the assumption that if a Swift module is present, the SDK is a pure Swift SDK and it uses the module map contents generated by CocoaPods (which modularizes the Swift header with a submodule). This is problematic since the custom module map contents in memory are ignored.
For mixed language SDKs, the custom module map contents should be …
> [Release Tooling] Create module maps for mixed language targets

- FirebaseCore/Sources/FIRApp.m
- FirebaseCore/Tests/Unit/FIRAppTest.m
In Xcode 15.1 `TARGET_OS_IOS` is now `0` instead of `1` on visionOS. This PR fixes the build and unit tests of Firebase Core on Xcode 15.1 beta 1.
Note: https://github.com/google/GoogleUtilities/pull/132 is also needed to fix the build (not yet tagged / released).
> [visionOS] Fix FirebaseCore build and tests on Xcode 15.1 beta 1

- FirebaseAppCheckInterop.podspec
I'm not sure why the CI in #11860 didn't surface this. 
I locally tried to stage the FirebaseAppCheckInterop.podspec after merging #11860 and saw:
```
Validating spec
-> FirebaseAppCheckInterop (10.17.0)
- NOTE  | url: The URL (https://twitter.com/Firebase) is not reachable.
🔥    - WARN  | file patterns: The `public_header_files` pattern did not match any file.
- NOTE  | xcodebuild:  note: Building targets in dependency order
- NOTE  | [iOS] xcodebuild:  /var/folders/hz/7v68p4h95sb2ypb614xp20jc00r7sc/T/CocoaPods-Lint-20231011-82337-1s67496-FirebaseAppCheckInterop/App.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is …
```
> [AppCheck] Fix 'public_headers_dir' in 'FirebaseAppCheckInterop.podspec'

- .github/workflows/auth.yml
- .github/workflows/firebase_app_check.yml
- .github/workflows/messaging.yml
We currently don't lint interop podspecs, but we should. See https://github.com/firebase/firebase-ios-sdk/pull/11928#issuecomment-1758671837
#no-changelog
> [Infra] Lint interop podspecs in GHA

- FirebaseMessaging/Sources/FIRMessagingUtilities.m
- FirebaseMessaging/Sources/Token/FIRMessagingAuthKeychain.m
In Xcode 15.1 `TARGET_OS_IOS` is now `0` instead of `1` on visionOS. This PR fixes the build of Firebase Messaging on Xcode 15.1 beta 1 (and `MessagingUnit` passes).
Note: https://github.com/google/GoogleUtilities/pull/132 is also needed to fix the build (not yet tagged / released).
#no-changelog
> [visionOS] Fix FirebaseMessaging build on Xcode 15.1 beta 1

- .github/workflows/database.yml
- FirebaseDatabase.podspec
- FirebaseDatabase/CHANGELOG.md
- FirebaseDatabase/Swift/Sources/Codable/DataSnapshot+ReadDecodable.swift
- FirebaseDatabase/Swift/Sources/Codable/DatabaseReference+WriteEncodable.swift
- FirebaseDatabase/Swift/Sources/Codable/EncoderDecoder.swift
- FirebaseDatabase/Swift/Sources/Codable/ServerTimestamp.swift
- FirebaseDatabase/Swift/Sources/SPMSwiftHeaderWorkaround.swift
- FirebaseDatabaseSwift.podspec
- FirebaseDatabaseSwift/CHANGELOG.md
- FirebaseDatabaseSwift/Sources/FirebaseDatabaseSwift.swift
- Package.swift
- ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
**Context**
- The contents of RTDB's Swift extension SDK has been moved into the main RTDB module, and the RTDB Swift extension SDK now re-exports the API that used to live in it.
- This change should be non-breaking.
---
**Tasks**
---
**Important**
- This PR contains an assumption in the source code that docs will be at hosted at https://firebase.google.com/docs/ios/swift-migration cc: @morganchen12
> [Database] Consolidate Database and DatabaseSwift

- FirebaseDatabase/Sources/Core/FPersistentConnection.m
- FirebaseDatabase/Sources/Core/FRepo.m
- FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m
- FirebaseDatabase/Sources/Realtime/FWebSocketConnection.m
In Xcode 15.1 `TARGET_OS_IOS` is now `0` instead of `1` on visionOS. This PR fixes the build and unit tests for RTDB on Xcode 15.1 beta 1 / visionOS.
Note: https://github.com/google/GoogleUtilities/pull/132 is also needed to fix the build (not yet tagged / released).
#no-changelog
> [visionOS] Fix FirebaseDatabase build on Xcode 15.1 beta 1

- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeyEnrollmentRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRFinalizePasskeySignInRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRStartPasskeyEnrollmentRequest.m
- FirebaseAuth/Sources/Backend/RPC/FIRStartPasskeySignInRequest.m
- FirebaseAuth/Tests/Unit/FIRFinalizePasskeyEnrollmentRequestTests.m
- FirebaseAuth/Tests/Unit/FIRFinalizePasskeySignInRequestTests.m
> [Passkey #6] Update passkey related proto naming change

- Crashlytics/Crashlytics/Components/FIRCLSApplication.m
In Xcode 15.1 `TARGET_OS_IOS` is now `0` instead of `1` on visionOS. This PR fixes the build and for Crashlytics on Xcode 15.1 beta 1 / visionOS.
Note: https://github.com/google/GoogleUtilities/pull/132 is also needed to fix the build (not yet tagged / released).
#no-changelog
> [visionOS] Fix Crashlytics build on Xcode 15.1 beta 1

- FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m
- FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.h
- FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.m
- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckErrors.h
- FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestProviderTests.m
This will allow developers to more granularly determine when errors occur in `FIRAppAttestProvider` (when performing `generateKeyWithCompletionHandler:`, `attestKey:clientDataHash:completionHandler:` or `generateAssertion:clientDataHash:completionHandler:`), along with additional debugging information (`keyId` and `clientDataHash` lengths).
#no-changelog
> [App Check] Add failure reasons for App Attest error cases

- .github/workflows/firebase_app_check.yml
- FirebaseAppCheck/Sources/Core/Errors/FIRAppCheckErrorUtil.m
- Fixed `warning: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead` on watchOS (introduced in #11956).
- Added `watchos` to `pod lib lint` testing matrix.
#no-changelog
> [App Check] Fix warning due to NSUInteger length on watchOS

- FirebaseDatabase/Swift/Sources/SPMSwiftHeaderWorkaround.swift
- FirebaseInAppMessaging/Swift/Source/SPMSwiftHeaderWorkaround.swift
- Firestore/Example/Podfile
- Firestore/Swift/Source/SwiftHeaderWorkaround.swift
- ReleaseTooling/Sources/ZipBuilder/ModuleMapBuilder.swift
Meant to include these in #11954. They don't affect pod spec staging and aren't release critical.
#no-changelog
> [Firestore] Follow-up review items from #11954

- FirebaseFirestore.podspec
- Gemfile
Promising fix for #11973.
Global green test run: https://github.com/firebase/firebase-ios-sdk/pull/11977/checks?sha=35d90ffde73fc0e977e5881a4fd126df3d593e59
#no-changelog
> [Firestore] Fix build-for-testing linking affecting CocoaPods (Approach 1)

- FirebaseAnalyticsSwift/Tests/ObjCAPI/ObjCAPITests.m
- FirebaseAnalyticsSwift/Tests/SwiftUnit/AnalyticsAPITests.swift
Update Analytics swift API tests. #no-changelog
> Update Analytics swift API tests.

- FirebaseRemoteConfigSwift.podspec
Remove unneeded FirebaseCore import (see convo [here](https://github.com/firebase/firebase-ios-sdk/pull/11914#discussion_r1353054971))
> [Config] Update FirebaseRemoteConfigSwift.podspec

- .github/workflows/client_app.yml
- scripts/build.sh
This ensures we are testing both iOS11+ and iOS13+ schemes in the client app. There exists two OS specific schemes for each package manager so SDKs that require iOS 13+ can be separately tested (e.g. FirebaseAnalyticsSwift, FIAMSwift).
#no-changelog
> [Infra] Enable testing for iOS 13+ client app scheme

- FirebaseAppCheck/CHANGELOG.md
- FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m
- FirebaseAppCheck/Tests/Unit/AppAttestProvider/FIRAppAttestProviderTests.m
Resets the stored key ID if [`attestKey:clientDataHash:completionHandler:`](https://developer.apple.com/documentation/devicecheck/dcappattestservice/3573911-attestkey?language=objc) fails due to [`DCErrorInvalidKey`](https://developer.apple.com/documentation/devicecheck/dcerror/dcerrorinvalidkey?language=objc). This should resolve App Check / App Attest failures after app reinstallation, device migration, or restoration of a device from a backup (see [docs](https://developer.apple.com/documentation/devicecheck/establishing_your_app_s_integrity?language=objc)).
> [App Check] Reset App Attest key state if `attestKey` fails

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Backend/RPC/Proto/FIRPasskeyInfo.m
- FirebaseAuth/Sources/Backend/RPC/Proto/FIRPasskeyInfo_Internal.h
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRPasskeyInfo.h
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRUser.h
- FirebaseAuth/Sources/Public/FirebaseAuth/FirebaseAuth.h
- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Sources/User/FIRUser_Internal.h
- FirebaseAuth/Tests/Unit/FIRUserTests.m
- Implemented startPasskeyEnrollmentWithName:completion: public API
- Implemented finalizePasskeyEnrollmentWithPlatformCredential:completion: implementation public API
- Added public data type PasskeyInfo 
- Added relative unit tests
Future PR
Test cases that need "expires_in" changes in first for finalizePasskeyEnrollmentWithPlatformCredential:completion: on both provided passkey name and not provided passkey name.
> [Passkey #7] FIRUser startPasskeyEnrollmentWithName:completion: & finalizePasskeyEnrollmentWithPlatformCredential:completion: implementation

- scripts/build.sh
See description in #11708. `xcodebuild test` will do a build so running `xcodebuild build test` is doing an extra build.
Outstanding follow-up work
#no-changelog
> [Infra] Speed up xcodebuilds by only testing

- .github/workflows/client_app.yml
In addition to the source FST builds in `firestore.yml`, this should add some additional test coverage.
#no-changelog
> [Infra] Add job that builds ClientApp with source Firestore via SPM

- Gemfile
- Gemfile.lock
Updated `cocoapods-generate` to `2.2.5`, which includes Xcode 14/15 fixes:
- https://github.com/square/cocoapods-generate/commit/63d5c28322fd8d9a787d7729c8531417cf347d8b
- https://github.com/square/cocoapods-generate/commit/a602226e509ab82266778396bfd28297be8dbf57
- https://github.com/square/cocoapods-generate/commit/52428d4d45b922e11849bcb2c4a99c89b77db3f7
- https://github.com/square/cocoapods-generate/commit/b212ea0e80f40dd83d913ff9f7346b43d3c0f36e
#no-changelogs
> Update cocoapods-generate to v2.2.5

- FirebasePerformance/CHANGELOG.md
- FirebasePerformance/Sources/Gauges/CPU/FPRCPUGaugeCollector.m
Fix the following:
```
- WARN  | xcodebuild:  /Users/p/gh6/firebase-ios-sdk/FirebasePerformance/Sources/Gauges/CPU/FPRCPUGaugeCollector.m:48:37: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
```
> Fix Xcode 15.1 build warning

- FirebaseMLModelDownloader/CHANGELOG.md
- FirebaseMLModelDownloader/Sources/TelemetryLogger.swift
Migrated from the telemetry logging target `GDTCORTarget.FLL` to `GDTCORTarget.CCT` in the Firebase ML Model Downloader SDK.
#no-changelog
> [ML Model Downloader] Migrate from FLL to CCT logging endpoint

- .github/workflows/core.yml
- scripts/build.sh
Add Xcode 15 CI including visionOS for SPM
#no-changelog
> FirebaseCore CI on Xcode 15

- scripts/zip_quickstart_test.sh
This should fix recent failures in the zip tests trying to run quickstarts on the unavailable iPhone 15 with Xcode 14.2. iPhone 14 shows available in https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md and https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
> Fix zip quickstart regression

- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Auth/FIRAuth_Internal.h
- FirebaseAuth/Sources/Backend/RPC/FIRSignUpNewUserRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRSignUpNewUserRequest.m
- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.h
- FirebaseAuth/Tests/Unit/FIRAuthTests.m
- FirebaseAuth/Tests/Unit/FIRSignUpNewUserRequestTests.m
- FirebaseAuth/Tests/Unit/FIRSignUpNewUserResponseTests.m
- FirebaseAuth/Tests/Unit/FIRUserTests.m
Fix https://github.com/firebase/firebase-ios-sdk/issues/11911
> Use sign up endpoint for link with email password (resubmit #11925)

- .github/workflows/abtesting.yml
- .github/workflows/analytics.yml
- .github/workflows/appdistribution.yml
- .github/workflows/auth.yml
- .github/workflows/core.yml
- .github/workflows/core_extension.yml
- .github/workflows/core_internal.yml
- .github/workflows/crashlytics.yml
- .github/workflows/database.yml
- .github/workflows/dynamiclinks.yml
- .github/workflows/firebase_app_check.yml
- .github/workflows/firestore.yml
- FirebaseAuth/Tests/Unit/FIRAuthKeychainServicesTests.m
- FirebaseAuth/Tests/Unit/FIRAuthUserDefaultsTests.m
- FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m
- scripts/build.sh
Add Xcode 15.0.1 to CI for abtesting, analytics, appdistribution, auth, core, core_extension, core_internal, crashlytics, database, dynamiclinks, app_check, and firestore.
- Fixed a few warning issues in test code.
- Consolidated pod database unit testing with `pod lib lint` instead of `pod gen`
#no-changelog
> More Xcode 15 CI

- ReleaseTooling/Sources/PodspecsTester/main.swift
Since they aren't part of this repo, pods such as GoogleUtilities, GoogleDataTransport and AppCheckCore don't get pushed to SpecsTesting. We use SpecsStaging as a staging area for those.
#no-changelog
> [Release Tooling] Add SpecsStaging to `pod spec lint` sources

- .github/workflows/abtesting.yml
- .github/workflows/crashlytics.yml
- .github/workflows/dynamiclinks.yml
- .github/workflows/functions.yml
- .github/workflows/installations.yml
- .github/workflows/messaging.yml
- .github/workflows/performance.yml
- .github/workflows/storage.yml
b/309446328
Tested and passed: https://github.com/firebase/firebase-ios-sdk/actions/runs/6775251502/job/18414128462
> Fix nightly FTL test by downgrading python version 

- FirebaseCore.podspec
`GoogleUtilities/Logger` version `7.12` adds a getter for the logging level.
#no-changelog
> [Release] Require `GoogleUtilities/Logger` `7.12` in FirebaseCore

- FirebaseCore/Extension/FIRLogger.h
- FirebaseCore/Sources/FIRLogger.m
- FirebaseCore/Tests/Unit/FIRLoggerTest.m
- Package.swift
Added a getter for the current logger level. This wraps `GULGetLoggerLevel` added in https://github.com/google/GoogleUtilities/pull/138.
#no-changelog
> [Core] Add `FIRGetLoggerLevel` function

- FirebaseAppCheck/Sources/Core/FIRAppCheck.m
- FirebaseAppCheck/Sources/Core/FIRAppCheckLogger.h
- FirebaseAppCheck/Sources/Core/FIRAppCheckLogger.m
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckLoggerTests.m
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckTests.m
Sets the App Check Core logging level (`GACAppCheckLogger.logLevel`) to the equivalent Firebase logging level when instantiating `FIRAppCheck`.
#no-changelog
> Set `GACAppCheckLogger.logLevel` in Firebase App Check

- cmake/external/GoogleUtilities.cmake
Updated the cmake `GoogleUtilities` dependency to [`7.12.0`](https://github.com/google/GoogleUtilities/releases/tag/7.12.0) since `FirebaseCore` updated to this version in https://github.com/firebase/firebase-ios-sdk/pull/12059.
#no-changelog
> Update cmake dependency for GoogleUtilities to 7.12.0

- .github/workflows/firestore.yml
- cmake/GoogleUtilities.cmake
The default Python in CI changed recently. Fix inspired by #12055
Also update the source and header paths for GoogleUtilities
For some reason, most Firestore jobs are not running in nightlies, but not clear to me why.
> Fix cmake ci

- .github/workflows/database.yml
> Disable RTDB unit tests for now in XC15 CI

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/SignUpNewUserRequest.swift
- FirebaseAuth/Sources/Swift/MultiFactor/Phone/PhoneMultiFactorInfo.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/SignUpNewUserTests.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
Swift implementation of #12009
There are no AuthTests.swift changes because some tests were missed in #11942. I'll follow up with those in a separate PR.
> [auth-swift] Swift implementation of link anon to email password

- FirebaseAuth/Sources/Swift/Utilities/AuthRecaptchaVerifier.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
This is a follow on to #11942 that missed six recaptcha unit tests when adapting #11681 to Swift.
#no-changelog
> [auth-swift] Add six missing recaptcha unit tests

- Package.swift
See https://github.com/google/GoogleUtilities/blob/7.12.1/CHANGELOG.md#7121-swiftpm-only
cc: @paulb777 
#no-changelog
> [SwiftPM] Bump GULs dependency's range minimum to 7.12.1

- FirebaseAuth/Sources/Swift/Auth/AuthComponent.swift
- FirebaseAuth/Sources/Swift/Auth/AuthOperationType.swift
- FirebaseAuth/Sources/Swift/Auth/AuthSerialTaskQueue.swift
- FirebaseAuth/Sources/Swift/Backend/AuthRPCResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/CreateAuthURIResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/DeleteAccountResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/EmailLinkSignInResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/GetAccountInfoResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Enroll/FinalizeMFAEnrollmentRequest.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Enroll/FinalizeMFAEnrollmentResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Unenroll/WithdrawMFAResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/Proto/AuthProto.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/Proto/AuthProtoMFAEnrollment.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/Proto/Phone/AuthProtoFinalizeMFAPhoneRequestInfo.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/Proto/TOTP/AuthProtoFinalizeMFATOTPEnrollmentRequestInfo.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/SecureTokenRequest.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/SetAccountInfoResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/VerifyAssertionResponse.swift
- FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPMultiFactorInfo.swift
- FirebaseAuth/Sources/Swift/SystemService/AuthAPNSToken.swift
- FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift
- FirebaseAuth/Sources/Swift/SystemService/AuthNotificationManager.swift
- FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Sources/Swift/User/UserInfoImpl.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthInternalErrors.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthWebUtils.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthWebView.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthWebViewController.swift
Remove extra `public` specifiers that were used while the source was a mix of languages.
In this PR, I reviewed all files that should not have any `public`s and `@objc` specifications.  There may still be extra specifiers in public classes.
> [auth-swift] Remove extra publics

- .github/workflows/zip.yml
- scripts/zip_quickstart_test.sh
Add Quickstart tests for Xcode 15 zip distribution and investigate #11947.
Everything builds, so no repro of #11947 
The tests are flaky with Xcode 15 so I updated the script to only build.
The main thing we need to test here is building. The tests run in the quickstart repo.
Quickstart tests for RTDB and Firestore are disabled because they build on building a binary of FirebaseUI which needs its resources signed, which the zip builder doesn't support.
> Add Xcode 15 CI for zip qs tests

- FirebaseMessaging/CHANGELOG.md
- FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.h
- FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.m
- FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.h
- FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m
- FirebaseMessaging/Tests/UnitTests/FIRMessagingAPNSInfoTest.m
- FirebaseMessaging/Tests/UnitTests/FIRMessagingAuthKeychainTest.m
- FirebaseMessaging/Tests/UnitTests/FIRMessagingTokenInfoTest.m
Fix #12075 for Messaging.
Passed unit tests before and after updating them. Fixed one of the unit tests that has always been broken.
> Messaging: Adopt NSSecureCoding for internal classes

- .github/workflows/auth.yml
- .github/workflows/crashlytics.yml
- .github/workflows/storage.yml
Disable more macos-13 tests flaking on the iOS simulator. Still running build tests on macos-13 and testing them on macos-12.
#no-changelog
> Reduce nightly flakes

- Gemfile
- Gemfile.lock
CocoaPods 1.14.3 works with the macos system ruby again
#no-changelog
> CocoaPods 1.14.3

- FirebaseAuth/Tests/Unit/ObjCAPITests.m
- FirebaseAuth/Tests/Unit/SwiftAPI.swift
- Add Objective C API build tests
- Few cleanups for Swift API tests of duplicate removal and missing tests
- auth-swift branch version of the PR in #12121 
TODO: enum and typedef testing
> Auth: Add Objective C API build tests

- FirebaseAuth/Sources/Swift/ActionCode/ActionCodeSettings.swift
- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/Auth/AuthSettings.swift
- FirebaseAuth/Sources/Swift/AuthProvider/FederatedAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Sources/Swift/MultiFactor/Phone/PhoneMultiFactorAssertion.swift
- FirebaseAuth/Sources/Swift/MultiFactor/Phone/PhoneMultiFactorGenerator.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- FirebaseAuth/Tests/Unit/ObjCAPITests.m
- FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/SwiftAPI.swift
- Package.swift
- auth-swift branch version of #12117 
- Add Objective C API build tests and make discovered fixes
I didn't port the setAPNSToken API since it seems to be a mistake and no-op in the Objective C implementation
> [auth-swift] Add Objective C API build tests

- ReleaseTooling/Package.swift
- ReleaseTooling/Sources/PrivacyKit/PrivacyManifest.swift
- ReleaseTooling/Sources/PrivacyManifestGenerator/PrivacyManifestWizard.swift
- ReleaseTooling/Sources/PrivacyManifestGenerator/main.swift
- Add initial code for a tool that generates xcprivacy files 
- The idea is for the CLI to be like a "wizard" that walks you through a series of questions and generates a manifest with your answers.
- The tool requires a path to an xcframework. This will be the xcframework that the generated Privacy Manifest will be for.
- Locally, I'm a ways ahead, but will be opening smaller PRs that should be easy to review.
Structure:
- `privacy-manifest-generator` (executable target)
- depends on `PrivacyKit` (source target) which will model the data types described in https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
- The `PrivacyKit.PrivacyManifest` type will be encodable into a plist which will populate the .xcprivacy file.
#no-changelog
> [Release Tooling] Initial xcprivacy file generation tooling

- FirebaseMessaging.podspec
- FirebaseMessaging/Sources/FIRMessagingConstants.h
- FirebaseMessaging/Sources/FIRMessagingConstants.m
- FirebaseMessaging/Sources/FIRMessagingExtensionHelper.m
- Package.swift
This is expected to fix b/309154411.
> Add product_id to GoogleDataTransport logging for compliance.

- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppAttestProvider.h
- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckDebugProvider.h
- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRDeviceCheckProvider.h
See cl/585793441 for docsgen (googlers only). Addresses the lack of doc in this comment: https://github.com/firebase/firebase-ios-sdk/issues/11284#issuecomment-1828405118
#no-changelog
> redeclare protocol method so it can be added to docs

- FirebaseAuth/Sources/Backend/RPC/FIRSetAccountInfoRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRSetAccountInfoRequest.m
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRUser.h
- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Tests/Unit/FIRSetAccountInfoRequestTests.m
- FirebaseAuth/Tests/Unit/FIRUserTests.m
Added FIRUser level unenrollPasskeyWithCredentialID:completion: API.
This has been tested with backend staging endpoint.
> [Passkey #9] Passkey withdraw

- ReleaseTooling/Sources/Utils/ShellUtils.swift
This is a minor problem. I don't have a .bash_profile, so whenever I run the release tooling, any script it invokes prints a warning that the  `.bash_profile` it tries to source does not exist.
I could add an empty bash profile to my machine, but generalizing the script may be better.
> [Release Tooling] Fix .bash_profile warning for when no .bash_profile exists

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
Updated the Carthage artifacts for the 10.19.0 release. Verified with `carthage update`.
<details>
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseABTestingBinary.json" "10.19.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAdMobBinary.json" "10.19.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "10.19.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppCheckBinary.json" "10.19.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppDistributionBinary.json" "10.19.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" "10.19.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json" …
```
> [Release] Carthage updates for 10.19.0

- ClientApp/Podfile
- CocoapodsIntegrationTest/TestEnvironments/Cocoapods_multiprojects_frameworks/Podfile
- CoreOnly/Tests/FirebasePodTest/Podfile
- Example/watchOSSample/Podfile
- FirebaseRemoteConfig.podspec
- FirebaseRemoteConfig/Interop/RemoteConfigInterop.swift
- FirebaseRemoteConfig/Interop/RolloutAssignment.swift
- FirebaseRemoteConfig/Interop/RolloutsStateSubscriber.swift
- FirebaseRemoteConfig/Sources/FIRRemoteConfigComponent.h
- FirebaseRemoteConfig/Sources/FIRRemoteConfigComponent.m
- FirebaseRemoteConfig/Tests/Sample/Podfile
- FirebaseRemoteConfig/Tests/SwiftUnit/RemoteConfigInteropTests.swift
- FirebaseRemoteConfig/Tests/Unit/FIRRemoteConfigComponentTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
- FirebaseRemoteConfigInterop.podspec
- Package.swift
- scripts/localize_podfile.swift
RC interop Implementation
- This change is for interop and RCComponent.
- Interop and its unit tests are written in Swift under `FirebaseRemoteConfig/Interop` and `FirebaseRemoteConfig/Tests/SwiftUnit`
- Updated dependency for SPM and CocoaPod for the new Interop.
#no-changelog
> [Rollouts] RC interop implementation

- .github/workflows/firestore.yml
- Firestore/core/src/util/schedule.cc
- cmake/sanitizer_options.cmake
> Activate asan on ubuntu

- SwiftPackageManager.md
Apps created with Xcode 15 have `User Script Sandboxing = YES` set by default which requires all referenced files to be specified in the run script inputs. The official docs don't state this yet: https://firebase.google.com/docs/crashlytics/get-started?platform=ios#set-up-dsym-uploading
Fix from @samedson is here: https://github.com/firebase/firebase-ios-sdk/pull/11463#issue-1767693978
I think if would make sense to add this to the in-repo docs to save people some time searching.
> [Docs] Xcode 15 and User Script Sandboxing

- Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c
From support feedback, many support issues for initial crash is because they attached the debugger. Explicitly log that information on SDK side.
https://screenshot.googleplex.com/3AiRj3BqShHhRQA
#no-changelog
> Adding log for user who have debugger attached

- Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
In `FIRServerTimestampTests.mm` there is a check to verify that the server timestamp values generated by the backend are within 10 seconds of the time on the local device. This, however, appears to be too aggressive, even for production. Therefore, increase the tolerance to 200 seconds.
#no-changelog
> Firestore: Increase clock skew tolerance in FIRServerTimestampTests.mm

- Firestore/Example/Tests/Integration/API/FIRAggregateTests.mm
- Firestore/Example/Tests/Integration/API/FIRCountTests.mm
- SwiftPackageManager.md
This verifies that the descriptive error message that occurs when the server does not have the required index has the URL that customers can follow to create the index.
This is a port of the "getCountFromServer error message is good if missing index" integration test from https://github.com/firebase/firebase-js-sdk/blob/42bfb0b8243a6c36b66a0bbedf61436e70591062/packages/firestore/test/integration/api/aggregation.test.ts#L130-L155 and https://github.com/firebase/firebase-android-sdk/pull/4232.
Googlers see b/254063570 for details.
#no-changelog
> Firestore: Add test that verifies aggregate query error message when missing index

- Carthage.md
- FirebaseAppDistributionInternal/README.md
- Firestore/core/test/unit/FSTGoogleTestTests.mm
- Gemfile
- README.md
- docs/ContinuousIntegration.md
I have created a `main` branch from the tip of `master`. I added one commit (7035247e8dfbd9ea88305c136c24a268998778b6) to `main` already that features many reference changes. To test it out, I'm opening this PR into `main` which includes some additional reference changes.
#no-changelog
> [Infra] Test new `main` branch

- SwiftPackageManager.md
Did a grep on `main` and found one reference that refers to Firebase's `master` branch. All other references to `master` involve other repos.
#no-changelog
> [Infra] Fix unchanged reference to 'master' branch

- Crashlytics/Crashlytics/FIRCrashlytics.m
- Crashlytics/Crashlytics/Rollouts/CrashlyticsRemoteConfigManager.swift
- Crashlytics/UnitTestsSwift/CrashlyticsRemoteConfigManagerTests.swift
- FirebaseCrashlytics.podspec
- Package.swift
- Adding interop dependency to Crashlytics SDK
- Validate the rollouts data on Crash side(maxNumOfAssignments, maxLengthOfParamValue)
- Adding support for Crashlytics writing swift code
- Unit tests
#no-changelog
> [Rollouts] Crashlytics Rollouts interop Integration

- Gemfile
- ReleaseTooling/Sources/Utils/ShellUtils.swift
See comment here (https://github.com/firebase/firebase-ios-sdk/pull/12158#discussion_r1410917059).
Going to let a global CI run finish and will re-evaluate then if this PR is worth it.
> [Release Tooling] Stop sourcing .bash_profile when running generated shell scripts

- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/AuthMFAResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/EmailLinkSignInResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/VerifyAssertionResponse.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/VerifyPasswordResponse.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Sources/Swift/User/UserProfileChangeRequest.swift
Fix four issues integration testing Multi-Factor Authentication thanks to the test case from #11079 
- Build issue from using `withCompletion:` instead of  `completion:` in some APIs
- Created an `AuthMFAResponse` protocol for responses that need AuthBackend's checking of MFA error throwing
- Fixed the type of `MultiFactorInfo` hint arrays. They should be `PhoneMultiFactorInfo` and `TOTPMultiFactorInfo` instead of the common base type.
- Fixed a logic error in PhoneAuthProvider.swift: `idToken` can be non-nil for both the `recaptcha` and `credential` cases.
> MFA Integration Testing fixes

- FirebaseAuth/Tests/Unit/ObjCGlobalTests.m
- FirebaseAuth/Tests/Unit/SwiftGlobalTests.swift
- Package.swift
Global list generated from grepping for `extern` in public header files.
The new tests are also included in the corresponding [auth-swift] PR #12228 
The health-metrics CI failure is not reproducible. I suspect it will go away after main merge and tag update.
> Add build tests for Auth globals

- FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
- FirebaseAuth/Tests/Sample/SwiftApiTests/AccountInfoTests.swift
- FirebaseAuth/Tests/Sample/SwiftApiTests/AnonymousTests.swift
- FirebaseAuth/Tests/Sample/SwiftApiTests/EmailPasswordTests.swift
- FirebaseAuth/Tests/Sample/SwiftApiTests/FacebookTests.swift
- FirebaseAuth/Tests/Sample/SwiftApiTests/GoogleTests.swift
- FirebaseAuth/Tests/Sample/SwiftApiTests/TestsBase.swift
- FirebaseCore/Tests/SwiftUnit/CoreAPITests.swift
- FirebaseDatabase/Tests/Unit/Swift/DatabaseAPITests.swift
- FirebaseFunctions/Sources/Callable+Codable.swift
- FirebaseFunctions/Sources/HTTPSCallable.swift
- FirebaseFunctions/Tests/Integration/IntegrationTests.swift
- FirebaseFunctions/Tests/Unit/FunctionsAPITests.swift
- FirebaseInstallations/Source/Tests/Unit/Swift/InstallationsAPITests.swift
- FirebaseMessaging/Tests/UnitTestsSwift/FIRMessagingAPITest.swift
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/AsyncAwaitTests.swift
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/Codable.swift
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/PropertyWrapperDefaultConfigsTests.swift
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/PropertyWrapperTests.swift
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/Value.swift
- FirebaseStorage/Sources/AsyncAwait.swift
- FirebaseStorage/Sources/StorageReference.swift
- FirebaseStorage/Tests/Integration/StorageAsyncAwait.swift
- Firestore/Swift/Source/AsyncAwait/CollectionReference+AsyncAwait.swift
- Firestore/Swift/Source/AsyncAwait/Firestore+AsyncAwait.swift
- Firestore/Swift/Source/Codable/DocumentReference+ReadDecodable.swift
Remove unnecessary checks for Swift compiler Concurrency support.
Concurrency is always available in the currently supported minimum Xcode 14.1 and above.
> Remove unnecessary compiler checks for Concurrency support

- IntegrationTesting/ClientApp/ClientApp.xcodeproj/project.pbxproj
- IntegrationTesting/ClientApp/Shared-iOS12+/swift-import-test.swift
- IntegrationTesting/ClientApp/Shared-iOS13+/swift-import-test.swift
The Xcode project file changes come from configuration done to the settings highlighted in green.
> [auth-swift] Add 'FirebaseAuth*' to iOS 13+ scheme using SPM

- FirebaseStorage/Tests/Integration/StorageAsyncAwait.swift
- FirebaseStorage/Tests/Integration/StorageIntegration.swift
Use unique names to try to address recent storage integration test flakiness
Also move task.cancel after task.observe to address another possible flake
> Storage Integration Test flakiness

- Crashlytics/Crashlytics/FIRCrashlytics.m
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/FeatureRolloutsTestApp.xcodeproj/project.pbxproj
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/FeatureRolloutsTestApp/ContentView.swift
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/FeatureRolloutsTestApp/FeatureRolloutsTestApp.entitlements
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/FeatureRolloutsTestApp_CrashlyticsRemoteConfig_iOS/ContentView.swift
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/FeatureRolloutsTestApp_Crashlytics_iOS/ContentView.swift
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/FeatureRolloutsTestApp_RemoteConfig_iOS/ContentView.swift
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/Podfile
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/Shared/CrashButtonView.swift
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/Shared/FeatureRolloutsTestAppApp.swift
- FirebaseRemoteConfig/generate_featureRolloutsTestApp.sh
Adding integration test app
Right now added 4 targets:
- Neither Crash nor RC integration
- Either one of Crash or RC integration
- Both Crash and RC integration
To run the test app:
- gcert your local machine
- run `./generate_featureRolloutsTestsApp.sh`
Console app: https://firebase-console-ci.corp.google.com/u/0/project/feature-rollouts-test-app/settings/general/ios:com.firebase.config.featureRolloutsTestApp
#no-changelog
> [Rollouts] Add integration test app

- FirebaseCore/CHANGELOG.md
- ReleaseTooling/Sources/ZipBuilder/CarthageUtils.swift
- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
Static xcframeworks containing privacy manifests should be embedded in Xcode 15. The `Info.plist`s that have been historically included in our static xcframeworks should therefore be removed.
Note, only the `Info.plist`s within the _platform_ frameworks (`.framework`) need to be removed. The root level `Info.plist` in the xcframework (`.xcframework`) does not seem to cause issues.
---
Locally built a `FirebaseSharedSwift.xcframework` with and without these changes:
```
diff --color <(tree FrameworkWithPlist) <(tree FrameworkWithoutPlist)
1c1
< FrameworkWithoutPlist
---
> FrameworkWithPlist
9a10
>     │       ├── Info.plist
24a26
>     │       ├── Info.plist
44a47
>     │       ├── Info.plist
64a68
>     │       ├── Info.plist
84a89
>     │       ├── Info.plist
99a105
>             ├── …
```
> [Release Tooling] Stop including 'Info.plist's in static xcframeworks

- FirebaseMessaging/CHANGELOG.md
- FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.h
- FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m
- FirebaseMessaging/Sources/Token/FIRMessagingTokenStore.m
Fix #12245. 
If decoding of the FIRMessagingTokenInfo fails, fallback to the pre-10.19.0 code and migrate the keychain to the NSSecure encode.
Summary from @ncooke3:
1. developer onboards to 10.20.0+ → secure tokens are always read and written
2. developer updates to 10.20.0+ from 10.18.0 or below → initial read of an unsecure token, write back a secured token, and always read secure tokens afterwards
3. developer updates to 10.20.0+ from 10.19.0 → two subcases:
a. the unsecure token was overwritten by the secure token & always read later as a secure token
b. the unsecure token was NOT overwritten yet and the fallback decode code path kicks into effect
> Decode old fcmToken format

- FirebaseAuth/Sources/MultiFactor/TOTP/FIRTOTPSecret.m
- FirebaseAuth/Sources/Utilities/FIRAuthRecaptchaVerifier.m
[Closes #11887]
* Replaced `NSLog` calls in `FIRTOTPSecret.m` and `FIRAuthRecaptchaVerifier.m` with `FIRLogger` invocations
* This commit introduces message codes `I-AUT000023`, `I-AUT000024`, `I-AUT000025`, `I-AUT000026`, `I-AUT000027`, `I-AUT000028`, `I-AUT000029`, `I-AUT000030`, and `I-AUT000031`
> [#11887] Removed `NSLog` Calls from FirebaseAuth

- FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift
- FirebaseCore/Tests/SwiftUnit/CoreAPITests.swift
- FirebaseDatabase/Tests/Unit/Swift/DatabaseAPITests.swift
- FirebaseFunctions/Tests/Unit/FunctionsAPITests.swift
- FirebaseInstallations/Source/Tests/Unit/Swift/InstallationsAPITests.swift
- Updated comments to say async/await is available on iOS 13+ (from 15+ and macOS 10.15+) since it was backported in Xcode 13.2+ / Swift 5.5.2+
- Removed mention of Swift 5.5+ in the comments since we only support 5.6+
- Fixed macOS 11.15 typos (version doesn't exist -- assumed 10.15 since that's the minimum for async/await)
#no-changelog
> Update async/await availability comments to "iOS 13+"

- Firestore/Source/Public/FirebaseFirestore/FIRAggregateSource.h
- Firestore/Source/Public/FirebaseFirestore/FIRQuery.h
Apply the feedback to the count and aggregation API documentation as suggested in https://github.com/firebase/firebase-js-sdk/pull/6608. This is a port of https://github.com/firebase/firebase-js-sdk/pull/7933.
#no-changelog
> Firestore: Small Count API documentation improvements

- Crashlytics/Crashlytics/Rollouts/CrashlyticsRemoteConfigManager.swift
- Crashlytics/Crashlytics/Rollouts/EncodedRolloutAssignment.swift
- Crashlytics/Crashlytics/Rollouts/StringToHexConverter.swift
- Crashlytics/UnitTests/FIRCLSFileTests.m
- Crashlytics/UnitTestsSwift/CrashlyticsRemoteConfigManagerTests.swift
- FirebaseRemoteConfig/Interop/RolloutAssignment.swift
- Adding a intermediate data object `EncodedRolloutAssignment` to process string value hex encoding and serialization
- Re-write [`FIRCLSFileHexEncodeString`](https://github.com/firebase/firebase-ios-sdk/blob/a8d753baf0f76ead89dc3fd3138431a162722d5b/Crashlytics/Crashlytics/Helpers/FIRCLSFile.m#L660) logic to swift
- Unit testing
Checked rollouts are successfully attached to non-fatals after integration:
#no-changelog
> [Rollouts] Rollouts serialization

- Crashlytics/Crashlytics/Handlers/FIRCLSHandler.m
- FirebaseDatabase/CHANGELOG.md
- FirebasePerformance/Tests/Unit/FPRNetworkTraceTest.m
> [NFC] Fix typos `occured` → `occurred`

- FirebaseAuth/Sources/Swift/Auth/AuthDataResult.swift
- FirebaseAuth/Sources/Swift/Auth/AuthTokenResult.swift
- FirebaseAuth/Sources/Swift/AuthProvider/EmailAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/FacebookAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/GameCenterAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/GitHubAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/GoogleAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/OAuthCredential.swift
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthCredential.swift
- FirebaseAuth/Sources/Swift/AuthProvider/TwitterAuthProvider.swift
- FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift
- FirebaseAuth/Sources/Swift/MultiFactor/MultiFactorInfo.swift
- FirebaseAuth/Sources/Swift/MultiFactor/Phone/PhoneMultiFactorInfo.swift
- FirebaseAuth/Sources/Swift/SystemService/AuthAppCredential.swift
- FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift
- FirebaseAuth/Sources/Swift/User/AdditionalUserInfo.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Sources/Swift/User/UserInfo.swift
- FirebaseAuth/Sources/Swift/User/UserInfoImpl.swift
- FirebaseAuth/Sources/Swift/User/UserMetadata.swift
- FirebaseAuth/Tests/Unit/SwiftAPI.swift
After discoveries about NSSecureCoding and decoding from the keychain, this PR rolls out the learnings across all the relevant classes in Auth and addresses a few other issues:
- In the ObjC implementation, NSSecureCoding is only `public` for OAuthCredential and PhoneAuthCredential, therefore move NSSecureCoding on all other `open` classes to an extension
- Move key declarations into `MARK: Secure Coding` sections
- Use `of` parameter to specify allowed types on all `decodeObject` calls.
- Implement NSSecureCoding commented code from AuthTokenResult.swift. 
- Even thought the UserInfo.uid was not nullable in the ObjC implementation, after linking email auth to phone number auth in the quickstart, it will be nil and crash at the now updated fatalError in …
> [auth-swift] Consistent NSSecureCoding decode

- Firestore/CHANGELOG.md
- Package.swift
- SwiftPM-PlatformExclude/FirebaseFirestoreWrap/dummy.m
- SwiftPM-PlatformExclude/FirebaseFirestoreWrap/include/dummy.h
The proposed consists of two parts:
1. Change the Package.swift to only build Firestore's binary targets on platforms that support the binary distribution (e.g. !visionOS)
- This shifts the problem from the package loading phase to the compilation phase.
2. Add a warning in the source wrapper target to issue a warning only on visionOS and only when it is detected that the client is using the binary distro*.
- *: We can determine this by configuring the wrapper target in the binary distro code path to define a preprocessor directive.
> [Firestore] Add warning when building Firestore's binary SPM distro for visionOS

- Firestore/CHANGELOG.md
Follow-up work to #12279 after the decision to switch the warning to an error.
#no-changelog
> [Firestore] Update CHANGELOG.md

- README.md
#no-changelog
See also internal cl/599193113 for updates to the platform support table matrix
> Update README.md for visionOS

- FirebasePerformance/README.md
- FirebasePerformance/generate_project.sh
- Firestore/Example/FuzzTests/FuzzingResources/Serializer/Corpus/ConvertTextToBinary.sh
- Firestore/core/CMakeLists.txt
- Firestore/core/src/nanopb/pretty_printing.cc
- Firestore/core/test/unit/FSTGoogleTestTests.mm
```
git grep --name-only XCode | xargs sed -i '' "s/XCode/Xcode/g"
```
#no-changelog
> [NFC] Fix typos: XCode -> Xcode

- FirebaseRemoteConfig/Sources/RCNConfigContent.m
- FirebaseRemoteConfig/Sources/RCNConfigDBManager.h
- FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
- FirebaseRemoteConfig/Sources/RCNConfigDefines.h
- FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m
- Package.swift
Add insertOrUpdate method to persist rollout metadata in sqlite db
Add load method to load rollout metadata from sqlite db
#no-changelog
> [Rollouts] Implement insert and load logic for rollout metadata in RC

- Firestore/core/src/util/string_format.h
Remove unnecessary brace initialization in call to AlphaNum. This does not change any functionality, but merely improves the code quality to use AlphaNum in the intended manner.
Brace-initialized calls to AlphaNum are unsupported, and are misused as function parameters, which cause problems when attempts are made to modify the implementations of functions such as StrCat. While this particular usage (inside a base-class constructor call) itself isn't problematic, it does blocking brace initialization in the future in Google's internal source code repository, hence this change. Googlers see cl/598865604 for details.
#no-changelog
> Firestore: Remove unnecessary brace initialization in call to AlphaNum

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/Auth/AuthComponent.swift
This fixes the following console log warning:
10.20.0 - [FirebaseCore][I-COR000030] An instance conforming to FIRAuthProvider was requested, but the instance provided does not conform to the protocol
> [auth-swift] Fix Component warning

- IntegrationTesting/ClientApp/Podfile
The Client App Podfile was missing local paths for CoreInternal and CoreExtension. This can cause build failures when those change locally like https://github.com/firebase/firebase-ios-sdk/actions/runs/7595950042/job/20689094685
> Fix Client App build issue

- Crashlytics/Crashlytics/Components/FIRCLSUserLogging.h
- Crashlytics/Crashlytics/Components/FIRCLSUserLogging.m
- Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.h
- Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.m
- Crashlytics/Crashlytics/FIRCrashlytics.m
- Crashlytics/Crashlytics/Handlers/FIRCLSException.h
- Crashlytics/Crashlytics/Handlers/FIRCLSException.mm
- Crashlytics/Crashlytics/Models/FIRCLSInternalReport.h
- Crashlytics/Crashlytics/Models/FIRCLSInternalReport.m
- Crashlytics/Crashlytics/Rollouts/CrashlyticsRemoteConfigManager.swift
- Crashlytics/Crashlytics/Rollouts/EncodedRolloutAssignment.swift
- Crashlytics/UnitTests/FIRCLSLoggingTests.m
- Crashlytics/UnitTests/FIRCLSRolloutsPersistenceManagerTests.m
- Crashlytics/UnitTests/FIRRecordExceptionModelTests.m
- Crashlytics/UnitTestsSwift/CrashlyticsRemoteConfigManagerTests.swift
Base on this summary of events crashlytics record:
|  Events |  API |  Persistence File(s) |  Will Crash?  | 
|---|---|---|---|
| non-fatal  | recordError()  | error_a/b |  No  |  
| native-fatal  |  N/A | exception, signal, mach_exception  |  YES | 
|  custom exception |  recordExceptionModel() |  custom_exception_a/b |  No | 
| on-demand fatal |  recordOnDemandExceptionModel() | exception(if we consider it's fatal), custom_exception_a/b(if we consider it's non-fatal) |  No |
Here is how we read rollouts info:
|  File | SDK log for rollouts |  Backend Process | 
|---|---|---|
| error_a/b (.clsrecord) | each error entry will attach the rollouts state with the entry  | read rollouts from each entry | 
| exception, signal, mach_exception (.clsrecord)|  write rollouts separately - …
> [Rollouts]Writing Rollouts to persistence

- Firestore/core/src/util/filesystem_apple.mm
- Firestore/core/src/util/filesystem_posix.cc
This is a follow-up to https://github.com/firebase/firebase-ios-sdk/pull/12264.
#no-changelog
> Firestore: Another use foundation API instead of C API

- FirebaseMessaging/Sources/FIRMessagingSyncMessageManager.m
- FirebaseMessaging/Sources/FIRMessagingUtilities.h
- FirebaseMessaging/Sources/FIRMessagingUtilities.m
Before storing a new message to the message database, we check whether there is enough free disk space. If there is no enough disk space, nothing will be stored. 
This check is not necessary. Because when there is no enough disk space, sqlite will return SQLITE_FULL and abort the transaction.
#no-changelog
> Delete unnecessary file system API usages.

- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
Xcode 14 friendly version of #12114. 
The first commit was something I had stashed a few weeks back. Revisiting it now, I simplified it with the file enumerator approach.
```console
FirebaseInAppMessaging.xcframework
├── Info.plist
├── Resources ← 🎯 Non-privacy manifest bundles are NOT embedded for Xcode 14 users.
│   └── InAppMessagingDisplayResources.bundle
│       ├── FIRInAppMessageDisplayStoryboard.storyboard
│       │   ├── Info.plist
│       │   ├── banner-view-vc.nib
│       │   ├── card-view-vc.nib
│       │   ├── image-only-vc.nib
│       │   ├── lGH-bl-7Xw-view-ef6-R8-q1S.nib
│       │   ├── lbb-HM-tHJ-view-vRb-yf-OWE.nib
│       │   ├── modal-view-vc.nib
│       │   ├── oTF-1C-LZP-view-SM1-hn-m3n.nib
│       │   └── x01-lq-3r6-view-1pz-BP-O6T.nib
│       ├── Info.plist
│   …
```
> [Release Tooling] Only embed bundles containing privacy manifests

- FirebaseFunctions/Sources/Callable+Codable.swift
- FirebaseFunctions/Sources/Functions.swift
- FirebaseFunctions/Sources/FunctionsError.swift
- FirebaseFunctions/Sources/HTTPSCallable.swift
Make several fixes after reviewing the output of a docs build of FirebaseFunctions scheme in the SPM project
> Doc fixes for Functions

- FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
- FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
- FirebaseRemoteConfig/Sources/RCNConfigConstants.h
- FirebaseRemoteConfig/Sources/RCNConfigContent.h
- FirebaseRemoteConfig/Sources/RCNConfigContent.m
- FirebaseRemoteConfig/Sources/RCNConfigFetch.m
- FirebaseRemoteConfig/Sources/RCNConfigSettings.m
- FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.h
- FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNUserDefaultsManagerTests.m
Set active rollout metadata after activate config.
Add last active template version to userDefault.
Looks like the previous PR is getting bigger, split this part into a PR for better review. Notifying interop logic will be in a following PR.
#no-changelog
> [Rollouts] Set active rollout metadata after activating config

- .github/workflows/storage.yml
This validates a proof of concept of using GHA retry (#11253) instead of travis retry. 
It doesn't address the Storage Integration flake, but it successfully retries it.
#no-changelog
> Try GHA retry

- .github/workflows/health-metrics-presubmit.yml
- scripts/health_metrics/README.md
Downversion to actions/upload-artifact@v3
The new upload-artifact version from #12337 broke the health metrics presubmit job - https://github.com/firebase/firebase-ios-sdk/actions/runs/7748205614/job/21130380583
```
With the provided path, there will be 41 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
The failures are related to https://github.com/actions/upload-artifact/issues/478. We need a resolution before going to actions/upload-artifact@v4
> Fix health-metrics

- FirebaseRemoteConfig/Sources/RCNConfigConstants.h
- FirebaseRemoteConfig/Sources/RCNConfigContent.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
Diff rollout metadata for updatedKeys in RemoteConfigUpdater
Before diffing, convert rollout metadata NSArray into a NSDictionary with the parameter key string as key and  a Dictionary (rollout id as key and variant id as value) as value.
#no-changelog
> [Rollouts] Diff rollout metadata for updatedKeys in RemoteConfigUpdater

- FirebaseCore/CHANGELOG.md
- Package.swift
- Increased to `swift-tools-version:5.7.1` in `Package.swift`
- This aligns with the minimum version of Xcode supported by the SDK (14.1)
> Increase `swift-tools-version` to `5.7.1`

- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/FeatureRolloutsTestApp.xcodeproj/project.pbxproj
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/FeatureRolloutsTestApp_CrashlyticsRemoteConfig_iOS/ContentView.swift
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/FeatureRolloutsTestApp_RemoteConfig_iOS/ContentView.swift
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/Shared/RemoteConfigButtonView.swift
Add RC fetch and activate logic into test App
-Within RC only schema
-Within RC+Crashlytics schema
Text value is "unfetched" while first launch and change after fetch + activate with targeted value.
#no-changelog
> [Rollouts]Add remote config logic to featureRollouts test app

- .github/workflows/auth.yml
The auth Objective C integration tests stopped building when the default Xcode became 14.3 yesterday. See https://github.com/firebase/firebase-ios-sdk/actions/runs/7797150970/job/21271664663
Since we don't need to support Xcode 14.3 for too much longer, moving these tests to Xcode 15.
Fix #12360
> Fix auth integration test build issue

- .github/workflows/abtesting.yml
- .github/workflows/auth.yml
- .github/workflows/crashlytics.yml
#no-changelog
See if this reduces nightly flakiness
> Migrate a few more retry steps

- FirebaseAppCheck/Sources/Core/FIRAppCheck.m
The private `kDummyFACTokenValue` constant is no longer used in Firebase App Check. The replacement constant now lives in App Check Core: https://github.com/google/app-check/blob/3e464dad87dad2d29bb29a97836789bf0f8f67d2/AppCheckCore/Sources/Core/GACAppCheckTokenResult.m#L21-L23
#no-changelog
> Remove placeholder token constant from Firebase App Check

- Firestore/Source/Public/FirebaseFirestore/FIRTimestamp.h
- Firestore/core/include/firebase/firestore/timestamp.h
- Firestore/core/test/unit/FSTGoogleTestTests.mm
- scripts/update_xcode_target.rb
Updated links to other repositories that have been changed to `main` branches.
#no-changelogs
> Update links to `main` branches

- CoreOnly/Sources/Firebase.h
Fixes 
and the Interop import fixes the next failure:
> [auth-swift] Include Swift-generated ObjC Auth types via Firebase.h

- Firestore/CHANGELOG.md
- Firestore/core/src/model/value_util.cc
- Firestore/core/src/model/value_util.h
- Firestore/core/test/unit/model/value_util_test.cc
When user calls `arrayRemove` on map object, since the key order in mutation is not necessary align with the order in document and the SDK falsely assume for hash map the item is always sorted by keys, sometimes `arrayRemove` doesn't work.
> Bug fix for flaky behaviour when using Map in arrayRemove

- FirebaseStorage/Sources/Storage.swift
The `AuthInterop` and `AppCheckInterop` instances returned by `ComponentType<ProtocolName>.instance(for: ProtocolName.self, in: app.container)` are nullable (e.g., if AppCheck or Auth aren't added to an app). This hasn't broken the Storage SDK because the instances are only used in [`StorageTokenAuthorizer`](https://github.com/firebase/firebase-ios-sdk/blob/2c76938316df35db9f8f5aa69bfeacfac40a8a07/FirebaseStorage/Sources/Internal/StorageTokenAuthorizer.swift#L117-L118), where they're nullable parameters.
#no-changelog
> Make `AuthInterop` and `AppCheckInterop` properties optional in Storage

- FirebaseCore/CHANGELOG.md
- ReleaseTooling/Sources/ZipBuilder/CarthageUtils.swift
- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
This reverts commit 0fa8498f4b97e2ac1e550100e1996e13888d03fc.
Fix #12390
> Revert "[Release Tooling] Stop including 'Info.plist's in static xcframeworks (#12243)"

- FirebaseInAppMessaging/CHANGELOG.md
- FirebaseInAppMessaging/Sources/Flows/FIRIAMMessageClientCache.m
> [FIAM] Fix an objc_retain crash

- .github/workflows/storage.yml
Disable ObjC quickstart on Xcode 15.2
GHA is flaking because with a redefinition of module 'SwiftBridging' error. See  https://github.com/firebase/firebase-ios-sdk/actions/runs/7908402675/job/21587502678
from a GHA configuration issue though:
https://forums.developer.apple.com/forums/thread/739510
> Disable flaky Storage ObjC quickstart on Xcode 15.2

- FirebaseCore/Extension/FIRComponentType.h
- FirebaseCore/Sources/FIRComponentType.m
- FirebaseStorage/Sources/Storage.swift
- FirebaseStorage/Tests/Unit/StorageComponentTests.swift
- Gemfile
Updated [`+ (T)instanceForProtocol:inContainer:`](https://github.com/firebase/firebase-ios-sdk/blob/2c76938316df35db9f8f5aa69bfeacfac40a8a07/FirebaseCore/Extension/FIRComponentType.h#L30) in `FIRComponentType` to return a `nullable T` instead of `T`. The [underlying call](https://github.com/firebase/firebase-ios-sdk/blob/ab0d0854a3682f14c0ee26859469cb4b1636d5e1/FirebaseCore/Sources/FIRComponentType.m#L25) to [`instanceForProtocol:`](https://github.com/firebase/firebase-ios-sdk/blob/ab0d0854a3682f14c0ee26859469cb4b1636d5e1/FirebaseCore/Sources/FIRComponentContainer.m#L189-L203) in `FIRComponentContainer` can return `nil`.
This is a follow-up that addresses https://github.com/firebase/firebase-ios-sdk/pull/12387#issuecomment-1942408448.
#no-changelog
> Make `instanceForProtocol:inContainer:` return `nullable T`

- ReleaseTooling/Sources/ZipBuilder/CarthageUtils.swift
Some internal testing showed errors for CFBundleShortVersionString and MinimumOSVersion missing from the Info.plist. This PR adds them.
Currently the implementation is iOS specific.
This PR is mostly moot after #12414, but is still relevant for the one case where generateInfoPlist is still used and if we ever need it in the future.
> [Binary] Add missing values to Info.plist generator

- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
Use Xcode built Info.plist's instead of self-generated ones when building binary distributions.
This will produce a more accurate Info.plist and be less likely to cause problems with App Store or other validation.
`CarthageUtils.generatePlistContents` is now used only for the placeholder Firebase framework.
The test results match current `main` (Outstanding bug with Resource directory structure)
More context for Googlers at b/318008447
#no-changelog
> [binary] Use Xcode built Info.plist's

- Firestore/Swift/Source/Codable/DocumentReference+ReadDecodable.swift
Hey there, noticed that I can't specify source on the decodable extensions on `DocumentReference`.
I understand that you're not accepting changes that affect the public API (quoted below), but this is a non-breaking change that brings parity across the API and I wanted to get your thoughts. 
> At this time we cannot accept changes that affect the public API.  If you'd like to help 
> us make Firebase APIs better, please propose your change in a feature request so that we
> can discuss it together.
> Add FirebaseSource to ReadDecodable extensions of DocumentReference

- .github/workflows/zip.yml
- FirebaseAnalytics.podspec
- FirebaseCrashlytics.podspec
- FirebaseFirestoreInternal.podspec
- FirebaseInAppMessaging.podspec
- FirebaseMessaging.podspec
- FirebasePerformance.podspec
- FirebaseSessions.podspec
- GoogleAppMeasurement.podspec
- Package.swift
nanopb 0.3.9.10 or 2.30910.0 introduces a privacy manifest for nanopb
Confirmed the Privacy manifest is being built into the zip after updating SpecsStaging
CI failures match main and are related to a zip builder issue with GoogleUtilities
> Enable nanopb version with privacy manifest

- ReleaseTooling/Sources/Utils/FileManager+Utils.swift
- ReleaseTooling/Sources/ZipBuilder/ResourcesManager.swift
Fix #12385
This PR fixes the Resource organization issue in GoogleUtilities in the zip that's been causing the nightly zip build failures for the last week.
The issue isn't reproducible in Xcode 15 on macos 13. I suspect the root cause may have to do with file system repercussions of building GoogleUtilities a second time separately for Carthage.
I'll do a bit more investigation, but this should be ready for review, so we can unblock progress on #12407
Getting:
Should be:
> Fix GoogleUtilities zip file structure

- FirebaseSessions/Tests/TestApp/Shared/MockSubscriberSDK.swift
unwrap optional due to this change: https://github.com/firebase/firebase-ios-sdk/pull/new/fixSessionTests
#no-changelog
> add optional

- .github/workflows/zip.yml
- Crashlytics/Resources/PrivacyInfo.xcprivacy
- FirebaseABTesting.podspec
- FirebaseABTesting/Sources/Resources/PrivacyInfo.xcprivacy
- FirebaseAuth.podspec
- FirebaseAuth/Sources/Resources/PrivacyInfo.xcprivacy
- FirebaseCore.podspec
- FirebaseCore/Extension/Resources/PrivacyInfo.xcprivacy
- FirebaseCore/Internal/Sources/Resources/PrivacyInfo.xcprivacy
- FirebaseCore/Sources/Resources/PrivacyInfo.xcprivacy
- FirebaseCoreExtension.podspec
- FirebaseCoreInternal.podspec
- FirebaseCrashlytics.podspec
- FirebaseDynamicLinks.podspec
- FirebaseDynamicLinks/Sources/Resources/PrivacyInfo.xcprivacy
- FirebaseFirestore.podspec
- FirebaseFirestoreInternal.podspec
- FirebaseInstallations.podspec
- FirebaseInstallations/Source/Library/Resources/PrivacyInfo.xcprivacy
- FirebaseMessaging.podspec
- FirebaseMessaging/Sources/Resources/PrivacyInfo.xcprivacy
- FirebaseRemoteConfig.podspec
- FirebaseRemoteConfig/Swift/Resources/PrivacyInfo.xcprivacy
- Firestore/Source/Resources/PrivacyInfo.xcprivacy
- Firestore/Swift/Source/Resources/PrivacyInfo.xcprivacy
- Package.swift
Add privacy manifests for the Firebase SDKs named in https://developer.apple.com/support/third-party-SDK-requirements/
FirebaseCoreDiagnostics is not included because it is no longer part of the product.
Other non-named Firebase SDKs are still being investigated.
> Privacy Manifests for named Firebase SDKs

- ReleaseTooling/Sources/Utils/FileManager+Utils.swift
- ReleaseTooling/Sources/ZipBuilder/ResourcesManager.swift
- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
fix #12422
It turns out that Resources in macOS and catalyst are generated by xcodebuild in Privacy Manifest bundles. When xcodebuild creates a fat framework including Catalyst, the Resource structure is maintained.
This PR fixes the directory enumeration so that Privacy manifest bundles are always treated as atomic entities. Reference https://developer.apple.com/documentation/foundation/filemanager/2765464-enumerator
After more investigation, this PR only fixes the documentation. Everything else should be ready for further testing of privacy manifests.
#no-changelog
> Fix metadata.md generation

- Crashlytics/CHANGELOG.md
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/SourcesObjC/NanoPB/FIRSESNanoPBHelpers.h
- FirebaseSessions/SourcesObjC/NanoPB/FIRSESNanoPBHelpers.m
- Package.swift
It's not clear to me how to reliably pass arrays of structures from Swift to C, so I changed the boundary so that only a pointer to a struct needs to be passed across the language barrier.
See an example of passing arrays at https://github.com/firebase/firebase-ios-sdk/issues/11403#issuecomment-1963020799. When passing to the Swift inout parameter, only the zeroth element of the array gets copied.
Fix #11403
> Fix FirebaseSessions release mode crash

- Crashlytics/CHANGELOG.md
- Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.h
- Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.m
- Crashlytics/Crashlytics/Models/FIRCLSInstallIdentifierModel.h
- Crashlytics/Crashlytics/Models/FIRCLSInstallIdentifierModel.m
- Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.h
- Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
- Crashlytics/Protogen/nanopb/crashlytics.nanopb.c
- Crashlytics/Protogen/nanopb/crashlytics.nanopb.h
- Crashlytics/UnitTests/FIRCLSContextManagerTests.m
- Crashlytics/UnitTests/FIRCLSInstallIdentifierModelTests.m
- Crashlytics/UnitTests/FIRCLSReportAdapterTests.m
- Crashlytics/UnitTests/Mocks/FIRMockInstallations.h
- Crashlytics/UnitTests/Mocks/FIRMockInstallations.m
- FirebaseSessions/Sources/Development/DevEventConsoleLogger.swift
- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/FirebaseSessionsError.swift
- FirebaseSessions/Sources/Installations+InstallationsProtocol.swift
- FirebaseSessions/Sources/SessionCoordinator.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Sources/Settings/SettingsDownloadClient.swift
- FirebaseSessions/SourcesObjC/Protogen/nanopb/sessions.nanopb.c
- FirebaseSessions/SourcesObjC/Protogen/nanopb/sessions.nanopb.h
- FirebaseSessions/Tests/Unit/Mocks/MockInstallationsProtocol.swift
- FirebaseSessions/Tests/Unit/SessionCoordinatorTests.swift
Backend change: cl/605651435, cl/607350087
Adding `firebase_authtication_token` to session_event and report_event
Note:
[installations authTokenWithCompletion:] and [installations installationIDWithCompletion:] run async.
Test:
Checked session is record to real time table: https://plx.corp.google.com/scripts2/snapshots/_59d646f1_02d0_4793_bae9_8e5ffc231f39?resourcekey=LcVuPRToXp0YpeQk0d8Djw
> Sending authentication token for crashlytics and session

- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/Podfile
Add Fireperf dependency to feature rollouts test app
#no-changelog
> Add Fireperf dependency to feature rollouts test app

- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
- ReleaseTooling/Sources/ZipBuilder/ModuleMapBuilder.swift
Updated the gRPC-C++ framework name to `grpcpp` to match the module name: https://github.com/grpc/grpc/blob/0d69f8dc7492507ed4280a55f97a06cc35a813d2/gRPC-C%2B%2B.podspec#L44-L47
#no-changelog
> [Release Tooling] Rename gRPC-C++ framework to grpcpp

- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
context in b/327020913
Validated locally by building one xcframework. It's possible this could blow up when building all of the xcframeworks, but hopefully not.
> [Release Tooling] Validation workaround for Xcode 15.3b3

- FirebaseCore/CHANGELOG.md
- Firestore/CHANGELOG.md
Updated `Unreleased` CHANGELOG entries to `10.22.0`.
> Update CHANGELOG entries to 10.22.0

- FirebaseCore/CHANGELOG.md
From https://github.com/firebase/firebase-ios-sdk/pull/12443#pullrequestreview-1906614952:
> We still need a release note about privacy manifest introduction and probably one about addressing validation issues in Xcode 15.3 for binary distributions including Analytics and Firestore(SPM)
> [Release] Additional changelog updates for 10.22.0

- ReleaseTooling/Template/README.md
I haven't fully investigated what is going on here. But when integrating `FirebaseCrashlytics.xcframework`, I see:
Adding `-lc++` fixes the errors. 
Two observations:
1. The errors only appear after adding the `-ObjC` flag.
2. Crashlytics's `module.modulemap` includes  `link "c++"` and so does Analytics's. But, weirdly, this error does not surface when just depending on Analytics.
Steps to reproduce:
1. In Xcode 15, create app.
2. Drag in necessary xcframeworks for Crashlytics
3. Notice the build succeeds
4. Add -ObjC linker flag 
5. Notice build fails
6. Add -lc++ linker flag 
7. Notice build succeeds
> [Release Tooling] Recommend -lc++ linker flag for manual integration

- FirebaseCore/CHANGELOG.md
- Firestore/CHANGELOG.md
Added a CHANGELOG entry that covers the framework renames in #12437 and #12447. Removed the entry from `Firestore/CHANGELOG.md` since it is now covered by this one.
> Add CHANGELOG entry for renamed frameworks

- FirebaseCore/CHANGELOG.md
Fixed typos on `BoringSSL-GRPC` and `grpcpp`.
> Fix framework names in changelog entry

- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
- ReleaseTooling/Sources/ZipBuilder/ModuleMapBuilder.swift
Renamed several frameworks to match their module names (`CFBundleExecutable` name in their `Info.plist` files):
- `abseil` --> `absl`: https://github.com/CocoaPods/Specs/blob/c51b98a526569c195efaa40f8b15c0c80ea05297/Specs/3/8/6/abseil/1.20240116.1/abseil.podspec.json#L17
- `BoringSSL-GRPC` --> `openssl_grpc`: https://github.com/grpc/grpc/blob/00c01f395c01204fbd767abe7143bd1a49e82a20/src/objective-c/BoringSSL-GRPC.podspec#L87-L92
- `gRPC-Core` --> `grpc`: https://github.com/grpc/grpc/blob/00c01f395c01204fbd767abe7143bd1a49e82a20/gRPC-Core.podspec#L48-L54
- `leveldb-library` --> `leveldb`
- `PromisesSwift` --> `Promises`: https://github.com/google/promises/blob/540318ecedd63d883069ae7f1ed811a2df00b6ac/PromisesSwift.podspec#L26
#no-changelog
> [Release Tooling] Rename frameworks to match modules

- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
I think binary plists are more performant, but I don't think xml plists will significantly worse since they are so small. I think making the switch is worth it so zip are easier to diff.
See https://github.com/firebase/firebase-ios-sdk/pull/12439#discussion_r1506141724
> [Release Tooling] Prefer xml Info.plist

- Package.swift
Updated the Firestore binary with the release candidate for the 10.22.0 release.
#no-changelog
> [Release] Add Firestore 10.22.0 binary

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
Updated the Carthage artifacts for the 10.22.0 release. Verified with `carthage update`.
<details>
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseABTestingBinary.json" "10.22.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAdMobBinary.json" "10.22.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "10.22.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppCheckBinary.json" "10.22.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppDistributionBinary.json" "10.22.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" "10.22.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json" …
```
> [Release] Carthage updates for 10.22.0

- FirebaseAnalyticsOnDeviceConversion.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 10.22.1 #no-changelog
> Analytics 10.22.1

- CONTRIBUTING.md
- FirebaseDatabase/Tests/Integration/FData.m
- FirebaseDatabase/Tests/Integration/FIRDatabaseQueryTests.m
- FirebaseDatabase/Tests/Integration/FOrderByTests.m
- Firestore/core/src/immutable/keys_view.h
- Firestore/core/src/util/hashing.h
- README.md
- scripts/setup_check.sh
- scripts/style.sh
`clang-format@17` is no longer available in Homebrew, upgraded to v18.
#no-changelog
> Upgrade `clang-format` to v18

- FirebaseAnalyticsOnDeviceConversion.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Cherry picking commit 89526bf44a74f0cc1e53a18de74090e01f1828db into `release-10.22.1`.
#no-changelog
> Analytics 10.22.1 (#12482)

- FirebaseAnalyticsOnDeviceConversion.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
> Restore 10.23.0 versions to main after 10.22.1

- cmake/external/abseil-cpp.cmake
- cmake/external/abseil-cpp.patch.txt
The current version of abseil-cpp (used by grpc) uses some deprecated builtins, which cause warnings that make the build fail on Xcode 15 (due to warnings-as-errors).
Until grpc is updated, this PR will work around the issue by adding a patch to abseil-cpp to turn off that warning for that file.
> Patch abseil-cpp to ignore deprecated errors in new Xcode.

- cmake/external/abseil-cpp.patch.txt
#12498 merged with trailing whitespace. fixing here.
> Fix CI breakage from recent merge

- FirebaseMessaging.podspec
Fix #12511 
* FirebaseMessaging-Unit-unit and FirebaseMessaging-Unit-integration tests passed
> Resolved warning no rule to process file 'PrivacyInfo.xcprivacy' of type 'text.xml' with CocoaPods

- FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
- FirebaseRemoteConfig/Sources/RCNConstants3P.m
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/FirebaseRemoteConfigSwift_APIBuildTests.swift
Revert constants change in remote config public api test
Add back the firebase namespace constant in RC
#no-changelog
> [Rollouts] Revert constants change in remote config public api test

- scripts/check_firestore_symbols.sh
Example of new output (bottom of screenshot)
#no-changelog
> [Firestore] Improve logging in scripts/check_firestore_symbols.sh

- FirebaseFirestoreInternal/FirebaseFirestore/FIRSnapshotListenOptions.h
Working on a CI workflow to automate the detection of this... This is gtg though.
#no-changelog
> [Firestore] Re-export public header added in #12370

- Firestore/core/src/local/index_backfiller.cc
- Firestore/core/src/local/index_backfiller.h
- Firestore/core/src/local/local_documents_view.cc
- Firestore/core/src/local/local_documents_view.h
- Firestore/core/src/remote/bloom_filter.cc
> Fix Firestore build warnings

- Package.swift
> [Release] Re-spin FST with signed artifact

- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
Fix incorrect unit test.
Test on sponge as well it passed: https://fusion2.corp.google.com/invocations/03e0c2a3-996d-4225-91dc-f8b702ecbaaf/targets
#no-changelog
> fix unit tests

- FirebaseVertexAI/Sample/ChatSample/Views/ErrorDetailsView.swift
- FirebaseVertexAI/Sources/Errors.swift
- FirebaseVertexAI/Sources/GenerateContentError.swift
- FirebaseVertexAI/Sources/GenerativeAIRequest.swift
- FirebaseVertexAI/Sources/GenerativeAIService.swift
- FirebaseVertexAI/Sources/GenerativeAISwift.swift
- FirebaseVertexAI/Sources/GenerativeModel.swift
- FirebaseVertexAI/Sources/VertexAI.swift
- Package.swift
- Removed the SPM dependency on `generative-ai-swift`
- Updated `VertexAI` / `VertexAIComponent` to use forked classes
- Updated `GenerativeModel` classes to call Vertex AI instead of Google AI
- Updated samples to reflect SDK changes
#no-changelog
> Use forked `google-generative-ai` in Vertex AI samples

- .github/workflows/vertexai.yml
Runs `spmbuildonly` since the unit tests target is not yet ready.
#no-changelog
> Add CI workflow for Vertex AI

- FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Added tests to verify that an App Check header is added to requests when an `AppCheckInterop` instance is provided. All the previously existing tests verify that the header is not added (`nil`).
#no-changelog
> Add App Check tests in `GenerativeModelTests`

- FirebaseVertexAI/Sample/ChatSample/ViewModels/ConversationViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift
- FirebaseVertexAI/Sources/VertexAI.swift
- FirebaseVertexAI/Sources/VertexAIComponent.swift
- FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
> Make `generativeModel` an instance method of `VertexAI`

- .github/workflows/abtesting.yml
- .github/workflows/auth.yml
- .github/workflows/core.yml
- .github/workflows/core_internal.yml
- .github/workflows/crashlytics.yml
- .github/workflows/database.yml
- .github/workflows/firestore.yml
- .github/workflows/functions.yml
- .github/workflows/installations.yml
- .github/workflows/messaging.yml
- .github/workflows/mlmodeldownloader.yml
- .github/workflows/remoteconfig.yml
- .github/workflows/sessions.yml
- .github/workflows/shared-swift.yml
> More visionOS CI

- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
Took awhile to pin down, but I'm finding there are **two** issues with private headers (I think it's a symptom of CocoaPods setup... not sure).
Affecting grpcpp, grpc, openssl_grpc:
```
grpcpp.framework/
├── Headers -> Versions/Current/Headers
├── Modules -> Versions/Current/Modules
├── PrivateHeaders -> Versions/Current/PrivateHeaders
├── Resources -> Versions/Current/Resources
├── Versions
│   ├── A
│   │   ├── Headers
│   │   ├── Modules
│   │   ├── PrivateHeaders
│   │   │          ├── PrivateHeaders -> Versions/A/PrivateHeaders ←⚠️ This is unexpected that this would be here. 
│   │   │          └── ...
│   │   ├── Resources
│   │   └── grpcpp
│   └── Current -> A
└── grpcpp -> Versions/Current/grpcpp
```
And affecting only abseil:
```
bsl.framework/
├── Headers -> …
```
> [Release Tooling] Add case to address both issues with PrivateHeaders

- .github/workflows/vertexai.yml
- FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
- scripts/build.sh
Verifies the VertexAI Sample build in CI
(The other CI failures are unrelated - a systematic outage of the cache used in some of the jobs)
> Build Sample in CI

- .github/workflows/zip.yml
- FirebaseCore/CHANGELOG.md
- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
- scripts/setup_quickstart_framework.sh
Fix #12557
Change zip builder to create macOS/macCatalyst frameworks with the following format:
```
CoreWaffleVarnishing.framework/
CoreWaffleVarnishing -> Versions/Current/CoreWaffleVarnishing
Resources -> Versions/Current/Resources
Versions/
Current -> A
A/
CoreWaffleVarnishing
Resources/
Info.plist
… other resources …
```
CocoaPods already creates macOS/macCatalyst frameworks with the above structure, so CP frameworks are now copied rather than manually reconstructed.
> [Release Tooling] Update XCFramework structure

- FirebaseVertexAI/Sources/VertexAI.swift
- FirebaseVertexAI/Sources/VertexAIComponent.swift
- FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
- Package.swift
- Use StorageComponentTests as a template for VertexComponentTests
- Get a unique VertexAI instance for different regions.
- Enable OCMock testing on Xcode 15.3
> VertexAI Component tests; fix instance generation for different regions

- FirebaseVertexAI/Sources/CountTokensRequest.swift
- FirebaseVertexAI/Tests/Unit/CountTokenResponses/success-total-tokens.json
- FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Added the field `totalBillableCharacters` to `CountTokensResponse`.
#no-changelog
> Add `totalBillableCharacters` to `CountTokensResponse` in Vertex AI

- FirebaseCore/CHANGELOG.md
Clarify the release note to only Analytics since Firestore won't be fixed until 10.24.0.
> Tweak release note

- FirebaseFirestore.podspec
- ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift
It's confusing for FirebaseFirestoreInternal to float to future versions from the version set on FirebaseFirestore.
> [CocoaPods] Lock FirestoreInternal version to Firestore

- FirebaseVertexAI/Sample/ChatSample/ViewModels/ConversationViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift
- FirebaseVertexAI/Sources/VertexAI.swift
- FirebaseVertexAI/Sources/VertexAIComponent.swift
- FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
- FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
Renamed the Vertex AI parameter `region` to `location`.
#no-changelog
> Rename the Vertex AI parameter `region` to `location`

- Crashlytics/CHANGELOG.md
- FirebaseCore/CHANGELOG.md
- FirebaseStorage/CHANGELOG.md
- Firestore/CHANGELOG.md
> [Release] Version changelog entries for 10.24.0

- FirebaseCore/Sources/FIRApp.m
- FirebaseVertexAI/Sources/GenerativeAIService.swift
- FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
- Updated component name to `fire-vertex`
- Added a `gl-swift/` language tag (omitted a language version based on `gl-objc/` [precedent](https://github.com/firebase/firebase-ios-sdk/blob/c8dadd00b476ca92444c0ff8cae1754a55c2e22c/Firestore/Source/API/FIRFirestore.mm#L120))
- Added a `fire/<firebase-version>` tag
#no-changelog
> Add platform tags in `x-goog-api-client`

- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
#no-changelog
When the tooling looks for resources, it was doing a recursive search and finding the `Resources` directories in all of the macOS/macCatalyst directories (introduced in #12595). Since #12595, every macOS/macCatalyst framework has  a `Resources` directory to contain the framework-level Info.plist (this plist lives at the root of the .framework for other platforms). See below:
_From [Apple Developer - Placing content in a bundle](https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle?language=objc)_
So, to fix `METADATA.md` saying that everything product has resources, do a shallow search in each product directory at the root of the `Firebase.zip`. The resulting `METADATA.md` should match the 10.23.0 `METADATA.md`.
> [Release Tooling] Fix METADATA.md regression introduced in #12595

- FirebaseAuth/Tests/Unit/SwiftAPI.swift
Available swift test cases for passkey
> Passkey swift tests

- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Tests/Unit/FIRUserTests.m
Fix the provided passkey name not being cached issue.  Added more unit tests to guard this.
> fix passkey name caching issue

- FirebaseVertexAI/Sources/GenerateContentResponse.swift
- FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Added a computed property that returns the function calls, if any, from the first candidate of a `GenerateContentResponse`. This is a port of https://github.com/google/generative-ai-swift/pull/123.
#no-changelog
> Add `functionCalls` accessor to `GenerateContentResponse`

- FirebaseCore/Sources/FIROptions.m
- FirebaseCore/Tests/Unit/FIROptionsTest.m
- Package.swift
- SwiftPMTests/swift-test/all-imports.swift
Based on https://semver.org/#spec-item-9
- Start with `0.1.0-vertexai-preview`
- Fix some implementations and tests to handle both one and two digit major versions
- Update tests to handle string suffix
Confirmed that SPM Update to Latest will do an automatic update from https://github.com/paulb777/app-check/releases/tag/0.1.0-vertexai-preview to https://github.com/paulb777/app-check/releases/tag/0.2.0-vertexai-preview
> Vertex AI preview versioning

- FirebaseVertexAI/Sample/ChatSample/ViewModels/ConversationViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift
- FirebaseVertexAI/Sources/VertexAI.swift
- FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
Removed the `location` parameter from VertexAI public APIs -- now hardcoded to `us-central1`.
#no-changelog
> Remove `location` from Vertex AI public API

- FirebaseVertexAI/Sources/GenerativeAIRequest.swift
- Removed the `apiVersion` parameter from the `RequestOptions` constructor in Vertex AI
- Hardcoded `v2beta` since it is the only supported API version
> Remove `apiVersion` from `RequestOptions` in Vertex AI

- Package.swift
> [Release] Update binary SPM Firestore distro for 10.24.0

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuthErrors.h
- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.h
- FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m
- FirebaseAuth/Sources/Utilities/FIRAuthInternalErrors.h
Added the public facing ERROR_PASSKEY_ENROLLMENT_NOT_FOUND error
Fix the app crashing issue after sign in with a already removed passkey. The issue was due to after receiving the error, we kept going with the sign in.  Added the return statement after error has been received.
> fix the sign in with deleted passkey crash issue

- FirebaseVertexAI/Sample/GenerativeAISample.xcodeproj/project.pbxproj
- FirebaseVertexAI/Sample/GenerativeAISample/GenerativeAISampleApp.swift
- FirebaseVertexAI/Sample/GoogleService-Info.plist
- FirebaseVertexAI/Sample/README.md
- Added a placeholder/fake `GoogleService-Info.plist` file to Vertex AI sample app to make it easier to see where to place a real one.
- Added a `projectID` check for `mockproject-1234`, printing instructions to the console if the placeholder file has not been replaced.
- Updated the sample's bundle ID to `com.google.firebase.VertexAISample`.
- Added a README for the sample directory.
#no-changelog
> Add placeholder `GoogleService-Info.plist` to Vertex AI sample

- FirebaseAuth/Tests/Sample/AuthSample.xcodeproj/project.pbxproj
- FirebaseAuth/Tests/Sample/Sample/MainViewController+OAuth.m
- FirebaseAuth/Tests/Sample/Sample/MainViewController+Passkey.h
- FirebaseAuth/Tests/Sample/Sample/MainViewController+Passkey.m
- FirebaseAuth/Tests/Sample/Sample/MainViewController.m
- FirebaseAuth/Tests/Sample/Sample/UserInfoViewController.m
Added a passkey section in sample app for sign up with passkey, enrollment with passkey, sign in with passkey and withdraw passkey workflows.
This PR addressed the comments in https://github.com/firebase/firebase-ios-sdk/pull/12128.
This PR added passkey withdraw workflow in sample app
> Sample app for passkey

- FirebaseVertexAI/Sources/CountTokensRequest.swift
- FirebaseVertexAI/Tests/Unit/CountTokenResponses/success-no-billable-characters.json
- FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
`CountTokensResponse` omits `totalBillableCharacters` on image-only prompts (no characters). Set `totalBillableCharacters` to `0` during decoding if the field is omitted from the JSON payload.
#no-changelog
> Handle `totalBillableCharacters` optional decoding in Vertex AI

- FirebaseVertexAI/Sources/FunctionCalling.swift
- FirebaseVertexAI/Sources/GenerateContentRequest.swift
- FirebaseVertexAI/Sources/GenerativeModel.swift
- FirebaseVertexAI/Sources/VertexAI.swift
Implemented "forced" (formerly "constrained") function calling (see [`ToolConfig`](https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/ToolConfig) for details). This is a port of https://github.com/google/generative-ai-swift/pull/124.
Testing in Function Calling Sample + Gemini 1.5 Pro:
- `AUTO` default behaviour (no changes)
- `NONE` disables function calls ("Unfortunately, I don't have access to real-time exchange rates...")
- `ANY`
- `allowedFunctionNames: nil` - no function calls allowed, same as `NONE`
- `allowedFunctionNames: ["get_exchange_rate"]` - only returns function calls, no text
#no-changelog
> Add forced function calling support in Vertex AI

- FirebaseVertexAI/Sources/GenerateContentRequest.swift
- FirebaseVertexAI/Sources/GenerativeModel.swift
- FirebaseVertexAI/Sources/VertexAI.swift
- FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
Added support for providing a system instruction when instantiating a `GenerativeModel` in Vertex AI. This can be used to direct the model towards specific behaviour. This is a port of https://github.com/google/generative-ai-swift/pull/129.
Testing Example:
```
let model = VertexAI.vertexAI().generativeModel(
modelName: "gemini-1.5-pro-preview-0409",
systemInstruction: ModelContent(parts: "Talk like a pirate.")
)
let response = try await model.generateContent("Hello")
print(response.text!)
```
> Ahoy there, matey! 👋  What brings ye to these waters? 🦜  Is there loot to be plundered or a hearty tale to be told? 💰  Speak yer mind, me hearty! 🗣️ 
#no-changelog
> Add system instruction support in Vertex AI

- FirebaseVertexAI/Sample/GenerativeAISample.xcodeproj/project.pbxproj
- FirebaseVertexAI/Sample/GenerativeAISample/GenerativeAISampleApp.swift
- Removed Firebase App Check from the list of frameworks installed by default in the Vertex AI sample
- It is not required to use the sample and emits a DeviceCheck (default provider) configuration error if not configured
- Added a recommendation comment to use App Check where we call `FirebaseApp.configure()`
#no-changelog
> Remove FirebaseAppCheck module from Vertex AI sample app

- .github/actions/notices_generation/app.rb
- CONTRIBUTING.md
- Crashlytics/Crashlytics/Components/FIRCLSApplication.h
- Crashlytics/Crashlytics/Components/FIRCLSContext.h
- Crashlytics/Crashlytics/Components/FIRCLSProcess.c
- Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c
- Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c
- Crashlytics/Crashlytics/Helpers/FIRCLSAllocate.c
- FirebaseMessaging/Sources/FIRMessagingPubSub.m
- docs/AddNewPod.md
- docs/AddNewProduct.md
Fixed typos. Mainly Crashlytics
1. sep `e` rated -> separated
2. contin ` ` ous -> continuous
3. occur ` ` ences -> occurrences
4. app `p` ears -> appears
5. han `ld` ers -> handlers
6. rece ` ` ving -> receiving
7. invo `k` ved -> involved
8. mult ` ` ples -> multiples
> Fix some typos

- Firestore/core/src/util/string_format.cc
The Visual Studio compiler doesn't support __attribute__((no_sanitize_address)), and instead expects __declspec(no_sanitize_address), so adjust the usage to swap between those two options based on which is being used.
This fixes the Firebase C++ SDK build.
#no-changelog
> Use declspec in Firestore on Windows machines

- Crashlytics/CHANGELOG.md
- FirebaseAppCheck/CHANGELOG.md
- FirebaseDatabase/CHANGELOG.md
- FirebaseInAppMessaging/CHANGELOG.md
- FirebasePerformance/CHANGELOG.md
I recently merged PRs to migrate away from user defaults for the following SDKs:
- App Check
- Performance
- Sessions
- InAppMessaging
- Database
I'm updating each's changelog with the exception of Sessions because Sessions does not have a changelog. So, I'm ensuring that its clients, Crashlytics & Performance, mention this in their changelogs.
#no-changelog
> [Release] Update changelogs for user defaults migration PRs

- FirebaseVertexAI/Sample/ChatSample/Views/ErrorDetailsView.swift
- FirebaseVertexAI/Sample/ChatSample/Views/ErrorView.swift
- FirebaseVertexAI/Sources/GenerateContentResponse.swift
- FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
Added [`usageMetadata`](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/GenerateContentResponse#usagemetadata) to `GenerateContentResponse`.
#no-changelog
> Add `usageMetadata` to `GenerateContentResponse` in Vertex AI

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
After the 10.25.0 release, Xcode 15.2 will be the lowest supported Xcode version.
#no-changelog
> Update Issue Xcode placeholder to a supported version

- FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
Added tests to verify that the expected symbols in `GenerateContentResponse` are public.
#no-changelog
> Add public API tests for `GenerateContentResponse` in Vertex AI

- .github/workflows/archiving.yml
- .github/workflows/firestore.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/spectesting.yml
Fix #12780
Now that https://github.com/grpc/grpc/pull/36340 has been published in grpc 1.62.5, update dependent CI jobs to macos-14
> [CI] Update grpc dependent jobs to macos-14

- Firestore/CHANGELOG.md
- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
- Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift
- Firestore/core/src/nanopb/nanopb_util.h
This should fix:
https://github.com/firebase/firebase-ios-sdk/issues/12620
https://github.com/firebase/firebase-ios-sdk/issues/11773
> Allow Blob of data with zero length.

- FirebaseVertexAI/Sources/GenerativeAIService.swift
Added a version value to the language tag in Vertex AI. Blank values weren't being picked up by the backend. Picked version `5` (the Swift major version supported) since we don't need anything more specific.
#no-changelog
> [Vertex AI] Add Swift major version to language tag

- FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
https://github.com/firebase/firebase-ios-sdk/issues/10884
* I ran Firebase remote config tests locally.
> Make use of SQLITE_OPEN_FILEPROTECTION_COMPLETEUNTILFIRSTUSERAUTHENTICATION conditional.

- FirebaseVertexAI/Sources/VertexAI.swift
- FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
Re-added the `location` parameter that was removed in https://github.com/firebase/firebase-ios-sdk/pull/12706 to allow developers to specify a custom location ID. The location `us-central1` is used as a default if not specified.
#no-changelog
> [Vertex AI] Re-added `location` parameter to public API

- FirebaseVertexAI/Sources/CountTokensRequest.swift
- FirebaseVertexAI/Sources/FunctionCalling.swift
- FirebaseVertexAI/Sources/GenerateContentResponse.swift
- FirebaseVertexAI/Sources/GenerationConfig.swift
- FirebaseVertexAI/Sources/ModelContent.swift
- FirebaseVertexAI/Sources/Safety.swift
Removed public `Codable` (`Decodable` and/or `Encodable`) conformance. This is a port of https://github.com/google-gemini/generative-ai-swift/pull/142.
#no-changelog
> [Vertex AI] Remove public `Codable` conformance

- FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m
- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
- ReleaseTooling/Template/README.md
In practice, this PR will remove the gRPC-Certificates.bundle and add the FIAM UI resource bundle into the framework (rather than alongside it). 
Checks on green CI:
- I was able to validate that iOS and macOS apps archive, but am having certs trouble getting to the App Store Connect part.
#no-changelog
> [Release Tooling] Consistent approach to resources when building on Xcode 15

- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
There is an unused folder that is created during the zip build: `frameworks_being_built/`. It's unused so it looks safe to remove.
#no-changelog
> [Release Tooling] Cleanup unused folder references

- Crashlytics/CHANGELOG.md
- FirebaseAppCheck/CHANGELOG.md
- FirebaseCore/CHANGELOG.md
- FirebaseDatabase/CHANGELOG.md
- FirebaseInAppMessaging/CHANGELOG.md
- FirebasePerformance/CHANGELOG.md
- FirebaseRemoteConfig/CHANGELOG.md
- Firestore/CHANGELOG.md
Updated `Unreleased` changelog entries to `10.25.0`.
#no-changelog
> Update unreleased changelog entries for 10.25.0

- FirebaseAuth/Interop/FIRAuthInterop.h
- FirebaseFunctions.podspec
- FirebaseStorage.podspec
The `getTokenForcingRefresh:withCallback:` method in FirebaseAuthInterop can invoke the completion handler with [`nil, nil`](https://github.com/firebase/firebase-ios-sdk/blob/521cbcf3c17008ccc46509523e3a854d38749e41/FirebaseAuth/Sources/Auth/FIRAuth.m#L2546) but `(void (^)(SomeType *_Nullable value, NSError *_Nullable error))` completion blocks are translated to `async throws -> SomeType` in Swift async/await. The `_Nullable_result` annotation, instead of just `_Nullable`, signals that the return type may be `nil` even when no error is thrown; see Swift [SE-0297](https://github.com/apple/swift-evolution/blob/43b894b0c496b69dd8636bc97bb720212647bb7a/proposals/0297-concurrency-objc.md?plain=1#L259) for more details.
Before:
`func getToken(forcingRefresh forceRefresh: Bool) async throws -> …
> Update `FIRAuthInterop` to use `_Nullable_result` annotation

- .github/workflows/api_diff_report.yml
- FirebaseStorage/Sources/Storage.swift
Updated to Python 3.10 since Python 3.7 [isn't available](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) on `arm64`.
#no-changelog
> Use Python 3.10 in `diff_report` job

- .github/workflows/api_diff_report.yml
- FirebaseVertexAI/Sources/VertexAI.swift
- Added `location` validation (must not be empty or contain whitespace/newline or `/` characters).
- Updated the `location` docs to point to the Generative AI-specific [URL](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/locations#available-regions).
This makes the location validation closer to the Android implementation https://github.com/firebase/firebase-android-sdk/pull/5890/files.
#no-changelog
> [Vertex AI] Add `location` checks for slashes and whitespace

- .github/workflows/performance.yml
Updated the Performance `quickstart` job to run on `macos-14` and disabled the legacy ObjC quickstart which doesn't build on Xcode 15.
#no-changelog
> Disable failing ObjC Performance quickstart on CI

- .github/workflows/functions.yml
- .github/workflows/performance.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/storage.yml
> Cherrypick CI fixes into vertex-ai branch

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
Updated the Carthage artifacts for the https://github.com/firebase/firebase-ios-sdk/releases/tag/10.25.0. Verified with `carthage update`.
<details>
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseABTestingBinary.json" "10.25.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAdMobBinary.json" "10.25.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "10.25.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppCheckBinary.json" "10.25.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppDistributionBinary.json" "10.25.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" "10.25.0"
binary …
```
> [Release] Carthage updates for 10.25.0

- Package.swift
Note: This is planned to be an SPM-only release so the version is only changed in `Package.swift`.
#no-changelog
> [Release] Update Package.swift for 10.26.0

- Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.m
- Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c
- Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c
- Crashlytics/Crashlytics/Handlers/FIRCLSSignal.h
All Apple OS's send SIGTERM (like any good unix based system) when they want to request a graceful termination of an application, when the app doesn't quit in those circumstances, it'll receive a SIGKILL. This often gives us the opportunity to get a stack trace where we know Apple wants the app to be terminated but don't know why (watchdog events). This is just one more piece of information that can be added to the puzzle of figuring out unexplained app terminations.
Example in the Firebase Console:
> Add SIGTERM support

- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/SceneDelegate.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/OtherAuthMethodControllers/PasswordlessViewController.swift
- FirebaseAuth/Tests/SampleSwift/Podfile
- FirebaseAuth/Tests/SampleSwift/README.md
Remove FDL dependency from the sample and update the README.
I'll make similar changes to the quickstart once this merges.
> [auth-swift] Remove FDL dep and update sample readme

- FirebaseVertexAI/Sample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift
- FirebaseVertexAI/Sources/Chat.swift
- FirebaseVertexAI/Sources/ModelContent.swift
- FirebaseVertexAI/Tests/Unit/ModelContentTests.swift
- FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
Added support for URI-based file data (in addition to existing support for data as inline bytes). Files may be uploaded using the Firebase Storage SDK.
Example Usage:
```
// Obtain a reference to the file in Firebase Storage.
let reference = Storage.storage().reference(withPath: "/image.jpg")
let imagePart = ModelContent.Part.fileData(
mimetype: "image/jpeg",
// Construct a gs:// URI from the bucket name and full path
uri: "gs://\(reference.bucket)/\(reference.fullPath)"
)
```
#no-changelog
> [Vertex AI] Add URI-based file data support

- .github/workflows/analytics.yml
- .github/workflows/database.yml
- .github/workflows/firestore.yml
- .github/workflows/inappmessaging.yml
- .github/workflows/remoteconfig.yml
- scripts/health_metrics/file_patterns.json
We have no plans to release these podspecs again and will remove them in the next major release.
> Stop CI on Swift podspecs

- FirebaseVertexAI/Sources/FunctionCalling.swift
Added a default value of `nil` for `requiredParameters` in the `FunctionDeclaration` constructor. This is a port of https://github.com/google-gemini/generative-ai-swift/pull/153.
#no-changelog
> [Vertex AI] Add default `nil` for `FunctionDeclaration` `requiredParameters`

- .github/workflows/zip.yml
- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
- ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift
- scripts/build_zip.sh
> [Release Tooling] Add functionality to build dynamic frameworks

- FirebaseMessaging/Sources/FIRMessagingRmqManager.m
#12900
* I ran tests locally ✅
> Improve Usage of SQLITE_OPEN_FILEPROTECTION_NONE in FIRMessagingRmqManager.m

- FirebaseVertexAI-Docs.podspec
- FirebaseVertexAI/Sources/Chat.swift
- FirebaseVertexAI/Sources/GenerativeAIService.swift
- FirebaseVertexAI/Sources/GenerativeAISwift.swift
- FirebaseVertexAI/Sources/GenerativeModel.swift
- FirebaseVertexAI/Sources/VertexAI.swift
Successor to #12911.
#no-changelog
> Add docsgen podspec for VertexAI and clean up some doc comments

- FirebaseDatabase/CHANGELOG.md
- FirebaseDatabase/Sources/Realtime/FWebSocketConnection.h
- FirebaseDatabase/Sources/Realtime/FWebSocketConnection.m
- FirebaseDatabase/Tests/Integration/FData.m
- FirebaseDatabase/Tests/Integration/FIRDatabaseQueryTests.m
Use the previously implemented NSURLSessionWebSocket for all platforms that support it instead of only watchOS where it was only previously used.
Fix #12883
> [RTDB] Use NSURLSessionWebSocket instead of SocketRocket where possible

- FirebaseVertexAI/Sources/Constants.swift
- FirebaseVertexAI/Sources/CountTokensRequest.swift
- FirebaseVertexAI/Sources/GenerateContentRequest.swift
- FirebaseVertexAI/Sources/ModelContent.swift
- FirebaseVertexAI/Sources/Safety.swift
- FirebaseVertexAI/Sources/VertexAI.swift
- Renamed `GenerativeAISwift` to `Constants` and made it `internal` instead of `public`.
- Not needed for external use.
- Fixed `intepretable` and `indiciate` typos.
- Expanded on `VertexAI` class docs.
#no-changelog
> [Vertex AI] Make `Constants` file internal and fix typos

- FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m
Address feedback in https://github.com/firebase/firebase-ios-sdk/commit/ab94a58fd65f83a6e432c6d67aebdb3b0ccf7bed#r141810158
#no-changelog
> [InAppMessaging] Follow-up to #12910

- FirebaseInAppMessaging/CHANGELOG.md
- FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m
After merging, will cherry-pick this along with  #12910 and #12917 into the `release-10.26` branch (via PR).
> [Release] Update FIAM changelog to reflect 10.26.0

- FirebaseVertexAI/Sources/GenerationConfig.swift
- FirebaseVertexAI/Tests/Unit/GenerationConfigTests.swift
- FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
Added a [`responseMIMEType`](https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/GenerationConfig) parameter to the `GenerationConfig` constructor to allow configuration of the media type of the generated candidate text (e.g., `"application/json"` to produce JSON text). This is a port of https://github.com/google-gemini/generative-ai-swift/pull/161.
#no-changelog
> [Vertex AI] Add `responseMIMEType` to `GenerationConfig`

- FirebaseVertexAI/Sources/GenerateContentResponse.swift
- FirebaseVertexAI/Tests/Unit/GenerateContentResponses/unary-success-function-call-mixed-content.json
- FirebaseVertexAI/Tests/Unit/GenerateContentResponses/unary-success-function-call-parallel-calls.json
- FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
- Added support for responses that include both `text` and `functionCall` parts (or other content types in the future).
- Note: Multiple `text` parts in a single response is theoretical at this time (may need to revisit the joining approach if the output doesn't match our expectations).
- Also added a test for parallel function calling (multiple `functionCall` parts in one response).
This is a port of https://github.com/google-gemini/generative-ai-swift/pull/165.
#no-changelog
> [Vertex AI] Make `text` computed property handle mixed-parts responses

- .github/workflows/auth.yml
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample.xcodeproj/project.pbxproj
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/AppDelegate.swift
- FirebaseAuth/Tests/SampleSwift/ObjCApiTests/AnonymousAuthTests.m
- FirebaseAuth/Tests/SampleSwift/ObjCApiTests/EmailPasswordAuthTests.m
- FirebaseAuth/Tests/SampleSwift/SwiftApiTests/FacebookTests.swift
- FirebaseAuth/Tests/SampleSwift/SwiftApiTests/GoogleTests.swift
- scripts/build.sh
- scripts/install_prereqs.sh
> [auth-swift] Build and test Sample with SPM instead of CocoaPods

- FirebaseAppCheck.podspec
- FirebaseAppCheck/CHANGELOG.md
Fix #12899
FirebaseAppCheck uses `FIRGetLoggerLevel` which was added to FirebaseCore in 10.18.0. Update the podspec dependency to reflect that.
> Update FirebaseAppCheck's FirebaseCore dependency
