- FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuthErrors.h
> fix doc comments in auth header

- .github/workflows/notice_generation.yml
- .github/workflows/prerelease.yml
- Update typo of the prerelease workflow
- Schedule notices generations earlier than nightly report generation, which will involve the latest generation outcome.
> Update testing workflows

- FirebaseFunctions/Tests/ObjCIntegration/FIRIntegrationTests.m
Attempting to update tests to reproduce #9855
> Verify localizedDescription with FunctionsInvalid Argument error

- .github/workflows/update-cpp-sdk-on-release.yml
> For updating C++ deps, also recognize GITHUB_REF of refs/tags/x.y.z

- FirebaseAnalyticsSwift.podspec
- FirebaseAnalyticsSwift/Tests/SwiftUnit/AnalyticsAPITests.swift
> Analytics swift API tests

- docs/ContinuousIntegration.md
Thanks to @granluo who wrote the initial version of much of this content in an internal doc.
> Add Continuous Integration docs

- ReleaseTooling/Sources/ZipBuilder/CocoaPodUtils.swift
- ReleaseTooling/Sources/ZipBuilder/ModuleMapBuilder.swift
- I made some unrelated refactors while working on #9829 and wanted to send them in their own PR
#no-changelog
> [Infra] Refactors small areas of the `ZipBuilder`

- FirebaseFunctions/CHANGELOG.md
Corresponding Changelog update for #9955
> Changelog for Functions Error code fix

- FirebaseDatabase/CHANGELOG.md
- FirebaseDatabase/Sources/Api/FIRDatabase.m
> Fix RTDB race condition

- .github/workflows/watchos-sample.yml
> [Infra] Fix incorrectly named GHA job

- .github/workflows/zip.yml
- FirebaseCore/CHANGELOG.md
- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
> Fix module name for Promises and Protobuf

- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
Replace NSLog with kFIRLoggerRemoteConfig. b/240725171
> Replace NSLog with kFIRLoggerRemoteConfig

- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
Fixes bugs from the bug bash. Also adds check for background so connection is not made while app is in the background.
- bug/241812063 - Too many config updates when reconnecting stream
- bug/241811829 - Multiple config updates during start up
- bug/241810568 - Duplicate Fetches
> Realtime rc merge patch v1

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
- Firestore/Source/API/FIRFilter+Internal.h
- Firestore/Source/API/FIRFilter.mm
- Firestore/Source/API/FIRQuery+Internal.h
- Firestore/Source/API/FIRQuery.mm
- Firestore/core/src/api/query_core.cc
- Firestore/core/src/api/query_core.h
- Firestore/core/src/core/composite_filter.cc
- Firestore/core/src/core/composite_filter.h
- Firestore/core/src/core/field_filter.cc
- Firestore/core/src/core/field_filter.h
- Firestore/core/src/core/filter.h
- Firestore/core/src/core/query.cc
- Firestore/core/src/core/query.h
- Firestore/core/src/core/target.cc
- Firestore/core/src/local/leveldb_index_manager.cc
- Firestore/core/test/unit/core/filter_test.cc
- Firestore/core/test/unit/testutil/testutil.cc
- Firestore/core/test/unit/testutil/testutil.h
#no-changelog
- Implement the Composite Filter class.
- Perform parsing of AND/OR filters to create Composite Filter objects.
- Add filter validation for composite filters.
- Update core/query and api/query_core to handle composite filters.
> Implement the Composite Filter class

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
Updated the Carthage JSON files for the Firebase 9.5.0 release.
> Update Carthage JSON for Firebase 9.5.0

- ReleaseTooling/Sources/ZipBuilder/CocoaPodUtils.swift
> Fix Analytics source build

- FirebaseDatabase/CHANGELOG.md
- FirebaseDatabase/Sources/third_party/SocketRocket/FSRWebSocket.m
> Fix priority inversion issue exposed by Xcode 14

- .github/workflows/prerelease.yml
- .github/workflows/zip.yml
Fix #10129 which only needed more time to finish
> Move zip and prerelease nightlies early

- FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
- FirebaseRemoteConfig/Sources/RCNConfigConstants.h
- FirebaseRemoteConfig/Sources/RCNConfigFetch.m
- FirebaseRemoteConfig/Sources/RCNConfigSettings.m
- FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.h
- FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.m
Save template version in settings
> Save template version in settings

- Firestore/core/src/core/firestore_client.cc
> Fix index backfilling frequency

- FirebaseAnalytics.podspec
- FirebaseAnalyticsSwift/Tests/SwiftUnit/AnalyticsAPITests.swift
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 9.6.0 podspec files
#no-changelog
> Analytics 9.6.0

- FirebaseAnalyticsSwift/Tests/SwiftUnit/AnalyticsAPITests.swift
Add API tests for Analytics.sessionID().
#no-changelog
> Add API tests for Analytics.sessionID()

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
I found I had no way to specify an issue for Firebase dependencies or infrastructure
> Add All and Infrastructure as product options

- Firestore/core/src/core/composite_filter.cc
- Firestore/core/src/core/composite_filter.h
- Firestore/core/src/remote/serializer.cc
- Firestore/core/src/remote/serializer.h
- Firestore/core/test/unit/core/filter_test.cc
- Firestore/core/test/unit/remote/serializer_test.cc
> Support encoding and decoding Composite Filters.

- FirebaseStorage/CHANGELOG.md
Update Changelog including breaking changes for Firebase Storage in next major release.
> Storage Changelog for Firebase 10

- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Sources/Storage.swift
- FirebaseStorage/Tests/Unit/StorageReferenceTests.swift
- Fix CHANGELOG API signatures
- Include `http` in docs
- Add `XCTAssertThrowsError` tests
> Address missed review comments from #10216

- FirebaseStorage/Sources/AsyncAwait.swift
- FirebaseStorage/Sources/Internal/StorageTokenAuthorizer.swift
- FirebaseStorage/Sources/Internal/StorageUtils.swift
- FirebaseStorage/Sources/Storage.swift
- FirebaseStorage/Sources/StorageComponent.swift
- FirebaseStorage/Sources/StorageUploadTask.swift
- FirebaseStorage/Tests/Integration/StorageAsyncAwait.swift
- FirebaseStorage/Tests/Unit/StorageTests.swift
- Add missing sync from the Objective C port
- Add missing interval adjustment when retry times change from the Objective C port
- Review all TODOs in FriebaseStorage. See review notes for more detail
#no-changelog
> Missing sync, missing interval processing, todo review

- scripts/make_release_notes.py
When selecting a specific version, we want to include all its subheaders in the generated output.
> Include subheaders in script output

- Firestore/Source/API/FIRAggregateQuery+Internal.h
- Firestore/Source/API/FIRAggregateQuery.mm
- Firestore/Source/API/FIRAggregateQuerySnapshot+Internal.h
- Firestore/Source/API/FIRAggregateQuerySnapshot.mm
- Firestore/Source/Public/FirebaseFirestore/FIRAggregateQuery.h
- Firestore/Source/Public/FirebaseFirestore/FIRAggregateQuerySnapshot.h
- Firestore/Source/Public/FirebaseFirestore/FIRAggregateSource.h
- Firestore/Source/Public/FirebaseFirestore/FIRQuery.h
The wording is copied from https://github.com/firebase/firebase-android-sdk/pull/4143
#no-changelog
> Firestore: Re-write API docs for COUNT API

- Firestore/CHANGELOG.md
- Update all CHANGELOG entries marked as `# Unreleased`
#no-changelog
> [Firebase 10] Update 'Unreleased' changelog entries

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 10.0.0 #no-changelog
> Analytics 10.0.0

- FirebaseDatabase/CHANGELOG.md
- FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDatabase.h
Addresses, but #10195 is not resolved.
Fixes #10272
> add deprecation for watchOS

- FirebaseCore/Extension/FIRLogger.h
- FirebaseCore/Sources/FIRLogger.m
- FirebaseFirestoreSwift.podspec
- Firestore/Example/Podfile
- Firestore/Swift/CHANGELOG.md
- Firestore/Swift/Source/Codable/DocumentID.swift
- Package.swift
> [Firestore] Add runtime warnings to `@DocumentID` setter and initializer

- Firestore/Swift/Source/Codable/DocumentID.swift
- Firestore/Swift/Source/Codable/EncoderDecoder.swift
> Address PR feedback for Firestore Codable

- FirebaseStorage/Tests/Unit/StorageReferenceTests.swift
> [Storage] Extend timeout for flaking test

- Firestore/Source/Public/FirebaseFirestore/FIRQuery.h
> Tweak docs for Query.count

- Firestore/Example/Tests/Integration/API/FIRCountTests.mm
- Firestore/Source/Public/FirebaseFirestore/FirebaseFirestore.h
> Fix missing aggregate query headers in umbrella

- Firestore/Example/Tests/Integration/API/FIRCountTests.mm
- Firestore/Source/Public/FirebaseFirestore/FirebaseFirestore.h
Cherry-pick #10301 to release-10.0 branch
> Fix missing aggregate query headers in umbrella (#10301)

- FirebaseAuth/Sources/MultiFactor/FIRMultiFactor.m
- FirebaseAuth/Sources/MultiFactor/FIRMultiFactorInfo+Internal.h
- FirebaseAuth/Sources/MultiFactor/Phone/FIRPhoneMultiFactorInfo.m
Fix a bug where multi factor phone number returns NULL.
> Persist FIRPhoneMultiFactorInfo (instead of FIRMultiFactorInfo) so that full phone number is always cached

- FirebaseDatabase/Sources/third_party/SocketRocket/FSRWebSocket.m
> Fixed unused warnings building in release config

- FirebaseCoreExtension.podspec
- FirebaseFirestoreSwift.podspec
- Package.swift
> [Firebase 10] Cherry-pick `FirebaseFirestoreSwift` build fix into release branch

- .github/workflows/abtesting.yml
- .github/workflows/auth.yml
- .github/workflows/crashlytics.yml
- .github/workflows/database.yml
- .github/workflows/functions.yml
- .github/workflows/messaging.yml
- .github/workflows/remoteconfig.yml
- .github/workflows/shared-swift.yml
- .github/workflows/storage.yml
- scripts/build.sh
- Addresses https://github.com/firebase/firebase-ios-sdk/pull/10321#pullrequestreview-1134970685
> [Firebase 10] Cherry-pick CI fixes into release branch

- Carthage.md
See discussion in #10251
#no-changelog
> Fix Carthage installation directory in instructions

- .github/workflows/zip.yml
> Workaround Xcode 14 CocoaPods Resource build issue

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Carthage] Update Carthage artifacts for Firebase 10

- FirebaseCore/Sources/FIRApp.m
[Sessions] Update Sessions User Agent for Optimization
> [Sessions] Update Sessions User Agent for Optimization

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Source/API/FIRFirestore+Internal.h
- Firestore/core/CMakeLists.txt
- Firestore/core/src/core/composite_filter.cc
- Firestore/core/src/core/composite_filter.h
- Firestore/core/src/core/field_filter.cc
- Firestore/core/src/core/query.cc
- Firestore/core/src/core/query.h
- Firestore/core/src/core/target.h
- Firestore/core/src/local/index_backfiller.cc
- Firestore/core/src/local/index_manager.h
- Firestore/core/src/local/leveldb_index_manager.cc
- Firestore/core/src/local/leveldb_index_manager.h
- Firestore/core/src/local/memory_index_manager.cc
- Firestore/core/src/local/memory_index_manager.h
- Firestore/core/src/local/query_engine.cc
- Firestore/core/src/local/query_engine.h
- Firestore/core/src/remote/serializer.cc
- Firestore/core/src/util/logic_utils.cc
- Firestore/core/src/util/logic_utils.h
- Firestore/core/test/unit/core/filter_test.cc
- Firestore/core/test/unit/core/query_test.cc
- Firestore/core/test/unit/local/leveldb_index_manager_test.cc
- Firestore/core/test/unit/local/query_engine_test.cc
- Firestore/core/test/unit/remote/serializer_test.cc
- Firestore/core/test/unit/util/logic_utils_test.cc
> Support DNF transform for Or Query Support

- Firestore/core/src/core/composite_filter.cc
- Firestore/core/src/core/composite_filter.h
- Firestore/core/src/util/logic_utils.cc
> Change the parameter of WithAddedFilters function

- Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
- Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
- Firestore/core/src/core/query.cc
- Firestore/core/src/core/target.h
- Firestore/core/src/local/index_manager.h
- Firestore/core/src/local/leveldb_index_manager.cc
- Firestore/core/src/local/leveldb_index_manager.h
- Firestore/core/src/local/memory_index_manager.cc
- Firestore/core/src/local/memory_index_manager.h
- Firestore/core/test/unit/local/leveldb_index_manager_test.cc
- Firestore/core/test/unit/local/leveldb_query_engine_test.cc
- Firestore/core/test/unit/local/query_engine_test.cc
> Update Limit and OrderBy filtering mechanism for Or Query

- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Sources/StorageReference.swift
- FirebaseStorage/Tests/Integration/Credentials.swift
- FirebaseStorage/Tests/ObjCIntegration/FIRStorageIntegrationTests.m
> Fixed issue where metadata wasn't properly initialized

- FirebaseAuth/CHANGELOG.md
Updated the changelog for the Firebase 10.1.0 (M123) release.
> Update CHANGELOG for Firebase 10.1.0 (M123)

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
Analytics 10.1.0 #no-changelog
> Analytics 10.1.0

- ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift
Remove the -fembed-bitcode-marker compiling flag.
> Remove the bitcode compiling flag.

- FirebaseSessions/ProtoSupport/Protos/sessions.options
- FirebaseSessions/ProtoSupport/Protos/sessions.proto
- FirebaseSessions/Protogen/nanopb/sessions.nanopb.c
- FirebaseSessions/Protogen/nanopb/sessions.nanopb.h
- FirebaseSessions/Sources/SessionStartEvent.swift
Updates the proto to match the backend
#no-changelog
> [Sessions] Update Sessions proto with newest changes

- Firestore/core/src/bundle/bundle_serializer.cc
- Firestore/core/src/bundle/bundle_serializer.h
- Firestore/core/src/core/core_fwd.h
- Firestore/core/src/core/filter.h
- Firestore/core/src/core/query.cc
- Firestore/core/src/core/query.h
- Firestore/core/src/core/target.h
- Firestore/core/src/local/leveldb_index_manager.cc
- Firestore/core/src/remote/serializer.cc
- Firestore/core/src/remote/serializer.h
- Firestore/core/test/unit/core/query_test.cc
- Firestore/core/test/unit/remote/serializer_test.cc
> Replace FilterList with std::vector<Filter> for future maintenance

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
> Update project file

- Firestore/core/src/core/composite_filter.h
- Firestore/core/src/core/field_filter.cc
- Firestore/core/src/core/field_filter.h
- Firestore/core/src/core/filter.h
- Firestore/core/src/local/leveldb_index_manager.cc
- Firestore/core/src/remote/serializer.cc
- Firestore/core/src/util/logic_utils.cc
> Support GetFilters() in core::Filter

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Carthage] Update Carthage artifacts for Firebase 10.1.0

- FirebaseStorage/CHANGELOG.md
- FirebaseStorage/Sources/StorageReference.swift
Fix occasional nightly regression on storage tests in #10358
> Fix a race condition where a download size could exceed maxSize

- FirebaseSessions/Sources/ApplicationInfo.swift
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.h
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.m
- FirebaseSessions/Sources/NetworkInfo.swift
- FirebaseSessions/Tests/Unit/ApplicationInfoTests.swift
- FirebaseSessions/Tests/Unit/Mocks/MockNetworkInfo.swift
> [Sessions] Add NetworkInfo abstraction over CoreTelephony helpers

- FirebaseSessions/README.md
Adds development instructions
#no-changelog
> [Sessions] Update README with development procedures

- .github/workflows/generate_issues.yml
Address https://github.com/firebase/firebase-ios-sdk/issues/10358#issuecomment-1300230520
> Exclude sessions integration tests from nightly report

- Firestore/core/src/local/leveldb_index_manager.cc
- Firestore/core/src/util/logic_utils.cc
- Firestore/core/src/util/logic_utils.h
- Firestore/core/test/unit/local/leveldb_query_engine_test.cc
- Firestore/core/test/unit/local/query_engine_test.cc
- Firestore/core/test/unit/util/logic_utils_test.cc
> Performing IN expansion

- scripts/nanopb/nanopb_objc_generator.py
- scripts/nanopb/proto_generator.py
Follow up from https://github.com/firebase/firebase-ios-sdk/pull/10439
Validated this works by re-running generators and ensuring there's no changes.
> Format nanopb generator scripts

- FirebaseRemoteConfig/Sources/RCNConfigFetch.m
> [RemoteConfig] Expose NSUnderlyingError to client

- FirebaseSessions/Sources/ApplicationInfo.swift
- FirebaseSessions/Sources/Development/DevEventConsoleLogger.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/ApplicationInfoTests.swift
- FirebaseSessions/Tests/Unit/Mocks/MockApplicationInfo.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
This is a replacement to the PR #10456 because of the state it got into.
#no-changelog
> Apply development environment to the Protos.

- CONTRIBUTING.md
> Improve swiftformat usage docs

- FirebaseStorage/CHANGELOG.md
> Improve Storage Changelog for 10492

- FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
- FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h
- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
Update Realtime exceptions to the ones specified in this doc: [go/realtime-rc-sdk-exceptions](http://goto.google.com/realtime-rc-sdk-exceptions)
> Replace old realtime exceptions with new exceptions

- SymbolCollisionTest/Podfile
Fix Symbol Collision nightly failure in #10497
> Ensure recent GSI in Symbol Collision test

- FirebaseSessions.podspec
- FirebaseSessions/Sources/ApplicationInfo.swift
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.h
- FirebaseSessions/Sources/NanoPB/FIRSESNanoPBHelpers.m
- FirebaseSessions/Sources/NetworkInfo.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/TestApp/Podfile.lock
- FirebaseSessions/Tests/Unit/Mocks/MockApplicationInfo.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
> Depend on Google Utlities for device platform + Add Model information to session events.

- .github/workflows/crashlytics.yml
- Crashlytics/Shared/FIRCLSNetworking/FIRCLSURLBuilder.m
- Crashlytics/UnitTests/FABURLBuilderTests.m
- Crashlytics/UnitTests/FIRCLSCompactUnwindTests.m
- Crashlytics/UnitTests/FIRCLSDwarfTests.m
- Crashlytics/UnitTests/FIRCLSInternalReportTests.m
- Crashlytics/UnitTests/FIRCLSMachO/FIRCLSMachOBinaryTests.m
- Crashlytics/UnitTests/FIRCLSMachO/FIRCLSMachOTests.m
- Crashlytics/UnitTests/FIRCLSMachO/FIRCLSdSYMTests.m
- Crashlytics/UnitTests/FIRCLSProcessReportOperationTests.m
- Crashlytics/UnitTests/FIRCLSReportAdapterTests.m
- Crashlytics/UnitTests/FIRCLSReportManagerTests.m
- Crashlytics/UnitTests/FIRCLSSymbolResolverTests.m
- Crashlytics/UnitTests/FIRCrashlyticsReportTests.m
- Package.swift
- scripts/spm_test_schemes/FirebaseCrashlyticsUnit.xcscheme
Right now Crashlytics doesn't support unit test from SPM, adding the Craslytics unit tests scheme in for SPM
Will run CI/CD to make sure nothing broken
#no-changelog
> [Crashlytics] Adding unit test scheme to SPM

- FirebaseRemoteConfig/Sources/Private/RCNConfigFetch.h
- FirebaseRemoteConfig/Sources/RCNConfigFetch.m
- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
- FirebaseRemoteConfig/Tests/Unit/RCNPersonalizationTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
- FirebaseRemoteConfigSwift/Tests/ObjC/FetchMocks.m
Implementation of [go/realtime-rc-fetch-id](http://goto.google.com/realtime-rc-fetch-id)
> Realtime RC Fetch ID

- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
> Add defaults for data collection state fields.

- FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h
- docs/FirebaseOptionsPerProduct.md
Update FIrebase Options API documentation and summarize usage of Options by Firebase product.
#no-changelog
> Firebase Options Documentation

- FirebaseSessions/ProtoSupport/Protos/sessions.proto
- FirebaseSessions/Protogen/nanopb/sessions.nanopb.c
- FirebaseSessions/Protogen/nanopb/sessions.nanopb.h
- FirebaseSessions/Sources/Development/DevEventConsoleLogger.swift
- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/FirebaseSessionsError.swift
- FirebaseSessions/Sources/SessionCoordinator.swift
- FirebaseSessions/Sources/SessionSampler.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/SessionCoordinatorTests.swift
- FirebaseSessions/Tests/Unit/SessionSamplerTests.swift
Implement sampling for session related events.
#no-changelog
> Introduce sampling to session events.

- .github/workflows/database.yml
Thanks to @sunmou99 for pointing out these were still disabled
#no-changelog
> Turn RTDB quickstart testing back on

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> Carthage 10.3

- FirebaseStorage/Sources/StorageDownloadTask.swift
> Two Storage Swift porting typos

- FirebaseSessions/Sources/SessionLocalConfig.swift
- FirebaseSessions/Tests/Unit/Mocks/MockSessionLocalConfig.swift
Note: There are no tests here yet since everything depends on Bundle and there is no point testing them yet.
Next PR would be about integrating the local config overrides with Settings layer and at that time tests will be introduced.
#no-changelog
> Introduce LocalConfigOverrides for settings.

- FirebaseStorage/Tests/Integration/StorageIntegration.swift
The pause and resume tests were never ported from Objective C to Swift. Here they are ...
#no-changelog
> Add Pause/resume swift integration tests

- FirebaseAppDistribution/Sources/Public/FirebaseAppDistribution/FIRAppDistribution.h
- FirebaseAppDistributionInternal/Sources/InAppFeedback.swift
Add missing method to the public header and fix a build error.
#nochangelog
> Update method documentation and fix a build error

- FirebaseAuth/Sources/Public/FirebaseAuth/FIRFederatedAuthProvider.h
- FirebaseCombineSwift/Sources/Auth/OAuthProvider+Combine.swift
Fix typo
Thanks to @frboulais for pointing this out in  #9820
> Fix Auth API docs typo

- FirebaseAuth/Sources/Auth/FIRAuth.m
> Another typo

- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/SessionInitiator.swift
- FirebaseSessions/Tests/Unit/InitiatorTests.swift
Pending: Applying sampling rate. Reason: Requires a bit of refactor before applying, so will do in a separate PR.
#no-changelog
> Apply the Configs Settings to the SDK

- FirebaseAuth/Sources/MultiFactor/FIRMultiFactor.m
- FirebaseAuth/Sources/User/FIRUser.m
> Fix secure coding bugs in MFA

- .allstar/binary_artifacts.yaml
Fix #10577
Update after #10634 moved these binary files.
> Update allstar ignore paths after recent directory structure

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 10.4.0 #no-changelog
> Analytics 10.4.0

- FirebaseAuth/CHANGELOG.md
Add two external contributions to CHANGELOG.
> FirebaseAuth changelog update for 10.4.0

- Crashlytics/CHANGELOG.md
- Firestore/CHANGELOG.md
> [Release] Update CHANGELOGs for 10.4.0 release

- .github/workflows/storage.yml
> Don't trigger Storage CI on scripts changes

- .github/workflows/sessions-integration-tests.yml
- scripts/build.sh
> Enable events to be generated for Autopush and Staging environments.

- FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m
> Fix misplaced return after error

- FirebaseAppDistribution.podspec
- Package.swift
> Remove unused dependency

- Firestore/Swift/Source/Codable/CollectionReference+WriteEncodable.swift
> Add `@discardableResult` to `addDocument`

- FirebaseRemoteConfig/Sources/FIRRemoteConfigUpdate.m
- FirebaseRemoteConfig/Sources/Private/FIRRemoteConfig_Private.h
- FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h
- FirebaseRemoteConfig/Sources/RCNConfigContent.m
- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
- FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
To align with current API naming
> Rename updatedParams to updatedKeys

- FirebaseSessions/Tests/TestApp/AppQualityDevApp.xcodeproj/project.pbxproj
- FirebaseSessions/Tests/TestApp/Shared/AppQualityDevAppApp.swift
- FirebaseSessions/Tests/TestApp/Shared/MockSubscriberSDK.swift
Adds a fake subscriber SDKs to our test app with data collection enabled
> Fix Sessions Test App with Fake Subscriber

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Release] Carthage artifacts for 10.4.0 / M126

- FirebasePerformance/Sources/FPRClient+Private.h
- FirebasePerformance/Sources/FPRClient.m
- FirebasePerformance/Tests/Unit/FPRClientTest.m
#no-changelog
Initialize Firebase Performance using Component system. This is a precursor to Sessions Library Integration.
> Make Firebase Performance initialize using Component system.

- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
> Update Realtime RC service URL.

- FirebaseCore/CHANGELOG.md
- FirebaseCore/Extension/FIROptionsInternal.h
- FirebaseCore/Sources/FIROptions.m
> Remove unused methods in FIROptions

- FirebaseSessions/Tests/TestApp/AppQualityDevApp.xcodeproj/xcshareddata/xcschemes/AppQualityDevApp_iOS.xcscheme
- FirebaseSessions/Tests/TestApp/AppQualityDevApp.xcodeproj/xcshareddata/xcschemes/UITests_iOS.xcscheme
- FirebaseSessions/Tests/TestApp/UITestsiOS/UITestsiOS.swift
- scripts/build.sh
> Propagate log environment variable to unit tests for the app.

- FirebaseInstallations/Source/Tests/Utils/FIRTestKeychain.m
Fix warning that caused FIS spec to fail linting in nightly CI.
Fixes #10725
#no-changelog
> [Infra] Ignore deprecations in test utility

- FirebaseAuth/Sources/Public/FirebaseAuth/FirebaseAuth.h
- FirebaseAuth/Sources/Swift/Storage/AuthKeychainServices.swift
- FirebaseAuth/Sources/Swift/Storage/AuthUserDefaults.swift
- FirebaseAuth/Tests/Unit/FIRAuthUserDefaultsTests.m
Fix style - primarily indentation
Fix warnings - missing header in umbrella and `outError` in doc comments
> Fix build warnings and style

- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
> Prevent capturing of Network Info unless Perf is installed

- .github/workflows/check.yml
- .github/workflows/firestore.yml
- .github/workflows/update-cpp-sdk-on-release.yml
> Address GHA deprecation warnings

- FirebaseSessions/ProtoSupport/Protos/sessions.options
- FirebaseSessions/ProtoSupport/Protos/sessions.proto
- FirebaseSessions/Sources/Development/DevEventConsoleLogger.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/SourcesObjC/Protogen/nanopb/sessions.nanopb.c
- FirebaseSessions/SourcesObjC/Protogen/nanopb/sessions.nanopb.h
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
- Does not implement new fields yet
#no-changelog
> Remove previous_session_id in favor of first_session_id and session_index

- FirebaseMessaging/CHANGELOG.md
- FirebasePerformance/CHANGELOG.md
- Firestore/CHANGELOG.md
Please make sure to add a unrelease changelog when you make a publicly visible change.
> update missing changelog

- FirebaseAppCheck/Sources/Core/FIRAppCheck.m
This PR is *almost* worthless but hey, I was in there and saw it and the github web PR ui is a pretty quick flow, so here's a typo fix
Yes, I ignored the template for PRs, apologies in advance, however if you simply click on "file changes" and check the diff that's faster than reading anything else I would type in here.
Cheers :-)
> Fix typo in error message

- FirebaseSessions/Sources/SessionGenerator.swift
- FirebaseSessions/Sources/SessionStartEvent.swift
- FirebaseSessions/Tests/Unit/SessionCoordinatorTests.swift
- FirebaseSessions/Tests/Unit/SessionGeneratorTests.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
Follow up from https://github.com/firebase/firebase-ios-sdk/pull/10762
#no-changelog
> Update SessionGenerator for first_session_id, session_index

- FirebaseCombineSwift/Tests/Unit/Auth/GameCenterAuthProviderTests.swift
- FirebaseCombineSwift/Tests/Unit/Auth/SignInWithGameCenterTests.swift
Fixed build and disabled test failures resulting from #10441 
Opened #10767 to track restoration of disabled tests.
Fix #10758
> Fix build and disable broken Game Center Combine tests

- FirebaseAuth/Sources/Backend/RPC/FIRSignInWithGameCenterResponse.h
> Fix breif typo

- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/SessionGenerator.swift
- FirebaseSessions/Tests/Unit/Library/FirebaseSessionsTestsBase.swift
- FirebaseSessions/Tests/Unit/SessionGeneratorTests.swift
> Update sampling to calculate per-run-of-app instead of per-session

- FirebaseSessions/README.md
- FirebaseSessions/Sources/Settings/LocalOverrideSettings.swift
> Add comments outlining the worries against using FirebaseSessionsEnabled

- FirebaseRemoteConfig/Sources/RCNConfigFetch.m
> Make FetchType header capitalized to match backend 

- CoreOnly/Tests/FirebasePodTest/Podfile
> Add FirebaseSessions to FirebasePodTest

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h
> Fix verifying typo

- FirebaseSessions/Sources/Settings/SessionsSettings.swift
- FirebaseSessions/Tests/Unit/SessionsSettingsTests.swift
Seeing customers using it - disabling for now.
> Disable Sessions due to usage

- FirebaseSessions/Sources/Development/NanoPB+CustomStringConvertible.swift
Fixes: https://github.com/firebase/firebase-ios-sdk/issues/10793
#no-changelog
> Fix Sessions on Xcode 13

- FirebaseSessions/Tests/TestApp/AppQualityDevApp-iOS-Info.plist
- FirebaseSessions/Tests/TestApp/AppQualityDevApp-macOS-Info.plist
- FirebaseSessions/Tests/TestApp/AppQualityDevApp.xcodeproj/project.pbxproj
Disabled in https://github.com/firebase/firebase-ios-sdk/pull/10796, need the testapp to continue working
> Turn on Firebase Sessions Test App while SDK disabled

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
- FirebaseAuth/Sources/Swift/Backend/AuthRequestConfiguration.swift
- FirebaseAuth/Sources/User/FIRUser.m
- Package.swift
> [auth-swift] Re-enable logging code (pt. 1)

- FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- FirebaseAuth/Tests/Unit/FIRAuthTests.m
- FirebaseAuth/Tests/Unit/FakeBackendRPCIssuer.swift
Tweak the fake infra a bit to support replacing the mock tests in FIRAuthTests.m and implemented the first two tests.
> [auth-swift] First mock replacements

- FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
- FirebaseCore/Extension/FIRHeartbeatLogger.h
Follow-up to #10817 
#no-changelog
> [auth-swift] Re-enable logging code (pt. 2)

- FirebaseAuth/Sources/Swift/Storage/AuthKeychainServices.swift
- FirebaseAuth/Tests/Unit/FIRAuthKeychainServicesTests.m
> [auth-swift] Get 'FIRAuthKeychainServicesTests.m' tests passing

- FirebaseAuth/Sources/Swift/Storage/AuthKeychainServices.swift
> [auth-swift] Resolve TODO by with 'FirebaseLogger' usage

- FirebaseAuth/Tests/Unit/AuthTests.swift
Follow up to #10820 with comments describing test flow
> [auth-swift] Document flow in mock replacement test using fake

- FirebaseAuth/Tests/Unit/AuthTests.swift
> [auth-swift] Fix test name

- FirebaseSessions/Sources/Settings/SessionsSettings.swift
- FirebaseSessions/Tests/Unit/SessionsSettingsTests.swift
Reverts firebase/firebase-ios-sdk#10796
> Revert "Disable Sessions due to usage"

- FirebaseSessions/Tests/TestApp/AppQualityDevApp-iOS-Info.plist
- FirebaseSessions/Tests/TestApp/AppQualityDevApp-macOS-Info.plist
- FirebaseSessions/Tests/TestApp/AppQualityDevApp.xcodeproj/project.pbxproj
Reverts firebase/firebase-ios-sdk#10811
> Revert "Turn on Firebase Sessions Test App while SDK disabled"

- Firestore/core/src/remote/bloom_filter.cpp
- Firestore/core/src/remote/bloom_filter.h
#no-changelog
create bloom_filter.h file
> Create bloom filter class header filer

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 10.6.0 #no-changelog
> Analytics 10.6.0

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
Updated the Carthage project specification JSON files for the Firebase 10.6.0 / M128 release.
<details>
<summary>Cartfile</summary>
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseABTestingBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAdMobBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppCheckBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAppDistributionBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDatabase …
```
> [Release] Carthage artifacts for 10.6.0 / M128

- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
- FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m
- FirebaseRemoteConfigSwift/Tests/SwiftAPI/APITests.swift
> Add tests and sampleApp changes for updatedKeys

- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatStorage.swift
> [FirebaseCore] Use optional instead of error

- FirebaseAppDistributionInternal/Sources/AppDistributionApiService.swift
- FirebaseAppDistributionInternal/Tests/Unit/AppDistributionApiServiceTests.swift
- FirebaseAppDistributionInternal/Tests/Unit/FakeUtils/URLSessionPartialMock.swift
> Refactor methods that handle API responses

- FirebaseAppDistributionInternal/Sources/AppDistributionApiService.swift
- FirebaseAppDistributionInternal/Tests/Unit/AppDistributionApiServiceTests.swift
> Fix parameter in createFeedback completion

- FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
- FirebaseAppDistributionInternal/Sources/InAppFeedback.swift
> Fix params for screenshot methods

- FirebaseAppDistributionInternal/Sources/ApiService.swift
> Fix ApiService

- FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h
> Change doc references to hyphenate real-time

- FirebaseAppDistribution/Sources/FIRAppDistribution.m
- FirebaseAppDistributionInternal/Resources/AppDistributionInternalStoryboard.storyboard
- FirebaseAppDistributionInternal/Sources/ApiService.swift
- FirebaseAppDistributionInternal/Sources/FeedbackViewController.swift
> Add API calls for creating feedback

- Crashlytics/CHANGELOG.md
- FirebaseAuth/CHANGELOG.md
- FirebaseStorage/CHANGELOG.md
- Firestore/CHANGELOG.md
> [v10.7.0] Update changelogs for release

- FirebaseAppDistribution/Sources/FIRAppDistribution.m
- FirebaseAppDistributionInternal/Sources/ApiService.swift
> Fix call to FindRelease endpoint

- CONTRIBUTING.md
- Crashlytics/Crashlytics/Helpers/FIRCLSDefines.h
- Crashlytics/Shared/FIRCLSMachO/FIRCLSCodeMapping.m
- Crashlytics/UnitTests/FIRCLSDwarfExpressionTests.m
- FirebaseDatabase/Tests/Helpers/SenTest+FWaiter.h
- FirebaseDatabase/Tests/Integration/FData.m
- FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m
- FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/FRCLog.h
- FirebaseRemoteConfig/Tests/Unit/RCNConfigAnalyticsTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfig+FIRAppTest.m
- Firestore/Source/API/FSTUserDataWriter.h
- README.md
- scripts/setup_check.sh
- scripts/style.sh
Cherry-pick clang-format PR to auth-swift branch, since we're not at a good spot to rebase.
> [Infra] Upgrade to clang-format16 (#10973)

- FirebaseAuth/Sources/Swift/Storage/AuthKeychainServices.swift
- FirebaseAuth/Tests/Unit/AuthKeychainServicesTests.swift
- Reduce visibility of a private helper
- See comment for https://github.com/firebase/firebase-ios-sdk/commit/920e8d4c311277242e40f5a349d40c38fb84f68c
#no-changelog
> [auth-swift] Prep for keychain dependency injection (pt. 2)

- FirebaseAppDistributionInternal/README.md
- FirebaseAppDistributionInternal/Resources/AppDistributionInternalStoryboard.storyboard
- FirebaseAppDistributionInternal/Sources/ApiService.swift
- FirebaseAppDistributionInternal/Sources/FeedbackViewController.swift
> Export new API changes in AppDistributionInternal to `master`

- FirebaseAuth/Sources/Auth/FIRAuth.m
- Update internal auth initializer to accept keychain instances.  
- Remove unused `firebaseAppId` ivar.
- Eleven thousandth PR! 🎉 
#no-changelog
> [auth-swift] Update initializer to accept keychain storage types

- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- FirebaseAuth/Tests/Unit/VerifyAssertionTests.swift
> Objective C property functions should be Swift computed properties

- FirebaseAppDistributionInternal/Sources/InAppFeedback.swift
> Fix screenshot delay bug

- FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Sources/Swift/Backend/AuthRequestConfiguration.swift
- FirebaseAuth/Sources/Swift/Backend/IdentityToolkitRequest.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/SecureTokenRequest.swift
- FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/AuthBackendRPCImplentationTests.swift
- FirebaseAuth/Tests/Unit/RPCBaseTests.swift
> [auth-swift] User decoding and api cleanup

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/MultiFactor/FIRMultiFactor+Internal.h
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRMultiFactor.h
- FirebaseAuth/Sources/Swift/Backend/RPC/GetAccountInfoResponse.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- FirebaseAuth/Tests/Unit/DeleteAccountTests.swift
- FirebaseAuth/Tests/Unit/FakeBackendRPCIssuer.swift
- FirebaseAuth/Tests/Unit/GetOOBConfirmationCode.swift
- FirebaseAuth/Tests/Unit/RPCBaseTests.swift
- FirebaseAuth/Tests/Unit/SecureTokenTests.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
First several UserTests.swift tests.
#no-changelog
> [auth-swift] UserTests.swift Part 1

- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Sources/Swift/User/UserProfileChangeRequest.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
UserProfileChangeRequest.swift implementation and unit tests
#no-changelog
> [auth-swift] UserProfileChangeRequest.swift

- FirebaseAuth/Sources/Swift/Auth/AuthTokenResult.swift
- FirebaseAuth/Tests/Unit/FakeBackendRPCIssuer.swift
- FirebaseAuth/Tests/Unit/RPCBaseTests.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
> [auth-swift] GetIDTokenResult unit tests

- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/FIRUserTests.m
- FirebaseAuth/Tests/Unit/UserTests.swift
> [auth-swift] User reload() unit tests and fix

- Crashlytics/UnitTests/FIRCLSReportManagerTests.m
- Same approach as in #11021 
- Fix #11028
#no-changelog
> [Infra] Add tear down logic in set up code

- FirebaseAuth.podspec
- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Auth/FIRAuth_Internal.h
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h
- FirebaseAuth/Sources/Swift/Storage/AuthKeychainServices.swift
- FirebaseAuth/Sources/Swift/Storage/AuthStorage.swift
- FirebaseAuth/Sources/Swift/Storage/AuthUserDefaults.swift
- FirebaseAuth/Tests/Unit/AuthKeychainServicesTests.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- FirebaseAuth/Tests/Unit/Fakes/FakeAuthKeychainServices.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
- Final PR in a series of PRs meant to make Auth accept a fake keychain instance.
#no-changelog
> [auth-swift] Finish Auth refactoring to allow for injecting fake keychain instance for macOS tests

- FirebaseCombineSwift/Sources/Firestore/DocumentReference+Combine.swift
> Use caller's encoder when seting document data

- FirebaseCombineSwift/CHANGELOG.md
> [Release] Update CHANGELOG entry following #11034

- FirebaseCore/Sources/FIRApp.m
> [FirebaseCore] Add comment to notify future-us about potential side effects of code change

- Crashlytics/Crashlytics/Components/FIRCLSCrashedMarkerFile.c
- Crashlytics/Crashlytics/Components/FIRCLSHost.m
- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Auth/FIRAuthGlobalWorkQueue.m
- FirebaseAuth/Tests/Unit/FIRAuthBackendRPCImplementationTests.m
- FirebaseCore/CHANGELOG.md
- FirebaseDatabaseSwift/Sources/Codable/DataSnapshot+ReadDecodable.swift
- FirebaseDatabaseSwift/Sources/Codable/DatabaseReference+WriteEncodable.swift
- FirebaseMessaging/Sources/FIRMessagingUtilities.m
- Firestore/core/include/firebase/firestore/timestamp.h
> Address Xcode 14.3 build warnings and a few typos

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 10.8.0 #no-changelog
> Analytics 10.8.0

- FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m
Fixes tests on rebase branch.
#no-changelog
> [auth-swift] Fix test by using DataWrapper API

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> Carthage json updates for 10.8.0

- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthURLPresenter.swift
- FirebaseAuth/Tests/Unit/AuthURLPresenterTests.swift
- FirebaseAuth/Tests/Unit/FIRPhoneAuthProviderTests.m
- FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift
- FirebaseAuth/Tests/Unit/OAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
> [auth-swift] Checkpoint after first Phone Auth Recaptcha unit test

- FirebaseCore/CHANGELOG.md
- Package.swift
1. git checkout master
2. git fetch
3. git checkout 10.8.0 
4. git checkout -b release-10.8  
5. git push origin HEAD
6. git checkout -b nc/10.8.1-patch
7. git cherry-pick 3bd6364152431e532a78b304a23a1228100878a7 # Commit from '#11121'
8. Update `Package.swift`'s package version
9. git add; git commit -m "[Release] Bump package version in Package.swift"
10. git push origin HEAD
After this merges, I plan to:
1. git checkout release-10.8
2. Sync my local `release-10.8`
3. git tag 10.8.1
4. git push origin 10.8.1
> [Release] Cherry-pick changes for SPM-only 10.8.1 patch release

- FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m
> Update for proposed g3 ocmock changes

- FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift
- FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
Simplify some of the test synchronization and other minor cleanups.
#no-changelog
> [auth-swift] Some unit test cleanup

- FirebaseAnalyticsSwift/Tests/SwiftUnit/AnalyticsAPITests.swift
- Package.swift
- scripts/spm_test_schemes/AnalyticsSwiftUnit.xcscheme
Run these tests in both CocoaPods and SPM and add build coverage tests for Analytics Swift APIs
> Add AnalyticsSwiftUnit tests to SPM

- Crashlytics/CHANGELOG.md
> fix change log

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 10.9.0 #no-changelog
> Analytics 10.9.0

- Gemfile
- Gemfile.lock
> CocoaPods 1.12.1

- Package.swift
> [Release] Update Package.swift for 10.9.0 release (RC2)

- FirebaseSessions/Sources/SessionCoordinator.swift
- FirebaseSessions/Tests/Unit/SessionCoordinatorTests.swift
The purpose of this is to make it consistent with Android and so we can catch issues where the FIID lookup failed
#no-changelog
> Update Sessions to send events when FIID empty

- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift
- FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/RPCBaseTests.swift
- FirebaseAuth/Tests/Unit/SendVerificationCodeTests.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
> [auth-swift] Seven PhoneAuth related tests in UserTests.swift

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Release] Update Carthage artifacts for Firebase 10.9.0

- ReleaseTooling/Template/README.md
> [Release] Update Zip Disribution README.md

- docs/AddNewProduct.md
> Fix link on AddNewProduct.md

- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheck.h
> fix undocumented appcheck

- .github/workflows/storage.yml
> Fix action leak

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/Auth/AuthComponent.swift
Fix retain cycle caught by `FIRAuthLifeCycleTests testLifeCycle`
> Fix Component system retain cycle

- Crashlytics/CHANGELOG.md
Updated the CHANGELOG entry for Crashlytics
> Update CHANGELOGs for M132 (10.10.0)

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 10.10.0 #no-changelog
> Analytics 10.10.0

- FirebaseAppCheck/Sources/Core/FIRAppCheck.m
Potential fix for discussion in [PR #11270](https://github.com/firebase/firebase-ios-sdk/pull/11270#discussion_r1195678029).
#no-changelog
> [App Check] Always return fresh limitedUseToken

- FirebaseAppCheck/Interop/FIRAppCheckInterop.h
- FirebaseAppCheck/Sources/Core/FIRAppCheck.m
- FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheck.h
- Package.swift
- SharedTestUtilities/AppCheckFake/FIRAppCheckFake.h
- SharedTestUtilities/AppCheckFake/FIRAppCheckFake.m
Merged `FirebaseAppCheck` changes from PRs #11224 and #11270. Will need to manually integrate these changes into the generic `AppCheck` directory in a follow-up PR.
#no-changelog
> [App Check] Merge latest FirebaseAppCheck changes from master

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Release] Update Carthage artifacts for Firebase 10.10.0

- Firestore/CHANGELOG.md
- Firestore/core/src/remote/remote_objc_bridge.cc
> Safe cast for number of aggregations to fix compilation warning.

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
More AuthTests.swift along with two Auth.swift bug fixes the new tests found
> More AuthTests.swift implementation

- Firestore/core/src/api/query_core.h
A minor typo fix that i stumbled upon.
> Typo fix: query_core.h

- FirebaseAuth/Tests/Sample/Sample/UIViewController+Alerts.h
> Typo fix: UIViewController+Alerts.h

- FirebasePerformance/CHANGELOG.md
- FirebasePerformance/Sources/FIRPerformance.m
Internal reference bug b/241759285.
> Fixed a bug to honor data collection flags before Firebase app was configured.

- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift
> [auth-swift] Rest of token refresh unit tests

- FirebaseAuth/Tests/Sample/Sample/MainViewController+Email.m
- FirebaseAuth/Tests/Sample/Sample/MainViewController+MultiFactor.m
This is an updated PR of #11226.
> Add totp sign in example to sample app

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/Auth/AuthComponent.swift
- FirebaseAuth/Tests/Unit/AuthTests.swift
- Application Delegate tests
- Interop tests
- `appWillBeDeleted` implementation for ComponentLifecycleMaintainer conformance
- keychainServiceNameForAppName implementation
- progress on `protectedDataInitialization`
- UIApplicationDelegate method implementations
> [auth-swift] More Auth.swift and AuthTests.swift

- FirebaseAuth/Sources/Backend/FIRAuthBackend.m
- FirebaseAuth/Sources/MultiFactor/FIRMultiFactor.m
- FirebaseAuth/Tests/Sample/Sample/MainViewController+Email.m
- FirebaseAuth/Tests/Sample/Sample/MainViewController+Google.m
- FirebaseAuth/Tests/Sample/Sample/MainViewController+Internal.h
- FirebaseAuth/Tests/Sample/Sample/MainViewController.m
If TOTP MFA enrolled, add specific totpMfaInfo in the error list when sign-in with the following first factors -
- Any provider
- Sign in with email link
- reauthentication
Updated the sample app to reflect the changes.
> provide missing TOTP factor type of error in the error code

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 10.11.0 #no-changelog
> Analytics 10.11.0

- FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.m
Updated the error msg to be more generic regardless of which MFA factor, it throws the same error msg.
> updated invalid verification code error msg

- Package.swift
Fix Package.swift warning (oversight from #11337)
> Update Package.swift for Firestore/Swift/README removal

- Package.swift
> Firestore 10.11.0 spm update

- FirebaseAuth/Sources/Public/FirebaseAuth/FIRMultiFactor.h
- FirebaseAuth/Sources/Swift/Backend/RPC/GetAccountInfoResponse.swift
- FirebaseAuth/Sources/Swift/MultiFactor/MultiFactorInfo.swift
- FirebaseAuth/Sources/Swift/MultiFactor/Phone/PhoneMultiFactorAssertion.swift
- FirebaseAuth/Sources/Swift/MultiFactor/Phone/PhoneMultiFactorInfo.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
> [auth-swift] UserTests.swift progress

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> Carthage 10.11.0

- FirebaseAuth/Tests/Unit/FIRFinalizeMFAEnrollmentRequestTests.m
- FirebaseAuth/Tests/Unit/FIRFinalizeMFASignInRequestTests.m
- FirebaseAuth/Tests/Unit/FIRStartMFAEnrollmentRequestTests.m
Added unit tests for start and finalize MFA enrollment flows
> [Unit tests] TOTP Enrollment

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/Auth/AuthDataResult.swift
- FirebaseAuth/Sources/Swift/AuthProvider/EmailAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/GitHubAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthCredential.swift
- FirebaseAuth/Sources/Swift/AuthProvider/TwitterAuthProvider.swift
- FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift
- FirebaseAuth/Sources/Swift/MultiFactor/MultiFactorResolver.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/AdditionalUserInfoTests.swift
- FirebaseAuth/Tests/Unit/EmailAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/GitHubAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/PhoneAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/TwitterAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/UserTests.swift
- FirebaseAuth/Tests/Unit/VerifyPhoneNumberTests.swift
- associated type enum for PhoneAuthCredential
- Additional coding fixes and tests
> [auth-swift] associated type enum for PhoneAuthCredential

- FirebaseAuth/Sources/Swift/AuthProvider/FacebookAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/GameCenterAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/GoogleAuthProvider.swift
- FirebaseAuth/Sources/Swift/AuthProvider/OAuthCredential.swift
- FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthCredential.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/FacebookAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/GoogleAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/OAuthProviderTests.swift
- FirebaseAuth/Tests/Unit/SignInWithGameCenterTests.swift
> [auth-swift] Finish coding coverage and fixes

- Crashlytics/CHANGELOG.md
> Update language in CHANGELOG.md

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/AuthProvider/OAuth/FIROAuthProvider.m
- FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRFederatedAuthProvider.h
- FirebaseAuth/Sources/SystemService/FIRAuthAPNSTokenManager.m
- FirebaseAuth/Sources/SystemService/FIRAuthNotificationManager.m
- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Sources/Utilities/FIRAuthDefaultUIDelegate.m
- FirebaseAuth/Sources/Utilities/FIRAuthURLPresenter.h
- FirebaseAuth/Sources/Utilities/FIRAuthURLPresenter.m
- FirebaseAuth/Sources/Utilities/FIRAuthWebView.h
- FirebaseAuth/Sources/Utilities/FIRAuthWebView.m
- FirebaseAuth/Sources/Utilities/FIRAuthWebViewController.m
- FirebaseAuth/Tests/Unit/FIRAuthAPNSTokenManagerTests.m
- FirebaseAuth/Tests/Unit/FIRAuthURLPresenterTests.m
- FirebaseAuth/Tests/Unit/FIROAuthProviderTests.m
- FirebaseAuth/Tests/Unit/FIRPhoneAuthProviderTests.m
Fixed Firebase Auth SDK build issues for visionOS, along with corresponding unit test changes.
#no-changelog
> [Auth] Fix Firebase Auth build on visionOS

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 10.12.0
#no-changelog
Note: GoogleAppMeasurementOnDeviceConversion has no source changes
> Analytics 10.12.0

- Package.swift
Pending a [successful RC creation](https://github.com/firebase/firebase-ios-sdk/actions/runs/5425712267), I will update the Firestore checksum.
> [Release] Update Package.swift for 10.12.0  release

- .github/workflows/zip.yml
Experimenting to see if this diff's TODO is still relevant.
#no-changelog
> [Infra] Run 'zip / quickstart_framework_firestore' on Xcode 14

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift
> [auth-swift] Address a few todos

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Release] Update Carthage artifacts for Firebase 10.12.0

- FirebaseAuth/Sources/Public/FirebaseAuth/FIRMultiFactor.h
for constant FIRPhoneMultiFactorID and FIRTOTPMultiFactorID
#no-changelog
> Updating API reference for TOTP

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift
- FirebaseAuth/Sources/Swift/MultiFactor/MultiFactorResolver.swift
- FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift
- FirebaseAuth/Sources/Swift/User/User.swift
Second swath of transition to async/await internal APIs 
#no-changelog
> [auth-swift] async/await swath 2

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- Add function to wrap optional callbacks onto the main thread
- Add function to wrap async function call into synchronous API calls
- Verify swizzling setup works the same running unit tests here and on master
I was only able to come up with the second case for the no-parameter callback case. Any suggestions about how to handle parameters?
> [auth-swift] Helper functions for async await transition

- Firebase.podspec
- FirebaseInAppMessaging/CHANGELOG.md
> Fix FIAM Firebase.podspec tvos dependency spec

- SwiftDashboard.md
Update Swift Dashboard to indicate we have Property Wrapper support for Remote Config.
> Update Dashboard for RC property wrappers

- README.md
a few grammatical changes, like in line 263, 
changed Fore to for, 
and other small changes to fix grammar and make it more readable.
> fixed a few grammatical mistakes README.md

- FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
Create response object when necessary and return it instead of passing it into `postInternal`
#no-changelog
> Internal AuthBackend API improvement

- FirebaseAuth/Sources/MultiFactor/TOTP/FIRTOTPSecret.m
> shared application fix

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 10.13.0 #no-changelog
> Analytics 10.13.0

- FirebaseAuth/CHANGELOG.md
Added  changelog entries for Firebase Auth 10.13.0.
> [Auth] Add changelogs for 10.13.0

- ReleaseTooling/Sources/Utils/FileManager+Utils.swift
> [Release Tooling] File Utils timestamp should use 'yyyy'

- Package.swift
> [Docs] Update Package.swift docs

- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Public/FirebaseAuth/FIRAuth.h
- FirebaseAuth/Sources/Utilities/FIRAuthRecaptchaVerifier.h
- FirebaseAuth/Sources/Utilities/FIRAuthRecaptchaVerifier.m
A recent revert missed some TARGET_OS_XR -> TARGET_OX_VISION updates
> Update to TARGET_OS_VISION

- FirebaseDynamicLinks/CHANGELOG.md
- FirebaseDynamicLinks/Sources/FIRDLDefaultRetrievalProcessV2.h
- FirebaseDynamicLinks/Sources/FIRDLDefaultRetrievalProcessV2.m
- FirebaseDynamicLinks/Sources/FIRDLJavaScriptExecutor.m
- FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.h
- FirebaseDynamicLinks/Sources/FIRDynamicLinks.m
- FirebaseDynamicLinks/Tests/Unit/FIRDynamicLinksTest.m
> Refactoring method names.

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> Carthage 10.14.0

- FirebaseAuth/Tests/Unit/FIRAuthTests.m
The tests succeed without recapthca fallback triggered.
Fixed 2 places:
1. Set `enablementStatusForProvider:FIRAuthRecaptchaProviderPassword]).andReturn(NO);` so that the first call failed without recaptcha token.
2. reorder _mockBackend mock calls so that the second call succeed with recaptcha token.
> Fix recaptcha fall back tests

- Firestore/Example/Firestore.xcodeproj/project.pbxproj
- Firestore/Example/Tests/Util/FSTExceptionCatcher.h
- Firestore/Example/Tests/Util/FSTExceptionCatcher.m
- Firestore/Swift/Tests/BridgingHeader.h
- Firestore/Swift/Tests/Integration/AsyncAwaitIntegrationTests.swift
- scripts/sync_project.rb
> [Firestore] Add shared test utility to pod sources

- .github/workflows/client_app.yml
- FirebaseRemoteConfigSwift/Sources/FirebaseRemoteConfigSwift.swift
> [ConfigSwift] Only re-export the API that used to be in ConfigSwift

- .github/workflows/client_app.yml
> [Infra] Disable 'client_app / cocoapods' GHA job

- .github/workflows/firestore.yml
Fixes #11788
#no-changelog
cc: @wu-hui
> [Infra] Disable non-iOS tests that build Firestore from source via SPM

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Release] Carthage artifacts for 10.15.0 / M137

- FirebaseInAppMessaging/Swift/Tests/Unit/FirebaseInAppMessaging_APIBuildTests.swift
I added TODOs for where we can make improvements. I will circle back after merging our Swift extension SDKs and start tracking bugs for Firebase 11 improvements. 
#no-changelog
> [InAppMessaging] Add FIAM and FIAMSwift API build tests

- Firestore/CHANGELOG.md
> [Firestore] Add release note for #11815

- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckTests.m
> Enable `FIRAppCheckTests` on CI

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 10.16.0 #no-changelog
> Analytics 10.16.0

- FirebaseABTesting/CHANGELOG.md
Rolling this fix into 10.16.0 post codefreeze since we're doing a rc respin later today.
> Changelog update to 10.16.0

- Crashlytics/CHANGELOG.md
- FirebasePerformance/CHANGELOG.md
- FirebaseSessions/Sources/SessionStartEvent.swift
This is a regression of #11027. Fixes #11725.
> Fix a regression of a memory leak in Sessions.

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Release] Update Carthage artifacts for Firebase 10.16.0 / M138

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> Add visionOS to BUG_REPORT.yml

- .github/actions/notices_generation/Gemfile
- .github/actions/notices_generation/Gemfile.lock
- Gemfile
- Gemfile.lock
Fix #11897 
Context in https://github.com/CocoaPods/CocoaPods/issues/12081
> Lock activesupport because of 7.1 breaking change

- FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPSecret.swift
Swift implementation of #11554
> [auth-swift] Fix TOTP for building in extensions

- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Auth/FIRAuth_Internal.h
- FirebaseAuth/Sources/Backend/RPC/FIRSignUpNewUserRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRSignUpNewUserRequest.m
- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.h
- FirebaseAuth/Tests/Unit/FIRAuthTests.m
- FirebaseAuth/Tests/Unit/FIRSignUpNewUserRequestTests.m
- FirebaseAuth/Tests/Unit/FIRSignUpNewUserResponseTests.m
- FirebaseAuth/Tests/Unit/FIRUserTests.m
> Use sign up endpoint for link with email password

- FirebasePerformance/Sources/Instrumentation/UIKit/FPRUIViewControllerInstrument.m
- Package.swift
> [visionOS] Add support for Firebase Performance on visionOS

- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Auth/FIRAuth.m
- FirebaseAuth/Sources/Auth/FIRAuth_Internal.h
- FirebaseAuth/Sources/Backend/RPC/FIRSignUpNewUserRequest.h
- FirebaseAuth/Sources/Backend/RPC/FIRSignUpNewUserRequest.m
- FirebaseAuth/Sources/User/FIRUser.m
- FirebaseAuth/Sources/Utilities/FIRAuthErrorUtils.h
- FirebaseAuth/Tests/Unit/FIRAuthTests.m
- FirebaseAuth/Tests/Unit/FIRSignUpNewUserRequestTests.m
- FirebaseAuth/Tests/Unit/FIRSignUpNewUserResponseTests.m
- FirebaseAuth/Tests/Unit/FIRUserTests.m
Reverts firebase/firebase-ios-sdk#11925 since backend is not ready.
> Revert "Use sign up endpoint for link with email password"

- Firestore/Swift/Tests/Integration/QueryIntegrationTests.swift
This is the same as https://github.com/firebase/firebase-ios-sdk/pull/11826 for the Swift tests.
> Update OR query Swift tests.

- Package.swift
Taken from the nightly zip build.
#no-changelog
> [Release] Update Package.swift with 10.17.0 RC0 Firestore binary artifact

- FirebaseAuth/Tests/Unit/FIRUserTests.m
- FirebaseMessaging/CHANGELOG.md
> fix exisits typo

- .github/workflows/firestore.yml
> [Infra] Allow override for Firestore CI

- .github/workflows/firestore.yml
Reverts firebase/firebase-ios-sdk#11994
> Revert "[Infra] Allow override for Firestore CI"

- GoogleAppMeasurement.podspec
Analytics 10.17.0 RC1 #no-changelog
> Analytics 10.17.0 RC1

- Gemfile
- Gemfile.lock
> CocoaPods 1.14.0

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/Utilities/AuthWebUtils.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Models/AuthMenu.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AuthViewController.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExampleUITests/AuthenticationExampleUITests.swift
- FirebaseAuth/Tests/Unit/AuthWebUtilsTests.swift
- FirebaseAuth/Tests/Unit/SwiftAPI.swift
Swift implementation of #11619 
#no-changelog
> [auth-swift] Custom Auth Domains

- .github/workflows/client_app.yml
> [Infra] Post #11941 work

- Gemfile
- Gemfile.lock
> CocoaPods 1.14.2

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Carthage] Update Carthage artifacts for Firebase 10.17.0

- .github/workflows/core.yml
- .github/workflows/messaging.yml
- .github/workflows/storage.yml
visionOS does not yet work in CI. It was actually running these tests on macOS.
See discussion in #12028
> Undo non-working visionOS CI

- FirebaseAppCheck.podspec
- Package.swift
- ReleaseTooling/Sources/PodspecsTester/main.swift
> Update AppCheckCore dependency to 10.18.0

- FirebaseAppCheck/CHANGELOG.md
Added a CHANGELOG entry for https://github.com/firebase/firebase-ios-sdk/pull/12067.
> [App Check] Add CHANGELOG entry for 10.18.0

- Package.swift
> Update Firestore SPM binary for 10.18.0

- FirebaseAuth/Sources/Swift/AuthProvider/OAuthProvider.swift
- FirebaseAuth/Tests/Unit/SwiftAPI.swift
Reviewed in conjunction with the master PR #12091
#no-changelog
> [auth-swift] Mostly unified Swift API tests

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> Carthage updates for 10.18.0

- FirebasePerformance/Sources/FIRPerformance.m
> Make fire-perf config error message Swift-friendly

- ReleaseTooling/Sources/PrivacyKit/PrivacyManifest.swift
- ReleaseTooling/Sources/PrivacyManifestGenerator/PrivacyManifestWizard.swift
- ReleaseTooling/Sources/PrivacyManifestGenerator/PrivacyQuestionnaire.swift
- ReleaseTooling/Sources/PrivacyManifestGenerator/Questionnaire.swift
- ReleaseTooling/Sources/PrivacyManifestGenerator/main.swift
> [Release Tooling] xcprivacy generation tooling (2)

- FirebaseAuth/Sources/Public/FirebaseAuth/FIRUser.h
> Remove recommendation to use deprecated fetchSignInMethods

- Package.swift
> [Release] Update Firestore SPM binary for 10.19.0

- .github/workflows/abtesting.yml
- .github/workflows/crashlytics.yml
- .github/workflows/dynamiclinks.yml
- .github/workflows/functions.yml
- .github/workflows/installations.yml
- .github/workflows/messaging.yml
- .github/workflows/performance.yml
- .github/workflows/storage.yml
Updated FTL GitHub Action: https://github.com/FirebaseExtended/github-actions/pull/9
FTL Action needs update
Test passed: https://github.com/firebase/firebase-ios-sdk/actions/runs/7118599545/job/19381950469#step:9:20
> Update firebase test lab GitHub Action

- Package.swift
#no-changelog
Will revert this after tagging from `master`
> [SwiftPM] Update 'firebaseVersion' to 10.19.1

- Package.swift
This reverts commit c60c958e707c50a9cf8bcb7cfd7d51c566d726c5.
Now that 10.19.1 is released, switch version back to 10.20
> Revert "[SwiftPM] Update 'firebaseVersion' to 10.19.1 (#12195)"

- .github/workflows/messaging.yml
- scripts/build.sh
Workaround until #12205 is fixed
Fix #12197
> Disable flaky messaging integration test

- FirebaseRemoteConfig/Sources/RCNConfigConstants.h
My first pull request in RC!
Add a string constant as key of rollout metadata in fetch response
#no-changelog
> [Rollouts]Add a rollout metadata constant

- FirebaseAuth/Sources/Swift/Auth/Auth.swift
- FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/Unit/SwiftAPI.swift
Swift implementation of #12081 and #12122 and #12148
> [auth-swift] Email enumeration deprecations

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 10.20.0 #no-changelog
> Analytics 10.20.0

- FirebaseAuth/Sources/Swift/SystemService/SecureTokenService.swift
- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Sources/Swift/User/UserMetadata.swift
See the embedded comments for the fixes and the learnings.
I'll do another PR to comprehensively review and apply these learnings across the codebase.
#no-changelog
> Fixes uncovered testing keychain decoding across versions and instances

- .github/workflows/storage.yml
- scripts/build.sh
The storage integration tests continue to flake almost every night. See #12259 
This restructure may mitigate or at least help narrow it down.
> Storage integration tests: restructure to attempt to mitigate flakes

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> Carthage 10.20.0

- FirebaseAuth/Sources/MultiFactor/FIRMultiFactorResolver.m
> Fixed mfa resolver always using default auth instance to finalize

- FirebaseAuth/CHANGELOG.md
> Release Note for multifactor resolver auth instance fix

- FirebaseAuth/Sources/MultiFactor/FIRMultiFactor.m
Follow up to https://github.com/firebase/firebase-ios-sdk/pull/12266#issuecomment-1889515693
> Fixed mfa factor always using default auth instance

- README.md
> Remove versions from README platform docs

- Firestore/core/src/bundle/bundle_serializer.cc
- Firestore/core/test/unit/bundle/bundle_reader_test.cc
[#9407](https://github.com/firebase/firebase-ios-sdk/issues/9407)
#no-changelog
> Support empty map in Firestore bundle

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 10.21.0 #no-changelog
> Analytics 10.21.0

- Package.swift
> [Release] Add Firestore release binary

- .github/workflows/api_diff_report.yml
- .github/workflows/firebase_app_check.yml
- .github/workflows/health-metrics-presubmit.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/spectesting.yml
- .github/workflows/zip.yml
Update update-artifact and download-artifact to v4
Update the `find` command in zip.yml for the slightly different resulting directory structure.
> Update GHA artifact functions

- FirebaseStorage/Sources/AsyncAwait.swift
- FirebaseStorage/Sources/Result.swift
- FirebaseStorage/Sources/Storage.swift
- FirebaseStorage/Sources/StorageDownloadTask.swift
- FirebaseStorage/Sources/StorageListResult.swift
- FirebaseStorage/Sources/StorageMetadata.swift
- FirebaseStorage/Sources/StorageObservableTask.swift
- FirebaseStorage/Sources/StorageReference.swift
- FirebaseStorage/Sources/StorageTask.swift
- FirebaseStorage/Sources/StorageUploadTask.swift
> Storage docs fixes

- Crashlytics/CHANGELOG.md
- Crashlytics/Crashlytics/Components/FIRCLSHost.m
> Remove calls to statfs for supporting Privacy Manifests

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Carthage] Update Carthage artifacts for Firebase 10.21.0

- Gemfile
- Gemfile.lock
> Update to CocoaPods 1.15.2

- Crashlytics/CHANGELOG.md
- FirebaseSessions/Sources/Development/DevEventConsoleLogger.swift
Address comments in #12383
#no-changelog
> Fix release notes

- .github/workflows/zip.yml
> Remove temporary GHA trigger

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 10.22.0 #no-changelog
> Analytics 10.22.0

- Crashlytics/CHANGELOG.md
- FirebaseRemoteConfig/CHANGELOG.md
- ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
Adding release notes and privacy manifest for Rollouts
Release notes copied from android: https://github.com/firebase/firebase-android-sdk/pull/5530
> add release notes and privacy manifest for interop

- FirebaseAnalyticsSwift/Tests/ObjCAPI/ObjCAPITests.m
- FirebaseAnalyticsSwift/Tests/SwiftUnit/AnalyticsAPITests.swift
API tests for Analytics 10.22.0 #no-changelog
> Add API tests for hashed email and phone number

- FirebaseCore/CHANGELOG.md
After merge, will cherry-pick into release branch.
> [Release] Add patch note for 10.22.1

- Crashlytics/UnitTestsSwift/CrashlyticsRemoteConfigManagerTests.swift
> fix unit test

- Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.h
- Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.m
> Fix rollouts tests

- FirebaseRemoteConfig/Sources/RCNConfigDBManager.h
- FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
> reword parameter name

- Crashlytics/CHANGELOG.md
> edit release notes

- Firestore/Source/API/FIRFirestore.mm
- Firestore/Source/API/FIRSnapshotListenOptions.mm
> [Firestore] Add unlinked symbol introduced in #12370

- Package.swift
> [Firestore] Bump dependency ranges for Firestore's binary SPM distro

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 10.23.0
#no-changelog
Note: GoogleAppMeasurementOnDeviceConversion has no source changes
> Analytics 10.23.0

- Firestore/CHANGELOG.md
This release note is a little late but should be part of the M145 release notes.
> [Release] Add release note for signed artifact changes

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> Carthage 10.23.0

- FirebaseVertexAI/Sample/ChatSample/ViewModels/ConversationViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift
- FirebaseVertexAI/Sources/VertexAI.swift
- FirebaseVertexAI/Sources/VertexAIComponent.swift
- FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
> Manage location on VertexAI instead of model

- FirebaseCore/CHANGELOG.md
> [Docs] Update `FirebaseCore/CHANGELOG.md` with correct issue #

- FirebaseVertexAI/Sources/Chat.swift
- FirebaseVertexAI/Sources/FunctionCalling.swift
- FirebaseVertexAI/Sources/GenerateContentRequest.swift
- FirebaseVertexAI/Sources/GenerativeModel.swift
- FirebaseVertexAI/Sources/JSONValue.swift
- FirebaseVertexAI/Sources/ModelContent.swift
- FirebaseVertexAI/Sources/VertexAI.swift
- FirebaseVertexAI/Tests/Unit/ChatTests.swift
- FirebaseVertexAI/Tests/Unit/GenerateContentResponses/unary-success-function-call-empty-arguments.json
- FirebaseVertexAI/Tests/Unit/GenerateContentResponses/unary-success-function-call-no-arguments.json
- FirebaseVertexAI/Tests/Unit/GenerateContentResponses/unary-success-function-call-with-arguments.json
- FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
- FirebaseVertexAI/Tests/Unit/JSONValueTests.swift
- FirebaseVertexAI/Tests/Unit/VertexComponentTests.swift
Added manual function calling support. This is a port of https://github.com/google/generative-ai-swift/pull/116.
#no-changelog
> Add function calling support in Vertex AI

- FirebaseVertexAI/Sample/GenerativeAISample.xcodeproj/project.pbxproj
- Package.swift
- Renamed the `FirebaseVertexAI` library to `FirebaseVertexAI-Preview`
- Updated the samples to reference the renamed library
#no-changelog
> Add `-Preview` suffix to `FirebaseVertexAI` library name

- Package.swift
> [Release] Update Package.swift for 10.23.1 patch

- FirebaseAnalytics.podspec
- FirebaseAnalyticsOnDeviceConversion.podspec
- FirebaseCore/CHANGELOG.md
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 10.23.1 #no-changelog
> Analytics 10.23.1

- Firebase.podspec
- FirebaseAnalytics.podspec
- FirebaseAnalyticsOnDeviceConversion.podspec
- FirebaseCore.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
> 10.23.1 podspec updates

- FirebaseCore/CHANGELOG.md
> Release note for watchOS zip/Carthage

- CoreOnly/Tests/FirebasePodTest/FirebasePodTest/AppDelegate.swift
- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsBundle.swift
- FirebaseCore/Internal/Tests/Unit/HeartbeatStorageTests.swift
- FirebaseCore/Internal/Tests/Unit/HeartbeatTests.swift
- FirebaseRemoteConfigSwift/Sources/FirebaseRemoteConfigSwift.swift
- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/Installations+InstallationsProtocol.swift
- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
- Mintfile
The most notable change is the transformation of `.forEach` to `for ... in ...`
#no-changelog
> Update to SwiftFormat 0.53.5

- FirebaseVertexAI/Sources/GenerativeAISwift.swift
- FirebaseVertexAI/Tests/Unit/GenerateContentResponses/unary-failure-api-key.json
Updated from the staging to prod endpoint in the Vertex AI SDK.
#no-changelog
> Update to prod endpoint in Vertex AI

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
> Analytics 10.24.0

- Package.swift
> [Release] Update Firestore's binary deps in Package.swift

- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift
I'm unsure if this fixes #12409 as I couldn't reproduce it to begin with, but it may help.
#no-changelog
> [FirebaseCoreInternal] Switch to implementation-only import of GULs

- FirebaseVertexAI/Sample/GenerativeAISample.xcodeproj/project.pbxproj
- FirebaseVertexAI/Sample/GenerativeAISample/GenerativeAISampleApp.swift
- FirebaseVertexAI/Sample/GoogleService-Info.plist
- FirebaseVertexAI/Sample/README.md
Cherry-pick #12724 into `vertexai-preview-0.1.0` branch.
#no-changelog
> Add placeholder `GoogleService-Info.plist` to Vertex AI sample (#12724)

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Carthage] Update Carthage artifacts for Firebase 10.24.0

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
> Update Issue and FR templates for VertexAI

- FirebaseVertexAI/Sample/FunctionCallingSample/Screens/FunctionCallingScreen.swift
- FirebaseVertexAI/Sample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAISample.xcodeproj/project.pbxproj
- FirebaseVertexAI/Sample/GenerativeAISample/ContentView.swift
Added a new function calling example in the Vertex AI sample app. This is a port of https://github.com/google/generative-ai-swift/pull/127.
#no-changelog
> Add function calling sample in Vertex AI

- FirebaseVertexAI/Sample/FunctionCallingSample/Screens/FunctionCallingScreen.swift
- FirebaseVertexAI/Sample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAISample.xcodeproj/project.pbxproj
- FirebaseVertexAI/Sample/GenerativeAISample/ContentView.swift
- FirebaseVertexAI/Sample/GenerativeAISample/GenerativeAISampleApp.swift
- FirebaseVertexAI/Sample/GoogleService-Info.plist
- FirebaseVertexAI/Sample/README.md
- FirebaseVertexAI/Sources/CountTokensRequest.swift
- FirebaseVertexAI/Sources/FunctionCalling.swift
- FirebaseVertexAI/Sources/GenerateContentRequest.swift
- FirebaseVertexAI/Sources/GenerativeModel.swift
- FirebaseVertexAI/Sources/VertexAI.swift
- FirebaseVertexAI/Tests/Unit/CountTokenResponses/success-no-billable-characters.json
- FirebaseVertexAI/Tests/Unit/GenerativeModelTests.swift
- FirebaseVertexAI/Tests/Unit/VertexAIAPITests.swift
- Added forced (constrained) function calling and system instruction support in the SDK
- Added a function calling example in the sample app
#no-changelog
> Update `vertex-preview-0.1.0` for pre-release

- FirebaseCore/Internal/Tests/Unit/HeartbeatTests.swift
> [CoreInternal] Make test encoder deterministic to avoid Xcode 15 flakiness

- FirebaseAppCheck.podspec
- FirebaseAppCheck/Sources/Core/FIRAppCheck.m
- FirebaseAppCheck/Sources/Core/FIRAppCheckSettings.h
- FirebaseAppCheck/Sources/Core/FIRAppCheckSettings.m
- FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckSettingsTests.m
- Package.swift
> [AppCheck] Migrate to GoogleUtilities's storage container

- .github/workflows/archiving.yml
- .github/workflows/firestore.yml
- .github/workflows/functions.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
Fix #12779 
Follow up to #12746 to address issues caught in nightlies
#no-changelog
> Todos and workarounds for tests not yet ready for macos-14

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
> Another macos-14 CI workaround

- FirebaseAppCheck.podspec
- Package.swift
> [App Check] Bump dependency on AppCheckCore to 10.19.0+

- Crashlytics/CHANGELOG.md
> [Crashlytics] Make 10.25.0 changelog entry more precise

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 10.25.0 #no-changelog
> Analytics 10.25.0

- .github/workflows/functions.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/storage.yml
> Disable quickstart CI that doesn't work with Xcode 15

- Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.m
> Gracefully fail rollout write

- .github/workflows/zip.yml
opening separately to prevent CI disruption in #12890
#no-changelog
> [Infra] Test dynamic frameworks on all zip.yml jobs

- FirebaseVertexAI/Sources/VertexAI.swift
- Added checks to prevent space, newline or `/` characters in model names, similar to locations.
- Updated supported location links to point to Firebase docs.
#no-changelog
> [Vertex AI] Add basic checks for invalid model names

- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Utility/DataSourceProvider/DataSourceProvider.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AuthViewController.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/SettingsViewController.swift
- FirebaseAuth/Tests/SampleSwift/README.md
Fix some build errors and typos.
Update the README for SPM.
#no-changelog
> [auth-swift] Fix Sample build warnings

- Dangerfile
- FirebaseVertexAI/CHANGELOG.md
- scripts/make_release_notes.py
Let me know if the release note should be more specific or if the version should be something else.
> Add script changes for VertexAI

- FirebaseMessaging/Sources/FIRMessaging.m
- FirebaseMessaging/Sources/FIRMessagingContextManagerService.m
- FirebaseMessaging/Tests/UnitTests/FIRMessagingContextManagerServiceTest.m
- FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m
> [Messaging] Cleanup compilation guards for building on older SDKs

- .github/workflows/firestore.yml
Unblocks #12934
Fix #12769
#no-changelog
> [Infra] Attempt to fix #12769

- .github/workflows/zip.yml
Lines 354 and 355 and indicate that this comment is no longer needed.
#no-changelog
> [NFC] Remove outdated comment

- FirebaseVertexAI/README.md
Add a `README` in the root of the `FirebaseVertexAI` directory with a Preview disclaimer like https://github.com/firebase/firebase-android-sdk/pull/5954.
#no-changelog
> [Vertex AI] Add README.md with Preview disclaimer

- FirebaseVertexAI/CHANGELOG.md
Updated the CHANGELOG entry with latest copy for the Vertex AI for Firebase public preview.
> [Vertex AI] Update CHANGELOG entry with latest copy

- .github/workflows/zip.yml
#12941's testing seems to indicate this is working now. It may be due to how the frameworks are now embedded in the QS.
> [Infra] Re-enable 'zip / quickstart_framework_firestore' job

- scripts/make_release_notes.py
Googlers see cl/633869184 for context.
> use correct variable

- .github/workflows/crashlytics.yml
- .github/workflows/sessions.yml
> Update retry logic for flaky tests

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
> Analytics 10.27.0

- FirebaseVertexAI/CHANGELOG.md
Added a Vertex AI for Firebase changelog entry for the 10.27.0 (Preview) release.
> [Vertex AI] Add CHANGELOG entry for 10.27.0

- Package.swift
Getting this staged.
#no-changelog
> [Release] Update FirestoreInternal binary for 10.27.0 / M148

- FirebaseRemoteConfigSwift/Tests/SwiftAPI/APITestBase.swift
> [Remote Config] Attempt to reduce int. tests flakes

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Release] Carthage versions for M148 / 10.27.0

- Crashlytics/Crashlytics/FIRCrashlytics.m
> Fix deprecated typo

- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Swift/Utilities/AuthWebUtils.swift
- FirebaseAuth/Tests/Unit/OAuthProviderTests.swift
> Fix Auth Domain search code to match comment

- FirebaseStorage/Sources/Storage.swift
- FirebaseVertexAI/Sources/VertexAI.swift
Follow up to review comment in #13047
> [v11] Address component system cleanup PR comments

- scripts/release_testing_setup.sh
> [Infra] Get testing tag from latest tag merged to main

- .github/actions/notices_generation/app.rb
> [Infra] Quick fix for NOTICES generation

- FirebaseMessaging/CHANGELOG.md
- FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.m
- FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m
Fix #12343 
Most of #12343 was addressed in #13064. This does the rest
> [v11] Finish Messaging SecureCoding

- FirebaseMessaging/Sources/FIRMessaging.m
> [v11] Clean up deprecated app delegate methods

- FirebaseVertexAI/CHANGELOG.md
Added a changelog entry for tvOS and visionOS community support in the Vertex AI SDK.
> [Vertex AI] Add CHANGELOG for tvOS/visionOS community support

- Crashlytics/CHANGELOG.md
> [Docs] Update Crashlytics/CHANGELOG.md

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 10.28.0 #no-changelog
Waiting for https://github.com/google/GoogleAppMeasurement/pull/75. Creating this PR earlier than usual since it's Tuesday late night.
> Analytics 10.28.0

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> Carthage 10.28.0

- Crashlytics/CHANGELOG.md
- Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.m
- Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c
- Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c
- Crashlytics/Crashlytics/Handlers/FIRCLSSignal.h
- Firebase.podspec
- FirebaseCore.podspec
- FirebaseCrashlytics.podspec
- Package.swift
Firebase `10.28.1` patch release to revert #12881.
> [Release] Cherrypicks for 10.28.1 patch release

- FirebaseCore/Extension/FIRAppInternal.h
- FirebaseCore/Sources/FIRApp.m
Internal API so no proposal planned. Unused in internal search.
#no-changelog
> [v11] Remove unused string constant

- Crashlytics/CHANGELOG.md
Updated the wording in the changelog entry.
> [Crashlytics] Updated changelog entry for 10.28.1

- FirebaseInAppMessaging/Swift/Tests/Unit/FirebaseInAppMessaging_APIBuildTests.swift
> [NFC] Remove dated TODOs

- .github/workflows/auth.yml
- .github/workflows/remoteconfig.yml
Didn't dig in too deep how to get these test working, but am addressing smaller fixes to get the test further along.
#no-changelog
> [Infra] Update disabled FTL tests

- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift
- FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m
- FirebasePerformance/Sources/FPRNanoPbUtils.m
Crahlytics and Sessions are okay (iOS12+ )
Remove some version check for fireperf (iOS13+)
#no-changelog
> remove os check for major update

- FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
- FirebaseFunctions/Sources/Internal/FunctionsSerializer.swift
- FirebaseInstallations/Source/Tests/Unit/Swift/InstallationsAPITests.swift
- FirebaseVertexAI/Sources/GenerativeAIService.swift
- Firestore/Swift/Tests/Integration/SnapshotListenerSourceTests.swift
- Mintfile
- ReleaseTooling/Sources/ZipBuilder/HashCalculator.swift
> [v11] Update to SwiftFormat 0.54.0

- FirebaseDatabase.podspec
> [Database] Remove previously deleted files from podspec

- FirebaseAppCheck/Apps/FIRAppCheckTestApp/Podfile
- FirebaseDynamicLinks/Tests/Sample/Podfile
- FirebasePerformance/Tests/FIRPerfE2E/Podfile
- FirebasePerformance/Tests/TestApp/Podfile
- FirebaseRemoteConfig/Tests/FeatureRolloutsTestApp/Podfile
- FirebaseSessions/Tests/TestApp/Podfile
Fix some CI including the performance and sessions integration test builds
> Update repo Podfiles to iOS 13 minimum

- FirebaseDatabase.podspec
Partially reverts firebase/firebase-ios-sdk#13249
> Revert "[Database] Remove previously deleted files from podspec"

- Package.swift
> [Infra] Bump lower bound of nanopb in Package.swift

- .github/workflows/sessions-integration-tests.yml
- FirebaseSessions/Tests/TestApp/Podfile
- FirebaseSessions/Tests/TestApp/Shared/MockSubscriberSDK.swift
- scripts/health_metrics/README.md
Should fix https://github.com/firebase/firebase-ios-sdk/actions/runs/9863389797/job/27236063983
#no-changelog
> Update Sessions integration test CI

- FirebaseCombineSwift/Tests/Integration/Storage/StorageIntegration.swift
Fix https://github.com/firebase/firebase-ios-sdk/actions/runs/9852482890/job/27201108497
> Make Storage combine tests more robust

- .github/workflows/zip.yml
- FirebaseCore/CHANGELOG.md
- ReleaseTooling/Sources/ZipBuilder/main.swift
- ReleaseTooling/ZipBuilderV2Plan.md
- scripts/build_zip.sh
- scripts/check_firestore_symbols.sh
> [v11] Release tooling should default to building dynamic frameworks

- FirebaseAnalytics.podspec
- FirebaseStorage/Tests/Unit/StorageAPITests.swift
- FirebaseStorage/Tests/Unit/StorageAuthorizerTests.swift
- FirebaseStorage/Tests/Unit/StorageComponentTests.swift
- FirebaseStorage/Tests/Unit/StorageMetadataTests.swift
- FirebaseStorage/Tests/Unit/StoragePathTests.swift
- FirebaseStorage/Tests/Unit/StorageReferenceTests.swift
- FirebaseStorage/Tests/Unit/StorageTestHelpers.swift
- FirebaseStorage/Tests/Unit/StorageTests.swift
- FirebaseStorage/Tests/Unit/StorageUpdateMetadataTests.swift
- FirebaseStorage/Tests/Unit/StorageUtilsTests.swift
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Placeholder Analytics 11.0.0 #no-changelog
> Placeholder Analytics 11.0.0

- FirebaseMLModelDownloader/Tests/Integration/ModelDownloaderIntegrationTests.swift
- FirebaseMLModelDownloader/Tests/Unit/ModelDownloaderUnitTests.swift
Update deprecated API and disable flaky test
#no-changelog
> [ml-model-downloader] Update unit test deprecated API

- FirebaseFirestoreInternal.podspec
- Firestore/CHANGELOG.md
- Package.swift
The Firestore tests look good. (The spm tests are currently failing on main)
> Update to gRPC 1.65.0

- Package.swift
> [v11] Update Package.swift for GDT 10.0.0

- FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift
- FirebaseAuth/Tests/Unit/SignInWithGameCenterTests.swift
> Remove unnecessary import and fix API in unit test

- Firestore/Source/API/FIRDocumentSnapshot.mm
- Firestore/Source/API/FSTUserDataReader.mm
- Firestore/Source/API/converters.mm
> [Infra] Use <> style imports when importing public Core header

- FirebaseAuth/Sources/Swift/Auth/AuthComponent.swift
> Fix for internal build

- FirebaseAuth/Sources/ObjC/FIRRecaptchaBridge.m
- FirebaseAuth/Tests/Unit/AuthTests.swift
Fix param/definition mismatch, Xcode 16 test flake, and Xcode 16 build warning
> Fix param/definition mismatch and Xcode 16 issues

- .github/workflows/spm.yml
> [Infra] Don't test objc-import-test target, build it

- FirebaseAuth/Sources/Swift/Utilities/AuthRecaptchaVerifier.swift
- FirebaseAuth/Tests/Unit/AuthBackendRPCImplentationTests.swift
> Disable recaptcha integration and heartbeat tests for internal build system

- Package.swift
> [Infra] Bump lower AppCheckCore dep. to 11.0.1+

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 11.0.0 #no-changelog
> Analytics 11.0.0

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 11.0.0 (rc2) #no-changelog
Note: Reusing GoogleAppMeasurementOnDeviceConversion (rc1)
> Analytics 11.0.0 (rc2)

- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatController.swift
- FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsBundle.swift
- FirebaseCore/Internal/Sources/HeartbeatLogging/RingBuffer.swift
- FirebaseCore/Internal/Tests/Unit/HeartbeatControllerTests.swift
- All source codes under the FirebaseCore/Internals directory have been reviewed.
- All corrected typos were found in comments and non-compiling sections of the project.
> Fix typo of the FirebaseCore internals

- CoreOnly/Tests/FirebasePodTest/FirebasePodTest/SceneDelegate.swift
- FirebaseFunctions/Sources/FunctionsError.swift
- FirebaseFunctions/Sources/Internal/FunctionsSerializer.swift
- FirebaseFunctions/Tests/Integration/IntegrationTests.swift
- **All files** under the FirebaseFunctions directory have been reviewed.
- All corrected typos found in comments and non-compiling sections of the project.
> Fix typo of the FirebaseFunctions files

- FirebaseAuth/Sources/Swift/User/User.swift
After finding a logic issue in code review working on #13246, simplify some User.swift token management code.
> [Auth] Token management cleanup

- FirebaseCore/CHANGELOG.md
- FirebaseCore/Tests/SwiftUnit/CoreAPITests.swift
- FirebaseCore/Tests/SwiftUnit/FirebaseAppTests.swift
- FirebaseCore/Tests/Unit/FIRLoggerTest.m
- All files (including source codes, md files, etc) under the FirebaseCore source directory have been reviewed.
Important note:
- The only code change is a fix on a local variable name which seems perfectly safe to change since it is invisible from the outside of its tiny scope.
> Fix typo of the FirebaseCore test files and md files

- .github/workflows/firebasepod.yml
> Update Xcode version for pod installation test

- FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
- FirebaseRemoteConfig/Sources/RCNConfigContent.m
- FirebaseRemoteConfig/Sources/RCNConfigDBManager.h
- FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
- FirebaseRemoteConfig/Sources/RCNConfigRealtime.m
- FirebaseRemoteConfig/Sources/RCNConfigSettings.m
All files have been reviewed. (some of them are in a separate branch.)
Most of the changes are just simple comments, but there is also a single log message that seems acceptable to change.
> Review FirebaseRemoteConfig Sources

- FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m
All files have been reviewed.
Fortunately, the only issue I found was in a single comment.
> Review FirebaseRemoteConfig Tests SampleApp

- FirebaseRemoteConfig/Tests/Unit/FIRRemoteConfigComponentTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
- FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m
All changes are just in the comments.
> Review FirebaseRemoteConfig Tests Unit files

- FirebasePerformance/Tests/Unit/Configurations/FPRRemoteConfigFlagsTest.m
- FirebasePerformance/Tests/Unit/FPRNetworkTraceTest.m
- FirebasePerformance/Tests/Unit/FPRTraceBackgroundActivityTrackerTest.m
- FirebasePerformance/Tests/Unit/Instruments/FPRNSURLSessionInstrumentTest.m
- FirebasePerformance/Tests/Unit/Timer/FIRTraceTest.m
All changes are just in the comments.
All files have been reviewed.
> Fix all typos found under the FirebasePerformance/Tests/Unit directory

- FirebasePerformance/Sources/Configurations/FPRConfigurations.m
- FirebasePerformance/Sources/Gauges/CPU/FPRCPUGaugeCollector.h
- FirebasePerformance/Sources/Gauges/FPRGaugeManager.m
- FirebasePerformance/Sources/Instrumentation/FPRNetworkTrace.h
- FirebasePerformance/Sources/Loggers/FPRGDTLogger.h
All changes are just comments.
All files have been reviewed.
> Review files under the FirebasePerformance/Sources directory

- FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/App/InAppMessaging-Example-iOS/Base.lproj/Main.storyboard
I just wanted to review and make sure this was ok after the merge, then I found out that I missed this typo last time.
Now I'm confident that there are no more typos in the app.
>  Review FirebaseInAppMessaging FunctionalTestApp

- FirebaseStorage/Sources/Internal/StorageInternalTask.swift
- FirebaseStorage/Sources/Storage.swift
Internal b/355173354
Introduced in #13220
> Fix non-main thread callback issue

- FirebaseVertexAI/Sources/Logging.swift
The only change were in a comment
> Review FirebaseVertexAI Sources

- FirebaseStorage/CHANGELOG.md
No impact on the code or functionality at all.
> Review FirebaseStorage non-source files

- FirebaseSessions/ProtoSupport/Protos/sessions.options
- FirebaseSessions/README.md
All changes are non-source files
> Review FirebaseSessions non-source files

- FirebaseSessions/Sources/FirebaseSessions.swift
- FirebaseSessions/Sources/Settings/SessionsSettings.swift
- FirebaseSessions/Sources/Settings/SettingsDownloadClient.swift
> Review FirebaseSessions source files

- FirebaseCore/Sources/FIRApp.m
> [Core] Update log message from deprecated goo.gl link

- Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
- Firestore/Example/Tests/Integration/API/FIRFirestoreSourceTests.mm
- Firestore/Example/Tests/Integration/API/FIRIndexingTests.mm
Most of the typos are just repeated.
All changes seem safe to apply.
> Review Firestore Integration Tests

- Firestore/Protos/README.md
- Firestore/Protos/protos/google/api/http.proto
All proto files and their sibling files have been reviewed.
All changes were in the comments.
> Review Firestore Protos

- Firestore/Swift/Tests/API/BasicCompileTests.swift
- Firestore/Swift/Tests/Integration/IndexingTests.swift
I have reviewed all the files and found a few comment typos. I am ignoring British-English spelling and common typos where the word is correct but not in the standard version.
> Review Firestore Swift Tests

- Firestore/core/test/unit/local/leveldb_index_manager_test.cc
- Firestore/core/test/unit/local/lru_garbage_collector_test.h
- Firestore/core/test/unit/local/mutation_queue_test.cc
Please double-check the `SCOPED_TRACE` changes and let me know the result.
Commits are separated based on the type of change for easier conflict resolution.
Thanks.
>  Review Firestore local unit test files

- Firestore/core/test/unit/util/string_win_test.cc
There was only a single typo in a single comment among all the files.
> Review Firestore util unit test files

- Firestore/core/src/util/executor.h
- Firestore/core/src/util/string_format.cc
All typos were in the comments.
> Review Firestore core source util files

- Firestore/core/test/unit/FSTGoogleTestTests.mm
- Firestore/core/test/unit/credentials/firebase_app_check_credentials_provider_test.mm
- Firestore/core/test/unit/testutil/async_testing.h
All files have been reviewed.
Changes are just comments and logs.
> Review Firestore remaining test files

- Interop/FirebaseComponentSystem.md
There was only a single typo in a comment among all the files I checked.
>  Review Interop files 

- GoogleUtilitiesComponents/Sources/GULCCComponentContainer.m
This is the last one, I think I have covered the entire library and I'm happy to say that the last issue was in a simple comment as usual 🙌🏻
Thanks for your patience and reviewing all the PRs and making this amazing SDK 🙏🏻
> Review GoogleUtilitiesComponents Sources

- ReleaseTooling/Sources/PodspecsTester/InitializeSource.swift
I checked all the PodspecsTester files and this was the only typo I found.
> Review ReleaseTooling PodspecsTester Sources

- ReleaseTooling/Sources/ZipBuilder/ResourcesManager.swift
ZipBuilder files are much more but I found only one issue among all of them and that was a comment as usual :)
> Review ReleaseTooling ZipBuilder Sources

- cmake/sanitizer_options.cmake
I have split the review process of the cmake files into separate comments, codes, and messages reviews. This is the message review PR and there are a few typos that have been fixed. Please take a look and tell me if you found any issues with these fixes.
> Review cmake messages

- cmake/FindASANDylib.cmake
I have split the review process of the cmake files into separate comments, codes, and messages reviews. This is the comment review and there are a few typos that have been fixed.
> Review cmake comments

- scripts/check_copyright.sh
> [Infra] Update check_copyright.sh to ignore root `third_party` directories

- Package.swift
Upload Firestore RC for v11
Fix #13224
#no-changelog
> [v11] Update Package.swift

- scripts/release_testing_setup.sh
> [Infra] Quiet the git fetch

- .github/workflows/prerelease.yml
- scripts/create_spec_repo/RC_firebase_sdk.textproto
- scripts/release_testing_setup.sh
Now that prerelease.yml is working at HEAD, want to send some other fixes and
cleanup. Previously, I made the script checkout the main branch but I actually
think it should be whatever branch is checked out during the workflow.
> [Infra] Cleanup and small fixes for prerelease.yml

- Crashlytics/UnitTests/FIRCLSSettingsTests.m
Fix flake in https://github.com/firebase/firebase-ios-sdk/actions/runs/10190861366/job/28191239943
> [Infra] Extend expectation wait time in FIRCLSSettingsTests.m

- .github/workflows/prerelease.yml
Same fix as in #13438.
Fix #13440
> [Infra] Apply #13438 fix to other job in 'prerelease.yml'

- Package.swift
> [Firestore] Update Firestore SPM binary to fix spm-binary workflow

- Firestore/Source/Public/FirebaseFirestore/FIRVectorValue.h
Addresses https://github.com/firebase/firebase-ios-sdk/pull/13404#discussion_r1713598405
Related to https://github.com/firebase/firebase-ios-sdk/pull/13453
> [Firestore] Add Sendable annotation to VectorValue

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 11.1.0 #no-changelog
> Analytics 11.1.0

- FirebaseAuth/Sources/Swift/ActionCode/ActionCodeSettings.swift
- FirebaseAuth/Sources/Swift/Backend/RPC/GetOOBConfirmationCodeRequest.swift
- FirebaseAuth/Tests/Unit/GetOOBConfirmationCodeTests.swift
- FirebaseAuth/Tests/Unit/RPCBaseTests.swift
API proposal - [go/firebaseauth-fdl-deprecation-api-proposal](http://goto.google.com/firebaseauth-fdl-deprecation-api-proposal)
Sample App, SwiftAPITest will be included in different PRs.
> Adding LinkDomain to ActionCodeSetting

- Package.swift
> Update Firestore SPM for 11.1.0

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> Carthage M152 11.1.0

- FirebaseAuth/Sources/Swift/User/User.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/Models/AuthMenu.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/AccountLinkingViewController.swift
- FirebaseAuth/Tests/SampleSwift/AuthenticationExample/ViewControllers/UserViewController.swift
- Fix delete user action (previously was not deleting the user but signing in with SiwA) 
- Add SiwA token revocation flow
Credit to @peterfriese on the approach to SiwA and the corresponding token revocation flow 🚀 
#no-changelog
> [Auth] Fix delete action in sample app

- Firebase.podspec
> Fix Firebase/Crashlytics min iOS version

- README.md
Correct `AddNewPod` link at README.md.
> Correct AddNewPod link at README.md

- FirebaseSessions/Sources/Development/NanoPB+CustomStringConvertible.swift
Fix: <img width="1406" alt="Screenshot 2024-09-09 at 6 18 05 PM" src="https://github.com/user-attachments/assets/c7283353-78da-4a14-8eb5-485818b65465">
#no-changelog
> [Infra] Silence extensions warnings in Sessions SDK

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
Updated the Carthage artifacts for Firebase M153 / https://github.com/firebase/firebase-ios-sdk/releases/tag/11.2.0.
#no-changelog
> [Release] Carthage updates for M153 / 11.2.0

- CoreOnly/NOTICES
> [Infra] Update NOTICES

- FirebaseSessions/Tests/Unit/Error+EquatableTests.swift
> [Infra] Silence extensions warnings in Sessions SDK tests

- .github/workflows/spm.yml
Appears to fix the issue in the nightlies
#no-changelog
Fix #13670
> [Infra] Limit concurrnet matrix jobs in spm.yml

- FirebaseMessaging/Sources/FIRMessaging.m
- FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessaging.h
- FirebaseMessaging/Sources/Public/FirebaseMessaging/FirebaseMessaging.h
> [Messaging] Prep `FIRMessagingExtensionHelper` usage for refactored 1P target

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 11.3.0 #no-changelog
> Analytics 11.3.0

- SymbolCollisionTest/Podfile
> Ensure test of recent TagManager

- .github/workflows/abtesting.yml
- .github/workflows/appdistribution.yml
- .github/workflows/auth.yml
- .github/workflows/core.yml
- .github/workflows/core_extension.yml
- .github/workflows/core_internal.yml
- .github/workflows/crashlytics.yml
- .github/workflows/database.yml
- .github/workflows/dynamiclinks.yml
- .github/workflows/firebase_app_check.yml
- .github/workflows/firestore.yml
- .github/workflows/functions.yml
- .github/workflows/inappmessaging.yml
- .github/workflows/installations.yml
- .github/workflows/messaging.yml
- .github/workflows/mlmodeldownloader.yml
- .github/workflows/performance.yml
- .github/workflows/remoteconfig.yml
- .github/workflows/sessions.yml
- .github/workflows/shared-swift.yml
- .github/workflows/spm.yml
- .github/workflows/storage.yml
Complete update started in #13697
> CI updates for visionOS and Xcode 16: part 2

- FirebaseMessaging/Sources/FIRMessaging.m
- FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessaging.h
- FirebaseMessaging/Sources/Public/FirebaseMessaging/FirebaseMessaging.h
…ctored 1P target (#13691)"
This reverts commit 846a41f9e5591679ad2a9c885d6376b38878cb41.
> Revert "[Messaging] Prep #13691

- Package.swift
> Firestore SPM binary for 11.3.0

- .github/workflows/zip.yml
Investigate #13727 
#no-changelog
> Run zip testing with Xcode 16

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> Carthage 11.3.0

- FirebaseAuth/README.md
Update link in README.md for `FirebaseAuth-SampleSwift`.
> [docs] Update link in README.md for FirebaseAuth SampleSwift.

- FirebaseAuth/Tests/Unit/AuthBackendRPCImplementationTests.swift
The file name has a typo and I fixed it. Also it contained a simple typo in commit message, so I fixed it as well.
> Enhance FirebaseAuth file structure

- scripts/release_testing_setup.sh
> [Infra] Release testing should grab latest tag on any branch

- FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.m
All changes are comments and safe to merge.
> Docs: enhance FirebaseMessaging token sources comments

- FirebaseInstallations/Source/Tests/Unit/FIRInstallationsStoreTests.m
Local method, not referenced outside
> Enhance FirebaseInstallation unit test methods

- FirebaseInAppMessaging/Sources/Flows/FIRIAMFetchFlow.m
I just found a single local reference to this method and fix that as well. Please check if there are more.
Thanks
> Fix a method name in FirebaseInAppMessaging

- FirebaseStorage/Sources/AsyncAwait.swift
> [storage] Docs build fixes

- FirebaseCore/Sources/FIRConfiguration.m
- FirebaseCore/Sources/FIRLogger.m
- FirebaseCore/Sources/Public/FirebaseCore/FIRConfiguration.h
- FirebaseCore/Tests/Unit/FIRConfigurationTest.m
cc: @cherylEnkidu @aashishpatil-g
> [Core] Add logging level getter to FIRConfiguration

- FirebasePerformance/Tests/TestApp/PerfTestRigApp.xcodeproj/project.pbxproj
- FirebasePerformance/Tests/TestApp/Tests/PerfControllerTests.m
A class name and its corresponding file name had a repeated typo. I've renamed and changed all the references to the file and class. Please double check and see if something is missing. 
Thanks
> Enhance FirebasePerformance TestApp files structure

- FirebaseMessaging/Sources/FIRMessagingRemoteNotificationsProxy.m
All references to the changes have been updated and are ready for merging.
> Improve FirebaseMessaging remote notification proxy source code

- FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfig+FIRAppTest.m
No outside references to this renamed test method
> Test: improve FirebaseRemoveConfig unit tests

- FirebaseStorage/Tests/ObjCIntegration/ObjCAPITests.m
- FirebaseStorage/Tests/ObjCIntegration/ObjCPPAPITests.mm
No outside reference to this function name
> Fix: a repeated typo in multiple test files of the FirebaseStorage

- FirebaseSessions/ProtoSupport/Protos/sessions.proto
A simple typo in the comments. Fully backward compatible.
> Docs: enhance FirebaseSessions's proto documentations

- FirebaseSessions/Tests/Unit/SessionStartEventTests.swift
No external references to this method name
> Test: a function name in FirebaseSessions' unit tests

- FirebaseSessions/Sources/Installations+InstallationsProtocol.swift
Not referenced from the outside of the file.
> Fix: a variable name in FirebaseSessions' source code

- scripts/api_diff_report/pr_commenter.py
Corrected a single variable name
> Build: enhance api diff report scripts

- scripts/cpplint.py
- scripts/style.sh
All changes are in comments and backward compatible
> Docs: enhance scripts comments

- cmake/external/leveldb_patch_test.py
Please double-check to ensure everything is correct. Thanks
> Fix: a repeated typo in python file

- FirebaseAuth/CHANGELOG.md
- FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Enroll/FinalizeMFAEnrollmentRequest.swift
- FirebaseAuth/Tests/Unit/FinalizeMFAEnrollmentRequestTests.swift
> [Auth] Restore MFA request setup to Firebase 10 behavior

- FirebaseFunctions/Sources/Callable+Codable.swift
> Correct documentation for Callable default timeout

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 11.4.0 #no-changelog
> Analytics 11.4.0

- Crashlytics/CHANGELOG.md
- FirebaseAuth/CHANGELOG.md
- FirebasePerformance/CHANGELOG.md
- Firestore/CHANGELOG.md
> [Release] Update changelogs for 11.4.0

- Package.swift
> [Release] Update Firestore SPM binary for M155

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
> [Release] Carthage artifacts for 11.4.0

- Firestore/core/test/unit/bundle/bundle_reader_test.cc
I haven't found any references to this, but please double-check if possible. Thanks!
> Firestore: review bundle reader tests

- FirebaseStorage/Tests/Unit/StoragePathTests.swift
Not referenced anywhere, safe to merge. Thanks.
> FirebaseStorage: review storage path tests

- Firestore/core/test/unit/core/event_manager_test.cc
I haven't found any references to this, but please double-check if possible. Thanks!
> test: review firestore event manager tests

- Firestore/core/test/unit/remote/serializer_test.cc
It's not a major issue, but at least Xcode's spell check will be satisfied! :)
> Firestore: review serializer tests

- ReleaseTooling/Sources/FirebaseManifest/FirebaseManifest.swift
> [Infra] Update `FirebaseVertexAI` row in FirebaseManifest.swift

- FirebaseAuth/Tests/SampleSwift/SwiftApiTests/PhoneAuthTests.swift
Implement integration test for verifying phone number sign-in with Firebase.
> Adding Integration Test for Phone Number Authentication in Firebase

- FirebaseCombineSwift/Sources/Auth/GameCenterAuthProvider+Combine.swift
> Fix Auth Combine build for watchOS

- FirebaseSharedSwift/Sources/third_party/FirebaseDataEncoder/FirebaseDataEncoder.swift
> [Docs] Fix DocC warnings in FirebaseSharedSwift

- Crashlytics/CHANGELOG.md
> add changelog

- .github/actions/notices_generation/action.yml
> [Infra] Migrate notices GHA to use upload-artifact@v4

- Package.swift
Updated the Firestore binary URL in SPM for the M156 / 11.5.0 release.
#no-changelog
> [Release] Update Firestore SPM binary for M156

- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
> Add Data Connect to Feature Request template

- FirebaseAuth/CHANGELOG.md
Added a changelog entry for #14067 since it will go in the 11.5 CocoaPods / SPM releases.
> [Auth] Add CHANGELOG entry for #14067

- FirebasePerformance/CHANGELOG.md
Added a changelog entry for #14048 since it will be included in 11.5.0 (M156) for CocoaPods and SPM.
> [Performance] Add changelog entry for #14048

- .github/workflows/sessions-integration-tests.yml
Test case looks to have passed.
Fixes #12771
#no-changelog
> [Infra] Migrate away from macos-12 in sessions-integration-tests.yml

- FirebaseAuth/Sources/Swift/Utilities/AuthRecaptchaVerifier.swift
I previously marked this unchecked Sendable. The class is not Sendable.
#no-changelog
> [Auth] Undo unchecked Sendable addition

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
- ReleaseTooling/CarthageJSON/FirebaseVertexAIBinary.json
> Carthage 11.6.0

- .github/workflows/crashlytics.yml
Only run unit tests on macos-15
> Minimize Crashlytics flakes

- FirebaseRemoteConfigInterop.podspec
Fix typo: `Remoet` → `Remote`
#no-changelog
> [NFC] Update FirebaseRemoteConfigInterop.podspec

- FirebaseAuth/Sources/Swift/User/User.swift
Another simple typo in a comment.
> [FirebaseAuth] docs: enhance code documentations

- FirebaseRemoteConfig/SwiftNew/ConfigRealtime.swift
> [Config] Follow-up to 'RCNRealtime' port

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 11.7.0 #no-changelog
> Analytics 11.7.0

- .github/workflows/firestore.yml
- Package.swift
> [Release] Update Firestore binary for 11.7.0

- docs/firebase-api-guidelines.md
> [Docs] Create firebase-api-guidelines.md

- FirebaseRemoteConfig/Tests/SwiftUnit/UserDefaultsManagerOrigTests.swift
Generated tests are taking more time to refine
#no-changelog
> [Config] Port UserDefaultsManagerTests.swift

- FirebaseRemoteConfig/Tests/SwiftUnit/ConfigValueOrigTests.swift
- FirebaseRemoteConfig/Tests/SwiftUnit/ConfigValueTests.swift
> [Config] Port ConfigValueOrigTests.swift and generate new tests

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
- ReleaseTooling/CarthageJSON/FirebaseVertexAIBinary.json
> [Release] Carthage for M158 / 11.7.0

- FirebaseRemoteConfig/Tests/SwiftUnit/RemoteConfigComponentOrigTest.swift
- FirebaseRemoteConfig/Tests/SwiftUnit/TestUtilities.swift
- FirebaseRemoteConfig/Tests/Unit/FIRRemoteConfigComponentTest.m
> [Config] Port Component tests

- FirebaseFunctions/Backend/index.js
🤦🏼  I made a simple coding mistake.
> Fix bug in genStream function impl.

- FirebaseRemoteConfig/SwiftNew/RemoteConfig.swift
> [Config] Port over Sendability changes from #14375

- FirebaseVertexAI/Tests/Unit/Snippets/CloudStorageSnippets.swift
- Package.swift
Added "tests" to verify that the Vertex AI Google Cloud Storage [code snippets](https://firebase.google.com/docs/vertex-ai/solutions/cloud-storage?platform=ios) compile. See internal cl/699201476 for fixes.
#no-changelog
> [Vertex AI] Add compilation tests for GCS snippets

- FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenGCSImage.swift
- FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenGenerationConfig.swift
- FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenInlineImage.swift
- FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenModel.swift
- FirebaseVertexAI/Sources/VertexAI.swift
- FirebaseVertexAI/Tests/TestApp/Tests/Integration/IntegrationTests.swift
- FirebaseVertexAI/Tests/Unit/Types/Imagen/ImageGenerationParametersTests.swift
- FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenGCSImageTests.swift
- FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenGenerationRequestTests.swift
- FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenGenerationResponseTests.swift
- FirebaseVertexAI/Tests/Unit/Types/Imagen/ImagenInlineImageTests.swift
Updated the public API surfaces of Imagen-related files to match the reviewed API proposal.
#14221
#no-changelog
> [Vertex AI] Update Imagen public APIs to match API proposal

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
> Set FIREBASE_CI for release and prerelease CI

- Package.swift
> Firestore 11.8.0 SPM binary update

- Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
All changes are backward compatible
> [Crashlytics] enhance inline documentations

- FirebaseAuth/Tests/SampleSwift/Podfile
> [Infra] Bump Auth sample app's dep. on RecaptchaEnterprise

- .github/workflows/abtesting.yml
- .github/workflows/appdistribution.yml
- .github/workflows/auth.yml
- .github/workflows/core.yml
- .github/workflows/core_extension.yml
- .github/workflows/core_internal.yml
- .github/workflows/crashlytics.yml
- .github/workflows/database.yml
- .github/workflows/dynamiclinks.yml
- .github/workflows/firebase_app_check.yml
- .github/workflows/firestore.yml
- .github/workflows/functions.yml
- .github/workflows/inappmessaging.yml
- .github/workflows/installations.yml
- .github/workflows/messaging.yml
- .github/workflows/mlmodeldownloader.yml
- .github/workflows/performance.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/remoteconfig.yml
- .github/workflows/sessions.yml
- .github/workflows/shared-swift.yml
- .github/workflows/spm.yml
- .github/workflows/storage.yml
- .github/workflows/vertexai.yml
- .github/workflows/zip.yml
> Run CI with Xcode 16.2

- .github/workflows/symbolcollision.yml
Addresses build failure in nightlies after update to AdMob 12.0.0
#no-changelog
> Update Symbol Collision test Xcode

- FirebaseVertexAI/Sample/ChatSample/ViewModels/ConversationViewModel.swift
- FirebaseVertexAI/Sample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift
- FirebaseVertexAI/Sample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift
> update vertex ai sample to use gemini 2.0 flash

- FirebaseRemoteConfig/CHANGELOG.md
- FirebaseRemoteConfig/Sources/Private/RCNConfigFetch.h
> [RC] Fix a concurrency crash

- Crashlytics/CHANGELOG.md
- FirebaseAuth/CHANGELOG.md
- FirebaseDatabase/CHANGELOG.md
- FirebaseMessaging/CHANGELOG.md
- FirebaseRemoteConfig/CHANGELOG.md
- FirebaseVertexAI/CHANGELOG.md
- Firestore/CHANGELOG.md
Updated `Unreleased` CHANGELOG entries to `11.9.0`.
> [Release] Update unreleased CHANGELOG entries for 11.9.0

- FirebaseFunctions/CHANGELOG.md
Thanks for coming up with the entry, Andrew!
#no-changelog
> [Functions] Update CHANGELOG.md for App Check fix

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 11.9.0 #no-changelog
> Analytics 11.9.0

- FirebaseAuth/Sources/Swift/Utilities/AuthRecaptchaVerifier.swift
Exclude the `recaptchaToken(siteKey:actionString:fakeToken:)` method from internal builds, where reCAPTCHA isn't available.
#no-changelog
> [Auth] Compile-out `recaptchaToken(...)` for 1P

- Package.swift
Updated the Firestore binary URL in SPM for the M160 / 11.9.0 release.
#no-changelog
> [Release] Update Firestore SPM binary for M160

- FirebaseVertexAI/Sources/Protocols/Internal/CodableProtoEnum.swift
- FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenAspectRatio.swift
- FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenPersonFilterLevel.swift
- FirebaseVertexAI/Sources/Types/Public/Imagen/ImagenSafetyFilterLevel.swift
- FirebaseVertexAI/Sources/Types/Public/Schema.swift
- FirebaseVertexAI/Sources/VertexAI.swift
Address low hanging Swift 6 build issues. The following issue remains in the Chat implementation:
> Swift 6 build fixes for Vertex AI

- FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessaging.h
> [Messaging] Update `FIRMessaging` header doc

- .github/workflows/vertexai.yml
- FirebaseVertexAI/Sources/Chat.swift
- FirebaseVertexAI/Sources/FirebaseInfo.swift
- FirebaseVertexAI/Sources/FunctionCalling.swift
- FirebaseVertexAI/Sources/GenerateContentRequest.swift
- FirebaseVertexAI/Sources/GenerationConfig.swift
- FirebaseVertexAI/Sources/GenerativeAIRequest.swift
- FirebaseVertexAI/Sources/GenerativeAIService.swift
- FirebaseVertexAI/Sources/GenerativeModel.swift
- FirebaseVertexAI/Sources/Safety.swift
- FirebaseVertexAI/Sources/Types/Internal/Imagen/ImagenGenerationRequest.swift
- FirebaseVertexAI/Sources/Types/Public/Schema.swift
VertexAI successfully builds with this PR, but Chat history is broken.
Next step is to add CI and then a changelog, but that can wait for the next PR.
#no-changelog
> [VertexAI] More Swift 6

- CONTRIBUTING.md
- scripts/setup_check.sh
- scripts/style.sh
> [Infra] Update to clang-format@20 and apply updated styling.

- README.md
> Update README.md for clang-format 20

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 11.10.0 #no-changelog
> Analytics 11.10.0

- FirebaseRemoteConfig/CHANGELOG.md
- FirebaseRemoteConfig/Swift/Codable.swift
- FirebaseRemoteConfig/Tests/Swift/SwiftAPI/Codable.swift
> [Config] Revert adding encoder/decoder params to Codable APIs

- .github/actions/testing_report_generation/app.rb
- .github/workflows/generate_issues.yml
https://github.com/firebase/firebase-ios-sdk/actions/runs/13834108157/job/38712477533
Fix #14566
> [Infra] Debug broken issues generation workflow

- .github/actions/testing_report_generation/app.rb
This should hopefully get us on the right debugging track earlier.
#no-changelog
> [Infra] Add comment to testing report generation app

- .github/workflows/storage.yml
> [Infra] Install visionOS sim in `storage x spm` workflow

- Package.swift
> [Release] Firestore binary for 11.10

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
- ReleaseTooling/CarthageJSON/FirebaseVertexAIBinary.json
> [Release] Carthage for M161

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 11.11.0 #no-changelog
> Analytics 11.11.0

- Package.swift
> [11.11.0] Firestore binary update

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
- ReleaseTooling/CarthageJSON/FirebaseVertexAIBinary.json
> [Release] Add carthage artifacts for M162 / 11.11.0 release

- .github/workflows/abtesting.yml
Trying based on https://github.com/actions/runner-images/issues/11916#issuecomment-2778821609
> Start Xcode 16.3 in CI

- FirebaseAuth/Tests/Unit/ActionCodeURLTests.swift
Follow up to #14666 and #14668
#no-changelog
> Add unit tests for ActionCodeURL

- .github/workflows/spm.yml
> [Infra] Move 'spm' workflow to Xcode 16

- .github/workflows/crashlytics.yml
> [Infra] Move 'crashlytics' workflow to Xcode 16

- .github/workflows/firebasepod.yml
> [Infra] Move 'firebasepod' workflow to Xcode 16

- .github/workflows/performance-integration-tests.yml
- .github/workflows/sessions-integration-tests.yml
#no-changelog
Fix https://github.com/firebase/firebase-ios-sdk/actions/runs/14369592550 etc
> Update timed integration tests to run on macos-15

- FirebaseVertexAI/Tests/TestApp/Tests/Integration/GenerateContentIntegrationTests.swift
- FirebaseVertexAI/Tests/TestApp/Tests/Utilities/InstanceConfig.swift
> [VertexAI] Add schema minItems/maxItems test

- .github/workflows/abtesting.yml
- .github/workflows/database.yml
- .github/workflows/dynamiclinks.yml
- .github/workflows/firebase_app_check.yml
- .github/workflows/inappmessaging.yml
- .github/workflows/installations.yml
- .github/workflows/messaging.yml
- .github/workflows/remoteconfig.yml
- .github/workflows/shared-swift.yml
- scripts/build.sh
> [Infra] Migrate more workflows to Xcode 16

- .github/workflows/prerelease.yml
> [Infra] Update prerelease.yml to macos-15

- scripts/check_imports.swift
> [infra] Remove last usage of @_implementationOnly in the repo

- .github/workflows/firestore.yml
> [Infra] Update firestore.yml

- .github/workflows/dynamiclinks.yml
> [Infra] Go build only for FDL tests

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 11.12.0 #no-changelog
> Analytics 11.12.0

- FirebaseAuth/CHANGELOG.md
- FirebaseCore/CHANGELOG.md
- FirebaseFunctions/CHANGELOG.md
- FirebaseVertexAI/CHANGELOG.md
- Firestore/CHANGELOG.md
Updated `Unreleased` changelog entries to version `11.12.0` for the M163 release.
> [Release] Update unreleased changelog entries to `11.12.0`

- scripts/build.sh
Fix nightly failure.
#no-changelog
> [Infra] Temp. fix for RC's iOS integration tests

- .github/workflows/notice_generation.yml
> Fix permissions in notice_generation.yml

- FirebaseFunctions/Tests/CombineUnit/HTTPSCallableTests.swift
> [Infra] Fix Combine unit test

- Crashlytics/Crashlytics/Helpers/FIRCLSInternalLogging.c
#no-changelog
related issue: #14770
> Fix %lx, %lu, %ld, %llx, %llu, %lld

- FirebaseAI/Sources/Types/Internal/APIConfig.swift
> [Firebase AI] Vertex AI Gemini API

- FirebaseAI/Tests/TestApp/Tests/Integration/SchemaTests.swift
- FirebaseAuth/Tests/SampleSwift/SwiftApiTests/GoogleTests.swift
- FirebaseStorage/Sources/StorageTask.swift
- Mintfile
> [CI] Update to swiftformat 0.55.5

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 11.13.0 #no-changelog
> Analytics 11.13.0

- Package.swift
> [Release] Update Package.swift for M164 release

- ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAIBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAdMobBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAnalyticsOnDeviceConversionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppCheckBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAppDistributionBinary.json
- ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json
- ReleaseTooling/CarthageJSON/FirebaseCrashlyticsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json
- ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFirestoreBinary.json
- ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json
- ReleaseTooling/CarthageJSON/FirebaseGoogleSignInBinary.json
- ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMLModelDownloaderBinary.json
- ReleaseTooling/CarthageJSON/FirebaseMessagingBinary.json
- ReleaseTooling/CarthageJSON/FirebasePerformanceBinary.json
- ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json
- ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json
- ReleaseTooling/CarthageJSON/FirebaseVertexAIBinary.json
> [Release] Carthage for 11.13.0

- ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift
Address https://github.com/firebase/firebase-ios-sdk/pull/14875#issuecomment-2895964307
#no-changelog
> [Infra] Do not float dependency on FirebaseAI

- .github/workflows/combine.yml
- FirebaseTestingSupport/Auth/Sources/PhoneAuthProviderFake.swift
Fixes one of the nightly failures 
#no-changelog
> [Auth] Fix 'PhoneAuthProviderFake.swift' following Swift 6 changes

- .github/workflows/auth.yml
> [Infra] Remove dupe job in .github/workflows/auth.yml

- .github/workflows/core.yml
> [Infra] Remove dupe job in .github/workflows/core.yml

- .github/workflows/storage.yml
> [Infra] Move Storage over to common linting job

- .github/workflows/abtesting.yml
- .github/workflows/appdistribution.yml
- .github/workflows/auth.yml
- .github/workflows/core.yml
- .github/workflows/core_internal.yml
- .github/workflows/crashlytics.yml
- .github/workflows/database.yml
- .github/workflows/firebase_app_check.yml
- .github/workflows/installations.yml
- .github/workflows/messaging.yml
- .github/workflows/mlmodeldownloader.yml
- .github/workflows/performance.yml
- .github/workflows/remoteconfig.yml
- .github/workflows/sessions.yml
- .github/workflows/storage.yml
Changed workflow files use `.github/workflows/common_catalyst.yml`
#no-changelog
> [Infra] Trigger dependent workflows when .github/workflows/common_catalyst.yml changes

- FirebaseSessions/Sources/Installations+InstallationsProtocol.swift
> [Sessions] Fix Sendability warnings

- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
> [Infra] Update FEATURE_REQUEST.yml

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/zip.yml
> [Infra] Remove FDL qs from [pre]release.yml

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- GoogleAppMeasurementOnDeviceConversion.podspec
- Package.swift
Analytics 11.15.0 #no-changelog
> Analytics 11.15.0

- FirebaseCore/CHANGELOG.md
> [Infra] Update CHANGELOG.md for `Options.deepLinkURLScheme` deprecation

- Package.swift
SPM successor to #15015
Fixes #14732 
#no-changelog
> [Infra] For SPM, defer to Xcode for supported platform versions

- Firestore/Protos/protos/google/api/http.proto
> docs: fix `bidirectional`

- FirebaseTestingSupport/Firestore/Sources/FIRQueryFake.mm
> [Infra] Suppress designated initializer warning in `FIRQueryFake`

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 12.1.0 #no-changelog
> Analytics 12.1.0

- Crashlytics/UnitTests/Mocks/FIRCLSMockFileManager.m
> [Infra] Attempt to reduce Crashlytics testing flake

- ReleaseTooling/Sources/ZipBuilder/main.swift
> [Infra] Update release tooling minimum versions

- scripts/build.sh
> [Infra] Remove 18.3.1 sim workaround

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 12.2.0 #no-changelog
> Analytics 12.2.0

- FirebaseAuth/CHANGELOG.md
Updated `Unreleased` changelog entries (Auth only).
> [Auth] Update changelog entry for 12.2.0

- .github/workflows/performance-integration-tests.yml
> fix(ci): Perf. int. tests need Xcode 16.4 and should run daily

- .github/workflows/abtesting.yml
- .github/workflows/auth.yml
- .github/workflows/crashlytics.yml
- .github/workflows/database.yml
- .github/workflows/firestore.yml
- .github/workflows/functions.yml
- .github/workflows/inappmessaging.yml
- .github/workflows/messaging.yml
- .github/workflows/performance.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/remoteconfig.yml
- .github/workflows/storage.yml
- .github/workflows/zip.yml
This secret appears to be unused:
- firebase-ios-sdk: https://github.com/search?q=repo%3Afirebase%2Ffirebase-ios-sdk%20signin_secret&type=code
- only yaml hits where it is defined
- quickstarts-ios: https://github.com/search?q=repo%3Afirebase%2Fquickstart-ios%20signin_secret&type=code
- no hits
#no-changelog
> chore(ci): Remove unused secret

- .github/workflows/auth.yml
> fix(ci): Remove duplicate `runs-on` use in auth.yml

- .github/workflows/remoteconfig.yml
> fix(ci): Fix syntax errors in remoteconfig.yml

- .github/workflows/prerelease.yml
manual testing: 
[![prerelease](https://github.com/firebase/firebase-ios-sdk/actions/workflows/prerelease.yml/badge.svg?branch=nc%2Fpre-1&event=workflow_dispatch)](https://github.com/firebase/firebase-ios-sdk/actions/workflows/prerelease.yml)
#no-changelog
> fix(ci): Fix prerelease.yml by removing unneeded lowercasing

- .github/workflows/zip.yml
Commented out to test something in #15274
#no-changelog
> fix(ci): Revert unintended change in zip.yml

- .github/workflows/auth.yml
> fix(ci): Update indentation in auth.yml

- .github/workflows/abtesting.yml
- .github/workflows/auth.yml
- .github/workflows/common_quickstart.yml
- .github/workflows/crashlytics.yml
- .github/workflows/database.yml
- .github/workflows/firestore.yml
- .github/workflows/inappmessaging.yml
- .github/workflows/installations.yml
- .github/workflows/messaging.yml
- .github/workflows/performance.yml
- .github/workflows/remoteconfig.yml
- .github/workflows/storage.yml
- scripts/setup_quickstart_spm.sh
- scripts/test_quickstart.sh
> feat(ci): Test SPM quickstarts

- FirebaseAnalytics.podspec
- GoogleAppMeasurement.podspec
- Package.swift
Analytics 12.4.0 #no-changelog
> Analytics 12.4.0

- Crashlytics/CHANGELOG.md
- FirebaseAI/CHANGELOG.md
> chore(m171): Version changelogs

- .github/workflows/common_cocoapods.yml
> feat(ci): Add verbose option to reusable lint workflow
